### ISSUE TITLE
RX 460/550 Not supported !

### ISSUE THREAD

**Issue by AbdelXY** [Lolliedieb/lolMiner-releases#1]
Hi,
I was setting up to mining some equihash coins like equi 144_5 (works great) but unfortunately It does not work for **equishash 192_7 algo** as I get an error saying:
**"RX 460 and RX 550 are not supported for the current algo"**

I was trying to find a solution but nothing.
Please may you look at it and try to fix it.
I enjoy your work and thank you

**Comment by AbdelXY** [comment]
hello any help please

**Comment by Lolliedieb** [comment]
Should be fixed since long ago, when enough memory is avail (192_7 needs 4G variant of cards)
