### ISSUE TITLE
Can't add 1.43 as custom miner in HiveOS.

### ISSUE THREAD

**Issue by HorusRus** [Lolliedieb/lolMiner-releases#1000]
Can't add 1.43 as custom miner in HiveOS.
Unable to install miner from https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/lolMiner_v1.43_Lin64.tar.gz

**Comment by viper1986** [comment]
Update HiveOS. 0.6-213@220204

**Comment by RedBoardDev** [comment]
![image](https://user-images.githubusercontent.com/66514178/152527021-9b540e87-99a0-48d3-8125-a94fb0ea35b4.png)
No 0.6-213@220204 is not good :(

**Comment by viper1986** [comment]
Try from the shell:
wget http://download2.hiveos.farm/repo/binary/hive-miners-lolminer-1.43_0.6-01_amd64.deb
dpkg -i hive-miners-lolminer-1.43_0.6-01_amd64.deb

or wait till they fix it.

**Comment by RedBoardDev** [comment]
Yes, I made the direct order afterwards :) But thank you
It might help someone else

**Comment by HorusRus** [comment]
At the moment everything is fine. At the beginning, there was an error during manual installation via the link and through wget. Then the official update of HiveOS was with an error too.

**Comment by hgurkann** [comment]
im looking for same solution.
I want to install lolminer on hiveos as "custom" miner
so if can manage it to install as a custom miner. I can you 2 lolminer at the same time 
one for ETH+TON
other one for ETC+TON
