### ISSUE TITLE
Eth+Ton doens't work on laptop

### ISSUE THREAD

**Issue by RandomStuffx** [Lolliedieb/lolMiner-releases#1002]
Dual mode doesn't work on 3060 laptop. 
Eth mining is working fine but ton is only 22mh while it should be at least 500-700

**Comment by jgonzis** [comment]
> Dual mode doesn't work on 3060 laptop. Eth mining is working fine but ton is only 22mh while it should be at least 500-700

Change PL... or play with --maxdualimpact 10

Eth will go down and TON will increase. It cannot be 100% ETH and 100% TON...
