### ISSUE TITLE
10% Rejected(seed) on Ton Whales pool @ 1.43

### ISSUE THREAD

**Issue by puiconnie** [Lolliedieb/lolMiner-releases#1004]
I got around 10% Rejected(seed) on Ton Whales pool
someone said that updated to 1.41b will fix the problems,
but i already tried 1.42,1.43 , problems are still here

**Comment by jgonzis** [comment]
> I got around 10% Rejected(seed) on Ton Whales pool someone said that updated to 1.41b will fix the problems, but i already tried 1.42,1.43 , problems are still here

That is tonwhales servers. It is well know that problems.. try other of the 3 servers or change to other pool that doesn't have that problems like toncoinpool.io or ton-pool
