### ISSUE TITLE
3090 results ETH + TON dual mining 1.43 lolminer

### ISSUE THREAD

**Issue by ahai1990** [Lolliedieb/lolMiner-releases#1005]
Good job lolminer
![IMG_20220204_152650__01](https://user-images.githubusercontent.com/9350254/152546530-2ff8d425-09e0-4c1e-9a36-22485f9aeeb5.jpg)

**Comment by adriatiksejdiu** [comment]
Can you send me config file how to config for dual ETH+TON

**Comment by linoxoidunix** [comment]
Can you send me config file how to config for dual ETH+TON

**Comment by jgonzis** [comment]
> Can you send me config file how to config for dual ETH+TON

It is in the bat file....

**Comment by Xefier** [comment]
How did you get it to work? These are my results 
https://github.com/Lolliedieb/lolMiner-releases/issues/1022

**Comment by jgonzis** [comment]
> How did you get it to work? These are my results #1022 (TON at 0 Mh/s on Windows) #1023 (Not working at all on Hive OS)

HiveOS your configuration  is not right. I write you there.

Windows the 0 could be is a Pascal for example without anymore information is not possible more help. The HiveOS check the videos selecting also only 1 pool for ton
