### ISSUE TITLE
Miningrigrentals and lolminer 1.43

### ISSUE THREAD

**Issue by GADZ12** [Lolliedieb/lolMiner-releases#1006]
Hi, just testing new lolminer. But getting error from MRR server: Worker not authorized: GADZ12.212515

`No working connection for 300 seconds (Authorization or Work missing). Reconnecting. Lost connection to stratum server us-central01.miningrigrentals.com:3344 or server not reachable. Trying to connect in 1 second(s) DNS over HTTPS resolve failed - switching to standard resolve Connected to us-central01.miningrigrentals.com(45.76.227.84):3344 (TLS disabled) Set Ethash stratum mode: EthereumStratum/1.0.0 Subscribed to stratum server Pool responded in ETHPROXY format to EthereumStratum/1.0.0 login request. Changing to stratum mode ETHPROXY. Set Ethash stratum mode: Ethereum Proxy Error: Worker not authorized: GADZ12.212515 Test to connect to failover pool Authorized worker: GADZ12.212515 The pool requested a reconnect. Doing so! false Too many attempts. Switching to failover pool us-west01.miningrigrentals.com:3344 DNS over HTTPS resolve failed - switching to standard resolve Connected to us-west01.miningrigrentals.com(138.197.204.233):3344 (TLS disabled) Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.`

The workername is correct and works with other miners.
Any ideas or solution?

**Comment by jgonzis** [comment]
> Hi, just testing new lolminer. But getting error from MRR server: Worker not authorized: GADZ12.212515
> 
> `No working connection for 300 seconds (Authorization or Work missing). Reconnecting. Lost connection to stratum server us-central01.miningrigrentals.com:3344 or server not reachable. Trying to connect in 1 second(s) DNS over HTTPS resolve failed - switching to standard resolve Connected to us-central01.miningrigrentals.com(45.76.227.84):3344 (TLS disabled) Set Ethash stratum mode: EthereumStratum/1.0.0 Subscribed to stratum server Pool responded in ETHPROXY format to EthereumStratum/1.0.0 login request. Changing to stratum mode ETHPROXY. Set Ethash stratum mode: Ethereum Proxy Error: Worker not authorized: GADZ12.212515 Test to connect to failover pool Authorized worker: GADZ12.212515 The pool requested a reconnect. Doing so! false Too many attempts. Switching to failover pool us-west01.miningrigrentals.com:3344 DNS over HTTPS resolve failed - switching to standard resolve Connected to us-west01.miningrigrentals.com(138.197.204.233):3344 (TLS disabled) Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.`
> 
> The workername is correct and works with other miners. Any ideas or solution?

That seems that wallet is not correct...

Ethereum Proxy Error: Worker not authorized: GADZ12.212515

Check your flightsheet connection
