### ISSUE TITLE
mine ETH+TON but two 3060 ti does not mine TON

### ISSUE THREAD

**Issue by Kawasick** [Lolliedieb/lolMiner-releases#1007]
![image](https://user-images.githubusercontent.com/99034413/152561231-6a8b7a7e-1eff-4f80-8bf9-e041b0070f71.png)

I think it may be something from the lhrtune do you know how to disable it only for those two cards?

**Comment by crazygamer786** [comment]
i have this same issue last 2 cards don't mine

**Comment by sebek72** [comment]
I have an issue that only one 3060ti LHR does not perform well on TON
The one that work are 42ETH/900TON
This one 43ETH/200TON

**Comment by smarley2** [comment]
Here the same, 3 3060ti cards, 2 not mining.
And the one that is mining is too low.

**Comment by Kawasick** [comment]
In your OverClock, put PL in 0 and try if they are unlocked, it worked for me

**Comment by nicothyrael** [comment]
It didn't work for me. Nor 0 or empty.

**Comment by jgonzis** [comment]
> It didn't work for me. Nor 0 or empty.

It is Power Limit configuration, it is said in the Wiki. Also remember to restart miner each OC change
