### ISSUE TITLE
URGENT - Mining delay RIG Lol miner 1.42

### ISSUE THREAD

**Issue by netobertuso** [Lolliedieb/lolMiner-releases#1008]
Every time I'm away from the computer for more than 40 min, LOL MINER delays mining, when I come back I press enter and this screen comes up, what I noticed is that even mining like in the image, I DIDN'T EARN THOSE MH/s, Does anyone know what this is? I'm losing a lot of hash because of this, help me,
![Inkeddelay lol miner_LI](https://user-images.githubusercontent.com/96551942/152573672-b29bab3e-2e05-433f-a323-7512d0d1f526.jpg)
![Inkeddelay lol miner_LI](https://user-images.githubusercontent.com/96551942/152573692-d6f230a5-99f2-4968-b047-1599d7f80e22.jpg)
 please.

**Comment by Lolliedieb** [comment]
This is a known Windows thing - sadly Windows stops the console completely when you click into it. Right now not much I can do about it (unless I disallow to mark anything in the miner window ... there is some trade off)
