### ISSUE TITLE
2 same rig, 2 different hasrate ??

### ISSUE THREAD

**Issue by queinnec35** [Lolliedieb/lolMiner-releases#1009]
hello, i try the new miner 1.43 with eth +ton
i have very good result on 3 rig (rtx 3070 =>1300 core , 60 mh eth 1.43gh ton)
but on another rig i cap to 1.08gh with ton, 59 eth, same setting,s ame card, same driver , same hiveos version ?
somebody find why ?
i ahve make a clone ssd to be sure, same mother board , 2 different result

on windows now, i have strange mix, some 3070 make low eth but big ton, and some good eth and low ton ? can we set the split power?

**Comment by queinnec35** [comment]
![salon](https://user-images.githubusercontent.com/77555392/152580306-05cbcb12-c9a6-437b-a020-34b9c10983a9.jpg)

**Comment by queinnec35** [comment]
![benoit](https://user-images.githubusercontent.com/77555392/152580342-bb062570-f085-4f2e-b160-8a028c7a5db0.jpg)

**Comment by sebek72** [comment]
Increase PL and restart miner

**Comment by jgonzis** [comment]
Totally right increase PL or directly remove it!!
