### ISSUE TITLE
1.45 dual mining ETH+ TON continuous LHR Lock

### ISSUE THREAD

**Issue by Protoss46** [Lolliedieb/lolMiner-releases#1010]
![image](https://user-images.githubusercontent.com/29915123/152602262-122aada7-67d7-42e5-9961-70ac4946c3a0.png)

I'm having continuous lhr lock while dual mining. --lhrtune paramater goes to as low as -100.

**Comment by dealbreak3r** [comment]
Same problem here that started with version 1.43.  I noticed that 1.43 completes a very brief LHR autotune process at first, and then consistently detects locks, dropping lhrtune well past -40.   The LHR cards never get an opportunity to mine anything.

I tested the sample *.bat for dualmining ETH+TON, as well as just ETH.  Both do not work on LHR cards.   Windows 10, Nvidia Driver 472.12

I reverted back to 1.42 and the problem goes away.   1.42 takes its time through the initial LHR autotune process, finds a positive value for lhrtune, and works flawlessly afterwards.   Devs please take a look at this.

**Comment by jgonzis** [comment]
Nvidia Driver 472.12 and PLEASE use Core Clock Fix and leave Power Limit to 100% or ton get pl and launch a lock

**Comment by dealbreak3r** [comment]
1.  Already using 472.12
2.  Core clocks are already fixed using the --cclk parameter
3.  This is not just a TON mining issue, the LHR locking is affecting ETH mining.

**Comment by jgonzis** [comment]
> 1. Already using 472.12
> 2. Core clocks are already fixed using the --cclk parameter
> 3. This is not just a TON mining issue, the LHR locking is affecting ETH mining.

So same config with 1.42 don't lock and 1.43 lock. Is it possible that you do a run with both of 30min and put the picture. Wait 2 minutes between them. And only ETH (let's avoid TON ) Many thanks

**Comment by dealbreak3r** [comment]
exactly. here's what I'm seeing, but let me run them both now again for 30mins like you asked. I'll be back in an hour :)  No OC on the memory just to eliminate that possibility.

lolminer.exe --algo ETHASH --pool eth.2miners.com:2020 --user 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker --cclk 1125,1155,960,1560,1485 --log on --watchdog exit

v1.42
![1 42](https://user-images.githubusercontent.com/37665464/152614557-a07424e6-4c32-4047-8923-cc7d3d51181a.JPG)

v1.43
![1 43](https://user-images.githubusercontent.com/37665464/152614558-f16adc67-8621-4a16-830c-e1d93348d9fa.JPG)

**Comment by jgonzis** [comment]
> exactly. here's what I'm seeing, but let me run them both now again for 30mins like you asked. I'll be back in an hour :) No OC on the memory just to eliminate that possibility.
> 
> lolminer.exe --algo ETHASH --pool eth.2miners.com:2020 --user 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker --cclk 1125,1155,960,1560,1485 --log on --watchdog exit
> 
> v1.42 ![1 42](https://user-images.githubusercontent.com/37665464/152614557-a07424e6-4c32-4047-8923-cc7d3d51181a.JPG)
> 
> v1.43 ![1 43](https://user-images.githubusercontent.com/37665464/152614558-f16adc67-8621-4a16-830c-e1d93348d9fa.JPG)

Thank that will be useful

**Comment by dealbreak3r** [comment]
Here's your update.  Logs attached. I used 1.43 first, then waited a few minutes before starting 1.42.    GPU 0,1 are FHR, GPU 2,3,4 are LHR.  I've been using T-Rex miner for months and wish to switch over to dual mine ETH+TON.  As you can see I just can't get eth working on my LHR cards on this new version.

lolminer.exe --algo ETHASH --pool eth.2miners.com:2020 --user 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker --cclk 1125,1155,960,1560,1485 --log on --watchdog exit

v1.43
[1.43.log](https://github.com/Lolliedieb/lolMiner-releases/files/8007026/1.43.log)
![1 43](https://user-images.githubusercontent.com/37665464/152621512-4442df3a-c613-49d3-88cc-968ee7da4292.JPG)

v1.42
[1.42.log](https://github.com/Lolliedieb/lolMiner-releases/files/8007024/1.42.log)
![1 42](https://user-images.githubusercontent.com/37665464/152621506-79b7f545-a2d8-4bb2-92c7-32244e843239.JPG)

**Comment by Lolliedieb** [comment]
From the screenshots I would assume most issues are with Windows?
Can you tell me the exact driver version please (to check the code path ... having multiple for different drivers ...)

**Comment by PhanTi33** [comment]
Same issue with 1.43 - keeps locking up the card no matter what lhr setting you pick and even only on solo eth mininig. 3080lhr card, 471.68 driver. 1.42 runs with the same settings without any problem. Windows OS. Fellow of mine has hive os with similar 3080lhr cards and has no problems with these locks on v1.43

**Comment by Protoss46** [comment]
Fixed the problem with resetting all gpu clocks to default values (nvidia-smi.exe -rgc ). Core locking must be done by --mclk parameter and any previous core lock parameter must be reset to the default. 
Before starting the miner, you can verify the clock frequency is on idle (~200mhz) with msi afterburner or nvidiainspector.

**Comment by jgonzis** [comment]
Msi Afterburner For Memory
LolMiner lock clock with --cclk

**Comment by Protoss46** [comment]
> Msi Afterburner For Memory LolMiner lock clock with --cclk

If you dont unlock the previous lock clock frequency --mclk parameter wont work.
