### ISSUE TITLE
 Astronomical hashrates reported in ETH+TON mode

### ISSUE THREAD

**Issue by belviranli** [Lolliedieb/lolMiner-releases#1011]
The picture explains the problem.

684 MH/s ETH on 3080 Ti :D Plus 545 Gh/S on Ton. I am lucky :D 

![image](https://user-images.githubusercontent.com/54647757/152604021-5df6eca8-17ae-4ce5-b9a2-34e3527bb48d.png)

My OC settings:
![image](https://user-images.githubusercontent.com/54647757/152604220-3f6414a9-0d7e-4926-8a65-f67192c41131.png)

nvidia-smi screenshot:
![image](https://user-images.githubusercontent.com/54647757/152604156-a931b6de-ed7a-45a4-a38e-d1c65d6931e5.png)

**Comment by jgonzis** [comment]
Use Nvidia Driver 472.12....

New Drivers Don't work properly
