### ISSUE TITLE
lolminer has stopped working

### ISSUE THREAD

**Issue by sfiggg** [Lolliedieb/lolMiner-releases#1013]
Been dual mining ton+eth with no issue since this morning. Suddenly got the attached issue and can no longer dual mine without getting the error after building dag. 

Have tried downloading new version of 1.43 but same error. Can mine ton individually with no issue. 

![N1TTzgr](https://user-images.githubusercontent.com/99051377/152606663-c349962b-9111-4028-a96e-316589f67c25.png)
g

**Comment by jgonzis** [comment]
> Been dual mining ton+eth with no issue since this morning. Suddenly got the attached issue and can no longer dual mine without getting the error after building dag.
> 
> Have tried downloading new version of 1.43 but same error. Can mine ton individually with no issue.
> 
> ![N1TTzgr](https://user-images.githubusercontent.com/99051377/152606663-c349962b-9111-4028-a96e-316589f67c25.png) g

Increase your virtual memory space:

https://www.windowscentral.com/how-change-virtual-memory-size-windows-10?amp
