### ISSUE TITLE
3080 12 GB card on hive

### ISSUE THREAD

**Issue by Brellic** [Lolliedieb/lolMiner-releases#1015]
Hive shows the card as 220a wont mine. Works on windows not great but works. any idea what this issues is
27:00.0
Device 220a  · EVGA

**Comment by jgonzis** [comment]
> Hive shows the card as 220a wont mine. Works on windows not great but works. any idea what this issues is 27:00.0 Device 220a · EVGA

Try new drivers from nvidia-driver-update --list
