### ISSUE TITLE
TON+ETH DualMining and you can't select devices via EXTRAPARAMETERS? Issue and Fix is here.

### ISSUE THREAD

**Issue by heni015** [Lolliedieb/lolMiner-releases#1017]
Hi. I'm trying to mine TON+ETH on 2 of my cards, not at other cards, but there is a issue.
When you add your card to EXTRAPARAMETERS, all the time all cards trying to mine TON+ETH.
`set "EXTRAPARAMETERS=--devices=2,6`
but there is fast fix for it. Just replace at end of code **:W10**  and **:OtherW** with code below.
```
:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog exit !EXTRAPARAMETERS!
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END
```

```
:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause
```

**Comment by Sober13666** [comment]
got it. Same Issue.

**Comment by jgonzis** [comment]
> Hi. I'm trying to mine TON+ETH on 2 of my cards, not at other cards, but there is a issue. When you add your card to EXTRAPARAMETERS, all the time all cards trying to mine TON+ETH. `set "EXTRAPARAMETERS=--devices=2,6` but there is fast fix for it. Just replace at end of code **:W10** and **:OtherW** with code below.
> 
> ```
> :W10
> "%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog exit !EXTRAPARAMETERS!
> if %ERRORLEVEL% == 42 (
> 	timeout 10
> 	goto W10
> )
> goto END
> ```
> 
> ```
> :OtherW
> "%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor
> if %ERRORLEVEL% == 42 (
> 	timeout 10
> 	goto OtherW
> )
> 
> :END
> pause
> ```

Please use new bat file added in the releases section. It has been a bug in the zip file.
