### ISSUE TITLE
Disable a specific card

### ISSUE THREAD

**Issue by Sandraa03** [Lolliedieb/lolMiner-releases#1018]
I just applied this new feature to my rigs but I would like to disable this dual mining on some specific card on a rig and obly mine as always, is this possible? I cannot find any option to do it

**Comment by jgonzis** [comment]
> I just applied this new feature to my rigs but I would like to disable this dual mining on some specific card on a rig and obly mine as always, is this possible? I cannot find any option to do it

Yes... in Windows please use updated bat file from the release section others OS in their extra parameters 

Just add --devices 0,2 that will use only 0 and 2
