### ISSUE TITLE
Unable to Powerlimit using GTX970 while mining TON

### ISSUE THREAD

**Issue by crypto767** [Lolliedieb/lolMiner-releases#1019]
The power limit on Hive for lolminer 1.43 does not seem to have any effect. It works fine for RVN but as soon as you start mining TON the card just runs full speed and too hot.

**Comment by jgonzis** [comment]
> The power limit on Hive for lolminer 1.43 does not seem to have any effect. It works fine for RVN but as soon as you start mining TON the card just runs full speed and too hot.

Use MSI Afterburner for that... to limit it or use a Fixed Core option
