### ISSUE TITLE
Allocation of DAG failed with error: Memory object allocation failure. Ubuntu 18.04. Nvidia 1050 ti

### ISSUE THREAD

**Issue by lerg96** [Lolliedieb/lolMiner-releases#102]
I have some problems mining with my nvidia 1050 ti. zombie mode is not working o am i wrong?

lolMiner v1.16a
Ubuntu 18.04.4 LTS
NVIDIA-SMI 440.100 
Driver Version: 440.100
CUDA Version: 10.2

`./lolMiner --algo ETHASH --pool $POOL --user $WALLET $@ --tls 1 --keepfree 16 --4g-alloc-size 4000 `
or
`./lolMiner --algo ETHASH --pool $POOL --user $WALLET $@ --tls 1 --4g-alloc-size 4000 `

Setup Miner...
Device 0:
    Name:    GeForce GTX 1050 Ti
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  4036 MByte
    Max epoch (approx): 372
    Active:  true (Selected Algorithm: ETHash)
Device 1:
    Name:    Radeon RX 580 Series
    Address: 2:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8178 MByte (8158 MByte free)
    Max epoch (approx): 893
    Active:  true (Selected Algorithm: ETHash)
New job received: 0x034ef1 Epoch: 381 Target: 0000000112e0be82
-------------------------------------------------------
         Generating light cache for epoch 381
-------------------------------------------------------
Start Mining...
-------------------------------------------------------
     Done (2645 ms), size of new DAG: 4072 MByte
-------------------------------------------------------
GPU 0: insufficient memory for DAG epoch 381.
GPU 0: will be in Zombie mode with reduced hashrate.
GPU 0: Allocation of DAG failed with error: Memory object allocation failure
**GPU 0: will be stopped.**

**Comment by jgonzis** [comment]
Try: -4g-alloc-size 4072

**Comment by slobodanzivojinovic** [comment]
Same problem... Did you solve it... Thank you

**Comment by 5ive5tar** [comment]
I'm also having the same issue. Any fix yet? Would appreciate it!

**Comment by jgonzis** [comment]
> I'm also having the same issue. Any fix yet? Would appreciate it!

The size of the mem must be higher for ETH, you can try ETC but not ETH in Zombie mode

**Comment by evanma08** [comment]
Same question anybody solved yet?

**Comment by evanma08** [comment]
> > I'm also having the same issue. Any fix yet? Would appreciate it!
> 
> The size of the mem must be higher for ETH, you can try ETC but not ETH in Zombie mode

I have tried but useless

**Comment by sonicblu** [comment]
Pc ...right click....properties ...advanced system settings...advanced tab...performance..click settings.
Advanced tab...change virtual memory.....

I went to 32000 for initial and max....

Set ....apply ....restart

**Comment by jgonzis** [comment]
> I have some problems mining with my nvidia 1050 ti. zombie mode is not working o am i wrong?
> 
> lolMiner v1.16a
> Ubuntu 18.04.4 LTS
> NVIDIA-SMI 440.100
> Driver Version: 440.100
> CUDA Version: 10.2
> 
> `./lolMiner --algo ETHASH --pool $POOL --user $WALLET $@ --tls 1 --keepfree 16 --4g-alloc-size 4000 `
> or
> `./lolMiner --algo ETHASH --pool $POOL --user $WALLET $@ --tls 1 --4g-alloc-size 4000 `
> 
> ## Setup Miner...
> Device 0:
> Name: GeForce GTX 1050 Ti
> Address: 1:0
> Vendor: NVIDIA Corporation
> Memory: 4036 MByte
> Max epoch (approx): 372
> Active: true (Selected Algorithm: ETHash)
> Device 1:
> Name: Radeon RX 580 Series
> Address: 2:0
> Vendor: Advanced Micro Devices (AMD)
> Memory: 8178 MByte (8158 MByte free)
> Max epoch (approx): 893
> Active: true (Selected Algorithm: ETHash)
> New job received: 0x034ef1 Epoch: 381 Target: 0000000112e0be82
> ```
>      Generating light cache for epoch 381
> ```
> 
> ## Start Mining...
> ```
>  Done (2645 ms), size of new DAG: 4072 MByte
> ```
> 
> GPU 0: insufficient memory for DAG epoch 381.
> GPU 0: will be in Zombie mode with reduced hashrate.
> GPU 0: Allocation of DAG failed with error: Memory object allocation failure
> **GPU 0: will be stopped.**

Why you don't mine the other gpu without the 1st one just adding --devices 1  Now you will be able to mine with the 8Gb ETH.

**Comment by jgonzis** [comment]
Zombie Mode in Nvidia not working.
