### ISSUE TITLE
Cooldown error on 3060s that aren't warm

### ISSUE THREAD

**Issue by mikeike951** [Lolliedieb/lolMiner-releases#1020]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/76020129/152620224-61a3ab48-0345-4d19-82d1-0d927d7d52cc.png">
Earlier today I was able to get my 3060 to run for maybe 30 minutes or so. Now they won't launch at all. I just keep getting this same error. I am using two miners at once. Gminer 2.74 for two other cards on the same rig. The other two are FHR cards so I don't really need to dual mine on those. Any idea why I can't get the 3060s back to work on lol?

**Comment by jgonzis** [comment]
> <img alt="image" width="470" src="https://user-images.githubusercontent.com/76020129/152620224-61a3ab48-0345-4d19-82d1-0d927d7d52cc.png">
> 
> Earlier today I was able to get my 3060 to run for maybe 30 minutes or so. Now they won't launch at all. I just keep getting this same error. I am using two miners at once. Gminer 2.74 for two other cards on the same rig. The other two are FHR cards so I don't really need to dual mine on those. Any idea why I can't get the 3060s back to work on lol?

It works for all GPUs. That seems or:

HiveOS not updated 
Flightsheet not right done

Could you share the flightsheet if you have HiveOS updated

**Comment by jgonzis** [comment]
Solved with 1.46, in case you select more than 2 pools for DUAL MINING
