### ISSUE TITLE
3060 Ti ETH + TON 0 Mh/s on TON

### ISSUE THREAD

**Issue by Xefier** [Lolliedieb/lolMiner-releases#1022]
Windows 10
lolMiner 1.43

- I already interacted with the TON Whales telegram bot and it said "Congrats! Now you can use Whales Pool."
- I tried restarting the miner
- I tried setting Core Limit to 1350 (~120W) and 1800 (~170W)

![image](https://user-images.githubusercontent.com/6353352/152623547-3e1e0df4-b2b9-4343-9945-8a768af2e586.png)

**Comment by Xefier** [comment]
I have the same issue on Hive OS

**Comment by RootCause1** [comment]
Make sure to change --dual mode to TONDUAL under :W10 and :OtherW for editing the .bat file.  

It is explained for Hive OS under https://github.com/Lolliedieb/lolMiner-releases/wiki/Example-to-configure-Dual-Mining-ETH-ETC-UBQHASH-TON

**Comment by Xefier** [comment]
So the thing is "mining" TON at the same time but the hashrate is 0 Mh/s. Except one time one of my GPUs had an error then the other GPU was actually getting some hashrate on TON but then after rebooting the TON hashrate went back down to 0

**Comment by Xefier** [comment]
See, I'm getting TON jobs but still 0 MH/s
![image](https://user-images.githubusercontent.com/6353352/152629425-245d4c73-9993-4193-b2b6-d19d349fb82d.png)

**Comment by Xefier** [comment]
And the pool says I got 2 shares from the time it actually had hashrate and since then I haven't changed any config other than rebooting the machine.

**Comment by Xefier** [comment]
Also tried switching to a different pool but same issue

**Comment by Xefier** [comment]
Also the pool seems to be fully aware that I'm mining to it, yet I still have 0 MH/s.

![image](https://user-images.githubusercontent.com/6353352/152630293-e1746642-e3fe-4199-bc0e-95d788408d22.png)

**Comment by Xefier** [comment]
The exact same flight sheet seems to work on a 3rd rig

**Comment by RootCause1** [comment]
Did you try this? Thats odd that it works on one rig and not the other. 

![image](https://user-images.githubusercontent.com/28808954/152630552-e4d7c0e1-c66f-49cb-8e82-b73a1344d6f7.png)

**Comment by Xefier** [comment]
> Did you try this? Thats odd that it works on one rig and not the other.
> 
> ![image](https://user-images.githubusercontent.com/28808954/152630552-e4d7c0e1-c66f-49cb-8e82-b73a1344d6f7.png)

I obviously have that part configured correctly as you can see from all my evidence.

**Comment by Xefier** [comment]
However it does seems like only one of my 3070s are getting decent hashrate, the rest have horrible TON hashrate. (Like 30-90)

**Comment by RootCause1** [comment]
I was able to get my two 3060ti LHRs going and my 3060ti Non-LHR. It does take a min or two to setup and go especially with the LHR cards.

**Comment by Xefier** [comment]
Haven't tried it on any LHR cards yet. 
Update: 3090 seems to work

**Comment by Xefier** [comment]
With adjust overclocks I got better hashrates on the 1 3070 that was already decent. HOWEVER the rest of the cards still have terrible hashrate or 0...

**Comment by Xefier** [comment]
OK here we go, it seems the key is that you need to restart the miner after adjusting clock and power settings unlike other algorithms. Most of the cards are getting decent TON hashrates now. Probably can go higher if I adjust the settings more aggressively.

**Comment by RootCause1** [comment]
Yea on my LHRs it is my non LHRs are doing good. Good to hear you figured to not mining TON part.

**Comment by Xefier** [comment]
Got decent results on the 3070s at least but still 3060 Tis being pretty stubborn
![image](https://user-images.githubusercontent.com/6353352/152632467-2326eb7f-4ca3-4a02-9c18-5cfbc729dc53.png)

**Comment by Xefier** [comment]
Also on another rig my 3060 Tis simply refuse to have any TON hashrate even up to 140W

**Comment by jgonzis** [comment]
> Also on another rig my 3060 Tis simply refuse to have any TON hashrate even up to 140W

Please put PL 170 and RESTART MINER that will make to go. If Watts touch your PL limit then TON will not work perfectly

**Comment by Xefier** [comment]
Yea the key seems to never hit the power limit. However unfortunately in my case I can't afford to just let the power consumption go up too high. But the solution to that is to control the power via core lock which does reduce TON hashrate but I'm starting to find a decent balance between ETH/TON and Watts but it is pretty tough.

**Comment by jgonzis** [comment]
> Yea the key seems to never hit the power limit and restart miner every time you tweak any overclock/power settings. However unfortunately in my case I can't afford to just let the power consumption go up too high. But the solution to that is to control the power via core lock which does reduce TON hashrate but I'm starting to find a decent balance between ETH/TON and Watts but it is pretty tough.

You can also play with the parameter of the wiki tuning

--maxdualimpact and put a value of 0.1 or 0.2 instead of the default 0.5

**Comment by Xefier** [comment]
Ah yes --maxdualimpact  does help with tweaking, thanks.
