### ISSUE TITLE
Hive OS TON + ETH lolminer exited (exitcode=0), waiting to cooldown a bit

### ISSUE THREAD

**Issue by Xefier** [Lolliedieb/lolMiner-releases#1023]
Hive OS 0.6-213@220205
lolMiner The latest (1.43)

![image](https://user-images.githubusercontent.com/6353352/152626303-bc2625e8-eb87-40cc-931b-a02019897c93.png)
![image](https://user-images.githubusercontent.com/6353352/152626313-2fd8ec0d-08ac-48f4-b4df-89c67a02dcda.png)

**Comment by Xefier** [comment]
I'm not sure which solved it but I tried 3 things and it prevented this error
- Removed Worker name from second hash algorithm
- Removed Extra config arguments (I only put that there because of a guide)
- Changed Version from THe latest to specifically 1.43

**Comment by Manolo74410** [comment]
Hi, i have the same error but only with the classique TON wallet...

And nothing of your issue work for me 

![image](https://user-images.githubusercontent.com/99068515/152632894-6096585b-4e19-4d40-9d82-a2dd80885e3e.png)

**Comment by jgonzis** [comment]
> Hi, i have the same error but only with the classique TON wallet...
> 
> And nothing of your issue work for me
> 
> ![image](https://user-images.githubusercontent.com/99068515/152632894-6096585b-4e19-4d40-9d82-a2dd80885e3e.png)

Update HiveOS please.... that seems you don't have click the Orange link of the update

**Comment by jgonzis** [comment]
> Hive OS 0.6-213@220205 lolMiner The latest (1.43)
> 
> ![image](https://user-images.githubusercontent.com/6353352/152626303-bc2625e8-eb87-40cc-931b-a02019897c93.png) ![image](https://user-images.githubusercontent.com/6353352/152626313-2fd8ec0d-08ac-48f4-b4df-89c67a02dcda.png)

That will not work... workername is only for toncoinpool.io and cannot work with other ton pools so you have there a problem...

**Comment by Manolo74410** [comment]
> 

Thanks but my HiveOS is Ok (with morning update)... another idea ?

**Comment by jgonzis** [comment]
> > 
> 
> Thanks but my HiveOS is Ok (with morning update)... another idea ?

Manolo, ha de ser la configuración. Si puedes pon la tuya y te digo que te está fallando. Mira de seleccionar solo 1 pool para TON

**Comment by Manolo74410** [comment]
> > > 
> > 
> > 
> > Thanks but my HiveOS is Ok (with morning update)... another idea ?
> 
> Manolo, ha de ser la configuración. Si puedes pon la tuya y te digo que te está fallando. Mira de seleccionar solo 1 pool para TON



My configuration : 
![image](https://user-images.githubusercontent.com/99068515/152636594-8d4c15ae-fc02-4265-b1f8-59a5b9a1d0e9.png)
![image](https://user-images.githubusercontent.com/99068515/152636597-690959dc-c87f-47ac-b9c5-16b772444b5a.png)
![image](https://user-images.githubusercontent.com/99068515/152636607-15d63594-afa6-4ed3-85ec-9464cd6e424b.png)
![image](https://user-images.githubusercontent.com/99068515/152636621-356db0e5-3096-49cd-98cd-7fb3126fe33d.png)

**Comment by jgonzis** [comment]
> > > > 
> > > 
> > > 
> > > Thanks but my HiveOS is Ok (with morning update)... another idea ?
> > 
> > 
> > Manolo, ha de ser la configuración. Si puedes pon la tuya y te digo que te está fallando. Mira de seleccionar solo 1 pool para TON
> 
> My configuration : ![image](https://user-images.githubusercontent.com/99068515/152636594-8d4c15ae-fc02-4265-b1f8-59a5b9a1d0e9.png) ![image](https://user-images.githubusercontent.com/99068515/152636597-690959dc-c87f-47ac-b9c5-16b772444b5a.png) ![image](https://user-images.githubusercontent.com/99068515/152636607-15d63594-afa6-4ed3-85ec-9464cd6e424b.png) ![image](https://user-images.githubusercontent.com/99068515/152636621-356db0e5-3096-49cd-98cd-7fb3126fe33d.png)

With that config and HiveOS update (orange link clicked) it has to work... come to Telegram in case updated to see which error shows the miner log

**Comment by khizar007** [comment]
Remove Worker name from both first and second hash algorithm will fix the problem.

**Comment by arpbit33** [comment]
I am facing same issue. I removed both worker name from both algorithm.  It is still the same.

**Comment by Manolo74410** [comment]
> I am facing same issue. I removed both worker name from both algorithm. It is still the same.

I have found a solution for me.
Sélect only one link for ton pool

**Comment by jgonzis** [comment]
> > I am facing same issue. I removed both worker name from both algorithm. It is still the same.
> 
> I have found a solution for me. Sélect only one link for ton pool

Thx that right!!!

**Comment by khizar007** [comment]
working config
![image](https://user-images.githubusercontent.com/52601404/152660587-c56a467a-74b0-44c9-9625-3f9197edd651.png)

**Comment by stratum-ui** [comment]
> working config ![image](https://user-images.githubusercontent.com/52601404/152660587-c56a467a-74b0-44c9-9625-3f9197edd651.png)

Good Day.
Can't figure out hot to set up eth and ton wallets to make it work properly with this config. when i apply this config in connects to ton pool and starts seeing work assignments but it does not try to solve any.. and it completely refuses to log in to binance pool which i ordinarily use..
![problem1](https://user-images.githubusercontent.com/99313509/153132561-501c1064-6342-494a-8779-c135b3c2273b.jpg)

**Comment by jgonzis** [comment]
> > working config ![image](https://user-images.githubusercontent.com/52601404/152660587-c56a467a-74b0-44c9-9625-3f9197edd651.png)
> 
> Good Day. Can't figure out hot to set up eth and ton wallets to make it work properly with this config. when i apply this config in connects to ton pool and starts seeing work assignments but it does not try to solve any.. and it completely refuses to log in to binance pool which i ordinarily use.. ![problem1](https://user-images.githubusercontent.com/99313509/153132561-501c1064-6342-494a-8779-c135b3c2273b.jpg)

Here hasn't connect yet to ethash pool, dag is not generated yet. I see Pascal gpus. Are you with 1.44?

**Comment by stratum-ui** [comment]
> Here hasn't connect yet to ethash pool, dag is not generated yet. I see Pascal gpus. Are you with 1.44?
The point is it keeps not connecting.. no lolminer ver 1.43

**Comment by stratum-ui** [comment]
> > > working config ![image](https://user-images.githubusercontent.com/52601404/152660587-c56a467a-74b0-44c9-9625-3f9197edd651.png)
> > 
> > 
> > Good Day. Can't figure out hot to set up eth and ton wallets to make it work properly with this config. when i apply this config in connects to ton pool and starts seeing work assignments but it does not try to solve any.. and it completely refuses to log in to binance pool which i ordinarily use.. ![problem1](https://user-images.githubusercontent.com/99313509/153132561-501c1064-6342-494a-8779-c135b3c2273b.jpg)
> 
> Here hasn't connect yet to ethash pool, dag is not generated yet. I see Pascal gpus. Are you with 1.44?
![problem1-1](https://user-images.githubusercontent.com/99313509/153178603-123fa932-2e3a-45cb-a874-efa2e47f3dbc.jpg)
The point is it keeps not connecting.. no lolminer ver 1.43

**Comment by jgonzis** [comment]
> > > > working config ![image](https://user-images.githubusercontent.com/52601404/152660587-c56a467a-74b0-44c9-9625-3f9197edd651.png)
> > > 
> > > 
> > > Good Day. Can't figure out hot to set up eth and ton wallets to make it work properly with this config. when i apply this config in connects to ton pool and starts seeing work assignments but it does not try to solve any.. and it completely refuses to log in to binance pool which i ordinarily use.. ![problem1](https://user-images.githubusercontent.com/99313509/153132561-501c1064-6342-494a-8779-c135b3c2273b.jpg)
> > 
> > 
> > Here hasn't connect yet to ethash pool, dag is not generated yet. I see Pascal gpus. Are you with 1.44?
> > ![problem1-1](https://user-images.githubusercontent.com/99313509/153178603-123fa932-2e3a-45cb-a874-efa2e47f3dbc.jpg)
> > The point is it keeps not connecting.. no lolminer ver 1.43

1.43 doesn't work with Pascal...
