### ISSUE TITLE
Connecting through eth proxy not possible/not working 

### ISSUE THREAD

**Issue by GTreaper** [Lolliedieb/lolMiner-releases#1025]
Hello, I'm trying to connect via my local eth proxy which I'm hosting. But no matter what I try it fails, miner says connected then 1sec later it's disconnected.

I'm using atrides eth proxy.

Works great with trex but can't get it working on lolminer, any help is appreciated.

And yes I wanna use the proxy

**Comment by jgonzis** [comment]
> Hello, I'm trying to connect via my local eth proxy which I'm hosting. But no matter what I try it fails, miner says connected then 1sec later it's disconnected.
> 
> I'm using atrides eth proxy.
> 
> Works great with trex but can't get it working on lolminer, any help is appreciated.
> 
> And yes I wanna use the proxy

Use the socks option added to do that

**Comment by GTreaper** [comment]
> > Hello, I'm trying to connect via my local eth proxy which I'm hosting. But no matter what I try it fails, miner says connected then 1sec later it's disconnected.
> > I'm using atrides eth proxy.
> > Works great with trex but can't get it working on lolminer, any help is appreciated.
> > And yes I wanna use the proxy
> 
> Use the socks option added to do that

Thanks for the answer, can I use that when dual mining ton and eth?  And I assume you mean the option --socks5 is that correct?

**Comment by jgonzis** [comment]
> > > Hello, I'm trying to connect via my local eth proxy which I'm hosting. But no matter what I try it fails, miner says connected then 1sec later it's disconnected.
> > > I'm using atrides eth proxy.
> > > Works great with trex but can't get it working on lolminer, any help is appreciated.
> > > And yes I wanna use the proxy
> > 
> > 
> > Use the socks option added to do that
> 
> Thanks for the answer, can I use that when dual mining ton and eth? And I assume you mean the option --socks5 is that correct?

Yes try it... with eth works. TON Pools don't allow that... but let's see if you are able to jump it.

**Comment by GTreaper** [comment]
> > > > Hello, I'm trying to connect via my local eth proxy which I'm hosting. But no matter what I try it fails, miner says connected then 1sec later it's disconnected.
> > > > I'm using atrides eth proxy.
> > > > Works great with trex but can't get it working on lolminer, any help is appreciated.
> > > > And yes I wanna use the proxy
> > > 
> > > 
> > > Use the socks option added to do that
> > 
> > 
> > Thanks for the answer, can I use that when dual mining ton and eth? And I assume you mean the option --socks5 is that correct?
> 
> Yes try it... with eth works. TON Pools don't allow that... but let's see if you are able to jump it.

Tried just eth to begin with but adding --socks5 with the ip and port as arg just gets me too where it sits at connecting to pool and never connects. hmm this was a hard nut to crack

**Comment by GTreaper** [comment]
For now i think i can just run two instances of miners, running T-rex for eth via my proxy and lolminer on ton, seem to be working fine! 
Would be great if you have some time over to check out how to solve this issue! 

A last question and i'm sorry to be bugging you, but split mining where you split eth hashrate between two pools doesn't seem to be working in hiveos. I added these parameters to extra config, should i do it different?

--dualmode SPLIT-20 --dualpool eu1.ethermine.org:4444 --dualworker NvidiaRig
