### ISSUE TITLE
bug oc with --mclk dual mine eth ton - windows

### ISSUE THREAD

**Issue by xMasterSolidx** [Lolliedieb/lolMiner-releases#1026]
rtx 3060 lhr v2

oc memory clock --mclk 1250
eth 20 MH/S
Ton 900MH/S

afterburner oc memory clock +1250
eth 35MH/S
Ton 900MH/S

afterburner oc core clock +200 memory clock +1250
eth 35MH/S
ton 1.111GH/S

> 
Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --mclk 1250 --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --mclk 1250 --watchdog exit --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause

>

**Comment by jgonzis** [comment]
> rtx 3060 lhr v2
> 
> oc memory clock --mclk 1250 eth 20 MH/S Ton 900MH/S
> 
> afterburner oc memory clock +1250 eth 35MH/S Ton 900MH/S
> 
> afterburner oc core clock +200 memory clock +1250 eth 35MH/S ton 1.111GH/S
> 
> > 
> 
> Rem ################################# Rem ## End of user-editable part ## Rem #################################
> 
> if exist "%CD%\lolMiner.exe" goto infolder echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..." for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F if exist "%MyVariable%" goto WindowsVer echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus " goto END
> 
> :infolder set MyVariable=%CD%\lolMiner.exe
> 
> :WindowsVer echo "Running lolMiner from %MyVariable%" for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j if "%version%" == "10.0" goto W10 goto OtherW
> 
> :W10 "%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --mclk 1250 --watchdog exit if %ERRORLEVEL% == 42 ( timeout 10 goto W10 ) goto END
> 
> :OtherW "%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --mclk 1250 --watchdog exit --nocolor if %ERRORLEVEL% == 42 ( timeout 10 goto OtherW )
> 
> :END pause
> 
> >

It is not a BUG. --mclk is only for TON not for ETH. It is been informed in the wiki

mclk do a fix of the memory not a offset memory, for that please use MSI Afterburner in Windows or Mining OS in Linux. If you have run 1 time with -mclk you will need to restart computer memory is bloques very low
