### ISSUE TITLE
Question: selecting devices

### ISSUE THREAD

**Issue by DasUnding** [Lolliedieb/lolMiner-releases#1028]
I have a little questions. I have problems selecting certain devices for mining using: "EXTRAPARAMETERS=--devices 1" or set "EXTRAPARAMETERS=--devicesbypcie on, --devices 4:0" but all devices are selected instead of the desired one. What is wrong? Maybe someone can help.

**Comment by nameless314** [comment]
I'm assuming you're using the eth+ton batch file that came with the zip file. That one is missing the !EXTRAPARAMETERS argument in the code. You can either add the argument or download the .bat file they attached separately outside the zip file. https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

**Comment by DasUnding** [comment]
Yes I tested the dual mining. Thank you for the batch file it works now.
