### ISSUE TITLE
dualmode eth not working on 1,43 version

### ISSUE THREAD

**Issue by lollo1988vt** [Lolliedieb/lolMiner-releases#1029]
after upgrade on 1.43 version dualmode eth (divide gpu on 2 eth pool different ) not working

**Comment by vjk1992** [comment]
it works if you correct in the previous guide "turned Off" for Etash and put "turned On" for tondual

**Comment by lollo1988vt** [comment]
the comand --dualmode eth are notrecognized

**Comment by telethrasher** [comment]
if you're putting the command in ExtraParameters section a lot of the batch files are missing the !EXTRAPARAMETERS! call at the bottom ...
the two lines with --watchdog exit should be followed by !EXTRAPARAMETERS!

like:
:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog off !EXTRAPARAMETERS!

**Comment by lollo1988vt** [comment]
I'm using hiveos, if i want select 4 gpus on first pool eth and 4 gpus on second pool, when i put in extra parameters --dualpool eth is not recognize 
come how can i program the rig so that 4 gpus work on one eth pool and 4 gpus work on another pool? with version 1.42 the --dualpool command works perfectly

**Comment by jgonzis** [comment]
> I'm using hiveos, if i want select 4 gpus on first pool eth and 4 gpus on second pool, when i put in extra parameters --dualpool eth is not recognize come how can i program the rig so that 4 gpus work on one eth pool and 4 gpus work on another pool? with version 1.42 the --dualpool command works perfectly

--dualpool ETHASH not eth ;-)

**Comment by RdWing** [comment]
Actually this is still broken. Until 1.42 you can use --dualmode eth with dualdevices to point certain cards in your rig to another pool, no problem. But 1.43 and later no longer work. Is there a plan to restore this functionality? It's really important for folks that might do commission or other structures.

**Comment by jgonzis** [comment]
> Actually this is still broken. Until 1.42 you can use --dualmode eth with dualdevices to point certain cards in your rig to another pool, no problem. But 1.43 and later no longer work. Is there a plan to restore this functionality? It's really important for folks that might do commission or other structures.

Completely right, but it was replaced to a more logical  parameters, could you please put your old line and I transform to the new scheme?
