### ISSUE TITLE
DUALTON, mixed rig inc. Vega56 - (last) 4 cards have TON hash rate, (first) 4 cards all TON = 0 Mh/s. So strange. 

### ISSUE THREAD

**Issue by rnschnei** [Lolliedieb/lolMiner-releases#1030]
DUALTON is so brilliant it is not even funny. 

this rig - Vega56, Vega56, Radeon VII, Vega56, Vega56, Vega56, Vega56, 3080Ti
first 4 cards, 0 TON hashrate; last 4 cards have TON hashrate... 
(HiveOS) 
![image](https://user-images.githubusercontent.com/26250402/152636416-c6b2df7f-a064-4943-b74f-0175cc94edbd.png) 

any suggestions? 

PS Have another rig with 7 cards (5500XT, 5700's, 2070 Super); works fine, all cards have ETH hash and TON hash.

**Comment by rnschnei** [comment]
just tried --maxdualimpact 25,25,25,25,25,25,25,*
last 4 dropped in ETH, up in TON; no difference to first 4

**Comment by hsynynrdg** [comment]
Same here, 
Has 2x rtx 3060 lhr v2 exactly same cards but one of has TON hash the other 0.

Tried with --maxdualimpact 1,4 it became same but not work with default values

**Comment by shmox75** [comment]
> maxdualimpact

Hi can you help on how did you fix it please

**Comment by hsynynrdg** [comment]
> > maxdualimpact
> 
> Hi can you help on how did you fix it please

I wrote that is fixed my issue.

--maxdualimpact 1,4

**Comment by rnschnei** [comment]
I was able to get the first 4 cards to start TON hashing using super-high (... are they?) values in maxdualimpact... (this got some of the first-4 running --maxdualimpact 40,50,100,50,*,*,*,*; tried values of 500 and 100 too) but then the ETH rate gets washed out on the first-4. 
My guess is it is some kind of issue with Vega 56's (modded BIOS on Vega64, FYI). BTW, seeing 3 different TON hash rates for very similar ETH hashrates on the last 4 / Vega56's in that group. 
![image](https://user-images.githubusercontent.com/26250402/152703002-92e69f7a-e40d-4091-9bd3-503946257b48.png)

Will try with a single Vega56 in a different system, when I can... 
Also, it might have to do with what order the cards are started in (pass DAG check); when I re-launch, the first 4 cards are not consistent in their TON hashrate, nor if they even start TON or not. (Appears to move around. Just a guess as to the cause, because DAG check order is one of the varying items.)

**Comment by jgonzis** [comment]
Lot of the problems come for the Power Limit...

And also if there is a DAG Repair at the start of the miner. If it is a DAG Repair then  no TON will be mined with the AMD.

**Comment by rnschnei** [comment]
thanks @jgonzis!

yeah, I was watching the DAG repairs like a hawk in the logs. I have had sessions where all cards fully pass but then only the last 4 hash TON. 

no power limits set for AMD's, although I did try removing the Vdd's completely... can try pushing them up too... I didn't think Vdd would have as much of an impact?

To my inexperienced mind, there is nothing different about the first 4 cards (at least the first 3 Vega56's anyhow.) (core clock set lower because no TON.) 
![image](https://user-images.githubusercontent.com/26250402/153048655-04d5c37a-e2f5-4784-ac8f-12866818bc6d.png)

As I mentioned in one of my earlier posts, I could get some of the first 4 to start... with really high values of maxdualimpact but then the ETH:TON ratio was really skewed. Backing off on the maxdualimpact weight then they just failed to start.... 

Are the maxdualimpacts weight relative to each other (other cards in the system) or anything like that? Or just an 'intensity' per card? 
Is there debug logging or something else where I could look for hints? 

If I were feeling really ambitious I can try to swap the physical/PCIe slot location of the cards and see what happens; need to transfer the settings so a little tricky but doable.

**Comment by jgonzis** [comment]
> thanks @jgonzis!
> 
> yeah, I was watching the DAG repairs like a hawk in the logs. I have had sessions where all cards fully pass (no repair required) but then only the last 4 hash TON.
> 
> no power limits set for AMD's, although I did try removing the Vdd's completely... can try pushing them up too... I didn't think Vdd would have as much of an impact?
> 
> To my inexperienced mind, there is nothing different about the first 4 cards (at least the first 3 Vega56's anyhow.) (core clock set lower because no TON.) ![image](https://user-images.githubusercontent.com/26250402/153048655-04d5c37a-e2f5-4784-ac8f-12866818bc6d.png)
> 
> As I mentioned in one of my earlier posts, I could get some of the first 4 to start... with really high values of maxdualimpact but then the ETH:TON ratio was really skewed. Backing off on the maxdualimpact weight then they just failed to start....
> 
> Are the maxdualimpacts weight relative to each other (other cards in the system) or anything like that? Or just an 'intensity' per card? Is there debug logging or something else where I could look for hints?
> 
> If I were feeling really ambitious I can try to swap the physical/PCIe slot location of the cards and see what happens; need to transfer the settings so a little tricky but doable.

--maxdualimpact can be set for each card, or globally... give a tries:

--maxdualimpact 3 

Could you try with the 1.44?

Or a stupid thing I didn't try make it with --dagdelay 2 on 3 just to test...
