### ISSUE TITLE
Dual mining ETH+TON: --pool "eth.2miners.com:2020" can not be split into a address and a port

### ISSUE THREAD

**Issue by thales51064** [Lolliedieb/lolMiner-releases#1033]
Tried to setup lolminer to dual mining ETH+TON but for some reason it reject the 2miners pool saying there's an format error. Did I miss something?

Settings from dual_mine_eth_ton.bat is:

> set "POOL=eth.2miners.com:2020"
> set "WALLET=myNanoAddress.workerName"
> 
> set "TONPOOL=server1.whalestonpool.com"
> set "TONWALLET=myTonAddress"
> 							
> set "EXTRAPARAMETERS="

proof: 
![alacritty_Ew2qlI5XPg](https://user-images.githubusercontent.com/95551644/152641146-b59fcb1e-b189-43c0-be35-1c401ffba6a7.png)

**Comment by Brogetter** [comment]
figure it out?

**Comment by drcdtorres** [comment]
you need to add the https:// at the beginning of the TONPOOL

**Comment by thales51064** [comment]
> you need to add the https:// at the beginning of the TONPOOL

it's working now, thanks a bunch
