### ISSUE TITLE
1.43 miner stats API, there is no worker name.

### ISSUE THREAD

**Issue by Rigmondotnet** [Lolliedieb/lolMiner-releases#1034]
Hello, I am a developer of Rigmon.net (miner monitoring app)
New miner stats API is cool but I could not find worker name anywhere.
User put worker name with wallet address like bellow and then it is well visible on mining pool.
> --user  wallet_address.worker_name

Before API is changed, user name was accessible from "Stratum.Current_User"
Most miner support worker name through API and it is very useful information for the management.
Please add API support for worker name.

Love new API for dual miners.
Thanks!

**Comment by jgonzis** [comment]
You are completely right... it doesn't show the Worker name:

Using --user wallet_address.worker_name and also using --worker worker_name

I open feature and try to add it, not only user in algorithm also worker name as you said.

**Comment by jgonzis** [comment]
We have it yet for 1.46, thanks for the information
