### ISSUE TITLE
what is the best nvidia driver for rtx 3000 NO lhr ? the more stable?

### ISSUE THREAD

**Issue by queinnec35** [Lolliedieb/lolMiner-releases#1035]
hello, i still have random bug, on hiveos, maybe the dev can advice to us the best driver to use? i dont want the best hashrate, i want the more stable and leave alone my rig, boring to check every hour if he still work..
on windows i have some bug, but all rig at the same time, so i think it s a lolminer bug, not the  rig /computer. (memory acces violation or press a key to exit, unable to launch again, after wait 20 min that work )

thx for your replay

**Comment by jgonzis** [comment]
> hello, i still have random bug, on hiveos, maybe the dev can advice to us the best driver to use? i dont want the best hashrate, i want the more stable and leave alone my rig, boring to check every hour if he still work.. on windows i have some bug, but all rig at the same time, so i think it s a lolminer bug, not the rig /computer. (memory acces violation or press a key to exit, unable to launch again, after wait 20 min that work )
> 
> thx for your replay

470.74 or 470.86 or 470.94 are working great...  I think your problem could be very high memory OC... which value are you using?

**Comment by queinnec35** [comment]
i use 470.74 atm, that not oc i have try many setting, that work great, but sometime i got error on wondows, , when i check hiveos rig , 1 or 2 have the same timing reboot, it s synchro :) that s not random
