### ISSUE TITLE
ETH + TON Dual Mining High Stale Shares

### ISSUE THREAD

**Issue by Protoss46** [Lolliedieb/lolMiner-releases#1037]
![image](https://user-images.githubusercontent.com/29915123/152647389-fc1d87bb-fac6-4afd-aeb4-5c355ee43e7b.png)

Very high stale shares with ETH + TON mining. Currenty %6 stale shares.
You can compare the difference with the secrenshoot, before and after 5. February. Same server with 35 ms latency.

**Comment by sfiggg** [comment]
same issue for me.. stales went from from <1% to 5%

**Comment by nameless314** [comment]
Similar issue on my 3070FE. Averaging 5% stale on ethermine @20ms latency

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/29915123/152647389-fc1d87bb-fac6-4afd-aeb4-5c355ee43e7b.png)
> 
> Very high stale shares with ETH + TON mining. Currenty %6 stale shares. You can compare the difference with the secrenshoot, before and after 5. February. Same server with 35 ms latency.

Which OS and which GPUs? could we have some information?.  With wifi 6 rigs... normal stales.
![image](https://user-images.githubusercontent.com/38668405/152654756-015951fd-18f2-4e28-b207-39f482d6e2d1.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/29915123/152647389-fc1d87bb-fac6-4afd-aeb4-5c355ee43e7b.png)
> 
> Very high stale shares with ETH + TON mining. Currenty %6 stale shares. You can compare the difference with the secrenshoot, before and after 5. February. Same server with 35 ms latency.

Is it possible to have a log file?. to check if the miner is reporting also that.  just to have more feedback

**Comment by Protoss46** [comment]
![image](https://user-images.githubusercontent.com/29915123/152657544-2ffb7e2e-2f5d-480e-99b8-3b47539b02fb.png)
[log.txt](https://github.com/Lolliedieb/lolMiner-releases/files/8008842/log.txt)
I don't keep the logs but this is what i could get from the last  terminal session. Uptime: 7h 49m 10s
Stales are still high.

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/29915123/152657544-2ffb7e2e-2f5d-480e-99b8-3b47539b02fb.png) ![image](https://user-images.githubusercontent.com/29915123/152657651-0aad435c-3d84-452d-a0a4-728e78c0ae1f.png) [log.txt](https://github.com/Lolliedieb/lolMiner-releases/files/8008842/log.txt) I don't keep the logs but this is what i could get from the last terminal session. Uptime: 7h 49m 10s Stales are still high. Wired connection, Windows 10 and 472.12 nvidia driver

It is Nvidia... could you try last idea, add that parameter:

set "EXTRAPARAMETERS=--dns-over-https 0"


All problems are in Windows, that's what we have confirmed

**Comment by mohsenk94** [comment]
Just wanted to raise the issue here as well and ask if it's pool related
it apparently is common for a lot of people and it's not pool related
I have 620Mhs/s on Ethermine ETHHash and ~15Gh/s on ton-pool and getting close to 7% stale shares

I am also using Windows so I added the "--dns-over-https 0" command as well
Will update the results in a few hours

**Comment by jgonzis** [comment]
> Just wanted to raise the issue here as well and ask if it's pool related it apparently is common for a lot of people and it's not pool related I have 620Mhs/s on Ethermine ETHHash and ~15Gh/s on ton-pool and getting close to 7% stale shares
> 
> I am also using Windows so I added the "--dns-over-https 0" command as well Will update the results in a few hours

Many thanks... let's see if that helps. 

It is confirmed is with Nvidia and at the moment Ampere GPUs. Someone confirmed 3080ti not affected, but to be confirmed

**Comment by sfiggg** [comment]
confirming the dns parameter did not resolve my stales either. still at 4% after 4 hours on windows 10 with 3080 LHR and 3070 FHR cards driver 472.12

**Comment by jgonzis** [comment]
> confirming the dns parameter did not resolve my stales either. still at 4% after 4 hours on windows 10 with 3080 LHR and 3070 FHR cards driver 472.12

It is possible a last test? Could you run 2 instances? 1 with FHR and the other the LHR?

2 names and let's try to confirm if the LHR is the problem.  

--devices 0 --worker yyy
--devices 1 --worker xxx

**Comment by sfiggg** [comment]
testing now.. will report back

**Comment by sfiggg** [comment]
after 2 hours: 6.09% stales on the 3070 FHR and 2.1% on the 3080 LHR. Neither has an invalid share.

**Comment by miras89** [comment]
Hi, I have to report the same. ETH+TON > stales have skyrocketed on eth from 0.8% to almost 5%.
All cards NVIDIA LHR, flexpool.io, wired connection up to 12ms latence to the pool.
![image](https://user-images.githubusercontent.com/99108328/152666733-cb459dad-b0c6-4a6c-8ade-ae1bcade7537.png)

**Comment by mohsenk94** [comment]
Same here
High amount of Stale shares even after --dns-over-https 0
AND 3080TI also having a lot of stale shares as well

**Comment by jgonzis** [comment]
Many thanks to all for the test. That help a lot... at the moment no one is reporting with Turing that's is great. Could it be the kernel code for Ampere then the problem... the dev has started to work on it...

Meanwhile some pools pay stales so not worries, if it is  not your case, with Linux OS is working great

**Comment by mohsenk94** [comment]
well yeah some pools like Hiveon does pay Stales BUT when you hit +5% stale shares, they suspend your payouts! 
So I highly recommend NOT to use Hiveon at the moment
Regarding switching to Linux, well that would be a lot of work for most users who use Windows,
For me personally I have to use windows because I need to run multiple instances of the same miner at the same time and Hive doesn't allow that.

Appreciate the work, waiting on the update

**Comment by matthewingram** [comment]
> Many thanks to all for the test. That help a lot... at the moment no one is reporting with Turing that's is great. Could it be the kernel code for Ampere then the problem... the dev has started to work on it...
> 
> Meanwhile some pools pay stales so not worries, if it is not your case, with Linux OS is working great

I'm having the issue with this group of cards as well 1660super, 2060 super, 2070, and 2070supers that are in a separate miner.

**Comment by jgonzis** [comment]
> > Many thanks to all for the test. That help a lot... at the moment no one is reporting with Turing that's is great. Could it be the kernel code for Ampere then the problem... the dev has started to work on it...
> > Meanwhile some pools pay stales so not worries, if it is not your case, with Linux OS is working great
> 
> I'm having the issue with this group of cards as well 1660super, 2060 super, 2070, and 2070supers that are in a separate miner.

4-5% too? that will mean all Nvidia are affected then... it has to be something around the extra push it was implemented.

It has to be solved for 1.44 for sure

**Comment by matthewingram** [comment]
> > > Many thanks to all for the test. That help a lot... at the moment no one is reporting with Turing that's is great. Could it be the kernel code for Ampere then the problem... the dev has started to work on it...
> > > Meanwhile some pools pay stales so not worries, if it is not your case, with Linux OS is working great
> > 
> > 
> > I'm having the issue with this group of cards as well 1660super, 2060 super, 2070, and 2070supers that are in a separate miner.
> 
> 4-5% too? that will mean all Nvidia are affected then... it has to be something around the extra push it was implemented.
> 
> It has to be solved for 1.44 for sure

Yes, see my gpu models and the pool stats on flexpool. LOL-DualTon is that rig.
[https://imgur.com/a/JR0ChTH](url)

**Comment by jgonzis** [comment]
> > > > Many thanks to all for the test. That help a lot... at the moment no one is reporting with Turing that's is great. Could it be the kernel code for Ampere then the problem... the dev has started to work on it...
> > > > Meanwhile some pools pay stales so not worries, if it is not your case, with Linux OS is working great
> > > 
> > > 
> > > I'm having the issue with this group of cards as well 1660super, 2060 super, 2070, and 2070supers that are in a separate miner.
> > 
> > 
> > 4-5% too? that will mean all Nvidia are affected then... it has to be something around the extra push it was implemented.
> > It has to be solved for 1.44 for sure
> 
> Yes, see my gpu models and the pool stats on flexpool. LOL-DualTon is that rig. https://imgur.com/a/JR0ChTH

really help full.... it is a complete Nvidia problem

**Comment by jgonzis** [comment]
Just to confirm all test where done with ETH + TON?. Right?

**Comment by matthewingram** [comment]
> Just to confirm all test where done with ETH + TON?. Right?

For me. Yes. ton+eth

**Comment by sfiggg** [comment]
> Just to confirm all test where done with ETH + TON?. Right?

Yes - this occurs for me when dual mining eth + ton. I get stale shares on eth pool but no stale shares on ton pool.

**Comment by mohsenk94** [comment]
Same here
stales just on Eth pool
entire rig is Nvidia as well. and on windows

**Comment by jgonzis** [comment]
We will try an idea tomorrow to see if we are in the right way. In Linux is working perfectly but Windows is our problem now.

**Comment by mohsenk94** [comment]
if there is anything we can do to help, I'm here to do so at all extent.
After everything the mining community thought me over the last year, I owe it to everyone in this industry to do my best to help out.
I have almost all the LHR cards available in the market to do tests on. So let me know if  I can help in anyway

**Comment by thatvinceguy** [comment]
I'm in the same boat.  7 card mixed rig, 6 are nvidia rtx 3000 types and 1 is an amd 6700xt.  Running 1.43 on windows 10. Hash rate is 505mh/10.4Gh, getting about 5% stale eth shares while dualmining ETH/TON.  Pinging the ethermine pool @27ms. No stales on TON I hope they get the issue resolved.

**Comment by Sn0whax** [comment]
Just wanted to confirm the high eth stales on a 3090 as well. Dual and Single mode. ~5% stales on ethermine.

**Comment by jgonzis** [comment]
> Just wanted to confirm the high eth stales on a 3090 as well. Dual and Single mode. ~5% stales on ethermine.

Thx, it is confirmed, new release will solve it. We have an idea where is the problem

**Comment by rodneyoh** [comment]
> > Just wanted to confirm the high eth stales on a 3090 as well. Dual and Single mode. ~5% stales on ethermine.
> 
> Thx, it is confirmed, new release will solve it. We have an idea where is the problem

Is there any way to provisionally solve it?
strange that I noticed from 1 day to here, I didn't have this perception of many stales on Saturday.

**Comment by jgonzis** [comment]
Some of the pools pay the stale normally so it is not a big temporary issue. Next days release will solve it

**Comment by jgonzis** [comment]
![image](https://user-images.githubusercontent.com/38668405/152863388-569666c4-e33e-49d4-bcfa-af3c2c55ef1b.png)
It seems we are on the right way... same machine with the problem of high stales... 
lolminerworker was 1.43 
lolMiner144 new 1.44 beta (soon released)

Thanks every one for the feedbacks and the patient

**Comment by vilemooni** [comment]
This seems to consern also hiveos (linux) and amd polaris cards (rx480, 580, 590 in my rig) lolminer 1.43 ETH+TON. Similar hashrate with nvidiarig with gminer, almost 4x stales compared. Not end of world as still kinda low but difference is noticeable.
![image](https://user-images.githubusercontent.com/87166404/152952691-2a2f3623-e55a-4f3b-a455-f2334511bdc2.png)

**Comment by jgonzis** [comment]
New 1.44 is there with the Nvidia Fix Stales for Windows... enjoy it!!
