### ISSUE TITLE
Fluctuating hash rates on miner start

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#104]
The reported hash rates in the API fluctuate a lot when the miner starts mining, e.g.
0, 0, 1, 2, 4, 4, 4,....

This leads to incorrect benchmark results (too low in this case).

Is there a way to get stable values right from the start?

**Comment by Lolliedieb** [comment]
Which algorithm is this? I will try to make it better - but will not work for all algos ;)

**Comment by UselessGuru** [comment]
I'll have to some more testing. 
I'll do this when 1.18a is available for windows.

**Comment by UselessGuru** [comment]
Just started testing with 1.18a. Reported hashrates in api start with low values and increase steadily.

Affected are
--coin AUTO144_5
--coin AUTO192_7
--coin BTG
--algo BEAM-III
--algo C29AE 
--algo C31
--algo C32 
--algo ETHASH

So it looks like a general issue. I assume you should not use 0 as the starting point for calculating hash rates.
lolMiner is one of the very few showing this behavior.

**Comment by jgonzis** [comment]
Depending on the short stats information, at the moment showing properly information
