### ISSUE TITLE
Dual Mining 30 Series

### ISSUE THREAD

**Issue by thompsontj12** [Lolliedieb/lolMiner-releases#1040]
My 3060 Ti's don't even start Ton mining and my 3070's have a lower hashrate than my 20 series cards.

**Comment by thompsontj12** [comment]
This is on windows I might add

**Comment by Sober13666** [comment]
Try different driver

**Comment by jgonzis** [comment]
> My 3060 Ti's don't even start Ton mining and my 3070's have a lower hashrate than my 20 series cards.

Try 472.12 
PL with MSI Afterburner 100%
add  --cclk paramter
1350 to the 3060TI
1050 to the 3070 

for example 
Remember the --mclk don't work you will lock the GPU in ETH

**Comment by thompsontj12** [comment]
Found the solution. All I needed to do was increase the power limit on the 30 series cards before starting the miner and figure out the lowest power limit % for them to start TON mining.

**Comment by jgonzis** [comment]
> Found the solution. All I needed to do was increase the power limit on the 30 series cards before starting the miner and figure out the lowest power limit % for them to start TON mining.

Thx... I think we haven't put that information well explained. Power Limit can block all

**Comment by thompsontj12** [comment]
@jgonzis I'm also having issues bypassing certain GPUs that I don't want dual mined on Windows... Say I want to bypass GPU 0, does this look correct?

set "EXTRAPARAMETERS=--maxdualimpact 0 --devices 1,2,3,4,5,6,7"

**Comment by jgonzis** [comment]
> @jgonzis I'm also having issues bypassing certain GPUs that I don't want dual mined on Windows... Say I want to bypass GPU 0, does this look correct?
> 
> set "EXTRAPARAMETERS=--maxdualimpact 0 --devices 1,2,3,4,5,6,7"

The bat file of the ZIP is not correctly, use the updated one:

https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

**Comment by thompsontj12** [comment]
I am already using the one you sent me. Does not work. Do my parameters look correct?

**Comment by jgonzis** [comment]
> @jgonzis I'm also having issues bypassing certain GPUs that I don't want dual mined on Windows... Say I want to bypass GPU 0, does this look correct?
> 
> set "EXTRAPARAMETERS=--maxdualimpact 0 --devices 1,2,3,4,5,6,7"

With maxdualimpact 0 you say 0 TON to ALL GPUs. You only need the --devices 1,2,3,4,5,6,7

**Comment by thompsontj12** [comment]
@jgonzis ok even with --maxdualimpact 0 I am still mining Ton on all of my GPU's. I am wanting to skip over a GPU entirely with the --devices parameter but it still mines on it. I don't think it is working.

**Comment by jgonzis** [comment]
> @jgonzis ok even with --maxdualimpact 0 I am still mining Ton on all of my GPU's. I am wanting to skip over a GPU entirely with the --devices parameter but it still mines on it. I don't think it is working.

Very small but a bit... to Skip run lolMiner instances... one with dual mining and other only eth ?

**Comment by thompsontj12** [comment]
@jgonzis Yes... so I don't want to mine on GPU 0 at all... the following command does not work. I took out maxdualimpact to avoid confusion. Do I have the command line wrong?
set "EXTRAPARAMETERS=--devices 1,2,3,4,5,6,7"

**Comment by jgonzis** [comment]
You put it right... Could you check that in your bat if that blue word that I mark to you, if that !EXTRAPARAMETERS! is not there it will never do the selection you correctly do:

![image](https://user-images.githubusercontent.com/38668405/152690088-0f3a7b63-fa17-43fd-8da0-42ba9e4f544f.png)

**Comment by thompsontj12** [comment]
@jgonzis That was it. Thanks
