### ISSUE TITLE
6600 xt shuts down by itself within 1 hour

### ISSUE THREAD

**Issue by bilemedimki** [Lolliedieb/lolMiner-releases#1043]
i have a 6600 xt 

It shuts down by itself 1 hour after running the program.

i am using windows

help me please

ty..

**Comment by jgonzis** [comment]
> i have a 6600 xt
> 
> It shuts down by itself 1 hour after running the program.
> 
> i am using windows
> 
> help me please
> 
> ty..

It could be driver issue... try to make a loop in the bat file to auto restart.

You could also give more Core Voltage, that could be another problem...

**Comment by bilemedimki** [comment]
> try to make a loop in the bat file to auto restart.

how can I do that 

I tried toncoinpool, I did tls on but it crashed there after about 6 hours

Thank you for your help

**Comment by jgonzis** [comment]
> > try to make a loop in the bat file to auto restart.
> 
> how can I do that
> 
> I tried toncoinpool, I did tls on but it crashed there after about 6 hours
> 
> Thank you for your help

If you are using the provided bat file. 
Delete this 3 lines:
If %ERRORLEVEL...
)
Goto END

![Screenshot_20220206-092042_Code Viewer](https://user-images.githubusercontent.com/38668405/152672909-d1ec72ff-367d-4d63-9847-4efe4a231956.jpg)

**Comment by jgonzis** [comment]
Also if you want there is a bat file with a watchdog for Windows in the Guide Windows in the wiki zone
