### ISSUE TITLE
1.43: ETH+TON dual impact ratio is not constant

### ISSUE THREAD

**Issue by Sanchous98** [Lolliedieb/lolMiner-releases#1044]
Eth/ton ratio is not constant. For example, on rtx 3080ti setting --maxdualimpact 0.2 causes 81.5mh/1.6gh ratio in most cases. But sometimes ratio becomes 78mh/2.15gh and can be solved by miner restart. Not a critical bug, but it leads to unpredicatble profit, so would be nice if it will be solved. As I saw, it happens only if --lhrtune is not set, but I'm not sure about it

**Comment by jgonzis** [comment]
> Eth/ton ratio is not constant. For example, on rtx 3080ti setting --maxdualimpact 0.2 causes 81.5mh/1.6gh ratio in most cases. But sometimes ratio becomes 78mh/2.15gh and can be solved by miner restart. Not a critical bug, but it leads to unpredicatble profit, so would be nice if it will be solved. As I saw, it happens only if --lhrtune is not set, but I'm not sure about it

It could be during the tunning moment... have you try it in long term... if after locked it is stable?

**Comment by Sanchous98** [comment]
> > Eth/ton ratio is not constant. For example, on rtx 3080ti setting --maxdualimpact 0.2 causes 81.5mh/1.6gh ratio in most cases. But sometimes ratio becomes 78mh/2.15gh and can be solved by miner restart. Not a critical bug, but it leads to unpredicatble profit, so would be nice if it will be solved. As I saw, it happens only if --lhrtune is not set, but I'm not sure about it
> 
> It could be during the tunning moment... have you try it in long term... if after locked it is stable?

It's constant until restart. It is set up before tuning process and it remains the same until restart. It's not fluctuating during tuning process, but it does between different starts, so I need to restart the miner several times with the same parameters until I get expected eth/ton ratio. I've got 5 * rtx 3080 ti and and if I set the same --maxdualimpact values for all cards they can have different ton hashrate. But after restart it changes like I said before

**Comment by Sanchous98** [comment]
![Screenshot_20220205-211604](https://user-images.githubusercontent.com/45293316/152656105-ed880483-c265-4280-9842-e5ac9e3e9042.jpg)
![Screenshot_20220205-212941](https://user-images.githubusercontent.com/45293316/152656106-a19bbd5f-e395-4d17-b6af-8775587066fc.jpg)
To clarify, look at the 2nd and 3rd card. The difference between screenshots is just a restart. In this case I got lucky and achieved a better result in ton without loss in eth hashrate (3rd card is still tuning and I think it will achieve the same eth hashrate). The 4th card is 580 and I have really changed maxdualimpact for it, so it's not an issue. I think that the issue is in calculating of ton target hashrate for lhr card (I don't now exactly what's the process, but I see that the ton hashrate chosen at the start of tuning remains the same)

**Comment by viper1986** [comment]
I have the same problem for 1660 Super. The Toon hashrate i very random.
![image](https://user-images.githubusercontent.com/19300597/152657782-191d835b-15b8-4739-a9d9-27338820d91d.png)

After couple restart hashrate get stable and almost the same for all cards.

**Comment by jgonzis** [comment]
> > > Eth/ton ratio is not constant. For example, on rtx 3080ti setting --maxdualimpact 0.2 causes 81.5mh/1.6gh ratio in most cases. But sometimes ratio becomes 78mh/2.15gh and can be solved by miner restart. Not a critical bug, but it leads to unpredicatble profit, so would be nice if it will be solved. As I saw, it happens only if --lhrtune is not set, but I'm not sure about it
> > 
> > 
> > It could be during the tunning moment... have you try it in long term... if after locked it is stable?
> 
> It is set up before tuning process and it remains the same until restart. It's not fluctuating during tuning process, but it does between different starts, so I need to restart the miner several times with the same parameters until I get expected eth/ton ratio. I've got 5 * rtx 3080 ti and and if I set the same --maxdualimpact values for all cards they can have different ton hashrate. But after restart it changes like I said before

Remember each change of OC needs a restart... to right calculation.

**Comment by Sanchous98** [comment]
> > > > Eth/ton ratio is not constant. For example, on rtx 3080ti setting --maxdualimpact 0.2 causes 81.5mh/1.6gh ratio in most cases. But sometimes ratio becomes 78mh/2.15gh and can be solved by miner restart. Not a critical bug, but it leads to unpredicatble profit, so would be nice if it will be solved. As I saw, it happens only if --lhrtune is not set, but I'm not sure about it
> > > 
> > > 
> > > It could be during the tunning moment... have you try it in long term... if after locked it is stable?
> > 
> > 
> > It is set up before tuning process and it remains the same until restart. It's not fluctuating during tuning process, but it does between different starts, so I need to restart the miner several times with the same parameters until I get expected eth/ton ratio. I've got 5 * rtx 3080 ti and and if I set the same --maxdualimpact values for all cards they can have different ton hashrate. But after restart it changes like I said before
> 
> Remember each change of OC needs a restart... to right calculation.

Of course, but the fact is that I change nothing. Also I found if I lock core clock --maxdualimpact works wierd: setting 0.4 value changes nothing, values till 0.31 also do nothing, but 0.3 drops ton hashrate to minimum and doesn't change till 0 value. So --maxdualimpact works well only with core clock offset

**Comment by CoastalControls** [comment]
Some problem here. Running a 3090 on Windows 10. Hashrates for Ethereum/Ton are (102/550), (87/1400), (81/1710) for various restarts of the miner with no changes to my OCs or startup batch file. The biggest problem for me is that when it hits on (102/550) my memory overheats.

**Comment by jgonzis** [comment]
> Some problem here. Running a 3090 on Windows 10. Hashrates for Ethereum/Ton are (102/550), (87/1400), (81/1710) for various restarts of the miner with no changes to my OCs or startup batch file. The biggest problem for me is that when it hits on (102/550) my memory overheats.

The problems are:

PL needs to be 100%, more power is need it to dual mining 
2nd Memory Temperature Throlling, check it with GPU-Z
Use Fixed Core 1200 for example: run cmd as administrator an run : nvidia-smi -lgc 1200

Remember each change OC need a restart

**Comment by CoastalControls** [comment]
OK, tried it on my full hashrate 3060ti. This card has no issues with heating, and the power limit is set at 100%. I control the actual power use by fixing the core OC at 1350 MHz. The ratio between Eth/Ton is all over the place. It is effected by the "maxdualimpact" variable, but there is still a huge degree of randomness to the ratio between restarts of the miner.

**Comment by drikhan** [comment]
Same issue happened to me, lhr kept adjusting and jumping on minerstat. 
I solved it by putting the --lhrwait command so it overclocks first before the lhrtuning comes in.
Hope it helps!
