### ISSUE TITLE
Split eth between 2 pools HiveOs

### ISSUE THREAD

**Issue by GTreaper** [Lolliedieb/lolMiner-releases#1047]
Trying to split eth hashrate between two pools, but cant get it to work in hiveos. 
Added --dualmode SPLIT-20 --dualpool eu1.ethermine.org:4444 --dualworker NvidiaRig to extra parameters. How should it be configured?

**Comment by jgonzis** [comment]
> Trying to split eth hashrate between two pools, but cant get it to work in hiveos. Added --dualmode SPLIT-20 --dualpool eu1.ethermine.org:4444 --dualworker NvidiaRig to extra parameters. How should it be configured?

You  should also add the 2nd wallet... 

 --dualmode SPLIT-20.0 --dualpool $DUALPOOL --dualuser $DUALWALLET --dualworker $DUALWORKER

**Comment by GTreaper** [comment]
> > Trying to split eth hashrate between two pools, but cant get it to work in hiveos. Added --dualmode SPLIT-20 --dualpool eu1.ethermine.org:4444 --dualworker NvidiaRig to extra parameters. How should it be configured?
> 
> You should also add the 2nd wallet...
> 
> --dualmode SPLIT-20.0 --dualpool $DUALPOOL --dualuser $DUALWALLET --dualworker $DUALWORKER

Shit im dumb , thought it would grab the def wallet sorry! 
The big question is can it both split and dual mine eth and ton at the same time?
