### ISSUE TITLE
Lolminer dual mining not working on 1080ti

### ISSUE THREAD

**Issue by Egyptianminer** [Lolliedieb/lolMiner-releases#1049]
Hi all am dual mining using lolminer ETH+Ton on all my GPUs and it'sworking fine however for some reason it's nor working on my 1080ti and they are only mining ETH.

Anyone knows a fix for that? Or it just that thise cards do not support dual mining

**Comment by jgonzis** [comment]
Yes pascal at the moment is not implemented!! It is another post with it. I close this one
