### ISSUE TITLE
[C32] Incorrect spelling for "You're"

### ISSUE THREAD

**Issue by platinum4** [Lolliedieb/lolMiner-releases#105]
When trying to use the correct term here it is "You're" for "You are"; I think you have Your

![image](https://user-images.githubusercontent.com/6779241/102452394-e9673e80-3fff-11eb-95fd-ddd27e6130c8.png)

**Comment by Lolliedieb** [comment]
Fixed for 1.18 ... but dang you found the easter egg in my miner xD
