### ISSUE TITLE
1.43: Uneven hashrate distribution ETH+TON 3090 

### ISSUE THREAD

**Issue by LaenorSama** [Lolliedieb/lolMiner-releases#1050]
Uneven hashrate distribution. on one card there can be 107MH ETH / 1.7GH TON, on another card 115MH THE / 400MH TON, on the third card 120MH ETH / 40MH TON. Each time the miner is restarted, the values are different. I use Hive OS, lolMiner 1.43, GPU 3090 MSI.

![photo_2022-02-06_00-09-06](https://user-images.githubusercontent.com/55910514/152655453-e15205c9-522c-4ad6-987f-c76be3af209b.jpg)
![photo_2022-02-06_00-09-13](https://user-images.githubusercontent.com/55910514/152655455-95863c47-8ba0-4bb3-94bf-aaef96d97e3c.jpg)

**Comment by jgonzis** [comment]
Let me give you correct OC:

Core 1200
Memory 2500
PL 0

Your problem as you see is when Watts get the PL then TON don't work... 

You also have Thermal Memory problem in GPU2....  It was also before?.

**Comment by LaenorSama** [comment]
I have also tried such settings

**Comment by jgonzis** [comment]
> I have also tried such settings

Problem is what I said to you... you need to do it and restart miner to see the change... 

Put PL to 0 and rerun miner... 

Also it could be your refrigeration system is not good and you need to reduce from 1200 to 1140 to reduce Watts

**Comment by LaenorSama** [comment]
![image](https://user-images.githubusercontent.com/55910514/152656302-632bafe5-1495-456e-a731-bc5dd4a82865.png)

Thanks for the recommendation. I've done everything. But it didn't help much. A lot of ETH hershate is lost. And the hashrate TON should be higher judging by the table.

**Comment by LaenorSama** [comment]
![image](https://user-images.githubusercontent.com/55910514/152656751-b2de45fa-148d-4353-abf9-b2245e063969.png)

updated the graphics card driver and restarted the miner

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/55910514/152656751-b2de45fa-148d-4353-abf9-b2245e063969.png)
> 
> updated the graphics card driver and restarted the miner

You are having Thermal Throlling with GPU2 and GPU3... when you solve that you will be able to get max performance... 

You could also try to reduce Core to see if you generate less Heat... You could check that is Memory Problem, with a hive Shell you could run this parameter... and you will see ACTIVE word ... that is Memory Throlling:

nvidia-smi -q -d PERFORMANCE | grep "SW Power Cap"

**Comment by viper1986** [comment]
I have the same problem for 1660 Super. The Toon hashrate i very random.
![image](https://user-images.githubusercontent.com/19300597/152657782-191d835b-15b8-4739-a9d9-27338820d91d.png)

After couple restart hashrate get stable and almost the same for all cards.

**Comment by jgonzis** [comment]
> I have the same problem for 1660 Super. The Toon hashrate is very random. ![image](https://user-images.githubusercontent.com/19300597/152657782-191d835b-15b8-4739-a9d9-27338820d91d.png)
> 
> After couple restart hashrate get stable and almost the same for all cards.

Remember jobs of tons are put in small gaps of eth... so depending could go up and down but the photo seems quite good of your final result. If you want more TON hashrate increase Core... and remember to restart miner

**Comment by viper1986** [comment]
Yes, there are quite good but after couple of restart miner.
![image](https://user-images.githubusercontent.com/19300597/152671651-410101b7-df6b-443a-acbf-2465a1b4e405.png)

It's hard to predict the speed at which the program will start. Which is why it's hard to estimate the profit.
If the hashrate was the same or slightly different it would not be a problem.

**Comment by LaenorSama** [comment]
after several reboots, the situation has stabilized. 
I also switched to ton-pool just in case
