### ISSUE TITLE
ETH + TON 6900XT Crashes

### ISSUE THREAD

**Issue by Sinyk7** [Lolliedieb/lolMiner-releases#1051]
![image](https://user-images.githubusercontent.com/6602468/152655786-0df22027-4410-4b52-993f-b66ce7f1db30.png)

This has happened a couple times to my 6900XT system now. It will mine for a couple hours, then the miner crashes. It also won't start up again if i open it right away. I'm using the 21.10.2 AMD Driver.

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/6602468/152655786-0df22027-4410-4b52-993f-b66ce7f1db30.png)
> 
> This has happened a couple times to my 6900XT system now. It will mine for a couple hours, then the miner crashes. It also won't start up again if i open it right away. I'm using the 21.10.2 AMD Driver.

That could be driver ... or to much OC in the 6900XT... 

Could you put a safer OC?

**Comment by Sinyk7** [comment]
I upgraded to the latest drivers AMD had 22.2.1 and dropped my OC 200 MHz on the core. Now this is happening:

![image](https://user-images.githubusercontent.com/6602468/152656365-3d24edcc-a7d6-4b7b-969c-aabe29689761.png)

No error, but it says press any key to continue. If you do, the program crashes.

**Comment by Ralph416** [comment]
Exact same issue. Get the exception thrown right after "HTTPS resolve succeeded". So it's not just me. Also using 6900XTs and 6800XTs. Primary ETH to nicehash. Secondary TON to whalestonpool.

**Comment by jgonzis** [comment]
> Reference in new is

Share the OC... In Mining OS (HiveOS, MMPOS, RAVEOS) all are working great, so it could be driver from windows is not working properly... 

Could you try to change the pool to 

wss://pplns.toncoinpool.io/stratum

To see if that works?.

Many thanks!

**Comment by Sinyk7** [comment]
I have a 3070 in HiveOS with a 5600X triple mining ETH + TON on lolMiner and RTM with XMRig and so far it's running solid. 
My other system is a 6900XT with a 5900XT in Win10 triple mining as well.

I changed the pool and so far it's working. I notice that compared to Whalestonpool i am sent new jobs way less frequently.

![image](https://user-images.githubusercontent.com/6602468/152657352-c449812d-18d3-4762-9ee9-d2448b05a66b.png)

As for the OC:

![image](https://user-images.githubusercontent.com/6602468/152657439-b92879e0-6ee6-41ca-92aa-2cb16d32f79c.png)

**Comment by jgonzis** [comment]
Try other Pool please:
Servers:
toncoinpool.io: wss://pplns.toncoinpool.io/stratum
ton-pool.com: https://next.ton-pool.com
icemining.ca  ton.hashrate.to:4003

**Comment by jgonzis** [comment]
> I have a 3070 in HiveOS with a 5600X triple mining ETH + TON on lolMiner and RTM with XMRig and so far it's running solid. My other system is a 6900XT with a 5900XT in Win10 triple mining as well.
> 
> I changed the pool and so far it's working. I notice that compared to Whalestonpool i am sent new jobs way less frequently.
> 
> ![image](https://user-images.githubusercontent.com/6602468/152657352-c449812d-18d3-4762-9ee9-d2448b05a66b.png)
> 
> As for the OC:
> 
> ![image](https://user-images.githubusercontent.com/6602468/152657439-b92879e0-6ee6-41ca-92aa-2cb16d32f79c.png)

that confirms the tonwhales server problem... 

Many thanks for the information and the tries... don't worry about the jobs profit is similar to all pools

**Comment by Ralph416** [comment]
That appears to be it. Switching to toncoinpool.io solved the exception being thrown. There does seem to be something wrong with the way it's calculating the local hashrate though. If I run at 1100MHz for a example just for a few seconds then switch to 1600 it never updates to new hashrate even minutes later. I have to restart the miner then it shows correct rate immediately.

**Comment by jgonzis** [comment]
> That appears to be it. Switching to toncoinpool.io solved the exception being thrown. There does seem to be something wrong with the way it's calculating the local hashrate though. If I run at 1100MHz for a example just for a few seconds then switch to 1600 it never updates to new hashrate even minutes later. I have to restart the miner then it shows correct rate immediately.

Yes... each change of OC needs to restart miner.... to correctly calculations.

Confirmed tonwhales.com not working properly for Cloudflare problems

**Comment by queinnec35** [comment]
same problem here with random crash during 24h of OC test, windows , hiveos, driver and more ... i think it s whaleston pool the problem , i go create a new account pool and i come back tomorrow

**Comment by coofcookie** [comment]
Similar issue with whaleston pool

**Comment by jgonzis** [comment]
> Similar issue with ton whales pool

Yes yes please avoid it until solve it... the other 2 pools are great or better...

**Comment by telethrasher** [comment]
sorry to be an idiot but when i go to toncoinpool.io and try to find the mining address it just sends me to ton stratum miner which is not what i'm looking for - 
can someone give me a hand finding the darn mining address ?
thx

**Comment by jgonzis** [comment]
> sorry to be an idiot but when i go to toncoinpool.io and try to find the mining address it just sends me to ton stratum miner which is not what i'm looking for - can someone give me a hand finding the darn mining address ? thx

wss://pplns.toncoinpool.io/stratum
