### ISSUE TITLE
Hashrate Drop Then Smart DAG Repair

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1052]
I tried on multiple rigs FHR and LHR, for some reason while mining suddenly some gpus goes to zero MH/S and then smart repair starts working every now and then to get one of the gpus to normal hashing level.

![image](https://user-images.githubusercontent.com/49044292/152656770-9a01a4ca-ccc6-4e91-ba63-ea7a75943921.png)

**Comment by jgonzis** [comment]
> I tried on multiple rigs FHR and LHR, for some reason while mining suddenly some gpus goes to zero MH/S and then smart repair starts working every now and then to get one of the gpus to normal hashing level.
> 
> ![image](https://user-images.githubusercontent.com/49044292/152656770-9a01a4ca-ccc6-4e91-ba63-ea7a75943921.png)

That pass only at start... that means you put a very high Memory OC on GPU0... and you need to wait to be repair to reduce HArdware Share

**Comment by Vinasis01** [comment]
I waited till all the repair was done, then it happened after an hour or so.
I am using safe OC for my gpus and been running them for months on those numbers and no issues appeared, will restart the rig and monitor more 
When I start the miner I get this message

![image](https://user-images.githubusercontent.com/49044292/152657086-0b9cc800-32b3-4112-9aad-fe494ca27e6a.png)

**Comment by Vinasis01** [comment]
it got closed...
