### ISSUE TITLE
Shared acepted

### ISSUE THREAD

**Issue by cajaritohh** [Lolliedieb/lolMiner-releases#1054]
I am mining ethereum with lolminer 1.42 through hiveos with an rx 570 8gb, but in the miner it says that I have eg 472 accepted shares and I go to the ethermine pool and the accepted shares are less eg 23. Why is it not reflected the same amount that the miner says, but in the pool it is not the same amount?

**Comment by jgonzis** [comment]
> I am mining ethereum with lolminer 1.42 through hiveos with an rx 570 8gb, but in the miner it says that I have eg 472 accepted shares and I go to the ethermine pool and the accepted shares are less eg 23. Why is it not reflected the same amount that the miner says, but in the pool it is not the same amount?

472 during the start... Ethermine show less time !! not from start

**Comment by cajaritohh** [comment]
Not to.  Principle, it is what accumulated after mining for several hours, I get a number of shares accepted by the miner lolminer which is now 1.43, but if one checks what is accumulated from shared accepted in lolminer vs ethermine the shares do not match.

**Comment by jgonzis** [comment]
> Not to. Principle, it is what accumulated after mining for several hours, I get a number of shares accepted by the miner lolminer which is now 1.43, but if one checks what is accumulated from shared accepted in lolminer vs ethermine the shares do not match.

I told you... ethermine Don't do full 24hours stats shares... check it with flexpool.io and you will see it please
