### ISSUE TITLE
FHR GPU treated as LHR

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1055]
Randomly a gpu gets treated as LHR in a FHR rig of 3070 GPUS

In this case it's gpu #10, in a previous run of the miner another gpu was dealt with the same way

![image](https://user-images.githubusercontent.com/49044292/152657920-064545c1-5da6-4984-bf09-7fd22886d4d5.png)

**Comment by jgonzis** [comment]
> Randomly a gpu gets treated as LHR in a FHR rig of 3070 GPUS
> 
> In this case it's gpu #10, in a previous run of the miner another gpu was dealt with the same way
> 
> ![image](https://user-images.githubusercontent.com/49044292/152657920-064545c1-5da6-4984-bf09-7fd22886d4d5.png)

that normally happens because it touch Power Limit...  (Put it to 0 in HiveOS or 100% in Windows)

you can also use parameter: --lhrtune off,off,off,.... and it will not happen :-)
