### ISSUE TITLE
No GPUs detected in lolminer

### ISSUE THREAD

**Issue by melaneej** [Lolliedieb/lolMiner-releases#1056]
I am converting my miner to ubuntu os and lolminer now will not detect my GPUs - 3 AMD Radeon RX 5700 XTs.  Was previously mining successfully in Windows with lolminer.   I have installed all updated drivers for the cards.  Cards are detected on the system, just not when launching lolminer.

error happens right after setup miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 0

Any help would be greatly appreciated.

**Comment by jgonzis** [comment]
> I am converting my miner to ubuntu os and lolminer now will not detect my GPUs - 3 AMD Radeon RX 5700 XTs. Was previously mining successfully in Windows with lolminer. I have installed all updated drivers for the cards. Cards are detected on the system, just not when launching lolminer.
> 
> error happens right after setup miner... OpenCL driver detected. Number of OpenCL supported GPUs: 0
> 
> Any help would be greatly appreciated.

". I have installed all updated drivers for the cards" That is the problem, probably last drivers are not compatible and need to do an update in all the code for that.
