### ISSUE TITLE
Defect Segments

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1057]
Middle of mining suddenly defect segments happen and the hashrate drops from about 780 mh/s on eth to like 40 or 50 mh/s and it starts trying to repair each dag for each gpu for 15 minutes or so

![image](https://user-images.githubusercontent.com/49044292/152659860-1b9f605b-2abe-4c9c-a1b7-c0ce42db46a5.png)

**Comment by mohsenk94** [comment]
I also get this on some of my cards, (Also got this issue on NBMiner a few months back when I was using it on some of my cards) 
It seems to be because of overclock settings, most likely high memory clock.
for me, It just fixes it in like 2-5 minutes and keeps on mining with no issues.
but if you waited 15 minutes and it's still not done , maybe try this command?
--disable-dag-verify 1

and see how it works

**Comment by Vinasis01** [comment]
It's going faster now with the smart repair by half, does this line seem written well? the gpus are full hashrate but sometimes I get semi lhr unlock and another member recommended i use the lhrtune off command

![image](https://user-images.githubusercontent.com/49044292/152661372-6957beb3-4658-45f4-a513-ad360f4f7e82.png)

**Comment by mohsenk94** [comment]
OK so it's still taking a long while then... yeah probably better try to disable dag verification
yeah the command seems good. 
I believe you can also just use "--lhrtune off" instead of using 13 off s , Or at least it's how it works on T-rex :D it might work here as well

**Comment by Vinasis01** [comment]
/sigh it happened again, if every 30-40 minutes this happens and takes 10-20 minutes to get fixed it means something is not right, this is not happening to my other rigs which have similar gpus...

![image](https://user-images.githubusercontent.com/49044292/152662292-65c55a19-ec5b-4171-8211-2d321cdad9f5.png)

**Comment by jgonzis** [comment]
> /sigh it happened again, if every 30-40 minutes this happens and takes 10-20 minutes to get fixed it means something is not right, this is not happening to my other rigs which have similar gpus...
> 
> ![image](https://user-images.githubusercontent.com/49044292/152662292-65c55a19-ec5b-4171-8211-2d321cdad9f5.png)

That is an advise that you are pushing to high the Memory, lolMiner will repair it for you, but take care about it, because it can continue the degratation, not all memories are able to go super high and if they go they degrate faster.
