### ISSUE TITLE
Miner fails

### ISSUE THREAD

**Issue by Leozolt** [Lolliedieb/lolMiner-releases#1058]
Using 1.43 on Ubuntu 24

got this kind of program exits...

GPU 2: Share accepted (16 ms) 
New job received: 0x77cadf Epoch: 471 Difficulty: 10.00G 
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
free(): double free detected in tcache 2
./dual_mine_eth_ton.sh: line 20: 1482708 Aborted                 (core dumped) ./lolMiner --devices 1,2 --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker $ETHWORKER $@

free(): double free detected in tcache 2  ...  ?

Any Idea?

**Comment by coofcookie** [comment]
Same issue

**Comment by Wables** [comment]
```https://server1.whalestonpool.com: Address is registered
free(): double free detected in tcache 2

lolminer exited (exitcode=0), waiting to cooldown a bit
```

same issue with hive os with lhr 3060ti's dual mining ton and eth

**Comment by Wables** [comment]
> Using 1.43 on Ubuntu 24
> 
> got this kind of program exits...
> 
> GPU 2: Share accepted (16 ms) New job received: 0x77cadf Epoch: 471 Difficulty: 10.00G https://server1.whalestonpool.com: Address is valid https://server1.whalestonpool.com: Address is registered free(): double free detected in tcache 2 ./dual_mine_eth_ton.sh: line 20: 1482708 Aborted (core dumped) ./lolMiner --devices 1,2 --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker $ETHWORKER $@
> 
> free(): double free detected in tcache 2 ... ?
> 
> Any Idea?

try using "next.ton-pool.com" as your pool instead, fixed it for me
https://ton-pool.com/ is the website

**Comment by jgonzis** [comment]
Yes it was... new 1.44 should help on that. 

Also a new mining pool (icemining.ca) is added that should help in that pool problems
