### ISSUE TITLE
Miner restarting without error

### ISSUE THREAD

**Issue by itsjcrane** [Lolliedieb/lolMiner-releases#1061]
1.43 is restarting without any errors.  This occurs in both HiveOS (no error displayed) and also happens in windows (mining halts and just displays message "press any key to continue" and closes if you press a key).  This is occurring on both AMD and Nvidia rigs at 2 different physical locations.  I originally had them all running for 20 hours of so without issue.  Now they will just randomly restart the miner after just a few minutes to an hour.  LA also seems to spike a bit from time to time.  Plenty of power overhead on all rigs and using locked core clocks on all GPUs.

**Comment by Tylon-ldd** [comment]
My miners restart about every 1 hour.

**Comment by sebek72** [comment]
Looks familiar (from older miner versions). Probably related to some ton pool issues. Working for days and then suddenly crashing. Am seeing this also today. Yesterday it was fine.

**Comment by allpaspartou** [comment]
Having the same issue! Dual miner not working right! After some minutes it says " press enter to continue" and it restarts! Thats on Windows 10. Using betterhash pool for ethereum (months now with no problem at all) and whales pool for ton coin! Which pools are you using???

**Comment by sebek72** [comment]
I think it is a whalespool issue

**Comment by itsjcrane** [comment]
> 

I am using whaleston pool.  how can we prevent the blocking/ban?  searching reddit now.  seems familiar

**Comment by coofcookie** [comment]
Same issue, i am on whaleston pool

**Comment by itsjcrane** [comment]
I can't find any support for their pool.  i hate leaving all this extra profit potential on the table

**Comment by vkokosike** [comment]
yes, it's because of the pool. just change the TON pool

**Comment by itsjcrane** [comment]
> yes, it's because of the pool. just change the TON pool

Changed a little over an hour ago.  All good so far.

**Comment by Subyzero** [comment]
Mine restarting at around 4 h. i have look to the error log , is like the miner don't receive anymore ETH shares at beggining. Now i can't see how much time the miner stays offline, but he is restarting alone.
![image](https://user-images.githubusercontent.com/99119517/152675592-d9ff5849-9799-46bf-94bd-109244e1dcc4.png)

**Comment by jgonzis** [comment]
> Mine restarting at around 4 h. i have look to the error log , is like the miner don't receive anymore ETH shares at beggining. Now i can't see how much time the miner stays offline, but he is restarting alone. ![image](https://user-images.githubusercontent.com/99119517/152675592-d9ff5849-9799-46bf-94bd-109244e1dcc4.png)

It is all said before... don't use tonwhales pool.... lot of other working option!!!

**Comment by jgonzis** [comment]
All that should be solved and improved with 1.44, also added a new mining pool icemining.ca
