### ISSUE TITLE
TON+ETH:  Too many attempts.  Switching to failover pool

### ISSUE THREAD

**Issue by chrishilbert** [Lolliedieb/lolMiner-releases#1062]
ETH+TON throwing lots of this error today:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2332975/152661459-21f1deb1-e013-43a4-8961-3e730dd6cdbf.png">

**Comment by Tylon-ldd** [comment]
Same issue.

**Comment by pyrexjis** [comment]
Same issue.

**Comment by empereurfn** [comment]
Same issue here on windows with 2miners eth pool and tonwhales

**Comment by coofcookie** [comment]
Same issue

**Comment by chrishilbert** [comment]
Issue appears related to the pool.  Switched to ton-pool and humming right along again.

**Comment by delideha** [comment]
same

**Comment by jgonzis** [comment]
> ETH+TON throwing lots of this error today:
> 
> <img alt="image" width="815" src="https://user-images.githubusercontent.com/2332975/152661459-21f1deb1-e013-43a4-8961-3e730dd6cdbf.png">

Please don't use tonwhales at the moment with Windows 



> same

Said several times don't use tonwhales at the moment...

**Comment by chrishilbert** [comment]
Had a crash overnight with ton-pool.  Seems the dual mining is unstable at the moment, regardless of pool.

**Comment by vandark25** [comment]
add manually --ton-mode 1 on settings section

**Comment by jgonzis** [comment]
Release 1.44 should solve lot of the connection... https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44
