### ISSUE TITLE
Low hashrate on RTX 3080 FE dual mining ETH+TON

### ISSUE THREAD

**Issue by maxouille** [Lolliedieb/lolMiner-releases#1063]
Hi, 

I managed to get 1.6GH/s on Whalespool before it crashes. I switched to TON Pool but my 3080 does not seems to ramp up. 

I'm stuck at 220W with -100 Core ; +900 Mem, No PL. On WhalesPool, it ramped up to 1.6GH/s but here i'm stuck at 300MH/s. 

![2022-02-05 23_51_46-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/5927407/152661614-ab332a54-8ef2-4c55-a3f1-80e9811731d1.png)

![gpu](https://user-images.githubusercontent.com/5927407/152661639-4d500c35-48c6-4f81-ba02-36e975214e89.gif)

I don't know if it's thermal Throttling or something else. I had the same temps on Whalespool while getting 1.6GH/s. 

Any ideas ?

**Comment by HeraklesTR** [comment]
you are termal throttling, your memory temp is wooping 108 celcius. you need termal ped replacement asap or your card may die.

**Comment by maxouille** [comment]
> you are termal throttling, your memory temp is wooping 108 celcius. you need termal ped replacement asap or your card may die.

It's weird that it worked for more than an hour and now it's locked due to thermal throttling. Does not make any sense. Also, dropping from 1.6GH/s to 300MH/s is hardcore don't you think ?

**Comment by telethrasher** [comment]
100% FAN or the card will DIE

**Comment by maxouille** [comment]
I'm gonna repaste/repad some day. But that's weird anyway. 

Even when the card is cold, I can have some times when TON hashrate is at 0.

**Comment by jgonzis** [comment]
As the other collegue said Memory 108C... and FAN only 59C

Please use Fixed Core Always for example 1200
PL to 100% (it will be controlled by the Fixed Core)
And give a try to the new 1.44
