### ISSUE TITLE
Ton pool connection mode:... On every 10 seconds..

### ISSUE THREAD

**Issue by pyrexjis** [Lolliedieb/lolMiner-releases#1065]
on eth-ton dualmode On every 10 seconds i'm getting this.. in about 25-30 mins miner crashes and restarts...
![Ekran görüntüsü 2022-02-06 023217](https://user-images.githubusercontent.com/98655590/152662546-e7c302e9-8c6e-4567-95af-f7833e70e4ed.png)
It worked perfectly yesterday.. doing this for 3-4 hours...
![Ekran görüntüsü 2022-02-06 024110](https://user-images.githubusercontent.com/98655590/152662683-548153be-3988-4026-bb9e-0394b9cc0e6b.png)

**Comment by jgonzis** [comment]
> on eth-ton dualmode On every 10 seconds i'm getting this.. in about 25-30 mins miner crashes and restarts... ![Ekran görüntüsü 2022-02-06 023217](https://user-images.githubusercontent.com/98655590/152662546-e7c302e9-8c6e-4567-95af-f7833e70e4ed.png) It worked perfectly yesterday.. doing this for 3-4 hours... ![Ekran görüntüsü 2022-02-06 024110](https://user-images.githubusercontent.com/98655590/152662683-548153be-3988-4026-bb9e-0394b9cc0e6b.png)

Yes... tonwhales pool are not working properly. Use ton-pool.com or toncoinpool.io 

That are going lot better for now.
