### ISSUE TITLE
Dual Mining LHR Issues

### ISSUE THREAD

**Issue by thompsontj12** [Lolliedieb/lolMiner-releases#1067]
I am having an issue with a 3060 Ti LHR that will not find it's "sweet spot" while dual mining Eth + TON. Any suggestions? It just keeps reducing the lhrtune parameters. Went to -500 earlier today and was still locking up. Mining in Windows.

**Comment by thompsontj12** [comment]
Mining in Windows

**Comment by calvinIsAwesome** [comment]
In HiveOS, lock the core clock to 1440, memory clock 2200, power limit 160 will get you 44.x in ETH and 1.1xx in TON. After changing this parameters, restart the miner to see the changes. Best regards.

**Comment by telethrasher** [comment]
trying to simulate your settings in windows... does hive lock the clock at 2200 or is that a mem clock boost of 2200 ?
thx

**Comment by jgonzis** [comment]
Try new lolMiner 1.44, it should solve some of the problems... https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44
