### ISSUE TITLE
no EXTRAPARAMETRES detecte in windows for select devices

### ISSUE THREAD

**Issue by malagacripto** [Lolliedieb/lolMiner-releases#1068]
https://prnt.sc/26peeg9
When I try to add the parameter to select the gpu to do dual mining, it does not detect it and it does the mining with all the gpus at the same time, does anyone know how to solve that error?

**Comment by telethrasher** [comment]
i had to add the "  !EXTRAPARAMETERS!  " comment to both lines at the bottom of the dual_mine_eth_ton.bat file...

the two lines should look like this :

:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog exit !EXTRAPARAMETERS!

:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor

**Comment by nameless314** [comment]
They have the correct batch file outside the the zip file if you don't want to tweak.https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

**Comment by bilemedimki** [comment]
https://www.youtube.com/watch?v=bcHGpl3Y9_U
3:20

**Comment by malagacripto** [comment]
> They have the correct batch file outside the the zip file if you don't want to tweak.https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

thanks!!!!

**Comment by jgonzis** [comment]
Please use new 1.44 that also includes the new working bat files and a new mining pool too
