### ISSUE TITLE
Dual Eth/Ton miner not working

### ISSUE THREAD

**Issue by Chaos0794** [Lolliedieb/lolMiner-releases#1070]
![image](https://user-images.githubusercontent.com/99105353/152664638-cff6db4b-bbae-4256-af30-3f24f0c98462.png)
Hey all, just installed lolminer on windows for the first time to try the dual eth/ton mining, and it keeps just stopping and saying press any key to continue. Any ideas?

**Comment by telethrasher** [comment]
several things - in other comments there have been issues with TonWhales so everyone jumped to TonCoinPool
the other issue i found was that there was no !EXTRAPARAMETERS! call in the two lines at the bottom after --watchdog exit
hope it helps

**Comment by jgonzis** [comment]
New release 1.44 solved the tonwhales problems and add new pool icemining.ca
Also dual mining files come yet with the EXTRAPARAMETERS right now
