### ISSUE TITLE
Not sure why lolminer not running? 

### ISSUE THREAD

**Issue by lucb4719** [Lolliedieb/lolMiner-releases#1071]
Trying to set up ETH-TON dual miner and I'm running into this issues. Any suggestions to get this running?

![Capture](https://user-images.githubusercontent.com/99105861/152665088-b06f9899-f899-4070-aa62-db936de5a60f.PNG)

**Comment by jgonzis** [comment]
> Trying to set up ETH-TON dual miner and I'm running into this issues. Any suggestions to get this running?
> 
> ![Capture](https://user-images.githubusercontent.com/99105861/152665088-b06f9899-f899-4070-aa62-db936de5a60f.PNG)

PRoblem is TONWHALES.com... 

don't use that pool. Use toncoinpool.io or ton-pool.com and all will work :-)
