### ISSUE TITLE
v1.42 perfect TON mining NOW crashing after a few seconds with v1.43

### ISSUE THREAD

**Issue by GYKrauss** [Lolliedieb/lolMiner-releases#1074]
v1.43 crashes after a few seconds with same tonwhales address and settings. 3080ti. Obviously, the dual mining is crashing as well.

**Comment by Lumi412** [comment]
yup...same here.  my system was dual mining ETH+TON for about 8 hours yesterday with no issues.  then all of the sudden it crashed and ever sonce lasy night I cannot get the mioner to startup and run without crashing after about 5 seconds.  very odd....   :(

**Comment by telethrasher** [comment]
mine crashed on Whale Pool but not TonCoinPool
