### ISSUE TITLE
low hashrate on CMP 170HX card with error fan speed

### ISSUE THREAD

**Issue by calvinIsAwesome** [Lolliedieb/lolMiner-releases#1075]
With the power limit set to 200W, this card should get around 160MH/s. However lolminer only reports like 152MH/s, which is significantly lower than other mining softwares. Another issue is the incorrect fan speed. Since this card does not have a built-in cooling fan, the number show on the state should not be 100%. I do hope the developers may resolve this problem one day. Thank you!

**Comment by jgonzis** [comment]
> With the power limit set to 200W, this card should get around 160MH/s. However lolminer only reports like 152MH/s, which is significantly lower than other mining softwares. Another issue is the incorrect fan speed. Since this card does not have a built-in cooling fan, the number show on the state should not be 100%. I do hope the developers may resolve this problem one day. Thank you!

I recommend you to have a read on the review of the miners... You are having the best perfomance. Problem of your comparative is that other miners inflate hashrate. LolMiner doesn't do it... 

check that review at: [Review 1.000.000 Shares](https://www.hashrate.no/tests/ampere)

There you will understand that not all miners are honest with the reported Hashrate.

**Comment by bhoolat** [comment]
Having an issue with these cards where only some are mining TON and others say N/A. With the ones that do mine have varying hashrate from 79MH/s to 314 MH/s. However they are working perfectly fine on ETH with 160MH/s on all cards.

**Comment by jgonzis** [comment]
> Having an issue with these cards where only some are mining TON and others say N/A. With the ones that do mine have varying hashrate from 79MH/s to 314 MH/s. However they are working perfectly fine on ETH with 160MH/s on all cards.

Try to play with Fixed Core and no Limit Core... if you don't do you will not be able to get nice profit.

Also some user in the Telegram group --maxdualimpact 4 helped him to reduce a bit ETH but maximize TON . 

Fixed Core at 1400
PL to 0
