### ISSUE TITLE
6800 rig was working, now crashing

### ISSUE THREAD

**Issue by Lumi412** [Lolliedieb/lolMiner-releases#1076]
My RX 6800 rig was mining ETH+TON all day yesterday fine and dandy. Then all of the sudden last night around 10 PM my system crashed. Now when I tried to dual mine, it loads up the miner, builds the DAG, then it starts mining for about 2–5 seconds and then Lolminer crashes. 

Any clue how to fix this? 

Thank you

**Comment by telethrasher** [comment]
mine is constantly crashing on TonWhale pool but not TonCoinPool

**Comment by bilemedimki** [comment]
> mine is constantly crashing on TonWhale pool but not TonCoinPool

crashing there . the program is faulty

**Comment by Ham2022ed** [comment]
my 3060 ti crashes on dual mining too "ton+eth"

**Comment by jgonzis** [comment]
> my 3060 ti crashes on dual mining too "ton+eth"

The answer is before!!! DON'T USE TONWHALES... use ton-pool.com or toncoinpool.io that's all :-)
