### ISSUE TITLE
lolminer 1.43 dual mining Crash

### ISSUE THREAD

**Issue by pabloguns** [Lolliedieb/lolMiner-releases#1078]
### Discussed in https://github.com/Lolliedieb/lolMiner-releases/discussions/1077

<div type='discussions-op-text'>

<sup>Originally posted by **pabloguns** February  5, 2022</sup>
![toncoinerror](https://user-images.githubusercontent.com/99106102/152665732-da57140d-1c36-470c-828b-503ccc46370e.jpg)

Hello, could someone help me please. It kept running for a few hours and then it gave me this error.
The rig is made up of 2 rtx3060v1 + 2 6700xt. Thanks a lot</div>

**Comment by bhaveshp902** [comment]
Mine 3060v1 is also creating after every 2 hours

**Comment by telethrasher** [comment]
mine crashed in the same way constantly on TonWhales, i switched to TonCoinPool all ok now

**Comment by rotor33** [comment]
I got this error too win10

**Comment by Ham2022ed** [comment]
after a while it stops mining 
says: "press any key ................."

**Comment by queinnec35** [comment]
change for ton-pool
