### ISSUE TITLE
lol1.43, only eth fine. only ton fine. dual issue

### ISSUE THREAD

**Issue by imageyx** [Lolliedieb/lolMiner-releases#1080]
![image](https://user-images.githubusercontent.com/99107569/152666321-4891e84e-3c95-4d3e-be34-cfdf489c9e9e.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/99107569/152666321-4891e84e-3c95-4d3e-be34-cfdf489c9e9e.png)

Don't use TONWHALES!!!!

use ton-pool.com or toncoinpool.io that's all :-)
