### ISSUE TITLE
Trying to use split in windows --worker cannot be specified more than once 

### ISSUE THREAD

**Issue by GTreaper** [Lolliedieb/lolMiner-releases#1081]
trying to launch split eth in windows gives me this message.. using the bat that was in the zip, only changed wallet. Tried with a fresh orig bat same thing option '--worker' cannot be specified more than once
Press any key to continue . . .

**Comment by jgonzis** [comment]
> trying to launch split eth in windows gives me this message.. using the bat that was in the zip, only changed wallet. Tried with a fresh orig bat same thing option '--worker' cannot be specified more than once Press any key to continue . . .

which bat file are you using... please always more information... it is impossible without your config to help you...

**Comment by GTreaper** [comment]
Like I wrote, I tried with a fresh original bat file that was in the zip folder. I tried using it without changing anything. Didn't change wallets or pool just started it as it is when downloading the zip

**Comment by jgonzis** [comment]
> Like I wrote, I tried with a fresh original bat file that was in the zip folder. I tried using it without changing anything. Didn't change wallets or pool just started it as it is when downloading the zip

Thx it is not correct the --worker of the line should be --dualworker change it to work
 
![Screenshot_20220206-144727_Code Viewer](https://user-images.githubusercontent.com/38668405/152683925-0bb19af0-4ab3-4cd7-8ad4-132d7e476154.jpg)
