### ISSUE TITLE
Crashing and showing this while starting or after a while.

### ISSUE THREAD

**Issue by bhaveshp902** [Lolliedieb/lolMiner-releases#1083]
![Uploading IMG_20220206_095012.jpg…]()

**Comment by bhaveshp902** [comment]
![IMG_20220206_095012](https://user-images.githubusercontent.com/43637866/152667693-9035168c-63f4-43a5-864a-6b2c864064fc.jpg)

**Comment by vonchilli** [comment]
issue with tonwhalepool on windows, switching to 'wss://pplns.toncoinpool.io/stratum' fixed the issue for me

**Comment by NOnooSS** [comment]
Switch on ton-pool works also

**Comment by jgonzis** [comment]
New Release 1.44 should solve that problems. Also a new pool added icemining.ca
