### ISSUE TITLE
Lol miner 1.43 constantly crashing HiveOS

### ISSUE THREAD

**Issue by JeremyvanCampen** [Lolliedieb/lolMiner-releases#1086]
Every 10 minutes lol miner throws the error free(): double free detected in tcache 2  in the logs which makes the rig reboot. Using dual mining mode in version 1.43, it was working perfectly all day yesterday and with no change this has been the situation for a full day now. I tried lowering all OC's and even removing entire OC's.

Using 3060 TI, 2060 and 1660 TI. I also have a full 5700XT rig which has been working flawlessly. Looks like a issue on the nvidia side for me atleast.

**Comment by jgonzis** [comment]
> Every 10 minutes lol miner throws the error free(): double free detected in tcache 2 in the logs which makes the rig reboot. Using dual mining mode in version 1.43, it was working perfectly all day yesterday and with no change this has been the situation for a full day now. I tried lowering all OC's and even removing entire OC's.
> 
> Using 3060 TI, 2060 and 1660 TI. I also have a full 5700XT rig which has been working flawlessly. Looks like a issue on the nvidia side for me atleast.

Which pool are you using?

if it is tomwhales that's normal... it is buggy pool... 

Use ton-pool or toncoinpool.io

**Comment by JeremyvanCampen** [comment]
I'm using tonwhales right now. I'll switch over and see if the problem is resolved.

**Comment by JeremyvanCampen** [comment]
Seems switching away from tonwhales resolved my issue. I'd recommend doing this to everyone having the same issues. Currently on ton-pool.

**Comment by jgonzis** [comment]
> Seems switching away from tonwhales resolved my issue. I'd recommend doing this to everyone having the same issues. Currently on ton-pool.

Many thx for the comment. I hope that helps more people too

**Comment by Jipepe13** [comment]
> Seems switching away from tonwhales resolved my issue. I'd recommend doing this to everyone having the same issues. Currently on ton-pool.

Seems have same problem on ton-pool
