### ISSUE TITLE
Press any key to continue on tonpool and whales

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1088]
Left my FHR rig overnight to mine dual ETH and TON (TON on TONPOOL) and tested previously with tonwhales, woke up and found the press any key to continue message and all the mining stopped with defect segments as well, this rig was getting on nicehash and on trex 850-860 mh/s on ETH

![image](https://user-images.githubusercontent.com/49044292/152677267-0eeeb4f9-26a3-4f4b-843c-c8d4c3c60c0b.png)

![image](https://user-images.githubusercontent.com/49044292/152677280-534632aa-26f3-45d1-abb1-29eb1b47ad23.png)

**Comment by jgonzis** [comment]
> Left my FHR rig overnight to mine dual ETH and TON (TON on TONPOOL) and tested previously with tonwhales, woke up and found the press any key to continue message and all the mining stopped with defect segments as well, this rig was getting on nicehash and on trex 850-860 mh/s on ETH
> 
> ![image](https://user-images.githubusercontent.com/49044292/152677267-0eeeb4f9-26a3-4f4b-843c-c8d4c3c60c0b.png)
> 
> ![image](https://user-images.githubusercontent.com/49044292/152677280-534632aa-26f3-45d1-abb1-29eb1b47ad23.png)

DAG Verification are advise that your memory is overclock too much, lolMiner repairs it for you, but it is an important advice that your OC it probably not the best and can dangerous damage or degradate your memory.

About reported hashrate, I recommend you the best comparative with 1.000.000 shares to avoid luck, [Hashrate Comparative](https://www.hashrate.no/tests/ampere) That will show, that don't believe the reported Speed of the miners.... not all of them are honest with the reported hashrate. 

To have a constant loop in case one of the TON Pools go down, you can delete the marked blue line of the bat file. 
![image](https://user-images.githubusercontent.com/38668405/152689916-de869d6a-f856-45ea-b03f-eebb10bfccb0.png)
Version 1.44 will solve that to autowait in case it crash.

**Comment by Vinasis01** [comment]
Thanks for replying, sorry but can you explain what you mean by "To have a constant loop in case one of the TON Pools go down", this is my first time using lolminer so I am not an expert with it yet and still learning

**Comment by jgonzis** [comment]
> Thanks for replying, sorry but can you explain what you mean by "To have a constant loop in case one of the TON Pools go down", this is my first time using lolminer so I am not an expert with it yet and still learning

The idea, is that in case the TON pool goes down that crash lolMiner, so make a pause of 10s and restarted automatic for Windows, so you should care about any tonpool goes down. 

For that you should remove the 2 blue lines of your bat file.

**Comment by jgonzis** [comment]
> Thanks for replying, sorry but can you explain what you mean by "To have a constant loop in case one of the TON Pools go down", this is my first time using lolminer so I am not an expert with it yet and still learning

Or redownload that new bat file: 

https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

**Comment by Vinasis01** [comment]
Thanks will test that, appreciate it

**Comment by LaenorSama** [comment]
I have the same problem on windows 11. I'll try a new bat-file. Thanks!

**Comment by jgonzis** [comment]
And remember don't use tonwhales.com pool

**Comment by nameless314** [comment]
@jgonzis I'm not sure if anyone tried this, but I can run 2 instances of lolminer 1.42, 1 for eth and 1 for ton (on tonwhale) on 6600xt with no issues

**Comment by jgonzis** [comment]
> @jgonzis I'm not sure if anyone tried this, but I can run 2 instances of lolminer 1.42, 1 for eth and 1 for ton (on tonwhale) on one 6600xt with no issues using the overclock settings I was using on 1.43

Yes, the problem came with the block of 1.43... 1.44 has solved that. Problem of 2 instances it that performance is not the best

**Comment by jgonzis** [comment]
Try 1.44, it should be all solved now. Also try new minining pool icemining.ca it works great too.
