### ISSUE TITLE
resolved!! thanks

### ISSUE THREAD

**Issue by malagacripto** [Lolliedieb/lolMiner-releases#1089]
They have the correct batch file outside the the zip file if you don't want to tweak.https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

_Originally posted by @nameless314 in https://github.com/Lolliedieb/lolMiner-releases/issues/1068#issuecomment-1030748962_

**Comment by jgonzis** [comment]
thx for the feedback :-)
