### ISSUE TITLE
1.17: Segfault if dns is not working

### ISSUE THREAD

**Issue by ldm314** [Lolliedieb/lolMiner-releases#109]
DNS was not working temporarily on my machine. Launching lolMiner caused a segfault. Ubuntu 18.04. Fixing DNS, lolMiner works as expected.

<pre>
(base) brian@deep-machine:~/mining/amd/lolMiner-1.17$ ./mine_beam.sh
+---------------------------------------------------------+
|    _       _ __  __ _                   _   _ _____     |
|   | | ___ | |  \/  (_)_ __   ___ _ __  / | / |___  |    |
|   | |/ _ \| | |\/| | | '_ \ / _ \ '__| | | | |  / /     |
|   | | (_) | | |  | | | | | |  __/ |    | |_| | / /      |
|   |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_|/_/       |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|           Made by Lolliedieb, December 2020             |
+---------------------------------------------------------+

Setup Miner...
Device 0:
    Name:    AMD Radeon RX 5600 XT
    Address: 4:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  6128 MByte (6064 MByte free)
    Active:  true (Selected Algorithm: BeamHash III 4G+)
Device 1:
    Name:    AMD Radeon RX 5600 XT
    Address: 7:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  6128 MByte (6064 MByte free)
    Active:  true (Selected Algorithm: BeamHash III 4G+)

Connecting to pool...
./mine_beam.sh: line 16:  5293 Segmentation fault      (core dumped) ./lolMiner --coin BEAM --pool $POOL --user $WALLET $@
</pre>

**Comment by Lolliedieb** [comment]
Good catch!
Thanks, I will check that :)

**Comment by Lolliedieb** [comment]
Fixed with 1.18.
