### ISSUE TITLE
Feature Request: Alephium (Blake3) and ETH + ALPH

### ISSUE THREAD

**Issue by Mumpitz23** [Lolliedieb/lolMiner-releases#1090]
Have you considered adding Blake3 algorithm? ALPHDUAL might be even better than ETH+TON.

**Comment by jgonzis** [comment]
We should polish first all ETH+TON for all the miner, but let put a feature request. I

**Comment by DiDragon2022** [comment]
Right. Please first do the full work with ETH+TON. so that it works correctly and there are no periodic shutdowns.

**Comment by jgonzis** [comment]
> Right. Please first do the full work with ETH+TON. so that it works correctly and there are no periodic shutdowns.

For That shutdowns, we know that is when pool goes down... 

Try to have a full loop, removing the selected blue lines of your bat file please, that will help meanwhile next release comes

![image](https://user-images.githubusercontent.com/38668405/152693138-1024507c-ca97-4210-b7a3-cb82f1c67202.png)

**Comment by DiDragon2022** [comment]
ThANKS a lot , my Dear !!

> > Right. Please first do the full work with ETH+TON. so that it works correctly and there are no periodic shutdowns.
> 
> For That shutdowns, we know that is when pool goes down...
> 
> Try to have a full loop, removing the selected blue lines of your bat file please, that will help meanwhile next release comes
> 
> ![image](https://user-images.githubusercontent.com/38668405/152693138-1024507c-ca97-4210-b7a3-cb82f1c67202.png)

**Comment by oldani** [comment]
Is there a way to fix shutdowns on hiveOS? Had to disable dual mining due this, and nothing shows up in logs

**Comment by chrishilbert** [comment]
Also seeing mining stop on HiveOS.  Not sure how to resolve.

**Comment by jgonzis** [comment]
> Is there a way to fix shutdowns on hiveOS? Had to disable dual mining due this, and nothing shows up in logs



> Also seeing mining stop on HiveOS. Not sure how to resolve.

Don't use tonwhales.com pool

**Comment by jgonzis** [comment]
From1.45 it is done :-)
