### ISSUE TITLE
lhr tune lock

### ISSUE THREAD

**Issue by Zveroboev** [Lolliedieb/lolMiner-releases#1092]
Hello. How can I set settings similar to trex miner?
"lhr-tune": "74"
"lhr-autotune-mode": "off"

lolminer has --lhrtune arg, but I didn't understand what number it needs to set for an analog of 74% lhr unlock. Analog for "lhr-autotune-mode" setting I didn't find at all.

**Comment by jgonzis** [comment]
> Hello. How can I set settings similar to trex miner? "lhr-tune": "74" "lhr-autotune-mode": "off"
> 
> lolminer has --lhrtune arg, but I didn't understand what number it needs to set for an analog of 74% lhr unlock. Analog for "lhr-autotune-mode" setting I didn't find at all.

As defect the lhr tune will go automatic and it will be a value, that value means how much over or under is your GPU, some will be 23.1 and anothers could be negative -6.5, each GPU is different. When you mine and after some minutes that is stable, you can have that parameter and used as parameter , for example you have 9.5, so you can put --lhrtune 9.5 and it will automatic go to 9.5, and avoid all calibration.  

lolMiner inform of all locks that GPUs have, we didn't have it in background, we considered is good information for the miner.
