### ISSUE TITLE
Why does this happen? unexpeted low hasrate

### ISSUE THREAD

**Issue by malagacripto** [Lolliedieb/lolMiner-releases#1093]
when I start the miner these messages do not appear I do not know what happens
image 
![Screenshot_4](https://user-images.githubusercontent.com/99104674/152686921-91be2a1e-ea6f-44e8-bce2-89422418d6a2.png)

**Comment by jgonzis** [comment]
> when I start the miner these messages do not appear I do not know what happens image ![Screenshot_4](https://user-images.githubusercontent.com/99104674/152686921-91be2a1e-ea6f-44e8-bce2-89422418d6a2.png)

These are the steps to detect the LHR... it is completely normal. at the start... it could be also another locks. Miner just inform about it. I think it is nice to have that information, not keep it in background

**Comment by malagacripto** [comment]
> hese are the steps to detect the LHR... it is completely normal. at the start... it could be also another locks. Miner just inform about it. I think it is nice to have that information, not keep it in background

so is that normal? I just have to wait and start mining normally?

**Comment by jgonzis** [comment]
> > hese are the steps to detect the LHR... it is completely normal. at the start... it could be also another locks. Miner just inform about it. I think it is nice to have that information, not keep it in background
> 
> so is that normal? I just have to wait and start mining normally?

Si todas las LHR hacen ese paso, lolMiner lo enseña, otros mineros lo esconden...
