### ISSUE TITLE
ETH+TON : TON average speed is not showing. /  No EFFECTIVE HASHRATE @ WHALES POOL BOT

### ISSUE THREAD

**Issue by rigger774** [Lolliedieb/lolMiner-releases#1094]
Ethash: Average speed (15s): 14.70 Mh/s | 24.76 Mh/s Total: 39.46 Mh/s
**SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s**
New job received: 0x67fd3a Epoch: 471 Difficulty: 10.00G 
New job received: 0xb2e368 Epoch: 471 Difficulty: 10.00G 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve succeeded 
New job received: 0x6b6cf7 Epoch: 471 Difficulty: 10.00G 
Ton job with difficulty 274.88G and giver Ef8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4PgP received.
Ethash: Average speed (15s): 15.14 Mh/s | 24.76 Mh/s Total: 39.90 Mh/s
**SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s**

**Comment by jgonzis** [comment]
> Ethash: Average speed (15s): 14.70 Mh/s | 24.76 Mh/s Total: 39.46 Mh/s **SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s** New job received: 0x67fd3a Epoch: 471 Difficulty: 10.00G New job received: 0xb2e368 Epoch: 471 Difficulty: 10.00G Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded New job received: 0x6b6cf7 Epoch: 471 Difficulty: 10.00G Ton job with difficulty 274.88G and giver Ef8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4PgP received. Ethash: Average speed (15s): 15.14 Mh/s | 24.76 Mh/s Total: 39.90 Mh/s **SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s**

That could be 2 things:

1st. Don't use tonwhales at the moment, it is having constant blocks cloudfare, better use ton-pool.com or toncoinpool.io
2nd. The OC of your GPUs... it you have a Power Limit value and you are not using Fix Core that's the problem. 

Don't limit GPUs with Power Limit, use always Fix Core. 

IF you say your OS and your GPUs I will try to guide you in a sweet OC

**Comment by zabolash** [comment]
I have the same problem. I've tried using pools tonuniverse and ton-pool.com. I don't use powerlimit, it is set to 100%. Everything works fine on the 3080 ti, but on the 1080 ti the TON has 0Mh/s. Moreover, the same 1080 ti normally works in TON mining without Etherium.

**Comment by jgonzis** [comment]
> I have the same problem. I've tried using pools tonuniverse and ton-pool.com. I don't use powerlimit, it is set to 100%. Everything works fine on the 3080 ti, but on the 1080 ti the TON has 0Mh/s. Moreover, the same 1080 ti normally works in TON mining without Etherium.

Pascal (1080ti) aren't working in TON Dual... it was announced in the release.  It is been working on it

**Comment by zhukenny007** [comment]
missing TONWALLET keyword in the batch run file setting.

**Comment by rigger774** [comment]
> 

cd "$(dirname "$0")"

./lolMiner --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker $ETHWORKER $@
while [ $? -eq 42 ]; do
    sleep 10s
    ./lolMiner --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker $ETHWORKER $@
done

**Comment by rigger774** [comment]
> > Ethash: Average speed (15s): 14.70 Mh/s | 24.76 Mh/s Total: 39.46 Mh/s **SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s** New job received: 0x67fd3a Epoch: 471 Difficulty: 10.00G New job received: 0xb2e368 Epoch: 471 Difficulty: 10.00G Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded New job received: 0x6b6cf7 Epoch: 471 Difficulty: 10.00G Ton job with difficulty 274.88G and giver Ef8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4PgP received. Ethash: Average speed (15s): 15.14 Mh/s | 24.76 Mh/s Total: 39.90 Mh/s **SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s**
> 
> That could be 2 things:
> 
> 1st. Don't use tonwhales at the moment, it is having constant blocks cloudfare, better use ton-pool.com or toncoinpool.io 2nd. The OC of your GPUs... it you have a Power Limit value and you are not using Fix Core that's the problem.
> 
> Don't limit GPUs with Power Limit, use always Fix Core.
> 
> IF you say your OS and your GPUs I will try to guide you in a sweet OC

seems I need find another pool

**Comment by jgonzis** [comment]
Try new 1.44 that will help in lot of the problems.
