### ISSUE TITLE
High Load Average level on HiveOS

### ISSUE THREAD

**Issue by AlexStud** [Lolliedieb/lolMiner-releases#1095]
http://joxi.ru/gmvp3y3Heyn3dA
Is it the issue of the lol miner in dual mining?

**Comment by jgonzis** [comment]
> http://joxi.ru/gmvp3y3Heyn3dA Is it the issue of the lol miner in dual mining?

That seems more that the read of some of the GPUs are not ok... probably an extreme OC have made a GPU not reporting and that's the problem...

**Comment by AlexStud** [comment]
Thanks for the reply!

**Comment by 3djc** [comment]
Could this be reopened ? I have a similar issue with a x12 octominer rig (so no riser issues or anything like that). Using SAME flighsheet (mining TONCOIN on a single LHR card) and overclock, 1.42 works fine for weeks, installed 1.43, got LA error.  Restarting the miner solves the issue for a couple of hours at most. Rolled back 1.42, steady for the last 24hours,
