### ISSUE TITLE
ETH+TON dual mining problem: 

### ISSUE THREAD

**Issue by DariushAhmadi** [Lolliedieb/lolMiner-releases#1096]
I am trying to run lolMiner in Hiveos with this configuration:
<img width="679" alt="Screen Shot 1400-11-17 at 20 31 55" src="https://user-images.githubusercontent.com/2545079/152692146-a2c58ef2-57dd-41b4-a047-6e9e1398a9f5.png">
and face with error in miner log:
u-eth.hiveon.net:4444" can not be split into a address and a port. Please use format <pool address>:<pool port>
<img width="1400" alt="Screen Shot 1400-11-17 at 20 34 15" src="https://user-images.githubusercontent.com/2545079/152692172-b4c5fac8-3190-47e8-bb37-ce4d5e9a8f1c.png">

**Comment by jgonzis** [comment]
![image](https://user-images.githubusercontent.com/38668405/152692931-04071f62-f79b-41bf-bc56-809d1ed253ba.png)
