### ISSUE TITLE
ETH+TON Dual mine : Effective hashrate on pool, too much lower than hashrate of miner

### ISSUE THREAD

**Issue by Parham2004** [Lolliedieb/lolMiner-releases#1097]
After 24 hours, Effective hashrate on the pool more than half of showing hashrate on Miner
Using : Tonwhales.com Pool / lolminer V1.43 / HiveOS / 3 different workers 
Tonwhales.com Pool stats : 
Shares in 24h: 463
Shares in 60m: 21
Effective hashrate in 24h: 1.47 GH/s
Effective hashrate in 60m: 1.60 GH/s

HiveOS stats :
![image](https://user-images.githubusercontent.com/52333982/152692653-2f8136d7-2f14-46cc-b09e-86ee495f2837.png)
![image](https://user-images.githubusercontent.com/52333982/152692662-5c6e404a-631d-43bd-a73a-8540ee89bf31.png)

**Comment by jgonzis** [comment]
> After 24 hours, Effective hashrate on the pool more than half of showing hashrate on Miner Using : Tonwhales.com Pool / lolminer V1.43 / HiveOS / 3 different workers Tonwhales.com Pool stats : Shares in 24h: 463 Shares in 60m: 21 Effective hashrate in 24h: 1.47 GH/s Effective hashrate in 60m: 1.60 GH/s
> 
> HiveOS stats : ![image](https://user-images.githubusercontent.com/52333982/152692653-2f8136d7-2f14-46cc-b09e-86ee495f2837.png) ![image](https://user-images.githubusercontent.com/52333982/152692662-5c6e404a-631d-43bd-a73a-8540ee89bf31.png)

Tonwhales is blocking for cloudfare, please use toncoinpool.io or ton-pool.com, you will stop with that problems and have real hashrate
