### ISSUE TITLE
dual mining ETH TOn . Non LHR 3080 not getting the ton hashrate. After several reboots/miner regard sometimes it get the full hashrate for ton or else very less and stays at 150 mhs.

### ISSUE THREAD

**Issue by Venkat2382** [Lolliedieb/lolMiner-releases#1098]
![image](https://user-images.githubusercontent.com/20469626/152693519-b26e149e-3065-449d-bed2-564fe25f92a5.jpeg)

**Comment by jgonzis** [comment]
Your problem is the Power Limit, put in HiveOS PowerLimit to 0, and restart miner... that will helps
