### ISSUE TITLE
lolminer 1.43 emergency.sh won't run in hiveos

### ISSUE THREAD

**Issue by vilemooni** [Lolliedieb/lolMiner-releases#1099]
After lolminer detects dead gpu it launches the emergency script with red lines. However nothing happens and rig never gets rebooted. No stats in the hiveos browser either. 

I ran the script manually after reboot and it worked just fine.

**Comment by jgonzis** [comment]
> After lolminer detects dead gpu it launches the emergency script with red lines. However nothing happens and rig never gets rebooted. No stats in the hiveos browser either.
> 
> I ran the script manually after reboot and it worked just fine.

That is HiveOS fail, the watchdog works perfectly in the rigs.

**Comment by jgonzis** [comment]
Did you get it that restart the watchdog in HiveOS?. You can do it by algo or miners.

**Comment by nqzhang** [comment]
same problems here

**Comment by vilemooni** [comment]
I edited the script to use nohup and it started working, i dont think the change persisted after i updated from 1.43 to 1.44. but i havent had issues with cards and rig hasht restarted so i dont know if this is relevant anymore.

**Comment by nqzhang** [comment]
I am now using hiveos watchdog to restart rig, But I think the problem still exists after update lolminer from 1.43 to 1.44

**Comment by Martin-Luther** [comment]
Same problem here ... The rig should restart on crashed device(s), but it won't ...

**Comment by jgonzis** [comment]
> Same problem here ... The rig should restart on crashed device(s), but it won't ...

![image](https://user-images.githubusercontent.com/38668405/153581188-e612658c-3373-41d5-bd86-d1d14e52c4c2.png)

![image](https://user-images.githubusercontent.com/38668405/153581359-6cf85e61-37e4-49ea-9275-abfb4750d3d4.png)

![image](https://user-images.githubusercontent.com/38668405/153581414-9c75d526-400f-42b5-92e0-fe4f8ba5c504.png)

Working properly...

**Comment by Martin-Luther** [comment]
My version is v1.44, and before the update it used to work ... not anymore ... 
<img width="507" alt="Screenshot 2022-02-11 at 12 18 49" src="https://user-images.githubusercontent.com/2272470/153583265-7f026259-33c5-410a-bf19-62a199f6a601.png">

<img width="941" alt="Screenshot 2022-02-11 at 12 19 34" src="https://user-images.githubusercontent.com/2272470/153583302-22dd6799-940b-47d5-9877-5e78ab3db210.png">

<img width="424" alt="Screenshot 2022-02-11 at 12 22 33" src="https://user-images.githubusercontent.com/2272470/153583332-062df582-c125-48e7-a3a6-e4602a8e9c91.png">

**Comment by jgonzis** [comment]
> My version is v1.44, and before the update it used to work ... not anymore ... <img alt="Screenshot 2022-02-11 at 12 18 49" width="507" src="https://user-images.githubusercontent.com/2272470/153583265-7f026259-33c5-410a-bf19-62a199f6a601.png">
> 
> <img alt="Screenshot 2022-02-11 at 12 19 34" width="941" src="https://user-images.githubusercontent.com/2272470/153583302-22dd6799-940b-47d5-9877-5e78ab3db210.png">
> 
> <img alt="Screenshot 2022-02-11 at 12 22 33" width="424" src="https://user-images.githubusercontent.com/2272470/153583332-062df582-c125-48e7-a3a6-e4602a8e9c91.png">

try then to copy your old emergency.sh from the previous folder...

**Comment by jgonzis** [comment]
> > try then to copy your old emergency.sh from the previous folder...
> 
> Thanks, where is it located ?

/hive/miners/lolminer and there you should have all the folders of the version you use it

**Comment by Martin-Luther** [comment]
> /hive/miners/lolminer and there you should have all the folders of the version you use it

The only problem is that for both folders, it is a symlink pointing to `watchdog.sh` :(

<img width="691" alt="Screenshot 2022-02-11 at 12 45 56" src="https://user-images.githubusercontent.com/2272470/153586769-a64522b6-8933-4722-816a-05e2f91a7a3a.png">

**Comment by nqzhang** [comment]
I don't think the problem is caused by the script。you can manually execute the emergency.sh and its worked.

**Comment by Martin-Luther** [comment]
> I don't think the problem is caused by the script。you can manually execute the emergency.sh and its worked.

Of course ... by hand, it works ... But It is like the script is never called ...
Is it the same script that is in charge of closing the miner ? Could the issue be related to a problem while trying to close the miner ? Some kind of unhandled exception where the execution is halted before reaching the `emergency.sh` ?

Again, it used to work for a while ... I have been facing this issue since one or two weeks now.

<img width="941" alt="Screenshot 2022-02-11 at 12 19 34" src="https://user-images.githubusercontent.com/2272470/153593677-ad702ca7-d756-4f59-9459-a41ad66fad8d.png">

**Comment by nqzhang** [comment]
maybe platform related.I found that the nvidia card works but the amd card does not

**Comment by Martin-Luther** [comment]
> maybe platform related.I found that the nvidia card sometimes works but the amd card does not
On this rig, I have 1 nvidia & 11 amd cards

On another rig with exactly the same versions, I have 4 nvidia and 1 amd ... and everything is working just fine ...

**Comment by Martin-Luther** [comment]
> Could it be something with the GPU... By the way, try to increase the Core Voltage of that GPU... I found that people in AMD is using same Voltage than for only ETH, please that should be increased, or it could have crashed

Thank you for the tip, I will try, but it does not solve my problem ... If tomorrow there is another problem with the rig, I would like it to reboot ... In some cases, it working but not for this specific error.
Maybe I should just take the time to write a script that will tail for the logs and wait for that specific error to trigger `emergency.sh`.

**Comment by jgonzis** [comment]
> > Could it be something with the GPU... By the way, try to increase the Core Voltage of that GPU... I found that people in AMD is using same Voltage than for only ETH, please that should be increased, or it could have crashed
> 
> Thank you for the tip, I will try, but it does not solve my problem ... If tomorrow there is another problem with the rig, I would like it to reboot ... In some cases, it working but not for this specific error. Maybe I should just take the time to write a script that will tail for the logs and wait for that specific error to trigger `emergency.sh`.

But when the crash is in red, is hardware problem, normally in AMD is voltage or too high Memory.... or it could be Riser or PSU too

**Comment by bitcoincff** [comment]
I am using lolminer and when there is an error reboot.sh is not executed. is waiting for something. I see reboot.sh and emergency.sh in the lolminer folder. but it does not execute it or something happens because it is waiting. If it didn't find it, it would show an error message, even I have intentionally changed to rebbot.sh and there it does give an error. I'm root and it still doesn't work. lolminer 1.46 simplemining
