### ISSUE TITLE
Support for Ycash

### ISSUE THREAD

**Issue by hloo** [Lolliedieb/lolMiner-releases#11]
Ycash is a chain fork of Zcash that will launch at block height 570,000 of the Zcash blockchain (around July 18, 2019). A testnet will be available starting June 7, 2019. We are using Equihash(192,7).

We'd love for Ycash miners to be able to mine using lolMIner.

Note that Ycash is changing the Zcash address formats. (For example, Sapling addresses start with "ys" instead of "zs".)

More information:

https://www.ycash.xyz/the_fork/

https://github.com/YcashFoundation/ycash

**Comment by ceazer2801** [comment]
Please add support for Ycash

**Comment by Lolliedieb** [comment]
Was already supported by older versions with the overwritepersonal parameter. New 0.9 version now also has --coin YEC.
