### ISSUE TITLE
lolminer 1.17 on ethos starts with Error: Parsing error of "DEVICES" argument in json configuration.

### ISSUE THREAD

**Issue by riiikk** [Lolliedieb/lolMiner-releases#110]
Hi, I have been running 1.16 successfully on ethos 1.3.3 for some time, installed using the "third party miner installer" and updated lolminer to 1.17 in the same manner the other day. Unsuccessfully...When starting the miner I get the logo with the version 1.17 and under that:
 Error: Parsing error of "DEVICES" argument in json configuration. I start lolminer using flags, no json, however when the miner is started for some reason  a lolminer_config.json is created under /run/ethos/ . Anyone seen this, solved this?

**Comment by riiikk** [comment]
Oh, forgot to mention, If i restore the file lolMiner from 1.16 into miner directory and starts it up, all is well again.

**Comment by Lolliedieb** [comment]
Can you provide me the content of the file?

**Comment by riiikk** [comment]
Surething, which file do you need?  lolMiner? , the nonworking I presume?

**Comment by Lolliedieb** [comment]
No, the json file you mentioned - because something is in there the miner
does not like ;)

Am Mi., 6. Jan. 2021 um 12:40 Uhr schrieb riiikk <notifications@github.com>:

**Comment by riiikk** [comment]
Was about to install 1.17 again in order to give you the json-file and got 1.18 instead since the ethos install script sets up latest version...and 1.18 seem to work just fine...
