### ISSUE TITLE
Windows 11 - lolminer 1.43 memory overclock not working

### ISSUE THREAD

**Issue by vilemooni** [Lolliedieb/lolMiner-releases#1100]
Windows 11 - lolminer 1.43 memory overclock will not go over 9251MHz (offset +-0) no matter what input. It only allows me to decrease memory speed from default not increase it by 1300 which would be optimal. 

Also feature request:
lolminer should release memory and coreclocks on miner exit.

**Comment by jgonzis** [comment]
> Windows 11 - lolminer 1.43 memory overclock will not go over 9251MHz (offset +-0) no matter what input. It only allows me to decrease memory speed from default not increase it by 1300 which would be optimal.
> 
> Also feature request: lolminer should release memory and coreclocks on miner exit.

Memory clock is only for TON not for ETH... 

You are right it should run nvidia-smi -rlc

**Comment by vilemooni** [comment]
So this means that if i mine TON only the --mclk function would let me overclock the memory? 
Dual mining eth+ton the miner says that it sets up the mclk however it doesnt.

**Comment by jgonzis** [comment]
> So this means that if i mine TON only the --mclk function would let me overclock the memory? Dual mining eth+ton the miner says that it sets up the mclk however it doesnt.

You should use 3rd Party apps like MSI Afterburner For example

**Comment by vilemooni** [comment]
> > So this means that if i mine TON only the --mclk function would let me overclock the memory? Dual mining eth+ton the miner says that it sets up the mclk however it doesnt.
> 
> You should use 3rd Party apps like MSI Afterburner For example

Yes this is what i'we been doing since the memory oc didint work as I expected. Thought it could be something with windows 11.  Is there a possiblitity to add nvidia-smi commands into the .bat file somehow?

Thanks!
