### ISSUE TITLE
Eth Pool Mh/s = 0

### ISSUE THREAD

**Issue by pgranados0503** [Lolliedieb/lolMiner-releases#1102]
Mining with TON ok, but mining of eth pool hashrate is 0

Windows 11

**Comment by jgonzis** [comment]
> Mining with TON ok, but mining of eth pool hashrate is 0
> 
> Windows 11

Gpus?
Config file?
Photo?
Some information will help

**Comment by achilless2234** [comment]
> Mining with TON ok, but mining of eth pool hashrate is 0
> 
> Windows 11

same issue here..

**Comment by jgonzis** [comment]
> Gpus?
> Config file?
> Photo?
> Some information will help

Gpus?
Config file?
Photo?
Some information will help

I close until more information
