### ISSUE TITLE
Unable to Dual ETH TON Mine. Please Help!

### ISSUE THREAD

**Issue by BobaBreath** [Lolliedieb/lolMiner-releases#1104]
![Dual ETH TON Prob](https://user-images.githubusercontent.com/99145573/152700784-7569d260-62a2-4371-a528-680344710fa9.png)

Help! I am very new to dual mining and have no idea why I am unable to progress past this point. I can post my batch file if that will help.

**Comment by jgonzis** [comment]
> ![Dual ETH TON Prob](https://user-images.githubusercontent.com/99145573/152700784-7569d260-62a2-4371-a528-680344710fa9.png)
> 
> Help! I am very new to dual mining and have no idea why I am unable to progress past this point. I can post my batch file if that will help.

In Windows use another pool... don't use tonwhales.com please. Or it will crash.

Better option ton-pool or toncoinpool.io

**Comment by BobaBreath** [comment]
> 

THANK YOU. I actually ended up swapping to TON-pool! I shouldve pulled this. My bad. What happened with tonwhales?

**Comment by jgonzis** [comment]
> > 
> 
> THANK YOU. I actually ended up swapping to TON-pool! I shouldve pulled this. My bad. What happened with tonwhales?

The protocol https using cloudfare is blocking connection and crashes
