### ISSUE TITLE
Question: Eth+Zil+Ton 

### ISSUE THREAD

**Issue by johnnyde94** [Lolliedieb/lolMiner-releases#1105]
Hello is it possible to set up Eth+zil and ton as well? I don't see why it wouldn't work and I am going to try to test it. My Major question would be how to set it up in hive os. I think if I used an eth proxy it should all work.

**Comment by jgonzis** [comment]
> Hello is it possible to set up Eth+zil and ton as well? I don't see why it wouldn't work and I am going to try to test it. My Major question would be how to set it up in hive os. I think if I used an eth proxy it should all work.

the easy and fast way... use EZIL.ME to mine ETH and adds automaticly ZIL too :-)

**Comment by johnnyde94** [comment]
Thank you! How would I set it up with shard pool if I still wanted to use Ethermine as that’s what I am more interested in. Here are my current configs. I totally guessed on the windows bat file and I do not believe it’s working. I am so getting an issue if I try to dual mine ton and eth… if I use whales pool I get this error that will be the last picture if I do https, if I do http it does the other pic. I would prefer whales pool as I have all my other rigs on them already. Thanks!

Ps: I am getting most confused in the Pw I believe. Idk if it should be proxy.pass or proxy!pass as shard pool made it seem like it should be the latter. On shardpool I keep getting a proxy error. 

![image](https://user-images.githubusercontent.com/1479544/152845163-a9147e9c-e0d5-438d-b303-27d02f24c6ba.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845179-bf25a921-8e2b-450c-8b2e-549395d39d79.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845193-32c064cf-afe2-439d-ac86-bb56e30b5d70.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845220-e265924d-b99b-4b20-9a0f-fae3f5b92bc5.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845228-84219104-e832-4352-b605-d6e96d15195f.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845241-e21c3838-be3d-4624-8ddc-92233e858d4a.jpeg)

**Comment by jgonzis** [comment]
> Thank you! How would I set it up with shard pool if I still wanted to use Ethermine as that’s what I am more interested in. Here are my current configs. I totally guessed on the windows bat file and I do not believe it’s working. I am so getting an issue if I try to dual mine ton and eth… if I use whales pool I get this error that will be the last picture if I do https, if I do http it does the other pic. I would prefer whales pool as I have all my other rigs on them already. Thanks!
> 
> Ps: I am getting most confused in the Pw I believe. Idk if it should be proxy.pass or proxy!pass as shard pool made it seem like it should be the latter. On shardpool I keep getting a proxy error.
> 
> ![image](https://user-images.githubusercontent.com/1479544/152845163-a9147e9c-e0d5-438d-b303-27d02f24c6ba.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845179-bf25a921-8e2b-450c-8b2e-549395d39d79.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845193-32c064cf-afe2-439d-ac86-bb56e30b5d70.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845220-e265924d-b99b-4b20-9a0f-fae3f5b92bc5.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845228-84219104-e832-4352-b605-d6e96d15195f.jpeg)![image](https://user-images.githubusercontent.com/1479544/152845241-e21c3838-be3d-4624-8ddc-92233e858d4a.jpeg)

You have it... just don't use tonwhales.com pool🙂

**Comment by BANZAI-616** [comment]
Так у вас получилось запустить в итоге 3 монеты?

**Comment by jgonzis** [comment]
you can mine directly en EZIL.ME or use a proxy ZIL like shardpool or rustpool it should work with 3 systems. 

try it with new 1.44
