### ISSUE TITLE
Dual miner won't stop Lhr locking

### ISSUE THREAD

**Issue by javsezlol1** [Lolliedieb/lolMiner-releases#1107]
Lol miner is just constantly detecting lhr even with locked core clock
On 3060 lhr - windows - ton+eth+ driver 472. 12- running as admin

Lhrtune has reduced - 200+ with no affect to the hashrate

**Comment by telethrasher** [comment]
mine did the same thing - sometime during the night my 472.12 driver got corrupted - not sure when but the instance kept running through but with the windows wallpaper now a black background and no taskbar --- when i re-booted i had the same problem you're having with hugely negative LHR numbers...
    i finally realized after banging my head against the table that i needed to do a clean DDU uninstall and reinstall of the 472.12 driver - and now it's tuning like a champ again --- 

   one way you can tell if there's a driver problem is it doesn't go through " LHR Semi-Unlock Tuning Ongoing "  those lines were completely missing when i was trying to run with the corrupted Nvidia driver and i was getting the way negative unlock numbers and it never ever stabalized....
