### ISSUE TITLE
Дуал майниг Эфир+Тон

### ISSUE THREAD

**Issue by Johner84** [Lolliedieb/lolMiner-releases#1108]
Почему не майнит Тон карта 1080ti?
![20220207_033638_HDR](https://user-images.githubusercontent.com/99152263/152709455-0813cdfb-b343-4533-9bbb-82bfe6178221.jpg)

**Comment by Johner84** [comment]
![Capture+_2022-02-07-04-05-30](https://user-images.githubusercontent.com/99152263/152710014-8e2c9d58-5d87-47b9-b8c3-84726a9ec8b9.png)

**Comment by Johner84** [comment]
Вроде Nvidia 10 серии не потдерживает дуал майнинг. В этом дело? А будет ли потдержка в дальнейшем?

**Comment by jgonzis** [comment]
Pascal is ready in new version 1.44
