### ISSUE TITLE
API host

### ISSUE THREAD

**Issue by lrossy** [Lolliedieb/lolMiner-releases#111]
Is there a way to configure the API host to something other then 127.0.0.1? 

For example a param like --apihost 0.0.0.0 --apiport 3333 

Thanks

**Comment by UselessGuru** [comment]
You can change the port. But not the address (why would you?).
--apiport [port]

**Comment by lrossy** [comment]
We use an API collection method that pulls data from another server. Also, when running lolMiner inside a docker its impossible to expose the API port without a workaround.

**Comment by Lolliedieb** [comment]
Should not work with 1.18 :)
