### ISSUE TITLE
A5000 Dual Ton mining settings & Hashrate issues

### ISSUE THREAD

**Issue by span3252** [Lolliedieb/lolMiner-releases#1110]
Currently dual mining ETH/Ton with A5000 & A6000
A5000 & 6000 both ETH mining is normal at around 101 MH
However, with Ton A5000 is only mining at 152 MH, whilst A6000 is at 1.7Gh which is a huge discrepancy not sure if its an overclock issue or miner issue. my 3080ti LHRs and 3090s are all mining normally. 

Hive settings: Core/Mem A5000 1200/2580; A6000 1000/2580
![image](https://user-images.githubusercontent.com/99157959/152721358-b9790156-3382-43b8-9afd-ff388d1eaec0.png)

**Comment by halalmeats** [comment]
I have issues with A5000, too. I will often get 0 MHs with TON unless my eth hashrate is at 80 - 90.

**Comment by jgonzis** [comment]
> I have issues with A5000, too. I will often get 0 MHs with TON unless my eth hashrate is at 80 - 90.

Problem is that you should put PL... it should be to 0. PL 0

you can try to use --maxdualimpact 4, that will give less ETH but a big amount of  TON.

Reember to use always FIXED Core... 

Don't do like the photo above -200 always Fixed Core
