### ISSUE TITLE
Miner not working on 1660 Super (TI)

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [Lolliedieb/lolMiner-releases#1112]
Hello to all!
I checked a lot before posting here.

The miner does not work for 1660 Super (TI) cards.

I tried to run dual mining with ETH. The hashes go to the console, nothing comes to the pool.

I tried to start mining the TON coin separately. Exactly the same situation.

I tried to use another miner (Tonminer 1.0.11) - everything is fine!
I am using RaveOS.

Therefore, I concluded that your miner stopped working with regular cards (not LHR).

**Comment by edisonchan** [comment]
It works with 1660 super, check your code first.

**Comment by Oleg-Perevyshin** [comment]
--dualmode TONDUAL
--dualpool https://pool.services.tonwhales.com
--dualuser EQBKIuKESzpMMvIcsfWFacTJH_8LpiCJvA3RYcxPl8vzCrZ3

What is wrong here?
I tried different pool addresses.

**Comment by jgonzis** [comment]
> --dualmode TONDUAL --dualpool https://pool.services.tonwhales.com --dualuser EQBKIuKESzpMMvIcsfWFacTJH_8LpiCJvA3RYcxPl8vzCrZ3
> 
> --dualmode TONDUAL --dualpool https://server1.whalestonpool.com --dualuser EQBKIuKESzpMMvIcsfWFacTJH_8LpiCJvA3RYcxPl8vzCrZ3
> 
> What is wrong here? I tried different pool addresses.

Is should work if you are with 1.43... let's see if 1.44 solve eht problems for you... it could also be that you are limiting the GPU from PL and that is the problem
