### ISSUE TITLE
socks5 proxy does not work while dual mining.

### ISSUE THREAD

**Issue by edisonchan** [Lolliedieb/lolMiner-releases#1113]
![image](https://user-images.githubusercontent.com/8596506/152729246-9067be5f-db32-431b-a0de-cf06cf115baf.png)

```
set "POOL=stratum+ssl://172.65.239.73:5555"
set "WALLET=xxxxxx"

set "TONPOOL=wss://pplns.toncoinpool.io/stratum"
set "TONWALLET=xxxxxxx"
							
set "EXTRAPARAMETERS=--apiport=1000 --worker xxxx --dualworker xxxx --socks5 127.0.0.1:10808"
```

now I have to use SocksCAP windows 64 for mining with proxy, but the API of lolminer does not work in this method, so I hope lolminer add support socks5 proxy for dual mining.

**Comment by oiG8Uchi** [comment]
I hope that when the lolminer supports toncoin's socks5, can consider set the proxy of eth and ton respectively

**Comment by jgonzis** [comment]
Correct, try new release 1.44 and also new pool icemining.ca is working great now for ETH+DUAL too
