### ISSUE TITLE
Плавающая загрузка 3060 ti lhr v2 на эфире. 

### ISSUE THREAD

**Issue by xmariwanax** [Lolliedieb/lolMiner-releases#1114]
En
The problem is that when you start dual mining, just mining on lolminer, the video card does not load at 100% at the whole moment of time, the download is intermittent, a couple of seconds 100% then seconds 5 0%. In connection with what mining does not work. 

On the trex miner, the load is stable 99-100%.

Tell me how to configure lolminer so that my card would work stably? 
I work under win10.

Rus
Проблема заключается в том что, при запуске дуалмайнинга, просто майнинга на lolminer видеокарта не загружается на 100% во всем моменте времени, загрузка идет прерывисто, пара секунд 100% потом секунд 5 0%. Всвязи с чем майнить не получается. 

На майнере trex загрузка стабильно 99-100%.

Подскажите как настроить lolminer что бы моя карта работала стабильно? 
Работаю под win10.

**Comment by xmariwanax** [comment]
![Screenshot_20220206-141206877.jpg](https://user-images.githubusercontent.com/61599107/152736921-04e48fb6-892c-4b9b-bbdb-d1da5ed82794.jpg)

**Comment by xmariwanax** [comment]
![Screenshot_20220206-133248617.jpg](https://user-images.githubusercontent.com/61599107/152736999-ecd5f3a5-d69b-4261-817e-4e61f61ffbb8.jpg)

**Comment by jgonzis** [comment]
Give a try to the new release 1.44

Remember: Nvidia Driver 472.12
Use Power Limit to 100%
Use Fix Core in EXTRAPARAMETERS add --cclk value_core

Many thanks
