### ISSUE TITLE
LOLminer TON+ETH Restarts in HiveOS

### ISSUE THREAD

**Issue by JayaKrishnaSK** [Lolliedieb/lolMiner-releases#1116]
Hello Miners, am facing some issues with my Both rigs( one with Nvidia and other with AMD) which are powered by HiveOS and am using 1.43v lolminer with dual coin setup (ETH+TON). the miner restarts every 10 minutes and has no issues reported in LOG file and i watched it live even though there is no warrings or any response for restarting the miner. both rigs are facing the same issue.
///////////////////////////////////////////////////LOG Data/////////////////////////////////////////////

Ethash: Average speed (10s): 30.46 Mh/s | 30.56 Mh/s | 81.89 Mh/s | 95.51 Mh/s Total: 238.41 Mh/s
SHA256-TON: Average speed (10s): 776.51 Mh/s | 763.71 Mh/s | 1918.19 Mh/s | 1766.64 Mh/s Total: 5225.05 Mh/s
Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received.
New job received: 0x4b3d9e Epoch: 471 Difficulty: 4.30G 
Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve succeeded 
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received.
Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received.
New job received: 0x3cf659 Epoch: 471 Difficulty: 4.30G 
Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received.
Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve succeeded 
New job received: 0x47fa51 Epoch: 471 Difficulty: 4.30G 
Ethash: Average speed (10s): 30.46 Mh/s | 30.55 Mh/s | 81.83 Mh/s | 95.50 Mh/s Total: 238.35 Mh/s
SHA256-TON: Average speed (10s): 776.45 Mh/s | 763.53 Mh/s | 1917.51 Mh/s | 1766.99 Mh/s Total: 5224.49 Mh/s
double free or corruption (out)

lolminer exited (exitcode=0), waiting to cooldown a bit

[37mTrying to release TIME_WAIT sockets:
tcp        0      0 127.0.0.1:44444         127.0.0.1:47956         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:47860         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:47822         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:47924         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:47888         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:48012         TIME_WAIT  
///////////////////////////////////////////End of LOG//////////////////////////////////////////////////////////

**Comment by murat49370** [comment]
Hello,
I have the same problem...

**Comment by saiaman** [comment]
same here

**Comment by jgonzis** [comment]
> Hello Miners, am facing some issues with my Both rigs( one with Nvidia and other with AMD) which are powered by HiveOS and am using 1.43v lolminer with dual coin setup (ETH+TON). the miner restarts every 10 minutes and has no issues reported in LOG file and i watched it live even though there is no warrings or any response for restarting the miner. both rigs are facing the same issue. ///////////////////////////////////////////////////LOG Data/////////////////////////////////////////////
> 
> Ethash: Average speed (10s): 30.46 Mh/s | 30.56 Mh/s | 81.89 Mh/s | 95.51 Mh/s Total: 238.41 Mh/s SHA256-TON: Average speed (10s): 776.51 Mh/s | 763.71 Mh/s | 1918.19 Mh/s | 1766.64 Mh/s Total: 5225.05 Mh/s Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received. New job received: 0x4b3d9e Epoch: 471 Difficulty: 4.30G Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded https://server1.whalestonpool.com: Address is valid https://server1.whalestonpool.com: Address is registered Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received. Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received. New job received: 0x3cf659 Epoch: 471 Difficulty: 4.30G Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received. Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded New job received: 0x47fa51 Epoch: 471 Difficulty: 4.30G Ethash: Average speed (10s): 30.46 Mh/s | 30.55 Mh/s | 81.83 Mh/s | 95.50 Mh/s Total: 238.35 Mh/s SHA256-TON: Average speed (10s): 776.45 Mh/s | 763.53 Mh/s | 1917.51 Mh/s | 1766.99 Mh/s Total: 5224.49 Mh/s double free or corruption (out)
> 
> lolminer exited (exitcode=0), waiting to cooldown a bit
> 
> �[37mTrying to release TIME_WAIT sockets: tcp 0 0 127.0.0.1:44444 127.0.0.1:47956 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47860 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47822 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47924 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47888 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:48012 TIME_WAIT ///////////////////////////////////////////End of LOG//////////////////////////////////////////////////////////

Yes please don't use tonwhales... it the connection is lost crash the program. The new block cloudfare makes that. IT will be solve for 1.44 but meanwhile use ton-pool or toncoinpool.io

**Comment by murat49370** [comment]
It doesn't work, I tried to make the pool change since yesterday. I did a lot of research, saw all the tickets and couldn't get a stable rig...

**Comment by murat49370** [comment]
![Sans titre](https://user-images.githubusercontent.com/58220637/152788279-7b3be627-433a-4977-99f6-603d003a3aac.png)

**Comment by jgonzis** [comment]
New pools are comming. At the end is pools connection. I don't see Any crash information. Only restarts without information?

**Comment by murat49370** [comment]
The miner displays this message: "lolminer exited (exitcode=0), waiting to cooldown a bit"
and restarts every 5-10 minutes.

**Comment by JayaKrishnaSK** [comment]
> It doesn't work, I tried to make the pool change since yesterday. I did a lot of research, saw all the tickets and couldn't get a stable rig...

BUT for me the problem has been resolved by changing the pool to ton-pool.

**Comment by JayaKrishnaSK** [comment]
> > Hello Miners, am facing some issues with my Both rigs( one with Nvidia and other with AMD) which are powered by HiveOS and am using 1.43v lolminer with dual coin setup (ETH+TON). the miner restarts every 10 minutes and has no issues reported in LOG file and i watched it live even though there is no warrings or any response for restarting the miner. both rigs are facing the same issue. ///////////////////////////////////////////////////LOG Data/////////////////////////////////////////////
> > Ethash: Average speed (10s): 30.46 Mh/s | 30.56 Mh/s | 81.89 Mh/s | 95.51 Mh/s Total: 238.41 Mh/s SHA256-TON: Average speed (10s): 776.51 Mh/s | 763.71 Mh/s | 1918.19 Mh/s | 1766.64 Mh/s Total: 5225.05 Mh/s Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received. New job received: 0x4b3d9e Epoch: 471 Difficulty: 4.30G Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded https://server1.whalestonpool.com: Address is valid https://server1.whalestonpool.com: Address is registered Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received. Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received. New job received: 0x3cf659 Epoch: 471 Difficulty: 4.30G Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received. Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded New job received: 0x47fa51 Epoch: 471 Difficulty: 4.30G Ethash: Average speed (10s): 30.46 Mh/s | 30.55 Mh/s | 81.83 Mh/s | 95.50 Mh/s Total: 238.35 Mh/s SHA256-TON: Average speed (10s): 776.45 Mh/s | 763.53 Mh/s | 1917.51 Mh/s | 1766.99 Mh/s Total: 5224.49 Mh/s double free or corruption (out)
> > lolminer exited (exitcode=0), waiting to cooldown a bit
> > �[37mTrying to release TIME_WAIT sockets: tcp 0 0 127.0.0.1:44444 127.0.0.1:47956 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47860 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47822 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47924 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47888 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:48012 TIME_WAIT ///////////////////////////////////////////End of LOG//////////////////////////////////////////////////////////
> 
> Yes please don't use tonwhales... it the connection is lost crash the program. The new block cloudfare makes that. IT will be solve for 1.44 but meanwhile use ton-pool or toncoinpool.io

Thanks for your response and solution. It resolved the issue.

**Comment by jgonzis** [comment]
> > > Hello Miners, am facing some issues with my Both rigs( one with Nvidia and other with AMD) which are powered by HiveOS and am using 1.43v lolminer with dual coin setup (ETH+TON). the miner restarts every 10 minutes and has no issues reported in LOG file and i watched it live even though there is no warrings or any response for restarting the miner. both rigs are facing the same issue. ///////////////////////////////////////////////////LOG Data/////////////////////////////////////////////
> > > Ethash: Average speed (10s): 30.46 Mh/s | 30.56 Mh/s | 81.89 Mh/s | 95.51 Mh/s Total: 238.41 Mh/s SHA256-TON: Average speed (10s): 776.51 Mh/s | 763.71 Mh/s | 1918.19 Mh/s | 1766.64 Mh/s Total: 5225.05 Mh/s Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received. New job received: 0x4b3d9e Epoch: 471 Difficulty: 4.30G Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded https://server1.whalestonpool.com: Address is valid https://server1.whalestonpool.com: Address is registered Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received. Ton job with difficulty 274.88G and giver Ef8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716uj0 received. New job received: 0x3cf659 Epoch: 471 Difficulty: 4.30G Ton job with difficulty 274.88G and giver Ef8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhFww received. Ton pool connection mode:https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded New job received: 0x47fa51 Epoch: 471 Difficulty: 4.30G Ethash: Average speed (10s): 30.46 Mh/s | 30.55 Mh/s | 81.83 Mh/s | 95.50 Mh/s Total: 238.35 Mh/s SHA256-TON: Average speed (10s): 776.45 Mh/s | 763.53 Mh/s | 1917.51 Mh/s | 1766.99 Mh/s Total: 5224.49 Mh/s double free or corruption (out)
> > > lolminer exited (exitcode=0), waiting to cooldown a bit
> > > �[37mTrying to release TIME_WAIT sockets: tcp 0 0 127.0.0.1:44444 127.0.0.1:47956 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47860 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47822 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47924 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:47888 TIME_WAIT tcp 0 0 127.0.0.1:44444 127.0.0.1:48012 TIME_WAIT ///////////////////////////////////////////End of LOG//////////////////////////////////////////////////////////
> > 
> > 
> > Yes please don't use tonwhales... it the connection is lost crash the program. The new block cloudfare makes that. IT will be solve for 1.44 but meanwhile use ton-pool or toncoinpool.io
> 
> Thanks for your response and solution. It resolved the issue.

1.44 will improve that... soon will it come
