### ISSUE TITLE
Dualmold ETH+TON restart WIN10 on 8cards DELL 3060ti LHR platform

### ISSUE THREAD

**Issue by zhukenny007** [Lolliedieb/lolMiner-releases#1117]
I have 2 type of 3060ti LHR display cards. 8pcs LENOVO , 8pcs DELL. ETH+TON Dual mining works fine on the LENOVO cards, but it keep restarting the other maching with DELL display cards. Setting is same, No power limit, fixed core. Any clue to make it stable on DELL 3060ti LHR ?

**Comment by zhukenny007** [comment]
fixed core @1500MHz,  fixed memory clock +1400Mhz(2050MHz), fan 100,  power limit 100%

**Comment by wowlpv500** [comment]
Overclock on memory probably too high. Is it hynix??

**Comment by zhukenny007** [comment]
Memory is Samsung. +1400 works on most miner. And it also works on another 3060ti LHR machine. So I am courious whats cause the fatal error and restart windows.

**Comment by calvinIsAwesome** [comment]
> Memory is Samsung. +1400 works on most miner. And it also works on another 3060ti LHR machine. So I am courious whats cause the fatal error and restart windows.

same here，miner would restart for no reason after 2-3 hours of mining, don't know why

**Comment by jgonzis** [comment]
Try New release 1.44 : https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44
