### ISSUE TITLE
lolminer dual mining doesnt restart

### ISSUE THREAD

**Issue by ltwarrior18** [Lolliedieb/lolMiner-releases#1118]
If internet connection is lost, than it will stop and will never try to reconnect.  Also whale pool seems to be broken, at least for me, but ton pool works fine. 

I have 2x 3070: "FE, Asus Dual". Using Msi afterburner I locked them @0.78 volts, and  +mem 1100-1300 lower if connected to display. Also increased core clocks +275. It increased Ton coin mhs at least by 100.

I have 2x 3060: "Both gygabyte: 3xfan, Eagle". Eagle is so bad at dual minning it heats to 90celsius and fan is at 100%. Also I noticed with 3060 they don;t really benefit from highrer msi core clock, you need to increase voltage and leave core clock at default. Because of temps eagle loses 400 mhs compared to 3x fan gygabyte. It makes me puke with this high voltage inefficiency.

**Comment by jgonzis** [comment]
> If internet connection is lost, than it will stop and will never try to reconnect. Also whale pool seems to be broken, at least for me, but ton pool works fine.
> 
> I have 2x 3070: "FE, Asus Dual". Using Msi afterburner I locked them @0.78 volts, and +mem 1100-1300 lower if connected to display. Also increased core clocks +275. It increased Ton coin mhs at least by 100.
> 
> I have 2x 3060: "Both gygabyte: 3xfan, Eagle". Eagle is so bad at dual minning it heats to 90celsius and fan is at 100%. Also I noticed with 3060 they don;t really benefit from highrer msi core clock, you need to increase voltage and leave core clock at default. Because of temps eagle loses 400 mhs compared to 3x fan gygabyte. It makes me puke with this high voltage inefficiency.

Please could you use the new bat file? 
https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

Many thanks
