### ISSUE TITLE
lol 1.43 cant run on Ubuntu 16.04 - `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by khunpoum** [Lolliedieb/lolMiner-releases#1119]
```
./lolMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./lolMiner)
```

```
/lib/x86_64-linux-gnu/libc.so.6 --version
GNU C Library (Ubuntu GLIBC 2.23-0ubuntu11.3) stable release version 2.23, by Roland McGrath et al.
```

```
# ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
```

OS: Ubuntu 16.04.5 LTS

**Comment by khunpoum** [comment]
Which version of Ubuntu is better for LolMiner 1.43 and Polaris AMD GPU?

**Comment by jgonzis** [comment]
> ```
> ./lolMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./lolMiner)
> ```
> 
> ```
> /lib/x86_64-linux-gnu/libc.so.6 --version
> GNU C Library (Ubuntu GLIBC 2.23-0ubuntu11.3) stable release version 2.23, by Roland McGrath et al.
> ```
> 
> ```
> # ldd --version
> ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
> ```
> 
> OS: Ubuntu 16.04.5 LTS

It is really old version that's the problem... Is it any option to update it?
