### ISSUE TITLE
Anyone make dual ETH+TON works on 3060 or 3070 laptop  GPU ? 

### ISSUE THREAD

**Issue by zhukenny007** [Lolliedieb/lolMiner-releases#1120]
I try on both, it seems doesn't works , laptop GPU has hardward power limit, 3060 is 105W limit, 3070 is 115w limit.

**Comment by jgonzis** [comment]
> I try on both, it seems doesn't works , laptop GPU has hardward power limit, 3060 is 105W limit, 3070 is 115w limit.

you can but they are probably not prepared for the high intensity usage
