### ISSUE TITLE
Very low  hashrate in dual mode ETH+TONCoin on 3060v1 under driver 470.05

### ISSUE THREAD

**Issue by AleksP** [Lolliedieb/lolMiner-releases#1121]
TONCoin hashrate are between 0 (zero) and nornal 900 mh/s

![2022-02-07](https://user-images.githubusercontent.com/1014006/152783399-0a5cc593-2bbb-48ca-8566-c49d85cdfc21.png)
![2022-02-07 (1)](https://user-images.githubusercontent.com/1014006/152783741-e1225073-6ed3-42c3-aa3f-c2d64e72abbf.png)
[

**Comment by jgonzis** [comment]
> TONCoin hashrate are between 0 (zero) and nornal 900 mh/s
> 
> ![2022-02-07](https://user-images.githubusercontent.com/1014006/152783399-0a5cc593-2bbb-48ca-8566-c49d85cdfc21.png) [

Please, put Power Limit to 100% and use fixed core that's the proble you have now. 

To use Fixed Core : 
- MSI Afterburner
- nvidia-smi -lgc 1500
- add parameter to the new ETH+DUAL bat in "EXTRAPARAMETERS=--cclk 1500" muss be administrator : https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat
