### ISSUE TITLE
TONDUAL memory issue ?

### ISSUE THREAD

**Issue by RaOult82** [Lolliedieb/lolMiner-releases#1123]
Random crashes (at start or after 12h) with the following message :

...
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
malloc(): unsorted double linked list corrupted
double free or corruption (out)
./dual_mine_eth_ton.sh : ligne 22 :  4072 Abandon                 (core dumped) ./lolMiner --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker $ETHWORKER --lhrtune 12 $@

**Comment by RaOult82** [comment]
Hello, it finally crashed with ton-pool.com also :

...
Ton pool connection mode: ton-pool.com websocket job pushing (--ton-mode 2)
DNS over HTTPS resolve succeeded
./dual_mine_eth_ton.sh : ligne 22 :  8045 Erreur de segmentation  (core
dumped) ./lolMiner --algo ETHASH --pool $ETHPOOL --user $ETHWALLET
--dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker
$ETHWORKER --lhrtune 0 $@

Best regards

**Comment by jgonzis** [comment]
1.44 released: https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44
