### ISSUE TITLE
Dual ETH + TON, 0 hashrate for TON

### ISSUE THREAD

**Issue by suprahom** [Lolliedieb/lolMiner-releases#1125]
Just noticed that TON has been receiving an 0 hashrate all day. Reached out to Whale server support and they mentioned that its a issue with lolminer and the latest version.

Hoping to see if there is a update?

**Comment by igormursa** [comment]
change the pool to `https://next.ton-pool.com`

**Comment by Xefier** [comment]
Have you made sure to use unrestricted power limit and a core lock? At first I had 0 Mh/s on TON but now these are my results
3060 Ti
ETH Before 61 MH/s at 122W
ETH+TON (ETH = 60.15, TON = 1143) at 148W
https://github.com/Lolliedieb/lolMiner-releases/issues/1022

**Comment by suprahom** [comment]
Thank you to both for your replies.

However no luck with either suggestions.

I switched over to next.ton-pool. And after 6 hours of mining =

Your pool balance is: 0 TON
Your hash rate in last 1h is: 0.00MH/s
Your hash rate in last 24h is: 0.00MH/s


And as far as using unrestricted power limit and core lock. Half of the GPU's has no power limit and half did. But I can't imagine that would stop TON being hashed. As it did work without a problem for 1 day or so...

So I really don't know what is going on...

**Comment by stanchiam** [comment]
> Thank you to both for your replies.
> 
> However no luck with either suggestions.
> 
> I switched over to next.ton-pool. And after 6 hours of mining =
> 
> Your pool balance is: 0 TON Your hash rate in last 1h is: 0.00MH/s Your hash rate in last 24h is: 0.00MH/s
> 
> And as far as using unrestricted power limit and core lock. Half of the GPU's has no power limit and half did. But I can't imagine that would stop TON being hashed. As it did work without a problem for 1 day or so...
> 
> So I really don't know what is going on...

what is your gpu model? my 1070 ti also same issue, seems like not supported on all gpu yet

**Comment by igormursa** [comment]
@stanchiam makes a good point 10x series are not supported

**Comment by jgonzis** [comment]
> @stanchiam makes a good point 10x series are not supported

Now yes 1.44 :-)

**Comment by mooleshacat** [comment]
> change the pool to `https://next.ton-pool.com`

That is not an answer especially if the answer is to centralize the mining to one single pool. Fix your software.

**Comment by jgonzis** [comment]
> > change the pool to `https://next.ton-pool.com`
> 
> That is not an answer especially if the answer is to centralize the mining to one single pool. Fix your software.

4 months ago... there weren't pools with STRATUM+TCP they later all change... so I think we were the first to work the final used protoctol :-)
