### ISSUE TITLE
Inconsistent TON mining with --dualmode TONDUAL

### ISSUE THREAD

**Issue by igormursa** [Lolliedieb/lolMiner-releases#1127]
I am playing around with a 3080Ti and I am not mining 100%
by accident or pure luck, my first time yielded me 1700Mh/s for TON and about 75Mh/s for ETH so I took this for granted 
what I did observe that these numbers are not consistent,
I'll always get 75Mh/s on ETH but I need to restart the miner several times until I get back to the 1700Mh/s on TON
And when I say not consistent I mean range from 500-1500Mh/s 
```
Connected to: eu1.ethermine.org:4444 (15ms latency)
Algorithm 2: SHA256-TON
Connected to: https://next.ton-pool.com:443 (87ms latency)

      Name        Speed   Pool  Shares    Best    Eff.    Speed     Pool
                   Mh/s   Mh/s  A/S/Hw   Share  Mh/s/W     Mh/s     Mh/s
GPU 0 RTX 3080 Ti 75.18  75.58  29/0/0  112.3G   0.234  1527.23  1303.30
---------------------------
Total             75.18  75.58  29/0/0  112.3G   0.234  1527.23  1303.30

        Shares   Best    Eff.  Power  CCLK   MCLK  Core  Fan  --lhrtune
        A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Pct
GPU 0   33/0/1   1.4T   5.014  304.1  1727  10739    54   85        7.4
---------------------------
Total   33/0/1   1.4T   5.014  304.1
---------------------------------------------
New job received: 0x5f8ac5 Epoch: 472 Difficulty: 4.30G
```
My settings:
```
Drivers: v511.23
Mem Clock +1500
Core Clock +200
PL 80% (305W +/-)
```
PS: are these good numbers? 75 Mh/s ETH and 1700Mh/s TON?

**Comment by DasUnding** [comment]
I am not sure but I belive it has something to do with the tuning process. I got different results: 75MH/s ETH and 2900 MH/s Ton but sometimes it is 80MH/s ETH and 2600 MH/s Ton. It is also possible to get in between these two. I locked at around 1590 with an overlock at around +200 MHz core at this low clocks, which means around 0.75V and +750 MHz memory clock.

**Comment by igormursa** [comment]
> I am not sure but I belive it has something to do with the tuning process. I got different results: 75MH/s ETH and 2900 MH/s Ton but sometimes it is 80MH/s ETH and 2600 MH/s Ton. It is also possible to get in between these two. I locked at around 1590 with an overlock at around +200 MHz core at this low clocks, which means around 0.75V and +750 MHz memory clock. Consider also it is water cooled. Are you on windows 10 or 11 or something else?


I'm on W10
What is your `lhrtune` number?
