### ISSUE TITLE
Error: Your input to --pool "br.crazypool.org:3333" can not be split into a address and a port. Please use format <pool address>:<pool port>.

### ISSUE THREAD

**Issue by Marcos-AV** [Lolliedieb/lolMiner-releases#1129]
I'm receiving the error below when I start the miner (version 1.43):

`Error: Your input to --pool "br.crazypool.org:3333" can not be split into a address and a port. Please use format <pool address>:<pool port>.
`
I'm currently using this command line:

`lolminer.exe --algo ETHASH --pool stratum+tcp://br.crazypool.org:3333 --user 0x562fa372697652e554c70d39a3d97693b24ed4e5.PCGamerXeon --ethstratum=ETHV1 --dualmode TONDUAL --dualpool server1.whalestonpool.com --dualuser EQDE2zna2nfgchbb55VOCtL5qj-9w0wAXYFy0dErhPjTd30y
`
However, if I remove from --dualpool to the end, the miner starts correctly.

**Comment by jgonzis** [comment]
lolminer.exe --algo ETHASH --pool stratum+tcp://br.crazypool.org:3333 --user 0x562fa372697652e554c70d39a3d97693b24ed4e5.PCGamerXeon --ethstratum=ETHV1 --dualmode TONDUAL --dualpool wss://pplns.toncoinpool.io/stratum --dualuser EQDE2zna2nfgchbb55VOCtL5qj-9w0wAXYFy0dErhPjTd30y
