### ISSUE TITLE
'lolMiner.exe' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by ManningGithub** [Lolliedieb/lolMiner-releases#113]
I'm getting an issue once I begin to use the .bat file. My command prompt says "lolminer.exe is not recognized as an internal or external command, operable program or batch file". 

https://gyazo.com/5b148e3d9c7e031fc45d550d17df612b
https://gyazo.com/0773b258257314f6991f0ae064cc7884

Thanks in advance.

**Comment by NoobMine** [comment]
I had that happen after my antivirus intercepted it. I added the file to the antivirus exceptions list, deleted the miner, reloaded it again from the downloaded zip folder and ran the miner again.

**Comment by Lolliedieb** [comment]
Very likely similar issue as #112 .

**Comment by scd3524** [comment]
did you ever figure this out ?  im having the same issues

**Comment by ediaz13** [comment]
Go to your antivirus configuration and add lolMiner as an exception.

**Comment by FernandoLeite98** [comment]
> Go to your antivirus configuration and add lolMiner as an exception.

That doesnt work aswell. I only have Windows Defender as AV
