### ISSUE TITLE
ETH+TON windows settings for 3070 and 3060

### ISSUE THREAD

**Issue by ptbeto** [Lolliedieb/lolMiner-releases#1130]
When using T-Rex on windows on my 3070, for example, i used the --mclock 1400 and --lock-cclock 1150.
How do i set these values on lolminer? And how do i set up the core and memory for better setup on dual mining ETH+TON? I tried looking at your guides and readme but couldnt understand how the values work.
And how do i set up a fixed fan speed or target core temperature for autofan?

Thanks in advance.

Best regards

**Comment by jgonzis** [comment]
> When using T-Rex on windows on my 3070, for example, i used the --mclock 1400 and --lock-cclock 1150. How do i set these values on lolminer? And how do i set up the core and memory for better setup on dual mining ETH+TON? I tried looking at your guides and readme but couldnt understand how the values work. And how do i set up a fixed fan speed or target core temperature for autofan?
> 
> Thanks in advance.
> 
> Best regards

You cannot fix memory with lolMiner you have to use 3rd App like MSI Afterburner. 
clock you can do it with:

--cclk xxx

You can add that in EXTRAPARAMETERS of the bat file.  for example --cclk 1050,1350  that will do 1050 to GPU0 and 1350 to GPU1
https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

**Comment by japone777** [comment]
> > Например, при использовании T-Rex в Windows на моем 3070 я использовал --mclock 1400 и --lock-cclock 1150. Как мне установить эти значения на lolminer? И как мне настроить ядро ​​и память для лучшей настройки дуал-майнинга ETH+TON? Я пытался просмотреть ваши руководства и ридми, но не мог понять, как работают значения. И как установить фиксированную скорость вентилятора или целевую температуру ядра для автовентилятора?
> > Заранее спасибо.
> > С наилучшими пожеланиями
> 
> Вы не можете исправить память с помощью lolMiner, вы должны использовать третье приложение, такое как MSI Afterburner. часы вы можете сделать это с:
> 
> --cclk ххх
> 
> Вы можете добавить это в EXTRAPARAMETERS файла bat. например --cclk 1050,1350, который сделает 1050 для GPU0 и 1350 для GPU1 https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat

Please tell me, one of the video cards falls off for me, each time it’s different, can you tell me what to write in the file so that when the card falls off, it restarts?

**Comment by jgonzis** [comment]
> > > Например, при использовании T-Rex в Windows на моем 3070 я использовал --mclock 1400 и --lock-cclock 1150. Как мне установить эти значения на lolminer? И как мне настроить ядро ​​и память для лучшей настройки дуал-майнинга ETH+TON? Я пытался просмотреть ваши руководства и ридми, но не мог понять, как работают значения. И как установить фиксированную скорость вентилятора или целевую температуру ядра для автовентилятора?
> > > Заранее спасибо.
> > > С наилучшими пожеланиями
> > 
> > 
> > Вы не можете исправить память с помощью lolMiner, вы должны использовать третье приложение, такое как MSI Afterburner. часы вы можете сделать это с:
> > --cclk ххх
> > Вы можете добавить это в EXTRAPARAMETERS файла bat. например --cclk 1050,1350, который сделает 1050 для GPU0 и 1350 для GPU1 https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.43/dual_mine_eth_ton.bat
> 
> Please tell me, one of the video cards falls off for me, each time it’s different, can you tell me what to write in the file so that when the card falls off, it restarts?

Try new 1.44 that solve some fixes ... and try not to push to hard the GPUs
