### ISSUE TITLE
Windows 11 - Low hashrate for Dual ETH+TON

### ISSUE THREAD

**Issue by GuRuNa** [Lolliedieb/lolMiner-releases#1131]
I try mine ETH+TON on my non LHR card 3080,3070,3060Ti but I lost around 10 MH on ETH on all card
- RTX 3080  ETH : 95 , ETH+TON : 86 on ETH
- RTX 3070  ETH : 60 , ETH+TON : 51 on ETH
- RTX3060Ti  ETH : 60 , ETH+TON : 51 on ETH
but I saw another people who mine in HiveOS get ETH hashrate same as mine only eth.
This is because Windows ?

**Comment by rcerebro** [comment]
> I try mine ETH+TON on my non LHR card 3080,3070,3060Ti but I lost around 10 MH on ETH on all card
> 
> * RTX 3080  ETH : 95 , ETH+TON : 86 on ETH
> * RTX 3070  ETH : 60 , ETH+TON : 51 on ETH
> * RTX3060Ti  ETH : 60 , ETH+TON : 51 on ETH
>   but I saw another people who mine in HiveOS get ETH hashrate same as mine only eth.
>   This is because Windows ?

![image](https://user-images.githubusercontent.com/38794375/152861062-47786933-4a7f-4f22-a6ed-9816a72270f1.png)

3070 NLHR

1300 lock clock
1100 memory clock

**Comment by vilemooni** [comment]
RTX 3080 - 99,6MH/s eth 2,3GH TON -> lock core 1560, memory +1300MHz (10550Mhz)

**Comment by Riridesu** [comment]
Im lossing 5~10MH/s (52~55MH/s) on RX6800 as well, same memory clock for mining ETH (62MH/s), change only core clock for mining TON.
Ive tried to increase Voltage and power limit but hash rate wont come back to normal.

**Comment by jgonzis** [comment]
New 1.44 is there, that will help lot of the problems in Windows...
I recommend you to have a look the the new pool icemining.ca, it is actually the best protocol for TON

https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44

Also EXTRAPARAMETERS working now in the dual files.

Give a try!!
