### ISSUE TITLE
Only specific cards eth + ton

### ISSUE THREAD

**Issue by mkuttert** [Lolliedieb/lolMiner-releases#1134]
good night, how do I select only specific cards to do dual mining eth + ton?

**Comment by mrjavascript** [comment]
I ran into the same issue.  I tried running --devices AMD or --devices 1 to run the dualminer on a specific index, and all cards on the rig are set to active.  If I set this flag in mine_eth.bat under extra params, the cards are selected correctly.

**Comment by mkuttert** [comment]
> I ran into the same issue. I tried running --devices AMD or --devices 1 to run the dualminer on a specific index, and all cards on the rig are set to active. If I set this flag in mine_eth.bat under extra params, the cards are selected correctly.

how do i do this in hiveos?

**Comment by mrjavascript** [comment]
I was running this on a Win10 rig.  The --devices param works correctly in the mine_eth.bat file, I noticed that this flag was not working in the eth/ton dual mine batch script.

**Comment by thompsontj12** [comment]
You will want to use the newest .bat file that is not in the package. That solves i

**Comment by AdyDubz** [comment]
> 

@thompsontj12 where i can find the new .bat that ure saying?

**Comment by jgonzis** [comment]
New 1.44 is there https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44

You are able to select with --maxdualimpact which card mine ETH+TON and which only ETH.
 
Example for --dualdevices and --maxdualimpact
Consider a 6 card rig with --dualdevices 4,5 --maxdualimpact 0,0,,,,
This rig will mine:

Eth only on GPUs 0 & 1 (ton dual mining disabled by maxdualimpact)
Eth + Ton on GPUs 2 & 3
Ton only on GPUs 4 & 5 (eth mining disabled by dualdevices)
