### ISSUE TITLE
1.17 Miner stops working shortly after starting. Does not provide explanation.

### ISSUE THREAD

**Issue by NoobMine** [Lolliedieb/lolMiner-releases#114]
![troubleshoot](https://user-images.githubusercontent.com/77028380/103706206-73933900-4fe7-11eb-822c-b2e2f90bdd1d.PNG)

Using Windows 10 PC with RTX 3070, Nvidia driver 457.09

Tried mining on Ethermine pool and the same thing happened. Am a complete noob to the mining scene, any help would be greatly appreciated!

**Comment by jgonzis** [comment]
That's normally the OC of the memory. you can also made a loop in the bat file:

:loop
lolminer.exe -a ....
goto loop

**Comment by Pragmatich** [comment]
> That's normally the OC of the memory. you can also made a loop in the bat file:
> 
> :loop
> lolminer.exe -a ....
> goto loop


Just like that?

lolMiner.exe --algo ETHASH --pool eth.2miners.com:2020 --user ADDRESS.RIG_ID
keepfree 56
pause
:loop
lolminer.exe -a ....
goto loop

**Comment by jgonzis** [comment]
> > That's normally the OC of the memory. you can also made a loop in the bat file:
> > :loop
> > lolminer.exe -a ....
> > goto loop
> 
> Just like that?
> 
> lolMiner.exe --algo ETHASH --pool eth.2miners.com:2020 --user ADDRESS.RIG_ID
> keepfree 56
> pause
> :loop
> lolminer.exe -a ....
> goto loop

like this:

 :loop
 lolMiner.exe --algo ETHASH --pool eth.2miners.com:2020 --user ADDRESS.RIG_ID
goto loop

**Comment by Pragmatich** [comment]
Of course, what a silly I am... Thanks a lot.

**Comment by jgonzis** [comment]
Solved with new bat files
