### ISSUE TITLE
Looking forward to a more stable version

### ISSUE THREAD

**Issue by calvinIsAwesome** [Lolliedieb/lolMiner-releases#1140]
Having two major problems dual Mining ETH+TON.
1. Miner would restart for no reason after couple of hours of working, even if I have locked coreclock, set no power limit and not using whalestonpool
2. Problem selecting specific cards to run dual mining algorithm. Hashrate is lower for those card I left purely mining ETH, and they sometimes even show some ghost hashrate for mining TON.

**Comment by Acilleuz** [comment]
I`ve the same problems...

**Comment by mozad-12** [comment]
I have same problems too.

**Comment by jgonzis** [comment]
New 1.44 is there, that will help lot of the problems in Windows...
I recommend you to have a look the the new pool icemining.ca, it is actually the best protocol for TON

https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44

Also EXTRAPARAMETERS working now in the dual files.

Give a try!!
