### ISSUE TITLE
cannot split into a address and port

### ISSUE THREAD

**Issue by DeanJing** [Lolliedieb/lolMiner-releases#1143]
while I input the right ip:port, I donot know what the issue?
HIVEOS latest version

**Comment by jgonzis** [comment]
> while I input the right ip:port, I donot know what the issue? HIVEOS latest version

That is the flighsheet is not correctly... 

Have a look to the configuration 👍 
https://www.youtube.com/channel/UCzzt77TQJhRjqN1ZwBR1AMw/
