### ISSUE TITLE
My AMD 5700xt local 3.2G, but remote is 0 and shares 0/0/0.  Can you help me

### ISSUE THREAD

**Issue by Rempage** [Lolliedieb/lolMiner-releases#1144]

**Comment by Rempage** [comment]
ETH + TON

**Comment by jgonzis** [comment]
It could be that you don't have so much hashrate try New 1.44, that will help lot of the problems in Windows...

I recommend you to have a look the the new pool icemining.ca, it is actually the best protocol for TON, it works on low diff gpu

https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44

Also EXTRAPARAMETERS working now in th dual files.**

**Comment by juandelacruz-calvo** [comment]
HIya, I have the same issue with all the AMD [https://imgur.com/a/yIqSymv](https://imgur.com/a/yIqSymv)

**Comment by jgonzis** [comment]
> HIya, I have the same issue with all the AMD https://imgur.com/a/yIqSymv I'm on v1.44 on Windows and the rig has been stable for a solid 2 or 3 days but any of the AMD cards have shares even thought they have hasrate

That could be that a little bit of more Core is need it or drivers...
