### ISSUE TITLE
3070 and 2070 -> set "EXTRAPARAMETERS=--cclk 1500"

### ISSUE THREAD

**Issue by djax54** [Lolliedieb/lolMiner-releases#1145]
Hello!

I was getting really low TON hashrates on my 2070 (300s) while my 3070 was getting 2k+. I saw somewhere here that adding set "EXTRAPARAMETERS=--cclk 1500" helped by forcing the cards to stick at 1500... This was around the same suggestion for my 3070.

However, this seems to been a permanent change. I would like to undo it. How? Google isn't helping much. 

(Note: this fixed my 2070.. but it lowered my 3070 significantly. But the gross was still better. However, it also somehow lowered my ETH on my 3070 by 10 mh/s... not willing to take that hit. Also use this computer for other things.. would like the cores to function normally when NOT mining... Please help.)

**Comment by vilemooni** [comment]
Nvidia-smi -i 0 -rgc It will reset core clock to default. If you set only one value it will affect both cards wich is not desirable. Both cards should have their own value. What kind of hashrate you get for 2070?

**Comment by djax54** [comment]
> Nvidia-smi -rgc It will reset core clock to default. You can point to a single gpu with -i 0 option where 0-n is your gpu number. If you set only one value it will affect both cards wich is not desirable. Both cards should have their own value. What kind of hashrate you get for 2070?

![image](https://user-images.githubusercontent.com/99246757/152953339-c0f44cc3-ad01-41cb-bc46-1bd18feeee83.png)

Thanks! Ended up installing new drivers and restarting. one of the two did it. 

but my 3070 was low on ETH still tho... But I just opened up TREX miner to check it.. and it was normal.. then reopened lolminer and now my 2070 is low!  But 3070 is normal and im getting higher than ever TON... so ill just sit on this for now.

But this is good to know thanks! I would probably like to set the 2070 to 1500 and leave the 3070 to do its thing.

If image doesnt work im getting 
ETH - 61.53 mhs / 35.06 mhs (normally 41ish)
TON - 2093 mhs (saw this 2200s at one point) / 1121.8 mhs

**Comment by Mumpitz23** [comment]
> > Nvidia-smi -rgc It will reset core clock to default. You can point to a single gpu with -i 0 option where 0-n is your gpu number. If you set only one value it will affect both cards wich is not desirable. Both cards should have their own value. What kind of hashrate you get for 2070?
> 
> ![image](https://user-images.githubusercontent.com/99246757/152953339-c0f44cc3-ad01-41cb-bc46-1bd18feeee83.png)
> 
> Thanks! Ended up installing new drivers and restarting. one of the two did it.
> 
> but my 3070 was low on ETH still ... When I just opened up TREX miner to check it.. it was normal.. then reopened lolminer and 3070 was good but now my 2070 is low! But im getting higher than ever TON... so ill just sit on this for now.
> 
> But this is good to know thanks! I would probably like to set the 2070 to 1500 and leave the 3070 to do its thing.
> 
> If image doesnt work im getting ETH - 61.53 mhs / 35.06 mhs (normally 41ish) TON - 2093 mhs (saw this 2200s at one point) / 1121.8 mhs
> 
> EDIT: reopened to help people with maybe a similar issue find it for a bit. Will close in a day or so. Technically my issue is solved.

Your Power draw per card?

**Comment by jgonzis** [comment]
New 1.44 is there, that will help lot of the problems in Windows...
I recommend you to have a look the the new pool icemining.ca, it is actually the best protocol for TON

https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44

Also EXTRAPARAMETERS working now in th dual files.

**Comment by djax54** [comment]
> 

![image](https://user-images.githubusercontent.com/99246757/153061841-110106bc-639b-4e90-bbdd-ee0be4e53391.png)

but this is a fresh 1.44 file without any extra params on whale pool. gonna try and hit the withdraw limit on there so clear it out before moving to something else.

not sure about this new icemining pool.. you gotta download this wallet for it to work? https://medium.com/icemining-guides/how-to-mine-mwc-and-withdraw-to-a-cli-wallet-any-http-listener-c623419e0910

**Comment by jgonzis** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/99246757/153061841-110106bc-639b-4e90-bbdd-ee0be4e53391.png)
> 
> but this is a fresh 1.44 file without any extra params on whale pool. gonna try and hit the withdraw limit on there so clear it out before moving to something else. my 2070 is getting about 1/2 the TON it did last night.
> 
> not sure about this new icemining pool.. you gotta download this wallet for it to work? https://medium.com/icemining-guides/how-to-mine-mwc-and-withdraw-to-a-cli-wallet-any-http-listener-c623419e0910

The reduction of stales for Nvidia have made to reduce also TON... try to put positive core to recover that small extra

You have to use your same wallet of TON for icemining.ca
