### ISSUE TITLE
whale ton pool/ton pool (both on hiveos choosing)   0 report effective hashrate.  

### ISSUE THREAD

**Issue by DICHEAD** [Lolliedieb/lolMiner-releases#1146]
hello

ETH+ton mining ok for few day. all of sudden, 0 mh effective hashrate  on both ton coin pool.

ETH is run fine but ton coin is not. (its look like its mining normally on hive os)

on hive shell i got red code running around. (is not normal mining screen that we use to see)

sorry i don't know how to post picture.

looking forward for 1.44

**Comment by jgonzis** [comment]
New 1.44 is there. I recommend you to have a look the the new pool icemining.ca, it is actually the best protocol for TON
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44
