### ISSUE TITLE
How to choose which GPU produces

### ISSUE THREAD

**Issue by liqy2019** [Lolliedieb/lolMiner-releases#115]
Sometimes you need to use one GPU to work and the other to produce ETH ..

**Comment by Lolliedieb** [comment]
Use --devices parameter, e.g.
--devices 1,2,3 to skip over device 0 (the first one in system).
Use lolMiner --list-devices to check all detected devices to the the order right.

**Comment by liqy2019** [comment]
thinks

> Use --devices parameter, e.g.
> --devices 1,2,3 to skip over device 0 (the first one in system).
> Use lolMiner --list-devices to check all detected devices to the the order right.

thinks !
