### ISSUE TITLE
1.44 3060LHR v1 TON 0Mh/s

### ISSUE THREAD

**Issue by oiG8Uchi** [Lolliedieb/lolMiner-releases#1152]
![image](https://user-images.githubusercontent.com/95996550/152997029-f7753d0f-6ffe-4e45-93b0-508acd0cebcf.png)

**Comment by Stiffman** [comment]
![image](https://user-images.githubusercontent.com/77394243/153003666-3a2ef6da-61b4-4b05-a494-c2d4a28dda73.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/77394243/153003666-3a2ef6da-61b4-4b05-a494-c2d4a28dda73.png)

Power Limit to 0!!

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/95996550/152997029-f7753d0f-6ffe-4e45-93b0-508acd0cebcf.png)

Please Power to 100% in Windows or PL to 0 in HiveOS. 



Always please use Fixed Clock. If you don't do Fixed Clock TON will not work propoerly.

**Comment by oiG8Uchi** [comment]
![image](https://user-images.githubusercontent.com/95996550/153010122-32b3b150-61a3-4342-9cfb-754c4a6ea881.png)

**Comment by oiG8Uchi** [comment]
Maybe it's a network problem？
