### ISSUE TITLE
1.44 Dual Mining ETH hash drop

### ISSUE THREAD

**Issue by moon1z10** [Lolliedieb/lolMiner-releases#1153]
I upgraded from 1.43 to 1.44 but ETH hash drop when dual mining (eth + TONCOIN).

For example, 3080 non lhr rig, it was 99.51MH/s but it dropped to 98.5MH/s.
And it's happening on 3070 non lhr too.

**Comment by yurimoe** [comment]
3080Ti lhr, it was 80MH/s +ton 1.7g (lhrtune 23). but it dropped to 78.2MH/s +ton 1.7g (lhrtune 18).

**Comment by jgonzis** [comment]
> I upgraded from 1.43 to 1.44 but ETH hash drop when dual mining (eth + TONCOIN).
> 
> For example, 3080 non lhr rig, it was 99.51MH/s but it dropped to 98.5MH/s. And it's happening on 3070 non lhr too.

> 3080Ti lhr, it was 80MH/s +ton 1.7g (lhrtune 23). but it dropped to 78.2MH/s +ton 1.7g (lhrtune 18).

Version 1.43  have the 5% Stales if the pool pay them all you can stay in 1.43, or new version that doesn't have stales. Pushing to the limit the Mhs has bring that problem in 1.43.
