### ISSUE TITLE
bug that made the miner crash 

### ISSUE THREAD

**Issue by mozad-12** [Lolliedieb/lolMiner-releases#1154]
![20220208_181616](https://user-images.githubusercontent.com/99247654/153011919-387e34a2-7f52-4ff1-bfa0-2d2e306b0072.jpg)
Still have bug that made the miner crash

**Comment by jgonzis** [comment]
> ![20220208_181616](https://user-images.githubusercontent.com/99247654/153011919-387e34a2-7f52-4ff1-bfa0-2d2e306b0072.jpg) Still have bug that made the miner crash

Which Version are you using 1.43 or 1.44?

**Comment by mozad-12** [comment]
> > ![20220208_181616](https://user-images.githubusercontent.com/99247654/153011919-387e34a2-7f52-4ff1-bfa0-2d2e306b0072.jpg) Still have bug that made the miner crash
> 
> Which Version are you using 1.43 or 1.44?

1.44

**Comment by jgonzis** [comment]
I hope you could share your OC and try it with another pool... if you are using the new bat files that should be automatic loop. It could also crash the Driver for the OC...

**Comment by mozad-12** [comment]
![Uploading 20220210_064614.jpg…]()
![Uploading 20220210_055030.jpg…]()
This happens after a while

**Comment by mozad-12** [comment]
![20220210_064614](https://user-images.githubusercontent.com/99247654/153338060-ff1dc228-24ae-4ac8-b3df-f75f185a0583.jpg)
![20220210_055030](https://user-images.githubusercontent.com/99247654/153338084-982c9758-0f87-424f-86e1-09d9416e028b.jpg)

This happens after a while

**Comment by jgonzis** [comment]
It seems that GPU0 has crashed...  Which GPU is it?. 

If it is a 6800/6900, you need to add some extra voltage or it will not be able to do ETH+TON. Remember dualmining needs some extra Watts.

**Comment by jgonzis** [comment]
That should be solved with last releases
