### ISSUE TITLE
Please support old cards too.( P106-100 / rx470 , rx480)

### ISSUE THREAD

**Issue by istyles50** [Lolliedieb/lolMiner-releases#1155]
For p106-100  / amd 470 products, toncoin mining does not work when ethereum + toncoin dual mining.

**Comment by jgonzis** [comment]
> For p106-100 / amd 470 products, toncoin mining does not work when ethereum + toncoin dual mining.

That is not true... check your OC or flighsheet they are working:

470 in 1.43
P106-100 in 1.44
