### ISSUE TITLE
Support for additional dual mining (ERGO+?)

### ISSUE THREAD

**Issue by Cougarvsd** [Lolliedieb/lolMiner-releases#1156]
Hello,

could you please consider to ensure dual mining outlives ETH mining?

I understand that ERG algo is very much ETH like as it uses memory and shares OCs. I would love to be able to do something like ERG+ALPH after ETH.
thanks

**Comment by jgonzis** [comment]
It is complicated, because only ETH use Memory, ERG use Memory and Core... so it will kill the other algo... 

Complicated what you look forward :-)

**Comment by Cougarvsd** [comment]
thanks for this quick feedback. I hoped it could work :s
