### ISSUE TITLE
Hive.os Lolminer 14.3 ETH/TON restart issues

### ISSUE THREAD

**Issue by pam1212** [Lolliedieb/lolMiner-releases#1161]
Hello,

I am a new user here!

I am using Hive.os and I have 6 rigs of 8 GPUs each. Each rig has 8 RTX 3070s.

I started mining ETH / TON with Lolminer 14.3 over the past few days. I have the current image of Hive.Os (0.6-213@220206), current kernel (5.10.0), and current Nvidia drivers (495.46).

I have noticed many of the rigs would randomly restart a few hours after running. The warnings I am receiving on my Telegram bot are:

Load average: 28.02 15.39 9.67
LA > 48
LA > 48
Load average: 75.53 20.00 11.28
etc.

In this example, I rebooted all rigs 14 hours ago. Checking this morning, here is what I see:
Worker 1 - 14h 26m
Worker 2 - 11h 15m
Worker 3 - 4h 22m
Worker 4 - 6h 38m
Worker 5 - 5h 40m
Worker 6 - 4h 21m

This indicates workers 2-6 have rebooted at some point due to LA being too high. What is causing the LA to ramp up hours into mining? Is there an issue with the software?
For clarity: All of my rigs have never had this problem for the past 9 months mining just ETH.

Thanks!

**Comment by jgonzis** [comment]
> Hello,
> 
> I am a new user here!
> 
> I am using Hive.os and I have 6 rigs of 8 GPUs each. Each rig has 8 RTX 3070s.
> 
> I started mining ETH / TON with Lolminer 14.3 over the past few days. I have the current image of Hive.Os (0.6-213@220206), current kernel (5.10.0), and current Nvidia drivers (495.46).
> 
> I have noticed many of the rigs would randomly restart a few hours after running. The warnings I am receiving on my Telegram bot are:
> 
> Load average: 28.02 15.39 9.67 LA > 48 LA > 48 Load average: 75.53 20.00 11.28 etc.
> 
> In this example, I rebooted all rigs 14 hours ago. Checking this morning, here is what I see: Worker 1 - 14h 26m Worker 2 - 11h 15m Worker 3 - 4h 22m Worker 4 - 6h 38m Worker 5 - 5h 40m Worker 6 - 4h 21m
> 
> This indicates workers 2-6 have rebooted at some point due to LA being too high. What is causing the LA to ramp up hours into mining? Is there an issue with the software? For clarity: All of my rigs have never had this problem for the past 9 months mining just ETH.
> 
> Thanks!

Lot of the problems come from the TON pools. 1.44 should help on that, also adding a good new TON pool like icemining.ca

You should consider that ETH+TON requieres more Watts, I suppose that's not your problem. 

In which pool where you mining?. all the same connection to the same pool?

**Comment by pam1212** [comment]
> 

Thank you so much for the response!
Yes, they are all on the same pool. I am currently using Tonwhales.com right now. I have registered on their telegram and I am generating Ton which is great. 
Wattage: Yes, I have increased the wattage to account for the dual mining. I am getting roughly 61.50MH/s / 1.08 GH/s speeds. Core temps are around 35-40 degrees. I have all wattages monitored and temps are really good (TONS OF AIRFLOW).
For some reason it is fine for hours, then LA will ramp up. (for example, worker 1 was totally fine 10 minutes ago, and now:
 6.48-1min,    5.16-5min,  4.06-15min, LOAD AVERAGE) for a few minutes, and now back down.

**Comment by jgonzis** [comment]
> > 
> 
> Thank you so much for the response! Yes, they are all on the same pool. I am currently using Tonwhales.com right now. I have registered on their telegram and I am generating Ton which is great. Wattage: Yes, I have increased the wattage to account for the dual mining. I am getting roughly 61.50MH/s / 1.08 GH/s speeds. Core temps are around 35-40 degrees. I have all wattages monitored and temps are really good (TONS OF AIRFLOW). For some reason it is fine for hours, then LA will ramp up. (for example, worker 1 was totally fine 10 minutes ago, and now: 6.48-1min, 5.16-5min, 4.06-15min, LOAD AVERAGE) for a few minutes, and now back down.

We hope next 1.44 will solve lot of the tonwhales problems... that cause to the miner too
