### ISSUE TITLE
Some cards not used

### ISSUE THREAD

**Issue by mans71** [Lolliedieb/lolMiner-releases#1164]
I have a 100% stable rig with enough power supply and 8 X A2000. For some reason some of the cards are not used for mining TON. Which cards that are not used are random for each restart of the server. Also, MH on each card are quite different for no obvious reason. 

Using latest HiveOS with lolMiner 1.43

```
Statistics (19:41:34); Uptime: 6h 38m 3s 
Algorithm 1: Ethash 
Connected to: eth-se.flexpool.io:4444 (5ms latency) 
Algorithm 2: SHA256-TON 
Connected to: https://server1.whalestonpool.com:443 (26ms latency) 

      Name       Speed    Pool    Shares    Best    Eff.    Speed    Pool
                  Mh/s    Mh/s    A/S/Hw   Share  Mh/s/W     Mh/s    Mh/s
GPU 0 RTX A2000  32.49   34.00   203/0/0    1.7T   0.468   519.69  333.77
GPU 1 RTX A2000  35.56   34.84   208/0/0    2.2T   0.511   284.47  207.17
GPU 2 RTX A2000  43.26   44.22   264/0/0    3.4T   0.627     0.00    0.00
GPU 3 RTX A2000  43.26   46.06   275/0/0    1.3T   0.626     0.00    0.00
GPU 4 RTX A2000  43.18   43.04   257/0/0  997.3G   0.628     0.00    0.00
GPU 5 RTX A2000  34.15   33.50   200/0/0  305.9G   0.491   273.16  184.15
GPU 6 RTX A2000  43.16   41.87   250/0/0  473.3G   0.623    21.58   23.02
GPU 7 RTX A2000  43.18   40.03   239/0/0    3.4T   0.623     0.00    0.00
--------------------------- 
Total           318.24  317.55  1896/0/0    3.4T   0.574  1098.90  748.11
```

**Comment by Cougarvsd** [comment]
I have three A2000 in my rig and they dont dual mine either (rest does).

**Comment by jgonzis** [comment]
Th

> I have a 100% stable rig with enough power supply and 8 X A2000. For some reason some of the cards are not used for mining TON. Which cards that are not used are random for each restart of the server. Also, MH on each card are quite different for no obvious reason.
> 
> Using latest HiveOS with lolMiner 1.43
> 
> ```
> Statistics (19:41:34); Uptime: 6h 38m 3s 
> Algorithm 1: Ethash 
> Connected to: eth-se.flexpool.io:4444 (5ms latency) 
> Algorithm 2: SHA256-TON 
> Connected to: https://server1.whalestonpool.com:443 (26ms latency) 
> 
>       Name       Speed    Pool    Shares    Best    Eff.    Speed    Pool
>                   Mh/s    Mh/s    A/S/Hw   Share  Mh/s/W     Mh/s    Mh/s
> GPU 0 RTX A2000  32.49   34.00   203/0/0    1.7T   0.468   519.69  333.77
> GPU 1 RTX A2000  35.56   34.84   208/0/0    2.2T   0.511   284.47  207.17
> GPU 2 RTX A2000  43.26   44.22   264/0/0    3.4T   0.627     0.00    0.00
> GPU 3 RTX A2000  43.26   46.06   275/0/0    1.3T   0.626     0.00    0.00
> GPU 4 RTX A2000  43.18   43.04   257/0/0  997.3G   0.628     0.00    0.00
> GPU 5 RTX A2000  34.15   33.50   200/0/0  305.9G   0.491   273.16  184.15
> GPU 6 RTX A2000  43.16   41.87   250/0/0  473.3G   0.623    21.58   23.02
> GPU 7 RTX A2000  43.18   40.03   239/0/0    3.4T   0.623     0.00    0.00
> --------------------------- 
> Total           318.24  317.55  1896/0/0    3.4T   0.574  1098.90  748.11
> ```



> I have three A2000 in my rig and they dont dual mine either (rest does).

Problem is the PL of the A2000, they are ETH GPUs... they don't have more Power to give any extra... They are really good for ETH in terms of efficiency but they power limit is 70... so to get some TON you will loose lot of ETH...
