### ISSUE TITLE
1070 0mh/s and 1070 ti 200mh/s

### ISSUE THREAD

**Issue by DongerDomination** [Lolliedieb/lolMiner-releases#1165]
Is it not possible to mine Ton with the 1070? And is the reward of my 1070 ti with 200mh/s right? 
![Screenshot_20220208_202118](https://user-images.githubusercontent.com/99274327/153060111-c9811136-9690-4071-9dc3-10ef4bb2ed26.jpg)

**Comment by cool2hatex** [comment]
i have same problem which now shows 0.00 for everything

**Comment by jgonzis** [comment]
> Is it not possible to mine Ton with the 1070? And is the reward of my 1070 ti with 200mh/s right? ![Screenshot_20220208_202118](https://user-images.githubusercontent.com/99274327/153060111-c9811136-9690-4071-9dc3-10ef4bb2ed26.jpg)

with pascal more Power need it... 

try with --maxdualimpact 6 

I tested several Pascal and only 1070TI 1080 or 1080TI are able to give decent profit

**Comment by GuRuNa** [comment]
It work for me my 1070 in ETH+TON
lock voltage : 1000 mv , mem : 400
ETH : 21 , TON : 300
lolminer 1.44

**Comment by jgonzis** [comment]
> ![photo_2022-02-15_00-20-21](https://user-images.githubusercontent.com/99685758/153932114-98ef55fd-ba51-4210-b52a-6f779d8caff6.jpg) ![photo_2022-02-15_00-19-52](https://user-images.githubusercontent.com/99685758/153932121-6cef1374-358e-4122-aca0-b7366c532c92.jpg)

You will need to put PL to around 150W to have some TON, need more Watts. You will not get TON unless you increase the watts
