### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lexasub** [Lolliedieb/lolMiner-releases#1167]
Hello, i try run eth mining(and others). miner is crashes. os - gentoo
driver nvidia 470.86.
CUDA Version: 11.4  
gpu 3060lhr v2
![image](https://user-images.githubusercontent.com/16270007/153074079-2d0db9fe-0069-47ea-b528-77973d22c57c.png)
![image](https://user-images.githubusercontent.com/16270007/153074486-d8930743-09fa-4dda-bae4-4c14548c635c.png)
strace : 
[log.log](https://github.com/Lolliedieb/lolMiner-releases/files/8027427/log.log)

**Comment by lexasub** [comment]
in other miner programs all is good

**Comment by jgonzis** [comment]
> Hello, i try run eth mining(and others). miner is crashes. os - gentoo driver nvidia 470.86. CUDA Version: 11.4 gpu 3060lhr v2 ![image](https://user-images.githubusercontent.com/16270007/153074079-2d0db9fe-0069-47ea-b528-77973d22c57c.png) ![image](https://user-images.githubusercontent.com/16270007/153074486-d8930743-09fa-4dda-bae4-4c14548c635c.png) strace : [log.log](https://github.com/Lolliedieb/lolMiner-releases/files/8027427/log.log)

Could you try 1.44 please?

Also it could be the file configuration too.

**Comment by lexasub** [comment]
![image](https://user-images.githubusercontent.com/16270007/153096710-0d2316b5-6319-4679-80dd-be79263436c9.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/16270007/153096710-0d2316b5-6319-4679-80dd-be79263436c9.png)

Could you share your running line?

**Comment by lexasub** [comment]
i tryed

> > ![image](https://user-images.githubusercontent.com/16270007/153096710-0d2316b5-6319-4679-80dd-be79263436c9.png)
> 
> Could you share your running line?

i tryed use conf file
 algo=ETHASH
pool=eth.2miners.com:2020
user=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker
and i tryed ./lolMiner --algo ETHASH --pool eth.2miners.com:2020 --user 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker

**Comment by lexasub** [comment]
[log.log](https://github.com/Lolliedieb/lolMiner-releases/files/8030991/log.log)

**Comment by jgonzis** [comment]
> i tryed
> 
> > > ![image](https://user-images.githubusercontent.com/16270007/153096710-0d2316b5-6319-4679-80dd-be79263436c9.png)
> > 
> > 
> > Could you share your running line?
> 
> i tryed use conf file(./lolMiner) algo=ETHASH pool=eth.2miners.com:2020 user=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker and i tryed ./lolMiner --algo ETHASH --pool eth.2miners.com:2020 --user 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker

Could you share the error of /var/log/syslog?

**Comment by lexasub** [comment]
> > i tryed
> > > > ![image](https://user-images.githubusercontent.com/16270007/153096710-0d2316b5-6319-4679-80dd-be79263436c9.png)
> > > 
> > > 
> > > Could you share your running line?
> > 
> > 
> > i tryed use conf file(./lolMiner) algo=ETHASH pool=eth.2miners.com:2020 user=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker and i tryed ./lolMiner --algo ETHASH --pool eth.2miners.com:2020 --user 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker
> 
> Could you share the error of /var/log/syslog?
dmesg(i doesn't have /var/log/syslog)
lollMiner[23566]: segfault at 7fc415c17c80 ip 00007fc415c17c80 sp 00007ffe27822d38 error 15
[43645.065178] Code: 00 00 f0 72 a2 12 c4 7f 00 00 40 9e a2 12 c4 7f 00 00 40 9f a2 12 c4 7f 00 00 00 93 a2 12 c4 7f 00 00 10 6a a2 12 c4 7f 00 00 <c0> ff a2 12 c4 7f 00 00 40 78 a2 12 c4 7f 00 00 10 75 a2 12 c4 7f

**Comment by baramuse** [comment]
I've got a segfault error 15 as well. Don't know if it relates or if I should create another issue.
I does happen randomly, not systematically at startup for example.
`lolMiner 1.46, N 470.82.00, 5.10.0-hiveos #721`
Don't know what other useful information you need
```
Feb 22 18:17:06 Pigeonnier kernel: [21464.840936][T17172] lolMiner[17172]: segfault at 7f0ce40008d0 ip 00007f0ce40008d0 sp 00007f0d157fbd68 error 15
Feb 22 18:17:06 Pigeonnier kernel: [21464.840947][T17172] Code: 00 00 00 b0 04 00 00 00 00 00 00 b0 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 55 02 00 00 00 00 00 00 <07> 07 07 07 07 07 07 07 02 06 00 00 00 07 01 03 00 01 00 01 00 02
```

**Comment by jgonzis** [comment]
> 

Which TON pool where you using?. Could you get last message from the miner? I don't know if you have logs-on.

**Comment by baramuse** [comment]
> > 
> 
> Which TON pool where you using?. Could you get last message from the miner? I don't know if you have logs-on.

```
---------------------------------------------
Statistics (18:43:17); Uptime: 0h 26m 4s
The api is active on port 44444
Algorithm 1: Ethash
Connected to: eth.2miners.com:2020 (39ms latency)
Algorithm 2: SHA256-TON
Connected to: https://pool.services.tonwhales.com:443 (101ms latency)

      Name         Speed    Pool  Shares    Best    Eff.     Speed     Pool
                    Mh/s    Mh/s  A/S/Hw   Share  Mh/s/W      Mh/s     Mh/s
GPU 0 RTX 3060 Ti  45.19   16.74   3/0/0   33.8G   0.273   1408.77  1406.03
GPU 1 RTX 3060 Ti  45.17   39.06   7/0/0   31.0G   0.297   1408.26  1054.52
GPU 2 RTX 3060 Ti  45.19   22.32   4/0/0   39.2G   0.297   1408.84   878.77
GPU 3 RTX 3060 Ti  45.18   33.48   6/0/0   52.8G   0.283   1393.08   527.26
GPU 4 RTX 3060 Ti  45.21   44.64   8/0/0  431.5G   0.279   1409.21   527.26
GPU 5 RTX 3060 Ti  45.11   50.22   9/0/0  273.1G   0.292   1405.80  1230.27
GPU 6 RTX 3060     35.79   44.64   8/0/0   29.8G   0.234   1197.26  1230.27
GPU 7 RTX 3060     35.77   27.90   5/0/0   54.2G   0.234   1196.44  1581.78
---------------------------
Total             342.60  278.97  50/0/0  431.5G   0.274  10827.66  8436.15

        Shares    Best    Eff.   Power  CCLK  MCLK  Core  Fan  --lhrtune
        A/S/Hw   Share  Mh/s/W       W   MHz   MHz  Temp  Pct
GPU 0    8/0/0   20.9T   8.511   165.0  1440  8100    71   98       23.6
GPU 1    6/0/0    4.9T   9.249   151.8  1440  8100    66   76       23.4
GPU 2    5/0/0    5.2T   9.254   151.7  1440  8100    63   72       23.4
GPU 3    3/0/0    2.1T   8.739   158.9  1440  8100    61   96       23.4
GPU 4    3/0/0  402.7T   8.689   161.7  1440  8100    70   81       22.4
GPU 5    7/0/0    1.1T   9.091   154.1  1440  8100    62   71       22.0
GPU 6    7/0/0    3.9T   7.830   152.4  1650  8600    61   70       19.4
GPU 7    9/0/0    5.6T   7.833   152.2  1650  8600    57   64       18.6
---------------------------
Total   48/0/0  402.7T   8.649  1247.9
---------------------------------------------
Ethash: Average speed (10s): 45.19 Mh/s | 45.17 Mh/s | 45.19 Mh/s | 45.18 Mh/s | 45.21 Mh/s | 45.11 Mh/s | 35.79 Mh/s | 35.77 Mh/s Total: 342.61 Mh/s
SHA256-TON: Average speed (10s): 1408.82 Mh/s | 1408.13 Mh/s | 1408.84 Mh/s | 1393.10 Mh/s | 1409.25 Mh/s | 1405.71 Mh/s | 1197.31 Mh/s | 1196.49 Mh/s Total: 10827.64 Mh/s
New job received: 0x32b903 Epoch: 475 Difficulty: 8.73G
```

**Comment by jgonzis** [comment]
> > > 
> > 
> > 
> > Which TON pool where you using?. Could you get last message from the miner? I don't know if you have logs-on.
> 
> that's the last logs before the crash
> 
> ```
> ---------------------------------------------
> Statistics (18:43:17); Uptime: 0h 26m 4s
> The api is active on port 44444
> Algorithm 1: Ethash
> Connected to: eth.2miners.com:2020 (39ms latency)
> Algorithm 2: SHA256-TON
> Connected to: https://pool.services.tonwhales.com:443 (101ms latency)
> 
>       Name         Speed    Pool  Shares    Best    Eff.     Speed     Pool
>                     Mh/s    Mh/s  A/S/Hw   Share  Mh/s/W      Mh/s     Mh/s
> GPU 0 RTX 3060 Ti  45.19   16.74   3/0/0   33.8G   0.273   1408.77  1406.03
> GPU 1 RTX 3060 Ti  45.17   39.06   7/0/0   31.0G   0.297   1408.26  1054.52
> GPU 2 RTX 3060 Ti  45.19   22.32   4/0/0   39.2G   0.297   1408.84   878.77
> GPU 3 RTX 3060 Ti  45.18   33.48   6/0/0   52.8G   0.283   1393.08   527.26
> GPU 4 RTX 3060 Ti  45.21   44.64   8/0/0  431.5G   0.279   1409.21   527.26
> GPU 5 RTX 3060 Ti  45.11   50.22   9/0/0  273.1G   0.292   1405.80  1230.27
> GPU 6 RTX 3060     35.79   44.64   8/0/0   29.8G   0.234   1197.26  1230.27
> GPU 7 RTX 3060     35.77   27.90   5/0/0   54.2G   0.234   1196.44  1581.78
> ---------------------------
> Total             342.60  278.97  50/0/0  431.5G   0.274  10827.66  8436.15
> 
>         Shares    Best    Eff.   Power  CCLK  MCLK  Core  Fan  --lhrtune
>         A/S/Hw   Share  Mh/s/W       W   MHz   MHz  Temp  Pct
> GPU 0    8/0/0   20.9T   8.511   165.0  1440  8100    71   98       23.6
> GPU 1    6/0/0    4.9T   9.249   151.8  1440  8100    66   76       23.4
> GPU 2    5/0/0    5.2T   9.254   151.7  1440  8100    63   72       23.4
> GPU 3    3/0/0    2.1T   8.739   158.9  1440  8100    61   96       23.4
> GPU 4    3/0/0  402.7T   8.689   161.7  1440  8100    70   81       22.4
> GPU 5    7/0/0    1.1T   9.091   154.1  1440  8100    62   71       22.0
> GPU 6    7/0/0    3.9T   7.830   152.4  1650  8600    61   70       19.4
> GPU 7    9/0/0    5.6T   7.833   152.2  1650  8600    57   64       18.6
> ---------------------------
> Total   48/0/0  402.7T   8.649  1247.9
> ---------------------------------------------
> Ethash: Average speed (10s): 45.19 Mh/s | 45.17 Mh/s | 45.19 Mh/s | 45.18 Mh/s | 45.21 Mh/s | 45.11 Mh/s | 35.79 Mh/s | 35.77 Mh/s Total: 342.61 Mh/s
> SHA256-TON: Average speed (10s): 1408.82 Mh/s | 1408.13 Mh/s | 1408.84 Mh/s | 1393.10 Mh/s | 1409.25 Mh/s | 1405.71 Mh/s | 1197.31 Mh/s | 1196.49 Mh/s Total: 10827.64 Mh/s
> New job received: 0x32b903 Epoch: 475 Difficulty: 8.73G
> ```

let's try to see if new 1.46a solve that issue with the connection... Because I don't know where it could be the problem now... If continue and you get how to get it I will try in my rigs too to try to found that segfault...

The only strange think is the HiveOS Version do you have, for example: 5.10.0-hiveos #83 I'm in this one, you are also in tonwhales... seems to be working great... I don't know if you could use new connection: 

wss://stratum.whalestonpool.com/stratum

I'm on it without any inconvenient with the test version for several days

**Comment by baramuse** [comment]
> wss://stratum.whalestonpool.com/stratum

ok I set up the new connection, will see how it behaves
I don't know yet how to install a miner that's not part of an hive's update.

I can try as well to install a newer image of HiveOS : 
```
> Loading Hive OS images list from https://download.hiveos.farm/history/
> Select version to install
 0) Exit
 1) hiveos-0.6-212-stable@211201.img.xz · Latest Stable · K 5.10.83 · N 470.86 · A OpenCL 20.40-5.11.1001 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs
 2) hiveos-0.6-210-beta@210914.img.xz · Latest Beta · K 5.10.60 · N 470.63.01 · A OpenCL 20.40-5.11.0825 · Beta Image based on modern Linux LTS kernel for new hardware and latest drivers for AMD and Nvidia GPUs
 3) hiveos-0.6-211-stable@211104.img.xz · K 5.10.72 · N 470.82.00 · A OpenCL 20.40-5.11.1001 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs
 4) hiveos-0.6-208-stable@210818.img.xz · K 5.4.140 · N 460.91.03 · A OpenCL 20.40-5.11.0701 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs incl. RX 6600 series
 5) hiveos-0.6-208-beta@210818.img.xz · K 5.10.60 · N 470.63.01 · A OpenCL 20.40-5.11.0701 · Beta Image based on modern Linux LTS kernel for new hardware and latest Nvidia and AMD GPUs
 6) hiveos-0.6-205-stable@210715.img.xz · K 5.4.132 · N 460.84 · A OpenCL 20.40-5.11.0701 · Dual-Boot / Image with support for latest Nvidia and AMD GPUs incl. RX 6700/6800/6900 series
 7) hiveos-0.6-205-beta@210715.img.xz · K 5.10.50 · N 465.31 · A OpenCL 20.40-5.11.0701 · Beta Image for new hardware and latest AMD and Nvidia GPUs
 8) hiveos-0.6-203-stable@210403.img.xz · K 5.4.108 · N 460.67 · A OpenCL 20.40-5.9.0325 · Dual-Boot / Universal image for AMD and Nvidia
 9) hiveos-0.6-200-beta@210303.img.xz · K 5.4.99 · N 460.56 · A OpenCL 20.40 · Beta Image with initial AMD BigNavi support
10) hiveos-0.6-172@201105.zip · K 5.0.21 · N 450.66 · A OpenCL legacy+pal 20.30 · Dual-Boot / Universal image for AMD and Nvidia
11) hiveos-0.6-97@191128.zip · K 5.0.21 · N 440.31 · A OpenCL legacy+pal 19.20 · Dual-Boot / Legacy Stable based on Ubuntu 18.04 (EOL)
12) hiveos-0.6-39@190503.zip · K 4.13.16 · N 418.56 · A 18.10-572953 · MBR Boot / Legacy Stable based on Ubuntu 16.04 (EOL)
>
```
But  I won't do that before the end of the week when I'll have physical access to the RIG in case of an  OS upgrade problem

**Comment by jgonzis** [comment]
> > wss://stratum.whalestonpool.com/stratum
> 
> ok I set up the new connection, will see how it behaves I don't know yet how to install a miner that's not part of an hive's update.
> 
> I can try as well to install a newer image of HiveOS :
> 
> ```
> > Loading Hive OS images list from https://download.hiveos.farm/history/
> > Select version to install
>  0) Exit
>  1) hiveos-0.6-212-stable@211201.img.xz · Latest Stable · K 5.10.83 · N 470.86 · A OpenCL 20.40-5.11.1001 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs
>  2) hiveos-0.6-210-beta@210914.img.xz · Latest Beta · K 5.10.60 · N 470.63.01 · A OpenCL 20.40-5.11.0825 · Beta Image based on modern Linux LTS kernel for new hardware and latest drivers for AMD and Nvidia GPUs
>  3) hiveos-0.6-211-stable@211104.img.xz · K 5.10.72 · N 470.82.00 · A OpenCL 20.40-5.11.1001 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs
>  4) hiveos-0.6-208-stable@210818.img.xz · K 5.4.140 · N 460.91.03 · A OpenCL 20.40-5.11.0701 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs incl. RX 6600 series
>  5) hiveos-0.6-208-beta@210818.img.xz · K 5.10.60 · N 470.63.01 · A OpenCL 20.40-5.11.0701 · Beta Image based on modern Linux LTS kernel for new hardware and latest Nvidia and AMD GPUs
>  6) hiveos-0.6-205-stable@210715.img.xz · K 5.4.132 · N 460.84 · A OpenCL 20.40-5.11.0701 · Dual-Boot / Image with support for latest Nvidia and AMD GPUs incl. RX 6700/6800/6900 series
>  7) hiveos-0.6-205-beta@210715.img.xz · K 5.10.50 · N 465.31 · A OpenCL 20.40-5.11.0701 · Beta Image for new hardware and latest AMD and Nvidia GPUs
>  8) hiveos-0.6-203-stable@210403.img.xz · K 5.4.108 · N 460.67 · A OpenCL 20.40-5.9.0325 · Dual-Boot / Universal image for AMD and Nvidia
>  9) hiveos-0.6-200-beta@210303.img.xz · K 5.4.99 · N 460.56 · A OpenCL 20.40 · Beta Image with initial AMD BigNavi support
> 10) hiveos-0.6-172@201105.zip · K 5.0.21 · N 450.66 · A OpenCL legacy+pal 20.30 · Dual-Boot / Universal image for AMD and Nvidia
> 11) hiveos-0.6-97@191128.zip · K 5.0.21 · N 440.31 · A OpenCL legacy+pal 19.20 · Dual-Boot / Legacy Stable based on Ubuntu 18.04 (EOL)
> 12) hiveos-0.6-39@190503.zip · K 4.13.16 · N 418.56 · A 18.10-572953 · MBR Boot / Legacy Stable based on Ubuntu 16.04 (EOL)
> >
> ```
> 
> But I won't do that before the end of the week when I'll have physical access to the RIG in case of an OS upgrade problem

Select 1 please and later write yes 
![image](https://user-images.githubusercontent.com/38668405/155201278-5434e77d-2eb6-4633-bca3-a7a6b9c82aef.png)

**Comment by baramuse** [comment]
> 

I'll do that only when I'll have access to the Rig, I never performed a system upgrade remotely before and I don't want it to "crash" the whole rig until I got physical access and fix it.

**Comment by jgonzis** [comment]
> > 
> 
> I'll do that only when I'll have access to the Rig, I never performed a system upgrade remotely before and I don't want it to "crash" the whole rig until I got physical access and fix it.

Perfect!! always better a restart that a end rig haha :-)

**Comment by baramuse** [comment]
> > > 
> > 
> > 
> > I'll do that only when I'll have access to the Rig, I never performed a system upgrade remotely before and I don't want it to "crash" the whole rig until I got physical access and fix it.
> 
> Perfect!! always better a restart that a end rig haha :-)

Call me paranoid but I've worked long enough in IT to know that nothing ever go as smoothly as planned.. and when it does, just take it as a freebie ^^

**Comment by jgonzis** [comment]
> > > > 
> > > 
> > > 
> > > I'll do that only when I'll have access to the Rig, I never performed a system upgrade remotely before and I don't want it to "crash" the whole rig until I got physical access and fix it.
> > 
> > 
> > Perfect!! always better a restart that a end rig haha :-)
> 
> Call me paranoid but I've worked long enough in IT to know that nothing ever go as smoothly as planned.. and when it does, just take it as a freebie ^^

I found 2 more rigs that with 5.10.0-hiveos #72 crashing like you have...

**Comment by baramuse** [comment]
well I'll see if I have anymore crashes just by using the new stratum address in the meanwhile

**Comment by jgonzis** [comment]
> well I'll see if I have anymore crashes just by using the new stratum address in the meanwhile, as I was using the http one before

testing 1.46a and no crash at the moment... I will confirm it ...

**Comment by jgonzis** [comment]
> well I'll see if I have anymore crashes just by using the new stratum address in the meanwhile, as I was using the http one before

Try to update to 1.46a, to see if resolves to you too:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start

**Comment by baramuse** [comment]
> > well I'll see if I have anymore crashes just by using the new stratum address in the meanwhile, as I was using the http one before
> 
> Try to update to 1.46a, to see if resolves to you too: cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start

ok I just did update the miner to 1.46a

Got a few DAG errors this time (but self fixing)
```
GPU 5: DAG verification detected 1206 defect segment(s)
GPU 5: DAG repair will be started. This may take a moment.
GPU 1: DAG verification detected 1172 defect segment(s)
GPU 1: DAG repair will be started. This may take a moment.
GPU 3: DAG verification detected 1199 defect segment(s)
GPU 3: DAG repair will be started. This may take a moment.
GPU 2: DAG verification detected 885 defect segment(s)
GPU 2: DAG repair will be started. This may take a moment.
GPU 4: DAG verification detected 1206 defect segment(s)
GPU 4: DAG repair will be started. This may take a moment.
```

**Comment by jgonzis** [comment]
> > > well I'll see if I have anymore crashes just by using the new stratum address in the meanwhile, as I was using the http one before
> > 
> > 
> > Try to update to 1.46a, to see if resolves to you too: cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start
> 
> ok I just did update the miner to 1.46a
> 
> Got a few DAG errors this time (but self fixing)
> 
> ```
> GPU 5: DAG verification detected 1206 defect segment(s)
> GPU 5: DAG repair will be started. This may take a moment.
> GPU 1: DAG verification detected 1172 defect segment(s)
> GPU 1: DAG repair will be started. This may take a moment.
> GPU 3: DAG verification detected 1199 defect segment(s)
> GPU 3: DAG repair will be started. This may take a moment.
> GPU 2: DAG verification detected 885 defect segment(s)
> GPU 2: DAG repair will be started. This may take a moment.
> GPU 4: DAG verification detected 1206 defect segment(s)
> GPU 4: DAG repair will be started. This may take a moment.
> ```

I see now HiveOS is crashed... but any feedback?

**Comment by baramuse** [comment]
Well, no segfault since yesterday on the 3 rigs... so I'd say that fixed it for now !

**Comment by jgonzis** [comment]
> Well, no segfault since yesterday on the 3 rigs... so I'd say that fixed it for now !

Really Many thanks for the feedback :-)

**Comment by lexasub** [comment]
it also fix my problem too, thank you very much))
