### ISSUE TITLE
{HELP}`GLIBC_2.25' not found (required by ./lolMiner)

### ISSUE THREAD

**Issue by AhrimanSefid** [Lolliedieb/lolMiner-releases#1168]
Hi Admin.
can help me fixed Error:

./lolMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./lolMiner)

**Comment by jgonzis** [comment]
> Hi Admin. can help me fixed Error:
> 
> ./lolMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./lolMiner)

The problem is your hiveos kernel... please update do:

hive-replace --list
1
yes

**Comment by AhrimanSefid** [comment]
./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user BTC:wallet.1 --tls 0 how?

**Comment by AhrimanSefid** [comment]
![image](https://user-images.githubusercontent.com/1332246/153087048-f50a003c-ca45-49db-b877-dd1ab9d3002f.png)

**Comment by AhrimanSefid** [comment]
![image](https://user-images.githubusercontent.com/1332246/153087204-c5e3c5f7-aaa0-4dcf-8ac6-3171fded0717.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/1332246/153087204-c5e3c5f7-aaa0-4dcf-8ac6-3171fded0717.png)

Sorry I thought you hat HiveOS that happens with old Ubuntu... Do you any options to update?

**Comment by AhrimanSefid** [comment]
yes try update not work.

**Comment by jgonzis** [comment]
> yes try update not work.

Sorry, but OS need it...
