### ISSUE TITLE
pool port value recognition broken with dual mining

### ISSUE THREAD

**Issue by hbouma** [Lolliedieb/lolMiner-releases#1169]
When trying to dual mine ethereum with Ton, I can't use --dualpool https://next.ton-pool.com with --pool s-us.comining.io:9999  . I get the following error:

Error: Your input to --pool "s-us.comining.io:9999" can not be split into a address and a port. Please use format <pool address>:<pool port>.

Any dualpool server that doesn''t have a port value will cause this error, like the wss://pplns.toncoinpool.io/stratum one as well. I don't know how people are able to use these servers. I'm guessing the issue is that I'm trying to use awesome miner so the command line options are not coming in the order you normally expect where the dualpool is being issued first. I'm not sure how to change the order but thought its something to raise here as well. 

Thanks as always for your great miner!

**Comment by jgonzis** [comment]
> When trying to dual mine ethereum with Ton, I can't use --dualpool https://next.ton-pool.com with --pool s-us.comining.io:9999 . I get the following error:
> 
> Error: Your input to --pool "s-us.comining.io:9999" can not be split into a address and a port. Please use format :.
> 
> Any dualpool server that doesn''t have a port value will cause this error, like the wss://pplns.toncoinpool.io/stratum one as well. I don't know how people are able to use these servers. I'm guessing the issue is that I'm trying to use awesome miner so the command line options are not coming in the order you normally expect where the dualpool is being issued first. I'm not sure how to change the order but thought its something to raise here as well.
> 
> Thanks as always for your great miner!

Could you share you complete configuration.  That normally happens for and incorrect configuration. Which version 1.43 or 1.44?

**Comment by hbouma** [comment]
I'm using 1.44 because of the stale share issue. When I tried --dualpool ton.hashrate.to:4003  it would work without error, but you are right I do think its a configuration error as I can get it to run now.  However, I'm still having a lot of problems like with the next.ton-pool.com:

Websocket handshare done with pool https://next.ton-pool.ccom
Ton job with difficulty 68.72G and giver Ef-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMMn2 received.
Pool https://next.ton-pool.club timeout or send defect message: ""
Pool https://next.ton-pool.club timeout or send defect message: ""

Different error with wss://pplns.toncoinpool.io/stratum : 

Subscribed to stratum server. Pool difficulty: 400.00G
Received a defect stratum message: conversion of data to type "bool" failed

These errors happen on both Windows 10 using your batch file and Linux (HiveOS). I'm also stuck in that my rig of Polaris cards can't dual mine either. It reports 2x the expected TON hash rate , shows new TON jobs, but never reports a single found share. Mining TON solo works though.

I'll close this issue shortly though since these are not directly related to the original issue.

Thanks!

**Comment by jgonzis** [comment]
> I'm using 1.44 because of the stale share issue. When I tried --dualpool ton.hashrate.to:4003 it would work without error. So I've been using that pool for now. But you are right I do think its a configuration error as I can get it to at least start with the other pools. However, I'm still having a lot of problems like with the next.ton-pool.com:
> 
> Websocket handshare done with pool https://next.ton-pool.ccom Ton job with difficulty 68.72G and giver Ef-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMMn2 received. Pool https://next.ton-pool.club timeout or send defect message: "" Pool https://next.ton-pool.club timeout or send defect message: ""
> 
> Different error with wss://pplns.toncoinpool.io/stratum :
> 
> Subscribed to stratum server. Pool difficulty: 400.00G Received a defect stratum message: conversion of data to type "bool" failed
> 
> These errors happen on both Windows 10 using your batch file and Linux (HiveOS). I'm also stuck in that my rig of Polaris cards can't dual mine either on Windows 10. It reports 2x the expected TON hash rate , shows new TON jobs, but never reports a single found share. Mining TON solo works though.
> 
> I'll close this issue shortly though since these are not directly related to the original issue.
> 
> Thanks!

The error of toncoinpool.io is the workerName, in HiveOS  take some strange spaces and that is the problem. Icemining.ca is like ETH pool they don't care about that strange characters. 
I suppose same problem is for tonpool with workerName,  so it should be the flightsheet I think

**Comment by hbouma** [comment]
The ton worker name is being set to --dualworker hal9000  . it shouldn't have any strange characters. but thanks.

**Comment by jgonzis** [comment]
That should be OK then in toncoinpool.io, ton-pool haven't got dualworker. It is been complicated the pools, we hope new icemining.ca with the standard protocol of eth helps in that stability
