### ISSUE TITLE
Cannot run 1.18 version on RX 470 4Gb

### ISSUE THREAD

**Issue by Titomir** [Lolliedieb/lolMiner-releases#117]
Cannot run 1.18 version on XFX (Elpida) RX 470 4Gb / Error 0 GPU. Using on RaveOS

**Comment by Lucky21110** [comment]
Same here

**Comment by Lucky21110** [comment]
Fixed here you have to run driver 20.30 or 20.40. 👍

**Comment by jgonzis** [comment]
Great news... that could be on the usually problems of people with 1.18a in RaveOS.

Make the upgrade -b 8545-1850
