### ISSUE TITLE
LHR detected on non-LHR card

### ISSUE THREAD

**Issue by Xefier** [Lolliedieb/lolMiner-releases#1172]
How do I disable LHR tuning? None of the cards on this machine even have LHR end yet one of them detected LHR mode and started tuning it.

**Comment by xlminfei** [comment]
add "--lhrwait 60000"
this mean the LHR check will start 60000 seconds after the start of the miner

**Comment by jgonzis** [comment]
> How do I disable LHR tuning? None of the cards on this machine even have LHR end yet one of them detected LHR mode and started tuning it.

You can add in EXTRAPARAMETERS information --lhrtune off

**Comment by Xefier** [comment]
> add "--lhrwait 60000" this mean the LHR check will start 60000 seconds after the start of the miner

This not an actual solution because the same problem will then happen 16.66 hours later

**Comment by Xefier** [comment]
> 

This is what I was looking for, thanks

**Comment by Xefier** [comment]
> > How do I disable LHR tuning? None of the cards on this machine even have LHR end yet one of them detected LHR mode and started tuning it.
> 
> You can add in EXTRAPARAMETERS information --lhrtune off

This is what I was looking for, thanks
