### ISSUE TITLE
ETH + TON error ..  conversion of data to type "b" failed 

### ISSUE THREAD

**Issue by ibminer** [Lolliedieb/lolMiner-releases#1175]
I tried to set lolminer to miners ETH + TON on HiveOS last version on RTX3060Ti LHR.
I get this error and can't connect to  server ....

Received a defect stratum message: conversion of data to type "b" failed

**Comment by jgonzis** [comment]
> I tried to set lolminer to miners ETH + TON on HiveOS last version on RTX3060Ti LHR. I get this error and can't connect to server ....
> 
> Received a defect stratum message: conversion of data to type "b" failed

That is a problem with toncoinpool.com and the workername, please try in WorkerNAME of TONDUAL to write it manually please instead of %WORKER_NAME%. Thx
