### ISSUE TITLE
lol1.44 ETH+TON ton-pool.com WIN10 Error <title>Rate Limited</title>

### ISSUE THREAD

**Issue by vokforever** [Lolliedieb/lolMiner-releases#1176]
![image](https://user-images.githubusercontent.com/29547475/153158674-60c0f260-1e20-4500-9d09-46820b4bb82e.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/29547475/153158674-60c0f260-1e20-4500-9d09-46820b4bb82e.png)

Sorry for the inconvenience, It has been really complicated the pools problem of TON, only icemining.ca works without any issue at the moment with 1.44.


tonpool/toncoinpool - 1.43
tomwhales/icemining.ca - 1.44

Sure a 1.45 should come solving all the remains.
