### ISSUE TITLE
RTX 3060 Laptop GPU can't mine ETH

### ISSUE THREAD

**Issue by DNLINYJ** [Lolliedieb/lolMiner-releases#1178]
Version : 1.44
System : Windows 10 2004 x64
NVIDIA Driver Version : 462.35
Log :
![image](https://user-images.githubusercontent.com/82745795/153179285-b05d9642-956a-4de3-9258-dc76b96ef47b.png)

**Comment by adjustinthings** [comment]
Increase your memory

**Comment by DNLINYJ** [comment]
As far as I know, several people have encountered the same problem as me, and I can mine normally when I use NBMiner. ¯\_(ツ)_/¯ (Memory is 6144 MByte big, it should be enough to mine ETH)

**Comment by DNLINYJ** [comment]
In NBMiner, it seem work fine.
![image](https://user-images.githubusercontent.com/82745795/153181888-50963fc6-8221-4ae0-a41f-741ae47c0d25.png)

**Comment by jgonzis** [comment]
> Version : 1.44 System : Windows 10 2004 x64 NVIDIA Driver Version : 462.35 Log : ![image](https://user-images.githubusercontent.com/82745795/153179285-b05d9642-956a-4de3-9258-dc76b96ef47b.png)

PRoblem is not the 6Gb... Problem is the OC of the memory... Reduce it and it will work.

I'm really worried seeing you are at EPOCH 482 in NBMiner... when actual Epoch is 472...
