### ISSUE TITLE
Slower speed on ethash after upgrade to 1.43 and 1.44

### ISSUE THREAD

**Issue by grzech1991** [Lolliedieb/lolMiner-releases#1181]
Hi!

I would like to report a problem with a miner, I have a mixed rig. 6
nvidia non-LHR RTX3XXX cards, 1 RX 6700XT card and 3 nvidia LHR cards.
Full speed is approx. 680MH / s on ethash. After updating lolminer from
1.42 to 1.43 or 1.44 there is a decrease of about 1.5-2MH / s on the
whole rig. Request for help.

I mine only ethash, not ethash with ton.

Thanks in advance

**Comment by Sinyk7** [comment]
I lost about 100-120 MH on my 6900XT going from 1.43 to 1.44. Eth hashrate remains the same.

**Comment by gazaptr** [comment]
same here i am using 6900xt
lolminer 1.43 ver. 62mh eth and 3.6gh ton but after upgrade
lolminer 1.44 ver 28 mh eth and 300mh ton

i try single eth mine and befor upgrade(1.43 ver) 62 mh but lolminer 1.44 ver 28 mh eth
i try single TON mine and same gh here lolminer 1.43 and lolminer 1.44 ver 3,6gh

so problem eth mining pls fix it i am using hiveOs

**Comment by grzech1991** [comment]
STOP! I don't mine TON, only ethash!

**Comment by Mumpitz23** [comment]
Seems to be the result of reduced stale shares on NVidia cards when using Windows. Anyhow I'd like to have the option back to use 1.43 mode since I and I guess other haven't had problems with stales in 1.43

**Comment by grzech1991** [comment]
My lolminer working only on linux/hiveos.

**Comment by jgonzis** [comment]
> Hi!
> 
> I would like to report a problem with a miner, I have a mixed rig. 6 nvidia non-LHR RTX3XXX cards, 1 RX 6700XT card and 3 nvidia LHR cards. Full speed is approx. 680MH / s on ethash. After updating lolminer from 1.42 to 1.43 or 1.44 there is a decrease of about 1.5-2MH / s on the whole rig. Request for help.
> 
> I mine only ethash, not ethash with ton.
> 
> Thanks in advance

Question... if you return to 1.42 what are the Mhs?... Could you share some photos. So we can see if all is the same GPU or not... just to have an idea where is happening. 

It could be DAG Increase and needed more GPU... Let's try to see where it could be the problem

**Comment by grzech1991** [comment]
@jgonzis  https://imgur.com/a/tapxP9r check this, after & before

**Comment by jgonzis** [comment]
> @jgonzis https://imgur.com/a/tapxP9r check this, after & before

I found that the problem are only the LHR... could you try to run the 1.42, and check in Miner Log, which lhrtune value is there, and we can try it the same to the 1.44  with time it should get the same, is start lower and try later the max.

**Comment by mohsenk94** [comment]
I'm recently experiencing a loot of un-stable LHR tune values as well
Miner going for 1-2 hours tuning and still going...
I tested it with both 1.44 and 1.43 (Ethermine and Ton-poo.com ETH+TON Dual mine) and same problem... It used to tune them all in less than 30 minutes and start working.. the last 2 days I'm having the issue
I'm also facing "Defect Segment detection" from Dag Verification and the "Smart Dag recovery" is also not working properly and is not fixing the problem

In the meantime it seems to not work properly for me (Add to that, Ton-pool also had a lot of issues the last 2 days and making stuff worst) So I switched to ETH only with T-rex (All due respect, Trex is unlocking my LHR cards for 3~7% more than LOL ) 
Waiting for a stable release

**Comment by jgonzis** [comment]
> I'm recently experiencing a loot of un-stable LHR tune values as well Miner going for 1-2 hours tuning and still going... I tested it with both 1.44 and 1.43 (Ethermine and Ton-poo.com ETH+TON Dual mine) and same problem... It used to tune them all in less than 30 minutes and start working.. the last 2 days I'm having the issue I'm also facing "Defect Segment detection" from Dag Verification and the "Smart Dag recovery" is also not working properly and is not fixing the problem
> 
> In the meantime it seems to not work properly for me (Add to that, Ton-pool also had a lot of issues the last 2 days and making stuff worst) So I switched to ETH only with T-rex (All due respect, Trex is unlocking my LHR cards for 3~7% more than LOL ) Waiting for a stable release

It is true the pools problems of TON is quite big with https protocol.. they don't have prepared servers. I'm with icemining.ca working perfectly from yesterday.

Here you can ser how to connect if you want it to put part on it.
https://youtu.be/jA_ayYi-FS4

The LHR is good in Trex, they did a good job, but in NO LHR they are not the best: https://www.hashrate.no/tests/ampere
You can check a comparative of 1M test shares, to see pool reality, not reported.

**Comment by jgonzis** [comment]
> After 12h i still have impact for lower hashrate on LHR devices. 1.42 is faster.

Thx for the feedback, only in LHR right?.

**Comment by grzech1991** [comment]
Yes, this impact is only on LHR. Please fix this :) after adjusting for devfee and electricity costs, your miner on LHR is still better than t-rex or similar
