### ISSUE TITLE
How to make know my autotune LHR value in mine in logs not show eth lhr value.

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#1187]
![Screenshot_20220209-225052_Edge.jpg](https://user-images.githubusercontent.com/92781808/153256489-8abd79fa-5deb-479e-b8d9-cd85d2f106e6.jpg)

**Comment by jgonzis** [comment]
> ![Screenshot_20220209-225052_Edge.jpg](https://user-images.githubusercontent.com/92781808/153256489-8abd79fa-5deb-479e-b8d9-cd85d2f106e6.jpg)

I see it in the --lhrtune value, 8.6, 13.0, 6.6, .... There you have it :-)
