### ISSUE TITLE
Huge drop ETH mh for 1.44 ver lolminer

### ISSUE THREAD

**Issue by gazaptr** [Lolliedieb/lolMiner-releases#1188]
hii am using 6900xt
lolminer 1.43 ver. 62mh eth and 3.6gh ton but after upgrade
lolminer 1.44 ver 28 mh eth and 300mh ton

i try single eth mine and befor upgrade(1.43 ver) 62 mh but lolminer 1.44 ver 28 mh eth
i try single TON mine and same gh here lolminer 1.43 and lolminer 1.44 ver 4,6gh

so problem eth mining pls fix it i am using hiveOs

**Comment by jgonzis** [comment]
> hii am using 6900xt lolminer 1.43 ver. 62mh eth and 3.6gh ton but after upgrade lolminer 1.44 ver 28 mh eth and 300mh ton
> 
> i try single eth mine and befor upgrade(1.43 ver) 62 mh but lolminer 1.44 ver 28 mh eth i try single TON mine and same gh here lolminer 1.43 and lolminer 1.44 ver 4,6gh
> 
> so problem eth mining pls fix it i am using hiveOs

It is strange...  here 4 x 6900XT without any issue...  could you share some photos please?
![image](https://user-images.githubusercontent.com/38668405/153267306-70ccdaab-2f5c-4357-bb8c-b14baa53b812.png)

**Comment by Sn0whax** [comment]
No issues on 6900xt here either.

**Comment by gazaptr** [comment]
i solve this problem
i downgraded my hiveos by 0.6-212@220208 ver. but lol miner 1.44

**Comment by gazaptr** [comment]
hiveos last versiyon whit lolminer ver 1.44
![hiveos son versiyon](https://user-images.githubusercontent.com/99351745/153279461-31296bc1-084d-4e70-8b8c-fbf5750c4173.png)

**Comment by jgonzis** [comment]
> hiveos last versiyon whit lolminer ver 1.44 ![hiveos son versiyon](https://user-images.githubusercontent.com/99351745/153279461-31296bc1-084d-4e70-8b8c-fbf5750c4173.png)

Now I know why.... too much undervolt... core 2200 at 650 will never go... and more with ETH+TON

Copy my OC the 6900xt

**Comment by gazaptr** [comment]
thank you for answer

**Comment by jgonzis** [comment]
> thank you for answer

I hope that works 🤞
