### ISSUE TITLE
dual mining eth + ton, problem with ton for 3060 ti lhr

### ISSUE THREAD

**Issue by elio1454** [Lolliedieb/lolMiner-releases#1189]
Hi, i use dual mining eth + ton  but with 3060 ti Lhr , the ton hashrate it's 0

**Comment by jgonzis** [comment]
> Hi, i use dual mining eth + ton but with 3060 ti Lhr , the ton hashrate it's 0

Wait 1 minute to start to be sure is unlock

- Nvidia Driver 472.12
- User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe  as Administrator
- Power Limit 100%  MSI Afterburner

Other Tips and Tricks:
- Check Memory Temperature for Thermal in GDDR6x
- No Monitor Connected to that GPU
- Gen2 to the Mobo Slot
- Use Riser

**Comment by elio1454** [comment]
--cclk  ( number ?)
    Il giovedì 10 febbraio 2022, 10:15:24 CET, jgonzis ***@***.***> ha scritto:  
 
 



Hi, i use dual mining eth + ton but with 3060 ti Lhr , the ton hashrate it's 0


Wait 1 minute to start to be sure is unlock
   
   - Nvidia Driver 472.12
   - User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe as Administrator
   - Power Limit 100% MSI Afterburner

Other Tips and Tricks:
   
   - Check Memory Temperature for Thermal in GDDR6x
   - No Monitor Connected to that GPU
   - Gen2 to the Mobo Slot
   - Use Riser

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jgonzis** [comment]
> Hello driver 472.12 have others problems like unrealistic hashrate. Il venerdì 11 febbraio 2022, 11:41:25 CET, jgonzis ***@***.***> ha scritto:
> […](#)
> --cclk  ( number ?) Il giovedì 10 febbraio 2022, 10:15:24 CET, jgonzis @.> ha scritto: Hi, i use dual mining eth + ton but with 3060 ti Lhr , the ton hashrate it's 0 Wait 1 minute to start to be sure is unlock - Nvidia Driver 472.12 - User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe as Administrator - Power Limit 100% MSI Afterburner Other Tips and Tricks: - Check Memory Temperature for Thermal in GDDR6x - No Monitor Connected to that GPU - Gen2 to the Mobo Slot - Use Riser — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> Try with 1650 to start... if you are with monitor connected. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

Try to wait 1 min before start to be sure is unlock... try also to put for example --lhrwait 25 ...

**Comment by elio1454** [comment]
Hello, can i suggest  a dual mining eth + tent for next versions ?
    Il venerdì 11 febbraio 2022, 12:30:51 CET, jgonzis ***@***.***> ha scritto:  
 
 



Hello driver 472.12 have others problems like unrealistic hashrate. Il venerdì 11 febbraio 2022, 11:41:25 CET, jgonzis @.> ha scritto:
…
--cclk  ( number ?) Il giovedì 10 febbraio 2022, 10:15:24 CET, jgonzis @.> ha scritto: Hi, i use dual mining eth + ton but with 3060 ti Lhr , the ton hashrate it's 0 Wait 1 minute to start to be sure is unlock - Nvidia Driver 472.12 - User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe as Administrator - Power Limit 100% MSI Afterburner Other Tips and Tricks: - Check Memory Temperature for Thermal in GDDR6x - No Monitor Connected to that GPU - Gen2 to the Mobo Slot - Use Riser — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> Try with 1650 to start... if you are with monitor connected. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.>


Try to wait 1 min before start to be sure is unlock... try also to put for example --lhrwait 25 ...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jgonzis** [comment]
> Hello, can i suggest  a dual mining eth + tent for next versions ? Il venerdì 11 febbraio 2022, 12:30:51 CET, jgonzis ***@***.***> ha scritto: Hello driver 472.12 have others problems like unrealistic hashrate. Il venerdì 11 febbraio 2022, 11:41:25 CET, jgonzis @.> ha scritto: … --cclk  ( number ?) Il giovedì 10 febbraio 2022, 10:15:24 CET, jgonzis @.> ha scritto: Hi, i use dual mining eth + ton but with 3060 ti Lhr , the ton hashrate it's 0 Wait 1 minute to start to be sure is unlock - Nvidia Driver 472.12 - User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe as Administrator - Power Limit 100% MSI Afterburner Other Tips and Tricks: - Check Memory Temperature for Thermal in GDDR6x - No Monitor Connected to that GPU - Gen2 to the Mobo Slot - Use Riser — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> Try with 1650 to start... if you are with monitor connected. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> Try to wait 1 min before start to be sure is unlock... try also to put for example --lhrwait 25 ... — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

Problem is that Tent use memory.Equihash use  memory. So the dual is really then complicated

**Comment by elio1454** [comment]
Ok and eth + nim ?
    Il venerdì 11 febbraio 2022, 20:48:59 CET, jgonzis ***@***.***> ha scritto:  
 
 



Hello, can i suggest  a dual mining eth + tent for next versions ? Il venerdì 11 febbraio 2022, 12:30:51 CET, jgonzis @.> ha scritto: Hello driver 472.12 have others problems like unrealistic hashrate. Il venerdì 11 febbraio 2022, 11:41:25 CET, jgonzis @.> ha scritto: … --cclk  ( number ?) Il giovedì 10 febbraio 2022, 10:15:24 CET, jgonzis @.> ha scritto: Hi, i use dual mining eth + ton but with 3060 ti Lhr , the ton hashrate it's 0 Wait 1 minute to start to be sure is unlock - Nvidia Driver 472.12 - User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe as Administrator - Power Limit 100% MSI Afterburner Other Tips and Tricks: - Check Memory Temperature for Thermal in GDDR6x - No Monitor Connected to that GPU - Gen2 to the Mobo Slot - Use Riser — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> Try with 1650 to start... if you are with monitor connected. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> Try to wait 1 min before start to be sure is unlock... try also to put for example --lhrwait 25 ... — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.>


Problem is that Tent use memory.Equihash use memory. So the dual is really then complicated

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jgonzis** [comment]
Has to be analysed
