### ISSUE TITLE
lolminer 1.18 Error: Parsing error of "DEVICES" argument in json configuration.

### ISSUE THREAD

**Issue by riiikk** [Lolliedieb/lolMiner-releases#119]
Hi again, It seems I was a bit premature closing the issue...as two of my rigs shows the same error (as with v.1.17) after updating to 1.18 And I have identical rigs working with 1.18. And if I run 1.16 they both startup OK
![lolminer-error](https://user-images.githubusercontent.com/76701323/103844471-418edf00-509a-11eb-8227-635ae3429a7c.png)

the nonworking rig has lolminer_config.json looking like this:
{
    "DEFAULTS": {
        "DEVICES": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11
        ],
        "APIPORT": 42024
    },
    "ETHOS": {
        "COIN": "ETH",
        "POOLS": [

        ]
    }
}
/run/ethos/lolminer_config.json (END)

And the ones that are working have  json file that looks like this:
{
    "DEFAULTS": {
        "DEVICES": "AMD",
        "APIPORT": 42067
    },
    "ETHOS": {
        "COIN": "BEAM",
        "POOLS": [

        ]
    }
}

**Comment by Lolliedieb** [comment]
Ah ... cause the format is not 100% right ... 
Using "DEVICES" : "0,1,2,3,4,5,6,..." would work 
hmm ... I can create a fall back for 1.19 to get it right ... but better here remove that "DEVICES" line from the text file. Just do it, miner will work fine.

**Comment by riiikk** [comment]
Hm, It seems the file is recreated, or at least changing it don´t work...I will have to wait for your proposed fallback in 1.19 , so stuck on 1.16 for now.

Thanks for all good work

**Comment by Lolliedieb** [comment]
Fixed with release of 1.19
