### ISSUE TITLE
Unrealistic Hashrate Reported

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1190]
As the title says, unrealistic hashrates are being reported, or zero.

System was working fine and then I restarted it and that started to happen.

Tried version 1.43 and 1.44

![image](https://user-images.githubusercontent.com/49044292/153273129-92915605-b842-4802-89ac-2a38d0b57421.png)

**Comment by GTreaper** [comment]
Same problem for me

**Comment by jgonzis** [comment]
> As the title says, unrealistic hashrates are being reported, or zero.
> 
> System was working fine and then I restarted it and that started to happen.
> 
> Tried version 1.43 and 1.44
> 
> ![image](https://user-images.githubusercontent.com/49044292/153273129-92915605-b842-4802-89ac-2a38d0b57421.png)

Could you please report which GPU... which Drivers, which OC... it is imposible without information to help or to find any bug.

> Same problem for me

**Comment by GTreaper** [comment]
> > As the title says, unrealistic hashrates are being reported, or zero.
> > System was working fine and then I restarted it and that started to happen.
> > Tried version 1.43 and 1.44
> > ![image](https://user-images.githubusercontent.com/49044292/153273129-92915605-b842-4802-89ac-2a38d0b57421.png)
> 
> Could you please report which GPU... which Drivers, which OC... it is imposible without information to help or to find any bug.
> 
> > Same problem for me

As I had same issue I will provide with this information when I'm home. But for now, it's a 3080 ti, locked core at 1350mhz memory +1400, also tried with lower memory driver is a newer version not the newest as I game on this specific device.
I will check driver version later

**Comment by Vinasis01** [comment]
@jgonzis please re-open the issue, you asked for information 2 hours ago and I just saw it to reply but you closed it...

The rig has a mix of 8 LHR gpus (3070 TI and 3080), as for core clock and memory I've tried different settings ranging from low to high.

OS windows 10 - it was working fine till about 2-3 hours before posting the original post.

As for the driver I am using the 472.12

![image](https://user-images.githubusercontent.com/49044292/153401621-1bfa4d2f-f93e-4a60-aca7-92949ae4d76c.png)

**Comment by jgonzis** [comment]
> @jgonzis you asked for information 2 hours ago and I just saw it to reply but you closed it...
> 
> The rig has a mix of 8 LHR gpus (3070 TI and 3080), as for core clock and memory I've tried different settings ranging from low to high.
> 
> OS windows 10 - it was working fine till about 2-3 hours before posting the original post.
> 
> As for the driver I am using the 472.12
> 
> ![image](https://user-images.githubusercontent.com/49044292/153401621-1bfa4d2f-f93e-4a60-aca7-92949ae4d76c.png)

It closed but I continue answering, problem is that we need information to help. Without information,  please think how we are able to answer or help the people. It is really complicated. All big problem are comming from windows, problems with HiveOS, MMPOS or Raveos. 

Normally are same problems:

NO Nvidia Driver 472.12
PL is not to 100%
Not using Lock Core or lolMiner.exe not administrator to lock it
GDDR6X Memory Temperature, because please don't understand that ETH+TON requieres more Watts and that is more temperature. 

So without any information is imposible. We promise we try our best but we need information.
