### ISSUE TITLE
Hashrate watchdog issue for dual mining

### ISSUE THREAD

**Issue by FreshCloud330** [Lolliedieb/lolMiner-releases#1191]
Dual mining on hiveos and i tried to set hasharte watchdog for each algoritms but i am always getting this error: Ethash minimal hashrate is not set

**Comment by jgonzis** [comment]
> Dual mining on hiveos and i tried to set hasharte watchdog for each algoritms but i am always getting this error: Ethash minimal hashrate is not set

It could be that you didn't feel the right flight sheet with the 2nd coin, so only read the ETH and not also TON

**Comment by FreshCloud330** [comment]
![IMG_20220210_155801](https://user-images.githubusercontent.com/80773438/153413035-3f88ad8d-5b27-48d5-a357-e37a32b7b6d2.jpg)
![IMG_20220210_155747](https://user-images.githubusercontent.com/80773438/153413060-f8a1263a-4675-4de7-a8e8-08ce1deb2dc5.jpg)

This is how my settings are. Anything wrong?

**Comment by Sego88** [comment]
Same for me and other users. "We got Ethash minimal hashrate is not set" everytime the miner is booted. On watchdog settings etash and ton have been set according the previous picture. In case I set up my flight sheet using a single coin "ETH" and I add the following script in miner configuration "--dualmode TONDUAL --dualpool https://pool.services.tonwhales.com --dualuser TON_WALLET_ADDRESS" the error didn't appea but obviously I'm loosing the TON hasrate graphic and the watchdog monitoring.

**Comment by jgonzis** [comment]
> Same for me and other users. "We got Ethash minimal hashrate is not set" everytime the miner is booted. On watchdog settings etash and ton have been set according the previous picture. In case I set up my flight sheet using a single coin "ETH" and I add the following script in miner configuration "--dualmode TONDUAL --dualpool https://pool.services.tonwhales.com --dualuser TON_WALLET_ADDRESS" the error didn't appear but obviously I'm loosing the TON hasrate graphic and the watchdog monitoring.

> ![IMG_20220210_155801](https://user-images.githubusercontent.com/80773438/153413035-3f88ad8d-5b27-48d5-a357-e37a32b7b6d2.jpg) ![IMG_20220210_155747](https://user-images.githubusercontent.com/80773438/153413060-f8a1263a-4675-4de7-a8e8-08ce1deb2dc5.jpg)
> 
> This is how my settings are. Anything wrong?

Don't put the comma, I recommend instead of algo you choose miners... I have it like this:

![image](https://user-images.githubusercontent.com/38668405/153579398-528c90db-2860-415f-a735-ee057dd45ab8.png)

It is working for me properly. If a GPU crash lolMiner will stop mining and that values will go to 0 too

**Comment by Marcos-AV** [comment]
> ![image](https://user-images.githubusercontent.com/38668405/153579398-528c90db-2860-415f-a735-ee057dd45ab8.png)
> 
> It is working for me properly. If a GPU crash lolMiner will stop mining and that values will go to 0 too

Let me see if I understood correctly: In this case, you only insert the desired hashrate for the watchdog to act based on the first coin (ETH) and not the second (TON)?

**Comment by jgonzis** [comment]
> > ![image](https://user-images.githubusercontent.com/38668405/153579398-528c90db-2860-415f-a735-ee057dd45ab8.png)
> > It is working for me properly. If a GPU crash lolMiner will stop mining and that values will go to 0 too
> 
> Let me see if I understood correctly: In this case, you only insert the desired hashrate for the watchdog to act based on the first coin (ETH) and not the second (TON)?

Yes... if crash crash all... so not more need it

**Comment by jgonzis** [comment]
> > > > ![image](https://user-images.githubusercontent.com/38668405/153579398-528c90db-2860-415f-a735-ee057dd45ab8.png)
> > > > It is working for me properly. If a GPU crash lolMiner will stop mining and that values will go to 0 too
> > > 
> > > 
> > > Let me see if I understood correctly: In this case, you only insert the desired hashrate for the watchdog to act based on the first coin (ETH) and not the second (TON)?
> > 
> > 
> > Yes... if crash crash all... so not more need it
> 
> in my scenario tons mining can loose some mh sometimes. When it happens i want it reboot itself

How Can it loose it?... could you show that scenario to let me think how to solve it?.
Many  thanks 😊

**Comment by FreshCloud330** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/38668405/153579398-528c90db-2860-415f-a735-ee057dd45ab8.png)
> > > > > It is working for me properly. If a GPU crash lolMiner will stop mining and that values will go to 0 too
> > > > 
> > > > 
> > > > Let me see if I understood correctly: In this case, you only insert the desired hashrate for the watchdog to act based on the first coin (ETH) and not the second (TON)?
> > > 
> > > 
> > > Yes... if crash crash all... so not more need it
> > 
> > 
> > in my scenario tons mining can loose some mh sometimes. When it happens i want it reboot itself
> 
> How Can it loose it?... could you show that scenario to let me think how to solve it?. Many thanks 😊

I am not sure. i must get 920 mh but sometimes i get 880mh. i think this loose happening because of lhr tune. i know this is minimal difference btw

**Comment by FreshCloud330** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/38668405/153579398-528c90db-2860-415f-a735-ee057dd45ab8.png)
> > > > > > > It is working for me properly. If a GPU crash lolMiner will stop mining and that values will go to 0 too
> > > > > > 
> > > > > > 
> > > > > > Let me see if I understood correctly: In this case, you only insert the desired hashrate for the watchdog to act based on the first coin (ETH) and not the second (TON)?
> > > > > 
> > > > > 
> > > > > Yes... if crash crash all... so not more need it
> > > > 
> > > > 
> > > > in my scenario tons mining can loose some mh sometimes. When it happens i want it reboot itself
> > > 
> > > 
> > > How Can it loose it?... could you show that scenario to let me think how to solve it?. Many thanks 😊
> > 
> > 
> > I am not sure. i must get 920 mh but sometimes i get 880mh. i think this loose happening because of lhr tune. i know this is minimal difference btw
> 
> A movement around 880-920 is completely normal if a for example new job is comming... I thought you said from 920 to 200 or something similar

it is not actually movement, if it starts with 920mh it keeps going with 920mh untill rig restart or lhr tune, same goes for the 880mh scenario
