### ISSUE TITLE
lhr tune loop

### ISSUE THREAD

**Issue by kekwxd008** [Lolliedieb/lolMiner-releases#1196]
after i updated my windows + graphic card driver  and miner . lhr tune begin to loop . before my updates and 1.44 lhr tune takes 1-5 min then i it gets stable but after this updates its in loop forever detected mining lock . Unlocking & reducing --lhr tune parameter...
 
windows 10 update KB5010342

driver update to 472.xx to 511.65

miner update to 1.43 to 1.44

**Comment by jgonzis** [comment]
> after i updated my windows + graphic card driver and miner . lhr tune begin to loop . before my updates and 1.44 lhr tune takes 1-5 min then i it gets stable but after this updates its in loop forever detected mining lock . Unlocking & reducing --lhr tune parameter...
> 
> windows 10 update KB5010342
> 
> driver update to 472.xx to 511.65
> 
> miner update to 1.43 to 1.44

Don't use NEW Drivers. Use please 472.12 for LHR Gpus.

Wait 1 minute to start to be sure is unlock

- User Fixed Core applying --cclk in EXTRAPARAMETERS bat file and lolMiner.exe  as Administrator
- Power Limit 100%  MSI Afterburner

Other Tips and Tricks:
- Check Memory Temperature for Thermal in GDDR6x
- No Monitor Connected to that GPU
- Gen2 to the Mobo Slot
- Use Riser
