### ISSUE TITLE
HTML Page to see Mining Data

### ISSUE THREAD

**Issue by CryptoLLC** [Lolliedieb/lolMiner-releases#1201]
Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats
Would be a great feature. Thanks.

**Comment by jgonzis** [comment]
> Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.

That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too

**Comment by devour7** [comment]
> > Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.
> 
> That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too

What have you been doing all these months? The dag takes minutes to build, and the basics are shit, you guys are way behind other miners,just saying.

**Comment by jgonzis** [comment]
> > > Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.
> > 
> > 
> > That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too
> 
> What have you been doing all these months? The dag takes minutes to build, and the basics are shit, you guys are way behind other miners,just saying.

DAG Minutes? It is the faster DAG and the only with repairing DAG, no other miner have it.

Could you show if you are having Repairing DAG?.  In some to much undervolt AMD that can made DAG not properly loaded and need to be repaired.

If you don't care about DAG Repair use --disable-dag-verify but you can get bad shares.

**Comment by devour7** [comment]
> > > > Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.
> > > 
> > > 
> > > That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too
> > 
> > 
> > What have you been doing all these months? The dag takes minutes to build, and the basics are shit, you guys are way behind other miners,just saying.
> 
> DAG Minutes? It is the faster DAG and the only with repairing DAG, no other miner have it.
> 
> Could you show a picture if you are having Repairing DAG?. In some to much undervolt AMD that can made DAG not properly loaded and need to be repaired.
> 
> If you don't care about DAG Repair use --disable-dag-verify but you can get bad shares.

![221](https://user-images.githubusercontent.com/82796337/153705258-0f7b61f6-62ae-48c2-8e03-e35e03604916.jpg)

It will repair one by one every time,It takes 10+ minutes before it's all done. and if you adjust the overclock after running, you cannot get result before restarting.difficult to adjustment for new users.

**Comment by jgonzis** [comment]
> > > > > Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.
> > > > 
> > > > 
> > > > That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too
> > > 
> > > 
> > > What have you been doing all these months? The dag takes minutes to build, and the basics are shit, you guys are way behind other miners,just saying.
> > 
> > 
> > DAG Minutes? It is the faster DAG and the only with repairing DAG, no other miner have it.
> > Could you show a picture if you are having Repairing DAG?. In some to much undervolt AMD that can made DAG not properly loaded and need to be repaired.
> > If you don't care about DAG Repair use --disable-dag-verify but you can get bad shares.
> 
> ![221](https://user-images.githubusercontent.com/82796337/153705258-0f7b61f6-62ae-48c2-8e03-e35e03604916.jpg)
> 
> It will repair one by one every time,It takes 10+ minutes before it's all done. and if you adjust the overclock after running, you cannot get result before restarting.difficult to adjustment for new users.

DAG Repair is an advise that Memories are getting degradated at that Memory OC that you have. If you don't want to download them just add parameter --disable-dag-verify then it won't check just mine directly.

 But if you accept the recommendation check your Memory OC until DAG repair doesn't appear other times we have found could be the riser or the USB Cable.  With the memory I saw it could be then Memory OC I think you have more than 1400 in MSI Afterburner...

**Comment by devour7** [comment]
> > > > > > Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.
> > > > > 
> > > > > 
> > > > > That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too
> > > > 
> > > > 
> > > > What have you been doing all these months? The dag takes minutes to build, and the basics are shit, you guys are way behind other miners,just saying.
> > > 
> > > 
> > > DAG Minutes? It is the faster DAG and the only with repairing DAG, no other miner have it.
> > > Could you show a picture if you are having Repairing DAG?. In some to much undervolt AMD that can made DAG not properly loaded and need to be repaired.
> > > If you don't care about DAG Repair use --disable-dag-verify but you can get bad shares.
> > 
> > 
> > ![221](https://user-images.githubusercontent.com/82796337/153705258-0f7b61f6-62ae-48c2-8e03-e35e03604916.jpg)
> > It will repair one by one every time,It takes 10+ minutes before it's all done. and if you adjust the overclock after running, you cannot get result before restarting.difficult to adjustment for new users.
> 
> DAG Repair is an advise that Memories are getting degradated at that Memory OC that you have. If you don't want to download them just add parameter --disable-dag-verify then it won't check just mine directly.
> 
> But if you accept the recommendation check your Memory OC until DAG repair doesn't appear other times we have found could be the riser or the USB Cable. With the memory I saw it could be then Memory OC I think you have more than 1400 in MSI Afterburner...

That overclocking data is adjusted for each card, it has been running on other miners for more than a year without problems, it can be kept at less than 3% inefficiency, I have tried -disable-dag-verify, it will become very unstable, but thanks for your reply.

**Comment by jgonzis** [comment]
> > > > > > > Can you guys add an html page so we can see that data from the miner? Gminer has a great html ui page that shows all the stats. This would be a great addition. Something like -- localhost/stats Would be a great feature. Thanks.
> > > > > > 
> > > > > > 
> > > > > > That should be improved, completely right. You can use TightVNC to connect to your Windows RIG and check it with Android easyly too
> > > > > 
> > > > > 
> > > > > What have you been doing all these months? The dag takes minutes to build, and the basics are shit, you guys are way behind other miners,just saying.
> > > > 
> > > > 
> > > > DAG Minutes? It is the faster DAG and the only with repairing DAG, no other miner have it.
> > > > Could you show a picture if you are having Repairing DAG?. In some to much undervolt AMD that can made DAG not properly loaded and need to be repaired.
> > > > If you don't care about DAG Repair use --disable-dag-verify but you can get bad shares.
> > > 
> > > 
> > > ![221](https://user-images.githubusercontent.com/82796337/153705258-0f7b61f6-62ae-48c2-8e03-e35e03604916.jpg)
> > > It will repair one by one every time,It takes 10+ minutes before it's all done. and if you adjust the overclock after running, you cannot get result before restarting.difficult to adjustment for new users.
> > 
> > 
> > DAG Repair is an advise that Memories are getting degradated at that Memory OC that you have. If you don't want to download them just add parameter --disable-dag-verify then it won't check just mine directly.
> > But if you accept the recommendation check your Memory OC until DAG repair doesn't appear other times we have found could be the riser or the USB Cable. With the memory I saw it could be then Memory OC I think you have more than 1400 in MSI Afterburner...
> 
> That overclocking data is adjusted for each card, it has been running on other miners for more than a year without problems, it can be kept at less than 3% inefficiency, I have tried -disable-dag-verify, it will become very unstable, but thanks for your reply.

Is normal that starts working perfectly, the degrading come with time...  been NO LHR, me recommendation is to take care of them... 3% of 60Mhs is 1.8Mhs the  is real 58.2Mhs, so running them at 1000 of Memory  you will get +59Mhs without DAG problems( I hope depending how damaged their are). So then 1000 memory with out error +59Mhs is more profitable than 60 or 61Mhs with -3%, and continues Memory degradation. 

You can  also check some test of profit at the pool with 1Million Shares test : https://www.hashrate.no/tests/ampere

If you only compare reported hashrate instead average pool hashrate (what we get paid)

But anyways thanks for the try and for asking about the DAG Repair function, I totally agree we should explain that exclusive functionality of the miner.

**Comment by jgonzis** [comment]
Gui is there from 1.45

**Comment by devour7** [comment]
> Gui is there from 1.45

1.46 is amazing, I get 61.8Mh/s eth and 2Gh/s ton on my best 3070, other cards get 60~61Mh/s and 1.9~2Gh/s, It's stable... how can your guys do that?

**Comment by jgonzis** [comment]
> > Gui is there from 1.45
> 
> 1.46 is amazing, I get 61.8Mh/s eth and 2Gh/s ton on my best 3070, other cards get 60~61Mh/s and 1.9~2Gh/s, It's stable... how can your guys do that?

Problem has been working lot of time trying to solve pools connection until they changed protocols and updated they possibilities. After that, time can be dedicated to improvements.  Many thanks for your feedback.
