### ISSUE TITLE
Unrealistic Hashrate Reported

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1206]
System was working fine and then I restarted it and that started to happen.

Tried version 1.43 and 1.44

The rig has a mix of 8 LHR gpus (3070 TI and 3080), as for core clock and memory I've tried different settings ranging from low to high.

OS windows 10 - it was working fine till about 2-3 hours before posting the original post.

As for the driver I am using the 472.12

![image](https://user-images.githubusercontent.com/49044292/153402838-2fab61b3-334e-4158-b0e2-8b520dc5a050.png)

Also sometimes it goes to zero

![image](https://user-images.githubusercontent.com/49044292/153404531-b48010e5-228b-4dde-835d-3a2db57949d7.png)

**Comment by jgonzis** [comment]
> System was working fine and then I restarted it and that started to happen.
> 
> Tried version 1.43 and 1.44
> 
> The rig has a mix of 8 LHR gpus (3070 TI and 3080), as for core clock and memory I've tried different settings ranging from low to high.
> 
> OS windows 10 - it was working fine till about 2-3 hours before posting the original post.
> 
> As for the driver I am using the 472.12
> 
> ![image](https://user-images.githubusercontent.com/49044292/153402838-2fab61b3-334e-4158-b0e2-8b520dc5a050.png)
> 
> Also sometimes it goes to zero
> 
> ![image](https://user-images.githubusercontent.com/49044292/153404531-b48010e5-228b-4dde-835d-3a2db57949d7.png)

That 0 is Nvidia Driver Crash of one of the GPUs... please try to reduce the Memory OC of your RIG..

**Comment by Vinasis01** [comment]
@jgonzis other softwares are mining fine, is that a thing with lolminer?

**Comment by jgonzis** [comment]
> @jgonzis other softwares are mining fine, is that a thing with lolminer?

No other miner do ETH+TON in Nvidia... and that requieres more Power, seen all going to 0 that is a crash of the driver, normally that happens for an excess of Memory OC. I don't know as I comment you in the other. Are you using our bat file or your bat file?. 

With our bat file we added the option of --watchdog exit, so in case a Nvidia GPU out of the miner to try to restart. 

I also don't know which Memory OC are you using...
