### ISSUE TITLE
--fan

### ISSUE THREAD

**Issue by ektefa** [Lolliedieb/lolMiner-releases#1208]
Hey guys
Its a feature request. Param to set fan speed in percent. I use fixed core & mem clocks. So I need afterburner or other overclocking tools just to set fan speed and I realy hate that. That would be great to see such param.
Also a web page to show miner stats instead/beside current json output. Something like t-rex would be great.
Update: Something like rig management t-rex provides. See two workers stats in one place (connection by IP or something)

**Comment by jgonzis** [comment]
> Hey guys Its a feature request. Param to set fan speed in percent. I use fixed core & mem clocks. So I need afterburner or other overclocking tools just to set fan speed and I realy hate that. That would be great to see such param. Also a web page to show miner stats instead/beside current json output. Something like t-rex would be great. Update: Something like rig management t-rex provides. See two workers stats in one place (connection by IP or something)

It was decision to avoid any extern interaction to avoid any backdoor that could hack the miner. Any external option that modify something from the miner could be a leak for hackers.

In your case, you can use different options. Load profile Fan directly in MSI Afterburner and load it in the bat file directly:

C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe -Profile1

Other option is to use tightvnc, it is a free VNC connection to your Windows Rig. And you will be able to see all mining information.
