### ISSUE TITLE
Hive.os Lolminer 14.4 Eth/Ton restart issues

### ISSUE THREAD

**Issue by pam1212** [Lolliedieb/lolMiner-releases#1209]
Hello,

I am a new user here!

I am using Hive.os and I have 6 rigs of 8 GPUs each. Each rig has 8 RTX 3070s.

I started mining ETH / TON with Lolminer 14.3 over the past few days. I have the current image of Hive.Os (0.6-213@220209), current kernel (5.10.0), and current Nvidia drivers (495.46).

I have noticed many of the rigs would randomly restart a few hours after running. 

In this example, I rebooted all rigs 14 hours ago. Checking this morning, here is what I see:
Worker 1 - 14h 26m
Worker 2 - 11h 15m
Worker 3 - 4h 22m
Worker 4 - 6h 38m
Worker 5 - 5h 40m
Worker 6 - 4h 21m

For clarity: All of my rigs have never had this problem for the past 9 months mining just ETH.

Currently mining to Flexpool and to ton-pool with information inputting into the miner's user config. 

Thanks!

**Comment by queinnec35** [comment]
same here random reboot timer (only the miner restart, not the rig i can read booted 4 day ago for exemple)
ton poll too

**Comment by StrgrDngr** [comment]
Same issue here. Hive OS version 0.6-213@220209, lolminer version 1.44. Nvidia 470.74. Mining ETH+Ton is causing random miner restarts. Sometimes it happens after 15 minutes but can take 20+ hours before the restart occurs. OS and rig remains running, only the miner restarts.

**Comment by zxmmxzzxmmxz** [comment]
I figured it's cuz the ton pool (I'm using toncoin pool and it has the problem) becomes unresolvable sometimes, which triggers the miner to stop mining, and restart the mining process when the pool address is resolvable again.

I don't know a mitigation to this neither do I know if it's a miner problem or pool problem tho.

The worst thing is, under HiveOS with Nvidia cards, it's likely to fuck your OC cuz the miner restart randomly and only a rig reboot can solve the problem.

Please kindly investigate this or have an option to NOT stop mining when ton pool is unresolvable.

**Comment by jgonzis** [comment]
> I figured it's cuz the ton pool (I'm using toncoin pool and it has the problem) becomes unresolvable sometimes, which triggers the miner to stop mining, and restart the mining process when the pool address is resolvable again.
> 
> I don't know a mitigation to this neither do I know if it's a miner problem or pool problem tho.
> 
> The worst thing is, under HiveOS with Nvidia cards, it's likely to fuck your OC cuz the miner restart randomly and only a rig reboot can solve the problem.
> 
> Please kindly investigate this or have an option to NOT stop mining when ton pool is unresolvable.

All the problems are for TON Pools, it has been really complicated searching solutions to improve it. 

![image](https://user-images.githubusercontent.com/38668405/153585819-8366e552-e8f1-4495-8718-a01282c84be1.png)

For example using icemining.ca no problems during 3 days for example with 1.44

**Comment by queinnec35** [comment]
i will try this ice mining with 2 rig of 4

**Comment by jgonzis** [comment]
> i will try this ice mining with 2 rig of 4

I hope you can give later your feed.

**Comment by wcavanagh** [comment]
Hi All,
Seeing the same here, on HiveOS miner restarting, no errors that I can see.  I am using ton-pool.  Anyone got any solutions?  My rigs mining jusy Eth do not do this.

**Comment by wcavanagh** [comment]
Yes i mean miner app reboots, but rig stays online no issues, I have 6 rigs and they all do the same, triggers all my alerts and is really annoying.  I am certain it is a pool issue as I read all over it is the case.

**Comment by wcavanagh** [comment]
I have swapped over to icemining lets see how that goes

**Comment by jgonzis** [comment]
Thx for the patient

**Comment by wcavanagh** [comment]
Seems to be much better now :)
