### ISSUE TITLE
0.00 mh/s

### ISSUE THREAD

**Issue by ledlamp** [Lolliedieb/lolMiner-releases#121]
wat ![](https://8etb.qonq.gq)

**Comment by Lolliedieb** [comment]
Seems like the GPU either has crashed or did not even start mining. 
Please provide as much information as possible, including:
- What OS (Windows or Linux) this is?
- What GPU model is running?
- Which driver version?
- Does the card do screen output in parallel?

Always willing to help, but I need maximum information available to do so.

**Comment by ledlamp** [comment]
Windows 10 Pro 20H2 19042.685
NVIDIA 1050 Ti
Driver version 460.89
laptop clamshell is closed and outputting to HDMI only

**Comment by jgonzis** [comment]
That's true... Windows mem use don't let many options in ETHash for 4Gb. You can mine with lolminer etchash without problem now.
