### ISSUE TITLE
Mining ETH+Zil and Ton

### ISSUE THREAD

**Issue by mflanagan1041** [Lolliedieb/lolMiner-releases#1213]
Was wondering is it possible to mine eth with zil on ezil and mining ton at the same time? Can the miner still switch for Zil? if not can we implement this? its possible on hiveos but i cant get it to work on windows.

**Comment by mrarefasl** [comment]
> Im Mining over minerstat using lolminer. Do you have right pool address? Wallet need to be eth.zil And you also need to wait a couple of min before it shows stats on pool.

could you please share how much profit per MH (on ethash algo) do you get in 24h ?

**Comment by jgonzis** [comment]
The easy and fast way is to directly mine in EZIL.ME then that is automatic to have the ETH+TON+ZIL...

If you want you to use a proxy... here is a working connection with rustpool for example

![image](https://user-images.githubusercontent.com/38668405/153585652-252763a2-7052-4971-bddf-00b389189343.png)
