### ISSUE TITLE
 Periodically, the minor loop is re-executed without errors. 1.44

### ISSUE THREAD

**Issue by cutestor1** [Lolliedieb/lolMiner-releases#1214]
The miner is also periodically created dag, and the miner loop is executed without any error log.

**Comment by jgonzis** [comment]
> The miner is also periodically created dag, and the miner loop is executed without any error log.

That normally is for pool problems... I suppse you are in tonwhales or ton-pool right?.

![image](https://user-images.githubusercontent.com/38668405/153585488-829441f1-884e-429e-9ef0-b25da64781d8.png)
For example not using that pools 3 days without any issue.
