### ISSUE TITLE
eth pool connect failed

### ISSUE THREAD

**Issue by wangsxiang** [Lolliedieb/lolMiner-releases#1216]
return Lost connection to stratum server eu1.ethermine.org:4444 or server not reachable.
But I can use nbminer dig and ping successfully

**Comment by jgonzis** [comment]
> return Lost connection to stratum server eu1.ethermine.org:4444 or server not reachable. But I can use nbminer dig and ping successfully

That should be something with the configuration file, probably you have active tls or similar. Which OS are you using?. Could you share your config file and the error?.

Many thanks
