### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by cutestor1** [Lolliedieb/lolMiner-releases#1217]
I get a roll minor application error and it hangs.

![error](https://user-images.githubusercontent.com/95376187/153550626-c5822edd-ab7c-4947-a306-a76047574a24.jpg)

**Comment by jgonzis** [comment]
> I get a roll minor application error and it hangs.
> 
> ![error](https://user-images.githubusercontent.com/95376187/153550626-c5822edd-ab7c-4947-a306-a76047574a24.jpg)

Which OS?.
Which Drivers?
Which Pool?
Which GPU?.
Has started or before run?.
Check to disable Antivirus
