### ISSUE TITLE
AMD Firepro S9000

### ISSUE THREAD

**Issue by rowis36** [Lolliedieb/lolMiner-releases#1218]
Hallo, i have one AMD Firepro S9000 card. Works only with lolminer. But miner detect this card like W8000. And i can`t manage anything - GPU  and memory clocks, undervolting etc. I see only card temperature. What should i do for right card management? Maybe one vbios need to be added to lolminer? 
     I have one variant - to load one vbios from HD7970 6 gb, but it is very risky... And i do not know - lolminer works with HD7970. Some one know this?

**Comment by jgonzis** [comment]
> Hallo, i have one AMD Firepro S9000 card. Works only with lolminer. But miner detect this card like W8000. And i can`t manage anything - GPU and memory clocks, undervolting etc. I see only card temperature. What should i do for right card management? Maybe one vbios need to be added to lolminer? I have one variant - to load one vbios from HD7970 6 gb, but it is very risky... And i do not know - lolminer works with HD7970. Some one know this?

lolMiner doesn't touch the Voltage or Memory of the GPUs... that is better to use 3rd Party APPs that they do it or Linux OS 

HD7970 works, but I think not for ETH... be have it as 3GB. With do Ergo and ETC
