### ISSUE TITLE
Problem about "dualdevices" option

### ISSUE THREAD

**Issue by iegsystems** [Lolliedieb/lolMiner-releases#1219]
Hi, 
I want to mine with ETH + TON with some of GPUs (GPU 0,1,3) and the others (GPU 2,4) should mine only ETH.  I added command in miner option "--dualdevices 0,1,3" at hiveos. However, lolminer doesn't work correctly. Normally, GPU 0,1,3 should mine with both algo but they mine only ton. GPU 2 and 4 mine with both algo. When I change dualdevice options like " --dualdevices 2,4", GPU 0,1,3 will mine with dual algo but GPU 2,4 will mine only ton algo. Could anyone help for me to solution?
![IMG-20220211-WA0011.jpg](https://user-images.githubusercontent.com/99487576/153605863-4bea05b9-6eab-4658-b347-7bee2b6e1aec.jpg)
![IMG-20220211-WA0010.jpg](https://user-images.githubusercontent.com/99487576/153605909-162011a0-9c6d-4feb-8fb7-f659b675a402.jpg)

**Comment by jgonzis** [comment]
I try to explain you...

--dualdevices will only mine ton in that devices. You should use --maxdualimpact

`--maxdualimpact *,*,0,*,0`

That will do 0 TON to GPU 2 and 4 like you want :-)
