### ISSUE TITLE
R9 290 Insufficient memory for DAG

### ISSUE THREAD

**Issue by xfrolx** [Lolliedieb/lolMiner-releases#122]
Hello, i start mining on amd r9 290 4gb in HiveOs with --4g-alloc-size 4076 parameter and catch "Insufficient memory for DAG" message :(
what am I doing wrong? Help me please :)

![image](https://user-images.githubusercontent.com/55754442/103951649-8711e180-5158-11eb-9ab9-702c55ce8e1f.png)

**Comment by Lolliedieb** [comment]
This is because R9 390 currently has no kernel for zombie mode - and ... sorry for my confusion, but according to the Wiki page about R9 300 series there should be no 4G R9 390 - they are all 8G!
https://en.wikipedia.org/wiki/Radeon_Rx_300_series

 Can you please double check what card this is? In doubt run clinfo in the Hive shell and paste me its output here :)

**Comment by xfrolx** [comment]
> This is because R9 390 currently has no kernel for zombie mode - and ... sorry for my confusion, but according to the Wiki page about R9 300 series there should be no 4G R9 390 - they are all 8G!
> https://en.wikipedia.org/wiki/Radeon_Rx_300_series
> 
> Can you please double check what card this is? In doubt run clinfo in the Hive shell and paste me its output here :)

i have r9 **2**90 :)
![image](https://user-images.githubusercontent.com/55754442/104002957-354e7300-51bb-11eb-8e6d-01596b1135a9.png)

--4g-alloc-size 4064
or
--4g-alloc-size 4056
or
--4g-alloc-size 4000

didn't change the situation...

**Comment by Lolliedieb** [comment]
Ah sorry ... indeed R9 200 do not have zombie mode at the moment ... what was last epoch that did work with the cards? Did 380 still work? (just guessing if a zombie would be worth it)

**Comment by xfrolx** [comment]
> Ah sorry ... indeed R9 200 do not have zombie mode at the moment ... what was last epoch that did work with the cards? Did 380 still work? (just guessing if a zombie would be worth it)

they stopped mining at 16.12.2020, dag size calculator say, that is 383 epoch. is it worth waiting for zombie mod on 290? :)

**Comment by jgonzis** [comment]
Solved with latest releases...
