### ISSUE TITLE
High number of stales even only mining ETH

### ISSUE THREAD

**Issue by zabihchaudhry** [Lolliedieb/lolMiner-releases#1220]
Hi all,
I did use lolminer 1.43 and 1.44 for dual mining. During that both version gave me high numbers of stales, and submission was getting less and less until I restart miner. Then I stopped dual mining switched to mine only ETH to flexpool (latency 10-18ms).
But stales are nonstop 2%, never had these many stales before. I am mining on hiveos and have all RX 6800 from MSI trio. I have tried every method, but stales not stabling. OC checked, PSU ok, Lan connection, hive replaced, BTC s37 motherboard check, ssd check, ram checked, internet is fine. The problem occured after dual mining for 2 days. Right now I switched to TeamRedMiner, mining is very slow but stales are little bit less, but they are there. Before it wasn't like that. Your help would be much appreciated. I like lolminer because it submit more shares, but 3 3 stales not a good choice. 
![Screenshot_20220212-014005_Chrome](https://user-images.githubusercontent.com/20650525/153611634-8106ac69-7ed0-4898-a96b-41b3df4dfd34.jpg)
![Screenshot_20220212-014050_Hive OS](https://user-images.githubusercontent.com/20650525/153611750-b918eb9a-1e28-4556-9be4-f76b7665e1b3.jpg)
![Screenshot_20220212-014125_Hive OS](https://user-images.githubusercontent.com/20650525/153611861-55632d28-34ca-4a49-82b6-54f752a8ed62.jpg)
![Screenshot_20220212-014142_Hive OS](https://user-images.githubusercontent.com/20650525/153611906-9de099c4-a67d-4f7a-919f-cbec43de5624.jpg)

**Comment by jgonzis** [comment]
> Hi all, I did use lolminer 1.43 and 1.44 for dual mining. During that both version gave me high numbers of stales, and submission was getting less and less until I restart miner. Then I stopped dual mining switched to mine only ETH to flexpool (latency 10-18ms). But stales are nonstop 2%, never had these many stales before. I am mining on hiveos and have all RX 6800 from MSI trio. I have tried every method, but stales not stabling. OC checked, PSU ok, Lan connection, hive replaced, BTC s37 motherboard check, ssd check, ram checked, internet is fine. The problem occured after dual mining for 2 days. Right now I switched to TeamRedMiner, mining is very slow but stales are little bit less, but they are there. Before it wasn't like that. Your help would be much appreciated. I like lolminer because it submit more shares, but 3 3 stales not a good choice. ![Screenshot_20220212-014005_Chrome](https://user-images.githubusercontent.com/20650525/153611634-8106ac69-7ed0-4898-a96b-41b3df4dfd34.jpg) ![Screenshot_20220212-014050_Hive OS](https://user-images.githubusercontent.com/20650525/153611750-b918eb9a-1e28-4556-9be4-f76b7665e1b3.jpg) ![Screenshot_20220212-014125_Hive OS](https://user-images.githubusercontent.com/20650525/153611861-55632d28-34ca-4a49-82b6-54f752a8ed62.jpg) ![Screenshot_20220212-014142_Hive OS](https://user-images.githubusercontent.com/20650525/153611906-9de099c4-a67d-4f7a-919f-cbec43de5624.jpg)

stales under 1% is good value, also you have different disconnections and is 24hours time stales. Seen your screen you have it all together the big ones. It could be a small issue also in your ISP or the network in that moment. Don't worry about it, also your pool pay the stales.

![image](https://user-images.githubusercontent.com/38668405/153622966-25ddb376-ff4d-4919-85fc-593916f63332.png)
