### ISSUE TITLE
Any way to dual mine only with specific cards?

### ISSUE THREAD

**Issue by wallacepf** [Lolliedieb/lolMiner-releases#1224]
Hello Guys,

Couldn't find any reference in the docs and for that reason, I'm asking here. Is there any way to dual mine only using specific cards in my rig? I have a rig with 5 cards and I only want to dual mine in cards 1 and 3 the remaining cards should be mining only ETH. Tried to --dualdevices option but it only enables the second coin in those cards. Currently, I'm using two miners as a workaround like lolminer for cards 1 and 3 and Gminer for the remaining.

**Comment by iaries77** [comment]
I also want to know how to set。

**Comment by mohsenk94** [comment]
Well, if you like LOL Miner, you can use 2 different batch files and use 2 instances of LOL miner!
1 with arguments:
-d 1,3
and one with argument:
-d 0,2,4

**Comment by jgonzis** [comment]
> Hello Guys,
> 
> Couldn't find any reference in the docs and for that reason, I'm asking here. Is there any way to dual mine only using specific cards in my rig? I have a rig with 5 cards and I only want to dual mine in cards 1 and 3 the remaining cards should be mining only ETH. Tried to --dualdevices option but it only enables the second coin in those cards. Currently, I'm using two miners as a workaround like lolminer for cards 1 and 3 and Gminer for the remaining.

Yes it is in the chanhelog of 1.44 try this: 
`--maxdualimpact 0,*,0,*,0`
0 will only mine ETH
