### ISSUE TITLE
AMD R290 (Hawaii) ETC + TON Dual Mining

### ISSUE THREAD

**Issue by alexander-pav** [Lolliedieb/lolMiner-releases#1225]
Hello!
Dual mining ETC + TON is possible on Hawaii GPUs?
On my AMD R290 it always shows "SHA256-TON: Average speed (15s): 0.00 Mh/s"

![Screenshot from 2022-02-12 01-38-06](https://user-images.githubusercontent.com/19728262/153667796-db45be2e-9d6d-449f-b9eb-26a7f779877c.png)

**Comment by jgonzis** [comment]
> Hello! Dual mining ETC + TON is possible on Hawaii GPUs? On my AMD R290 it always shows "SHA256-TON: Average speed (15s): 0.00 Mh/s"
> 
> ![Screenshot from 2022-02-12 01-38-06](https://user-images.githubusercontent.com/19728262/153667796-db45be2e-9d6d-449f-b9eb-26a7f779877c.png)

Sorry R9 290 is hasn't got TON support only from Polaris...
