### ISSUE TITLE
lolminer not detecting mix rig card 

### ISSUE THREAD

**Issue by Ammaragab** [Lolliedieb/lolMiner-releases#1229]
Hi Team

I do have 2 mixed rigs AMD / Nvidia I'm trying to double mine but the problem with the miner is detecting only the Nvidia card and is not detecting the one .... please let me know how I can fix this issue 

Regards 
![rtx](https://user-images.githubusercontent.com/75908515/153688653-04897345-7ffd-4565-8552-3e1214d65b9d.JPG)
![rtx2](https://user-images.githubusercontent.com/75908515/153688655-75ea25c8-690a-4f70-9d4d-b03b4f337c19.JPG)

**Comment by jgonzis** [comment]
> Hi Team
> 
> I do have 2 mixed rigs AMD / Nvidia I'm trying to double mine but the problem with the miner is detecting only the Nvidia card and is not detecting the one .... please let me know how I can fix this issue
> 
> Regards ![rtx](https://user-images.githubusercontent.com/75908515/153688653-04897345-7ffd-4565-8552-3e1214d65b9d.JPG) ![rtx2](https://user-images.githubusercontent.com/75908515/153688655-75ea25c8-690a-4f70-9d4d-b03b4f337c19.JPG)

Could you try to use a lower AMD Driver Version?. It could be that new driver version has got a new kernel and not yet loaded.

**Comment by Ammaragab** [comment]
I have tried 7 different versions of the amd driver and still, the miner is not detection the and GPU

**Comment by jgonzis** [comment]
> I have tried 7 different versions of the amd driver and still, the miner is not detection the and GPU

Could you please try a Mining OS, like MMPOS or HiveOS please? Just be sure it works:

https://youtu.be/5tP3CeSbgJk

**Comment by jgonzis** [comment]
No problem or feedback... close issue
