### ISSUE TITLE
connection report with issues

### ISSUE THREAD

**Issue by LuisMedina89** [Lolliedieb/lolMiner-releases#1230]
Hi, anyone knows why the report of the shares looks like this? internet connection is the same as always.

![Screenshot_20210921-001232](https://user-images.githubusercontent.com/99519943/153693678-c30d10a6-7842-4a05-8981-9cba1d937ed7.png)

**Comment by jgonzis** [comment]
> Hi, anyone knows why the report of the shares looks like this? internet connection is the same as always.
> 
> ![Screenshot_20210921-001232](https://user-images.githubusercontent.com/99519943/153693678-c30d10a6-7842-4a05-8981-9cba1d937ed7.png)

Could you share your config file?. It is really strange, first time I see it.

**Comment by jgonzis** [comment]
No information close Issue
