### ISSUE TITLE
Dual mine eth+ton ton pool connection stops eth and ton ming

### ISSUE THREAD

**Issue by matthewingram** [Lolliedieb/lolMiner-releases#1234]
Occasionally getting connectivity issues to ton pool when dual mining eth +ton. When the websocket fails mining stops on both eth pool and ton pool. Is there a way to keep it from killing the eth mining if that pool is still working fine?

**Comment by 122566** [comment]
The same issues occured, is there any way to solve this problem?

**Comment by corvy** [comment]
As a workaround I use a hashrate watchdog on Hiveos.

**Comment by jgonzis** [comment]
> Occasionally getting connectivity issues to ton pool when dual mining eth +ton. When the websocket fails mining stops on both eth pool and ton pool. Is there a way to keep it from killing the eth mining if that pool is still working fine?

Yes, the pools systems are hard, nearly all the problems come with the pool TON Protocols, please use like the other collegue said. Watchdog in HiveOS will solve all that problems.

**Comment by pabloguns** [comment]
> 

Hello! and for Windows 10 how could I configure "WatchDog"?

**Comment by jgonzis** [comment]
> > 
> 
> Hello! and for Windows 10 how could I configure "WatchDog"?

The bat file comes with a loop in case of crash... also a pause of 10s and then restart... it should work without problems

**Comment by matthewingram** [comment]
> > Hello! and for Windows 10 how could I configure "WatchDog"?
> 
> The bat file comes with a loop in case of crash... also a pause of 10s and then restart... it should work without problems

I looks like it retry’s every 5 seconds. Not sure how many times but it ends up like this….
![image](https://user-images.githubusercontent.com/29441969/153723300-f4e2f332-97a5-4b29-bd05-67f01dd3c4d6.jpg)

**Comment by jgonzis** [comment]
> > > Hello! and for Windows 10 how could I configure "WatchDog"?
> > 
> > 
> > The bat file comes with a loop in case of crash... also a pause of 10s and then restart... it should work without problems
> 
> I looks like it retry’s every 5 seconds. Not sure how many times but it ends up like this…. ![image](https://user-images.githubusercontent.com/29441969/153723300-f4e2f332-97a5-4b29-bd05-67f01dd3c4d6.jpg)

it seems you don't have the version 1.44 or the last bat file with the loop

**Comment by sebek72** [comment]
For me ton-pool.com has issues with 1.44. On 1.43 it works stable for me.

**Comment by jgonzis** [comment]
> For me ton-pool.com has issues with 1.44. On 1.43 it works stable for me.

Thx for the feedback

**Comment by Lozty1** [comment]
Telegram TON-Pool News (09/02/2022):

_We have received reports from miners that lolMiner 1.44 sometimes gets disconnected from our pool and balance stop growing. We occasionally restart the pool server to upgrade the software, but it seems that lolMiner 1.44 has problems reconnecting to the pool, while lolMiner 1.43 handles that gracefully. For now, please use lolMiner 1.43 with our pool before the problem gets fixed._

**Comment by cbrwx** [comment]
revert back to older versions and keep posting the issues so they know, also if you are running windows; creating a bat file that checks logs and restarts upon found string is not hard at all.

Something like;

"		copy %~dp0logs\2022-*.log lolminerlog.log
		findstr /c:"Pool not reacting " %~dp0logs\lolminerlog.log >> %WOrkerName%_storeurbugs.txt
		if %errorlevel%==0 (
 		echo Found, restarting miner.
					goto :a_command_that_closes(taskkill)_miner_and_restarts
			) else (
		echo no bugs found.
			goto :continue_without_doing_shit_adding_timeout_then_loop
			)
"

**Comment by jgonzis** [comment]
> revert back to older versions and keep posting the issues so they know, also if you are running windows; creating a bat file that checks logs and restarts upon found string is not hard at all.
> 
> Something like;
> 
> " \dirty but works, also this will require you to delete logs every time you start the miner copy %~dp0logs\2022-*.log lolminerlog.log findstr /c:"Pool not reacting " %~dp0logs\lolminerlog.log >> %WOrkerName%_storeurbugs.txt if %errorlevel%==0 ( echo Found, restarting miner. goto :a_command_that_closes(taskkill)_miner_and_restarts ) else ( echo no bugs found. goto :continue_without_doing_shit_adding_timeout_then_loop ) "

Try 1.45 with Extra-Parameters  --ton-mode 2

It should work properly

**Comment by jgonzis** [comment]
No problem or feedback... close issue
