### ISSUE TITLE
1080 and 1080ti 

### ISSUE THREAD

**Issue by NecrosisDnB** [Lolliedieb/lolMiner-releases#1239]
Hello ! I hope I'm in the correct place. I've noticed my 1080 and 1080ti are still unresponsive with the experimental kernel. 1070 is working great tho ty for everything 🙌

**Comment by jgonzis** [comment]
> Hello ! I hope I'm in the correct place. I've noticed my 1080 and 1080ti are still unresponsive with the experimental kernel. 1070 is working great tho ty for everything 🙌

If you are in HiveOS try to put :

![image](https://user-images.githubusercontent.com/38668405/153722127-3a103461-c50b-43ba-923c-ccd1daba11e9.png)

Or the same to Windows if you could put it later than start the mining.

**Comment by NecrosisDnB** [comment]
> > Hello ! I hope I'm in the correct place. I've noticed my 1080 and 1080ti are still unresponsive with the experimental kernel. 1070 is working great tho ty for everything 🙌
> 
> If you are in HiveOS try to put :
> 
> ![image](https://user-images.githubusercontent.com/38668405/153722127-3a103461-c50b-43ba-923c-ccd1daba11e9.png)
> 
> Or the same to Windows if you could put it later than start the mining.

Ok I am on windows and it works for eth just not TON. I even tried it without the pill. Idk ty tho for the help

**Comment by jgonzis** [comment]
> > > Hello ! I hope I'm in the correct place. I've noticed my 1080 and 1080ti are still unresponsive with the experimental kernel. 1070 is working great tho ty for everything 🙌
> > 
> > 
> > If you are in HiveOS try to put :
> > ![image](https://user-images.githubusercontent.com/38668405/153722127-3a103461-c50b-43ba-923c-ccd1daba11e9.png)
> > Or the same to Windows if you could put it later than start the mining.
> 
> Ok I am on windows and it works for eth just not TON. I even tried it without the pill. Idk ty tho for the help

Which PL are you putting??

**Comment by NecrosisDnB** [comment]
Good news I remembered after the last comment that I didn't try it without the pill on 1.44 so now with your suggestion I got most of them going.  However I have 1 1080 FE still at 0 mh and I don't run the pill at all on it. I will try a different OC as you suggested for this one and see of it responds. Thank you for your help.

**Comment by KSereryakov** [comment]
> > > > Hello ! I hope I'm in the correct place. I've noticed my 1080 and 1080ti are still unresponsive with the experimental kernel. 1070 is working great tho ty for everything 🙌
> > > 
> > > 
> > > If you are in HiveOS try to put :
> > > ![image](https://user-images.githubusercontent.com/38668405/153722127-3a103461-c50b-43ba-923c-ccd1daba11e9.png)
> > > Or the same to Windows if you could put it later than start the mining.
> > 
> > 
> > Ok I am on windows and it works for eth just not TON. I even tried it without the pill. Idk ty tho for the help
> 
> Which PL are you putting??

hello. I have the same problem with the 1080 ti, that every time a hashrate is randomly started or not started on different cards. I tried with any PL and I have rave0S, there is no tablet used for these cards. I tried running ETC+Tor, everything works well. How can this problem be solved? I see not the first topic on this issue here.

**Comment by jgonzis** [comment]
> > > > > Hello ! I hope I'm in the correct place. I've noticed my 1080 and 1080ti are still unresponsive with the experimental kernel. 1070 is working great tho ty for everything 🙌
> > > > 
> > > > 
> > > > If you are in HiveOS try to put :
> > > > ![image](https://user-images.githubusercontent.com/38668405/153722127-3a103461-c50b-43ba-923c-ccd1daba11e9.png)
> > > > Or the same to Windows if you could put it later than start the mining.
> > > 
> > > 
> > > Ok I am on windows and it works for eth just not TON. I even tried it without the pill. Idk ty tho for the help
> > 
> > 
> > Which PL are you putting??
> 
> hello. I have the same problem with the 1080 ti, that every time a hashrate is randomly started or not started on different cards. I tried with any PL and I have rave0S, there is no tablet used for these cards. I tried running ETC+Tor, everything works well. How can this problem be solved? I see not the first topic on this issue here.

It is complicated in RaveOS for the ETHPILL... ETC don't have problems for the Dag Size. I don't that a --lhrwait 30 will help you... did you try a very high PL too.

**Comment by KSereryakov** [comment]
> Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже пробовали очень высокий PL.

Yes, I tried any PL. and he didn't even specify PL. Nothing changes at the same time

**Comment by jgonzis** [comment]
> > Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже пробовали очень высокий PL.
> 
> Yes, I tried any PL. and he didn't even specify PL. Nothing changes at the same time

could you add: 

--maxdualimpact 10 

Let's give space to TON then...

**Comment by KSereryakov** [comment]
> > > Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже пробовали очень высокий PL.
> > 
> > 
> > Yes, I tried any PL. and he didn't even specify PL. Nothing changes at the same time
> 
> could you add:
> 
> --maxdualimpact 10
> 
> Let's give space to TON then...



> > > Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже пробовали очень высокий PL.
> > 
> > 
> > Yes, I tried any PL. and he didn't even specify PL. Nothing changes at the same time
> 
> could you add:
> 
> --maxdualimpact 10
> 
> Let's give space to TON then...

I don't really understand why you wrote this parameter if it is written, double mining is disabled

```
Example for --dualdevices and --maxdualimpact
Consider a 6 card rig with --dualdevices 4,5 --maxdualimpact 0,0,*,*,*,*
This rig will mine:

Eth only on GPUs 0 & 1 (ton dual mining disabled by maxdualimpact)
Eth + Ton on GPUs 2 & 3
Ton only on GPUs 4 & 5 (eth mining disabled by dualdevices)
```

**Comment by jgonzis** [comment]
> > > > Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже пробовали очень высокий PL.
> > > 
> > > 
> > > Yes, I tried any PL. and he didn't even specify PL. Nothing changes at the same time
> > 
> > 
> > could you add:
> > --maxdualimpact 10
> > Let's give space to TON then...
> 
> > > > Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже пробовали очень высокий PL.
> > > 
> > > 
> > > Yes, I tried any PL. and he didn't even specify PL. Nothing changes at the same time
> > 
> > 
> > could you add:
> > --maxdualimpact 10
> > Let's give space to TON then...
> 
> I don't really understand why you wrote this parameter if it is written, double mining is disabled
> 
> ```
> Example for --dualdevices and --maxdualimpact
> Consider a 6 card rig with --dualdevices 4,5 --maxdualimpact 0,0,*,*,*,*
> This rig will mine:
> 
> Eth only on GPUs 0 & 1 (ton dual mining disabled by maxdualimpact)
> Eth + Ton on GPUs 2 & 3
> Ton only on GPUs 4 & 5 (eth mining disabled by dualdevices)
> ```

You have 6 GPU... and you want GPU0 and 1 to mine ETH... that is done `--maxdualimpact 0,0,*,*,*,*` putting a 0 in the GPU that you dont' want to mine TON. 

Now the other way you want GPUs to only mine TON, that is done with --dualdevices paramters. OF that Rig of 6 you want that 4,5 mine only TON so that is done adding --dualdevices 4,5

**Comment by KSereryakov** [comment]
> > > Это сложно в RaveOS для ETHPILL... У ETC нет проблем с Dag Size. Я не думаю, что --lhrwait 30 вам поможет... вы тоже испытывали очень высокий PL.
> > 
> > 
> > Да, я пробовал любой PL. и он даже не указал PL. При этом ничего не меняется
> 
> не могли бы вы добавить:
> 
> --maxdualimpact 10
> 
> Тогда давайте дадим место TON...

для чего этот параметр? что он делает?

**Comment by jgonzis** [comment]
> для чего этот параметр? что он делает?

That will make that GPU focus more in TON that ETH... let's try if that values helps to make some TON in the Pascal

**Comment by KSereryakov** [comment]
> > для чего этот параметр? что он делает?
> 
> Это заставит этот GPU больше фокусироваться на TON, чем на ETH... давайте попробуем, помогут ли эти значения сделать TON в Pascal.

did you come up with the meaning of this command? the description also says what kind of team it is and what it does. what does the focus on Ton have to do with it?
