### ISSUE TITLE
Inadequate hashrate on gtx 1060 5gb

### ISSUE THREAD

**Issue by Maxton33** [Lolliedieb/lolMiner-releases#1240]
My gtx 1060 5gb produces ~800MH/s when solo mining. When mining eth + ton, my card gives out 19.5MH / s and 1.2GH / s. These are excellent numbers, but everything is extremely unstable. It can work stably for a couple of hours, sometimes it doesn’t work at all. Nothing reaches the pool. What do I to do with it? And is dual mining possible on my video card at all?

**Comment by jgonzis** [comment]
> My gtx 1060 5gb produces ~800MH/s when solo mining. When mining eth + ton, my card gives out 19.5MH / s and 1.2GH / s. These are excellent numbers, but everything is extremely unstable. It can work stably for a couple of hours, sometimes it doesn’t work at all. Nothing reaches the pool. What do I to do with it? And is dual mining possible on my video card at all?

That is a crash in the TON part of the driver... that value is not right. Which Driver are you using?

**Comment by Maxton33** [comment]
> 



> > My gtx 1060 5gb produces ~800MH/s when solo mining. When mining eth + ton, my card gives out 19.5MH / s and 1.2GH / s. These are excellent numbers, but everything is extremely unstable. It can work stably for a couple of hours, sometimes it doesn’t work at all. Nothing reaches the pool. What do I to do with it? And is dual mining possible on my video card at all?
> 
> That is a crash in the TON part of the driver... that value is not right. Which Driver are you using?
I use 470.86 driver. When dual mining, shares reach etermine , but they don't reach ton whales. Do I need to update the driver?

**Comment by jgonzis** [comment]
> > > My gtx 1060 5gb produces ~800MH/s when solo mining. When mining eth + ton, my card gives out 19.5MH / s and 1.2GH / s. These are excellent numbers, but everything is extremely unstable. It can work stably for a couple of hours, sometimes it doesn’t work at all. Nothing reaches the pool. What do I to do with it? And is dual mining possible on my video card at all?
> > 
> > 
> > That is a crash in the TON part of the driver... that value is not right. Which Driver are you using?
> 
> I use 470.86 driver. When dual mining, shares reach etermine , but they don't reach ton whales. Do I need to update the driver?

No that should work ok... and you are with 1.44 so need to investigate

**Comment by Maxton33** [comment]
> > > > My gtx 1060 5gb produces ~800MH/s when solo mining. When mining eth + ton, my card gives out 19.5MH / s and 1.2GH / s. These are excellent numbers, but everything is extremely unstable. It can work stably for a couple of hours, sometimes it doesn’t work at all. Nothing reaches the pool. What do I to do with it? And is dual mining possible on my video card at all?
> > > 
> > > 
> > > That is a crash in the TON part of the driver... that value is not right. Which Driver are you using?
> > 
> > 
> > I use 470.86 driver. When dual mining, shares reach etermine , but they don't reach ton whales. Do I need to update the driver?
> 
> No that should work ok... and you are with 1.44 so need to investigate

I would love to. I just don't know how.

**Comment by jgonzis** [comment]
> > > > > My gtx 1060 5gb produces ~800MH/s when solo mining. When mining eth + ton, my card gives out 19.5MH / s and 1.2GH / s. These are excellent numbers, but everything is extremely unstable. It can work stably for a couple of hours, sometimes it doesn’t work at all. Nothing reaches the pool. What do I to do with it? And is dual mining possible on my video card at all?
> > > > 
> > > > 
> > > > That is a crash in the TON part of the driver... that value is not right. Which Driver are you using?
> > > 
> > > 
> > > I use 470.86 driver. When dual mining, shares reach etermine , but they don't reach ton whales. Do I need to update the driver?
> > 
> > 
> > No that should work ok... and you are with 1.44 so need to investigate
> 
> I would love to. I just don't know how.

Could you run nvidia-smi to have some information about the result meanwhile you are mining.

**Comment by Krysinski** [comment]
I have same issue with 1.46a and 470 driver. I try to use 510 drivers on linux and 1.50 version, but lolminer cant recognise my 1060 5G: cuda device not detected.
i use "--maxdualimpact *,10,10,10,10 --dualdevices 0", there is not enough memory for DAG in gpu 0 for mining eth (x-server take some).

**Comment by jgonzis** [comment]
> I have same issue with 1.46a and 470 driver. I try to use 510 drivers on linux and 1.50 version, but lolminer cant recognise my 1060 5G: cuda device not detected. i use "--maxdualimpact *,10,10,10,10 --dualdevices 0", there is not enough memory for DAG in gpu 0 for mining eth (x-server take some). 1060 5G (gpu 1 - gpu 4) have 160 bit membus and give only 17 Mh/s on eth, but for TON i see about 1100 Mh/s and 0 shares all time. 1060 5G (gpu 0) have 192 bit membus and give 21 Mh/s on eth some time ago, now it give only TON 800 Mh/s and normal shares. ![image](https://user-images.githubusercontent.com/15215123/168957982-62eeef2c-9bfa-4a4d-b109-2cfd3cc2c4f7.png) ![image](https://user-images.githubusercontent.com/15215123/168958863-2b46ab63-05e1-48ec-bd90-bf383b01aaa8.png)

Could you come to the Telegram Group, and we share you a working beta 1.51 that solve that problem?

**Comment by Krysinski** [comment]
> > I have same issue with 1.46a and 470 driver. I try to use 510 drivers on linux and 1.50 version, but lolminer cant recognise my 1060 5G: cuda device not detected. i use "--maxdualimpact *,10,10,10,10 --dualdevices 0", there is not enough memory for DAG in gpu 0 for mining eth (x-server take some). 1060 5G (gpu 1 - gpu 4) have 160 bit membus and give only 17 Mh/s on eth, but for TON i see about 1100 Mh/s and 0 shares all time. 1060 5G (gpu 0) have 192 bit membus and give 21 Mh/s on eth some time ago, now it give only TON 800 Mh/s and normal shares. ![image](https://user-images.githubusercontent.com/15215123/168957982-62eeef2c-9bfa-4a4d-b109-2cfd3cc2c4f7.png) ![image](https://user-images.githubusercontent.com/15215123/168958863-2b46ab63-05e1-48ec-bd90-bf383b01aaa8.png)
> 
> Could you come to the Telegram Group, and we share you a working beta 1.51 that solve that problem?

yes, i can try. Group name?

**Comment by jgonzis** [comment]
Working... new release 1.51
