### ISSUE TITLE
>lolminer: Unrecoverable memory error by GPU 0.

### ISSUE THREAD

**Issue by LaenorSama** [Lolliedieb/lolMiner-releases#1241]
![image](https://user-images.githubusercontent.com/55910514/153731129-7c1e5c44-5b56-4e72-b9b3-8b7ac1ca7d32.png)
A video card memory error often appears. hive os

**Comment by maxprogenuine** [comment]
Thank you for your solution concerning about this issue @jgonzis 🙏🙂
I will do the suggestion to solve my problem right now. So, i'm happy to come by here because i can read many discussion about my ETH mining especially using Hive OS under Linux.
