### ISSUE TITLE
Dual mining Ergo +  Ton 

### ISSUE THREAD

**Issue by Hoboter** [Lolliedieb/lolMiner-releases#1242]
greetings, dear programmer!
it would be great if you add support for Ergo+Ton dual mining for nvidia 1000 series ...
The load on the GPU cores at Ergo is quite low during the search for solutions and rises only during the generation of the dataset - at this point the mining tone can be suspended. that is, the mode of such dual mining should have a good increase in returns and may be in demand not only on 3GB 1060, but also on many other models of this series, for which mining ETH+Ton in dual mode does not make sense, due to the high load on GPU cores.
Have you considered this option for adding to the new versions of lolminer?

**Comment by jgonzis** [comment]
> greetings, dear programmer! it would be great if you add support for Ergo+Ton dual mining for nvidia 1000 series ... The load on the GPU cores at Ergo is quite low during the search for solutions and rises only during the generation of the dataset - at this point the mining tone can be suspended. that is, the mode of such dual mining should have a good increase in returns and may be in demand not only on 3GB 1060, but also on many other models of this series, for which mining ETH+Ton in dual mode does not make sense, due to the high load on GPU cores. Have you considered this option for adding to the new versions of lolminer?

At the moment ERGO  + TON is not possible, because ERGO use Core the same that uses TON so that will not work... It will just underperformance all
