### ISSUE TITLE
Mixed rig, only Nvidia Cards show NA hashrate

### ISSUE THREAD

**Issue by saifiasif** [Lolliedieb/lolMiner-releases#1243]
Hello guys,
So Im mining ETH + ton.  I got this error where lolminer shows me NA hash rate ( doesn't start) on Nvidia cards only if I put the OC delay time 0 sec (disabled). If I use 30 secs it would be fine until the miner restarts and since the oc is already applied it doesn't start just shows me NA. This happens only on Nvidia cards and AMD cards are fine. I'm running a rig with 13 cards  ( 12 Nvidia, 1 AMD).
Mobo: Asrock H110, 8gb ram, USB stick, 2 3080, 9 3070ti, rx580 8gb, all with risers. The risers are fine i can mine eth with no problems its just ETH + TON.
The error for the 12 gpus was error failed to created dag for all 12 nvidia on hiveos miner screen.
 Any input would be appreciated

**Comment by jgonzis** [comment]
> Hello guys, So Im mining ETH + ton. I got this error where lolminer shows me NA hash rate ( doesn't start) on Nvidia cards only if I put the OC delay time 0 sec (disabled). If I use 30 secs it would be fine until the miner restarts and since the oc is already applied it doesn't start just shows me NA. This happens only on Nvidia cards and AMD cards are fine. I'm running a rig with 13 cards ( 12 Nvidia, 1 AMD). Mobo: Asrock H110, 8gb ram, USB stick, 2 3080, 9 3070ti, rx580 8gb, all with risers. The risers are fine i can mine eth with no problems its just ETH + TON. The error for the 12 gpus was error failed to created dag for all 12 nvidia on hiveos miner screen. Any input would be appreciated

Well TON takes 2 Minnute to appear in HiveOS stats... COuld you also share your OC ? it could be you are not using lock Core and you still don't have PL to 0... Many thanks in advance

**Comment by saifiasif** [comment]
Thank you for the reply. it's just this one rig with this problem the others are mining fine. PL was 0, OC reduce all by 200-300mhz from what was stable in ETH ( for approx 17 days). lockcore is used. Please see below picture ( there was a time i left it like this for 9 hours, there was no change (please note 2 differerent pics with diff cclks)
![121](https://user-images.githubusercontent.com/73171200/153749472-ea16418e-ccb6-472b-83ea-ffbb745804b5.PNG)
)
![22222](https://user-images.githubusercontent.com/73171200/153749519-e16f2a30-6651-48d3-88c6-1b2769623e0b.PNG)

**Comment by saifiasif** [comment]
This is the fightsheet
![image](https://user-images.githubusercontent.com/73171200/153749618-dd7cd175-d4b9-4fc9-ba43-9a36a8a2eb8b.png)

**Comment by jgonzis** [comment]
> This is the fightsheet ![image](https://user-images.githubusercontent.com/73171200/153749618-dd7cd175-d4b9-4fc9-ba43-9a36a8a2eb8b.png)

Please select only 1 server
Remove Dagdelay , lhrwait and also try 1st without --maxdualimpact, remove worker2 name.

Try...

**Comment by saifiasif** [comment]
this happened
![2](https://user-images.githubusercontent.com/73171200/153757669-c3189a1b-8e9b-4b37-9195-b53f54d7e4ee.PNG)
![1](https://user-images.githubusercontent.com/73171200/
![12121212](https://user-images.githubusercontent.com/73171200/153757867-f3c5eded-2553-43c8-a835-517f5d6ac3ec.PNG)
153757681-6ea73c92-8279-475b-8269-366070426d0d.PNG)
d

**Comment by jgonzis** [comment]
> this happened ![2](https://user-images.githubusercontent.com/73171200/153757669-c3189a1b-8e9b-4b37-9195-b53f54d7e4ee.PNG) ![1](https://user-images.githubusercontent.com/73171200/ ![12121212](https://user-images.githubusercontent.com/73171200/153757867-f3c5eded-2553-43c8-a835-517f5d6ac3ec.PNG) 153757681-6ea73c92-8279-475b-8269-366070426d0d.PNG) d

Many thanks, you have there the information... please reduce GPU 10 memory. That GPU is unluckily not silicon lottery.   It is not very high but that value is too much. Try reducing it or you will continue having crashes.  Sometimes is also riser or socket of the Motherboard. Starting first lowering Memory.

I recommend you to active watchdog of HiveOS to automatically restart rig and autorestart mining
