### ISSUE TITLE
Some issues 1.44 in windows

### ISSUE THREAD

**Issue by sosme2012** [Lolliedieb/lolMiner-releases#1244]
1：no fan control
2：--cclk and --mclk doesn't work on 6 cards.
eg: --cclk 1200,1200,1150,1150,1150,1200 --mclk 1300,1300,1300,1300,1300,1300.
only devices 1 & 2 work.
3：Core frequency fluctuations will lead to loss of hashrate in non lhr card.

**Comment by jgonzis** [comment]
> 1：no fan control 2：--cclk and --mclk doesn't work on 6 cards. eg: --cclk 1200,1200,1150,1150,1150,1200 --mclk 1300,1300,1300,1300,1300,1300. only devices 1 & 2 work. 3：Core frequency fluctuations will lead to loss of hashrate in non lhr card.

1: To Fan control and Memory use external Apps like MSI Afterburner.
2: To Clock it will only fix Nvidia Ampere and Turing. For that you have to use the last bat file from 1.44, and also remember to add lolMiner.exe Run As Administrator or it will not be able to fix the Core. The parameter --mclk you are using it was a paramter used only to TON to put a specific Memory State to reduce Watts, it is not used for ETH. For that use MSI Afterburn.
3: If you want to block the NO LHR GPUs, you can use --lhrtune auto,off,auto,auto that will make for example that NOLHR GPU1 to not be detected as LHR

Also if you want to load a Directly Profile in MSI Afterburner, edit the bat file and add the beginning: 

C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe -Profile1

That will load Profile1 of MSI Afterburner automatic...  You can different profiles depening the COIN

**Comment by drond1** [comment]
> Also if you want to load a Directly Profile in MSI Afterburner, edit the bat file and add the beginning:
> 
> C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe -Profile1
> 
> That will load Profile1 of MSI Afterburner automatic... You can different profiles depening the COIN

Hello, can you show how it should look in bat file ?

**Comment by jgonzis** [comment]
![image](https://user-images.githubusercontent.com/38668405/154138374-57b25f70-928e-41f2-9d5d-6e39defe0a96.png)

**Comment by drond1** [comment]
> ![image](https://user-images.githubusercontent.com/38668405/154138374-57b25f70-928e-41f2-9d5d-6e39defe0a96.png)
Not works. Lolminer 1.44
![image](https://user-images.githubusercontent.com/99704990/154372952-8dbd3bf4-1d24-45d4-9551-4c08271c1f1f.png)

**Comment by drond1** [comment]
Solved. It must looks like "C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -Profile1
then it works, with ""

**Comment by jgonzis** [comment]
> Solved. It must looks like "C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -Profile1 then it works, with ""

Thx for the correction you are right... try to delete old version of lolminer, it seems running in folder 1.41b.is it right?
