### ISSUE TITLE
ETH+TON the problem

### ISSUE THREAD

**Issue by Heaven20222022** [Lolliedieb/lolMiner-releases#1245]
Double dig ETH+TON process kept encounter lock card, unlock, lock again, calculate the force does not come
![20220213123708](https://user-images.githubusercontent.com/99574545/153739046-aa44a20f-f643-4f83-a526-077e2a712b2b.jpg)
.

**Comment by Heaven20222022** [comment]
3060TI LHR

**Comment by jgonzis** [comment]
> Double dig ETH+TON process kept encounter lock card, unlock, lock again, calculate the force does not come ![20220213123708](https://user-images.githubusercontent.com/99574545/153739046-aa44a20f-f643-4f83-a526-077e2a712b2b.jpg) .

I suppose you are in Windows... Remember to use Nvidia Driver 472.12
Use also 1.44, 1.43 works too but 1.44 seems better stability.
PL to 100% 
--cclk in the bat file, remember to use the 1.44 or the add in release section 1.43 and also very important. You have to put lolMiner.exe as Run As Administrator

![image](https://user-images.githubusercontent.com/38668405/153747273-8eb71ae8-c416-40af-84b0-756be61f61be.png)

If your rig is big, it could be an option to go to HiveOS to control all easy and without less problem. 

https://youtu.be/5tP3CeSbgJk
