### ISSUE TITLE
Lolminer 1.44 Crashing and Reload

### ISSUE THREAD

**Issue by tuttexx** [Lolliedieb/lolMiner-releases#1246]
I need help with this rig mining error ETH+TON

![Captura de pantalla 2022-02-12 a la(s) 05 37 49](https://user-images.githubusercontent.com/99583684/153744115-b2555b6a-375e-4471-ab03-14a53d3ef9c3.png)

**Comment by jgonzis** [comment]
Could you show what's happening during mining, or your OC, or which Pool of TON are you mining. It has been several crashes for TON pools stability. I close it until you give more information please
