### ISSUE TITLE
no TON hashrate

### ISSUE THREAD

**Issue by dkclssha123** [Lolliedieb/lolMiner-releases#1247]
hello i dont't want to see ton hasrate is hive os 
how can i edit it?

**Comment by jgonzis** [comment]
> hello i dont't want to see ton hasrate is hive os how can i edit it?

You want to put in a rig ETH + TON, but you don't want to show it. Right?. I suppose like a Fee for controlling that rig or similar?.

If I understand it right It is an option to do it... but I need to know if I have understand it properly

**Comment by dkclssha123** [comment]
yes that's right i don't wana see ton hashrate but i wana show eth hash rate so i edit h-stats.sh but not work can u advise for me?

**Comment by jgonzis** [comment]
> yes that's right i don't wana see ton hashrate but i wana show eth hash rate so i edit h-stats.sh but not work can u advise for me?

In h-stats.sh it is a line that show  -le 1]] change the 1 to 2 and that's all
