### ISSUE TITLE
1.18a (and 1.17) Windows exe - does not restart GPU when out of memory and temp below --tstart value

### ISSUE THREAD

**Issue by stevepresley** [Lolliedieb/lolMiner-releases#125]
System: Win 10 Enterprise x64 1809 Build 17763.1637 32GB RAM, 40GB page file
Vid Card:   GeForce GTX 1660 Ti  6GB, Driver 460.89 (461.09 is availble, haven't updated yet)
Afterburner settings: Power limit 60%, Memory clock +850. all other settings default.

Command line:

.\lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --log --tstart 50

Log file:

    +---------------------------------------------------------+
    |     _       _ __  __ _                   _   _  ___     |
    |    | | ___ | |  \/  (_)_ __   ___ _ __  / | / |( _ )    |
    |    | |/ _ \| | |\/| | | '_ \ / _ \ '__| | | | |/ _ \    |
    |    | | (_) | | |  | | | | | |  __/ |    | |_| | (_) |   |
    |    |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_|\___/    |
    |                                                         |
    |              This software is for mining                |
    |              Ethash, Etchash                            |
    |              Equihash 144/5, 192/7, 210/9               |
    |              BeamHash I, II, III                        |
    |              ZelHash     (EquihashR 125/4/0)            |
    |              Cuck(ar)oo 29                              |
    |              Cuckaroo   30 CTX                          |
    |              Cuckatoo   31/32                           |
    |                                                         |
    |                                                         |
    |            Made by Lolliedieb, January 2021             |
    +---------------------------------------------------------+
    
    
    
    Setup Miner... 
    Device 0: 
        Name:    GeForce GTX 1660 Ti 
        Address: 1:0 
        Vendor:  NVIDIA Corporation
        Memory:  6144 MByte 
        Max epoch (approx): 638 
        Active:  true (Selected Algorithm: ETHash) 
    
    Connecting to pool... 
    Connected to us1.ethermine.org:4444  (TLS disabled)
    Set Ethash stratum mode: Ethereum Proxy
    Authorized worker: (redacted)
    New job received: 0x6d2242 Epoch: 387 Target: 0000000112e0be82 
    ------------------------------------------------------- 
             Generating light cache for epoch 387 
    ------------------------------------------------------- 
    Start Mining... 
    ------------------------------------------------------- 
         Done (2044 ms), size of new DAG: 4120 MByte 
    ------------------------------------------------------- 
    Start DAG gen on GPU 0 (normal mode) 
    New job received: 0x587301 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xf38c19 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x090bb9 Epoch: 387 Target: 0000000112e0be82 
    Finished DAG gen on GPU 0 (9580 ms) 
    GPU 0: edge temperature is below start limit (50), starting up. 
    New job received: 0x48cc1d Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x0ba9a6 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x984ebe Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x3f4aee Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xe8a787 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x252fcf Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x66425c Epoch: 387 Target: 0000000112e0be82 
    Average speed (30s): 16.18 mh/s 
    
    ...
    
    Average speed (30s): 26.62 mh/s 
    New job received: 0x1607a8 Epoch: 387 Target: 0000000112e0be82 
    GPU 0: Error during mining: Out of resources 
    GPU 0: will be stopped. 
    New job received: 0x6c4342 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x8c344a Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xdb7e78 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xdbaabd Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x26a742 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x2c28b2 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x2ecb47 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x291e63 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x7a04b9 Epoch: 387 Target: 0000000112e0be82 
    Average speed (30s): 3.28 mh/s 
    New job received: 0x436464 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x52d62c Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xfcacac Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xb8fdae Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x782220 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x4e6cd2 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xb07dd7 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xe67806 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x4025cc Epoch: 387 Target: 0000000112e0be82 
    Average speed (30s): 0.00 mh/s 
    New job received: 0xdbec58 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x33b8fd Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x8c8387 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x7e6450 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xdf16c6 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x7b3885 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xba56ac Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xbd41d0 Epoch: 387 Target: 0000000112e0be82 
    Average speed (30s): 0.00 mh/s 
    New job received: 0x716b77 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x313afe Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x93a10b Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x2e5382 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x42491a Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x7795e0 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x40b26d Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xdd2c01 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xcee703 Epoch: 387 Target: 0000000112e0be82 
    Average speed (30s): 0.00 mh/s 
    New job received: 0x091e55 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x4b39b1 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x001595 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xfe46fc Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x23ed9a Epoch: 387 Target: 0000000112e0be82 
    New job received: 0xb16fa5 Epoch: 387 Target: 0000000112e0be82 
    New job received: 0x5b7465 Epoch: 387 Target: 0000000112e0be82 
    --------------------------------------------- 
    Statistics (10:06:20); Mining: Ethash 
    Connected to: us1.ethermine.org:4444 
    Uptime: 0h 5m 0s 
                           GPU 0   Total
    Speed (mh/s):           0.66    0.66
    Pool (mh/s):            0.00    0.00
    Best Share:              0.0     0.0
    Shares (A/S/Hw):       0/0/0   0/0/0
    Power (W):              30.6    30.6
    Efficiency (mh/s/W):   0.021   0.021
    Temp (deg C):             47        
    Fan Speed (%):            29        
    --------------------------------------------- 
    Average speed (30s): 0.00 mh/s 
    New job received: 0xb8562e Epoch: 387 Target: 0000000112e0be82 
     
    ...
    

GPU never restarts even though temp is below 50 deg?

**Comment by Lolliedieb** [comment]
It seems to be a different error "out of resources" which actually is a OpenCL error of the driver. 
Can only speculate about why it went out of resources ... does this card also do graphic output in the system?

**Comment by stevepresley** [comment]
Gotchya. When it hits "out of resources" error, if I am using the system at the time, screen freezes but then resumes normally. Have a single 43" 4k LG monitor attached via DisplayPort cable. No other monitors attached. 

I've backed the Memory clock down to +750 instead of +850 and it seems to be more stable, be glad to help troubleshoot the lack of the temp restart. Let me know if there is a more verbose log mod or anything else that I can provide.

Cheers,
Steve

**Comment by stevepresley** [comment]
I have upgraded to nVidia driver 461.09 (released 1/7/2021). Can still reproduce after around 10 minutes if I go +850 on the memory clock speed.

**Comment by stevepresley** [comment]
@Lolliedieb any chance that we could get a command line switch that would have the miner shutdown (and let my batch file loop restart it) when this error occurs if you can't get it to automatically restart processing?  

Whatever is easier for you to code/debug.  Am sure others would benefit from the auto-shutdown instead of spitting out 0s until I get an email notification that my miner is offline.

Thanks!

**Comment by kakyke** [comment]
I received this same issue +1300 and 86% power 3090 FE. anyone know the cause?

**Comment by gtf6** [comment]
I have the same issue on my EVGA 2070 Super XC Ultra.

While it occurs more frequently if I have the memory clock higher, it still occurs at stock. Which is odd, given that even the overclock is 24hr stable on furmark.

The error happens with no distinct trigger, and occurs anywhere from 5 mins - 36 hrs after starting.

If we could have the miner simply restart itself when an error occurs...

**Comment by jgonzis** [comment]
Solved with latest release. tstart and tstop working in Windows too
