### ISSUE TITLE
All devices deselected or failed compatiblity check. Closing lolMiner

### ISSUE THREAD

**Issue by ussourwood** [Lolliedieb/lolMiner-releases#1252]
Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    Intel(R) UHD Graphics
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  6455 MByte
    Active:  false (not selected)

All devices deselected or failed compatiblity check. Closing lolMiner

C:\lolMiner_v1.44_Win64\1.44>

How to resolve the issue?

**Comment by jgonzis** [comment]
> Setup Miner... OpenCL driver detected. Number of OpenCL supported GPUs: 1 No Cuda driver or GPUs detected. Device 0: Name: Intel(R) UHD Graphics Address: 4294967295:4294967295 Vendor: Intel(R) Corporation Drivers: OpenCL Memory: 6455 MByte Active: false (not selected)
> 
> All devices deselected or failed compatiblity check. Closing lolMiner
> 
> C:\lolMiner_v1.44_Win64\1.44>
> 
> How to resolve the issue?

We are sorry but oyu need a dedicated GPU to mine. You cannot use the Integrated GPU of the CPU
