### ISSUE TITLE
the looping of the lhr search

### ISSUE THREAD

**Issue by PolyakRussia** [Lolliedieb/lolMiner-releases#1253]
Good afternoon. Windows 10. drivers 472.12. 2 riga. In one 6 pcs not LHR 3080, 1 pc not LHR 3070, 3 pcs 3080 ti. In 2 Riga 3 pcs 3080 ti. When launching the t-rex miner on Ethereum, my 3080 ti mine 91-95 mx. When dual mining with an alephium coin shows 80-85 mx. 
When dual mining in the lol manner 1.43 or 1.44 shows from 0 to 80 mx. Constant looping of the lhr search. The value reaches -1500. If xp is fixed, then the mx value is very low in the region of 70 mx. 
I apologize for the English. Google translate.
![Screenshot_2022-02-14-07-00-56-898_com anydesk anydeskandroid](https://user-images.githubusercontent.com/99628626/153794701-1fdf0eb8-108e-4da5-8802-eb822763379d.jpg)
![Screenshot_2022-02-14-07-01-42-103_com anydesk anydeskandroid](https://user-images.githubusercontent.com/99628626/153794708-3f2fcb07-b1e6-4736-b85f-6eed49b5c9e1.jpg)

**Comment by jgonzis** [comment]
I see you are not using Lock Core. It could be for several reason. PL is not to 100% and you don't use LOCK Core
It could be that GDDR6X reach Memory Temp ... 

We have add a Guide how to put Lock Core in lolMiner. For that 3080TI, with a lock Core aroun 1200-1260 should it work perfectly.

[https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,-Watchdog,-WebServer,...)](https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,-Watchdog,-WebServer,...))
