### ISSUE TITLE
1.18a Geforce GT 645M

### ISSUE THREAD

**Issue by Kyllu** [Lolliedieb/lolMiner-releases#126]
There is a chance that it works on this card?
+---------------------------------------------------------+
|     _       _ __  __ _                   _   _  ___     |
|    | | ___ | |  \/  (_)_ __   ___ _ __  / | / |( _ )    |
|    | |/ _ \| | |\/| | | '_ \ / _ \ '__| | | | |/ _ \    |
|    | | (_) | | |  | | | | | |  __/ |    | |_| | (_) |   |
|    |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_|\___/    |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|            Made by Lolliedieb, January 2021             |
+---------------------------------------------------------+

Setup Miner...
Device 0:
    Name:    GeForce GT 645M
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  2048 MByte
    Problem in loading kernel

**Comment by jgonzis** [comment]
Not supported GPU to old
