### ISSUE TITLE
How to enable dual mining on some cards and keep single mining on the other cards?

### ISSUE THREAD

**Issue by skygunner** [Lolliedieb/lolMiner-releases#1262]
I wish to enable mining ETH+TON on devices 3 4 5 6, and keep all the cards mining ETH only, can't seem to figure out how to do this. 

--dualdevices is for letting the cards mine the 2nd coin, not dual mining on them.

**Comment by Kostas-13** [comment]
Use then:  --devices "3,4,5,6" and mine Eth+Ton at lolminer for the specific gpus.
Then open a 2nd Eth miner of your choice for the rest of them and disable ofc there the 3,4,5,6 cards.

**Comment by skygunner** [comment]
Then this is a lose of profit for lolminer lol

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kostas-13** [comment]
I didn't said run something else.. I said run a 2nd miner of yr choice that could be eth lolminer or whatever u prefer eg.
=>dual_mine_eth_ton_toncoinpool.bat (lolminer)
and
=>mine_eth.bat (lolminer)

**Comment by jgonzis** [comment]
> I wish to enable mining ETH+TON on devices 3 4 5 6, and keep all the cards mining ETH only, can't seem to figure out how to do this.
> 
> --dualdevices is for letting the cards mine the 2nd coin, not dual mining on them.

Hi You should use --maxdualimpact 0,0,0,*,*,*,*  that will mine 0 TON in GPU 0,1,2 and dual in 3,4,5,6.
