### ISSUE TITLE
3070 LHR dual mining ETH TON in HiveOS = keeps getting LHR locked

### ISSUE THREAD

**Issue by orangpelupa** [Lolliedieb/lolMiner-releases#1263]
it goes to lhrtune value -74 and it is still getting lhr locked. I have tried with

- no OC, no PL
- no OC, 180 PL
- 200 core OC, no PL
- 200 core OC, 180 PL

all results in lhr locks.

**Comment by rokkiemaru** [comment]
Same issue here in windows, with 3070 LHR keep unlocking and pausing.

**Comment by nCr78** [comment]
Same issue while dual mining ETH + TON with 3070 Ti on Windows 10, driver version 472.12, any OC (fixed / not-fixed core, mem OC etc is irrelevant, even after 1 hour). Only clue I have is that it's the main GPU that the system uses - the rest of the GPUs are not locking.

**Comment by jgonzis** [comment]
> Same issue while dual mining ETH + TON with 3070 Ti on Windows 10, driver version 472.12, any OC (fixed / not-fixed core, mem OC etc is irrelevant, even after 1 hour). Only clue I have is that it's the main GPU that the system uses - the rest of the GPUs are not locking.

That sometimes happen for an external use of Windows, if you have a Intel you can try to use the integrated CPU... or increase a lot more the CORE Lock of the primary GPU, just to have enough margin to avoid that windows use. 

> it goes to lhrtune value -74 and it is still getting lhr locked. I have tried with
> 
> * no OC, no PL
> * no OC, 180 PL
> * 200 core OC, no PL
> * 200 core OC, 180 PL
> 
> all results in lhr locks.

Try to follow the guide: https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,-Watchdog,-WebServer,...)
