### ISSUE TITLE
Can you add bat file for https://alephium-pool.com ?

### ISSUE THREAD

**Issue by yahorbukhta** [Lolliedieb/lolMiner-releases#1265]
Server: detect-my-region.alephium-pool.com:20032

**Comment by jgonzis** [comment]
> Server: detect-my-region.alephium-pool.com:20032

You just only need to edit the Bat file ... we have put like a zone to edit and you will be able to put there your wallet and the pool really easy :-)

**Comment by yahorbukhta** [comment]
Please, write to me conditions for creating bat file.

nnslvp@gmail.com

@jgonzis
