### ISSUE TITLE
Aleph dual mode freezes system

### ISSUE THREAD

**Issue by Basement-Science** [Lolliedieb/lolMiner-releases#1266]
using the example script (`dual_mine_eth_aleph.bat`) or other command lines, on my system the miner manages to almost completely freeze the system, so much that it is hard to even terminate. No errors are displayed.

Windows 11, 1x 5700 XT

**Comment by jgonzis** [comment]
> using the example script (`dual_mine_eth_aleph.bat`) or other command lines, on my system the miner manages to almost completely freeze the system, so much that it is hard to even terminate. No errors are displayed.
> 
> Windows 11, 1x 5700 XT

Could you please try if happens the same with the dual_mine_eth_ton? just to be sure where is problem?.

Or try just only running --devices 1 only 1 gpu... to have more information.

**Comment by jgonzis** [comment]
> using the example script (`dual_mine_eth_aleph.bat`) or other command lines, on my system the miner manages to almost completely freeze the system, so much that it is hard to even terminate. No errors are displayed.
> 
> Windows 11, 1x 5700 XT
Known windows issue: do not have any browser window open while miner is tuning on amd

**Comment by cbrwx** [comment]
perhaps tune down ur cards a bit until it works, or even better no overclock and take it from there? You give no information either, bout ur setup; nor ur overclock settings, if any.

**Comment by jgonzis** [comment]
> perhaps tune down ur cards a bit until it works, or even better no overclock and take it from there? You give no information either, bout ur setup; nor ur overclock settings, if any.

It seems a bug not yet know... if a explorer is open it gets hangs up until some time latter than return to normally

**Comment by Basement-Science** [comment]
> Could you please try if happens the same with the dual_mine_eth_ton? just to be sure where is problem?.
> Or try just only running --devices 1 only 1 gpu... to have more information.

Dual mining TON works fine for me, this happens only with the new `--dualmode ALEPHDUAL`
Only 1 GPU is installed in the system. The driver also does NOT crash.

**Comment by jgonzis** [comment]
> > Could you please try if happens the same with the dual_mine_eth_ton? just to be sure where is problem?.
> > Or try just only running --devices 1 only 1 gpu... to have more information.
> 
> Dual mining TON works fine for me, this happens only with the new `--dualmode ALEPHDUAL` Only 1 GPU is installed in the system. The driver also does NOT crash.

Did you try it?

It only happens in AMD in Windows at the moment
Known windows issue: do not have any browser window open while miner is tuning on amd

**Comment by Basement-Science** [comment]
> Did you try it?

**Yes**, with `dual_mine_eth_ton.bat` there is no freeze. But there is this issue: #1269 
So the output is: 
```
> New job received: 0x7b6036 Epoch: 473 Difficulty: 4.30G
> Pool https://next.ton-pool.com timeout or send defect message: "<unspecified file>(1): expected value"
> Pool https://next.ton-pool.com timeout or send defect message: "<unspecified file>(1): expected value"
> New job received: 0xf5c856 Epoch: 473 Difficulty: 4.30G
> Ethash: Average speed (15s): 51.00 Mh/s
> SHA256-TON: Average speed (15s): 662.96 Mh/s
> Pool https://next.ton-pool.com timeout or send defect message: "<unspecified file>(1): expected value"
```
With my own config dualMining on tonWhales pool, there are no issues at all.

> 
> It only happens in AMD in Windows at the moment Known windows issue: do not have any browser window open while miner is tuning on amd

I will try that in a few minutes.

**Comment by Basement-Science** [comment]
Ok, did a bunch more tests. This is what I tried:
- Closing more and more programs.
- OC to stock and my usual ETH settings, which both are 100% stable in all applications including games, productivity, and all mining programs/algos I've tried
- restarting GPU
- rebooting OS

None of the above made any difference. In all these cases the system freezes more and more. The only way to terminate the miner was always to press `ctrl+shit+win+B` and then quickly kill it with task manager.
There was 1 attempt out of at least 15, where it actually worked fine, no idea why. It started mining and showed a hashrate for both algos and system was responsive. Seemed to be random. Next attempts without any changes failed again.

I found out something else:
I tried supplying **_invalid_** Pool URLs for ALEPH and ETH pools (in `dual_mine_eth_aleph.bat`). With invalid ALEPH pool, the same problem occurs. With invalid ETH pool, there is no freezing issue, and it does not matter if ALEPH pool is valid, it does not mine anything either way. So it seems to be related to **ETH startup**.

**Comment by jgonzis** [comment]
> Ok, did a bunch more tests. This is what I tried:
> 
> * Closing more and more programs.
> * OC to stock and my usual ETH settings, which both are 100% stable in all applications including games, productivity, and all mining programs/algos I've tried
> * restarting GPU
> * rebooting OS
> 
> None of the above made any difference. In all these cases the system freezes more and more. The only way to terminate the miner was always to press `ctrl+shit+win+B` and then quickly kill it with task manager. There was 1 attempt out of at least 15, where it actually worked fine, no idea why. It started mining and showed a hashrate for both algos and system was responsive. Seemed to be random. Next attempts without any changes failed again.
> 
> I found out something else: I tried supplying **_invalid_** Pool URLs for ALEPH and ETH pools (in `dual_mine_eth_aleph.bat`). With invalid ALEPH pool, the same problem occurs. With invalid ETH pool, there is no freezing issue, and it does not matter if ALEPH pool is valid, it does not mine anything either way. So it seems to be related to **ETH startup**.

Many thanks for the feedback... we are looking on it

**Comment by jgonzis** [comment]
Try 1.46 that should be solved now.

**Comment by Basement-Science** [comment]
Yep works now, thanks!

**Comment by jgonzis** [comment]
> Yep works now, thanks!

Many thanks for the feedback
