### ISSUE TITLE
So how do I log in to the GUI, I see no port number given

### ISSUE THREAD

**Issue by YaakovLi** [Lolliedieb/lolMiner-releases#1267]

**Comment by jgonzis** [comment]
http://localhost:8080/gui

From another computer just put: http://ip_of_the_rig:8080/gui

**Comment by dotas86** [comment]
I too cannot view the gui from this or any other PC. Maybe it does not work for everyone?

**Comment by jgonzis** [comment]
> I too cannot view the gui from this or any other PC. Maybe it does not work for everyone?

You need to have at least 1.45, and which OS are you using?

**Comment by dotas86** [comment]
Yes, I use1.45 and I'm on Windows 10 21H2

**Comment by jgonzis** [comment]
> Yes, I use1.45 and I'm on Windows 10 21H2

Have you add that --apiport ? 
Could you check you see that in the miner in stats 60s:
![image](https://user-images.githubusercontent.com/38668405/155001823-0c3499e3-aeb0-4041-9afc-102c49580894.png)

**Comment by dotas86** [comment]
That line is missing from my statistics
![statistics lolminer](https://user-images.githubusercontent.com/20579775/155002731-efead4da-bb86-4e53-9b0c-4ca7b427141a.PNG)
.

**Comment by jgonzis** [comment]
> That line is missing from my statistics ![statistics lolminer](https://user-images.githubusercontent.com/20579775/155002731-efead4da-bb86-4e53-9b0c-4ca7b427141a.PNG) EDIT: I can see multiple lines being totally different or missing. I am guessing the colors can be changed by the user, otherwise that's also something different on my part.

that means you haven't add in your bat file the "--apiport 44444"

**Comment by dotas86** [comment]
I am a moron. I did have the command in the bat file, I had it after the = sign which just didn't work. Now it works that I have corrected it. Thanks!
