### ISSUE TITLE
dualdevices version 1.45

### ISSUE THREAD

**Issue by rashrrr** [Lolliedieb/lolMiner-releases#1268]
dualdevices dont work for ETH+ALPH dual mining

**Comment by jgonzis** [comment]
> dualdevices dont work for ETH+ALPH dual mining

You are right... is not working yet. You can only mine ETH, or ETH+ALPH not option to mine only ALPH at the moment.

**Comment by ahmed150222** [comment]
It doesn’t mine in ton pool, 1.43 version does. Rig and miner work, but hashrate in ton-pool shows 0.

**Comment by jgonzis** [comment]
> It doesn’t mine in ton pool, 1.43 version does. Rig and miner work, but hashrate in ton-pool shows 0.

Could you put a photo or something? that will help...
