### ISSUE TITLE
Ton-pool stolled mining 

### ISSUE THREAD

**Issue by kotopuz** [Lolliedieb/lolMiner-releases#1269]
1.44 mining was ok for eth and ton.
Using toon-pool
Using latest raveos.
No change was made, only updated miner. 
Using config
--dualmode TONDUAL --dualpool https://next.ton-pool.com  --dualuser tonwallet

![Screenshot_20220215-211605_Chrome](https://user-images.githubusercontent.com/34707464/154142717-2d77fec2-eda2-4bdd-8731-da240576c659.jpg)

**Comment by cbrwx** [comment]
same issue here, i reverted back to 1.44 until next release.

**Comment by kotopuz** [comment]
I went back to 1.43 which is working. 1.44 occasionally working.

**Comment by Basement-Science** [comment]
I think ton-pool might have done something, it was working earlier today with v1.45.
Getting the same error now on Windows 11.

**Comment by kotopuz** [comment]
Well. I think it's not pool, because version 1.43 works fine. May be something with the timings

**Comment by chrishilbert** [comment]
Also having this issue when going to 1.45 from 1.44.  No issues with ton-pool besides random miner crashes on 1.44.

**Comment by AirLucius** [comment]
I have the same error at https://next.ton-pool.com v1.45

**Comment by t-prod** [comment]
Me too back on 1.43

**Comment by Anton-Nikishkin** [comment]
same issue

**Comment by sebek72** [comment]
use --ton-mode 2 (for ton-pool.com)

**Comment by kotopuz** [comment]
> use --ton-mode 2 (for ton-pool.com)

What will be full command then? The one below?

--dualmode TONDUAL --dualpool https://next.ton-pool.com/ --dualuser tonwallet --ton-mode 2

**Comment by sebek72** [comment]
with mode 2 it works, but also not stable. Back to 1.43

**Comment by kotopuz** [comment]
> 

Same.

**Comment by kotopuz** [comment]
> with mode 2 it works, but also not stable. Back to 1.43
Actually 1.43 also not stable. Keep getting miner restarted after error. Somehow I can't get stable run for a long time with 1.43 44 or 45 versions.

**Comment by Jipepe13** [comment]
When using lolMiner 1.45 or above, please use the new pool address wss://eu1.stratum.ton-pool.com/stratum
Do not use lolMiner 1.45 or above with the original pool address https://next.ton-pool.com - this may be throttled in the future.

**Comment by kotopuz** [comment]
> When using lolMiner 1.45 or above, please use the new pool address wss://eu1.stratum.ton-pool.com/stratum Do not use lolMiner 1.45 or above with the original pool address https://next.ton-pool.com - this may be throttled in the future.

Thanks you good man. Not sure where you know this from, but for now things wokring fine. Will see in the long run...

**Comment by wardensc2** [comment]
> When using lolMiner 1.45 or above, please use the new pool address wss://eu1.stratum.ton-pool.com/stratum Do not use lolMiner 1.45 or above with the original pool address https://next.ton-pool.com - this may be throttled in the future.

After follow your guide, my rig show ton hashrate but when I check with telegram bot of ton-pool.com  show zero ton and hashrate. How can I check and withdraw ton

**Comment by Jipepe13** [comment]
> > When using lolMiner 1.45 or above, please use the new pool address wss://eu1.stratum.ton-pool.com/stratum Do not use lolMiner 1.45 or above with the original pool address https://next.ton-pool.com - this may be throttled in the future.
> 
> Thanks you good man. Not sure where you know this from, but for now things wokring fine. Will see in the long run...

Just on official telegram chanel: https://t.me/next_ton_pool/50

**Comment by Jipepe13** [comment]
> > When using lolMiner 1.45 or above, please use the new pool address wss://eu1.stratum.ton-pool.com/stratum Do not use lolMiner 1.45 or above with the original pool address https://next.ton-pool.com - this may be throttled in the future.
> 
> After follow your guide, my rig show ton hashrate but when I check with telegram bot of ton-pool.com show zero ton and hashrate. How can I check and withdraw ton

Did you had registered your wallet to ton-pool bot?

(sorry if my english is not so good, i'm french)

**Comment by wardensc2** [comment]
> > > When using lolMiner 1.45 or above, please use the new pool address wss://eu1.stratum.ton-pool.com/stratum Do not use lolMiner 1.45 or above with the original pool address https://next.ton-pool.com - this may be throttled in the future.
> > 
> > 
> > After follow your guide, my rig show ton hashrate but when I check with telegram bot of ton-pool.com show zero ton and hashrate. How can I check and withdraw ton
> 
> Did you had registered your wallet to ton-pool bot?
> 
> (sorry if my english is not so good, i'm french)

Of course I already registered. I mined on windows this ton-pool.com with lolminer 1.43

After I switch to Hiveos all version of lolminer cant mine with ton-pool.com. 
Now I mine ton with lolminer 1.44 with tonwhale

Here the telegram image when I switch to new pool address wss://eu1.stratum.ton-pool.com/stratum

![image](https://user-images.githubusercontent.com/77379748/154796043-4fdf14df-ee03-4a59-9f3a-cbabe38bbc2f.png)

**Comment by mrDrauzer** [comment]
To work with NiceHash
And dual Miner Ton
![Решение](https://user-images.githubusercontent.com/59542149/154821418-1ddcb4af-bb62-41cd-a20e-7e691c54311b.png)

**Comment by ams3401** [comment]
wss://na1.stratum.ton-pool.com/stratum

**Comment by jgonzis** [comment]
1.45 with new stratum
Or 
1.46 with old and new stratum without parameters

**Comment by Jipepe13** [comment]
> 1.46 with old and new stratum without parameters
Can you explain please?

**Comment by jgonzis** [comment]
> > 1.46 with old and new stratum without parameters
> > Can you explain please?

1.46 works automatically with: 
 - https://next.ton-pool.com 
- wss://eu1.stratum.ton-pool.com/stratum
