### ISSUE TITLE
1.18a AMD RX BEAM HASHIII miner hangs after few minutes

### ISSUE THREAD

**Issue by mknagec** [Lolliedieb/lolMiner-releases#127]
1.18a, and also all versions after 1.06, miner hangs mining beamhash III on various stable rigs using AMD RX570, RX580, RX560 4G.

Miner starts as normal and after few minutes hangs, system stays stable. Checked multiple times.
Lolminer versions 1.05 and 1.06 are stable and work as intended.

1. RX570 NITRO 1120-1850, W10, driver 19.63, compute enabled, TRM patch for TDR enabled, minig speed 15 sols average
2. RX580 NITRO 1120-1850, W10, driver 19.63, compute enabled, TRM patch for TDR enabled, minig speed 16 sols average
3. RX560 PULSE 1020-1650, W10, driver 19.63, compute enabled, TRM patch for TDR enabled, minig speed 5.9 sols average

1.18a does have some minor mining speed increase, up to 0,7 sols per card, but is seems unstable..

Is there any possible fix?

**Comment by Lolliedieb** [comment]
Hmm ... let me compare what went different in 1.07 .. something must have changed there...

**Comment by mknagec** [comment]
1.20 no change, hangs after some time (15-45mins), miner software only..

**Comment by jgonzis** [comment]
Old thread
