### ISSUE TITLE
Unable to mine ALPH in dual mining 

### ISSUE THREAD

**Issue by itchys** [Lolliedieb/lolMiner-releases#1271]
Constantly getting disconnected from any ALPH server 
Tried a couple of servers but just keeps getting disconnected

![image](https://user-images.githubusercontent.com/98382917/154249742-64950867-f7ad-4c23-978c-f4dca7d16517.png)

**Comment by jgonzis** [comment]
> Constantly getting disconnected from any ALPH server Tried a couple of servers but just keeps getting disconnected
> 
> ![image](https://user-images.githubusercontent.com/98382917/154249742-64950867-f7ad-4c23-978c-f4dca7d16517.png)

the test are working without any issue... It could be also that user is not correct?.... I have been working since yesterday without any error. Try also woolypooly or metapool too

**Comment by itchys** [comment]
ive tried woolypooly but same results

**Comment by jgonzis** [comment]
> I've tried woolypooly but same results I've also tried to ping to server but request always timed out
> 
> after a bit of research I see that only ssl return my ping realized that I didn't add ssl in lol miner for ALPH

Thx for the information... I problem less
