### ISSUE TITLE
1.45 not working on hiveos (ETH/TON)

### ISSUE THREAD

**Issue by shmox75** [Lolliedieb/lolMiner-releases#1272]
Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well.
Please note that I'm using DUAL ETH/TON

**Comment by thejustman** [comment]
ton-pool doesn't work with 1.45, but whalespool DO. on previous version both works fine.

**Comment by jgonzis** [comment]
> Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON

Thanks for giving which Pool are you using... 

We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address

And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.

**Comment by shmox75** [comment]
> > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> 
> Thanks for giving which Pool are you using...
> 
> We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> 
> And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.

Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol

**Comment by jgonzis** [comment]
> > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > 
> > 
> > Thanks for giving which Pool are you using...
> > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> 
> Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol

So then I hope you show your config or the start of the miner... to have some more information

**Comment by shmox75** [comment]
> > > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > > 
> > > 
> > > Thanks for giving which Pool are you using...
> > > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> > 
> > 
> > Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol
> 
> So then I hope you show your config or the start of the miner... to have some more information
![Screen](https://user-images.githubusercontent.com/39054055/154273398-44365b99-889d-436a-a6fc-f2afc0620090.png)

**Comment by jgonzis** [comment]
> > > > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > > > 
> > > > 
> > > > Thanks for giving which Pool are you using...
> > > > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > > > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> > > 
> > > 
> > > Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol
> > 
> > 
> > So then I hope you show your config or the start of the miner... to have some more information
> > ![Screen](https://user-images.githubusercontent.com/39054055/154273398-44365b99-889d-436a-a6fc-f2afc0620090.png)

Your problem is in flightsheet. You cannot connect to eth pool. Share the flightsheet without wallets if you can

**Comment by chudykrzys** [comment]
I have got the same problem. Lolminer can't connect to eth pool.
Same configuration works in V1.44

`Connected to daggerhashimoto.eu-north.nicehash.com(172.65.216.96):3353  (TLS enabled)
Error: Handshake failed with message stream truncated 
Lost connection to stratum server daggerhashimoto.eu-north.nicehash.com:3353 or server not reachable. 
Trying to connect in 5 second(s) `

**Comment by jgonzis** [comment]
> I have got the same problem. Lolminer can't connect to eth pool. The same configuration works with V1.44
> 
> `Connected to daggerhashimoto.eu-north.nicehash.com(172.65.216.96):3353 (TLS enabled) Error: Handshake failed with message stream truncated Lost connection to stratum server daggerhashimoto.eu-north.nicehash.com:3353 or server not reachable. Trying to connect in 5 second(s) `
> 
> ![screenshot-2022-02-16-18-46-58](https://user-images.githubusercontent.com/43378619/154324979-537a1cda-0e92-4eba-b59f-9004197b6254.png)



> I have got the same problem. Lolminer can't connect to eth pool. The same configuration works with V1.44
> 
> `Connected to daggerhashimoto.eu-north.nicehash.com(172.65.216.96):3353 (TLS enabled) Error: Handshake failed with message stream truncated Lost connection to stratum server daggerhashimoto.eu-north.nicehash.com:3353 or server not reachable. Trying to connect in 5 second(s) `
> 
> ![screenshot-2022-02-16-18-46-58](https://user-images.githubusercontent.com/43378619/154324979-537a1cda-0e92-4eba-b59f-9004197b6254.png)

Only add in extra parameters, it is an open bug that is will be solved soon:
`--ethstratum ETHV1`

**Comment by shmox75** [comment]
> --ethstratum ETHV1
![Sans titre](https://user-images.githubusercontent.com/39054055/154338953-a7e8de67-e0a3-4536-aca5-d266566b4f6a.png)

**Comment by shmox75** [comment]
> > > > > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > > > > 
> > > > > 
> > > > > Thanks for giving which Pool are you using...
> > > > > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > > > > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> > > > 
> > > > 
> > > > Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol
> > > 
> > > 
> > > So then I hope you show your config or the start of the miner... to have some more information
> > > ![Screen](https://user-images.githubusercontent.com/39054055/154273398-44365b99-889d-436a-a6fc-f2afc0620090.png)
> 
> Your problem is in flightsheet. You cannot connect to eth pool. Share the flightsheet without wallets if you can
![Sans titre](https://user-images.githubusercontent.com/39054055/154339041-33a4a92f-6162-4417-ab0f-693b31dabee7.png)

**Comment by jgonzis** [comment]
> > > > > > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > > > > > 
> > > > > > 
> > > > > > Thanks for giving which Pool are you using...
> > > > > > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > > > > > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> > > > > 
> > > > > 
> > > > > Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol
> > > > 
> > > > 
> > > > So then I hope you show your config or the start of the miner... to have some more information
> > > > ![Screen](https://user-images.githubusercontent.com/39054055/154273398-44365b99-889d-436a-a6fc-f2afc0620090.png)
> > 
> > 
> > Your problem is in flightsheet. You cannot connect to eth pool. Share the flightsheet without wallets if you can
> > ![Sans titre](https://user-images.githubusercontent.com/39054055/154339041-33a4a92f-6162-4417-ab0f-693b31dabee7.png)

My rig is working same config. I suppose is something around a firewall. Why you don't try to use the SSL port? 
![Screenshot_20220216-220417_Chrome](https://user-images.githubusercontent.com/38668405/154356938-b05a75a4-dde2-430d-b5b5-cde4b75ebe34.jpg)

**Comment by shmox75** [comment]
> > > > > > > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > > > > > > 
> > > > > > > 
> > > > > > > Thanks for giving which Pool are you using...
> > > > > > > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > > > > > > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> > > > > > 
> > > > > > 
> > > > > > Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol
> > > > > 
> > > > > 
> > > > > So then I hope you show your config or the start of the miner... to have some more information
> > > > > ![Screen](https://user-images.githubusercontent.com/39054055/154273398-44365b99-889d-436a-a6fc-f2afc0620090.png)
> > > 
> > > 
> > > Your problem is in flightsheet. You cannot connect to eth pool. Share the flightsheet without wallets if you can
> > > ![Sans titre](https://user-images.githubusercontent.com/39054055/154339041-33a4a92f-6162-4417-ab0f-693b31dabee7.png)
> 
> My rig is working same config. I suppose is something around a firewall. Why you don't try to use the SSL port? ![Screenshot_20220216-220417_Chrome](https://user-images.githubusercontent.com/38668405/154356938-b05a75a4-dde2-430d-b5b5-cde4b75ebe34.jpg)

Hi, I'm not using a firewall, and 1.44 is working well with the same config. May I ask you how to use SSL port ?

**Comment by jgonzis** [comment]
> > > > > > > > > Hi devs, upgrading to 1.45 on hiveos gives issues 0mh/s all the time. Downgrading to 1.44 works well. Please note that I'm using DUAL ETH/TON
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thanks for giving which Pool are you using...
> > > > > > > > We found that for ton-pool in 1.45 parameter --ton-mode 2 need or use the new pool address wss://eu1.stratum.ton-pool.com/stratum
> > > > > > > > And for people mining in Nicehash stratum : --ethstratum ETHV1 need it too.
> > > > > > > 
> > > > > > > 
> > > > > > > Hi, I'm using icemining Pool. If I'm not wrong it's using stratum+tcp protocol
> > > > > > 
> > > > > > 
> > > > > > So then I hope you show your config or the start of the miner... to have some more information
> > > > > > ![Screen](https://user-images.githubusercontent.com/39054055/154273398-44365b99-889d-436a-a6fc-f2afc0620090.png)
> > > > 
> > > > 
> > > > Your problem is in flightsheet. You cannot connect to eth pool. Share the flightsheet without wallets if you can
> > > > ![Sans titre](https://user-images.githubusercontent.com/39054055/154339041-33a4a92f-6162-4417-ab0f-693b31dabee7.png)
> > 
> > 
> > My rig is working same config. I suppose is something around a firewall. Why you don't try to use the SSL port? ![Screenshot_20220216-220417_Chrome](https://user-images.githubusercontent.com/38668405/154356938-b05a75a4-dde2-430d-b5b5-cde4b75ebe34.jpg)
> 
> Hi, I'm not using a firewall, and 1.44 is working well with the same config. May I ask you how to use SSL port ?

Just select in the ethermine server ssl. It will end in 5555
