### ISSUE TITLE
1.45 nicehash stratum can't connect

### ISSUE THREAD

**Issue by EricKeong** [Lolliedieb/lolMiner-releases#1273]
As title dual ming ETH+TON, 1.44 work well.

**Comment by jgonzis** [comment]
> As title dual ming ETH+TON, 1.44 work well.

Yes it is a know bug...  just force Nicehash with that parameter meanwhile the update come: 

--ethstratum ETHV1

**Comment by Vinasis01** [comment]
> > As title dual ming ETH+TON, 1.44 work well.
> 
> Yes it is a know bug... just force Nicehash with that parameter meanwhile the update come:
> 
> --ethstratum ETHV1

Add this line in the extra parameters?

**Comment by jgonzis** [comment]
> > > As title dual ming ETH+TON, 1.44 work well.
> > 
> > 
> > Yes it is a know bug... just force Nicehash with that parameter meanwhile the update come:
> > --ethstratum ETHV1
> 
> Add this line in the extra parameters?

Yes pleased
