### ISSUE TITLE
ETC+ALPH on Palit Gaming Pro OC RTX 3080 !NOT! LHR. Strange issue

### ISSUE THREAD

**Issue by RuEfendi** [Lolliedieb/lolMiner-releases#1279]
Windows 10, Core 1500MHz, Voltage 725mV, Memory +1250MHz.

On start mining it's ok, etchash hashrate 98.49MH/s, blake3 hashrate 1255 MH/s, Power 300W

After one and a half days mining lolMiner 1.45 outputs unexpectedly and continuously: 

### "Please wait lhr semi-unlock tuning is ongoing"

And etchash reported hashrate falls down to 70MH/s

After restart lolMiner 1.45 it's ok again

**Comment by jgonzis** [comment]
> Windows 10, Core 1500MHz, Voltage 725mV, Memory +1250MHz.
> 
> On start mining it's ok, etchash hashrate 98.49MH/s, blake3 hashrate 1255 MH/s, Power 300W
> 
> After one and a half days mining lolMiner 1.45 outputs unexpectedly and continuously:
> 
> ### "Please wait lhr semi-unlock tuning is ongoing"
> And etchash reported hashrate falls down to 70MH/s
> 
> After restart lolMiner 1.45 it's ok again

That could happen in the tunning, or in Windows for the uses GPU Windows, it can be easy disabled with --lhrtune off in the EXTRAPARAMTERS, then if you have a NOLHR no more problems with it :-)

**Comment by RuEfendi** [comment]
> That could happen in the tunning, or in Windows for the uses GPU Windows, it can be easy disabled with --lhrtune off in the EXTRAPARAMTERS, then if you have a NOLHR no more problems with it :-)

Thanks, dear colleague
