### ISSUE TITLE
Stuck device detected, invoking emergency script

### ISSUE THREAD

**Issue by JavierTobar** [Lolliedieb/lolMiner-releases#128]
I keep getting the following error log

> Stuck device detected, invoking emergency script 

I'm mining ETH with ETHash on HiveOS with 4 5700xt with the lastest version of lolMiner
Basically 3 GPUs stay at 0.00 MH/s while one keeps working properly. 

I've read previous threads that this often happens when OC settings are unstable. I've been having this issue for about 4 days now, I've tried several different conservative OC settings.

The current OC settings are 
![image](https://user-images.githubusercontent.com/43936658/104112455-0ddfcf00-52bd-11eb-98de-fe2d03a14a22.png)

Meanwhile, the OS logs the following 

> Jan  9 13:29:20 hive5700XT kernel: [ 1542.905378] amdgpu: Failed to export SMU metrics table!
Jan  9 13:29:20 hive5700XT kernel: [ 1542.905434] amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!

What I've tried : 

- Different OC Settings
- Different splitters and power cables 
- Changed 1 riser (I'm using ubit risers so I rely on green led to know if they're working properly or not)
- Updating Hive OS to 0.6-191@210109
- Changing motherboard BIOS to a more stable one (v1208 for B250 mining expert)

Any insight would be greatly appreciated

**Comment by Keimling27** [comment]
when happen the cero speed if you start lol miner you have hashrate ?  or starts with cero

**Comment by jgonzis** [comment]
No answer from user...
