### ISSUE TITLE
Fan Speed Control and Memory Offset

### ISSUE THREAD

**Issue by Protoss46** [Lolliedieb/lolMiner-releases#1280]
Could you please add fan speed control and memory offset settings.
Fan speed control with target temp. setting would be much appreciated.

**Comment by Mrgaton** [comment]
like 

--MaxMemory 4 gb --MaxFanSpeed 500 RPM 

?

**Comment by Protoss46** [comment]
Like :

--fan                      Sets GPU fan speed in percent or target temperature (auto-fan).
                                   Valid formats:
                                      --fan N           (where N is the fan speed)
                                      --fan t:N         (where N is the target core temperature)
                                      --fan t:N[F1-F2]  (same as above, but with the fan speed constrained by [F1%, F2%] range)
                                      --fan tm:N        (where N is the target memory temperature)
                                      --fan tm:N[F1-F2] (same as above, but with the fan speed constrained by [F1%, F2%] range)
                                   Example: --fan 45,t:67,tm:95,t:69[45-100],tm:90[50-95]
                                   which translates to
                                      GPU #0: set fan speed to 45%
                                      GPU #1: maintain GPU core temperature at 67C
                                      GPU #2: maintain GPU memory temperature at 90C
                                      GPU #3: maintain GPU core temperature at 69C
                                              with the fan speed limited to [45%, 100%] range
                                      GPU #4: maintain GPU memory temperature at 90C
                                              with the fan speed limited to [50%, 95%] range
                                   Note: fan speeds are limited to [0%, 100%] range in auto-fan mode by default.

        --mclock                   Sets GPU memory clock offset in MHz.
                                   Requires running the miner with administrative privileges.
                                   Will be set to 0 on exit and during DAG rebuild.

**Comment by jgonzis** [comment]
> Like :
> 
> --fan Sets GPU fan speed in percent or target temperature (auto-fan). Valid formats: --fan N (where N is the fan speed) --fan t:N (where N is the target core temperature) --fan t:N[F1-F2] (same as above, but with the fan speed constrained by [F1%, F2%] range) --fan tm:N (where N is the target memory temperature) --fan tm:N[F1-F2] (same as above, but with the fan speed constrained by [F1%, F2%] range) Example: --fan 45,t:67,tm:95,t:69[45-100],tm:90[50-95] which translates to GPU #0: set fan speed to 45% GPU #1: maintain GPU core temperature at 67C GPU #2: maintain GPU memory temperature at 90C GPU #3: maintain GPU core temperature at 69C with the fan speed limited to [45%, 100%] range GPU #4: maintain GPU memory temperature at 90C with the fan speed limited to [50%, 95%] range Note: fan speeds are limited to [0%, 100%] range in auto-fan mode by default.
> 
> ```
>     --mclock                   Sets GPU memory clock offset in MHz.
>                                Requires running the miner with administrative privileges.
>                                Will be set to 0 on exit and during DAG rebuild.
> ```

Be careful, that mclok function was done it only focus on TON Mining. If you use it for other algo you will lost all performance, because is not an offset it is a fix memory clock

**Comment by sosme2012** [comment]
Currently these two functions of lolminer can only use other software like msi afterburner.But once the pc reboots.That's game over.lol 🤣

**Comment by Protoss46** [comment]
> 
lol
I'm requesting a feature.  Not asking for explanation. I should correct the title.

**Comment by jgonzis** [comment]
> > 
> 
> lol I'm requesting a feature. Not asking for explanation. I should correct the title.

Sorry, I have misunderstood...

**Comment by sibar85** [comment]
Agree with your request

**Comment by jgonzis** [comment]
> Agree with your request


> Agree with your request

We have the beta lolNvidiaOC.exe working, the idea if works correctly included in lolMiner.

**Comment by Protoss46** [comment]
Please, i beg you, also add option for applying overlock settings after dag build.  Dag repair takes too much time and sometimes fails.
