### ISSUE TITLE
ETH+TON json config example

### ISSUE THREAD

**Issue by rafaeljpc** [Lolliedieb/lolMiner-releases#1283]
I couldn't find an example of JSON file with ETH+TON dual mining. Minerstat uses JSON config setup and the JSON documentation is not so well shown.

Sorry to bother and Thank you

**Comment by jgonzis** [comment]
lolMiner.exe --algo ETHASH --pool {ETHPOOL} --user {wallet.workername} --dualmode TONDUAL --dualpool {TONPOOL} --dualuser {wallet}  --cclk {coreclock} 

I hope like this is easy to put it in your Minerstat format

**Comment by jgonzis** [comment]
> Sorry, but I don't think it uses cmdline for lolminer anymore. :-(
> 
> This is where I stopped the configuration...... Then miner don't even start and don't show any error message
> 
> ![image](https://user-images.githubusercontent.com/690796/154509606-1f662fac-d829-462a-bb09-a42c3e7a3182.png)

Thanks I know why ... select only 1 pool for tonwhales.com please. If you select more than 1 it will not go.

**Comment by rafaeljpc** [comment]
It didn't start the dual mining, only ethash. whats is the json tag for dual mining? Tryed "DUALMODE" (it breaks), "DMODE" (it ignore dual mining), "DALGO" also is ignored
