### ISSUE TITLE
1070ti dual

### ISSUE THREAD

**Issue by Tilnov** [Lolliedieb/lolMiner-releases#1286]
Hello friends! First of all, I would like to thank you for your work. thanks a lot .
I put in mining on Lol 1.45 , 
![BC1AB030-1193-4EAF-8DA3-088B82D404B6](https://user-images.githubusercontent.com/34181140/154544745-b1d3ce2b-0921-45f3-bc6c-96055b1d1f3b.jpeg)
![Uploading C0B3B1B7-4DCF-457A-804C-2E4A997E57CF.jpeg…]()
1070ti, installed pl150. cards press 280ghs ton. can you get more?

**Comment by jgonzis** [comment]
If you accept to reduce some ETH, you can put parameter --maxdualimpact 12 in extra config and you will get more TON but less ETH. Try it :-) to find your optimal value, 8 or 10 or 12
