### ISSUE TITLE
Error LOLMINER 1.45 - Miner Ton Coin

### ISSUE THREAD

**Issue by iurycatita** [Lolliedieb/lolMiner-releases#1290]
Hi,

When upgrading from version 1.44 to 1.45, it is no longer possible to mine Ton Coin on Hiveos, the attached message is displayed. When I go back to version 1.44, I succeed in mining.\

![WhatsApp Image 2022-02-18 at 12 09 56](https://user-images.githubusercontent.com/8600757/154711049-1d66bd73-714b-4c3c-bdd6-c30fe78cd976.jpeg)

**Comment by mrDrauzer** [comment]
при переходе с 1.43 на 1.45 полезли ошибки ( OS Windows)
проблема наблюдается  при Dual Mine  eth+ton и eth_aleph....

![Lolminer](https://user-images.githubusercontent.com/59542149/154764520-fd291e96-6ef2-4ce7-9f2b-48ba7c6018d8.png)

В Bat изменил пулы  и кошельки также как это было в версии 1,43
set "POOL=daggerhashimoto.eu-west.nicehash.com:3353"
set "WALLET=ХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХ.lolMinerDuo"

set "TONPOOL=https://next.ton-pool.com:443"
set "TONWALLET=ХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХ"
							
set "EXTRAPARAMETERS="

**Comment by mrDrauzer** [comment]
To work with NiceHash
And dual Miner Ton
![Решение](https://user-images.githubusercontent.com/59542149/154821418-1ddcb4af-bb62-41cd-a20e-7e691c54311b.png)

**Comment by jackymardt** [comment]
For lolMiner >= 1.45 users: please use wss://eu1.stratum.ton-pool.com/stratum as pool address to --pool argument

**Comment by jackymardt** [comment]
For lolMiner >= 1.45 users: please use wss://eu1.stratum.ton-pool.com/stratum as pool address to --pool argument

**Comment by iurycatita** [comment]
The error message was resolved by passing to Lolminer being:

`--ton-mode 2`

Thank you very much answers.

**Comment by jgonzis** [comment]
Thx for the help of the other miners to solve it faster!!
