### ISSUE TITLE
[Feature Request] Maintenance Wallet and Duration in minutes or %

### ISSUE THREAD

**Issue by wasarinta** [Lolliedieb/lolMiner-releases#1291]
Please add parameter for maintenance wallet and duration in minutes or in % of a day mining for maintenance wallet (single/dual mining).

Thank you.

**Comment by jgonzis** [comment]
> Please add parameter for maintenance wallet and duration in minutes or in % of a day mining for maintenance wallet (single/dual mining).
> 
> Thank you.

That is actually done. It is done for Single. not for Dual. The split mining:

https://github.com/Lolliedieb/lolMiner-releases/wiki/lolMiner-1.43-dual-and-split-mining-options#split-speed-evenly-for-ethetc-or-ubiq

The hashrate is split in according to the value you want  --dualmode SPLIT-5.5 to a 5,5% of the hashrate to the pool and wallet you add later.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
