### ISSUE TITLE
No Stable Hashrate Dual ETH + TON

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1292]
Running a rig of 13x RTX (3060 TI - 3070 - 3080) FHR, on TREX I get 855 mh/s, on Nicehash I get 850 mh/s, when I start dual mining ETH + TON on LOLMiner 1.43 - 1.44 - .145 I understand there is a slight hit on the ETH performance but the hashrate is unstable.

For example I start the miner I get 810 mh/s, I close the miner and start it again and I get 795 mh/s, I close the miner and start it again and I get 822 mh/s...I close the miner and start it again and I get 830 mh/s...

I have to do this multiple times to get it to a range between 820-830 mh/s.

Same overclock settings used all across the miners and I lowered them even more due to LOLMiner having defective segments when I used the normal overclocks that I used with other miners (average level overclocks nothing high or extreme).

Sometimes it can be opening and closing the miner 3-4 times, and sometimes more than 15-20 times

Running windows 10.

I asked around and seems I am not the only one having this issue.

Example:
Run # 1

![image](https://user-images.githubusercontent.com/49044292/154765388-60913021-6b99-47e8-b5a3-4cc5be87faa7.png)

Run # 2

![image](https://user-images.githubusercontent.com/49044292/154765686-7eaab345-5d95-4749-8476-047665fa1ec4.png)

Run # 3

![image](https://user-images.githubusercontent.com/49044292/154766043-25bf4c78-d486-43ad-b8a9-af848b0e69cc.png)

Run # 4

![image](https://user-images.githubusercontent.com/49044292/154766428-1bdcc9bf-595e-4d11-93d2-09f4a06d286d.png)

**Comment by jgonzis** [comment]
> Running a rig of 13x RTX (3060 TI - 3070 - 3080) FHR, on TREX I get 855 mh/s, on Nicehash I get 850 mh/s, when I start dual mining ETH + TON on LOLMiner 1.43 - 1.44 - .145 I understand there is a slight hit on the ETH performance but the hashrate is unstable.
> 
> For example I start the miner I get 810 mh/s, I close the miner and start it again and I get 795 mh/s, I close the miner and start it again and I get 822 mh/s...I close the miner and start it again and I get 830 mh/s...
> 
> I have to do this multiple times to get it to a range between 820-830 mh/s.
> 
> Same overclock settings used all across the miners and I lowered them even more due to LOLMiner having defective segments when I used the normal overclocks that I used with other miners (average level overclocks nothing high or extreme).
> 
> Sometimes it can be opening and closing the miner 3-4 times, and sometimes more than 15-20 times
> 
> Running windows 10.
> 
> I asked around and seems I am not the only one having this issue.
> 
> Example: Run # 1
> 
> ![image](https://user-images.githubusercontent.com/49044292/154765388-60913021-6b99-47e8-b5a3-4cc5be87faa7.png)
> 
> Run # 2
> 
> ![image](https://user-images.githubusercontent.com/49044292/154765686-7eaab345-5d95-4749-8476-047665fa1ec4.png)
> 
> Run # 3
> 
> ![image](https://user-images.githubusercontent.com/49044292/154766043-25bf4c78-d486-43ad-b8a9-af848b0e69cc.png)
> 
> Run # 4
> 
> ![image](https://user-images.githubusercontent.com/49044292/154766428-1bdcc9bf-595e-4d11-93d2-09f4a06d286d.png)

Are you using Lock Core?. We complete recommend to use Lock Core and PL to 100%.

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer)

About ETH Hashrate: you can always check the reality of the average at the pool, what we get payed in that great test: https://www.hashrate.no/tests/ampere
