### ISSUE TITLE
Can`t Support 10+GPUs? GPU n: error when allocating memory or building DAG. Disabling card.

### ISSUE THREAD

**Issue by luoxiaoningtrue** [Lolliedieb/lolMiner-releases#1293]
I have a 12GPUs rig, 3090 x 10 and 3060Ti x 2, running on lolMiner1.45 Win10.
When I use all of 12GPUs, next problem was happened
GPU n1: error when allocating memory or building DAG. Disabling card.
GPU n2: error when allocating memory or building DAG. Disabling card.
2GPUs was disabled, the n1, n2 was random.

When use 11GPUs, same problem happened, 1GPU(random) was disabled.
When use 10GPUs, no problem, it all work at well.

Anyway, the GPUs over 10+ cannot be used. is lolMiner not supported? Or is it a problem with my setting?

**Comment by jgonzis** [comment]
> I have a 12GPUs rig, 3090 x 10 and 3060Ti x 2, running on lolMiner1.45 Win10. When I use all of 12GPUs, next problem was happened GPU n1: error when allocating memory or building DAG. Disabling card. GPU n2: error when allocating memory or building DAG. Disabling card. 2GPUs was disabled, the n1, n2 was random.
> 
> When use 11GPUs, same problem happened, 1GPU(random) was disabled. When use 10GPUs, no problem, it all work at well.
> 
> Anyway, the GPUs over 10+ cannot be used. is lolMiner not supported? Or is it a problem with my setting?

I think you should increase the Virtual Disk .... That could be the problem. Also try to see at the start if something is allocated in the GPU... but normally is that you will need a higher Virtual Disk. Or just change to Linux and that problem will be removed. Using like MMPOS or HiveOS
