### ISSUE TITLE
Unstable ETH-TON mining

### ISSUE THREAD

**Issue by Romybron** [Lolliedieb/lolMiner-releases#1298]
Hi, I own multiple NON-LHR cards (3060Ti, 3070, 3080) and the software keeps saying:
"Low hashrate",
"GPU will be paused again for clean dual mode calibration",
"detected as LHR. Switching to LHR mode",
"please wait LHR semi-unlock tuning is ongoing"

Is there a way to force NON-LHR ? This is driving me crazy since I am loosing nearly 40% hashrate against expected 10% from the dual mining

Thanks !!

**Comment by newbee008** [comment]
My settings: it is stable, but the eth rate is not high. do not know why

GPU 1 RTX 3060 Ti  37.99   37.69  1028/0/0  12.4T   0.228  1139.52  1134.02  1917/16/1  836.1T   6.846  165.9  1545  7593    54   55       14.4
GPU 2 RTX 3060 Ti  36.91   34.43   939/0/0  29.7T   0.230   999.43   984.42   1672/6/0  110.1T   6.224  160.1  1068  7493    49   45       20.8

**Comment by jgonzis** [comment]
> Hi, I own multiple NON-LHR cards (3060Ti, 3070, 3080) and the software keeps saying: "Low hashrate", "GPU will be paused again for clean dual mode calibration", "detected as LHR. Switching to LHR mode", "please wait LHR semi-unlock tuning is ongoing"
> 
> Is there a way to force NON-LHR ? This is driving me crazy since I am loosing nearly 40% hashrate against expected 10% from the dual mining
> 
> Thanks !!

Try to put --lhrtune off and then it will not detect any GPU as LHR. So you will avoid that problems.

**Comment by jgonzis** [comment]
> My settings: it is stable, but the eth rate is not high. do not know why
> 
> GPU 1 RTX 3060 Ti 37.99 37.69 1028/0/0 12.4T 0.228 1139.52 1134.02 1917/16/1 836.1T 6.846 165.9 1545 7593 54 55 14.4 GPU 2 RTX 3060 Ti 36.91 34.43 939/0/0 29.7T 0.230 999.43 984.42 1672/6/0 110.1T 6.224 160.1 1068 7493 49 45 20.8

I see that you haven't push the memory quite high. And in the seconds it seems you are not using Lock Core
