### ISSUE TITLE
Not getting hashrate on my LHR cards when mining ETH + TON 

### ISSUE THREAD

**Issue by hendra2222** [Lolliedieb/lolMiner-releases#1299]
Hi,
This maybe an issue for LOLMiners to some cards:
Can someone help me what would be the reason for not getting TON hashrate when mining dual ETH and TON? I have 4 cards:
3060 LHR
3060 TI LHR
2070super
6700

2070 and 6700 I am getting TON hashrate of 780 and 816 and eth 45mh/s and 38.9mh/s
but both my LHR Cards are getting 0 TON hashrate .. This happens since release of ETH and TON support

my 3060LHR = gigabyte 3060 12gb ram
3060 ti = Gigabyte 3060 ti 8gb ram

This is not the case when mining TON Coin only. I am getting all together 5000+ Mh/s..
![ETH_TON LHR ISSUE](https://user-images.githubusercontent.com/94904567/154812179-e084845f-75d1-48e8-89b7-48cf1b6b2687.jpg)

This happens on all version of LOL Miner since release. Latest also not getting hashrate. 

Please help me!
regards,
Hendra

**Comment by sebek72** [comment]
Increase PL and core clock (seems to be limited).

**Comment by hendra2222** [comment]
> Increase PL and core clock (seems to be limited).

What is PL Sebek72??

**Comment by hendra2222** [comment]
Wow this works thank you SebeK!, for some reason I cant get the 3060 ti to get pass 200mh/s is that normal?

![image](https://user-images.githubusercontent.com/94904567/154843914-ed5188c5-3bad-4918-8286-a0145d459c7b.png)

I cant go pass the current PL , MEM, CORE setting .. it's 70c now on that card. even setting it higher doesnt make it go over 200mh/s

**Comment by hendra2222** [comment]
ah nvmd I got it working now! pump up the PL helps.
