### ISSUE TITLE
pls fix it. --mclk 10250 Actually I have 9242 MHz 

### ISSUE THREAD

**Issue by langrad** [Lolliedieb/lolMiner-releases#1300]
Why is there a ceiling for settings and how to get around it, set in the miner config --mclk 10250 and in fact the maximum performance 
 9242 MHz  And you can't set it up, pls fix it.

**Comment by jgonzis** [comment]
> Why is there a ceiling for settings and how to get around it, set in the miner config --mclk 10250 and in fact the maximum performance 9242 MHz And you can't set it up, pls fix it.

It is not really a fix --mclk it was done to help only TON Miners. You should use MSI Afterburner or Nvidia Inspector Memory Offset.
