### ISSUE TITLE
Can't get a 3060 v2 stable Eth+Ton

### ISSUE THREAD

**Issue by GYKrauss** [Lolliedieb/lolMiner-releases#1304]
I have tried every  possible OC setting and fixed clocks. I have overclocked and underclocked core and memory with power left at 100. I have tried every LHR tuning. I cannot get a stable result. What would be the absolute safest settings including lolminer flags just to see any stable result without LHR lock?

**Comment by newbee008** [comment]
Name         Speed    Pool    Shares   Best    Eff.    Speed     Pool     Shares    Best    Eff.  Power  CCLK  MCLK  Core  Fan  --lhrtune
                    Mh/s    Mh/s    A/S/Hw  Share  Mh/s/W     Mh/s     Mh/s     A/S/Hw   Share  Mh/s/W      W   MHz   MHz  Temp  Pct
GPU 0 RTX 3060     32.74   32.17   877/0/0   3.0T   0.247   879.65   897.47   1524/5/0  139.3T   6.646  131.9  1433  8092    62   69       12.4


My settings, is this good or bad?

**Comment by jgonzis** [comment]
> I have tried every possible OC setting and fixed clocks. I have overclocked and underclocked core and memory with power left at 100. I have tried every LHR tuning. I cannot get a stable result. What would be the absolute safest settings including lolminer flags just to see any stable result without LHR lock?

Which OS are you using? I suppose Windows, and which Nvidia Drivers?


> Name Speed Pool Shares Best Eff. Speed Pool Shares Best Eff. Power CCLK MCLK Core Fan --lhrtune Mh/s Mh/s A/S/Hw Share Mh/s/W Mh/s Mh/s A/S/Hw Share Mh/s/W W MHz MHz Temp Pct GPU 0 RTX 3060 32.74 32.17 877/0/0 3.0T 0.247 879.65 897.47 1524/5/0 139.3T 6.646 131.9 1433 8092 62 69 12.4
> 
> My settings, is this good or bad?

It is not bad... could a higher Clock give some extra, but I think is good

**Comment by egotist713** [comment]
> > I have tried every possible OC setting and fixed clocks. I have overclocked and underclocked core and memory with power left at 100. I have tried every LHR tuning. I cannot get a stable result. What would be the absolute safest settings including lolminer flags just to see any stable result without LHR lock?
> 
> Which OS are you using? I suppose Windows, and which Nvidia Drivers?
> 
> > Name Speed Pool Shares Best Eff. Speed Pool Shares Best Eff. Power CCLK MCLK Core Fan --lhrtune Mh/s Mh/s A/S/Hw Share Mh/s/W Mh/s Mh/s A/S/Hw Share Mh/s/W W MHz MHz Temp Pct GPU 0 RTX 3060 32.74 32.17 877/0/0 3.0T 0.247 879.65 897.47 1524/5/0 139.3T 6.646 131.9 1433 8092 62 69 12.4
> > My settings, is this good or bad?
> 
> It is not bad... could a higher Clock give some extra, but I think is good

Why don't you write anywhere - what version of the driver is recommended?

**Comment by jgonzis** [comment]
> 

For Windows it is in the Wiki 472.12, that the best for LHR GPUs. the NOLHR work ok normally

**Comment by GYKrauss** [comment]
Completely missed the driver recommendation. apologies. Works much better now.

**Comment by jgonzis** [comment]
> Completely missed the driver recommendation. apologies. Works much better now.

Many thanks to you for try it and for the feedback enjoy mining :-)

**Comment by GYKrauss** [comment]
Thanks. Though 3080ti VRAM temps are now >100c with dual mining - is this normal/safe?

**Comment by jgonzis** [comment]
> Thanks. Though 3080ti VRAM temps are now >100c with dual mining - is this normal/safe?

Try if it is possible to reduce a bit increasing fan...
