### ISSUE TITLE
3080 Lhr 12G keeps pausing/restarting LHR mode

### ISSUE THREAD

**Issue by michiganpinball** [Lolliedieb/lolMiner-releases#1307]
Have a new geforce rtx 3080 12g.   This is an LHR card.  When starting LOLMINER the program detects LHR mode and attempts to unlock card.

Then it detects "Mining Lock" and says unlocking and reducing --lhrtune parameter
Then pauses gpu to make sure it is unlocked.
Then detects Mining Lock again....and repeats this sequence indefinitely.

Hash rate is very low - likely due to all the pauses.

Hopefully there will be a fix for the 3080 12G LHR.  But until then is there a way to disable the LHR check so can at least get the 55 mh/s?

**Comment by gnyzbk** [comment]
> Have a new geforce rtx 3080 12g. This is an LHR card. When starting LOLMINER the program detects LHR mode and attempts to unlock card.
> 
> Then it detects "Mining Lock" and says unlocking and reducing --lhrtune parameter Then pauses gpu to make sure it is unlocked. Then detects Mining Lock again....and repeats this sequence indefinitely.
> 
> Hash rate is very low - likely due to all the pauses.
> 
> Hopefully there will be a fix for the 3080 12G LHR. But until then is there a way to disable the LHR check so can at least get the 55 mh/s?

u can use --lhrtune off to disable lhr

**Comment by jgonzis** [comment]
Like the other miner said, use --lhrtune off and mine dual to get max profit of that gpu
