### ISSUE TITLE
AMD dual mining ETH+ALPH 2 problem new version

### ISSUE THREAD

**Issue by jrchico** [Lolliedieb/lolMiner-releases#1308]
**21st Feb 2022 18:40:18
Hashrate trigger - Restart

Hashrate dropped by 28.67% and mining client was restarted.

21st Feb 2022 18:21:39**

**21st Feb 2022 17:39:04
Consumption increase alert sent to Jrchico (376.44%)**

i get this error every 40 min on different rims.

I am mining with AMD grafics card and dual mining eth + alph

I see two problems in the new version:
1. Hashrate dropped
2. Consumption increase alert sent to Jrchico (376.44%)

**Comment by jgonzis** [comment]
> **21st Feb 2022 18:40:18 Hashrate trigger - Restart
> 
> Hashrate dropped by 28.67% and mining client was restarted.
> 
> 21st Feb 2022 18:21:39**
> 
> **21st Feb 2022 17:39:04 Consumption increase alert sent to Jrchico (376.44%)**
> 
> i get this error every 40 min on different rims.
> 
> I am mining with AMD grafics card and dual mining eth + alph
> 
> I see two problems in the new version:
> 
> 1. Hashrate dropped
> 2. Consumption increase alert sent to Jrchico (376.44%)

Which OS are you using?. 

Could you send pictures of the miner running?. that will help to analyse what's going on... the Consumption increase information is not from lolMiner, so we cannot determinate what's happening.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
