### ISSUE TITLE
memory tweak for 1080 and 1080ti

### ISSUE THREAD

**Issue by schwalbe247** [Lolliedieb/lolMiner-releases#1309]
does lolminer have mt command for pascal gpus like other miners such as gminer? want to try and dual mine but having it’s not worth it. i’ve tried enabling eth pill in rave os but causes my cards to crash. Cards run perfect with memory tweak command in gminer. please add this as a feature

**Comment by jgonzis** [comment]
> does lolminer have mt command for pascal gpus like other miners such as gminer? want to try and dual mine but having it’s not worth it. i’ve tried enabling eth pill in rave os but causes my cards to crash. Cards run perfect with memory tweak command in gminer. please add this as a feature

Dual mode and Pill will end normally in a crash. There is not ETHPILL for lolMiner, normally that is applied from the OS, like HiveOS do it. Also helps the delay that can be added in HiveOS to tune properly the GPU. I suppose you are in Windows right?.

**Comment by nulledone** [comment]
Pill and dual mining only works if you use low power limit, which kind of defeats the purpose of the pill. I get 32mh to 0.9gh at 200w, without pill it drops few mh 25-28 with same power limit.
