### ISSUE TITLE
Miner mines for day than stopes

### ISSUE THREAD

**Issue by samuellsk** [Lolliedieb/lolMiner-releases#131]
Miner is started normally, it mines for days (as i m checking on it from time to time) than MH/s drop to 0 , but it keeps going, but its not mining.

![image](https://user-images.githubusercontent.com/22764003/104119628-e1659a80-5330-11eb-9c09-1440d92d5c11.png)

Any option when it does this to just make a restart / self heal ?

Thank you.

**Comment by nolan437** [comment]
I'm having the same problem.  Sometimes it stops only a few minutes after it started running.  
2080 ti (461.09)
Windows 10 is up to date
1.19 build

**Comment by Keimling27** [comment]
for searching the problem it would be interesting to see whats happen before the hashrate sinks to cero

**Comment by CCWBee** [comment]
got the exact same issue, from what i can see the only solution is setting it to restart the miner every hour or so

**Comment by clamatac** [comment]
something similar here, I have made a bat file to restart windows every 3 hours.

But it seems, after each reset, the reported hashrate seems to suffer/low a lot

Greetings

**Comment by jgonzis** [comment]
New Cuda Solver should solve it
