### ISSUE TITLE
Mining doesn't start properly on 5600XT (Windows)

### ISSUE THREAD

**Issue by rluik** [Lolliedieb/lolMiner-releases#1310]
Windows 11
Radeon 22.2.2
lolMiner 1.46
No browser windows opened

ETH+TON dual mode
ETH hashrate displays something like 0.1 MH
TON 0 MH

**Comment by PolyakRussia** [comment]
A similar problem. On tone and on eth 0 mh

**Comment by jgonzis** [comment]
> Windows 11 Radeon 22.2.2 lolMiner 1.46 No browser windows opened
> 
> ETH+TON dual mode ETH hashrate displays something like 0.1 MH TON 0 MH

Could you try with older drivers please?. like 21.10 or 21.4. Many thanks.



> A similar problem. On tone and on eth 0 mh. 3080 no lhr, 3070 no lhr and 3080ti

With 0 information about, your OS, your config, Nvidia Driver... really complicated to help you. I hope you consider to give more information or somephotos of the stats to try to help you.

**Comment by aelitasch** [comment]
i also had same issue, rx 5600xt driver version 21.5.1 , not working on latest lolminer 1.46, it shows 0MH/s sometimes 0.12MH/s on ETH and TON. I'm using windows 10 21H1,  for extra bug i think my rtx3060 lhrv1 detected as lhrv2, i need to force --mode b

**Comment by jgonzis** [comment]
> i also had same issue, rx 5600xt driver version 21.5.1 , not working on latest lolminer 1.46, it shows 0MH/s sometimes 0.12MH/s on ETH and TON. I'm using windows 10 21H1, for extra bug i think my rtx3060 lhrv1 detected as lhrv2, i need to force --mode b

Could you post some photos... I think what it could be... it doesn't generate the DAG, increase Core Voltage, new extra TON needs more Voltage

**Comment by aelitasch** [comment]
> > i also had same issue, rx 5600xt driver version 21.5.1 , not working on latest lolminer 1.46, it shows 0MH/s sometimes 0.12MH/s on ETH and TON. I'm using windows 10 21H1, for extra bug i think my rtx3060 lhrv1 detected as lhrv2, i need to force --mode b
> 
> Could you post some photos... I think what it could be... it doesn't generate the DAG, increase Core Voltage, new extra TON needs more Voltage
Maybe this helps?
![Screenshot 2022-02-23 150504](https://user-images.githubusercontent.com/75564486/155281128-0ef9d460-efba-471c-9de6-17cfb4826963.png)

**Comment by jgonzis** [comment]
> > > > i also had same issue, rx 5600xt driver version 21.5.1 , not working on latest lolminer 1.46, it shows 0MH/s sometimes 0.12MH/s on ETH and TON. I'm using windows 10 21H1, for extra bug i think my rtx3060 lhrv1 detected as lhrv2, i need to force --mode b
> > > 
> > > 
> > > Could you post some photos... I think what it could be... it doesn't generate the DAG, increase Core Voltage, new extra TON needs more Voltage
> > > Maybe this helps?
> > > ![Screenshot 2022-02-23 150504](https://user-images.githubusercontent.com/75564486/155281128-0ef9d460-efba-471c-9de6-17cfb4826963.png)
> 
> It seems it dies only at starting after DAG Generation... Try lowering Core or increasing Core Voltage please...

It should not be the problem... but it is connect directly to the mother board right?

**Comment by aelitasch** [comment]
> > > > > i also had same issue, rx 5600xt driver version 21.5.1 , not working on latest lolminer 1.46, it shows 0MH/s sometimes 0.12MH/s on ETH and TON. I'm using windows 10 21H1, for extra bug i think my rtx3060 lhrv1 detected as lhrv2, i need to force --mode b
> > > > 
> > > > 
> > > > Could you post some photos... I think what it could be... it doesn't generate the DAG, increase Core Voltage, new extra TON needs more Voltage
> > > > Maybe this helps?
> > > > ![Screenshot 2022-02-23 150504](https://user-images.githubusercontent.com/75564486/155281128-0ef9d460-efba-471c-9de6-17cfb4826963.png)
> > 
> > 
> > It seems it dies only at starting after DAG Generation... Try lowering Core or increasing Core Voltage please...
> 
> It should not be the problem... but it is connect directly to the mother board right?

yes it is connected to motherboard directly using pci e riser, its okay i already downgrade to lolminer 1.45 for my amd cards and for my nvidia cards im using 1.46a hehe

**Comment by Marsl10** [comment]
I have 3 GPU, 6700xt, 6800, 6700XT. First of them have 0Mhs. On windows 10. Lolminer v1.46a.
On 1.45 all ok.

**Comment by jgonzis** [comment]
> I have 3 GPU, 6700xt, 6800, 6700XT. First of them have 0Mhs. On windows 10. Lolminer v1.46a. On 1.45 all ok.

I suppose with your 0 Information that you are talking about Dual Mining... And More that 1.46a needs more Core Voltage for the extra 20% TON, so try to put more Core Voltage on that GPU please
