### ISSUE TITLE
1.46 crashing twice every 30 mins. No gain on Mh

### ISSUE THREAD

**Issue by kotopuz** [Lolliedieb/lolMiner-releases#1312]
Thanks for releasing new version !
Can't see any improvement in hashrates on 5700xt( you mentioned 10-15 %). Do I need to set some parameters to get such boost?

Bat used( old one used as new one is crashing)
--dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser TONWALLET

Using latest raveos.
Crashing every 15 min in mode 6 with ton pool new stratum
Trying use old ton pool stratum which will use mode 2.
It's already working more than 20 mins without crash.

**Comment by kotopuz** [comment]
Update. Raveos.
1hr running on old stratum and keeps crashing every 2 minutes after that 
--dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser TONWALLET

**Comment by jgonzis** [comment]
> Update. Raveos. 1hr running on old stratum and keeps crashing every 2 minutes after that --dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser TONWALLET

Could you try to see the log... to see what's happening?. Or when it crash?. That will help. Without that is really difficult. It could be just that the more TON needs more Core for the 5700. It has been tested a lot the connection to ton-pool and was working properly

**Comment by starsfox911** [comment]
каждые 50 минут вылет....

**Comment by jgonzis** [comment]
> каждые 50 минут вылет....

Just for a general notice:
When ever reporting an issue, please always include
- the miner version and the algorithms you are running
- the GPU types involved
- the operations system
- the driver version if known
Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
Thanks!

**Comment by kotopuz** [comment]
> 
Thanks.
Will try to catch errors in logs.
Could you share settings used to test 5700 or 5700xt please?

**Comment by jgonzis** [comment]
> > 
> 
> Thanks. Will try to catch errors in logs. Could you share settings used to test 5700 or 5700xt please?

normally 👍 
Core 1400
Voltage Core 800
And the others values the ETH Values

**Comment by starsfox911** [comment]
> > каждые 50 минут вылет....
> 
> Just for a general notice: When ever reporting an issue, please always include
> 
> * the miner version and the algorithms you are running
> * the GPU types involved
> * the operations system
> * the driver version if known
>   Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
>   Thanks!



5.10.0-hiveos #83
0.6-213@220221 
470.86 divers Nvidia
RTX 3060 × 2·RTX 3080 × 1·RTX 3060 Ti × 5
сделал откат до версии 1.45,там вылеты были но реже.

вот что мне пишет HiveOs

>GPU are lost, rebooting48s
>GPU driver error, no temps2m 41s

[Tue Feb 22 15:10:09 2022] NVRM: Xid (PCI:0000:04:00): 62, pid=3649, 0000(0000) 00000000 00000000
[Tue Feb 22 15:10:09 2022] NVRM: Xid (PCI:0000:04:00): 45, pid=3649, Ch 00000010
 больше я не могу ничего найти

**Comment by kotopuz** [comment]
> > Update. Raveos. 1hr running on old stratum and keeps crashing every 2 minutes after that --dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser TONWALLET
> 
> Could you try to see the log... to see what's happening?. Or when it crash?. That will help. Without that is really difficult. It could be just that the more TON needs more Core for the 5700. It has been tested a
![Screenshot_20220222-142055_Chrome](https://user-images.githubusercontent.com/34707464/155140927-b5ab3d83-3097-46a0-9d8f-c2164410598b.jpg) lot the connection to ton-pool and was working properly

Got the moment of crashing from logs.

**Comment by kotopuz** [comment]
> > Update. Raveos. 1hr running on old stratum and keeps crashing every 2 minutes after that --dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser TONWALLET
> 
> Could you try to see the log... to see what's happening?. Or when it crash?. That will help. Without that is really difficult. It could be just that the more TON needs more Core for the 5700. It has been tested a lot the connection to ton-pool and was working properly

![Screenshot_20220222-142055_Chrome](https://user-images.githubusercontent.com/34707464/155145807-523c730f-8b15-4a2b-a94d-a2570fd2577f.jpg)

**Comment by kotopuz** [comment]
> 
Looks like problem here is that great pool again.

**Comment by jgonzis** [comment]
Nice nice feedback ... It is possible to try tonwhales pool for a while? or try the new ton-pool : wss://eu1.stratum.ton-pool.com/stratum

Many thanks in advance

**Comment by kotopuz** [comment]
> 

O was downvolting down to 735 on 1.45! On 1.65 I had one reboot in 6 hours. With 800 efficiency if not looking good and fans changed from 70 to 100%! Looks like 1.46 require higher gpu voltage for stability. Will try downvolt to 740 with new pool and 1.46.

**Comment by jgonzis** [comment]
> > 
> 
> O was downvolting down to 735 on 1.45! On 1.65 I had one reboot in 6 hours. With 800 efficiency is not looking good and fans changed from 70 to 100%! Looks like 1.46 require higher gpu voltage for stability. Will try downvolt to 740 with new pool and 1.46.

Put 750... with AMD always steps of 12.5mV

**Comment by kotopuz** [comment]
> Nice nice feedback ... It is possible to try tonwhales pool for a while? or try the new ton-pool : wss://eu1.stratum.ton-pool.com/stratum
> 
> Many thanks in advance

Well. Mined impression. When I rose Core volts significantly like 850 all seems to be stable. But with 1.46 I can't operate as efficiently as with 1.45. There are still some crashes like every hour, but what's the point of upgrading to 1.46 if temps rise and Core freq will have to be decreased. I think lolminer missing essential feature.  Autotuning based on efficiency with predefined boundaries like max Temps or fan % or hashrate.

**Comment by jgonzis** [comment]
> > Nice nice feedback ... It is possible to try tonwhales pool for a while? or try the new ton-pool : wss://eu1.stratum.ton-pool.com/stratum
> > Many thanks in advance
> 
> Well. Mined impression. When I rose Core volts significantly like 850 all seems to be stable. But with 1.46 I can't operate as efficiently as with 1.45. There are still some crashes like every hour, but what's the point of upgrading to 1.46 if temps rise and Core freq will have to be decreased. I think lolminer missing essential feature. Autotuning based on efficiency with predefined boundaries like max Temps or fan % or hashrate.

Could you try 1.46a? To test it
Overwrite 1.46 to 1.46a:

cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start

**Comment by kotopuz** [comment]
> > > Nice nice feedback ... It is possible to try tonwhales pool for a while? or try the new ton-pool : wss://eu1.stratum.ton-pool.com/stratum
> > > Many thanks in advance
> > 
> > 
> > Well. Mined impression. When I rose Core volts significantly like 850 all seems to be stable. But with 1.46 I can't operate as efficiently as with 1.45. There are still some crashes like every hour, but what's the point of upgrading to 1.46 if temps rise and Core freq will have to be decreased. I think lolminer missing essential feature. Autotuning based on efficiency with predefined boundaries like max Temps or fan % or hashrate.
> 
> Could you try 1.46a? To test it, which HiveOS versión? Overwrite 1.46 to 1.46a:
> 
> cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start

Hello.  Not tried yet a 1.46a. With 750 on core and 1400 all went fine whole night. This morning suddenly got two restats in 30 mins, reduced core to 1200, again gew miner crashes. I do not understand what gping on. Internet is very good fiber link and no hardware problems in setup. Could it be a pool problem? I use raveos latest version.

**Comment by jgonzis** [comment]
> > > > Nice nice feedback ... It is possible to try tonwhales pool for a while? or try the new ton-pool : wss://eu1.stratum.ton-pool.com/stratum
> > > > Many thanks in advance
> > > 
> > > 
> > > Well. Mined impression. When I rose Core volts significantly like 850 all seems to be stable. But with 1.46 I can't operate as efficiently as with 1.45. There are still some crashes like every hour, but what's the point of upgrading to 1.46 if temps rise and Core freq will have to be decreased. I think lolminer missing essential feature. Autotuning based on efficiency with predefined boundaries like max Temps or fan % or hashrate.
> > 
> > 
> > Could you try 1.46a? To test it, which HiveOS versión? Overwrite 1.46 to 1.46a:
> > cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start
> 
> Hello. Not tried yet a 1.46a. With 750 on core and 1400 all went fine whole night. This morning suddenly got two restats in 30 mins, reduced core to 1200, again gew miner crashes. I do not understand what gping on. Internet is very good fiber link and no hardware problems in setup. Could it be a pool problem? I use raveos latest version.

I know it was a crash in case pool fails in 1.46, but with 1.46a that was solved... let's try to see in RaveOS upadte to 1.46a

**Comment by kotopuz** [comment]
> 

Uhh. Few hours 1.46a was stable. Then 10 reboot after low hashrate. Logs where disabled. Will try to cat now.

**Comment by jgonzis** [comment]
> > 
> 
> Uhh. Few hours 1.46a was stable. Then 10 reboot after low hashrate. Logs where disabled. Will try to cat ch now.

1.46a has been a quite good solution, could you try to put 25more mV to the core, just more Voltage, the dual normaly consumes a little bit more, and it could be a crash in the GPU...
