### ISSUE TITLE
Disconnect from NICEHASH

### ISSUE THREAD

**Issue by Vinasis01** [Lolliedieb/lolMiner-releases#1315]
Hello, running multiple rigs on windows with ETH to nicehash, randomly after a few hours any rig get this error 

Would adding this link fix the issue? it was proposed in one of the posts for version 1.45?

--ethstratum ETHV1

![image](https://user-images.githubusercontent.com/49044292/155157993-522ef686-2e7f-4b84-8d0a-721a32336a4e.png)

**Comment by jgonzis** [comment]
> Hello, running multiple rigs on windows with ETH to nicehash, randomly after a few hours any rig get this error
> 
> Would adding this link fix the issue? it was proposed in one of the posts for version 1.45?
> 
> --ethstratum ETHV1
> 
> ![image](https://user-images.githubusercontent.com/49044292/155157993-522ef686-2e7f-4b84-8d0a-721a32336a4e.png)

If it is 1.46, it is a bug not restoring the connection an update will come very soon. it is a know bug.

**Comment by jgonzis** [comment]
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.46a

Updated!

**Comment by Vinasis01** [comment]
There is no windows download in the assets, will it be added later?

**Comment by jgonzis** [comment]
> There is no windows download in the assets, will it be added later?

It should be Windows too: 
https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Win64.zip
