### ISSUE TITLE
t is periodically disconnected from the NiceHash server

### ISSUE THREAD

**Issue by japone777** [Lolliedieb/lolMiner-releases#1319]
t is periodically disconnected from the NiceHash server, the hashrate is 0 on all algorithms, the built-in timer does not restart the miner. If you restart manually, then everything starts to mine again, how to configure that when the hashrate is equal to 0, the miner is restarted?

**Comment by jgonzis** [comment]
> t is periodically disconnected from the NiceHash server, the hashrate is 0 on all algorithms, the built-in timer does not restart the miner. If you restart manually, then everything starts to mine again, how to configure that when the hashrate is equal to 0, the miner is restarted?

Use new Version 1.46a please... that should solve the problem!!
