### ISSUE TITLE
Memory allocation error (Gefore TI 1050)

### ISSUE THREAD

**Issue by beinando** [Lolliedieb/lolMiner-releases#132]
Hi, i just checked out the Ether - Mining using a Gefore1050 TI. 

I get the following error message:

"GPU 0: insufficient memory for DAG epoch 387.
GPU 0: will be in Zombie mode with reduced hashrate.
GPU 0: Allocation of DAG failed with error: Memory object allocation failure
GPU 0: will be stopped."

In the file "mine_eth_4G.bat" , i tried --4g-alloc-size  4024, --4g-alloc-size  4072 (as someone here proposed in another topic), --4g-alloc-size  4088 and --4g-alloc-size  4096, all of them producing the same error written above.

I use NVIDIA cuda runtime 10.1 , already tried and working for deep learning applications.

Would be cool if someone could help me. Thank you!

**Comment by mizuapo** [comment]
Same problem (nvidia memory: 4039 mb, 4040 mb), could you help us? (hive os, lol miner v1.18) but the sapphire nitro works correctly (4096Mb)

**Comment by OdinIsWithUs** [comment]
Same issue here. Nvidia GeForce 1650. Tried changing the parameters as suggested in the Zip file text, but nothing seems to be working for me whatsoever. 

It runs fine and boots up, but just gives me that same message as above (however it says Epoch 388)

**Comment by almoutinho** [comment]
Same here with a gtx 970

Thanks

**Comment by jgonzis** [comment]
No Nvidia Support for Zombie Mode
