### ISSUE TITLE
HiveOS ETH+TON 1.46/1.46a (gtx 1660super) Unrecoverable memory error

### ISSUE THREAD

**Issue by Sankerke** [Lolliedieb/lolMiner-releases#1320]
Hi, after upgrading to 1.46 (from **1.43** which works pretty well) i'm having crashes every 10-15minutes with "Unrecoverable memory error   by GPU *" on my rig with **9x gtx 1660 super** cards. I've tried different OC and even without any OC, result is the same. Also i've tried different -maxdualimpact parameter, it didn't help.

After i upgraded to 1.46a, rig reboots every ~10minutes BUT without error, just with message "lolminer reboot".

I have another rig on new RTX and RX cards and it works very well there on both 1.43/1.46

**Comment by JohnnyPh** [comment]
Same issue for one of my 1660s grid, for now just temporarily disabled the card will help prevent the error

**Comment by Denis-2021** [comment]
I get the same Unrecoverable memory error on HiveOS every time on different GPU 1660Ti/1660 Super
The problem is in versions 1.44-Latest(1.46)

**Comment by Imam279** [comment]
same with me

**Comment by jgonzis** [comment]
When ever reporting an issue, please always include
- the miner version and the algorithms you are running
- the GPU types involved
- the operations system
- the driver version if known
Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
Thanks!

**Comment by JohnnyPh** [comment]
> When ever reporting an issue, please always include
> 
> * the miner version and the algorithms you are running
> * the GPU types involved
> * the operations system
> * the driver version if known
>   Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
>   Thanks!

error: Unrecoverable memory error by GPU -> which lead to all the rest GPU crash right after that and triggered hiveos reboot itself as "gpu lost"
My spec:
0.6-213@220222
 5.10.0-hiveos #60
N470.63.01
GTX 1660 × 4·GTX 1660s × 3·GTX 1060 × 2
Most of the time it crash on GPU6 the if i enable that one, sometimes it crash on different GPU but disable the GPU6 also help prevent the problem
I didn't capture the error but here is my OC setting
![760699F6-F843-40E9-9FED-FC3FDE8A3039](https://user-images.githubusercontent.com/28253406/155299935-7bae7f80-0422-4b24-b604-525eb0fd54aa.png)
![BFC8A6D8-DF08-43FC-B29F-3A6D1BFC318E](https://user-images.githubusercontent.com/28253406/155299947-e96a5ad4-994b-4e81-beb6-2fb8982ac223.png)

**Comment by jgonzis** [comment]
> > When ever reporting an issue, please always include
> > 
> > * the miner version and the algorithms you are running
> > * the GPU types involved
> > * the operations system
> > * the driver version if known
> >   Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
> >   Thanks!
> 
> error: Unrecoverable memory error by GPU -> which lead to all the rest GPU crash right after that and triggered hiveos reboot itself as "gpu lost" My spec: 0.6-213@220222 5.10.0-hiveos #60 N470.63.01 GTX 1660 × 4·GTX 1660s × 3·GTX 1060 × 2 Most of the time it crash on GPU6 the if i enable that one, sometimes it crash on different GPU but disable the GPU6 also help prevent the problem I didn't capture the error but here is my OC setting (GPU6 OC was 1600core, 2380mem,pl110 at the time it crash) ![760699F6-F843-40E9-9FED-FC3FDE8A3039](https://user-images.githubusercontent.com/28253406/155299935-7bae7f80-0422-4b24-b604-525eb0fd54aa.png) ![BFC8A6D8-DF08-43FC-B29F-3A6D1BFC318E](https://user-images.githubusercontent.com/28253406/155299947-e96a5ad4-994b-4e81-beb6-2fb8982ac223.png)

Many thanks, Could it be that new dual is more aggresive. Could you please try lowering the memory OC? they to test something saver like 1900. To see if it is stable first.

**Comment by JohnnyPh** [comment]
> > > When ever reporting an issue, please always include
> 
> > > 
> 
> > > * the miner version and the algorithms you are running
> 
> > > * the GPU types involved
> 
> > > * the operations system
> 
> > > * the driver version if known
> 
> > >   Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
> 
> > >   Thanks!
> 
> > 
> 
> > error: Unrecoverable memory error by GPU -> which lead to all the rest GPU crash right after that and triggered hiveos reboot itself as "gpu lost" My spec: 0.6-213@220222 5.10.0-hiveos #60 N470.63.01 GTX 1660 × 4·GTX 1660s × 3·GTX 1060 × 2 Most of the time it crash on GPU6 the if i enable that one, sometimes it crash on different GPU but disable the GPU6 also help prevent the problem I didn't capture the error but here is my OC setting (GPU6 OC was 1600core, 2380mem,pl110 at the time it crash) ![760699F6-F843-40E9-9FED-FC3FDE8A3039](https://user-images.githubusercontent.com/28253406/155299935-7bae7f80-0422-4b24-b604-525eb0fd54aa.png) ![BFC8A6D8-DF08-43FC-B29F-3A6D1BFC318E](https://user-images.githubusercontent.com/28253406/155299947-e96a5ad4-994b-4e81-beb6-2fb8982ac223.png)
> 
> 
> 
> Many thanks, Could it be that new dual is more aggresive. Could you please try lowering the memory OC? they to test something saver like 1900. To see if it is stable first.

Look like that's the cause, prety much no error now... thanks😁

**Comment by jgonzis** [comment]
> > > > When ever reporting an issue, please always include
> > 
> > 
> > > >
> > 
> > 
> > > > * the miner version and the algorithms you are running
> > 
> > 
> > > > * the GPU types involved
> > 
> > 
> > > > * the operations system
> > 
> > 
> > > > * the driver version if known
> > 
> > 
> > > > Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
> > 
> > 
> > > > Thanks!
> > 
> > 
> > > 
> > 
> > 
> > > error: Unrecoverable memory error by GPU -> which lead to all the rest GPU crash right after that and triggered hiveos reboot itself as "gpu lost" My spec: 0.6-213@220222 5.10.0-hiveos #60 N470.63.01 GTX 1660 × 4·GTX 1660s × 3·GTX 1060 × 2 Most of the time it crash on GPU6 the if i enable that one, sometimes it crash on different GPU but disable the GPU6 also help prevent the problem I didn't capture the error but here is my OC setting (GPU6 OC was 1600core, 2380mem,pl110 at the time it crash) ![760699F6-F843-40E9-9FED-FC3FDE8A3039](https://user-images.githubusercontent.com/28253406/155299935-7bae7f80-0422-4b24-b604-525eb0fd54aa.png) ![BFC8A6D8-DF08-43FC-B29F-3A6D1BFC318E](https://user-images.githubusercontent.com/28253406/155299947-e96a5ad4-994b-4e81-beb6-2fb8982ac223.png)
> > 
> > 
> > Many thanks, Could it be that new dual is more aggresive. Could you please try lowering the memory OC? they to test something saver like 1900. To see if it is stable first.
> 
> Look like that's the cause, prety much no error now... thanks😁

The experience I have with some 1660S Samsung, is that after some time of use at high Memory OC, they start to crash me. I finally get them stables at 1900... but each GPUs is different. 

Thx for the feedback
