### ISSUE TITLE
подозрение на Южный мост

### ISSUE THREAD

**Issue by starsfox911** [Lolliedieb/lolMiner-releases#1321]
После последнего обновления риг постоянно вылетает +- 30 мин, ошибка в ненайденой температуре графического адаптера.
далее ничего нельзя отследить.... риг зависает.
материнская плата на 12 карт Biostar,вот и я думаю, что с поднятием хешрейтом не справляется южный мост,до этого обновления все было ок.
возможно ли 
МП
TB250-BTC PRO BIOSTAR Group (5.12 02/22/2018)
CPU
2 × Intel(R) Celeron(R) CPU G3900 @ 2.80GHz AES
Модель диска
ATA TOSHIBA MK7559GS 750GB
Тип системы
linux
Ядро
5.10.0-hiveos #83

**Comment by jgonzis** [comment]
> После последнего обновления риг постоянно вылетает +- 30 мин, ошибка в ненайденой температуре графического адаптера.
> далее ничего нельзя отследить.... риг зависает.
> материнская плата на 12 карт Biostar,вот и я думаю, что с поднятием хешрейтом не справляется южный мост,до этого обновления все было ок.
> возможно ли
> МП
> TB250-BTC PRO BIOSTAR Group (5.12 02/22/2018)
> CPU
> 2 × Intel(R) Celeron(R) CPU G3900 @ 2.80GHz AES
> Модель диска
> ATA TOSHIBA MK7559GS 750GB
> Тип системы
> linux
> Ядро
> 5.10.0-hiveos #83

Please try to update to 1.46a: We found some users with that problem too:

cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xvf lolMiner_v1.46a_Lin64.tar.gz && cd 1.46a && miner stop && cp lolMiner /hive/miners/lolminer/1.46 && miner start
