### ISSUE TITLE
Version 1.46 a can 't pick up parameters for the 3060ti msi gaming

### ISSUE THREAD

**Issue by japone777** [Lolliedieb/lolMiner-releases#1322]
Version 1.46 a can 't pick up parameters for the 3060ti msi gaming .. in Version 1.4, everything is fine-tuned automatically. In version 1.46 a, the parameters jump from 35 mh\s to 0 mh\s to 25 mh\s
what to do?

**Comment by japone777** [comment]
if you restart the miner several times, it can pick up the speed, but then at some point any other card falls off..output in version 1.46 a unstable selection of parameters

**Comment by jgonzis** [comment]
When ever reporting an issue, please always include
- the miner version and the algorithms you are running
- the GPU types involved
- the operations system
- the driver version if known
Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
Thanks!

**Comment by japone777** [comment]
> Сообщая о проблеме, всегда указывайте
> 
> * версия майнера и алгоритмы, которые вы используете
> * задействованные типы графических процессоров
> * операционная система
> * версия драйвера, если она известна 
>   . Кроме того: любой вывод майнера, также известный как вывод его консоли, чрезвычайно ценен для нас, чтобы понять, почему что-то может не работать, например, состояние настройки, сообщение о сбое или проблема с подключением к пулу. Поэтому, когда это возможно, старайтесь помочь нам, предоставив это - это повысит вероятность того, что мы поможем вам с вашей проблемой, или облегчит нам поиск ошибки - если она есть - от которой вы сильно страдаете. 
>   Спасибо!

Eth+ ton 1.46a
1070ti
3060ti lhr
3070
3080
3090
Windows 10
472.12

**Comment by jgonzis** [comment]
> > Сообщая о проблеме, всегда указывайте
> > 
> > * версия майнера и алгоритмы, которые вы используете
> > * задействованные типы графических процессоров
> > * операционная система
> > * версия драйвера, если она известна
> >   . Кроме того: любой вывод майнера, также известный как вывод его консоли, чрезвычайно ценен для нас, чтобы понять, почему что-то может не работать, например, состояние настройки, сообщение о сбое или проблема с подключением к пулу. Поэтому, когда это возможно, старайтесь помочь нам, предоставив это - это повысит вероятность того, что мы поможем вам с вашей проблемой, или облегчит нам поиск ошибки - если она есть - от которой вы сильно страдаете.
> >   Спасибо!
> 
> Eth+ ton 1.46a 1070ti 3060ti lhr 3070 3080 3090 Windows 10 472.12

The tune need to be done without browser or anyother program running.... Also let's try to use --lhrtune off,auto,off,off,off considering that you have LHR in the GPU1 (GPU0 will be 1070ti).... to see if that helps... I don't know if you are using lock core or not?. Have you read our Windows Guide Recommendation?. https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer)

**Comment by japone777** [comment]
> --lhrtune off



> > > Сообщения о проблемах, всегда указывайте
> > > 
> > > * версии майнера и алгоритмы, которые вы придерживаетесь
> > > * исчерпывающие типы графических процессоров
> > > * операционная система
> > > * версия драйвера, если она поймается 
> > >   . Кроме того: любой вывод майнера, также известный как вывод его консоли, имеет значение для нас, понять, почему что-то может не работать, например, состояние, сообщение о проблеме с подключением к пулу. Поэтому, когда это возможно, постарайтесь помочь, прежде чем поставить это - это повысит вероятность того, что мы поможем вам с проблемой бедствия, или облегчит нам поиск ошибок - если она есть - от чего сильно выявляется. 
> > >   Спасибо!
> > 
> > 
> > Eth+ тонна 1.46a 1070ti 3060ti л/ч 3070 3080 3090 Windows 10 472,12
> 
> Настройка должна выполняться без запуска или любой другой программы.... Также давайте попробуем --lhrtune off,auto,off,off,off, полагаю, что у вас есть LHR в GPU1 (GPU0 будет 1070ti)... , чтобы посмотреть, поможет ли это... Я не знаю, присутствует ли вы ядро ​​блокировки или нет? Вы прочитали наши рекомендации по руководству по Windows?. [https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR, Watchdog, WebServer)](https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer))

Friend, msi 3060 t i gaming xlr is a very specific card in terms of mining and differs from other lhr cards, as evidenced by many posts of other owners on other forums. The core frequency is not fixed on it, the video card simply resets the settings

**Comment by japone777** [comment]
> > > Сообщая о проблеме, всегда указывайте
> > > 
> > > * версия майнера и алгоритмы, которые вы используете
> > > * задействованные типы графических процессоров
> > > * операционная система
> > > * версия драйвера, если она известна
> > >   . Кроме того: любой вывод майнера, также известный как вывод его консоли, чрезвычайно ценен для нас, чтобы понять, почему что-то может не работать, например, состояние настройки, сообщение о сбое или проблема с подключением к пулу. Поэтому, когда это возможно, старайтесь помочь нам, предоставив это - это повысит вероятность того, что мы поможем вам с вашей проблемой, или облегчит нам поиск ошибки - если она есть - от которой вы сильно страдаете.
> > >   Спасибо!
> > 
> > 
> > Eth+ тонна 1.46a 1070ti 3060ti л/ч 3070 3080 3090 Windows 10 472,12
> 
> Настройка должна выполняться без запуска браузера или любой другой программы.... Также давайте попробуем использовать --lhrtune off,auto,off,off,off, учитывая, что у вас есть LHR в GPU1 (GPU0 будет 1070ti)... , чтобы посмотреть, поможет ли это... Я не знаю, используете ли вы ядро ​​блокировки или нет? Вы читали наши рекомендации по руководству по Windows?. [https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR, Watchdog, WebServer)](https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer))


besides, my 1070ti eventually starts mining 0 megahash. afterburner, its settings are active, that is, it does not work only in the miner. If you manually close and open the miner, it starts mining again
At first I thought it was a fixed 1070, because it was she who constantly fell off, the others did not fall off, but then I took it off to clean it and the other one fell off .. it's in the miner

**Comment by jgonzis** [comment]
> > > > Сообщая о проблеме, всегда указывайте
> > > > 
> > > > * версия майнера и алгоритмы, которые вы используете
> > > > * задействованные типы графических процессоров
> > > > * операционная система
> > > > * версия драйвера, если она известна
> > > >   . Кроме того: любой вывод майнера, также известный как вывод его консоли, чрезвычайно ценен для нас, чтобы понять, почему что-то может не работать, например, состояние настройки, сообщение о сбое или проблема с подключением к пулу. Поэтому, когда это возможно, старайтесь помочь нам, предоставив это - это повысит вероятность того, что мы поможем вам с вашей проблемой, или облегчит нам поиск ошибки - если она есть - от которой вы сильно страдаете.
> > > >   Спасибо!
> > > 
> > > 
> > > Eth+ тонна 1.46a 1070ti 3060ti л/ч 3070 3080 3090 Windows 10 472,12
> > 
> > 
> > Настройка должна выполняться без запуска браузера или любой другой программы.... Также давайте попробуем использовать --lhrtune off,auto,off,off,off, учитывая, что у вас есть LHR в GPU1 (GPU0 будет 1070ti)... , чтобы посмотреть, поможет ли это... Я не знаю, используете ли вы ядро ​​блокировки или нет? Вы читали наши рекомендации по руководству по Windows?. [https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR, Watchdog, WebServer)](https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer))
> 
> besides, my 1070ti eventually starts mining 0 megahash. afterburner, its settings are active, that is, it does not work only in the miner. If you manually close and open the miner, it starts mining again At first I thought it was a fixed 1070, because it was she who constantly fell off, the others did not fall off, but then I took it off to clean it and the other one fell off .. it's in the miner ![666](https://user-images.githubusercontent.com/99234250/155545225-2a94edeb-1543-43f5-a6d2-23524789b512.JPG)

Could it be DAG Repairing ... I don't know... I don't see much more information
