### ISSUE TITLE
LolMiner 1.45-1.46 Can't connect to nicehash pool via HiveOS

### ISSUE THREAD

**Issue by Denis-2021** [Lolliedieb/lolMiner-releases#1324]
When I use v1.44 everything connects and work, but v1.45 doesn't connect at all and v1.46 connects at first but that disconnects after some time and cant reconnect.

**Comment by jgonzis** [comment]
> When I use v1.44 everything connects and work, but v1.45 doesn't connect at all and v1.46 connects at first but that disconnects after some time and cant reconnect.

Yes you are right. 1.46a has solved that in the fix... it must reconnect correctly
