### ISSUE TITLE
version 1.46a not hold OC settings compare to 1.46

### ISSUE THREAD

**Issue by bekman1** [Lolliedieb/lolMiner-releases#1327]
After upgrading to 1.46a i must decrease my memory OC settings from 2600 to 2400 or 2200 for many my 3070 LHR cards.
dmesg comand output show many segfault errors messages of lolMiner process.
What have you changed in 1.46a ??? Stability is much less, compare to 1.46
Regards

**Comment by lexaser** [comment]
same problem with 1.46a，i have some 3060ti LHR and 3070 LHR cards，3060ti works well while 3070 prompts memory error

**Comment by HeraklesTR** [comment]
exactly, all in a sudden, my 3090 3070ti's in my rig getting crash restarts even they doesnt look crashed. they dont in previous version, even in 1.46 all was fine. @Lolliedieb also can you release the core and memory locks after closing the miner like t-rex miner does? i dont want to restart my pc every time to makes clocks free again...

**Comment by japone777** [comment]
Are your cards completely disabled until you restart your computer?

**Comment by jgonzis** [comment]
> exactly, all in a sudden, my 3090 3070ti's in my rig getting crash restarts even they doesnt look crashed. they dont in previous version, even in 1.46 all was fine. @Lolliedieb also can you release the core and memory locks after closing the miner like t-rex miner does? i dont want to restart my pc every time to makes clocks free again...

You can put nvidia-smi -rgc to remove the locks of the clocks.



> After upgrading to 1.46a i must decrease my memory OC settings from 2600 to 2400 or 2200 for many my 3070 LHR cards. dmesg comand output show many segfault errors messages of lolMiner process. What have you changed in 1.46a ??? Stability is much less, compare to 1.46 Regards

That segfault doesn't come from the memory, when is memory is a message saying Unrecoverable memory, but doesn't make a segfault. Could you try to show last lolMiner log, before the crash of the segfault. Also in which OS happened and verstion to have more information?

**Comment by KoodGarma** [comment]
> exactly, all in a sudden, my 3090 3070ti's in my rig getting crash restarts even they doesnt look crashed. they dont in previous version, even in 1.46 all was fine. @Lolliedieb also can you release the core and memory locks after closing the miner like t-rex miner does? i dont want to restart my pc every time to makes clocks free again...

Agreed, in the meantime, another option is to use MSI Afterburner to restore default GPU settings.

**Comment by jgonzis** [comment]
> same problem with 1.46a，i have some 3060ti LHR and 3070 LHR cards，3060ti works well while 3070 prompts memory error

Some photos 

> > exactly, all in a sudden, my 3090 3070ti's in my rig getting crash restarts even they doesnt look crashed. they dont in previous version, even in 1.46 all was fine. @Lolliedieb also can you release the core and memory locks after closing the miner like t-rex miner does? i dont want to restart my pc every time to makes clocks free again...
> 
> Agreed, in the meantime, another option is to use MSI Afterburner to restore default GPU settings.

We are working on that... we already have a file that do it, but we want to integrated all in the exe file... I hope next release have it

**Comment by KoodGarma** [comment]
> After upgrading to 1.46a i must decrease my memory OC settings from 2600 to 2400 or 2200 for many my 3070 LHR cards. dmesg comand output show many segfault errors messages of lolMiner process. What have you changed in 1.46a ??? Stability is much less, compare to 1.46 Regards

I was noticing lower hashrates w/ 1.46a maybe because the OCs weren't keeping, but I went back to 1.45 and am also getting the same lower hashrates.

**Comment by jgonzis** [comment]
> same problem with 1.46a，i have some 3060ti LHR and 3070 LHR cards，3060ti works well while 3070 prompts memory error

Could you please provide more information, OS?, Drivers, Photo... really please understand it is complicated without information to try to find where it could be a problem...

**Comment by jgonzis** [comment]
> Could you please provide more information, OS?, Drivers, Photo... really please understand it is complicated without information to try to find where it could be a problem...

Could you please provide more information, OS?, Drivers, Photo... really please understand it is complicated without information to try to find where it could be a problem...

**Comment by bekman1** [comment]
> > After upgrading to 1.46a i must decrease my memory OC settings from 2600 to 2400 or 2200 for many my 3070 LHR cards. dmesg comand output show many segfault errors messages of lolMiner process. What have you changed in 1.46a ??? Stability is much less, compare to 1.46 Regards

i use Linux (hiveOS  0.6-213) Nvidia driver 470.86
The problem only on 3070 LHR (Asus TUF, ASUS DUAL, EVGA XC3) all cards is OC variant.
Not all my 3070 LHR cards is affected. Many other 3070 LHR cards work stable with old OC settings from version 1.46
dmesg output show MEMORY READ/WRITE errors of affected cards. After decreasing memory OC for 200-400 mhz, stability come back.
I start mining with folowing OC settings: PL 66-68%, Core clock boost 0, Memory boost 2600 mhz
Before i start lolMiner 1.46a i fix core clock with:  sudo nvidia-smi -lgc 1395,1395

**Comment by F41nT** [comment]
Have the same issue with OC stability. HiveOS 220222, 1.46a. I thought that I have a problem with mem temps but after going back to 1.46 no more reboots. NVIDIA driver 470.86. Couldn't sleep whole night because of that ; _ ;

**Comment by jgonzis** [comment]
> > > After upgrading to 1.46a i must decrease my memory OC settings from 2600 to 2400 or 2200 for many my 3070 LHR cards. dmesg comand output show many segfault errors messages of lolMiner process. What have you changed in 1.46a ??? Stability is much less, compare to 1.46 Regards
> 
> i use Linux (hiveOS 0.6-213) + Awesome Miner. Nvidia driver 470.86 The problem only on 3070 LHR (Asus TUF, ASUS DUAL, EVGA XC3) all cards is OC variant. Not all my 3070 LHR cards is affected. Many other 3070 LHR cards work stable with old OC settings from version 1.46 dmesg output show MEMORY READ/WRITE errors of affected cards. After decreasing memory OC for 200-400 mhz, stability come back. But ETH hashrate is less now, of course. I start mining with folowing OC settings: PL 66-68% (152-162 watt), Core clock boost 0 mhz, Memory boost 2600 mhz Before i start lolMiner 1.46a i fix core clock with: sudo nvidia-smi -lgc 1395,1395 After stoping, the core clock fix will be reset with: sudo nvidia-smi -rgc lolMiner startet with administrator privileges.
> 
> demesg output: `[ 139.629588] NVRM: Xid (PCI:0000:01:00): 31, pid=4301, Ch 00000011, intr 00000000. MMU Fault: ENGI NE GRAPHICS GPCCLIENT_T1_0 faulted @ 0x7fb6_2d801000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_RE AD [ 139.651627] NVRM: GPU at PCI:0000:0a:00: GPU-6fa98846-84fa-6fce-eded-a76815c2cecb [ 139.651628] NVRM: Xid (PCI:0000:0a:00): 31, pid=4301, Ch 00000011, intr 00000000. MMU Fault: ENGI NE GRAPHICS GPCCLIENT_T1_0 faulted @ 0x7fb6_2fa01000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_RE AD [25209.224765] perf: interrupt took too long (2516 > 2500), lowering kernel.perf_event_max_sample_ra te to 79250 [34561.283842] perf: interrupt took too long (3148 > 3145), lowering kernel.perf_event_max_sample_ra te to 63500 [51628.690174] lolMiner[10260]: segfault at 10 ip 00007f3382448a88 sp 00007f3353b49c08 error 6 in li bc-2.27.so[7f33822ba000+1e7000] [51628.690186] Code: d1 f3 a4 c3 80 fa 10 73 17 80 fa 08 73 27 80 fa 04 73 33 80 fa 01 77 3b 72 05 0 f b6 0e 88 0f c3 c5 fa 6f 06 c5 fa 6f 4c 16 f0 <c5> fa 7f 07 c5 fa 7f 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 48 89 4c [51716.541210] lolMiner[5102]: segfault at 10 ip 00007ff348349a88 sp 00007ff330c1fc08 error 6 in lib c-2.27.so[7ff3481bb000+1e7000] [51716.541215] Code: d1 f3 a4 c3 80 fa 10 73 17 80 fa 08 73 27 80 fa 04 73 33 80 fa 01 77 3b 72 05 0 f b6 0e 88 0f c3 c5 fa 6f 06 c5 fa 6f 4c 16 f0 <c5> fa 7f 07 c5 fa 7f 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 48 89 4c [51741.260315] lolMiner[9987]: segfault at 10 ip 00007fd861afea88 sp 00007fd800ffac08 error 6 in lib c-2.27.so[7fd861970000+1e7000] [51741.260329] Code: d1 f3 a4 c3 80 fa 10 73 17 80 fa 08 73 27 80 fa 04 73 33 80 fa 01 77 3b 72 05 0 f b6 0e 88 0f c3 c5 fa 6f 06 c5 fa 6f 4c 16 f0 <c5> fa 7f 07 c5 fa 7f 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 48 89 4c [51841.585728] NVRM: GPU at PCI:0000:04:00: GPU-6d7b224e-919d-790e-49f7-accac69ec746 [51841.585733] NVRM: Xid (PCI:0000:04:00): 31, pid=11058, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_5 faulted @ 0x7f9f_a6000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R EAD [51841.625802] NVRM: Xid (PCI:0000:08:00): 31, pid=11058, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_0 faulted @ 0x7fa2_65000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R EAD [51841.649338] NVRM: GPU at PCI:0000:03:00: GPU-15851083-e416-6357-6571-32b41a6ca3ec [51841.649339] NVRM: Xid (PCI:0000:03:00): 31, pid=11058, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_1 faulted @ 0x7fa2_97c06000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R EAD [51841.669013] NVRM: Xid (PCI:0000:01:00): 31, pid=11058, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_1 faulted @ 0x7fa2_64807000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R EAD [51841.691847] NVRM: Xid (PCI:0000:05:00): 31, pid=11058, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_0 faulted @ 0x7fa2_61600000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R EAD [51841.716552] NVRM: Xid (PCI:0000:0a:00): 31, pid=11058, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_0 faulted @ 0x7fa2_65800000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R EAD [52101.857176] lolMiner[29096]: segfault at 10 ip 00007fe5eb51fa88 sp 00007fe588ffac08 error 6 in li bc-2.27.so[7fe5eb391000+1e7000] [52101.857190] Code: d1 f3 a4 c3 80 fa 10 73 17 80 fa 08 73 27 80 fa 04 73 33 80 fa 01 77 3b 72 05 0 f b6 0e 88 0f c3 c5 fa 6f 06 c5 fa 6f 4c 16 f0 <c5> fa 7f 07 c5 fa 7f 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 48 89 4c [52209.346120] NVRM: Xid (PCI:0000:09:00): 31, pid=30174, Ch 00000011, intr 00000000. MMU Fault: ENG INE GRAPHICS GPCCLIENT_T1_2 faulted @ 0x7f55_7fa00000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_R `

Use always  PL to 100% or  correct in HiveOS PL go 0 and put the Core directly if the Configuration of HiveOS.

**Comment by jgonzis** [comment]
> Have the same issue with OC stability. HiveOS 220222, 1.46a. I thought that I have a problem with mem temps but after going back to 1.46 no more reboots. NVIDIA driver 470.86. Couldn't sleep whole night because of that ; _ ;

There were no changes in code of mining from 1.46 to 1.46a. Unless you give more information about your OC your GPUs, which fails appear, if you are using maxdualimpact or not we cannot help you.
