### ISSUE TITLE
How to DISABLE LHR?

### ISSUE THREAD

**Issue by Druxlolz** [Lolliedieb/lolMiner-releases#1328]
Hello.

I got a 3060 NON LHR or V1 and are having BIG issues with lolminer.

The problem is that LHR keeps activating even when it's not a lhr card, it will do it everytime and i would have to restart miner to get it up to 48 mh/s again...

I tried a few commands in lolminer but didn't have any luck anyone know how to diable LHR tuner????
It's very annoying that there is no guide / option on wiki about this.

**Comment by jgonzis** [comment]
> Hello.
> 
> I got a 3060 NON LHR or V1 and are having BIG issues with lolminer.
> 
> The problem is that LHR keeps activating even when it's not a lhr card, it will do it everytime and i would have to restart miner to get it up to 48 mh/s again...
> 
> I tried a few commands in lolminer but didn't have any luck anyone know how to diable LHR tuner???? It's very annoying that there is no guide / option on wiki about this.

Hi,

you can add --lhrtune off

That will disable LHR Detection.
