### ISSUE TITLE
the parameter --apiport has not aplied

### ISSUE THREAD

**Issue by GalayZloy** [Lolliedieb/lolMiner-releases#1329]
The are errors while starting miner:
`option '--apiport' cannot be specified more than once`
`lolminer exited (exitcode=0), waiting to cooldown a bit`
`Skipping miner log rotation due to execution time < 30sec`
Miner not starting.

**Comment by Kostas-13** [comment]
on windows? if so..
Have u specify a port eg. --apiport 8080
for me it's like.. =>

:W10
"%MyVariable%" --devices "5,0" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit --apiport 8080

v1.46a and workin fine.

**Comment by GalayZloy** [comment]
> 

:44444 is default port and aplied if parameter --apiport has not setted.
if i set custom port, `--apiport 23456` for example, miner give errors.

**Comment by jgonzis** [comment]
> No, its HiveOS.

Because HiveOS has by default 44444 and you cannot edit... it is standard, unless you edit the files of the lolminer global config in /hive/miners/lolminer/1.46a
