### ISSUE TITLE
rtx 2060 super 8gb is only using 4g

### ISSUE THREAD

**Issue by NickG8970** [Lolliedieb/lolMiner-releases#133]
Setup Miner...
Device 0:
    Name:    GeForce RTX 2060 SUPER
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  8192 MByte
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash)

Connecting to pool...
Connected to eu1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x0bA67B7011340452147054739bfA5a3f68561C86.lolMinerWorker
New job received: 0xc8da02 Epoch: 387 Target: 0000000112e0be82
-------------------------------------------------------
         Generating light cache for epoch 387
-------------------------------------------------------
Start Mining...
-------------------------------------------------------
     Done (2083 ms), size of new DAG: 4120 MByte
is this normal?

**Comment by Lolliedieb** [comment]
Yes, this is normal, because the dag size is depending on the epoch we have.
