### ISSUE TITLE
 where to prescribe DISABLE LHR?

### ISSUE THREAD

**Issue by japone777** [Lolliedieb/lolMiner-releases#1333]
Where exactly in the file should I write --lhrtune off to disable lhr selection? please screenshot

**Comment by michiganpinball** [comment]
![nolhr](https://user-images.githubusercontent.com/95937952/155394655-d15c8d10-5ae3-448d-b00a-325ad0651111.jpg)

**Comment by jgonzis** [comment]
> Where exactly in the file should I write --lhrtune off to disable lhr selection? please screenshot

You can add it also the EDITABLE part after the = of EXTRAPARAMETERS
