### ISSUE TITLE
dual and solo TON mining is differs by 2 times

### ISSUE THREAD

**Issue by od1nson** [Lolliedieb/lolMiner-releases#1336]
Dual and single TON mining is differs by 2 times. When I start mining TON solo, it's about 1600 Mh/s, but if I start it in duo mining ETH+TON, it's about 100-300 Mh/s for TON, with increased memory clock, and 48-49 Mh/s for ETH, but without any overclocking action, it's ~800 Mh/s for TON and 35-40 Mh/s for ETH.
According to my observations, when I mine TON solo, the GPU Clock goes from 1600MHz to 1800MHz
and that's 1600 Mh/s for TON, but in duo, GPU Clock goes down to 950-1000MHz, without any core clock curve editing in MSI Afterburner and that's 100-300 Mh/s for TON.

Lenovo Legion 5 15ACH6H 82JU0010RU
RTX3060 Laptop, 90W
511.79
1.43
1.45
1.46a
Win11

**Comment by jgonzis** [comment]
> Dual and single TON mining is differs by 2 times. When I start mining TON solo, it's about 1600 Mh/s, but if I start it in duo mining ETH+TON, it's about 100-300 Mh/s for TON, with increased memory clock, and 48-49 Mh/s for ETH, but without any overclocking action, it's ~800 Mh/s for TON and 35-40 Mh/s for ETH. According to my observations, when I mine TON solo, the GPU Clock goes from 1600MHz to 1800MHz and that's 1600 Mh/s for TON, but in duo, GPU Clock goes down to 950-1000MHz, without any core clock curve editing in MSI Afterburner and that's 100-300 Mh/s for TON.
> 
> Lenovo Legion 5 15ACH6H 82JU0010RU RTX3060 Laptop, 90W 511.79 1.43 1.45 1.46a Win11

Yes solo could go higher... with dual the core needs more time of use, he consumes meore and that's why the limit of 90W take effect blocky to go up the Core in the dual
