### ISSUE TITLE
ETH mining not sending shares and trying to reconnect for the last 2h

### ISSUE THREAD

**Issue by thiagottjv** [Lolliedieb/lolMiner-releases#1337]
Hi, I'm mining ETH on crazypool and TON on icemining with HiveOS with lolminer v1.46a.
The miner is mining for 3h now but for the last 2h it is not sending shares to the pool.
I`m getting the error:
Pool not reacting to submitted shares for too long. Reconnecting. 
or
Pool not sending data for 150 seconds. Reconnecting. 
This is happening only with 1 of my 4 rigs. All of them using the same flightsheet on HiveOS and lolminer version (1.46a).

This is the Crazypool dashboard:
![image](https://user-images.githubusercontent.com/4126003/155413146-51fcacb7-b9d7-4622-8399-7cc7acdbff60.png)
This is the Icemining:
![image](https://user-images.githubusercontent.com/4126003/155413624-e016300f-8608-4eb4-bdd0-c6dfd4793ad8.png)

I`ll restart the rig now and see if it will keep mining.

**Comment by jgonzis** [comment]
> Hi, I'm mining ETH on crazypool and TON on icemining with HiveOS with lolminer v1.46a. The miner is mining for 3h now but for the last 2h it is not sending shares to the pool. I`m getting the error: Pool not reacting to submitted shares for too long. Reconnecting. or Pool not sending data for 150 seconds. Reconnecting. This is happening only with 1 of my 4 rigs. All of them using the same flightsheet on HiveOS and lolminer version (1.46a).
> 
> This is the Crazypool dashboard: ![image](https://user-images.githubusercontent.com/4126003/155413146-51fcacb7-b9d7-4622-8399-7cc7acdbff60.png) This is the Icemining: ![image](https://user-images.githubusercontent.com/4126003/155413624-e016300f-8608-4eb4-bdd0-c6dfd4793ad8.png)
> 
> I`ll restart the rig now and see if it will keep mining.

Check what says the miner please?. What info display the 60s stats of that 6600xt? could you put it too?.

**Comment by thiagottjv** [comment]
Sorry, I don't know how to do it. On this rig I have 11 6600xt and one 3060 (no LHR).
Since I restarted it is mining without problem.
I just opened this issue because I think it may be related with today's update (I was using the v1.46 before) and could occur without anyone knowing (since the miner or hiveos wont restart).

![image](https://user-images.githubusercontent.com/4126003/155425942-cb922605-c118-4329-9e81-71292d21f8f1.png)

**Comment by jgonzis** [comment]
> Sorry, I don't know how to do it. On this rig I have 11 6600xt and one 3060 (no LHR). Since I restarted it is mining without problem. I just opened this issue because I think it may be related with today's update (I was using the v1.46 before) and could occur without anyone knowing (since the miner or hiveos wont restart).
> 
> ![image](https://user-images.githubusercontent.com/4126003/155425942-cb922605-c118-4329-9e81-71292d21f8f1.png)

Click in the top menu in the pick and select miner log. Then you will have the information there

**Comment by jgonzis** [comment]
Waiting for answer
