### ISSUE TITLE
Frequent disconnections

### ISSUE THREAD

**Issue by gravisxv** [Lolliedieb/lolMiner-releases#1338]
My miner has started behaving wrong in last 2 months or so. Im mining ergo continuosly and so far no problem, i even put a loop in bash script to restart and went well for lets say 6 months. Now it is almost once a day detecting a card crash and failing to restart/continue, while the card have not crashed. A simple manual command 'killall lolMiner' fix this with the miner restarting, but it is also silly in long terms.

**Comment by jgonzis** [comment]
> My miner has started behaving wrong in last 2 months or so. Im mining ergo continuosly and so far no problem, i even put a loop in bash script to restart and went well for lets say 6 months. Now it is almost once a day detecting a card crash and failing to restart/continue, while the card have not crashed. A simple manual command 'killall lolMiner' fix this with the miner restarting, but it is also silly in long terms.

When ever reporting an issue, please always include
- the miner version and the algorithms you are running
- the GPU types involved
- the operations system
- the driver version if known
Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
Thanks!
