### ISSUE TITLE
1.46a 3070LHR DAG repair at the beginning.

### ISSUE THREAD

**Issue by billvvv** [Lolliedieb/lolMiner-releases#1339]
Windows10， 427.12 3070LHR    1.46a --dualimpact 1.0
No matter how I changed the bat file, it will start with a verification detected. and I tried to restart my computer. the same.

start with the verification with 1200+segment and take a long time to repair. 
------------------------------------------------------- 
          Generated light cache for epoch 475 
       Took 3526 ms, size of new DAG: 4823 MByte 
------------------------------------------------------- 
GPU 1: Starting DAG generation (normal mode)
New job received: 00000000eb8da3ee Epoch: 475 Difficulty: 1.12G  
GPU 1: DAG build complete 15%
New job received: 00000000eb8da3ef Epoch: 475 Difficulty: 1.12G  
GPU 1: DAG build complete 31%
GPU 1: DAG build complete 47%
New job received: 00000000eb8da3f0 Epoch: 475 Difficulty: 1.12G  
GPU 1: DAG build complete 63%
GPU 1: DAG build complete 79%
New job received: 00000000eb8da3f1 Epoch: 475 Difficulty: 1.12G  
GPU 1: DAG build complete 95%
GPU 1: DAG generation completed (3615 ms)
GPU 1: DAG verification detected 1206 defect segment(s)
GPU 1: DAG repair will be started. This may take a moment.
GPU 1: starting smart DAG repair

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑at the start up↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓before crash↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

--------------------------------------------- 
Statistics (18:12:27); Uptime: 7h 18m 4s 
Algorithm 1: Ethash 
Connected to: daggerhashimoto.hk.nicehash.com:3353 (118ms latency) 
Algorithm 2: SHA256-TON 
Connected to: wss://eu1.stratum.ton-pool.com/stratum:443 (164ms latency) 

      Name     Speed   Pool      Shares    Best    Eff.    Speed     Pool
                Mh/s   Mh/s      A/S/Hw   Share  Mh/s/W     Mh/s     Mh/s
GPU 1 RTX 3070 44.12  39.78  2527/28/12  376.8G   0.213  1744.76  1553.01
--------------------------- 
Total          44.12  39.78  2527/28/12  376.8G   0.213  1744.76  1553.01

         Shares    Best    Eff.  Power  CCLK  MCLK  Core  Fan  --lhrtune
         A/S/Hw   Share  Mh/s/W      W   MHz   MHz  Temp  Pct           
GPU 1   594/0/0  286.7T   8.426  206.6  1453  8242    52   54        0.2
--------------------------- 
Total   594/0/0  286.7T   8.426  206.6                                  
--------------------------------------------- 
Ethash: Average speed (15s): 44.17 Mh/s
SHA256-TON: Average speed (15s): 1746.71 Mh/s
New job received: 000000007605a06a Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a06b Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a06c Epoch: 475 Difficulty: 559.49M  
Ethash: GPU 1: Found a share of difficulty 1.56G 
Ethash: GPU 1: Share accepted (107 ms) 
Ethash: GPU 1: Found a share of difficulty 0.71G 
Ethash: GPU 1: Share accepted (107 ms) 
Ethash: Average speed (15s): 44.11 Mh/s
SHA256-TON: Average speed (15s): 1744.33 Mh/s
New job received: 000000007605a06d Epoch: 475 Difficulty: 559.49M  
Ethash: GPU 1: Found a share of difficulty 0.91G 
Ethash: GPU 1: Share accepted (127 ms) 
Ethash: GPU 1: Found a share of difficulty 0.76G 
Ethash: GPU 1: Share accepted (108 ms) 
New job received: 000000007605a06e Epoch: 475 Difficulty: 559.49M  
SHA256-TON: GPU 1: Found a share of difficulty 131.14G 
SHA256-TON: GPU 1: Share accepted (165 ms) 
SHA256-TON: GPU 1: Found a share of difficulty 498.57G 
SHA256-TON: GPU 1: Share accepted (164 ms) 
New job received: 000000007605a06f Epoch: 475 Difficulty: 559.49M  
Ethash: Average speed (15s): 44.15 Mh/s
SHA256-TON: Average speed (15s): 1746.06 Mh/s
New job received: 000000007605a070 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a071 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a072 Epoch: 0 Difficulty: 559.49M  
GPU 1: Starting DAG generation (normal mode)
GPU 1: DAG build complete 75%
GPU 1: DAG generation completed (611 ms)
GPU 1: DAG verification detected 256 defect segment(s)
GPU 1: DAG repair will be started. This may take a moment.
GPU 1: starting smart DAG repair
Ethash: Average speed (15s): 44.13 Mh/s
SHA256-TON: Average speed (15s): 1745.31 Mh/s
New job received: 000000007605a073 Epoch: 0 Difficulty: 559.49M  
--------------------------------------------- 
Statistics (18:13:27); Uptime: 7h 19m 4s 
Algorithm 1: Ethash 
Connected to: daggerhashimoto.hk.nicehash.com:3353 (119ms latency) 
Algorithm 2: SHA256-TON 
Connected to: wss://eu1.stratum.ton-pool.com/stratum:443 (164ms latency) 

      Name     Speed   Pool      Shares    Best    Eff.    Speed     Pool
                Mh/s   Mh/s      A/S/Hw   Share  Mh/s/W     Mh/s     Mh/s
GPU 1 RTX 3070 44.13  39.78  2531/28/12  376.8G   0.536  1745.22  1554.69
--------------------------- 
Total          44.13  39.78  2531/28/12  376.8G   0.536  1745.22  1554.69

         Shares    Best    Eff.  Power  CCLK  MCLK  Core  Fan  --lhrtune
         A/S/Hw   Share  Mh/s/W      W   MHz   MHz  Temp  Pct           
GPU 1   596/0/0  286.7T  21.184   81.9  1454  8242    37   48        0.2
--------------------------- 
Total   596/0/0  286.7T  21.184   81.9                                  
--------------------------------------------- 
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
New job received: 000000007605a074 Epoch: 0 Difficulty: 559.49M  
Ton job with difficulty 68.72G and giver Ef8JfFUEJhhpRW80_jqD7zzQteH6EBHOzxiOhygRhBdt44YH received.
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
--------------------------------------------- 
Statistics (18:14:27); Uptime: 7h 20m 4s 
Algorithm 1: Ethash 
Connected to: daggerhashimoto.hk.nicehash.com:3353 (119ms latency) 
Algorithm 2: SHA256-TON 
Connected to: wss://eu1.stratum.ton-pool.com/stratum:443 (164ms latency) 

      Name     Speed   Pool      Shares    Best    Eff.  Speed     Pool   Shares
                Mh/s   Mh/s      A/S/Hw   Share  Mh/s/W   Mh/s     Mh/s   A/S/Hw
GPU 1 RTX 3070  0.00  39.69  2531/28/12  376.8G   0.000   0.00  1551.16  596/0/0
--------------------------- 
Total           0.00  39.69  2531/28/12  376.8G   0.000   0.00  1551.16  596/0/0

          Best    Eff.  Power  CCLK  MCLK  Core  Fan  --lhrtune
         Share  Mh/s/W      W   MHz   MHz  Temp  Pct           
GPU 1   286.7T   0.000   47.3  1454  8242    31   44        0.2
--------------------------- 
Total   286.7T   0.000   47.3                                  
--------------------------------------------- 
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
New job received: 000000007605a075 Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a076 Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a077 Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a078 Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a079 Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a07a Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a07b Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a07c Epoch: 0 Difficulty: 559.49M  
New job received: 000000007605a07d Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a07e Epoch: 475 Difficulty: 559.49M  
GPU 1: smart DAG repair done 
GPU 1: DAG verification passed
GPU 1: Starting DAG generation (normal mode)
New extra nonce received: 17eb9b
New target received: 00000007ad35ab75 (Diff 0.130266)
New job received: 000000007605a07f Epoch: 475 Difficulty: 559.49M  
Ethash: Average speed (15s): 0.08 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
New job received: 000000007605a080 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a081 Epoch: 475 Difficulty: 559.49M  
GPU 1: DAG build complete 15%
GPU 1: DAG build complete 31%
New job received: 000000007605a082 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a083 Epoch: 475 Difficulty: 559.49M  
GPU 1: DAG build complete 47%
New job received: 000000007605a084 Epoch: 475 Difficulty: 559.49M  
GPU 1: DAG build complete 63%
New job received: 000000007605a085 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a086 Epoch: 475 Difficulty: 559.49M  
GPU 1: DAG build complete 79%
GPU 1: DAG build complete 95%
GPU 1: DAG generation completed (3627 ms)
GPU 1: DAG verification detected 1206 defect segment(s)
GPU 1: DAG repair will be started. This may take a moment.
GPU 1: starting smart DAG repair
New job received: 000000007605a087 Epoch: 475 Difficulty: 559.49M  
GPU 1: smart DAG repair done 
GPU 1: DAG verification detected 1206 defect segment(s)
GPU 1: DAG repair will be started. This may take a moment.
New job received: 000000007605a088 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a089 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a08a Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a08b Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a08c Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a08d Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a08e Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a08f Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a090 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a091 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a092 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a093 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a094 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a095 Epoch: 475 Difficulty: 559.49M  
Ethash: Average speed (15s): 0.00 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
New job received: 000000007605a096 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a097 Epoch: 475 Difficulty: 559.49M  
New job received: 000000007605a098 Epoch: 475 Difficulty: 559.49M  
New target received: 0000000f5a6b56ea (Diff 0.065133)
New job received: 000000007605a099 Epoch: 475 Difficulty: 279.74M  
New job received: 000000007605a09a Epoch: 475 Difficulty: 279.74M  
Unrecoverable memory error by GPU 1.
Reboot for this GPU required.
Please check your (memory) OC & voltage settings on this card.
New job received: 000000007605a09b Epoch: 475 Difficulty: 279.74M  
Device 1 detected as crashed. 
Closing miner with exit code 42 (--watchdog close).

**Comment by billvvv** [comment]
I've tried any OC and default. the same.

**Comment by billvvv** [comment]
this problem is old , the same as 1.44 1.45 1.46

**Comment by jgonzis** [comment]
Dag Repair is a Premium Advise of a Memory OC PRoblem... or Riser problem... You will always have it. You mine without just adding --disable-dag-verify 

But that will avoid a right loaded DAG for mining.
