### ISSUE TITLE
No data requested

### ISSUE THREAD

**Issue by bendwebs** [Lolliedieb/lolMiner-releases#134]
Trying to connect to any pool (right now trying us1.ethermine.org) ends up generated the following error:

Warning: resolve: The requested name is valid, but no data of the requested type was found
Lost connection to stratum server : or server not reachable.
Trying to connect in 1 second

**Comment by Lolliedieb** [comment]
Seems to be a connection issue ... I can connect well - to both ethermine eu and us servers.
