### ISSUE TITLE
The LHR GPU check is not working stable

### ISSUE THREAD

**Issue by NudeNULL** [Lolliedieb/lolMiner-releases#1341]
I am using the latest version (1.46a) in hive OS for dual mining with TON and for different cards I randomly get the raw calculated hashrate lower than expected with a message like this for a 3080Ti card:

GPU 3: measured GPU raw speed: 65.30MH/s (Memory clock: 10652 mhz) 
GPU 3: does not seem to be LHR - sorry for bothering you

After that it gets stuck with that hashrate, but after a restart of the rig it could work but other cards would get that issue, and so on after every restart I get random cards that have lower calculated hashrate and the lhrtune parameter also stuck at auto like forever, for example for GPU 3:

         Shares    Best    Eff.   Power  CCLK   MCLK  Core  Fan  --lhrtune
         A/S/Hw   Share  Mh/s/W       W   MHz    MHz  Temp  Pct           
GPU 0     1/0/0  762.4G   6.123   115.6  1350   7901    50   75        0.0
GPU 1     2/0/0  607.8G   6.241   216.5  1245  10652    41   75       10.2
GPU 2     2/0/0    3.3T   8.481   269.1  1350  10551    39   75        9.2
GPU 3     2/0/0    8.0T  11.381   290.2  1350  10652    44   84       auto

Let me know please what specific information could help you fix this problem, thanks!

**Comment by jgonzis** [comment]
> I am using the latest version (1.46a) in hive OS for dual mining with TON and for different cards I randomly get the raw calculated hashrate lower than expected with a message like this for a 3080Ti card:
> 
> GPU 3: measured GPU raw speed: 65.30MH/s (Memory clock: 10652 mhz) GPU 3: does not seem to be LHR - sorry for bothering you
> 
> After that it gets stuck with that hashrate, but after a restart of the rig it could work but other cards would get that issue, and so on after every restart I get random cards that have lower calculated hashrate and the lhrtune parameter also stuck at auto like forever, for example for GPU 3:
> 
> ```
>      Shares    Best    Eff.   Power  CCLK   MCLK  Core  Fan  --lhrtune
>      A/S/Hw   Share  Mh/s/W       W   MHz    MHz  Temp  Pct           
> ```
> 
> GPU 0 1/0/0 762.4G 6.123 115.6 1350 7901 50 75 0.0 GPU 1 2/0/0 607.8G 6.241 216.5 1245 10652 41 75 10.2 GPU 2 2/0/0 3.3T 8.481 269.1 1350 10551 39 75 9.2 GPU 3 2/0/0 8.0T 11.381 290.2 1350 10652 44 84 auto
> 
> Let me know please what specific information could help you fix this problem, thanks!

Which Nvidia Driver are you using?. Try to use 470.74. Also try to use Fixed Core that helps... normally 1200 it is a good value. That lower Value could be:

- Nvidia Driver
- Memory Throlling GDDR6X... try wait 1 min fans 100% and run it

**Comment by NudeNULL** [comment]
The problem was in NVIDIA drivers, I had some older version (460..) and didn't knew that Hive OS is not updating them automatically)

**Comment by jgonzis** [comment]
Thx for the Feedback
