### ISSUE TITLE
cards fall off

### ISSUE THREAD

**Issue by japone777** [Lolliedieb/lolMiner-releases#1345]
You didn't help me, you just deleted my topic, I just have nothing falling off in Nbminer when mining ether. On Lol maine eth+ ton, 1070ti falls off...are you planning to release a new version with a fix of these bugs?

**Comment by japone777** [comment]
I use another miner and it is stable and the profitability is the same, this is a problem with your miner

**Comment by japone777** [comment]
> > Вы мне не помогли, просто удалили мою тему, просто у меня в Nbminer ничего не отваливается при майнинге эфира. На Lol maine eth+ ton отваливается 1070ti...вы планируете выпустить новую версию с фиксом этих багов?
> 
> Я закрываю, но вы все равно можете опубликовать проблему 1070ti, как говорится. Экспериментальный PASCAL, у вашей карты могут быть проблемы, другой майнер не делает eth + ton, так что вы не знаете, стабильно ли там тоже. Падение - это не проблема шахты, это аппаратная проблема, проверьте стояк или мощность блока питания...

Another miner mines perfectly without disconnections, this is not a problem with my pascal, or seasonic power supplies. This is the problem of your miner, he disables my cards
![Снимок7676](https://user-images.githubusercontent.com/99234250/155879063-3c8cc00a-9eba-4bd0-ae46-45d6805538ef.JPG)

**Comment by japone777** [comment]
> > Вы мне не помогли, просто удалили мою тему, просто у меня в Nbminer ничего не отваливается при майнинге эфира. На Lol maine eth+ ton отваливается 1070ti...вы планируете выпустить новую версию с фиксом этих багов?
> 
> Я закрываю, но вы все равно можете опубликовать проблему 1070ti, как говорится. Экспериментальный PASCAL, у вашей карты могут быть проблемы, другой майнер не делает eth + ton, так что вы не знаете, стабильно ли там тоже. Падение - это не проблема шахты, это аппаратная проблема, проверьте стояк или мощность блока питания...

я не буду писать название майнера, но это проблема вашем майнере,я мучался с этим 3 дня.пофкиксите это пожалуйста

**Comment by jgonzis** [comment]
> 

With Pascal as we said, is experimental. I haven't seen any photo of your OC or similar to search where is the hardware problem. But honestly with the 1070ti, is not profitable that dual mining the lost of ETH performance doesn't compensate. Better to have 30Mhs with 1070ti at 125W than 25Mhs and 100Mhs of TON. But the miner has to decide.

**Comment by japone777** [comment]
> > 
> 
> Паскаль, как мы сказали, экспериментальный. Я не видел ни одной фотографии вашей ОС или похожей на поиск, где проблема с оборудованием. Но, честно говоря, с 1070ti не выгодно, чтобы двойной майнинг не компенсировал потерю производительности ETH. Лучше иметь 30Mhs с 1070ti при 125W, чем 25Mhs и 100Mhs TON. Но майнер должен решить.

это неразогнанные,я сейчас тестирую на стабильность и уже сутки все стабильно, чуть позже попробую разгон..
