### ISSUE TITLE
Dual mine eth+ton inconsistent

### ISSUE THREAD

**Issue by igormursa** [Lolliedieb/lolMiner-releases#1346]
Normally I would get 75 Mh/s on eth and around 2500 mh/s on TON but if I restart the miner it's a nightmere to bring it back to 2500Mh/s on ton
I don't change anything between runs so settings are not an issue
Auto lhr tune never stops autotuning, config tunes that worked stable in the past now dont work

```
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
```

I see a lot of Ton job with ... but the speed is always 0
```
Ton job with difficulty 274.88G and giver Ef8JfFUEJhhpRW80_jqD7zzQteH6EBHOzxiOhygRhBdt44YH received.
New job received: 0x28def2 Epoch: 476 Difficulty: 4.30G
New job received: 0x702404 Epoch: 476 Difficulty: 4.30G
Ton job with difficulty 274.88G and giver Ef-FV4QTxLl-7Ct3E6MqOtMt-RGXMxi27g4I645lw6MTWg0f received.
New job received: 0x52689d Epoch: 476 Difficulty: 4.30G
Ton job with difficulty 274.88G and giver Ef8JfFUEJhhpRW80_jqD7zzQteH6EBHOzxiOhygRhBdt44YH received.
New job received: 0xa86979 Epoch: 476 Difficulty: 4.30G
Ethash: Average speed (15s): 75.32 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s
```

System: 3080Ti Running on version 1.46a 511.79 drivers and Windows 10

Update: after half a day of restarting the miner I finally got it running at ETH 70-73 Mh/s and TON 2200 Mh/s

**Comment by jgonzis** [comment]
Please follow the Windoss Guide... 1st of all put driver 472.12..

**Comment by mooleshacat** [comment]
> Please follow the Windoss Guide... 1st of all put driver 472.12..

That is not a proper solution. You are training people to use out of date software which is a terrible dis-service to the internet. You need to update your software to work with the latest drivers.

**Comment by jgonzis** [comment]
> > Please follow the Windoss Guide... 1st of all put driver 472.12..
> 
> That is not a proper solution. You are training people to use out of date software which is a terrible dis-service to the internet. You need to update your software to work with the latest drivers.

From 26 of Feb it has changed a lot :-)... at this time it was 100%... now the driver work with 512.xx not the last one that Nvidia has blocked it another time
