### ISSUE TITLE
lhr lock hit no stop while dual mining eth+ton

### ISSUE THREAD

**Issue by dardares** [Lolliedieb/lolMiner-releases#1348]
Hi,

This week i've added an RTX 3070ti to one of my rig. I have already 3 other LHR card, the 3060ti, without any issues.

While dual mining eth+ton, my card alway hit the lhr lock, so stop mining, try another lhrtune value, restart mining, then hit again, and so on, no stop. I've been let it run for many hours, and the miner still tuning lhr value.

No any of my other lhr card do this when dual mining. He do for few minut after started mining, then stay stable. If i don't use dual mining, and mining only eth, my 3070ti don't have any issues., and give me 64mh stable.

I have try whit the 1.45,1.46 and 1.46a version, and the same issues occur on every version. This is a big issue for me, because the card pause mining everytime. I'm using hive os latest version, but i have also try it on another rig whit windows, the same issues occur whit this card only.

Thank for your help!

**Comment by jgonzis** [comment]
Could you show which Nvidia Drivers do you have?.

It also seems that  3070ti could have Thermal Memory Throlling. Could you try with lower Core and with fan at 100%. 

Many thanks in advance

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/23410370/155860862-4ce9a5f8-8281-45b7-8108-4c4474d23986.png) Hi, It seem more stable whit a less agressive overclock on the memory. My fan is alway at 100%. Core stay stable between 60 and 65 degree celsius. I would eventually think about replacing memory cooling pad, but since the card is new, i can dissassemble it for now, for the warranty. Hive don't show memory temp, but on windows the temperature of the memory is at 96.
> 
> Thank

It is possible to try the Nvidia 470.74?...

If you want to see if thermal Memory is present  run:

nvidia-smi -q -d PERFORMANCE | grep "SW Power Cap"

You can have interesting information... if lower OC helps, make me think more that is thermal Throlling

**Comment by ViperGuyMike** [comment]
I have the same issue, and only with one of my 3070ti cards. My 1080's, 3060ti's, 3070 non-lhr, other 3070ti, 3080ti, and 3090 are all fine. Just this one 3070ti loops in lhr tuning indefinitely. I believe that every person I have seen with this complaint is having the issue with a 3070ti. I am beginning to wonder if it is just one model of 3070ti having this issue, which would explain why not many people have the issue. I have reset my OC's to factory, and all kinds of settings from mild to wild with no change. I always keep my fans at 100% as well. For now, I just have that card set to mine TON only.

**Comment by jgonzis** [comment]
> I have the same issue, and only with one of my 3070ti cards. My 1080's, 3060ti's, 3070 non-lhr, other 3070ti, 3080ti, and 3090 are all fine. Just this one 3070ti loops in lhr tuning indefinitely. I believe that every person I have seen with this complaint is having the issue with a 3070ti. I am beginning to wonder if it is just one model of 3070ti having this issue, which would explain why not many people have the issue. I have reset my OC's to factory, and all kinds of settings from mild to wild with no change. I always keep my fans at 100% as well. For now, I just have that card set to mine TON only.

Have you try to find if it is a Memory Temp Problem?
Could be also a Riser problem..

I have seen that loop also in a FTW3 EVGA 3070ti, and it was a bad pad installation from EVGA.

That constant loop is normally memory Throlling. With TON no memory use so that means what no problem

**Comment by BLADLust1** [comment]
Hello, I have the same issue on rig with 3x3080 LHR +1x1660. On another PC where only one 3080 LHR -all ok.
Problem only on 1.46(a) version. On 1.45 all is ok, no problems, but want more hashes on TON.

**Comment by jgonzis** [comment]
> Hello, I have the same issue on rig with 3x3080 LHR +1x1660. On another PC where only one 3080 LHR -all ok. Problem only on 1.46(a) version. On 1.45 all is ok, no problems, but want more hashes on TON.

Problem of 1.46a is the extra 20% is more heat too and it could be your gpus where near the limit i  1.45... make test with fans 100%... to be sure about that.

**Comment by BLADLust1** [comment]
> > Hello, I have the same issue on rig with 3x3080 LHR +1x1660. On another PC where only one 3080 LHR -all ok. Problem only on 1.46(a) version. On 1.45 all is ok, no problems, but want more hashes on TON.
> 
> Problem of 1.46a is the extra 20% is more heat too and it could be your gpus where near the limit i 1.45... make test with fans 100%... to be sure about that.

Coolers on 100%, Im decrease memory and core by 10% and nothing changes, always lock LHR

**Comment by jgonzis** [comment]
> > > Hello, I have the same issue on rig with 3x3080 LHR +1x1660. On another PC where only one 3080 LHR -all ok. Problem only on 1.46(a) version. On 1.45 all is ok, no problems, but want more hashes on TON.
> > 
> > 
> > Problem of 1.46a is the extra 20% is more heat too and it could be your gpus where near the limit i 1.45... make test with fans 100%... to be sure about that.
> 
> Coolers on 100%, Im decrease memory and core by 10% and nothing changes, always lock LHR

Try to show with photo or something...

When ever reporting an issue, please always include
- the miner version and the algorithms you are running
- the GPU types involved
- the operations system
- the driver version if known
Additionally: any output from the miner, aka its console output is extremely valuable for us to get an idea why something might not work, just for example the tuning status or crash message or a pool connection issue. Therefore when ever possible try to help us out by providing this - it will improve the likelihood for us to help you with your problem or ease us finding the bug - if there is one - that you suffer from a lot.
Thanks!
