### ISSUE TITLE
1.46a (Windows). TON now working on AMD RX5700

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1349]
Command line used:

`2022-02-26 15:59:58 VERBOSE: Bin\lolMiner-v1.46a\lolminer.exe --algo TON --pool wss://eu1.stratum.ton-pool.com/stratum:443 --user ############### --pass ############,c=TON --log off --apiport 4001 --shortstats 7 --longstats 30 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 9:0`

Connecting to pool...
Ton pool connection mode: Ton stratum (developed by icemining.ca) (--ton-mode 6)
DNS over HTTPS resolve succeeded
Connected to wss://eu1.stratum.ton-pool.com/stratum(104.26.9.92):443  (TLS enabled)
TLS Handshake success
Websocket handshare done with pool wss://eu1.stratum.ton-pool.com/stratum
Authorized worker: ###############################
Ton job with difficulty 68.72G and giver Ef-FV4QTxLl-7Ct3E6MqOtMt-RGXMxi27g4I645lw6MTWg0f received.
Start Mining...
**Device 1 detected as crashed.**
Closing miner with exit code 42 (--watchdog close).

Dual mining ETH + TON works fine.
Also GTX 1660 Super & RX580 mine TON (single and dual algo mode) work fine.

**Comment by jgonzis** [comment]
That seems that the rx580 needs some extra core Voltage... That message is normally for that
