### ISSUE TITLE
Frequent crashing - Error During Mining: Out of Resources

### ISSUE THREAD

**Issue by gtf6** [Lolliedieb/lolMiner-releases#135]
Hi,

I am regularly experiencing the following error:

GPU 0: Error during mining: Out of resources 
GPU 0: will be stopped.

This will happen randomly, from 5 minutes to 36 hours after starting lolminer.

This happens both when overclocked, and at stock. (2070 Super)

The worst bit is that lolminer just sits there, reporting a 0 hashrate. 

No idea what the cause is. Does anyone know of a way to make the miner restart itself upon an error occurring?  That would solve mine, and many other people's issues.

**Comment by Lolliedieb** [comment]
The miner has some issues at the moment that are Nvidia related when mining while the same GPU does screen output ...
In case this is inevitable I would suggest to use an other software in case this is inevitable (e.g. by putting the card into a rig that uses a different way for its screen output).

**Comment by gtf6** [comment]
Thanks for the response @Lolliedieb 

I believe this is incorrect. The error still occurs:
- When I use the onboard CPU graphics for the display
- Physically disconnect the display from the PC
- Add a second card (GTX 980ti) which is not connected to the display (both worker GPUs crash at different times)

In my case, at least, it does not appear to be connected to using the same GPU that is running screen output.

if mh/s = 0 > 60 seconds, then restart lolminer

Could something like that be coded in?

**Comment by darmattermatters** [comment]
Hi there
I have 2 2080ti's and having the same exact issue.

Please advise.

Thanks!

**Comment by yipengyou** [comment]
Did you guys have a fix to the issue? Is it a hardware issue with the card itself?

**Comment by gtf6** [comment]
> Did you guys have a fix to the issue? Is it a hardware issue with the card itself?

I still have the same issue, as do two of my mates who also use Nvidia cards.

Seems that lolminer is just not well coded for nvidia

**Comment by yipengyou** [comment]
How long have the cards been mining for? What is the OC on them?
