### ISSUE TITLE
RX580 series with no hash rate for TON on dual mine with ETH

### ISSUE THREAD

**Issue by GauchoBois** [Lolliedieb/lolMiner-releases#1350]
Hi, I need help with my rx580s... I'm running lolminer in plain Ubuntu 20.04.2 LTS in dual mining ETH+TON, and lolMiner_v1.46a_Lin64.tar.gz.
It works like a charm in the rigs with rx5000 series as well as rtx3000s, but no hash rate for TON in any rx580. The cards are recognized and it does mine ETH but not TON always showing 0.0 Mh/s, like this:

```
Device 0: 
    Name:    Radeon RX 580 Series 
    Address: 4:0 
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8146 MByte (8127 MByte free) 
    Max epoch (approx): 889 
    Active:  true (Selected Algorithm: ETHash OpenCL) 
Device 1: 
    Name:    Radeon RX 580 Series 
    Address: 5:0 
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8146 MByte (8127 MByte free) 
    Max epoch (approx): 889 
    Active:  true (Selected Algorithm: ETHash OpenCL) 
Device 2: 
    Name:    AMD Radeon RX 580 2048SP 
    Address: 7:0 
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8146 MByte (8127 MByte free) 
    Max epoch (approx): 889 
    Active:  true (Selected Algorithm: ETHash OpenCL) 
Device 3: 
    Name:    Radeon RX 580 Series 
    Address: 8:0 
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  7941 MByte (7922 MByte free) 
    Max epoch (approx): 864 
    Active:  true (Selected Algorithm: ETHash OpenCL) 

Connecting to pool... 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve succeeded 
DNS over HTTPS resolve succeeded 
Connected to eth-us-east1.nanopool.org(144.217.14.109):9999  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
```

as an example of the output:

```
Ethash: Average speed (15s): 21.59 Mh/s | 20.20 Mh/s | 27.76 Mh/s | 22.63 Mh/s Total: 92.18 Mh/s
SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
```
and they keep throwing 0.00 until any of them crashes.

AMD driver is: amdgpu-pro-20.20-1098277-ubuntu-20.04.

Any parameter to config to make them mine? Thanks a lot in advance for any help.

**Comment by jgonzis** [comment]
> Hi, I need help with my rx580s... I'm running lolminer in plain Ubuntu 20.04.2 LTS in dual mining ETH+TON, and lolMiner_v1.46a_Lin64.tar.gz. It works like a charm in the rigs with rx5000 series as well as rtx3000s, but no hash rate for TON in any rx580. The cards are recognized and it does mine ETH but not TON always showing 0.0 Mh/s, like this:
> 
> ```
> Device 0: 
>     Name:    Radeon RX 580 Series 
>     Address: 4:0 
>     Vendor:  Advanced Micro Devices (AMD)
>     Drivers: OpenCL
>     Memory:  8146 MByte (8127 MByte free) 
>     Max epoch (approx): 889 
>     Active:  true (Selected Algorithm: ETHash OpenCL) 
> Device 1: 
>     Name:    Radeon RX 580 Series 
>     Address: 5:0 
>     Vendor:  Advanced Micro Devices (AMD)
>     Drivers: OpenCL
>     Memory:  8146 MByte (8127 MByte free) 
>     Max epoch (approx): 889 
>     Active:  true (Selected Algorithm: ETHash OpenCL) 
> Device 2: 
>     Name:    AMD Radeon RX 580 2048SP 
>     Address: 7:0 
>     Vendor:  Advanced Micro Devices (AMD)
>     Drivers: OpenCL
>     Memory:  8146 MByte (8127 MByte free) 
>     Max epoch (approx): 889 
>     Active:  true (Selected Algorithm: ETHash OpenCL) 
> Device 3: 
>     Name:    Radeon RX 580 Series 
>     Address: 8:0 
>     Vendor:  Advanced Micro Devices (AMD)
>     Drivers: OpenCL
>     Memory:  7941 MByte (7922 MByte free) 
>     Max epoch (approx): 864 
>     Active:  true (Selected Algorithm: ETHash OpenCL) 
> 
> Connecting to pool... 
> Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
> DNS over HTTPS resolve succeeded 
> DNS over HTTPS resolve succeeded 
> Connected to eth-us-east1.nanopool.org(144.217.14.109):9999  (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> https://server1.whalestonpool.com: Address is valid
> https://server1.whalestonpool.com: Address is registered
> ```
> 
> as an example of the output:
> 
> ```
> Ethash: Average speed (15s): 21.59 Mh/s | 20.20 Mh/s | 27.76 Mh/s | 22.63 Mh/s Total: 92.18 Mh/s
> SHA256-TON: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
> ```
> 
> and they keep throwing 0.00 until any of them crashes.
> 
> AMD driver is: amdgpu-pro-20.20-1098277-ubuntu-20.04.
> 
> Any parameter to config to make them mine? Thanks a lot in advance for any help.

Which AMD Driver do you have in the rig?. It need 20.40 to work properly.

**Comment by GauchoBois** [comment]
Genius!!! it worked like a charm, thanks a lot!!!!

Just for the record: 
downloaded the driver from here: https://www.amd.com/es/support/kb/release-notes/rn-amdgpu-unified-linux-20-40
then purged the previous one with: 
`sudo amdgpu-pro uninstall
`
installed the new one with:
```
tar -xvf amdgpu-pro-20.40-1147286-ubuntu-20.04.tar.xz
cd amdgpu-pro-20.40-1147286-ubuntu-20.04/
sudo ./amdgpu-pro-install --opencl=legacy -y
```
not sure if the --opencl=legacy is required but I just do it since long ago by default... any comments on that to enlighten it would be perfect.

Cheers.

**Comment by jgonzis** [comment]
> Genius!!! it worked like a charm, thanks a lot!!!!
> 
> Just for the record: downloaded the driver from here: https://www.amd.com/es/support/kb/release-notes/rn-amdgpu-unified-linux-20-40 then purged the previous one with: `sudo amdgpu-pro uninstall ` installed the new one with:
> 
> ```
> tar -xvf amdgpu-pro-20.40-1147286-ubuntu-20.04.tar.xz
> cd amdgpu-pro-20.40-1147286-ubuntu-20.04/
> sudo ./amdgpu-pro-install --opencl=legacy -y
> ```
> 
> not sure if the --opencl=legacy is required but I just do it since long ago by default... any comments on that to enlighten it would be perfect.
> 
> Cheers.

Many thanks for the feedback
