### ISSUE TITLE
P106-100/1060 6gb ETH/TON or ETH/ALPH  Erratic  Hash Rates 

### ISSUE THREAD

**Issue by JRTHEELECTRONICGUY** [Lolliedieb/lolMiner-releases#1352]
On the P 100 I can’t even get it to run

But the 1060s will run

But after clocks levels out one card stays around 140 MHZ rest go down to around 10 MH ALPH or TON and 20 ish MH ETH

One rig is 8 1060s Second Rig is 8 p106-100

Please help

**Comment by JRTHEELECTRONICGUY** [comment]
Is there any suggestions to get the 1060s working on dual mining

or the p106-100

**Comment by jgonzis** [comment]
> On the P 100 I can’t even get it to run
> 
> But the 1060s will run
> 
> But after clocks levels out one card stays around 140 MHZ rest go down to around 10 MH ALPH or TON and 20 ish MH ETH
> 
> One rig is 8 1060s Second Rig is 8 p106-100
> 
> Please help

For Pascal the Dual Mining Works, but not really too much profit. You will need a lot of Power to get some result or add the parameter --maxdualimpact 10 reducing your ETH but increasing TON
