### ISSUE TITLE
1.46a ETH+TON hiveos amd gpu 0 hashrate after few hour

### ISSUE THREAD

**Issue by EricKeong** [Lolliedieb/lolMiner-releases#1354]
Try-ed 1.43, 1.44, 1.45, 1.46a amd gpu will suddently 0 hashrate, auto restart miner a time aday or few time aday(hiveos watchdog active)..
[Watchdog  restart miner Amd 0 hashrate hiveos log.txt](https://github.com/Lolliedieb/lolMiner-releases/files/8148415/Watchdog.restart.miner.Amd.0.hashrate.hiveos.log.txt)

**Comment by jgonzis** [comment]
That seems to be a too much undervolt voltage. Because there are Watts but stops mining. Could you please increase in 25mV the voltage?

**Comment by EricKeong** [comment]
Ok thanks, will try adding voltage to test out again.

**Comment by korayuygur** [comment]
This happened to me when I was configuring my 2 rigs. One is 4x3080 non lhr and other one was 5x3080ti.
Rigs mined few hours and then 0 hash. I've tried alot of settings but again 0 hash at random timeframes. What I've found was a minor stability issue which affected in the long run.

This is how I fixed.
1. Use 472.12 driver.
2. Core lock lowest as possible.
3. This is the crucial part. 101% power. If you have space for more power at afterburner just increase it to 101%. If not then leave it as 100%. I guess the gpus which have room for rising the power above 100% are the cards which their full powers were stock reduced. So 100% in afterburner is not 100% of that gpu in reality. Thats why they cause problems when they demand the power which is not enough.
4. Experiment the memory delta. If you normally mine eth with 1600, first decrease it to 1500 etc. Hash wont change much somehow. But if its higher, it may produce stability problem.

Now both of the rigs are mining without problems and hashes are great. Try that you'll see it will be stable.

**Comment by korayuygur** [comment]
It happened again after 2 hours. My problematic gpus has max 110% power limit it afterburner. So I've rised to 105% now its stable. So power limit rising is the best place to sort out this issue imo. gpu draws what is needed, you wont see some crazy watts there.
