### ISSUE TITLE
GPU is not lhr, sorry for bothering you.

### ISSUE THREAD

**Issue by OlivierGaland** [Lolliedieb/lolMiner-releases#1355]
Hello,

I have a rig with 4 x 3060Ti using ETH+TON dual. All are LHR (some v1 , some v2) on hiveos

Using previously 1.43 lolminer, I noticed sometimes that 1 or 2 random gpu were hitting only 29 Mh/s during the auto-tune process instead of 42 Mh/s. They are then stuck to 29 Mh/s all the time.
My workaround was using the watchdog with minimal hash limit to restart the miner, as the issue is random, after a few restart it was finally hitting 4 x 42Mh/s.

I tried today the 1.46a lolminer and had again the issue, with a supplemntary information in log somewhat like : "GPU is not lhr, sorry for bothering you", I guess it is a clue to understand what is happening on your side.

My workaround of restarting the miner still works, but I was wondering if it was possible to implement a flag to force to declare a GPU manually as LHR (expecting it will hit 42 Mh/s in my case).

Anyway thanks for the good job on your product.
Olivier, France.

**Comment by josuetenista** [comment]
Facing the same issue

**Comment by jgonzis** [comment]
> Hello,
> 
> I have a rig with 4 x 3060Ti using ETH+TON dual. All are LHR (some v1 , some v2) on hiveos
> 
> Using previously 1.43 lolminer, I noticed sometimes that 1 or 2 random gpu were hitting only 29 Mh/s during the auto-tune process instead of 42 Mh/s. They are then stuck to 29 Mh/s all the time. My workaround was using the watchdog with minimal hash limit to restart the miner, as the issue is random, after a few restart it was finally hitting 4 x 42Mh/s.
> 
> I tried today the 1.46a lolminer and had again the issue, with a supplemntary information in log somewhat like : "GPU is not lhr, sorry for bothering you", I guess it is a clue to understand what is happening on your side.
> 
> My workaround of restarting the miner still works, but I was wondering if it was possible to implement a flag to force to declare a GPU manually as LHR (expecting it will hit 42 Mh/s in my case).
> 
> Anyway thanks for the good job on your product. Olivier, France.

Which Nvidia Driver are you using?... that seems that is not 470 driver....

**Comment by jgonzis** [comment]
> Hello,
> 
> You are right, i'm using on this rig 460 driver.
> 
> I will update and check if the issue still occurs
> 
> Many thanks for your feedback. Olivier
> 
> [Edit] Confirmed issue was coming from using driver 460, I did several restart of my miner using 470 and did not had the issue anymore.

Many thanks for the feedback. Enjoy mining
