### ISSUE TITLE
1.46.a ETH+TON (win10) lhr  hashrate 0 but shares accepted

### ISSUE THREAD

**Issue by MartynIden** [Lolliedieb/lolMiner-releases#1356]
1.46.a ETH+TON (win10) lhr card 3060
after completing auto lhr tune visible worker performance 0 (hashrate 0 in statistics) same situation on API
 but shares accepted on both protocols
power consumtion is full

**Comment by jgonzis** [comment]
> 1.46.a ETH+TON (win10) lhr card 3060 after completing auto lhr tune visible worker performance 0 (hashrate 0 in statistics) same situation on API but shares accepted on both protocols power consumtion is full

Which Driver are you using?. 

Could you share please a Photo too?
