### ISSUE TITLE
Ubuntu 20.04 - mine_etc.sh Active: false

### ISSUE THREAD

**Issue by buckinbulls** [Lolliedieb/lolMiner-releases#1357]
Trying to mine but continuing to hit a block on mine_etc.sh & mine_cortex.sh

using
Ubuntu 20.04.4 LTS
Lolminer v1.46a
Radeon RX 550

Does anything jump out on what might be causing the issue?

Setup Miner... 
OpenCL driver detected.
Number of OpenCL supported GPUs: 1 
No Cuda driver or GPUs detected. 
Device 0: 
    Name:    Radeon RX550/550 Series 
    Address: 1:0 
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  4096 MByte (4032 MByte free) 
    Active:  false (Unsupported device or driver version.) 

$ glxinfo | grep -iE 'vendor:|device:|version:'
GLX version: 1.4

$ lsmod | grep amd
amdgpu               7028736  31
amd_iommu_v2           20480  1 amdgpu
amdttm                 69632  1 amdgpu
amd_sched              36864  1 amdgpu
amdkcl                 28672  3 amd_sched,amdttm,amdgpu
drm_kms_helper        184320  1 amdgpu
drm                   491520  13 drm_kms_helper,amdttm,amdgpu,amdkcl
i2c_algo_bit           16384  1 amdgpu

$ dpkg -l xserver-xorg-video-amdgpu
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version      Architecture Description
+++-=========================-============-============-=======================>
ii  xserver-xorg-video-amdgpu 19.1.0-1     amd64        X.Org X server -- AMDGP>
lines 1-6/6 (END)

$ inxi -Fxz
Graphics:
  Device-1: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] 
  driver: amdgpu v: 5.13.11.21.50 bus ID: 01:00.0 
  Display: x11 server: X.Org 1.20.13 driver: amdgpu 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Radeon RX550/550 Series 
  v: 4.6.14800 Core Profile Context 21.50 direct render: Yes

**Comment by pdieppa** [comment]
Have you tried AMD drivers version 20.40?

**Comment by buckinbulls** [comment]
thanks, that is the package I thought I installed from https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-40 however, its looking like it might have been a different one ... ugh ... will try again.

**Comment by buckinbulls** [comment]
downloaded package and looks like I already had it

~/Downloads/amd-2040$ sudo apt-get install amdgpu-install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
amdgpu-install **is already the newest version (21.50.50000-1376259).**
The following packages were automatically installed and are no longer required:
  ca-certificates-java java-common libaccinj64-10.1 libatk-wrapper-java
  libatk-wrapper-java-jni libcudart10.1 libcufft10 libcufftw10 libcupti-dev
  libcupti-doc libcupti10.1 libcurand10 libcusolver10 libcusolvermg10
  libcusparse10 libegl-dev libgl1-mesa-dev libgles-dev libgles1 libglvnd-dev
  libid3-3.8.3v5 libid3tag0 libjs-underscore libncurses5 libnppc10 libnppial10
  libnppicc10 libnppicom10 libnppidei10 libnppif10 libnppig10 libnppim10
  libnppist10 libnppisu10 libnppitc10 libnpps10 libnvgraph10 libnvjpeg10
  libnvrtc10.1 libnvtoolsext1 libnvvm3 libopengl-dev libopusfile0
  libthrust-dev libvdpau-dev node-html5shiv ocl-icd-opencl-dev
  opencl-c-headers openjdk-8-jre openjdk-8-jre-headless
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

**Comment by blackmennewstyle** [comment]
> downloaded package and looks like I already had it
> 
> ~/Downloads/amd-2040$ sudo apt-get install amdgpu-install Reading package lists... Done Building dependency tree Reading state information... Done amdgpu-install **is already the newest version (21.50.50000-1376259).** The following packages were automatically installed and are no longer required: ca-certificates-java java-common libaccinj64-10.1 libatk-wrapper-java libatk-wrapper-java-jni libcudart10.1 libcufft10 libcufftw10 libcupti-dev libcupti-doc libcupti10.1 libcurand10 libcusolver10 libcusolvermg10 libcusparse10 libegl-dev libgl1-mesa-dev libgles-dev libgles1 libglvnd-dev libid3-3.8.3v5 libid3tag0 libjs-underscore libncurses5 libnppc10 libnppial10 libnppicc10 libnppicom10 libnppidei10 libnppif10 libnppig10 libnppim10 libnppist10 libnppisu10 libnppitc10 libnpps10 libnvgraph10 libnvjpeg10 libnvrtc10.1 libnvtoolsext1 libnvvm3 libopengl-dev libopusfile0 libthrust-dev libvdpau-dev node-html5shiv ocl-icd-opencl-dev opencl-c-headers openjdk-8-jre openjdk-8-jre-headless Use 'sudo apt autoremove' to remove them. 0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

According to the command lines, you are using **amdgpu-install is already the newest version (21.50.50000-1376259).**, which is **21.50**
Someone asked you to use 20.40. Be aware, on GNU/Linux Ubuntu, the drivers 20.40 does not work kernel > 5.4.54, your kernel is 5.13.11 currently. If you want to use edge AMD drivers.

**Comment by buckinbulls** [comment]
was able to finally load the 20.40 drivers and LOL is now up and running, thanks for the tips.

**Comment by pdieppa** [comment]
You are welcome
