### ISSUE TITLE
No Win 64 Build of lolMiner 1.19

### ISSUE THREAD

**Issue by davidbuckleyni** [Lolliedieb/lolMiner-releases#136]
While checking from a guide i see their is no win 64 version of lolMiner 1.19

**Comment by UselessGuru** [comment]
As written '(Windows build will follow within 24 hrs)'

**Comment by Lolliedieb** [comment]
Also the changes for Windows are rather minimal ... because the most important thing is the zombie tune thing which is mostly for Linux.
