### ISSUE TITLE
Lack of Watchdog response to NVIDIA hang GPUs

### ISSUE THREAD

**Issue by SickoCrypto** [Lolliedieb/lolMiner-releases#1360]
Hi Guys, 

I have an issue with my miner, lolMiner v1.45, the miner keeps running even if hash rate drops to 0 Mh/s. This is a problem since there is no alarm or watchdog that can prevent this issue from happing, the only solution I found is to restart the miner. 

Is it possible to put a Watchdog option in case any GPUs go to 0 Mh/s to reboot or restart the miner? this problem I've only seen on NVIDIA GPUs.

**Comment by jgonzis** [comment]
We have a bat file with a watchdog. In:

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer)

You can also use MMPOS Agent for Windows that includes also Watchdog and tuning functionss

**Comment by SickoCrypto** [comment]
Thanks for sharing mate ! However I’m using SMOS which is a Linux system, any solution for this one ?

**Comment by jgonzis** [comment]
> Thanks for sharing mate ! However I’m using SMOS which is a Linux system, any solution for this one ?

SMOS that's good, better than Windows. Try to use 1.46a that has the reconnection option updated that should sure help you.

**Comment by SickoCrypto** [comment]
> > Thanks for sharing mate ! However I’m using SMOS which is a Linux system, any solution for this one ?
> 
> SMOS that's good, better than Windows. Try to use 1.46a that has the reconnection option updated that should sure help you.

Do you mean this “  --watchdogscript exit reboot.sh” is it the correct argument ?

**Comment by jgonzis** [comment]
> > > Thanks for sharing mate ! However I’m using SMOS which is a Linux system, any solution for this one ?
> > 
> > 
> > SMOS that's good, better than Windows. Try to use 1.46a that has the reconnection option updated that should sure help you.
> 
> Do you mean this “ --watchdogscript exit reboot.sh” is it the correct argument ?

I think SMOS has also a watchdog to reboot in case is 0... Sometime that happens for a Crash GPU... it is any crash?. Or in 1.45 it was a problem with the reconnnection..
