### ISSUE TITLE
which restful api I can get the miner data?

### ISSUE THREAD

**Issue by rocqina** [Lolliedieb/lolMiner-releases#1361]
like this http://ip:port/summary ?

Is there other apis?

**Comment by jgonzis** [comment]
> like this http://ip:port/summary ?
> 
> Is there other apis?

Yes 
http://ip:port/gui

Remember to active the --apiport xxxx value, HiveOS is 44444, 5500 Raveos, 4028 MMPOS

**Comment by rocqina** [comment]
Thanks！
