### ISSUE TITLE
No such node (MINER.ALGO)

### ISSUE THREAD

**Issue by zer0012** [Lolliedieb/lolMiner-releases#1362]
Help！（probably very stupid question）

Mining ETH or Ton alone with lolminer works fine

But ETH and Ton together don't work

I used the latest version of the HiveOS image

![image](https://user-images.githubusercontent.com/28901119/156209292-50cc1e2a-df5e-421e-8b72-cc4f421734d9.png)

![image](https://user-images.githubusercontent.com/28901119/156209215-13e897da-5e91-4476-8bb5-2f2d04e90e69.png)

![O0 Q$DU@W8_73I8@F$JRW1R](https://user-images.githubusercontent.com/28901119/156208806-c3ac0dea-a5c8-43c8-9bb6-caeaa5a7d674.png)

`    hive-miners-lolminer-1.46
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 6674 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://download.hiveos.farm/repo/binary  hive-miners-lolminer-1.46 0.6-01 [6674 kB]
Fetched 6674 kB in 6s (1092 kB/s)
Selecting previously unselected package hive-miners-lolminer-1.46.
(Reading database ... 89271 files and directories currently installed.)
Preparing to unpack .../hive-miners-lolminer-1.46_0.6-01_amd64.deb ...
Unpacking hive-miners-lolminer-1.46 (0.6-01) ...
Setting up hive-miners-lolminer-1.46 (0.6-01) ...

Trying to release TIME_WAIT sockets:
tcp        0      0 127.0.0.1:44444         127.0.0.1:49878         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:49872         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:49882         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:49868         TIME_WAIT  
tcp        0      0 127.0.0.1:44444         127.0.0.1:49886         TIME_WAIT  

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

Skipping miner log rotation due to execution time < 30sec

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  No such node (MINER.ALGO)

lolminer exited (exitcode=0), waiting to cooldown a bit

> Miner screen is running`

**Comment by vocals100** [comment]
Hi Zer, could you solve this?
