### ISSUE TITLE
lolMiner 1.46a - RX 570 4GB - ERGO mining - Constant random crashes - Using older version of lolMiner: no issue

### ISSUE THREAD

**Issue by blackmennewstyle** [Lolliedieb/lolMiner-releases#1363]
Hello,

I'm facing some weird issue when using `LolMiner 1.46a`, i get constantly this error:
```
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
--------------------------------------------- 
Statistics (01:13:36); Uptime: 0h 5m 0s 
The api is active on port 4445
Mining: Autolykos V2 (Ergo) 
Connected to: stratum-ergo.flypool.org:3443 (17ms latency) 

      Name   Speed   Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Fan
              Mh/s   Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Pct
GPU 0 RX 570 63.19  26.67     2/0  12.9G   0.928   67.6  1200  1860    41   47
--------------------------- 
Total        63.19  26.67     2/0  12.9G   0.928   67.6                       
--------------------------------------------- 
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
--------------------------------------------- 
Statistics (01:14:36); Uptime: 0h 6m 0s 
The api is active on port 4445
Mining: Autolykos V2 (Ergo) 
Connected to: stratum-ergo.flypool.org:3443 (17ms latency) 

      Name   Speed   Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Fan
              Mh/s   Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Pct
GPU 0 RX 570 63.19  22.22     2/0  12.9G   0.927   67.7  1200  1860    41   50
--------------------------- 
Total        63.19  22.22     2/0  12.9G   0.927   67.7                       
--------------------------------------------- 
Average speed (15s): 63.19 Mh/s
Average speed (15s): 63.19 Mh/s
Lost connection to stratum server stratum-ergo.flypool.org:3443 or server not reachable. 
Trying to connect in 5 second(s) 
Average speed (15s): 43.20 Mh/s
Unrecoverable error by GPU 0.
Please check your (memory) OC & UV settings on this card.
Device 0 detected as crashed. 
Closing miner with exit code 42 (--watchdog close).  
```

If i rollback to `lolMiner 1.45`, same overclocking, everything works perfectly fine.

**Comment by jgonzis** [comment]
Ergo wasn't change it, really strange. Could be something about the connection that made that error... It seems in the reconnection of the pool that crash.

**Comment by blackmennewstyle** [comment]
Little correction, the issue is also present with `lolMiner 1.45`, it just happens less frequently lol

**Comment by jgonzis** [comment]
> Little correction, the issue is also present with `lolMiner 1.45`, it just happens less frequently lol

Which OS and which Drivers? And which Core Voltage? Could you try to increase it 25mV?

**Comment by blackmennewstyle** [comment]
> > Little correction, the issue is also present with `lolMiner 1.45`, it just happens less frequently lol
> 
> Which OS and which Drivers? And which Core Voltage? Could you try to increase it 25mV?

GNU/Linux Ubuntu Server 20.04 - kernel 5.4.0-54 amd64 - AMDGPU 20.40

My whole overclock settings (executed with root privileges):
```
/home/ceedii/amdmemorytweak/linux/amdmemtweak --gpu 0 --ref 20 > /dev/null 2>&1
echo "manual" | tee -a /sys/class/drm/card0/device/power_dpm_force_performance_level > /dev/null 2>&1
echo "5" | tee -a /sys/class/drm/card0/device/pp_power_profile_mode > /dev/null 2>&1
echo "0 1 2" | tee -a /sys/class/drm/card0/device/pp_dpm_sclk > /dev/null 2>&1
echo "0 1 2" | tee -a /sys/class/drm/card0/device/pp_dpm_mclk > /dev/null 2>&1
echo "80000000" | tee -a /sys/class/drm/card0/device/hwmon/hwmon*/power1_cap > /dev/null 2>&1
echo "s 2 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "s 3 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "s 4 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "s 5 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "s 6 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "s 7 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "m 2 1760 840" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
echo "c" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
```
It's not an overclocking issue, i have been using these settings before without a single problem until the latest `lolMiner` updates.
I actually switch to `Team Red Miner` and i'm running it since almost 24 hours without a single issue....

**Comment by jgonzis** [comment]
> > > Little correction, the issue is also present with `lolMiner 1.45`, it just happens less frequently lol
> > 
> > 
> > Which OS and which Drivers? And which Core Voltage? Could you try to increase it 25mV?
> 
> GNU/Linux Ubuntu Server 20.04 - kernel 5.4.0-54-generic amd64 - AMDGPU 20.40
> 
> My whole overclock settings (executed with root privileges):
> 
> ```
> /home/ceedii/amdmemorytweak/linux/amdmemtweak --gpu 0 --ref 20 > /dev/null 2>&1
> echo "manual" | tee -a /sys/class/drm/card0/device/power_dpm_force_performance_level > /dev/null 2>&1
> echo "5" | tee -a /sys/class/drm/card0/device/pp_power_profile_mode > /dev/null 2>&1
> echo "0 1 2" | tee -a /sys/class/drm/card0/device/pp_dpm_sclk > /dev/null 2>&1
> echo "0 1 2" | tee -a /sys/class/drm/card0/device/pp_dpm_mclk > /dev/null 2>&1
> echo "80000000" | tee -a /sys/class/drm/card0/device/hwmon/hwmon*/power1_cap > /dev/null 2>&1
> echo "s 2 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "s 3 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "s 4 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "s 5 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "s 6 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "s 7 1200 875" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "m 2 1760 840" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> echo "c" | tee -a /sys/class/drm/card0/device/pp_od_clk_voltage > /dev/null 2>&1
> ```
> 
> It's not an overclocking issue, i have been using these settings before without a single problem until the latest `lolMiner` updates. I actually switch to `Team Red Miner` and i'm running it since almost 24 hours without a single issue....
It could be new DAG needs more Core Voltage... 1200 and 875mv is a good underclock. As you didn't try it the 900 mV to see if that is the problem I close the issue, as you found  a working solution. Many thanks
