### ISSUE TITLE
[Feature Request] allow manually loading previous Dual-mining auto-tune parameters

### ISSUE THREAD

**Issue by Basement-Science** [Lolliedieb/lolMiner-releases#1367]
This is mostly about ETH+Aleph dual mining:

Auto-tuning takes some time, and can be affected by other GPU load on the system (browsers, etc). It may determine suboptimal parameters and then runs inefficiently the entire time, so you have to check the tuning after every miner restart and possibly restart it again, _**and**_ stop all other GPU loads during tuning.
I would like the ability to load the tuning parameters using a command-line argument once OC and overall setup is final. It should be pretty simple I imagine:

1. Add a command-line argument like `--dualTuningParams` which loads the parameters.
2. without the command-line argument, miner works as it does now, performing auto-tuning.
3. When auto-tuning is complete on ALL GPUs, display the determined values as comma-separated list of GPUs, maybe encoded into one number per GPU. Example message: `Tuning complete. Use --dualTuningParams 47181246,89117756,14877534 to load determined parameters manually.`
4. If GPU configuration has changed, (some added or removed) old parameters should be invalid, so maybe add some UID into each GPU's number.

**Comment by jgonzis** [comment]
> This is mostly about ETH+Aleph dual mining:
> 
> Auto-tuning takes some time, and can be affected by other GPU load on the system (browsers, etc). It may determine suboptimal parameters and then runs inefficiently the entire time, so you have to check the tuning after every miner restart and possibly restart it again, _**and**_ stop all other GPU loads during tuning. I would like the ability to load the tuning parameters using a command-line argument once OC and overall setup is final. It should be pretty simple I imagine:
> 
> 1. Add a command-line argument like `--dualTuningParams` which loads the parameters.
> 2. without the command-line argument, miner works as it does now, performing auto-tuning.
> 3. When auto-tuning is complete on ALL GPUs, display the determined values as comma-separated list of GPUs, maybe encoded into one number per GPU. Example message: `Tuning complete. Use --dualTuningParams 47181246,89117756,14877534 to load determined parameters manually.`
> 4. If GPU configuration has changed, (some added or removed) old parameters should be invalid, so maybe add some UID into each GPU's number.

Why you don't use --maxdualimpact to do the balance?, that is easy to control and faster.
