### ISSUE TITLE
Is there anyway to use socks5 proxy in hiveos?

### ISSUE THREAD

**Issue by special911sp** [Lolliedieb/lolMiner-releases#1368]
I want to use socks5 proxy in the hiveos, so i try to use the --socks5 and --proxy xxx.xxx.x.x:xxxx in Extra config arguments ,but there's someting wrong that i can't connect to the pool. Anybody know the reason? Appreciate it!

**Comment by jgonzis** [comment]
> I want to use socks5 proxy in the hiveos, so i try to use the --socks5 and --proxy xxx.xxx.x.x:xxxx in Extra config arguments ,but there's someting wrong that i can't connect to the pool. Anybody know the reason? Appreciate it!

It is like --socks5 xxx.xxx.xxx.xxx that function was added serveral releases before. IT will probably not work with dualmining for the TON Pools
