### ISSUE TITLE
Average speed (30s): 34.27mh/s | 9.10mh/s Total: 43.37 mh/s

### ISSUE THREAD

**Issue by NickG8970** [Lolliedieb/lolMiner-releases#137]
I have 2 gpu's both 8gb, but it doesn't look like the 2nd one is doing a lot:
Setup Miner...
Device 0:
    Name:    GeForce RTX 2060 SUPER
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  8192 MByte
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash)
Device 1:
    Name:    Radeon RX 580 Series
    Address: 2:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8192 MByte (8142 MByte free)
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash)

Connecting to pool...
Connected to eu1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x0bA67B7011340452147054739bfA5a3f68561C86.lolMinerWorker
New job received: 0xf581fa Epoch: 387 Target: 0000000112e0be82
-------------------------------------------------------
         Generating light cache for epoch 387
-------------------------------------------------------
Start Mining...
New job received: 0x9fc27b Epoch: 387 Target: 0000000112e0be82
-------------------------------------------------------
     Done (2098 ms), size of new DAG: 4120 MByte
-------------------------------------------------------
Start DAG gen on GPU 0 (normal mode)
Start DAG gen on GPU 1 (normal mode)

**Comment by Keimling27** [comment]
its a driver problem which card has the problem the rx 580?

**Comment by stevepresley** [comment]
@NickG8970 if it is not a driver issue, you could also try running each card on its own thread.. check this post for my batch file of how to do that - https://github.com/Lolliedieb/lolMiner-releases/issues/158#issuecomment-763041277

**Comment by jgonzis** [comment]
Solved with new CUDA solver + computemode ON
