### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by EzPecks** [Lolliedieb/lolMiner-releases#1371]
Hi, how are u?

Lol returns the following message:

```
OpenCL driver detected.
Number of OpenCL supported GPUs: 1 
No Cuda driver or GPUs detected. 
Device 0: 
    Name:    AMD Liverpool
    Address: 0:1 
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  2487 MByte (3981 MByte free) 
    Active:  false (Unsupported device or driver version.)
```
I have an AMD GPUs based on the Volcanic Islands graphics architecture named "Spooky".

I read that it use an architecture similar to Tonga.

Can you add support to this device please?

**Comment by jgonzis** [comment]
> Hi, how are u?
> 
> Lol returns the following message:
> 
> ```
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 1 
> No Cuda driver or GPUs detected. 
> Device 0: 
>     Name:    AMD Liverpool
>     Address: 0:1 
>     Vendor:  Advanced Micro Devices (AMD)
>     Drivers: OpenCL
>     Memory:  2487 MByte (3981 MByte free) 
>     Active:  false (Unsupported device or driver version.)
> ```
> 
> I have an AMD GPUs based on the Volcanic Islands graphics architecture named "Spooky".
> 
> I read that it use an architecture similar to Tonga.
> 
> Can you add support to this device please?

You need a dedicated GPU...  that GPU is really old.
