### ISSUE TITLE
Issue with miner fee

### ISSUE THREAD

**Issue by Fernal976** [Lolliedieb/lolMiner-releases#1373]
Miner keeps crashed and restart when connect fee pool or something every frequent minutes
![20220305_174615](https://user-images.githubusercontent.com/100999370/156880995-93f5a23b-081c-4a26-a8b8-bf54093b1610.jpg)

**Comment by jgonzis** [comment]
> Miner keeps crashed and restart when connect fee pool or something every frequent minutes ![20220305_174615](https://user-images.githubusercontent.com/100999370/156880995-93f5a23b-081c-4a26-a8b8-bf54093b1610.jpg)

That is not from lolMiner... it doesn't do a 60Fee seconds like that, check if you are paying to HiveON Pool with the 3% or you are using another miner. But lolMiner doesn't do that... Recheck your Config.
