### ISSUE TITLE
1.46a - when dual mining TON, AMD card only gets 1Mh/s on eth when it normally gets ~50, expected?

### ISSUE THREAD

**Issue by frachel** [Lolliedieb/lolMiner-releases#1374]
Doing eth only my AMD 5700 gets ~50Mh/s and my nvidia 1060's get ~20.

When doing dual with TON the nvidia still get ~20 for eth, but the AMD drops to 1Mh/s.. is that expected?

**Comment by jgonzis** [comment]
> Doing eth only my AMD 5700 gets ~50Mh/s and my nvidia 1060's get ~20.
> 
> When doing dual with TON the nvidia still get ~20 for eth, but the AMD drops to 1Mh/s.. is that expected?

1060 Cannot do properly TON + ETH, you will need lot of Power and loss of ETH, with AMD is normal a small lost, you can try to increase Core, but a small lost is quite normal...
