### ISSUE TITLE
dualmining lolMiner.cfg

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1379]
Like topic, any samples or ideas? :D

**Comment by jgonzis** [comment]
> Like topic, any samples or ideas? :D

For which OS?.

**Comment by dawidmosk** [comment]
> > Like topic, any samples or ideas? :D
> 
> For which OS?.

both, win, lnx.

**Comment by jgonzis** [comment]
> > > Like topic, any samples or ideas? :D
> > 
> > 
> > For which OS?.
> 
> both, win, lnx.

You have the bat files or sh files, also with lot of examples, you should haven't problems to configure it.

**Comment by dawidmosk** [comment]
I know how to use parameters/args - I'm asking for cfg file. Not working.

**Comment by jgonzis** [comment]
> I know how to use parameters/args - I'm asking for cfg file. Not working.

I don't understand what you want to put then in that cfg file. 

In Linux is easy as doing that :
lolMiner $(< lolminer.conf)

**Comment by dawidmosk** [comment]
> > I know how to use parameters/args - I'm asking for cfg file. Not working.
> 
> I don't understand what you want to put then in that cfg file.
> 
> In Linux is easy as doing that : lolMiner $(< lolminer.conf)

I was talking about this config file, loaded auto:
root@srv:~/lolMiner# ./lolMiner
unrecognised option 'dualmode'
unrecognised option 'nocolor'

**Comment by jgonzis** [comment]
> > > I know how to use parameters/args - I'm asking for cfg file. Not working.
> > 
> > 
> > I don't understand what you want to put then in that cfg file.
> > In Linux is easy as doing that : lolMiner $(< lolminer.conf)
> 
> I was talking about this config file, loaded auto: root@srv:~/lolMiner# ./lolMiner unrecognised option 'dualmode' unrecognised option 'nocolor'

With that parameter load the most used mining OS the config in Ubuntu 20.04, I don't know why it doesn't work to you. 
lolMiner $(< lolminer.conf)

**Comment by dawidmosk** [comment]
> lolMiner $(< lolminer.conf)

ok, thanks :/

**Comment by dawidmosk** [comment]
I know issue is closed but maybe in the future solution will be nice for someone:
lolMiner.cfg is not this same like lolMiner.conf.
lolMiner.cfg is orig config file with limited options
lolMiner.conf it's just parameters in file (lolMiner --algo --etc..):
> lolMiner $(< lolMiner.conf)

Conclusion:
.cfg have for example "algo=ETHASH", a .conf file have just parameters "--algo ETHASH"

**Comment by jgonzis** [comment]
> I know issue is closed but maybe in the future solution will be nice for someone: lolMiner.cfg is not this same like lolMiner.conf. lolMiner.cfg is orig config file with limited options lolMiner.conf it's just parameters in file (lolMiner --algo --etc..):
> 
> > lolMiner $(< lolMiner.conf)
> 
> Conclusion: .cfg have for example "algo=ETHASH", a .conf file have just parameters "--algo ETHASH"

That is true, it comes from HiveOS... is how they load the defaults
