### ISSUE TITLE
A question about zombie mode automatic tuning 

### ISSUE THREAD

**Issue by Molers** [Lolliedieb/lolMiner-releases#138]
hi,I have some AMD RX580 4G cards, and i tried some parameters,The results are different ，such as

--keepfree 16 --4g-alloc-size 3992 11.7mh/s
--keepfree 16 --4g-alloc-size 4000 12.35mh/s
--keepfree 16 --4g-alloc-size 4016 14.6mh/s
--keepfree 16 --4g-alloc-size 4032 17.0mh/s
--keepfree 16 --4g-alloc-size 4040 18.4mh/s
--keepfree 16 --4g-alloc-size 4044 19.11mh/s
--keepfree 16 --4g-alloc-size 4048 19.85mh/s
--keepfree 16 --4g-alloc-size 4060 22.11mh/s
--keepfree 16 --4g-alloc-size 4063 22.7mh/s
--keepfree 16 --4g-alloc-size 4064 22.9mh/s
--keepfree 16 --4g-alloc-size 4064 24.1mh/s 
--keepfree 24 --4g-alloc-size 4056 21.33mh/s

and i see 1.19Version has a  zombie mode automatic tuning function, can He find the best calculation and parameters auto,
and Although I read readme.txt ,but i Still won't set parameters，ok,I should be stupid.....
if you can help me,I will be very thankful，thank you.

**Comment by dmitriy79** [comment]
How do I disable this setting? How do I set EPOCH 0 permanently so that it is always 0 and never toggles? Why is there no lominer source code anywhere to remove this parameter itself?

**Comment by dmitriy79** [comment]
Comrades developers! Set Epoch: 0 in the source code of the program so that it never changes

**Comment by dmitriy79** [comment]
Otherwise, the GPU runs out of memory. GPU Errors Detected a defect share (potential hardware error)!

**Comment by jgonzis** [comment]
New Zombie Auto better solution
