### ISSUE TITLE
Lolminer autotuning?

### ISSUE THREAD

**Issue by kotopuz** [Lolliedieb/lolMiner-releases#1380]
Dear all,

Is it possible to implement some autotunjng feature?
Say define max fan or temperature and automatically find maximum frequency and lowest voltage for each card? Say set some frequency and run miner for 1 hour, if all fine then calculate efficiency as usd per mh, lower voltages and run again. Say start with 1000mz and go up to 1800 mhz. When tests ate done select most efficient combination and run miner with those settings. Algorithm is clear, it could take few days to map each card frequency vs voltage and mh cost and select the best. Is it possible? It could be useful to make such tests and then let user to select combination he need, but automatic approach would make miner really great!

**Comment by jgonzis** [comment]
> Dear all,
> 
> Is it possible to implement some autotunjng feature? Say define max fan or temperature and automatically find maximum frequency and lowest voltage for each card? Say set some frequency and run miner for 1 hour, if all fine then calculate efficiency as usd per mh, lower voltages and run again. Say start with 1000mz and go up to 1800 mhz. When tests ate done select most efficient combination and run miner with those settings. Algorithm is clear, it could take few days to map each card frequency vs voltage and mh cost and select the best. Is it possible? It could be useful to make such tests and then let user to select combination he need, but automatic approach would make miner really great!

Problem for that is that is need to be administrator...  with lot of options too and each GPU is different. It is always better that user test and decide what to use. Because it can cause lot of crashes looking the max performance.

**Comment by kotopuz** [comment]
Ok. Even a  week of reboots and crashes with best settings found and long run will payback. Generic settings can be used as memory,gpu freq and voltage. Mjn max and step should be defined by user to run all combinations and calculate efficiency. Do you think you do it? I saw some autotuners on github. May be fork them and add option to run on lolminer(default should have autotune disabled)?

**Comment by jgonzis** [comment]
> Ok. Even a week of reboots and crashes with best settings found and long run will payback. Generic settings can be used as memory,gpu freq and voltage. Mjn max and step should be defined by user to run all combinations and calculate efficiency. Do you think you do it? I saw some autotuners on github. May be fork them and add option to run on lolminer(default should have autotune disabled)?

Doing autotune without controlling the Rigs with lot of Silicon lottery is not easy as a click... and can cause damage to the GPU. I don't think that will take this responsability the miner.

**Comment by kotopuz** [comment]
Many thanks for replies. I thought that it was about automation of human actions during tuning, but thanks anyway.
