### ISSUE TITLE
Error when allocating memory or building DAG. Disabling card, Linux mint, gtx 1070

### ISSUE THREAD

**Issue by chuckleburger666** [Lolliedieb/lolMiner-releases#1385]
I just switched over to Linux Mint from windows 10, so please bare with me, I mine when I'm not using my Gaming rig, and I'm getting this error: GPU 0: error when allocating memory or building DAG. Disabling card. Not sure why, I've used this card before for mining, I've got 8gb vram, so I'm not running into size limits on the DAG.
I'm using lolminer 1.46a.

Any help would be much appreciated.

**Comment by jgonzis** [comment]
> I just switched over to Linux Mint from windows 10, so please bare with me, I mine when I'm not using my Gaming rig, and I'm getting this error: GPU 0: error when allocating memory or building DAG. Disabling card. Not sure why, I've used this card before for mining, I've got 8gb vram, so I'm not running into size limits on the DAG. I'm using lolminer 1.46a.
> 
> Any help would be much appreciated.

You should increase Virtual Disk or you willl not been able to run it. Linux not need it but Windows yes
