### ISSUE TITLE
How to make fix this issue. Pool show less hashrate as compared to miner. Please help lolminer. SEE THIS!!

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#1386]
![Screenshot_20220308-090134_Hive OS.jpg](https://user-images.githubusercontent.com/92781808/157161306-2f94e4f8-0160-438f-9c59-abea3692e958.jpg)![Screenshot_20220308-090048_Telegram.jpg](https://user-images.githubusercontent.com/92781808/157161318-c86a404e-2d57-434d-a3ef-31706c36d7d5.jpg)

**Comment by jgonzis** [comment]
> ![Screenshot_20220308-090134_Hive OS.jpg](https://user-images.githubusercontent.com/92781808/157161306-2f94e4f8-0160-438f-9c59-abea3692e958.jpg)![Screenshot_20220308-090048_Telegram.jpg](https://user-images.githubusercontent.com/92781808/157161318-c86a404e-2d57-434d-a3ef-31706c36d7d5.jpg)

Just make a restart, it will be fixed... in the EPOCH swap in some LHR card is affected. It seems your rig is full LHR. I'm sure update will be launched before next EPoch in 4 days.
