### ISSUE TITLE
new gui, refreshed or not?

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1387]
On date page /gui should be some "a live" sign.. for example datetime - refreshed with page/data. I never now is a live/fresh or dead - and i have to refresha page all the time.

**Comment by jgonzis** [comment]
> On date page /gui should be some "a live" sign.. for example datetime - refreshed with page/data. I never now is a live/fresh or dead - and i have to refresha page all the time.

The Gui refreseh automatic each 10 seconds, you can check the runtime in the table. And you will see how increase each 10s.
