### ISSUE TITLE
half hash rate RTX 3090 win 11 lolminer 1.43

### ISSUE THREAD

**Issue by LaenorSama** [Lolliedieb/lolMiner-releases#1389]
This situation started yesterday. At the start, the miner works as usual, but after a while the hashrate drops twice, both for ETH and TON, it does not recover on its own. After restarting the computer, everything comes back to normal for a while. Also, for some reason, everything comes back to normal when connected to a computer via RDP.
RTX 3090 win 11 lolminer 1.43

**Comment by jgonzis** [comment]
> This situation started yesterday. At the start, the miner works as usual, but after a while the hashrate drops twice, both for ETH and TON, it does not recover on its own. After restarting the computer, everything comes back to normal for a while. Also, for some reason, everything comes back to normal when connected to a computer via RDP. RTX 3090 win 11 lolminer 1.43

Could you add --lhrtune off in the EXTRAPARAMETERS, just to avoid any LHR Check that causes the half. I also recommend you if you can to uses 1.46a, you will get a really nice boost in TON
