### ISSUE TITLE
Miner stop working after few hours mining

### ISSUE THREAD

**Issue by feckk** [Lolliedieb/lolMiner-releases#139]
Have start using lolminer yesterday. Had mining for a few hours. Then it breaks. 
Now it does not run anymore. Any thoughts on what could be? Thanks.

![error3](https://user-images.githubusercontent.com/61942391/104341082-ab274700-54f9-11eb-8df7-85335f240735.png)

**Comment by ForeignImport** [comment]
I have the same issue and I went to look for the .exe, it doesn't exist on 1.19 Winzip

**Comment by Keimling27** [comment]
This looks like your antivirus has delete the miner exe  download again and allow the miner in your antivirus

**Comment by jgonzis** [comment]
Antivirus problem, and try new version more stable in Windows
