### ISSUE TITLE
how to make fix the servers reconnecting!!!! see this screenshot.. i am faced this problem several times and miner restart own..

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#1391]
<img width="467" alt="Capture1" src="https://user-images.githubusercontent.com/92781808/157846220-7513c727-4bb6-40da-a8b8-285765d176c7.PNG">
<img width="337" alt="Capture2" src="https://user-images.githubusercontent.com/92781808/157846230-a772e700-c61b-4b24-bb14-e27766734de3.PNG">

**Comment by jgonzis** [comment]
> <img alt="Capture1" width="467" src="https://user-images.githubusercontent.com/92781808/157846220-7513c727-4bb6-40da-a8b8-285765d176c7.PNG">
> 
> <img alt="Capture2" width="337" src="https://user-images.githubusercontent.com/92781808/157846230-a772e700-c61b-4b24-bb14-e27766734de3.PNG">

Hi, 1.46a help on reconnections with a fix bug that was in previous versions. But seen that Why you don't try to connect to the ssl connection. As you see you have problems with the ethermine pool that is not responding.

**Comment by ROCKET0101** [comment]
how to make connect with ssl connection in hive os

**Comment by ROCKET0101** [comment]
I am using SSL connection but miner show reconnecting problem again. Mean SSL connection is also not working. Please provide me a solution lol developers.
<img width="424" alt="s" src="https://user-images.githubusercontent.com/92781808/158044672-89b6285e-557b-4143-954e-3b0c2d885471.PNG">
.

**Comment by jgonzis** [comment]
But seems to have worked... because it has shares before ....which version are you using and how many pools do you have selected?

**Comment by ROCKET0101** [comment]
i am using 1.46a Lolminer and only 2 pool servers selected Asia and Asia 2
![ss](https://user-images.githubusercontent.com/92781808/158054776-9035b647-38d2-40ca-9fbd-2c161d4c570c.PNG)

**Comment by jgonzis** [comment]
Just to discard, selecting only 1 goes??

**Comment by ROCKET0101** [comment]
> Just to discard, selecting only 1 goes??

I select one server Like (Asia) only. I will try bro.. if reconnecting problem will show me again i will tell you.

**Comment by ROCKET0101** [comment]
same issue again please help me brother . please fix this issue . i was selected only one server, but the problem remain same.
![Capture](https://user-images.githubusercontent.com/9278
![ss](https://user-images.githubusercontent.com/92781808/158414883-d68a125f-2e77-4519-ac91-4a4697003ff5.PNG)
1808/158414614-5b707058-415b-4cfe-a0d1-dadd1750d325.PNG)
ue.
