### ISSUE TITLE
Bug on Workstation Display for rigs behind firewall

### ISSUE THREAD

**Issue by Identita** [Lolliedieb/lolMiner-releases#1392]
When running the latest release (1.46a) when you run multiple machine behind a firewall in dual mining configuration (ETH + ALPH) the workstations (should be 3) appear listed properly on ethermine.org but on woolypooly.com they appear in a consolidated workstation name defined as "undefined" See attached.
![2022-03-11 bug](https://user-images.githubusercontent.com/23223039/157903201-fe3b7d5f-949b-4c94-8640-959eb8219354.png)

**Comment by jgonzis** [comment]
> When running the latest release (1.46a) when you run multiple machine behind a firewall in dual mining configuration (ETH + ALPH) the workstations (should be 3) appear listed properly on ethermine.org but on woolypooly.com they appear in a consolidated workstation name defined as "undefined" See attached. ![2022-03-11 bug](https://user-images.githubusercontent.com/23223039/157903201-fe3b7d5f-949b-4c94-8640-959eb8219354.png)

Undefined is when you haven't add the --dualworker Name_Rig it is like "default name" --dualworker is to assign a name to the 2nd connection.

**Comment by Identita** [comment]
Sorry I was unfamiliar as I just moved from T-Rex and didn't know if it went in the top half of the config or bottom. Thanks

**Comment by jgonzis** [comment]
> Sorry I was unfamiliar as I just moved from T-Rex and didn't know if it went in the top half of the config or bottom. Thanks

Thx for the reply. I understand the solution worked :-)
