### ISSUE TITLE
AMD Radeon 8870M - Device not supported or not listed

### ISSUE THREAD

**Issue by ydlmz** [Lolliedieb/lolMiner-releases#1394]
I tried to launch lolMiner on my notebook with AMD Radeon 8870M but it said that "This device is not supported or listed in the instructions".

Please let the program support that GPU.

**Comment by jgonzis** [comment]
> I tried to launch lolMiner on my notebook with AMD Radeon 8870M but it said that "This device is not supported or listed in the instructions".
> 
> Please let the program support that GPU.

It is complicated... when it is not dedicated GPU
