### ISSUE TITLE
ton mining shows 0 hash rate and no info since yesterday

### ISSUE THREAD

**Issue by Corleone78** [Lolliedieb/lolMiner-releases#1395]
Hi,
According to lolminer no issues shows and it looks that I am dual mining fine , but since yesterday no balance and no info in bot. 
I have been mining since a while ago and no issues and now I updated did everything and still same issue. 
Can anybody help?

**Comment by jgonzis** [comment]
> Hi, According to lolminer no issues shows and it looks that I am dual mining fine , but since yesterday no balance and no info in bot. I have been mining since a while ago and no issues and now I updated did everything and still same issue. Can anybody help?

Make a restart of the miner... also which pool are you using to try to see if we found something with another users and sames pools
