### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Chemada1** [Lolliedieb/lolMiner-releases#1396]
![E26A41C7-A4EE-4C8E-95EF-A37AB2F7CEA6](https://user-images.githubusercontent.com/101533678/158087620-e9a472c0-475c-4a6d-8e89-ee49d470f516.jpeg)

why does my miner say this?

**Comment by tsfrederick333** [comment]
Pool address incorrectly

**Comment by jgonzis** [comment]
> ![E26A41C7-A4EE-4C8E-95EF-A37AB2F7CEA6](https://user-images.githubusercontent.com/101533678/158087620-e9a472c0-475c-4a6d-8e89-ee49d470f516.jpeg)
> 
> why does my miner say this?

Yes, as you can see not connected to the Pool of ZEL...
