### ISSUE TITLE
neverending story

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [Lolliedieb/lolMiner-releases#1399]
I'm trying to redo my rig flighsheet (yes I'm on hive) and noticed something weird. One of my cards never stops hitting an lhr lock. However, lolminer keeps trying to overcome this by reducing the tuning value on every cycle. At one point, I thought it had crashed the rig since lolminer showed 0 for all the cards

After 30m, the lhr value is almost -100
		

```
                                                                                                                                        
      Name         Speed    Pool   Shares    Best    Eff.    Speed     Pool   Shares
                    Mh/s    Mh/s   A/S/Hw   Share  Mh/s/W     Mh/s     Mh/s   A/S/Hw
GPU 0 RTX 3060 Ti  35.19   32.76   15/0/0  243.0G   0.289  1037.49   885.75   24/0/0
GPU 1 RTX 3060     31.22   32.22   15/0/0   42.1G   0.276  1027.16   553.59   15/0/0
GPU 2 RTX 3060     31.25   21.48   10/0/0   60.8G   0.256  1060.25  1550.06   42/0/0
GPU 3 RX 6700XT    46.17   50.48   23/0/0   90.2G   0.453  1119.63  1254.81   34/0/0
GPU 4 RTX 3060     31.28   51.56   24/0/0  579.6G   0.248  1051.96  1070.28   29/0/0
GPU 5 RTX 3060 Ti  42.13   51.56   24/0/0  735.2G   0.318   886.30   996.47   27/0/0
GPU 6 RTX 3070     27.63    4.30    2/0/0    4.7G   0.362  1003.04   369.06   10/0/0
GPU 7 RTX 3060 Ti  38.16   27.93   13/0/0  118.0G   0.204  1507.81  1550.06   42/0/0
GPU 8 RTX 3060 Ti  35.64   12.89    6/0/0   44.7G   0.289  1074.33   959.56   26/0/0
---------------------------                                                                                                             
Total             318.67  285.17  132/0/0  735.2G   0.289  9767.97  9189.66  249/0/0
                                                                                                                                        
          Best    Eff.   Power  CCLK  MCLK  Core  Junc   Mem  Fan  --lhrtune
         Share  Mh/s/W       W   MHz   MHz  Temp  Temp  Temp  Pct           
GPU 0   220.2T   8.530   121.1  1080  7920    56  n.a.  n.a.   67       23.4
GPU 1     3.0T   9.090   112.5  1380  8350    55  n.a.  n.a.   60       32.6
GPU 2    34.7T   8.674   121.7  1410  8100    52  n.a.  n.a.   76       38.8
GPU 3   611.3G  10.986   101.4  1550  1074    43    51    64   42        0.0
GPU 4   644.3G   8.330   125.8  1395  8100    57  n.a.  n.a.   81       35.4
GPU 5     1.8T   6.686   132.1  1260  8050    53  n.a.  n.a.   51       45.8
GPU 6   427.3G  13.159    75.7  1020  8125    45  n.a.  n.a.   81      -97.8
GPU 7   729.7G   8.051   186.8  1440  7500    55  n.a.  n.a.   74       35.6
GPU 8     2.8T   8.713   122.8  1110  7920    51  n.a.  n.a.   75       29.2
---------------------------                                                                                                             
Total   220.2T   8.844  1100.0                                              
---------------------------------------------       
```

**Comment by jgonzis** [comment]
> I'm trying to redo my rig flighsheet (yes I'm on hive) and noticed something weird. One of my cards never stops hitting an lhr lock. However, lolminer keeps trying to overcome this by reducing the tuning value on every cycle. At one point, I thought it had crashed the rig since lolminer showed 0 for all the cards
> 
> After 30m, the lhr value is almost -100
> 
> ```
>                                                                                                                                         
>       Name         Speed    Pool   Shares    Best    Eff.    Speed     Pool   Shares
>                     Mh/s    Mh/s   A/S/Hw   Share  Mh/s/W     Mh/s     Mh/s   A/S/Hw
> GPU 0 RTX 3060 Ti  35.19   32.76   15/0/0  243.0G   0.289  1037.49   885.75   24/0/0
> GPU 1 RTX 3060     31.22   32.22   15/0/0   42.1G   0.276  1027.16   553.59   15/0/0
> GPU 2 RTX 3060     31.25   21.48   10/0/0   60.8G   0.256  1060.25  1550.06   42/0/0
> GPU 3 RX 6700XT    46.17   50.48   23/0/0   90.2G   0.453  1119.63  1254.81   34/0/0
> GPU 4 RTX 3060     31.28   51.56   24/0/0  579.6G   0.248  1051.96  1070.28   29/0/0
> GPU 5 RTX 3060 Ti  42.13   51.56   24/0/0  735.2G   0.318   886.30   996.47   27/0/0
> GPU 6 RTX 3070     27.63    4.30    2/0/0    4.7G   0.362  1003.04   369.06   10/0/0
> GPU 7 RTX 3060 Ti  38.16   27.93   13/0/0  118.0G   0.204  1507.81  1550.06   42/0/0
> GPU 8 RTX 3060 Ti  35.64   12.89    6/0/0   44.7G   0.289  1074.33   959.56   26/0/0
> ---------------------------                                                                                                             
> Total             318.67  285.17  132/0/0  735.2G   0.289  9767.97  9189.66  249/0/0
>                                                                                                                                         
>           Best    Eff.   Power  CCLK  MCLK  Core  Junc   Mem  Fan  --lhrtune
>          Share  Mh/s/W       W   MHz   MHz  Temp  Temp  Temp  Pct           
> GPU 0   220.2T   8.530   121.1  1080  7920    56  n.a.  n.a.   67       23.4
> GPU 1     3.0T   9.090   112.5  1380  8350    55  n.a.  n.a.   60       32.6
> GPU 2    34.7T   8.674   121.7  1410  8100    52  n.a.  n.a.   76       38.8
> GPU 3   611.3G  10.986   101.4  1550  1074    43    51    64   42        0.0
> GPU 4   644.3G   8.330   125.8  1395  8100    57  n.a.  n.a.   81       35.4
> GPU 5     1.8T   6.686   132.1  1260  8050    53  n.a.  n.a.   51       45.8
> GPU 6   427.3G  13.159    75.7  1020  8125    45  n.a.  n.a.   81      -97.8
> GPU 7   729.7G   8.051   186.8  1440  7500    55  n.a.  n.a.   74       35.6
> GPU 8     2.8T   8.713   122.8  1110  7920    51  n.a.  n.a.   75       29.2
> ---------------------------                                                                                                             
> Total   220.2T   8.844  1100.0                                              
> ---------------------------------------------       
> ```

Update to Nvidia 470 Drivers please, and be sure PL is to 0

**Comment by basking-in-the-sun2000** [comment]
Sorry forgot to mention that. The driver version is 470.103.01 and don't think I had any pl limits

**Comment by jgonzis** [comment]
> Sorry forgot to mention that. The driver version is 470.103.01 and don't think I had any pl limits

Could you share the OC of that GPU please?

**Comment by basking-in-the-sun2000** [comment]
1020/2650

**Comment by jgonzis** [comment]
> 1020/2650

Just wait to the new comming release that for sure will solve that problem.

**Comment by basking-in-the-sun2000** [comment]
great, thanks

**Comment by jgonzis** [comment]
> great, thanks

Ready the new version :-)
