### ISSUE TITLE
hash keeps going to 0 after a few hours

### ISSUE THREAD

**Issue by gordesky1** [Lolliedieb/lolMiner-releases#14]
Hello.   I been noticing for my 2 amds on zel  after a few hours I see it reporting 0hash meaning it quit mining and I have to keep restarting it..  the cards didn't crash or anything.   I asked the zel discord and a pool owner equipool.1ds.us  said he also herd about that and had people report it sense it is a urgent issue.

Will this be fixed soon? or a quick fix I can do?

**Comment by Lolliedieb** [comment]
If the problem still persistent? 
I am aware that sometimes cards fall to 0 when voltage is not high enough - so please share more details about your cards and settings.

**Comment by croelanjr** [comment]
Hi Lolliedieb, I am creating a server on Linux, I am interested in using your lolminer software. Question: What Linux operating system have you developed your software? What version of kernel are you working on in the latest version of lolminer? with this information I can create my linux server without problem. Another question: is there a possibility to separate your lolminer software AMD and NVIDIA? , I tell you that before I used lolminer for GRIN currency, and it was only your lolminer software in AMD and it has worked without problem.
Regards
Croelan, Jr.
