### ISSUE TITLE
Unlock 3060ti LHR 55 mh

### ISSUE THREAD

**Issue by DarMar22** [Lolliedieb/lolMiner-releases#1401]
Lolminer are very close to unlocking the 3060ti lhr at least. 
I have 2 3060tilhr (Eagle Gforce RTX driver version 511.65) that give an average of 46mh. 
Yesterday I downloaded the latest version 1.46a to test the eth+alph and the truth was that it didn't download much but it didn't give me much about aleph either so I started blocking the core (--cclk) modifying the commands etc. 
leaving just this for ETH alone (lolMiner --algo ETHASH --pool eu1.ethermine.org:4444 --user xxxwaletxxx.DaR) And started mining each plate at 55.65 mh eth! 
Obviously I kept  thinking that the program had unlocked the board...very happy.... few hours late nvidia show me a new driver version 511.79 is available.... stop the machine and classic.. when I run the program again....45mh :(. until now I still haven't been able to discover what combination I made with the afterburner and the miner to unlock the plates.

i have win11, and now is imposible perform a dual mining eth-alph or eth-ton... i try to find why...i downgrade the driver to 511.65 but nothing.... but i think is close the 100% unlock

**Comment by Ricco59163** [comment]
interresting ! new glitch ;)

**Comment by cosdal** [comment]
can you test the tool removelhr ? tell me how is going with 3060ti lhr. Thanks

**Comment by DarMar22** [comment]
> 

if u say about the program from sergey LHR v2 is all malware and troyans

**Comment by DarMar22** [comment]
I still trying but nothing... i think i broke the LHR open some secuence off miners....

**Comment by cosdal** [comment]
that's i know sergey program have a troyans i check it too. is other one removeLHR the name. Is not so popular but for me is working well. i use with 3080 LHR and i get max hashrate. If you know too MSI Afterburner i change the power limit to 76% and i get nice hashrate octopus about 82.00M and power GPU 258 Watt.

**Comment by cosdal** [comment]
> that's i know sergey program have a troyans i check it too. is other one removeLHR the name. Is not so popular but for me is working well. i use with 3080 LHR and i get max hashrate. If you use both removeLHR and change with MSI Afterburner  the power limit to 76% then you get nice hashrate "octopus" about 82.00M and power GPU 258 Watt.

**Comment by DarMar22** [comment]
i try to find but nothing

**Comment by cosdal** [comment]
> i try to find but nothing
msi afterburner https://www.msi.com/Landing/afterburner/graphics-cards?msclkid=62a08c1fa84911eca8612fe009876d5f
and the tool is removeLHR @com
