### ISSUE TITLE
Log file has NULLs at the start after some time of mining

### ISSUE THREAD

**Issue by Juriyx** [Lolliedieb/lolMiner-releases#1405]
As a result, I can't see the actual statistics at some moment, neither in the RaveOS interface ("Worker logs" menu item) nor in the log file, downloaded by WinSCP. Here is an example of the log:
[lolminer-1.46a-nvidia.log](https://github.com/Lolliedieb/lolMiner-releases/files/8304502/lolminer-1.46a-nvidia.log)
Fix it, please. Also, in my opinion, the log should store at least 24h of mining and the previous 48 hours should be saved to lolminer-1.46a-nvidia.old.log file and lolminer-1.46a-nvidia.log.1.gz archive.

**Comment by jgonzis** [comment]
> As a result, I can't see the actual statistics at some moment, neither in the RaveOS interface ("Worker logs" menu item) nor in the log file, downloaded by WinSCP. Here is an example of the log: [lolminer-1.46a-nvidia.log](https://github.com/Lolliedieb/lolMiner-releases/files/8304502/lolminer-1.46a-nvidia.log) Fix it, please. Also, in my opinion, the log should store at least 24h of mining and the previous 48 hours should be saved to lolminer-1.46a-nvidia.old.log file and lolminer-1.46a-nvidia.log.1.gz archive.

You can add the function in RAveOS Log-on to store it, that has to be done by the OS.
