### ISSUE TITLE
Stats args not working properly in HiveOS when Dual Mining

### ISSUE THREAD

**Issue by m2internet** [Lolliedieb/lolMiner-releases#1410]
When dual mining (ETH + TON) I cannot add the parameters --shortstats or --longstats without getting the error:
--shortstats cannot be duplicated/entered twice   (I forget the wording exactly)

Not the end of the world, but i'd love to slow down the stat spam on the screen. So small  issue/bug.

Thanks for the software :)

**Comment by jgonzis** [comment]
> When dual mining (ETH + TON) I cannot add the parameters --shortstats or --longstats without getting the error: --shortstats cannot be duplicated/entered twice (I forget the wording exactly)
> 
> Not the end of the world, but i'd love to slow down the stat spam on the screen. So small issue/bug.
> 
> Thanks for the software :)

Yes because HiveOS have them by default in the lolminer config global

**Comment by m2internet** [comment]
Ah, found it. Thx
