### ISSUE TITLE
Could you add VRAM Temp for GDDR6X  in Linux  and windows like T-rex and gminer please

### ISSUE THREAD

**Issue by samy63** [Lolliedieb/lolMiner-releases#1411]
Could you add VRAM Temp for GDDR6X  in Linux  and Windows like T-rex and gminer please

I do dual mining ETH+TON

thank you in advance

**Comment by Ada66a** [comment]
👍

**Comment by jgonzis** [comment]
> Could you add VRAM Temp for GDDR6X in Linux and Windows like T-rex and gminer please
> 
> I do dual mining ETH+TON
> 
> thank you in advance

It is one of the comming development...

**Comment by jgonzis** [comment]
Done it!!
