### ISSUE TITLE
lolminer -nicehash  connection problems

### ISSUE THREAD

**Issue by iso0606** [Lolliedieb/lolMiner-releases#1412]
I got the problems that I mentioned above ( sometimes in few hours but sometimes in every 5 minutes) . After than I can not connect to the server.(I tried with both  NiceHash 's mentioned versions)
1.46-1.46a I used both of these versions and I faced the same situation with both these versions.
![lol hata](https://user-images.githubusercontent.com/102291646/159892152-2aef39a6-83ba-4951-88dc-f9eb49dacc20.png)

**Comment by jgonzis** [comment]
> I got the problems that I mentioned above ( sometimes in few hours but sometimes in every 5 minutes) . After than I can not connect to the server.(I tried with both NiceHash 's mentioned versions) 1.46-1.46a I used both of these versions and I faced the same situation with both these versions. ![lol hata](https://user-images.githubusercontent.com/102291646/159892152-2aef39a6-83ba-4951-88dc-f9eb49dacc20.png)

That is internet, be sure you hace put the correct wallet ... but that shows it cannot connect and previous it has so check firewall or try other nicehash server
