### ISSUE TITLE
HELP ! Anybody know how to dual mining ETH + ERG ? RAVEOS

### ISSUE THREAD

**Issue by THANHALEN** [Lolliedieb/lolMiner-releases#1416]
OS        : RAVEOS
CARD   : 3060 ti LHR
ETH      : 45Mh/s
I used this launch option but it's not working, only show hashrate ETH only.  
----------------------------------------------------------------------------------------------------------------
--dualmode Autolykos2 --dualpool https://erg.2miners.com:8888 --dualuser ergwallet --devices 0,1,2,3,4,5,6,7
----------------------------------------------------------------------------------------------------------------

**Comment by jgonzis** [comment]
> ## OS : RAVEOS
> CARD : 3060 ti LHR
> ETH : 45Mh/s
> I used this launch option but it's not working, only show hashrate ETH only.
> ## --dualmode Autolykos2 --dualpool https://erg.2miners.com:8888 --dualuser ergwallet --devices 0,1,2,3,4,5,6,7

Have you update to last RaveOS release?  Or check in the miner?

Because which Gpu do you want to mine ETH and which ones ERGO?

**Comment by THANHALEN** [comment]
First thank your comment so much !
I upgraded new raveos version from command console "upgrade"
Could i use 3060 Ti LHR to dual mining coin ETH + ERG sametime on same GPU? with 70% ETH + 30% ERG? and if it could be, how command launch option i will input? tks

**Comment by jgonzis** [comment]
> First thank your comment so much ! I upgraded new raveos version from command console "upgrade" Could i use 3060 Ti LHR to dual mining coin ETH + ERG sametime on same GPU? with 70% ETH + 30% ERG? and if it could be, how command launch option i will input? tks

That type of mining is not yet available. Other do 30% ETH and 70% Ergo... is more profitable 78% ETh

**Comment by THANHALEN** [comment]
Thank you again #jgonzis !
Can you show me that launch option with LOLMINER 1.47? ETH + ERG tks

**Comment by jgonzis** [comment]
> Thank you again #jgonzis ! Can you show me that launch option with LOLMINER 1.47? ETH + ERG tks

Which Gpus ETH and which ones ERG?

**Comment by THANHALEN** [comment]
Thanks you so much, jgonzis !
