### ISSUE TITLE
1.47 Sometimes LHR cards are detected as FHR

### ISSUE THREAD

**Issue by Sanchous98** [Lolliedieb/lolMiner-releases#1418]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/45293316/160260172-3ed221d4-cafa-4df9-8cbf-0943ce926fb9.png">

As you see, one of the RTX 3080Ti is detected as FHR and is locked on 33 MH/s. It happens randomly.

**Comment by jgonzis** [comment]
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/45293316/160260172-3ed221d4-cafa-4df9-8cbf-0943ce926fb9.png">
> 
> As you see, one of the RTX 3080Ti is detected as FHR and is locked on 33 MH/s. It happens randomly.

Could you reduce the memory OC?
Also please drivers 470.103.01 or 510.xx
And not delay OC

**Comment by Sanchous98** [comment]
> > <img alt="image" width="400" src="https://user-images.githubusercontent.com/45293316/160260172-3ed221d4-cafa-4df9-8cbf-0943ce926fb9.png">
> > As you see, one of the RTX 3080Ti is detected as FHR and is locked on 33 MH/s. It happens randomly.
> 
> Could you reduce the memory OC? Also please drivers 470.103.01 or 510.xx And not delay OC

I tried to reduce OC, but it still happens rarely on different cards. Driver is 470.103.01. It's not a big problem cause the miners works without restarts, but it will be a little annoying when I'll try to update system or something else. I fixed it by activating hashrate watchdog in hive which will restart the miner if the overall hashrate will too low, but it will apply after ~5 minutes, because about miner requires some time to tune.

**Comment by jgonzis** [comment]
> > > <img alt="image" width="400" src="https://user-images.githubusercontent.com/45293316/160260172-3ed221d4-cafa-4df9-8cbf-0943ce926fb9.png">
> > > As you see, one of the RTX 3080Ti is detected as FHR and is locked on 33 MH/s. It happens randomly.
> > 
> > 
> > Could you reduce the memory OC? Also please drivers 470.103.01 or 510.xx And not delay OC
> 
> I tried to reduce OC, but it still happens rarely on different cards. Driver is 470.103.01. It's not a big problem cause the miners works without restarts, but it will be a little annoying when I'll try to update system or something else. I fixed it by activating hashrate watchdog in hive which will restart the miner if the overall hashrate will too low, but it will apply after ~5 minutes, because about miner requires some time to tune.

Are you doing CPU Mining?

**Comment by Sanchous98** [comment]
> > > > <img alt="image" width="400" src="https://user-images.githubusercontent.com/45293316/160260172-3ed221d4-cafa-4df9-8cbf-0943ce926fb9.png">
> > > > As you see, one of the RTX 3080Ti is detected as FHR and is locked on 33 MH/s. It happens randomly.
> > > 
> > > 
> > > Could you reduce the memory OC? Also please drivers 470.103.01 or 510.xx And not delay OC
> > 
> > 
> > I tried to reduce OC, but it still happens rarely on different cards. Driver is 470.103.01. It's not a big problem cause the miners works without restarts, but it will be a little annoying when I'll try to update system or something else. I fixed it by activating hashrate watchdog in hive which will restart the miner if the overall hashrate will too low, but it will apply after ~5 minutes, because about miner requires some time to tune.
> 
> Are you doing CPU Mining?

Nope. There are no cpu bound tasks

**Comment by sasi1212** [comment]
Here is the changelog of lolMiner v1.47.

> lolMiner v1.47 (improved ETH solver with up to 78% unlock; parameter --lhrtune now takes absolute % values to fix a certain percentage of unlocking; reduced Ton & Alephium fee in Eth+Ton / Ethash+Alephium dual mining to 0%; new --silence parameter controls the amount of information the miner will print during its work; added Nvidia memory junction temperature readings on cards that support this; fixed a bug with dual mining on LHR cards where the dual algorithm was mined with reduced rate after Ethash epoch change; fixed a bug with --compactaccept not showing the * sign on short statistics. NOTE: for more info on this update, check here: https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.47)

It says, `--lhrtune` takes % value now onwards. I was using `--lhrtune` earlier with the index 17 (previous valuesa are -40 to +40). With this update, `--lhrtune` recognizes 17 as 17%. So I faced low hash as you guys faced. What I did was added `--lhrtune 77` and getting great hashrate on my 3060Ti LHR cards.

Happy mining !

**Comment by Sanchous98** [comment]
> Here is the changelog of lolMiner v1.47.
> 
> > lolMiner v1.47 (improved ETH solver with up to 78% unlock; parameter --lhrtune now takes absolute % values to fix a certain percentage of unlocking; reduced Ton & Alephium fee in Eth+Ton / Ethash+Alephium dual mining to 0%; new --silence parameter controls the amount of information the miner will print during its work; added Nvidia memory junction temperature readings on cards that support this; fixed a bug with dual mining on LHR cards where the dual algorithm was mined with reduced rate after Ethash epoch change; fixed a bug with --compactaccept not showing the * sign on short statistics. NOTE: for more info on this update, check here: https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.47)
> 
> It says, `--lhrtune` takes % value now onwards. I was using `--lhrtune` earlier with the index 17 (previous valuesa are -40 to +40). With this update, `--lhrtune` recognizes 17 as 17%. So I faced low hash as you guys faced. What I did was added `--lhrtune 77` and getting great hashrate on my 3060Ti LHR cards.
> 
> Happy mining !

Man, just don't write if don't understand the problem

**Comment by sasi1212** [comment]
Enjoy !

**Comment by jgonzis** [comment]
> > Here is the changelog of lolMiner v1.47.
> > > lolMiner v1.47 (improved ETH solver with up to 78% unlock; parameter --lhrtune now takes absolute % values to fix a certain percentage of unlocking; reduced Ton & Alephium fee in Eth+Ton / Ethash+Alephium dual mining to 0%; new --silence parameter controls the amount of information the miner will print during its work; added Nvidia memory junction temperature readings on cards that support this; fixed a bug with dual mining on LHR cards where the dual algorithm was mined with reduced rate after Ethash epoch change; fixed a bug with --compactaccept not showing the * sign on short statistics. NOTE: for more info on this update, check here: https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.47)
> > 
> > 
> > It says, `--lhrtune` takes % value now onwards. I was using `--lhrtune` earlier with the index 17 (previous valuesa are -40 to +40). With this update, `--lhrtune` recognizes 17 as 17%. So I faced low hash as you guys faced. What I did was added `--lhrtune 77` and getting great hashrate on my 3060Ti LHR cards.
> > Happy mining !
> 
> Man, just don't write if don't understand the problem. The problem is that LHR card is detected as non LHR, so --lhrtune is not working at all for this card

Try to reduce the Memory OC of the 3080TI... IT seems and not trigger the new Unlock

**Comment by Gkozd** [comment]
Same for 3080 LHR. **1.47 lolminer HiveOS Kernel 5.10.0-hiveos #60, N470.103.01.**
Actually one of g-card in my rig is non-LHR - so i was trying to use a different miner for it (gminer - higher hashrate 102 Mh/s - lolminer is giving me only 100,8 Mh/s for same OC). 
Basically: devices 0,1,2,3,4,6,7, - > lolminer (LHR g-cards)
devices 5 - gminer (non-lhr g-card)
But After a while it start to thinking, that one of LHR g-card (6th usually) is FHR...
When ALL of g-cards from rig are assigned to lolminer, none of above is happening.

**Comment by jgonzis** [comment]
> Same for 3080 LHR. **1.47 lolminer HiveOS Kernel 5.10.0-hiveos #60, N470.103.01.** Actually one of g-card in my rig is non-LHR - so i was trying to use a different miner for it (gminer - higher hashrate 102 Mh/s - lolminer is giving me only 100,8 Mh/s for same OC). Basically: devices 0,1,2,3,4,6,7, - > lolminer (LHR g-cards) devices 5 - gminer (non-lhr g-card) But After a while it start to thinking, that one of LHR g-card (6th usually) is FHR... When ALL of g-cards from rig are assigned to lolminer, none of above is happening.

To be sure about the hashrate I recommend you check the review https://www.hashrate.no/tests/ampere

You will see not all Reported hashrate is reality at the pool. It is  a test 1Million share to determine how much miner overestimate their reported hashrate vs reality

**Comment by Sanchous98** [comment]
> Same for 3080 LHR. **1.47 lolminer HiveOS Kernel 5.10.0-hiveos #60, N470.103.01.** Actually one of g-card in my rig is non-LHR - so i was trying to use a different miner for it (gminer - higher hashrate 102 Mh/s - lolminer is giving me only 100,8 Mh/s for same OC). Basically: devices 0,1,2,3,4,6,7, - > lolminer (LHR g-cards) devices 5 - gminer (non-lhr g-card) But After a while it start to thinking, that one of LHR g-card (6th usually) is FHR... When ALL of g-cards from rig are assigned to lolminer, none of above is happening.

That seems to be the cause. I have one rx580 in the rig and it runs on Phoenix. I think that's why lolminer sometimes thinks that one card is FHR

**Comment by jgonzis** [comment]
> > Same for 3080 LHR. **1.47 lolminer HiveOS Kernel 5.10.0-hiveos #60, N470.103.01.** Actually one of g-card in my rig is non-LHR - so i was trying to use a different miner for it (gminer - higher hashrate 102 Mh/s - lolminer is giving me only 100,8 Mh/s for same OC). Basically: devices 0,1,2,3,4,6,7, - > lolminer (LHR g-cards) devices 5 - gminer (non-lhr g-card) But After a while it start to thinking, that one of LHR g-card (6th usually) is FHR... When ALL of g-cards from rig are assigned to lolminer, none of above is happening.
> 
> That seems to be the cause. I have one rx580 in the rig and it runs on Phoenix. I think that's why lolminer sometimes thinks that one card is FHR

Why not all lolMiner 😉

**Comment by Sanchous98** [comment]
> > > Same for 3080 LHR. **1.47 lolminer HiveOS Kernel 5.10.0-hiveos #60, N470.103.01.** Actually one of g-card in my rig is non-LHR - so i was trying to use a different miner for it (gminer - higher hashrate 102 Mh/s - lolminer is giving me only 100,8 Mh/s for same OC). Basically: devices 0,1,2,3,4,6,7, - > lolminer (LHR g-cards) devices 5 - gminer (non-lhr g-card) But After a while it start to thinking, that one of LHR g-card (6th usually) is FHR... When ALL of g-cards from rig are assigned to lolminer, none of above is happening.
> > 
> > 
> > That seems to be the cause. I have one rx580 in the rig and it runs on Phoenix. I think that's why lolminer sometimes thinks that one card is FHR
> 
> Why not all lolMiner 😉

Because phoenix is almost 1MH faster and consumes 7-8% less power)

**Comment by jgonzis** [comment]
> > > > Same for 3080 LHR. **1.47 lolminer HiveOS Kernel 5.10.0-hiveos #60, N470.103.01.** Actually one of g-card in my rig is non-LHR - so i was trying to use a different miner for it (gminer - higher hashrate 102 Mh/s - lolminer is giving me only 100,8 Mh/s for same OC). Basically: devices 0,1,2,3,4,6,7, - > lolminer (LHR g-cards) devices 5 - gminer (non-lhr g-card) But After a while it start to thinking, that one of LHR g-card (6th usually) is FHR... When ALL of g-cards from rig are assigned to lolminer, none of above is happening.
> > > 
> > > 
> > > That seems to be the cause. I have one rx580 in the rig and it runs on Phoenix. I think that's why lolminer sometimes thinks that one card is FHR
> > 
> > 
> > Why not all lolMiner 😉
> 
> Because phoenix is almost 1MH faster and consumes 7-8% less power, against every miner). At least if we are talking about Polaris cards

Could you check please hashrate.no/tests and you will understand why it is that 1Mhs.
