### ISSUE TITLE
0 Hashrate

### ISSUE THREAD

**Issue by Yusufiste** [Lolliedieb/lolMiner-releases#142]
I have gtx 1650 super but i have 0 hashrate and always says "Average speed (30s): 0.00 mh/s"
Please help

**Comment by Keimling27** [comment]
Normally cero only happens if your device have no power is it connect in pcie slot or raycer card.  How many gb has your card 4 or 8

**Comment by LVardis** [comment]
I have the same graphics card and I'm experiencing the same problem. The graphics card has 4GB VRAM and I've tried all possible fixes in the 4G_Windows_Readme file.

**Comment by jgonzis** [comment]
Same as https://github.com/Lolliedieb/lolMiner-releases/issues/170
