### ISSUE TITLE
3080TI - only 22 Mhs

### ISSUE THREAD

**Issue by NucleaR-II** [Lolliedieb/lolMiner-releases#1420]
Hello,

Thanks for the new miner and that you are trying to break LHR.

a 3080TI creates only 22MHs with me with the ver. 1.47
can I do something about it ? All other miners and versions work 

THANKS

![Lolminer](https://user-images.githubusercontent.com/90964949/160285355-9c9767aa-2c27-4337-bb29-b2b228c53957.jpg)

**Comment by Sanchous98** [comment]
https://github.com/Lolliedieb/lolMiner-releases/issues/1418

The same bug. Card is detected as FHR randomly

**Comment by NucleaR-II** [comment]
for me it says: inf
and 
re-calibrate unlocker. Doing so...

**Comment by jgonzis** [comment]
> Hello,
> 
> Thanks for the new miner and that you are trying to break LHR.
> 
> a 3080TI creates only 22MHs with me with the ver. 1.47 can I do something about it ? All other miners and versions work
> 
> THANKS
> 
> ![Lolminer](https://user-images.githubusercontent.com/90964949/160285355-9c9767aa-2c27-4337-bb29-b2b228c53957.jpg)

Could you reduce the memory OC? 
Also please  drivers 470.103.01 or 510.xx
And not delay OC

**Comment by sasi1212** [comment]
Here is the changelog of lolMiner v1.47.

> lolMiner v1.47 (improved ETH solver with up to 78% unlock; parameter --lhrtune now takes absolute % values to fix a certain percentage of unlocking; reduced Ton & Alephium fee in Eth+Ton / Ethash+Alephium dual mining to 0%; new --silence parameter controls the amount of information the miner will print during its work; added Nvidia memory junction temperature readings on cards that support this; fixed a bug with dual mining on LHR cards where the dual algorithm was mined with reduced rate after Ethash epoch change; fixed a bug with --compactaccept not showing the * sign on short statistics. NOTE: for more info on this update, check here: https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.47)

It says, `--lhrtune` takes % value now onwards. I was using `--lhrtune` earlier with the index 17 (previous valuesa are -40 to +40). With this update, `--lhrtune` recognizes 17 as 17%. So I faced low hash as you guys faced. What I did was added `--lhrtune 77` and getting great hashrate on my 3060Ti LHR cards.

Happy mining !

**Comment by jgonzis** [comment]
> Here is the changelog of lolMiner v1.47.
> 
> > lolMiner v1.47 (improved ETH solver with up to 78% unlock; parameter --lhrtune now takes absolute % values to fix a certain percentage of unlocking; reduced Ton & Alephium fee in Eth+Ton / Ethash+Alephium dual mining to 0%; new --silence parameter controls the amount of information the miner will print during its work; added Nvidia memory junction temperature readings on cards that support this; fixed a bug with dual mining on LHR cards where the dual algorithm was mined with reduced rate after Ethash epoch change; fixed a bug with --compactaccept not showing the * sign on short statistics. NOTE: for more info on this update, check here: https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.47)
> 
> It says, `--lhrtune` takes % value now onwards. I was using `--lhrtune` earlier with the index 17 (previous valuesa are -40 to +40). With this update, `--lhrtune` recognizes 17 as 17%. So I faced low hash as you guys faced. What I did was added `--lhrtune 77` and getting great hashrate on my 3060Ti LHR cards.
> 
> Happy mining !

Thx for reading the chanhelog... also fully recommended to not put values for lhrtune, you will block the max normally. Better let the miner get it

**Comment by tphan26363** [comment]
My 1080TI also not detected as LHR so it is mining at 60Mhs.  I use --lhr 100 and it get me to 85Mhs

**Comment by jgonzis** [comment]
> My 1080TI also not detected as LHR so it is mining at 60Mhs. I use --lhr 100 and it get me to 85Mhs

Without a photo of the full stats mining Information is impossible to help you.
0 info OS
0 info Drivers
0 info OC

I hope you can share it to try to help

**Comment by tphan26363** [comment]
Win10
driver 5.12
![Cap3](https://user-images.githubusercontent.com/53447108/161405040-5dccb2da-37ae-4ee9-8ce2-7a0a68260c83.png)
![Cap2](https://user-images.githubusercontent.com/53447108/161405041-1a4b9cc9-abbd-407b-a99e-5dd18dffe5ba.png)
![Cap1](https://user-images.githubusercontent.com/53447108/161405042-6c153bd3-919b-4236-be84-d9f102ac2d7d.png)

**Comment by jgonzis** [comment]
> Win10 driver 5.12 ![Cap3](https://user-images.githubusercontent.com/53447108/161405040-5dccb2da-37ae-4ee9-8ce2-7a0a68260c83.png) ![Cap2](https://user-images.githubusercontent.com/53447108/161405041-1a4b9cc9-abbd-407b-a99e-5dd18dffe5ba.png) ![Cap1](https://user-images.githubusercontent.com/53447108/161405042-6c153bd3-919b-4236-be84-d9f102ac2d7d.png)

Here I don't see any  1080TI. It seems all working. Also conservative values
