### ISSUE TITLE
Release notes:- question (power/volt efficiency)

### ISSUE THREAD

**Issue by nrpeyton** [Lolliedieb/lolMiner-releases#1422]
Hi,

In the release notes, you recommend locking the core clock.

My question is, how do I lock the core clock without losing power efficiency?

 Locking the voltage at the minimum while **simultaneously** setting a core overclock (using the **offset method**), allows maintaining a higher clock _without_ the higher power/current normally associated with those higher clocks.

Examples:

_(only locking core clock)_
```
Core: 1100
Voltage: 750
```

_(locking voltage + core offset)_
```
Core: 1350 (1100 + 250 offset)
Voltage: 750 
```

Thanks.

Nick

P.S
The difference with my method, is you are setting a HARD overclock (or a "REAL" overclock), in other words, you are getting something extra for nothing.

By only locking the core clock, you are not overclocking or underclocking your GPU, you're just telling the driver to look up the voltage/frequency table and set a "stock" (or "factory") voltage/frequency pair.  Further, it also eliminates the need to set max_power, (power depends on voltage)  `power = volts x amps`.

**Is there a way around this? _(electricity here $0.45 / kWh )_**

.

.

**Comment by jgonzis** [comment]
Offset don't move the lock Core.

Lock Core is to use Nvidia-smi -lgc 1350 for example

**Comment by nrpeyton** [comment]
Not sure I understand your response? Can you elaborate, please?

Many thanks.

**Comment by nrpeyton** [comment]
> Offset don't move the lock Core.
> 
> Lock Core is to use Nvidia-smi -lgc 1350 for example

Not sure I understand your response? Can you elaborate, please?

Many thanks.

**Comment by jgonzis** [comment]
> > Offset don't move the lock Core.
> > Lock Core is to use Nvidia-smi -lgc 1350 for example
> 
> Not sure I understand your response? Can you elaborate, please?
> 
> Many thanks.

To lock the core is nvidia-smi -lgc 1350   

The core offset doesn't affect. You need the previous parameter
