### ISSUE TITLE
lolMiner v1.47 keep retuning once every hour

### ISSUE THREAD

**Issue by kaitran1910** [Lolliedieb/lolMiner-releases#1424]
First of all, I'm much appreciated all of your hard works to bring us amazing LHR solver.

One of the issue I've got lately when updating to lolMiner v1.47 is the miner keep re-tuning the LHR once every 1 hour as observed:
![Screen Shot 2022-03-27 at 9 44 59 PM](https://user-images.githubusercontent.com/61256810/160312801-d3226e19-049f-4578-9363-d119c30a32ed.png)

Issued observed within lolMiner log:
Suddenly received a job with Epoch 0 as below:
![275789678_1261221314401966_6789063717886924485_n](https://user-images.githubusercontent.com/61256810/160311327-4ddde000-58b5-4f1d-88c5-96b8561a0d26.jpg)

Using NiceHash pool stratum+tcp://daggerhashimoto.usa-east.nicehash.com:3353 
Currently using HiveOS newest version.
Nvidia driver: 470.103.01

Same OC works fine in v1.46a version with driver 470.86
Issue only happened when updating HiveOS alongs with new lolMiner v1.47

**Comment by jgonzis** [comment]
> First of all, I'm much appreciated all of your hard works to bring us amazing LHR solver.
> 
> One of the issue I've got lately when updating to lolMiner v1.47 is the miner keep re-tuning the LHR once every 1 hour as observed: ![Screen Shot 2022-03-27 at 9 44 59 PM](https://user-images.githubusercontent.com/61256810/160312801-d3226e19-049f-4578-9363-d119c30a32ed.png)
> 
> Issued observed within lolMiner log: Suddenly received a job with Epoch 0 as below: ![275789678_1261221314401966_6789063717886924485_n](https://user-images.githubusercontent.com/61256810/160311327-4ddde000-58b5-4f1d-88c5-96b8561a0d26.jpg)
> 
> Using NiceHash pool stratum+tcp://daggerhashimoto.usa-east.nicehash.com:3353 Currently using HiveOS newest version. Nvidia driver: 470.103.01
> 
> Same OC works fine in v1.46a version with driver 470.86 Issue only happened when updating HiveOS alongs with new lolMiner v1.47

That's completely normal you are doing ZIL and you don't have --enablezilcache that means the DAG Generation creates a LHR Semiock. Try adding that... normally each DAG Change creates always a semilock

**Comment by kaitran1910** [comment]
Wait but I'm not even mining ZIL ...?
I'm dual mining ETH+TON. Will --enablezilcache mean anything in this scenario?

**Comment by jgonzis** [comment]
> Wait but I'm not even mining ZIL ...? I'm dual mining ETH+TON. Will --enablezilcache mean anything in this scenario?

No ... Nicehash will have several switch in case their pick your rig for other user

**Comment by kaitran1910** [comment]
Much appreciated.

After switching to other pool, the problem has gone.

**Comment by jgonzis** [comment]
> Much appreciated.
> 
> After switching to other pool, the problem has gone.

Many thanks for the feedback 😀 

Enjoy mining

**Comment by Rom66** [comment]
I have same issues with nicehash and eth, can i fix autotune, or - - enableethcache ? 
![Screenshot_20220329_005014_hiveos mobile](https://user-images.githubusercontent.com/102543084/160500620-0e93ef58-6e67-420b-adb8-9588269b6202.jpg)

**Comment by Rom66** [comment]
It seem to be ok with - - enablezilcache!
![Screenshot_20220329_064640_hiveos mobile](https://user-images.githubusercontent.com/102543084/160535441-d4d637b9-3390-469b-aa26-6dae215f224f.jpg)

**Comment by KevinCRM** [comment]
> Much appreciated.
> 
> After switching to other pool, the problem has gone.

I have the same problem mining ETH+TON, what pool did u change? Eth or Ton pool

**Comment by KevinCRM** [comment]
> It seem to be ok with - - enablezilcache! ![Screenshot_20220329_064640_hiveos mobile](https://user-images.githubusercontent.com/102543084/160535441-d4d637b9-3390-469b-aa26-6dae215f224f.jpg)

Where do u put that? I'm new on HiveOS 
Would work with ETH+TON mining?

**Comment by jgonzis** [comment]
> 

Yes for sure 1.47 will work with ETH +TON also... you can follow the guides from the YouTube Channel  to configure it

**Comment by KevinCRM** [comment]
> > 
> 
> Yes for sure 1.47 will work with ETH +TON also... you can follow the guides from the YouTube Channel to configure it

I mean the --enablezilcache 
Ihave the same issues about miner restarting every hour with ETH+TON

**Comment by kaitran1910** [comment]
> > > 
> > 
> > 
> > Yes for sure 1.47 will work with ETH +TON also... you can follow the guides from the YouTube Channel to configure it
> 
> I mean the --enablezilcache Ihave the same issues about miner restarting every hour with ETH+TON

For the previous question, I'm changing ETH pool.

If you want to stay on NiceHash, put the `--enablezilcache` in the Flight Sheet under `Extra config arguments` section as this example 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/61256810/160710149-7ff276ea-19b4-44a2-bcfd-d7fab21e02ff.png">

**Comment by ABredhauer** [comment]
I have the same issue and have been running with --enablezilcache

I am mining eth/zil using shardpool + ALPH I'm seeing regular drops in hash rate every hour despite having the zil cache option enabled

![image](https://user-images.githubusercontent.com/65760259/161409696-66c6e417-a8f3-4bd1-bf25-3dfd3962cc4c.png)

![image](https://user-images.githubusercontent.com/65760259/161409913-57b63ace-94ae-4d4f-8cca-4167ee257f0e.png)

**Comment by jgonzis** [comment]
> I have the same issue and have been running with --enablezilcache
> 
> I am mining eth/zil using shardpool + ALPH I'm seeing regular drops in hash rate every hour despite having the zil cache option enabled
> 
> ![image](https://user-images.githubusercontent.com/65760259/161409696-66c6e417-a8f3-4bd1-bf25-3dfd3962cc4c.png)
> 
> ![image](https://user-images.githubusercontent.com/65760259/161409913-57b63ace-94ae-4d4f-8cca-4167ee257f0e.png)

In AMD needs to be improved. In case LHR use 470.103.01 or 510.xx driver

**Comment by ABredhauer** [comment]
> > I have the same issue and have been running with --enablezilcache
> > I am mining eth/zil using shardpool + ALPH I'm seeing regular drops in hash rate every hour despite having the zil cache option enabled
> > ![image](https://user-images.githubusercontent.com/65760259/161409696-66c6e417-a8f3-4bd1-bf25-3dfd3962cc4c.png)
> > ![image](https://user-images.githubusercontent.com/65760259/161409913-57b63ace-94ae-4d4f-8cca-4167ee257f0e.png)
> 
> In AMD needs to be improved. In case LHR use 470.103.01 or 510.xx driver

This is with a 3060ti running the 510.60.02 driver

**Comment by jgonzis** [comment]
> > > I have the same issue and have been running with --enablezilcache
> > > I am mining eth/zil using shardpool + ALPH I'm seeing regular drops in hash rate every hour despite having the zil cache option enabled
> > > ![image](https://user-images.githubusercontent.com/65760259/161409696-66c6e417-a8f3-4bd1-bf25-3dfd3962cc4c.png)
> > > ![image](https://user-images.githubusercontent.com/65760259/161409913-57b63ace-94ae-4d4f-8cca-4167ee257f0e.png)
> > 
> > 
> > In AMD needs to be improved. In case LHR use 470.103.01 or 510.xx driver
> 
> This is with a 3060ti running the 510.60.02 driver

1.48 has improved eth+alph, it is always the same GPU?

**Comment by ABredhauer** [comment]
> > > > I have the same issue and have been running with --enablezilcache
> > > > I am mining eth/zil using shardpool + ALPH I'm seeing regular drops in hash rate every hour despite having the zil cache option enabled
> > > > ![image](https://user-images.githubusercontent.com/65760259/161409696-66c6e417-a8f3-4bd1-bf25-3dfd3962cc4c.png)
> > > > ![image](https://user-images.githubusercontent.com/65760259/161409913-57b63ace-94ae-4d4f-8cca-4167ee257f0e.png)
> > > 
> > > 
> > > In AMD needs to be improved. In case LHR use 470.103.01 or 510.xx driver
> > 
> > 
> > This is with a 3060ti running the 510.60.02 driver
> 
> 1.48 has improved eth+alph, it is always the same GPU?

Yeah just the single GPU in this rig at the moment. I’m waiting for hive to release an update that includes 1.48 to test with that version

**Comment by kaitran1910** [comment]
> 
If you know a bit about Linux command line, you can follow this to manually update the lolMiner to v1.48:
https://github.com/Lolliedieb/lolMiner-releases/discussions/1413#discussioncomment-2438121

Please note that the given guide is for updating from v1.46a to v1.47
You need to change the download link and directory accordingly

Here's my short note following that guide to manually update every single time
`miner stop
cd /tmp
wget /*download link*/
tar -xvf lol<tab>
cd /*directory*/
cp lolMiner /hive/miners/lolminer/<ver>
miner start`
Clarification for some placeholder in the code:
1. `/*download link*/` : the download link for the version you want to update to. In this v1.48 case on HiveOS, it should be `wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.48/lolminer-1.48.CustomHiveOS.tar.gz`
2. `<tab>` : here you can hit the Tab button on your keyboard to quickly generate the full file name. In this case, it should be `tar -xvf lolminer-1.48.CustomHiveOS.tar.gz` 
3. `/*directory*/` : go to the directory that's just been unzip. In this case, it should be `cd lolminer`
4. `/hive/miners/lolminer/<ver>` : depends on each version you currently have. Assuming you are using v1.47, then it should be `cp lolMiner /hive/miners/lolminer/1.47`

Sorry for the messy explanation. Let me know if you feel unclear 😄

**Comment by ABredhauer** [comment]
Thanks for the instructions, I've upgraded to 1.48 and will let it run for a few hours and report back

**Comment by ABredhauer** [comment]
Miner has been running for about 5 and a half hours on 1.48 now. Not seeing any significant difference in behaviour and still getting the hourly drops. The line below is roughly when I upgraded and restarted the miner

![image](https://user-images.githubusercontent.com/65760259/161472146-81d2da2b-341b-4930-ac46-f788be2915f4.png)

I captured 2 section of the logs - first when it switched from Eth to ZIL
![image](https://user-images.githubusercontent.com/65760259/161472257-08e530bb-1de9-4e65-9dd9-d99c3a9f5318.png)


And then when it switched back to zil
![image](https://user-images.githubusercontent.com/65760259/161472272-2af1668d-598e-4b06-b516-31ddc970c501.png)

**Comment by jgonzis** [comment]
> Miner has been running for about 5 and a half hours on 1.48 now. Not seeing any significant difference in behaviour and still getting the hourly drops. The line below is roughly when I upgraded and restarted the miner
> 
> ![image](https://user-images.githubusercontent.com/65760259/161472146-81d2da2b-341b-4930-ac46-f788be2915f4.png)
> 
> I captured 2 section of the logs - first when it switched from Eth to ZIL ![image](https://user-images.githubusercontent.com/65760259/161472257-08e530bb-1de9-4e65-9dd9-d99c3a9f5318.png)
> 
> And then when it switched back to zil ![image](https://user-images.githubusercontent.com/65760259/161472272-2af1668d-598e-4b06-b516-31ddc970c501.png)

Right... with nicehash DAG Changes can break that routine...

**Comment by ABredhauer** [comment]
I'm not using nicehash though? I'm using shardpool proxying ethermine

**Comment by jgonzis** [comment]
> I'm not using nicehash though? I'm using shardpool proxying ethermine

You should have --enablezilcache or you will have cuts

**Comment by ABredhauer** [comment]
please scroll up - I'm currently running with that enabled

**Comment by ABredhauer** [comment]
> > I'm not using nicehash though? I'm using shardpool proxying ethermine
> 
> You should have --enablezilcache or you will have cuts

Please scroll up, I already said I'm running with that option enabled

**Comment by jgonzis** [comment]
> > > I'm not using nicehash though? I'm using shardpool proxying ethermine
> > 
> > 
> > You should have --enablezilcache or you will have cuts
> 
> Please scroll up, I already said I'm running with that option enabled

Sorry... we will have a look to that double dag...

**Comment by ABredhauer** [comment]
> > > > I'm not using nicehash though? I'm using shardpool proxying ethermine
> > > 
> > > 
> > > You should have --enablezilcache or you will have cuts
> > 
> > 
> > Please scroll up, I already said I'm running with that option enabled
> 
> Sorry... we will have a look to that double dag...

All g, I'm sure you're across a lot of issues. Let me know if there's any logging I can enable to help

**Comment by AzrelixJ** [comment]
I am having the same issue with Dag rebuilds with ETH+ZIL+TON via Shardpool, every time the ZIL mining stops the dag rebuilds for ETH even though I have --enablezilcache set
![image](https://user-images.githubusercontent.com/84561314/163664006-a0a667d4-1e89-4513-bea9-65a6684baa05.png)
