### ISSUE TITLE
maxdualimpact arguments do not only take active cards

### ISSUE THREAD

**Issue by michalis97500** [Lolliedieb/lolMiner-releases#1425]
in my system i use
--devices 0,1,3,4,5,6 for all tests below : 
GPU2 is connected but doesn't mine. 

with --maxdualimpact 1,1,1,1,*,1 GPU5 still mines the 2nd algo and GPU 4 does not. 
with --maxdualimpact 1,1,1,1,1,*,1 GPU5 does not mine

I think that the argument position is mapped to the GPU connected instead of the one active in lolminer

**Comment by jgonzis** [comment]
> in my system i use --devices 0,1,3,4,5,6 for all tests below : GPU2 is connected but doesn't mine.
> 
> with --maxdualimpact 1,1,1,1,_,1 GPU5 still mines the 2nd algo and GPU 4 does not. with --maxdualimpact 1,1,1,1,1,_,1 GPU5 does not mine
> 
> I think that the argument position is mapped to the GPU connected instead of the one active in lolminer

To disable TON is:

`--maxdualimpact *,*,0,*` that will make gpu2 to make only eth and the rest eth+ton/alph

**Comment by michalis97500** [comment]
I am aware of what you are saying, but it is not what I said.

--devices 0,1,3,4,5,6
--maxdualimpact *,*,0,*,*,*

The above suggests that there are 6 GPUs connected to the system and GPU 3 will not dual mine. See, in devices the third argument is "3" and in maxdualimpact it is "0". But keep in mind that GPU 2 is excluded from active devices. In reality if you want to have these devices and NOT mine on GPU 3 you need : 

--devices 0,1,3,4,5,6
--maxdualimpact *,*,*,0,*,*,*

Devices with 6 arguments, maxdualimpact with 7. The n'th place in maxdualimapct corresponds to the GPU (n-1) instead of the active device

**Comment by jgonzis** [comment]
> 

Now I got it... so maxdualimpact doesn't count the select GPU it take all selected and not... Got it
