### ISSUE TITLE
Spiking "Reported Hashrate" on Flexpool using v1.47

### ISSUE THREAD

**Issue by m2internet** [Lolliedieb/lolMiner-releases#1426]
Firstly, thanks for the software. The most stable out of all the dual miners. 

I upgraded my HiveOS rig yesterday to the 1.47 version and ran my usual ETH + TON dual mining on Flexpool.io. Today i went back and noticed it was actually spiking in the charts for "reported hashrate". It would literally drop to 0 reported hashrate for like 5-10 minutes then back up to 440+-MH/s.

So i removed the only arg i added --silence and went back to 1.46a, and it worked just fine never spiking on the reported hashrate. So i changed nothing else but removing the --silence arg and going back to 1.46a.

![lolminer-147-bug1](https://user-images.githubusercontent.com/99066460/160325059-371e5c90-7de8-449e-933c-5e2a3efa889e.PNG)

**Comment by m2internet** [comment]
Forgot to mention:
- running on HiveOS latest version  5.10.0-hiveos #83 - OS version 0.6-213@220325
- three 3070 FHR's - Nvidia drivers 470.86
- seven 6600xt's - AMD drivers 20.40 (5.11.1001)

**Comment by jgonzis** [comment]
> Forgot to mention:
> 
> * running on HiveOS latest version  5.10.0-hiveos # 83 - OS version 0.6-213@220325
> * three 3070 FHR's - Nvidia drivers 470.86
> * seven 6600xt's - AMD drivers 20.40 (5.11.1001)

Many thanks, are you doing ETH+ZIL+TON?

**Comment by m2internet** [comment]
Just ETH + TON

**Comment by m2internet** [comment]
Noticed this today, even though FlexPool showed intermittent "reported hashrate" spikes/crashes, HiveOS reported no such spikes/crashes in hashrate for that same time:
![lolminer-bug1](https://user-images.githubusercontent.com/99066460/160430823-895641af-26d1-402f-9a38-bca1bccc5aa2.png)


Here is my "flight sheet" just for more data:
![lolminer-bug2](https://user-images.githubusercontent.com/99066460/160431027-67357e4b-2599-46b7-a781-44290d2ff768.png)

**Comment by m2internet** [comment]
Gonna switch over again soon, will try v1.47 again and let you know

**Comment by jgonzis** [comment]
> Gonna switch over again soon, will try v1.47 again and let you know

Thx 😊

**Comment by fenomentn** [comment]
hello,
i have the same problem on hiveos after update to version 1.47 on flexpool
i try to change the driver but the same problem
[
<img width="1069" alt="Screen Shot 2022-03-28 at 11 03 01 PM" src="https://user-images.githubusercontent.com/99438899/160495023-599c5beb-e84c-42d5-bb41-5494bb732c86.png">
](url)

**Comment by jgonzis** [comment]
> hello, i have the same problem on hiveos after update to version 1.47 on flexpool i try to change the driver but the same problem [ <img alt="Screen Shot 2022-03-28 at 11 03 01 PM" width="1069" src="https://user-images.githubusercontent.com/99438899/160495023-599c5beb-e84c-42d5-bb41-5494bb732c86.png"> ](url)

That is HiveOS API check the pool please. Yesterday it was a hard day for HiveOS Servers

**Comment by fenomentn** [comment]
i don't see much in the pool but in hiveos there is spikes about 10 min delay and the graph from today 
<img width="1154" alt="Screen Shot 2022-03-28 at 11 21 34 PM" src="https://user-images.githubusercontent.com/99438899/160496928-e96dfce0-289e-41cd-ac58-1d0eadee521e.png">
<img width="1245" alt="Screen Shot 2022-03-28 at 11 15 58 PM" src="https://user-images.githubusercontent.com/99438899/160496999-957284aa-0035-4204-aa39-839c6dfe2ba5.png">

**Comment by jgonzis** [comment]
> i don't see much in the pool but in hiveos there is spikes about 10 min delay and the graph from today <img alt="Screen Shot 2022-03-28 at 11 21 34 PM" width="1154" src="https://user-images.githubusercontent.com/99438899/160496928-e96dfce0-289e-41cd-ac58-1d0eadee521e.png"> <img alt="Screen Shot 2022-03-28 at 11 15 58 PM" width="1245" src="https://user-images.githubusercontent.com/99438899/160496999-957284aa-0035-4204-aa39-839c6dfe2ba5.png">

Pool.is perfect... HiveOS is not perfect hehe 

They have server problems...

**Comment by fenomentn** [comment]
> > i don't see much in the pool but in hiveos there is spikes about 10 min delay and the graph from today <img alt="Screen Shot 2022-03-28 at 11 21 34 PM" width="1154" src="https://user-images.githubusercontent.com/99438899/160496928-e96dfce0-289e-41cd-ac58-1d0eadee521e.png"> <img alt="Screen Shot 2022-03-28 at 11 15 58 PM" width="1245" src="https://user-images.githubusercontent.com/99438899/160496999-957284aa-0035-4204-aa39-839c6dfe2ba5.png">
> 
> Pool.is perfect... HiveOS is not perfect hehe
> 
> They have server problems...

yeah i see now there is spikes problem in hiveos server i hope they fix it soon

![image](https://user-images.githubusercontent.com/99438899/160499785-d72ce91f-7cf6-45f8-9eb0-d0d71eb59edd.png)

thanks

**Comment by m2internet** [comment]
Ok, I have pinpointed the issue that caused my spike on FlexPool's graphs. It was because I changed the "global_config.conf" in 1.46 to minimalize the stats output. This must be conflicting with the new "--silence" feature added to 1.47.

I had my global_config.conf set to:
`--timeprint 1 --shortstats 0 --longstats 900 --basecolor  `

The "crash" in the hashrate happens exactly at the "longstats" trigger at 900 seconds/15 minutes mark. And this shows on the FlexPool graph as the crash in reported hashrate.

In this snapshot:
- **RED** is the global_config.conf changed to my settings 
- **YELLOW** is the default settings for global_config.conf 
![lolminer-147-bug2](https://user-images.githubusercontent.com/99066460/160682882-b7c8516c-8810-4840-89e6-681b20da73b3.PNG)

So if i don't modify the global_config.conf settings, the 1.47 miner works fine. Otherwise there is some conflict.

**Comment by jgonzis** [comment]
> Ok, I have pinpointed the issue that caused my spike on FlexPool's graphs. It was because I changed the "global_config.conf" in 1.46 to minimalize the stats output. This must be conflicting with the new "--silence" feature added to 1.47.
> 
> I had my global_config.conf set to: `--timeprint 1 --shortstats 0 --longstats 900 --basecolor `
> 
> The "crash" in the hashrate happens exactly at the "longstats" trigger at 900 seconds/15 minutes mark. And this shows on the FlexPool graph as the crash in reported hashrate.
> 
> In this snapshot:
> 
> * **RED** is the global_config.conf changed to my settings
> * **YELLOW** is the default settings for global_config.conf
>   ![lolminer-147-bug2](https://user-images.githubusercontent.com/99066460/160682882-b7c8516c-8810-4840-89e6-681b20da73b3.PNG)
> 
> So if i don't modify the global_config.conf settings, the 1.47 miner works fine. Otherwise there is some conflict.

Many thanks for the feedback
