### ISSUE TITLE
Much different hashrates while dual mining ETH and TON

### ISSUE THREAD

**Issue by KaeMs** [Lolliedieb/lolMiner-releases#1427]
I've just started testing ETH+TON mining using 3060ti LHR and got weird result

![image](https://user-images.githubusercontent.com/16589750/160346844-ffd5d009-5bb9-488e-acd8-3d3f6bb385ef.png)

I've researched that for 3060ti I should've gotten about 2GH/s for Solo mining, and prolly around 1GH/s for dual mining right?

![image](https://user-images.githubusercontent.com/16589750/160347232-07a0f693-5408-4c46-8b75-c882052694d3.png)

But as shown by my first image, it's not the case, I even got very low values for MHs. Some has even lower than 20 MH/s

For extra info here's my rig overclocking settings
![image](https://user-images.githubusercontent.com/16589750/160347460-d0fccb44-c36f-48a9-8e43-641069286478.png)

Is there anything wrong with my settings or something else?

**Comment by KaeMs** [comment]
Oh and I'm running on

- Hive OS 0.6-213@220325
- Latest Version for Miner Config

**Comment by EricKeong** [comment]
Just push up your power limit or just let it be unlimited since you are using lock core clock. Then hashrate should be fine.

**Comment by KaeMs** [comment]
> 

Yes I did that in the beginning, but it doesn't do much, only raised the hashrate by a bit, and still too much difference between each GPU, 2 GPUs got around 100-102 MHs, the others only 44-46 ish MHs

**Comment by KaeMs** [comment]
Nevermind, actually it was my memory limit that makes the miner for TON not gaining the right amount of MHs, I set it to empty, and even limited the power to 150, and everything works better now

**Comment by jgonzis** [comment]
Nice to see it... PL is better always to 0, and work only with Lock Core. It is the best way to do it :-)
