### ISSUE TITLE
3060Ti LHR not unlocking

### ISSUE THREAD

**Issue by DanielMck05** [Lolliedieb/lolMiner-releases#1429]
I have an MSI 3060TI LHR that has always been a problem child, and never been able to get over 38MH/s, while other cards were always at 44-45. This GPU in lolminer 1.47 will not unlock past 58%, and the miner constantly says "need to recalibrate un-locker. doing so..." but the value never changes, and the hashrate is always fluctuating between 10-25MH/s. Terrible.

**Comment by jgonzis** [comment]
> I have an MSI 3060TI LHR that has always been a problem child, and never been able to get over 38MH/s, while other cards were always at 44-45. This GPU in lolminer 1.47 will not unlock past 58%, and the miner constantly says "need to recalibrate un-locker. doing so..." but the value never changes, and the hashrate is always fluctuating between 10-25MH/s. Terrible.

As the collegue say: 

Run nvidia-driver-update 470.103.01   it takes time in a USB so keep calm.

Look to his Cclk, he is well using the Lock Core in this case to 1395, good Clock for the 3060TI.

**Comment by DanielMck05** [comment]
This is not fixed and closed out, not sure why you closed it. I am using Driver 470.103.01, and I have left it for several hours. I have also tried every overclock configuration I can, including NO Overclocks at all, Power limit only, and I have tried core clock locked between 1400-1600, and memory overclocks from 1000 up to 2600, but no difference is shown.

The only reason I posted it here is because I have been using T-rex and Gminer reliably for months with it unlocked at 73% at 38MH/s, but lolminer wont unlock over 58% and 25-30MH/s at MAX, and just keeps saying "need to recalibrate un-locker. doing so..." but the value never changes.

**Comment by jgonzis** [comment]
> This is not fixed and closed out, not sure why you closed it. I am using Driver 470.103.01, and I have left it for several hours. I have also tried every overclock configuration I can, including NO Overclocks at all, Power limit only, and I have tried core clock locked between 1400-1600, and memory overclocks from 1000 up to 2600, but no difference is shown.
> 
> The only reason I posted it here is because I have been using T-rex and Gminer reliably for months with it unlocked at 73% at 38MH/s, but lolminer wont unlock over 58% and 25-30MH/s at MAX, and just keeps saying "need to recalibrate un-locker. doing so..." but the value never changes.

Could you please show Full OC and the Stats of HiveOS?

Also.closed I wait your answer I'm been advised

**Comment by Rom66** [comment]
Leave power limit and let lolminer ajust power.

**Comment by DanielMck05** [comment]
I've got some more time to mess with it, and I have found that if I set my FHR cards on T-rex, and my LHR cards on lolminer 1.47, then the 3060 TI gets up to almost 41MH/s. But If i have all 12 cards (7 LHR, 5 FHR), on lolminer, then it does like mentioned above.

Attached is my overclock settings in hiveos.
![3060TI](https://user-images.githubusercontent.com/102536592/160854933-2442a6ec-ca23-4564-98bf-593d656fce52.png)

**Comment by jgonzis** [comment]
> Well, now its not working even when seperate. The rig just rebooted for no reason, with no error messages, and now it wont go over 57.7% again. Its been running for over 30 min, and all it says is, "GPU 7: need to re-calibrate unlocker. Doing so..." but nothing happens. You can also see the hashrate fluctuation.
> 
> ![Stats 2](https://user-images.githubusercontent.com/102536592/160870255-ce04aa03-6a33-4a96-a49e-ec6a4b2be8a6.png)

I saw that rig in Telegram... the new version tunning I hope it solves it. Also could you try to change the riser?
