### ISSUE TITLE
Error when allocating memory or building DAG. Disabling card

### ISSUE THREAD

**Issue by kavdav** [Lolliedieb/lolMiner-releases#1432]
Error when allocating memory or building DAG. Disabling card
version: Lolminer 1.46a
Windows 10
![C__Windows_system32_cmd exe 28  03  2022 20_03_51 (2)](https://user-images.githubusercontent.com/82096313/160461010-d99fe10d-529a-4f21-8335-28c86cf343ca.png)

Pls help :)

**Comment by jgonzis** [comment]
> Error when allocating memory or building DAG. Disabling card version: Lolminer 1.46a Windows 10 ![C__Windows_system32_cmd exe 28 03 2022 20_03_51 (2)](https://user-images.githubusercontent.com/82096313/160461010-d99fe10d-529a-4f21-8335-28c86cf343ca.png)
> 
> Pls help :)

Please increase your Windows Virtual Disk... 

https://support.esri.com/en/technical-article/000002245#:~:text=Windows%207%2C%20Windows%20Server%202008%20and%20Windows%20Vista%3A&text=Click%20Settings%20under%20Performance.,and%20Maximum%20size%20(MB).

**Comment by kavdav** [comment]
Tnx for help:)

**Comment by jgonzis** [comment]
> Tnx for help:)

Thx for the feedback
