### ISSUE TITLE
Not unlocking LHR on RTX 3070ti

### ISSUE THREAD

**Issue by Samciak** [Lolliedieb/lolMiner-releases#1435]
I have a rig of 8 rtx 3070ti and one of the card cant be unlocked as others. Im using hive os with nvidia driver 470.103.01. Other 7 card are running really good under new unlocker but this card not. I left it running for a whole night and it was not able to unlock the card. The hashrate was ranged between 20-52mhs and thats really bad for rtx 3070ti. Cards are not overheating and and I dont have problem with unlocking this card in other miners. For now I switched to trex miner beacause im getting only 1mhs less per card and it can unlock every card for the same hashrate. Can you please help me fix the problem?

**Comment by IMarkoMC** [comment]
Try upgrading your driver to the recommended ones.
![image](https://user-images.githubusercontent.com/44303652/160721237-c53d2684-adb4-42eb-916d-90fb6b659b0d.png)
I'm getting a stable 58mh/s

**Comment by Samciak** [comment]
I can mine 59-60mhs with Trex miner and it is stable. Try my oc if you want. And 470.103.01 is really bad driver for mining. Actually lol miner is more stable for me with driver 470.74. I will try 510.60.02 later if it solves my problem. But I think it is just lolminer bug. Im using Trex miner for card which cannot be unlocked in lol and rest of the cards are in lol. I hope that they will fix this soon because it is annoying that it cannot be unlocked at all. And it is not overheating ,my memory temps are under 95 all the time. 
<img width="1223" alt="Snímka obrazovky 2022-03-30 o 11 01 12" src="https://user-images.githubusercontent.com/68124717/160793895-569eb31b-b145-4826-94de-27875116b6d2.png">
<img width="717" alt="Snímka obrazovky 2022-03-30 o 11 03 28" src="https://user-images.githubusercontent.com/68124717/160794384-c6401397-ae43-4288-8511-45547e17954f.png">

**Comment by cool2hatex** [comment]
Did it solve the problem? I mean driver update. I have same issues with 3080 and 3080ti

**Comment by Samciak** [comment]
No and Yes but basically no. Do what I did. Use driver 470.74 and use cards which works on lol and which not use in Trex. It is not perfect but it works.

**Comment by jgonzis** [comment]
> Did it solve the problem? I mean driver update. I have same issues with 3080 and 3080ti

Try pllease that OC:

Core 1080
Memory 2000
PL to 0 

It has been reported that the LHR detection in 1.47 hasn't considered really high Memory OC... That could be the problem. Could you make a try?

**Comment by Samciak** [comment]
Didn't help. I tried it on multiple drivers. It just lowered my hashrate. I don't understand why is this happening. Because I have 8 rtx 3070ti from the same brand the same model and 1 of them cannot be unlocked which is not even the one that has bad silicon lottery.

**Comment by jgonzis** [comment]
> Didn't help. I tried it on multiple drivers. It just lowered my hashrate. I don't understand why is this happening. Because I have 8 rtx 3070ti from the same brand the same model and 1 of them cannot be unlocked which is not even the one that has bad silicon lottery.

Try to change the riser... I suppose you don't have OC Delay

**Comment by Samciak** [comment]
No, I don't have OC delay. And I can't change the riser because the card is in the MOBO. Maybe that's the problem man. Maybe it cannot unlock cards in the motherboard. Because all other cards are in risers. But I don't have left space after I recently added 1060 to my rig I need to kick it out and try to put it in riser. I will inform you how it went this evening. And also I noticed that when you try high memory clock the trex unlocker is cathing up. Your unlocker work well in low memory clocks but when you push harder on memory there is not big diffrence in unlock compare to trex. At least in my case. But I can push hard on memory because it is cold outside(3°C, rn) but in summer Iam F because during day outside will be 30°C and more so i will not be able to push on cards.
<img width="1295" alt="Snímka obrazovky 2022-04-02 o 17 48 34" src="https://user-images.githubusercontent.com/68124717/161391134-c564e950-7e62-42a1-ae95-c319dcda6785.png">

<img width="1300" alt="Snímka obrazovky 2022-04-02 o 17 48 39" src="https://user-images.githubusercontent.com/68124717/161391144-083bb52a-3c82-4595-9e7f-0d8900ef3116.png">

**Comment by jgonzis** [comment]
> No, I don't have OC delay. And I can't change the riser because the card is in the MOBO. Maybe that's the problem man. Maybe it cannot unlock cards in the motherboard. Because all other cards are in risers. But I don't have left space after I recently added 1060 to my rig I need to kick it out and try to put it in riser. I will inform you how it went this evening. And also I noticed that when you try high memory clock the trex unlocker is cathing up. Your unlocker work well in low memory clocks but when you push harder on memory there is not big diffrence in unlock compare to trex. At least in my case. But I can push hard on memory because it is cold outside(3°C, rn) but in summer Iam F because during day outside will be 30°C and more so i will not be able to push on cards. <img alt="Snímka obrazovky 2022-04-02 o 17 48 34" width="1295" src="https://user-images.githubusercontent.com/68124717/161391134-c564e950-7e62-42a1-ae95-c319dcda6785.png">
> 
> <img alt="Snímka obrazovky 2022-04-02 o 17 48 39" width="1300" src="https://user-images.githubusercontent.com/68124717/161391144-083bb52a-3c82-4595-9e7f-0d8900ef3116.png">

That could  be... but also you haven't tested 510.60 or 470.103.01 to see if helps. Also in mobo could be a factor too

**Comment by Samciak** [comment]
I tried 470.103.01 and 510.54 And it didn't help. I haven't tried yet to put the card into the riser because I don't have a rig at home and I didn't make it yesterday but I will try it soon as possible and let you know. Thanks for helping.

**Comment by jgonzis** [comment]
> I tried 470.103.01 and 510.54 And it didn't help. I haven't tried yet to put the card into the riser because I don't have a rig at home and I didn't make it yesterday but I will try it soon as possible and let you know. Thanks for helping.

I hope you can put the full stats mining with all the information to see extra information

**Comment by IMarkoMC** [comment]
Pushing the mem that hard wont help you at all

**Comment by Samciak** [comment]
<img width="1328" alt="Snímka obrazovky 2022-04-17 o 20 36 21" src="https://user-images.githubusercontent.com/68124717/163727891-03664d4c-fbfa-47f4-865c-2d13bf05d0be.png">
Whatever Trex miner did. Everything works as should. Dont even have problem with unlocking. It was just lolminer problem
