### ISSUE TITLE
10-minute interruptions

### ISSUE THREAD

**Issue by Blues2121** [Lolliedieb/lolMiner-releases#1437]
Hi,
With the 1.47 version, there are 10-minute interruptions? What is the reason of this?

![Ekran görüntüsü 2022-03-29 204209](https://user-images.githubusercontent.com/101578367/160673401-412459c4-3e95-41f4-8978-b916a8424211.png)
Hiveos,
2miner,
3070 ti,
Nvidia: 470.103.01,
Mem:2400,
Cor:965,
PL:0,

**Comment by Komayo** [comment]
Happening the same here on all my 11 rigs. :(

**Comment by Npro13** [comment]
maybe it's a bug hiveOS
Sorry, I do not know English well

**Comment by jgonzis** [comment]
It is right HiveOS server are out 15%.... at the moment. It is HiveOS Problem we hope it is soon solved .

Always check at the pool never HiveOS

**Comment by Blues2121** [comment]
Thank you for the information,
