### ISSUE TITLE
Lolminer 1.47 mining at 0mh/s

### ISSUE THREAD

**Issue by FukenRonald** [Lolliedieb/lolMiner-releases#1438]
Hi, so I've been testing LolMiner1.47 on HiveOs with nvidia driver 510.60.02 and all my cards are mining at 0 mh/s. 
I have 3x 3060tiLHR and 1x 2060 6gb.
I have no problem mining with other miners.
So my question is, what the fuk is wrong??

**Comment by telix11** [comment]
I have the same Problem. Dual minning ETH+ALPH and see 0mh/s

**Comment by jgonzis** [comment]
> I have the same Problem. Dual minning ETH+ALPH and see 0mh/s

With ETH+ALPH it is know a bug... fixed in the Beta 1.48... 



> Hi, so I've been testing LolMiner1.47 on HiveOs with nvidia driver 510.60.02 and all my cards are mining at 0 mh/s. I have 3x 3060tiLHR and 1x 2060 6gb. I have no problem mining with other miners. So my question is, what the fuk is wrong??

Could you share the OC and what the miner said ? to have some informaiton to know where could be the problem?

**Comment by FukenRonald** [comment]
I tried is with no oc too and it was mining at 0mh/s. The Miner wasn't saying anything except showing my cards mining at 0mh/s, like it wasn't a problem.

**Comment by toolpusher13** [comment]
![nie kopie](https://user-images.githubusercontent.com/80599507/161402706-072ce285-12e0-4c93-aa9c-54bf869bbd36.png)
Please can you check the file. I am running Lol on Hive but cant run on Windows. Same problem  - 0 hashrate

**Comment by jgonzis** [comment]
> ![nie kopie](https://user-images.githubusercontent.com/80599507/161402706-072ce285-12e0-4c93-aa9c-54bf869bbd36.png) Please can you check the file. I am running Lol on Hive but cant run on Windows. Same problem - 0 hashrate

I think your problem is the eth SSL configuration:

You did it perfectly, but you put and ssl pool port and should be add or change to port 4444 or add --tls on or put ssl://eth-de.flexpool.io:5555

3.options

**Comment by toolpusher13** [comment]
Yes you are right. I have been already replied with the same answer on your discord channel. Thanks anyway.
