### ISSUE TITLE
1.47 mining ETH+Ton with driver version 470.103.01 and 510.x never stop re-calibrating

### ISSUE THREAD

**Issue by naplesblue** [Lolliedieb/lolMiner-releases#1440]
I tried highly recommended driver v470.103.01 and 510.x with 1.47 dual mining eth+ton over a night. It seems miner could never reach a stable calibration number. 
![QQ20220330-091233@2x](https://user-images.githubusercontent.com/44143000/160731304-47ea5ba8-ec26-41fd-8296-f1956bb5d7b2.jpg)
Those up and downs was newer driver with 1.47.

I switched back to driver version 470.86, miner takes less than 5 mins getting the maximum unlock rate. Not that stable but much better with recommended nvidia driver.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/44143000/160731667-bcdd7a42-73c2-49fe-986a-906bd289868d.png">

**Comment by Rom66** [comment]
Look this and try: - - enablezilcache command
https://github.com/Lolliedieb/lolMiner-releases/issues/1424

**Comment by naplesblue** [comment]
@Rom66 Thanks. I am using ethermine pool and ton-pool for dual mining, I think I could get --enablezilcache a try.

**Comment by Samciak** [comment]
@naplesblue have you try it yet? it helped or not?

**Comment by jgonzis** [comment]
> I tried highly recommended driver v470.103.01 and 510.x with 1.47 dual mining eth+ton over a night. It seems miner could never reach a stable calibration number. ![QQ20220330-091233@2x](https://user-images.githubusercontent.com/44143000/160731304-47ea5ba8-ec26-41fd-8296-f1956bb5d7b2.jpg) Those up and downs was newer driver with 1.47.
> 
> I switched back to driver version 470.86, miner takes less than 5 mins getting the maximum unlock rate. Not that stable but much better with recommended nvidia driver. <img alt="image" width="1135" src="https://user-images.githubusercontent.com/44143000/160731667-bcdd7a42-73c2-49fe-986a-906bd289868d.png">

New 1.48 will come with a new tunning for DUAL... At least the good information that also old drivers solved the problem.

**Comment by cool2hatex** [comment]
At 1.48 i have similar issue. It works perfect for sometime and says gpu needs re-calibrate and then enter re-calibration loop for every 5 minutes. Driver was 512.15

**Comment by jgonzis** [comment]
> At 1.48 i have similar issue. It works perfect for sometime and says gpu needs re-calibrate and then enter re-calibration loop for every 5 minutes. Driver was 512.15

Could you show the full stats of the miner? I suppose you are using Lock Core and leaving miner alone?

**Comment by cool2hatex** [comment]
I figured it out. It turned out when i log off from remote connection ram speed drops to 4996. I login back (with remote program) ram speed recovers and everything works fine until i log out again. All win11 settings preventing sleep. For now i locked memory with minerstat and seems like fine. I checked pci slot etc. none at power save mode. I think this can be special for win11. Btw other miner programs working normal in same case.

**Comment by ian0808** [comment]
--enablezilcache works
![enablezilcache](https://user-images.githubusercontent.com/102851666/161373290-56d188a8-2b90-4b67-99d7-0facddfb5691.png)

**Comment by jgonzis** [comment]
> I figured it out. It turned out when i log off from remote connection ram speed drops to 4996. I login back (with remote program) ram speed recovers and everything works fine until i log out again. All win11 settings preventing sleep. For now i locked memory with minerstat and seems like fine. I checked pci slot etc. none at power save mode. I think this can be special for win11. Btw other miner programs working normal in same case.

Did it work the P0 state?



> --enablezilcache works ![enablezilcache](https://user-images.githubusercontent.com/102851666/161373290-56d188a8-2b90-4b67-99d7-0facddfb5691.png)

Really good photo

**Comment by naplesblue** [comment]
> @naplesblue have you try it yet? it helped or not?

No. It didn't work. Waiting for hiveos update with 1.48.

**Comment by jgonzis** [comment]
> > @naplesblue have you try it yet? it helped or not?
> 
> No. It didn't work. Waiting for hiveos update with 1.48.

Try reducing a little bit the core or memory too. Also that gpu is in mobo? 

I suppose HiveOS will update soon

**Comment by naplesblue** [comment]
updated hiveos with 1.48, still the same. I am using 3080lhr and 3060ti lhr.

![QQ20220404-185801@2x](https://user-images.githubusercontent.com/44143000/161531332-c497d604-b109-4711-9257-a21de11be129.jpg)

**Comment by jgonzis** [comment]
> updated hiveos with 1.48, still the same. I am using 3080lhr and 3060ti lhr.
> 
> ![QQ20220404-185801@2x](https://user-images.githubusercontent.com/44143000/161531332-c497d604-b109-4711-9257-a21de11be129.jpg)

Interesting... 

Could you show the full stats from the miner. That seems not unlocking properly
