### ISSUE TITLE
Mining ETH+TON+ZIL on different pools

### ISSUE THREAD

**Issue by Parham2004** [Lolliedieb/lolMiner-releases#1441]
Hi,

I was wondering is it possible to mine Ethereum , Toncoin/Alephum and Zilliqa at same time on different pools? 
(For Example : ETH = Ethermine / Zil = ezill / TON = ton-pool)
the lolMiner has --dualmode zil that make possible to mine ETH+ZIL without proxy mode and on pool that doesn't have proxy mode but as I'm using the --dual mode TONCOIN, I think is not possible to use both at same time because the --dualpool , --dualuser and ... parameters can't be use at same time.
I'm already using the shardpool proxy mode but I was wondering if using --dualmode zil beside the --dualmode toncoin is possible could this feature add in future updates?

**Comment by jgonzis** [comment]
> Hi,
> 
> I was wondering is it possible to mine Ethereum , Toncoin/Alephum and Zilliqa at same time on different pools? (For Example : ETH = Ethermine / Zil = ezill / TON = ton-pool) the lolMiner has --dualmode zil that make possible to mine ETH+ZIL without proxy mode and on pool that doesn't have proxy mode but as I'm using the --dual mode TONCOIN, I think is not possible to use both at same time because the --dualpool , --dualuser and ... parameters can't be use at same time. I'm already using the shardpool proxy mode but I was wondering if using --dualmode zil beside the --dualmode toncoin is possible could this feature add in future updates?

You can do it using direct ETH Pool of Ezil.Me the easy way... or use proxy servers like Rustpool or shardpool. 

But remember PLEASE PLEASE... add --enablezilcache

**Comment by m2internet** [comment]
I'm tyring to do this as well and missing something...im sure its obvious, hopefully you can help/point me in the right direction. 

**Error:  Worker not authorized. Authorization problem on all configured pools.**

I'm on the latest version/update of HiveOS as of 4/1/2022. Below is my version ifno, flightsheet, & lolminer output error I'm getting:

![Screenshot 2022-04-01 124616](https://user-images.githubusercontent.com/99066460/161307148-8af34dfe-8e32-4c66-87c7-7aaa1f66721c.jpg)
![Screenshot 2022-04-01 124327](https://user-images.githubusercontent.com/99066460/161306755-820621db-8324-419e-8c00-634d9f4b9b33.jpg)
![Screenshot 2022-04-01 124354](https://user-images.githubusercontent.com/99066460/161307367-20c91bef-d548-4746-9b96-2255dd07da66.jpg)

**Comment by jgonzis** [comment]
> I'm tyring to do this as well and missing something...im sure its obvious, hopefully you can help/point me in the right direction.
> 
> **Error: Worker not authorized. Authorization problem on all configured pools.**
> 
> I'm on the latest version/update of HiveOS as of 4/1/2022. Below is my version ifno, flightsheet, & lolminer output error I'm getting:
> 
> ![Screenshot 2022-04-01 124616](https://user-images.githubusercontent.com/99066460/161307148-8af34dfe-8e32-4c66-87c7-7aaa1f66721c.jpg) ![Screenshot 2022-04-01 124327](https://user-images.githubusercontent.com/99066460/161306755-820621db-8324-419e-8c00-634d9f4b9b33.jpg) ![Screenshot 2022-04-01 124354](https://user-images.githubusercontent.com/99066460/161307367-20c91bef-d548-4746-9b96-2255dd07da66.jpg)
> 
> thx in advance

That I know it :-)

Please put the %WORKER_NAME%  in ton inthe worker name text box. And leave only %WAL% in Wallet.

It is a small changes in 1.48 sorry for the inconvenience...

**Comment by m2internet** [comment]
Hey I tried that, still the same issue. Tried all different combos of moving around the worker name as well.
