### ISSUE TITLE
PCIE_Address in API as hex address

### ISSUE THREAD

**Issue by cryptopoo** [Lolliedieb/lolMiner-releases#1442]
Hello!

I would like to propose to have PCIE_Address field populated in hexadecimal format like `lspci` reports, for instance:
```
lspci  | grep VGA
13:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT / 6800M] (rev c1)
```

However, in lolminer 1.47 API, I get the following addresses:

```
curl -s "http://127.0.0.1:44444/summary"  | grep PCIE_Address

            "PCIE_Address": "19:0"
```

So PCIE_Address right now is a decimal and would be nice if it would be in hexadecimal (since is an address, and addresses are nice in hex format).

Would like to hear what you think! Cheers!

**Comment by jgonzis** [comment]
> Hello!
> 
> I would like to propose to have PCIE_Address field populated in hexadecimal format like `lspci` reports, for instance:
> 
> ```
> lspci  | grep VGA
> 13:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT / 6800M] (rev c1)
> ```
> 
> However, in lolminer 1.47 API, I get the following addresses:
> 
> ```
> curl -s "http://127.0.0.1:44444/summary"  | grep PCIE_Address
> 
>             "PCIE_Address": "19:0"
> ```
> 
> So PCIE_Address right now is a decimal and would be nice if it would be in hexadecimal (since is an address, and addresses are nice in hex format).
> 
> Would like to hear what you think! Cheers!

Hi!!! We meet here ;-) haha... 

I suppose for the autofan function you apply ...  Let me comment with the DEV if he can do it :-)

**Comment by cryptopoo** [comment]
Hello !

Not a big problem for me, I have implemented all that is needed for my purpose. Was more talking about a consistent way, also for others to use this address without too much manipulation.

Basically it would either make sense to have the pcie bus id as a pure integer (decimal) or in a "pcie address" format that is standard to other implementations (like lspci) :) This way other devs could have some data they are more familiar to manage / handle :)

Just my two cents :v:

**Comment by jgonzis** [comment]
> Hello !
> 
> Not a big problem for me, I have implemented all that is needed for my purpose. Was more talking about a consistent way, also for others to use this address without too much manipulation.
> 
> Basically it would either make sense to have the pcie bus id as a pure integer (decimal) or in a "pcie address" format that is standard to other implementations (like lspci) :) This way other devs could have some data they are more familiar to manage / handle :)
> 
> Just my two cents ✌️

It is completely right... I will give the information to Lolliedieb, or if you want to comment directly sure you can found him also in the Telegram group.

**Comment by jgonzis** [comment]
Problem about PCI Hex, we asked different Mining OS and that make to change the parser and also checking that depending the version is one or the other... So complicated until new API is done.

**Comment by cryptopoo** [comment]
Makes total sense, I imagine many users already parsed that value that way, so indeed a new API or field would be needed for this. Thanks for looking into it!

**Comment by jgonzis** [comment]
> Makes total sense, I imagine many users already parsed that value that way, so indeed a new API or field would be needed for this. Thanks for looking into it!

Thx to you. About your script, did many people use it?.

**Comment by cryptopoo** [comment]
Well, I guess so. While I cannot say how many people installed it I can say that at least 9k unique visitors opened the project.
So overall not bad. Donation-wise it was very poor, unfortunately. Time-wise I have spent quite some time.

But all in all, I will leave the project there because it can be a very good base for people to understand that you can manipulate data in HiveOS, without touching HiveOS. So I see it like some good literature for students to open up their way of getting around things when they can't get them directly ;)

Cheers!
