### ISSUE TITLE
Thanks,LoLminer 1.47  in 3060ti is Perfect  (ETH,ETH+TON)

### ISSUE THREAD

**Issue by mattmmx166** [Lolliedieb/lolMiner-releases#1444]
![111](https://user-images.githubusercontent.com/96329153/161175550-968f0567-13b6-423a-9945-252828525eb6.jpg)
![2](https://user-images.githubusercontent.com/96329153/161376586-7822ea40-5c7b-42f4-8985-8b9082ac8e92.jpg)

**Comment by nrpeyton** [comment]
> ![111](https://user-images.githubusercontent.com/96329153/161175550-968f0567-13b6-423a-9945-252828525eb6.jpg)

a *before* pic would have been helpful

**Comment by jgonzis** [comment]
> ![111](https://user-images.githubusercontent.com/96329153/161175550-968f0567-13b6-423a-9945-252828525eb6.jpg)

Many thanks for the feedback. It really motivate people happy with the results

**Comment by donPuerto** [comment]
What is your hiveOS setting?

**Comment by jgonzis** [comment]
> What is your hiveOS setting?

Share your config better to improve what you have. So we can see where it could be your problem

**Comment by donPuerto** [comment]
@jgonzis Here it is
![image](https://user-images.githubusercontent.com/9329005/165459538-9c917d61-a8c8-4667-82e2-1760e69b440b.png)

**Comment by jgonzis** [comment]
> @jgonzis Here it is I was wondering on how to achieved 47mh ![image](https://user-images.githubusercontent.com/9329005/165459538-9c917d61-a8c8-4667-82e2-1760e69b440b.png)

I suppose you don't have Hynix v2 right?. The old 3060ti lhr hynix crash if they go over 1750...

**Comment by donPuerto** [comment]
@jgonzis how to check in HiveOS if it is Hynix v2 or not?

**Comment by jgonzis** [comment]
> @jgonzis how to check in HiveOS if it is Hynix v2 or not?

Only testing, if you put 3000 in memory and doesn't crash. Also manufactured gpu of this year should be v2 too

**Comment by donPuerto** [comment]
@jgonzis What is your setting for your memory Clock? I just tested and it doesnt Crash tho,

CCLK?
MCLOCK?
PL?

Do we have special setting on LOLminer?

**Comment by mattmmx166** [comment]
![360截图16720330164228](https://user-images.githubusercontent.com/96329153/165751081-685c0828-7454-42f5-8395-255cd722ff50.jpg)

**Comment by jgonzis** [comment]
> @jgonzis What is your setting for your memory Clock? I just tested and it doesnt Crash tho,
> 
> CCLK? MCLOCK? PL?
> 
> My ultimate goal here is to achieved Low Power? see below ![image](https://user-images.githubusercontent.com/9329005/165749721-218ed465-0854-49b2-943e-1c62d8df742a.png)
> 
> Do we have special setting on LOLminer? here's mine ![image](https://user-images.githubusercontent.com/9329005/165749536-5abc949d-a978-4326-b2ac-4362e871989d.png)

Something to work on it for sure!!

**Comment by jgonzis** [comment]
> ![360截图16720330164228](https://user-images.githubusercontent.com/96329153/165751081-685c0828-7454-42f5-8395-255cd722ff50.jpg)

Nice Rig... I think that you could put 1380 at clock and don't loose Mhs performance and probabyl reduce a pair of Watts too :-)

**Comment by jgonzis** [comment]
> Why I have 170watts per GPU compare to @jgonzis and @matt maybe I am doing dual mining

It could be the OC and old Hynix 3060ti consume a lot of more Watts than Samsung memory
