### ISSUE TITLE
mclk不可用

### ISSUE THREAD

**Issue by Zhangxinyurr** [Lolliedieb/lolMiner-releases#1447]
--mclk 不能设置正确的显存频率 请问怎么设置

**Comment by jgonzis** [comment]
> --mclk 不能设置正确的显存频率 请问怎么设置

You have to use MSI Afterburner or in the Wiki Section you have a 3erd App lolNvidiaOC.exe that will do it for you:

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)
