### ISSUE TITLE
Ton worker is not shown on icemining webpage

### ISSUE THREAD

**Issue by Neme57u** [Lolliedieb/lolMiner-releases#1449]
I copied the same config i had in the bat file of lolminer 1.46, but even when the miner shows ton is being mined (dual with eth), the icemining web page does not show the miner, i thought it was because the miner was starting, but it's been an hor and nothing.

**Comment by Earsblower** [comment]
Funny how I already told you in Discord :D Here's an example to simplify : 

set "POOL=eth-us-east.flexpool.io:4444"
set "WALLET=*****WHATEVER YOUR WALLET IS*****.RTX3090"

set "TONPOOL=ton.hashrate.to:4003"
set "TONWALLET=*****WHATEVER YOUR WALLET IS"
							
set "EXTRAPARAMETERS=--dualworker RTX3090"

As you can see in the example, do NOT name your rig after the WALLET in TONPOOL but add --dualworker in EXTRAPARAMETERS , hope it's easier this way !

**Comment by jgonzis** [comment]
Nice for giving the solution!! :-)

**Comment by Neme57u** [comment]
Thank you!
