### ISSUE TITLE
ETChash & ETHASH algo changing on the fly

### ISSUE THREAD

**Issue by Rom1kz** [Lolliedieb/lolMiner-releases#145]
I'm pool operator and working on ZIL & ETC mining implementation
when miners mine ETC as primary coin the miner doesn't want mine ZIL when pool send the new work (produces rejects only)..
my pool send 2 important flags with the each work update - "coin" and "algo"
```
{"coin":"etc","algo":"etchash","params":["8be210b0cb934f1eb9c97884c13cbcdb", ... ]}
{"coin":"zil","algo":"ethash","params":["e30a25c19c6745ae9b7a166fef5e9824", ... ]}
```

would you plz impletent these flags and changing the algo on the fly ?

you can test the miner on comining.io pool

**Comment by jgonzis** [comment]
In wiki is a complete explanation of the Dual Mining with examples too
