### ISSUE TITLE
1.48, dual eth+alph, only alph 0.00, one card

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1451]
I have strange thing after update from 1.47 to 1.48. Every thing working except one card 3060 Ti on ALPH is 0,00 hash rate. Another cards 3060/3060 Ti work perfect on ETH and ALPH together. Restart did not help, decreasing OC too. When i back to 1.47 work again on all cards together.

**Comment by jgonzis** [comment]
> I have strange thing after update from 1.47 to 1.48. Every thing working except one card 3060 Ti on ALPH is 0,00 hash rate. Another cards 3060/3060 Ti work perfect on ETH and ALPH together. Restart did not help, decreasing OC too. When i back to 1.47 work again on all cards together.

Could you please Share your OC Configuration... to be sure you are using Lock Core and no Power Limit configuration?

**Comment by dawidmosk** [comment]
My configuration is:
3x3060 Ti, -201core, 1120mem, 140
4x3060, -501core, 1620mem, 112

**Comment by sebek72** [comment]
ALPH is core intensive and needs more power (especialy when dual mining)
try locked core clock 1350-1450 and power limit to 160w for 3060ti and 130 for 3060

**Comment by jgonzis** [comment]
> Now it's working, but i have to wait for HR stable. Thank you, now i know where is problem.

Yes the 4-5min tuning that is correct

**Comment by dawidmosk** [comment]
Yes, but even with this locking conf. randomly some Ti stops working - freezing on: 0.00 or ~0.07. I did back to 1.47 and is perfect with that settings (better like before - more stable -  thx). Today i will try again 1.48 (i will check few configurations with full restart and waiting for tunning).

**Comment by jgonzis** [comment]
> Yes, but even with this locking conf. randomly some Ti stops working - freezing on: 0.00 or ~0.07. I did back to 1.47 and is perfect with that settings (better like before - more stable - thx). Today i will try again 1.48 (i will check few configurations with full restart and waiting for tunning).

Thx for the feedback

**Comment by dawidmosk** [comment]
After few tests-complete restart with 0.00Mh/s on some cards 3060 Ti(ETH and/or ALPH) i think solution was inside you set about change **locking cclk** but i even start increasing between 1450-1550(for cards with problem - Ti) and this now for one hour working stable and great. After this settings i got ~10Mh/s extra more together on ETH, and more stable ALPH in little bit higher rate. Thanks again.

**Comment by jgonzis** [comment]
> After few tests-complete restart with 0.00Mh/s on some cards 3060 Ti(ETH and/or ALPH) i think solution was inside you set about change **locking cclk** but i even start increasing between 1450-1550(for cards with problem - Ti) and this now for one hour working stable and great. After this settings i got ~10Mh/s extra more together on ETH, and more stable ALPH in little bit higher rate. Thanks again.

Many thanks for the feedback, it is really important the lock core and NO Power Limit. Enjoy mining
