### ISSUE TITLE
lolNvidiaOC.exe

### ISSUE THREAD

**Issue by Earsblower** [Lolliedieb/lolMiner-releases#1452]
Hey guys, so I've read in the Wiki under Windows guide, at the very bottom, that there's this .exe to OC directly in lolminer ( we should be able to control core clocks / mem clocks / FANS !! )

But there's no real explanation on how to integrate the .exe to lolminer ? Maybe I'm just dumb but I can't seem to make it work. Anyone knows or could explain ? 

Thanks,

**Comment by jgonzis** [comment]
> Hey guys, so I've read in the Wiki under Windows guide, at the very bottom, that there's this .exe to OC directly in lolminer ( we should be able to control core clocks / mem clocks / FANS !! )
> 
> But there's no real explanation on how to integrate the .exe to lolminer ? Maybe I'm just dumb but I can't seem to make it work. Anyone knows or could explain ?
> 
> Thanks,

You should have a bat file like:

lolNvidiaOC.exe --....
lolMiner.exe --algo ETHASH ...

That's the way to have it. Or use directly All with MSI AFterburner and only launch lolMiner.exe
