### ISSUE TITLE
lol 1.48 windows not showing pool balance in webui

### ISSUE THREAD

**Issue by matthewingram** [Lolliedieb/lolMiner-releases#1454]
I just updated on Windows from 1.46a to 1.48. On the WebUI below the tab it use to show my eth pool balance. 1.48 that disappeared. It still shows the "That TON pool API is not yet supported" in the same spot though.

**Comment by jgonzis** [comment]
> I just updated on Windows from 1.46a to 1.48. On the WebUI below the tab it use to show my eth pool balance. 1.48 that disappeared. It still shows the "That TON pool API is not yet supported" in the same spot though.

Try to change you eth wallet and instead of putting ethwallet.worker

Just put ETHWALLET  and add in EXTRAPARAMETERS=--worker nameworker"

Many thanks, confirm me if works please
