### ISSUE TITLE
High stale shares on windows lolminer 1.48

### ISSUE THREAD

**Issue by akashsutradhar** [Lolliedieb/lolMiner-releases#1455]
Getting Too much stale shares...
![Screenshot_20220402-003543_Chrome](https://user-images.githubusercontent.com/94909616/161354381-f506ba36-bfa3-40cb-acbe-fac0214a4869.jpg)

**Comment by jgonzis** [comment]
> Getting Too much stale shares... ![Screenshot_20220402-003543_Chrome](https://user-images.githubusercontent.com/94909616/161354381-f506ba36-bfa3-40cb-acbe-fac0214a4869.jpg)

You should now SSL Connection Ethermine is corrupted. It has been reported in their discord. Check also information in miner. It seems not ssl is working
