### ISSUE TITLE
eth费用

### ISSUE THREAD

**Issue by Zhangxinyurr** [Lolliedieb/lolMiner-releases#1456]
lolminer eth费用是tls吗  在中国tcp不是安全的方式

**Comment by jgonzis** [comment]
What do you recommend?

**Comment by Zhangxinyurr** [comment]
> 

lolminer的eth服务费用通过tcp还是ssl

**Comment by jgonzis** [comment]
> 

It is over SSL.

**Comment by Zhangxinyurr** [comment]
> 

有人通过抓包获取到tcp连接ip 这是怎么回事

**Comment by Zhangxinyurr** [comment]
> 它通过 SSL。

大部分中国用户害怕使用tcp到水池

**Comment by Zhangxinyurr** [comment]
tcp失去所有中国用户

**Comment by Zhangxinyurr** [comment]
我使用1.47 1.48 如果费用通过tcp 我将会被法庭 所以我很害怕

**Comment by jgonzis** [comment]
> 

It use SSL connection, no other Fee connection possible.
