### ISSUE TITLE
nvidia newest drivers are bad!

### ISSUE THREAD

**Issue by xrtw** [Lolliedieb/lolMiner-releases#1458]
with newest drivers, LHR is glitching and always trying to unlock.
https://i.gyazo.com/1155dd56643b1ffd94725ab350f38dbf.png

**Comment by gigabyteminer** [comment]
Use 472.12 hashrate 3060ti 39.02 stabel

**Comment by jgonzis** [comment]
> with newest drivers, LHR is glitching and always trying to unlock. https://i.gyazo.com/1155dd56643b1ffd94725ab350f38dbf.png

According to that photo it has been working properly until something lock it. Pool speed is 88Mhs. After 10hours, so it seems something is blocking it
