### ISSUE TITLE
Pool not detecting my miner on 1.48

### ISSUE THREAD

**Issue by lionking2208** [Lolliedieb/lolMiner-releases#1459]
1.46a is working fine but 1.48 is not detected on icemining pool.. i checked adress 10 times, tryed on 6 rigs and there is 0 miners mining on icemining pool...

**Comment by DfrostX** [comment]
As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker 

Ex:
set "POOL=eth-us-east.flexpool.io:4444"
set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"

set "TONPOOL=ton.hashrate.to:4003"
set "TONWALLET=WHATEVER YOUR WALLET IS"

set "EXTRAPARAMETERS=--dualworker RTX3090"

**Comment by jgonzis** [comment]
> As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker
> 
> Ex: set "POOL=eth-us-east.flexpool.io:4444" set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"
> 
> set "TONPOOL=ton.hashrate.to:4003" set "TONWALLET=WHATEVER YOUR WALLET IS"
> 
> set "EXTRAPARAMETERS=--dualworker RTX3090"

Many thanks 😊
