### ISSUE TITLE
Received a defect stratum message: conversion of data to type "bool" failed - Lol miner 1.48 on Win 64 

### ISSUE THREAD

**Issue by DjUnited27** [Lolliedieb/lolMiner-releases#1460]
Name:    Radeon RX 580 Series
    Address: 1:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8192 MByte (8128 MByte free)
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash OpenCL)

Connecting to pool...
Ton pool connection mode: toncoinpool.io stratum (--ton-mode 3)
DNS over HTTPS resolve failed - switching to standard resolve
DNS over HTTPS resolve failed - switching to standard resolve
Connected to eu1.ethermine.org(172.65.218.130):4444  (TLS disabled)
Connected to wss://pplns.toncoinpool.io/stratum(104.22.15.214):443  (TLS enabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0xf53eb0fc3C54b5F11e2a4EC8BE73aeeD00B8D58F.LolMinerDualRX588 Worker:LolMinerDualRX588
TLS Handshake success
Websocket handshare done with pool wss://pplns.toncoinpool.io/stratum
Subscribed to stratum server. Pool difficulty: 200.00G
**Received a defect stratum message: conversion of data to type "bool" failed**

Hi! Does anyone knows what is the problem? ****

**Comment by jgonzis** [comment]
> ```
> Name:    Radeon RX 580 Series
> Address: 1:0
> Vendor:  Advanced Micro Devices (AMD)
> Drivers: OpenCL
> Memory:  8192 MByte (8128 MByte free)
> Max epoch (approx): 894
> Active:  true (Selected Algorithm: ETHash OpenCL)
> ```
> 
> Connecting to pool... Ton pool connection mode: toncoinpool.io stratum (--ton-mode 3) DNS over HTTPS resolve failed - switching to standard resolve DNS over HTTPS resolve failed - switching to standard resolve Connected to eu1.ethermine.org(172.65.218.130):4444 (TLS disabled) Connected to wss://pplns.toncoinpool.io/stratum(104.22.15.214):443 (TLS enabled) Set Ethash stratum mode: Ethereum Proxy Authorized worker: 0xf53eb0fc3C54b5F11e2a4EC8BE73aeeD00B8D58F.LolMinerDualRX588 Worker:LolMinerDualRX588 TLS Handshake success Websocket handshare done with pool wss://pplns.toncoinpool.io/stratum Subscribed to stratum server. Pool difficulty: 200.00G **Received a defect stratum message: conversion of data to type "bool" failed**
> 
> Hi! Does anyone knows what is the problem? ****

Please put in EXTRAPARAMETERS=--dualworker rig1"

And remove after the tonwallet the worker please

**Comment by DjUnited27** [comment]
> > ```
> > Name:    Radeon RX 580 Series
> > Address: 1:0
> > Vendor:  Advanced Micro Devices (AMD)
> > Drivers: OpenCL
> > Memory:  8192 MByte (8128 MByte free)
> > Max epoch (approx): 894
> > Active:  true (Selected Algorithm: ETHash OpenCL)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Connecting to pool... Ton pool connection mode: toncoinpool.io stratum (--ton-mode 3) DNS over HTTPS resolve failed - switching to standard resolve DNS over HTTPS resolve failed - switching to standard resolve Connected to eu1.ethermine.org(172.65.218.130):4444 (TLS disabled) Connected to wss://pplns.toncoinpool.io/stratum(104.22.15.214):443 (TLS enabled) Set Ethash stratum mode: Ethereum Proxy Authorized worker: 0xf53eb0fc3C54b5F11e2a4EC8BE73aeeD00B8D58F.LolMinerDualRX588 Worker:LolMinerDualRX588 TLS Handshake success Websocket handshare done with pool wss://pplns.toncoinpool.io/stratum Subscribed to stratum server. Pool difficulty: 200.00G **Received a defect stratum message: conversion of data to type "bool" failed**
> > Hi! Does anyone knows what is the problem? ****
> 
> Please put in EXTRAPARAMETERS=--dualworker rig1"
> 
> And remove after the tonwallet the worker please

Yeah its really worked. Thanks a lot. I removed TON worker name and of course added EXTRAPARAMETERS=--dualworker rig1" 
Don't understand why we can't use worker name but its fine as long as it properly works

**Comment by jgonzis** [comment]
> > > ```
> > > Name:    Radeon RX 580 Series
> > > Address: 1:0
> > > Vendor:  Advanced Micro Devices (AMD)
> > > Drivers: OpenCL
> > > Memory:  8192 MByte (8128 MByte free)
> > > Max epoch (approx): 894
> > > Active:  true (Selected Algorithm: ETHash OpenCL)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Connecting to pool... Ton pool connection mode: toncoinpool.io stratum (--ton-mode 3) DNS over HTTPS resolve failed - switching to standard resolve DNS over HTTPS resolve failed - switching to standard resolve Connected to eu1.ethermine.org(172.65.218.130):4444 (TLS disabled) Connected to wss://pplns.toncoinpool.io/stratum(104.22.15.214):443 (TLS enabled) Set Ethash stratum mode: Ethereum Proxy Authorized worker: 0xf53eb0fc3C54b5F11e2a4EC8BE73aeeD00B8D58F.LolMinerDualRX588 Worker:LolMinerDualRX588 TLS Handshake success Websocket handshare done with pool wss://pplns.toncoinpool.io/stratum Subscribed to stratum server. Pool difficulty: 200.00G **Received a defect stratum message: conversion of data to type "bool" failed**
> > > Hi! Does anyone knows what is the problem? ****
> > 
> > 
> > Please put in EXTRAPARAMETERS=--dualworker rig1"
> > And remove after the tonwallet the worker please
> 
> Yeah its really worked. Thanks a lot. I removed TON worker name and of course added EXTRAPARAMETERS=--dualworker rig1" Don't understand why we can't use worker name but its fine as long as it properly works

Small Bug not solved sorry. In 1.48 was changed but not completely for the dual mining. 1.49 will solve it
