### ISSUE TITLE
Can I hide "New Job Received..." from console?

### ISSUE THREAD

**Issue by AlexBringer** [Lolliedieb/lolMiner-releases#1462]
Hello! I just started work with LolMiner. In my previous miner application, I use commands "--log_newjob 0" to hide this unwanted information. You know, I use Windows , and I often watch my hashrate and temperatures, but this "New Job Received..." spammed all my console window
![log](https://user-images.githubusercontent.com/102863372/161385599-a32da725-bd38-4e56-a697-bce77d0698da.jpg)
.

**Comment by DfrostX** [comment]
Add this:

set "EXTRAPARAMETERS= silence 1

**Comment by AlexBringer** [comment]
Thank you! I just tried find this commands in Google, and in Readme files, but found nothing. Maybe because it's a fresh option from 1.47 version. But its what I need. Great!

**Comment by DfrostX** [comment]
Yes, you need 1.47 minimum for it to work as it was added to that built

**Comment by jgonzis** [comment]
> Hello! I just started work with LolMiner. In my previous miner application, I use commands "--log_newjob 0" to hide this unwanted information. You know, I use Windows , and I often watch my hashrate and temperatures, but this "New Job Received..." spammed all my console window ![log](https://user-images.githubusercontent.com/102863372/161385599-a32da725-bd38-4e56-a697-bce77d0698da.jpg) .

Just do what the collegue said... Thx of having other miners helping people, really proud of that!!
