### ISSUE TITLE
lower Hashrate with 1.47 vs 1.46a on my lhr cards ? 

### ISSUE THREAD

**Issue by thatvinceguy** [Lolliedieb/lolMiner-releases#1464]
I tried out 1.47 since I saw many people had positive results.  It looks like my hashrate on my LHR cards got worse instead of better.  I have a total of 4 LHR cards on my rig, the remainder are FHR and one AMD.  Specifically, GPU 2, GPU 4, GPU 6, and GPU 7 are LHR cards.  GPU 7 is a 3070 TI and it did go up just a bit, which is great.  However, GPU's 2, 4, and 6 went down about 3mh/s each.  The longer it runs, the worse it gets.  After a day or so, those individual cards get as low as 38mh/s each when they originally got about 44-45mh on 1.46a. GPU2 is an MSI 3070 LHR.  GPU's 4 and 6 are Gigabyte 3060 TI LHR cards.  Many people reported an increase of a few mh, so I was suprised when I got a decrease.   I posted some screenshots that show driver, os, oc settings, etc. I have tried both nvidia drivers recommended.  Currently on the 510.xx.   I monitored the miner and it doesn't look like it's getting hung up anywhere, atleast not that it shows on screen.  Have also attached pics of miner. Going to run 1.46a for the meanwhile.  I was really hoping for that little extra bump in mh,  so any advice you guys can offer me that can help me get 1.47 working right would be great.  Thanks.

lower hashrate with 1.47, gpu 2, 4, and 6 went down. total ~796mh/s reported, 784mh/s on pool
![image](https://user-images.githubusercontent.com/99154454/161394998-a9a77f1c-f25d-4922-b023-f082fe69eaba.png)

1.47 miner after about an hour of runtime
still lower hash rate, both reported, and on-pool.
![image](https://user-images.githubusercontent.com/99154454/161398651-6be186ca-9db2-4e2a-87b2-547944d454ae.png)

higher hashrate with 1.46a total ~802mh/s reported, 795mh/s on pool
![image](https://user-images.githubusercontent.com/99154454/161395247-3b5e5ef4-fdae-4f50-87df-5f03e5abd5ec.png)

1.46a miner 
![image](https://user-images.githubusercontent.com/99154454/161395803-2bb03d5d-719e-4712-a542-d36d1ebeced5.png)

**Comment by jgonzis** [comment]
> I tried out 1.47 since I saw many people had positive results. It looks like my hashrate on my LHR cards got worse instead of better. I have a total of 4 LHR cards on my rig, the remainder are FHR and one AMD. Specifically, GPU 2, GPU 4, GPU 6, and GPU 7 are LHR cards. GPU 7 is a 3070 TI and it did go up just a bit, which is great. However, GPU's 2, 4, and 6 went down about 3mh/s each. The longer it runs, the worse it gets. After a day or so, those individual cards get as low as 38mh/s each when they originally got about 44-45mh on 1.46a. GPU2 is an MSI 3070 LHR. GPU's 4 and 6 are Gigabyte 3060 TI LHR cards. Many people reported an increase of a few mh, so I was suprised when I got a decrease. I posted some screenshots that show driver, os, oc settings, etc. I have tried both nvidia drivers recommended. Currently on the 510.xx. I monitored the miner and it doesn't look like it's getting hung up anywhere, atleast not that it shows on screen. Have also attached pics of miner. Going to run 1.46a for the meanwhile. I was really hoping for that little extra bump in mh, so any advice you guys can offer me that can help me get 1.47 working right would be great. Thanks.
> 
> lower hashrate with 1.47, gpu 2, 4, and 6 went down. total ~796mh/s reported, 784mh/s on pool ![image](https://user-images.githubusercontent.com/99154454/161394998-a9a77f1c-f25d-4922-b023-f082fe69eaba.png)
> 
> 1.47 miner after about an hour of runtime still lower hash rate, both reported, and on-pool. ![image](https://user-images.githubusercontent.com/99154454/161398651-6be186ca-9db2-4e2a-87b2-547944d454ae.png)
> 
> higher hashrate with 1.46a total ~802mh/s reported, 795mh/s on pool ![image](https://user-images.githubusercontent.com/99154454/161395247-3b5e5ef4-fdae-4f50-87df-5f03e5abd5ec.png)
> 
> 1.46a miner ![image](https://user-images.githubusercontent.com/99154454/161395803-2bb03d5d-719e-4712-a542-d36d1ebeced5.png)

You are not the 1st that has less TON on it. It seems something on the tunning. 

I only 1 strange thing that I think you have... You have OC Delay in your parameters... 

Could you test 2 things:

Could you please delete  OC Delay?
Could you try the 1.48 to be sure if new version solve problems for you?
