### ISSUE TITLE
High stale shares on windows in latwst lolminer

### ISSUE THREAD

**Issue by akashsutradhar** [Lolliedieb/lolMiner-releases#1465]
No SSL connection, 10x3070ti and 2x3080ti...don't close the issue untill it is solve..thanks
Wrong Gpus number.. gpu1,gpu3,gpu5 like these

**Comment by jgonzis** [comment]
> No SSL connection, 10x3070ti and 2x3080ti...don't close the issue untill it is solve..thanks Wrong Gpus number.. gpu1,gpu3,gpu5 like these

Please show information ... People is having their SSL Connection using the --tls on parameter. If I don't see any photo or error or config I cannot help. I close it until photo or more informationn comes. Thx
