### ISSUE TITLE
Founders Edition 3060 ti with EVGA 3070 lhr Problems

### ISSUE THREAD

**Issue by ecredeem** [Lolliedieb/lolMiner-releases#1466]
Okay so i'm giving lolminer 1.48 a chance, my drivers are up to date with recommended drivers from dev. 

- I'm using windows not HIVEOS 
-  I set the core clocks in the bat file in eth, 
- connected to 2miners correctly, 
- set up memory clocks, fan speed, and power limit in msi afterburner

My problem: Once the DAG are created and sharing, my EVGA 3070 are working at 40.09 mh/s as speed and pool 78.31 mh/s
however my Founders Edition 3060 ti is at 0mh/s all around.

How do I configure lolminer 1.48 to make my founders Edition work alongside my EVGA 3070 lhr in the same rig

**Comment by pdieppa** [comment]
Please post your command line!

**Comment by jgonzis** [comment]
> Okay so i'm giving lolminer 1.48 a chance, my drivers are up to date with recommended drivers from dev.
> 
> * I'm using windows not HIVEOS
> * I set the core clocks in the bat file in eth,
> * connected to 2miners correctly,
> * set up memory clocks, fan speed, and power limit in msi afterburner
> 
> My problem: Once the DAG are created and sharing, my EVGA 3070 are working at 40.09 mh/s as speed and pool 78.31 mh/s however my Founders Edition 3060 ti is at 0mh/s all around.
> 
> How do I configure lolminer 1.48 to make my founders Edition work alongside my EVGA 3070 lhr in the same rig

Could you please put the Command line and a photo with the full stats Miners that will help. I close it until photo is here to comment and find the solution.
