### ISSUE TITLE
lolminer 1.48 eff n/a Power n/a

### ISSUE THREAD

**Issue by CryterStrife** [Lolliedieb/lolMiner-releases#1467]
does anyone know why I don't see efficiency and consumption? i use lolMiner 1.48
![277408343_639228023779987_4259044823311453978_n](https://user-images.githubusercontent.com/102883948/161405473-244398eb-d3a4-43a6-93de-e0c4d943f526.jpg)

**Comment by jgonzis** [comment]
> does anyone know why I don't see efficiency and consumption? i use lolMiner 1.48 ![277408343_639228023779987_4259044823311453978_n](https://user-images.githubusercontent.com/102883948/161405473-244398eb-d3a4-43a6-93de-e0c4d943f526.jpg)

That normally it is because the NVML Library is not in the proper folder. I don't know if you are also using the recommended version 512.15.

**Comment by CryterStrife** [comment]
> > > > does anyone know why I don't see efficiency and consumption? i use lolMiner 1.48 ![277408343_639228023779987_4259044823311453978_n](https://user-images.githubusercontent.com/102883948/161405473-244398eb-d3a4-43a6-93de-e0c4d943f526.jpg)
> > > 
> > > 
> > > That normally it is because the NVML Library is not in the proper folder and Power cannot be read it. I don't know if you are also using the recommended version 512.15.
> > 
> > 
> > yes i am using 512.15. so how do i solve?
> 
> Try that:
> 
> https://programmerah.com/solved-win-nvidia-smi-csolved by reinstalling the driversannt-usefailed-to-initialize-nvml-unknown-error-43941/


solved by reinstalling the drivers

**Comment by jgonzis** [comment]
Great. Thx for the feedback
