### ISSUE TITLE
LolMiner 1.48 DUAL MINING ETH+ALPH

### ISSUE THREAD

**Issue by donkurami** [Lolliedieb/lolMiner-releases#1468]
On 3060Ti dual mining is not working on ALEPHIUM.Please take  a look,or IDK,it is my fisrt post here :)

**Comment by jgonzis** [comment]
> On 3060Ti dual mining is not working on ALEPHIUM.Please take a look,or IDK,it is my fisrt post here :)

Thx for posting. But It is working... If you share photo that for sure will help. Could you please put the full stats of the miner?. 

There normally gives us lot of information to now where is your problem.  I'm sure it will be only a problem in the correction or that Core Clock is not locked.

**Comment by donkurami** [comment]
hmm,i switch back to LolMiner 1.48 and now hirominers pool detect my hash,last night did not!WIth the same setup from last night,i mine the whole day with trex.For now it seems fine,i guess they did something(developers)....Nope after 5-10 min...one card goes 20-34mh/s ETH and 200-300 ALPH...other 47mh/s on ETH,0mh/s on ALPH...On the other issue you said to lock core clock?How i have on MSI AB profile and i use them from a year

**Comment by jgonzis** [comment]
> 

You can fix Lock Core with --cclk and have a small guide in:
https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)

**Comment by donkurami** [comment]
![Desktop Screenshot 2022 04 03 - 23 17 56 91](https://user-images.githubusercontent.com/102884824/161447735-08b01aa1-f2b7-4af0-947e-2a6b05ef5ae1.png)
![Desktop Screenshot 2022 04 03 - 23 18 35 03 (2)](https://user-images.githubusercontent.com/102884824/161447736-a95b22af-4852-4b47-ae72-ec5cecbdd070.png)
![Desktop Screenshot 2022 04 03 - 23 18 44 14 (2)](https://user-images.githubusercontent.com/102884824/161447737-3e92858c-73fb-4c33-9a17-67fd8235c50e.png)
![Desktop Screenshot 2022 04 03 - 23 24 01 41](https://user-images.githubusercontent.com/102884824/161447739-59a2f92e-b640-49be-97c0-4ff7876bda00.png)
![Desktop Screenshot 2022 04 03 - 23 29 09 49](https://user-images.githubusercontent.com/102884824/161447740-76eb9334-afbc-4a5e-9890-63a960210e67.png)
![Desktop Screenshot 2022 04 03 - 23 33 58 51](https://user-images.githubusercontent.com/102884824/161447741-e11fc468-18d6-47c1-911c-cd403a5096af.png)

**Comment by jgonzis** [comment]
Lot of requirements failing:

PL is not 100.
Lock Core is not fixed for example 1500
Not using 512.15 (recommend)

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)

**Comment by donkurami** [comment]
yep, i know about the driver...I will wait for new versions on Nb orTrex...thank you for your time

**Comment by jgonzis** [comment]
> yep, i know about the driver...I will wait for new versions on Nb orTrex...thank you for your time

OK... of course you can try it with 472.12, but unless you lock the core and PL100%. It will not mine properly. I hope you give a try. Thx
