### ISSUE TITLE
1.48 alephium low?

### ISSUE THREAD

**Issue by gigabyteminer** [Lolliedieb/lolMiner-releases#1471]
Why alephium hashrate so low. I play with all configs and not go up.
![515FC6E2-8632-4368-94BD-8BF21F86579A](https://user-images.githubusercontent.com/91029365/161425353-7692717d-7e3c-4d6a-b60a-5c7d1b32a4a2.jpeg)

**Comment by donkurami** [comment]
Same here,with Trex 25.8 DUAL i got 300Mh/s on alph with eth 45-46mh/s...

**Comment by gigabyteminer** [comment]
1.48 eats more cpu. If you have meter in wall then you see this. I had from wall 177w and in cmd 129w. Now its eat cmd 129 but from wall 202w. I but in cpu power min 1% and max 20%. Now cpu runs 0.87% and power is normal.

**Comment by gigabyteminer** [comment]
I found that if i but cclk 1450-1500 then i get eth 48,80 and alph 56 and with cclk 1200-1400 then alph 680 and eth 43

**Comment by jgonzis** [comment]
> I found that if i but cclk 1450-1500 then i get eth 48,80 and alph 56 and with cclk 1200-1400 then alph 680 and eth 43

Right... you got it before we answer... Always use Lock Core... or it is not possible to tune properly. It is one of the recommendations of the release. 

You can add --cclk in the bat file, to lock the Core. Remember to restart each time the miner for the proper tunning.

**Comment by donkurami** [comment]
![Desktop Screenshot 2022 04 03 - 23 33 58 51](https://user-images.githubusercontent.com/102884824/161447678-f9acda5b-993d-4228-8120-71a3cafe7e5d.png)
![Desktop Screenshot 2022 04 03 - 23 29 09 49](https://user-images.githubusercontent.com/102884824/161447687-42c5a880-bb8a-4f16-a1f3-7f316f334cd1.png)
![Desktop Screenshot 2022 04 03 - 23 17 56 91](https://user-images.githubusercontent.com/102884824/161447697-f6426a3d-1af7-43a5-a94f-f5a2830e1276.png)
![Desktop Screenshot 2022 04 03 - 23 18 35 03 (2)](https://user-images.githubusercontent.com/102884824/161447701-5a308d61-a7bc-4211-a53e-95d3e8f5f1d3.png)
![Desktop Screenshot 2022 04 03 - 23 18 44 14 (2)](https://user-images.githubusercontent.com/102884824/161447702-cc2093c5-71c2-4469-b7b7-ca015747711b.png)
![Desktop Screenshot 2022 04 03 - 23 24 01 41](https://user-images.githubusercontent.com/102884824/161447703-bdabdf44-bffd-4395-a146-149e0ec443e3.png)
