### ISSUE TITLE
 fan control

### ISSUE THREAD

**Issue by bilemedimki** [Lolliedieb/lolMiner-releases#1472]
hi
I want to keep my cards at 58c. how can I do that .
Can I do --tmode 58?
for windows
please help 
thanks.

**Comment by jgonzis** [comment]
> hi I want to keep my cards at 58c. how can I do that . Can I do --tmode 58? for windows please help thanks.

To make that, you should use 3rd Apps like:

- MSI Afterburner
- MMPOS Windows Agent

**Comment by sibar85** [comment]
I dont get it, how almost all miners have fan control but lolminer doesnt!?

**Comment by jgonzis** [comment]
> I dont get it, how almost all miners have fan control but lolminer doesnt!?

You are right... it is a nice feature that should be added. At the moment only fix fan with lolNvidiaOC.exe

**Comment by sulplangis** [comment]
i was just gonna add Feature request fan control
TG https://t.me/lolMiner/90388
```
H@K, [10/19/2022 10:46 PM]
Feature request!
-fan control
```
