### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Demon1874716** [Lolliedieb/lolMiner-releases#1486]
Who is owner of wallet 0x360d6f9efea21c82d341504366fd1c2eeea8fa9d using in your guide for newbie miners?

**Comment by Demon1874716** [comment]
I need to contact him

**Comment by jgonzis** [comment]
> Who is owner of wallet 0x360d6f9efea21c82d341504366fd1c2eeea8fa9d using in your guide for newbie miners?

No idea... ask what you need to help you
