### ISSUE TITLE
How to set Ton forwarding server.

### ISSUE THREAD

**Issue by kindman4** [Lolliedieb/lolMiner-releases#1487]
Lolminer V1. 46 & 1.48. When eth + ton, how to set the ton forwarding server? I tried many methods similar to eth, such as:

Eth works
lolmine:"Pool=stratum+ ssl://ServerIP:Port "
Server:sudo redir :5555 ethermine. org:14444

But ton TCP cannot link
lolmine:"Pool=stratum+ tcp://ServerIP:Port " --or delete [stratum+tcp://]
Server:sudo redir :5555 stratum+ tcp://tcp.whalestonpool.com:4001 --or delete [stratum+tcp://]

Or ton HTTPS cannot be linked
lolmine:"Pool= https://ServerIP:Port " --or delete [https://]
Server:sudo redir :5555 https://server1.whalestonpool.com --or delete [https://]

And as same as WSS...

So, how should lolminer and server be set? Thank you!

**Comment by jgonzis** [comment]
Better for ETH ssl, direct use ssl://... not need it the stratum+...

With https:// just only https://url... 
For wss:// the same without the port number.

You can share your file if you want more check.
