### ISSUE TITLE
1.48 Hashrate in miner but not on pool

### ISSUE THREAD

**Issue by malisdanny** [Lolliedieb/lolMiner-releases#1488]
I have an issue with the latest version on icemining.ca pool, i see hashrate in the miner for TON (and ETH) but its not detected in the pool, windows and hiveos. works fine with the same settings on hiveos 1.47 and 1.46a on windows. No issue on ETH pool with 1.48.

**Comment by Bedasek** [comment]
Same here, I'm mining via Hiveos, and all I did is I upgraded from 1.47 to 1.48, didn't make any other updates to the flightsheet.
Now I'm noticing 0 GH/s in the pool.

**Comment by sibar85** [comment]
Pool hashrate not showing on miner, or showing both hashrates on one card

**Comment by DfrostX** [comment]
As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker

Ex:
set "POOL=eth-us-east.flexpool.io:4444"
set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"

set "TONPOOL=ton.hashrate.to:4003"
set "TONWALLET=WHATEVER YOUR WALLET IS"

set "EXTRAPARAMETERS=--dualworker RTX3090"

**Comment by malisdanny** [comment]
> As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker
> 
> Ex: set "POOL=eth-us-east.flexpool.io:4444" set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"
> 
> set "TONPOOL=ton.hashrate.to:4003" set "TONWALLET=WHATEVER YOUR WALLET IS"
> 
> set "EXTRAPARAMETERS=--dualworker RTX3090"

Thank you, it worked in windows and hiveos :)

**Comment by jgonzis** [comment]
> > As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker
> > Ex: set "POOL=eth-us-east.flexpool.io:4444" set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"
> > set "TONPOOL=ton.hashrate.to:4003" set "TONWALLET=WHATEVER YOUR WALLET IS"
> > set "EXTRAPARAMETERS=--dualworker RTX3090"
> 
> Thank you, it worked in windows and hiveos :)

Yes 1.48 has that new concept of dualworker. It will be solved for next release sorry
