### ISSUE TITLE
Issue with 1.48 version on Zotac Trinity 12GB

### ISSUE THREAD

**Issue by elbelli2008** [Lolliedieb/lolMiner-releases#1489]
Hi, version 1.47 work fine, but qith the lastest version of lolminer 1.48, hashrate drop to 0 and N/A,
I revert and downgrade to 1.47 and work fine again.

Can You help me to resolve this issue,.

Im using N 510.54 Nvida drivers on HiveOS.

thanks 

regards

**Comment by Maxtrixkhan** [comment]
N 510.54 Nvidia change to 512.15 or any 512xxx version

**Comment by Shano592** [comment]
HiveOS drivers are only up to 510.54 atm

**Comment by jgonzis** [comment]
> Hi, version 1.47 work fine, but qith the lastest version of lolminer 1.48, hashrate drop to 0 and N/A, I revert and downgrade to 1.47 and work fine again.
> 
> Can You help me to resolve this issue,.
> 
> Im using N 510.54 Nvida drivers on HiveOS.
> 
> thanks
> 
> regards

Could you share your OC and the information of the miner? 

The important is one of the versions working
