### ISSUE TITLE
ETH+TON+ZIL  | different pools | .bat file?

### ISSUE THREAD

**Issue by thomas-gh1** [Lolliedieb/lolMiner-releases#1492]
Please help me edit my .bat file to mine ETH + TON + ZIL with **different ZIL/ETH pools.**

Current file:
```
cd \
cd C:\lolMiner_v1.48_Win64\1.48
lolMiner.exe

--algo ETHASH --pool eu1.ethermine.org:4444 --user 0xETH_WALLET 

--dualmode zil --dualpool eu.ezil.me:5555 --dualuser 0xETH_WALLET.0xZIL_WALLET 

--enablezilcache
```

Why different pool for Eth and ZIL?  _(See below):_

![2022-04-05 (1)](https://user-images.githubusercontent.com/103011804/161666666-a17ba5f7-7af1-4b3d-a75e-f18cd13780c8.png)

EZIL.ME=PPS
I know there are other pools _(non-PPS)_, but I do not want to take the **risk**!  If a new Ethereum pool is 10% less profitable, then  time + money = wasted.

.

ZIL mining is worth it:

![2022-04-05](https://user-images.githubusercontent.com/103011804/161667575-cffa1ca1-5660-4f70-b736-7cbe4e153411.png)

**Comment by rcerebro** [comment]
Ezil accept now PLNS

![image](https://user-images.githubusercontent.com/38794375/161748401-7d58abef-0954-4d1e-98fe-de48a38708ac.png)

**Comment by nrpeyton** [comment]
The list of pools in my screenshot:

Only the top 10 (most profitable pools) are shown.  That means ezil.me must be less profitable than the least profitable pool on that list (in 10th place).  Which translates to at least 7.43% less profitable than my current pool.

If a pool can't even make the top 10 list, then it obviously values its own respective business model more than it respects its Miners.

**Comment by jgonzis** [comment]
> Please help me edit my .bat file to mine ETH + TON + ZIL with **different ZIL/ETH pools.**
> 
> Current file:
> 
> ```
> cd \
> cd C:\lolMiner_v1.48_Win64\1.48
> lolMiner.exe
> 
> --algo ETHASH --pool eu1.ethermine.org:4444 --user 0xETH_WALLET 
> 
> --dualmode zil --dualpool eu.ezil.me:5555 --dualuser 0xETH_WALLET.0xZIL_WALLET 
> 
> --enablezilcache
> ```
> 
> Why different pool for Eth and ZIL? _(See below):_
> 
> ![2022-04-05 (1)](https://user-images.githubusercontent.com/103011804/161666666-a17ba5f7-7af1-4b3d-a75e-f18cd13780c8.png)
> 
> EZIL.ME=PPS I know there are other pools _(non-PPS)_, but I do not want to take the **risk**! If a new Ethereum pool is 10% less profitable, then time + money = wasted.
> 
> .
> 
> ZIL mining is worth it:
> 
> ![2022-04-05](https://user-images.githubusercontent.com/103011804/161667575-cffa1ca1-5660-4f70-b736-7cbe4e153411.png)

It has correct configuration. You will mine in both pools.eth I'm ethermine and zil only 2 min of each 90 on ezil.me

**Comment by ltwarrior18** [comment]
We need already --triplemode you choose your ethereum pool + ziliqa pool + ton or aleqa pool. Risking your ethereum just to mine ziliqa is very bad - I mean your eth mining is tied to zil pool, when we want other pool. so Ziliqa should be seperated too!

**Comment by ltwarrior18** [comment]
All morning I was trying to figure out how to triple mine, without zil pool, and there is no way around it.

**Comment by jgonzis** [comment]
> All morning I was trying to figure out how to triple mine, without zil pool, and there is no way around it.

No way... You have to use EZIL.ME or use the Proxy.

https://youtu.be/52HHqb0Dz6w

https://youtu.be/VSgGiqakAGQ

**Comment by ltwarrior18** [comment]
ETH/ZIL with server listening works fine on lolminer, we get 2 stats for eth and zil, but what we need is dualmode to support ZIL,TONDUAL, so we would get ETH/ZIL + TON, so we could see all 3 coins being mined, and listening when zil starts is more reliant than connecting to pool proxies, that suck in all your mhs, and start doing hardware errors as the ping increases quite a lot...

**Comment by dawidmosk** [comment]
Maybe there is any way to new version lolMiner have possibility **three** pools **addresses** ETH + ZIL + ALPH/TON (without pool prepared like ezil.me)

**Comment by nrpeyton** [comment]
> > All morning I was trying to figure out how to triple mine, without zil pool, and there is no way around it.
> 
> No way... You have to use EZIL.ME or use the Proxy.
> 
> https://youtu.be/52HHqb0Dz6w
> 
> https://youtu.be/VSgGiqakAGQ

That is ridiculous.

You can't [force] people to only mine with one pool.  

The ezil.me pool has a monopoly over zil mining, and it utilises that monopoly to profit from Ethereum by REMOVING the CHOICE to mine with your own choice of pool.

Why did you say "no way"??

Would it really be that difficult to add a `--zil_pool` command? 

The first miner that adds it will have an edge over other miner's, i.e., you will be the ONLY miner that offers "true" triple mining without being robbed.

Regards,

**Comment by jgonzis** [comment]
> > > All morning I was trying to figure out how to triple mine, without zil pool, and there is no way around it.
> > 
> > 
> > No way... You have to use EZIL.ME or use the Proxy.
> > https://youtu.be/52HHqb0Dz6w
> > https://youtu.be/VSgGiqakAGQ
> 
> That is ridiculous.
> 
> You can't [force] people to only mine with one pool.
> 
> The ezil.me pool has a monopoly over zil mining, and it utilises that monopoly to profit from Ethereum by REMOVING the CHOICE to mine with your own choice of pool.
> 
> Why did you say "no way"??
> 
> Would it really be that difficult to add a `--zil_pool` command?
> 
> The first mining_app that adds it will have an edge over other apps, i.e., you will be the ONLY miner that offers "true" triple mining without being robbed.
> 
> Regards,

We are not forcing anyone. You can use Ezil.me, really easy way or use a Proxy server like Shardpool.io or Rustpool.xyz. It has been used for several people without problems for months with lot of guide videos in YouTube
