### ISSUE TITLE
Stutterings in games after mining

### ISSUE THREAD

**Issue by Duxter7** [Lolliedieb/lolMiner-releases#1493]
So, it took me awhile to find the culprit of my micro stutterings in all games after mining without rebooting. I'm pretty sure the problem is the miner.

After mining on my RTX 3070 (FHR) ETH+TON for at least 8-12 hours and then starting up any game I get mirco stutterings, but they are really annoying. 

When I started getting the stutterings I then tried signing out and signing in order to exclude any software problem in my system but the problem stayed. Also I tried to not use the miner for the same 12 hours period of time and I didn't get the stutterings.

Also, it's not RAM, I have auto-cleaning of Standby Memory every 5 min. 

When I get the stutterings for a fraction of second my GPU utilization drops and rises again afterwards.

Currently I'm testing Gminer to see if it has the same issue. If it doesn't, it means 100 percent the problem with Lolminer 

Windows 10, 512.15 Nvidia Drivers

**Comment by zulu1905** [comment]
reset overclock before play game. if dont know how to reset overclock, you can restart your computer. it is easy way

**Comment by Duxter7** [comment]
> reset overclock before play game. if dont know how to reset overclock, you can restart your computer. it is easy way

I have 2 profiles in MSI Afterburner, one for Gaming and the other one is for Mining. 

Also, like I said in the first place, the problem starts to appear only after mining for a good amount of time.

**Comment by A01709042** [comment]
maybe throttling, degradation or high oc on games? It could also be that your bat file has a core lock, or maybe you installed the nvidia overclock utility and don’t realize you’re double overclocking, that happened to me once 

Try removing administrator permissions from lolminer, if you don’t run it as admin and it still happens it probably is 100% sure not lolminer because it literally cannot change gpu settings without it, it will say “lacking permissions” and run without overclock

**Comment by Duxter7** [comment]
> maybe throttling, degradation or high oc on games? It could also be that your bat file has a core clock lock, or maybe you installed the nvidia overclock utility and don’t realize you’re double overclocking, that happened to me once 
> 
> Try removing administrator permissions from lolminer, if you don’t run it as admin and it still happens it probably is 100% sure not lolminer because it literally cannot change gpu settings without it, it will say “lacking permissions” and run without overclock 

Throttling and High OC is definitely not an issue, since my GPU is undervolted and just slightly overclocked (in comparison to mining), GPU is only hitting 55C while gaming with 70C being hot spot.

There are no OC settings inside the batch file, only in MSI Afterburner.

I also swapped my 3070 FHR to 3080 10Gb LHR and surprisingly it works flawlessly.

So either my 3070 is dying (but again, after reboot everything is fine and without running the miner everything is also fine) or the problem with the miner itself for specific GPUs

**Comment by A01709042** [comment]
Have you methodically separated all variables and tested each one of them with control baseline settings? I’m not a dev for lolminer or anything but honestly if the miner doesn’t have administrative permission it sounds really really not possible that it can tweak your gpu settings. I’d check how the clocks behave both before mining (with some benchmarks or gaming) while and after mining for 6 hours + while gaming before a restart + after it with two separate miners. The thing here is the need to restart points me to think it might be a bug related to your oc settings, so maybe try overclocking directly in lolminer with the same values from afterburner, try gaming without overclocking after 6+ hours of mining etc. Basically separate all variables so you can isolate what specifically is the issue. And make sure lolminer never asks for user prompt when run, that would usually make it impossible to change gpu settings unless you’re using a custom cmd prompt or an admin cmd prompt or shell

**Comment by Duxter7** [comment]
> Have you methodically separated all variables and tested each one of them with control baseline settings? I’m not a dev for lolminer or anything but honestly if the miner doesn’t have administrative permission it sounds really really not possible that it can tweak your gpu settings. I’d check how the clocks behave both before mining (with some benchmarks or gaming) while and after mining for 6 hours + while gaming before a restart + after it with two separate miners. The thing here is the need to restart points me to think it might be a bug related to your oc settings, so maybe try overclocking directly in lolminer with the same values from afterburner, try gaming without overclocking after 6+ hours of mining etc. Basically separate all variables so you can isolate what specifically is the issue. And make sure lolminer never asks for user prompt when run, that would usually make it impossible to change gpu settings unless you’re using a custom cmd prompt or an admin cmd prompt or shell 

Thanks for your input!
I have commented on the issue and since swapped to 3080 LHR and the problem disappeared.

But I had RivaTuner and my OC settings were applied and different from when I was mining. 

And I don't think lolminer had messed with OC settings, since the problem only starts appearing after mining for an extensive period of time. Maybe it has to do with DAD, idk. 

But, like I said, 3080 LHR works fine. So the problem may be either bug Iolminer for specific GPUs, the bug in the 512.15 driver, again for specific GPUs or my dying GPU (although this just doesn't fit in my head how is this possible)

**Comment by jgonzis** [comment]
You can always run lolNvidiaOC.exe --reset 
App from the Windows Guide, that will restart all driver. Give a try if helps
