### ISSUE TITLE
LHR keeps calibrating

### ISSUE THREAD

**Issue by fr4ncisx** [Lolliedieb/lolMiner-releases#1497]
When HDR is ON, LHR keeps calibrating

**Comment by Maxtrixkhan** [comment]
Hi pal why you want HDR on a Mining rig. 
Any stress on GPU will cause calibration issues and LHR locks. So thats it. You want to mine use a desktop screen with low resolution or do remote management. Teamveiwer etc

**Comment by jgonzis** [comment]
> When HDR is ON, LHR keeps calibrating

It is comment in the release, try not to stress the GPU... also be sure PL is to 100%, you use Lock Core and you are with drivers 512.15

**Comment by fr4ncisx** [comment]
This was on desktop no stressing gpu, HDR turns on itself, native 4k Resolution, can't do much. Only solution switch to 1080p no hdr monitor

**Comment by jgonzis** [comment]
> This was on desktop no stressing gpu, HDR turns on itself, native 4k Resolution, can't do much. Only solution switch to 1080p no hdr monitor

Could you try to active P0 if that helps... which Driver are you using?

**Comment by fr4ncisx** [comment]
With p0 state it's the same, using latest drivers 512.15 on windows 10

**Comment by jgonzis** [comment]
> With p0 state it's the same, using latest drivers 512.15 on windows 10

I hope you can put the full stats and say which is your pool server. Without information is just giving ideas but could not be the right ones

**Comment by fr4ncisx** [comment]
mining on 2miners eu

**Comment by jgonzis** [comment]
> mining on 2miners eu

Is it possible the full stats with the OC?

**Comment by fr4ncisx** [comment]
Locked Core clock: 1380 // Memory Clock offset +1000 // no power limit

**Comment by jgonzis** [comment]
> Locked Core clock: 1380 // Memory Clock offset +1000 // no power limit
> 
> RTX 3060 Ti

Is it possible the full stats of the miner? Could you make a screenshot to have information about it. I assume you are in 512.15
