### ISSUE TITLE
LolMiner 1.48 ETH+TON, Second Algorithm 0 Hash Rate

### ISSUE THREAD

**Issue by blastertwist** [Lolliedieb/lolMiner-releases#1498]
Hello i'm trying new LolMiner version 1.48 in HiveOS.
The result of the test quite satisfying with the ETH algorithm, i can get 2 mh/s more than before.
However when do the dual mining with TONCOIN, the TON hash shows only 0 hash.

This is my result after running 10H ++
![Screen Shot 2022-04-06 at 07 29 33](https://user-images.githubusercontent.com/22257499/161872595-3a32f917-c197-4ae0-98e9-48ce25cc1237.png)

This is my LolMiner settings on HiveOS:
![Screen Shot 2022-04-06 at 07 33 21](https://user-images.githubusercontent.com/22257499/161872663-f3544f6d-2566-4dae-b7eb-0cb96e5f7d38.png)

I do not know how to fix this, please help me.

**Comment by DfrostX** [comment]
As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker

Ex:
set "POOL=eth-us-east.flexpool.io:4444"
set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"

set "TONPOOL=ton.hashrate.to:4003"
set "TONWALLET=WHATEVER YOUR WALLET IS"

set "EXTRAPARAMETERS=--dualworker RTX3090"

**Comment by blastertwist** [comment]
> As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker
> 
> Ex: set "POOL=eth-us-east.flexpool.io:4444" set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"
> 
> set "TONPOOL=ton.hashrate.to:4003" set "TONWALLET=WHATEVER YOUR WALLET IS"
> 
> set "EXTRAPARAMETERS=--dualworker RTX3090"

I dont have rig name from the wallet, or how to do it on HIveOS?
From the settings extraparameters i already add --dualworker RTX3060Ti like my posted image about the miner settings and it is still not working

**Comment by Bedasek** [comment]
I found out that version 1.48 treats the miner config in hiveos flightsheet differently.
I configured it this way and it's just fine.
YES, INCLUDING THE EMPTY FIELDS BELOW "TONDUAL"

![obrazek](https://user-images.githubusercontent.com/17751503/162064929-63c4773e-3cad-4f4f-8309-5d8262f9ff95.png)

**Comment by blastertwist** [comment]
> I found out that version 1.48 treats the miner config in hiveos flightsheet differently. I configured it this way and it's just fine. YES, INCLUDING THE EMPTY FIELDS BELOW "TONDUAL"
> 
> * **statsformat** and **silence** are optional parameters.
> * **dualpool** set accordingly to your pool
> 
> ![obrazek](https://user-images.githubusercontent.com/17751503/162064929-63c4773e-3cad-4f4f-8309-5d8262f9ff95.png)

Yeah its worked! Thank you bro!
