### ISSUE TITLE
Low  hashrate for ALPH on ETH+ALPH mining with lolminer

### ISSUE THREAD

**Issue by unaisp** [Lolliedieb/lolMiner-releases#1499]
I used to get 45.6 Mhs for ETH and 650Mhs for ALPH while doing dual mining on t-rex on 3060 Ti LHR V2 Cards. But the lol miner gives me only 225Mhs for ALPH with the same clocks. ETH hash rate is good (48+ Mhs) in the latest versions of lolminer. Tested the same on nvidia driver 470/495/510 drivers.

Core Clock: +150
Memory Clock: 2660
Power Limit: 160W

**Comment by DfrostX** [comment]
As posted previously, remove the rig name from the wallet and add set "EXTRAPARAMETERS=--dualworker

Ex:
set "POOL=eth-us-east.flexpool.io:4444"
set "WALLET=WHATEVER YOUR WALLET IS.RTX3090"

set "TONPOOL=ton.hashrate.to:4003"
set "TONWALLET=WHATEVER YOUR WALLET IS"

set "EXTRAPARAMETERS=--dualworker RTX3090"

**Comment by Bedasek** [comment]
ETH+ALPH on my 3060 Ti gets me 44.1 + 590 MH/s.
My OC is 1300/2400 consuming 147 W.

Tho I think you problem is most likely offset core clock. Always use locked clock. In other words, always use only the absolute value (in MHz) for both core and memory.

**Comment by jgonzis** [comment]
> I used to get 45.6 Mhs for ETH and 650Mhs for ALPH while doing dual mining on t-rex on 3060 Ti LHR V2 Cards. But the lol miner gives me only 225Mhs for ALPH with the same clocks. ETH hash rate is good (48+ Mhs) in the latest versions of lolminer. Tested the same on nvidia driver 470/495/510 drivers.
> 
> Core Clock: +150 Memory Clock: 2660 Power Limit: 160W

That's the problem, you are not using Lock Core. You should fix the core clock of the GPU, with offset will not work properly.  It is commented in the release section
