### ISSUE TITLE
how to use socks5 proxy?

### ISSUE THREAD

**Issue by myth2loki** [Lolliedieb/lolMiner-releases#1500]
how to use socks5 proxy?

**Comment by edisonchan** [comment]
It does not work for eth.

**Comment by jgonzis** [comment]
> how to use socks5 proxy?

--socks5 proxyservwr

**Comment by myth2loki** [comment]
> > how to use socks5 proxy?
> 
> --socks5 proxyserver

it worked, thanks

**Comment by jgonzis** [comment]
> > > how to use socks5 proxy?
> > 
> > 
> > --socks5 proxyserver
> 
> it worked, thanks

Thx for the feedback 🙂

**Comment by dhery** [comment]
Sir What method do you use when making socks5 proxy server ?

**Comment by jgonzis** [comment]
> Sir What method do you use when making socks5 proxy server ?

--socks5 proxyserver.... 

Normally ETHPROXY is the best solution
