### ISSUE TITLE
DNS over HTTPS resolved failed

### ISSUE THREAD

**Issue by BLCheung** [Lolliedieb/lolMiner-releases#1501]
![image](https://user-images.githubusercontent.com/19581432/161984166-e1f0e753-3991-4542-89f7-a405f3d9c529.png)
Why i always resolved failed? can make it success ?

**Comment by igralec84** [comment]
Are you using the "--tls" extra parameter and SSL port of the mining pool?

**Comment by igralec84** [comment]
> > Are you using the "--tls" extra parameter and SSL port of the mining pool?
> 
> I used ssl，is necessary in my region，other options are default

Checked my logs and i get the same thing, but don't see any problem with shares or anything.

**Comment by Gkozd** [comment]
Random Events/behaviour - sometimes it is working as intended (?), sometimes it is failing...
OK
![DNS over OK](https://user-images.githubusercontent.com/87426164/162275656-2553aa42-3407-42ad-8208-2e4f3ad5e5a5.JPG)

next run (batch file - win10) 
FAIL 
![DNS over  FAIL](https://user-images.githubusercontent.com/87426164/162275682-f46c9211-33ea-46ab-b7e9-c6a559c89dc4.JPG)

**Comment by jgonzis** [comment]
That sometimes is your ISP that block the connection to cloudflare. It is not a problem if fails try normal connection
