### ISSUE TITLE
How to choose which GPUs to DUAL mining ETH+TON?

### ISSUE THREAD

**Issue by chulakorn** [Lolliedieb/lolMiner-releases#1504]
Hi there,

I have some gpu with poor heat management and it could not handle ETH+TON and it lead to crashing the rig time to time.

Is there any extra argument to set

-> Majority of GPU do DUAL mining with ETH + TON
-> Some GPU doing ETH only

I tried dualdevice but it only either to choose which to mine ETH and another to TON

** Running the rig on HiveOS.

**Comment by naplesblue** [comment]
paste from hiveos config sample: using argument --dualdevices 4,5 +  for mining second coin on GPU3..GPU5. Combining with previous param means that GPU0..GPU2 will mine first coin GPU4..GPU5 will mine second coin and GPU3 is disabled.

**Comment by chulakorn** [comment]
@naplesblue yes, I tried that sample config, it went as I mentioned or at least what I have done

some gpu are mining ETH as main coin only and some will mine TON only.

but not running as ETH+TON and some to ETH only.

**Comment by chulakorn** [comment]
I overlooked 1.44 released note, below are the way out.

Example for --dualdevices and --maxdualimpact Consider a 6 card rig with --dualdevices 4,5 --maxdualimpact 0,0,*,*,*,* This rig will mine:

Eth only on GPUs 0 & 1 (ton dual mining disabled by maxdualimpact)
Eth + Ton on GPUs 2 & 3
Ton only on GPUs 4 & 5 (eth mining disabled by dualdevices)
