### ISSUE TITLE
3070 TI issue ETH+TON 

### ISSUE THREAD

**Issue by extronica01** [Lolliedieb/lolMiner-releases#1505]
I have 2 rigs, the 1st rig got 6x 3070 TI GPU while the 2nd Rig got 4x 3070 TI same brand and memory... if I run the rig for ETH only it can reach a maximum of 61 mh/s per gpu.. but when running ETH + TON there's always 1 GPU that can't reach its maximum potential no matter what settings I had made.. is this a miners issue or something else? core clock at 1110.  Heat is not a problem.. my temperature runs only at around 65 to 69.  im using WINDOWS 10 and the latest lolminer 1.48 and followed the recommended driver 512.15

![InkedproblemChild_LI](https://user-images.githubusercontent.com/103166103/162127794-c095e1fb-4811-409f-b79d-9b34bb89c299.jpg)

![eth](https://user-images.githubusercontent.com/103166103/162127847-74974c47-6605-47de-9c8f-4675f000edfd.JPG)

**Comment by sebek72** [comment]
Looks like you got unlucky with the silicon lottery

**Comment by Bedasek** [comment]
AAMOF, it could be the other way around and you got lucky with silicon lottery :)

Try to lower OC a lil bit on GPU 1. Then restart miner and see if you get higher MH.
It may sound crazy but in my case it got me higher hashrate even tho all my GPU are the same brand, etc.

**Comment by jgonzis** [comment]
> I have 2 rigs, the 1st rig got 6x 3070 TI GPU while the 2nd Rig got 4x 3070 TI same brand and memory... if I run the rig for ETH only it can reach a maximum of 61 mh/s per gpu.. but when running ETH + TON there's always 1 GPU that can't reach its maximum potential no matter what settings I had made.. is this a miners issue or something else? core clock at 1110. Heat is not a problem.. my temperature runs only at around 65 to 69. im using WINDOWS 10 and the latest lolminer 1.48 and followed the recommended driver 512.15
> 
> ![InkedproblemChild_LI](https://user-images.githubusercontent.com/103166103/162127794-c095e1fb-4811-409f-b79d-9b34bb89c299.jpg)
> 
> ![eth](https://user-images.githubusercontent.com/103166103/162127847-74974c47-6605-47de-9c8f-4675f000edfd.JPG)

Correctly... follow the guide of the other miner. Try reducing core clock and reduce steps of 200 the memory. It will be a moment that gets that unlock
