### ISSUE TITLE
HiveOS Settings EZIL

### ISSUE THREAD

**Issue by Shano592** [Lolliedieb/lolMiner-releases#1506]
Hi all, can someone please confirm with me the correct settings for HiveOS, for setting up ETH+ZIL using the EZIL pool?

![Screenshot_20220407-175628](https://user-images.githubusercontent.com/100468509/162154637-df55895e-d822-484e-bd15-de381fba9998.png)
![Screenshot_20220407-175619](https://user-images.githubusercontent.com/100468509/162154668-0ac98628-2590-49ea-86b8-129ede515e9a.png)

The wallet and everything is set up right, as i have been using TRex miner, but the ETH component in LOLMINER is hitting and holding a massive 78.5 LHR.

The issue I'm having is that the DAG files look to be rebuilding after each coin change (ETH/ZIL/ETH), and going through LHR calibration each time.  So I want to check that I have the correct arguments in the Flight Sheet.

**Comment by jgonzis** [comment]
> Hi all, can someone please confirm with me the correct settings for HiveOS, for setting up ETH+ZIL using the EZIL pool?
> 
> ![Screenshot_20220407-175628](https://user-images.githubusercontent.com/100468509/162154637-df55895e-d822-484e-bd15-de381fba9998.png) ![Screenshot_20220407-175619](https://user-images.githubusercontent.com/100468509/162154668-0ac98628-2590-49ea-86b8-129ede515e9a.png)
> 
> The wallet and everything is set up right, as i have been using TRex miner, but the ETH component in LOLMINER is hitting and holding a massive 78.5 LHR.
> 
> The issue I'm having is that the DAG files look to be rebuilding after each coin change (ETH/ZIL/ETH), and going through LHR calibration each time. So I want to check that I have the correct arguments in the Flight Sheet.

Ezil need %WAL%.Zilwallet unless you put the zilwallet will not work

**Comment by Shano592** [comment]
It is working.  I'm getting ZIL payout.  %WAL% in this case is both ETH and ZIL, as ETH.ZIL.

That is not the problem.  The problem is the DAG files being remade after the change in epoch, from 0 (ZIL) to 484/485 (ETH).  They are not being cached.

**Comment by jgonzis** [comment]
> It is working. I'm getting ZIL payout. %WAL% in this case is both ETH and ZIL, as ETH.ZIL.
> 
> That is not the problem. The problem is the DAG files being remade after the change in epoch, from 0 (ZIL) to 484/485 (ETH). They are not being cached.

Sorry I see the error

--enablezilcache 
--cclk 1750
--ethstratum ETHPROXY 

Write it like that.
