### ISSUE TITLE
Overclock settings only working briefly 

### ISSUE THREAD

**Issue by A01709042** [Lolliedieb/lolMiner-releases#1507]
Hey so I have a zotac 3080 lhr and I get around 73-74 mhs in trex, so I switched to lolminer and I’m getting 76+ Which is awesome but for some reason randomly after a few hours I will see and it gets down to 30-40 mh/s and I thought it could be lhr tuning but I realized after a while that it’s because my core clock is way above the locked core clock lock value I have it on and so it throttles and memory is not able to get overclocked, this gets fixed if I restart the miner. So the problem is this is while I use the nvidiaOC.exe utility because if I overclock directly in my bat file, if lolminer crashes it restarts and asks for admin privileges and it gets stuck until I realize I need to go to my pc or run Remote Desktop to click on it. So is there a way to setup my bat file with a coroutine so that my oc settings are kept without me needing to restart the miner or authorize admin privileges in case lolminer crashes? I checked and my gpu does not crash, and when it has crashed it doesn’t crash the miner and it just goes back to mine with normal oc, so the settings are not the problem. I just want to find a way to automate this Regardless of if I overclock in my bat file or through nvidiaOC.exe thanks 

Msi does not make an absolute core clock lock and since it fluctuates it doesn’t really have the same results to undervolt there than directly with the miner

**Comment by jgonzis** [comment]
> Hey so I have a zotac 3080 lhr and I get around 73-74 mhs in trex, so I switched to lolminer and I’m getting 76+ Which is awesome but for some reason randomly after a few hours I will see and it gets down to 30-40 mh/s and I thought it could be lhr tuning but I realized after a while that it’s because my core clock is way above the locked core clock lock value I have it on and so it throttles and memory is not able to get overclocked, this gets fixed if I restart the miner. So the problem is this is while I use the nvidiaOC.exe utility because if I overclock directly in my bat file, if lolminer crashes it restarts and asks for admin privileges and it gets stuck until I realize I need to go to my pc or run Remote Desktop to click on it. So is there a way to setup my bat file with a coroutine so that my oc settings are kept without me needing to restart the miner or authorize admin privileges in case lolminer crashes? I checked and my gpu does not crash, and when it has crashed it doesn’t crash the miner and it just goes back to mine with normal oc, so the settings are not the problem. I just want to find a way to automate this Regardless of if I overclock in my bat file or through nvidiaOC.exe thanks
> 
> Msi does not make an absolute core clock lock and since it fluctuates it doesn’t really have the same results to undervolt there than directly with the miner

It could be that epoch change that made you the LHR problem. Also why you don't do a loop?

LolNvidiaOC.exe....

:loop 
LolMiner.exe ....
Timeout 10
goto loop

So in case crash will do 10s timeout and restart. I will update soon the watchdog file that I hope helps
