### ISSUE TITLE
R9 390 doesn't dual mine TON

### ISSUE THREAD

**Issue by jone3fingers** [Lolliedieb/lolMiner-releases#1509]
I am using HiveOS I have been mining the last week with a new rig and I am new to mining. I have 2x R9-390's and a RX590 Fatboy. My rig has been working perfectly with ETH-Zil getting 27Mh/s and 30 Mh/s on cards. Today I thought I would try adding TON into the mix. The RX590 is working great, but the R9 390's are not working at all for TON.

**Comment by jgonzis** [comment]
> I am using HiveOS I have been mining the last week with a new rig and I am new to mining. I have 2x R9-390's and a RX590 Fatboy. My rig has been working perfectly with ETH-Zil getting 27Mh/s and 30 Mh/s on cards. Today I thought I would try adding TON into the mix. The RX590 is working great, but the R9 390's are not working at all for TON.

Dual Mining is working on Polaris and newer GPUs
