### ISSUE TITLE
 Zombie Mode hash rate reduced: Memory allocation error: Insufficient memory for Epoch 387:

### ISSUE THREAD

**Issue by OdinIsWithUs** [Lolliedieb/lolMiner-releases#151]
I am being displayed all three of these messages when trying to run the most recent software.

I have adjusted the 4G parameters to try and work around this, but nothing I seem to do makes a single difference. 

This is what I have entered currently. I have changed them both multiple times and still nothing.

I have the Nvidia GeForce 1650, 4GB.

**Comment by sobertram** [comment]
> I am being displayed all three of these messages when trying to run the most recent software.
> 
> I have adjusted the 4G parameters to try and work around this, but nothing I seem to do makes a single difference.
> 
> This is what I have entered currently. I have changed them both multiple times and still nothing.
> 
> I have the Nvidia GeForce 1650, 4GB.

I also have the same zotac Geforce 1650 4GB card and I am able to get it to work for me but the hashrate is too low so i stopped. Here are the settings i used. BTW for mine nvidia-smi shows 3911M of memory.

--4g-alloc-size 3840

Here is an excerpt of it running.

./mine_eth_4G.sh
+---------------------------------------------------------+
|    _       _ __  __ _                   _   _  ___      |
|   | | ___ | |  \/  (_)_ __   ___ _ __  / | / |/ _ \     |
|   | |/ _ \| | |\/| | | '_ \ / _ \ '__| | | | | (_) |    |
|   | | (_) | | |  | | | | | |  __/ |    | |_| |\__, |    |
|   |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_|  /_/     |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|            Made by Lolliedieb, January 2021             |
+---------------------------------------------------------+

Setup Miner...
Device 0:
    Name:    GeForce GTX 1650
    Address: 3:0
    Vendor:  NVIDIA Corporation
    Memory:  3911 MByte
    --4g-alloc-size 3840
    Max epoch (approx): 352
    Active:  true (Selected Algorithm: ETHash)

Connecting to pool...
Connected to us1.ethermine.org:5555  (TLS enabled)
TLS Handshake success
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x1fXXXXXXXXXXXXXXXXXXXXXXXXXXXXXEc.worker
New job received: 0x8a6b67 Epoch: 389 Target: 0000000112e0be82
-------------------------------------------------------
         Generating light cache for epoch 389
-------------------------------------------------------
Start Mining...
-------------------------------------------------------
     Done (2812 ms), size of new DAG: 4136 MByte
-------------------------------------------------------
GPU 0: insufficient memory for DAG epoch 389.
GPU 0: will be in Zombie mode with reduced hashrate.
Start DAG gen on GPU 0 (memory saving mode)
New job received: 0x89eb7e Epoch: 389 Target: 0000000112e0be82
New job received: 0x5dace0 Epoch: 389 Target: 0000000112e0be82
New job received: 0xc134c6 Epoch: 389 Target: 0000000112e0be82
New job received: 0x903dd6 Epoch: 389 Target: 0000000112e0be82
New job received: 0xddc14e Epoch: 389 Target: 0000000112e0be82
New job received: 0x4200cf Epoch: 389 Target: 0000000112e0be82
Finished DAG gen on GPU 0 (15356 ms)
New job received: 0x3d03bb Epoch: 389 Target: 0000000112e0be82
New job received: 0xaef0e8 Epoch: 389 Target: 0000000112e0be82
New job received: 0x652744 Epoch: 389 Target: 0000000112e0be82
Average speed (30s): 0.23 mh/s
New job received: 0xeb0f24 Epoch: 389 Target: 0000000112e0be82
New job received: 0xda9e80 Epoch: 389 Target: 0000000112e0be82
New job received: 0x84a957 Epoch: 389 Target: 0000000112e0be82
New job received: 0xab6d0b Epoch: 389 Target: 0000000112e0be82
New job received: 0xb4e9d9 Epoch: 389 Target: 0000000112e0be82
New job received: 0x9866e0 Epoch: 389 Target: 0000000112e0be82
New job received: 0xfa1b4e Epoch: 389 Target: 0000000112e0be82
New job received: 0xb6f731 Epoch: 389 Target: 0000000112e0be82
New job received: 0xcbf800 Epoch: 389 Target: 0000000112e0be82
New job received: 0x431b8d Epoch: 389 Target: 0000000112e0be82
Average speed (30s): 0.58 mh/s
New job received: 0xf132c5 Epoch: 389 Target: 0000000112e0be82

**Comment by jgonzis** [comment]
Change: --4g-alloc-size 3840 for --4g-alloc-size 4072 or --4g-alloc-size 4080... higher value more speed you will have.

**Comment by sobertram** [comment]
yes if the card can handle but the miner craps out unless i have it set to
the value, 3840 because as you can see from the miner as well, the card
only has 3911M available. Crap card, I would never buy it for mining but
had it for other things and decided to see if i can mine with it. Mining
ravencoin with it now with another miner.

**Comment by jgonzis** [comment]
Zombie Mode not supported on Nvidia. Use new CUDA for ETC or ERGO
