### ISSUE TITLE
Low hashrate on RTX 2070 (TON)

### ISSUE THREAD

**Issue by JustAResearcher** [Lolliedieb/lolMiner-releases#1511]
Currently dual mining ETH/TON And the 2070 cards get about 1.2GH of ton hashrate. My RTX 2060 get 1.2GH and 2070 super gets 1.7GH. So that should put a 2070 around 1,5GH.

**Comment by Bedasek** [comment]
IDK man, but I kinda doubt that a single RTX2070 gets you 1.2 GH/s of TON hashrate while dualmining ETH+TON.
I'm getting it on 3070, let alone on 2070
Check it out here - https://www.hashrate.no/2070

**Comment by JustAResearcher** [comment]
Have you used Lolminer 1.48? That hashrate website is just wrong. I get 1.8GH on 2080, 1.7GH on 2070 super and 1.2GH on both 2070 and 2060. I have a whole farm mining this right now lol.

**Comment by jgonzis** [comment]
The hashrate of TON depends on the Core Mhz... more Core more TON and More Watts

**Comment by JustAResearcher** [comment]
> The hashrate of TON depends on the Core Mhz... more Core more TON and More Watts

I understand this lol. This is regardless of power levels. Something is not right with the miner on 2070.

**Comment by jgonzis** [comment]
> > The hashrate of TON depends on the Core Mhz... more Core more TON and More Watts
> 
> I understand this lol. This is regardless of power levels. Something is not right with the miner on 2070.

No is not, problem is that 2070 is quite similar to 2060, no more space to do more TON unless you sacrifice ETH...
