### ISSUE TITLE
Very low hashrate on Ubuntu 

### ISSUE THREAD

**Issue by LulaSvob** [Lolliedieb/lolMiner-releases#1513]
Hi,

I've been trying to make it work for some time now but to no avail. 
I am getting very low hash rates on lolMiner on Ubuntu compared to NBMiner for example. 

At 14th minute of running lolMiner I am at 30-ish mh/s whereas with NB I get 44.9 at minute 3. 
Overclock settings stay the same between both miners and I do not touch. 
Here is other info that may help:

**lolMiner info:**
![Screenshot from 2022-04-09 08-39-06](https://user-images.githubusercontent.com/32610546/162558386-21dededf-5e86-4254-b68a-ea196d03aae6.png)

**NBMiner info with same OC settings:**
![Screenshot from 2022-04-09 08-43-13](https://user-images.githubusercontent.com/32610546/162558413-60fcc9c1-79fb-4290-b1e7-2d27cdb0503f.png)

**Drivers:**
![Screenshot from 2022-04-09 08-44-04](https://user-images.githubusercontent.com/32610546/162558422-95e4bc06-2c13-4c6d-9b28-d3fbe6219a90.png)

**OS Info:**
![Screenshot from 2022-04-09 08-44-17](https://user-images.githubusercontent.com/32610546/162558430-7521ffe4-bd01-467b-95b2-30d39b0f48a0.png)

I tried searching for a way to lock memory clock or to tune LHR on linux but couldn't find a way to do it. 
Please advise as to what can be the problem here.

**Comment by jgonzis** [comment]
Have you fixed the lock Core to 1050 to try?
Or are you using offset Core?

**Comment by LulaSvob** [comment]
I usually fix core clock with miner but here I don't see such an option. Do you have anything else in mind? 

In this rig I use shell scripts and Nvidia drivers/server and GWE to do tuning and OC. 
Maybe it's worth mentioning that I do not have these problems on my other couple of rigs, one running HiveOS and the other Windows - they both run quite smoothly with quite higher Mh/s than NBMiner used to provide for them.

**Comment by jgonzis** [comment]
> I usually fix core clock with miner but here I don't see such an option. Do you have anything else in mind?
> 
> In this rig I use shell scripts and Nvidia drivers/server and GWE to do tuning and OC. Maybe it's worth mentioning that I do not have these problems on my other couple of rigs, one running HiveOS and the other Windows - they both run quite smoothly with quite higher Mh/s than NBMiner used to provide for them.

You can try as parameters --cclk or use nvidia-smi -lgc value

**Comment by LulaSvob** [comment]
Ok, fixing the core clock doesn't work either. See below screenshot and bear in mind that I intentionally left it running for 21 minutes or so without anything else running on the computer to make sure it's not anything external. I do not have these issues with any other miner and am using exact same overclock for other miners too (except now I added the fixed core clock for lolMiner)

![image](https://user-images.githubusercontent.com/32610546/165016888-26d9079b-3f8d-42da-9c3c-52c9e0d12718.png)

**Comment by jgonzis** [comment]
> Ok, fixing the core clock doesn't work either. See below screenshot and bear in mind that I intentionally left it running for 21 minutes or so without anything else running on the computer to make sure it's not anything external. I do not have these issues with any other miner and am using exact same overclock for other miners too (except now I added the fixed core clock for lolMiner)
> 
> ![image](https://user-images.githubusercontent.com/32610546/165016888-26d9079b-3f8d-42da-9c3c-52c9e0d12718.png)

Thx for the photo. Which Nvidia Driver are you using?

**Comment by jgonzis** [comment]
> 470.103.01 on Ubuntu 21.10

Try a higher lock clock 1550.. it seems that OC is applied late, for the 82.x LHR ... I don't know if you are mining cpu or similar. I suppose monitor is connected and that makes some changes too

**Comment by LulaSvob** [comment]
Doesn't work either. I even left it overnight because at first it was reporting very high hashrate on the server but in about 12 hours it dropped to 20. 

I guess it's just not meant to be, I will continue using NB miner for now with a couple of MH/s lower hashrate.

**Comment by jgonzis** [comment]
> Doesn't work either. I even left it overnight because at first it was reporting very high hashrate on the server but in about 12 hours it dropped to 20.
> 
> I guess it's just not meant to be, I will continue using NB miner for now with a couple of MH/s lower hashrate.

If you put old versión 1.46a it should work, but not with new unlock.  It should be something related to that Ubuntu 21.10... quite curios what it could  be. I can only say if you wouls like to burn and usb with a mining OS like MMPOS or HiveOS to test It...

**Comment by LulaSvob** [comment]
As I said above I have a couple of other rigs, one on HiveOS and one on Windows and they both work just fine. It's only the Linux one that has problems but it has only 1 card in it, so not a huge problem. Thanks very much for being so responsive and have a nice weekend. :)

**Comment by jgonzis** [comment]
> As I said above I have a couple of other rigs, one on HiveOS and one on Windows and they both work just fine. It's only the Linux one that has problems but it has only 1 card in it, so not a huge problem. Thanks very much for being so responsive and have a nice weekend. :)
If you can give a test with 1.46a just curious to confirm is new unlocker. Thx to you for trying lolMiner 😊

**Comment by LulaSvob** [comment]
1.46a is way better, meaning it goes up to 43-ish which is very close to what I get with other miners.

![image](https://user-images.githubusercontent.com/32610546/166137582-def3c818-57cf-4497-883c-06da9393a2c5.png)

![image](https://user-images.githubusercontent.com/32610546/166137541-f6c52315-e4d9-4082-859d-876536ea126b.png)

But not quite as good as others though as I get 44-ish on NB for instance and 1.46a drops to 41-42 quite often

![image](https://user-images.githubusercontent.com/32610546/166137653-175cbe2f-af07-45e7-b05d-3b8a24473bfb.png)

**Comment by jgonzis** [comment]
> 1.46a is way better, meaning it goes up to 43-ish which is very close to what I get with other miners.
> 
> ![image](https://user-images.githubusercontent.com/32610546/166137582-def3c818-57cf-4497-883c-06da9393a2c5.png)
> 
> ![image](https://user-images.githubusercontent.com/32610546/166137541-f6c52315-e4d9-4082-859d-876536ea126b.png)
> 
> But not quite as good as others though as I get 44-ish on NB for instance and 1.46a drops to 41-42 quite often
> 
> ![image](https://user-images.githubusercontent.com/32610546/166137653-175cbe2f-af07-45e7-b05d-3b8a24473bfb.png)

That drops are normally if there is monitor connected. Could be reduce with a higher Core clock. It is quite interesting then that the new unlock is not going properly.   I assume is better lol that NBMiner 43vs 44 considering that NBMiner hashrate is overestimated 😅...

Also for last curiosity making dual mining in 1.47 or 1.48 same problem with the unlock?.

I hope next 1.49 could solve your issue...

**Comment by LulaSvob** [comment]
Hey, I just updated to Ubuntu 22.04 LTS and results are the same for 1.48 single mining eth. 

I am not doing dual mining in principal but just gave it a try with default settings for 1.48 with dual_mine_eth_ton.sh and here's the result:

![image](https://user-images.githubusercontent.com/32610546/166193308-97089c16-8fa8-4c63-b9f1-6037f9a3e877.png)

Interestingly the pool hashrate this time is higher at the 6-7 minute mark even though after I took the screenshot it started dropping but keeps at around 40ish. 

I get ya about NBMiner. Will def. give lol another try with higher core clock and maybe dual mining to see if it gets me further.

**Comment by jgonzis** [comment]
> Hey, I just updated to Ubuntu 22.04 LTS and results are the same for 1.48 single mining eth.
> 
> I am not doing dual mining in principal but just gave it a try with default settings for 1.48 with dual_mine_eth_ton.sh and here's the result:
> 
> ![image](https://user-images.githubusercontent.com/32610546/166193308-97089c16-8fa8-4c63-b9f1-6037f9a3e877.png)
> 
> Interestingly the pool hashrate this time is higher at the 6-7 minute mark even though after I took the screenshot it started dropping but keeps at around 40ish.
> 
> I get ya about NBMiner. Will def. give lol another try with higher core clock and maybe dual mining to see if it gets me further.

the pool is quite lucky in just 7 min hehe... it will go down for sure. Interesant that seems enter directly locked... really interesting

**Comment by xertSuns1** [comment]
Hi can I ask if you are interested in this. I am.Ok so if it at all is just me or are you going to help in this? I will pay you. This can be stressful so please work with me .I am interested in what else you would like to do? I have some things that need to be attended to....please email me

**Comment by xertSuns1** [comment]
Satoshi will be looking into it on occasion.
