### ISSUE TITLE
LHR detection fails with every new epoch

### ISSUE THREAD

**Issue by igralec84** [Lolliedieb/lolMiner-releases#1514]
Anyone else experiencing this, my 3080Ti often get detected as FHR even if you start the miner and needs a couple of tried to get detected as LHR, but after every new epoch when a new DAG file is built, i find it detected as FHR and doing 62mhs. Works stable until the next epoch.

      Name         Speed    Pool     Shares   Best    Eff.  Power  CCLK   MCLK  Core  Junc   Mem  Fan   LHR
                    Mh/s    Mh/s     A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Temp  Temp  Pct   Pct
**GPU 1 RTX 3080 Ti  92.76**   92.78   5648/0/0  26.3T   0.371  249.8  1498  10541    58    67    92   60  77.5

------------------------------------------------------- 
          Generated light cache for epoch 485 

**GPU 1: fault during  LHR detection . Continuing in full hash rate mode.** 

      Name         Speed    Pool     Shares   Best    Eff.  Power  CCLK   MCLK  Core  Junc   Mem  Fan   LHR
                    Mh/s    Mh/s     A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Temp  Temp  Pct   Pct
**GPU 1 RTX 3080 Ti  62.36**   92.73   5650/0/0  26.3T   0.340  191.6  1498  10541    50    58    78   60  77.5

**Comment by Shano592** [comment]
Every time a new DAG file is created, my system fires through LHR calibration.  See issue 1506...

**Comment by jgonzis** [comment]
> Anyone else experiencing this, my 3080Ti often get detected as FHR even if you start the miner and needs a couple of tried to get detected as LHR, but after every new epoch when a new DAG file is built, i find it detected as FHR and doing 62mhs. Works stable until the next epoch.
> 
> ```
>   Name         Speed    Pool     Shares   Best    Eff.  Power  CCLK   MCLK  Core  Junc   Mem  Fan   LHR
>                 Mh/s    Mh/s     A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Temp  Temp  Pct   Pct
> ```
> 
> **GPU 1 RTX 3080 Ti 92.76** 92.78 5648/0/0 26.3T 0.371 249.8 1498 10541 58 67 92 60 77.5
> 
> ```
>       Generated light cache for epoch 485 
> ```
> 
> **GPU 1: fault during LHR detection . Continuing in full hash rate mode.**
> 
> ```
>   Name         Speed    Pool     Shares   Best    Eff.  Power  CCLK   MCLK  Core  Junc   Mem  Fan   LHR
>                 Mh/s    Mh/s     A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Temp  Temp  Pct   Pct
> ```
> 
> **GPU 1 RTX 3080 Ti 62.36** 92.73 5650/0/0 26.3T 0.340 191.6 1498 10541 50 58 78 60 77.5

That needs and improvements, in some is working other not... needs a new Detection

**Comment by Bedasek** [comment]
1. Do you have more LHR cards and just this single one having issues?
2. are you running version v1.48 ? Cuz what you are describing used to be a bug in previous releases. v1.48 fixed it

**Comment by igralec84** [comment]
> 1. Do you have more LHR cards and just this single one having issues?
> 
>     2. are you running version v1.48 ? Cuz what you are describing used to be a bug in previous releases. v1.48 fixed it

1. Yes i have another LHR card 3060 but doesn't have this problem, always detected as LHR.
2. Running v1.48 on Win 11.

**Comment by jgonzis** [comment]
> > 1. Do you have more LHR cards and just this single one having issues?
> >    
> >    2. are you running version v1.48 ? Cuz what you are describing used to be a bug in previous releases. v1.48 fixed it
> 
> 1. Yes i have another LHR card 3060 but doesn't have this problem, always detected as LHR.
> 2. Running v1.48 on Win 11.

Any option to see OC and full stats mining (the Blue stats)

**Comment by igralec84** [comment]
![miage](https://snipboard.io/a8cMLG.jpg)

Core locked at 1500mhz @750mv, memory +1300mhz, PL 100%. Been running these settings since September on various miners. Currently v1.48 is around 3.5mh/s and 15w on the wall better than gminer i used before.

**Comment by jgonzis** [comment]
> ![miage](https://camo.githubusercontent.com/2c97ad52ef70d61971e0fe1d6f477209f73860610670df68313ec547d7b93568/68747470733a2f2f736e6970626f6172642e696f2f6138634d4c472e6a7067)
> 
> Core locked at 1500mhz @750mv, memory +1300mhz, PL 100%. Been running these settings since September on various miners. Currently v1.48 is around 3.5mh/s and 15w on the wall better than gminer i used before. Using Afterburner to OC, did notice if i close the miner, clocks seem to be a little higher than when mining on the 3060 and 3070, which causes DAG needing to be repaired every time unless i remove the OC until DAG is finished. Drivers are 512.15.

Thx for the feedback, with Linux was proved that epoch changes was working could it be Windows not 100% let's have a look

**Comment by jegerima** [comment]
I had the same problem and I solved it upgrading to 512.15 Nvidia driver
