### ISSUE TITLE
Ref: #1506 Closed without solution.  HiveOS settings for EZIL with LolMiner

### ISSUE THREAD

**Issue by Shano592** [Lolliedieb/lolMiner-releases#1515]
> Hi all, can someone please confirm with me the correct settings for HiveOS, for setting up ETH+ZIL using the EZIL pool?
> 
> ![Screenshot_20220407-175628](https://user-images.githubusercontent.com/100468509/162154637-df55895e-d822-484e-bd15-de381fba9998.png) ![Screenshot_20220407-175619](https://user-images.githubusercontent.com/100468509/162154668-0ac98628-2590-49ea-86b8-129ede515e9a.png)
> 
> The wallet and everything is set up right, as i have been using TRex miner, but the ETH component in LOLMINER is hitting and holding a massive 78.5 LHR.
> 
> The issue I'm having is that the DAG files look to be rebuilding after each coin change (ETH/ZIL/ETH), and going through LHR calibration each time. So I want to check that I have the correct arguments in the Flight Sheet.

Ezil need %WAL%.Zilwallet unless you put the zilwallet will not work

_Originally posted by @jgonzis in https://github.com/Lolliedieb/lolMiner-releases/issues/1506#issuecomment-1093906377_

**Comment by Shano592** [comment]
I am getting paid in ZIL and ETH.  The wallet is correct and the EZIL page reflects this.

The problem is that the DAG files do not store in cache, and LHR calibration happens at each change.

**Comment by jgonzis** [comment]
> I am getting paid in ZIL and ETH. The wallet is correct and the EZIL page reflects this.
> 
> The problem is that the DAG files do not store in cache, and LHR calibration happens at each change.
> 
> This is why I am asking for confirmation of the settings, before I close this issue. The ones in the images I have linked are not working.

Could it be that you have 6Gb cards.

Also to enablezilcache is like --enablezilcache

**Comment by Shano592** [comment]
Almost.  This is the solution that gave the correct responses in LolMiner v1.48.

Also, using 12GB cards.  V2 LHR RTX3060''s

![Screenshot_20220411-180001](https://user-images.githubusercontent.com/100468509/162691447-43c7a5ac-14ca-43c4-858c-c4d4420efa51.png)
