### ISSUE TITLE
1.47和1.48切换网络出现低算力未能恢复lhr 3070ti

### ISSUE THREAD

**Issue by xiangcailai** [Lolliedieb/lolMiner-releases#1516]
![1649343988(1)](https://user-images.githubusercontent.com/103317183/162573773-fee4376f-f05b-4537-b86d-fdea67bd6d60.jpg)
算力变成0.8m后无法重启lhr 一直被锁定 3070ti

**Comment by xiangcailai** [comment]
@jgonzis @Lolliedieb

**Comment by jgonzis** [comment]
> ![1649343988(1)](https://user-images.githubusercontent.com/103317183/162573773-fee4376f-f05b-4537-b86d-fdea67bd6d60.jpg) 算力变成0.8m后无法重启lhr 一直被锁定 3070ti

That could be the epoch changes. Also if you are in Nicehash it has  been notify some problems in their servers

**Comment by xrtw** [comment]
no nicehash. this happens if internet was lost. sorry

**Comment by jgonzis** [comment]
> no nicehash. this happens if internet was lost. sorry

Thx for the feedback
