### ISSUE TITLE
Another question…

### ISSUE THREAD

**Issue by A01709042** [Lolliedieb/lolMiner-releases#1517]
Sorry to bother again, I’ll try to help people here in return <3

anyways, I’m the guy you gave the loop instructions to, the one with problems using nvidiaoc.exe 

am I supposed to remove the watchdog or remove something else from my bat file after adding the loop you instructed me to? i feel it could  conflict with something, right? 

And I’m not very familiar with batch files, is the “normal” OC (not nvidiaOC.exe), the one done through the bat file, made by lolminer or is it an nvidia or windows feature? Because if so, then I could study batch syntax to write my own master script so that the oc is done there and it just runs a coroutine/loop with the miner batch inside it 

thanks a lot and thanks for this great lhr unlock!

**Comment by jgonzis** [comment]
Have you tryed the last watchdog file?

Just decompress it in the folder of lolminer and edit the editable part. Try to see is works to you. You have all explained better in:

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)

**Comment by A01709042** [comment]
Thanks! I will try that, I also found your guide in absolute core clock lock and it worked, but if msi crashes I will try your guide. 

Thanks a lot for the explanation it’s really helpful. 

Btw I can help with improving your  translations if you want help with that
