### ISSUE TITLE
Pool https://next.ton-pool.com timeout or send defect message: " "

### ISSUE THREAD

**Issue by oguzhaslak** [Lolliedieb/lolMiner-releases#1518]
in 1.48  (windows )
too many errors
DNS over HTTPS resolve failed - switching to standard resolve
Connected to next.ton-pool.com(172.67.72.126):443  (TLS disabled)

**Comment by jgonzis** [comment]
> in 1.48 (windows ) too many errors DNS over HTTPS resolve failed - switching to standard resolve Connected to next.ton-pool.com(172.67.72.126):443 (TLS disabled)

Try the wss://eu1.stratum.ton-pool.com/stratum

**Comment by oguzhaslak** [comment]
wss://eu1.stratum.ton-pool.com/stratum solved my issue with extraparameters --tls=1 --dualtls=1 --ton-mode 3 on rx 6600/6700
