### ISSUE TITLE
Windows 11 3080Ti LHR只有50%

### ISSUE THREAD

**Issue by rxszcn** [Lolliedieb/lolMiner-releases#1519]
3080Ti，Windows 11最高只能60m左右，而在WIndows 10可以到90m。
都是512.15驱动。请在Windows 11 上亲自测试。

**Comment by jgonzis** [comment]
> 3080Ti，Windows 11最高只能60m左右，而在WIndows 10可以到90m。 都是512.15驱动。请在Windows 11 上亲自测试。

Share a Photo.

Normally problem is PL Is not at 100% and you don't have locked the core for example at 1200. 

Guide: https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)
