### ISSUE TITLE
Bug name worker on MPH

### ISSUE THREAD

**Issue by Salvo52** [Lolliedieb/lolMiner-releases#1520]
Hi,
I 've issue with 1.48 on MiningPoolHub that i hasnt with 1.46a.
The worker name is "doubled".
When i start 1.46a miner  line "Authorized worker " write only "user" but in 1.48 that's write  "user.worker"
So that's do this on pool :  user.worker.worker
Thanks

**Comment by jgonzis** [comment]
> Hi, I 've issue with 1.48 on MiningPoolHub that i hasnt with 1.46a. The worker name is "doubled". When i start 1.46a miner line "Authorized worker " write only "user" but in 1.48 that's write "user.worker" So that's do this on pool : user.worker.worker Thanks

Use wallet.worker or --user wallet --worker worker don't put 2 times the worler
