### ISSUE TITLE
Wall of Stats

### ISSUE THREAD

**Issue by JackDeRke** [Lolliedieb/lolMiner-releases#1522]
Maybe I just don´t find it.
In the Wall of stats part I see that sometimes the layout is vertical and sometimes horizontal.
Meaning the direction the GPUs are listed. Is there a command to turn these? I´d prefere them listed side by side instead of in rows.
Thanks :)

**Comment by jgonzis** [comment]
> Maybe I just don´t find it. In the Wall of stats part I see that sometimes the layout is vertical and sometimes horizontal. Meaning the direction the GPUs are listed. Is there a command to turn these? I´d prefere them listed side by side instead of in rows. Thanks :)

Just only use --vstats instead --hstata
