### ISSUE TITLE
1.48 wont start on 3060v1 

### ISSUE THREAD

**Issue by oguzhaslak** [Lolliedieb/lolMiner-releases#1525]
i try with drivers 470.05 and 512.15 
both gives 0 hashrate on this new version

**Comment by jgonzis** [comment]
> i try with drivers 470.05 and 512.15 both gives 0 hashrate on this new version

With 3060v1, please use 470.05, that is the unlocker. if you want add parameter --lhrtune off that will avoid any detection of LHR
