### ISSUE TITLE
ETH/ZIL+TON re-calibrate unlocker all the time 3060 V2

### ISSUE THREAD

**Issue by mmll1** [Lolliedieb/lolMiner-releases#1526]
Hi
Lolminer 1.48 re-calibrate unlocker all the time. This problem exists for 3060 V2 only, all other RTX cards are doing very well.
Linux  510.60.02, HIVEOS and POOL, 6x3060 V2, 2600W PSU. All RTX cards have the same input paramters --enablezilcache 1, --hstats 200
![image](https://user-images.githubusercontent.com/59337355/162764662-7ea8b65f-4f6e-489d-828b-9f7704d63cd5.png)
24 h stats
I have counted number of re-calibrate unlocker, It were between 10-20 per hour in 24 h mining stats.
I think that Lolminer have issue with 3060 V2 Cards.

**Comment by jgonzis** [comment]
> Hi Lolminer 1.48 re-calibrate unlocker all the time. This problem exists for 3060 V2 only, all other RTX cards are doing very well. Linux 510.60.02, HIVEOS and POOL, 6x3060 V2, 2600W PSU. All RTX cards have the same input paramters --enablezilcache 1, --hstats 200 ![image](https://user-images.githubusercontent.com/59337355/162764662-7ea8b65f-4f6e-489d-828b-9f7704d63cd5.png) 24 h stats I have counted number of re-calibrate unlocker, It were between 10-20 per hour in 24 h mining stats. I think that Lolminer have issue with 3060 V2 Cards.

Well that is quite normal... I recommend to put only --enablezilcache the 1 is not need it. Could it be that also with TON that makes it harded. 

Which Nvidia Driver are you using?. 470.103.01 or 510.54 are probably the most stable

**Comment by mmll1** [comment]
N 510.60.02 driver.
Strange, this is happening with 3060 V2 cards only.
Here you can see, 24 h stats with 3070 Ti, with the same paramteres. No gaps, straight line. So It should be somthing wrong with miner for 3060 cards 
![image](https://user-images.githubusercontent.com/59337355/162902140-cef7c4f0-ed55-46f9-94a2-700f0ea8eccf.png)

**Comment by jgonzis** [comment]
> N 510.60.02 driver. Strange, this is happening with 3060 V2 cards only. Here you can see, 24 h stats with 3070 Ti, with the same paramteres. No gaps, straight line. So It should be somthing wrong with miner for 3060 cards ![image](https://user-images.githubusercontent.com/59337355/162902140-cef7c4f0-ed55-46f9-94a2-700f0ea8eccf.png)

Could it be interesting to check a little bit the miner stats and the OC... or... that a limit on the LHRTUNE could help too. Is it CPU Mining in the 3060v2 rig?

**Comment by mmll1** [comment]
I decreased OC as low as possible, the same issue. NO CPU mining, GPU only. I tried with gminer the same OC, and worked fine, no gaps just straight line. Yes, I can limit --lhr tune, consequence is lower hash rate. If I do that, then better I use gminer.

**Comment by jgonzis** [comment]
> I decreased OC as low as possible, the same issue. NO CPU mining, GPU only. I tried with gminer the same OC, and worked fine, no gaps just straight line. Yes, I can limit --lhr tune, consequence is lower hash rate. If I do that, then better I use gminer.

Make a comparative, directly don't decrease, that are read of hiveOS ... check the Miner Log to see after a 24hours. Don't forget about Fee in dual difference too when you make that comparative to others

**Comment by mmll1** [comment]
Checking log file all the time, but no improvement. Yes, I know about a fee, for that reason I'm staying with lolminer, but if you won't fix this with 3060 in new version, I'll use another miner. I'm not the only one who has issues with 3060 V2 cards, it got to be on miner side.
