### ISSUE TITLE
3080ti dodge the unlock

### ISSUE THREAD

**Issue by frentevermina** [Lolliedieb/lolMiner-releases#1527]
I am observing on Windows, 3080 ti is detected as lhr correctly, but after some time, the hash rate starts to drop down to 40mh/s and it doesn't get unlocked again. I have to close and open the miner again.

Tested with different OC and undervolt. Nothing changes.

I don't know if it's because of the new lolminer version or the recommended drivers for this new version.

**Comment by jgonzis** [comment]
> I am observing on Windows, 3080 ti is detected as lhr correctly, but after some time, the hash rate starts to drop down to 40mh/s and it doesn't get unlocked again. I have to close and open the miner again.
> 
> Tested with different OC and undervolt. Nothing changes.
> 
> I don't know if it's because of the new lolminer version or the recommended drivers for this new version.

What type of mining are you doing?. If you are doing ZIL or similar that could happen, add please --enablezilcache

Also which Nvidia Drivers are you using?

**Comment by frentevermina** [comment]
I am only mining eth. 

I am using 512.15 Nvida drivers (the recommended drivers for 1.48). Before i used 472.12 Only happens with 3080ti, my others GPUs (3060ti) are working fine, never drops.
