### ISSUE TITLE
1.48 no hashrate reported on pool - TON

### ISSUE THREAD

**Issue by ibby24** [Lolliedieb/lolMiner-releases#1528]
Hello,

Recently I upgraded to lolminer 1.48 hive os Nd changed the flight sheets to 1.48. 

After the change the miner spun up and started mining.

A few days later I checked the ton stats and they were near 0. 

I am on the whales tonpool. 

So I reverted the miner back to 1.47 andits been working fine. 

I am not sure if anyone else has had this issue

**Comment by jgonzis** [comment]
> Hello,
> 
> Recently I upgraded to lolminer 1.48 hive os Nd changed the flight sheets to 1.48.
> 
> After the change the miner spun up and started mining.
> 
> A few days later I checked the ton stats and they were near 0.
> 
> I am on the whales tonpool.
> 
> So I reverted the miner back to 1.47 andits been working fine.
> 
> I am not sure if anyone else has had this issue

It could the %WORKER_NAME%, we found a small bug in 1.48 that Worker Name should be put in the worker text box or with --dualworker ....
