### ISSUE TITLE
Issues hashrate RTX 3080 LHR

### ISSUE THREAD

**Issue by Stevejobs1992** [Lolliedieb/lolMiner-releases#1529]
Hello my freinds
I have RTX 3080 LHR Asus Tuf
I mining in hiveos and ETH+TON
for defult hashrate 3080 lhr 74 mh
My card only 45 mh
Core 1500
Mem 2850
Pl 0

why?

**Comment by jgonzis** [comment]
> Hello my freinds I have RTX 3080 LHR Asus Tuf I mining in hiveos and ETH+TON for defult hashrate 3080 lhr 74 mh My card only 45 mh Core 1500 Mem 2850 Pl 0
> 
> why?

Why Nvidia Drivers are you using?. Could you try to reduce Core to 1200 and Memory a pair of steps too?. 

Just try a bit reduction to see if gets that hashrate
