### ISSUE TITLE
The memory adjustment of gddr5 or gddr5x

### ISSUE THREAD

**Issue by wen936988** [Lolliedieb/lolMiner-releases#1530]
The memory adjustment of gddr5 or gddr5x, such as -- MT of T-Rex, can greatly improve the computing power of gtx1060. Does lolminer have such a function?

**Comment by jgonzis** [comment]
> The memory adjustment of gddr5 or gddr5x, such as -- MT of T-Rex, can greatly improve the computing power of gtx1060. Does lolminer have such a function?

That is a feature request... that is in the TODO List. They have done good job with that feature
