### ISSUE TITLE
Lolminer 1.48 not working on HiveOS after last update

### ISSUE THREAD

**Issue by MonkeyFarm** [Lolliedieb/lolMiner-releases#1532]
“Lost connection to stratum server”
Other miners are working fine
I did unset FS deleted and made a new 
Still getting the connection error. 

Someone may help me to fix it ? 
I already downgraded To 1.47 and the same error remains

**Comment by jgonzis** [comment]
> “Lost connection to stratum server” Other miners are working fine I did unset FS deleted and made a new Still getting the connection error.
> 
> Someone may help me to fix it ? I already downgraded To 1.47 and the same error remains

Could you please share a photo Flightsheet and Miner log to try to guide you please?.
