### ISSUE TITLE
dual mining on same pool

### ISSUE THREAD

**Issue by ekinmanyak123** [Lolliedieb/lolMiner-releases#1533]
Is it possible to dual mine on same pool 
For example:
etc/etc

**Comment by jgonzis** [comment]
> Is it possible to dual mine on same pool For example: etc/etc

YOu can do it, but you have to decide which GPU do ETH and which other do ETC, you cannot do with both gpus ETH and ETC.

**Comment by ekinmanyak123** [comment]
Oh I see thx

> > Is it possible to dual mine on same pool For example: etc/etc
> 
> YOu can do it, but you have to decide which GPU do ETH and which other do ETC, you cannot do with both gpus ETH and ETC.



> > Is it possible to dual mine on same pool For example: etc/etc
> 
> YOu can do it, but you have to decide which GPU do ETH and which other do ETC, you cannot do with both gpus ETH and ETC.

**Comment by ekinmanyak123** [comment]
Oh I see thx

> > Is it possible to dual mine on same pool For example: etc/etc
> 
> YOu can do it, but you have to decide which GPU do ETH and which other do ETC, you cannot do with both gpus ETH and ETC.



> > Is it possible to dual mine on same pool For example: etc/etc
> 
> YOu can do it, but you have to decide which GPU do ETH and which other do ETC, you cannot do with both gpus ETH and ETC.
