### ISSUE TITLE
i use the lolminer for daulmining eth and ton,but false! Am i setting wrong?

### ISSUE THREAD

**Issue by alixeking** [Lolliedieb/lolMiner-releases#1534]
i use the ssl for mining! can somebody  check the setting for me?
@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set 
"POOL=111.44.112.49:1XXX3  "
set "WALLET=0x939C860B846843FB6f8e5E094786028567543276 .lolMinerWorker"

set 
"TONPOOL=ssl.abcdefg.cn:4103"
set "TONWALLET=0x939C860B846843FB6abcdefg786029746DAd876"
							

set "EXTRAPARAMETERS="

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit
timeout 10
goto W10
goto END

:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit --nocolor
timeout 10
goto OtherW

:END
pause

**Comment by alixeking** [comment]
![LOLMINER4](https://user-images.githubusercontent.com/101870529/163442139-8506ac96-c20b-4e53-b7cc-36ed20681e54.jpg)
![lolminer3](https://user-images.githubusercontent.com/101870529/163442154-57b0c01b-a912-47da-8ee4-07fe0642a880.jpg)
![lolminer2](https://user-images.githubusercontent.com/101870529/163442163-7f6f4cc6-b24f-44df-a2a3-4b75cdd6cca7.jpg)

**Comment by alixeking** [comment]
WHY THE HASPRATE IS 0?WHEN I ONLY MINE THE ETH IS OK WHEN I ONLY MINE THE TON THE HASPRATE IS 0 TOO

**Comment by jgonzis** [comment]
The problem is that you haven't put a proper TON Wallet, you put the same ETH Wallet in TON that will never work. That is why it says Not autorized Worker :-) could you try with a TON Wallet. 

Also how did you get that Pool of TON? it is the 1st time I saw it

**Comment by alixeking** [comment]
iI put&nbsp; the&nbsp; wallet&nbsp; that&nbsp; generat&nbsp; in&nbsp; ton web. iIam in China ,so&nbsp; I must&nbsp; buy&nbsp; a&nbsp; server on aboard,and&nbsp; make&nbsp; a&nbsp; translate for&nbsp; the&nbsp; rig!




@echo off


setlocal enableDelayedExpansion


Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################


set "POOL=stratum+ssl://ssl.abcd.cn:16688"
set "WALLET=0x939C860B846843FB6f8e5E094786029746DAd876.lolMinerWorker"


set "TONPOOL=stratum+ssl://ssl.abcd.cn:4103"
set "TONWALLET=EQDD6CzlEiIPKgF1vGcK1MAgoPGpuzLT0E513Q8Uvo9hOZiV"
							
set "EXTRAPARAMETERS="


Rem #################################
Rem ##&nbsp; End of user-editable part&nbsp; ##
Rem #################################


if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^&gt;nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END


:infolder
set MyVariable=%CD%\lolMiner.exe


:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW


:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit
timeout 10
goto W10
goto END


:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit --nocolor
timeout 10
goto OtherW


:END
pause

**Comment by alixeking** [comment]
I try to single&nbsp; mine&nbsp; the&nbsp; ton&nbsp; .but can't not work.0 hashrate!&nbsp; iI single&nbsp; mine&nbsp; the&nbsp; eth&nbsp; it is ok!I&nbsp; mine&nbsp; the&nbsp; ton&nbsp; in&nbsp; icemining

**Comment by alixeking** [comment]
iI have&nbsp; set&nbsp; the&nbsp; proper wallet&nbsp; now!but&nbsp; it&nbsp; is&nbsp; also&nbsp; 0 hashrate!use&nbsp; the&nbsp; same&nbsp; setting for&nbsp; eth&nbsp; single&nbsp; miNing&nbsp; is ok!and&nbsp; not&nbsp; work for&nbsp; ton single mining

**Comment by jgonzis** [comment]
Ton pools that I know are:

Tonwhales
Ton-pool
Icemining.ca 
Toncoinpool.io 

You have to connect to 2 pools for dual mining and 2 wallets.

You are always putting same pool

**Comment by alixeking** [comment]
iI set&nbsp; the&nbsp; different pool&nbsp; now!but&nbsp; the&nbsp; same&nbsp; it&nbsp; is&nbsp; 0hashrate




@echo off


setlocal enableDelayedExpansion


Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################


set "POOL=stratum+tcp://101.43.111.49:19002"
set "WALLET=0x939C860B846843FB6f8e5E094786029746DAd876.lolMinerWorker"


set "TONPOOL=stratum+ssl://ssl.abcd.cn:4103"
set "TONWALLET=EQDD6CzlEiIPKgF1vGcK1MAgoPGpuzLT0E513Q8Uvo9hOZiV"
							
set "EXTRAPARAMETERS="


Rem #################################
Rem ##&nbsp; End of user-editable part&nbsp; ##
Rem #################################


if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^&gt;nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END


:infolder
set MyVariable=%CD%\lolMiner.exe


:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW


:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit
timeout 10
goto W10
goto END


:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit --nocolor
timeout 10
goto OtherW


:END
pause

**Comment by alixeking** [comment]
I have&nbsp; a&nbsp; issue that&nbsp; .when&nbsp; I&nbsp; set&nbsp; the&nbsp; oc&nbsp; setting&nbsp; in&nbsp; the&nbsp; t-rex！c clock for 1000,&nbsp; m clock&nbsp; for&nbsp; 1500 in t-rex!&nbsp; if&nbsp; iI change&nbsp; to&nbsp; MSI afterburner&nbsp; what&nbsp; values&nbsp; should&nbsp; i&nbsp; set for&nbsp; the&nbsp; c clock and m clock!&nbsp; in the Afterburner&nbsp; the&nbsp; cclock&nbsp; only&nbsp; set&nbsp; 959 for the max!

**Comment by alixeking** [comment]
I have&nbsp; a&nbsp; issue that&nbsp; .when&nbsp; I&nbsp; set&nbsp; the&nbsp; oc&nbsp; setting&nbsp; in&nbsp; the&nbsp; lolMiner！c clock for 1000,&nbsp; m clock&nbsp; for&nbsp; 1500 in lolMiner!&nbsp; if&nbsp; iI change&nbsp; to&nbsp; MSI afterburner&nbsp; what&nbsp; values&nbsp; should&nbsp; i&nbsp; set for&nbsp; the&nbsp; c clock and m clock!&nbsp; in the Afterburner&nbsp; the&nbsp; cclock&nbsp; only&nbsp; set&nbsp; 959 for the max!
