### ISSUE TITLE
Lower hashrate in HiveOS with FHR GPUs

### ISSUE THREAD

**Issue by Sethtrosity** [Lolliedieb/lolMiner-releases#1536]
I'm not sure what the issue is, but I get about 10 MH/s less using lolminer than gminer.
I don't have any parameters set on either and all my overclocks are exactly the same.

What could be the issue?

![hiveLOL](https://user-images.githubusercontent.com/20674650/163550456-784f852a-a602-42fc-af1c-997485629482.jpg)

![hiveGMINER](https://user-images.githubusercontent.com/20674650/163550471-960e5438-2214-4fc3-b562-4ef183b111d7.jpg)

**Comment by Sanchous98** [comment]
> I'm not sure what the issue is, but I get about 10 MH/s less using lolminer than gminer. I don't have any parameters set on either and all my overclocks are exactly the same.
> 
> What could be the issue?
> 
> ![hiveLOL](https://user-images.githubusercontent.com/20674650/163550456-784f852a-a602-42fc-af1c-997485629482.jpg)
> 
> ![hiveGMINER](https://user-images.githubusercontent.com/20674650/163550471-960e5438-2214-4fc3-b562-4ef183b111d7.jpg)

It's ok, because of different implementation. Check the hashrate on the pool side

**Comment by jgonzis** [comment]
> I'm not sure what the issue is, but I get about 10 MH/s less using lolminer than gminer. I don't have any parameters set on either and all my overclocks are exactly the same.
> 
> What could be the issue?
> 
> ![hiveLOL](https://user-images.githubusercontent.com/20674650/163550456-784f852a-a602-42fc-af1c-997485629482.jpg)
> 
> ![hiveGMINER](https://user-images.githubusercontent.com/20674650/163550471-960e5438-2214-4fc3-b562-4ef183b111d7.jpg)

Considering the last analysis ... GMiner has an overestimation of about 1% + 1% Fee. LolMiner gives what report, and it has only 0.7% Fee

lolMiner 843,9 - 0.7% Fee = 838Mhs at the pool
GMiner -1% desviation hashrate - 1% Fee = 835,93Mhs at the pool.

It is very typisch in the miner to show more hash than the reality to make the miner pick them. You can have the last review at hashrate.no/tests with 1Million Shares.

**Comment by Sethtrosity** [comment]
I guess I somewhat understand the reporting now. It's just extremely weird to see my 3080's doing sub 100 MH when I know they can.

**Comment by jgonzis** [comment]
> > > 
> > 
> > 
> > Considering the last analysis ... GMiner has an overestimation of about 1% + 1% Fee. LolMiner gives what report, and it has only 0.7% Fee
> > lolMiner 843,9 - 0.7% Fee = 838Mhs at the pool GMiner -1% desviation hashrate - 1% Fee = 835,93Mhs at the pool.
> > It is very typisch in the miner to show more hash than the reality to make the miner pick them. You can have the last review at hashrate.no/tests with 1Million Shares.
> 
> I guess I somewhat understand the reporting now. It's just extremely weird to see my 3080's doing sub 100 MH when I know they can.

But as we comment that 100.4Mhs you see is not real: -1% over reporting plus 0.3% extra fee is lower Mhs than lolMiner. It has been one of the political decision of lolMiner don't lie the miner, never inflate hash to pick up users for this way. We know other miners do it, but it is not lolMiner philosophy.

**Comment by Sethtrosity** [comment]
> > > > 
> > > 
> > > 
> > > Considering the last analysis ... GMiner has an overestimation of about 1% + 1% Fee. LolMiner gives what report, and it has only 0.7% Fee
> > > lolMiner 843,9 - 0.7% Fee = 838Mhs at the pool GMiner -1% desviation hashrate - 1% Fee = 835,93Mhs at the pool.
> > > It is very typisch in the miner to show more hash than the reality to make the miner pick them. You can have the last review at hashrate.no/tests with 1Million Shares.
> > 
> > 
> > I guess I somewhat understand the reporting now. It's just extremely weird to see my 3080's doing sub 100 MH when I know they can.
> 
> But as we comment that 100.4Mhs you see is not real: -1% over reporting plus 0.3% extra fee is lower Mhs than lolMiner. It has been one of the political decision of lolMiner don't lie the miner, never inflate hash to pick up users for this way. We know other miners do it, but it is not lolMiner philosophy.

So according to the release notes of 1.47, lol's fee is now 1% as well. Is that correct?

'Fee on the new scheme is 1%, other solvers are unchanged.'

**Comment by jgonzis** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Considering the last analysis ... GMiner has an overestimation of about 1% + 1% Fee. LolMiner gives what report, and it has only 0.7% Fee
> > > > lolMiner 843,9 - 0.7% Fee = 838Mhs at the pool GMiner -1% desviation hashrate - 1% Fee = 835,93Mhs at the pool.
> > > > It is very typisch in the miner to show more hash than the reality to make the miner pick them. You can have the last review at hashrate.no/tests with 1Million Shares.
> > > 
> > > 
> > > I guess I somewhat understand the reporting now. It's just extremely weird to see my 3080's doing sub 100 MH when I know they can.
> > 
> > 
> > But as we comment that 100.4Mhs you see is not real: -1% over reporting plus 0.3% extra fee is lower Mhs than lolMiner. It has been one of the political decision of lolMiner don't lie the miner, never inflate hash to pick up users for this way. We know other miners do it, but it is not lolMiner philosophy.
> 
> So according to the release notes of 1.47, lol's fee is now 1% as well. Is that correct?
> 
> 'Fee on the new scheme is 1%, other solvers are unchanged.'

Only for LHR GPUs for the new unlocker +78%. All other AMD, and NVIDIA FHR is 0.7%.

There is any reason to increase the fee of something that hasn't change. Only new unlocker 78% have that increase for the work of developing.  In my opinion, that will be an abuse to the users increase the fee when there is any improvement on the Nvidia FHR or AMD.
