### ISSUE TITLE
Hashrate lowered after updating driver

### ISSUE THREAD

**Issue by msymms** [Lolliedieb/lolMiner-releases#1542]
Hi, 
My hashrate dropped from 52 Mh/s to 44 Mhs/s after upgrading to the recommended driver 512.15.  I am running a version 1.48 with a 3070 Ti.  What adjustments can I make

**Comment by jgonzis** [comment]
> Hi, My hashrate dropped from 52 Mh/s to 44 Mhs/s after upgrading to the recommended driver 512.15. I am running a version 1.48 with a 3070 Ti. What adjustments can I make

Have you lock the Core?. And PL to 100%?. 

For a 3070TI you should get around 60Mhs with a Memory OFfset of 1000 an a lock Core of 1200. You need to wait 5 minutes until full tune is done. 

If you share your miner log with the full stats we can have a look on it.
