### ISSUE TITLE
https://github.com/Lolliedieb/lolMiner-releases/labels/feature%20request ETC/ ALPH

### ISSUE THREAD

**Issue by 4bdennis** [Lolliedieb/lolMiner-releases#1543]
ETC/ALPH for dual mining please

**Comment by jgonzis** [comment]
> ETC/ALPH for dual mining please

https://github.com/Lolliedieb/lolMiner-releases/wiki/Example-to-configure-Dual-Mining-ETH-ETC-UBQHASH-ALPH

It is at the moment the best dual Miner of ALPH. You also have all the guides in the YouTube Channel for the different pools:

https://www.youtube.com/c/lolMinerSupport

**Comment by 4bdennis** [comment]
thank you
