### ISSUE TITLE
ERGO Mining

### ISSUE THREAD

**Issue by yshn12** [Lolliedieb/lolMiner-releases#1544]
Hi
I have RTX 3060 V2 cards. While mining ergo. LHR is not active. Is there a setting you can recommend?

**Comment by jgonzis** [comment]
> Hi I have RTX 3060 V2 cards. While mining ergo. LHR is not active. Is there a setting you can recommend?

Probably one of the best OC is:

Core 1050
Memory 2000
PL 0 

That normally avoid the LHR with ERGO
