### ISSUE TITLE
Issue with ETH + TON + ZIL Mining

### ISSUE THREAD

**Issue by ApexKiwi** [Lolliedieb/lolMiner-releases#1545]
Hi Lolminer Support

Following on from my question on your youtube video here;
https://www.youtube.com/watch?v=VSgGiqakAGQ&t=1s

I've tried this but when I start the flight sheet the GPU's don't start.
This is the flight sheet I'm using, using standard a standard Binance ETH wallet address for the ETH and TON Keeper wallet address for the TON.
![image](https://user-images.githubusercontent.com/103908798/163738396-afb4b274-609d-4be1-8540-325b11b3a940.png)

The lolminer config is this;
![image](https://user-images.githubusercontent.com/103908798/163738417-8333d8cc-96f1-473f-b0de-aa648dfec5e0.png)

And the full pass which you can't see there is;
zil16wf8mgwlvngp7azchhk9vvv4xg9lt4c93txk04@us2.ethermine.org:4444

When I use this flight sheet with default Lolminer config it dual mines ETH & TON really well. So I must have made a mistake somewhere in the ZIL lolminer config?

**Comment by jgonzis** [comment]
> Hi Lolminer Support
> 
> Following on from my question on your youtube video here; https://www.youtube.com/watch?v=VSgGiqakAGQ&t=1s
> 
> I've tried this but when I start the flight sheet the GPU's don't start. This is the flight sheet I'm using, using standard a standard Binance ETH wallet address for the ETH and TON Keeper wallet address for the TON. ![image](https://user-images.githubusercontent.com/103908798/163738396-afb4b274-609d-4be1-8540-325b11b3a940.png)
> 
> The lolminer config is this; ![image](https://user-images.githubusercontent.com/103908798/163738417-8333d8cc-96f1-473f-b0de-aa648dfec5e0.png)
> 
> And the full pass which you can't see there is; [zil16wf8mgwlvngp7azchhk9vvv4xg9lt4c93txk04@us2.ethermine.org](mailto:zil16wf8mgwlvngp7azchhk9vvv4xg9lt4c93txk04@us2.ethermine.org):4444
> 
> When I use this flight sheet with default Lolminer config it dual mines ETH & TON really well. So I must have made a mistake somewhere in the ZIL lolminer config?

Well I see 2 errors here:

Pool is: shardpool.io and you write sharedpool.io

The 2 mistake you have 2 times %WORKER_NAME%

**Comment by ApexKiwi** [comment]
Thanks for the feedback...... but with those two fixed the GPU's still sit idle?

Here's the updated flight sheet:
![image](https://user-images.githubusercontent.com/103908798/163880616-c48a6229-a523-4334-bb07-4fda69fa1d9f.png)

![image](https://user-images.githubusercontent.com/103908798/163880679-43a86303-ae13-420d-8039-70b118ae3de6.png)

Any further ideas sir?

**Comment by jgonzis** [comment]
> Thanks for the feedback...... but with those two fixed the GPU's still sit idle?
> 
> Here's the updated flight sheet: ![image](https://user-images.githubusercontent.com/103908798/163880616-c48a6229-a523-4334-bb07-4fda69fa1d9f.png)
> 
> ![image](https://user-images.githubusercontent.com/103908798/163880679-43a86303-ae13-420d-8039-70b118ae3de6.png)
> 
> Any further ideas sir?
Try pool:  us1-zil.shardpool.io:3333 near to your us connection 

Could you show what error gives the miner log? That will help me to see where could be the problem
