### ISSUE TITLE
after internet loss , low hash rate .(lhr pct 1.0)

### ISSUE THREAD

**Issue by yurimoe** [Lolliedieb/lolMiner-releases#1546]
Lost connection to stratum server asia-eth.2miners.com:12020 or server not reachable. 
Trying to connect in 5 second(s) 
Ethash: Average speed (10s): 48.12 Mh/s
SHA256-TON: Average speed (10s): 1188.84 Mh/s
Ton pool connection mode: Ton stratum (developed by icemining.ca) (--ton-mode 6) 
SOCKS5 connection via 192.168.0.143:2333 succeeded 
Connected to ton.sg.hashrate.to(139.99.80.128):4103  (TLS enabled)
TLS Handshake success 
Ton job with difficulty 17.18G and giver kf_NSzfDJI1A3rOM0GQm7xsoUXHTgmdhN5-OrGD8uwL2JMvQ received.
SOCKS5 connection via 192.168.0.143:2333 succeeded 
Connected to asia-eth.2miners.com(139.99.68.66):12020  (TLS enabled)
Ethash: Average speed (10s): 18.27 Mh/s
SHA256-TON: Average speed (10s): 563.01 Mh/s
Ethash: Average speed (10s): 0.64 Mh/s
SHA256-TON: Average speed (10s): 21.06 Mh/s
TLS Handshake success 
Set Ethash stratum mode: Ethereum #
Statistics (18:29:13); Uptime: 2h 24m 0s 
The api is active on port 44444
Algorithm 1: Ethash 
Connected to: asia-eth.2miners.com:12020 (196ms latency) 
Algorithm 2: SHA256-TON 
Connected to: ton.sg.hashrate.to:4103 (82ms latency) 

Name        Speed   Pool  Shares    Best    Eff.   Speed     Pool
                   Mh/s   Mh/s  A/S/Hw   Share  Mh/s/W    Mh/s     Mh/s
GPU 1 RTX 3060 Ti 26.58  43.43  43/0/0  328.0G   0.622  672.67  1224.86
Total             26.58  43.43  43/0/0  328.0G   0.622  672.67  1224.86

Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc  Fan  LHR
A/S/Hw  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Pct  Pct
GPU 1   616/0/0  12.2T  15.735   42.8  1440  8200    44    56   68  1.0            

Ethash: Average speed (10s): 0.64 Mh/s
Ethash: Average speed (10s): 0.64 Mh/s

**Comment by yurimoe** [comment]
lolminer 1.47 1.48

**Comment by jgonzis** [comment]
> Lost connection to stratum server asia-eth.2miners.com:12020 or server not reachable. Trying to connect in 5 second(s) Ethash: Average speed (10s): 48.12 Mh/s SHA256-TON: Average speed (10s): 1188.84 Mh/s Ton pool connection mode: Ton stratum (developed by icemining.ca) (--ton-mode 6) SOCKS5 connection via 192.168.0.143:2333 succeeded Connected to ton.sg.hashrate.to(139.99.80.128):4103 (TLS enabled) TLS Handshake success Ton job with difficulty 17.18G and giver kf_NSzfDJI1A3rOM0GQm7xsoUXHTgmdhN5-OrGD8uwL2JMvQ received. SOCKS5 connection via 192.168.0.143:2333 succeeded Connected to asia-eth.2miners.com(139.99.68.66):12020 (TLS enabled) Ethash: Average speed (10s): 18.27 Mh/s SHA256-TON: Average speed (10s): 563.01 Mh/s Ethash: Average speed (10s): 0.64 Mh/s SHA256-TON: Average speed (10s): 21.06 Mh/s TLS Handshake success Set Ethash stratum mode: Ethereum # Statistics (18:29:13); Uptime: 2h 24m 0s The api is active on port 44444 Algorithm 1: Ethash Connected to: asia-eth.2miners.com:12020 (196ms latency) Algorithm 2: SHA256-TON Connected to: ton.sg.hashrate.to:4103 (82ms latency)
> 
> Name Speed Pool Shares Best Eff. Speed Pool Mh/s Mh/s A/S/Hw Share Mh/s/W Mh/s Mh/s GPU 1 RTX 3060 Ti 26.58 43.43 43/0/0 328.0G 0.622 672.67 1224.86 Total 26.58 43.43 43/0/0 328.0G 0.622 672.67 1224.86
> 
> Shares Best Eff. Power CCLK MCLK Core Junc Fan LHR A/S/Hw Share Mh/s/W W MHz MHz Temp Temp Pct Pct GPU 1 616/0/0 12.2T 15.735 42.8 1440 8200 44 56 68 1.0
> 
> Ethash: Average speed (10s): 0.64 Mh/s Ethash: Average speed (10s): 0.64 Mh/s

Many thanks for the log... it seems doesn't start getting jobs
