### ISSUE TITLE
dual mining eth/ton with rtx 3090 ti, eth hashrate very low

### ISSUE THREAD

**Issue by acxel40** [Lolliedieb/lolMiner-releases#1547]
I been trying dual mining eth+ton with lolminer, using forced OC settings from lolminer in windows. I been reaching good result on TON 3.4ghs, but eth stays at 56mhs.

using same settings in solo mining eth with a different miner, I can get 128-131mhs on eth solo

**Comment by jgonzis** [comment]
> I been trying dual mining eth+ton with lolminer, using forced OC settings from lolminer in windows. I been reaching good result on TON 3.4ghs, but eth stays at 56mhs.
> 
> using same settings in solo mining eth with a different miner, I can get 128-131mhs on eth solo

Could you share your OC, that seems more you are using a PL limit and not using Lock Core.

**Comment by acxel40** [comment]
--cclk 1600 --mclk 1550 
also tried --mclk 2600 and 3000 (was not sure if it was added value or total value) all same result

**Comment by jgonzis** [comment]
> --cclk 1600 --mclk 1550 also tried --mclk 2600 and 3000 (was not sure if it was added value or total value) all same result

That is the reason thx for the information. --mclk doesn't work as you normally except. Was only launch for TON to reduce memory. So now you habe reduce with that parameter memory not increase it. You will need to restart the rig or open a cmd and run nvidia-smi -rmc to unlock that reduction

So please use MsI Afterburner,  MMPOS Windows Agent or lolNvidiaOC.exe (Wiki Section in Windows Guide) for Memory Offset.

**Comment by acxel40** [comment]
thank you sir, using lolNvidiaOC in my batch file fiext it, just need to find sweet spot now, but already 127mhs eth
 / 3.3ghs ton

**Comment by jgonzis** [comment]
> thank you sir, using lolNvidiaOC in my batch file fiext it, just need to find sweet spot now, but already 127mhs eth / 3.3ghs ton

Great news and don't forget that hashrate is real... lolMiner doesn't inflate hashrate.
