### ISSUE TITLE
ETH,TON and ZIL

### ISSUE THREAD

**Issue by wasarinta** [Lolliedieb/lolMiner-releases#1548]
at the beginning zil..
![image](https://user-images.githubusercontent.com/81989126/163845806-7677c898-99b8-43e9-a71e-99a1480b44d0.png)

at the end zil... 
![image](https://user-images.githubusercontent.com/81989126/163845957-a85b6ddb-8f1a-4330-aaba-224617e41384.png)

a couple minutes later..
![image](https://user-images.githubusercontent.com/81989126/163846491-e7b8f4ad-6406-4bdd-b1b8-9ffdb0aa4d04.png)

flight sheet w/ or w/o --ethstratum ETHPROXY same results...
![image](https://user-images.githubusercontent.com/81989126/163846771-8e31ff2c-e294-4188-9d86-89c71686f1a9.png)

never happen before just today...

**Comment by jgonzis** [comment]
It seems new epoch is getting New parts of the memory that doesn't habe that "silicon lottery" to go to that speed. I recommend you to reduce the memory a pair of step on that gpu 2 and 3, to be sure dag repair doesn't happen in the zil swaps. For example 100 or 200 points.

**Comment by wasarinta** [comment]
> It seems new epoch is getting New parts of the memory that doesn't habe that "silicon lottery" to go to that speed. I recommend you to reduce the memory a pair of step on that gpu 2 and 3, to be sure dag repair doesn't happen in the zil swaps. For example 100 or 200 points.

been reducing memory from +2600 to +1900 GPU 2 and +2600 to +1700 GPU 3 until both dag repair doesn't happen at all but same results.

![image](https://user-images.githubusercontent.com/81989126/163944126-8eae36e5-5ca1-4387-9ef3-f486b2139407.png)

**Comment by jgonzis** [comment]
Try removing all lhtrune maxdualimpact ... lhrwait I don't know I suppose you have oc delay...

Let's see if comes from maxdualimpact that problem

**Comment by wasarinta** [comment]
> Try removing all lhtrune maxdualimpact ... lhrwait I don't know I suppose you have oc delay...
> 
> Let's see if comes from maxdualimpact that problem

i don have oc delay... but okay i'll try removing lhrtune, maximpact, lhrwait.. and starting w/ core 1350 and mem +1500.. i'll report back.

**Comment by wasarinta** [comment]
> 
> 
> Let's see if comes from maxdualimpact that problem


yes it comes from maxdualimpact... now it works fine... thanks dev.

**Comment by jgonzis** [comment]
> > Let's see if comes from maxdualimpact that problem
> 
> yes it comes from maxdualimpact... now it works fine... thanks dev.
> 
> mem +2600 GPU 2 & 3 --hstats 200 --enablezilcache --lhrwait 40
> 
> at the beginning zil.. ![image](https://user-images.githubusercontent.com/81989126/164067317-d416cb11-5689-4ccc-949b-811cd1efe033.png)
> 
> at the end of zil GPU 2, 3 & 4 not re-build any dag again... ![image](https://user-images.githubusercontent.com/81989126/164067677-e94bc819-b0b2-4614-90e2-7d61799c6b41.png)

Thx for the feedback
