### ISSUE TITLE
Toncoin does not support gost encrypted tunnel forwarding

### ISSUE THREAD

**Issue by yuhailove11** [Lolliedieb/lolMiner-releases#1549]
For the same gost encryption tunnel forwarding configuration, when I use gminer, the CMD window displays the computing power, but the computing power of lolminer is always 0 。Here is my configuration。
stratum+tcp://43.129.*.*:10087
The encrypted tunnel corresponds to：stratum+tcp://tcp.whalestonpool.com:4001
cmd window diskplay：
Ton pool connection mode:(--ton-mode 0)
Connected to 43.129.*.*(43.129.*.*):10087 (TLS disab1ed)
Average speed (15s): 0.00 Mh/ s

**Comment by jgonzis** [comment]
> For the same gost encryption tunnel forwarding configuration, when I use gminer, the CMD window displays the computing power, but the computing power of lolminer is always 0 。Here is my configuration。 stratum+tcp://43.129._._:10087 The encrypted tunnel corresponds to：stratum+tcp://tcp.whalestonpool.com:4001 cmd window diskplay： Ton pool connection mode:(--ton-mode 0) Connected to 43.129.206.237(43.129._._):10087 (TLS disab1ed) Average speed (15s): 0.00 Mh/ s

Are you trying to using a --socks5 proxy that will help you on that?.  try to add also before that --ton-mode 6

**Comment by yuhailove11** [comment]
Thanks ，I have sloved this problem according to your suggestion！

**Comment by jgonzis** [comment]
> Thanks ，I have sloved this problem according to your suggestion！

Many thanks for the feedback. Enjoy mining
