### ISSUE TITLE
zumbi mode insufficient memory using a gtx 970

### ISSUE THREAD

**Issue by almoutinho** [Lolliedieb/lolMiner-releases#155]
Hello all, I have download the zumbi feature version 1.19 in order to mine using a gtx 970 4GB GPU.

I have got an "insufficient memory" error message. Does anyone know if the zumbi function is still working?

Command line here:
set "POOL=naw-eth.hiveon.net:4444"
set "WALLET=0x654066bbE8a170F7c16f150Cd71420f76C2B5a3a.lolMinerWorker_gtx970"lolMiner.exe --devices 1 --algo ETHASH --pool !POOL! --user !WALLET! --4g-alloc-size 4024 --keepfree 8

Here is the console output:

+---------------------------------------------------------+
| _ _ __ __ _ _ _ ___ |
| | | ___ | | / () __ ___ _ __ / | / |/ _ \ |
| | |/ _ | | |/| | | '_ \ / _ \ '| | | | | () | |
| | | () | | | | | | | | | / | | || |_, | |
| |_|_/||| |||| ||_|| |()| /_/ |
| |
| This software is for mining |
| Ethash, Etchash |
| Equihash 144/5, 192/7, 210/9 |
| BeamHash I, II, III |
| ZelHash (EquihashR 125/4/0) |
| Cuck(ar)oo 29 |
| Cuckaroo 30 CTX |
| Cuckatoo 31/32 |
| |
| |
| Made by Lolliedieb, January 2021 |
+---------------------------------------------------------+

Setup Miner...
Device 0:
Name: GeForce RTX 3060 Ti
Address: 1:0
Vendor: NVIDIA Corporation
Memory: 8192 MByte
Active: false (not selected)
Device 1:
Name: GeForce GTX 970
Address: 2:0
Vendor: NVIDIA Corporation
Memory: 4096 MByte
--4g-alloc-size 4024
Max epoch (approx): 375
Active: true (Selected Algorithm: ETHash)

Connecting to pool...
Connected to naw-eth.hiveon.net:4444 (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x654066bbE8a170F7c16f150Cd71420f76C2B5a3a.lolMinerWorker_gtx970
New job received: 0x297e57 Epoch: 388 Target: 00000000dbe6fece
     Generating light cache for epoch 388
Start Mining...
 Done (2080 ms), size of new DAG: 4128 MByte
GPU 1: insufficient memory for DAG epoch 388.
GPU 1: will be paused.
New job received: 0x7adbc1 Epoch: 388 Target: 00000000dbe6fece

Thank you!

**Comment by jgonzis** [comment]
Could you try to change : --4g-alloc-size 4024 --keepfree 8 for --4g-alloc-size 4072, 

Also why you only select --devices 1? you can mine with both... but I think that zombie mode in Nvidia is not working perfectly...

**Comment by Bremboo** [comment]
I have the same issue with the same graphics card. I'm running the _mine_eth_4G.bat_ file.

I tried using default _--4g-alloc-size 4024 --keepfree 8_ , I also tried using _--4g-alloc-size 4024_ and _--4g-alloc-size 4072_ but received the same results: 
![image](https://user-images.githubusercontent.com/42119096/106378072-4d747500-63aa-11eb-9ac8-9ddbff29fe90.png)

Any ideas?

**Comment by jgonzis** [comment]
That's normal, you cannot mine more ETH with 4Gb cards in Windows... you can still in Linux but a lower speed.

**Comment by juleklO** [comment]
> That's normal, you cannot mine more ETH with 4Gb cards in Windows... you can still in Linux but a lower speed.

lolMiner's "Zombie Mode" was specifically created for mining (or attemptining it) with 4G cards on windows and linux, I guess that's why he's even here, I've tried many things to get my old 970s to run, no luck so far, the readme states that changing drivers might help, also chaning the --keepfree and --4g-alloc-size in the bat might help. Read through the "$G_Windows_Readme.txt", and good luck

**Comment by kapi2454** [comment]
May be the problem is that GTX970 has 3.5Gb, not 4gb.
https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/191814/gtx-970-35gb-vram-issue/

**Comment by jgonzis** [comment]
Windows can not mine more ETH with 4Gb Cards... the card is correct, but the Windows driver use some space of that 4Gb, for this reason only 3.5Gb left

**Comment by kapi2454** [comment]
it only happend in NVidia?
I see this on AMD teamredminer, it's suppose to mine with 4Gb

```
:: These environment variables should be set to for the driver to allow max mem allocation from the gpu(s).
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100
set GPU_MAX_HEAP_SIZE=100
set GPU_USE_SYNC_OBJECTS=1

:: Example batch file for starting teamredminer.  Please fill in all <fields> with the correct values for you.
:: Format for running miner:
::      teamredminer.exe -a <algo> -o stratum+tcp://<pool address>:<pool port> -u <pool username/wallet> -p <pool password>
::
:: Fields:
::      algo - the name of the algorithm to run. E.g. lyra2z, phi2, or cnv8
::      pool address - the host name of the pool stratum or it's IP address. E.g. lux.pickaxe.pro
::      pool port - the port of the pool's stratum to connect to.  E.g. 8332
::      pool username/wallet - For most pools, this is the wallet address you want to mine to.  Some pools require a username
::      pool password - For most pools this can be empty.  For pools using usernames, you may need to provide a password as configured on the pool.

:: Example steps:
:: 1. If you prefer a different pool, change the pool server address.
::
:: 2. Replace the example wallet with your own wallet(!).
::
:: 3. Name your worker by changing "trmtest" to your name of choice after the wallet below.
::
:: 4. You're good to go!

teamredminer.exe -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u 0x02197021fefa795fec661a45f60e47a6f6605281.trmtest -p x --restart_gpus --uac --eth_4g_max_alloc=374 --eth_epoch=374


```

**Comment by jgonzis** [comment]
As  we said before... it is not possible to mine ETH in Windows with 4Gb cards... it doesn't depend on the miner... it is not enough free space in the memory to do it ... it doesn't affect the miner

**Comment by jgonzis** [comment]
Same as https://github.com/Lolliedieb/lolMiner-releases/issues/170
