### ISSUE TITLE
can't OC, lolminer always running under default memory clock

### ISSUE THREAD

**Issue by trimbilrepo** [Lolliedieb/lolMiner-releases#1550]
just realize that lolminer 1.48 running under default memory clock.
tried to oc the card with memory offset 1300 via afterburner, nvidia inspector and lolNvidiaOC but the results still the same.
lolminer always runing on 5001 MHz even the default card has 7001 MHz

<img width="405" alt="image" src="https://user-images.githubusercontent.com/1433412/164004315-71fee641-7bb9-4f9d-8cc6-3cbc81f88fad.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1433412/164005174-eee656ae-bdd7-49b8-a865-c5b5840d6b53.png">

**Comment by jgonzis** [comment]
> just realize that lolminer 1.48 running under default memory clock. tried to oc the card with memory offset 1300 via afterburner, nvidia inspector and lolNvidiaOC but the results still the same. lolminer always runing on 5001 MHz even the default card has 7001 MHz
> 
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/1433412/164004315-71fee641-7bb9-4f9d-8cc6-3cbc81f88fad.png">
> 
> <img alt="image" width="802" src="https://user-images.githubusercontent.com/1433412/164005174-eee656ae-bdd7-49b8-a865-c5b5840d6b53.png">

The problem is you add parameter --mclk in the config lane. Reboot rig and remove the parameter --mclk from the bat file please. Just use MSI Afterburner for that :-)
