### ISSUE TITLE
new amd driver hiveos

### ISSUE THREAD

**Issue by damachine** [Lolliedieb/lolMiner-releases#1551]
hello. 
the new hiveos image with the new AMD driver v5.13.0201 AMD OpenCL v21.50.2
 breaks my vega 64 card. card did not detect by lolminer. under teamredminer all works. thanks all

**Comment by jgonzis** [comment]
> hello. the new hiveos image with the new AMD driver v5.13.0201 AMD OpenCL v21.50.2 breaks my vega 64 card. card did not detect by lolminer. under teamredminer all works. thanks all

Many thanks for the feedback. We will work on that fast.

**Comment by jgonzis** [comment]
> hello. the new hiveos image with the new AMD driver v5.13.0201 AMD OpenCL v21.50.2 breaks my vega 64 card. card did not detect by lolminer. under teamredminer all works. thanks all

We just had some talk with hive engineer and some of our tests seem to confirm it: as long as only one card type is in the rig the new image seems ok, but mixing different generations of cards ... well then the trouble starts

**Comment by jgonzis** [comment]
> hello. the new hiveos image with the new AMD driver v5.13.0201 AMD OpenCL v21.50.2 breaks my vega 64 card. card did not detect by lolminer. under teamredminer all works. thanks all

It seems also HiveOS has deleted for the problem of that version.

**Comment by damachine** [comment]
hello. the problem with my mix rig the vega hash is by 40mh under new hiveos image amd driver is now 21.40.1 (5.13.0201) all works under trm. thanks all greets

**Comment by jgonzis** [comment]
> hello. the problem with my mix rig the vega hash is by 40mh under new hiveos image amd driver is now 21.40.1 (5.13.0201) all works under trm. thanks all grComment 
Could it be that doesn't apply the OC properly?, no that not because TRM works great. Well TRM has an amazing performance with Vega, so it could be that the difference you comme
