### ISSUE TITLE
ton+eth mining hashrates

### ISSUE THREAD

**Issue by Sadrakhani** [Lolliedieb/lolMiner-releases#1552]
hi i have 3080ti gamerock my hashrates are 77 and 3100 mh/s in ton and eth dual mining
after shutting down my pc my hashrates lower to 74.8 and 3.03 mh/s
why is this happend? my windows is 10

**Comment by jgonzis** [comment]
> hi i have 3080ti gamerock my hashrates are 77 and 3100 mh/s in ton and eth dual mining after shutting down my pc my hashrates lower to 74.8 and 3.03 mh/s why is this happend? my windows is 10

Try to check that PL is to 100%. That you are using Lock Core and that Memory TEMP is not high.

**Comment by Sadrakhani** [comment]
> > hi i have 3080ti gamerock my hashrates are 77 and 3100 mh/s in ton and eth dual mining after shutting down my pc my hashrates lower to 74.8 and 3.03 mh/s why is this happend? my windows is 10
> 
> Try to check that PL is to 100%. That you are using Lock Core and that Memory TEMP is not high.

I didnt lock core and overclock core and memory 
Just increase pl to 108 and my card power usage is about 338 and hashrates are 77 and 3100
But now after doing same thing power usage is 330 
Do you have idea to increse power usage

**Comment by jgonzis** [comment]
> > > hi i have 3080ti gamerock my hashrates are 77 and 3100 mh/s in ton and eth dual mining after shutting down my pc my hashrates lower to 74.8 and 3.03 mh/s why is this happend? my windows is 10
> > 
> > 
> > Try to check that PL is to 100%. That you are using Lock Core and that Memory TEMP is not high.
> 
> I didnt lock core and overclock core and memory Just increase pl to 108 and my card power usage is about 338 and hashrates are 77 and 3100 But now after doing same thing power usage is 330 Do you have idea to increse power usage

I really recommend to lock the core... that is the  best for tunning Dual

**Comment by mmll1** [comment]
I have bigger problem
It is impossible to unlock 3080Ti with dual mining ETH+TON
Sometimes lolminer says that is 3080TI FHR, hhahaha
strange, I tried with lhrtune, maxdualimpact, the same problem,
in most cases unlock is about 83-84% which is 55 MH and 1 GB ton
If I eliminate TON mining that is about 92 MH/s
something is really wrong with lolminer for 3080TI dual mining  ETH+TON
lock core: 1400, mem:2600; HIVEOS
don't have heat issues, everything is bellow 75 deg

**Comment by mmll1** [comment]
What to say I have the same issue, in new gminer I've got 88 Mh/s and 2.6 GH/s TON in Lolminer never over 86 Mh/s 1.7 GH/s. Admin says that is something wrong with my 3080Ti but whay in gminer works fine in lolminer are not. That means that is nothing wrong with my 3080Ti, something is worng with lolminer and unlocker. Lolminer has big issues with 3080Ti and unlocking, sometime says that 3080Ti is a FHR GPU, then unlocking till 84% and unlocking all the time and so on. Gminer unlock immediately with no prolems, with lolminer I have big problems. I'm very dissapointing on admin, who accuses GPU, not a lolminer, who is unable to unlock 3080Ti. It's a shame that admin close my open issue with so stupid explanations.

**Comment by jgonzis** [comment]
> What to say I have the same issue, in new gminer I've got 88 Mh/s and 2.6 GH/s TON in Lolminer never over 86 Mh/s 1.7 GH/s. Admin says that is something wrong with my 3080Ti but why in gminer works fine in lolminer is not. That means that is nothing wrong with my 3080Ti, something is worng with lolminer and unlocker. Lolminer has big issues with 3080Ti and unlocking, sometime says that 3080Ti is a FHR GPU, then unlocking till 84% and unlocking all the time and so on. Gminer unlock immediately with no prolems, with lolminer I have big problems. I'm very dissapointing on admin, who accuses GPU, not a lolminer, who is unable to unlock 3080Ti. It's a shame that admin close my open issue with so stupid explanations.

As I comment to you: . GMiner inflates hashrate, Fee 1.5% and doesn't have unlock +78%. If you want to use the new  unlocker of lolMiner +78% reduce the memory until not FHR, if you still don't want to do it. Use old unlocker from 1.46a same as lolminer 74%. It will not be there a problem the unproper memory you are putting for your bad silicon GPU.
