### ISSUE TITLE
i mine ton in icemining pool! but when i mine in 5minutes and 5 second ,the pool disconect for 5 seconds and retry to connects!

### ISSUE THREAD

**Issue by alixeking** [Lolliedieb/lolMiner-releases#1553]
very 5min and 5 seconds it will lost the connections  and retry to connect! why?  i  use asus ac86u for acrossing the GFW on asuswrt! what  is the problem,the miner or the pool?how to fix it ?
![image](https://user-images.githubusercontent.com/101870529/164456800-61558bb2-688a-416b-a8e0-fa4b501980aa.png)
![image](https://user-images.githubusercontent.com/101870529/164459883-ab1e1e81-64f5-4da4-a1dc-961a3390a8e3.png)

**Comment by alixeking** [comment]
i use the pool ton.hk.hashrate.to:4102

**Comment by jgonzis** [comment]
> very 5min and 5 seconds it will lost the connections and retry to connect! why? i use asus ac86u for acrossing the GFW on asuswrt! what is the problem,the miner or the pool?how to fix it ? ![image](https://user-images.githubusercontent.com/101870529/164456800-61558bb2-688a-416b-a8e0-fa4b501980aa.png) ![image](https://user-images.githubusercontent.com/101870529/164459883-ab1e1e81-64f5-4da4-a1dc-961a3390a8e3.png)

We know that there are some issues with that ton pool... have you tried the other ones of the other TON pool?
