### ISSUE TITLE
Impossible to unlock 3080Ti with dual mining ETH+TON

### ISSUE THREAD

**Issue by mmll1** [Lolliedieb/lolMiner-releases#1555]
It is impossible to unlock 3080Ti with dual mining ETH+TON
Sometimes lolminer says that is 3080TI FHR, hhahaha,
strange, I tried with lhrtune, maxdualimpact, the same problem,
in most cases unlock is about 83-84% which is 55 MH and 1 GB ton and for my oppinion too high.
If I eliminate TON mining that is about 92 MH/s
Something is really wrong with lolminer for 3080TI dual mining ETH+TON
lock core: 1400, mem:2600; HIVEOS
I don't have heat issues, everything is bellow 75 deg

**Comment by Sadrakhani** [comment]
Lock core in 1590 fix voltage 825mv and 1500 fix voltage 800
Don t change anything

**Comment by mmll1** [comment]
> Lock core in 1590 fix voltage 825mv and 1500 fix voltage 800 Don t change anything

Can't fix voltage in HIVEOS

**Comment by jgonzis** [comment]
> > Lock core in 1590 fix voltage 825mv and 1500 fix voltage 800 Don t change anything
> 
> Can't fix voltage in HIVEOS

As comment yesterday in the telegram group. Your memory hasn't got very good memory OC and your Bios PL limitation. Try to reduce mem and core until that limit is not reached
