### ISSUE TITLE
Hashrate difference in TON mining ETH+TON

### ISSUE THREAD

**Issue by mauricioalejandrodiaz** [Lolliedieb/lolMiner-releases#1556]
I have 4 rtx a5000 that work smoothly and stable when mining ETH. But when trying to mine ETH+TON the hashrates in TON are randomly very disparate. It is not that one mine always punctually more than the other, but that randomly 2 mine a lot and 2 mine little. I restart the miner and the same 2 mine a lot and 2 a little, and it's never the same GPU that mines little or a lot, it's completely random. Which may be? Has anyone else tried dual mining with the RTX A5000 and the same thing happens?

**Comment by jgonzis** [comment]
> I have 4 rtx a5000 that work smoothly and stable when mining ETH. But when trying to mine ETH+TON the hashrates in TON are randomly very disparate. It is not that one mine always punctually more than the other, but that randomly 2 mine a lot and 2 mine little. I restart the miner and the same 2 mine a lot and 2 a little, and it's never the same GPU that mines little or a lot, it's completely random. Which may be? Has anyone else tried dual mining with the RTX A5000 and the same thing happens?

That normally happens when is used PL and not Lock Core. It is complicated to tune properly without a lock core
