### ISSUE TITLE
Rtx a2000 Dual mining eth+ton

### ISSUE THREAD

**Issue by ltwarrior18** [Lolliedieb/lolMiner-releases#1558]
Is it possible to get an option to dual mine with rtx a2000? Like all other rtx cards? Thanks guys for hard work.

**Comment by jgonzis** [comment]
> Is it possible to get an option to dual mine with rtx a2000? Like all other rtx cards? Thanks guys for hard work.

IT is possible, but problem is no More PowerLimit left on the GPU to do it... so it is not recommended. The profit in really really low for that GPU. with PL 70
