### ISSUE TITLE
How to set Toncoin forward server by using Nginx

### ISSUE THREAD

**Issue by kindman4** [Lolliedieb/lolMiner-releases#1559]
This is how I set in nginx.conf of forward server :
==============
http
{
server {
            resolver 8.8.8.8;
            listen 14719;   
            location / {
            proxy_no_cache 1;
            proxy_cache_bypass 1;
            proxy_redirect off;
            expires -1;
            proxy_cache off;

            proxy_pass https://server1.whalestonpool.com;
            proxy_ssl_server_name on;
     
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
                           }
         }
}
==============
I could visit forward server IP:port,like: xxx.xxx.xxx.xxx:14719 in my browse.
It shows: 
Pool is working. Have a nice day :)

In eth_ton.bat,set like this:
set "tonpool=xxx.xxx.xxx.xxx:14719"

But lolminer shows:
Connected to xxx.xxx.xxx.xxx:14719 (Tls disenable)
==============
So how to set Toncoin forward server by using Nginx,thanks!

**Comment by jgonzis** [comment]
why you don't use a proxy server and use the function --socks5 ?

**Comment by kindman4** [comment]
> why you don't use a proxy server and use the function --socks5 ?

Sorry, I just dont know how to setup socks5,but I have success by using Nginx both Eth & Ton,
I have missing 2 steps:
server: openssl add  xx.key & xxx.crt
bat:use --ton-mode 6

**Comment by jgonzis** [comment]
> > why you don't use a proxy server and use the function --socks5 ?
> 
> Sorry, I just dont know how to setup socks5,but I have success by using Nginx both Eth & Ton, I have missing 2 steps: server: openssl add xx.key & xxx.crt bat:use --ton-mode 6

Great !!
