### ISSUE TITLE
Dual mining (AMD GPU) restart problem

### ISSUE THREAD

**Issue by bullvodka** [Lolliedieb/lolMiner-releases#1560]
hi.

I'm doing dual mining. I have 2 rigs.
1. rig = 6x6700XT + 2x6900XT (no problem the rig is working)
2. rig = 6x6900XT (It restarts after 1 minute)

**Comment by jgonzis** [comment]
> hi.
> 
> I'm doing dual mining. I have 2 rigs.
> 
> 1. rig = 6x6700XT + 2x6900XT (no problem the rig is working)
> 2. rig = 6x6900XT (It restarts after 1 minute)

That seems to be a PSU problem, a fail of energy.  Is it possible to see OC or if there are errors?

**Comment by bullvodka** [comment]
It can't be the PSU. because there is no problem when you just mine etherum.

**Comment by jgonzis** [comment]
> It can't be the PSU. because there is no problem when you just mine etherum.

Well, but only mining ETH is not the same Watts consume that making dual mining. The Consumes goes really up with Dual... why couldn't then be the PSU?.

**Comment by bullvodka** [comment]
hmm i didn't know that :( 
i have 6  x 6900 XT and 2000W PSU

only when i mine eth it use 1600-1700W

**Comment by jgonzis** [comment]
> hmm i didn't know that :( i have 6 x 6900 XT and 2000W PSU
> 
> only when i mine eth it use 1600-1700W

Then that is the reason it could be easy 50W x GPU or more to TON x 6 is over limit

**Comment by bullvodka** [comment]
:(

Thank you very much for the information. so is there a TON psu limitation for dualmine in lolminer?

**Comment by jgonzis** [comment]
> :(
> 
> Thank you very much for the information. so is there a TON psu limitation for dualmine in lolminer?

You  can use --maxdualimpact 0.1 to reduce the load of the dual
