### ISSUE TITLE
How can i verify the checksum of my download?

### ISSUE THREAD

**Issue by SR7673** [Lolliedieb/lolMiner-releases#1562]
Hi,
How can i verify my download using a sha256 checksum? I do not find any checksum information for that project.
I just downloaded lolMiner_v1.48_Lin64.tar.gz
Now when running sha256sum lolMiner_v1.48_Lin64.tar.gz i'm getting something like
8ee7c55b1a57a0f80417cb67f530dc3f0f749bdaad43aefb9ffe9d73c19e2f02
but i can't find any reference checksum here to verify that my download is actually the expected file...
Regards.

**Comment by jgonzis** [comment]
> Hi, How can i verify my download using a sha256 checksum? I do not find any checksum information for that project. I just downloaded lolMiner_v1.48_Lin64.tar.gz Now when running sha256sum lolMiner_v1.48_Lin64.tar.gz i'm getting something like 8ee7c55b1a57a0f80417cb67f530dc3f0f749bdaad43aefb9ffe9d73c19e2f02 but i can't find any reference checksum here to verify that my download is actually the expected file... Regards.

You are right we don't have it and it should have the md5 information. I will try to add it.
