### ISSUE TITLE
new hiveos amd driver

### ISSUE THREAD

**Issue by damachine** [Lolliedieb/lolMiner-releases#1564]
hello. the problem with my mix rig the vega hash is by 40mh under new hiveos image amd driver is now 21.40.1 (5.13.0201) all works under trm. thanks all greets.
#1551

**Comment by jgonzis** [comment]
> hello. the problem with my mix rig the vega hash is by 40mh under new hiveos image amd driver is now 21.40.1 (5.13.0201) all works under trm. thanks all greets. #1551

Which Mhs do you have before with lolMiner? TRM has an improvement in Vega compared to lol

**Comment by damachine** [comment]
vega 64 before update had 50mh now 40mh with lolminer
