### ISSUE TITLE
100% LHR unlock can be done

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1568]
https://www.nicehash.com/blog/post/100-lhr-unlock-at-nicehash-its-here

**Comment by dawidmosk** [comment]
nice but 100% really true? or something like hidden fees etc. ;) When lolMiner will get something similar? :D

**Comment by mmhorda** [comment]
nobody knows how they are doing it yet. 
It could be Dual mining behind the scene with the same profitability as 100% ETH and just showing you nice numbers ;)
It would be good if I am wrong.

**Comment by dawidmosk** [comment]
i thinking too, something wrong is with - maybe "artificial crowd". I have own webGUI with system scripts connected to great and clean lolMiner - so it's better to stay here even with small profitability differences. I don't trust where someone is between pool and pc - they can show you everything - it's RC version (so explanation is ready) ;) 

HWInfo is started after mining or before? Hangs, freeze or Killed? Maybe something other.

**Comment by mmhorda** [comment]
HWInfo 64 bit just closes by itself after hitting button RUN. People report that 32bit version HWInfo works just fine. (but I am too lazy to check already)
Maybe dudes have like real LHR unlock? Bugging sensors or something and it triggers real LHR unlock? :) nicehash admits that they cannot do anything right now in order to fix the behavior with monitoring tools.

**Comment by dawidmosk** [comment]
Ooo, so they killing application - probably they looking for filename or file signature - just change this will help - i think. Maybe the have - soon  will be leaked truth - like everything.

**Comment by igralec84** [comment]
Now also possible with NBminer, 3080ti doing 126mh/s :) For NH it didn't work if i didn't disable the FHR card i have.

**Comment by dawidmosk** [comment]
oo, so like i set - soon everything we will know... the last will be eth price :D

**Comment by mmhorda** [comment]
I have already tried and switched all to NBMiner. 
funny thing 3080Tis mining better than 3090 (30 watts more efficient)

**Comment by dawidmosk** [comment]
Run nbminer with **admin priviledge** to get 100% LHR unlock

**Comment by bds89** [comment]
3060ti 60+ Mh/s in NBMiner 130Wt

**Comment by ltwarrior18** [comment]
lolminer this time is behind, but soon it will catch up.

**Comment by dawidmosk** [comment]
they have to be quick - we need lol with dual :-)

**Comment by donegogov** [comment]
Yeah lol dual 3080 lhr lock eth + ton = nbminer 100% unlock eth

**Comment by dawidmosk** [comment]
you're optimist, for me: lol eth+alph > nbminer 100% :)

**Comment by dawidmosk** [comment]
On 41.3 problem with GPU has back - crashing random GPUs. On version 41.1 was stable. Anyone have this same problem?

**Comment by igralec84** [comment]
> Also 3050 and 3080 12gb have lhr v3, so they are not unlocked, only v2 lhr cards are... Also crypto is plummeting and GPU prices too...

Now also 3080 12G and 3050 are 90% unlocked with NBminer...

**Comment by AlexStud** [comment]
How's going? Did you know how already? 
Waiting for yours miner, guys, good luck!

**Comment by dawidmosk** [comment]
Nice, now everything working great - even price on eth - no changes lhr -> no-lhr - just higher hash rate, higher mem. temperature, this same price :D
