### ISSUE TITLE
3060 Ti LHR not mine with lolminer 1.49

### ISSUE THREAD

**Issue by el-quique** [Lolliedieb/lolMiner-releases#1569]
Hello. I am using Nvidia driver 510.60.02 or 470.86 in HiveOS and with lolminer 1.49 I get the image error. Any driver that you recommend. Thank you very much

PS: in lolminer 1.48 it works without problems
![Captura de pantalla de 2022-05-07 18-14-59](https://user-images.githubusercontent.com/5359805/167272033-24fd00a3-95a7-4f2f-ab53-88ab71100e45.png)

**Comment by mmhorda** [comment]
same here lolminer 1.49 is bugged with Autolykos.

**Comment by zulu1905** [comment]
1.48 at 3060ti with [eth+ton] 47mh eth + 1700 mh ton with 170 watts
1.49 at 3060ti with [eth+ton] 43mh eth + 1400 mh ton with 166 watts

1.49 sucks

**Comment by Kostas-13** [comment]
Same for 3080s FHR on Dual Ton+Eth at Win10
Ton doesn't start to mine, just Eth.. 
I'm sticking to 1.48 it's rock solid xD

**Comment by el-quique** [comment]
Now working. Thx
