### ISSUE TITLE
Support both --api 127.0.0.1:3333 and --api 0.0.0.0:3333

### ISSUE THREAD

**Issue by o2genum** [Lolliedieb/lolMiner-releases#157]
Both options are needed: some want to limit miner API server to localhost (for security), and some want to expose it.
This feature would be very appreciated!

**Comment by Lolliedieb** [comment]
Good point ... will include that :)

**Comment by Lolliedieb** [comment]
Implemented with 1.21
New parameter will be --apihost which will need a valid ip address for the binding, default will be 0.0.0.0, but restriction to 127.0.0.1 will be possible.
