### ISSUE TITLE
LHR a threshold issues.

### ISSUE THREAD

**Issue by SickoCrypto** [Lolliedieb/lolMiner-releases#1571]
There is an issue on 1.49 when you’re mining dual, basically wen a GPU hits the LHR threshold, it should restart to find next best value, instead GPU change to a FHR mode with a 40% to 50% decrease of hash rate. The only way to fix is a manual reboot. Just some feedback.

**Comment by jgonzis** [comment]
> There is an issue on 1.49 when you’re mining dual, basically wen a GPU hits the LHR threshold, it should restart to find next best value, instead GPU change to a FHR mode with a 40% to 50% decrease of hash rate. The only way to fix is a manual reboot. Just some feedback.

Try new 1.50 with proper drivers
