### ISSUE TITLE
GPU Memory temperature

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1573]
Can i please you to share expiration about small part of code?
I'm trying to do very small application to control GPU temperature on 30xx GPUs.
Using c + nvlm I have only core temp...
Part code needed only ;)

**Comment by jgonzis** [comment]
> Can i please you to share expiration about small part of code? I'm trying to do very small application to control GPU temperature on 30xx GPUs. Using c + nvlm I have only core temp... Part code needed only ;)

Well, Why you don't read directly the API of lolMiner to do it meanwhile you are mining?

**Comment by dawidmosk** [comment]
API of lolMiner to read? It don't exists but changelog im reading. I don't need few information form json - web API. I'm asking about code.
