### ISSUE TITLE
1.50 beta Win 10 Nvidia driver 512.59

### ISSUE THREAD

**Issue by MinerTi** [Lolliedieb/lolMiner-releases#1575]
3060 ti unlocked only partially. Need lolminer 1.51 for working with driver 512.59.

**Comment by jgonzis** [comment]
> 3060 ti unlocked only partially. Need lolminer 1.51 for working with driver 512.59.

It has to be done ... at the moment is 512.15, sure it will be added.

**Comment by Gkozd** [comment]
[GeForce 512.77 WHQL driver](https://www.guru3d.com/files-details/geforce-512-77-whql-driver-download.html)

**Comment by AleksP** [comment]
Unlock doesn't work with 3060 12GB v1 and win driver 512.77

**Comment by jgonzis** [comment]
> Unlock doesn't work with 3060 12GB v1 and win driver 512.77

It is know, at the moment only 512.15. Until final release
