### ISSUE TITLE
ETH / CNGPU dual mining

### ISSUE THREAD

**Issue by makoshark2001** [Lolliedieb/lolMiner-releases#1578]
Is it possible to implement CNGPU mining with ETH dual mining? CnGPU is core intensive not memory intensive. Might work well with ETH/ETC/ERGO or something. Could be a boost to earnings on NON Lhr cards like ETH/Aleph.

**Comment by jgonzis** [comment]
> Is it possible to implement CNGPU mining with ETH dual mining? CnGPU is core intensive not memory intensive. Might work well with ETH/ETC/ERGO or something. Could be a boost to earnings on NON Lhr cards like ETH/Aleph.

It could be done... problem is the profit of the coin ...

**Comment by makoshark2001** [comment]
Yeah but XEQ/RYO/CCX are almost the same as ETH and in some cases more profitable. So I wasn't sure if it would benefit running at the same time as ETH on the same GPU like Alephium/TON do.
