### ISSUE TITLE
Run as Admin - 1.50 Beta

### ISSUE THREAD

**Issue by SJDavies2020** [Lolliedieb/lolMiner-releases#1579]
If you dbl click on the .bat it runs fine.  If you try to run as Admin it doesn't find the .exe in the folder.

**Comment by GYKrauss** [comment]
Set the app lolMiner.exe to run as administrator. The .bat file, just run with user privileges. You will get a prompt and give it the OK.

**Comment by jgonzis** [comment]
> If you dbl click on the .bat it runs fine. If you try to run as Admin it doesn't find the .exe in the folder.

Do the comment of the user working great like he said
