### ISSUE TITLE
Not Unlocking 3080TI Windows 1.50 Beta driver v 512.59 works on NB

### ISSUE THREAD

**Issue by Dv8ers** [Lolliedieb/lolMiner-releases#1580]
Not Unlocking 3080TI Windows Beta see log file
[2022-05-12_18-48-39.log](https://github.com/Lolliedieb/lolMiner-releases/files/8681162/2022-05-12_18-48-39.log)

**Comment by kaseidu** [comment]
Running with admin privileges?

**Comment by Dv8ers** [comment]
yes with admin

**Comment by GYKrauss** [comment]
Which Driver?

**Comment by Dv8ers** [comment]
Nvidia 512.59 switched over to NBminer again  as it couldn't unlock

**Comment by kaseidu** [comment]
1.50 beta is restricted to 512.15

**Comment by Dv8ers** [comment]
Thanks, will try that version of the driver

**Comment by jgonzis** [comment]
> Not Unlocking 3080TI Windows Beta see log file [2022-05-12_18-48-39.log](https://github.com/Lolliedieb/lolMiner-releases/files/8681162/2022-05-12_18-48-39.log)

Did you read the release Section?..

It said at the moment until final release is 512.15... you are with 512.59, it will not work. I close it, new release with the support of that drivers will be released very soon
