### ISSUE TITLE
Dual mining ETH+TON doesn't start sometimes

### ISSUE THREAD

**Issue by charnet3d** [Lolliedieb/lolMiner-releases#1583]
Sometimes dual mining doesn't start and it mines with ETH only even with multiple restarts, though this cannot be consistently reproduced.

Specifying "--maxdualimpact 0.5" can help when multiple restarts don't do the trick, on the 3070 and 3060ti I have to increase the ratio to 1 or close to it to make get similar hashrate to auto tuning.

Tested this happening on a 3060ti LHR, 3070 NON-LHR, 3080 LHR and 3080Ti. All running v1.50 beta on windows 11. Nvidia Driver 512.15.

EDIT: This used to be an issue when Dual mining was first introduced and on a few versions after that, but on the latest 1.48 and 1.49 I don't remember encountering this (or probably so rarely I forgot).

**Comment by jgonzis** [comment]
> Sometimes dual mining doesn't start and it mines with ETH only even with multiple restarts, though this cannot be consistently reproduced.
> 
> Specifying "--maxdualimpact 0.5" can help when multiple restarts don't do the trick, on the 3070 and 3060ti I have to increase the ratio to 1 or close to it to make get similar hashrate to auto tuning.
> 
> Tested this happening on a 3060ti LHR, 3070 NON-LHR, 3080 LHR and 3080Ti. All running v1.50 beta on windows 11. Nvidia Driver 512.15.
> 
> EDIT: This used to be an issue when Dual mining was first introduced and on a few versions after that, but on the latest 1.48 and 1.49 I don't remember encountering this (or probably so rarely I forgot).

It has been comment that with Windows last beta hat something with the dual... analysing for next release

**Comment by shmox75** [comment]
Same issue here with 1.50 and 1.50a, reverting back to 1.49 which hasn't this issue.

**Comment by jgonzis** [comment]
> Same issue here with 1.50 and 1.50a, reverting back to 1.49 which hasn't this issue.

0 photo? Could you please help us to find the problem?. Did you try 1.51a?  We really need information. In our test goes if you down share information we can not search for the problem

**Comment by charnet3d** [comment]
Just to update you my original issue was actually solved with 1.50 and 1.50a. --dualfactor is a lot more predictable than --maxdualimpact and I get the right hashrate everytime. Thanks ! If shmox75's issue is resolves you can close this ticket.

**Comment by jgonzis** [comment]
> Just to update you my original issue was actually solved with 1.50 and 1.50a. --dualfactor is a lot more predictable than --maxdualimpact and I get the right hashrate everytime. Thanks ! If shmox75's issue is resolves you can close this ticket.

Thx for the feedback. Let's wait that some photo comes.  Is really complicated to get information wiithout photos or logs.

**Comment by shmox75** [comment]
> > Same issue here with 1.50 and 1.50a, reverting back to 1.49 which hasn't this issue.
> 
> 0 photo? Could you please help us to find the problem?. Did you try 1.51a? We really need information. In our test goes if you down share information we can not search for the problem

Yes I meant 1.51a sorry. TON hashrate stays 0 all the time, same for 1.51.
![LOLMINER](https://user-images.githubusercontent.com/39054055/169704187-5b6552ac-1216-41ac-818a-486d14c81c79.png)

**Comment by jgonzis** [comment]
> > > Same issue here with 1.50 and 1.50a, reverting back to 1.49 which hasn't this issue.
> > 
> > 
> > 0 photo? Could you please help us to find the problem?. Did you try 1.51a? We really need information. In our test goes if you down share information we can not search for the problem
> 
> Yes I meant 1.51a sorry. TON hashrate stays 0 all the time, same for 1.51. ![LOLMINER](https://user-images.githubusercontent.com/39054055/169704187-5b6552ac-1216-41ac-818a-486d14c81c79.png)
> 
> Please note that I'm on windows 11

Is it possible that you use --dualfactor 20 to test and you share the miner log, where it shows pool info, core, mem, speed,...  I hope only --dualfactor 20 works but let check it

**Comment by shmox75** [comment]
> > > > Same issue here with 1.50 and 1.50a, reverting back to 1.49 which hasn't this issue.
> > > 
> > > 
> > > 0 photo? Could you please help us to find the problem?. Did you try 1.51a? We really need information. In our test goes if you down share information we can not search for the problem
> > 
> > 
> > Yes I meant 1.51a sorry. TON hashrate stays 0 all the time, same for 1.51. ![LOLMINER](https://user-images.githubusercontent.com/39054055/169704187-5b6552ac-1216-41ac-818a-486d14c81c79.png)
> > Please note that I'm on windows 11
> 
> Is it possible that you use --dualfactor 20 to test and you share the miner log, where it shows pool info, core, mem, speed,... I hope only --dualfactor 20 works but let check it

Yes with --dualfactor 20 it works. Unfortunately it didn't write any log. here is a screenshot "rtx 3070 NON LHR"

![LOLMINER](https://user-images.githubusercontent.com/39054055/169704512-0b8a36bf-0202-4f33-b799-3ab2ada8e514.png)

**Comment by jgonzis** [comment]
So that shows the idea of dualfactor for Windows solve the tunning proces... great

**Comment by shmox75** [comment]
> So that shows the idea of dualfactor for Windows solve the tunning proces... great

Sorry, I don't know what that mean. "I'm not an expert"

**Comment by jgonzis** [comment]
> > So that shows the idea of dualfactor for Windows solve the tunning proces... great
> 
> Sorry, I don't know what that mean. "I'm not an expert" Hope this could help

you should play with the --dualfactor you can try 25 or 27.5 until you see that the reduction of ETH is not de desidered
