### ISSUE TITLE
bad unlocker

### ISSUE THREAD

**Issue by rexmining1** [Lolliedieb/lolMiner-releases#1586]
compared to nbminer this only gets 57mh on eth instead of 60-61 on 120w

**Comment by jgonzis** [comment]
> compared to nbminer this only gets 57mh on eth instead of 60-61 on 120w

That doesn't help too much the information you give... I hope you can be more specific. And I also hope you are comparing values of the pool not the miner. 

I hope you can upload some more information... last test done doesn't show your comment

![image](https://user-images.githubusercontent.com/38668405/168596372-a6f62545-9f0c-417c-bc52-53a41ca937b8.png)
