### ISSUE TITLE
cannot find where to input dual factor number

### ISSUE THREAD

**Issue by Ham2022ed** [Lolliedieb/lolMiner-releases#1589]
Could you guys please let me know how to setup dual factor? Thanks

**Comment by jgonzis** [comment]
> Could you guys please let me know how to setup dual factor? Thanks

start with a --dualfactor 25 for example... if you want more 2nd COIN then increase that value, or less decrease it.

--dualfactor parameter:
This parameter can be used as more direct alternative to --maxdualimpact. It is build in a way such that the hashrate of the Ton / Aleph solver will be dualfactor * Eth hash rate. So for example if the factor is 25 and the Eth hash rate is 59.5 mh/s, then the dual hash rate will be 25 times 59.5 mh/s = 1487,5 mh/s. The maximum dual factor at the moment is 64, a value of 0 will disable dual mining on the GPU. Using the parameter will skip all tuning of the dual algorithm and set the ratio directly after DAG build. Note that if you turn the value too high, then the Ethash hash rate might fall, turning it lower usually decreases energy intake.

The parameter takes a comma separated list of values, where auto or a star can be used to skip over a GPU that should remain in auto tuning mode. If you use --devices for restricting to some GPUs, then also it is sufficient to define it for the selected GPUs only. Note, that the old --maxdualimpact parameter now also understands "auto" to keep it more consistent.
