### ISSUE TITLE
Nvidia Driver version lolMiner 1.51

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1590]
_"Extended working range of 100% LHR unlocker to 470 and 472 drivers. Note: please do not use the new 515.x drivers - on them the unlock currently does not work."_

So what version of drivers is more preferable? We are using 470, 472, 510.
For example RTX 30xx*?

**Comment by fegauthier** [comment]
> i think 512.15 would be fine.

What's the purpose of supporting 470 and 472 if 510+ is working?

**Comment by dawidmosk** [comment]
> > i think 512.15 would be fine.
> 
> What's the purpose of supporting 470 and 472 if 510+ is working?

Yes, I was thinking about it too, but maybe someone is using different driver versions basing on card models, operating system version, working/gaming on it... etc. It's good option to develop this cases if. Going back to my question... which version is more stable for 100% time mining?

or different question way: which driver making more problems on mining?

**Comment by Larision** [comment]
i´ve rig with 4x1660super and 1xrtx2060 and nvidia 512.15 drivers, v1.51 mining 4 times more TON than 1.50.
30-31mh/s eth and around 2000mh/s ton each gpu. no errors and 100% stable.
![image](https://user-images.githubusercontent.com/41712973/169372172-4e15a5d6-c0e3-41cb-af7c-d9755b283485.png)

**Comment by dawidmosk** [comment]
> i´ve rig with 4x1660super and 1xrtx2060 and nvidia 512.15 drivers, v1.51 mining 4 times more TON than 1.50. 30-31mh/s eth and around 2000mh/s ton each gpu. no errors and 100% stable.

Nice, thank you.

**Comment by jgonzis** [comment]
> i´ve rig with 4x1660super and 1xrtx2060 and nvidia 512.15 drivers, v1.51 mining 4 times more TON than 1.50. 30-31mh/s eth and around 2000mh/s ton each gpu. no errors and 100% stable

Try what you want... each rig is different and need different drivers
