### ISSUE TITLE
lolMiner 1.51 ETCH hashrate decreased

### ISSUE THREAD

**Issue by BitMaci** [Lolliedieb/lolMiner-releases#1591]
In lolMiner 1.51 ETCHash hashrate is lower than previous versions. I have FHR card and latest Nvidia drivers 516.01/CUDA 11.7.

**Comment by jgonzis** [comment]
> In lolMiner 1.51 ETCHash hashrate is lower than previous versions. I have FHR card and latest Nvidia drivers 516.01/CUDA 11.7.

Could you share it with some pictures... before and after that doesn't give any information.... Many thanks

**Comment by BitMaci** [comment]
I didn't talk about before and after @jgonzis , I told you that "In lolMiner 1.51 ETCHash hashrate is lower than previous versions". I would add that 1.51 has the lower ETCH hashrate ever, but SLIGHTLY slower (GTX 1650 4GB DDR4 previous versions= 15.65 Mh/s - GTX 1650 4GB DDR4 lolMiner 1.51 = 15.45 Mh/s). Don't worry, I'll use 1.50, it's not a problem.

**Comment by jgonzis** [comment]
> I didn't talk about before and after @jgonzis , I told you that "In lolMiner 1.51 ETCHash hashrate is lower than previous versions". I would add that 1.51 has the lower ETCH hashrate ever, but SLIGHTLY slower (GTX 1650 4GB DDR4 previous versions= 15.65 Mh/s - GTX 1650 4GB DDR4 lolMiner 1.51 = 15.45 Mh/s). Don't worry, I'll use 1.50, it's not a problem. Thank you.

But we still don't know if you talk about Windows, Linux,...

**Comment by BitMaci** [comment]
Sorry for missing those details, I use windows 10 Pro 64bit, i7-8850H, 8Gb RAM and SSD 500GB. Basically the efficiency slightly  decreased from 0.376 Kw/h to 0.370 Kw/h. I know you're focusing on LHR, it's good, my "issue" was meant to let you know that in 1.51 there's this slight decrease. My card is GTX 1650 4Gb DDR4 OC settings (always the same) : core 0 - mem +450 - PL 60 (minimum allowed = 45 W) - Pstate OFF. Thank you.
