### ISSUE TITLE
RTX 2060 going to crazy !!!

### ISSUE THREAD

**Issue by zulu1905** [Lolliedieb/lolMiner-releases#1592]
with the lolminer 1.51

RTX 2060  going to crazy
33mh eth  2000 mh TOn and 80 watt power consumption
obviously it is a bug because it can not find ton share

**Comment by jgonzis** [comment]
> with the lolminer 1.51
> 
> RTX 2060 going to crazy 33mh eth 2000 mh TOn and 80 watt power consumption obviously it is a bug because it can not find ton share

Could you share a photo to know the drivers you are using?. In our test we haven't got that issue, so all information will be welcome please. Try in case to use --dualfactor 20 to see if helps

**Comment by zulu1905** [comment]
i am using 512.15 driver.

with dual factor 20  
still can not find ton share
![lolminer2060](https://user-images.githubusercontent.com/21012254/169527681-6e33c729-b869-4d7c-9624-244d1235ce6b.PNG)

and i set dualfactor 64 
see this
![lolminer2060dualfactor64](https://user-images.githubusercontent.com/21012254/169527873-c8295d4b-2b13-4290-92b0-25c65762cc85.PNG)

ton hash shows 2100 mh but zero effect it is a bug.

RTX 2060 normal hashrate is  33mh eth + 998mh Ton and 125 watt power consumption for dual mining.

**Comment by jgonzis** [comment]
> i am using 512.15 driver.
> 
> with dual factor 20 still can not find ton share ![lolminer2060](https://user-images.githubusercontent.com/21012254/169527681-6e33c729-b869-4d7c-9624-244d1235ce6b.PNG)
> 
> and i set dualfactor 64 see this ![lolminer2060dualfactor64](https://user-images.githubusercontent.com/21012254/169527873-c8295d4b-2b13-4290-92b0-25c65762cc85.PNG)
> 
> ton hash shows 2100 mh but zero effect it is a bug.
> 
> RTX 2060 normal hashrate is 33mh eth + 998mh Ton and 125 watt power consumption for dual mining.
> 
> @jgonzis

1.51a solve the problem... the Dev comment in the Telegram group, it was a bug in the 6Gb GPUS for Windows. Now new release solve the problem!! Thx for all the feedback to find the problem
