### ISSUE TITLE
little question about fee

### ISSUE THREAD

**Issue by queinnec35** [Lolliedieb/lolMiner-releases#1593]
hello i read the new fee value, if i use the old lolminer 1.46 (work stable and safe on non lhr rig) , does the new fee value apply ? or still the old value?
need i update my rig for save extra fee money? or can i continu with old 1.46a?
thx

**Comment by jgonzis** [comment]
> hello i read the new fee value, if i use the old lolminer 1.46 (work stable and safe on non lhr rig) , does the new fee value apply ? or still the old value? need i update my rig for save extra fee money? or can i continu with old 1.46a? thx

Each version has his fee, doing dual better to use last ones with 0% Fee in dual part. If you can try to use lastest. If not you can always go back. Last versions are really stable

**Comment by queinnec35** [comment]
ok thx, the probleme is update hiveos , kernel , driver, and soft, many bug here , and the toncoin pool have change adress with bug, the old work , i am scared to touch anything :)

**Comment by jgonzis** [comment]
> ok thx, the probleme is update hiveos , kernel , driver, and soft, many bug here , and the toncoin pool have change adress with bug, the old work , i am scared to touch anything :)

You are... if works don't touch😅
