### ISSUE TITLE
lolMiner 1.51 - ETH/TON Dual mining - Not mining TON with all cards

### ISSUE THREAD

**Issue by LayLo3D** [Lolliedieb/lolMiner-releases#1594]
I updated to lolMiner 1.51 this morning and once started ETH mining was working fine, but TON was only being mined on half the cards in the rig. I did specify any parameters. I then upgraded to the latest drivers, but it didn't solve the problem. Switching back to the previous version of lolMiner that I have installed (1.48) all cards mine both ETH and TON successfully.

I'm running Windows 10 and RTX 3090 cards.

**Comment by drond1** [comment]
Same problem. Win10, Mix rig 3060ti, 3070ti, 3080. Random card - 0 hashrate on TON,

![dualfactor 0](https://user-images.githubusercontent.com/99704990/169459658-7a893187-3397-49f6-8e2f-36b91a99318e.PNG)

But if I use --dualfactor 20, 24 (not auto), it works well for me. Keep watching. 

![dualfactor 20,24](https://user-images.githubusercontent.com/99704990/169459932-940d0247-2caa-4c12-9470-f86deb3cb69f.PNG)

**Comment by jgonzis** [comment]
Please, all problem in Windows is that user is using other components that "destroy" the tunning for these reason the --dualfactor helps that avoiding the waves that people comment. So now with --dualfactor is more easy to use the computer without problem. Also 1.51a solve the problem on 6Gb in Windows too.
