### ISSUE TITLE
Crashing on pass parm

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1598]
I dont know why but lolMiner crashing when using pass parameter:
|              Made by Lolliedieb, May 2022               |
+---------------------------------------------------------+
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
xxx/xxx: line 28: 16495 Aborted                 (core dumped) ./lolMiner --nocolor -a ETHASH -p sha256.poolbinance.com:1800 -u xxxx --pass 123456 --worker xxxx.001 --dualmode ALEPHDUAL --dualuser yyyy --dualpool de.alephium.herominers.com:1199 --tls 0 --dualworker zzzz --cclk 1185,1170,1170,1170,1170,*,1185 --mclk 7365,8115,8115,8115,8115,*,7365 --watchdog exit --watchdogscript /xxx/yyy.sh

There default password is 123456
Without password i have disconnection with unauthorized message.
On ethash.poolbinance.com work ok.
On binance payment is set to sha etc.

**Comment by jgonzis** [comment]
> I dont know why but lolMiner crashing when using pass parameter: | Made by Lolliedieb, May 2022 | +---------------------------------------------------------+ terminate called after throwing an instance of 'std::logic_error' what(): basic_string::_M_construct null not valid xxx/xxx: line 28: 16495 Aborted (core dumped) ./lolMiner --nocolor -a ETHASH -p sha256.poolbinance.com:1800 -u xxxx --pass 123456 --worker xxxx.001 --dualmode ALEPHDUAL --dualuser yyyy --dualpool de.alephium.herominers.com:1199 --tls 0 --dualworker zzzz --cclk 1185,1170,1170,1170,1170,_,1185 --mclk 7365,8115,8115,8115,8115,_,7365 --watchdog exit --watchdogscript /xxx/yyy.sh
> 
> There default password is 123456 Without password i have disconnection with unauthorized message. On ethash.poolbinance.com work ok. On binance payment is set to sha etc.

Sha256 pool? That could never work

**Comment by dawidmosk** [comment]
Yes, thanks.
