### ISSUE TITLE
Dual mode for split and TON/ALPH

### ISSUE THREAD

**Issue by sebek72** [Lolliedieb/lolMiner-releases#1599]
Would it be possible to add multiple dual modes?

Split the ETH part with mode SPLIT-X and additionally dual mine TON/APLH (no split)?

Thanks

**Comment by jgonzis** [comment]
> Would it be possible to add multiple dual modes?
> 
> Split the ETH part with mode SPLIT-X and additionally dual mine TON/APLH (no split)?
> 
> Thanks

Hi,

Split is not working with Dual... it only works with ETH or ETC, not possible with DUAL Mining

**Comment by sebek72** [comment]
I know. This was more of a feature request ;)
