### ISSUE TITLE
Error trying to mine Dual mode ETH + ALEPHIUM various versions

### ISSUE THREAD

**Issue by Cristian-Estevez** [Lolliedieb/lolMiner-releases#1600]
Hello: 
I've been using lolminer for a while now in hiveOS. Mostly mining Dual mode ETH+TON with no problems at all.
Today I wanted to try ETH+ALPH mode, but got the following error "lolminer exited (exitcode=0), waiting to cooldown a bit".
I tried it in 2 different rigs One of them has only 1 rtx3060ti and the otherone has 6 amd6600xt and 3 rtx3060ti. The same workers I've been using so far with no problems. 
So after created the flight sheet and ran it got that error message and the mining never starts. 
I tried different versions of lolminer (1.48, 1.49, 1.50, 1.51, 1.51a) and got the same error also.
The driver I'm using for nvidia is 510.60.02 and amd is 20.40
Is there any known issue regarding this? 

Here is my flight sheet setup:
![flightsheet1](https://user-images.githubusercontent.com/70970396/169719114-45fd9867-ea73-4715-855f-c9dfa644e39d.png)
![flightsheet2](https://user-images.githubusercontent.com/70970396/169719117-c1f471e9-9759-43c5-831a-a69f807fade6.png)
![flightsheet3](https://user-images.githubusercontent.com/70970396/169719119-106e3955-89f8-4666-a6d1-f29f7612e7ce.png)

Thanks in advance.

**Comment by jgonzis** [comment]
Hi, 

Try filling the information: 

![image](https://user-images.githubusercontent.com/38668405/169773545-24bf0611-68f4-440e-b233-1fc6795ddc3e.png)

Youtube vídeo: https://youtu.be/l9muRDlGUnw

**Comment by Cristian-Estevez** [comment]
I dont know why it did not complete itself. Its working perfectly. Thankyou

**Comment by jgonzis** [comment]
> I dont know why it did not complete itself. Its working perfectly. Thankyou

Thx for the feedback

**Comment by kb1811** [comment]
I am also having problem similar to this.
I have at one location X running both amd and nvidia gpus. Amd gpu and nvidia gpu do not mix in any of my rigs. 
This location X... eth + alph runs fine. 
At my other location Y however, i am getting "lolminer exited (exitcode=0), waiting to cooldown a bit"... only for the Amd rigs. Nvidias rigs runs fine at this same location Y.

I only difference i can see is the ISP are not the same. I did tried changing the dns to opendns, cloudflare... etc but still having the same problem in the amd. (btw they are all 6600xt)

help please...

![photo_2022-06-22_15-25-01](https://user-images.githubusercontent.com/83440635/174969451-be3e45aa-8073-47c0-bece-546f3792d9bd.jpg)
![photo_2022-06-22_15-25-06](https://user-images.githubusercontent.com/83440635/174969437-7bb33ba4-550e-41cd-b0f8-5dca81738387.jpg)
![photo_2022-06-22_15-25-08](https://user-images.githubusercontent.com/83440635/174969458-78a9c585-d846-417f-a6a1-16df592ffdec.jpg)
![photo_2022-06-22_15-25-11](https://user-images.githubusercontent.com/83440635/174969455-d4766e0a-2ce3-440e-8cb7-08070ac68313.jpg)
