### ISSUE TITLE
Miner stops after a day dual mining eth ton - lol version 1.51

### ISSUE THREAD

**Issue by Ham2022ed** [Lolliedieb/lolMiner-releases#1603]
Hi. I use the following dag file mining eth + ton . I am using crazy pool. the miner stops after about a day and does not recover. I am using version 1.51. Is there a problem with the dag file? because I could not setup the normal dag file using crazyminer.

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

lolMiner.exe --algo ETHASH --pool stratum+tcp://eu.crazypool.org:3333 --user 0x91cae71e2d55b2c7826ccd44102c590ca1238723.Worker --ethstratum=ETHV1 --dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser EQA4Tz2015M_iv5HFLHJNntmP9ApuVWm10dCS6WO1dQewAmA			

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit
timeout 10
goto W10
goto END

:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit --nocolor
timeout 10
goto OtherW

:END
pause

**Comment by jgonzis** [comment]
Use the watchdog file to autorestart in case is stop it for some reason:

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)
