### ISSUE TITLE
Stale Shares

### ISSUE THREAD

**Issue by thompsontj12** [Lolliedieb/lolMiner-releases#1604]
I'm getting a ton of stale shares when mining with 1.51/a and my rigs are stable on 1.46 regardless of the driver version. Would like to be able to use 1.51 due to dualfactor. Any suggestions? It gets to the point on all my rigs where it says too many stale shares, reconnecting...  constantly

**Comment by thompsontj12** [comment]
This happens when mining to miningpoolhub... changed to ethermine and it's working. Can this be fixed?

**Comment by jgonzis** [comment]
> This happens when mining to miningpoolhub... changed to ethermine and it's working. Can this be fixed?

Could it be that you are not using the proper port or connection. I think MPH use ETHV1 connnection
