### ISSUE TITLE
Full lhr unlock, dual mining, admin rights

### ISSUE THREAD

**Issue by DasUnding** [Lolliedieb/lolMiner-releases#1607]
Hello, is there a way to easily use old bat files as admin for dual mining with full lhr unlock in windows 11? By starting the bat file with admin rights it cannot find the lolMiner.exe. Is there a simple method to go around this?

**Comment by jgonzis** [comment]
> Hello, is there a way to easily use old bat files as admin for dual mining with full lhr unlock in windows 11? By starting the bat file with admin rights it cannot find the lolMiner.exe. Is there a simple method to go around this?

I recommend you to use the watchdog that has auto admin for LHR Rig too. Or you can create your own bat file all in one line. 
https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)
