### ISSUE TITLE
How to connect to lolminer web interface

### ISSUE THREAD

**Issue by krupis** [Lolliedieb/lolMiner-releases#1610]
Hello. I am running lolminer for my mining rigs. Could someone clarify to me how can I connect to webinterface?

I have tried to:
Http://<my_ip>:8080/gui
![image](https://user-images.githubusercontent.com/22237034/170821568-a76fe829-5623-42e3-ade3-808cc241b077.png)

Anybody having same issue?

**Comment by jgonzis** [comment]
> Hello. I am running lolminer for my mining rigs. Could someone clarify to me how can I connect to webinterface?
> 
> I have tried to: Http://<my_ip>:8080/gui ![image](https://user-images.githubusercontent.com/22237034/170821568-a76fe829-5623-42e3-ade3-808cc241b077.png)
> 
> Anybody having same issue?

You have to add in the run bat file --apiport 8080 

If you don't do it the API Port will not be active.

**Comment by krupis** [comment]
Hello. I have not managed to find a clear instruction on how to do this. Could you clarify where exactly do I need to add this line in the bat file? Should I add it in
set "EXTRAPARAMETERS=--apiport 8080" ?

**Comment by jgonzis** [comment]
> Hello. I have not managed to find a clear instruction on how to do this. Could you clarify where exactly do I need to add this line in the bat file? Should I add it in set "EXTRAPARAMETERS=--apiport 8080" ?
> 
> I looked at the git repository additional commands and other places and found a list of additional commands but not a single example on how this command can be executed and where this command needs to be typed. I think the instructions should be more clear

Like this it will work, you can also use from the Wiki Section the bat file with Watchdog it has it by default
