### ISSUE TITLE
Feature request: Eth+Kaspa dual-mining

### ISSUE THREAD

**Issue by supertypo** [Lolliedieb/lolMiner-releases#1611]
"Kaspa uses a modified version of [HeavyHash](https://arxiv.org/pdf/1911.05193.pdf). HeavyHash sandwhiches a matrix multiplication step between two "standard" hashes (e.g. keccak)."
  
There is an open source gpu miner available here:
https://github.com/tmrlvi/kaspa-miner
  
The coin has just recently been listed on exchanges (txbit & exbitron) and is still early in it's emission cycle.  
  
Lolminer would be the first miner to support dual-mining of the coin.
  
About:
Kaspa is a proof-of-work cryptocurrency which implements the GHOSTDAG protocol. GHOSTDAG does not orphan blocks created in parallel, rather allows them to coexist and orders them in consensus. It's aiming to be the worlds fastest and purest proof-of-work consensus engine. Current block time is 1/sec, and it will be lowered in the future.

**Comment by jgonzis** [comment]
Thx for the comment...

**Comment by XVGHypeMan** [comment]
Wolf the infamous FPGA bitstream coder said:

Here's what I learned how to implement the PoW from:
https://github.com/tmrlvi/kaspa-miner
https://github.com/tmrlvi/kaspa-miner/blob/main/src/pow/heavy_hash.rs

GitHub (https://github.com/tmrlvi/kaspa-miner)
GitHub - tmrlvi/kaspa-miner: A fast CPU/GPU miner for Kaspa
A fast CPU/GPU miner for Kaspa. Contribute to tmrlvi/kaspa-miner development by creating an account on GitHub.

**Comment by amaoback** [comment]
**Speaking on behalf of the Chinese community, we need this feature very much.**

**Comment by XVGHypeMan** [comment]
Lollie if you get a wallet at kdx.app we will kick you down some ;_)

**Comment by user745110460** [comment]
we need this feature very much.

**Comment by yuan6520** [comment]
支持ETH+KASPA

**Comment by chenhonghe** [comment]
We need this feature very much.

**Comment by sgarzaa** [comment]
it would be wonderful

**Comment by leevcc** [comment]
I believe it can perfectly replace toncoin

**Comment by user745110460** [comment]
Is anyone integrating this feature

**Comment by Shano592** [comment]
> Is anyone integrating this feature

SRBMiner is doing only KAS

**Comment by snoby** [comment]
+1 for implementation request

**Comment by mikaljan** [comment]
This would be the best feature to add!!

**Comment by snoby** [comment]
> This would be the best feature to add!!

BZminer has this already and it works well.

**Comment by ltwarrior18** [comment]
SRBminer already does ergo+kaspa or eth+kaspa minig. Ergo now is the king with NETA and other smart contracts and NFT. The bad side is that srbminer is amd only...

**Comment by mikaljan** [comment]
> SRBminer already does ergo+kaspa or eth+kaspa minig. Ergo now is the king with NETA and other smart contracts and NFT. The bad side is that srbminer is amd only...

Exacty, AMD only!
So please implement this ASAP!! thanks!!

**Comment by globalmining-cl** [comment]
Hello
+1 for implementation request

**Comment by supertypo** [comment]
Great news!

Looks like the newest beta has dual mining enabled! https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.53_beta

(Only for AMD so far)

**Comment by jgonzis** [comment]
> Great news!
> 
> Looks like the newest beta has dual mining enabled! https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.53_beta
> 
> (Only for AMD so far)

You are right, well step by step

**Comment by supertypo** [comment]
We got what we asked for 🎉 Lolminer 1.53 has dual mining KAS for both team green and red. Thanks! Closing issue...
