### ISSUE TITLE
ETH+Ton dual mining  with --dualdevices problem

### ISSUE THREAD

**Issue by Gurcano** [Lolliedieb/lolMiner-releases#1612]
Dual devices settings working wrong.
Secondary (TON) mining activated and first mining (ETH) deactivated when you set like this : --dualdevices 1,2,3 etc.
I want to stop dual mining on device 0 and it not work on the latest version.
Note 1 : --dualdevices -1,-2,-3 is working. But 0 never stopped on dual.
Note 2 : I'm using HiveOS (Latest version).

**Comment by jgonzis** [comment]
> Dual devices settings working wrong. Secondary (TON) mining activated and first mining (ETH) deactivated when you set like this : --dualdevices 1,2,3 etc. I want to stop dual mining on device 0 and it not work on the latest version. Note 1 : --dualdevices -1,-2,-3 is working. But 0 never stopped on dual. Note 2 : I'm using HiveOS (Latest version).


why are you using negatvies dual devices?.   it should be --dualdevices 1,2,3 that will avoid ETH and do TON on this 3 GPUs.  

If you write --dualdevices 0,1,2,3 it will do that 4 and the rest ETH +TON

**Comment by Gurcano** [comment]
Cause positive values don't work. Why you never read to messages well ?

30 May 2022 Pzt 15:56 tarihinde jgonzis ***@***.***> şunu
yazdı:
