### ISSUE TITLE
TON 0 Mh/s (dual mining TON + ETH)

### ISSUE THREAD

**Issue by ducanh-le** [Lolliedieb/lolMiner-releases#1615]
Hello, when dual mining, the TON algorithm sometime doesn't start with miner (sometime 0 Mh/s on some gpus and sometime all of them not working) while ETH is always stable.

Once TON algorithm is started, it will stable too but I needed to restart the miner many times to get it working on all gpus. (I have waited 5-10 min between each restart to sure that it's not working, today I wasted 1 hour to do that).

**Comment by GYKrauss** [comment]
Why is this closed? I still have this issue!
