### ISSUE TITLE
temperature limit

### ISSUE THREAD

**Issue by JackDeRke** [Lolliedieb/lolMiner-releases#1616]
I have a rig that I manage for a friend. His GPUs keep overheating in the day so I have a temp limit applied in the miner. Whenever it hits the limit the miner spams around 100 times that the limit has been reached and then switches the card to cool down.
Why does it do this? can´t it just say it once?
Thanks :)

**Comment by JackDeRke** [comment]
Currently we have a few colder days but I can try catching it.

jgonzis ***@***.***> schrieb am Mi., 15. Juni 2022, 15:30:

**Comment by JackDeRke** [comment]
Alright I forced it to happen in these two pictures by slowing down the fan
on this A2000 and setting a low limit, but it happens on my rig as well as
on my friends rig.


Am Mi., 15. Juni 2022 um 15:35 Uhr schrieb Malte Derke <
***@***.***>:

**Comment by jgonzis** [comment]
I hope you can post that photos, meanwhile I close it... until you send the photos.
