### ISSUE TITLE
lolminer freezing rig since about Ergo epoch ~343

### ISSUE THREAD

**Issue by rluik** [Lolliedieb/lolMiner-releases#1618]
Linux (mmpos, HiveOS), both on AMDs and NVIDIAs.
Other mining software are working.

**Comment by Rendzio** [comment]
Same goes for me. 4-5 hours ago it crashed and isn't working,
![Screenshot_773](https://user-images.githubusercontent.com/107176020/172794063-196bf347-6569-4bac-99a4-27131dca6900.png)

**Comment by DarkShad03** [comment]
Same here, all my rigs are having the same issue at the same time. Switched to nbminer for now, hope they release a fix soon

**Comment by Venrera** [comment]
I have the same problem( Miner suggests to check OC settings, but memory clock is blocked totally in my GPU, so it is just 0, and I don't want to unlock it using BIOS settings, as well as miner worked greately before. Now I am using T-rex miner, and it is working ok, but to be honest lolMiner balanced energy and efficiency much better for Autolykos2, now my card's average temperature is a few degrees higher with the same hashrate. Hope the problem will be fixed soon, I am much more loyal to the lolMiner.
I have Nvidia card.

**Comment by jgonzis** [comment]
> same problem..no update..or reponse

Today probably will be released with 1.52 working, our test found that now is working with the new release. It will be very soon updated.

**Comment by DarkShad03** [comment]
Any news on the update? I much prefer to use lolminer compared to t-rex for ergo
