### ISSUE TITLE
repeated dag errors

### ISSUE THREAD

**Issue by N6REJ** [Lolliedieb/lolMiner-releases#1621]
my 2060 ko has worked on hive for almost a year now flawlessly.  I brought it to my windows machine cause the mb died on my dedicated rig and I'm having issues.
Aside from the mining rate being 20% slower I'm getting constant dag errors.  It's always the same number of defect segments and will loop several times.  Often when I get up in the morning there is a fatal error that its trying to recover from.
i'm also having an issue where its not mining ton very well.  Most of the time its @ zero other times its a few hundred instead of 1.5G like it was in hive.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/1850089/173725759-c7398147-0fed-45ab-a60f-18e24d887be7.png">

[dual_mine_eth_ton_ethermine.zip](https://github.com/Lolliedieb/lolMiner-releases/files/8905289/dual_mine_eth_ton_ethermine.zip)

**Comment by rluik** [comment]
Are you using the same memory OC as in Hive? I hope you know you shouldn't, must be set to half on Windows vs Linux to run at the same clocks. What's your OC?

**Comment by jgonzis** [comment]
> my 2060 ko has worked on hive for almost a year now flawlessly. I brought it to my windows machine cause the mb died on my dedicated rig and I'm having issues. Aside from the mining rate being 20% slower I'm getting constant dag errors. It's always the same number of defect segments and will loop several times. Often when I get up in the morning there is a fatal error that its trying to recover from. i'm also having an issue where its not mining ton very well. Most of the time its @ zero other times its a few hundred instead of 1.5G like it was in hive.
> 
> <img alt="image" width="628" src="https://user-images.githubusercontent.com/1850089/173725759-c7398147-0fed-45ab-a60f-18e24d887be7.png">
> 
> [dual_mine_eth_ton_ethermine.zip](https://github.com/Lolliedieb/lolMiner-releases/files/8905289/dual_mine_eth_ton_ethermine.zip)

that DAG errors are normally related to Memory OC or riser...  But you are also using the old version 1.51 and not 1.51a for the dual ton. Could you try it the 1.51a?

**Comment by N6REJ** [comment]
update: its a eth issue.  Mining on unmineable with sol doesn't have the same problem.

**Comment by whl961210** [comment]
> update: its a eth issue. Mining on unmineable with sol doesn't have the same problem.

I think it’s problem with 2060 cards, I have over 80 gpus including 2060s, 2060 and 1660s, all of my 2060 gpus now encountered this error
