### ISSUE TITLE
segfault on startup

### ISSUE THREAD

**Issue by standula** [Lolliedieb/lolMiner-releases#1623]
Connecting to pool... 
DNS over HTTPS resolve succeeded 
Connected to de.alephium.herominers.com(88.99.164.154):1199  (TLS disabled)
./miner.sh: line 19: 28845 Segmentation fault      (core dumped) ./lolMiner --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode ALEPHDUAL --dualpool $ALEPHPOOL --dualuser $ALEPHWALLET --worker oil_rig_2 $@
root@worker:/hive/miners/lolminer/1.51a#

**Comment by jgonzis** [comment]
> Connecting to pool... DNS over HTTPS resolve succeeded Connected to de.alephium.herominers.com(88.99.164.154):1199 (TLS disabled) ./miner.sh: line 19: 28845 Segmentation fault (core dumped) ./lolMiner --algo ETHASH --poolETHPOOL−−user@ root@worker:/hive/miners/lolminer/1.51a#

could you share your full config line to check in my rig?

**Comment by standula** [comment]
Hi,

./lolMiner --log on --logfile /var/log/lolMiner.log --algo ETHASH --pool stratum+ssl://eu.ezil.me:25443 --user 0xxxxxxxxxxxxxxxxxxx.zzzzzzzzzzzzzzzzzzzzzzzz --dualmode ALEPHDUAL --dualpool de.alephium.herominers.com:1199 --dualuser aaaaaaaaaaa --worker oil_rig_2 --enablezilcache 1

I am looking for the core dump but there is not file in folder.

**Comment by jgonzis** [comment]
> Hi,
> 
> ./lolMiner --log on --logfile /var/log/lolMiner.log --algo ETHASH --pool stratum+ssl://eu.ezil.me:25443 --user 0xxxxxxxxxxxxxxxxxxx.zzzzzzzzzzzzzzzzzzzzzzzz --dualmode ALEPHDUAL --dualpool de.alephium.herominers.com:1199 --dualuser aaaaaaaaaaa --worker oil_rig_2 --enablezilcache 1
> 
> I am looking for the core dump but there is not file in folder.

Normally error is in /var/log/syslog
