### ISSUE TITLE
3080ti low dual minig hashrate, hiveos

### ISSUE THREAD

**Issue by Karaguay** [Lolliedieb/lolMiner-releases#1626]
Hi, im having problems only with the 3080ti, i put CC overclock but the miner dont apply it

![image](https://user-images.githubusercontent.com/107818194/174505924-f0bfb00a-5bf5-412d-9b55-785a5e131998.png)
![image](https://user-images.githubusercontent.com/107818194/174505948-80d0a4fb-7d2d-437c-98db-ec464b718e2f.png)
![image](https://user-images.githubusercontent.com/107818194/174506177-acee0ab6-492e-49d4-ab73-2d3f1e74815d.png)

its on default dual-factor value, If I change the dual factor, the Eth mhs improves but the TON literally goes down

Hiveos: 0.6-218@220615
Linux: 5.10.0-hiveos #110
Driver: N 510.60.02
lolminer v.1.51a

**Comment by jgonzis** [comment]
That is the typicial intern Power Limit from lot of 3080TI... really complicated to find a not limit bios
