### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by charnet3d** [Lolliedieb/lolMiner-releases#1628]
I think there should be a mention of --dualtls in the documentation of dual modes (where it's relevant). I was trying to set it on woolypooly for ALEPH and just figured it out from the other params (dualpool, dualuser, ...).

While talking about the documentation, the readme text file should include all possible arguments without exception. I think it's a bit outdated (it has no dual or OC arguments)

**Comment by jgonzis** [comment]
> I think there should be a mention of --dualtls in the documentation of dual modes (where it's relevant). I was trying to set it on woolypooly for ALEPH and just figured it out from the other params (dualpool, dualuser, ...).
> 
> While talking about the documentation, the readme text file should include all possible arguments without exception. I think it's a bit outdated (it has no dual or OC arguments)

--dualtls is implemented.  It should work, you can also use --dualpool ss://poolname  to connect to the pool with SSL connection

**Comment by charnet3d** [comment]
My hope was that the docs be as updated as possible so you can find what you want without visiting the wiki on github, or if you have to it's more for How-Tos and more detailed info.

Thank you for your hard work :)

**Comment by jgonzis** [comment]
> My hope was that the docs be as updated as possible so you can find what you want without visiting the wiki on github, or if you have to it's more for How-Tos and more detailed info.
> 
> Thank you for your hard work :)

You are right, sometimes there are lot of staff that is not show easy.
