### ISSUE TITLE
RTX3060V1 0.0 mhs ALEPHIUM

### ISSUE THREAD

**Issue by pabloguns** [Lolliedieb/lolMiner-releases#1629]
hello, could someone help me? sometimes it's hard to start mining ALEPHIUM, I have mixed rigs, 2 trx3060v1 and 2 6700xt. The 6700xt starts without problems, but the 3060 stays at 0.0 mh/s, I'm on Windows 10,

**Comment by jgonzis** [comment]
> hello, could someone help me? sometimes it's hard to start mining ALEPHIUM, I have mixed rigs, 2 trx3060v1 and 2 6700xt. The 6700xt starts without problems, but the 3060 stays at 0.0 mh/s, I'm on Windows 10,

Try to start with --dualfactor 15 first of all for the tune to see if works and later move that parameter to your desired value.
