### ISSUE TITLE
I have been run miner for a day, but I got nothing in my wallet.

### ISSUE THREAD

**Issue by littlefoxxdt** [Lolliedieb/lolMiner-releases#163]
When is the expected first payout from the miner?

**Comment by Keimling27** [comment]
It depends which pool you use at 2 miner for example you must reach 0,05 ether for payout. You can see in pool description.

**Comment by Lolliedieb** [comment]
This seems not miner related. Best is to check with the pool website - if that shows immature or unpaid balances for your account, then you are fine. If not you urgently should check if you mine to the right wallet & pool.
