### ISSUE TITLE
ETH + TON does not work in 1.52 release

### ISSUE THREAD

**Issue by nikolaiev** [Lolliedieb/lolMiner-releases#1635]
ETH + TON does not work in version 1.52
Miner mines only ETH instead of dual mining.

**Comment by RainbowMiner** [comment]
This has been announced. The new release v1.52 doesn't support TON any longer since TON mining is coming to an end within the following 20h (see here: https://ton.app):
> Removed: Support for mining Ton in single and dual mining modes. Note that existing dual mining configurations will automatically launch Eth / Etc / Ubiq only mode, so existing configurations will not be broken.
