### ISSUE TITLE
Can't Run the lolMiner

### ISSUE THREAD

**Issue by mbalci420-hub** [Lolliedieb/lolMiner-releases#164]
Hi guys. I downloaded the program. Unzip it, and made the necessary changes on the eth file but when I click on the setup file, nothing happens. I tried to delete and download it again and again but still nothing.

**Comment by Keimling27** [comment]
dont click miner.exe you must click the ether bat file you changed your wallet

**Comment by CruMar01** [comment]
yes doesn't work with the ether bat file.....
don't know the problem

**Comment by jgonzis** [comment]
Which is your config system?.

Also I recommend you to run the bat file directly from the command windows, that will let you more information...

**Comment by mbalci420-hub** [comment]
Thank you all guys. I feel like an idiot but I figured out that I didn't need to click on the exe file, I ran the bat file and started mining. Thanx again

**Comment by jgonzis** [comment]
Same as #452
