### ISSUE TITLE
API

### ISSUE THREAD

**Issue by jnelson32177a** [Lolliedieb/lolMiner-releases#1642]
Is there any way to find the API key that Lol miner uses for the GUI? I would like to try turning it into an actual graphical layout webpage for the stats?

**Comment by jgonzis** [comment]
> Is there any way to find the API key that Lol miner uses for the GUI? I would like to try turning it into an actual graphical layout webpage for the stats?

You don't need any API Key... you just only need to read IP:API_PORT/Summary to have all json information
