### ISSUE TITLE
Running 1.52 on Windows is nerfing my non-LHR 3070's - even when switching back to other miners

### ISSUE THREAD

**Issue by bryangottschalk** [Lolliedieb/lolMiner-releases#1643]
I used to get 62 MHs on 3070s now they get 37MHs after running lolMiner 1.52 on Windows. This is even the case if I switch back to NBMiner. I reproduced this on two different Windows rigs with 3070s and one 3060. It seems to limit my power under the hood to 80-95 watts when it should be at 120ish. I don't know how to increase the power limit back to reset from this, Afterburner is not working.

config used:  `"EXTRAPARAMETERS=--cclk=1200 --mclk=1400"`
Driver: 512.15
OS: Windows

![image](https://user-images.githubusercontent.com/25968605/177582666-4e2be46c-5476-4132-ada5-6e50a8f8c9c5.png)

![image](https://user-images.githubusercontent.com/25968605/177582721-0b758eae-c899-42ab-9f34-dd82f00a34a0.png)

**Comment by bryangottschalk** [comment]
It seems to limit my power under the good to 80-95 watts when it should be at 120ish. I don't know how to increase the power limit back, afterburner is not working

**Comment by jgonzis** [comment]
> I used to get 62 MHs on 3070s now they get 37MHs after running lolMiner 1.52 on Windows. This is even the case if I switch back to NBMiner. I reproduced this on two different Windows rigs with 3070s and one 3060. It seems to limit my power under the hood to 80-95 watts when it should be at 120ish. I don't know how to increase the power limit back to reset from this, Afterburner is not working.
> 
> config used: `"EXTRAPARAMETERS=--cclk=1200 --mclk=1400"` Driver: 512.15 OS: Windows
> 
> ![image](https://user-images.githubusercontent.com/25968605/177582666-4e2be46c-5476-4132-ada5-6e50a8f8c9c5.png)
> 
> ![image](https://user-images.githubusercontent.com/25968605/177582721-0b758eae-c899-42ab-9f34-dd82f00a34a0.png)

What you want to do is nearly that but... --mclk was only for TON Mining to reduce Watts. You could do that using the bat file with watchdog and lolNvidiaOC

in the parameters --cclk 1200,1200 --delay 20 --omclk 1400,1400 that will allow you to load the DAG with normal memory to reduce errors in DAG

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-Windows-(LHR,Watchdog,WebServer,OC)

**Comment by bryangottschalk** [comment]
Running my miner with the inverse of what I had done before seems to have fixed it fyi. --mclk=-1200
