### ISSUE TITLE
NVIDIA RTX3060ti FE 'err' Message in LOLMINER

### ISSUE THREAD

**Issue by Z-Adams1** [Lolliedieb/lolMiner-releases#1644]
Hi there,

I keep on getting one of the GPUs giving this error... tried to reduce my OC many times and to several levels, yet it still happens... I am running on Windows 10 and use MSI Afterburner... 

GPU drivers are up to date and I am using Lolminer 1.51a... I also tried rolling back to older GPU driver versions, but with no improvement.

Any ideas? Thanks!

![IMG_2327](https://user-images.githubusercontent.com/108840270/177655853-aa207d67-dc90-4916-bdcd-e06a7c109ed0.PNG)

**Comment by tsfrederick333** [comment]
Did you try a different riser or connections? Also, try to plug into existing gpu slot that is working to see if the error occurs again? If it doesn't then it might be a connection point

**Comment by jgonzis** [comment]
I complete agree, that seems to be a riser issue or psu or socket problem

**Comment by Z-Adams1** [comment]
I will try to change 

> Did you try a different riser or connections? Also, try to plug into existing gpu slot that is working to see if the error occurs again? If it doesn't then it might be a connection point

Thank you tsfrederick333... I will try changing risers... I am using the same type on all the GPUs, which is a 1X to 16X circuit but connected to a 4X slot on MB through and adapter that allows USB cable... they are also fed from the same PSU

**Comment by Z-Adams1** [comment]
It was a riser issue... thanks for the advise :)!
