### ISSUE TITLE
 The latest version, can't find the ETH+ALPH file

### ISSUE THREAD

**Issue by tsrjshyang** [Lolliedieb/lolMiner-releases#1645]
Hello
It's my first time using lolminer.I want to mine ETH and ALPH together，but  The latest version, can't find the ETH+ALPH file

**Comment by tsrjshyang** [comment]
![1](https://user-images.githubusercontent.com/84229995/178128561-fa3ba78b-140b-4942-8d04-140ed86c8c86.PNG)

**Comment by UselessGuru** [comment]
What about the dual_mine_eth_aleph* files?

**Comment by jgonzis** [comment]
Yes. It is ETH + ALEPH... the name of the coin is alephium, but is write as ALPH
