### ISSUE TITLE
Dual mining eth+ alph problem

### ISSUE THREAD

**Issue by augustors1** [Lolliedieb/lolMiner-releases#1649]
I am trying to dual eth+alph in some of my gpus and only mine eth at others.
0,1,2,3 = eth only
4,5,6,7,8 = dual eth+alph
But lolminer -devices select the gpus that will mine and -dualdevices select the 2nd algo only.
I went looking for this but didn´t find any exemples. How can I do this?

**Comment by jgonzis** [comment]
> I am trying to dual eth+alph in some of my gpus and only mine eth at others. 0,1,2,3 = eth only 4,5,6,7,8 = dual eth+alph But lolminer -devices select the gpus that will mine and -dualdevices select the 2nd algo only. I went looking for this but didn´t find any exemples. How can I do this?

You can use --maxdualimpact 0,0,0,0,*,*,*,*,* for example
