### ISSUE TITLE
Does the parameter "--cclk --mclk"  work on ubuntu?

### ISSUE THREAD

**Issue by panyi1981** [Lolliedieb/lolMiner-releases#1651]
I followed the wiki about **_Fix Clock Nvidia for Cuda by lolMiner (English)_**  and set --cclk XX & --mclk XX. It shows it core clock XX applied but actually it doesn't work. Please point out how to fix gpu clock on ubuntu,thanks a lot~~
OS:ubuntu22.04 
NvidiaDriver: 510.73.08 
GPU: 3080 10G LHR 
![snapshot2](https://user-images.githubusercontent.com/37579196/180008473-7a5665ce-aac7-49a8-91d5-9814e6ccf80b.png)

**Comment by mininggago** [comment]
> I followed the wiki about **_Fix Clock Nvidia for Cuda by lolMiner (English)_** and set --cclk XX & --mclk XX. It shows it core clock XX applied but actually it doesn't work. Please point out how to fix gpu clock on ubuntu,thanks a lot~~ OS:ubuntu22.04 NvidiaDriver: 510.73.08 GPU: 3080 10G LHR ![snapshot2](https://user-images.githubusercontent.com/37579196/180008473-7a5665ce-aac7-49a8-91d5-9814e6ccf80b.png)

That Clock was used for the old ALGO TON... lolMiner doesn't have Memory Clock for Nvidia sorry... you need use 3rd party Apps sorry

**Comment by jgonzis** [comment]
As comment the user he is right.
