### ISSUE TITLE
lolMiner 1.52b_2 eth/kas mode doesn't support solo kaspa mining.

### ISSUE THREAD

**Issue by eazytry** [Lolliedieb/lolMiner-releases#1653]
Hello!
When I try to run eth/kas with solo kaspa mode, I get infinity pool authorization  

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/40170333/180602112-d9cc6099-3ac5-49ad-bf00-31d88e142229.png">

**Comment by jgonzis** [comment]
> Hello! When I try to run eth/kas with solo kaspa mode, I get infinity pool authorization
> 
> <img alt="image" width="1149" src="https://user-images.githubusercontent.com/40170333/180602112-d9cc6099-3ac5-49ad-bf00-31d88e142229.png">

It seems solo is not working.
