### ISSUE TITLE
1.53 don't see KASPA in dual coin list

### ISSUE THREAD

**Issue by DmitryKoichev** [Lolliedieb/lolMiner-releases#1657]
<img width="509" alt="Screenshot 2022-07-29 at 13 01 53" src="https://user-images.githubusercontent.com/11480235/181754325-9255018f-ed3a-4556-8c98-301cb068ffdf.png">

I've selected KASPADUAL in lolMiner configuration 
but in dual coin list there is no KAS 

<img width="263" alt="Screenshot 2022-07-29 at 13 02 44" src="https://user-images.githubusercontent.com/11480235/181754454-8c8b7b15-cfa5-4113-af06-28f69142ae5b.png">
 
I've set all data manually to configuration: wallet, pool, port and looks like started to farm:

<img width="618" alt="Screenshot 2022-07-29 at 13 03 57" src="https://user-images.githubusercontent.com/11480235/181754633-800358cc-f4eb-4d84-a746-ee7014b029fe.png">

maybe I did something wrong that's why I don't see KAS in dual coin list ? or is it a bug ?

**Comment by jgonzis** [comment]
That was HiveOS fail... it should be updated since last test!!
