### ISSUE TITLE
Eth+Kaspa full node works?

### ISSUE THREAD

**Issue by Kostas-13** [Lolliedieb/lolMiner-releases#1659]
Just tried for the 1st time to mine Eth+Kaspa
Made a wallet with KDX win app. Then tried to mine it from my pc using the full node app.. but failed. xD 
If anyone have done it, pls share command parameters.

So I switched to the kaspa.acc-pool.pw everything works, using my old Eth-Ton settings kinda same values/results/temps/etc.

**Comment by jgonzis** [comment]
https://medium.com/@jgonzi/kaspa-mining-to-a-node-in-hiveos-79abe2c38961
