### ISSUE TITLE
Norton keeps removing lolminer.exe

### ISSUE THREAD

**Issue by jandeswart** [Lolliedieb/lolMiner-releases#1662]
I downloaded lolminer 1.53 windows x64 from github. After I unzipped the file, I could not find lolminer.exe in the folder. I then added it manually. But every time I run it (be it using the batch file, ore from the command prompt). Norton immediately removes it. I have googled how to get norton to not do that , but nothing works. Is it possible to run both lolminer and norton on a PC and if yes, please tell me how.

**Comment by jgonzis** [comment]
> I downloaded lolminer 1.53 windows x64 from github. After I unzipped the file, I could not find lolminer.exe in the folder. I then added it manually. But every time I run it (be it using the batch file, ore from the command prompt). Norton immediately removes it. I have googled how to get norton to not do that , but nothing works. Is it possible to run both lolminer and norton on a PC and if yes, please tell me how.

It is completely normal, it is detected as a miner, you should put in exclusion
