### ISSUE TITLE
No lhr unlock with 3080, or hashrate halved, after they were perfectly unlocked for months

### ISSUE THREAD

**Issue by GauchoBois** [Lolliedieb/lolMiner-releases#1663]
Hi,

I have two rigs with the same problem that started with no apparent reason. All of the boards where running perfectly unlocked until a couple of days in one rig and today in the second rig. Both rigs run on plain ubuntu 20.04 (no HiveOS) with kernel 5.4.0-53-generic and nvidia driver Nvidia 510.85.02. The rigs are:
rig1: with 2 Zotac 3080, 1 ASUS 3080, 1 Zotac 3080 ti, and 1 old MSI rx580 (amd). This frankenstein worked smoothly for about 3 months at 100% unlock. The Zotac 3080 mined around 103Mh/s just for reference and they now produce 55.6Mh/s even overclocked.
rig2: 6 Zotac 3080. Worked smoothly for about a month.

I'll try to describe now as much as I can the events in the correct order to try to see if somebody can help:
-started having ssd issues 2 days ago, recovered with fsck, then cloned just in case. Not sure now if the hashrate dropped before or after this. But only nvidia lhr cards have low hashrate, clear indication that it's a lhr unlock problem.
-still low hashrate despite miner shows lhr=100, so purged the driver, downgraded to 472.blabla with same result, back to 510, tried --LHR1, no overclocking nor power limitation, even removing the amd card... and nothing works.
-tried nbminer and t-rex with same low hashrate result
-tried the old phoenixminer I had and it starts mining at 100% (102Mh/s) for a while until lhr locks and reduces the hashrate (to 55Mh/s), as expected since it doesn't have lhr unlock.
-tried different issues in the xorg file and nothing worked.
-last try was to take the ssd from rig2, cloned it, reconnected the original ssd to rig2 and connected the cloned ssd to rig1... with same result...
-now BOTH RIGS HAVE LOW HASHRATE!!! It really amazes me, I don't think that the cloner could do something like this but maybe the reboot did to rig2 as well...
-obviously also tried with the newest version of lolminer without any success.

anyways, two different rigs, different card brands and models, all freaking locked. The boards don't look to get too hot either, all voltages from power supplies look are ok... 

Any ideas what could be wrong? I'm running out of ideas...

**Comment by mattiasminer** [comment]
Hi,
I am using Gminer on Ubuntu and have the same problem with hashrate halved on my two lhr cards.
I also tried NBMiner with same results.
For me it started yesterday with new updates for ubuntu and nvidia in the Software updater.
I have tried to change Nvidia drivers between 510 and 470 with no result.
I could also really use help with this.

**Comment by bjbschmitt** [comment]
I had the same problem, maybe NVIDIA added  some kind of new LHR lock to their new drivers 510.85.02 and 515.65.01 (tested both). A bit of waste of time, considering that the merge is coming in a couple of months.

Anyway, try to downgrade your driver to[ the 510.73.05 version](https://www.nvidia.com/Download/driverResults.aspx/188994/en-us/), it worked for me.

**Comment by GauchoBois** [comment]
ok, I found a solution but I don't fully understand what was wrong. I'm reporting what I did with the hope that somebody better debug the problem. 

I just came with the idea to clone the ssd from another old rig with 3070 (non-lhr) that was running with lolminer 1.46. Surprisingly, the miner tried to unlock the 3080s with some small percentage (as expected). Then just copied the lolminer 1.52a I had on it and started mining unlocked 100%!!! So, I thought that the old miner did some permanent unlocking again and tried it in the second buggy rig. The old miner was somehow partially unlocking the 3080s but then running the lolminer 1.53 or 1.52a didn't unlock them... So, just installing a second clone from the rig with the 3070s with the lolminer 1.52a worked well...

My conclusion (not sure if it is right) is that for some reason the new versions of lolminer somehow activate something in the driver that might be generating something somewhere hidden in a config file or whatever that I couldn't find (didn't looked too deep either)... that doesn't get erased when purging the driver, downgrading to 472, neither upgrading back to 510. The old version of lolminer 1.46 seems to be immune to this problem. 

I didn't try the solution from bjbschmitt unfortunately (I just saw it and I'm not at site now), but thanks very much though!!! If I find some time I'll try it in the next days.

Anyways, hope it helps. Thanks again to all of you.

**Comment by GauchoBois** [comment]
Last update... it just happened again last night! The lhr gets activated with no apparent reason with the configuration described in the previous comment. Tried the solution by bjbschmitt and it worked like a charm!!!

Just for the record, installing the .run nvidia driver from the link provided by bjbschmitt (https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/XFree86/Linux-x86_64/510.73.05/NVIDIA-Linux-x86_64-510.73.05.run&lang=us&type=TITAN) requires some tricks after purging the previous driver that I got from https://askubuntu.com/questions/149206/how-to-install-nvidia-run. Just ignore the warnings while installing the driver.

**Comment by jgonzis** [comment]
Completely normal 510.85 has block LHR... you must return to 510.73

**Comment by belgeran** [comment]
hi... just wanted to check if the latest releases support 515x?.. or 510.73 is still the preferred driver?

**Comment by jgonzis** [comment]
It should work with 515 too, but could not show memory tempa
