### ISSUE TITLE
Allocating buffers failed with: clCreateBuffer (-61)?

### ISSUE THREAD

**Issue by Merlingege** [Lolliedieb/lolMiner-releases#1664]

**Comment by jgonzis** [comment]
> _No description provided._

Could you share which AMD Drivees and GPU are you using?

**Comment by Merlingege** [comment]
![зображення_2022-08-14_163731021](https://user-images.githubusercontent.com/101415441/184539666-0043e974-e1d8-4f9d-9050-a13217f60c43.png)
![зображення_2022-08-14_163801054](https://user-images.githubusercontent.com/101415441/184539683-806006fe-c9c2-46fc-8fdf-02c9a74ec61d.png)

**Comment by jgonzis** [comment]
> ![зображення_2022-08-14_163731021](https://user-images.githubusercontent.com/101415441/184539666-0043e974-e1d8-4f9d-9050-a13217f60c43.png) ![зображення_2022-08-14_163801054](https://user-images.githubusercontent.com/101415441/184539683-806006fe-c9c2-46fc-8fdf-02c9a74ec61d.png)

Could it be AMD Drivers lastest version installed?. Could it be possible to try and old version like 21.5 or similar

**Comment by Merlingege** [comment]
I don't know if it is possible to install old versions, but I have the newest one
![зображення_2022-08-16_124419543](https://user-images.githubusercontent.com/101415441/184849557-4cedbc20-c7d7-438c-adfd-ecc548d8b3c1.png)

**Comment by jgonzis** [comment]
Try with older version it seems a driver issues

**Comment by Merlingege** [comment]
can you show me how to change to an older version?

**Comment by jgonzis** [comment]
Just download an older driver version from Internet and launch it

**Comment by Merlingege** [comment]
![зображення_2022-08-16_201733668](https://user-images.githubusercontent.com/101415441/184939757-5872006f-2f3c-426a-99cd-6a2ad2118c7d.png)
![зображення_2022-08-16_201800245](https://user-images.githubusercontent.com/101415441/184939839-d4d2cfae-aded-4e97-a35c-5d6659244c49.png)
I installed the older one, but the result is the same.

**Comment by jgonzis** [comment]
Could you show then full configuration bat file... let's try to have more
information

**Comment by Merlingege** [comment]
![зображення_2022-08-16_223124957](https://user-images.githubusercontent.com/101415441/184966040-e1603015-a794-46b4-aba4-a457d8fa40a9.png)

**Comment by jgonzis** [comment]
It is impossible to mine ethash with 4Gb GPU, that is the problem

**Comment by Merlingege** [comment]
Thanks for the help with the problem (info).
