### ISSUE TITLE
Error when allocating memory or building DAG

### ISSUE THREAD

**Issue by az-lag** [Lolliedieb/lolMiner-releases#1667]
Hi, new here. My rig has been working great for months until this past weekend. now when I start the 1hr admin ETH miner it gives me the following error for all 3 of my GPUs (2x 3060, 1x 3080ti)   "Error when allocating memory or building DAG. Disabling cards. 

can someone tell me what this means? are my cards too small to mine ETH now? 

Please advise.  
Thank you

**Comment by jgonzis** [comment]
> Hi, new here. My rig has been working great for months until this past weekend. now when I start the 1hr admin ETH miner it gives me the following error for all 3 of my GPUs (2x 3060, 1x 3080ti) "Error when allocating memory or building DAG. Disabling cards.
> 
> can someone tell me what this means? are my cards too small to mine ETH now?
> 
> Please advise. Thank you

In Windows that normally is Memory Virtual... that should be increased... (Pagefile.sys need to have more space). That doesn’t happen in Linux
