### ISSUE TITLE
Problem in loading Kernal

### ISSUE THREAD

**Issue by dbaca19** [Lolliedieb/lolMiner-releases#167]
Hi! I have an old GTX 760 4GB sitting around and I wanted to see if I could get it running with lolMiner to mine ETH, but when I load up the file it throws an error saying "Problem in loading Kernal." 

I tried adjusting the memory settings, but I still can't get it to work. Anyone have a solution?

**Comment by jgonzis** [comment]
> Hi! I have an old GTX 760 4GB sitting around and I wanted to see if I could get it running with lolMiner to mine ETH, but when I load up the file it throws an error saying "Problem in loading Kernal."
> 
> I tried adjusting the memory settings, but I still can't get it to work. Anyone have a solution?

YOu can only  mine now ETC... ETH is not possible in Windows now with the 4Gb card...

**Comment by rpraveenjitcs** [comment]
Hi...
I am also having GTX 760 4GB 
I modified the batch last line as below for mining ET. But I still get an error saying "Problem in loading Kernal."
lolMiner.exe --algo ETCHASH --pool !POOL! --user !WALLET! --keepfree 40 --4g-alloc-size 3968

Can someone please help me on this.

**Comment by jgonzis** [comment]
> Hi...
> I am also having GTX 760 4GB
> I modified the batch last line as below for mining ET. But I still get an error saying "Problem in loading Kernal."
> lolMiner.exe --algo ETCHASH --pool !POOL! --user !WALLET! --keepfree 40 --4g-alloc-size 3968
> 
> Can someone please help me on this.
Mining ETC you don't need --keepfree 40 --4g-alloc-size 3968... that was used for ETH...

**Comment by jgonzis** [comment]
It is too old GPU, try new 1.28a with new Kernel if they are supported and try ETC for the limit of Memory of the GPU
