### ISSUE TITLE
lolminer 1.54 ETH/KASPA Dual Mining Error

### ISSUE THREAD

**Issue by Fantafisch** [Lolliedieb/lolMiner-releases#1673]
Hi,

Dual Mining (ETH/KASPA) with lolminer 1.54 (using it at HiveOS) is still not possible. It starts ETH first then after a few seconds (about 30) KASPA mining starts too. At this point I get Hashrates for both Algo´s but when lolminer returns: "Tuning for dual mining completed" then KASPA Hashrate falls down to 0 MH/s and remains there. From this point I can see that there are no more hashes sent to pool.

lolminer out is something like that:

Ethash: Average speed (10s): 44.22 Mh/s | 44.54 Mh/s | 44.49 Mh/s | 44.50 Mh/s | 44.21 Mh/s Total: 221.96 Mh/s
HeavyHash-Kaspa: Average speed (10s): 38.81 Mh/s | 33.21 Mh/s | 37.83 Mh/s | 37.83 Mh/s | 44.95 Mh/s Total: 192.62 Mh/s

GPU 1: Tuning for dual mining completed.
GPU 0: Tuning for dual mining completed.
GPU 2: Tuning for dual mining completed.
New job received: 000000003a6de2ec Epoch: 510 Difficulty: 2.86G
New job received: 000000003a6de2ed Epoch: 510 Difficulty: 2.86G
GPU 3: Tuning for dual mining completed.
GPU 4: Tuning for dual mining completed.

Ethash: Average speed (10s): 48.28 Mh/s | 48.32 Mh/s | 48.20 Mh/s | 48.27 Mh/s | 48.32 Mh/s Total: 241.39 Mh/s
HeavyHash-Kaspa: Average speed (10s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s

Thanks for checking

**Comment by prodchia** [comment]
I can't seem to get the dual mining work on windows. I have a couple of 3060 LHR v2. I am using dual_mine_eth_kaspa.bat

**Comment by Kostas-13** [comment]
I think I saw that issue on windows when I 1st started to tweak my gpus.. check yr overclocks maybe.
Seems like it starts and they are power limited. =>1st raise yr TDP limit. +or Lock core as well +or lock vcore as well step by step.

**Comment by jgonzis** [comment]
> Hi,
> 
> Dual Mining (ETH/KASPA) with lolminer 1.54 (using it at HiveOS) is still not possible. It starts ETH first then after a few seconds (about 30) KASPA mining starts too. At this point I get Hashrates for both Algo´s but when lolminer returns: "Tuning for dual mining completed" then KASPA Hashrate falls down to 0 MH/s and remains there. From this point I can see that there are no more hashes sent to pool.
> 
> lolminer out is something like that:
> 
> Ethash: Average speed (10s): 44.22 Mh/s | 44.54 Mh/s | 44.49 Mh/s | 44.50 Mh/s | 44.21 Mh/s Total: 221.96 Mh/s HeavyHash-Kaspa: Average speed (10s): 38.81 Mh/s | 33.21 Mh/s | 37.83 Mh/s | 37.83 Mh/s | 44.95 Mh/s Total: 192.62 Mh/s
> 
> GPU 1: Tuning for dual mining completed. GPU 0: Tuning for dual mining completed. GPU 2: Tuning for dual mining completed. New job received: 000000003a6de2ec Epoch: 510 Difficulty: 2.86G New job received: 000000003a6de2ed Epoch: 510 Difficulty: 2.86G GPU 3: Tuning for dual mining completed. GPU 4: Tuning for dual mining completed.
> 
> Ethash: Average speed (10s): 48.28 Mh/s | 48.32 Mh/s | 48.20 Mh/s | 48.27 Mh/s | 48.32 Mh/s Total: 241.39 Mh/s HeavyHash-Kaspa: Average speed (10s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
> 
> Thanks for checking

That happens because you are not connected to a Kaspa Pool. When it should get jobs after tunning, that is because you are not connect. Normally error is you didn't put kaspa:xxxx just only xxxx

**Comment by Fantafisch** [comment]
> > Hi,
> > Dual Mining (ETH/KASPA) with lolminer 1.54 (using it at HiveOS) is still not possible. It starts ETH first then after a few seconds (about 30) KASPA mining starts too. At this point I get Hashrates for both Algo´s but when lolminer returns: "Tuning for dual mining completed" then KASPA Hashrate falls down to 0 MH/s and remains there. From this point I can see that there are no more hashes sent to pool.
> > lolminer out is something like that:
> > Ethash: Average speed (10s): 44.22 Mh/s | 44.54 Mh/s | 44.49 Mh/s | 44.50 Mh/s | 44.21 Mh/s Total: 221.96 Mh/s HeavyHash-Kaspa: Average speed (10s): 38.81 Mh/s | 33.21 Mh/s | 37.83 Mh/s | 37.83 Mh/s | 44.95 Mh/s Total: 192.62 Mh/s
> > GPU 1: Tuning for dual mining completed. GPU 0: Tuning for dual mining completed. GPU 2: Tuning for dual mining completed. New job received: 000000003a6de2ec Epoch: 510 Difficulty: 2.86G New job received: 000000003a6de2ed Epoch: 510 Difficulty: 2.86G GPU 3: Tuning for dual mining completed. GPU 4: Tuning for dual mining completed.
> > Ethash: Average speed (10s): 48.28 Mh/s | 48.32 Mh/s | 48.20 Mh/s | 48.27 Mh/s | 48.32 Mh/s Total: 241.39 Mh/s HeavyHash-Kaspa: Average speed (10s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
> > Thanks for checking
> 
> That happens because you are not connected to a Kaspa Pool. When it should get jobs after tunning, that is because you are not connect. Normally error is you didn't put kaspa:xxxx just only xxxx

Thx. That was the solution. I´ve forget to set kaspa:xxx at wallet address. Now it´s working.

**Comment by ilovesushi** [comment]
Hi. tried this config in a rig with a mix of 4 cards. the first 3080ti lhr colorful behaves the same it drops kspa rate to 0, other cards provide ethash+kaspa both

**Comment by jgonzis** [comment]
> Hi. tried this config in a rig with a mix of 4 cards. the first 3080ti lhr colorful behaves the same it drops kspa rate to 0, other cards provide ethash+kaspa both

That could be a problem in the server of the Kaspa Pool... which type of connection do you have?
