### ISSUE TITLE
Low hash rate for 3070 LHR on Ubuntu 

### ISSUE THREAD

**Issue by LulaSvob** [Lolliedieb/lolMiner-releases#1677]
Hi, 
Using either drivers 510.85 or 470.141.03 I get the following more or less same hash rate even when waiting for a long time: 

![image](https://user-images.githubusercontent.com/32610546/185549236-b12cfd69-d988-406c-b818-fb93f3d8d4ae.png)

What can be the problem as I see that you have enabled also the 470 drivers for unlocking LHR?

**Comment by jgonzis** [comment]
It is completely right, Nvidia has blocked another time the driver in last release use 470.129 or 510.73

**Comment by LulaSvob** [comment]
@jgonzis and do you happen to know a way to use a 510.65 driver on Ubuntu? Because I can't really find any references how to install it back after being forced to a newer version.

**Comment by jgonzis** [comment]
Directly install the previous driver that is all you need

**Comment by LulaSvob** [comment]
Definitely easier said than done. It took me quite some time to figure out how to do exactly what you suggest and the only method that worked is Option 2 from this link: https://www.linuxcapable.com/install-nvidia-510-47-xx-drivers-on-ubuntu-20-04-lts/ 

Thanks a lot for your time. Appreciated.

**Comment by jgonzis** [comment]
> Definitely easier said than done. It took me quite some time to figure out how to do exactly what you suggest and the only method that worked is Option 2 from this link: https://www.linuxcapable.com/install-nvidia-510-47-xx-drivers-on-ubuntu-20-04-lts/
> 
> Thanks a lot for your time. Appreciated.

In miming OS it is really easy they have the function, but normally was sh driver.xxx.sh 

Enjoy now the mining

**Comment by LulaSvob** [comment]
Yes, now I know. My problem was obtaining the actual drivers since ```sudo apt search``` was returning only drivers that didn't work. I downloaded the driver from nvidia's site and it worked.
