### ISSUE TITLE
Add Iterations/Sec to Console Output for Equihash Family Algorithms

### ISSUE THREAD

**Issue by rpringst** [Lolliedieb/lolMiner-releases#1679]
Due to the nature of the Generalized Birthday Problem at the heart of the Equihash family algorithms, may we please have Iterations/s in addition to Solutions/s logged in the console output when mining these algorithms? Thank you in advance!

**Comment by jgonzis** [comment]
> Due to the nature of the Generalized Birthday Problem at the heart of the Equihash family algorithms, may we please have Iterations/s in addition to Solutions/s logged in the console output when mining these algorithms? Thank you in advance!

That is a nice idea... It will be added why not in next release
