### ISSUE TITLE
Autolykos + Kaspa before Merge. SRBminer already has it on AMD. Team green doesn't have it yet ;)

### ISSUE THREAD

**Issue by ltwarrior18** [Lolliedieb/lolMiner-releases#1681]
Hello we need new version of lolminer. To switch to ergo + Kaspa mining before merge on Nvidia cards.  Some people will split to ETC, and some with AMD will go to ergo + Kaspa.
1.54 version was superb, but sadly Merge is on doorsteps. I feel like I am forced to mine ETC with Kaspa, when I would love to mine Ergo + Kaspa. Either I will need to buy amd GPU's or hopefully wait for new lol version.

Also remember that ETC will be ASIC minable, so people who will be switching to ETC + Kaspa will be at huge risk or simply won;t mine this option and go mine something else. But Ergo + Kaspa is a great niche offcourse for our favorite miner - lolminer!

**Comment by jgonzis** [comment]
Problem is the lost of Ergo more than 10%... but it will sure be analysed if Kaspa Price remains at this price.
