### ISSUE TITLE
Discord Link Not Working

### ISSUE THREAD

**Issue by airj1012** [Lolliedieb/lolMiner-releases#1684]
Invite is invalid.

![image](https://user-images.githubusercontent.com/64874325/186686371-16490f51-3a71-4b17-80ae-a6eb58858540.png)

![image](https://user-images.githubusercontent.com/64874325/186686463-dcd75e86-d6a0-402f-abf0-34088ddda3d9.png)

**Comment by jgonzis** [comment]
Now it should work:

https://discord.gg/zypMYNbJ5k

We put a never expired link now. Thx for the comment.
