### ISSUE TITLE
1.54 not so good on kaspa but awesome on alephium

### ISSUE THREAD

**Issue by dastardlyman12** [Lolliedieb/lolMiner-releases#1686]
all my rx5700s do really well on eth plus alph or eth classic plus alph they get basically the same eth hashrate as TRM when its just mining ETh alone. im running windows 10.  its really good.  but eth plus kaspa gets significantly less eth hashrate even though kaspa dual mining with eth doesnt seem to hit the gpu with much power requirement. its weird less power overall should mean more eth. to me it looks like you have hit the coding jackpot with eth plus alph. and for that i thank you.  we have a stack of old polaris and this weirdness doesnt seem to apply to them. best wishes and thank you doctor.

**Comment by jgonzis** [comment]
> all my rx5700s do really well on eth plus alph or eth classic plus alph they get basically the same eth hashrate as TRM when its just mining ETh alone. im running windows 10. its really good. but eth plus kaspa gets significantly less eth hashrate even though kaspa dual mining with eth doesnt seem to hit the gpu with much power requirement. its weird less power overall should mean more eth. to me it looks like you have hit the coding jackpot with eth plus alph. and for that i thank you. we have a stack of old polaris and this weirdness doesnt seem to apply to them. best wishes and thank you doctor.

That could be the OC, or.try the --dualfactor value. It hasn't need to lost less than 1% in ETH
