### ISSUE TITLE
1.55 not mining ERGO anymore

### ISSUE THREAD

**Issue by Faugus** [Lolliedieb/lolMiner-releases#1687]
The miner just quit after detecting GPUS.
On 1.54 it runs fine.
I'm on Windows.
The log file is blank.

lolMiner.exe -a AUTOLYKOS2 -p ergo-us-east1.nanopool.org:11111 -u MY_WALLET --devices 0,1

**Comment by jgonzis** [comment]
Many thanks, completely right, failing in Windows and Linux in some rigs... Dev working on it.

**Comment by jgonzis** [comment]
> The miner just quit after detecting GPUS. On 1.54 it runs fine. I'm on Windows. The log file is blank.
> 
> lolMiner.exe -a AUTOLYKOS2 -p ergo-us-east1.nanopool.org:11111 -u MY_WALLET --devices 0,1

Solved in 1.55a

**Comment by Faugus** [comment]
Waiting for the 1.55a Windows build
