### ISSUE TITLE
Feature Request: Is it possible to add additional GPU setting values to GPU section of API object?

### ISSUE THREAD

**Issue by stevepresley** [Lolliedieb/lolMiner-releases#169]
You already have Fan Speed and actual Temp and Wattage. Wondering if these extra values are available.

I'd like to see:
Core Voltage
Power Limit (%)
Temp Limit (%)
Core Clock (MHz) and/or +/- value
Memory Clock (MHz) and/or +/- value

**Comment by clamatac** [comment]
+1 sounds good to me

**Comment by jgonzis** [comment]
All this new information show in new extended stats
