### ISSUE TITLE
Invalid FLUX shares on AMD using version 1.55

### ISSUE THREAD

**Issue by innovative-sol** [Lolliedieb/lolMiner-releases#1690]
Version 1.55. After a few minutes of mining FLUX on a Radeon 480 the speed got from 15 sol/s to more than 30.000 sol/s and only invalid shares were produced. The driver never recovered.

**Comment by innovative-sol** [comment]
Statistics (09:57:19); Uptime: 0h 10m 21s
lolMiner 1.55, Nvidia 512.15, AMD CL 3444.0
Mining: ZelHash
Connected to: 88.198.11.177:55496 (23ms latency)

      Name           Speed      Pool    Iter.  Shares    Best     Eff.  Power  CCLK  MCLK  Core  Junc  Fan
                     sol/s     sol/s     it/s     A/R   Share  sol/s/W      W   MHz   MHz  Temp  Temp  Pct
GPU 0 RX 480 Grap 24666.42  14506.67  6166.60  1/1034  158.9M  574.988   42.9     0     0    51   N/A   34
GPU 1 GTX 1080 Ti    15.54      0.00     7.85     0/0     0.0      N/A    N/A   734   810    56    70   33
GPU 2 GTX 1080 Ti    16.01     56.06     7.86     4/0   42.6K      N/A    N/A   746   810    55    69   34
---------------------------
Total             24697.96  14562.73  6182.31  5/1034  158.9M  575.723   42.9
-----------------------------------------------
GPU 0: Found a share of difficulty 73.9k
GPU 0: Share is invalid or stale (23 ms)
Average speed (10s): 46927.69 sol/s | 31.56 sol/s | 30.16 sol/s Total: 46989.41 sol/s
GPU 0: Found a share of difficulty 13.9k
GPU 0: Found a share of difficulty 12.4k
GPU 0: Found a share of difficulty 9.5k
GPU 0: Share is invalid or stale (2 ms)
GPU 0: Share is invalid or stale (24 ms)
GPU 0: Share is invalid or stale (24 ms)

**Comment by jgonzis** [comment]
That is an AMD Driver issues... which version of AMD are you using please?

**Comment by innovative-sol** [comment]
Name:    Radeon (TM) RX 480 Graphics
Address: 1:0
Vendor:  Advanced Micro Devices (AMD)
Drivers: OpenCL
Memory:  8192 MByte (8128 MByte free)

Driver version: 31.0.12019.9007
Driver date: 19-Aug-22

**Comment by jgonzis** [comment]
> Name: Radeon (TM) RX 480 Graphics Address: 1:0 Vendor: Advanced Micro Devices (AMD) Drivers: OpenCL Memory: 8192 MByte (8128 MByte free)
> 
> Driver version: 31.0.12019.9007 Driver date: 19-Aug-22

Could you try and older Driver please?. something like 20.x or similar please?. Could it be a mod in the driver in last release

**Comment by innovative-sol** [comment]
I will a bit later. I have to rollback and right now I'm atr work...

**Comment by jgonzis** [comment]
Did it work?. Also another question. Hat 1.54 same problems?

**Comment by innovative-sol** [comment]
Unfortunately it doesn't work on older driver releases either. 1.55 seems better than 1.54 - which crashes immediately. Sorry for the bad news.

**Comment by jgonzis** [comment]
> Unfortunately it doesn't work on older driver releases either. 1.55 seems better than 1.54 - which crashes immediately. Sorry for the bad news.

In our test is working. Could you increase Core Voltage of that Polaris please?. Could it be it crashes the GPU for too much lower OC. Many thanks

**Comment by ngiotta** [comment]
I can confirm.  v1.55 is almost an instant crash for my RX580/RX5700 mixed rig on FLUX.

**Comment by jgonzis** [comment]
> I can confirm. v1.55 is almost an instant crash for my RX580/RX5700 mixed rig on FLUX.

Which Drivers and OC are you using?. The OC OF ethereum will not work for Flux

**Comment by ngiotta** [comment]
> > I can confirm. v1.55 is almost an instant crash for my RX580/RX5700 mixed rig on FLUX.
> 
> Which Drivers and OC are you using?. The OC OF ethereum will not work for Flux

I'm not sure how to check that.  I'm using RaveOS Build 8795.  

I've got an Equihash 125,4 tune running on it with increased core clock / core voltage, and decreased mem clock.  Same tune runs fine on v1.53b3.

**Comment by jgonzis** [comment]
> 

Try with higher Core Voltage, now more need it and share both miner logs if you can please 1.53 and the 1.54 that will help us more information.   Remember is giving more Hashrate now. Which GPUs crashes you in 1.55?

**Comment by ngiotta** [comment]
Sorry, I'm not a Linux guy, so I don't know how to pull the logs.  What I can tell you is that It's various RX580s that are dying.  Upped the core voltage just now from 900 to 925  Still died.  Not sure I want to up the core any higher than that.

**Comment by jgonzis** [comment]
> Sorry, I'm not a Linux guy, so I don't know how to pull the logs. What I can tell you is that It's various RX580s that are dying. Upped the core voltage just now from 900 to 925 Still died. Not sure I want to up the core any higher than that.

Only Polaris?... try more higher Core Voltage. A screenshot of the miner stats or the crash is the useful information. If you comment is so fast with the miner console will be easy to have it. Many thanks in advance

**Comment by ngiotta** [comment]
![screenshot-shell raveos com-2022 09 04-00_04_00](https://user-images.githubusercontent.com/2933262/188301730-eb9b076a-ee2a-452b-912a-abd982efa8c8.png)

So far it has only been Polaris.  Core voltage at 940mv for the last crash.

**Comment by jgonzis** [comment]
Many thanks... Can I request you a pair more test? 

If only 5700 XT is stable and Polaris without Core Voltage just free of use. I have just send that photo directly to developer too.

Many thanks in advance

**Comment by ngiotta** [comment]
I removed the core voltage values for the Polaris cards and that seemed to make it stable.  

5 RX-580s
4 RX-5700s
-------------
lolminer v1.55 5m Avg: 177 sol/s
lolminer v1.53b3 5m Avg: 175 sol/s

**Comment by jgonzis** [comment]
> I removed the core voltage values for the Polaris cards and that seemed to make it stable.
> 
> ## 5 RX-580s
> 4 RX-5700s
> lolminer v1.55 5m Avg: 177 sol/s lolminer v1.53b3 5m Avg: 175 sol/s

The 5700 have to make more... it could be an up/down moment that Mhs.
