### ISSUE TITLE
ERG mining not functional in version 1.55

### ISSUE THREAD

**Issue by innovative-sol** [Lolliedieb/lolMiner-releases#1692]
ERG mining is not working even using the BAT file from the archive. It crashes just after starting. Version 1.54 was working ok.

**Comment by jgonzis** [comment]
> ERG mining is not working even using the BAT file from the archive. It crashes just after starting. Version 1.54 was working ok.

Many thanks, completely right, failing in Windows and Linux in some rigs... Dev working on it.

**Comment by jgonzis** [comment]
New release 1.55a has solved that crash in some rigs.

**Comment by innovative-sol** [comment]
> New release 1.55a has solved that crash in some rigs.

Will there be a a version 1.55a for Windows as well?
