### ISSUE TITLE
1.55 many Share is invalid or stale

### ISSUE THREAD

**Issue by standula** [Lolliedieb/lolMiner-releases#1695]
Hi, in 1.55,

HeavyHash-Kaspa: GPU 9: Share is invalid or stale (18 ms)

New job received: 0x1d0a45 Epoch: 528 (ETCHash epoch: 264) Difficulty: 4.29G
HeavyHash-Kaspa: GPU 2: Share is invalid or stale (9 ms)
Etchash: GPU 4: Share accepted (9 ms)
**HeavyHash-Kaspa: GPU 9: Share is invalid or stale (18 ms)
HeavyHash-Kaspa: GPU 3: Share is invalid or stale (18 ms)
Etchash: GPU 3: Share accepted (18 ms)
HeavyHash-Kaspa: GPU 7: Share accepted (37 ms)
HeavyHash-Kaspa: GPU 1: Share is invalid or stale (37 ms)**
-----------------------------------------------
Statistics (18:31:05); Uptime: 0h 36m 4s
lolMiner 1.55, Nvidia 510.60.02, AMD CL 3180.7

**Comment by jgonzis** [comment]
> Hi, in 1.55,
> 
> HeavyHash-Kaspa: GPU 9: Share is invalid or stale (18 ms)
> 
> ## New job received: 0x1d0a45 Epoch: 528 (ETCHash epoch: 264) Difficulty: 4.29G
> HeavyHash-Kaspa: GPU 2: Share is invalid or stale (9 ms)
> Etchash: GPU 4: Share accepted (9 ms)
> **HeavyHash-Kaspa: GPU 9: Share is invalid or stale (18 ms) HeavyHash-Kaspa: GPU 3: Share is invalid or stale (18 ms) Etchash: GPU 3: Share accepted (18 ms) HeavyHash-Kaspa: GPU 7: Share accepted (37 ms) HeavyHash-Kaspa: GPU 1: Share is invalid or stale (37 ms)**
> Statistics (18:31:05); Uptime: 0h 36m 4s lolMiner 1.55, Nvidia 510.60.02, AMD CL 3180.7

You need to update to never AMD drivers...  that is really old the 3180. Could you please update your rig to mining 20.x AMD Drivers?

**Comment by standula** [comment]
Hi, it is latest hive os  version

 Current version: 0.6-219@220828

One week old installation

**Comment by jgonzis** [comment]
> Hi, it is latest hive os version
> 
> Current version: 0.6-219@220828
> 
> One week old installation

Not hiveOS installation... your Kernel is the old one with very old AMD Drivers... you are not in 20.40 AMD Drivers
