### ISSUE TITLE
1.55, ERG, crashed

### ISSUE THREAD

**Issue by EasyDing** [Lolliedieb/lolMiner-releases#1696]
![image](https://user-images.githubusercontent.com/5654052/188399641-15e87fa7-9a8a-4706-a566-0a848df28a75.png)

**Comment by UselessGuru** [comment]
Duplicate:
https://github.com/Lolliedieb/lolMiner-releases/issues/1692

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/5654052/188399641-15e87fa7-9a8a-4706-a566-0a848df28a75.png)

That is too much OC in GPU1 problem. Also new 1.55a should help in improvement.

**Comment by EasyDing** [comment]
I have no problem using other mining tools with the same overclocking parameters。
win11 + 1.55a

**Comment by EasyDing** [comment]
![image](https://user-images.githubusercontent.com/5654052/188420797-e62046a8-b702-4712-acee-eb234e000eba.png)
win11

**Comment by EasyDing** [comment]
![image](https://user-images.githubusercontent.com/5654052/188527174-e6e11d4e-c021-423a-ad02-d0c9deb451f9.png)
I have no problem use this oc with other tools. thanks
