### ISSUE TITLE
lolminer fails to progress beyond GPU detection

### ISSUE THREAD

**Issue by jsarich** [Lolliedieb/lolMiner-releases#1697]
Attempting to mine ERGO on a 3080 installed (512.15 firmware) in a windows 10 box with a radeon GPU, I receive no indication of a problem, but the program ends shortly after identifying GPUs.  

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 3
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    Radeon RX Vega M GH Graphics
    Address: 1:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  4096 MByte (4041 MByte free)
    Active:  false (not selected)
Device 1:
    Name:    Radeon RX Vega M GH Graphics
    Address: 1:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  4096 MByte (4041 MByte free)
    Active:  false (not selected)
Device 2:
    Name:    NVIDIA GeForce RTX 3080
    Address: 12:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  10239 MByte

C:\Users\Intel\Downloads\lolminer-1.55>

The other thing I find strange is that when attempting to do something as simple as --list-devices, it kicks off an endless thread loop:
Creator 580 started
Thread 580 done 1
Thread 580 done 2
Thread 580 done 3
Thread 580 done 4....to 8xx followed by a bunch of hex information, then repeats for 581 and so on.

Is there someplace that can help me understand what the problem is?

**Comment by jgonzis** [comment]
> Attempting to mine ERGO on a 3080 installed (512.15 firmware) in a windows 10 box with a radeon GPU, I receive no indication of a problem, but the program ends shortly after identifying GPUs.
> 
> Setup Miner... OpenCL driver detected. Number of OpenCL supported GPUs: 3 Cuda driver detected. Number of Cuda supported GPUs: 1 Device 0: Name: Radeon RX Vega M GH Graphics Address: 1:0 Vendor: Advanced Micro Devices (AMD) Drivers: OpenCL Memory: 4096 MByte (4041 MByte free) Active: false (not selected) Device 1: Name: Radeon RX Vega M GH Graphics Address: 1:0 Vendor: Advanced Micro Devices (AMD) Drivers: OpenCL Memory: 4096 MByte (4041 MByte free) Active: false (not selected) Device 2: Name: NVIDIA GeForce RTX 3080 Address: 12:0 Vendor: NVIDIA Corporation Drivers: Cuda Memory: 10239 MByte
> 
> C:\Users\Intel\Downloads\lolminer-1.55>
> 
> The other thing I find strange is that when attempting to do something as simple as --list-devices, it kicks off an endless thread loop: Creator 580 started Thread 580 done 1 Thread 580 done 2 Thread 580 done 3 Thread 580 done 4....to 8xx followed by a bunch of hex information, then repeats for 581 and so on.
> 
> Is there someplace that can help me understand what the problem is?

Please for ERGO, use 1.54 meanwhile 1.55a is not compiled
