### ISSUE TITLE
allow "pers" option

### ISSUE THREAD

**Issue by tripleyouwu** [Lolliedieb/lolMiner-releases#17]
the "pers" option is unavailable and causes rejected shares with some coins, this config option would be great!
Specifically referring to Ycash, its "ZcashPoW" and 192_7 and no way to specify it as such so at the very least a coin profile of that type would suffice, THX!

ok figured out the overwritepersonal but a ycash profile would be good too (sorry)

**Comment by autotunafish** [comment]
Mining ycash with this Miner still requires the overwrite personal parameter which is okay but a separate problem is that it will not parse notify correctly from Luxor.tech which passes in extra parameter along which lolmner is unable to correctly handle

**Comment by autotunafish** [comment]
After that should this issue because I can't change the title and is now inaccurate

**Comment by autotunafish** [comment]
Also apparently I have 2 github profiles

**Comment by Lolliedieb** [comment]
Sorry for late reply, but YCash worked with AUTO192_7 and --overwritePersonal option (see manual :) )
