### ISSUE TITLE
No active Card

### ISSUE THREAD

**Issue by standula** [Lolliedieb/lolMiner-releases#1700]
Hi, 
i have inactive card in debian. OpenCL is visible, but no cards active:

Setup Miner... 
GPU Health check failed for program build.
GPU Health check failed for create kernel build.
GPU Health check failed for enqueue kernel.
OpenCL driver detected.
Number of OpenCL supported GPUs: 1 
No Cuda driver or GPUs detected. 
Device 0: 
    Name:    AMD Radeon RX 6700 XT (navi22, LLVM 14.0.6, DRM 3.47, 5.19.0-1-amd64) 
    Address: 4294967295:4294967295 
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  12288 MByte 
    Active:  false (not selected)

Thanks

**Comment by jgonzis** [comment]
No more Feedback
