### ISSUE TITLE
No Cuda driver or GPUs detected

### ISSUE THREAD

**Issue by f2miner** [Lolliedieb/lolMiner-releases#1701]
tried running lolminer on archlinux using: 
`lolminer -a ETHASH -p eth.f2pool.com:6688 -u f2four20.20rig`

got back:
```
Setup Miner... 
OpenCL driver detected.
Number of OpenCL supported GPUs: 1 
No Cuda driver or GPUs detected. 
Device 0: 
    Name:     
    Address: 6:0 
    Vendor:  Advanced Micro Devices (AMD), ROCm
    Drivers: OpenCL
    Memory:  512 MByte (512 MByte free) 
    Active:  false (Unsupported device or driver version.) 

Connecting to pool... 
DNS over HTTPS resolve failed - switching to standard resolve 
Connected to eth.f2pool.com(2606:4700:90:0:4fb:aeec:54b4:a3ad):6688  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: f2four20.20rig Worker:20rig 
New job received: 0xa67714 Epoch: 516 Difficulty: 8.59G 
Start Mining... 
All devices deselected or failed compatiblity check. Closing lolMiner
```

I don't have a specialized rig and am trying to use my laptop when it's not being used. here are some stats:
```
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz 
GPU: AMD ATI 06:00.0 Renoir 
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M 
Memory: 2561MiB / 7313MiB
```

I also have 8Gib of ram with 4Gib of swap if that´s any useful

**Comment by jgonzis** [comment]
> tried running lolminer on archlinux using: `lolminer -a ETHASH -p eth.f2pool.com:6688 -u f2four20.20rig`
> 
> got back:
> 
> ```
> Setup Miner... 
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 1 
> No Cuda driver or GPUs detected. 
> Device 0: 
>     Name:     
>     Address: 6:0 
>     Vendor:  Advanced Micro Devices (AMD), ROCm
>     Drivers: OpenCL
>     Memory:  512 MByte (512 MByte free) 
>     Active:  false (Unsupported device or driver version.) 
> 
> Connecting to pool... 
> DNS over HTTPS resolve failed - switching to standard resolve 
> Connected to eth.f2pool.com(2606:4700:90:0:4fb:aeec:54b4:a3ad):6688  (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Authorized worker: f2four20.20rig Worker:20rig 
> New job received: 0xa67714 Epoch: 516 Difficulty: 8.59G 
> Start Mining... 
> All devices deselected or failed compatiblity check. Closing lolMiner
> ```
> 
> I don't have a specialized rig and am trying to use my laptop when it's not being used. here are some stats:
> 
> ```
> CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz 
> GPU: AMD ATI 06:00.0 Renoir 
> GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M 
> Memory: 2561MiB / 7313MiB
> ```
> 
> I also have 8Gib of ram with 4Gib of swap if that´s any useful

Integrated GPU in CPU are not possible to be used to mine.
