### ISSUE TITLE
help i want to use this software but i get error on my r5 m330

### ISSUE THREAD

**Issue by aprenminer** [Lolliedieb/lolMiner-releases#1703]
help i just want to mine some coins with my only graphics card. just extract a little I know that my graphics card is a waste of time but I don't have money to buy something better.
Please help, I don't know who else to ask for this, everyone recommends that I buy something better, but the truth is that I don't have the money to do it. I just want to extract some algorithms. i wanted to try to use my card in bitcoin but it would be crazy but algorithms not supported for asic equipment is a bit possible i wouldn't mind just extracting very few fractions some fractions would still be profitable for me

**Comment by jgonzis** [comment]
You cannot mine with a integrated GPU. You need a dedicated

**Comment by aprenminer** [comment]
> No puedes minar con una GPU integrada. Necesitas un dedicado



> No puedes minar con una GPU integrada. necesita un dedicado

it is a dedicated card. I have 2 graphics cards, an intel which is the one that comes standard with the processor and the 2gb r5. I admit that the r5 is not powerful but I do not have money to buy an rx 580 or more powerful it is much better to use this card than to have it mining bitcoin.
I don't understand why lolminer is not supported. I promise to pay the fees for using lolminer if the developer add it to the lolminer list.
I would just like to mine coins from an ASIC resistant algorithm
