### ISSUE TITLE
lolMiner 1.56, lower hashrate

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#1704]
I don't fully sure but I see HR downgrade on ETH, 3060 after upgrade from 1.55a to 1.56 (1/3 less like before) - i seen it after few hours mining.

**Comment by jgonzis** [comment]
> I don't fully sure but I see HR downgrade on ETH, 3060 after upgrade from 1.55a to 1.56 (1/3 less like before) - i seen it after few hours mining.

Could you share some pictures?. and be sure you have redownload last version?

**Comment by dawidmosk** [comment]
[](url)Yes sure... I wrote issue after few hours after change of version (I was busy). Normally always I'm waiting 30-60 minutes but now it was maybe 4-5 hours. Now for making picture i did picture before change and i changed from 1.55a to 1.56, few minutes - slow HR- picture again, switch back to 1.55a and needed few seconds to HR normally back - [picture.](url)
![a1 55a](https://user-images.githubusercontent.com/60958552/190039983-27ddcda9-2e60-4ae8-afa0-b6ce9da0b27f.png)
![c1 55a-few-secs](https://user-images.githubusercontent.com/60958552/190039988-b4355a4e-00db-4c16-bfb9-bad286ba1bf8.png)
![b1 56](https://user-images.githubusercontent.com/60958552/190039989-2ebcd41b-969f-4773-879c-2c7250bc76dd.png)

a1: before 1.55a - few hours working (from start issue)
a2: now after change to 1.56 - few minutes for sure
a3: now switch back to 1.55a - few seconds

**Comment by jgonzis** [comment]
You have to redownload 1.56 it has been a small bug with the unlock lhr

**Comment by jgonzis** [comment]
Note: Linux version got re-uploaded because of a LHR unlocker bug
