### ISSUE TITLE
v1.56 problem: Lost connection to stratum server stratum-ergo.flypool.org:3333 or server not reachable.

### ISSUE THREAD

**Issue by gorancel** [Lolliedieb/lolMiner-releases#1706]
After updating miner from 1.55a to 1.56 Ergo hashrate has droped significantly.

GPU 4 RTX 3070  94.66  146.42    21/1   64.1G   1.392   67.5  1410  7900    50    61   60
GPU 5 RTX 3070  94.36  113.14    16/1   35.6G   1.366   68.6  1410  7900    47    60   60
--------------------------- 
Total          568.26  632.28    92/3  901.7G   1.330  424.2                             
----------------------------------------------- 
Average speed (15s): 95.26 Mh/s | 94.06 Mh/s | 94.06 Mh/s | 95.26 Mh/s | 95.26 Mh/s | 94.06 Mh/s Total: 567.96 Mh/s
**Lost connection to stratum server stratum-ergo.flypool.org:3333 or server not reachable.** 
Trying to connect in 5 second(s) 
DNS over HTTPS resolve failed - switching to standard resolve 
Connected to stratum-ergo.flypool.org(172.65.222.76):3333  (TLS disabled)
Subscribed to stratum server
New extranonce received: b795 
Authorized worker: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.loki033070NONLHR 
New job received: 522bc14e Height: 838116 Target: 0000000112E0BE82... 
New extra nonce received: b795
GPU 2: Found a share of difficulty 7.05G 
GPU 2: Share accepted (46 ms)

**Comment by UselessGuru** [comment]
Same with Autolykos2 @ NiceHash

**Comment by jgonzis** [comment]
Both many thanks For the information... we found the problem... Really many thanks for the feedback. That problem with 1.56 doesn't happen in Herominers or 2Miners... It will be really soon solved!! Many thanks!!

**Comment by Lolliedieb** [comment]
Thanks for the report, 1.57 just went alive with the fix on board :)
