### ISSUE TITLE
Hashrate goes down while mining, seems the miner doesn't get the maximum frecuency for a given voltage

### ISSUE THREAD

**Issue by clamatac** [Lolliedieb/lolMiner-releases#171]
Hi,

first of all, sorry for my English.

I have just starting mining 7 days ago. More or less it is working properly, but I have noticed something strange that I do not know if it is a problem, bug or if it is normal.

I have an RTX 3080 and I use MSI AFTERBURNER in order to control temps, fan speeds etc, but also to limit voltage and to achieve the best working frequency for a given voltage. 

Here is a screenshoot:

![unnamed](https://user-images.githubusercontent.com/29074635/105610807-d8a1a980-5db1-11eb-8470-24147c94b291.png)

For a value of 712 mv the card must be working around 1300 Mhz, but most of the times it only gets 800-900 Mhz.

¿is it normal?

Any comment will be received with happiness  :)

Greetings

**Comment by jgonzis** [comment]
I think you have a memory temp problem, there are several 3080 with that problem. Make a try put fan to 100% an retry...

**Comment by clamatac** [comment]
thank so much, I have turn off my custom fan curve  and limit consumption wit a power limit of 70%. Now I have a frequency near 1600 Mhz with 725-750 mv.

I hope everything keeps this way.

Greetings

**Comment by jgonzis** [comment]
> thank so much, I have turn off my custom fan curve and limit consumption wit a power limit of 70%. Now I have a frequency near 1600 Mhz with 725-750 mv.
> 
> I hope everything keeps this way.
> 
> Greetings

You can try the latest HWINFO64 it will give you the mem temps of your Card so you will have an interesting information, that could help you. If you do it tells us which  temp do you get

**Comment by clamatac** [comment]
just do it, I have upgraded speed fan to 75%, and mem junc temp it is between 98-100 º C

I also has add 750 Mhz to VRM it seems and seems stable after 12 h of mining.

Thanks a lot
