### ISSUE TITLE
Enable Aeternity Support for RX 6600, RX 6600 XT and RX 6700 X

### ISSUE THREAD

**Issue by leogeeko** [Lolliedieb/lolMiner-releases#1710]
Hello my dear awesome devs.

Could you please support the cards above?

Thanks!!!

**Comment by jgonzis** [comment]
Many thanks for the feedback we will look on it for next releases

**Comment by heliosgnosis** [comment]
I have been asking out loud for years for that, maybe since the great winter is finally set in deep they will add it,  maybe lol

**Comment by jgonzis** [comment]
Solved with 1.62
