### ISSUE TITLE
how to mine kaspa? only one coin

### ISSUE THREAD

**Issue by viponedream** [Lolliedieb/lolMiner-releases#1711]
only one coin,

**Comment by jgonzis** [comment]
You can mine dual with --dualfactor 10 or 15

**Comment by GTreaper** [comment]
> only one coin,

Agreed!



> You can mine dual with --dualfactor 10 or 15

Not to sure what you mean? I also wanna mine just Kaspa, and by that i mean ONLY KASPA no dual mining just kaspa as the primary algo.

**Comment by jgonzis** [comment]
> > only one coin,
> 
> Agreed!
> 
> > You can mine dual with --dualfactor 10 or 15
> 
> Not to sure what you mean? I also wanna mine just Kaspa, and by that i mean ONLY KASPA no dual mining just kaspa as the primary algo.

At the moment is not possible, it is been analysed too... so I hope soon will be news

**Comment by cypher619** [comment]
would love to have single mining kaspa as well

**Comment by jgonzis** [comment]
We will have a look on it if is possible.

**Comment by jgonzis** [comment]
New release 1.58 with only KASPA

**Comment by cypher619** [comment]
windows version?
