### ISSUE TITLE
how to mine ergo + kaspa?

### ISSUE THREAD

**Issue by viponedream** [Lolliedieb/lolMiner-releases#1713]
lolMiner --algo  AUTOLYKOS2   --pool %pool1% --user %wal1% --worker %worker% --dualmode KASPADUAL --dualpool  %pool2%  --dualuser %wal2%  --dualworker %worker% --apiport 8020 --watchdog exit

this is doesnot work
it says main algo must be ethash?

**Comment by jgonzis** [comment]
That is not possible at the moment, the lost of performance in Ergo is too high. At the moment is ETC/ETHW + KASPA
