### ISSUE TITLE
Lolminer ZelCash No Hashrate Report on HiveOs

### ISSUE THREAD

**Issue by Ricco59163** [Lolliedieb/lolMiner-releases#1714]
Hi,

Gpu's work fine on Fluxpool but no Hashrate in Hiveos ?

any solutions ?

Thx for Help

**Comment by thaneb** [comment]
did you use api/http port argument in your miner settings ? modifying the default port may lead to such issue.

**Comment by jgonzis** [comment]
Nice one too...

**Comment by jgonzis** [comment]
No more feedback
