### ISSUE TITLE
Crash on connection loss to nanopool mining ETC+KASPA on Linux

### ISSUE THREAD

**Issue by GauchoBois** [Lolliedieb/lolMiner-releases#1717]
Hi, I keep having this problem that the miner crash when loosing connection with nanopool, but only in some rigs while the others work smoothly. I'm on plain Linux "Ubuntu 20.04.2 LTS" with kernel 5.4.0-53-generic. It happens with 1.57 and 1.58 as well. Looks like the miner crashes even though the connection is reestablished, with this output:

```
Lost connection to stratum server etc-us-west1.nanopool.org:19433 or server not reachable. 
Trying to connect in 5 second(s) 
DNS over HTTPS resolve failed - switching to standard resolve 
Connected to etc-us-west1.nanopool.org(66.42.105.146):19433  (TLS enabled)
TLS Handshake success 
Set Ethash stratum mode: Ethereum Proxy
and then crashes...
```

Tried different pool locations (east, west, Asia, blablabla) and same problem. Tried with adding two pools, first east and then west, and it switches but after the second connection loss it crashes (output correspond to this example). Sometimes doesn't even switch to the second pool...

```
Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
Trying to connect in 5 second(s) 
Etchash: Average speed (15s): 37.83 Mh/s | 58.33 Mh/s | 38.21 Mh/s | 37.78 Mh/s | 37.71 Mh/s | 37.76 Mh/s Total: 247.63 Mh/s
HeavyHash-Kaspa: Average speed (15s): 122.96 Mh/s | 189.58 Mh/s | 124.19 Mh/s | 122.79 Mh/s | 122.56 Mh/s | 122.72 Mh/s Total: 804.80 Mh/s
DNS over HTTPS resolve failed - switching to standard resolve 
Connected to etc-us-east1.nanopool.org(142.44.242.100):19433  (TLS enabled)
TLS Handshake success 
Set Ethash stratum mode: Ethereum Proxy
Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
Trying to connect in 5 second(s) 
and crashes...
```

Tried increasing the latency but it keeps failing, improving the network, switching from stratum to ssl, adding the while [ $? -eq 42 ]; loop... but nothing works.

It worked perfectly with ETH+KASPA as well as ERGO (also nanopool), and with other miners like bzminer mining ETC+KASPA also works with no problem, but I prefer using lolminer. 

BTW, I stick to nanopool because I use their API. Hope somebody can help. It will be very appreciated!!!

**Comment by jgonzis** [comment]
> Hi, I keep having this problem that the miner crash when loosing connection with nanopool, but only in some rigs while the others work smoothly. I'm on plain Linux "Ubuntu 20.04.2 LTS" with kernel 5.4.0-53-generic. It happens with 1.57 and 1.58 as well. Looks like the miner crashes even though the connection is reestablished, with this output:
> 
> ```
> Lost connection to stratum server etc-us-west1.nanopool.org:19433 or server not reachable. 
> Trying to connect in 5 second(s) 
> DNS over HTTPS resolve failed - switching to standard resolve 
> Connected to etc-us-west1.nanopool.org(66.42.105.146):19433  (TLS enabled)
> TLS Handshake success 
> Set Ethash stratum mode: Ethereum Proxy
> and then crashes...
> ```
> 
> Tried different pool locations (east, west, Asia, blablabla) and same problem. Tried with adding two pools, first east and then west, and it switches but after the second connection loss it crashes (output correspond to this example). Sometimes doesn't even switch to the second pool...
> 
> ```
> Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
> Trying to connect in 5 second(s) 
> Etchash: Average speed (15s): 37.83 Mh/s | 58.33 Mh/s | 38.21 Mh/s | 37.78 Mh/s | 37.71 Mh/s | 37.76 Mh/s Total: 247.63 Mh/s
> HeavyHash-Kaspa: Average speed (15s): 122.96 Mh/s | 189.58 Mh/s | 124.19 Mh/s | 122.79 Mh/s | 122.56 Mh/s | 122.72 Mh/s Total: 804.80 Mh/s
> DNS over HTTPS resolve failed - switching to standard resolve 
> Connected to etc-us-east1.nanopool.org(142.44.242.100):19433  (TLS enabled)
> TLS Handshake success 
> Set Ethash stratum mode: Ethereum Proxy
> Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
> Trying to connect in 5 second(s) 
> and crashes...
> ```
> 
> Tried increasing the latency but it keeps failing, improving the network, switching from stratum to ssl, adding the while [ $? -eq 42 ]; loop... but nothing works.
> 
> It worked perfectly with ETH+KASPA as well as ERGO (also nanopool), and with other miners like bzminer mining ETC+KASPA also works with no problem, but I prefer using lolminer.
> 
> BTW, I stick to nanopool because I use their API. Hope somebody can help. It will be very appreciated!!!

that seems a connection problem with the pool... could you try another pool just to make a test?

**Comment by GauchoBois** [comment]
that's exactly what I'm doing now, I'll keep you informed with the result. However, I still wonder why lolMiner crashes in the reconnection and it doesn't always happen neither in all rigs... btw, it doesn't even call the emergency.sh script and a soft reboot doesn't restart the rig either. Only a hard reset does...

**Comment by GauchoBois** [comment]
Update: there is no single crash after 2.5hs mining to ethermine. It's clear that nanopool ETC is having issues causing the disconnection (doesn't matter which nanopool is chosen). Nevertheless, lolMiner doesn't look to be able to handle the problem and crashes. It could be an improvement to make into this beloved miner.

Thanks a lot jgonzis for your help!

**Comment by GauchoBois** [comment]
Last update: it still happen with ethermine but much less frequent. This is the output:
`
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Trying to connect in 5 second(s) 
DNS over HTTPS resolve failed - switching to standard resolve 
----------------------------------------------- 
Statistics (23:49:00); Uptime: 12h 9m 5s 
lolMiner 1.58, AMD CL 3380.4
Algorithm 1: Etchash 

`

**Comment by GauchoBois** [comment]
Last last update. I got this strange behavior now in one of the rigs that it disconnects from the pools and doesn't manage to connect again... 

```
Etchash: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
HeavyHash-Kaspa: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
Time out on connection attempt resolve. Retrying. 
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Trying to connect in 5 second(s) 
Too many attempts. Switching to failover pool us1-etc.ethermine.org:5555 
DNS over HTTPS resolve failed - switching to standard resolve 
Time out on connection attempt resolve. Retrying. 
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Trying to connect in 5 second(s) 
Etchash: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
HeavyHash-Kaspa: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
DNS over HTTPS resolve failed - switching to standard resolve 
Time out on connection attempt resolve. Retrying. 
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Trying to connect in 5 second(s) 
DNS over HTTPS resolve failed - switching to standard resolve 
Etchash: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
HeavyHash-Kaspa: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
DNS over HTTPS resolve failed - switching to standard resolve 
Time out on connection attempt resolve. Retrying. 
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Trying to connect in 5 second(s) 
DNS over HTTPS resolve failed - switching to standard resolve 
Time out on connection attempt resolve. Retrying. 
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Trying to connect in 5 second(s) 
Etchash: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
HeavyHash-Kaspa: Average speed (15s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
----------------------------------------------- 
Statistics (13:47:56); Uptime: 6h 12m 41s 
lolMiner 1.58, AMD CL 3110.6
Algorithm 1: Etchash 
Connected to:   
Algorithm 2: HeavyHash-Kaspa 
Connected to: pool.br.woolypooly.com:3112  

```
It was like that for a couple of hours. The network access is available because I ssh to it remotely, and only a reboot is able to restart the miner. Other rigs where mining to ethermine and nanopool normally while this one was giving this output.

I wonder if I'm doing something wrong but this started happening only after started mining ETC...

Thanks in advance and I'll really appreciate if somebody can tell me how to debug this behavior.

**Comment by jgonzi** [comment]
As you see woolypooly.com still working connect it. Could you try to connect etc and kaspa to woolypooly.com

**Comment by GauchoBois** [comment]
I'm also getting some disconnections from woolypooly in other rigs from time to time (for kaspa), but much less frequently than any other etc mining pool. This is an example of a rig that is also starting to suffer lots of disconnections but the miner seems to tolerate them and doesn't crash:

```
rig16:~/lolminer/logs$ cat 2022-09-25_17-53-10.log | grep Lost
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server pool.woolypooly.com:3112 or server not reachable. 
Lost connection to stratum server etc-us-east1.nanopool.org:19433 or server not reachable. 
Lost connection to stratum server etc-us-west1.nanopool.org:19433 or server not reachable. 
Lost connection to stratum server etc-us-west1.nanopool.org:19433 or server not reachable.
```

while this is the logging for another rig connected to ethermine+woolypooly:
```
rig14:~/lolminer/logs$ cat 2022-09-25_19-14-11.log | grep Lost
Lost connection to stratum server us1-etc.ethermine.org:5555 or server not reachable. 
Lost connection to stratum server pool.br.woolypooly.com:3112 or server not reachable. 
```

That was about 1.5 hours of logging for both rigs.

I'm starting to think I have network and/or provider link issues, but it is strange that they didn't happen before when mining eth+kaspa. Maybe they were just not noticeable because the miner wasn't crashing... I don't know, I'm kind of disoriented now.

I'll keep researching about it and let you know if I find some workaround. Thanks a lot for the help.

**Comment by jgonzis** [comment]
Check you go directly and not by wifi or PLC to the router

**Comment by GauchoBois** [comment]
I just think it is the provider link at this point because this is not happening in another location where I have some more rigs that are indeed linked wirelessly to the provider router but the link is way better in that location. 

BTW the thread was started because it was curious to me that the miner not always handled the reconnection issue correctly and crashed, but it is now somehow doing it correctly though... I'll be back with more information if I finally find the source of the problem, but I'm starting to guess at this point that it is related to Netflix "primetime"... 

Anyways, what you suggest is correct, that's exactly what I did a while ago but it didn't improve, also improved the cabling before starting the thread, that's why I thought it wasn't the network. I'm in the process of checking all the freaking connectors and changing the switches for better ones (there is maybe a problem in the number of connections per switch), but again, I think "pool disconnection problem" might be solved by paying for a better Internet service...

**Comment by GauchoBois** [comment]
new update on this issue... I just figured that for some unknown reason it happens that the miner disconnects from ethermine with excessive undervolting (but not from woolypooly-kaspa). The miner doesn't even establish the connection with ethermine when the undervolting is too low... tried in a rig with old rx580s but it also happens in some other rigs from time to time when playing with OC&UV... this is the output:

```
Statistics (12:01:50); Uptime: 0h 2m 22s 
lolMiner 1.60, AMD CL 3180.7
Algorithm 1: Etchash 
Connected to: us1-etc.ethermine.org:5555  
Algorithm 2: HeavyHash-Kaspa 
Connected to: pool.br.woolypooly.com:3112  

      Name        Speed  Pool  Shares   Best    Eff.  Speed  Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Fan  Dual
                   Mh/s  Mh/s  A/S/Hw  Share  Mh/s/W   Mh/s  Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Pct   Fct
GPU 0 RX 480 Grap  0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000   27.2  1150   300    38   18  0.00
GPU 1 RX 580 2048  0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000   42.3  1026   400    33   43  0.00
GPU 2 RX 570       0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000   48.7   993   300    34   16  0.00
GPU 3 RX 580 2048  0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000   43.2  1011  1000    35   43  0.00
GPU 4 RX 580 2048  0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000   31.2   756   400    34   43  0.00
GPU 5 RX 580       0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000   48.3  1010   300    38   16  0.00
--------------------------- 
Total              0.00  0.00   0/0/0    0.0   0.000   0.00  0.00     0/0    0.0   0.000  240.8                             
-----------------------------------------------  

```
and keeps going like this for hours if I let it go... In order to reproduce it just turn the cvddc as low as 825 for the rx580 and some of them will handle it but some others pull this issue.

So, as a conclusion... I think that the original issue of pool disconnection is mainly due to excessive UV probably. Don't know why the manifestation is about pool disconnection though, but the rig has to be hard-reset after this and adjusting the UV solves the problem.

**Comment by jgonzis** [comment]
Could it be that tries to maintaining the connection but GPU is dead

**Comment by GauchoBois** [comment]
btw pinging us1-etc.ethermine.org while this happens works... so the problem looks clearly to be somewhere in the etc mining algorithm with the miner + the gpus not answering probably as you say... and not the connection, as can also be seen with the connection established to woolypooly

**Comment by jgonzis** [comment]
It should report ms to the pool to be connected and it doesn't conmect if first is not etc/eth

**Comment by GauchoBois** [comment]
just to confirm that this "connection+crash" issue is due to excessive undervolting of the GPU core and the manifestation is this strange symptom. It doesn't happen with mem undervolting that normally takes the GPU to 0Mh/s or through other messages like GPU not responding, etc.
