### ISSUE TITLE
Kaspa+Zil dual mining

### ISSUE THREAD

**Issue by ImmutableMethod** [Lolliedieb/lolMiner-releases#1719]
Can Kaspa+Zil dual mining please be added?
lolMiner.exe --algo KASPA --pool pool.us.woolypooly.com:3112 --user * --worker * --enablezilcache --dualmode ZIL --dualpool zmp://zil.flexpool.io --dualuser * --dualworker * --watchdog exit
Using the above in 1.58 gives Error: your dualmode option "ETHASH" requires primary --algo to be ETHASH, ETCHASH, or UBQHASH.

**Comment by jgonzis** [comment]
That is not working at the moment ZIL is only for ETH/ETC/ETHW at the moment
