### ISSUE TITLE
Number of stale shares doesn't match with ethermine reported number of stales

### ISSUE THREAD

**Issue by GauchoBois** [Lolliedieb/lolMiner-releases#1723]
Hi, just switched from nanopool to ethermine and figured it out that the number of stale is around x10 (around 3% of total per hour) more than those reported by lolMiner (only 2-3 stale shares reported). I'm mining with 5 rigs and only 2 of them showed in lolMiner 1-2 stales each.

Is this normal or there is an issue? If so, is there a way to improve this besides tuning the OC&UV? the problem is that since I have no accurate report in lolMiner I don't know exactly which are the buggy GPUs...

This is with 1.58 on plain linux Ubuntu.

Thanks for the help in advance, as always.

**Comment by Lolliedieb** [comment]
The miner can only report as stale what is responded by the pool as stale. If you have doubts run the miner with --stratum-debug to see the full miner to pool communication. The software can only report as stale when the pool reports the share was stale, otherwise it can not know.
