### ISSUE TITLE
full node kaspa - how to connect?

### ISSUE THREAD

**Issue by Maythecoffee** [Lolliedieb/lolMiner-releases#1724]
Hi, i n Bzminer i use 
solo+tcp://178.XX.XX.XXX:16110 to connect to my full node.
This prefix is not accepted by Lol, using simple 178.XX.XX.XXX:16110 i also can't connect, so what is the correct syntaxes for lol miner?

checked post about kstratum is it still actual? it seems as separate miner for dual mode..

updated: so i run in paralle ksstratum and i shocked it is working!!

**Comment by Maythecoffee** [comment]
kstratum is working.

**Comment by stoepie101** [comment]
Does anyone have a guide on how to get kstratum running on windows with node.js?
