### ISSUE TITLE
Error: Input to pool can not be split into an address and port In Hive flightsheet config when trying to setup for ETC/ZIL on ezil and KAS on a local node

### ISSUE THREAD

**Issue by DragonKeeper** [Lolliedieb/lolMiner-releases#1728]
Hello when setting up an attempt at dual mining ZIL/ETC  as the first coin on ezil.me along with Kaspa on a local node,  this error message shows up on the miner screen and the miner exits and then tries again after a few seconds with the same final result.
Error: Your input to --pool  "us-west.ezil.me:4444"  can not be split into an address and a port.  Please use format <pool address>:<pool port>.  Below is my configuration screen. 

![hive-lolminer-setup](https://user-images.githubusercontent.com/30033/192087564-c19535c7-538f-4c8d-8f4b-4ac0c14eefca.png)

I have noticed that when one of the colons is taken out of the second Pool server input, that error message does not happen,  Unfortunately the second pool can't be connected to with part of that missing, Unless there is a different way to accomplish that.  Please advise as to whether this is a bug or not.  Thanks

**Comment by jgonzis** [comment]
> Hello when setting up an attempt at dual mining ZIL/ETC as the first coin on ezil.me along with Kaspa on a local node, this error message shows up on the miner screen and the miner exits and then tries again after a few seconds with the same final result. Error: Your input to --pool "us-west.ezil.me:4444" can not be split into an address and a port. Please use format :. Below is my configuration screen.
> 
> ![hive-lolminer-setup](https://user-images.githubusercontent.com/30033/192087564-c19535c7-538f-4c8d-8f4b-4ac0c14eefca.png)
> 
> I have noticed that when one of the colons is taken out of the second Pool server input, that error message does not happen, Unfortunately the second pool can't be connected to with part of that missing, Unless there is a different way to accomplish that. Please advise as to whether this is a bug or not. Thanks

For wallet use only %WAL% and put %WORKER_NAME% in work box


About kaspa node+tcp doesn't work, use the guide:

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-KStratum-in-HiveOS-(Kaspa-Mining-directly-to-a-Node)
