### ISSUE TITLE
Dual ETC+KAS mining buggy

### ISSUE THREAD

**Issue by esippert** [Lolliedieb/lolMiner-releases#1731]
For some reason various cards will randomly 0.00 Mh/s on Kas, but still go on ETC.  No explanation, and restart miner causes random other cards to go 0.0 Mh/s.

**Comment by jgonzis** [comment]
> For some reason various cards will randomly 0.00 Mh/s on Kas, but still go on ETC. No explanation, and restart miner causes random other cards to go 0.0 Mh/s.

Show miner log... could it be a crash for the OC...

**Comment by dangitsdavid** [comment]
Same issue here. After tuning, everything goes to 0.

```
GPU 0: Tuning for dual mining completed. 
Etchash: Average speed (10s): 66.49 Mh/s | 77.69 Mh/s | 46.07 Mh/s | 43.36 Mh/s | 64.20 Mh/s | 69.80 Mh/s Total: 367.61 Mh/s
HeavyHash-Kaspa: Average speed (10s): 80.55 Mh/s | 101.97 Mh/s | 23.08 Mh/s | 39.25 Mh/s | 73.52 Mh/s | 75.87 Mh/s Total: 394.25 Mh/s
GPU 4: Tuning for dual mining completed. 
New job received: 0x498005 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
New job received: 0xad4c04 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
New job received: 0xb878b0 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
Etchash: GPU 1: Found a share of difficulty 23.40G 
Etchash: GPU 1: Share accepted (22 ms) 
New job received: 0xcbdda2 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
Etchash: Average speed (10s): 68.57 Mh/s | 84.32 Mh/s | 47.10 Mh/s | 46.99 Mh/s | 66.86 Mh/s | 74.98 Mh/s Total: 388.82 Mh/s
HeavyHash-Kaspa: Average speed (10s): 97.42 Mh/s | 27.17 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 72.85 Mh/s | 15.83 Mh/s Total: 213.26 Mh/s
New job received: 0xc6fec0 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
New job received: 0x77859f Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
New job received: 0x51edbc Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
New job received: 0x22df6d Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
New job received: 0x54c38c Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
----------------------------------------------- 
Statistics (01:53:37); Uptime: 0h 2m 1s 
lolMiner 1.59, Nvidia 510.60.02, Api port 44444
Algorithm 1: Etchash 
Connected to: us-west.ezil.me:4444 (26ms latency) 
Algorithm 2: HeavyHash-Kaspa 
Connected to: us.acc-pool.pw:16061  

      Name         Speed    Pool  Shares    Best    Eff.   Speed  Pool  Shares
                    Mh/s    Mh/s  A/S/Hw   Share  Mh/s/W    Mh/s  Mh/s     A/R
GPU 0 RTX 3080     70.57  141.98   4/0/0  270.2G   0.393   59.64  0.00     0/0
GPU 1 RTX 3080     83.16  141.98   4/0/0  930.7G   0.397   68.88  0.00     0/0
GPU 2 GTX 1080 Ti  45.91   35.50   1/0/0    8.5G   0.330   32.51  0.00     0/0
GPU 3 GTX 1080 Ti  45.64   70.99   2/0/0   29.2G   0.329   32.58  0.00     0/0
GPU 4 RTX 3080     67.45   70.99   2/0/0   15.8G   0.386   60.09  0.00     0/0
GPU 5 RTX 3080     73.98    0.00   0/0/0     0.0   0.412   51.22  0.00     0/0
--------------------------- 
Total             386.71  461.44  13/0/0  930.7G   0.379  304.92  0.00     0/0

         Best    Eff.   Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
        Share  Mh/s/W       W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
GPU 0     0.0   0.332   179.1   780  9451    53    65    96   85  0.00
GPU 1     0.0   0.329   209.0   915  9451    49    61    88   80  0.00
GPU 2     0.0   0.233   138.8  1404  5258    50    64   N/A   80  0.00
GPU 3     0.0   0.235   138.1  1392  5258    53    67   N/A   81  0.00
GPU 4     0.0   0.344   174.1   750  9451    54    67    96   85  0.00
GPU 5     0.0   0.285   179.0   825  9451    52    65    92   85  0.00
--------------------------- 
Total     0.0   0.299  1018.0                                         
----------------------------------------------- 
Etchash: Average speed (10s): 72.92 Mh/s | 85.90 Mh/s | 47.17 Mh/s | 46.98 Mh/s | 69.92 Mh/s | 75.85 Mh/s Total: 398.75 Mh/s
HeavyHash-Kaspa: Average speed (10s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s

```

**Comment by jgonzis** [comment]
Are you in Windows right?... it seems an Issue in 4G Gpus and Dual in Windows not Linux

**Comment by dangitsdavid** [comment]
This is on HIVEOS v0.6-219@220925 which should be running lolMiner v1.59a

**Comment by esippert** [comment]
> 

Nope this is in HiveOS.  6 RTX 3090's 1 RTX 3070 and 5 RTX 3060 ti's.

**Comment by jgonzis** [comment]
> Same issue here. After tuning, everything goes to 0.
> 
> ```
> GPU 0: Tuning for dual mining completed. 
> Etchash: Average speed (10s): 66.49 Mh/s | 77.69 Mh/s | 46.07 Mh/s | 43.36 Mh/s | 64.20 Mh/s | 69.80 Mh/s Total: 367.61 Mh/s
> HeavyHash-Kaspa: Average speed (10s): 80.55 Mh/s | 101.97 Mh/s | 23.08 Mh/s | 39.25 Mh/s | 73.52 Mh/s | 75.87 Mh/s Total: 394.25 Mh/s
> GPU 4: Tuning for dual mining completed. 
> New job received: 0x498005 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> New job received: 0xad4c04 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> New job received: 0xb878b0 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> Etchash: GPU 1: Found a share of difficulty 23.40G 
> Etchash: GPU 1: Share accepted (22 ms) 
> New job received: 0xcbdda2 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> Etchash: Average speed (10s): 68.57 Mh/s | 84.32 Mh/s | 47.10 Mh/s | 46.99 Mh/s | 66.86 Mh/s | 74.98 Mh/s Total: 388.82 Mh/s
> HeavyHash-Kaspa: Average speed (10s): 97.42 Mh/s | 27.17 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 72.85 Mh/s | 15.83 Mh/s Total: 213.26 Mh/s
> New job received: 0xc6fec0 Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> New job received: 0x77859f Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> New job received: 0x51edbc Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> New job received: 0x22df6d Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> New job received: 0x54c38c Epoch: 534 (ETCHash epoch: 267) Difficulty: 4.29G 
> ----------------------------------------------- 
> Statistics (01:53:37); Uptime: 0h 2m 1s 
> lolMiner 1.59, Nvidia 510.60.02, Api port 44444
> Algorithm 1: Etchash 
> Connected to: us-west.ezil.me:4444 (26ms latency) 
> Algorithm 2: HeavyHash-Kaspa 
> Connected to: us.acc-pool.pw:16061  
> 
>       Name         Speed    Pool  Shares    Best    Eff.   Speed  Pool  Shares
>                     Mh/s    Mh/s  A/S/Hw   Share  Mh/s/W    Mh/s  Mh/s     A/R
> GPU 0 RTX 3080     70.57  141.98   4/0/0  270.2G   0.393   59.64  0.00     0/0
> GPU 1 RTX 3080     83.16  141.98   4/0/0  930.7G   0.397   68.88  0.00     0/0
> GPU 2 GTX 1080 Ti  45.91   35.50   1/0/0    8.5G   0.330   32.51  0.00     0/0
> GPU 3 GTX 1080 Ti  45.64   70.99   2/0/0   29.2G   0.329   32.58  0.00     0/0
> GPU 4 RTX 3080     67.45   70.99   2/0/0   15.8G   0.386   60.09  0.00     0/0
> GPU 5 RTX 3080     73.98    0.00   0/0/0     0.0   0.412   51.22  0.00     0/0
> --------------------------- 
> Total             386.71  461.44  13/0/0  930.7G   0.379  304.92  0.00     0/0
> 
>          Best    Eff.   Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
>         Share  Mh/s/W       W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
> GPU 0     0.0   0.332   179.1   780  9451    53    65    96   85  0.00
> GPU 1     0.0   0.329   209.0   915  9451    49    61    88   80  0.00
> GPU 2     0.0   0.233   138.8  1404  5258    50    64   N/A   80  0.00
> GPU 3     0.0   0.235   138.1  1392  5258    53    67   N/A   81  0.00
> GPU 4     0.0   0.344   174.1   750  9451    54    67    96   85  0.00
> GPU 5     0.0   0.285   179.0   825  9451    52    65    92   85  0.00
> --------------------------- 
> Total     0.0   0.299  1018.0                                         
> ----------------------------------------------- 
> Etchash: Average speed (10s): 72.92 Mh/s | 85.90 Mh/s | 47.17 Mh/s | 46.98 Mh/s | 69.92 Mh/s | 75.85 Mh/s Total: 398.75 Mh/s
> HeavyHash-Kaspa: Average speed (10s): 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s | 0.00 Mh/s Total: 0.00 Mh/s
> ```

2 problems.... 
1st using 1.59 and not 1.59a
2nd not connected to the pool it does the autotune and stop because wallet is wrong probably. Show the full config to help us to find where is the  problem

**Comment by dangitsdavid** [comment]
> 1st using 1.59 and not 1.59a

Odd. Latest is selected in HIVEOS which should be 1.59a
<img width="360" alt="image" src="https://user-images.githubusercontent.com/32752664/192913806-86ff0690-fa0b-429e-b657-11b53b00cdf6.png">

---

> 2nd not connected to the pool it does the autotune and stop because wallet is wrong probably. 

The exact same config/flightsheet works on my other rig running one 2080, 2060, 1070 (3 card rig - all of them hashes). Only the 4x 3080, 2x 1080ti rig has an issue. 

Flightsheet:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/32752664/192914311-46cdd325-219a-464c-9cd2-f39adc766ba5.png">

**Comment by jgonzis** [comment]
So something is not going properly in HiveOS... look at your miner log:

lolMiner 1.59, Nvidia 510.60.02...

Sometimes I found HiveOS don't load properly some flightsheet

**Comment by jgonzis** [comment]
No more feedback
