### ISSUE TITLE
Mining pool payout IP's.  

### ISSUE THREAD

**Issue by esippert** [Lolliedieb/lolMiner-releases#1732]
Most of the pools I have selected require you put in the IP address of your miner/network in order to change things like minimum payouts and gas fee%'s wanted.  My own IP doesn't allow me in because I'm guessing the autoswap miner actually delivering the hashing goods.  How to you find the IP address of your "pool proxy" in order to change minimum payout?

**Comment by jgonzi** [comment]
> Most of the pools I have selected require you put in the IP address of your miner/network in order to change things like minimum payouts and gas fee%'s wanted. My own IP doesn't allow me in because I'm guessing the autoswap miner actually delivering the hashing goods. How to you find the IP address of your "pool proxy" in order to change minimum payout?

Try do a ping to the proxy or talk directly to the admins id the pools
