### ISSUE TITLE
Low difficulty share on mining Kaspa

### ISSUE THREAD

**Issue by imxp978** [Lolliedieb/lolMiner-releases#1737]
Hi, I am mining kaspa on acc-pool, I find my 3070 lhr is frequently having low difficulty shares ( rejected share).
I tried to lower the core clock from 250 to 150, however it did not help, I'm still getting 20-30% of rejected shares on this 3070.
I don't have other Nvidia card on the rig, couldn't tell if this is a gpu failure. my current 3070 oc setting is cclock:150 / mem clock:-2000 / PL: 135, and I use nvidia-smi -lmc 810 command to lower mem clock.

the gpu is a EVGA 3070 FTW3 LHR, and error message is as below:

    "id": "20",                                                                                                                                                                               
    "result": "null",                                                                                                                                                                         
    "error": [                                                                                                                                                                                
        "23",                                                                                                                                                                                 
        "low difficulty share",                                                                                                                                                               
        "null"                                                                                                                                                                                
    ]

**Comment by jgonzis** [comment]
> Hi, I am mining kaspa on acc-pool, I find my 3070 lhr is frequently having low difficulty shares ( rejected share). I tried to lower the core clock from 250 to 150, however it did not help, I'm still getting 20-30% of rejected shares on this 3070. I don't have other Nvidia card on the rig, couldn't tell if this is a gpu failure. my current 3070 oc setting is cclock:150 / mem clock:-2000 / PL: 135, and I use nvidia-smi -lmc 810 command to lower mem clock.
> 
> the gpu is a EVGA 3070 FTW3 LHR, and error message is as below:
> 
> ```
> "id": "20",                                                                                                                                                                               
> "result": "null",                                                                                                                                                                         
> "error": [                                                                                                                                                                                
>     "23",                                                                                                                                                                                 
>     "low difficulty share",                                                                                                                                                               
>     "null"                                                                                                                                                                                
> ]                 
> ```

which pool are you using ? be sure you are in 1.59a not in 1.59 in acc-pool

**Comment by imxp978** [comment]
I was using 1.59a in solo acc-pool, when I switched to woolypooly solo, that error haven't happened so far.

**Comment by jgonzis** [comment]
> I was using 1.59a in solo acc-pool, when I switched to woolypooly solo, that error haven't happened so far.

Be careful, some HiveOS updated to only 1.59, not the 1.59a. Only way to see it in the miner loh

**Comment by imxp978** [comment]
I didn't check the log, but in the console it showed 1.59a
