### ISSUE TITLE
High varience on woolypooly with lolminer kaspa 

### ISSUE THREAD

**Issue by shnoah641** [Lolliedieb/lolMiner-releases#1740]
I am getting a huge varience issue with woolypooly as I am mining. My gpu is causing the pool price to decrease for an unkown reason that I cannot figure out. I tried a different miner and it drove the price up so idk how to fix this issue.

**Comment by jgonzis** [comment]
It could be you dont have enough hash... try to share some photos to understand it better. because that doesnt seem to be a miner issue
