### ISSUE TITLE
Automatic overclock profile switch (HiveOS beta) and equihash 125/4

### ISSUE THREAD

**Issue by gottfrede203** [Lolliedieb/lolMiner-releases#1745]
Hi,

Have tested the automatic overclocking profile switch function in the HiveOS beta releases.
It seems to work with Ethash and Etcash, but not with Equihash 125/4 (tested with both "FLUX" and "NH-ZelHash" in the config arguments.
Possibly a bug? 
Tested with both 1.59a and 1.60.

This is what i get in the miner:
   Applying OC equihash 125/4 with:                                                                                                                     
   { "message": "Empty input", "code": 400 }                                                                                                            
   Recheck will be in 60 minutes

My equihash 125/4 overclocks get selected correctly with the native "auto select" function in HiveOS when I run a Flux flightsheet with the "standard" 1.60 release, so I'm sure I've set the correctly to the equihash 125/4 and zelhash algo.

**Comment by jgonzis** [comment]
> Hi,
> 
> Have tested the automatic overclocking profile switch function in the HiveOS beta releases. It seems to work with Ethash and Etcash, but not with Equihash 125/4 (tested with both "FLUX" and "NH-ZelHash" in the config arguments. Possibly a bug? Tested with both 1.59a and 1.60.
> 
> This is what i get in the miner: Applying OC equihash 125/4 with: { "message": "Empty input", "code": 400 } Recheck will be in 60 minutes
> 
> My equihash 125/4 overclocks get selected correctly with the native "auto select" function in HiveOS when I run a Flux flightsheet with the "standard" 1.60 release, so I'm sure I've set the correctly to the equihash 125/4 and zelhash algo.

Have you added properly the API KEY in the Password?.  We will recheck that works correctly too.

**Comment by jgonzis** [comment]
> Hi,
> 
> Have tested the automatic overclocking profile switch function in the HiveOS beta releases. It seems to work with Ethash and Etcash, but not with Equihash 125/4 (tested with both "FLUX" and "NH-ZelHash" in the config arguments. Possibly a bug? Tested with both 1.59a and 1.60.
> 
> This is what i get in the miner: Applying OC equihash 125/4 with: { "message": "Empty input", "code": 400 } Recheck will be in 60 minutes
> 
> My equihash 125/4 overclocks get selected correctly with the native "auto select" function in HiveOS when I run a Flux flightsheet with the "standard" 1.60 release, so I'm sure I've set the correctly to the equihash 125/4 and zelhash algo.

I have reupload with the correction, but to been able to run it you will need to delete first the previous version running that script in the shell. 

rm /hive/miners/custom/downloads/ lolminer-1.60.SwitchHiveOS.tar.gz


Many thanks for the feedback

**Comment by gottfrede203** [comment]
> I have reupload with the correction, but to been able to run it you will need to delete first the previous version running that script in the shell.
> 
> rm /hive/miners/custom/downloads/ lolminer-1.60.SwitchHiveOS.tar.gz
> 
> Many thanks for the feedback

I can confirm that it work - well done :-)
Thank you

**Comment by jgonzis** [comment]
> 

Thx to you... a small "  was the problem
