### ISSUE TITLE
1.60 flux bug on gtx card

### ISSUE THREAD

**Issue by HONO** [Lolliedieb/lolMiner-releases#1746]
unsuported device or driver bug on gtx 1060 and gtx 1070ti

was fine before 1.60

congrat for the performance boost on rtx 30 series!! working great!

**Comment by jgonzis** [comment]
> unsuported device or driver bug on gtx 1060 and gtx 1070ti
> 
> was fine before 1.60
> 
> congrat for the performance boost on rtx 30 series!! working great!

You are right, Pascal wasn't updated the code but it should be able to mine. Let's us recheck it . Many thanks

**Comment by Lolliedieb** [comment]
Respond we will have a look and fix with 1.61 - and hopefully with better new pascal code

**Comment by cbroker1** [comment]
Same problem here, I think, lolminer (v1.60) won't mine on 1070 and 1080.

**Comment by jgonzis** [comment]
> Same problem here, I think, lolminer (v1.60) won't mine on 1070 and 1080.

Right, it has been comment in the changelog that bug and dev will look on it for next release
