### ISSUE TITLE
5600xt (asrock) CL_INVALID_WORK_GROUP_SIZE cannot mine Flux

### ISSUE THREAD

**Issue by cbroker1** [Lolliedieb/lolMiner-releases#1748]
![image](https://user-images.githubusercontent.com/43118284/194644748-fbe13be4-28d0-4943-99f9-91aa3a2cd1b7.png)

**Comment by jgonzis** [comment]
That is a fault of respect. That is not the proper group to talk about other miners.

**Comment by cbroker1** [comment]
Oh boy, embarrassing, sorry.

**Comment by jgonzis** [comment]
> Oh boy, embarrassing, sorry.

Thx for the reply... just post lolMiner issue to try to Improve it
