### ISSUE TITLE
Feature request: Dual mining FLUX + ZIL 

### ISSUE THREAD

**Issue by thaneb** [Lolliedieb/lolMiner-releases#1749]
Hello fellow developers,

it would be awesome, if we could get dual mining Flux with ZIL.

Thank you

Best Regards

**Comment by jgonzis** [comment]
Some interesting to do...

**Comment by jovicailievski** [comment]
This one whould be so awesome I agree 100%

**Comment by jgonzis** [comment]
Here it is a solution:

[https://link.medium.com/Vz9OZTN62wb](https://link.medium.com/Vz9OZTN62wb)
