### ISSUE TITLE
Web UI doesn't auto refresh on lolMiner 1.61 / 1.60.

### ISSUE THREAD

**Issue by i1itione** [Lolliedieb/lolMiner-releases#1752]
<img width="106" alt="lolminer_20221013001" src="https://user-images.githubusercontent.com/21694907/195615487-fefa717c-522b-42bc-9cb9-9d53dc34f997.png">

I tried the v1.61 and v1.60, both of them have same probelm, is it a javascript issue of lolMiner's web interface?

**Comment by jgonzis** [comment]
> <img alt="lolminer_20221013001" width="106" src="https://user-images.githubusercontent.com/21694907/195615487-fefa717c-522b-42bc-9cb9-9d53dc34f997.png">
> 
> I tried the v1.61 and v1.60, both of them have same probelm, is it a javascript issue of lolMiner's web interface?

I will need to have a look... could it be something blocking it? It has work without problems in previous releases

**Comment by i1itione** [comment]
> > <img alt="lolminer_20221013001" width="106" src="https://user-images.githubusercontent.com/21694907/195615487-fefa717c-522b-42bc-9cb9-9d53dc34f997.png">
> > I tried the v1.61 and v1.60, both of them have same probelm, is it a javascript issue of lolMiner's web interface?
> 
> I will need to have a look... could it be something blocking it? It has work without problems in previous releases

I tried disabling any adblock but the auto refresh still doesn't work.

**Comment by jgonzis** [comment]
Solved for 1.62
![image](https://user-images.githubusercontent.com/38668405/200535639-8a1dfcb3-e11a-4efe-9940-1c5ed702fde0.png)

**Comment by jgonzis** [comment]
Solved with 1.62
