### ISSUE TITLE
Please add dual mining option

### ISSUE THREAD

**Issue by Jorgelote** [Lolliedieb/lolMiner-releases#1760]
More precisely, please add dual mining option for etchash or ethash + other coins such as "Radiant", or even some different coins like "AE" or "BTG" maybe some "Equihash" coin too like: "AION" or "Zhash/KOMODO", those ask for "Core Power mostly", at this times, there is not enough with only mining etc or ethw or AE, if there was a way to tune the other algos with etchash/ethash it would be great just to earn a little more at least.
ALPH and KASPA are getting higher hashrates and they can't handle all the miners, but if there was more dual mineable coins it will spread the hashrates and be more profitable all of them. 
I know that's a looot of work i am asking for, but it would spread some hashrate and all miners would be happy about it

**Comment by jgonzis** [comment]
Problem is that all the algos you comment are mixt between memory and Core, so really hard to combine duals there.
