### ISSUE TITLE
Option Not Returning Anything

### ISSUE THREAD

**Issue by djlaserman** [Lolliedieb/lolMiner-releases#1768]
running the command option "--list-devices" returns nothing but the logo and a list of algorithms ending by 'made by Lolliedieb, October 2022'

I think it should rather enumerate supported hardware found on the system like the CPU and GPUs instead....

C:\Users\redacted\AppData\Local\Programs\unmineable-miner-mfi\resources\miners\win32\lolMiner_1.61>lolminer --list-devices
+---------------------------------------------------------+
|     _       _ __  __ _                   _   __   _     |
|    | | ___ | |  \/  (_)_ __   ___ _ __  / | / /_ / |    |
|    | |/ _ \| | |\/| | | '_ \ / _ \ '__| | || '_ \| |    |
|    | | (_) | | |  | | | | | |  __/ |    | || (_) | |    |
|    |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)___/|_|    |
|                                                         |
|              This software is for mining                |
|              Autolykos V2                               |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash III                               |
|              Flux (ZelHash)                             |
|              kHeavyhash (Kaspa)                         |
|              Blake3 (Alephium)                          |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|            Made by Lolliedieb, October 2022             |
+---------------------------------------------------------+

C:\Users\redacted\AppData\Local\Programs\unmineable-miner-mfi\resources\miners\win32\lolMiner_1.61>

**Comment by Lolliedieb** [comment]
Just fixed in 1.62 development build. Issue was appearing only in --list-devices (not on normal mining) and only if Nvidia GPUs were present.

**Comment by djlaserman** [comment]
> Just fixed in 1.62 development build. Issue was appearing only in --list-devices (not on normal mining) and only if Nvidia GPUs were present.

Ok thanks, FYI I have no Nvidia GPU but an AMD RX 580 Sapphire... however I appreciate your sense of urgency in ironing out the issues. God bless
