### ISSUE TITLE
40% invalid/stale 1.61 > 1.62

### ISSUE THREAD

**Issue by derp55555** [Lolliedieb/lolMiner-releases#1776]
Changed nothing except 1.61 > 1.62 , getting 40% invalid/stale (0% before) when dual mining ethash/kas on 3090/3080/3070

edit: the invalid/stale are on the KAS shares not the ethash algo.

**Comment by jgonzis** [comment]
> Changed nothing except 1.61 > 1.62 , getting 40% invalid/stale (0% before) when dual mining ethash/kas on 3090/3080/3070
> 
> edit: the invalid/stale are on the KAS shares not the ethash algo.

Working on it... better stay for Dual in Windows in 1.61

**Comment by jgonzis** [comment]
> Changed nothing except 1.61 > 1.62 , getting 40% invalid/stale (0% before) when dual mining ethash/kas on 3090/3080/3070
> 
> edit: the invalid/stale are on the KAS shares not the ethash algo.

Just to confirm acc-pool right?

**Comment by derp55555** [comment]
> > Changed nothing except 1.61 > 1.62 , getting 40% invalid/stale (0% before) when dual mining ethash/kas on 3090/3080/3070
> > edit: the invalid/stale are on the KAS shares not the ethash algo.
> 
> Just to confirm acc-pool right?

https://kaspa-pool.org

**Comment by jgonzis** [comment]
Ok thx the other with that problems... acc-pool and Kaspa-pool... working on it at the moment

**Comment by Lolliedieb** [comment]
Fixed with the re-upload of 1.62 later that day
