### ISSUE TITLE
High CPU usage because of firewall lock

### ISSUE THREAD

**Issue by zeroua** [Lolliedieb/lolMiner-releases#1777]
App works fine with allowed connections to main pool and dev pool (wooly).

But it also tries to connect to 116.203.44.184 or 78.47.18.128 and when you block these connections in firewall - app makes about 10000 retries per second to reconnect, which causes significant load on CPU.

Can you make some timeout between retries?

This is count of blocked tries in last 5 minutes
![egui_G9ggNRNyZ5](https://user-images.githubusercontent.com/10744153/202004695-55e41d74-d7ac-4d90-be6e-2282f3f1f481.png)

**Comment by jgonzis** [comment]
> 116.203.44.184

That is the mail ip of Woolypool pool.woolypooly.com(116.203.44.184) .. if you lock it is normal the retry...
