### ISSUE TITLE
Kaspa only crashing or rebooting on 1.62 & 1.63 for Nvidia A4000

### ISSUE THREAD

**Issue by gatesl** [Lolliedieb/lolMiner-releases#1787]
No issues on 1.60, but 1.62 and 1.63 started crashing or failing reboot.

[crashlog](https://gist.github.com/gatesl/5b83c0139580f932e9925ac1feeea6d2), [dmesg](https://gist.github.com/gatesl/99eddf3cae145260aa15ed0134c8f426), [crashlog2](https://gist.github.com/gatesl/873f24629932f6890c59a9e6bc0befd8)

**Comment by jgonzis** [comment]
It seems applying OC from the OS. Could you just run the --mclk 810 and --cclk value? I didn't see that values in the start of 1.62-1.63. How it is applied that?

**Comment by Lolliedieb** [comment]
The code changes in 1.62 and 1.63 made the codes a bit more sensitive towards aggressive core offset values. If you did set that, consider lowering the value a bit.

**Comment by gatesl** [comment]
With mclk 810 on the launch and letting SMOS adjust +200 for the core, it has been stable for 24 hours.

**Comment by jgonzis** [comment]
It could be a moment not more Offset is possible try a little bit lower in the 1s GPU crashed

**Comment by gatesl** [comment]
Reproduced with 1.64 and +100 for the core.  Now trying 0 core.
