### ISSUE TITLE
KASPA on CMP 90HX, CMP70HX

### ISSUE THREAD

**Issue by Manclarity** [Lolliedieb/lolMiner-releases#1789]
For now minign edition cards like CMP 90HXs and CMP70HXs have very low hashrate on kHeavyHash algo. I'm not sure if it's the problem of cards it self. Different dirvers don't help as well. But maybe you could make it work properly adjusting the miner.

**Comment by jgonzis** [comment]
did you try 1.63?. 

that should be solved in 1.63. It was checked by different users.

**Comment by jgonzis** [comment]
> It works somehow if set both --mclk --cclk.

CMP don't allow max Clock with Mem Clock at 810. It is a limitation of the GPU

**Comment by ovenmittromney** [comment]
> > It works somehow if set both --mclk --cclk.
> 
> CMP don't allow max Clock with Mem Clock at 810. It is a limitation of the GPU

This is wholly incorrect, stop spouting nonsense - CMPs simply don't have a mState between idle and full power in the bios, and 810 is above idle. CMP idle clock is 405mhz. Command that and they run in 0 memstate.
