### ISSUE TITLE
Kaspa overclocking error

### ISSUE THREAD

**Issue by Heaven20222022** [Lolliedieb/lolMiner-releases#1790]
Please help me see where the problem is What's wrong with overclocking editing。
![微信图片_20221125204110](https://user-images.githubusercontent.com/99574545/203994962-96621911-f537-4b5b-a0d1-c2831253ef6c.jpg)
![微信图片_20221125204132](https://user-images.githubusercontent.com/99574545/203994975-3c22f961-6aa3-4230-8764-60ee0def9580.jpg)
![微信图片_20221125204145](https://user-images.githubusercontent.com/99574545/203994980-1e09602e-0e3b-48d1-8381-88728cc92c48.jpg)

**Comment by Heaven20222022** [comment]
The first one is not overclocked
The second and third sheets are overclocked and run incorrectly.

**Comment by jgonzis** [comment]
But that is normal... lolMiner don't modify OC of the GPUs. That is why it doesn't go. Where did you get that parameters from the github?
