### ISSUE TITLE
KASPA MINING RX 570

### ISSUE THREAD

**Issue by hany-mamdoh** [Lolliedieb/lolMiner-releases#1792]
Please we need to improve KASPA mining hashrate for old cards 4GB RX 570/580 and also with higher effeciency 
as it become useless now

**Comment by Lolliedieb** [comment]
Not a miner issue in that sense. I feel sorry, but the architecture unfortunately does not have a lot of features the new rdna2 GPUs or Nvidia Turing / Ampere has ... just instructions missing in the feature set that Kaspa can profit from. Therefore there can not be a real fix for this.
