### ISSUE TITLE
why is the wattage not showing? what's the solution?

### ISSUE THREAD

**Issue by btarapranovosakti** [Lolliedieb/lolMiner-releases#1794]
<img width="1440" alt="Screen Shot 2022-12-01 at 00 41 55" src="https://user-images.githubusercontent.com/119527443/204871026-53646e7d-9e0c-4702-8159-a5df30e0d5b5.png">

**Comment by jgonzis** [comment]
> <img alt="Screen Shot 2022-12-01 at 00 41 55" width="1440" src="https://user-images.githubusercontent.com/119527443/204871026-53646e7d-9e0c-4702-8159-a5df30e0d5b5.png">

That normally is that the nvml driver is not in the proper folder. I recommend you to do a fresh install with also Drivers 522. So then you will have also automatic unlock of the GPU.
