### ISSUE TITLE
slow down/lag/stuttering when moving windows around while mining

### ISSUE THREAD

**Issue by ib99** [Lolliedieb/lolMiner-releases#1795]
The miner works really well! 
But during mining Windows lags a lot. Even scrolling web pages or moving any windows around it just lags so much.
Win11, 6800XT.
CPU usage: 2%, RAM: 11gb used out of 32gb.

**Comment by jgonzis** [comment]
> The miner works really well! But during mining Windows lags a lot. Even scrolling web pages or moving any windows around it just lags so much. Win11, 6800XT. CPU usage: 2%, RAM: 11gb used out of 32gb.

Problem is the high usage that is done from the GPU to mine. IT is not a CPU issue, it is the transfer from the CPU to the GPU... you can try to put lower priority to the miner. To don't collpase your GPU that is running at max usage of the limitation.
