### ISSUE TITLE
Why pool hashrate is lower than local (about 3 percent).

### ISSUE THREAD

**Issue by i1itione** [Lolliedieb/lolMiner-releases#1796]
I use Hive OS and lolMiner 1.63, I noticed the pool hashrate is lower than local, is it normal?

<img width="387" alt="lolminer-20221201001" src="https://user-images.githubusercontent.com/21694907/204932315-e4a1fe1a-98dc-4a96-a16e-2792c27ad0a1.png">

I check the accepted speed at NiceHash, it almost equals to the pool hashrate showed on lolMiner indeed.

**Comment by jgonzis** [comment]
> I use Hive OS and lolMiner 1.63, I noticed the pool hashrate is lower than local, is it normal?
> 
> <img alt="lolminer-20221201001" width="387" src="https://user-images.githubusercontent.com/21694907/204932315-e4a1fe1a-98dc-4a96-a16e-2792c27ad0a1.png">
> 
> I check the accepted speed at NiceHash, it almost equals to the pool hashrate showed on lolMiner indeed.

You have 0.75% Fee that has to be taken out., And later enters two effects:

- Nicehash is a PPS pool where people can buy your hash and that make it to swap to another pool, that is time is lost, between connections. 
- Luck effect, with 10K Shares the Luck it is +-3%... so you are in line if you deduce the Fee 0.75% + Connection to other Pool from renting your hash + Luck Effect
-
