### ISSUE TITLE
Losing connection then server not reachable

### ISSUE THREAD

**Issue by rluik** [Lolliedieb/lolMiner-releases#1797]
Miner (or internet, or pool) stops working properly (connection to pool lost) then it mines at 0 MH/s and doesn't reconnect when the connection/pool recovers, restarting the miner it's able to connect to the pool.

lolMiner 1.63 Windows 11
Kaspa single mode
Tested at Woolypooly and Herominers

**Comment by jgonzis** [comment]
> Miner (or internet, or pool) stops working properly (connection to pool lost) then it mines at 0 MH/s and doesn't reconnect when the connection/pool recovers, restarting the miner it's able to connect to the pool.
> 
> lolMiner 1.63 Windows 11 Kaspa single mode Tested at Woolypooly and Herominers

You can try to add the watchdog bat file, to recover in case of Mhs... or add failsafe pool so you can have 2 polls in case 1 stop.
