### ISSUE TITLE
Can't mine 4G, is it because of my onboard videocard?

### ISSUE THREAD

**Issue by JonathanLachapelle** [Lolliedieb/lolMiner-releases#180]
The DAG size is 4152 Mbyte which is over the Memory of 4096 of my GTX 1050TI

Setup Miner...
Device 0:
    Name:    GeForce GTX 1050 Ti
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  4096 MByte
    --4g-alloc-size 4024
    Max epoch (approx): 375
    Active:  true (Selected Algorithm: ETHash)
Device 1:
    Name:    Intel(R) HD Graphics 4600
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Memory:  1629 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to us1.ethermine.org:14444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
New job received: 0x8380fd Epoch: 391 Target: 0000000112e0be82
-------------------------------------------------------
         Generating light cache for epoch 391
-------------------------------------------------------
Start Mining...
New job received: 0x472dcc Epoch: 391 Target: 0000000112e0be82
-------------------------------------------------------
     Done (2644 ms), size of new DAG: 4152 MByte
-------------------------------------------------------
GPU 0: insufficient memory for DAG epoch 391.
GPU 0: will be in Zombie mode with reduced hashrate.
GPU 0: Allocation of DAG failed with error: Memory object allocation failure
GPU 0: will be stopped.

**Comment by jgonzis** [comment]
with the 4Gb is complicated to mine unless you are in Linux... also now is better to use the ETC with that 4GB... you also select 4024, and in Linux you are able sometime to get 4080...  Also your card will not give a high Mhs in Linux too...
