### ISSUE TITLE
[FEATURE REQUEST] 0 mh/s auto restart

### ISSUE THREAD

**Issue by MitchellTN** [Lolliedieb/lolMiner-releases#181]
After running the program for several hours it will sometimes randomly just slow to 0 mh/s but continue to receive new jobs. The problem is easily fixed by simply restarting the program, however this is very inefficient because the user needs to constantly check the status of the program. A presumably quick solution would be to add an option that automatically restarts the program if it detects an average speed of 0 mh/s.

**Comment by JonathanLachapelle** [comment]
Excellent idea and probably fairly easy to implement

**Comment by qq932480666** [comment]
Good idea, but it should not be 0 mh/s. Setting 1 mh/s is the ideal choice because the wrong initial speed is greater than 0 mh/s and less than 1 mh/s.
![image](https://user-images.githubusercontent.com/69789399/105946301-f157db00-60a1-11eb-849c-41379580e752.png)

**Comment by jgonzis** [comment]
An easy solution that will detect if miner crash or miner is 0... is to use this bat file...  instead of the mine_eth.bat 

It will check in the API of the miner if it is working or not each 120seconds... I hope it helps :-) fell free to inform if not works to try to do it better


@echo off

setlocal enableDelayedExpansion
set url=http://127.0.0.1:4444
set file=lolMiner.json
set tmpfile=Perfomance.json

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

:loop
REM start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444


:mining
timeout 120
type NUL > %file%
type NUL > %tmpfile%
echo Proving Stats, press CTRL-C and Y to Quit!
certutil -urlcache -split -f %url% %file%

fc %file% %tmpfile% > nul
if errorlevel 1 (goto online) else (goto crash)

:online
findstr "Performance_Summary" %file% > %tmpfile%


FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x

for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)

:restart
echo "Killing Process"
taskkill /IM "lolMiner.exe" /F
echo "Restarting lolMiner"
goto loop

:crash
echo "LolMiner Not Running, restarting lolMiner"
goto loop

**Comment by bobbybean** [comment]
I tried this bat, but get this  [https://ibb.co/qRmkxWV](url)

The only parameters I changed was the pool and wallet. nothing else. When I start it windows trigered a warning, so I also disabled it temporarily to try. Still doesn't work. WHata am I doing wrong? 

My issue: Goes to 0mh/s sometimes after 30 minutes, 12 hours etc.

**Comment by jgonzis** [comment]
> I tried this bat, but get this [https://ibb.co/qRmkxWV](url)
> 
> The only parameters I changed was the pool and wallet. nothing else. When I start it windows trigered a warning, so I also disabled it temporarily to try. Still doesn't work. WHata am I doing wrong?
> 
> My issue: Goes to 0mh/s sometimes after 30 minutes, 12 hours etc.
I think I know the problem... my complete fault sorry... 

REM start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444 --》 start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444

Remove the REM that means not to launch sorry sorry sorry

**Comment by CCWBee** [comment]
Seems to work only i'm getting access denied, i know it has to do with permissions but not sure which, any idea?

**Comment by jgonzis** [comment]
> Seems to work only i'm getting access denied, i know it has to do with permissions but not sure which, any idea?

The problem is the Windows Defender Virus. It detect it as a Virus... unless you stop it or accept the file it won't let you mine in Windows

**Comment by thedavidtran** [comment]
Appears it starts a new session (in windows 10), doesn't close the existing window when I try the above script

**Comment by Firesuko** [comment]
> An easy solution that will detect if miner crash or miner is 0... is to use this bat file... instead of the mine_eth.bat
> 
> It will check in the API of the miner if it is working or not each 120seconds... I hope it helps :-) fell free to inform if not works to try to do it better
> 
> @echo off
> 
> setlocal enableDelayedExpansion
> set url=http://127.0.0.1:4444
> set file=lolMiner.json
> set tmpfile=Perfomance.json
> 
> Rem #################################
> Rem ## Begin of user-editable part ##
> Rem #################################
> 
> set "POOL=eth.2miners.com:2020"
> set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"
> 
> Rem #################################
> Rem ## End of user-editable part ##
> Rem #################################
> 
> :loop
> start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444
> 
> :mining
> timeout 120
> type NUL > %file%
> type NUL > %tmpfile%
> echo Proving Stats, press CTRL-C and Y to Quit!
> certutil -urlcache -split -f %url% %file%
> 
> fc %file% %tmpfile% > nul
> if errorlevel 1 (goto online) else (goto crash)
> 
> :online
> findstr "Performance_Summary" %file% > %tmpfile%
> 
> FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x
> 
> for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
> if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)
> 
> :restart
> echo "Killing Process"
> taskkill /IM "lolMiner.exe" /F
> echo "Restarting lolMiner"
> goto loop
> 
> :crash
> echo "LolMiner Not Running, restarting lolMiner"
> goto loop

okay so every time i add this into the batch file 
set url=http://127.0.0.1:4444
set file=lolMiner.json
set tmpfile=Perfomance.json
i get a error tab saying this is not recognized by internal or external use so what am i to pose to do?

**Comment by jgonzis** [comment]
> > An easy solution that will detect if miner crash or miner is 0... is to use this bat file... instead of the mine_eth.bat
> > It will check in the API of the miner if it is working or not each 120seconds... I hope it helps :-) fell free to inform if not works to try to do it better
> > @echo off
> > setlocal enableDelayedExpansion
> > set url=http://127.0.0.1:4444
> > set file=lolMiner.json
> > set tmpfile=Perfomance.json
> > Rem #################################
> > Rem ## Begin of user-editable part ##
> > Rem #################################
> > set "POOL=eth.2miners.com:2020"
> > set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"
> > Rem #################################
> > Rem ## End of user-editable part ##
> > Rem #################################
> > :loop
> > start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444
> > :mining
> > timeout 120
> > type NUL > %file%
> > type NUL > %tmpfile%
> > echo Proving Stats, press CTRL-C and Y to Quit!
> > certutil -urlcache -split -f %url% %file%
> > fc %file% %tmpfile% > nul
> > if errorlevel 1 (goto online) else (goto crash)
> > :online
> > findstr "Performance_Summary" %file% > %tmpfile%
> > FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x
> > for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
> > if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)
> > :restart
> > echo "Killing Process"
> > taskkill /IM "lolMiner.exe" /F
> > echo "Restarting lolMiner"
> > goto loop
> > :crash
> > echo "LolMiner Not Running, restarting lolMiner"
> > goto loop
> 
> okay so every time i add this into the batch file
> set url=http://127.0.0.1:4444
> set file=lolMiner.json
> set tmpfile=Perfomance.json
> i get a error tab saying this is not recognized by internal or external use so what am i to pose to do?

Could you try last 1.28a?  With new update that  should be solve it

**Comment by jgonzis** [comment]
That should be solved with new Cuda Solver releases and watchdog

**Comment by kingtut39** [comment]
@jgonzis I tried the above script on 1.32a and sometime when it is checking if lolminer is running it shows "access denied" and then starts a new instance of the miner while the other instance is still running fine. Nothing is getting blocked by AV or firewall so for now I have gone back to the default mine_eth.bat. Is there an update to the above script or is there a simple way to add a loop into the default mine_eth.bat?

**Comment by jgonzis** [comment]
> @jgonzis I tried the above script on 1.32a and sometime when it is checking if lolminer is running it shows "access denied" and then starts a new instance of the miner while the other instance is still running fine. Nothing is getting blocked by AV or firewall so for now I have gone back to the default mine_eth.bat. Is there an update to the above script or is there a simple way to add a loop into the default mine_eth.bat?

 bat files still contain a fail... create a file direct in:

http://lolminer.byethost16.com/

And it will as normal
