### ISSUE TITLE
lolMiner 1.64 Windows: Ethash & Kaspa not working on AMD RDNA1 cards (tested with RX5700)

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1810]
Your answer:
> It seems you have too much undervolt on that 5700, could you increase the Core Voltage?

No undervolting or OC.
Other miners do not have any issues with my voltage / clock settings.

Please do not close issues as resolved until they really solved. Thank you.

DAGs are getting built, but no hash rates:

`lolminer.exe --algo ETHASH --dualmode KASPADUAL --pool daggerhashimoto.auto.nicehash.com:443 --user ********************************.************* --pass x --tls on --dualpool kheavyhash.auto.nicehash.com:443 --dualuser ********************************.************* --dualpass x --dualtls on --ethstratum ETHV1 --log off --apiport 4001 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1`

```
Connecting to pool...
DNS over HTTPS resolve succeeded
DNS over HTTPS resolve succeeded
Connected to kheavyhash.auto.nicehash.com(34.117.82.207):443  (TLS enabled)
Connected to daggerhashimoto.auto.nicehash.com(34.149.10.66):443  (TLS enabled)
TLS Handshake success
TLS Handshake success
Set Ethash stratum mode: EthereumStratum/1.0.0
New extra nonce received: 5e7e32
Subscribed to stratum server
Authorized worker: 33hZYX8iFg5zm9E3geqrNgeP6TMzszZk5R
Authorized worker: 33hZYX8iFg5zm9E3geqrNgeP6TMzszZk5R.Blackbox
New target received: 000000029994e5b0 (Diff 0.384626)
New job received: 000000009fecf0eb Epoch: 535 Difficulty: 1.65G
New target received: 00000000259e0445 (Diff 6.805388)
Subscribed to extranonce
Start Mining...
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
-------------------------------------------------------
          Generated light cache for epoch 535
       Took 2503 ms, size of new DAG: 5303 MByte
-------------------------------------------------------
GPU 1: Starting DAG generation (normal mode)
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
-----------------------------------------------
Statistics (10:10:52); Uptime: 0h 0m 7s
lolMiner 1.64, Nvidia 522.25, AMD CL 3444.0, Api port 4001
Algorithm 1: Ethash
Connected to: daggerhashimoto.auto.nicehash.com:443
Algorithm 2: HeavyHash-Kaspa
Connected to: kheavyhash.auto.nicehash.com:443

      Name           Speed      Pool  Shares   Best    Eff.      Speed      Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
                      Mh/s      Mh/s  A/S/Hw  Share  Mh/s/W       Mh/s      Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
GPU 1 RX 5700 XT -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   10.0     6   200    30    31    32   43  0.00
---------------------------
Total            -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   10.0
-----------------------------------------------
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
New extra nonce received: c4f47d
New target received: 00000000259e0445 (Diff 6.805388)
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
New job received: 000000009fecf0ec Epoch: 535 Difficulty: 1.65G
New job received: 000000009fecf0ed Epoch: 535 Difficulty: 1.65G
-----------------------------------------------
Statistics (10:10:57); Uptime: 0h 0m 12s
lolMiner 1.64, Nvidia 522.25, AMD CL 3444.0, Api port 4001
Algorithm 1: Ethash
Connected to: daggerhashimoto.auto.nicehash.com:443
Algorithm 2: HeavyHash-Kaspa
Connected to: kheavyhash.auto.nicehash.com:443

      Name           Speed      Pool  Shares   Best    Eff.      Speed      Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
                      Mh/s      Mh/s  A/S/Hw  Share  Mh/s/W       Mh/s      Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
GPU 1 RX 5700 XT -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   54.0  1588  1836    37    51    54   43  0.00
---------------------------
Total            -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   54.0
-----------------------------------------------
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
GPU 1: DAG generation completed (7650 ms)
GPU 1: DAG verification passed
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s

[...]

Algorithm 1: Ethash
Connected to: daggerhashimoto.auto.nicehash.com:443
Algorithm 2: HeavyHash-Kaspa
Connected to: kheavyhash.auto.nicehash.com:443

      Name          Speed      Pool  Shares   Best    Eff.     Speed      Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
                     Mh/s      Mh/s  A/S/Hw  Share  Mh/s/W      Mh/s      Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
GPU 1 RX 5700 XT 0.000000  0.000000   0/0/0    0.0   0.000  0.000000  0.000000     0/0    0.0   0.000   73.4  2007   200    39    52    38   43  0.00
---------------------------
Total            0.000000  0.000000   0/0/0    0.0   0.000  0.000000  0.000000     0/0    0.0   0.000   73.4
-----------------------------------------------
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
New job received: 000000009fecf0fb Epoch: 535 Difficulty: 1.65G
Ethash: Average speed (1s): 0.000000 Mh/s
HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
Device 1 detected as crashed.
Closing miner with exit code 42 (--watchdog close).
``

**Comment by jgonzis** [comment]
> Your answer:
> 
> > It seems you have too much undervolt on that 5700, could you increase the Core Voltage?
> 
> No undervolting or OC. Other miners do not have any issues with my voltage / clock settings.
> 
> Please do not close issues as resolved until they really solved. Thank you.
> 
> DAGs are getting built, but no hash rates:
> 
> `lolminer.exe --algo ETHASH --dualmode KASPADUAL --pool daggerhashimoto.auto.nicehash.com:443 --user ********************************.************* --pass x --tls on --dualpool kheavyhash.auto.nicehash.com:443 --dualuser ********************************.************* --dualpass x --dualtls on --ethstratum ETHV1 --log off --apiport 4001 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1`
> 
> ```
> Connecting to pool...
> DNS over HTTPS resolve succeeded
> DNS over HTTPS resolve succeeded
> Connected to kheavyhash.auto.nicehash.com(34.117.82.207):443  (TLS enabled)
> Connected to daggerhashimoto.auto.nicehash.com(34.149.10.66):443  (TLS enabled)
> TLS Handshake success
> TLS Handshake success
> Set Ethash stratum mode: EthereumStratum/1.0.0
> New extra nonce received: 5e7e32
> Subscribed to stratum server
> Authorized worker: 33hZYX8iFg5zm9E3geqrNgeP6TMzszZk5R
> Authorized worker: 33hZYX8iFg5zm9E3geqrNgeP6TMzszZk5R.Blackbox
> New target received: 000000029994e5b0 (Diff 0.384626)
> New job received: 000000009fecf0eb Epoch: 535 Difficulty: 1.65G
> New target received: 00000000259e0445 (Diff 6.805388)
> Subscribed to extranonce
> Start Mining...
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> -------------------------------------------------------
>           Generated light cache for epoch 535
>        Took 2503 ms, size of new DAG: 5303 MByte
> -------------------------------------------------------
> GPU 1: Starting DAG generation (normal mode)
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> -----------------------------------------------
> Statistics (10:10:52); Uptime: 0h 0m 7s
> lolMiner 1.64, Nvidia 522.25, AMD CL 3444.0, Api port 4001
> Algorithm 1: Ethash
> Connected to: daggerhashimoto.auto.nicehash.com:443
> Algorithm 2: HeavyHash-Kaspa
> Connected to: kheavyhash.auto.nicehash.com:443
> 
>       Name           Speed      Pool  Shares   Best    Eff.      Speed      Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
>                       Mh/s      Mh/s  A/S/Hw  Share  Mh/s/W       Mh/s      Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
> GPU 1 RX 5700 XT -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   10.0     6   200    30    31    32   43  0.00
> ---------------------------
> Total            -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   10.0
> -----------------------------------------------
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> New extra nonce received: c4f47d
> New target received: 00000000259e0445 (Diff 6.805388)
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> New job received: 000000009fecf0ec Epoch: 535 Difficulty: 1.65G
> New job received: 000000009fecf0ed Epoch: 535 Difficulty: 1.65G
> -----------------------------------------------
> Statistics (10:10:57); Uptime: 0h 0m 12s
> lolMiner 1.64, Nvidia 522.25, AMD CL 3444.0, Api port 4001
> Algorithm 1: Ethash
> Connected to: daggerhashimoto.auto.nicehash.com:443
> Algorithm 2: HeavyHash-Kaspa
> Connected to: kheavyhash.auto.nicehash.com:443
> 
>       Name           Speed      Pool  Shares   Best    Eff.      Speed      Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
>                       Mh/s      Mh/s  A/S/Hw  Share  Mh/s/W       Mh/s      Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
> GPU 1 RX 5700 XT -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   54.0  1588  1836    37    51    54   43  0.00
> ---------------------------
> Total            -nan(ind)  0.000000   0/0/0    0.0   0.000  -nan(ind)  0.000000     0/0    0.0   0.000   54.0
> -----------------------------------------------
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> GPU 1: DAG generation completed (7650 ms)
> GPU 1: DAG verification passed
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> 
> [...]
> 
> Algorithm 1: Ethash
> Connected to: daggerhashimoto.auto.nicehash.com:443
> Algorithm 2: HeavyHash-Kaspa
> Connected to: kheavyhash.auto.nicehash.com:443
> 
>       Name          Speed      Pool  Shares   Best    Eff.     Speed      Pool  Shares   Best    Eff.  Power  CCLK  MCLK  Core  Junc   Mem  Fan  Dual
>                      Mh/s      Mh/s  A/S/Hw  Share  Mh/s/W      Mh/s      Mh/s     A/R  Share  Mh/s/W      W   MHz   MHz  Temp  Temp  Temp  Pct   Fct
> GPU 1 RX 5700 XT 0.000000  0.000000   0/0/0    0.0   0.000  0.000000  0.000000     0/0    0.0   0.000   73.4  2007   200    39    52    38   43  0.00
> ---------------------------
> Total            0.000000  0.000000   0/0/0    0.0   0.000  0.000000  0.000000     0/0    0.0   0.000   73.4
> -----------------------------------------------
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> New job received: 000000009fecf0fb Epoch: 535 Difficulty: 1.65G
> Ethash: Average speed (1s): 0.000000 Mh/s
> HeavyHash-Kaspa: Average speed (1s): 0.000000 Mh/s
> Device 1 detected as crashed.
> Closing miner with exit code 42 (--watchdog close).
> ``
>  
> ```

it connects correctly but crash the GPU without generating the DAG.... That is AMD Driver too new or OC. I close them because is easy to get notifiy later when you answer it.

**Comment by UselessGuru** [comment]
I tried again with out watchdog.

I can confirm that Ethash DAG gets created successfully.
GPU does not crash - however mem clock drops to 200MHz as soon as Ethash DAG is complete.
I tried increasing core voltage and/or power limit, but still the same problem.
RX580 works fine.

**Comment by jgonzis** [comment]
And With older versions??

**Comment by UselessGuru** [comment]
>> And With older versions??
Not tried.
All other miners (Gminer, TeamBlackMiner, SRBMiner etc.) work fine with my current config.
Also lolMiner works fine on RX5700 with all other tested algos (Autolykos, Beam, Cuckoo29, Cockatoo31/32, Equihash1254, Equihash1927, Equihas1445, EtcHash, Ethash, Ubqhash, Kaspa)

**Comment by jgonzis** [comment]
Well in dual mining only SRBMiner can do it...

**Comment by UselessGuru** [comment]
> only SRBMiner can do it for 5700XT in Kaspa and with Nicehash no other

Are you saying that lolMiner cannot dual mine Ethash & Kaspa on RX5700 in windows?

**Comment by UselessGuru** [comment]
Same issue with 1.65

**Comment by jgonzis** [comment]
Could you try without the short stats? It seems a GPU crash when clock goes from 15xxx to 20xx and memory down to 200. 

Also give a try with a pendrivre in a mining OS, could be interesting to see if there works
