### ISSUE TITLE
1.64 GPU Crashes on Kaspa ~3 hour mark 

### ISSUE THREAD

**Issue by mrschu87** [Lolliedieb/lolMiner-releases#1815]
Around the 3 hours mark have a 3060v2 LHR on one rig and a 3080ti on another rig crash after about ~3 hours of operation. Rigs include a mix of 3090, 3080ti, 3080, 3070ti, 3060ti, 3060v2 all LHR.  Using 1470 Locked Core, 200 core offset, and 810 memory lock.  Have played with reducing core offset to zero but same pattern seems to continue just longer duration until the next incident.  Have turned on logging.

Unrecoverable error by GPU 3.
Please check your OC & UV settings on this card.
Device 3 detected as crashed.    

Nvidia Drivers: 522.25

Tried --watchdog exit on command prompt and it did not restart the miner to continue mining (had to quick off manually)

Trying the Nvidia 8 December drivers next to see if that helps with stability.

**Comment by wen936988** [comment]
Me too. After running for a few hours, it will not move. You must turn it off and on again.

**Comment by dawidmosk** [comment]
Same issue here, after few hours gui stop responding and freeze console. Restart app helps for some time.

**Comment by Kostas-13** [comment]
After updating to 527.56 I had crashes on Kaspa as well..
I rolled back to 527.37-desktop-win10-win11-64bit-international-dch-whql
and everything is rock stable (As before).

**Comment by jgonzis** [comment]
> Around the 3 hours mark have a 3060v2 LHR on one rig and a 3080ti on another rig crash after about ~3 hours of operation. Rigs include a mix of 3090, 3080ti, 3080, 3070ti, 3060ti, 3060v2 all LHR. Using 1470 Locked Core, 200 core offset, and 810 memory lock. Have played with reducing core offset to zero but same pattern seems to continue just longer duration until the next incident. Have turned on logging.
> 
> Unrecoverable error by GPU 3. Please check your OC & UV settings on this card. Device 3 detected as crashed.
> 
> Nvidia Drivers: 522.25
> 
> Tried --watchdog exit on command prompt and it did not restart the miner to continue mining (had to quick off manually)
> 
> Trying the Nvidia 8 December drivers next to see if that helps with stability.

Reduce the core offset of the indicate gpu, that is the problem
