### ISSUE TITLE
LOLminer stats

### ISSUE THREAD

**Issue by tade94** [Lolliedieb/lolMiner-releases#1817]
In other miner I can see how much Watts a gpu consuming and what is the efficiency. But in lol miner power column it's show "n.a." and efficiency "n.a.". I'm using Nvidia GPUs. Please help how can I resolve this problem.

**Comment by auroracoin** [comment]
It should show them like this.     https://imgur.com/1HefkIp

**Comment by jgonzis** [comment]
> tade94

That is a problem of nvml it is not proper installed. Do a ddu or check where you have the nvml.dll
