### ISSUE TITLE
AMD 21.1.1 drivers failure

### ISSUE THREAD

**Issue by cerberuscrypto** [Lolliedieb/lolMiner-releases#182]
Miner was at version 1.20 working fine on older AMD drivers but with recent 21.1.1 update from AMD miner no longer recognises driver version and will not start. Tested rig with other mining sw and works ok on these drivers. Any chance we can get an update to support the new 21.1.1 and drivers? Hash rates are improved on them.

**Comment by jgonzis** [comment]
How is hashrate improved in the new version?

**Comment by Keimling27** [comment]
Which gpu you use -- if you use rx580 you must use old mining driver from amd crimson --the new driver all unstable

**Comment by jgonzis** [comment]
I was very happy with version 20.4.2... it was really working well

**Comment by Lolliedieb** [comment]
Can you run clinfo.exe (is shipped with amd drivers) and paste the output here? I will check it and see if I can provide a quick fix with next release.

**Comment by jgonzis** [comment]
Solved with new releases
