### ISSUE TITLE
Info like Fan speed, Power and Efficiency not displayed

### ISSUE THREAD

**Issue by BenjixLeGaulois** [Lolliedieb/lolMiner-releases#1822]
Hi,
I am using lolminer 1.65 on Windows with latest Nvidia drivers installed using Geforce Experience.
Some info like fan speed, power and efficiency are not displayed properly (I get err and N/A instead).
I have read that it may be related to NVML and bad driver installation, but installation of the last driver version was achieved without issue, I have no warning in the device manager and such kind of info is properly displayed with other miners such as bzminer.
I would like to point out that this issue does not seem to have an impact on mining.

Can you help further with this issue?
Thanks.

**Comment by jgonzis** [comment]
> BenjixLeGaulois

Check where do you have the nvml.dll file. And check all you have are the same file as the one in c:\windows\system32

**Comment by BenjixLeGaulois** [comment]
> > BenjixLeGaulois
> 
> Check where do you have the nvml.dll file. And check all you have are the same file as the one in c:\windows\system32

Thanks for your reply.
My nvml.dll file is in C:\Windows\System32 as well as in C:\Program File\NVIDIA Corporation\NVSMI and in C:\minerstat-windows\cli\lib (I am using Minerstat for mining). I noticed that the timestamps for the files at the latter two locations differed from the one in C:\Windows\System32, So I just copy-pasted them, relaunched the miner and it worked like a charm.
Thanks!

**Comment by jgonzis** [comment]
> > > BenjixLeGaulois
> > 
> > 
> > Check where do you have the nvml.dll file. And check all you have are the same file as the one in c:\windows\system32
> 
> Thanks for your reply. My nvml.dll file is in C:\Windows\System32 as well as in C:\Program File\NVIDIA Corporation\NVSMI and in C:\minerstat-windows\cli\lib (I am using Minerstat for mining). I noticed that the timestamps for the files at the latter two locations differed from the one in C:\Windows\System32, So I just copy-pasted them, relaunched the miner and it worked like a charm. Thanks!

Great!!Enjoy mining
