### ISSUE TITLE
Dual mine KASPA+ZIL only

### ISSUE THREAD

**Issue by defactoambassador** [Lolliedieb/lolMiner-releases#1830]
Right now only triple mining with other coins is permitted. Dual mining just those two would be nice.

**Comment by jgonzis** [comment]
It will be soon added properly, quite soon.

**Comment by shmox75** [comment]
Hey, Any update on it ?

**Comment by jgonzis** [comment]
> Hey, Any update on it ?


You have temporarily that solution:


https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL
