### ISSUE TITLE
50hx can't lock memory to 405

### ISSUE THREAD

**Issue by icelove88** [Lolliedieb/lolMiner-releases#1831]
50hx only can lock memory to 5000

**Comment by jgonzis** [comment]
It is complete normal because it doesn't have that state the 50hx series. Is not a lolMiner problem, it is a Nvidia Problem that doesn't allow that state

**Comment by icelove88** [comment]
50HX, 
C:\Users\Administrator>nvidia-smi -i 0 --query-supported-clocks mem --format=csv,noheader
7001 MHz
5001 MHz
405 MHz

**Comment by jgonzis** [comment]
> 50HX, C:\Users\Administrator>nvidia-smi -i 0 --query-supported-clocks mem --format=csv,noheader 7001 MHz 5001 MHz 405 MHz

Then try to run lolMiner with admite privileges or try with an admin command Windows nvidia-smi -lmc values if nvidia-smi doesn't lock it will not do it lolMiner, both call same nvidia function
