### ISSUE TITLE
Core clock offset # not applied.

### ISSUE THREAD

**Issue by Xefier** [Lolliedieb/lolMiner-releases#1837]
When I try to use --coff in Hive OS on my 3070 rig mining NEXA I get the message
"core clock offset # not applied" where # is whatever clock offset I set and I've tried many different numbers.

**Comment by tomekmak** [comment]
same here.

**Comment by constantinstr** [comment]
The same thing happens to me on 2 different rigs with rtx 3080 3090 and 3060 mixed boards. When using the --coff 215,215,215,255 command, it appears not applied in the miner.

**Comment by Xefier** [comment]
Turns out I had to upgrade my nvidia drivers

**Comment by constantinstr** [comment]
> Turns out I had to upgrade my nvidia drivers

Versión driver ?

**Comment by tomekmak** [comment]
> Turns out I had to upgrade my nvidia drivers

Which version of drivers ?

**Comment by amillerpax8** [comment]
@tomekmak @constantinstr I was also having this issue and confirmed just now that moving to the newest version on HiveOS solved it. The driver version was 525.85.05

**Comment by Beiga11** [comment]
This was happening to me on Windows even with the latest drivers (531) and the issue was that I was not running the miner in admin mode. Running in admin mode solved it

**Comment by Beiga11** [comment]
This was happening to me on Windows even with the latest drivers (531) and the issue was that I was not running the miner in admin mode. Running in admin mode solved it

**Comment by Beiga11** [comment]
This was happening to me on Windows even with the latest drivers (531) and the issue was that I was not running the miner in admin mode. Running in admin mode solved it
