### ISSUE TITLE
lolMiner 1.66 (Windows) on Nvidia 1660Super: Beam-III@Nicehash no hashrate

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1842]
lolMiner-v1.66\lolminer.exe --algo BEAM-III --pool beamv3.auto.nicehash.com:9200 --user ####################.############ --pass x --tls off --log off --apiport 4006 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 11:0

Miner connects, but does not start mining. What am I doing wrong?
AMD cards work fine.

**Comment by jgonzis** [comment]
> lolMiner-v1.66\lolminer.exe --algo BEAM-III --pool beamv3.auto.nicehash.com:9200 --user ####################.############ --pass x --tls off --log off --apiport 4006 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 11:0
> 
> Miner connects, but does not start mining. What am I doing wrong? AMD cards work fine.

Please which Nvidia Driver are you using?. Over 522.25 is having issues the kernel
