### ISSUE TITLE
作者抽水地址被墙了，导致罢工

### ISSUE THREAD

**Issue by MagicXC** [Lolliedieb/lolMiner-releases#1843]
作者抽水地址被墙了，导致罢工不挖了，你就不能换一个吗？

**Comment by jgonzis** [comment]
It is one of the things to fix for next release.

**Comment by MagicXC** [comment]
不错！要是你抽水能走用户同一个矿池ip端口就好了，一起转发没烦恼。

**Comment by jgonzis** [comment]
Should be Fixed with 1.67
