### ISSUE TITLE
lolminer-1.66.SwitchHiveOS EATING RAM

### ISSUE THREAD

**Issue by Johnj0** [Lolliedieb/lolMiner-releases#1844]
Mine neoxa, everything perfect, I started to do dual mining, neoxa + ZIL and the problems began, every time it alternates between coins, it consumes more and more ram. image and configuration attached. I have a 8gb stick
![image](https://user-images.githubusercontent.com/123912380/215368235-c8e5006d-c995-46fa-86dd-d7bab0c61ca9.png)
![image](https://user-images.githubusercontent.com/123912380/215368445-6a8cccaf-a50b-4f24-9063-56298c6f5e3c.png)

**Comment by jgonzis** [comment]
Could you plese reupdate it running that code, new version uploaded:

_miner stop && rm /hive/miners/custom/downloads/*.* && rm -r /hive/miners/custom/lolminer && miner start_

**Comment by Johnj0** [comment]
It does not consume more ram, but this new version does not apply the OC for both NEXA and ZIL
![image](https://user-images.githubusercontent.com/123912380/215485036-d3c07171-e07c-435e-a471-b0ac5b343a81.png)
![image](https://user-images.githubusercontent.com/123912380/215485276-8eb384cd-0324-48ba-863c-32a30590ea23.png)

**Comment by Johnj0** [comment]
Thank you very much problem solved
