### ISSUE TITLE
Nexa High share rejects on some startups from seemingly stable gpus

### ISSUE THREAD

**Issue by tjayz** [Lolliedieb/lolMiner-releases#1846]
See attached logs. Log1 shows 2.5 hour run with 0 rejects on all gpus. Log1 ends and gpu 2 conspicuously had an unrecoverable error which led to a restart of the miner. Log2 begins immediately after log1 ends, yet now gpu 1 has 70% reject rate vs 0% in log1.  Gpu 1 was seemingly stable per log1 yet now it is clearly amiss. 

I can think of three possible root causes. 1 is kernel, 2 is dag, 3 is different millivolt being applied to lock same core clock. If the issue was the dag I would think 100% of shares would be rejected. Kernel seems plausible since it seems shares are being presented prematurely given log2 shows 38% more shares on gpu 1 than gpu 0, the same gpus with the same oc. Alternatively, its possible the core was locked in log1  with an mv of 686 where in log2 it was locked at 670 creating a slightly power starved environment. Being able to lock mv along with pl would be a nice addition to the miner and msi afterburner does not let me lock mv lower than 700 on these cards. Even if it did, if miner restarts on gpu crash, afterburner has an error which on miner restart the gpu fans will lock at 0% requiring reboot.

I have seen this problem on all 3 of my rigs. I have achieved stability on the other two for 24hr+, this one is a pain. Of note, if I alter the settings for a lone gpu in a stable rig, it can now cause unrecoverable errors and high rejected shares on gpus other than the gpu which had its oc altered which doesn't make much sense and makes it incredibly difficult to achieve stability on a rig when the proper gpu is not being identified on crash in the logs.

[log1.log](https://github.com/Lolliedieb/lolMiner-releases/files/10531974/log1.log)
[log2.log](https://github.com/Lolliedieb/lolMiner-releases/files/10531975/log2.log)

**Comment by jgonzis** [comment]
Really interesting... 

It crash for an excess of Offset Core in GPU0, and the restart all is working except GPU1 that seems that kernel wasn't load properly.

**Comment by tjayz** [comment]
If its kernel, it is loading improperly for me frequently. Is there a way to increase the load time/decrease strain on miner start such as with trex setting --gpu-init-mode 1? Not sure slowing down dag gen would be of assistance here but I think you get the idea, thanks.

**Comment by jgonzis** [comment]
> If its kernel, it is loading improperly for me frequently. Is there a way to increase the load time/decrease strain on miner start such as with trex setting --gpu-init-mode 1? Not sure slowing down dag gen would be of assistance here but I think you get the idea, thanks.

Something to check in the next days... but it could be in that way. Something that made the kernel crash loading so fast

**Comment by tjayz** [comment]
bzminer 13.03 solved
