### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tjayz** [Lolliedieb/lolMiner-releases#1849]
Add pool mhs to the api so it can be viewed in the gui. as seen inside the miner. 

I get this message from the gui, "That pool NexaPoW is not yet supported", unclear if this is related to my request but currently mine to woolypooly ssl. 

I think more people would be aware of the gui if you slapped an index.html in releases for people to click, I created my own editing bzminers :4014 to :8020/gui. People too lazy to read readme files and what is attached with every release is still an outdated readme from 1.53. Very few probably use the -h function built in, might be useful for some to have an updated readme in the releases as well :)

**Comment by jgonzis** [comment]
> Add pool mhs to the api so it can be viewed in the gui. as seen inside the miner.
> 
> I get this message from the gui, "That pool NexaPoW is not yet supported", unclear if this is related to my request but currently mine to woolypooly ssl.
> 
> I think more people would be aware of the gui if you slapped an index.html in releases for people to click, I created my own editing bzminers :4014 to :8020/gui. People too lazy to read readme files and what is attached with every release is still an outdated readme from 1.53. Very few probably use the -h function built in, might be useful for some to have an updated readme in the releases as well :)

The pool NExaPow is not supported it means that not read the balance of the pool. I will check it too if the Display hashrate is not correct

**Comment by jgonzis** [comment]
![image](https://user-images.githubusercontent.com/38668405/216835354-d313746d-20ef-40bd-8901-fab04db1846e.png)
It shows the Mhs... Let me try to add the balance NexaPow of some of the pools too

**Comment by tjayz** [comment]
![Poolmhs where in gui](https://user-images.githubusercontent.com/90593277/217168426-3eaa007e-57f5-4079-9133-859f5649cdd1.png)

Sorry, I do not think I was clear and think the attached above clarifies. I am requesting the pool mhs inside the api/gui, the miner mhs is present, no issues there.

**Comment by tjayz** [comment]
Been using grafana with prometheus this request obsolete for me now
