### ISSUE TITLE
Can't Run Miner

### ISSUE THREAD

**Issue by cfimz** [Lolliedieb/lolMiner-releases#185]
I'm new to mining so i have no idea what i'm doing. Followed a youtube video to set up but am getting an error saying All devices deselected or failed compatibility check.. Can someone help explain to me how to resolve this?

thanks 

![image](https://user-images.githubusercontent.com/78108072/106045070-8791fe00-60ae-11eb-8c77-ceca3f4aec1f.png)

**Comment by jgonzis** [comment]
> I'm new to mining so i have no idea what i'm doing. Followed a youtube video to set up but am getting an error saying All devices deselected or failed compatibility check.. Can someone help explain to me how to resolve this?
> 
> thanks
> 
> ![image](https://user-images.githubusercontent.com/78108072/106045070-8791fe00-60ae-11eb-8c77-ceca3f4aec1f.png)

It is not possible to mine ETH with 3Gb... you can only with more memory cards... you should mine ETC or Beam for example

**Comment by cfimz** [comment]
Thank you for the explanation! i am in line for a new machine anyway :)
