### ISSUE TITLE
MC lock issue

### ISSUE THREAD

**Issue by TH9569** [Lolliedieb/lolMiner-releases#1851]
![image](https://user-images.githubusercontent.com/124556064/216964100-35444fdb-f863-4b06-a231-30a6b43f8c6a.png)
So guys, I've lock my MC at 5001, but its set at 6000 instead? 
Please advise. Thanks very much!

**Comment by jgonzis** [comment]
Which GPU?

**Comment by TH9569** [comment]
> Which GPU?

3070M

**Comment by jgonzis** [comment]
> > Which GPU?
> 
> 3070M

It could be the state I'm the 3070M is 6000, not all gpus have the 5000 Memory state.

**Comment by TH9569** [comment]
Yeap, you're right. Just check the supported clocks. There is no 5000 stated.
