### ISSUE TITLE
1.67BUG！

### ISSUE THREAD

**Issue by MagicXC** [Lolliedieb/lolMiner-releases#1855]
Test 3060Tix1.After running for a long time, there will be a situation where the CPU occupation is super high and the computing power is almost nothing, and bzminer is no problem under the same conditions.

**Comment by jgonzis** [comment]
> Test 3060Tix1.After running for a long time, there will be a situation where the CPU occupation is super high and the computing power is almost nothing, and bzminer is no problem under the same conditions.

Could you share some miner log information ... without that is imposible to have start to know where is the problem
