### ISSUE TITLE
Unrecoverable memory error by GPU 0. Reset of all Cuda GPUs required. Please check your (memory) OC & UV settings on this card. Device 0 detected as crashed. Closing miner and trying to call external script: emergency.bat (--watchdog script)

### ISSUE THREAD

**Issue by Mercyletter** [Lolliedieb/lolMiner-releases#1859]
OS: Windows 11 22H2
RTX 2060 12GB
I am experiencing this problem with the algorithm --algo BEAM-III --pool stratum+ssl://beamhash.unmineable.com:4444
But with --something ZEL --pers AUTO --pool stratum+ssl://zelhash.unmineable.com:4444 works without problems.
The values according to MSI sample are those of stock.
I don't know what's going on I'm new to this. Attached screenshots.
Thank you very much in advance.
All the best.
![1](https://user-images.githubusercontent.com/32906745/218207348-adc371ea-33c7-4f1c-b30b-a12d72debafe.jpg)

![2](https://user-images.githubusercontent.com/32906745/218207362-ae2d3f8d-ee98-4ea2-8638-9e8931b2f867.jpg)
![3](https://user-images.githubusercontent.com/32906745/218207376-e5813c30-b4d2-493e-ba09-bcc5d379bc4a.jpg)

**Comment by jgonzis** [comment]
With Windows and BEAM don't use 522.25 or it will not work
