### ISSUE TITLE
Warning: resolve: no such host is known

### ISSUE THREAD

**Issue by dtdilillo** [Lolliedieb/lolMiner-releases#186]
Hi,

Trying to run mine_eth.bat and I keep getting: 
_Warning: resolve: no such host is known
Lost connection to stratum server : or server not reachable._

And then it keeps trying to reconnect. Here are my specs:
_Setup Miner...
Device 0:
    Name:    Quadro P4000
    Address: 101:0
    Vendor:  NVIDIA Corporation
    Memory:  8192 MByte
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash)_

Please advise? Thank you!

**Comment by jgonzis** [comment]
That is a problem with the Internet connection... which server have you put in the bat file?...

**Comment by dtdilillo** [comment]
> 
> 
> That is a problem with the Internet connection... which server have you put in the bat file?...

I've tried us1.ethermine.org and us2.ethermine.org pools. I've also tried to run the ETC miner using us1-etc.ethermine.org.

**Comment by jgonzis** [comment]
Can you copy the complete bat file information... with an image or directly all... to check

**Comment by dtdilillo** [comment]
@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=us1.ethermine.org:4444"
set "WALLET=0x561917f345A50cF74e45f031f35Cf9F3136770AA.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! 
pause

**Comment by jgonzis** [comment]
> @echo off
> 
> setlocal enableDelayedExpansion
> 
> Rem #################################
> Rem ## Begin of user-editable part ##
> Rem #################################
> 
> set "POOL=us1.ethermine.org:4444"
> set "WALLET=0x561917f345A50cF74e45f031f35Cf9F3136770AA.lolMinerWorker"
> 
> Rem #################################
> Rem ## End of user-editable part ##
> Rem #################################
> 
> lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET!
> pause

It is perfect, you probably need to disable the firewall or the antivirus... try other pool 2miners for example,  that is correct

**Comment by dtdilillo** [comment]
> It is perfect, you probably need to disable the firewall or the antivirus... try other pool 2miners for example, that is correct

Hmm, what do you mean by other pool 2miners? Thanks. New to this space.

**Comment by jgonzis** [comment]
Change the pool to try for example:

eth.2miners.com:2020

To discard...

**Comment by Fohsap** [comment]
I think it might be an issue of your VPN or ISP blocking ports.  I've got a similar, unresolved issue, and I've disabled every firewall up to the VPN I use to get out....  I've tried various servers (similar config) and various pool hosts (ethminer, 2miners, etc.).  Strangely, no issue with Ethcoin (but the DAG files are too large for my GPU)....

Is it possible an SSL port is required for Beam Coin?  I've read about it.
I received errors using other mining softwares for RVC and Beam Coin; so, probably the same issue...  Of course, most mining softwares do nothing because they are broken.  You can be sure LolMiner works on newer systems, at least.

**Comment by Fohsap** [comment]
Can't edit that comment.  Did confirm the VPN firewall is off on the VPNs.  Moved forward to disable the VPN.  Moved forward to change VPN locations.  So, no firewall is standing in the way.  Could it be a national firewall across Australia, Japan, and China, or perhaps the VPS service imposing a firewall (expressly not anti-mining in their TOS and they said all ports are open in previous tickets)....  Next step will be to try another local computer....  Could it be the DNS (1.1.1.1)?  Or maybe SSL is required for Beam Coin and Raven Coin?

**Comment by Fohsap** [comment]
On port 3334, beam.sunpool.com worked with LolMiner.... Here's the issue:
(1) It worked on my high-performance hardware.
(2) It said "incompatible with hardware" on my low-performance hardware.
(3) Setup was a little confusing.  Scroll down on beam.sunpool.top and save the public and private key to a place where you definitely won't lose it.  You need to use the public key as your wallet, I think.

**Comment by jgonzis** [comment]
Firewall/ Internet Problem
