### ISSUE TITLE
Please add kas+zil 

### ISSUE THREAD

**Issue by wwe382300112** [Lolliedieb/lolMiner-releases#1861]

**Comment by jgonzis** [comment]
For Windows you have that guide to do KAS+ZIL, well any algo+zil:
https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL-Windows

For HiveOS that other guide, at the end are several Templates: 
https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide----lolMiner-AutoSwitch-(HiveOS---Beta)#any-algo--zil-mining-example

Meanwhile Dev ends that function to be integrated automaticly in the miner.
