### ISSUE TITLE
Win10, lolminer 1.673080ti x 4, overfrequency error!

### ISSUE THREAD

**Issue by MagicXC** [Lolliedieb/lolMiner-releases#1865]
The same parameters are normal in bzminer, but not in lol with core and video memory overclocking parameters
[http://wk.okczb.top/files/63ec9b11a0f5f/1111.jpg](url)

**Comment by jgonzis** [comment]
> The same parameters are normal in bzminer, but not in lol with core and video memory overclocking parameters [http://wk.okczb.top/files/63ec9b11a0f5f/1111.jpg](url)

That depens how stress each miner put to the GPU, normally lolMiner push some extra and sometimes same OC don't work the same in both miners

**Comment by jgonzis** [comment]
Which OC and Algo are you using?
