### ISSUE TITLE
NVIDIA CMP HX memory lock 810

### ISSUE THREAD

**Issue by arcanum144** [Lolliedieb/lolMiner-releases#1868]
On nvidia cmp hx cards --mclk 810 option does not work. The memory still runs at 5000mhz. How can I lower the memory frequency on the CMP HX to 810mhz? Thanks

**Comment by jgonzis** [comment]
> On nvidia cmp hx cards --mclk 810 option does not work. The memory still runs at 5000mhz. How can I lower the memory frequency on the CMP HX to 810mhz? Thanks

You cannot do it... Nvidia hasn't allow that state for CMP GPUs...
