### ISSUE TITLE
'lolMiner.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mincoamir** [Lolliedieb/lolMiner-releases#187]
I don't understand why, there isn't much that i can configure in the bat file, so im not sure what i have done wrong

**Comment by jgonzis** [comment]
> I don't understand why, there isn't much that i can configure in the bat file, so im not sure what i have done wrong

That os because you are Running it as Administrator...

You should add the folder of the lolMiner file. Example:

C:\Downloads\miner\lolMiner.exe -a ETHASH  ....

That will go to the exact folder, when Running as administrator is not in the folder of the download file and you should specify

**Comment by AnkurSingh28** [comment]
I was getting the same error but after making the changes and pointing to the correct folder path I am getting an access denied error.
![image](https://user-images.githubusercontent.com/31462536/106281064-ac869c80-6279-11eb-9299-359d6292e90e.png)

**Comment by AnkurSingh28** [comment]
The issue is now resolved. Windows defender was stopping it.

**Comment by jgonzis** [comment]
https://windowsreport.com/access-is-denied-windows-10/

If you’re getting Access is denied message, you might be able to fix it simply by setting your account as an administrator

Solution Number 6... it has to be with user privileges...
