### ISSUE TITLE
How to mine nexa + zil in dual in flexpool?

### ISSUE THREAD

**Issue by nngdevbr** [Lolliedieb/lolMiner-releases#1872]
How to mine nexa + zil in dual in flexpool?

I tried all the ways and I can't connect the flexpool to zilliqa can someone help me?

**Comment by jgonzis** [comment]
Hi, 

If you are using HiveOS just [https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide----lolMiner-AutoSwitch-(HiveOS---Beta)](https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide----lolMiner-AutoSwitch-(HiveOS---Beta)) 
There is there a guide and several profils, for Flexpool is like this:

ZIL,etc-us-east.flexpool.io:4444,
0x5806b063452c5ceba0ff807ec04bc1a3dfe9eabc/zil1r6qf8r4c0qasuqvfky3qlhdadyx2axa8wkem8c,{--cclk 1400,1400,1100,1400,14000 --moff 1500 --coff 0}

ZIL,etc-us-east.flexpool.io:4444,
ETC_WALLET/ZIL_WALLET,{--cclk 1400,1400,1100,1400,14000 --moff 1500 --coff 0}

In case Windows: [https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL-Windows](https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL-Windows)

All that will get updated quite soon but meanwhile you can mine any algo without loosing performance
