### ISSUE TITLE
1.68 - No problems

### ISSUE THREAD

**Issue by NasoLiteratus** [Lolliedieb/lolMiner-releases#1873]
Thanks appreciate your hard work, increased hashrate and efficiency across all my cards.
![lol  1 67 v 1 68](https://user-images.githubusercontent.com/50769264/221102277-a73e6309-3097-42f7-975e-ca3fcb8194fe.PNG)
![lol 1 67 v 1 68](https://user-images.githubusercontent.com/50769264/221102366-d6caf15a-71b8-40a1-94df-507dfb9082db.PNG)
![lol 1 67 v 1  68 G](https://user-images.githubusercontent.com/50769264/221102450-3d9f938d-ca75-4a47-b41d-6447316a41d3.PNG)

**Comment by jgonzis** [comment]
Nice to see a post without problems :-)  Really good performance

**Comment by NasoLiteratus** [comment]
Thanks Mate, All Good with no Issues.
I didnt expect it to increase the hash on all of my cards though.
Good job.
G'day from Australia

**Comment by Lolliedieb** [comment]
Like it, but closing it to keep github issue tracker clean :)
