### ISSUE TITLE
/hive/miners/lolminer/h-run.sh: line 7: lolMiner: command not found.

### ISSUE THREAD

**Issue by calipomza** [Lolliedieb/lolMiner-releases#1880]
Hello. In Hiveos I have a error in the miner:  /hive/miners/lolminer/h-run.sh: line 7: lolMiner: command not found.
That is in 2 rigs.
Thanks

**Comment by cutestor1** [comment]
It's the same symptom.
/hive/miners/lolminer/h-run.sh: line 7: lolMiner: command not found

Repeated messages keep coming out.

**Comment by constantinstr** [comment]
I have the same problem, in hiveos with lolminer 1.69

/hive/miners/lolminer/h-run.sh: line 7: lolMiner: command not found.

it happened after updating to version 1.69 of lolminer

**Comment by jgonzis** [comment]
Make a selfupgrade force in HiveOS. The package was uploaded with a problem from HiveOS but they solved.
