### ISSUE TITLE
OC BLOCKED

### ISSUE THREAD

**Issue by majfo** [Lolliedieb/lolMiner-releases#1884]
I was mining alepium  and kaspa pl170 cclk 1600\1300 mclk 810. And my graphic card was blocked in fan o pl 5% cclk 210mz mclk 810. If you overclock with or miner it changes but without the miner it is blocked in the values that I mentioned and not even with the gpu tweak lll it does not return to the normal values of rtx3600. Can you help me please. THANKS
![IMG_20230307_005908](https://user-images.githubusercontent.com/127163457/223325916-a14a9696-bb1e-42d2-9f50-6a5c8d476c85.jpg)
![IMG_20230307_005926](https://user-images.githubusercontent.com/127163457/223325935-f80d7a73-93a1-402c-a557-0d89e8e64df3.jpg)

**Comment by jgonzis** [comment]
You can try to use the miner OC... but remember to have Nvidia Driver +525

**Comment by majfo** [comment]
that was the 1st thing i did.but the problem is that the gpu only responds to miner overclocks it does not respond to gpu overclocks tweck lll even with the miner turned off it is blocked at the values shown! I already installed new maderbord bios, windows11, drivers, programs, miner, etc. I've done several health tests and nothing and that's why I asked for help. don't you have a program to clean the overclocks? thanks

**Comment by jgonzis** [comment]
> that was the 1st thing i did.but the problem is that the gpu only responds to miner overclocks it does not respond to gpu overclocks tweck lll even with the miner turned off it is blocked at the values shown! I already installed new maderbord bios, windows11, drivers, programs, miner, etc. I've done several health tests and nothing and that's why I asked for help. don't you have a program to clean the overclocks? thanks

Y has probado con el lolMinerGUI??

**Comment by majfo** [comment]
yes, but even if I do a reset, I turn off the miner, it returns to the same values

**Comment by jgonzis** [comment]
That seems more a problem of your computer thar reset that not the miner... try a mining OS if that solves you. Windows  try a DDU drivers and reinstall 528.xx

**Comment by majfo** [comment]
ok i try

**Comment by majfo** [comment]
uninstalled with ddu, I installed 528.24 driver but everything is the same. Could it be that the gpu is broken? Or is there a problem with the gpu bios?

**Comment by jgonzis** [comment]
Could you try a mining OS? Like mmpOS, SimpleMining or RaveOS?.

Let's see if there works properly

**Comment by majfo** [comment]
hello, i tried raveos but i can't use osminers because i only have net with wifi.
but the gpu responds to lolminer and continues to mine normally with the same hashrate and if you change overclocks it responds normally. only when I close the miner and it stays in the values of the photo, it is not normal.
I'm only worried because I don't have a rig, it's just my pc's gpu and it's only a year and 4 months old. And I need it for personal use. the pc continues to work normally I don't understand if gpu is good or not? Is there any program that does an analysis and repairs the gpu? thanks for your attention and advice.

**Comment by jgonzis** [comment]
I have all the rigs with mmpOS with WIFI... If you try it, you will not go back to Windows hehe.

For testing GPUs I usually use Furmark

**Comment by majfo** [comment]
ok but i need windows .thanks for your attention and advice.
