### ISSUE TITLE
algo+zil

### ISSUE THREAD

**Issue by aLcateLLo** [Lolliedieb/lolMiner-releases#1885]
I like your miner, but dont't use it now becouse algo+zil don't relize normaly. Every time dug file is needed time for genereting. When you planning realize it normally. And intresting in ergo+kas+zil or ergo+nexa+zil.

**Comment by jgonzis** [comment]
Hi...
You can have alook on that
https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL

**Comment by aLcateLLo** [comment]
I have tested in hiveos and windows. Both aren't good, especially windows. Rigel works better, it changes algos correctly. lolminer can continue mine etc after zil and after a half of minet back to nexa e.g.

**Comment by aLcateLLo** [comment]
And important thing it is cache of dug...

**Comment by jgonzis** [comment]
> I have tested in hiveos and windows. Both aren't good, especially windows. Rigel works better, it changes algos correctly. lolminer can continue mine etc after zil and after a half of minet back to nexa e.g.

That has a new way of do it... Cache Dag... is less than 1 second... the proper time to correctly unlock the OC :-)
