### ISSUE TITLE
New Feature requested: dual Kaspa + ETC (not ETC + Kaspa) or + something if possible

### ISSUE THREAD

**Issue by GauchoBois** [Lolliedieb/lolMiner-releases#1886]
Hi, is it possible to mine Kaspa + ETC instead of ETC + Kaspa? I mean, I'd like to mine Kaspa and then add dual ETC on top while slightly penalizing Kaspa (and not viceversa). I tried mining ETC + Kaspa by increasing the --dualfactor but it just keeps dropping ETC while Kaspa increases just slightly and it is always pretty far away of the numbers mining only Kaspa.

**Comment by jgonzis** [comment]
That will depend the OC you are using... 

You have also ETC/ETHW + ALPH
