### ISSUE TITLE
New version 1.70/NexaPow: GPU 1: error in allocating memory 0 .

### ISSUE THREAD

**Issue by RainbowMiner** [Lolliedieb/lolMiner-releases#1890]
Hi,

what does this error message mean for the GTX1070-8GB? It appeared with v1.70 on NexaPow / Window10.

```
Connecting to pool...
DNS over HTTPS resolve succeeded
Connected to stratum-eu.rplant.xyz(141.94.192.217):7092  (TLS disabled)
Subscribed to stratum server
New extra nonce received: 21f616eb
New target received: 00000009fffffff6 (Diff 0.1)
New work received: 7002
Authorized worker: nexa:removedforpublishing.rbm
Start Mining...
GPU 2: error in allocating memory 0 .
GPU 1: error in allocating memory 0 .
GPU 0: error in allocating memory 0 .
GPU 4: error in allocating memory 0 .
GPU 5: error in allocating memory 0 .
GPU 3: error in allocating memory 0 .
```

**Comment by jgonzis** [comment]
That is because not enough Virtual Memory Disk..

Nexa needs a lot. You can reduce it reducing Mhs too if you put --keepfree 4000, that will load the small LUT.

**Comment by RainbowMiner** [comment]
> That is because not enough Virtual Memory Disk..

I have a current virtual memory disk size of 160000 MB (156GB) for these six GPUs. Do I really need more for NexaPow?

**Comment by RainbowMiner** [comment]
Ok, solved. Running NexaPow on Windows really needs `--keepfree 1024` for these GPUs. Is this a principal problem with GPUs on Windows? Or does this relate to Nvidia and/or specific GPU models, only?

**Comment by jgonzis** [comment]
It is the 8Gb LUT needs lot of virtual memory... that doesn't happens in Linux.  Try to increase it to 100GB

**Comment by RainbowMiner** [comment]
> It is the 8Gb LUT needs lot of virtual memory... that doesn't happens in Linux. Try to increase it to 100GB

I have already got set the file size to 156GB. I suspect the problem isn't that virtual memory disk, but the fact, that Windows itself blocks a chunk of memory on each GPU. If I use --keepfree 1024 (1GB of memory reserved), the miner runs fine, even though pretty slow.

**Comment by jgonzis** [comment]
Did you try only some devices? not all at same time?

**Comment by RainbowMiner** [comment]
All rigs, all together in groups, only. But I'll give it a shot. I have one test rig with only one GPU. So it should be easy to try out.

**Comment by jgonzis** [comment]
> All rigs, all together in groups, only. But I'll give it a shot. I have one test rig with only one GPU. So it should be easy to try out.

Sorry I didn't explain properly... like --devices 1 for example

**Comment by lynxchat4** [comment]
Experimental I find last working keepfree parameter
--keepfree 6015

I tried to change the parameters - but no result:
--devices 
windows swap file 100-300 Gb

Now the speed lol on Windows is less than BZminer 0.5-1Mh .
Windows give a loss of 3.5-6.5% relative to raveos

But only in Windows work power limit on 3070m.

Please fix speed and dag on windows.

**Comment by jgonzis** [comment]
> Experimental I find last working keepfree parameter --keepfree 6015
> 
> I tried to change the parameters - but no result: --devices windows swap file 100-300 Gb
> 
> Now the speed lol on Windows is less than BZminer 0.5-1Mh . Windows give a loss of 3.5-6.5% relative to raveos
> 
> But only in Windows work power limit on 3070m.
> 
> Please fix speed and dag on windows.

Did you update nvidia drivers in Linux? I saw several 3070m running nexa with last drivers

**Comment by lynxchat4** [comment]
> 
In windows I use last Nvidia drivers with working PL. 528.49

Raveos   -  nvidia-525.60.11

**Comment by lynxchat4** [comment]
> > Experimental I find last working keepfree parameter --keepfree 6015
> > I tried to change the parameters - but no result: --devices windows swap file 100-300 Gb
> > Now the speed lol on Windows is less than BZminer 0.5-1Mh . Windows give a loss of 3.5-6.5% relative to raveos
> > But only in Windows work power limit on 3070m.
> > Please fix speed and dag on windows.
> 
> Did you update nvidia drivers in Linux? I saw several 3070m running nexa with last drivers

In windows I use last Nvidia drivers with working PL. 528.49

Raveos - nvidia-525.60.11

**Comment by lynxchat4** [comment]
Last working verson without "keepfree" - 1.68, but hashrate is LOW.
when  --keepfree 896 
in gpu-z :  
used memory:  ~1900 Mb

**Comment by lynxchat4** [comment]
I solve problem  "error in allocating memory 0 ."
Just update windows to 22H2 version.
Now I have hi hashrate and stable working without keepfee parameter.

**Comment by jgonzis** [comment]
thx for the feedback
