### ISSUE TITLE
lolMiner1.70 crash with too many files when mining kaspa

### ISSUE THREAD

**Issue by a52521255** [Lolliedieb/lolMiner-releases#1897]
![微信截图_20230316082710](https://user-images.githubusercontent.com/94586662/225478364-0ae766b0-41bd-4409-8c8f-9a9c5c00b8c6.png)
ubuntu 20.04 seems to crahed about 10-15hours after start, and always can be repeated, RTX3070 *6 8GRAM

**Comment by jgonzis** [comment]
As comment in the telegram group, that could be with the nohup and the redirection of your file line
