### ISSUE TITLE
挖kaspa    30hx   40hx 显卡无法锁定810显存评率

### ISSUE THREAD

**Issue by qq1165014727** [Lolliedieb/lolMiner-releases#1900]
![30hx1](https://user-images.githubusercontent.com/128031911/225560385-4f118a83-db7c-4648-911a-a4faf37126ba.png)

**Comment by qq1165014727** [comment]
> 

加入了--mclk 810    cmp 无法810吗？

**Comment by jgonzis** [comment]
Have you looked onto 
nvidia-smi -i 0 --query-supported-clocks=gr,mem --format=csv
already?
that will print you a full list of lock core and memory values that the card is allowed to take ...

**Comment by caokun320** [comment]
nvidia-smi -i 0 --query-supported-clocks=gr,mem --format=csv
graphics [MHz], memory [MHz]
2100 MHz, 6001 MHz
2085 MHz, 6001 MHz
2070 MHz, 6001 MHz
2055 MHz, 6001 MHz
2040 MHz, 6001 MHz
2025 MHz, 6001 MHz
2010 MHz, 6001 MHz
1995 MHz, 6001 MHz
1980 MHz, 6001 MHz
1965 MHz, 6001 MHz
1950 MHz, 6001 MHz
1935 MHz, 6001 MHz
1920 MHz, 6001 MHz
1905 MHz, 6001 MHz
1890 MHz, 6001 MHz
1875 MHz, 6001 MHz
1860 MHz, 6001 MHz
1845 MHz, 6001 MHz
1830 MHz, 6001 MHz
1815 MHz, 6001 MHz
1800 MHz, 6001 MHz
1785 MHz, 6001 MHz
1770 MHz, 6001 MHz
1755 MHz, 6001 MHz
1740 MHz, 6001 MHz
1725 MHz, 6001 MHz
1710 MHz, 6001 MHz
1695 MHz, 6001 MHz
1680 MHz, 6001 MHz
1665 MHz, 6001 MHz
1650 MHz, 6001 MHz
1635 MHz, 6001 MHz
1620 MHz, 6001 MHz
1605 MHz, 6001 MHz
1590 MHz, 6001 MHz
1575 MHz, 6001 MHz
1560 MHz, 6001 MHz
1545 MHz, 6001 MHz
1530 MHz, 6001 MHz
1515 MHz, 6001 MHz
1500 MHz, 6001 MHz
1485 MHz, 6001 MHz
1470 MHz, 6001 MHz
1455 MHz, 6001 MHz
1440 MHz, 6001 MHz
1425 MHz, 6001 MHz
1410 MHz, 6001 MHz
1395 MHz, 6001 MHz
1380 MHz, 6001 MHz
1365 MHz, 6001 MHz
1350 MHz, 6001 MHz
1335 MHz, 6001 MHz
1320 MHz, 6001 MHz
1305 MHz, 6001 MHz
1290 MHz, 6001 MHz
1275 MHz, 6001 MHz
1260 MHz, 6001 MHz
1245 MHz, 6001 MHz
1230 MHz, 6001 MHz
1215 MHz, 6001 MHz
1200 MHz, 6001 MHz
1185 MHz, 6001 MHz
1170 MHz, 6001 MHz
1155 MHz, 6001 MHz
1140 MHz, 6001 MHz
1125 MHz, 6001 MHz
1110 MHz, 6001 MHz
1095 MHz, 6001 MHz
1080 MHz, 6001 MHz
1065 MHz, 6001 MHz
1050 MHz, 6001 MHz
1035 MHz, 6001 MHz
1020 MHz, 6001 MHz
1005 MHz, 6001 MHz
990 MHz, 6001 MHz
975 MHz, 6001 MHz
960 MHz, 6001 MHz
945 MHz, 6001 MHz
930 MHz, 6001 MHz
915 MHz, 6001 MHz
900 MHz, 6001 MHz
885 MHz, 6001 MHz
870 MHz, 6001 MHz
855 MHz, 6001 MHz
840 MHz, 6001 MHz
825 MHz, 6001 MHz
810 MHz, 6001 MHz
795 MHz, 6001 MHz
780 MHz, 6001 MHz
765 MHz, 6001 MHz
750 MHz, 6001 MHz
735 MHz, 6001 MHz
720 MHz, 6001 MHz
705 MHz, 6001 MHz
690 MHz, 6001 MHz
675 MHz, 6001 MHz
660 MHz, 6001 MHz
645 MHz, 6001 MHz
630 MHz, 6001 MHz
615 MHz, 6001 MHz
600 MHz, 6001 MHz
585 MHz, 6001 MHz
570 MHz, 6001 MHz
555 MHz, 6001 MHz
540 MHz, 6001 MHz
525 MHz, 6001 MHz
510 MHz, 6001 MHz
495 MHz, 6001 MHz
480 MHz, 6001 MHz
465 MHz, 6001 MHz
450 MHz, 6001 MHz
435 MHz, 6001 MHz
420 MHz, 6001 MHz
405 MHz, 6001 MHz
390 MHz, 6001 MHz
375 MHz, 6001 MHz
360 MHz, 6001 MHz
345 MHz, 6001 MHz
330 MHz, 6001 MHz
315 MHz, 6001 MHz
300 MHz, 6001 MHz
2100 MHz, 5001 MHz
2085 MHz, 5001 MHz
2070 MHz, 5001 MHz
2055 MHz, 5001 MHz
2040 MHz, 5001 MHz
2025 MHz, 5001 MHz
2010 MHz, 5001 MHz
1995 MHz, 5001 MHz
1980 MHz, 5001 MHz
1965 MHz, 5001 MHz
1950 MHz, 5001 MHz
1935 MHz, 5001 MHz
1920 MHz, 5001 MHz
1905 MHz, 5001 MHz
1890 MHz, 5001 MHz
1875 MHz, 5001 MHz
1860 MHz, 5001 MHz
1845 MHz, 5001 MHz
1830 MHz, 5001 MHz
1815 MHz, 5001 MHz
1800 MHz, 5001 MHz
1785 MHz, 5001 MHz
1770 MHz, 5001 MHz
1755 MHz, 5001 MHz
1740 MHz, 5001 MHz
1725 MHz, 5001 MHz
1710 MHz, 5001 MHz
1695 MHz, 5001 MHz
1680 MHz, 5001 MHz
1665 MHz, 5001 MHz
1650 MHz, 5001 MHz
1635 MHz, 5001 MHz
1620 MHz, 5001 MHz
1605 MHz, 5001 MHz
1590 MHz, 5001 MHz
1575 MHz, 5001 MHz
1560 MHz, 5001 MHz
1545 MHz, 5001 MHz
1530 MHz, 5001 MHz
1515 MHz, 5001 MHz
1500 MHz, 5001 MHz
1485 MHz, 5001 MHz
1470 MHz, 5001 MHz
1455 MHz, 5001 MHz
1440 MHz, 5001 MHz
1425 MHz, 5001 MHz
1410 MHz, 5001 MHz
1395 MHz, 5001 MHz
1380 MHz, 5001 MHz
1365 MHz, 5001 MHz
1350 MHz, 5001 MHz
1335 MHz, 5001 MHz
1320 MHz, 5001 MHz
1305 MHz, 5001 MHz
1290 MHz, 5001 MHz
1275 MHz, 5001 MHz
1260 MHz, 5001 MHz
1245 MHz, 5001 MHz
1230 MHz, 5001 MHz
1215 MHz, 5001 MHz
1200 MHz, 5001 MHz
1185 MHz, 5001 MHz
1170 MHz, 5001 MHz
1155 MHz, 5001 MHz
1140 MHz, 5001 MHz
1125 MHz, 5001 MHz
1110 MHz, 5001 MHz
1095 MHz, 5001 MHz
1080 MHz, 5001 MHz
1065 MHz, 5001 MHz
1050 MHz, 5001 MHz
1035 MHz, 5001 MHz
1020 MHz, 5001 MHz
1005 MHz, 5001 MHz
990 MHz, 5001 MHz
975 MHz, 5001 MHz
960 MHz, 5001 MHz
945 MHz, 5001 MHz
930 MHz, 5001 MHz
915 MHz, 5001 MHz
900 MHz, 5001 MHz
885 MHz, 5001 MHz
870 MHz, 5001 MHz
855 MHz, 5001 MHz
840 MHz, 5001 MHz
825 MHz, 5001 MHz
810 MHz, 5001 MHz
795 MHz, 5001 MHz
780 MHz, 5001 MHz
765 MHz, 5001 MHz
750 MHz, 5001 MHz
735 MHz, 5001 MHz
720 MHz, 5001 MHz
705 MHz, 5001 MHz
690 MHz, 5001 MHz
675 MHz, 5001 MHz
660 MHz, 5001 MHz
645 MHz, 5001 MHz
630 MHz, 5001 MHz
615 MHz, 5001 MHz
600 MHz, 5001 MHz
585 MHz, 5001 MHz
570 MHz, 5001 MHz
555 MHz, 5001 MHz
540 MHz, 5001 MHz
525 MHz, 5001 MHz
510 MHz, 5001 MHz
495 MHz, 5001 MHz
480 MHz, 5001 MHz
465 MHz, 5001 MHz
450 MHz, 5001 MHz
435 MHz, 5001 MHz
420 MHz, 5001 MHz
405 MHz, 5001 MHz
390 MHz, 5001 MHz
375 MHz, 5001 MHz
360 MHz, 5001 MHz
345 MHz, 5001 MHz
330 MHz, 5001 MHz
315 MHz, 5001 MHz
300 MHz, 5001 MHz
645 MHz, 405 MHz
630 MHz, 405 MHz
615 MHz, 405 MHz
600 MHz, 405 MHz
585 MHz, 405 MHz
570 MHz, 405 MHz
555 MHz, 405 MHz
540 MHz, 405 MHz
525 MHz, 405 MHz
510 MHz, 405 MHz
495 MHz, 405 MHz
480 MHz, 405 MHz
465 MHz, 405 MHz
450 MHz, 405 MHz
435 MHz, 405 MHz
420 MHz, 405 MHz
405 MHz, 405 MHz
390 MHz, 405 MHz
375 MHz, 405 MHz
360 MHz, 405 MHz
345 MHz, 405 MHz
330 MHz, 405 MHz
315 MHz, 405 MHz
300 MHz, 405 MHz

**Comment by jgonzis** [comment]
You can only have 6000,5000 or 405, the 810 is not supported.
