### ISSUE TITLE
nexa+zil Stops in this state. Do you have a solution?

### ISSUE THREAD

**Issue by cutestor1** [Lolliedieb/lolMiner-releases#1904]
lol Miners running NEXA with configuration lines:
lol Miner -a NEXA -p stratum - eu.r plant.xyz:17092 -unexa:nqtsq5g5d7m6tmcjkxs5lwy7mxn2rdgh9rj89r4d.s4 --clclk 1470 --mclk 5000 --coff 255 nexa:nqtqtqtqtqtq5g5mkxswwh7mn7mn
--apiport 44445
--timeprint 1 --shortstats 10 --longstats 60 --basecolor
OC "Nexapow" application:
{"code":null","message":"Unauthorized","redirect":"/api/oauth/auth?state=92ea4445-dc44-4028-81ce-a5b947469804"}
Check again in the next ZIL Windows

===================================

It stops in this state when switching from zil to nexa.

**Comment by jgonzis** [comment]
Seen that it seem that parameters are not right... 

port 17092 is : ssl://stratum-eu.rplant.xyz:17092  I don't see the ssl or if not ssl then use por 7092 instead of the 17092.
