### ISSUE TITLE
lolMiner would be the perfect Kaspa miner with direct undervolting

### ISSUE THREAD

**Issue by defactoambassador** [Lolliedieb/lolMiner-releases#1909]
Right now we can undervolt using core offset, but it has a 200~ish limit on algorithms that need high core overclock.

With direct undervolting we can set the voltage of our cards regardless of core clock. Any ETA on when this can be implemented?

**Comment by jgonzis** [comment]
> Right now we can undervolt using core offset, but it has a 200~ish limit on algorithms that need high core overclock.
> 
> With direct undervolting we can set the voltage of our cards regardless of core clock. Any ETA on when this can be implemented?

Well at the moment with Nvidia you can do it with --coff , with AMD you will need to use his drivers in Windows or lolMinerGUI or in Linux lot of the MiningOS
