### ISSUE TITLE
Ethos error after updating to lolminer 1.20 in EthOS

### ISSUE THREAD

**Issue by mcmurtreya** [Lolliedieb/lolMiner-releases#191]
a few days ago the miner stopped working, after a hard reboot it would continue for a couple days then die again. i updated and miner to 1.20 i had issues with the miner starting.

here is the most recent error
+---------------------------------------------------------+
|   _       _ __  __ _                   _   ____   ___   |
|  | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \ / _ \  |
|  | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) | | | | |
|  | | (_) | | |  | | | | | |  __/ |    | |_ / __/| |_| | |
|  |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____|\___/  |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|            Made by Lolliedieb, January 2021             |
+---------------------------------------------------------+
Error: Your input to --pool "rofile=ETHOS" can not be split into a address and a port. Please use format <pool address>:<pool port>.

here is a copy of the config in ethos

============================================================================

globalminer lolminer$
maxgputemp 85$
stratumproxy enabled$
proxywallet 0xa9988ba5a5ac9651f69173fcd56d1e4452486ba1.3fdde7/mcmurtrey.a@gmail.com$
proxypool1 eth-us-west1.nanopool.org:9999$
proxypool2 eth-us-east1.nanopool.org:9999$
flags --cl-global-work 8192 --farm-recheck 200$
globalfan 85$
globalcore 1150$
globalmem 2150$
lolminer=flags --coin ETH$

any help would be appreciated.

**Comment by jgonzis** [comment]
if you put 1.19 works?? because and easy and tricky way is to overwrite the folder of the working one with the new one. That seems to be that parameters are not well passed to the miner... 

If you run it like:

lolMiner --coin ETH --pool eth-us-west1.nanopool.org:9999 -u  0xa9988ba5a5ac9651f69173fcd56d1e4452486ba1.3fdde7/mcmurtrey.a@gmail.com 

it should mine... 

As you see the error is: --pool "rofile=ETHOS" that means parameters are not well pass...

**Comment by mcmurtreya** [comment]
uninstalled the old miner and reinstalled 1.20 working now. jsut didnt update well within EthOS.
