### ISSUE TITLE
NEXA+ZIL 

### ISSUE THREAD

**Issue by Norinivan** [Lolliedieb/lolMiner-releases#1912]
Mining NEX + ZIL does not work.
![Screenshot_4](https://user-images.githubusercontent.com/37981410/227880869-05949014-2c09-4bcc-91c8-a12206058fce.jpg)
Cards 3070 and 2060S
User Config--coff 120 --cclk 1470 --mclk 5000 --pl 125 --zpool eu.crazypool.org:5005 --zuser zil1ccandg7fm3qd3sg0rxtz626e72pguwakhngjwk

**Comment by Norinivan** [comment]
I try latest lolminer from HiveOS, and download and install https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.72/lolminer-1.72.ZIL.tar.gz. The problem is present in both cases.

**Comment by jgonzis** [comment]
> I try latest lolminer from HiveOS, and download and install https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.72/lolminer-1.72.ZIL.tar.gz. The problem is present in both cases.

Found the issue... look the 1st - is bigger, remove the 2 - and rewrite them!!

**Comment by Norinivan** [comment]
Now the one that is listed in the manual by reference is working. ver.1.72
![1](https://user-images.githubusercontent.com/37981410/227892958-af745cc2-7eb5-42b8-a733-be30d9a49eae.jpg)

**Comment by Norinivan** [comment]
I remove custom miner and lolminer. Reinstall custom miner and start mining.
Job is o'key. Why hashrate to low? Preset old, hashrate from 303Mh>275Mh
![image](https://user-images.githubusercontent.com/37981410/227905059-ed567600-bbe8-43db-a659-fd93b33e4f4f.png)

**Comment by Norinivan** [comment]
Thank you very much! Reboot and work!
![image](https://user-images.githubusercontent.com/37981410/227910295-a3d419d0-9c2a-44f0-8c20-e07a3d4c1b1d.png)

**Comment by jgonzis** [comment]
SUPER!!! I close the issue then :-) Many thanks for the feedback. I hope soon all will be in the same miner and will be easy.
