### ISSUE TITLE
Lol 1.72; Windows 10; AMD 5700XT*6

### ISSUE THREAD

**Issue by manager220** [Lolliedieb/lolMiner-releases#1919]
Lol 1.72; Windows 10; AMD 5700XT*6 what should I write in the bat file to lower the frequency by core and by memory.

lolMiner.exe -a NEXA --pool stratum-eu.rplant.xyz:17092 --devices AMD --tls on -u nexa:nqtsq5g5wszhx2mwy0dzzrxf0000000403a8h29vfvwtxlq.5700XT --cclk 1450,1450,1450,1450,1450,1450 --mclk 1500,1500,1500,1500,1500,1500 --tstop 54
when running this command, the frequencies are not applied, everything works by default cclk 2000 mclk 1750

What am I doing wrong?

of the possible reasons, I think the driver is old from 2020, but in order to install a new driver for video cards, you need to reinstall all Windows

**Comment by jgonzis** [comment]
That is normal, lolMiner doesn't support AMD OC, at the moment only Nvidia OC. You can use 3rd Apps or the lolMinerGUI 1.0.4 to modify them
