### ISSUE TITLE
Using lolMiner with a 3GB GTX1050

### ISSUE THREAD

**Issue by MakufonSkifto** [Lolliedieb/lolMiner-releases#192]
How can I use lolMiner with a 3GB GTX1050? I can't get it to working even though i tried everything. Is there a way to do it or its just impossible under 4GB of VRAM

**Comment by HybridGardener** [comment]
I hit the same issue. Looks like after Epoch #384 we are S.O.L

The requirements to process have gone beyond the GPU capabilities. Sadly

**Comment by MakufonSkifto** [comment]
> I hit the same issue. Looks like after Epoch #384 we are S.O.L
> 
> 
> 
> The requirements to process have gone beyond the GPU capabilities. Sadly

So does this mean that there is no way to fix?

**Comment by jgonzis** [comment]
4Gb in in Windows is imposible for ETH or nearly impossible... you have to try to mine ETC for example... that will work...
