### ISSUE TITLE
Old guide - ALGO + ZIL - not working

### ISSUE THREAD

**Issue by tomekmak** [Lolliedieb/lolMiner-releases#1925]
Hi there. 
I tried to setup Lolminer for IRON + ZIL using this guide:

https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL
Unfortunately not working :(

Any help ?

**Comment by jgonzis** [comment]
> Hi there. I tried to setup Lolminer for IRON + ZIL using this guide:
> 
> https://github.com/Lolliedieb/lolMiner-releases/wiki/Guide-ALGO---ZIL Unfortunately not working :(
> 
> Any help ?

Yes it goes. Your fault is in your side... if you share some information we will try to help you.

**Comment by tomekmak** [comment]
Here is my configuration:
![screenshot 2688](https://user-images.githubusercontent.com/88006095/233679719-afb2ce77-0d5f-4d98-b3b5-2193ef70bdf1.jpg)


and result:

![screenshot 2689](https://user-images.githubusercontent.com/88006095/233679507-12f27d47-a049-42be-b5c3-e7f193bb6908.jpg)

**Comment by tomekmak** [comment]
I changed installation URL for https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.74/lolminer-1.74.ZIL.tar.gz

![screenshot 2690](https://user-images.githubusercontent.com/88006095/233683372-c04919c2-e95b-4d5a-b633-7c68f8bc82d5.jpg)

And miner started. Now i need to wait for ZIL window to check that ZIL will be mined.

**Comment by tomekmak** [comment]
Seems it it working like charm ;-)

**Comment by jgonzis** [comment]
Many thanks for the feedback
