### ISSUE TITLE
Alephium Pool hashrate not even 50% on 1.74

### ISSUE THREAD

**Issue by Miner-FTW** [Lolliedieb/lolMiner-releases#1928]
I updated to 1.74 in hiveos for my 30 series nvidia cards on alephium.
While on previous versions my total hashrate that shows on hiveos was pretty much constant, on 1.74 it does show an increase of about 5% on average at the same settings/power usage but that extra performance is all over the place
It goes from 1% extra (compared to previous lolminer version), to up to 10% extra

Now I don't really mind that, but what I do mind is that on 1.74 the hashrate the pool registers (herominers in my case) is not even half of what hiveos shows.
Switched back to the previous version for now, now hashrate back steady as a rock and pool is showing hashrate close to what hiveos reports.

**Comment by jgonzis** [comment]
> I updated to 1.74 in hiveos for my 30 series nvidia cards on alephium. While on previous versions my total hashrate that shows on hiveos was pretty much constant, on 1.74 it does show an increase of about 5% on average at the same settings/power usage but that extra performance is all over the place It goes from 1% extra (compared to previous lolminer version), to up to 10% extra
> 
> Now I don't really mind that, but what I do mind is that on 1.74 the hashrate the pool registers (herominers in my case) is not even half of what hiveos shows. Switched back to the previous version for now, now hashrate back steady as a rock and pool is showing hashrate close to what hiveos reports.

Totally right, we found it in some rigs, Note to solve for  next release. If you have it that error, please use 1.73. Many thanks for the feedback

**Comment by jgonzis** [comment]
> I updated to 1.74 in hiveos for my 30 series nvidia cards on alephium. While on previous versions my total hashrate that shows on hiveos was pretty much constant, on 1.74 it does show an increase of about 5% on average at the same settings/power usage but that extra performance is all over the place It goes from 1% extra (compared to previous lolminer version), to up to 10% extra
> 
> Now I don't really mind that, but what I do mind is that on 1.74 the hashrate the pool registers (herominers in my case) is not even half of what hiveos shows. Switched back to the previous version for now, now hashrate back steady as a rock and pool is showing hashrate close to what hiveos reports.

Solved with 1.75!!
