### ISSUE TITLE
Connection issue?

### ISSUE THREAD

**Issue by holycreeperz** [Lolliedieb/lolMiner-releases#193]
Whenever I load up the miner it repeatedly tries to connect to my chosen stratum but fails and says
 "Warning: resolve: The requested name is valid, but no data of the requested type was found
 Lost connection to stratum server : or server not reachable.
 Trying to connect in 1 second"
 
I'm assuming this is something with my firewall, but allowing access to the .exe isn't enough to fix it, any help?

**Comment by tricagames92** [comment]
same issue

**Comment by jgonzis** [comment]
Can you put your bat file??

that is something with the Firewall or the server is not well configured...

**Comment by holycreeperz** [comment]
> 
> 
> Can you put your bat file??
> 
> that is something with the Firewall or the server is not well configured...
I cant upload bat files so heres the contents

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=us2.ethermine.org:4444"
set "WALLET=0x352F5521ff3E0F36b0bF9B4041394c4A040D3D56.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! 
pause

**Comment by jgonzis** [comment]
Test like this:

lolMiner.exe --algo ETHASH --pool us2.ethermine.org:4444  --user 0x352F5521ff3E0F36b0bF9B4041394c4A040D3D56.lolMinerWorker

Or 

lolMiner.exe --algo ETHASH --pool us1.ethermine.org:4444  --user 0x352F5521ff3E0F36b0bF9B4041394c4A040D3D56.lolMinerWorker

**Comment by holycreeperz** [comment]
> 
> 
> Test like this:
> 
> lolMiner.exe --algo ETHASH --pool us2.ethermine.org:4444 --user 0x352F5521ff3E0F36b0bF9B4041394c4A040D3D56.lolMinerWorker
> 
> Or
> 
> lolMiner.exe --algo ETHASH --pool us1.ethermine.org:4444 --user 0x352F5521ff3E0F36b0bF9B4041394c4A040D3D56.lolMinerWorker

where do i replace that?

**Comment by jgonzis** [comment]
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET!

For one of the 2 options I put you before... and let's see if works...🤞

**Comment by holycreeperz** [comment]
same error message 😔

**Comment by jgonzis** [comment]
Change us1.ethermine.org:4444 for 

eth.2miners.com:2020 

To try other pool and disable firewall

**Comment by holycreeperz** [comment]
both do not work with firewall disabled, I don't know whats going on here

**Comment by jgonzis** [comment]
Try to make a photo of the load of the miner and the later info 🙂 usually that helps to find solutions

**Comment by holycreeperz** [comment]
![image](https://user-images.githubusercontent.com/78260789/106370559-fcb03e00-630f-11eb-9820-0435907e4597.png)
![image](https://user-images.githubusercontent.com/78260789/106370566-0afe5a00-6310-11eb-9619-a48f6c8ebb22.png)

**Comment by jgonzis** [comment]
Can you run CMD as administrator and go to the folder of lolminer  and type the:

lolMiner.exe --algo ETHASH --pool us2.ethermine.org:4444 --user 0x352F5521ff3E0F36b0bF9B4041394c4A040D3D56.lolMinerWorker

Because is all something with the connection...

**Comment by holycreeperz** [comment]
my cmd opens in an irregular location and im not sure how to navigate it to my separate drive

**Comment by holycreeperz** [comment]
Same issue

**Comment by jgonzis** [comment]
To go to the location just type

cd "the complete direction"

Small help: https://www.howtogeek.com/659411/how-to-change-directories-in-command-prompt-on-windows-10/

**Comment by holycreeperz** [comment]
i reopened console and it gave me a normal location and i was able to direct myself through there, but still had the same issue

**Comment by jgonzis** [comment]
try RaveOS/HiveOS/SMOS... in a Pendrive and you will discard... if fails you have something blocking your computer... if connect Windows is blocking the software...

**Comment by holycreeperz** [comment]
you know what, my dad does have a kickass website blocker on our router so that may be it, i'll talk to him about and get back to you later to see if it works

**Comment by holycreeperz** [comment]
after him completely disabling it and allowing both attempted pools, it still isnt working. he is going to check to see if it was blocked through the networks firewall tomorrow morning and from there we will see how it goes.

**Comment by Lolliedieb** [comment]
Have you tried other pools?
us2 did also not work for me, but eu1 did. Also some pools get blocked by some firewalls, usually switching to tls connection can resolve it then.

**Comment by Reccos300** [comment]
I have the same problem. I have tried disabling windows defender, all of the ethermine pools, and different ports. Also, there is never anything in the logs folder? Seems like this would be an issue that should write error report/stack trace or something?

**Comment by jgonzis** [comment]
and try with and SSL connection? in case is a block of the some firewall...

**Comment by Reccos300** [comment]
I don't think this is an issue with the firewall because I am able to use the lolMiner when connecting to a sparkpool... If I can connect to a sparkpool then it seems the issue is unique ethermine pools

**Comment by keddyboys** [comment]
Try disable ipv6. After disabled ipv6 worked for me.

**Comment by holycreeperz** [comment]
the only way I have been able to get this to work is over a vpn. i have actively had ipv6 disabled throughout the entirety of my testing process and still have not been able to figure it out, this is why i assume it is a network firewall issue.

**Comment by warthog02** [comment]
> Whenever I load up the miner it repeatedly tries to connect to my chosen stratum but fails and says
> "Warning: resolve: The requested name is valid, but no data of the requested type was found
> Lost connection to stratum server : or server not reachable.
> Trying to connect in 1 second"
> 
> I'm assuming this is something with my firewall, but allowing access to the .exe isn't enough to fix it, any help?

Had problem with "server not reachable or not in service" when using port 4444 but everything is working well now on port 2020.

**Comment by ggracia** [comment]
I had to disable Two-Way IPS in my Asus router, under AiProtection
<img width="562" alt="image" src="https://user-images.githubusercontent.com/4984462/163319875-6293b58b-5642-4ecb-9f7d-ecb909b08687.png">

**Comment by jgonzis** [comment]
> I had to disable Two-Way IPS in my Asus router, under AiProtection <img alt="image" width="562" src="https://user-images.githubusercontent.com/4984462/163319875-6293b58b-5642-4ecb-9f7d-ecb909b08687.png">

Thx for the feedback
