### ISSUE TITLE
Lolminer consuming lot of ram after 12+ hours (Windows10)

### ISSUE THREAD

**Issue by ab123cd1** [Lolliedieb/lolMiner-releases#1934]
Hi, my lolminer is consuming a lot of ram over time forcing me to restart my pc, i'm mining on windows 10 with lolminer 1.73 and recently updated to lolminer 1.75 (has the same issue)

After 12 or 20 hours of mining my lolminer uses 9gb of ram even when i close the miner, giving me 75% ram usage until i restart windows, is this memory leak?
after 25+ hours it gives me 95% ram usage slowing and freezing the entire system

in the picture it shows consuming 8gb of ram, weird because the default task manager doesn't show it
the name of the process is kryptex_lolminer.exe it has the same hash as the original so it is only a rename
note : i don't have any programs running in background, only mining.

it is my gaming rig that i left mining when not using it
Using windows 10 (22H2)
total virtual memory of 32gb on 2hdd
I have 16gb of ram
mining nexa with one rtx 3080 (driver version 531.68)

![this](https://user-images.githubusercontent.com/88064699/235207040-6e2b13c9-973c-4547-80be-f378ab902a8c.PNG)

**Comment by jgonzis** [comment]
> Hi, my lolminer is consuming a lot of ram over time forcing me to restart my pc, i'm mining on windows 10 with lolminer 1.73 and recently updated to lolminer 1.75 (has the same issue)
> 
> After 12 or 20 hours of mining my lolminer uses 9gb of ram even when i close the miner, giving me 75% ram usage until i restart windows, is this memory leak? after 25+ hours it gives me 95% ram usage slowing and freezing the entire system
> 
> in the picture it shows consuming 8gb of ram, weird because the default task manager doesn't show it the name of the process is kryptex_lolminer.exe it has the same hash as the original so it is only a rename note : i don't have any programs running in background, only mining.
> 
> it is my gaming rig that i left mining when not using it Using windows 10 (22H2) total virtual memory of 32gb on 2hdd I have 16gb of ram mining nexa with one rtx 3080 (driver version 531.68)
> 
> ![this](https://user-images.githubusercontent.com/88064699/235207040-6e2b13c9-973c-4547-80be-f378ab902a8c.PNG)

that 's true the Virtual Memory  in Windows doesn't work as in Linux, where there is not use of it.
