### ISSUE TITLE
Ironfish - Duplicate Mining requests

### ISSUE THREAD

**Issue by fangtasm** [Lolliedieb/lolMiner-releases#1936]
Unable to mine to own Ironfish node using the built-in pool. Results in duplicate mining requests being submitted, no accepted shares, no reported hashrate. Not sure if this has to do with the built in pool utilizing stratum v1. Attempted this from both Windows and HiveOS, it also appears having using --user wallet.work format results in a temporary ban end up needing to remove the work name just leaving the wallet address in place.

**Comment by jgonzis** [comment]
> Unable to mine to own Ironfish node using the built-in pool. Results in duplicate mining requests being submitted, no accepted shares, no reported hashrate. Not sure if this has to do with the built in pool utilizing stratum v1. Attempted this from both Windows and HiveOS, it also appears having using --user wallet.work format results in a temporary ban end up needing to remove the work name just leaving the wallet address in place.

Which Node are you using?.

**Comment by fangtasm** [comment]
The official release V1.1.0

**Comment by jgonzis** [comment]
> The official release V1.1.0

It use the Kerney666 mod connection that pools use too

**Comment by fangtasm** [comment]
Your response did not address the issue.
