### ISSUE TITLE
Lolminer 1.75 still not displaying correctly stats in cmd window 

### ISSUE THREAD

**Issue by auroracoin** [Lolliedieb/lolMiner-releases#1937]
Hi,
Lolminer 1.75 still not displaying correct stats in cmd window. Using windows 11 latest nvidia driver. Rolling back driver. Plz fix. Thx :)
<a href="https://imgur.com/sTGLLwh"><img src="https://i.imgur.com/sTGLLwh.jpg" title="source: imgur.com" /></a>

**Comment by jgonzis** [comment]
> Hi, Lolminer 1.75 still not displaying correct stats in cmd window. Using windows 11 latest nvidia driver. Rolling back driver. Plz fix. Thx :) [![](https://camo.githubusercontent.com/a6df9fc4a56cdea5d6fc018917f47012a650aee7028d4bc4c3a8db1135f97767/68747470733a2f2f692e696d6775722e636f6d2f7354474c4c77682e6a7067)](https://imgur.com/sTGLLwh)

That is the Nvidia Issue of changing the offset, use 528.xx that will solve te problem.

**Comment by auroracoin** [comment]
Thx :)
