### ISSUE TITLE
r9 unsupported device on ethos 1.3.3

### ISSUE THREAD

**Issue by fizroy** [Lolliedieb/lolMiner-releases#194]
Hy i am running lolminer 1.2 on ethos 1.3.3 and im trying to mine etc but i get this message in the miner:

Setup Miner...
Device 0:
    Name:    AMD Radeon (TM) R9 390 Series
    Address: 1:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8111 MByte (8104 MByte free)
    Active:  false (Unsupported device or driver version.)
Device 1:
    Name:    AMD Radeon (TM) R9 390 Series
    Address: 2:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8118 MByte (8111 MByte free)
    Active:  false (Unsupported device or driver version.)
Device 2:
    Name:    AMD Radeon (TM) R9 390 Series
    Address: 3:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8118 MByte (8111 MByte free)
    Active:  false (Unsupported device or driver version.)
Device 3:
    Name:    AMD Radeon (TM) R9 390 Series
    Address: 4:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8118 MByte (8111 MByte free)
    Active:  false (Unsupported device or driver version.)
Device 4:
    Name:    AMD Radeon R9 200 Series
    Address: 5:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8118 MByte (8111 MByte free)
    Active:  false (Unsupported device or driver version.)

what is the problem?

**Comment by jgonzis** [comment]
It seems the amd drivers are not properly installed... which  version do you have?.

**Comment by Lolliedieb** [comment]
Hmm ... the card seems to get somehow detected, but seems something going wrong here .... 
The driver version indeed would be interesting.

**Comment by Lolliedieb** [comment]
I modified 1.21 in a way it allows loading the kernels on older drivers - untested, but will likely work :)
