### ISSUE TITLE
Temp stop mining 

### ISSUE THREAD

**Issue by auroracoin** [Lolliedieb/lolMiner-releases#1948]
So if I put the argument  --tstop 60 the miner will stop mining if core temperature reaches 60c and idol without restart as in this line
set "EXTRAPARAMETERS=--devices 0 --cclk 1470 --coff 450 --mclk 810 --shortstats 30 --tstop 60 --log on"
Correct? This is what I want it to do if it is correct.

**Comment by jgonzis** [comment]
You need to add --tstart value... --tstart 50 will reauto start at 50C.

**Comment by auroracoin** [comment]
I want it NOT to restart if it reaches 60c so is my original bat file correct ? thx

**Comment by jgonzis** [comment]
Your line was ok then!!
