### ISSUE TITLE
v1.76a (Windows):  An attempt was made to access a socket in a way forbidden by its access permissions 

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1951]
`Bin\lolMiner-v1.76a\lolminer.exe --algo UBQHASH --pool ubqhash.mine.zergpool.com:19998 --user ################### --pass c=BTC,mc=UBQ,ID=#########,pl=0 --tls on --ethstratum ETHV1 --log off --apiport 4001 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 9:0`
+---------------------------------------------------------+
|   _       _ __  __ _                   _   _____  __    |
|  | | ___ | |  \/  (_)_ __   ___ _ __  / | |___  |/ /_   |
|  | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |    / /| '_ \  |
|  | | (_) | | |  | | | | | |  __/ |    | |_  / / | (_) | |
|  |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)/_/   \___/  |
|                                          Bugfix Version |
|                                                         |
|              This software is for mining                |
|              Autolykos V2                               |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash III                               |
|              NexaPow                                    |
|              Flux (ZelHash)                             |
|              kHeavyhash (Kaspa)                         |
|              Blake3 (Ironfish & Alephium)               |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|            Made by Lolliedieb, July 2023                |
+---------------------------------------------------------+

Setup Miner...
**bind: An attempt was made to access a socket in a way forbidden by its access permissions [system:10013 at C:/Boost/include/boost-1_82\boost/asio/detail/win_iocp_socket_service.hpp:244:5 in function 'bind']**

**Comment by jgonzis** [comment]
Did restart or run as admin help you?

**Comment by UselessGuru** [comment]
> Did restart or run as admin help you?

Neither did when the issue was present.
Now I cannot reproduce the error :-(
