### ISSUE TITLE
option 'cclk' is ambiguous and matches different versions of 'cclk'

### ISSUE THREAD

**Issue by oceancn** [Lolliedieb/lolMiner-releases#1956]
when i use "cclk=1470,1470" in ".cfg" file, the miner cannot start and the error is "option 'cclk' is ambiguous and matches different versions of 'cclk'", what is this mean?

**Comment by jgonzis** [comment]
It is not proper loading the .cfg with the configuration use a bat or sh file with the line included

**Comment by DerekZiemba** [comment]
This also goes for `mclk` and `pl`.  

Also tried less ambiguous `memclk`, `memclock`, `memoryclk`, `memoryclock`, & `powerlimit`.  But these aren't recognized.

**Comment by jgonzis** [comment]
It is:

--cclk
--mclk
--coff
--moff
--pl
--fan
