### ISSUE TITLE
AMD Radeon HD 8700M - not working

### ISSUE THREAD

**Issue by keanmix** [Lolliedieb/lolMiner-releases#1959]
Hi everyone, 
I tried to mine with AMD Radeon HD 8700M but it keep failing .
I updated the driver to the last AMD version . ( Adrenalin 22.6.1 Recommended (WHQL) - release date 6/23/22 )
I know it's an old graphics card... but still what is the difference?
here is a screenshot of the failure: 
![image](https://github.com/Lolliedieb/lolMiner-releases/assets/142752672/5e53b52a-ea38-4bf7-bf2c-ba97fb734e81)

**Comment by jgonzis** [comment]
That GPU is not supported
