### ISSUE TITLE
Error when allocating memory or building DAG. Disabling card RTX3050

### ISSUE THREAD

**Issue by shaosuyang6** [Lolliedieb/lolMiner-releases#1960]
Error when allocating memory or building DAG. Disabling card
version: Lolminer 1.76a
Windows 11
![屏幕截图 2023-08-24 020933(1)(1)](https://github.com/Lolliedieb/lolMiner-releases/assets/54598709/c5cadf07-7d25-47c4-af2b-66c808674370)

**Comment by jgonzis** [comment]
Normal it needs 6Gb or more for the actual ETHW
