### ISSUE TITLE
lolMiner v1.77 mining ETHASHB3, ETHASH fails on ZergPool

### ISSUE THREAD

**Issue by RainbowMiner** [Lolliedieb/lolMiner-releases#1971]
Win10 64bit, 6x GTX1070 (Pascal), Nvidia driver 537.58

`lolMiner.exe --pool ethashb3.mine.zergpool.com:9996 --user 3DxRETpBoXKrEBQxFb2HsPmG6apxHmKmUx --pass c=BTC,mc=RTH,ID=rbm,pl=0.0015 --devices 0,1,2,3,4,5 --algo ETHASHB3`

Starting lolMiner with -a ETHASHB3 starts and immediately stops with "Closing lolMiner..."

PS: same with RTX3070 rigs
PSPS: same with `-a ETHASH`
PSPSPS: I'll better downgrade. This seems like a general problem.

**Comment by UselessGuru** [comment]
Ethash3b @ ZergPool works for me using:

`Bin\lolMiner-v1.77b\lolminer.exe --algo ETHASHB3 --pool ethashb3.eu.mine.zergpool.com:9996 --user ********************* --pass c=BTC,mc=RTH,ID=*************,pl=0 --tls off --ethstratum ETHV1 --log off --apiport 4001 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 9:0`

Ethash @ ZergPool works for me using:

`Bin\lolMiner-v1.77b\lolminer.exe --algo ETHASH --pool ethash.eu.mine.zergpool.com:9999 --user ************** --pass c=BTC,mc=OCTA,ID=**************,pl=0 --tls off --ethstratum ETHV1 --log off --apiport 4001 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 9:0`

**Comment by RainbowMiner** [comment]
I will try 1.77b today. The fails were with v1.77

**Comment by RainbowMiner** [comment]
I can confirm that the v1.77b version solves the inst-death problem of v1.77
