### ISSUE TITLE
v1.78a (Windows): Error mining KASPA

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1972]
`lolMiner-v1.77b\lolminer.exe --algo KASPA --pool kheavyhash.auto.nicehash.com:9200 --user ***************************.********** --pass x --tls off --log off --apiport 4001 --shortstats 1 --longstats 5 --digits 6 --watchdog exit --dns-over-https 1 --devicesbypcie --devices 9:0`

gives me

`Connecting to pool...
DNS over HTTPS resolve succeeded
Connected to kheavyhash.auto.nicehash.com(34.117.82.207):9200  (TLS disabled)
New extra nonce received: 9952
Authorized worker: *****************************.***************
New target received: 0000000001ffffff (Diff 128)
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMiner`

Same issue with Nvidia GTX 1660 Super, AMD RX580 & RX5700.
Same issue with NiceHash, ZergPool

What is the minimum GPU memory requirement?

**Comment by Venkat2382** [comment]
Same error even in Hive os with 3060, 360ti and 3080 NVIDIA GPU’s.

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Still broken in 1.78a
