### ISSUE TITLE
lolminner cannot work on GTX1650

### ISSUE THREAD

**Issue by tricagames92** [Lolliedieb/lolMiner-releases#198]
GPU 0: insufficient memory for DAG epoch 391.
GPU 0: will be in Zombie mode with reduced hashrate.
GPU 0: Allocation of DAG failed with error: Memory object allocation failure
GPU 0: will be stopped.

**Comment by jgonzis** [comment]
That's normal... you cannot mine ETH in Windows with 4GB, you can only ETC for example

**Comment by tricagames92** [comment]
how to mine etc

**Comment by jgonzis** [comment]
> how to mine etc

Same has eth, you have a bat file, that you need to put a pool and a ETC wallet. You can make a ETC wallet in several exchange or a opensource in myetherwallet

**Comment by tricagames92** [comment]
ok i'll try

**Comment by PvtSec** [comment]
What about the Zombie mode ?

**Comment by jgonzis** [comment]
> What about the Zombie mode ?

Zombie Mode is not working on Nvidia GPU.... They work really well in AMD 4Gb but not in Nvidia...
