### ISSUE TITLE
v1.78a (Windows): How to dual mine EthashB3?

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#1989]
from https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.78 / changes:

Added multiple dual mining options for EthashB3 algorithm (Rethereum). The algorithm can now be used with --dualmode to be set to ALEPHDUAL (Blake3 - Alephium), FISHDUAL (Blake3 - Ironfish), RXDDUAL (Sha512 / 256D, Radiant) or KARLSENDUAL (HeavyHash-Karlsen).

However --algo ETHASHB3 --dualmode xxx don't seem to work.

**Comment by jgonzis** [comment]
At the moment is Buggy sorry. Will be an update soon. Also Nexa and RTH was broken in that realease. Sorry for the fail
