### ISSUE TITLE
mining error messages

### ISSUE THREAD

**Issue by Astronomiez1** [Lolliedieb/lolMiner-releases#199]
I have an AMD Radeon(TM) R6 Graphics which has 4GB of  VRAM so I try to mine eth with the mine_eth_4G.bat file and I've edited it to the pool and my wallet but I get these error messages:

Active:  false (Unsupported device or driver version.)

All devices deselected or failed compatiblity check. Closing lolMiner
Waiting for 10 seconds, press a key to continue ...

Does anyone know why this is happening?

**Comment by jgonzis** [comment]
If you are trying to mine ETH in Windows with 4Gb cards is not possible... you have to use Linux. And if that happens is the opencl driver version you have installed

**Comment by Astronomiez1** [comment]
can I use a virtual machine or can do I have to change my os

**Comment by jgonzis** [comment]
Some people have try virtual, but it stills the same problem... Memory is used by Windows... use a pendrive of another Linux OS

**Comment by jackdwaz** [comment]
hive os can be useful too instead of windows 10
