### ISSUE TITLE
Only 8 GPU working(Karlsen/RaveOS)

### ISSUE THREAD

**Issue by pboguk** [Lolliedieb/lolMiner-releases#1998]
Have a 10 GPU RIG(5700XT) and noticed that miner can work with no more 8 GPU.
In a case of 9 or 10 GPU - I got error:

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 9
Killed

No matter which GPU's disabled - only 8 can work simultaneously.
Tested on 1.78, 1.79 and 1.8

When using other miners - there is no problem with 8 and more GPU's

**Comment by jgonzis** [comment]
Can you try to update drivers? it is important to have new drivers for the bandwith

**Comment by pboguk** [comment]
Latest RaveOS release has amdgpu-5.13.11.21.50.
Is it enough or I need to have latest drivers?

**Comment by jgonzis** [comment]
If is possible to have newer drivers will be better.

**Comment by pboguk** [comment]
Unfortunately, RaveOS has only version above.
Anyway, than you for suggestion.
Hope, you'll find solution in future)

**Comment by jgonzis** [comment]
I thought a trick to try add:

--dualmode KARLSEN --dualpool your pool --dualuser your wallet --dualdevices 5,6,7,8,9

Just try to split like 2 miners run. 5 and 5 if that helps.

**Comment by pboguk** [comment]
Seems diver is the problem.
Installed Amd OpenCL driver v.20.40 (PAL) over ROCm and problem gone.
Thank you!

**Comment by jgonzis** [comment]
Thx for the feedback
