### ISSUE TITLE
Mining randomly stops/disconnects

### ISSUE THREAD

**Issue by ec3566** [Lolliedieb/lolMiner-releases#200]
When mining, the cmd window will not update, will be stuck on the last status message for a while, and it stalls. After a while, it disconnects. Ctrl+C fixes it, but this occurs at least once an hour.

**Comment by jgonzis** [comment]
You can use the following script that will allow you to autorestart in case the Mhs go down... and you don't need to click any Ctrl+C... and you can let more "automatic" mining



@echo off

setlocal enableDelayedExpansion
set url=http://127.0.0.1:4444
set file=lolMiner.json
set tmpfile=Perfomance.json

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"

Rem #################################
Rem ## End of user-editable part ##
Rem #################################

:loop
start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444

:mining
timeout 120
type NUL > %file%
type NUL > %tmpfile%
echo Proving Stats, press CTRL-C and Y to Quit!
certutil -urlcache -split -f %url% %file%

fc %file% %tmpfile% > nul
if errorlevel 1 (goto online) else (goto crash)

:online
findstr "Performance_Summary" %file% > %tmpfile%

FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x

for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)

:restart
echo "Killing Process"
taskkill /IM "lolMiner.exe" /F
echo "Restarting lolMiner"
goto loop

:crash
echo "LolMiner Not Running, restarting lolMiner"
goto loop

**Comment by Miller-GbG** [comment]
Sorry for my stupid question... SW Engineering is not my area. 

Do I put this script in the mining BAT-file`?

> You can use the following script that will allow you to autorestart in case the Mhs go down... and you don't need to click any Ctrl+C... and you can let more "automatic" mining
> 
> @echo off
> 
> setlocal enableDelayedExpansion
> set url=http://127.0.0.1:4444
> set file=lolMiner.json
> set tmpfile=Perfomance.json
> 
> Rem #################################
> Rem ## Begin of user-editable part ##
> Rem #################################
> 
> set "POOL=eth.2miners.com:2020"
> set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"
> 
> Rem #################################
> Rem ## End of user-editable part ##
> Rem #################################
> 
> :loop
> start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444
> 
> :mining
> timeout 120
> type NUL > %file%
> type NUL > %tmpfile%
> echo Proving Stats, press CTRL-C and Y to Quit!
> certutil -urlcache -split -f %url% %file%
> 
> fc %file% %tmpfile% > nul
> if errorlevel 1 (goto online) else (goto crash)
> 
> :online
> findstr "Performance_Summary" %file% > %tmpfile%
> 
> FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x
> 
> for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
> if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)
> 
> :restart
> echo "Killing Process"
> taskkill /IM "lolMiner.exe" /F
> echo "Restarting lolMiner"
> goto loop
> 
> :crash
> echo "LolMiner Not Running, restarting lolMiner"
> goto loop

**Comment by jgonzis** [comment]
> Sorry for my stupid question... SW Engineering is not my area.
> 
> Do I put this script in the mining BAT-file after the already existing loop?
> 
> > You can use the following script that will allow you to autorestart in case the Mhs go down... and you don't need to click any Ctrl+C... and you can let more "automatic" mining
> > @echo off
> > setlocal enableDelayedExpansion
> > set url=http://127.0.0.1:4444
> > set file=lolMiner.json
> > set tmpfile=Perfomance.json
> > Rem #################################
> > Rem ## Begin of user-editable part ##
> > Rem #################################
> > set "POOL=eth.2miners.com:2020"
> > set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"
> > Rem #################################
> > Rem ## End of user-editable part ##
> > Rem #################################
> > :loop
> > start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444
> > :mining
> > timeout 120
> > type NUL > %file%
> > type NUL > %tmpfile%
> > echo Proving Stats, press CTRL-C and Y to Quit!
> > certutil -urlcache -split -f %url% %file%
> > fc %file% %tmpfile% > nul
> > if errorlevel 1 (goto online) else (goto crash)
> > :online
> > findstr "Performance_Summary" %file% > %tmpfile%
> > FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x
> > for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
> > if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)
> > :restart
> > echo "Killing Process"
> > taskkill /IM "lolMiner.exe" /F
> > echo "Restarting lolMiner"
> > goto loop
> > :crash
> > echo "LolMiner Not Running, restarting lolMiner"
> > goto loop

You should overwrite it all it is a complete bat file :-)

**Comment by Miller-GbG** [comment]
Incl the wallet? ;) 


> You should overwrite it all it is a complete bat file :-)

**Comment by jgonzis** [comment]
> Incl the wallet? ;)
> I said I wasnt working with SW development... I didnt say I was stupid. hehe.
> 
> > You should overwrite it all it is a complete bat file :-)
put as new bat file and later put your wallet and pool that you like :-)

**Comment by Miller-GbG** [comment]
Hehe yes jjust kidding. 

But I have this part in the BAT-file right now. Not needed?

_":loop
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto loop
)
"_

> > Incl the wallet? ;)
> > I said I wasnt working with SW development... I didnt say I was stupid. hehe.
> > > You should overwrite it all it is a complete bat file :-)
> > > put as new bat file and later put your wallet and pool that you like :-)

**Comment by jgonzis** [comment]
With last version 1.24a that loop is perfect ... :-)

**Comment by Miller-GbG** [comment]
> With last version 1.24a that loop is perfect ... :-)

So nothing else needed? 

Because I get some random stops at times. Happened twice today already. Luckily I have a email notification so I can go in and manually restart when I am home. But if I am not, I want it to restart itself.

**Comment by jgonzis** [comment]
> > With last version 1.24a that loop is perfect ... :-)
> 
> So nothing else needed?
> 
> Because I get some random stops at times. Happened twice today already. Luckily I have a email notification so I can go in and manually restart when I am home. But if I am not, I want it to restart itself.

Which is your OC config? some times a little bit of more extra Voltage help...

**Comment by ronaldkunenborg** [comment]
Lolminer 1.21 stops randomly after anything from 30 to 70 jobs received. So I have added a "goto loop" at the end. With a timeout of 10 seconds to let the card cool off from 100C to about 70C. Is there a way to get lolminer to report *why* it stops?

**Comment by jgonzis** [comment]
> Lolminer 1.21 stops randomly after anything from 30 to 70 jobs received. So I have added a "goto loop" at the end. With a timeout of 10 seconds to let the card cool off from 100C to about 70C. Is there a way to get lolminer to report _why_ it stops?

If card is at 100C you should check your OC parameters that's a lot for the card... it could stop for this high temp...

**Comment by ronaldkunenborg** [comment]
> > Lolminer 1.21 stops randomly after anything from 30 to 70 jobs received. So I have added a "goto loop" at the end. With a timeout of 10 seconds to let the card cool off from 100C to about 70C. Is there a way to get lolminer to report _why_ it stops?
> 
> If card is at 100C you should check your OC parameters that's a lot for the card... it could stop for this high temp...

I increased the memory clock to 1800 and the fan speed to 66%, which lowered memory temps to 96C. That seemed to have helped, it's running fine now.

**Comment by Jimmyjeeb** [comment]
> > Sorry for my stupid question... SW Engineering is not my area.
> > Do I put this script in the mining BAT-file after the already existing loop?
> > > You can use the following script that will allow you to autorestart in case the Mhs go down... and you don't need to click any Ctrl+C... and you can let more "automatic" mining
> > > @echo off
> > > setlocal enableDelayedExpansion
> > > set url=http://127.0.0.1:4444
> > > set file=lolMiner.json
> > > set tmpfile=Perfomance.json
> > > Rem #################################
> > > Rem ## Begin of user-editable part ##
> > > Rem #################################
> > > set "POOL=eth.2miners.com:2020"
> > > set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"
> > > Rem #################################
> > > Rem ## End of user-editable part ##
> > > Rem #################################
> > > :loop
> > > start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444
> > > :mining
> > > timeout 120
> > > type NUL > %file%
> > > type NUL > %tmpfile%
> > > echo Proving Stats, press CTRL-C and Y to Quit!
> > > certutil -urlcache -split -f %url% %file%
> > > fc %file% %tmpfile% > nul
> > > if errorlevel 1 (goto online) else (goto crash)
> > > :online
> > > findstr "Performance_Summary" %file% > %tmpfile%
> > > FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x
> > > for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
> > > if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)
> > > :restart
> > > echo "Killing Process"
> > > taskkill /IM "lolMiner.exe" /F
> > > echo "Restarting lolMiner"
> > > goto loop
> > > :crash
> > > echo "LolMiner Not Running, restarting lolMiner"
> > > goto loop
> 
> You should overwrite it all it is a complete bat file :-)

What is this part:
set url=http://127.0.0.1:4444
set file=lolMiner.json
set tmpfile=Perfomance.json
should I modify anything here?

**Comment by jgonzis** [comment]
Try new version with CUDA Solver and properly watchdog
