### ISSUE TITLE
v1.80 - Device 0 Active: false () on RTX 3090 

### ISSUE THREAD

**Issue by KrazeyKami** [Lolliedieb/lolMiner-releases#2005]
Hi, 
I'm trying to use lolminer for mining kaspa. This is the error I get:

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 0
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    NVIDIA GeForce RTX 3090
    Address: 11:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  24575 MByte
    Active:  false ()

Connecting to pool...
DNS over HTTPS resolve succeeded
Connected to kas-euro.f2pool.com(172.65.197.4):1400  (TLS disabled)
New extra nonce received: 0e8b
Authorized worker: {redacted}
New target received: 0000000003ffffff (Diff 64)
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMiner

**Comment by xXEgorproXx** [comment]
+ i too have this problem on my 3060 lhr

**Comment by xXEgorproXx** [comment]
im find the way, use older versions, i tried 0.76 and it works

**Comment by KrazeyKami** [comment]
> im find the way, use older versions, i tried 0.76 and it works

I've tried version 1.76a and it works like a charm. Thanks!

**Comment by xXEgorproXx** [comment]
> > im find the way, use older versions, i tried 0.76 and it works
> 
> I've tried version 1.76a and it works like a charm. Thanks!
can you help me too? im new

**Comment by jgonzis** [comment]
Yes Kaspa was disable in 1.77, you are right.
