### ISSUE TITLE
All devices deselected or failed compatibility check

### ISSUE THREAD

**Issue by BarbzYHOOL** [Lolliedieb/lolMiner-releases#2006]
https://github.com/Lolliedieb/lolMiner-releases/issues/2004#issue-2037841284
Same but "--devices 0" creates another error for me:

"OpenCL driver detected.
Number of OpenCL supported GPUs: 0 
No Cuda driver or GPUs detected. "

But my GPU should work with OpenCL, got a Radeon HD 7850, and I got clinfo to work with `apt install mesa-opencl-icd`

Same as this dude https://github.com/Lolliedieb/lolMiner-releases/issues/1968

**Comment by jgonzis** [comment]
To really old GPU sorry

**Comment by BarbzYHOOL** [comment]
are you sure?? it says OpenCL is supported on AMD page @jgonzis
