### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by stp230** [Lolliedieb/lolMiner-releases#201]
![mine](https://user-images.githubusercontent.com/78352217/106446872-a3422f00-6435-11eb-988d-bbee14c822f3.PNG)
its been stuck here for about an hour, is that normal? it is my first time running a miner.

**Comment by jackdwaz** [comment]
it seems like it's stuck due to default oc settings. you may need to downclock your core and power usage in msi afterburner... what are your current settings?

**Comment by jgonzis** [comment]
Try new CUDA Solver in new releases that will help the stability and the stales too
