### ISSUE TITLE
RX 570 /RX 580 Unsupported device driver A22.20.5 (5.18.2301) hiveos

### ISSUE THREAD

**Issue by renardkgit** [Lolliedieb/lolMiner-releases#2016]
RX 570 /RX 580 Unsupported device driver A22.20.5 (5.18.2301) hiveos

**Comment by renardkgit** [comment]
![image](https://github.com/Lolliedieb/lolMiner-releases/assets/153966088/d97ecc3a-7841-465a-9fd6-215ad1874775)

**Comment by marcoasj** [comment]
yes, we are waiting for this.                
.for when?

**Comment by marcoasj** [comment]
are you working on it?

**Comment by imsudipk** [comment]
same issue fround , but i use older version of lolminer 1.70 and 1.71 beta there was no problem but update lolminer have some issue when its we don't know .

**Comment by marcoasj** [comment]
last version of lolminer Unsupported for Pyrin. Karlsen works correctly. the question is if the support for pyrin on polaris RX570/580 its coming or not.
THNKS.

**Comment by jgonzis** [comment]
> RX 570 /RX 580 Unsupported device driver A22.20.5 (5.18.2301) hiveos

Now supported in 1.82 :-)
