### ISSUE TITLE
lolminer-1.83 SwitchHiveOS IRON The profit is not calculated correctly !

### ISSUE THREAD

**Issue by kadiev75** [Lolliedieb/lolMiner-releases#2018]
I am attaching a photo...
![error](https://github.com/Lolliedieb/lolMiner-releases/assets/73716841/7f2a4792-2429-46ba-b7e0-685e3d1eb1f5)

**Comment by kadiev75** [comment]
help :)

**Comment by kadiev75** [comment]
?????????

**Comment by jgonzis** [comment]
Iron need to go in Mhs not Ghs.

**Comment by kadiev75** [comment]
IRON,stratum+ssl://ironfish-eu.unmineable.com:4444,USDT:TBBDSkmKd3wRjTetXJZmrmxcnQttz7E4rD.Ceco_01#5ssm-68cy,100000/400/0.13

Again it doesn't think anything I think I set it to Mhz

**Comment by jgonzis** [comment]
> IRON,stratum+ssl://ironfish-eu.unmineable.com:4444,USDT:TBBDSkmKd3wRjTetXJZmrmxcnQttz7E4rD.Ceco_01#5ssm-68cy,100000/400/0.13
> 
> Again it doesn't think anything I think I set it to Mhz

I send you by Telegram q message, share me the flightsheet to test it properly :-)
