### ISSUE TITLE
GRIN (cuckatoo32) not working on 6650XT and 5700XT

### ISSUE THREAD

**Issue by odee2004** [Lolliedieb/lolMiner-releases#2032]
I'm using lolminer 1.82a on WIndows 11. AMD driver version PRO Edition 23.Q4.

GPU BIOS not modded and not OCed.

Here's the error.

![image](https://github.com/Lolliedieb/lolMiner-releases/assets/6821225/a232b96f-f5e4-41a1-900a-b41f544ae7c3)

**Comment by jgonzis** [comment]
You need more memory. That's why is not allocaded

**Comment by odee2004** [comment]
System RAM or VRAM?

Both of my GPU have 8GB of VRAM each.

**Comment by jgonzis** [comment]
VRAM, more than 8Gb are requiered

**Comment by odee2004** [comment]
I see. But based on hasrate.no, Cuckatoo32 is the most profitable crypto for 6650 XT. Maybe they are wrong or is there a 6650 XT with more than 8GB of VRAM.

Anyways, thanks for the response!
