### ISSUE TITLE
lolMiner 1.83 GRAM mining - error in loading kernel

### ISSUE THREAD

**Issue by ruMiner** [Lolliedieb/lolMiner-releases#2035]
![Снимок экрана 2024-02-12 141421](https://github.com/Lolliedieb/lolMiner-releases/assets/99076726/da41b373-ff87-445b-a4cf-ced5163c09a7)
Anybody can help me with this issue? Default overclocking settings.

**Comment by albamef** [comment]
I have this problem too

**Comment by albamef** [comment]
Need new driver for NVIDIA. Version 525 or newer

**Comment by ruMiner** [comment]
> Need new driver for NVIDIA. Version 525 or newer

Thank you! I'll try to install new drivers.
