### ISSUE TITLE
HELP -PLS - LoLminer-1.83.SwitchHiveOS - It does not switch the PYI

### ISSUE THREAD

**Issue by kadiev75** [Lolliedieb/lolMiner-releases#2041]
After a lot of research I came to the conclusion that when it is the most profitable KLS from the algo.conf file it correctly takes the configuration and writes it to the lol.conf file and starts it correctly. It is the same when ALPH starts, but when PYI is the most profitable, it does not save the correct parameters in lol.conf and leaves the last ones ... and does not start mining PYI
on the last most profitable. I am attaching a photo where the problem is clearly visible:

![error](https://github.com/Lolliedieb/lolMiner-releases/assets/73716841/420a7ef2-be72-4ac7-984c-365084b3771b)
![error2](https://github.com/Lolliedieb/lolMiner-releases/assets/73716841/0c9c763f-a0c9-4584-b247-f9af7f4e84ea)

**Comment by jgonzis** [comment]
Problem should come from the flightsheet

**Comment by kadiev75** [comment]
You are great, thank you very much, the problem is fixed :)

**Comment by kadiev75** [comment]
You are great, thank you very much, the problem is fixed :)

**Comment by kadiev75** [comment]
You are great, thank you very much, the problem is fixed :)
