### ISSUE TITLE
lolMiner 1.84 (HiveOS) mining Nexa, GPUs not accepting all arguments.

### ISSUE THREAD

**Issue by footballguy05** [Lolliedieb/lolMiner-releases#2048]
I have a mixed rig of Nvidia cards, 3 x 1660 supers, 2 x 3060 Tis, and 1 x 3070.  running nvidia driver 535.161.07.  

Using the Miner Config Extra arugments: 

--coff 120, 120, 120, 250, 250, 250 --cclk 1470, 1470, 1470, 1470, 1470, 1470 --mclk 5000, 5000, 5000, 5000, 5000, 5000

My power levels are set in the HiveOS page, not in the miner file. Those are working fine at 125, 175, and 200, respectively. 

However, when my miner starts running, I noticed the GPUs are not taking all the assigned values.  Its grabbing the first number of each of the parameters and applying it to every card.  All of my offsets are going in at +120, and the 3060Tis and the 3070, which are cards 4,5, and 6, are not getting the offset of +250.  For trial and error, I also changed the core lock to 1550 for those cards, but the same thing happened.  the 1470 value was still applied to all cards.  Is there a reason for this? is there an issue with my syntax? Or is an error causing this? 

![IMG_6906](https://github.com/Lolliedieb/lolMiner-releases/assets/60530964/37b6cc19-b76e-4c52-8cb5-4aeb7a5aadd6)
![IMG_6905](https://github.com/Lolliedieb/lolMiner-releases/assets/60530964/52b1cec0-5644-4640-ad00-695ab0c21899)

**Comment by jgonzis** [comment]
You should remove spaces between parameters it is --coff 120,120,120 not 120, 120, 120...ñ
