### ISSUE TITLE
Please add  the capacity to read the local energy cost and decide if mining is profitable accordingly

### ISSUE THREAD

**Issue by Supermagnum** [Lolliedieb/lolMiner-releases#2055]
A example is:
https://data.nordpoolgroup.com/auction/day-ahead/prices?deliveryDate=latest&deliveryAreas=AT&currency=EUR&aggregation=Hourly

**Comment by jgonzis** [comment]
> A example is: https://data.nordpoolgroup.com/auction/day-ahead/prices?deliveryDate=latest&deliveryAreas=AT&currency=EUR&aggregation=Hourly

That is already done with AUTOSwitch... Where you can select the cost of the energy and add it
