### ISSUE TITLE
Lolminer won't run on AMD R7 M260

### ISSUE THREAD

**Issue by annavee** [Lolliedieb/lolMiner-releases#206]
Hi all - new to git and using lolminer. 

Would lolminer run on my laptop? Just curious to see how the process happens - (was following a youtube video that said lolminer was the best software for laptops)  :)

Any advice would be great.....A
![Lolminer kicking me out](https://user-images.githubusercontent.com/11341337/106591429-60ea3080-65a2-11eb-88f7-9bf297106312.png)

**Comment by Lolliedieb** [comment]
As you can see it only has 2G of memory. Mining Ethash - or any modern algorithm - is almost impossible, because all solvers would run out of memory. That is why it is not supported.
