### ISSUE TITLE
ALGO+ZIL      ezil.me close 25.03.2024 

### ISSUE THREAD

**Issue by IceSpar** [Lolliedieb/lolMiner-releases#2060]
Hello  ezil.me close 25.03.2024 after my miner started giving this message for Windows miners:
![image](https://github.com/Lolliedieb/lolMiner-releases/assets/165613219/735f86c5-c953-4baa-9ca8-c00356ab7fea)

"Could not resolve host eu.ezil.me "
as a result, the part that should mine Zip does not work. The part that mine is the main algorithm works
I mine Zil on k1pool in Windows . The support replied that everything was fine with them
Is it possible that lolminer fee is configured by ezel.me pool?

**Comment by jgonzis** [comment]
Please, try to use new ZIL Version, the close of EZIL has affect to our check Windows ZIL

**Comment by IceSpar** [comment]
Yep. thank you for fast fix.
