### ISSUE TITLE
What is new cmd to mine GRAM??

### ISSUE THREAD

**Issue by piwawa** [Lolliedieb/lolMiner-releases#2064]

**Comment by jgonzis** [comment]
Code ALPH:

--dualmode ALEPHDUAL --dualpool your_pool_ALPH --dualuser your_WALLET_ALPH.%WORKER_NAME% _your_OC_


Code GRAM:

--dualmode TONDUAL --dualpool your_pool_GRAM --dualuser your_WALLET_GRAM.%WORKER_NAME% _your_OC_


Code HTN/KLS/NTL

--dualmode KARLSENDUAL --dualpool your_pool_KLS --dualuser your_WALLET_HTN/KLS/NTL.%WORKER_NAME% _your_OC_


Code RXD:

--dualmode RXDDUAL --dualpool your_pool_RXD --dualuser your_WALLET_RXD.%WORKER_NAME% _your_OC_



Code CAS/NXL/PYI

--dualmode PYRINDUAL --dualpool your_pool_PYI --dualuser your_WALLET_CAS _your_OC_
