### ISSUE TITLE
fishhash problem!

### ISSUE THREAD

**Issue by MTCHANNELL** [Lolliedieb/lolMiner-releases#2065]
![image](https://github.com/Lolliedieb/lolMiner-releases/assets/94814602/7729ad82-02bb-4628-8df2-fa210a22b12c)

As seen in the picture, I constantly get the "lost connections" error in the "fishhash" algorithm. I submitted a nicehash ticket. I am waiting for a reply. I wanted to point out the same problem. I couldn't figure out whether the problem is with nicehash or minerda.

**Comment by jgonzis** [comment]
That are problem from the nicehash servers disconnections. As you Se you got shares without problems... something is disconnecting the pool in nicehash

**Comment by MTCHANNELL** [comment]
"Nicehash" made a different statement on this issue. But I'm not trying to find a solution anymore. But now I gave up on the "fishhash" algorithm in "nicehash". I am mining on the "fishhash" algorithm in a different pool. The problem is not with lolminer. Thank you very much for your interest.
