### ISSUE TITLE
1.86 - GRAM/TON dual mining infinite recalculation loop

### ISSUE THREAD

**Issue by aiwash** [Lolliedieb/lolMiner-releases#2071]
Hi, Win11, RTX4070

![image](https://github.com/Lolliedieb/lolMiner-releases/assets/75749338/38d770ff-a31a-4544-8982-591f32f87a8e)

I always have that message "Restarting dual tune to significant clock change" while running the miner.

.bat file:

lolMiner.exe --algo FISHHASH --pool de.ironfish.herominers.com:1145 --user XXX --dualmode TONDUAL --dualpool ton.hashrate.to:4002 --dualuser XXX --devices 0 --ton-mode 6 --cclk 2010 --moff 2000 --pl 210 
pause

The moment the turning starts, I have the defined clocks. After the end of the tuning, GPU loses around 20% clk speed and that restarting dual tuning in the infinite loop.

Single coin mining is working as intended.

So I left it mining for some time, the GPU is very cold, looks like it's not mining at all.

Please help.

**Comment by jgonzis** [comment]
Use new 1.87. Problem is that you are limited by the Power Limit. Don't use Power Limit. Use --cclk values

**Comment by aiwash** [comment]
I will try to update the miner and get back to you. Removing GPU configuration from the miner is not solving the issue.
btw, the arguments are taken from the "hashrate.no"

**Comment by aiwash** [comment]
Updated to version 1.87. Removed the power limit.
But the clock optimization got to be less often (every 2 min, not 30s). After the "dual mine optimizations", the clock drops from 2010 to around 1600.
![image](https://github.com/Lolliedieb/lolMiner-releases/assets/75749338/0374fd6b-c6c6-4a8b-b2b6-905ba9e38126)
Meaning, it did not help.

**Comment by jgonzis** [comment]
As I told you... clock changes because your config touch the power limit. If that happens will retune. Reduce --cclk value or remove pl

**Comment by aiwash** [comment]
I removed the power limit and clock speed reducing is not helping either, it is happening in any clock speed. Before setting it in lol miner I used Afterburner.
Once again, no issues with single coin mining.
Or you asking me to set 1400cclk? for 4070 with the 2550cclk out of the box it makes no sence.

**Comment by jgonzis** [comment]
Try --cclk 1400 and only mining not using others apps.  That will not change the clock. And will not retune. You can also block a factor always with --dualfactor value

**Comment by aiwash** [comment]
Well, the clock fixed on 1410, but it looks useless with 2kMh. I must play with the dual factor value indeed.
