### ISSUE TITLE
Low Gram hashrate on nwer versions compared to 1.84

### ISSUE THREAD

**Issue by Mancion** [Lolliedieb/lolMiner-releases#2073]
Hello, I started mining gram on 1.84 then switched to 1.86 to mine gram+fish. When I wanted to mine just gram on 1.86 and then on 1.87 I got way lower hashrate. What can be the problem? Gram +fish hashrate seems normal ( stats from hashrate.no) 
![! 84 gram](https://github.com/Lolliedieb/lolMiner-releases/assets/167348545/f4cc6257-7b7c-46e5-9323-d2d611b4d30a)
![1 87 gram](https://github.com/Lolliedieb/lolMiner-releases/assets/167348545/eb9e2363-de83-4d5b-a38c-71d8266278c3)

**Comment by jgonzis** [comment]
Upsss that is a good one... We will check Thanks for the feedback

**Comment by jgonzis** [comment]
Solved with new update 1.88
