### ISSUE TITLE
Autolykos on 4GB cards

### ISSUE THREAD

**Issue by bitcoincff** [Lolliedieb/lolMiner-releases#2084]
Hello, I am having problems mining autolykos on 4gb cards. It connects to the pool, creates the table, receives the jobs, but after a short time it causes problems. This has been happening since 05/05/2024 before that date, it worked fine

**Comment by jgonzis** [comment]
Dag has increase... are you trying it in Linux? That loads less memory?

**Comment by vovanella** [comment]
I have also had problems for several days
DAG size ERGO = 3.442 GB
