### ISSUE TITLE
1.75MH/s on 5500xt 4GB

### ISSUE THREAD

**Issue by yahia20** [Lolliedieb/lolMiner-releases#209]
GPU: 5500xt 4GB
driver: amdgpu-pro 20.40
the normal hash rate of the 5500xt would be around ~23MH/s or more according to google why am I getting only up to 1.75MH/s??
I DAG size is more than 4GB but still it shouldn't drop 87% of performance!
Is there any way to mine ETH with normal hash rate?? For now I am mining RVN but that's the third of the profit according to minerstat

**Comment by jgonzis** [comment]
> GPU: 5500xt 4GB
> driver: amdgpu-pro 20.40
> the normal hash rate of the 5500xt would be around ~23MH/s or more according to google why am I getting only up to 1.75MH/s??
> I DAG size is more than 4GB but still it shouldn't drop 87% of performance!
> Is there any way to mine ETH with normal hash rate?? For now I am mining RVN but that's the third of the profit according to minerstat

Have you use the --4g-alloc-size 4072 for example

**Comment by yahia20** [comment]
DAG doesn't genrate if above 3900 for some reason even though radeontop says I have enough free vram

**Comment by yahia20** [comment]
after trying to reinstall the amdgpu pro driver 4000 worked  but now hash rate is at max 0.35MH/s

**Comment by djhammett** [comment]
Hey everyone! I'm new to mining and recently purchased a GTX 1060 6GB card for its efficiency to ethash power. I am in IT so I know how to work my way around hardware but when it comes to software limitations I'm a bit behind. I'm sitting around 15.75mh/s which isn't bad but online I find results showing up to 22mh/s.  This is a gigabyte OC card that can turbo where needed.  Even OC the card theoretically by 16% wouldn't hit the target of 22mh/s.  My clocks without the OC software are 1974mhz at 64degrees Celcius pulling almost 100watts using the most up to date driver as of 2/11/21.  There is more room to squeeze power but something possibly in the batch file could be dragging it down? Any help is appreciated.

Thanks,

**Comment by jgonzis** [comment]
> Hey everyone! I'm new to mining and recently purchased a GTX 1060 6GB card for its efficiency to ethash power. I am in IT so I know how to work my way around hardware but when it comes to software limitations I'm a bit behind. I'm sitting around 15.75mh/s which isn't bad but online I find results showing up to 22mh/s. This is a gigabyte OC card that can turbo where needed. Even OC the card theoretically by 16% wouldn't hit the target of 22mh/s. My clocks without the OC software are 1974mhz at 64degrees Celcius pulling almost 100watts using the most up to date driver as of 2/11/21. There is more room to squeeze power but something possibly in the batch file could be dragging it down? Any help is appreciated.
> 
> Thanks,

Hi, I recommend you to use MSI Afterburner if you are in Windows to push the memory, the core is important but the most important is the memory... Nvidia lines 10x0 had a bottleneck with the size of the DAG so old Mining values are not actual... you can make a try with ETHASH and see how the Mhs are higher, because the DAG size is smaller

**Comment by djhammett** [comment]
> > Hey everyone! I'm new to mining and recently purchased a GTX 1060 6GB card for its efficiency to ethash power. I am in IT so I know how to work my way around hardware but when it comes to software limitations I'm a bit behind. I'm sitting around 15.75mh/s which isn't bad but online I find results showing up to 22mh/s. This is a gigabyte OC card that can turbo where needed. Even OC the card theoretically by 16% wouldn't hit the target of 22mh/s. My clocks without the OC software are 1974mhz at 64degrees Celcius pulling almost 100watts using the most up to date driver as of 2/11/21. There is more room to squeeze power but something possibly in the batch file could be dragging it down? Any help is appreciated.
> > Thanks,
> 
> Hi, I recommend you to use MSI Afterburner if you are in Windows to push the memory, the core is important but the most important is the memory... Nvidia lines 10x0 had a bottleneck with the size of the DAG so old Mining values are not actual... you can make a try with ETHASH and see how the Mhs are higher, because the DAG size is smaller

jgonzis thanks for responding so fast. Am I able to use MSI software with a Gigabyte card? Also I forgot to mention the batch file shows my mining as 15.75 but also shows my pool mining at 20.5mh/s. Should I assume the 20.5mh/s is my actual output not the 15.75mh/s block? I'm going to attach a photo for you.
![image](https://user-images.githubusercontent.com/78917530/107658748-4ca9d180-6c3b-11eb-9564-a63df453cacb.png)

**Comment by jgonzis** [comment]
The speed of the pool is the luck you have... more that Speed giving more solution that you should for your speed... lower that mean less solution that you should. 

You can use MSI Afterburner with nearly all Cards... Gigabyte works too great. Then you can test easy... pushing CORE, Push MEM and reduce PowerLimit ... to try to get your best share

**Comment by djhammett** [comment]
> The speed of the pool is the luck you have... more that Speed giving more solution that you should for your speed... lower that mean less solution that you should.
> 
> You can use MSI Afterburner with nearly all Cards... Gigabyte works too great. Then you can test easy... pushing CORE, Push MEM and reduce PowerLimit ... to try to get your best share

Got it, so I shouldn't expect the promised 22mh/s 24hrs a day. I took your advice and bumped the memory so it hovers at 8600mhz and now I'm hashing at 18.8mh/s which is 20% better than my previous 15.75mh/s. I underclocked the core as it didn't change my hashrate. I've been comparing the underclocked core with the overclocked core at 18.8mh/s so no difference. I'm keeping it underclocked to keep temps down and allowing the fans to cool the VRAM since that seems to be doing most of the work. Now I'll see if I can lower the power draw until I dip below 18.8mh/s for max efficiency. Thanks again for the help!

**Comment by bornik332211** [comment]
Does the rx 5500 xt 4 gb have any future for mining , i see that the mining is not so good on her but i read that there is potential for it and now i dont know if i should wait for the new update for zombie mode for her or resell her and buy a rx 570 or rx 580
