### ISSUE TITLE
Hello needed please 

### ISSUE THREAD

**Issue by Walker-ctrl** [Lolliedieb/lolMiner-releases#2090]
UQCILWtnzWkI7aMt-J-ynxGLku_fjD9Hxu5f0g5qoTcdQLia

**Comment by Walker-ctrl** [comment]
Anyone 
UQCILWtnzWkI7aMt-J-ynxGLku_fjD9Hxu5f0g5qoTcdQLia

**Comment by DraftedDev** [comment]
what?
