### ISSUE TITLE
1.88 incorrect Variable Gram +ironfish 

### ISSUE THREAD

**Issue by SunShots** [Lolliedieb/lolMiner-releases#2092]
![incorrect gram_iron](https://github.com/user-attachments/assets/f94f3ebd-f965-45b9-a73a-74979925323a)
![correct gram_iron](https://github.com/user-attachments/assets/40735122-589f-4f30-9e20-356afc8a10c2)

by default, the variables are incorrect on this sheet I did not check others as I don't need to use those but it might be prevalent throughout. I mined to this DUSER for a full day before I recognized the issue

**Comment by jgonzis** [comment]
You are right needs to be changed. Added some ZIP Windows File in 1.90 to help in the duals.
