### ISSUE TITLE
lolMiner 1.88 doesnt apply OC settings by command in rigs with mixed amd and nvidia cards.

### ISSUE THREAD

**Issue by daro84b** [Lolliedieb/lolMiner-releases#2095]
Hi, maybe there is a bug because when I work only with NVIDIA cards, OC applies correctly, but in a mixed rig with 9 AMD cards and 3 NVIDIA, OC only apply sometimes for 1st and 2nd card, sometimes for 2nd and 3rd nvidia card.
If you need to emulate it, it happened in a rig where 1st card is AMD, then 2nd to 4th are NVIDIA, then the rest are AMD.
Drivers:
21.50.2 (5.18.2301)
N525.89.02
Im using HiveOs

Algo: Fish-hash + pyrinhash

If I put --decives-nvidia or --devices-amd they work fine, but in a mixed flighsheet, OCs for nvidia cards doesnt apply via command settings, even sometimes via HiveOs OC settings. 

All nvidia cards are 3000 series and all AMD cards are 6000 series.

Thanks

**Comment by jgonzis** [comment]
you should put * in the AMD GPUs to be applied properly in each GPU.
