### ISSUE TITLE
Ergo

### ISSUE THREAD

**Issue by 2ndtlmining** [Lolliedieb/lolMiner-releases#2097]
Hey mate

Been using LOL for a while for Ergo mining, not sure with the mem table update today, but getting crashes on a 24GB cards:

![image](https://github.com/user-attachments/assets/05ba31f0-c701-400b-9664-feef8eb0d8dd)

Working fine on Rigel and some other miners

**Comment by schaeferchristian** [comment]
I have exactly the same problem with 8GB 3070 Cards (HiveOS). Tried several things like Updating/Downgrading LolMiner, HiveOS, Kernel, etc without success so far

**Comment by jgonzis** [comment]
Remember to update to 1.89, that should be solved since that released. Also added support for BLOCX too
