### ISSUE TITLE
Devices  deselected or failed compatibility check.

### ISSUE THREAD

**Issue by miner49er1** [Lolliedieb/lolMiner-releases#210]
So after watching "Son of a Tech" on youtube i decided to use this old laptop to try mining some ETH. After following all his instructions cmd executed the following. Is there something else i should have done or is my pc too old to do anything?

Device 0:
    Name:    AMD Radeon HD 6310 Graphics
    Address: 0:1
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  1572 MByte (1914 MByte free)
    Active:  false (Unsupported device or driver version.)

Connecting to pool...
Connected to us1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x1dd9D6C84eefAC7d5bA0b020b24Ff41B42162Db3.lolMinerWorker
New job received: 0xde9fa4 Epoch: 392 Target: 0000000112e0be82
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . .

**Comment by Lolliedieb** [comment]
Well you are trying to mine on a GPU that is more then 11 years old - this has not even the GCN architecture of AMD but one of the processors of it. Also the GPU has by far not enough memory to mine ethash or etchash or any similar algorithm. Sorry :(
