### ISSUE TITLE
RX 570 ETC Allocation of DAG failed with error: Memory object allocation failure

### ISSUE THREAD

**Issue by Clankcoll** [Lolliedieb/lolMiner-releases#212]
-------------------------------------------------------
Generating light cache for epoch 402 (ETCHash: 201)
-------------------------------------------------------
New job received: 0x21f012 Epoch: 402 (ETCHash epoch: 201) Target: 0000000200000000
New job received: 0x21f012 Epoch: 402 (ETCHash epoch: 201) Target: 0000000200000000
New job received: 0x21f012 Epoch: 402 (ETCHash epoch: 201) Target: 0000000200000000
Start Mining...
-------------------------------------------------------
     Done (1578 ms), size of new DAG: 2632 MByte
-------------------------------------------------------
Start DAG gen on GPU 1 (normal mode)
Start DAG gen on GPU 3 (normal mode)
Start DAG gen on GPU 0 (normal mode)
GPU 2: Allocation of DAG failed with error: Memory object allocation failure
GPU 2: will be stopped.
Average speed (3s): 0.00mh/s | 0.00mh/s | 0.00mh/s | 0.00mh/s Total: 0.00 mh/s
New job received: 0x6cbb20 Epoch: 402 (ETCHash epoch: 201) Target: 0000000200000000
Average speed (3s): 0.00mh/s | 0.00mh/s | 0.00mh/s | 0.00mh/s Total: 0.00 mh/s

Problem only with one card but all 4 are the same

**Comment by Clankcoll** [comment]
All 4 are the 4GB Variant

**Comment by jgonzis** [comment]
It is Windows or Linux?

In case Windows made a loop, or use the autorestart...

Linux some watchdog work great

**Comment by Clankcoll** [comment]
@jgonzis its Windows. Does not matter it fails every try with 4 GPU's 3 at the Same time work great doesn't matter wich i choose only when i use 4 one seems to fail.

**Comment by jgonzis** [comment]
It could be psu? That doesn't have enough power?... 

Could you try to add for example  --devices 0,1 with 4 connected that will mine 1 and 2 gpu... if you take 4 probably not enough Watts at the PSU

**Comment by Clankcoll** [comment]
Why should my PSU matter i mean i have 1000Watt PSU the max consume of the Card is around 130 Watt.

So 130*4  = 520Watt the Cpu needs at a peek around 45 Watts only 1 Ram slot is filled and 1 SSD 

So the max of the system consume should be around lets say 700 if we calculate generous  i still have 300 Overhead and you also can consume a little bit more as written on the Paper.
Usally u get other Problems when the PSU is not capable of running all at the Same time it would try to run them all and then Collaps i had that already :P

If i am somwhere complete wrong please teach me so that i can understand it. 
I mean i will try to run one GPU on its own PSU and see if that is really the problem.

BTW thanks for the fast answers @jgonzis

**Comment by Clankcoll** [comment]
Problem found:

--
U should not try to do Mining with a rig wich has only 4GB of RAM i Upgraded to 8GB works fine.
--
