### ISSUE TITLE
Feature request: A readout of GPU Memory Temperature

### ISSUE THREAD

**Issue by Adams2689** [Lolliedieb/lolMiner-releases#213]
It recently became possible to read GDDR6X memory from HWINFO.64. I was wondering if that could be supported in lolminer. It would give Ethereum miners a more useful temperature metric than the basic GPU temperature since Ethereum mining is memory intensive and heats up the memory much more than the GPU die.

**Comment by Lolliedieb** [comment]
Is on my personal wish list ... but need to figure out first how hwinfo does this - any hint or technical information appreciated :)

**Comment by luizrrodrigues** [comment]
I think only EVGA cards have vram sensor (iCX)

**Comment by Adams2689** [comment]
> I think only EVGA cards have vram sensor (iCX)

I have a 3090 Founder Edition, and it comes with the temperature sensor. Seems to be a standard sensor across all GDDR6X modules, probably because they get so hot.

**Comment by jgonzis** [comment]
Done in last Release!!
