### ISSUE TITLE
When epoch changes lolMiner stops working

### ISSUE THREAD

**Issue by bereav** [Lolliedieb/lolMiner-releases#215]
When epoch changes, for example it increases by 1, the lolMiner stops hasing.
The reported mh/s is 0.

The workaround is to stop the miner and start it again.
![image](https://user-images.githubusercontent.com/6616693/106899491-b71bb880-66f5-11eb-8b8e-bc370784cad6.png)

**Comment by jgonzis** [comment]
That could happen...  you can try new lolminer 1.21 with --watchdog exit to make a restart in case the driver fails... that will made it automaticly...

**Comment by bereav** [comment]
@jgonzis thank you, can you please link to the cli with this  --watchdog command?
