### ISSUE TITLE
Question LolMiner

### ISSUE THREAD

**Issue by croelanjr** [Lolliedieb/lolMiner-releases#216]
Hi Lolliedieb, I am creating a server on Linux, I am interested in using your lolminer software. Question: What Linux operating system have you developed your software? What version of kernel are you working on in the latest version of lolminer? What version of AMDGPUPRO? with this information I can create my linux server without problem. Another question: is there a possibility to separate your lolminer software AMD and NVIDIA? , I tell you that before I used lolminer for GRIN currency, and it was only your lolminer software in AMD and it has worked without problem.
regards
Croelan, Jr.

**Comment by jgonzis** [comment]
I think he put sometest with Ubuntu 20.04 and AMD GPU 20.40

**Comment by croelanjr** [comment]
Thanks, I need the confirmation of the developer's response.
