### ISSUE TITLE
Vega 56 on Linux: Unsupported device or driver version.

### ISSUE THREAD

**Issue by o2genum** [Lolliedieb/lolMiner-releases#217]
Is Vega 56 going to be supported on Linux?

```
Device 1: 
    Name:    Radeon RX Vega 
    Address: 8:0 
    Vendor:  Advanced Micro Devices (AMD), ROCm
    Memory:  8176 MByte (8176 MByte free) 
    Active:  false (Unsupported device or driver version.)
```

```
$ uname -a
Linux myrig 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

AMDGPU-PRO driver: amdgpu-pro-20.45-1188099-ubuntu-20.04

**Comment by alfio8788** [comment]
Same problem but with a vega 64

**Comment by MrGeorgen** [comment]
same problem with free mesa drivers and ROCm

**Comment by jgonzis** [comment]
You should install amdgpu 20.40 with the --opencl=rocm,pal,legacy    that will give you all opencl drivers and let you run the miner :-)

**Comment by alfio8788** [comment]
I had those installed first using --pro --opencl=pal,legacy,rocr (NOTE: rocr and not rocm), it did not work so I decided to uninstall and install only rocm from the rocmdocs.radeon.com, then ended up here, i will uninstall that and try again with the 20.40 drivers.

**Comment by alfio8788** [comment]
UPDATE:

It is working as intended using --opencl=pal,legacy,rocm --headless and kernel 5.6

**Comment by jgonzis** [comment]
> UPDATE:
> 
> It is working as intended using --opencl=pal,legacy,rocm --headless and kernel 5.6

Great news thanks for the feedback
