### ISSUE TITLE
Added new GPU, hashrate the same.

### ISSUE THREAD

**Issue by CCWBee** [Lolliedieb/lolMiner-releases#222]
I have been running a 2080ti at about 50-52 MH though after adding a 2070 super the total hash rate now only hits 48 MH or so.

Currently on Windows 10
i9 9900k
16 GB ram

cooling is more than sufficient and i guess its not a thermal issue as its from start up.

GPU performance in afterburner:

![image](https://user-images.githubusercontent.com/53530937/107106139-03641700-6822-11eb-9861-b44a12db3225.png)

![image](https://user-images.githubusercontent.com/53530937/107106094-cef05b00-6821-11eb-872b-026104d0ef4e.png)

same settings with 2070 disabled:
![image](https://user-images.githubusercontent.com/53530937/107106242-7d949b80-6822-11eb-9994-a9874d64400e.png)

![image](https://user-images.githubusercontent.com/53530937/107106247-81282280-6822-11eb-9112-93159d287a42.png)

would appreciate any help.

**Comment by jgonzis** [comment]
> I have been running a 2080ti at about 50-52 MH though after adding a 2070 super the total hash rate now only hits 48 MH or so.
> 
> Currently on Windows 10
> i9 9900k
> 16 GB ram
> 
> cooling is more than sufficient and i guess its not a thermal issue as its from start up.
> 
> GPU performance in afterburner:
> 
> ![image](https://user-images.githubusercontent.com/53530937/107106139-03641700-6822-11eb-9861-b44a12db3225.png)
> 
> ![image](https://user-images.githubusercontent.com/53530937/107106094-cef05b00-6821-11eb-872b-026104d0ef4e.png)
> 
> same settings with 2070 disabled:
> ![image](https://user-images.githubusercontent.com/53530937/107106242-7d949b80-6822-11eb-9994-a9874d64400e.png)
> 
> ![image](https://user-images.githubusercontent.com/53530937/107106247-81282280-6822-11eb-9112-93159d287a42.png)
> 
> would appreciate any help.

Easy trick:

start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 0
start lolMiner.exe --algo 
ETHASH --pool !POOL! --user !WALLET! --devices 1

Run 2 instances ;-) or change to HiveOS or RaveOS

**Comment by CCWBee** [comment]
Does seem to work though my reported hashrate to my pool is still only 48 MH

**Comment by jgonzis** [comment]
> Does seem to work though my reported hashrate to my pool is still only 48 MH


The reported is not important the real is the average... is good the average?

**Comment by CCWBee** [comment]
No even when running two instances which fixes the reported hashrate, the pool only reports 48 MH with about 48 MH with of shares

**Comment by MarcoGooseman** [comment]
I tried this and it only leaves the other gpu out of the mining...

**Comment by jgonzis** [comment]
Problem solve after release 1.25 with CUDA Solver
