### ISSUE TITLE
Miner runs on 0.00mh/s leading to emergency.bat

### ISSUE THREAD

**Issue by saminki16** [Lolliedieb/lolMiner-releases#223]
Hello,

im new to mining and i wonder why i cant get the 4g.bat running. Have a 1650 with 4096mbyte. Card is stock btw.
I followed the 4g.bat readme until it didnt crash with "allocate memory" but now the dag is instanly done the miner runs on 0mh/s what leads to an error.

I really dont know what i can still do run eth, etc works fine but isnt really worth :/

My .bat settings to get it run is down below. Adding 8 to keepfree and size will crash with "allocate memory again"

![LolMiner issue](https://user-images.githubusercontent.com/68564674/107107599-6362b980-6832-11eb-96b6-811350fc3ca8.PNG)
![Settings](https://user-images.githubusercontent.com/68564674/107107602-66f64080-6832-11eb-8631-62d622cec713.PNG)

**Comment by jgonzis** [comment]
> Hello,
> 
> im new to mining and i wonder why i cant get the 4g.bat running. Have a 1650 with 4096mbyte. Card is stock btw.
> I followed the 4g.bat readme until it didnt crash with "allocate memory" but now the dag is instanly done the miner runs on 0mh/s what leads to an error.
> 
> I really dont know what i can still do run eth, etc works fine but isnt really worth :/
> 
> My .bat settings to get it run is down below. Adding 8 to keepfree and size will crash with "allocate memory again"
> 
> ![LolMiner issue](https://user-images.githubusercontent.com/68564674/107107599-6362b980-6832-11eb-96b6-811350fc3ca8.PNG)
> ![Settings](https://user-images.githubusercontent.com/68564674/107107602-66f64080-6832-11eb-8631-62d622cec713.PNG)

You cannot mine more with the 4Gb in Windows... you can try in Linux but in Windows is nearly imposible with 4Gb ETH... you can try ETC

**Comment by saminki16** [comment]
Well like i said, its not really worth doing ETC. And when its not possible anyway, why still have the option available?

**Comment by jgonzis** [comment]
> Well like i said, its not really worth doing ETC. And when its not possible anyway, why still have the option available?

You can do also ETC+ZIL some extra :-)

**Comment by vmo64** [comment]
I am on ubuntu with a GTX 1650 Super 4GB stock and still get 0.00 mh/s, is it disabled on linux also?

**Comment by jgonzis** [comment]
Nvidia is not working properly with Zombie Mode... AMD yes ...

**Comment by vmo64** [comment]
What do I do?

**Comment by vmo64** [comment]
Not worth is

**Comment by ethtothe** [comment]
Try updating your drivers i had a similar problem

**Comment by jgonzis** [comment]
Nvidia doesn't support Zombie Mode. Try to mine ETC+ZIL
