### ISSUE TITLE
I can't launch lolMiner

### ISSUE THREAD

**Issue by LVLXI** [Lolliedieb/lolMiner-releases#226]
Hey guys,

I'm trying to use lolMiner and I've added Server and my Wallet Address to the .bat file, but when I launch the file, the window flashes on my screen for a second and closes down.

Does anyone know what's going on and/or how to fix this?

Thank you.

**Comment by jgonzis** [comment]
Same as https://github.com/Lolliedieb/lolMiner-releases/issues/452
