### ISSUE TITLE
Getting 8.60 mh/s with a RX 590

### ISSUE THREAD

**Issue by XRoritoX** [Lolliedieb/lolMiner-releases#227]
Just wondering why am I getting so poor hashate knowing that many people use Rx series videocards to mine ETH. Also the videocard doesn´t seem to be using it´s full power. Is there any command that makes it use all?

**Comment by MoonJumpMania** [comment]
I use an RX 480 and I was getting the same issue. Apparently the fix is to enable Compute mode as the GPU workload in the AMD Radeon Software but when I tried that, the miner just tells me to setup the miner.

**Comment by XRoritoX** [comment]
Thanky you so much! That really  worked! Now i´m getting 22 mh/s but I think people is getting even more with RX580...

**Comment by Keimling27** [comment]
Your hashrate depend on the driver and actice compute mode use lol miner 1.18 there is a compute mode automatic.
To reach hashrates upt o 30Mh/s  you must adjust your bios from the card.

**Comment by dizajjner** [comment]
> Thank you so much! That really worked! Now i´m getting 22 mh/s but I think people is getting even more with RX580...

Have you managed to get higher mh/s?

**Comment by Keimling27** [comment]
22 is ok without bios modding for that you can look there but i think to invest 50$ is to much for 1 card.
https://mining-bios.eu/

**Comment by XRoritoX** [comment]
> > Thank you so much! That really worked! Now i´m getting 22 mh/s but I think people is getting even more with RX580...
> 
> Have you managed to get higher mh/s?

Yes I did. Following those steps I raised the hashrate
