### ISSUE TITLE
lolMiner 1.22 for 474 574 GPU's

### ISSUE THREAD

**Issue by Titomir** [Lolliedieb/lolMiner-releases#228]
Hi all! Is there anybody who know how to raise speed on x16 slots on Motherboards? I have 3 rigs with 2x16x slots on each other. 4 gb card like 470/570 in GPU0 slot giving me best mh/s. About 27-29 mhs, but GPU1 in the second x16 slot giving me 19 mh\s. I understand that on 393 epoch 19 mh\s is very best value. But maybe i can make also 27-29 mh\s? I don't using risers at now. Putting GPU-s direct into slots. Maybe any ideas?)) MSI Z77A-G41 motherboard for example. I think i need to change some bios settings or it is limitation from vendor and i can't boost my second x16 slot. Something like this, sorry for too much words))

**Comment by oleg080878** [comment]
Dear developers! Please make a Lol miner so that 4 gigs can dig ether at a normal speed of 31-32 mh / s. until the era when 8 gig video cards fall off.
Thank.

**Comment by jgonzis** [comment]
That will not happen. DAG Size problem. You should use Zombie mode with the reduction of Mhs
