### ISSUE TITLE
lolminer grinmint authorization or work missing

### ISSUE THREAD

**Issue by Unnameless** [Lolliedieb/lolMiner-releases#23]
Hi,

I can’t make the latest lolminer do any work on grinmint. It errors with authorization or work missing. Syntax is correct!

![95F25C2E-2659-4BE3-8832-71E1336310C9](https://user-images.githubusercontent.com/36138092/70374213-eae42e00-18f8-11ea-9b14-108fd0826833.jpeg)

**Comment by Lolliedieb** [comment]
Should be fixed, grinmint in recent versions working fine for me
