### ISSUE TITLE
DAG Failed: Memory object allocation on GPU 1 and 3 only

### ISSUE THREAD

**Issue by CadavraX** [Lolliedieb/lolMiner-releases#231]
Hi all,
I just put together a new rig with a 5700XT 8 GB and 3 5600XT 6GBs. GPUs are all detected in Windows, Radeon software sees them no problem, and lolminer sees them on startup. GPUs 0 and 2 work no problem, but GPUs 1 and 3 always fail DAG with memory allocation error. The kicker is, it doesn't matter which cards are plugged into which pci ports, 1 and 3 never work. I am using Windows 10 64-bit, on an MSI Z390-A Pro board with 4 GBs of system RAM. Above 4G/Cryptocurrency is set in the BIOS (and BIOS has been updated to the latest version). 
Not really sure where to go with this issue, thanks!

**Comment by jgonzis** [comment]
You should try to have a higher swap file... ypu have lot of Cards so the fileswap of windows should be very very big or it will continue crash... try to increase that swap file to the maximum ca. 100Gb.

**Comment by CadavraX** [comment]
That was exactly it! I had 32000 thinking that would be more than enough but I cranked it up further and that resolved the issue. Thanks so much for taking the time to respond, I really appreciate it!
