### ISSUE TITLE
"No OpenCL devices found in your system. Closing lolMiner." I Have a RX 590

### ISSUE THREAD

**Issue by XRoritoX** [Lolliedieb/lolMiner-releases#237]
Hey guys, I´m having this issue, I guess my PC can´t recognize my RX590 graphic card and I think it´s because I can´t install the latest AMD drivers (They always crash when I try to install them). Any idea to make my card mine without installing those drivers? Thanks!

**Comment by Titomir** [comment]
Is that AFOX RX 590 8 Gb card? If yes - you have a big problem with them.

**Comment by devgas** [comment]
I have the same issue on Asus RX 580 8GB and Ubuntu 16.04 /

**Comment by XRoritoX** [comment]
Mine is a XFX RX 590 Fatboy, also a problematic card... but is there any way I can make the miner work without installing those drivers?

**Comment by otacrazy2123** [comment]
Same here, windows server 2019, rtx 2060!

**Comment by Lolliedieb** [comment]
Can you try to run clinfo.exe? That is doing a basic OpenCL check and showing up the detected cards on the system. If the card is not shown there I only can recommend to re-install your GPU drivers since some component of it is broken.

**Comment by XRoritoX** [comment]
Yes I´m 100% sure is a driver issue, the thing is that i´m havinig problems installing the latest AMD drivers on my RX590. It just freezes while i´m doing it. Maybe there are some other drivers I may install to make the computer recognize the card.

**Comment by XRoritoX** [comment]
Update: I did a clean windows install and tested with Radeon Software Crimson ReLive Edition Beta for Blockchain. Got the card mining, but at a poor hashrate of 8.60 mh/s. Now the issue is that I can´t change compute/graphic options because I still can´t install Adrenalin. Is there any way for me to set the compute mode of the card without the Adrenalin driver?

**Comment by jgonzis** [comment]
> Update: I did a clean windows install and tested with Radeon Software Crimson ReLive Edition Beta for Blockchain. Got the card mining, but at a poor hashrate of 8.60 mh/s. Now the issue is that I can´t change compute/graphic options because I still can´t install Adrenalin. Is there any way for me to set the compute mode of the card without the Adrenalin driver?

You have in the zip file of lolminer "examples_windows_with_compute_mode.zip" there show how to run the compute mode... It is only to add --computemode at the end of line:

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --computemode

**Comment by yumyumfarted** [comment]
> I have the same issue on Asus RX 580 8GB and Ubuntu 16.04 /

I'm having this issue as well, and I'm running 20.04.1. 

I found this, I'm not sure if it will help. It didn't help me, but I probably didn't do it correctly:

https://community.amd.com/t5/drivers-software/can-t-install-amdgpu-drivers-on-ubuntu-20-04-1-5-4-0-56-generic/m-p/426676

**Comment by yumyumfarted** [comment]
> Update: I did a clean windows install and tested with Radeon Software Crimson ReLive Edition Beta for Blockchain. Got the card mining, but at a poor hashrate of 8.60 mh/s. Now the issue is that I can´t change compute/graphic options because I still can´t install Adrenalin. Is there any way for me to set the compute mode of the card without the Adrenalin driver?

Make sure your card is in compute mode. Either how jgonzis described or by going into radeon settings > graphics > GPU # > Advanced > GPU workload > compute.

**Comment by otacrazy2123** [comment]
It was the graphics drivers.

Just used DDU to uninstall and then install it clear.
