### ISSUE TITLE
lolMiner is only using 4gb VRAM?

### ISSUE THREAD

**Issue by Jim1101** [Lolliedieb/lolMiner-releases#238]
Hi,
I'm new to mining and I've used LolMiner on my 8GB card but the DAG is showing as 4gb and windows task manager only shows about half my GPU memory being used. 

I am only getting around 7/9 mh/s but from other people online using the 4gb version of my card they are getting close to 20mh/s

**Comment by jgonzis** [comment]
You should run as administrator the bat file and also add: --computemode 

You have a bat file lolminer zip "examples_windows_with_compute_mode.zip" that will allow you to get +20Mhs. Other option is to change the Adrenaline driver to compute mode, both option will give you more hash. The bat file is like this when you look for it:

@echo off

setlocal enableDelayedExpansion


<job id="Elevate"><script language="VBScript">
  Set objShell = CreateObject("Shell.Application")
  Set objWshShell = WScript.CreateObject("WScript.Shell")
  Set objWshProcessEnv = objWshShell.Environment("PROCESS")
  strCommandLine = Trim(objWshProcessEnv("ELEVATE_CMDLINE"))
  objShell.ShellExecute "cmd", "/c " & strCommandLine, "", "runas"
</script></job>
:admin -----------------------------------------------------------

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --computemode
timeout 10

**Comment by Lolliedieb** [comment]
As jgonzis mentioned make sure the compute mode is on and you do not do graphics output with that card. Else it it normal we take less then 5G memory - more is currently not needed for this algorithm.
