### ISSUE TITLE
2 GPU 3070 half mining rates

### ISSUE THREAD

**Issue by cop95** [Lolliedieb/lolMiner-releases#239]
![0E946284-64D0-4AD8-8E26-3BF811850B1E](https://user-images.githubusercontent.com/78805091/107377032-700d3900-6ae2-11eb-938a-cb2956d5288d.jpeg)
 
 
With 1 GPU connected I’ve got 60.6~61 MH/s
What can I do ?

**Comment by DobroFenix** [comment]
Перезагрузи кудахтер или воткни в неё монитор.
У меня так же на rx5700 иногда бывает

**Comment by jgonzis** [comment]
There is a fast tip that is run 2 instances and add 

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 0
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 1

That will make you to run at 120Mhs :-)

**Comment by Speedytrack** [comment]
> There is a fast tip that is run 2 instances and add
> 
> lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 0
> lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 1
> 
> That will make you to run at 120Mhs :-)

Is this something that has to be done every time even if you have 3 or 4 GPUs? It worked great with my just two but have two more on the way.

**Comment by jgonzis** [comment]
I recommend you to try then HiveOS or RaveOS, focus on mining ☺

**Comment by trenty66** [comment]
im having the same issue where am i putting this is the file at?

**Comment by Speedytrack** [comment]
> I recommend you to try then HiveOS or RaveOS, focus on mining ☺

Thank you, I was able to do three occurrences. HiveOS website is a little intimidating.

**Comment by cop95** [comment]
> There is a fast tip that is run 2 instances and add 
> 
> 
> 
> lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 0
> 
> lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 1
> 
> 
> 
> That will make you to run at 120Mhs :-)
> 
> 

Thank you! I'm using Phoenix Miner, it's all good.

**Comment by Keimling27** [comment]
please run cm mode from lolminer 1.18 than you will have 50Mhz  and what are your msi afterburner settings? normally mem +1100 core clock -500 powerlimit 60% than you will have 60 Mhz

**Comment by jgonzis** [comment]
New CUDA Solver included in release 1.25 solve the problem.
