### ISSUE TITLE
Could i use lolminer with Nicehash on 2080ti

### ISSUE THREAD

**Issue by cisco150** [Lolliedieb/lolMiner-releases#240]
Could i use lolminer with Nicehash on 2080ti with plugins or any help be great. Thanks and what plugin would be best to use

**Comment by jgonzis** [comment]
Hi of course you can use it, I suppose you are in Windows:

lolMiner.exe --algo ETHASH --pool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 --user !YOUR_BTC_WALLET_OF_NICEHASH! 

You should change : !YOUR_BTC_WALLET_OF_NICEHASH!  for your BTC Wallet of Nicehash :-)

**Comment by jgonzis** [comment]
Remember to use it with latest releases , that includes the CUDA Solver
