### ISSUE TITLE
Issue with mining beam

### ISSUE THREAD

**Issue by yumyumfarted** [Lolliedieb/lolMiner-releases#241]
When mining beam, the miner will get stuck on the "Setup miner line". Just to be sure it wasn't me messing with anything, I redownloaded the miner. I then made the necessary changes, (my wallet and pool) and it's still stuck on Setup Miner. 

Specs:
Pentium G5400
6x RX 570s
1x RX 560
MSI h-310 mining motherboard
850 w EVGA GQ PSU
Win10 ameliorated
Kingston SSD
A usb hard drive

Log:
[2021-02-10_09-40-11.log](https://github.com/Lolliedieb/lolMiner-releases/files/5960206/2021-02-10_09-40-11.log)

I'm not really sure why it does this, it was working and now it's not. Maybe restarting my computer will help, but I'm not really sure.

After waiting a while, it started to get going, but was spitting out another error. I'm pretty sure I know what the problem is now. User error on my part.

**Comment by jgonzis** [comment]
Your problem is that you have add the SSL Parameter but you are connecting to a Stratum server:

Change to us1-beam.flypool.org:3443 or remove the --tls on parameter that you have in the line parameters.

Also take care that you are only selecting the Device 5, I suppose you have that info.

**Comment by yumyumfarted** [comment]
Oh that would make sense, thanks!
