### ISSUE TITLE
lolminer crashe on linux

### ISSUE THREAD

**Issue by mSv1306** [Lolliedieb/lolMiner-releases#242]
Hello, when I try to start lolminer in zombie mode on linux it crashes (I try with ubuntu 18.04 and 20.04, in both it crashes, I use the latest amd driver for each operating system).

I have an rx 570 4gb, does anyone know what it can be?

**Comment by jgonzis** [comment]
Which is the line parameters are you using?. 

Have you add the: --4g-alloc-size 4072 

If you put a log of the error that will help to find the problem you have.

**Comment by mSv1306** [comment]
I solved it, I had to lower the values of --4g-alloc-size to one that does not crash.
