### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by Abdzaqout** [Lolliedieb/lolMiner-releases#246]
I have problem when I'm try mining ethereum on my gtx 1650 says (cuda error in cudaprogram out of memory) I know its not worth it for 14 mh/s but I wanna get experience.

**Comment by sushantag9** [comment]
Try on linux with `--4g-alloc-size` and try a reduced value, of about 3900

**Comment by jgonzis** [comment]
Zombie Mode doesn't work with Nvidia. You should mine ETC+ZIL for example or ERGO. With last releases 1.31
