### ISSUE TITLE
Issue with Zombie mode

### ISSUE THREAD

**Issue by thowell76** [Lolliedieb/lolMiner-releases#247]
When I try to use zombie mode, I am getting the attached error message when I try to set zombie mode to 5 or 3 it crash and reboots.   I am running simple miner and I have 2 x RX5500 8 GB and a RX570 4GB.   
![IMG_1651](https://user-images.githubusercontent.com/78984377/107825723-9f75ad00-6d51-11eb-8b60-49ae3a556480.jpg)

**Comment by jgonzis** [comment]
Try new version with the auto tunning Zombie Mode
