### ISSUE TITLE
after adding "--tstop --tstart" parameters,very high rejection rate and high invalid ,i am confirm

### ISSUE THREAD

**Issue by mqqep** [Lolliedieb/lolMiner-releases#255]
after adding "--tstop --tstart" parameters,very high rejection rate and invalid ,i am confirm
my card is p106-100,there are 10000

**Comment by mqqep** [comment]
![035dc96933a15f9581dba40a6f3dd9d](https://user-images.githubusercontent.com/45333446/107863603-a35c1900-6e90-11eb-9c85-fab6da40ff5b.png)

**Comment by jgonzis** [comment]
> after adding "--tstop --tstart" parameters,very high rejection rate and invalid ,i am confirm
> my card is p106-100,there are 10000

--tstop and --start should go with the value... which is your complete parameters for the miner?

**Comment by mqqep** [comment]
> > 添加“ --tstop --tstart”参数后，拒绝率很高且无效，我确认
> > 我的卡是p106-100，有10000个
> 
> --tstop和--tstart应该带有值...这是矿工的完整参数吗？



> > after adding "--tstop --tstart" parameters,very high rejection rate and invalid ,i am confirm
> > my card is p106-100,there are 10000
> 
> --tstop and --tstart should go with the value... which is your complete parameters for the miner?

yes,my parameters is --tstart 70 --tstop 88

**Comment by jgonzis** [comment]
Improved with new Cuda Solver from 1.25 solve some of this problems
