### ISSUE TITLE
Lost connection to stratum server

### ISSUE THREAD

**Issue by darthcanada** [Lolliedieb/lolMiner-releases#256]
Hi, just installed lolminer latest version and trying to mine with my ethermine.org using us1.ethermine.org server and 4444 port and it will just repeat this error message : 

Lost connection to stratum server us1.ethermine.org: 4444 or server not reachable. Time out on connection attempt resolve. Retrying.

Is this because I live in Canada and can't use the US server ? How do I fix this ? 

***I have an RTX 3070

Thanks

**Comment by Shirwatel** [comment]
same error for me !!! trying to connect to a European server

**Comment by jgonzis** [comment]
Have you got --tls on  ? That sometimes happen SSL is active but the porrt server is not the right one...

**Comment by KiddMoeLester** [comment]
getting same issue here.... so do i have to turn the tls off? if so how do it

**Comment by deandrb1982** [comment]
![image](https://user-images.githubusercontent.com/21034562/108593048-40272680-7369-11eb-9179-3124d23e5035.png)

same here

**Comment by KiddMoeLester** [comment]
i changed the stratum port from 4444 to 14444 and now it actually works
![Captu1re](https://user-images.githubusercontent.com/79358574/108653305-abebc980-74f8-11eb-86d8-e7333d18fbab.PNG)

**Comment by MomsFreak** [comment]
I have exactly the same problem. When I mine with one rx 5700 xt I have no problems. When I push in a second gpu after an hour it gives this same problem.

**Comment by FedeIM** [comment]
> Hi guys! This is a miner from Argentina speaking to you. I am a Systems Engineering student.
> Today I started using lolMiner (after using TeamRedMiner for several months) and ran into the problem mentioned above (server not reachable. Time out on connection attempt resolve. Retrying). After several minutes of trying (and failing), I was finally able to find a solution, at least for my case.
> **MY SOLUTION** was to put the word "WALLET =", because I saw in the lower part of the code that it was referring to the Wallet, but in truth nowhere had Wallet been defined as such.
> 
> I show you an image of how it turned out for me:
> 
> ![image](https://user-images.githubusercontent.com/84020529/117814760-1cbe9a00-b23b-11eb-8b73-e67c6dd2a7fb.png)
> 
> I hope that my contribution can help more than one person!

hiciste algo mas perrito malvado? no puedo pasar de ese error

**Comment by Perroke** [comment]
> > Hi guys! This is a miner from Argentina speaking to you. I am a Systems Engineering student.
> 
> > Today I started using lolMiner (after using TeamRedMiner for several months) and ran into the problem mentioned above (server not reachable. Time out on connection attempt resolve. Retrying). After several minutes of trying (and failing), I was finally able to find a solution, at least for my case.
> 
> > **MY SOLUTION** was to put the word "WALLET =", because I saw in the lower part of the code that it was referring to the Wallet, but in truth nowhere had Wallet been defined as such.
> 
> > 
> 
> > I show you an image of how it turned out for me:
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/84020529/117814760-1cbe9a00-b23b-11eb-8b73-e67c6dd2a7fb.png)
> 
> > 
> 
> > I hope that my contribution can help more than one person!
> 
> 
> 
> hiciste algo mas perrito malvado? no puedo pasar de ese error

En mi caso, solo con hacer eso ya se me solucionó el error, no sé qué otra cosa podría ser.

**Comment by jgonzis** [comment]
> > > Hi guys! This is a miner from Argentina speaking to you. I am a Systems Engineering student.
> > 
> > 
> > > Today I started using lolMiner (after using TeamRedMiner for several months) and ran into the problem mentioned above (server not reachable. Time out on connection attempt resolve. Retrying). After several minutes of trying (and failing), I was finally able to find a solution, at least for my case.
> > 
> > 
> > > **MY SOLUTION** was to put the word "WALLET =", because I saw in the lower part of the code that it was referring to the Wallet, but in truth nowhere had Wallet been defined as such.
> > 
> > 
> > > 
> > 
> > 
> > > I show you an image of how it turned out for me:
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/84020529/117814760-1cbe9a00-b23b-11eb-8b73-e67c6dd2a7fb.png)
> > 
> > 
> > > 
> > 
> > 
> > > I hope that my contribution can help more than one person!
> > 
> > 
> > hiciste algo mas perrito malvado? no puedo pasar de ese error
> 
> En mi caso, solo con hacer eso ya se me solucionó el error, no sé qué otra cosa podría ser.
Muchas gracias por el aporte de la solución

**Comment by jgonzis** [comment]
> Same error for hiveos with lolminer 1.45 After i changed lolminer version to 1.44 its working now.

The error of connection is with only eth? With dual ? To which pool? Could you give us some photo or more information to try to have something to search
