### ISSUE TITLE
@developer  --split mining  Ether Cortex

### ISSUE THREAD

**Issue by Keimling27** [Lolliedieb/lolMiner-releases#257]
Dear Developer,
you made a split mining ETH ETC. 
Is it possible to make this with ETH and Cortex. I think a lot of mixed mining rig users have some 8gb and 11gb cards.
So they could have much more earnings

It would be nice if you can give me some Informations

**Comment by jgonzis** [comment]
You should launch 2 instances of lolminer, one for ETH and one for Cortex
