### ISSUE TITLE
0.9.5 Opencl init failure on Grin Algorithms

### ISSUE THREAD

**Issue by BallowandSunder** [Lolliedieb/lolMiner-releases#26]
Setup: Windows 10, 1900x Threadripper, 16GB RAM with a Vega 56 8GB

I just tried the new 0.9.5 that was just released and I get this issue..

![Not Working](https://user-images.githubusercontent.com/59857944/72395294-e0823480-36ed-11ea-8396-b9a4c6013db7.jpg)

0.9.3 still works perfectly fine..

![Working](https://user-images.githubusercontent.com/59857944/72395330-f8f24f00-36ed-11ea-87d9-97464bdb9883.jpg)

Any thoughts?

**Comment by Lolliedieb** [comment]
Hello, can you tell me your driver version? 
All kernels in 0.9.5(.1) were build for Adrenaline 18.12 / amdgpu-pro 18.50 and newer. Older drivers could cause a problem there

**Comment by BallowandSunder** [comment]
I am using the recommended drivers.

![using recommended drivers](https://user-images.githubusercontent.com/59857944/72410897-8188e380-371e-11ea-804f-19be09d05393.jpg)

![using recommended drivers 2](https://user-images.githubusercontent.com/59857944/72410909-88aff180-371e-11ea-84c3-1e7e66a4163c.jpg)

**Comment by Lolliedieb** [comment]
Ok ... strange. Can you test any 2019 release? It may be I involuntary did build for a slightly newer CL version :/

**Comment by BallowandSunder** [comment]
Even though it wasn't recommended... After trying all the 2018-2019 drivers, in my final test I used the 0.9.5 lolminer with the latest Jan9-2020 AMD drivers and bam things started working!

![drivers that worked](https://user-images.githubusercontent.com/59857944/72487025-8357b300-37c1-11ea-8c30-24685b9049b9.jpg)

Thank you for your time and input @Lolliedieb  keep up the excellent work!
