### ISSUE TITLE
Can you Mine ETH on 8G cards while mining ETC on 4G cards and dual mine ZIL?

### ISSUE THREAD

**Issue by litwi1rm** [Lolliedieb/lolMiner-releases#263]
Can you Mine ETH on 8G cards while mining ETC on 4G cards and dual mine ZIL?

https://github.com/Lolliedieb/lolMiner-releases/blob/master/dual_and_split_mining.md

**Comment by jgonzis** [comment]
> Can you Mine ETH on 8G cards while mining ETC on 4G cards and dual mine ZIL?
> 
> https://github.com/Lolliedieb/lolMiner-releases/blob/master/dual_and_split_mining.md

Only running 2 instances of lolMiner
