### ISSUE TITLE
1.22 / 1.24 on SimpleMiningOS watchdog not rebooting rig with GPUs at 0 Mh/s

### ISSUE THREAD

**Issue by CultureCrypto** [Lolliedieb/lolMiner-releases#264]
Re: Sapphire RX 580 4GB, zombie mode

Miner reports all GPUs are online, but one or more GPUs may drop to 0 Mh/s without triggering watchdog.  (I've seen all GPUs at 0 with v1.24a for hours, so I reverted back to 1.22)

**Comment by CultureCrypto** [comment]
![image](https://user-images.githubusercontent.com/30902036/108003388-a3f3cd00-6fc0-11eb-84dd-ff54aef39176.png)
hung on miner start, sitting at 0 Mh/s, no watchdog reboot

**Comment by jgonzis** [comment]
Take care you don't have --watchdog off ... also try last 1.24a that should solve some of the problem...

Which parameters are you using in the hang up screen

**Comment by CultureCrypto** [comment]
Here's my command line (in SMos)

--coin ETH --pool ssl://us1.ethermine.org:5555 --apihost 127.0.0.1 --apiport 4444 --user $walletETH.$rigName --4g-alloc-size 4080

I specifically went back to 1.22 because 1.24 seemed ok until several hours later I found the rig sitting with ALL the GPUs at 0 Mh/s, no shares delivered to the pool, no indication that anything was wrong. 

1.22 seemed better than 1.24a in that regard, but 1.22 will still plug with a GPU at 0 without triggering the watchdog.

**Comment by jgonzis** [comment]
Normally that goes down happens also for low voltage on the core, the new version use a little bit of more consume, so that could make to go up a little bit the Core voltage...  What is strange is that is doesn't autoreboot with the scrypt...

**Comment by CultureCrypto** [comment]
![image](https://user-images.githubusercontent.com/30902036/108604698-766ea100-737d-11eb-84db-682e09768b51.png)
Well this sucks....
![image](https://user-images.githubusercontent.com/30902036/108604723-a5851280-737d-11eb-8dac-20f7f6d99201.png)

**Comment by jgonzis** [comment]
That should be solve with new API and also from SMOS
