### ISSUE TITLE
9.5.1. All Grin-* algos isnt working on 1080Ti

### ISSUE THREAD

**Issue by Quake4** [Lolliedieb/lolMiner-releases#27]
![image](https://user-images.githubusercontent.com/29517243/72564304-7f5e8a80-38c0-11ea-96d5-36c73a256d36.png)

**Comment by Quake4** [comment]
same https://github.com/Lolliedieb/lolMiner-releases/issues/22

**Comment by devaux** [comment]
same #22 Quadro RTX 4000

**Comment by Quake4** [comment]
cookaroom working, but other still isnt working

**Comment by Unnameless** [comment]
Is nvidia support getting dropped?

**Comment by Quake4** [comment]
0.9.7 add grin31 working, but grind29 still isnt working
