### ISSUE TITLE
GPU 0: Allocation of DAG failed with error: Memory object allocation failure

### ISSUE THREAD

**Issue by hellomr193** [Lolliedieb/lolMiner-releases#271]
Name:    GeForce MX150
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  4096 MByte
    Max epoch (approx): 374
    Active:  true (Selected Algorithm: ETHash)
Device 1:
    Name:    Intel(R) UHD Graphics 620
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Memory:  3218 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to us1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0xea60B11a1714eaaE0A32131dA44fA284997D5ea0.lolMinerWorker
New job received: 0x2de69e Epoch: 395 Target: 0000000112e0be82
-------------------------------------------------------
         Generating light cache for epoch 395
-------------------------------------------------------
Start Mining...
-------------------------------------------------------
     Done (2546 ms), size of new DAG: 4184 MByte
-------------------------------------------------------
GPU 0: insufficient memory for DAG epoch 395.
GPU 0: will be in Zombie mode with reduced hashrate.
GPU 0: Allocation of DAG failed with error: Memory object allocation failure
GPU 0: will be stopped.

kindly help to solve this issue.

thanks

**Comment by makmemo** [comment]
same issue but with nvidia 960

**Comment by jgonzis** [comment]
With Nvidia or Windows not working properly the Zombie Mode... so you should try other coin like ETC for example

**Comment by tonyv619** [comment]
Having the same issue, but running Nvidia Geforce GTX 960m here. Entirely possible this computer's GPU isn't powerful enough - relatively new to mining here

**Comment by TheMCHacker785** [comment]
Same issue. but with a GTX 1650 TI. Also, most miners have failed to run so I was lucky to get this one to at least load.

**Comment by jgonzis** [comment]
> Same issue. but with a GTX 1650 TI. Also, most miners have failed to run so I was lucky to get this one to at least load.

That's completely normal... in Windows there is not more space for ETH in 4GB cards... best if you are in Windows mine ETCHASH with lolminer or ETC+ZIL to get more profit

**Comment by PeterBurkhard** [comment]
GTX 960 4 GB same issue.

**Comment by jgonzis** [comment]
> GTX 960 4 GB same issue.

With ETH I suppose. Not with ETC. As it is said before no more option to mine ETH with 4Gb Cards in Windows...

**Comment by srezasm** [comment]
I think the GPU RAM space for mining with the ETH algorithm must be more than 4GB while the Nvidia 960s RAM space is exactly 4GB.

**Comment by jgonzis** [comment]
> I think the GPU RAM space for mining with the ETH algorithm must be more than 4GB while the Nvidia 960s RAM space is exactly 4GB.

ETH Dag now is bigger than 4Gb... you are not able to mine in Windows with your Nvidia in Windows ETH sorry...
