### ISSUE TITLE
RX570 4 Gb lolMiner 1.21 for Windows

### ISSUE THREAD

**Issue by DMX555** [Lolliedieb/lolMiner-releases#272]
Good day!

In the lolMiner 1.21 version on the Asus RX570 4Gb  video card it gives out only 7.5 Mh / s on Windows 10, and in Linux and lolMiner 1.24a - 25 Mh / s, when is it planned to support Windows in version 1.24 ???

Thank!

**Comment by jgonzis** [comment]
> Good day!
> 
> In the lolMiner 1.21 version on the Asus RX570 4Gb video card it gives out only 7.5 Mh / s on Windows 10, and in Linux and lolMiner 1.24a - 25 Mh / s, when is it planned to support Windows in version 1.24 ???
> 
> Thank!

With Windows is not possible to get good result with the 4Gb in Ethereum... you need you do it with Linux. With Windows not more space in the memory of the card
