### ISSUE TITLE
Allocation of DAG failed with error: Memory object allocation failure on gtx 1660

### ISSUE THREAD

**Issue by dosilyoun** [Lolliedieb/lolMiner-releases#275]
Hello!

I am running lolMiner v1.24a on ubuntu 20.04 with three asus gtx 1660. When I try to mine etherum I got the following error:

`Setup Miner... 
Device 0: 
    Name:    GeForce GTX 1660 
    Address: 2:0 
    Vendor:  NVIDIA Corporation
    Memory:  5944 MByte 
    Max epoch (approx): 614 
    Active:  true (Selected Algorithm: ETHash) 
Device 1: 
    Name:    GeForce GTX 1660 
    Address: 10:0 
    Vendor:  NVIDIA Corporation
    Memory:  5944 MByte 
    Max epoch (approx): 614 
    Active:  true (Selected Algorithm: ETHash) 
Device 2: 
    Name:    GeForce GTX 1660 
    Address: 12:0 
    Vendor:  NVIDIA Corporation
    Memory:  5944 MByte 
    Max epoch (approx): 614 
    Active:  true (Selected Algorithm: ETHash) 

Connecting to pool... 
Connected to eu1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0xc14136fef20e591475a7a237e5552eb0926d8490.miner1 
New job received: 0xdd3d5b Epoch: 395 Target: 0000000112e0be82 
------------------------------------------------------- 
         Generating light cache for epoch 395 
------------------------------------------------------- 
Start Mining... 
New job received: 0xbc8c92 Epoch: 395 Target: 0000000112e0be82 
New job received: 0x0bdb47 Epoch: 395 Target: 0000000112e0be82 
New job received: 0x6b02bf Epoch: 395 Target: 0000000112e0be82 
------------------------------------------------------- 
     Done (2461 ms), size of new DAG: 4184 MByte 
------------------------------------------------------- 
GPU 2: Allocation of DAG failed with error: Memory object allocation failure 
GPU 2: will be stopped. 
GPU 0: Allocation of DAG failed with error: Memory object allocation failure 
GPU 0: will be stopped. 
GPU 1: Allocation of DAG failed with error: Memory object allocation failure 
GPU 1: will be stopped. 
New job received: 0x3563ff Epoch: 395 Target: 0000000112e0be82 
New job received: 0xa5ab1b Epoch: 395 Target: 0000000112e0be82 
New job received: 0x583853 Epoch: 395 Target: 0000000112e0be82 
`

Can anybody help me what may be the cause of this?
Thanks in advance!

**Comment by yumyumfarted** [comment]
Does running at stock speeds produce the same error? It might be a problem with memory timing/oc.

**Comment by jgonzis** [comment]
I have one card that makes me to run lower the OC ... try to put negative values in the memory to make a super stable run...

**Comment by yumyumfarted** [comment]
Some cards like lower clocks anyway, there's probably an explanation for it. I personally run lower clocks and get better rates, somehow. It consumes less power too.

**Comment by ruitaoyu** [comment]
@dosilyoun  did you found out what caused your problem? I am having the same problem right now. thanks

**Comment by jgonzis** [comment]
Try new releases with new CUDA Solver for more stability and less stales in Nvidia
