### ISSUE TITLE
Memory issue with AMD hardware: referenced memory error.

### ISSUE THREAD

**Issue by yumyumfarted** [Lolliedieb/lolMiner-releases#277]
Hello,

I've been having stability issues using my AMD gpus. I frequently get this error:

```
The instruction at 0x00007FF602371C4C referenced memory at
0x0000000000000000. The memory could not be read.

Click OK to terminate the program.
```

After clicking okay, the miner will either exit or restart. While this error is showing, mining will stop. One other thing to note is that a few minutes after mining, my settings in Wattman (Radeon software > Performance > Tuning) will be reset to automatic. Then the error will occur.

I've tired multiple things: Playing with OC, Core/memory clocks, and power limits. However, I found a setting called "Surface Format Optimization". This can be found in Settings > Graphics > GPU # > Advanced > Surface Format Optimization. After turning this setting off, my wattman settings did not reset within the first few minutes of mining. I'll have to see if the error still occurs, roughly 3-4 hours.

My guess is that the setting is designed to place textures in different places to increase the performance in games, it might move a value to a new address and tell the game. This miner probably doesn't have the ability to do that.

Update: my wattman settings still reset, so I tried running the miner without tweaking anything. I guess I'll still se if it still crashes.

Update 2: The error still occurred, this time sooner than a few hours. I'm out of ideas now. I was thinking OC but I have made everything stock. My cards also have an OC switch, I made turned those off as well.

Rig:
Pentium G5400
6x RX 570 (miners)
1x RX 560 (discrete) 
MSI H310 mining motherboard
EVGA 850GQ
Win10 Ameliorated (Custom)

_Originally posted by @yumyumfarted in https://github.com/Lolliedieb/lolMiner-releases/discussions/276_

**Comment by yumyumfarted** [comment]
I am mining beam, I haven't seen it mining ETH. I'll have to double check.

**Comment by jgonzis** [comment]
the windows Driver can crash normally the best is to have a loop in the bat file so that make to rerun the miner without problem...

**Comment by yumyumfarted** [comment]
> the windows Driver can crash normally the best is to have a loop in the bat file so that make to rerun the miner without problem... 

Will do! I also think it was a power issue. I'm using the integrated GPU on my CPU, and I took out my RX 560. Also unplugged fans that went doing anything. The driver no longer resets, but I still get this error. Would the loop fix this as well?

Thanks,

**Comment by jgonzis** [comment]
The loop will made to realaunch it automatically... if you  want to focus on mining  the best option a free Linux Mining OS

**Comment by yumyumfarted** [comment]
I'll toss one on my Ventoy! I'll go ahead and close this issue now. I reported it to AMD, but I'm skeptical that they will do anything.
