### ISSUE TITLE
Lost connection to stratum server zhash.eu.nicehash.com:3369 or server not reachable

### ISSUE THREAD

**Issue by KgsGrp** [Lolliedieb/lolMiner-releases#279]
Lost connection to stratum server zhash.eu.nicehash.com:3369 or server not reachable.
Trying to connect in 1 second
Connected to zhash.eu.nicehash.com:3369  (TLS disabled)
Subscribed to stratum server
Authorized worker: 3MTTSdhUgqAUSLUc1V7B14eP7bAR4GyuQV$0-NUKIt9dqMlyKQg-AAa1d8w
New job received: 000000000d11d0e4 (BgoldPoW)

**The rig has had this problem for a couple of days**
I use nice hash, it doesn't let me use lolminer version "1.16a"

**Comment by gocoelho** [comment]
Same problem here.

←[0m←[38;2;255;165;000mTrying to connect in 1 second
←[0m←[38;2;240;230;140mConnected to zhash.eu.nicehash.com:3369  (TLS disabled)
←[0m←[38;2;240;230;140mSubscribed to stratum server
←[0m←[38;2;240;230;140mAuthorized worker: **<hidden>**
←[0m←[38;2;189;183;107mNew job received: **<hidden>** (BgoldPoW)
←[0mAverage speed (30s): 1.1 sol/s
←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (12:38:41); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 12m 42s
←[0m←[38;2;100;149;237m                     ←[0m←[38;2;100;149;237m   GPU 0←[0m←[38;2;100;149;237m   Total←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mSpeed (sol/s):       ←[0m←[38;2;100;149;237m     1.2←[0m←[38;2;100;149;237m     1.2←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mBest Share:          ←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mShares (A/R):        ←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mPower (W):           ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mEfficiency (sol/s/W):←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mTemp (deg C):        ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mFan Speed (%):       ←[0m←[38;2;100;149;237m       0←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237m---------------------------------------------
←[0mAverage speed (30s): 1.3 sol/s
←[38;2;189;183;107mNew job received: **<hidden>** (BgoldPoW)
**←[0m←[38;2;255;165;000mLost connection to stratum server zhash.eu.nicehash.com:3369 or server not reachable.**

**Comment by jgonzis** [comment]
Internet  / Firewall problem
