### ISSUE TITLE
0.9.6 no API?

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [Lolliedieb/lolMiner-releases#28]
What happened with API since 0.9.6? there is no any listen API on port 4444 anymore.
Up to 0.9.5.1 worked fine.

**Comment by Lolliedieb** [comment]
That is strange, because that part should be untouched... I will test that when at home :)

**Comment by tymoteuszrogalewski** [comment]
Reboot rig didn't help.
Netstat tells that no deaemon is listening on 4444 port.
When stop 0.9.6 and start 0.9.5.1, than API goes up properly. Back again to new 0.9.6 - API disapears.

**Comment by tymoteuszrogalewski** [comment]
Problem solved, but dont now why at all

I just added "--apiport 4444" to command line options and API back.
In PDF from 0.9.5.1 and 0.9.8.1 desc about API didnt diff to thoose versions and in both are described, that default port is "0" - seems to be disabled as default, but upto 0.9.5.1 it didnt - it worked well as a default on 4444 port :) And for newer versions its like to be fixed with described in documentation :) ???
