### ISSUE TITLE
Detected a defect share (potential hardware error) lolminer v1.24

### ISSUE THREAD

**Issue by Caburm** [Lolliedieb/lolMiner-releases#280]
Asking for help, i'm currently using msi rtx 3060ti and I'm having this error detected a defect share (potential hardware error). What seems to be the reason? Attached is my current setup in MSI Afterburner. Thanks!

![MSI Afterburner](https://user-images.githubusercontent.com/79202471/108202568-44322900-715c-11eb-965f-9986f0e08670.png)

**Comment by yumyumfarted** [comment]
A defect share means someone has already found the share, or you card spit out the wrong hash format. This happens to my cards occasionally, it's totally normal. If it's happening a lot- possibly greater than 5-10 percent, there _might_ be a problem.

**Comment by Caburm** [comment]
> A defect share means someone has already found the share, or you card spit out the wrong hash format. This happens to my cards occasionally, it's totally normal. If it's happening a lot- possibly greater than 5-10 percent, there _might_ be a problem.

Ow I see, yeah it also happens to me occasionally. Guess i'm on the right path for now. Appreciate your reply!

**Comment by jgonzis** [comment]
That could happen when the memory OC is quite high... that is you case it is really high... you are very lucky with the quality of that Memories going at this speed

**Comment by jgonzis** [comment]
Try new Cuda Solver it has dag repair and could reduce that errorea
