### ISSUE TITLE
Zombie mode - more details needed

### ISSUE THREAD

**Issue by 4miners** [Lolliedieb/lolMiner-releases#283]
Hi,

I did some tests on GA-Z97X-UD3H-BK motherboard, which has 3 PCI-E x16 slots, running while fully populated on 8x, 8x, 4x speeds (2 first conform to Gen3 standard, not sure about the last one). I'm getting 25.98/24.19/16.71 MH/s using some Sapphire PULSE RX 580 4GB cards. I'm running lolMiner 1.24a on Linux ofc, I did some benchmarking using a high DAG epoch and looks like those cards can last for a while when directly connected to the motherboard.

Would be very nice if you can disclose in more detail how zombie mode exactly works, so people can adjust their hardware configs accordingly. There are some amazing motherboards on the market, like [Asrock ROMED8-2T](https://www.asrockrack.com/general/productdetail.asp?Model=ROMED8-2T#Specifications), which have 7 Gen4 PCI-E x16 slots and supports them at full speed due to the fact that Epyc processors have enough PCI-E lanes for it. These slots can be divided into lower-speed ones using bifurcation. I'm also wondering if DDR4 can have an advantage over DDR3, especially with 8 channels. In theory, a modern high-performance system (like Epyc one) can handle zombie mode forever without a significant slowdown in hashrate, is this correct? Do you know where are the bottlenecks exactly when utilizing zombie mode?

Best regards,
Mariusz

**Comment by Karasur** [comment]
Try to add more ram, with 16Gb ram should get 27.7/27.6/19.38

**Comment by dionysos1111** [comment]
Im using an older mobo asrock 970 pro3 r2 using 4x8gb ram.

I connected 2 rx470 in the 2 pcie x16 slots.
The hashrate on this board is for gpu0 27.47  and gpu1 16.08
![Screenshot_20210219-104923_Hive OS](https://user-images.githubusercontent.com/79309120/108488382-9d0ada00-72a0-11eb-99f7-ac4551e622b4.jpg)

I'm also using another mobo, asus z170 pro gaming with 2x 8gb mem and 2 rx470. Hashrate for gpu0 is 26.58 and gpu1 24.31

Also using a miner mobo H110 pro btc+ with 1 rx470 in the pcie x16 slot, hashrate 28.10.

When i connect risers in the x1 slots on any of the boards the hashrate drops on the other gpu's. When i connect riser to the miner mobo h110 pro btc+ the card in the pcie x16 fails.

I don't understand why gpu1 is always lower hashrate then gpu0, has it something to do with the lanes the mobo can max have? Especially on the asrock 970 pro3 the difference is significantly.

Anyone also has this problem or knows why this is?

And 4miners, you say you calculated how long we can use this setup, how long can we still use this setup?

**Comment by Karasur** [comment]
Currently you can get 26-27mh only for x8 or x16 pciex slots, 18-20mh for x4 slots.
970 pro3 has x16+x4
asus z170 pro gaming has x8+x8
H110 pro btc+ has x16

**Comment by 4miners** [comment]
@Karasur Thank you for the benchmarks! Inspired by you I did some more benchmarking as well on my system. I used a matching pair of [KHX16C9T3K2/8X](https://www.kingston.com/datasheets/khx16c9t3k2_8x.pdf) and [KHX16C9X3K2/16X](https://www.kingston.com/dataSheets/KHX16C9X3K2_16X.pdf).

Those results for 8x/8x/4x are following;
```
--------------------------------------------------
Dual channel 2x4GB KHX16C9T3K2/8X CL9 @ 1600
MH/s:        27.74 | 25.92 | 16.58 
Zombie-tune: 14.25 | 15.75 | 5
Power:       77W   | 79W   | 80W   @ 412W
--------------------------------------------------
Single channel 2x4GB KHX16C9T3K2/8X CL9 @ 1600
(sticks in slots DDR_1 + DDR_3, no should be no dual channel)
MH/s:        27.00 | 25.26 | 15.25 
Zombie-tune: 14.25 | 14.25 | 3.5
Power:       76W   | 80W   | 82W   @ 421W
--------------------------------------------------
Dual channel 2x4GB KHX16C9T3K2/8X CL9 + 2x8GB KHX16C9X3K2/16X CL9 @ 1333
(first pair placed in DDR_1 + DDR_2 slots, they are all reported as running at 1333)
MH/s:        27.74 | 25.92 | 16.59
Zombie-tune: 14.25 | 15.75 | 5
Power:       77W   | 78W   | 80W   @ 422W
--------------------------------------------------
Dual channel 2x8GB KHX16C9X3K2/16X CL9 @ 1333
(this RAM is rated 1600 but in default runs at 1333)
MH/s:        27.75 | 25.97 | 16.56
Zombie-tune: 14.5  | 15.5  | 5.25
Power:       77W   | 78W   | 80W   @ 415W
--------------------------------------------------
Dual channel 2x8GB KHX16C9X3K2/16X CL9 @ 2000
(overclocked)
MH/s:        27.91 | 26.04 | 16.78
Zombie-tune: 14.5  | 15.75 | 5
Power:       78W   | 78W   | 82W   @ 425W
--------------------------------------------------
Single channel 8GB KHX16C9X3K2/16X CL9 @ 2000
(overclocked, only 1 stick)
MH/s:        27.82 | 25.99 | 16.79
Zombie-tune: 14.5  | 15.25 | 5
--------------------------------------------------
```

Then I was wondering why the card in the second slot always has a lower hashrate, so I swapped the cards.
```
--------------------------------------------------
Single channel 8GB KHX16C9X3K2/16X CL9 @ 2000
(cards 1 and 2 swapped)
MH/s:        25.97 | 27.73 | 16.79
Zombie-tune: 15.75 | 14    | 5
--------------------------------------------------
```
Those cards are identical but one was coming from a different rig, turned out it had different BIOS. After I flashed it with the BIOS from a better performing card - the speeds were exactly the same for both 8x slots.

I was not sure if the 4x slot conforms to Gen3 or Gen2, I did some research. Looks like this slot is provided by Z297 PCH Chipset and according to Intel ARK this chipset provides only Gen2. I tested the card in a single x16 slot using a high-quality bifurcation riser that supports Gen3. There is a difference between Gen2 and Gen3 obviously:
```
--------------------------------------------------
Single channel 8GB KHX16C9X3K2/16X CL9 @ 2000
(PCI-E 3.0 4x)
MH/s:        20.93
Zombie-tune: 9
--------------------------------------------------
```
Looks like there is a difference between single and dual channel, also faster memory helps. However, I have no idea why your results, @Karasur, were so much worse in single channel / less RAM configuration. Did you let zombie mode to auto tune?

**Comment by Karasur** [comment]
@4miners
Yep, all tested with finished auto tune!
Much speed memory not worth the result.
I noticed that the only necessary option is to use 2 slot memory minimum.
Hope will try next week asus rampage vi extreme with 4 gpu at once.
Ordered 2 rank memory want to try with MAXIMUS IX APEX and 4 gpu.

**Comment by izhere** [comment]
Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!

**Comment by dionysos1111** [comment]
> Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!

First slot is x16 the other 2 must be x4 or probarly x1, need to use more or other mobo. Look at the asus rampage iv series

**Comment by izhere** [comment]
> > Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!
> 
> First slot is x16 the other 2 must be x4 or probarly x1, need to use more or other mobo. Look at the asus rampage iv series

I have A X370 MSI Gaming Pro motherboard, that will help me?

**Comment by dionysos1111** [comment]
> > > Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!
> > 
> > 
> > First slot is x16 the other 2 must be x4 or probarly x1, need to use more or other mobo. Look at the asus rampage iv series
> 
> I have A X370 MSI Gaming Pro motherboard, that will help me?

PCI-E GEN
Gen3(16, 0) (8, 8), Gen2(4)

Yes, first 2 slots the pcie 3.0 are 8x if 2 are used. X8 should get 25mh or so with good  oc

**Comment by KayWong** [comment]
> Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!

same problem with me, even the speed is the same

motherboard: BIOSTAR TB250-BTC
ram: 16G x 1 DDR4 3000
gpu0: 24~mh/s(Rx 570), gpu1: 8~mh/s(Rx 570), gpu2: 8~mh/s(Rx 570)
OS: Ubuntu 16.04 (kernel 4.1)

lolMiner start with the parameter --4g-alloc-size 4071 (Tried a higher value but the speed became almost 0）

If anyone knows what I should do, I would be very grateful

**Comment by nosilence1994** [comment]
@KayWong 
PCI-E of BIOSTAR TB250-BTC is 1×PCI-E X16 slots and 5×PCI-E X1. PCI-E X1 will limit the speed greatly.

**Comment by dionysos1111** [comment]
> Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!

1 x PCIe 3.0 X16
2 x PCIe 2.0 X16 (X4* and X1 electrical)
1 x PCIe 2.0 X1
*The PCIe 2.0 X4 slot operates at X2 when both X1 slots are populated
**Reduced PCIe bandwidth available when using Ryzen APUs

So other two pcie are x4, gives lower bandwidth. 

Get a new mobo, nothing else to do.

**Comment by mew905** [comment]
> Would be very nice if you can disclose in more detail how zombie mode exactly works, so people can adjust their hardware configs accordingly. There are some amazing motherboards on the market, like [Asrock ROMED8-2T](https://www.asrockrack.com/general/productdetail.asp?Model=ROMED8-2T#Specifications), which have 7 Gen4 PCI-E x16 slots and supports them at full speed due to the fact that Epyc processors have enough PCI-E lanes for it. These slots can be divided into lower-speed ones using bifurcation. I'm also wondering if DDR4 can have an advantage over DDR3, especially with 8 channels. In theory, a modern high-performance system (like Epyc one) can handle zombie mode forever without a significant slowdown in hashrate, is this correct? Do you know where are the bottlenecks exactly when utilizing zombie mode?
> 
> Best regards,
> Mariusz

Cheapest route would probably be Xeon E5 2600 series CPUs (40 lanes each) on a dual socket motherboard like a Dell T7600, T5600, Supermicro X9DRD-iF, X9DR3-F (has 6 PCIe slots), HP has a couple too.

Basically the cheapest *dual* LGA 2011 v1 motherboard you can find with the most slots, some ribbon cable risers for maximum bandwidth (the standard USB risers won't do)

So dual 40 lane CPUs gives you 80 lanes, or enough for 5 full-speed x16 slots, however it appears x8 is plenty so you could probably run some bifurcation boards and build a proper 4GB mining rig.

Also apparently system memory speed and timings affect hashrate so keep that in mind. However DDR3 ECC is pretty cheap

**Comment by abihakim** [comment]
> > Hi guys anyone can help me? I have Aorus B450 Pro motherboard, 32gb @3200mhz. I can get only the first card at 24mh/s, other 2 of them only 8mh/s What settings should I use for the miner? Thank you!
> 
> 1 x PCIe 3.0 X16
> 2 x PCIe 2.0 X16 (X4* and X1 electrical)
> 1 x PCIe 2.0 X1
> *The PCIe 2.0 X4 slot operates at X2 when both X1 slots are populated
> **Reduced PCIe bandwidth available when using Ryzen APUs
> 
> So other two pcie are x4, gives lower bandwidth.
> 
> Get a new mobo, nothing else to do.

Hello, I have Asrock B450 Pro4 Motherboard, It was written on the sheet:

**AMD Ryzen series CPUs (Matisse, Summit Ridge and Pinnacle Ridge)
- 2 x PCI Express 3.0 x16 Slots (PCIE2: x16 mode; PCIE4: x4 mode)***
http://www.asrock.com/MB/AMD/B450%20Pro4/#Specification

I'm using Ryzen 5 2600 atm.
Can It do two x8 for two rx570 to go zombie mode on lolminer?

Thanks in advance.

**Comment by ronitovi** [comment]
After all it turns out that "zombie mode" for 4G cards has almost no meaning since we can't make rigs out of them anymore... Pciex speed is not important on +4Gb cards 'cus they wont go in zombie mode but x16 (maybe at least x8) is crucial for 4G cards and it's almost impossible to find mobos that have multi x16 slots for decent prices... so, zombie mode is only good for 1-2 cards, not more, no suitable for rigs at all. Welcome & good-bye zombie mode!

**Comment by sami9i** [comment]
> Try to add more ram, with 16Gb should get 27.7/27.6/19.38 (RX470 Samsung 1200core and 2100+ mem).
> ASUS ROG MAXIMUS IX APEX (x16x8x4) + CPU G3930
> RAM1 - 8GB AMD R748G2133U2S-U 2133MHz
> RAM2 - 16GB Data XPG Gammix D10 [AX4U3200716G16A-DB10] 3200MHz
> RX470 Samsung - 1200/2100mem
> 
> 8GB RAM1 - 24.8/24.7/13.5 = avg 63
> 2x8GB RAM1 - 27.7/27.6/19.38 = avg 74,6-74,94
> 16GB RAM2 - 25.6/26.3/14.5 = avg 66.4
> 2x16GB RAM2 - 27.4/27.2/19.4 = 74
> 
> hm, should try 4GB+4GB maybe not total size matters but channels ?!

can u tell me mobo setting 
ihave the same mobo and the 2 cards

**Comment by sami9i** [comment]
> > Try to add more ram, with 16Gb should get 27.7/27.6/19.38 (RX470 Samsung 1200core and 2100+ mem).
> > ASUS ROG MAXIMUS IX APEX (x16x8x4) + CPU G3930
> > RAM1 - 8GB AMD R748G2133U2S-U 2133MHz
> > RAM2 - 16GB Data XPG Gammix D10 [AX4U3200716G16A-DB10] 3200MHz
> > RX470 Samsung - 1200/2100mem
> > 8GB RAM1 - 24.8/24.7/13.5 = avg 63
> > 2x8GB RAM1 - 27.7/27.6/19.38 = avg 74,6-74,94
> > 16GB RAM2 - 25.6/26.3/14.5 = avg 66.4
> > 2x16GB RAM2 - 27.4/27.2/19.4 = 74
> > hm, should try 4GB+4GB maybe not total size matters but channels ?!
> 
> can u tell me mobo setting
> ihave the same mobo and the 2 cards

get only 18mh rx 570
5 mh rx 470

**Comment by sami9i** [comment]
ga990  fxa

**Comment by sami9i** [comment]
@Karasur

**Comment by sami9i** [comment]
ga 990fxa  ud3 gigabyte
rx 570 4  hynix
470 4 samsung 
19 mhs 
5 mhs

**Comment by sami9i** [comment]
what is the mobo setting plz

**Comment by Bakrhany** [comment]
I have 2 RX 570 4gb I was getting about 25mh/s for only one GPU by zombie mode but when I connect the 2nd GPU I get lower hashrate about 20 MH/s for every GPU I don't know why ?
I need some help please

**Comment by billalarara** [comment]
hi, i wich to buy motherboard Asroc x299 killer, that have 4 pcie 3.0 x16 with crosfire technology, my quation is: it worth to buy for using 4 rx 570 4gb with lolminer zombie mode?

**Comment by jgonzis** [comment]
> Hi, I wish to buy motherboard Asrock x299 killer, that have 4 pcie 3.0 x16 with crossfire technology, my question is: it worth to buy for using 4 Rx 570 4GB with lolminer zombie mode?

I think now is better to mine ETC+ZIL or ERGO with lolMiner
