### ISSUE TITLE
 Allocation of DAG failed 

### ISSUE THREAD

**Issue by milchkuh2** [Lolliedieb/lolMiner-releases#284]
Hey, i get the following message when i connect my 5th RX5700/XT to the rig(as soon as i start the miner):
"GPU 4: Allocation of DAG failed with error: Memory object allocation failure
GPU 4: will be stopped.
GPU 0: Allocation of DAG failed with error: Memory object allocation failure
GPU 0: will be stopped."
I did not overclock and run them on standard settings (amd software).
I doesnt matter which GPU i connect as the 5th one and all these cards should have 8 GB. Hope you can help me.

RIG:
Intel cerlon G3950 3,00 Gh 2MB Cache
2x 4GB RAM
2x RX5700
3x RX5700XT
Win10
Asrock h110 pro btc+

**Comment by jgonzis** [comment]
I think the problem you have is that you don't have active probably the 4G Encode in the BIOS... you need that parameter to mine with more than 4 Cards. 

Have you try with 4 and works correctly?. If that happens you need to active the 4G Encoding in the BIOS.

**Comment by RunOrDrink** [comment]
Just increase your pagefile, put like 32gb with 32gb. Reset pc and should work.
