### ISSUE TITLE
--tstart 70 --tstop 90,this parameters to a high rehjection rate,i‘m sure

### ISSUE THREAD

**Issue by mqqep** [Lolliedieb/lolMiner-releases#290]
after adding  parameters --tstart 70 --tstop 90  the following error occurred randomly

Detected a defect share (potential hardware error)

this leads to a high rehjection rate,i‘m sure

**Comment by jgonzis** [comment]
> after adding parameters --tstart 70 --tstop 90 the following error occurred randomly
> 
> Detected a defect share (potential hardware error)
> 
> this leads to a high rehjection rate,i‘m sure

With new releases have been that improved.
