### ISSUE TITLE
Public IP Address Error

### ISSUE THREAD

**Issue by VexxMining** [Lolliedieb/lolMiner-releases#292]
The IP address ethermine has is different than my public IP address. The address that shows up in cmd -ipconfig and on whatismyip.com are the same and they are BOTH not the same as the one ethermine is expecting. When loading the miner I noticed the Ethereum stratum mode is : Ethereum Proxy, could that have an effect on this?

**Comment by jgonzis** [comment]
Ipconfig normally shows an intern ip address, only the router have normally the public ip...

That Ethereum Statum is the protocol connection, it doesn't affect IP or modify them.

**Comment by Lolliedieb** [comment]
The ip address is usually not affected by the miner software it all. 
Check your router configuration to see the current public ip address used.
