### ISSUE TITLE
'lolMiner.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by vladomeister** [Lolliedieb/lolMiner-releases#293]
I think this issue has less to do with the fact that im running the batch file as an administrator and that when i configure the mine_eth batch file the .exe program dissapears from the folder. Any help is appreciated, just trying to get into the mining game :)

**Comment by jgonzis** [comment]
> I think this issue has less to do with the fact that im running the batch file as an administrator and that when i configure the mine_eth batch file the .exe program dissapears from the folder. Any help is appreciated, just trying to get into the mining game :)

That's normal, you are running it as Administrator, then you should add the path of the lolMiner.exe

For example:

C:\lolMiner\lolMiner.exe -a ETHASH  ....

If you don't specify it, it will not find it, because In Administrator mode it starts in c\Windows\system32 folder and you haven't there the lolMiner.exe 

I hope I have explained well

**Comment by PBJ22557** [comment]
after i did this it says "access denied". i tried everything, running as administrator, disabling my anti virus, disabling my firewall.

**Comment by jgonzis** [comment]
> after i did this it says "access denied". i tried everything, running as administrator, disabling my anti virus, disabling my firewall.

Access denied is antivirus blocking... you should disable the folder...

**Comment by PBJ22557** [comment]
Sorry, but how do I disable the folder?

**Comment by jgonzis** [comment]
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by vladomeister** [comment]
Yup i have solved the issue since, my antivirus kept on deleting my executable file but now its up and running! Not related to the stuff before but when i go to change my payout amount on ethermine the hint for my ip address is different than the ip address of my only mining rig. Any help is welcome!

**Comment by jgonzis** [comment]
https://github.com/Lolliedieb/lolMiner-releases/issues/452
