### ISSUE TITLE
I can't see Fan Speed, Temp and power on miner

### ISSUE THREAD

**Issue by Joleks** [Lolliedieb/lolMiner-releases#295]
Hey guys i can't see a fan speed, temp and power on miner. How to fix this ? 
![Desktop Screenshot 2021 02 21 - 15 57 31 87](https://user-images.githubusercontent.com/79410953/108629208-3122a000-745f-11eb-924e-ad3f36e9885a.png)

**Comment by jgonzis** [comment]
Hi, which card are you using?.... Nvidia last drivers in Windows hat a problem with the NVML that doesn't show this information

**Comment by Lolliedieb** [comment]
Please provide more into on the used GPU - because AMDs and Nvidias have different sensors exposed - also between different models. Also Windows or Linux would be good to know.

**Comment by jgonzis** [comment]
New stats parameters have solved that problem too
