### ISSUE TITLE
Trojan founded?

### ISSUE THREAD

**Issue by Wspak262** [Lolliedieb/lolMiner-releases#296]
When i want to extract zip file, antivirus found trojan. Am i supposed be worried?
![Zrzut ekranu 2021-02-21 182324](https://user-images.githubusercontent.com/62672731/108632960-e6f6ea00-7471-11eb-8f83-5c4290d58144.png)

**Comment by jgonzis** [comment]
That's normal, nearly all miners are considered trojan by WINDOWS

**Comment by Lolliedieb** [comment]
I even signed the executable file ... so you can be sure it is like its supposed to be. Sadly many Antivirus do not like mining software because it obviously needs 
- Hardware access
- Open Ports for connecting to the pool or for telemetry api

**Comment by rprinku** [comment]
lol miner Zam spy boat Trojan virus found issue

**Comment by jgonzis** [comment]
Complete normal windows detection as virus.
