### ISSUE TITLE
Compatibility Failure.

### ISSUE THREAD

**Issue by Kipkurui-mutai** [Lolliedieb/lolMiner-releases#297]
Setup Miner...
Device 0:
    Name:    Intel(R) HD Graphics 4000
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Memory:  1400 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to eu1.ethermine.org:14444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x71312B55C814D0316eEE1CF1dd3873F0a197369D.lolMinerWorker
New job received: 0xde47ce Epoch: 396 Target: 0000000112e0be82
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . .

**Comment by ersnsmsk** [comment]
same issue help please:(

**Comment by jgonzis** [comment]
It is normal, it will only work with Nvidia or AMD cards...

**Comment by Kipkurui-mutai** [comment]
Only works with Nvidia or AMD cards.
