### ISSUE TITLE
Active:  false (Unsupported device or driver version.)

### ISSUE THREAD

**Issue by CuddlyHamsterWarrior** [Lolliedieb/lolMiner-releases#299]
Setup Miner...
Device 0:
    Name:    AMD Radeon(TM) R7 Graphics
    Address: 0:1
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  12714 MByte (16531 MByte free)
    Active:  false (Unsupported device or driver version.)
Device 1:
    Name:    AMD Radeon(TM) R7 Graphics
    Address: 0:1
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  12714 MByte (16531 MByte free)
    Active:  false (Unsupported device or driver version.)

Tell me how to fix this. Thank you.

**Comment by jgonzis** [comment]
Que version estás usando de lolMiner?

Es una 6800/6900?

**Comment by CuddlyHamsterWarrior** [comment]
Only English speakers reply please.

**Comment by barbossas** [comment]
Is there an update on this?
Running Win10 with RX6800 and get the same error.

**Comment by jgonzis** [comment]
New release has solved that
