### ISSUE TITLE
Connection failure to nicehash

### ISSUE THREAD

**Issue by DrRobotto** [Lolliedieb/lolMiner-releases#3]
I can't get any connection to the nicehash service with the following command:

lolMiner.exe --pool zhash.eu.nicehash.com --port 3369 --user #ADDRESS --pass x --devices NVIDIA --apiport 4068 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --coin AUTO144_5

Is there anything wrong with your miner or do I have any error in my configuration?

**Comment by SydorukAndrii** [comment]
lolMiner.exe --coin BEAM --pool stratum+tcp://beam.eu.nicehash.com:3370 --port 3370 --user #ADDRESS  --pass x
Does not work!

**Comment by Lolliedieb** [comment]
Nicehash on port 3370 neets --tls 0, because thats a non-tls port :)
