### ISSUE TITLE
Error: no user account or wallet configured 

### ISSUE THREAD

**Issue by m4rv5k1n7987** [Lolliedieb/lolMiner-releases#303]
hi, so ive just started out and am trying to start lolminer 1.21 on my windows10 
i seem to have followed the steps correctly as far as im aware apon setup but for some reason when i start it gives me error message: No user account or wallet to mine on configured.

i have checked by bat file and must be missing something.

any help would be greatly appreciated guys 🙌

**Comment by CHIPofficial** [comment]
do you still have POOL=blabblab

**Comment by jgonzis** [comment]
Bat file configuration

**Comment by DenAlS** [comment]
ну и какое решение проблемы?

**Comment by jgonzis** [comment]
> ну и какое решение проблемы?

Install lolMiner 1.31 and change the file bat.

Установите lolMiner 1.31 и измените файл bat.
