### ISSUE TITLE
all devices deselected or failed compatibility check. closing lolminer

### ISSUE THREAD

**Issue by DBCFD23** [Lolliedieb/lolMiner-releases#304]
Hello,

I am trying to use your miner, after adding the relevant mining pool paramters in the batch file it shwoing me the following message as attached in the pic as well : 

all devices deselected or failed compatibility check. closing lolminer
![Capture](https://user-images.githubusercontent.com/79508520/108824683-ea958880-75b9-11eb-8fdb-d3e351e17eb7.PNG)

**Comment by kamark85** [comment]
same

**Comment by twiddledeebit** [comment]
Getting the same thing on rig that's been running for weeks with no changes. It has (3) RX 480 GPUs and (1) RX 580 GPU. LolMiner ver 1.16a

**Comment by twiddledeebit** [comment]
upgraded to v1.21 and still same issue. Using AMD Crimson Blockchain driver.

**Comment by twiddledeebit** [comment]
Even though I have the Microsoft Update Service halted on this miner, I found that Microsoft OneDrive had somehow installed itself a few days ago. I uninstalled OneDrive and now lolMiner sees my GPUs and everything is back to normal. Don't know what the correlation or conflict was...

**Comment by markmason12** [comment]
same

**Comment by TiantianPython** [comment]
same

**Comment by lien-github** [comment]
same , why?

![image](https://user-images.githubusercontent.com/34596043/114853408-548e1980-9e16-11eb-93f8-0bab500ef37d.png)

**Comment by saisurajkarra** [comment]
have the same issue on ETchash even

**Comment by jgonzis** [comment]
Same as https://github.com/Lolliedieb/lolMiner-releases/issues/170
