### ISSUE TITLE
Lolminer doesn't support vega 3

### ISSUE THREAD

**Issue by CHIPofficial** [Lolliedieb/lolMiner-releases#308]
![image](https://user-images.githubusercontent.com/79542982/108904424-520c0200-75d3-11eb-9b8e-4dcae2299225.png)

**Comment by jgonzis** [comment]
Correct, also think that the memory of the Vega is the DDR4, that will be really low to mining in ETH...

**Comment by jgonzis** [comment]
https://github.com/Lolliedieb/lolMiner-releases/issues/170
