### ISSUE TITLE
Problem in loading kerner-Error

### ISSUE THREAD

**Issue by bcolak58** [Lolliedieb/lolMiner-releases#310]
help me ;  How can i solve this problem ?
![Ekran Alıntısı](https://user-images.githubusercontent.com/79603570/109060809-ecb13180-76f6-11eb-8657-225677bf957c.PNG)

name: Quadro k4200
adress : 20
Vendor : Nvidia
Memory : 4096 MByte

problem in loader kernel

**Comment by fdlibao** [comment]
I got the same problem with my Quadro K4200. Please help
![image](https://user-images.githubusercontent.com/44887762/109130950-43694a80-778d-11eb-92b0-713ddea11d21.png)

**Comment by fdlibao** [comment]
Encountered the same problem. Please help
![image](https://user-images.githubusercontent.com/44887762/109131047-5bd96500-778d-11eb-9b6d-d95d7f61c214.png)

**Comment by jgonzis** [comment]
I think the miner doesn't support that card...
