### ISSUE TITLE
Does lolminer support 2 gpu? bcs i'm getting like 50% performance

### ISSUE THREAD

**Issue by otacrazy2123** [Lolliedieb/lolMiner-releases#313]
Who should i configure/use the bats to work with 2 gpus? the split bat and the normal bat with 2 miners setup did not work properly, ended up with 25mhs on gpu 0 (2080) and 27 mhs on gpu1 (3070)

**Comment by antiplayrr** [comment]
Having the same issue here. Had my 3090 working great at 120mh/s. Adding in a 2080ti, dropped to 60mh/s across the 2 of them. Took the 3090 out, 2080ti ran as expected around 60mh/s. PSU is fine, and each GPU runs fine on its own.

**Comment by antiplayrr** [comment]
Dug in a bit more on some other threads. Found the solution. Running both

Start with 2 new instances (extract the zip file into 2 seperate folders) 

Edit the mine_eth.bat file

In the first one, replace 
'lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit' with
'lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 0 --watchdog exit' and save

In the second mine_eth.bat file, replace 
'lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit' with
'lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 1 --watchdog exit' and save

Run each mine_eth.bat file and your should get full mh/s out of each. Currently running about 60mh/s on 2 2080tis in the same system. From what I can tell, you'd just repeat this as needed when introducing more cards into the loop (ie 3rd card would be devices 2 and you'd run that .bat file as well)

Let me know if this works for you.

**Comment by otacrazy2123** [comment]
Just gave up and move to Phoenix Miner.
sry guys.
