### ISSUE TITLE
Card not mining?

### ISSUE THREAD

**Issue by klincb** [Lolliedieb/lolMiner-releases#315]
I wanted to try running the 1.21 miner on my r9 390 and since I am new I am not sure if I failed at setting it up or my card is faulty. Have been looking for a solution but cant seem to find anything. 
( I tried running it on my other PC with a RX 5700 and there it works fine)
https://imgur.com/YNpR88l
Can someone explain to me why my pool stays at 0 ? even after running it for a whole night it would barely make any progress.

**Comment by jgonzis** [comment]
> I wanted to try running the 1.21 miner on my r9 390 and since I am new I am not sure if I failed at setting it up or my card is faulty. Have been looking for a solution but cant seem to find anything.
> ( I tried running it on my other PC with a RX 5700 and there it works fine)
> https://imgur.com/YNpR88l
> Can someone explain to me why my pool stays at 0 ? even after running it for a whole night it would barely make any progress.

That's de luck... is mining but not shares has been found yet... let him time to find shares and that will change. You have small hash and that usuallly take more time to find solutions
