### ISSUE TITLE
RX480, Unsupported Device

### ISSUE THREAD

**Issue by kosshishub** [Lolliedieb/lolMiner-releases#316]
```
Device 0:
    Name:    Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    Address: 9:0
    Vendor:  Advanced Micro Devices (AMD), ROCm
    Memory:  4096 MByte (4096 MByte free)
    Active:  false (Unsupported device or driver version.)
```
ROCm OpenCL 2.2, 5.10.1-gentoo. It would be nice if it at least told me why it's unsupported. What are the requirements? There appears not to be any kind of verbose flag either.

**Comment by jgonzis** [comment]
You should install the AMD drivers from the website remember to add --opencl=pal,legacy,rocm that will let you all options for the cards.

Version 20.40 is one of the best
