### ISSUE TITLE
Zombie mode on PCIe 2.0 and ddr3

### ISSUE THREAD

**Issue by bullet97** [Lolliedieb/lolMiner-releases#317]
System:
CPU:AMD FX(tm)-6300 Six-Core Processor
Motherboard: Gigabyte 970A-UD3P
PCIe x16(2.0)
Total memory: 8 GB (ddr3)
Sapphire RX570 Pulse 4 gb
RaveOS
LolMiner 1.24a

Dear developer please answer, will be work zombie mode in similar systems?

Many times I started mining and give results about 8-10 Mh/s. But 2 times I was witness change dag file epoch and at this very moment hashrate increased to 25-26 Mh/s.  How do you explain such a result? 
That is, in such a system, the video card can work in zombie mode. Is there a bug in the program?

**Comment by jgonzis** [comment]
If you are in Windows are you running it with compute_mode?

**Comment by bullet97** [comment]
> If you are in Windows are you running it with compute_mode?

No, in Linux, RaveOS.

**Comment by jgonzis** [comment]
When starts mining it need some minutes until zombie mode is done... that could take time...

**Comment by bullet97** [comment]
Of course, several minutes and half an hour or more passed. The same result. Miner writes " auto tuning complete, result 0.5". 
Question about pci express 2.0 speed  enough for work 4gb card in zombie mode. And correctly work also.

**Comment by nylonW** [comment]
Maybe your card sits in a wrong slot, your mobo has 2 pci-e x16 and one of them works in x4 mode

**Comment by bullet97** [comment]
> Maybe your card sits in a wrong slot, your mobo has 2 pci-e x16 and one of them works in x4 mode

Thanks, but card in x16 slot absolutely sure.

**Comment by rst108** [comment]
Hashrate on computer is different from the pool. Sometimes hashrate on pool is low sometimes its high. But hashrate on computer should be stable. If you on raveos then you can see on the linux screen how much is your hashrate. But on windows you can only see your card effect on pool. Thats why sometime you see high, sometimes you see low. And it depends on your pool also. Even its mining same eth, different pool means you can get different hashrate and different reward. Hope this can help.
