### ISSUE TITLE
0.9.7 doesn't load 16G solvers on neither CT31 & CT32 [Nvidia]

### ISSUE THREAD

**Issue by Unnameless** [Lolliedieb/lolMiner-releases#32]
So decided to test the LOL miner on CT 31 & CT 32 on my beefy Titan Vs JHH. Each GPU has 32 GB vram.

Despite having the miner ran with GRIN-AT31 and GRIN-AT32 it selects the 8GB solvers despite having plenty of VRAM available. The speeds are also appalling: 0.3 for C32 and about 1gps for C31.

Bminer for reference crunches 2.7gps on C31 but on the 11 GB solver.
<img width="545" alt="Screen Shot 2020-02-05 at 12 39 12" src="https://user-images.githubusercontent.com/36138092/73835420-0b0b6d00-4816-11ea-8fe1-ebd35a4d897e.png">
<img width="495" alt="Screen Shot 2020-02-05 at 12 36 46" src="https://user-images.githubusercontent.com/36138092/73835426-0d6dc700-4816-11ea-9f7b-bdcc6cdbee2e.png">

**Comment by BallowandSunder** [comment]
Having the same issue with Titan RTX, C32 should be the one at least taking advantage of the full 24GB and your full 32GB. It was mentioned in the grin forums by one of the leading developers that the high memory and power of the RTX Titan was good for C32. Hopefully the 0.9.9 update includes the high memory and power of these beast cards.

**Comment by Unnameless** [comment]
Yeah, hope so too. Talked to lolliedieb like a week ago over discord and apparently he was not aware of this issue signaled here and said he will fix it, and make the miner properly recognize de 16G kernel.

He at first thought I was asking for a 32 GB solver, which would have been sweet non the less but I understand too much work for so very few people

**Comment by Lolliedieb** [comment]
The last versions at least have C32 16G kernel in for Nvidias - does it load?
