### ISSUE TITLE
BTC 37 motherboard

### ISSUE THREAD

**Issue by rst108** [Lolliedieb/lolMiner-releases#322]
Hello there,

Im having an issue with BTC 37 motherboard. 
As it shown, it has 8 x PCIE 3.0 x16 (or am i wrong about this)
But im using my rx580 4gb and only get 7-8 MH/s while other card with 8gb have no issue.

Im using hive os. In another normal botherboard with PCIE 3.0 x16 with no riser, im getting 22 MH/s.

Do you guys have any solution for this problem?

**Comment by pvk071** [comment]
BTC 37 have 8xPCIEx16, but they are running at PCIEx1. There is no way to increase the speed, it is actually the same as using PCIEx16->x1 risers.

**Comment by rst108** [comment]
i see that. so the spec written was wrong.
thank you for the information.
