### ISSUE TITLE
R7 370 4GB (Sapphire Nitro)

### ISSUE THREAD

**Issue by Nunaurs** [Lolliedieb/lolMiner-releases#323]
Sapphire R7 370 4GB Nitro doesn't work in zombie mode, not even on HiveOS. It does work & gets a fairly high hash rate 20+ MH/s with I think Phoenix Miner while mining ETHash ETC. So it mines the algorithm Ethash, but only when the coin is Etherium Classic/ETC (not sure though because it's not like I tried every single miner & configuration) & if I remember it was Phoenix Miner that did it on HiveOS.  I've seen recent (Feb 2021) YT vids showing 4GB cards mining on HiveOS that are still getting 20+ MH/s on Ethash mining Etherium (ETH) using lolminer, I tried with R7 370 4GB & no luck, and when I try with just lolminer, say in windows 10, it doesn't work. Is it a glitch with lolminer or does HiveOS do something different or is it Windows 10? I can't figure it out.  I noticed that HiveOS recognizes the R7 370 as an R9 270 (I think).  I just wish that lolminer worked with all 4GB cards, but I guess not. 1st time posting on Github, only used it for downloads up til now, so not sure if I'm posting in correct place, but I read in the latest update lolminer 1.24 for linux that support was added for R9 290(x) & 295. I used to think R7 370 was same line of cards but apparently not, dug around & found that R7 370 is Tahiti if I remember correctly, but not sure if it's a lot of extra work to add support for R7 370 4GB, if it currently doesn't exist. I've tried looking around the net & I can't find anything recent. Is there a special driver? Maybe that's why HiveOS seems to do the best for R7 370 4GB cards, because I don't pick or install the gpu driver. On windows I've tried the Crimson Relive Blockchain driver with no improvement or any luck, tried the most recent & 1 or 2 previous ones, still no change. If anyone can help with this it would be very much appreciated and I bet there's a enough people with R7 370 4GB cards dying to put them to better use. Thanks. 
1 last thing, there's a weird issue where some miners show only 3GBs of RAM on the R7 370 4GB, maybe that's why, maybe lolminer doesn't even accept it as a 4GB card to begin with. These are some answers I found but don't know how to implement. 1 person said an edit had to be made  "setx GPU_FORCE_64BIT_PTR 1 on ubuntu export GPU_FORCE_64BIT_PTR =1" & the person who they answered said that Ethermine was showing 3GB on an R7 370 4GB, another person answered this but someone responded they had and it didn't work:

create a bat file with these and insert your ethminer launch command in the last line. that should fix it.

setx GPU_USE_SYNC_OBJECTS 1 
setx GPU_FORCE_64BIT_PTR 0 
setx GPU_MAX_HEAP_SIZE 100
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer -G ...

**Comment by jgonzis** [comment]
This parameters are for Windows... in Windows Zombie Mode ist not working more, because there aren't space in the memory of the cards.

**Comment by jgonzis** [comment]
You can mine ETC or very soon ERGO too
