### ISSUE TITLE
incorrect name pickup when --worker is used for dual mining 

### ISSUE THREAD

**Issue by lelelolo** [Lolliedieb/lolMiner-releases#325]
Hi
I'm using on lolMiner 1.24a and I saw this issue should be fixed on version 1.21.
My setup
Dual mining ETH+ZIL on Ezil
I passed --worker manually with the command or in the lolMiner.cfg but Ezil did not pick up the worker name but it uses my ZIL wallet address.
Just wondering is this as per design?

Thank you.

**Comment by jgonzis** [comment]
Depending on pool, rustpool.xyz read it properly Ezil.me not
