### ISSUE TITLE
0mh/s on 2G GPU card.

### ISSUE THREAD

**Issue by ElementQi** [Lolliedieb/lolMiner-releases#331]
Can 2G GPU work well on lolMiner?

**Comment by rst108** [comment]
Please someone answer. I want to know also how far the DAG size can we go until zombie mode no longer profitable.
So far the current DAG is still normal MH/s eventhough the data said its no longer profitable.

**Comment by jgonzis** [comment]
> Can 2G GPU work well on lolMiner?

They will do in ERGO  and now only in BTG
