### ISSUE TITLE
Lolminer  1.24a no rebooting  in crach card 

### ISSUE THREAD

**Issue by kimoumokni** [Lolliedieb/lolMiner-releases#332]
![Screenshot_20210304-075526_Chrome](https://user-images.githubusercontent.com/60070763/109919720-d04a6180-7cc1-11eb-9e1a-af06fe64c39b.jpg)

**Comment by gravisxv** [comment]
I confirm, there is same problem in 1.22 version too. I simply added a reboot command in emergency script but the miner does nothing. Is there another way to send reboot command to the os without external tools?

**Comment by kimoumokni** [comment]
--coin BEAM --pool eu1-beam.flypool.org:3443<http://eu1-beam.flypool.org:3443> --user 191d5cec7c7b390819700517d022196728ccca4517d25cd82934d547fe3e118c95 --apihost 127.0.0.1<http://127.0.0.1> --apiport 4444

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
