### ISSUE TITLE
Windows: RX 580 0 g/s and crash on cuckatoo32

### ISSUE THREAD

**Issue by cheesesoda** [Lolliedieb/lolMiner-releases#335]
Running lolMiner 1.21 (Win64), and it will crash after a minute or two while trying to mine Grin (cuckatoo32/grin-c32). During that time, it will connect and receive new jobs from the pool (have tried multiple pools, same issue), but it will show 0 g/s for gpu0 and gpu1 before it crashes. The software does not have this same issue while mining Swap (cr29-32).

**Comment by ROGF10** [comment]
What are your overclock settings?

**Comment by cheesesoda** [comment]
Stock clock speeds.

**Comment by jgonzis** [comment]
how much memory hash your card?...
