### ISSUE TITLE
Problem in loading kernel

### ISSUE THREAD

**Issue by Urakorix** [Lolliedieb/lolMiner-releases#338]
Hi, so Im new into mining and Im getting this error. Im using gtx 660 2gb.....from my research I think it is because 2gb is just to weak to solve the algorythm. So if I get some GPU with over 4gb will it work? Im scared to pay for a new GPU and getting the same error. Ill appreciate any kind of help. Thanks

**Comment by jgonzis** [comment]
With 2 Gb is to small for mininig now... also your GPU is really all and you will not get any benefit of it ... only Watts consume...
