### ISSUE TITLE
Command to setup 2nd GPU for LoLMiner

### ISSUE THREAD

**Issue by McStuttter** [Lolliedieb/lolMiner-releases#347]
Good Morning,

2 Radeon 5700 XT Cards

I originally had a 1 gpu rig and I recently added a second one but it does not show up on LoLMiner when i run the mine_eth.bat file. I was wondering if anyone knew the command to add the second gpu or if it should automatically show up. I plan on adding atleast 6 gpu's so im trying to figure out the correct command to add or what I need to do for the second gpu to show up.

Thanks!

**Comment by pdieppa** [comment]
As long as you are not using the switch --devices, the cards should be detected automatically.
