### ISSUE TITLE
Lost connection to stratum server daggerhashimoto.usa.nicehash.com:3353 or server not reachable.

### ISSUE THREAD

**Issue by ben1628** [Lolliedieb/lolMiner-releases#348]
Should I be concerned about it? Is the other EthereumStratum slower?
What should I do to fix this?

Connecting to pool...
Connected to daggerhashimoto.usa.nicehash.com:3353  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Lost connection to stratum server daggerhashimoto.usa.nicehash.com:3353 or server not reachable.
Trying to connect in 1 second
Connected to daggerhashimoto.usa.nicehash.com:3353  (TLS disabled)
Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.
Set Ethash stratum mode: EthereumStratum/1.0.0
Subscribed to stratum server

**Comment by jgonzis** [comment]
> Should I be concerned about it? Is the other EthereumStratum slower?
> What should I do to fix this?
> 
> Connecting to pool...
> Connected to daggerhashimoto.usa.nicehash.com:3353 (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Lost connection to stratum server daggerhashimoto.usa.nicehash.com:3353 or server not reachable.
> Trying to connect in 1 second
> Connected to daggerhashimoto.usa.nicehash.com:3353 (TLS disabled)
> Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.
> Set Ethash stratum mode: EthereumStratum/1.0.0
> Subscribed to stratum server

Nicehash use the --ethstratum ETHV1

You should add this parameter to your config line... but in this case seems to be a internet disconnection or a small server fail of nicehash
