### ISSUE TITLE
究竟什么是影响算力的瓶颈

### ISSUE THREAD

**Issue by grandfatheryun** [Lolliedieb/lolMiner-releases#349]
主板z87x ud3h cpu g1820 内存条ddr3 1600 4gx2 在只有一张卡的时候oc能有26+m
但是在两张卡下只有24.5&24.4算力
显卡是2x蓝宝石580 2304sp Samsung显存颗粒
请问什么是影响算力的瓶颈

**Comment by jgonzis** [comment]
> 主板z87x ud3h cpu g1820 内存条ddr3 1600 4gx2 在只有一张卡的时候oc能有26+m
> 但是在两张卡下只有24.5&24.4算力
> 显卡是2x蓝宝石580 2304sp Samsung显存颗粒
> 请问什么是影响算力的瓶颈

问题在于pci通道......你不能用Gen3x16运行这两块卡，除非你有一个服务器CPU。

**Comment by grandfatheryun** [comment]
> > 主板z87x ud3h cpu g1820 内存条ddr3 1600 4gx2 在只有一张卡的时候oc能有26+m
> 
> > 但是在两张卡下只有24.5&24.4算力
> 
> > 显卡是2x蓝宝石580 2304sp Samsung显存颗粒
> 
> > 请问什么是影响算力的瓶颈
> 
> 
> 
> 问题在于pci通道......你不能用Gen3x16运行这两块卡，除非你有一个服务器CPU。

感谢你的回答，lolminer1.24a我测了在pcie3.0x8下和pcie2.0x16是没有什么算力的差距的毕竟带宽也才差0.2g不到
oc 核心1200 电压900 显存2100 电压900 ref给的是30

**Comment by grandfatheryun** [comment]
> > 主板z87x ud3h cpu g1820 内存条ddr3 1600 4gx2 在只有一张卡的时候oc能有26+m
> 
> > 但是在两张卡下只有24.5&24.4算力
> 
> > 显卡是2x蓝宝石580 2304sp Samsung显存颗粒
> 
> > 请问什么是影响算力的瓶颈
> 
> 
> 
> 问题在于pci通道......你不能用Gen3x16运行这两块卡，除非你有一个服务器CPU。
看下我的回复老哥

**Comment by Lolliedieb** [comment]
I do not understand a work here ... I guess its fixed?
