### ISSUE TITLE
RTX 5700 Crashing

### ISSUE THREAD

**Issue by johnnyseriuss** [Lolliedieb/lolMiner-releases#350]
Lolminer 1.21 Keeps crashing after its running for 30 or more randomly. I have attached pictures of what I get (I am not a coder) please help?
![2021-03-10 (10)](https://user-images.githubusercontent.com/80386435/110600715-3d427900-8152-11eb-80e2-904e043c0896.png)

![2021-03-10 (9)](https://user-images.githubusercontent.com/80386435/110600732-42072d00-8152-11eb-86e6-93bb44f9b852.png)

**Comment by jgonzis** [comment]
That's normally a Driver Issue or OC Issue. I recommend you 1st of all to run 1.24a 

2nd which is your memory Modules of the GPU... you are probably pushing to high the memory clocks... Which values of OC are you using?

**Comment by johnnyseriuss** [comment]
![2021-03-10 (12)](https://user-images.githubusercontent.com/80386435/110683748-5d058b80-81aa-11eb-8ca3-373cac9912b0.png)
 
These are my overclock values, I saw some people running these number without issues and it looks like Im the only having them? I will download the alpha version of lolminer thank you all for the help

**Comment by johnnyseriuss** [comment]
One last thing! Im running windows do I need to download linux for 1.24a? I don't see it for windows only version 1.21

**Comment by SVGA-GA** [comment]
i have samu issue (gigabyte 5700xt gaming oc)

**Comment by jgonzis** [comment]
It is important to know if you have a Samsung Memory...  the Samsung Memory crash if normally is passed from 1770-1780...That could be the problem... a really high Memory. ...

**Comment by SVGA-GA** [comment]
![Uploading Снимок.PNG…]()

**Comment by SVGA-GA** [comment]
<img width="1917" alt="1" src="https://user-images.githubusercontent.com/80427413/110701141-78e44e00-81f9-11eb-8a85-0eeb176cf657.PNG">
my settings fo BEAM

**Comment by jgonzis** [comment]
> <img alt="1" width="1917" src="https://user-images.githubusercontent.com/80427413/110701141-78e44e00-81f9-11eb-8a85-0eeb176cf657.PNG">
> 
> my settings fo BEAM

Are you having problems with that config??

**Comment by SVGA-GA** [comment]
> > 
> > my settings fo BEAM
> 
> Are you having problems with that config??

only on a coin BEAM. for ETH i have other settings

**Comment by johnnyseriuss** [comment]
> It is important to know if you have a Samsung Memory... the Samsung Memory crash if normally is passed from 1770-1780...That could be the problem... a really high Memory. ...

How do I find out if the onboard graphics memory is Samsung? My machine is a pre-built from HP and Omen 25L to be exact. I have attached the spec sheets from HP


![55A138D6-4A04-4621-9D0E-FF09BFDE4E7E](https://user-images.githubusercontent.com/80386435/110704564-225c1d00-81c3-11eb-97f4-1d2045b6b176.jpeg)

**Comment by johnnyseriuss** [comment]
> > > my settings fo BEAM
> > 
> > 
> > Are you having problems with that config??
> 
> only on a coin BEAM. for ETH i have other settings

What settings you have for ETH? Thank you

**Comment by jgonzis** [comment]
> > It is important to know if you have a Samsung Memory... the Samsung Memory crash if normally is passed from 1770-1780...That could be the problem... a really high Memory. ...
> 
> How do I find out if the onboard graphics memory is Samsung? My machine is a pre-built from HP and Omen 25L to be exact. I have attached the spec sheets from HP
> 
> ![55A138D6-4A04-4621-9D0E-FF09BFDE4E7E](https://user-images.githubusercontent.com/80386435/110704564-225c1d00-81c3-11eb-97f4-1d2045b6b176.jpeg)

Use GPU-Z that will give you all the information..

**Comment by johnnyseriuss** [comment]
> > > It is important to know if you have a Samsung Memory... the Samsung Memory crash if normally is passed from 1770-1780...That could be the problem... a really high Memory. ...
> > 
> > 
> > How do I find out if the onboard graphics memory is Samsung? My machine is a pre-built from HP and Omen 25L to be exact. I have attached the spec sheets from HP
> > 
> 
> Use GPU-Z that will give you all the information..

Hey you are the best so this is my info? (see attached picture)

I don't see memory manufacture but I do see the manufacture is HP

![RX 5700](https://user-images.githubusercontent.com/80386435/110729498-d920c300-81ec-11eb-91d6-35b5ad5a2a90.gif)

**Comment by jgonzis** [comment]
In Linux you can know this information.  Well jus try to put in your OC max 1770 memory.  And see if it is stable. Then you will know is a Samsung

**Comment by SVGA-GA** [comment]
> > > > my settings fo BEAM
> > > 
> > > 
> > > Are you having problems with that config??
> > 
> > 
> > only on a coin BEAM. for ETH i have other settings
> 
> What settings you have for ETH? Thank you

<img width="1436" alt="2" src="https://user-images.githubusercontent.com/80427413/110746912-3a28b500-8246-11eb-8bea-0ad436a0dcda.PNG">

**Comment by jgonzis** [comment]
> > > > > my settings fo BEAM
> > > > 
> > > > 
> > > > Are you having problems with that config??
> > > 
> > > 
> > > only on a coin BEAM. for ETH i have other settings
> > 
> > 
> > What settings you have for ETH? Thank you
> 
> <img alt="2" width="1436" src="https://user-images.githubusercontent.com/80427413/110746912-3a28b500-8246-11eb-8bea-0ad436a0dcda.PNG">

If it crash in Ethereum change memory to 1770... if then don't crash ... you have a Samsung Memory in your card

**Comment by SVGA-GA** [comment]
> > > > > > my settings fo BEAM
> > > > > 
> > > > > 
> > > > > Are you having problems with that config??
> > > > 
> > > > 
> > > > only on a coin BEAM. for ETH i have other settings
> > > 
> > > 
> > > What settings you have for ETH? Thank you
> > 
> > 
> > 
> 
> If it crash in Ethereum change memory to 1770... if then don't crash ... you have a Samsung Memory in your card

i have Micron

**Comment by jgonzis** [comment]
> > > > > > > my settings fo BEAM
> > > > > > 
> > > > > > 
> > > > > > Are you having problems with that config??
> > > > > 
> > > > > 
> > > > > only on a coin BEAM. for ETH i have other settings
> > > > 
> > > > 
> > > > What settings you have for ETH? Thank you
> > 
> > 
> > If it crash in Ethereum change memory to 1770... if then don't crash ... you have a Samsung Memory in your card
> 
> i have Micron

Still to high for a Micron... normally max is 1860... or it should be less... if crash reduce OC it is normally the problem...

**Comment by SVGA-GA** [comment]
<img width="609" alt="3" src="https://user-images.githubusercontent.com/80427413/110906460-a40f9000-8314-11eb-96b3-927d55c9ae32.PNG">

**Comment by jgonzis** [comment]
Make a loop...  delete de the pause and put in the .bat file like this... then if it crash it will restart automaticly

:loop 
lolminer.exe --BEAM ...
goto loop

**Comment by SVGA-GA** [comment]
> Make a loop... delete de the pause and put in the .bat file like this... then if it crash it will restart automaticly
> 
> :loop
> lolminer.exe --BEAM ...
> goto loop

thx, you. i hope this helps me

**Comment by SVGA-GA** [comment]
i find for ETH this *.bat file. it's ok?
---------------------------------------
:loop
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto loop
)

pause

**Comment by Lolliedieb** [comment]
It is ok
