### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by djhajjar** [Lolliedieb/lolMiner-releases#353]
Fan speed seems to stay at about 80% then jumps to 120% for 2ish seconds. Is this safe for the gpu? I'm assuming this isn't normal. 

Nvidia GeForce RTX 2080 Ti

**Comment by jgonzis** [comment]
The fan speed is not controled from the Miner... it is done by the Card or by the 3rd party app that you are using... You should check which is the GPU temp more than the fan speed

**Comment by ROGF10** [comment]
Hi mate, what temperatures are we talking about? Your gpu will spin your fans faster because he thinks that the gpu will overheat to much. This happens mostly of the time when you're overclocking your gpu. I always turn my fans up to 85%. I have also a rtx 2080ti. Give some more information.

**Comment by djhajjar** [comment]
Temperature for it is just above 80C
