### ISSUE TITLE
how to up to 28m each card

### ISSUE THREAD

**Issue by grandfatheryun** [Lolliedieb/lolMiner-releases#354]
cpu g1820 1800mhz 4gbx2 z87x-ud3h
there  are 2 card 580 2048sp x2
i give it oc 1150 850 2000 850
but it just per 24. 06m card
how to get 28m each card
i am sure  it's  work in pcie3. 0x. 8 per card

**Comment by ROGF10** [comment]
Which cards do you have? Try to overclock your memory frequency to 2400 mhz with 900mv

**Comment by grandfatheryun** [comment]
> Which cards do you have? Try to overclock your memory frequency to 2400 mhz with 900mv 

580 4g 2048sp i have ，That's Samsung memory，but it's too high to the card. Maybe it's none of card but with the pcie speed or epoch 400 (because the high day)so it's need work on pcie3. 0x16,and I try that, it was working but not high, just 27. 5m. oh, i try it single card

**Comment by ROGF10** [comment]
You can't mine anymore like you should normaly do with 4gb cards. The dag size is over 4gb. You need to use mining os because windows uses more videoram than a mining os. But still you'll be not able to do this for a long period of time. You can try running the "mine eth 4g" file instead of the "mine eth"  file. I should sell these 4gb cards and buy some 8gb cards.

**Comment by grandfatheryun** [comment]
> You can't mine anymore like you should normaly do with 4gb cards. The dag size is over 4gb. You need to use mining os because windows uses more videoram than a mining os. But still you'll be not able to do this for a long period of time. You can try running the "mine eth 4g" file instead of the "mine eth"  file. I should sell these 4gb cards and buy some 8gb cards.

thanks for your suggestion. but at this  moment, it's to expensive for cards which can mining eth, so i wants use my 580 4g to mine eth at zombie mode, as the epoch add, ethash work on 4g card will more and more low, but it's think about in more than one mouth

**Comment by nylonW** [comment]
you can mine up to 25-26 rn with 4gb rx 580
