### ISSUE TITLE
Gigabyte RX6800 sensoring error

### ISSUE THREAD

**Issue by Netekss** [Lolliedieb/lolMiner-releases#355]
I have five RX6800 from Gigabyte. Sometimes the mine breaks down with error:
"Error in getting sensor data from AMD ADL library. Snesoring will be disable." 
After this error I have to reboot. Any solution? 

EDIT:
driver = Adrenaline 21.2.3
OS = Win10
lolMiner 1.21

**Comment by jgonzis** [comment]
> I have five RX6800 from Gigabyte. Sometimes the mine breaks down with error:
> "Error in getting sensor data from AMD ADL library. Snesoring will be disable."
> After this error I have to reboot. Any solution?
> 
> EDIT:
> driver = Adrenaline 21.2.3
> OS = Win10
> lolMiner 1.21

You should run 1.24a    and make a loop in the bat file:

:loop 
lolminer.exe --algo ....
timeout 10
goto loop

**Comment by Netekss** [comment]
> > I have five RX6800 from Gigabyte. Sometimes the mine breaks down with error:
> > "Error in getting sensor data from AMD ADL library. Snesoring will be disable."
> > After this error I have to reboot. Any solution?
> > EDIT:
> > driver = Adrenaline 21.2.3
> > OS = Win10
> > lolMiner 1.21
> 
> You should run 1.24a and make a loop in the bat file:
> 
> :loop
> lolminer.exe --algo ....
> timeout 10
> goto loop

But can I use 1.24a on Windows10?

**Comment by jgonzis** [comment]
Sorry I mistake...
