### ISSUE TITLE
All my .bat files are NOT WORKING

### ISSUE THREAD

**Issue by TheseImpressions** [Lolliedieb/lolMiner-releases#358]
I turned off windows defender, I have no other malware blockers, I put the files in my exclusion list, I gave myself admin uac and ran it as admin to no avail. 
![Screenshot (120)](https://user-images.githubusercontent.com/80651646/111086523-be469b00-84d9-11eb-9499-61cdb3e997e2.png)

**Comment by jgonzis** [comment]
> I turned off windows defender, I have no other malware blockers, I put the files in my exclusion list, I gave myself admin uac and ran it as admin to no avail.
> ![Screenshot (120)](https://user-images.githubusercontent.com/80651646/111086523-be469b00-84d9-11eb-9499-61cdb3e997e2.png)

you should deactivate Windows protection against the virus... that's normal with the mining always...
