### ISSUE TITLE
--devices argument not working on HiveOS

### ISSUE THREAD

**Issue by kingrasha** [Lolliedieb/lolMiner-releases#359]
I am running a mixed rig mining eth on 8gb amd cards using Teamredminer & rvn on 4gb amd cards using nbminer. I switched the 4gb amd cards over to Beamv3 using LOLminer on HiveOS but can not get the --devices argument to work. All my cards run on LOLminer and cause teamredminer to become stuck in a loop, continuously trying and failing to load the DAG on the 8gb cards for obvious reasons. 

Any help would be appreciated.

Edit: Using latest installs of HiveOS & LOLminer for linux

**Comment by jgonzis** [comment]
> I am running a mixed rig mining eth on 8gb amd cards using Teamredminer & rvn on 4gb amd cards using nbminer. I switched the 4gb amd cards over to Beamv3 using LOLminer on HiveOS but can not get the --devices argument to work. All my cards run on LOLminer and cause teamredminer to become stuck in a loop, continuously trying and failing to load the DAG on the 8gb cards for obvious reasons.
> 
> Any help would be appreciated.
> 
> Edit: Using latest installs of HiveOS & LOLminer for linux

IT works like this: --devices 3,4   that will run 3 and 4 of the rig

**Comment by Lolliedieb** [comment]
The devices argument is already used by Hive itself. Please select cards in your mining profile.
