### ISSUE TITLE
Combatibility error when using Lolminer on Vega FE's with Minerstat

### ISSUE THREAD

**Issue by xcongamma** [Lolliedieb/lolMiner-releases#36]
I have 8 Vega FE's trying to mine MWC using  Lolminer on Cuckatoo31 but im getting an error saying "Failed Compatibility check". I think Vega FE device id is not added to the miner codebase. Maybe it only checks for 56/64 id's?
![LOLMINER Failed Compatibility Check](https://user-images.githubusercontent.com/43177196/74869015-cc4cdb00-531c-11ea-8076-ade6fb3d6a85.png)

It's a Linux mining OS running v1.2 package that has 18.50 drivers

**Comment by Lolliedieb** [comment]
This should be fixed now with 0.9.8 - there was an issue with 19.50 driver thats now fixed. Please test.
