### ISSUE TITLE
BAT file changes for running multiple pc's

### ISSUE THREAD

**Issue by 1990Summer** [Lolliedieb/lolMiner-releases#360]
I started mining on a second pc but found out the original batch file has to be altered. I found batch file changes, but these are for runninig multiple cards in one pc. Can someone guide me? Or is it best to make a seperate wallet for every pc?

**Comment by jgonzis** [comment]
you should only add at the end of the line lolminer.exe the --devices 3,4 that will run for example devices 3 and 4

**Comment by 1990Summer** [comment]
So if I have four pc's it should be this? And than use the same file on each pc?

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit --devices 1,2,3,4

or should they be different files on each pc, like:
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit --devices 1
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit --devices 2
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit --devices 3
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit --devices 4

**Comment by pdieppa** [comment]
Some pools require (not many) that you identity each worker with a unique name. --rig allows you to do that.
Post your command line so we can check it out for you.

**Comment by jgonzis** [comment]
Check new bat files in last release
