### ISSUE TITLE
Low mh/s on rx580 4gb 

### ISSUE THREAD

**Issue by oraopapao** [Lolliedieb/lolMiner-releases#361]
this is what it says sorry im a bit of a newbie

+---------------------------------------------------------+
|    _       _ __  __ _                   _   ____  _     |
|   | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \/ |    |
|   | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) | |    |
|   | | (_) | | |  | | | | | |  __/ |    | |_ / __/| |    |
|   |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____|_|    |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|           Made by Lolliedieb, February 2021             |
+---------------------------------------------------------+

Setup Miner...
Device 0:
    Name:    Radeon RX 580 Series
    Address: 6:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  4096 MByte (4046 MByte free)
    --4g-alloc-size 4024
    Max epoch (approx): 375
    Active:  true (Selected Algorithm: ETHash)

Connecting to pool...
Connected to eth.2miners.com:2020  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker
New job received: 0xe0a0e5 Epoch: 401 Target: 000000007e000000
-------------------------------------------------------
         Generating light cache for epoch 401
-------------------------------------------------------
Start Mining...
New job received: 0x1bd79e Epoch: 401 Target: 000000007e000000
New job received: 0xa864a3 Epoch: 401 Target: 000000007e000000
-------------------------------------------------------
     Done (2048 ms), size of new DAG: 4232 MByte
-------------------------------------------------------
GPU 0: insufficient memory for DAG epoch 401.
GPU 0: will be in Zombie mode with reduced hashrate.

**Comment by oraopapao** [comment]
0 mh/s now gg guess my gpu is trash

**Comment by jgonzis** [comment]
I suppose you are in Windows... in windows is not possible to mine more with 4Gb... in Linux you can try it if you use a Gen3x16 connection. 

If you are in Windows you can try to mine ETC or BEAM, that can be done without problem.
