### ISSUE TITLE
Issue with running lolminer. "lolMiner.exe is not recognized as an internal or external command, operable program or batch file"

### ISSUE THREAD

**Issue by cryptominerdegen** [Lolliedieb/lolMiner-releases#364]
https://gyazo.com/e90e58010e7db080c40a7fd5a323068a

I have done everything correct from getting the server address, stratum port, wallet address etc. 

I turn off my antivirus too and still nothing.

Any ideas on how to fix?

**Comment by jgonzis** [comment]
As you can see he is trying to run lolminer in c:\windows\system32... put before the lolminer.exe in the bat file the complete directory:

c:\minerfolder\lolminer.exe --algo ....

That will help Windows to know where is your lolminer.exe

**Comment by Sicaruis** [comment]
@jgonzis where should I put that, I am solving same issue

**Comment by jgonzis** [comment]
> @jgonzis where should I put that, I am solving same issue

In the bat file. In mine_eth.bat where you change the wallet ... at the bottom appears lolMiner.exe --algo ETHASH ...

Before the lolMiner.exe

**Comment by Sicaruis** [comment]
So at the very bottom line?

**Comment by jgonzis** [comment]
> So at the very bottom line?

Yes just before the pause or timeout... it should appears the lolMiner.exe you should put before that lolMiner.exe the exact drive\folder of the file.

**Comment by Sicaruis** [comment]
Now I have it like that and still not working
V:\DEV\lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET!

**Comment by Sicaruis** [comment]
@jgonzis I am actually fucked now, I really don´t know anymore

**Comment by jgonzis** [comment]
Try it manually...

Execute CMD Administrator
Then
V:
cd DEV
lolminer.exe 

If file doesn't run then you don't have it... Windows virus protección...

If you the logo of lolminer then is the config file

**Comment by Sicaruis** [comment]
Not working, so I am probably gonna try to reinstall it right? @jgonzis

**Comment by Lolliedieb** [comment]
It could be your antivirus did delete the .exe?
