### ISSUE TITLE
GTX 1060 6gb & GTX 1660 SUPER 6gb not mining well together??

### ISSUE THREAD

**Issue by ROGF10** [Lolliedieb/lolMiner-releases#365]
So I bought last weekend 2 extra cards. I'm building a new rig. I have at this moment the following GPU's in my new rig:

AMD RADEON 580 8gb
GTX 1660 Super 6 gb GDDR6 (SAMSUNG)
GTX 1060 6 gb GDDR5 (MICRON)

When I run the GTX 1060 with the RX 580 or GTX 1660S with the RX 580. Everything is just perfect. Im pushing with the GTX 1660S over the 32 mh/s stable and with the GTX 1060 24 mh/s. But when I try to mine on them all at once or only the NVidia cards my hashrate is going down a lot. I do not why I am having this issue. 

Does anybody have any suggestions?

**Comment by jgonzis** [comment]
> So I bought last weekend 2 extra cards. I'm building a new rig. I have at this moment the following GPU's in my new rig:
> 
> AMD RADEON 580 8gb
> GTX 1660 Super 6 gb GDDR6 (SAMSUNG)
> GTX 1060 6 gb GDDR5 (MICRON)
> 
> When I run the GTX 1060 with the RX 580 or GTX 1660S with the RX 580. Everything is just perfect. Im pushing with the GTX 1660S over the 32 mh/s stable and with the GTX 1060 24 mh/s. But when I try to mine on them all at once or only the NVidia cards my hashrate is going down a lot. I do not why I am having this issue.
> 
> Does anybody have any suggestions?

You are trying to mine in Windows...

If you do it run 2 instances of lolminer  and put at the end in one --devices 0,1 and in the other --devices 2

Try to run in Windows one AMD with one Nvidia and the other alone...
That will solve your problem of half rate. And you will have full rate.

**Comment by jgonzis** [comment]
> So I bought last weekend 2 extra cards. I'm building a new rig. I have at this moment the following GPU's in my new rig:
> 
> AMD RADEON 580 8gb
> GTX 1660 Super 6 gb GDDR6 (SAMSUNG)
> GTX 1060 6 gb GDDR5 (MICRON)
> 
> When I run the GTX 1060 with the RX 580 or GTX 1660S with the RX 580. Everything is just perfect. Im pushing with the GTX 1660S over the 32 mh/s stable and with the GTX 1060 24 mh/s. But when I try to mine on them all at once or only the NVidia cards my hashrate is going down a lot. I do not why I am having this issue.
> 
> Does anybody have any suggestions?

You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems with multiple GPU.

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Fixed with 1.25 / 1.26
