### ISSUE TITLE
Hash rate cut in half

### ISSUE THREAD

**Issue by joejoerey24** [Lolliedieb/lolMiner-releases#366]
Hello,

I am a fairly new miner. When I installed my second gpu the hash rate was cut in half.
I have one 1660ti & 1070ti that each alone put out about 30/mhs. When they are both installed and running they are giving me only 30mh/s. I have an 850w psu so I don't think that is the issue. 

Please advise.
![Capture](https://user-images.githubusercontent.com/80725693/111235938-b4976300-85bf-11eb-8807-affd5d8dbe02.PNG)

**Comment by ROGF10** [comment]
Friend I am facing the same issue..... I Have a GTX 1660 Super & GTX 1060 both 6gb. If i plug in just one card everything is fine.... Your PSU is definitely not the issue because I'm running my rig with 2 PSU total power almost 1500w

**Comment by ROGF10** [comment]
Hi!

I think I just figured out why this shit is happening. Lolminer running on windows doesn't work at his best. Try to flash HiveOs on a USB-Flashdrive or SSD/HDD, after this you should create an account for HiveOs. After everything is set up you can choose Lolminer from the miners list. All of this is easy to do with the link below! The guy in the video will guide you step by step. I've been frustrating for a long time about why this happens. But this should fix your problem 100000% 

https://www.youtube.com/watch?v=3Pw87g8Kkiw

**Comment by jgonzis** [comment]
Just run 2 instances of lolminer

In one add the --devices 0 and in the other --devices 1

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 0
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices 1

**Comment by joejoerey24** [comment]
That worked, thanks!

**Comment by joejoerey24** [comment]
Running two instances worked, 

Thanks!
