### ISSUE TITLE
Can't mine cortex (CTXC / Cuckaroo30) on Nvidia GPU 1070?

### ISSUE THREAD

**Issue by Alexakis97** [Lolliedieb/lolMiner-releases#373]
[https://imgur.com/Zt9LNml](url)

**Comment by stevepresley** [comment]
I got the same error message when trying to mine on 1660Tis

**Comment by jgonzis** [comment]
> I got the same error message when trying to mine on 1660Tis

Cortex Need at least 8Gb to be mined... so with the 1660Ti you can not mined. The photo from the other failure I cannot see it

**Comment by Alexakis97** [comment]
@jgonzis  I've got 8GB of mem

**Comment by stevepresley** [comment]
Ah okay. A better error message would help in that case. 

>

**Comment by Alexakis97** [comment]
> Starting mining...

> All devices deselected or failed compatibility check. Closing lolminer

**Comment by Brooklyn5pointz** [comment]
Trying to run 2x 3070s and 2x 3060Ti (all 8gb)

On windows 10.  Get a failed error. Anyone have an idea?

**Comment by jgonzis** [comment]
Try new CUDA Solver from lolMiner 1.25, that should improve the Nvidia problems
