### ISSUE TITLE
Zhash crypto on AMD HD 7990 

### ISSUE THREAD

**Issue by KgsGrp** [Lolliedieb/lolMiner-releases#374]
How does nicehash get +45 sol /over 20 sol for each gpu) (algo Zhash) with an AMD HD7990 GPU using lol miner 1.21?
I downloaded this original version from gihub and ... start it ... it gives me a maximum of 21 sol (1 sol for each gpu).. with the exact same gpu

**Comment by jgonzis** [comment]
Can you put some screenshot?

**Comment by KgsGrp** [comment]
![7990](https://user-images.githubusercontent.com/50601065/112652651-e9bc7480-8e4d-11eb-87fe-70bb3134f01c.jpg)
I slightly lowered the frequencies of my gpu to keep the temperatures low. If reset it acts to over 45 sol / s

**Comment by Lolliedieb** [comment]
Maybe thats both cards combined? From the hardware ... no way of getting 42 when a single 580 doing 28 ...
