### ISSUE TITLE
Not showing RTX Titan 24GB and Misreading RTX 2070 8GB

### ISSUE THREAD

**Issue by BallowandSunder** [Lolliedieb/lolMiner-releases#38]
Is the lolminer able to take advantage of the RTX Titan. It won't show up in the miner at all.

I looked back on all the lolminer logs and no word of RTX Titan. Even Tromp said that RTX Titan would be ideal for mining C32. Any word on when lolminer will be able to utilize the 24GB of the RTX Titan (or 48 GB with NVLink) or other higher Titans like the Titan V JHH Special Edition 32GB?

Also its misreading RTX 2070 GB. @Lolliedieb 

![misreading 2070](https://user-images.githubusercontent.com/59857944/76160827-ada35e00-60ea-11ea-995f-6102705c9dc0.jpg)

**Comment by Lolliedieb** [comment]
For C31 more then 16G does not make sense - even the 16G solver utilizes only approx 14G. 
Why exactly the 2070 picks the 4G solver instead of 8G is mysterious. Is the screen connected to that one?

**Comment by Lolliedieb** [comment]
That said - for C32 a solver with 20G+ could make sense. Will need to think about how best to build one :)

**Comment by BallowandSunder** [comment]
@Lolliedieb No, the picture is of a different rig and does not have the titan in this one.. This rig just has a Vega 56 and a RTX 2070 in it but its misreading the 2070 for 4G, I have the lastest Nvidia drivers.
