### ISSUE TITLE
0 mh/s on 3 gpus???

### ISSUE THREAD

**Issue by Tacopaco5** [Lolliedieb/lolMiner-releases#383]
![20210321_002508](https://user-images.githubusercontent.com/79564354/111896231-970e3300-89dd-11eb-9653-a86d2d194f7a.jpg)

Hey everyone, 
So my miner detects my 4 gpus 2 RX580s and 2 RX590s, latest drivers have been installed, all are on compute mode, latest BIOs update, 4g settings in bios enabled, Allocated vurtual memory is 32,000 MB, and offered up the soul of my first born. 

Running a Gigabyte ga-h110-d3a, Intel I3, 2x 750w PSUs, 120gb Kigston SSD, 8gb Ram, and a hamster on a wheel.

Does anyone have any solutions or is experiencing the same thing?

**Comment by jgonzis** [comment]
That's really strange... can you try a tip only to confirm is working...

run 4 instances adding:
 --devices 0 
 --devices 1 
 --devices 2 
 --devices 3

So let's check what's happening... Also with a 4 GPU i really recommend you try a mining OS... like MMPOS is free and easy to use

**Comment by elShimmer** [comment]
Yeah, I just did an update an I'm experiencing a similar issue. 0.00m/h on 2 gpus. one a 3090

**Comment by jgonzis** [comment]
> ![20210321_002508](https://user-images.githubusercontent.com/79564354/111896231-970e3300-89dd-11eb-9653-a86d2d194f7a.jpg)
> 
> Hey everyone,
> So my miner detects my 4 gpus 2 RX580s and 2 RX590s, latest drivers have been installed, all are on compute mode, latest BIOs update, 4g settings in bios enabled, Allocated vurtual memory is 32,000 MB, and offered up the soul of my first born.
> 
> Running a Gigabyte ga-h110-d3a, Intel I3, 2x 750w PSUs, 120gb Kigston SSD, 8gb Ram, and a hamster on a wheel.
> 
> Does anyone have any solutions or is experiencing the same thing?

You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems with multiple GPU. It should work great

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
The Nvidia issue should be fixed with 1.25 / 1.26.
For the 4x amds please report the problem on individual GPUs.

**Comment by jgonzis** [comment]
No user answer...
