### ISSUE TITLE
Reduced hashrate on 4GB (Radeon RX570) card after system restart.

### ISSUE THREAD

**Issue by sorenn90** [Lolliedieb/lolMiner-releases#384]
running on manjaro, I was really happy to see I had hashrates of 18-19MHs on my AMD radeon RX570 using this command:
lolMiner --algo ETHASH --pool eth-eu2.nanopool.org:9999 --user <wallet-address> --4g-alloc-size 4076
 
This ran steadily even after the DAG-size change using zombie mode for a couple of days.

Yet after a system reboot I'm not able to reach the same hashrates (now it's 1-2 MHs) anymore for some unknown reason (tried changing the alloc-size from anywhere between 4072 - 4080 with no luck.

**Comment by sorenn90** [comment]
strangely enough, after retrying a couple of times it appears to work again now (back up to 18MHs). I've checked my bash history but the command is exactly the same:
lolMiner --algo ETHASH --pool eth-eu2.nanopool.org:9999 --user --4g-alloc-size 4076
Not sure what might cause this issue.

**Comment by jgonzis** [comment]
Sometimes depen on what you have connected... you can try lower 4072 too... It could be a crash for a new DAG... Y suppose after --user you are putting your eth wallet

**Comment by sorenn90** [comment]
Thank you @jgonzis for your answer. I can notice almost immediately when it's going to 'kick off' in zombie mode. I have to stop the miner and restart it. Sometimes the first reported hashrate is like 0.xx and when it's going to work normally, it goes straight to 3-4 and rises up to 19 on average.. Also, could it be that the miner stops once a new DAG is in place?
