### ISSUE TITLE
Running one RX 580 however two devices are showing up w/ low hash rates

### ISSUE THREAD

**Issue by itslegendary** [Lolliedieb/lolMiner-releases#385]
I am running an RX 580 and recently I noticed that two devices are showing up and only averaging around 4.8 mh/s. One is named device 0 and the other one is named device 1. Both show the same exact info about the rx 580. I recently only encountered this. I was only getting one device to show up and got average hash rates previously. I can post a SS if requested. Thanks

**Comment by jgonzis** [comment]
Which OS? how much memory Gb has that 580?...

**Comment by itslegendary** [comment]
Windows 10 and it's 8 gb xfx. Sorry should have been more specific and give as much details as possible. 

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 22, 2021 at 8:36 AM, ***@***.***> wrote:   


Which OS? how much memory Gb has that 580?...

**Comment by jgonzis** [comment]
I suppose you don't have active the compute mode... you can do it directly from Adrenaline driver or by parameter in Lolminer. 

You can follow this guide to change directly in Adrenaline: 

https://www.kryptex.org/es/articles/amd-compute-mode-en

**Comment by itslegendary** [comment]
I do use compute mode. I have attached a screenshot showing how when i first boot lolminer, it registers two gpus are mining however i only have one rx 580. The entire time it mines, its showing hash rates for two miners from the same gpu? 



![LolMiner](https://user-images.githubusercontent.com/81124416/112046744-a7233100-8b09-11eb-9cd5-17d655232383.png)

**Comment by MarcoGooseman** [comment]
I have also 2 gpus that are mining at only half the rate: 3060ti & 2060 super

**Comment by itslegendary** [comment]
See the thing is I only have one gpu but it's showing up as 2. 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 3, 2021 at 3:37 PM, ***@***.***> wrote:   


I have also 2 gpus that are mining at only half the rate: 3060ti & 2060 super

**Comment by Lolliedieb** [comment]
This is normally a driver error / bug.
Deep clean it and re-install.
