### ISSUE TITLE
cannot connect. time out error. pls help!

### ISSUE THREAD

**Issue by sghound** [Lolliedieb/lolMiner-releases#386]
Hi, i just setup for mining test, keep getting timeout errors. same results with all servers asia, eu, and usa. using lolminer1.21 with antivirus pass thru. any help would be much appreciated.

Connecting to pool...
timeout on connection attempt resolve. Retrying.
Lost connection to stratum server or server not reachable.
Trying to connect in 1 second.

keeps repeating.

![timeout](https://user-images.githubusercontent.com/81179809/112025414-1895ca80-8b70-11eb-83f7-b7879cff9558.PNG)

**Comment by jgonzis** [comment]
> Hi, i just setup for mining test, keep getting timeout errors. same results with all servers asia, eu, and usa. using lolminer1.21 with antivirus pass thru. any help would be much appreciated.
> 
> Connecting to pool...
> timeout on connection attempt resolve. Retrying.
> Lost connection to stratum server or server not reachable.
> Trying to connect in 1 second.
> 
> keeps repeating.
> 
> ![timeout](https://user-images.githubusercontent.com/81179809/112025414-1895ca80-8b70-11eb-83f7-b7879cff9558.PNG)

You have 2 problems...:

- An Internet problem connection 
- You cannot mine more with a 4Gb in Windows ETH... you should look for other coins like Beam or ETC.

**Comment by Lolliedieb** [comment]
This is a DNS problem. Please pick an other pool
