### ISSUE TITLE
LOLMiner on 2 separate systems, low reported hashrate

### ISSUE THREAD

**Issue by SomeGuy79** [Lolliedieb/lolMiner-releases#387]
I'm mining on two separate desktops (both Win 10) at the same time. I copied the miner (lolminer 1.21) from my desktop to my 2nd system and started mining. I should be having 28mh + 60mh, but "reported" hashrate is at 28mh only via ethermine.org.  Seems like the pool don't understand that it's two different computers. Do I need to change name or something on the miner I copied?

Pretty new to this, sorry in advance if I missing something obvious.

**Comment by jgonzis** [comment]
You can add :

--worker PC1 and in the other --worker PC2 that will give you the information... in the ethermine.org

**Comment by SomeGuy79** [comment]
> You can add :
> 
> --worker PC1 and in the other --worker PC2 that will give you the information... in the ethermine.org

Thank you for your reply.  Where do I add the --worker PC1 and --worker PC2, is this in the LOLMinter mine_eth.bat file that is running on each machine?  If so, where in the BAT file?

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=us2.ethermine.org:4444"
set "WALLET=0x1D32CBD5ac5640ACb140d9BbAF682e4xxxxxxxxxxx.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

:loop
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto loop
)

pause


Thanks again for any assistance, much appreciated!

**Comment by SomeGuy79** [comment]
Ok, I figured it out. In the line set "WALLET=0x1D32CBD5ac5640ACb140d9BbAF682e4xxxxxxxxxxx.lolMinerWorker"   The lolMinerWorker is the worker name, so you can change that to say lolMinerWorker001, and on the other machine lolMinerWorker002.

**Comment by jgonzis** [comment]
You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems with multiple GPU.

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Is fixed with 1.25 / 1.26

**Comment by dedizones** [comment]
Miner: lolminer-ver. 1.32 v.1.32a
Pool:

**Comment by jgonzis** [comment]
> Miner: lolminer-ver. 1.32 v.1.32a
> Pool: eu.crazypool.org
> port: 3333
> Extra config arguments:
> --ethstratum=ETHV1
> --watchdog off
> --workmulti 180
> --devices NVIDIA
> --mode b
> --rebuild-defect 5
> 
> I have "Reported 0.00 H" how to fix that ?
> 
> ![image](https://user-images.githubusercontent.com/58809062/133343333-08261850-2ae7-46e8-8411-ba70784f13fa.png)
> 
> Server: https://eth.crazypool.org/#/

Is not a problem of the pool... it only send the reported to the 1st connection
