### ISSUE TITLE
Ambiguous option in .bat file

### ISSUE THREAD

**Issue by Welsige** [Lolliedieb/lolMiner-releases#389]
Following error is given when executing file "mine_ae.bat" embedded in 1,21 windows build.

option '-a' is ambiguous and matches '--algo', and '--computemode'

**Comment by jgonzis** [comment]
> Following error is given when executing file "mine_ae.bat" embedded in 1,21 windows build.
> 
> option '-a' is ambiguous and matches '--algo', and '--computemode'

--algo and -a do the same ... you can choose what you want. It is only different ways to put the same...

**Comment by Welsige** [comment]
Yes but the executable raises an error when using the provided -a option. It should either accept the -a flag without error or the included .bat corrected to --algo.

**Comment by Lolliedieb** [comment]
Fixed with 1.26
