### ISSUE TITLE
How to uninstall the miner

### ISSUE THREAD

**Issue by Fredssoon** [Lolliedieb/lolMiner-releases#390]
I deleted the miner but I forgot to deactivate it, how do you turn off the miner once you have deleted it? Should you download the same miner again to be able to deactivate it?

**Comment by jgonzis** [comment]
> I deleted the miner but I forgot to deactivate it, how do you turn off the miner once you have deleted it? Should you download the same miner again to be able to deactivate it?

in which OS?... what do you want to deactivate?.

**Comment by Fredssoon** [comment]
lolMiner_v1.21_Win64.zip
On Windows. But I was not really sure if it worked, so i uninstalled it and deleted it from my computer. But now it seems to be active

**Comment by Lolliedieb** [comment]
Not miner related

**Comment by helloworldxdwastaken** [comment]
miner keeps itself active after uninstallign it ,u need to terminate the process , and yes , is miner related
