### ISSUE TITLE
RX 6700 XT err (Unsupported device or driver version)

### ISSUE THREAD

**Issue by coloradokb** [Lolliedieb/lolMiner-releases#391]
Please forgive my newbie-ignorance. I cannot understand why my 6700 xt isn't working. I see a message (Unsupported device or driver version). The nvidia 3070/3090 is running perfectly. I'm running amd driver 27.20.15003.1004. Please see attached image. Am I missing something obvious? Thank you!
![lol_err_6700_xt](https://user-images.githubusercontent.com/199652/112251107-3fabd500-8c20-11eb-9545-eb2979ca96bd.png)

**Comment by coloradokb** [comment]
Oh...this is mining ethereum (mine_eth.bat).

**Comment by jgonzis** [comment]
> Please forgive my newbie-ignorance. I cannot understand why my 6700 xt isn't working. I see a message (Unsupported device or driver version). The nvidia 3070/3090 is running perfectly. I'm running amd driver 27.20.15003.1004. Please see attached image. Am I missing something obvious? Thank you!
> ![lol_err_6700_xt](https://user-images.githubusercontent.com/199652/112251107-3fabd500-8c20-11eb-9545-eb2979ca96bd.png)

I think in next realease it will be avalaible... the mining for 6700xt... And I hope it will be soon

**Comment by jgonzis** [comment]
> Please forgive my newbie-ignorance. I cannot understand why my 6700 xt isn't working. I see a message (Unsupported device or driver version). The nvidia 3070/3090 is running perfectly. I'm running amd driver 27.20.15003.1004. Please see attached image. Am I missing something obvious? Thank you!
> ![lol_err_6700_xt](https://user-images.githubusercontent.com/199652/112251107-3fabd500-8c20-11eb-9545-eb2979ca96bd.png)

You can find the 1.25alpha with support for 6700 in the telegram group if you want it 😉

**Comment by jgonzis** [comment]
You can try new 1.25 Lolminer  that has the support 6700XT

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Fixed with 1.25 / 1.26
