### ISSUE TITLE
rx 580 4gb 16x zombie 22 MH pcı 1x slot 6 mh ? Is it a fixable situation?

### ISSUE THREAD

**Issue by ocelot34** [Lolliedieb/lolMiner-releases#394]
4gb 16x zombie 22 MH pcı 1x slot 6 mh ? Is it a fixable situation? if so we're excited for the next update
Thanx

**Comment by jgonzis** [comment]
> 4gb 16x zombie 22 MH pcı 1x slot 6 mh ? Is it a fixable situation? if so we're excited for the next update
> Thanx

It is really great at Gen3x16 or Gen3x8 or Gen2x16... if it goes by riser that it will godown... It will go step by step down ...

**Comment by Black6spdZ** [comment]
DAG swap to main memory needs all the PCIe bandwidth it can get.. no way in hell it will work out over the x1 risers

**Comment by Lolliedieb** [comment]
Sadly this can not be fixed - we need the host system & bus to complete shares in zombie mode. With x1 connection that will not work much faster at this epoch heights.
