### ISSUE TITLE
Core Dumped 

### ISSUE THREAD

**Issue by n3v3rm0r382** [Lolliedieb/lolMiner-releases#398]
Ubuntu 18.04
GeForce Quadro 6000
GeForce 1060 Ti

$ ./lolMiner --coin ETH --pool us1.ethermine.org --  port 4444 --user my_wallet_address.myrigname
+---------------------------------------------------------+
|  _       _ __  __ _                   _   ____  _  _    |
| | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \| || |   |
| | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) | || |_  |
| | | (_) | | |  | | | | | |  __/ |    | |_ / __/|__   _| |
| |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____|  |_|   |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|           Made by Lolliedieb, February 2021             |
+---------------------------------------------------------+

**Setup Miner...
Segmentation fault (core dumped)**

nvidia-smi
Thu Mar 25 13:32:52 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.141                Driver Version: 390.141                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   41C    P8    34W / 180W |    132MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro 6000         Off  | 00000000:03:00.0 Off |                  Off |
| 30%   49C   P12    N/A /  N/A |      2MiB /  6067MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1554      G   /usr/lib/xorg/Xorg                            56MiB |
|    0      1694      G   /usr/bin/gnome-shell                          73MiB |
+-----------------------------------------------------------------------------+

**Comment by jgonzis** [comment]
Could you try to run last Nvidia Drivers?...

**Comment by Lolliedieb** [comment]
Checked the last build of lolMiner with a proper CUDA interface?

**Comment by jgonzis** [comment]
No user answer...

**Comment by Onepamopa** [comment]
I'm also getting segmentation fault when trying to run, it even segfaults when calling --list-devices

**Comment by jgonzis** [comment]
> I'm also getting segmentation fault when trying to run, it even segfaults when calling --list-devices (prints the banner and crashes)

Which OS ? Which driver?

**Comment by Onepamopa** [comment]
Simplemining

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:10:00.0 Off |                  N/A |
| 95%   44C    P2   270W / 271W |   4900MiB / 12053MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:21:00.0 Off |                  N/A |
| 95%   43C    P2   270W / 271W |   4900MiB / 12053MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:25:00.0 Off |                  N/A |
| 95%   46C    P2   270W / 271W |   4900MiB / 12053MiB |     97%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:26:00.0 Off |                  N/A |
| 95%   46C    P2   270W / 271W |   4900MiB / 12053MiB |     99%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  On   | 00000000:27:00.0 Off |                  N/A |
| 95%   45C    P2   270W / 271W |   4900MiB / 12053MiB |     99%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  On   | 00000000:28:00.0 Off |                  N/A |
| 94%   44C    P2   270W / 271W |   4900MiB / 12053MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by Onepamopa** [comment]
So.. any news?

**Comment by jgonzis** [comment]
Strange because with that information it seems that they are mining... at 270W and also memory used

**Comment by Onepamopa** [comment]
@jgonzis yeah, using T-rex not lolminer. I wasn't about to leave the rig just sitting there crashing all the time.
