### ISSUE TITLE
Running 2 gpus

### ISSUE THREAD

**Issue by HabibiTheHacker** [Lolliedieb/lolMiner-releases#399]
If i want to run 2 gpus in one system, where and what command do i add to the bat file?

**Comment by jgonzis** [comment]
It will automatic take all the gpus... if you want to run some specific devices add at the line commands.

--devices 0,1,4 that will check 0,1 and 4

**Comment by jlope071** [comment]
Hello, I’m fairly new to mining. I’m running 2 gpus. But my hash rate is being halved once I added the second. 

My first gpu is the msi 2060 super. The hash rate was about 37. Once I added a gigabyte 2060 to the mix. My hash rate is at about 35 with both. And ethermine isn’t showing 2 workers. I noticed that my gpus were only running at maybe 50% and 35% respectively.  
 
I’m having trouble finding a reliable source for a fix for ethermine to show 2 workers. I’m not sure how to make sure my .bat file is configured correctly.

**Comment by jgonzis** [comment]
You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems with multiple GPU.

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Is fixed with 1.25 / 1.26
