### ISSUE TITLE
BSC address on miner! 

### ISSUE THREAD

**Issue by WyzPanda** [Lolliedieb/lolMiner-releases#400]
I am new to mining. I am mining ethereum using lolminer. I put bsc address on bat file when I started mining. I realized this after many days. Can anyone explain how can resolve this issue. Will I receive ethereum of my bsc address or not.

**Comment by jgonzis** [comment]
BSC Wallet?  You should put a ETH wallet... eth wallet is ERC20 ... not in BSC Chain... you will not receive it

**Comment by WyzPanda** [comment]
@jgonzis But I think in metamask we can change it. I have some balance on binance smart chain on the same address and it is showing equivalent dollar amount of ethereum in ethereum mainnett network in metamask.

**Comment by WyzPanda** [comment]
@jgonzis I also found one article on internet about this. https://support.edge.app/support/solutions/articles/8000090190-how-to-recover-funds-eth-and-ethereum-tokens-sent-to-the-binance-smart-chain-bsc- I dont know if this is true.
