### ISSUE TITLE
One of my gpu's won't start?

### ISSUE THREAD

**Issue by JonnyOrNot** [Lolliedieb/lolMiner-releases#401]
I have connected both my gpus to my setup and only one runs.
![image](https://user-images.githubusercontent.com/81499469/112741167-4ff6e380-8f83-11eb-8ed5-58f57573c7d1.png)
![image](https://user-images.githubusercontent.com/81499469/112741173-6dc44880-8f83-11eb-92d2-d7eab2eb6405.png)
![image](https://user-images.githubusercontent.com/81499469/112741176-82084580-8f83-11eb-8b1a-677c044a3ece.png)

**Comment by jgonzis** [comment]
It is normal...  the GTX 960 cannot mine ETH...

**Comment by jgonzis** [comment]
You can try new 1.25 Lolminer with special CUDA version great for Windows, for that RTX 2070. 

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Right ... the 960 does not have enough memory. What you can do is using the dual mine options to put the 2070 to eth and the 960 to ETC.
