### ISSUE TITLE
Nvidia Tesla M2090 Error 

### ISSUE THREAD

**Issue by Dcrain5454** [Lolliedieb/lolMiner-releases#403]
I have 8 M2090 cards, and I have this error any suggestions? Thank you

Setup Miner...
Device 0:
Name: Tesla M2090
Address: 1:0
Vendor: NVIDIA Corporation
Memory: 6082 MByte
Problem in loading kernel

**Comment by Lolliedieb** [comment]
The Tesla M2090 is very old (2011), at the moment I do not have a working kernel for it ...

**Comment by Dcrain5454** [comment]
Thank you very much for the reply. Do you know of any mining software that
supports this old card?

**Comment by Lolliedieb** [comment]
Can you pm me in Telegram? @Lolliedieb

**Comment by jgonzis** [comment]
No user answer ...
