### ISSUE TITLE
DAG Allocation not working without error message

### ISSUE THREAD

**Issue by MisterMaxymilian** [Lolliedieb/lolMiner-releases#404]
I recently installed 2 more cards onto my rig and now lolMiner 1.21 will not mine.  I set up my wallet and pool correctly.  When I went to go launch the miner, everything started up as normal except for the fact there were no DAG Allocation lines popping up.  It connected to the pool and went straight to mining.  Then whenever the mhs popped up I was getting zero on all cards.

The miner was working perfectly for the last month with 2 RX 580 and 1 GTX 1070 and I had absolutely no issues.  However when I installed the new cards It will not allocate DAG no matter what config I set it up in.  Has anyone else had this issue?   Can anyone please help me.

**Comment by jgonzis** [comment]
> I recently installed 2 more cards onto my rig and now lolMiner 1.21 will not mine. I set up my wallet and pool correctly. When I went to go launch the miner, everything started up as normal except for the fact there were no DAG Allocation lines popping up. It connected to the pool and went straight to mining. Then whenever the mhs popped up I was getting zero on all cards.
> 
> The miner was working perfectly for the last month with 2 RX 580 and 1 GTX 1070 and I had absolutely no issues. However when I installed the new cards It will not allocate DAG no matter what config I set it up in. Has anyone else had this issue? Can anyone please help me.

You can try new 1.25 Lolminer with special CUDA version great for Windows and Linux, and less problems. 

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Is fixed with 1.25 / 1.26

**Comment by MisterMaxymilian** [comment]
Thank you
