### ISSUE TITLE
No OpenCL error 6gb 1660Ti.

### ISSUE THREAD

**Issue by Skrabibo** [Lolliedieb/lolMiner-releases#405]
Hey everyone I've looked all the issues and followed the foodsteps but I can't run my gpus on Lolminer. Can someone help me about it? 
ps: I've the lastest driver setting.

**Comment by jgonzis** [comment]
Windows or Linux?. Which Driver version do you have?

**Comment by jgonzis** [comment]
> Hey everyone I've looked all the issues and followed the foodsteps but I can't run my gpus on Lolminer. Can someone help me about it?
> ps: I've the lastest driver setting.

You can try new 1.25 Lolminer with special CUDA version great for Windows and Linux, and less problems. 

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Should be fixed with 1.26
