### ISSUE TITLE
AMD Vega 7 and Vega 11 support from Ryzen CPU's.

### ISSUE THREAD

**Issue by emdskar2** [Lolliedieb/lolMiner-releases#410]
Hi! I dedicate 8Gb of RAM to my Ryzen 5 PRO 4650G videocard and start lolminer.
But it cant work with Vega videocard.
Can you add Vega from APU support?

**Comment by jgonzis** [comment]
> Hi! I dedicate 8Gb of RAM to my Ryzen 5 PRO 4650G videocard and start lolminer.
> But it cant work with Vega videocard.
> Can you add Vega from APU support?

It is complicated to mine with integrated GPU... you will not be able to do it

**Comment by emdskar2** [comment]
Performace of Vega 11 is 40% of RX570 performance. 
Why not?

**Comment by jgonzis** [comment]
Memory ... is not the same DDR4 than a GDDR5... for Gaming ok... not for mining sorry

**Comment by emdskar2** [comment]
With DDR4 performance is 40% from RX570 with GDDR5

**Comment by jgonzis** [comment]
> With DDR4 performance is 40% from RX570 with GDDR5

The 40% you talk is gaming not mining... You need dedicated GPU for mining ETH

**Comment by emdskar2** [comment]
It's only yours opinion.

**Comment by jgonzis** [comment]
> It's only your opinion.

DDR4 3200：25.6 GB/s
RX570 224 GB/s memory bandwidth 

Take your conclusions... but you can try always...

**Comment by Lolliedieb** [comment]
> Performace of Vega 11 is 40% of RX570 performance.
> Why not?

Well in gaming maybe. But the issues are
- The Vega IGPUs do use waaay less memory bandwidth. Only 1/10 of what the discrete GPUs have.
- Often IGPUs do only allow using 4G of memory. Few can do more - but if, then its often not worth it 

Overall it is not a good idea to mine with them. You burn way more electricity then you can earn.
