### ISSUE TITLE
not using full VRAM on ubuntu 20.04 (20.40 amdgpupro)

### ISSUE THREAD

**Issue by gptnooui** [Lolliedieb/lolMiner-releases#411]
I was trying to mine ETH on ubuntu 20.04 on my 4GB gpu but after i install the driver the miner (lolminer 1.24a) says it have less VRAM (100-500 less vram), so the hashrate is reduced (and the max epoch too) why this is happening?

**Comment by gptnooui** [comment]
Both the memory and the memory free are reduced i dont know why

**Comment by jgonzis** [comment]
> I was trying to mine ETH on ubuntu 20.04 on my 4GB gpu but after i install the driver the miner (lolminer 1.24a) says it have less VRAM (100-500 less vram), so the hashrate is reduced (and the max epoch too) why this is happening?

It is normal, is it used some space for the Linux driver... try if you have a Intel cpu with gpu ... to load the gpu of the cpu and let full free memory to the 4Gb card

**Comment by gptnooui** [comment]
> > I was trying to mine ETH on ubuntu 20.04 on my 4GB gpu but after i install the driver the miner (lolminer 1.24a) says it have less VRAM (100-500 less vram), so the hashrate is reduced (and the max epoch too) why this is happening?
> 
> It is normal, is it used some space for the Linux driver... try if you have a Intel cpu with gpu ... to load the gpu of the cpu and let full free memory to the 4Gb card

But on Windows it uses full VRAM (4096) and Hive OS and Rave OS too, why this happen only on ubuntu?

**Comment by Lolliedieb** [comment]
There is a difference between Windows and Linux in the way the amount of memory is reported.
Windows OpenCL driver: total memory = GPU total memory, free memory= whats left after Windows took some
Linux OpenCL driver: total memory almost equal to free memory = what is left after Linux took some for driver components.

In any way what the miner shows at startup is the amount the miner can realistically use. So well - if you want to use zombie mode ideally, you should run the graphics output over (Intel) CPU graphics.
