### ISSUE TITLE
RX580 fine, 5700xt not computing

### ISSUE THREAD

**Issue by dhershko2** [Lolliedieb/lolMiner-releases#412]
I just added a powercolor 5700xt, i see it in lspci, when i fire up lolMiner, i see it recognized (below), but never get a dag created and computing 0.00mh/s.   If i try to run with just the one device (5700), it does create the dag but always showing me 0.00mh/s.  any suggestions?  

Setup Miner... 
Device 0: 
    Name:    Radeon RX 580 Series 
    Address: 1:0 
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  7995 MByte (7976 MByte free) 
    Active:  false (not selected) 
Device 1: 
    Name:    AMD Radeon RX 5700 XT 
    Address: 7:0 
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  8176 MByte (8112 MByte free) 
    Max epoch (approx): 893 
    Active:  true (Selected Algorithm: ETHash)

**Comment by jgonzis** [comment]
Which is your OC?. Windows or Linux?...

**Comment by dhershko2** [comment]
Im on ubuntu 18.04,  amd drivers  20.40 (planning to  try 20.50 asap).   

noticed these in  dmesg:

[51023.896095] amdgpu 0000:01:00.0: GPU fault detected: 146 0x03c84404 for process lolMiner pid 2787 thread lolMiner pid 2787
[51023.896103] amdgpu 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00305679
[51023.896107] amdgpu 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04044004
[51023.896114] amdgpu 0000:01:00.0: VM fault (0x04, vmid 2, pasid 32787) at page 3167865, read from 'TC5' (0x54433500) (68)

**Comment by Lolliedieb** [comment]
No idea what is going on here, but the error you report are memory errors on the card. Lower memclock and relax undervolting.

**Comment by o-walid** [comment]
Hello if i can get some help or an issue with this situation 


![image](https://user-images.githubusercontent.com/99087565/152649211-8eeb0f25-10be-4f89-b454-6d883fd03021.png)
