### ISSUE TITLE
Gtx 1060 6 Gb and Radeon Vega 64 very low mh/s and a ghost gpu listed

### ISSUE THREAD

**Issue by philo2409** [Lolliedieb/lolMiner-releases#415]
HI guys,

Thank you for lolminer, it's great

I'm using it since a week with my gtx 1060 6 gb with an avarage 23.3 mh/s and everything worked fine

Now i've tried to add a Vega 64 (with an expected 40 mh/s) but it turn out to be only 4 mh/s

More strange is that now the miner says that there are 3 gpus. but there are only 2 

What am i doing wrong?
![IMG-5965](https://user-images.githubusercontent.com/81846875/113470177-d57f0580-9453-11eb-82e0-680776310d8f.jpeg)
![IMG-5964](https://user-images.githubusercontent.com/81846875/113470178-d879f600-9453-11eb-8f21-8ac81d8c8e00.jpeg)
![IMG-5961](https://user-images.githubusercontent.com/81846875/113470182-da43b980-9453-11eb-941e-438f1547730b.jpeg)

**Comment by Woor** [comment]
Use DDU to properly remove AMD drivers, then re-install AMD drivers. Should fix it.

**Comment by nickchitwood** [comment]
If you're using remote desktop, then it will detect the GPU in weird ways (The black background indicates that might be the case)

**Comment by jgonzis** [comment]
You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems. 

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Well this is AMD driver related.
As mentioned above it usually is a driver quirk. Best is to deep clean it and re-install the AMD driver. That fixes double detection of cards.
