### ISSUE TITLE
Halving Hash Rates 

### ISSUE THREAD

**Issue by jlope071** [Lolliedieb/lolMiner-releases#418]
I started mining with my MSI 2060 Super gpu with a hash rate of 41 mh/s after underclocking it. After installing a Gigabyte 2060 OC. My hash rate was cut in half. It was averaging about 35 mh/s. Ethermine after letting both cards run for over an hour was still only reflecting one user. 

I assume I may need to edit some files in the eth batch file. I cannot find what I would need to edit. Also, not entirely sure what a DAG file is but it is not being populated on my end. Thank you in advance.

**Comment by jgonzis** [comment]
I think the next realease will solve that problem... with the halve rate in Windows

**Comment by jgonzis** [comment]
> I started mining with my MSI 2060 Super gpu with a hash rate of 41 mh/s after underclocking it. After installing a Gigabyte 2060 OC. My hash rate was cut in half. It was averaging about 35 mh/s. Ethermine after letting both cards run for over an hour was still only reflecting one user.
> 
> I assume I may need to edit some files in the eth batch file. I cannot find what I would need to edit. Also, not entirely sure what a DAG file is but it is not being populated on my end. Thank you in advance.

You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems. 

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)

**Comment by Lolliedieb** [comment]
Is fixed with 1.25 / 1.26
