### ISSUE TITLE
Allocation of DAG failed with error: Memory object allocation failure

### ISSUE THREAD

**Issue by zangorila** [Lolliedieb/lolMiner-releases#419]
Hello i have Nvidia rtx 3070 and when i start it it says this error.

**Comment by jgonzis** [comment]
> Hello i have Nvidia rtx 3070 and when i start it it says this error.

Could you please put a photo to see what is the problem??

**Comment by jgonzis** [comment]
> Hello i have Nvidia rtx 3070 and when i start it it says this error.

You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems.

**Comment by Lolliedieb** [comment]
Should be fixed with 1.25 / 1.26 with new CUDA back end.
