### ISSUE TITLE
MWC-C29D on 4xVega 56 error !!!

### ISSUE THREAD

**Issue by ArSd-g** [Lolliedieb/lolMiner-releases#42]
I mine with 4xVega56 same bios 3xHynix memory 1xSamsung, Ubuntu 18.04/Amdgpu-pro 19.50.
It very frustrating: 3 hynix works good but vega/samsung always goes to 0 H/s with stuck device error after 10-15sec. I tried severel OC option from low to high, 2 bioses 64/56 = same result...
Using 1GB hugepages /48 (2 cpu nodes) than i upgraded it to 64...
Help Please!!!

**Comment by Lolliedieb** [comment]
Can you give your settings of the cards? Going to 0 g/s is an indicator for too low voltage for mem clk
