### ISSUE TITLE
Lost connection to stratum server zhash.eu.nicehash.com:3369 or server not reachable.

### ISSUE THREAD

**Issue by gocoelho** [Lolliedieb/lolMiner-releases#420]
**AMD Radeon R7 M260 2G** 
Seems like this problem mention on issue #108 is happeing again

←[1m←[38;2;100;149;237m+---------------------------------------------------------+
←[0m←[1m←[38;2;100;149;237m|←[0m    _       _ __  __ _                   _   ____  _     ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m   | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \/ |    ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m   | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) | |    ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m   | | (_) | | |  | | | | | |  __/ |    | |_ / __/| |    ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m   |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____|_|    ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m                                                         ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              This software is for mining                ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              Ethash, Etchash                            ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              Equihash 144/5, 192/7, 210/9               ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              BeamHash I, II, III                        ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              ZelHash     (EquihashR 125/4/0)            ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              Cuck(ar)oo 29                              ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              Cuckaroo   30 CTX                          ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m              Cuckatoo   31/32                           ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m                                                         ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m                                                         ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m|←[0m           Made by Lolliedieb, February 2021             ←[1m←[38;2;100;149;237m|
←[0m←[1m←[38;2;100;149;237m+---------------------------------------------------------+
←[0m
Setup Miner...
Device 0:
    Name:    ←[38;2;255;069;000mAMD Radeon R7 M260
←[0m    Address: 4:0
    Vendor:  Advanced Micro Devices (AMD)
    Memory:  2048 MByte (1998 MByte free)
    Active:  true (Selected Algorithm: Equihash 144/5 AMD)
Device 1:
    Name:    ←[38;2;000;000;205mIntel(R) HD Graphics 5500
←[0m    Address: 
    Vendor:  Intel(R) Corporation
    Memory:  6511 MByte
    Active:  false (not selected)

Connecting to pool...
←[38;2;240;230;140mConnected to zhash.eu.nicehash.com:3369  (TLS disabled)
←[0m←[38;2;240;230;140mSubscribed to stratum server
←[0m←[38;2;240;230;140mAuthorized worker: *********
←[0m←[38;2;240;230;140mNew target received: 00326bf67fddb0f4
←[0m←[38;2;189;183;107mNew job received: 00000000f809bf03 (BgoldPoW)
←[0mStart Mining...
Error in getting sensor data from AMD ADL library. Sensoring will be disabled
←[38;2;189;183;107mNew job received: 00000000f809bf04 (BgoldPoW)
←[0mAverage speed (30s): 0.4 sol/s
Average speed (30s): 1.0 sol/s
←[38;2;178;034;034mDevice 0 detected as crashed.
←[0m←[38;2;178;034;034mTaking no further action (--watchdog off).
←[0m←[38;2;189;183;107mNew job received: 00000000f809bf05 (BgoldPoW)
←[0mAverage speed (30s): 1.2 sol/s
←[38;2;240;230;140mNew target received: 003c3c3c3c000000
←[0mAverage speed (30s): 1.2 sol/s
←[38;2;255;165;000mLost connection to stratum server zhash.eu.nicehash.com:3369 or server not reachable.
←[0m←[38;2;255;165;000mTrying to connect in 1 second
←[0m←[38;2;240;230;140mConnected to zhash.eu.nicehash.com:3369  (TLS disabled)
←[0m←[38;2;240;230;140mSubscribed to stratum server
←[0m←[38;2;240;230;140mAuthorized worker: ***************************
←[0m←[38;2;240;230;140mNew target received: 00326bf67fddb0f4
←[0m←[38;2;189;183;107mNew job received: 00000000b1388c08 (BgoldPoW)
←[0m←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (23:19:36); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 2m 40s
←[0m←[38;2;100;149;237m                     ←[0m←[38;2;100;149;237m   GPU 0←[0m←[38;2;100;149;237m   Total←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mSpeed (sol/s):       ←[0m←[38;2;100;149;237m     1.0←[0m←[38;2;100;149;237m     1.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mBest Share:          ←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mShares (A/R):        ←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mPower (W):           ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mEfficiency (sol/s/W):←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mTemp (deg C):        ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mFan Speed (%):       ←[0m←[38;2;100;149;237m       0←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237m---------------------------------------------
←[0mAverage speed (30s): 1.2 sol/s
Average speed (30s): 1.3 sol/s
Average speed (30s): 1.2 sol/s
Average speed (30s): 1.0 sol/s
←[38;2;240;230;140mNew target received: 003c3c3c3c000000
←[0mAverage speed (30s): 1.2 sol/s
←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (23:22:06); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 5m 10s
←[0m←[38;2;100;149;237m                     ←[0m←[38;2;100;149;237m   GPU 0←[0m←[38;2;100;149;237m   Total←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mSpeed (sol/s):       ←[0m←[38;2;100;149;237m     1.1←[0m←[38;2;100;149;237m     1.1←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mBest Share:          ←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mShares (A/R):        ←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mPower (W):           ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mEfficiency (sol/s/W):←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mTemp (deg C):        ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mFan Speed (%):       ←[0m←[38;2;100;149;237m       0←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237m---------------------------------------------
←[0mAverage speed (30s): 1.0 sol/s
←[38;2;189;183;107mNew job received: 00000000b1388c09 (BgoldPoW)
←[0m←[38;2;255;165;000mLost connection to stratum server zhash.eu.nicehash.com:3369 or server not reachable.
←[0m←[38;2;255;165;000mTrying to connect in 1 second
←[0mAverage speed (30s): 1.1 sol/s
←[38;2;240;230;140mConnected to zhash.eu.nicehash.com:3369  (TLS disabled)
←[0m←[38;2;240;230;140mSubscribed to stratum server
←[0m←[38;2;240;230;140mAuthorized worker: ****************************
←[0m←[38;2;240;230;140mNew target received: 00326bf67fddb0f4
←[0m←[38;2;189;183;107mNew job received: 0000000047a7bcfb (BgoldPoW)
←[0m←[38;2;189;183;107mNew job received: 0000000047a7bcfc (BgoldPoW)
←[0mAverage speed (30s): 1.4 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bcfd (BgoldPoW)
←[0mAverage speed (30s): 0.9 sol/s
Average speed (30s): 1.2 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bcfe (BgoldPoW)
←[0m←[38;2;189;183;107mNew job received: 0000000047a7bcff (BgoldPoW)
←[0m←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (23:24:36); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 7m 40s
←[0m←[38;2;100;149;237m                     ←[0m←[38;2;100;149;237m   GPU 0←[0m←[38;2;100;149;237m   Total←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mSpeed (sol/s):       ←[0m←[38;2;100;149;237m     1.1←[0m←[38;2;100;149;237m     1.1←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mBest Share:          ←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mShares (A/R):        ←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mPower (W):           ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mEfficiency (sol/s/W):←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mTemp (deg C):        ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mFan Speed (%):       ←[0m←[38;2;100;149;237m       0←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237m---------------------------------------------
←[0mAverage speed (30s): 1.2 sol/s
←[38;2;240;230;140mNew target received: 003c3c3c3c000000
←[0mAverage speed (30s): 1.3 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd00 (BgoldPoW)
←[0mAverage speed (30s): 1.1 sol/s
Average speed (30s): 1.1 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd01 (BgoldPoW)
←[0mAverage speed (30s): 1.2 sol/s
←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (23:27:07); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 10m 10s
←[0m←[38;2;100;149;237m                     ←[0m←[38;2;100;149;237m   GPU 0←[0m←[38;2;100;149;237m   Total←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mSpeed (sol/s):       ←[0m←[38;2;100;149;237m     1.2←[0m←[38;2;100;149;237m     1.2←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mBest Share:          ←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mShares (A/R):        ←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mPower (W):           ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mEfficiency (sol/s/W):←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mTemp (deg C):        ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mFan Speed (%):       ←[0m←[38;2;100;149;237m       0←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237m---------------------------------------------
←[0mAverage speed (30s): 1.3 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd02 (BgoldPoW)
←[0mAverage speed (30s): 1.0 sol/s
Average speed (30s): 0.9 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd03 (BgoldPoW)
←[0mAverage speed (30s): 1.8 sol/s
Average speed (30s): 0.6 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd04 (BgoldPoW)
←[0m←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (23:29:37); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 12m 40s
←[0m←[38;2;100;149;237m                     ←[0m←[38;2;100;149;237m   GPU 0←[0m←[38;2;100;149;237m   Total←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mSpeed (sol/s):       ←[0m←[38;2;100;149;237m     1.1←[0m←[38;2;100;149;237m     1.1←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mBest Share:          ←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100;149;237m     0.0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mShares (A/R):        ←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100;149;237m     0/0←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mPower (W):           ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mEfficiency (sol/s/W):←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mTemp (deg C):        ←[0m←[38;2;100;149;237m    n.a.←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237mFan Speed (%):       ←[0m←[38;2;100;149;237m       0←[0m←[38;2;100;149;237m        ←[0m←[38;2;100
;149;237m
←[0m←[38;2;100;149;237m---------------------------------------------
←[0mAverage speed (30s): 1.0 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd05 (BgoldPoW)
←[0mAverage speed (30s): 1.2 sol/s
Average speed (30s): 1.0 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd06 (BgoldPoW)
←[0mAverage speed (30s): 0.9 sol/s
Average speed (30s): 1.3 sol/s
←[38;2;189;183;107mNew job received: 0000000047a7bd07 (BgoldPoW)
←[0m←[38;2;100;149;237m---------------------------------------------
←[0m←[38;2;100;149;237mStatistics (23:32:07); Mining: Equihash 144/5
←[0m←[38;2;100;149;237mConnected to: zhash.eu.nicehash.com:3369
←[0m←[38;2;100;149;237mUptime: 0h 15m 10s

**Comment by jgonzis** [comment]
It seems you have some internet problems... because with this log you are connected...

**Comment by gocoelho** [comment]
I'm connected but sometimes seems like I'm losing connection. My i7 CPU mining randomxmonero so much more than my AMD Radeon 2GB mining Zhash... both are in my laptop. my statistic with lolminer still doesn't make sense for me. It make sense for you?

they should go "up" together... but seems like it only go "up" when I restart mining and just one time. Even if I let the laptop mining more than 24h

![image](https://user-images.githubusercontent.com/7503127/113949542-e7f79700-97e5-11eb-9045-d50e105579e7.png)
![image](https://user-images.githubusercontent.com/7503127/113949969-96034100-97e6-11eb-9289-57227c8f00bb.png)

If the zhash stats are "correct", I'll probably stop mining with GPU

**Comment by gocoelho** [comment]
- I have 2 internet providers. Both with this "Lost connection"
- I tried to add exception on windows firewall and antivirus folder. Still with "Lost connection"
- I tried to shutdown windows firewall. Still with "Lost connection"
- I tried to open a ticket with nicehash team... let see how long for they're anwser

**Comment by gocoelho** [comment]
Nicehash answer: "Your hardware is too old." ¬¬

Do you know how I can solve the message "Error in getting sensor data from AMD ADL library. Sensoring will be disabled" for Windows 10?

**Comment by gocoelho** [comment]
Nicehash said my hardware wasn't listed as an official hardware. If you can't help me with the AMD ADL library or anything like that, you can close this issue @jgonzis . Thanks ;)

**Comment by jgonzis** [comment]
> Nicehash said my hardware wasn't listed as an official hardware. If you can't help me with the AMD ADL library on Windows 10 or anything like that, you can close this issue @jgonzis . Thanks ;)

Are you trying by nicehash application or directly from lolMiner bat file?. I think they said that too for the low Memory of the GPU... with that old card is better to avoid trying to mine.

**Comment by gocoelho** [comment]
> > Nicehash said my hardware wasn't listed as official hardware. If you can't help me with the AMD ADL library on Windows 10 or anything like that, you can close this issue @jgonzis . Thanks ;)
> 
> Are you trying by nicehash application or directly from lolMiner bat file?. I think they said that too for the low Memory of the GPU... with that old card is better to avoid trying to mine.

I'm trying from nicehash application. I don't know about the possibility from the bat file. And when I start mining, you can check my logs saying "Error in getting sensor data from AMD ADL library. Sensoring will be disabled". I'm not sure if this message will help to solve the situation, maybe don't. But when I use CPUID HWMonitor it's possible to check temperature, clock and voltage of GPU.

Thank you for your support, I'm still learning about the mining process.

**Comment by Lolliedieb** [comment]
That ADL error is either a driver error or the GPU crashed ... The R7 200M generation is indeed not officially supported. I am surprised it actually tries to work - but its neither energy efficient nor will it give any good return. Better use a discrete Desktop graphics and no IGPU

**Comment by Glazami** [comment]
Just add the line (--enable-ecip1099 on) in the baht file in the lolminer 
And the connection error disappears.
Adding this line helped to get rid of the message: Lost connection to stratum server nicehash.com or server not reachable. Trying to connect in 1 second
