### ISSUE TITLE
In this new miner hat same issue as in old miner

### ISSUE THREAD

**Issue by kavdav** [Lolliedieb/lolMiner-releases#422]
I am running an one RX 580 and recently I noticed that two devices are showing up and only averaging around 4.8 mh/s. One is named device 0 and the other one is named device 1. Both show the same exact info about the rx 580. I recently only encountered this. I was only getting one device to show up and got average hash rates previously. Thanks
![Posnetek zaslona 2021-04-07 140739](https://user-images.githubusercontent.com/82096313/113864080-c2996780-97aa-11eb-9da9-b07878e9fac6.png)

**Comment by jgonzis** [comment]
> I am running an one RX 580 and recently I noticed that two devices are showing up and only averaging around 4.8 mh/s. One is named device 0 and the other one is named device 1. Both show the same exact info about the rx 580. I recently only encountered this. I was only getting one device to show up and got average hash rates previously. Thanks
> ![Posnetek zaslona 2021-04-07 140739](https://user-images.githubusercontent.com/82096313/113864080-c2996780-97aa-11eb-9da9-b07878e9fac6.png)

Are you in Windows? Have you activate compute mode? 

[https://www.kryptex.org/es/articles/amd-compute-mode-en](https://www.kryptex.org/es/articles/amd-compute-mode-en
)

**Comment by kavdav** [comment]
I have a Windows 10 and i have alredy activated compute mode.I have attached how look the average hashrate.
![Posnetek zaslona 2021-04-07 150638](https://user-images.githubusercontent.com/82096313/113871162-e9f43280-97b2-11eb-896b-6d2833dcc737.png)

**Comment by jgonzis** [comment]
It is strange... people is mining without any problem with that, try to add the :  `--computemode` at the end of the bat file... 

Or try a Linux OS like MMPOS or HiveOS to be sure is not a Windows problem...

**Comment by ben219brown** [comment]
Miner is treating your card as 2 devices.

Edit your bat file so it reads lolminer.exe --devices 0

Then you will only mine on GPU 0 and have a hashrate closer to 64 consistently

**Comment by kavdav** [comment]
So?
![Posnetek zaslona 2021-04-07 155732](https://user-images.githubusercontent.com/82096313/113878864-46a71b80-97ba-11eb-90ac-d324ef36cc3a.png)

**Comment by jgonzis** [comment]
> So?
> ![Posnetek zaslona 2021-04-07 155732](https://user-images.githubusercontent.com/82096313/113878864-46a71b80-97ba-11eb-90ac-d324ef36cc3a.png)

After --watchdog exit add  --devices 0 --computemode

**Comment by kavdav** [comment]
Nothing changed
![Posnetek zaslona 2021-04-07 165416](https://user-images.githubusercontent.com/82096313/113887697-021f7e00-97c2-11eb-8f8b-cbd5b25fdaed.png)
![Posnetek zaslona 2021-04-07 165551](https://user-images.githubusercontent.com/82096313/113887894-28ddb480-97c2-11eb-8075-509c8c5f503e.png)

**Comment by jgonzis** [comment]
an space --devices 0 (you haven't put the space jejeje)

**Comment by kavdav** [comment]
Thank you for help, i'm really appreciate.

**Comment by jgonzis** [comment]
> Thank you for help, i'm really appreciate.

You are welcome :-)

**Comment by Lolliedieb** [comment]
While the --devices 0 thing is a workaround the bug is deeper. Usually having two cards shown (but there is only one) is a driver issue. Best is to completely wipe out the driver and to re-install that freshly.
