### ISSUE TITLE
Device 0 detected as crashed. Closing miner and trying to call external script: emergency.bat (--watchdog script)

### ISSUE THREAD

**Issue by srikarsai7** [Lolliedieb/lolMiner-releases#423]
i am mining beam and it shows the error message above for nvidia rtx 1060 but this doesnt happen while mining ethereum

**Comment by jgonzis** [comment]
> i am mining beam and it shows the error message above for nvidia rtx 1060 but this doesnt happen while mining ethereum

I think you need more Gb to mine Beam and Ethereum... you could try with the 3Gb for example ETC

**Comment by Lolliedieb** [comment]
Well on a 6G that might be.

But note: Beam uses a different algorithm that needs more relaxed oc & uv settings then Ethash
