### ISSUE TITLE
how to disable one gpu on lolminer

### ISSUE THREAD

**Issue by Pratikd19** [Lolliedieb/lolMiner-releases#424]
how can i disable one gpu between two,  because i need one gpu for work

**Comment by jgonzis** [comment]
You can use the --devices 0,1,2,4 

That will make that the GPU 3 is free to use for another utility...

**Comment by Pratikd19** [comment]
Yes i know that, but how to do that that is my question

**Comment by jgonzis** [comment]
> Yes i know that, but how to do that that is my question

You should edit the bat file you are using to launch the miner.... and then in the lolMiner.exe line at the end put it

**Comment by Pratikd19** [comment]
I know nothing about it, if you tell little bit in detail it will be helpful

**Comment by jgonzis** [comment]
> I know nothing about it, if you tell little bit in detail it will be helpful

How you put your wallet and pool?. In the mine_eth.bat right?.

After pool and wallet is a line that starts with lolminer.exe --algo ETHASH... at the end add the --devices information

**Comment by Pratikd19** [comment]
yes, thanks
