### ISSUE TITLE
Gpu error on new epoch starting 

### ISSUE THREAD

**Issue by berghemhack** [Lolliedieb/lolMiner-releases#425]
When new epoch starting I get always a GPU error and have to restart lolminer manually for each time.
I'm using lolminer  1.23 on ubuntu x86_64  20.04  with 3 gpu rx580 8gb + 1 rx550 4gb in zombie mode.
if I use the 1.24 it is worse and I encounter many more errors... 
I haven't tried the new 1.25 yet because 1.23 when it's not changing epoch is what gives me the best result.

**Comment by Lolliedieb** [comment]
This is likely due to the bug that was fixed between 1.23 and 1.24. Note that the hashrate the 550 is showing in 1.23 may not be real - so I advice to change to newer version

**Comment by berghemhack** [comment]
With release 1.25 from epoch 408 to 409 I got the same issue i had to restart miner on 2miners.com.
