### ISSUE TITLE
Bugs in linux shell scripts

### ISSUE THREAD

**Issue by kbs1** [Lolliedieb/lolMiner-releases#43]
```
#!/bin/bash

#################################
## Begin of user-editable part ##
#################################

POOL=asia-grin.2miners.com:3030
WALLET=
PASS=x

#################################
##  End of user-editable part  ##
#################################

cd "$(dirname "$0")"

./lolMiner --coin GRIN-C29M --pool $POOL --port $PORT --user $WALLET --pass $PASS $@
```
As we can see `$PORT` is used but this is not specified in user settings. Miner segfaults with host not found (authoritative) when connecting to pool. After `PORT=3030` is added and `:3030` is removed from `POOL` everything works fine.

**Comment by Lolliedieb** [comment]
Ah ... thanks for reporting.
I will clean up the scripts for the next release (soon :D )
