### ISSUE TITLE
Rx570 crashes. 

### ISSUE THREAD

**Issue by Molutecb** [Lolliedieb/lolMiner-releases#433]
Rx570 works only with low settings ( core-1050, mem 1800 maximum). Pcie 3.0, x16. Giving 16mh/s. And it crashes when I'm trying to apply higher settings

![PXL_20210411_221618230~2](https://user-images.githubusercontent.com/28713177/114324845-3504a180-9b35-11eb-8d45-054214299974.jpg)
![PXL_20210411_221709855](https://user-images.githubusercontent.com/28713177/114324848-3c2baf80-9b35-11eb-9d2a-b274a7dd18ad.jpg)
![Screenshot_20210412-021341](https://user-images.githubusercontent.com/28713177/114324851-40f06380-9b35-11eb-8a91-885e6dfb11f5.png)

**Comment by jgonzis** [comment]
Try :

**Comment by jgonzis** [comment]
Try : 1100 / 850 remove the 2nd 850, put the memory in 1750 and remove the 30.

**Comment by Molutecb** [comment]
> Try : 1100 / 850 remove the 2nd 850, put the memory in 1750 and remove the 30.
> If works the recommendation OC could be:
> 1150 / 880 / 1900 in memory and 16 in REF.

1st - ok but 14mh only. 
2nd- crashes and goes offline+ no signal at the monitor
![PXL_20210413_153129599](https://user-images.githubusercontent.com/28713177/114579804-e6ffb300-9c86-11eb-82b4-336916b5e889.jpg)

**Comment by Molutecb** [comment]
RaveOS shows 0mh from the start

**Comment by cryp-tog** [comment]
It's not mining at all, not even trying.  Interesting.  you're going to have a really hard time now with ETH on a 4Gb card, the DAG blew past 4Gb a long time ago, in crypto-years (like dog years, but more volatile).  You're going to need to seriously consider mining something else very shortly anyway, you may have squeezed the last life out of the ETH mining you're going to be able to get.  Ominus Dominus....

**Comment by Lolliedieb** [comment]
Generally I recommend to relax the oc / uv settings for Zombie mode a lot. Run it like 1200 core and 950 mV or so. It will need more energy then, but hopefully will be stable. Problem is: zombie mode kernels are different to normal ethash kernels. They need to do more work to mine at all and have more core heavy cycles. That is why often this cards crash when you run them with "old" settings that did work as long as the DAG still did fit into the memory.

**Comment by Molutecb** [comment]
Solved: changed alloc-size to 4000
