### ISSUE TITLE
Still can't use --pers auto

### ISSUE THREAD

**Issue by hbouma** [Lolliedieb/lolMiner-releases#435]
I am stuck with having to use --algo due to awesome miner and last September you said you'd fix --pers AUTO working for auto switching in the AM bitcointalk thread for 1.08. Well, its now April and --pers auto is still not accepted as a valid command in 1.25. Getting this fixed would be greatly appreciated. Thanks!

**Comment by Lolliedieb** [comment]
You are right - at the moment the only way of doing so is
--coin AUTO144_5
while the combination of
--algo EQUI144_5 --pers AUTO is broken
I will fix this.

**Comment by Lolliedieb** [comment]
Fixed and verified to work in 1.27 development build, thanks for reminding me (again).

**Comment by hbouma** [comment]
Awesome! Thanks!
