### ISSUE TITLE
1.26 in Windows "Access is denied" upon execution

### ISSUE THREAD

**Issue by ccl13** [Lolliedieb/lolMiner-releases#438]
1.25 has the issue of running at 0 hashrate without watchdog killing process. Upgraded to 1.26 and cannot start the process. 1.21 runs without issue.

**Comment by TorGj** [comment]
1.25 worked fine ... *
1.26 in Windows: "Access is denied"

**Comment by ccl13** [comment]
Hmm apparently Anti-virus thinks the 1.26 release contains "PUA:Win32/Caypnamer.A!ml" malware.
