### ISSUE TITLE
More info in the documentation regarding the built-in API

### ISSUE THREAD

**Issue by blackmennewstyle** [Lolliedieb/lolMiner-releases#439]
Hello,

I'm looking for some information about how to interact with the built-in API?

How to retrieve or even send information?

**Comment by khalaf8176** [comment]
I dont now

**Comment by blackmennewstyle** [comment]
I found it. You can retrieve information simply by making a request with the address and port you have to set with the command lines options. Example: --apihost 192.168.0.1 --apiport 5555

http://192.168.0.1:5555/ will generate a json with all statistics. Exactly what i need. Perfect :)
