### ISSUE TITLE
TLS in command line

### ISSUE THREAD

**Issue by Weaksfx** [Lolliedieb/lolMiner-releases#44]
I wanna use 2 different pools. one with TLS and another without. Miner stopped with this: `option '--tls' cannot be specified more than once`.

**Comment by Lolliedieb** [comment]
Thanks for the report.

Indeed currently its a toggle for tls on / off only ... 
When using the older json file format for configuration it will work with selection for each pool entry separately. 

I will try to make it possible to do so as well in cmd line in the next build :)

**Comment by Weaksfx** [comment]
Thanks
