### ISSUE TITLE
failed compatibility check

### ISSUE THREAD

**Issue by mostlyari** [Lolliedieb/lolMiner-releases#440]
![image](https://user-images.githubusercontent.com/82539722/114767436-9eeb9980-9d35-11eb-9c2c-98da5419e3ce.png)

Hi there!

I'm unable to mine due to failed compatibility check. I have an nvidia Quadro K4200 with 32GB of physical memory on a windows 10 64 bit PC. The driver on the nvidia graphics card is the most up to date R460 U6 version. I am not sure what to do to fi

lolminer seems to only be using the dedicated video memory, which is 4096MB, I'm not sure why. Any help I could get on fixing this so I can start mining would be very much appreciated! Please and thank you!

**Comment by cryp-tog** [comment]
Your machine RAM is not really used for mining, only the card RAM.  And as such, 4Gb is not enough to mine Ether, unfortunately.  Mine something else, might I suggest Beam?

**Comment by Lolliedieb** [comment]
Well the card would still be ok with stuff like ETC and other Ethash forks. At the moment I did not build kernels for Kepler cards yet, but will maybe do it for the next release. Noted.

**Comment by mostlyari** [comment]
I tried the mine_eth_4GB.bat but to no avail. Is it because mine is a kepler card? Please do add that, that would be great.

I'll look into ETC as well. Thank you.

**Comment by jgonzis** [comment]
Problem solved with 1.28a
