### ISSUE TITLE
Eth+Zil mining

### ISSUE THREAD

**Issue by Warlockx** [Lolliedieb/lolMiner-releases#442]
Hey, I was using t-rex miner and it would pre allocate the dag for zil, is it possible to do that with lolminer? Since its so little time of actual farming, building the dag before the time to farm would probably give a bit more time to farm.

**Comment by jgonzis** [comment]
> Hey, I was using t-rex miner and it would pre allocate the dag for zil, is it possible to do that with lolminer? Since its so little time of actual farming, building the dag before the time to farm would probably give a bit more time to farm.

You can add --enablezilcache to have the ZIL Cache... and if you want to use the dual mining option to be able to mine in a ETH Pool and ZIL in another POOL... you could have a look to the DUAL Mining manual.

[https://github.com/Lolliedieb/lolMiner-releases/wiki/Dual-Mining-&-Splitting-modes-(English)](https://github.com/Lolliedieb/lolMiner-releases/wiki/Dual-Mining-&-Splitting-modes-(English))

That is an example to mine in EZIL pool ZIL and ETH in 2Miners:

POOL=eu.ezil.me:5555
ZILWALLET=zil12kfcrls87pzqnneratejhk8xa3wdzlhrdl7w5g
ETHWALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f

ETHPOOL=eth.2miners.com:2020 
WORKER=lolMinerWorker

 --algo ETHASH --pool $POOL --user $ETHWALLET.$ZILWALLET --worker $WORKER  $@ --enablezilcache --dualmode zil --dualstratum $ETHWALLET@$ETHPOOL

**Comment by Warlockx** [comment]
thanks, it worked. it will save 1060 ms, which is not alot, but for me that doesnt have much mh/s it could be crucial for finding a share
