### ISSUE TITLE
New to mining, shares going stale 

### ISSUE THREAD

**Issue by GOB0T** [Lolliedieb/lolMiner-releases#443]
I'm new to mining and I have a problem that I can't figure out. The miner will receive new jobs, it rarely finds shares and when it does they go stale. I don't know what to do and I was wondering if someone could help me out with this. Also looking for info about optimizing my GPU (rtx3070). Thanks in advance 

![image](https://user-images.githubusercontent.com/82626460/114962525-6ed4f100-9e30-11eb-8190-5054e2fedfed.png)

**Comment by jgonzis** [comment]
> I'm new to mining and I have a problem that I can't figure out. The miner will receive new jobs, it rarely finds shares and when it does they go stale. I don't know what to do and I was wondering if someone could help me out with this. Also looking for info about optimizing my GPU (rtx3070). Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/82626460/114962525-6ed4f100-9e30-11eb-8190-5054e2fedfed.png)

I think I know where is your problem... you are trying to mine ETH but you are connected using --algo ETCHASH instead of ETHASH. 

You have a ETH pool selected but you mining ETC that will never workd...
