### ISSUE TITLE
2nd gpu causes a major drop in hashrate

### ISSUE THREAD

**Issue by SuperSoldier247** [Lolliedieb/lolMiner-releases#448]
I have been mining with just an RTX 3070 for a little under a month now and decided to add a single gpu(1060 6gb). I should have enough power to easily use both (EVGA 750W gold), however when I try to mine with both, both of them highly underperform. Each has their own power cable so I know thats not the problem. Any ideas??? I'm very new to mining so anything helps.

**Comment by jgonzis** [comment]
> I have been mining with just an RTX 3070 for a little under a month now and decided to add a single gpu(1060 6gb). I should have enough power to easily use both (EVGA 750W gold), however when I try to mine with both, both of them highly underperform. Each has their own power cable so I know thats not the problem. Any ideas??? I'm very new to mining so anything helps.

That happened with the old versions of lolminer with 1.25/1.26 that should be solved. Better try the last one.

**Comment by kytler** [comment]
same i have a 800w power supply and wont get the 100% out of any card, they both seem to work to hit a 100 together
2080 ti
1660 ti
![image](https://user-images.githubusercontent.com/83205857/116042459-0c4fd200-a634-11eb-9e5a-81304be3ef79.png)

**Comment by jgonzis** [comment]
> same i have a 800w power supply and wont get the 100% out of any card, they both seem to work to hit a 100 together
> 2080 ti
> 1660 ti
> ![image](https://user-images.githubusercontent.com/83205857/116042459-0c4fd200-a634-11eb-9e5a-81304be3ef79.png)

I think you are using an old version of lolMiner... Could you please try the lolMiner 1.26.

Version 1.25/1.26 solve that problem.

**Comment by kytler** [comment]
> > same i have a 800w power supply and wont get the 100% out of any card, they both seem to work to hit a 100 together
> > 2080 ti
> > 1660 ti
> > ![image](https://user-images.githubusercontent.com/83205857/116042459-0c4fd200-a634-11eb-9e5a-81304be3ef79.png)
> 
> I think you are using an old version of lolMiner... Could you please try the lolMiner 1.26.
> 
> Version 1.25/1.26 solve that problem.

Done, updated the version and got the full 91 mh/s, i thought it didn't have to go for it since I experienced no problems with older versions.

Thanks!
