### ISSUE TITLE
AMD Radeon VII: Error in getting sensor data from AMD ADL library

### ISSUE THREAD

**Issue by WSDS-Crypto** [Lolliedieb/lolMiner-releases#45]
Hi,

I am running lolMiner v1.0 using an AMD Radeon VII GPU and lolMiner is unable to read GPU sensor data, I receive the following error message:

"Error in getting sensor data from AMD ADL library. Sensoring will be disabled."

Thanks in advance!

**Comment by Lolliedieb** [comment]
Yea .. they seem to have changed something in ADL between Vega 1st gen and 2nd generation (VII) ... thats why temperature and other data currently can not be read for VII and Navi GPUs in Windows. 

I will look into that.

**Comment by WSDS-Crypto** [comment]
Thanks, mining works great! 

It would just be nice to see the GPU stats as well, hopefully it is an easy fix :)

**Comment by Lolliedieb** [comment]
This should be fixed in 1.02 and newer :) At least temperature and watts now :)
