### ISSUE TITLE
Speed 60m/hs however pool showing 0mh/s

### ISSUE THREAD

**Issue by Nickipz** [Lolliedieb/lolMiner-releases#451]
---------------------------------------------
Statistics (12:12:07); Mining: Ethash
Connected to: us2.ethermine.org:4444
Uptime: 0h 2m 30s
                       GPU 0   Total
Speed (mh/s):          56.34   56.34
**Pool (mh/s):            0.00    0.00**
**Best Share:              0.0     0.0**
Shares (A/S/Hw):       0/0/3   0/0/3
Power (W):             120.9   120.9
Efficiency (mh/s/W):   0.464   0.466
Temp (deg C):             54
Fan Speed (%):            61
---------------------------------------------

This is showing on my gaming pc im using lolminer with, my other pc gets 55mh/s in the pool line.

Why is this happening? - this miner doesnt show up on ethermine dashboard
![pool0](https://user-images.githubusercontent.com/82690175/115099642-61298380-9f76-11eb-890e-fa256e5f3aa3.png)

**Comment by jgonzis** [comment]
The 0 POOL is normal at the beginning and more when it only have mining 2min... At soon as shares are send it will go up. 

My question here which is your hardware?.  Now with last version 1.26 if you have 2 Nvidia you should be able to mine all in one miner, ..

**Comment by Lolliedieb** [comment]
With this number of defects definitely something is wrong with the dag. Try lower oc when the miner starts up.

**Comment by jgonzis** [comment]
No user answer...
