### ISSUE TITLE
Can't find lolminer.exe

### ISSUE THREAD

**Issue by Brickson95** [Lolliedieb/lolMiner-releases#452]
I downloaded the win64 version of the file, and when I use the BAT file I get "'lolminer.exe' is not recognized as an internal or external command, operable program or batch file." From what I understand I need to add the .exe directory to my BAT file, but I can't find the .exe anywhere, it's like it wasn't downloaded... please help!

**Comment by jgonzis** [comment]
> I downloaded the win64 version of the file, and when I use the BAT file I get "'lolminer.exe' is not recognized as an internal or external command, operable program or batch file." From what I understand I need to add the .exe directory to my BAT file, but I can't find the .exe anywhere, it's like it wasn't downloaded... please help!

That normally happen because the Windows Defender has blocked the file... Try to let the folder as an Exception for the windows Defender. 
Other problem is that you try to run it as Administrator, so when you run as Administrator is goes to the folder C:\Windows\System32 to look for lolminer.exe. So it is recommended that you modify the bat file and add before the line: lolminer.exe --algo ...
C:\folder_of_lol_miner\lolminer.exe --algo ...

That will make to search directly on the lolMiner folder.

**Comment by Gibswal** [comment]
> I downloaded the win64 version of the file, and when I use the BAT file I get "'lolminer.exe' is not recognized as an internal or external command, operable program or batch file." From what I understand I need to add the .exe directory to my BAT file, but I can't find the .exe anywhere, it's like it wasn't downloaded... please help!

Ok this happened to me, all I did was open the .rar file again and copied the lolminer.exe and pasted it back into the folder where I originally extracted to, it seemed to have been deleted due to windows defender thinking it was a Trojan since I did that it's not happened since.

**Comment by StingrayStrikes** [comment]
Hi, I have the same problem, I have tried both running as administrator and not as, changed the file path to make sure it locates the .exe and I've even added the file to my windows defender exceptions but still the same thing. please help, is there anything different I can do?

**Comment by jgonzis** [comment]
> Hi, I have the same problem, I have tried both running as administrator and not as, changed the file path to make sure it locates the .exe and I've even added the file to my windows defender exceptions but still the same thing. please help, is there anything different I can do?

The easy way... open a CMD as Administrator 
Go to de folder   cd Folder
Run the bat file
Then you are sure you are in the folder, you have run as Administrator and than lolminer.exe is not blocked by Windows Defender

**Comment by Gibswal** [comment]
> Hi, I have the same problem, I have tried both running as administrator and not as, changed the file path to make sure it locates the .exe and I've even added the file to my windows defender exceptions but still the same thing. please help, is there anything different I can do?

Just get the zip/rar file w.e it was and copy the lolminer.exe file to the folder where your bat file is and try running it again
