### ISSUE TITLE
Lolminer RTX 3080 freezing

### ISSUE THREAD

**Issue by HigherQuality** [Lolliedieb/lolMiner-releases#454]
While mining eth my 3080 randomly crashes, black screens then forces me to hard reset my system. I'm hitting any temp limits and I my overclock seems responsible. Can anyone help me set up a log file or know how i can resolve this issue. 

![image](https://user-images.githubusercontent.com/24234956/115161706-3110dc00-a06d-11eb-94bc-7843f0f52c28.png)

**Comment by jgonzis** [comment]
> While mining eth my 3080 randomly crashes, black screens then forces me to hard reset my system. I'm hitting any temp limits and I my overclock seems responsible. Can anyone help me set up a log file or know how i can resolve this issue.
> 
> ![image](https://user-images.githubusercontent.com/24234956/115161706-3110dc00-a06d-11eb-94bc-7843f0f52c28.png)

That is quite high in memory for a 3080 if this parameters are for Windows, normally people is around 650-900...  That crash is normally for a OC problem in the memory... or a go down from PSU or Windows crash too. 
Which lolMiner are you using now?.

**Comment by HigherQuality** [comment]
I'm on 1.25. I have an 850w power supply. I'll try to turn down my memory clock and report back.

**Comment by jgonzis** [comment]
> I'm on 1.25. I have an 850w power supply. It doesn't crash at the same time everyone its normally after running for over an hour. I'll try to turn down my memory clock and report back.

I recommend you to try the 1.26 that solves some epoch changes

**Comment by HigherQuality** [comment]
So far it looks like my memory clock was too high. Ty
