### ISSUE TITLE
SOCKS5 support?

### ISSUE THREAD

**Issue by BakeryD** [Lolliedieb/lolMiner-releases#455]
Can we get SOCKS proxy support, lolminer doesnt work that great with torsocks...

**Comment by tao593** [comment]
在中国已经封了IP，DOH已经不起作用了。socks5代理是一个很棒的解决方案。
【machine translation】：
IP has been blocked in China, and DOH has no effect.The socks5 proxy is a great solution.

**Comment by jgonzis** [comment]
1.39 Has Socks5 Support
