### ISSUE TITLE
Potentially unwanted app

### ISSUE THREAD

**Issue by hoskuldurjons** [Lolliedieb/lolMiner-releases#456]
I downloaded the lolminer and ran it without issue for a few days. At a certain point I experienced a Access Denied issue but found the solution in [#112 ](https://github.com/Lolliedieb/lolMiner-releases/issues/112). However, after using the recommended solution in that thread my windows defender is now warning me about this _Program:Win32/Uwamson.A!ml_ that is affecting _\lolminer_v1.26_win64.zip._

Has anyone had their windows defender flag this program before ? Can anyone confirm if its a malware or if its just windows defender thinking anything related to mining has nefarious intent ?

Thanks in advance.

**Comment by jgonzis** [comment]
> I downloaded the lolminer and ran it without issue for a few days. At a certain point I experienced a Access Denied issue but found the solution in [#112 ](https://github.com/Lolliedieb/lolMiner-releases/issues/112). However, after using the recommended solution in that thread my windows defender is now warning me about this _Program:Win32/Uwamson.A!ml_ that is affecting _\lolminer_v1.26_win64.zip._
> 
> Has anyone had their windows defender flag this program before ? Can anyone confirm if its a malware or if its just windows defender thinking anything related to mining has nefarious intent ?
> 
> Thanks in advance.

Windows always all miners advise them... is common that issue. Because they see connections to internet (the pools)... so they think normally they are virus.

**Comment by hoskuldurjons** [comment]
> > I downloaded the lolminer and ran it without issue for a few days. At a certain point I experienced a Access Denied issue but found the solution in [#112 ](https://github.com/Lolliedieb/lolMiner-releases/issues/112). However, after using the recommended solution in that thread my windows defender is now warning me about this _Program:Win32/Uwamson.A!ml_ that is affecting _\lolminer_v1.26_win64.zip._
> > Has anyone had their windows defender flag this program before ? Can anyone confirm if its a malware or if its just windows defender thinking anything related to mining has nefarious intent ?
> > Thanks in advance.
> 
> Windows always all miners advise them... is common that issue. Because they see connections to internet (the pools)... so they think normally they are virus.

Yes, I am aware that windows defender flags most miners. I'm more concerned with this specific program >Program:Win32/Uwamson.A!ml< and if anyone has had malware issues associated with it.

**Comment by jgonzis** [comment]
> > > I downloaded the lolminer and ran it without issue for a few days. At a certain point I experienced a Access Denied issue but found the solution in [#112 ](https://github.com/Lolliedieb/lolMiner-releases/issues/112). However, after using the recommended solution in that thread my windows defender is now warning me about this _Program:Win32/Uwamson.A!ml_ that is affecting _\lolminer_v1.26_win64.zip._
> > > Has anyone had their windows defender flag this program before ? Can anyone confirm if its a malware or if its just windows defender thinking anything related to mining has nefarious intent ?
> > > Thanks in advance.
> > 
> > 
> > Windows always all miners advise them... is common that issue. Because they see connections to internet (the pools)... so they think normally they are virus.
> 
> Yes, I am aware that windows defender flags most miners. I'm more concerned with this specific program >Program:Win32/Uwamson.A!ml< and if anyone has had malware issues associated with it.

If you have downloaded from the github repository you don't have to be worry about it...

**Comment by Lolliedieb** [comment]
This is normal for a mining software. Many engines react to it. I signed the windows exe file - make sure the signature is there, then its fine.
