### ISSUE TITLE
Allocating buffers failed with: clCreateBuffer (-61)?

### ISSUE THREAD

**Issue by lpw5783** [Lolliedieb/lolMiner-releases#457]
Hi, any comment on the above? Please help. Thanks

**Comment by Lolliedieb** [comment]
Can you provide what kind of card and algorithm is this?

**Comment by lpw5783** [comment]
![System Info](https://user-images.githubusercontent.com/82851906/115492557-8e3aa680-a294-11eb-8387-154a66ba8edc.png)

hope is the above info.

**Comment by lpw5783** [comment]
Phoenix Miner 5.3b Windows/msvc - Release build
-----------------------------------------------

No CUDA driver found
Unknown OpenCL driver version! Hashrate and stale shares may suffer
OpenCL platform: OpenCL 2.1 AMD-APP (3075.13)
Available GPUs for mining:
GPU1: AMD Radeon R7 M340 (pcie 1), OpenCL 2.0, 2 GB VRAM, 6 CUs
Eth: the pool list contains 1 pool (1 from command-line)
Eth: primary pool: etchash.unmineable.com:3333
Starting GPU mining
ADL Overdrive not supported on GPU1
ADL adapter index not found for GPU1
Eth: Connecting to ethash pool etchash.unmineable.com:3333 (proto: EthProxy)
Eth: Connected to ethash pool etchash.unmineable.com:3333 (128.199.154.204)
Listening for CDM remote manager at port 60080 in read-only mode
Eth: New job #117e850c from etchash.unmineable.com:3333; diff: 4000MH
GPU1: Starting up... (0)
GPU1: Generating etchash light cache for epoch #209
Light cache generated in 2.6 s (16.2 MB/s)
GPU1: Using generic OpenCL kernels (device name 'Iceland')
Eth: New job #972e8187 from etchash.unmineable.com:3333; diff: 4000MH
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
GPU1: Free VRAM: 1.952 GB; used: 0.048 GB
GPU1: Allocating DAG for epoch #209 (2.63) GB
GPU1: Allocating buffers failed with: clCreateBuffer (-61).
Fatal error detected. Restarting.


hope the above will help. thanks

**Comment by Lolliedieb** [comment]
Sry, but this is lolMiner support, not Phoenix miner.

But generally: you can not mine Eth with a 2G mobile GPU. It needs a desktop discrete GPU with at least 6G memory at the moment.
