### ISSUE TITLE
BEAM- More than 4 GPU's on one rig= "OpenCL init failure: Memory object allocation failure" Active: False

### ISSUE THREAD

**Issue by cryp-tog** [Lolliedieb/lolMiner-releases#458]
I've tried this on two different rigs, two different locations, my buddy has a fresh build with 7 1050TI's (4Gb RAM): fresh install of W10, fresh SSD, fresh mining mobo, fresh 8Gb DDR3 1600 RAM.  Still seeing the same problem.  I'd chalked it up to old nasty hardware, or a glitch in Windows, but it's not.  W10 sees all the cards, DM looks good, but lolMiner won't activate the last few cards for some reason.  My buddy has more cards coming, but they're all 4Gb cards.

Tried:
- 1.21
- 1.25 mode a and b
- 1.26 mode a and b
- keepfree 256 (just in case?)
- Swapping cards around to make sure it wasn't the cards or the mobo, but we've seen this across other rigs as well
- Reducing core and mem clocks, adding voltage, just in case an aggressive BIOS had been applied to the cards prior
- Increasing Virtual Memory to 16Gb

I've tried everything I can think of, HELP?!?!?

![Capture](https://user-images.githubusercontent.com/82237817/115476376-5b969c80-a207-11eb-8ebf-8a296a6f7acd.PNG)

**Comment by cryp-tog** [comment]
Oh, also- I dumbed down the core and mem clocks and made sure the cards are getting enough power via Afterburner, just to make sure- still no good.

**Comment by jgonzis** [comment]
Have you got active 4G Encode on in the BIOS?

**Comment by cryp-tog** [comment]
BIOS hasn't been modified to my knowledge.  However, we did JUST seem to get these running, I had them put their page file to 32GB and it seems to be running.  Need to see if it actually holds or if it crashes, keep y'all posted.

**Comment by RunOrDrink** [comment]
I think  you should increase your page file to a high amount of gb, like 32gb. Restart pc and see if it works
