### ISSUE TITLE
LolMiner doesn't find a share when mining BeamIII on NiceHash

### ISSUE THREAD

**Issue by luc1an24** [Lolliedieb/lolMiner-releases#46]
Hi
When trying to mine BeamIII on NiceHash no shares are found
Following set of parameters was used: ./lolMiner.exe --algo BEAM-III --pool beamv3.eu.nicehash.com:3387 --user !Wallet! --tls 0
Could you please check why this is happening so we can have your miner integrated for the time of new fork?
Thank you very much!

**Comment by luc1an24** [comment]
It looks like the no response is given to the messages:
`{"method":"login","api_key":"3P4ahzNBJB822puM3NqMjZh1brdSkGPSfw.testRun","id":"login","jsonrpc":"2.0"}
{"code":0,"description":"Login successful","id":"login","jsonrpc":"2.0","nonceprefix":"0101732534","method":"result"}
{"jsonrpc":"2.0","method":"job","id":"3745456021","input":"9e3585bc632ebc9feb7bd3a4ec4581acdac4b89f83a36f55a734dd536c6ef87b","difficulty":173932544,"nonceprefix":"0101732534"}
{"jsonrpc":"2.0","method":"job","id":"3745456022","input":"05d8fcbddcd53c66dd402da369af13031cc9695f64f4fd7f80338ad67f3b2fdf","difficulty":173932544,"nonceprefix":"0101732534"}
{"jsonrpc":"2.0","method":"job","id":"3745456025","input":"e9c8fd4d8c6fd45ac931b0335b36e610f1758a8457c637b7eb9787dcc65c1456","difficulty":173932544,"nonceprefix":"4000020e4c"}
`

**Comment by Lolliedieb** [comment]
The pool seems to send a nonceprefix that is outside of the Beam spec. Please send maximum 6 bytes as for Beam Hash 2, then it will work fine.

**Comment by Lolliedieb** [comment]
The pool seems to send a nonceprefix that is outside of the Beam spec. Please send maximum 6 bytes as for Beam Hash 2, then it will work fine.

**Comment by Lolliedieb** [comment]
Reopened to await comment :)

**Comment by Lolliedieb** [comment]
Will be fixed with 1.01.
