### ISSUE TITLE
lolMiner crashes

### ISSUE THREAD

**Issue by Maxnflaxl1O** [Lolliedieb/lolMiner-releases#460]
the miner crashes pretty often ( in 8h Mining about 4 times ) 
i cant see an error or anything its just the pause in the batch file. 
( Press any key to contine . . . )

**Comment by cryp-tog** [comment]
at the very top of the script add ":start" and then before the "pause" add, "goto start"

:start
miner batch script stuff
goto start
pause

**Comment by Maxnflaxl1O** [comment]
thanks!
