### ISSUE TITLE
Lost connection bug

### ISSUE THREAD

**Issue by hackhy** [Lolliedieb/lolMiner-releases#461]
![image](https://user-images.githubusercontent.com/1840844/115518398-b0471f80-a2ba-11eb-9b0f-41ab619840c2.png)

Program reconnect many times, but I can connect pool by telnet, I CTRL+C restart mining bat file and I works.
Is there any bug when network unstabitily?  May be program can restart kernel after reconnect  many times?

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/1840844/115518398-b0471f80-a2ba-11eb-9b0f-41ab619840c2.png)
> 
> Program reconnect many times, but I can connect pool by telnet, I CTRL+C restart mining bat file and I works.
> Is there any bug when network unstabitily? May be program can restart kernel after reconnect many times?

You are connecting to China Server... Are you in China? If not it is recommended to mine to a near Server :


Europe	eth-eu.sparkpool.com	3333	
US	eth-us.sparkpool.com	3333	
Southeast Asia	asia.sparkpool.com	3333	
Korea	kr.sparkpool.com	3333	
Japan	jp.sparkpool.com	3333
