### ISSUE TITLE
reconnects every 30 seconds when no new job is received

### ISSUE THREAD

**Issue by Rom1kz** [Lolliedieb/lolMiner-releases#462]
lolMiner 1.26 now can't wait for a new job more than 30 seconds
there is many coins exists where block time much more than 30 sec
DBIX, TSF.. even ZIL - POW window lasts 60+ seconds

how can i manage job timeout to eliminate reconnects ?

![изображение](https://user-images.githubusercontent.com/34973778/115535449-6e5daf80-a2a1-11eb-9971-8cb7fe474ee6.png)

**Comment by cryp-tog** [comment]
Use a different pool?  Also- nice rig!!  I've heard flypool/ethermine is really good, also super fast (low ms round trip).

**Comment by jgonzis** [comment]
> lolMiner 1.26 now can't wait for a new job more than 30 seconds
> there is many coins exists where block time much more than 30 sec
> DBIX, TSF.. even ZIL - POW window lasts 60+ seconds
> 
> how can i manage job timeout to eliminate reconnects ?
> 
> ![изображение](https://user-images.githubusercontent.com/34973778/115535449-6e5daf80-a2a1-11eb-9971-8cb7fe474ee6.png)

that and Internet Problem and miner try to solve it reconnecting...

**Comment by Rom1kz** [comment]
> that and Internet Problem and miner try to solve it reconnecting...

nope, when i use old 1.17 version the problem is not present

**Comment by jgonzis** [comment]
That is solved with the 1.28a that increase the time of jobs until 150s
