### ISSUE TITLE
Lost connection bug

### ISSUE THREAD

**Issue by denglt** [Lolliedieb/lolMiner-releases#463]
PS D:\lolMiner\1.26> .\mine_eth_4G.bat
+---------------------------------------------------------+
|  _       _ __  __ _                   _   ____   __     |
| | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \ / /_    |
| | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) | '_ \   |
| | | (_) | | |  | | | | | |  __/ |    | |_ / __/| (_) |  |
| |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____|\___/   |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|             Made by Lolliedieb, April 2021              |
+---------------------------------------------------------+

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    Intel(R) UHD Graphics 620
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  3215 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to ethash.unmineable.com:3333  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Lost connection to stratum server ethash.unmineable.com:3333 or server not reachable.
Trying to connect in 1 second
Connected to ethash.unmineable.com:3333  (TLS disabled)
Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.
Set Ethash stratum mode: EthereumStratum/1.0.0
Lost connection to stratum server ethash.unmineable.com:3333 or server not reachable.
Trying to connect in 1 second
Connected to ethash.unmineable.com:3333  (TLS disabled)
Immediately lost connection on EthereumStratum/1.0.0 (Nicehash) stratum mode. Reconnect attempt will try ETHPROXY stratum mode.
Set Ethash stratum mode: Ethereum Proxy
Lost connection to stratum server ethash.unmineable.com:3333 or server not reachable.
Trying to connect in 1 second

Bug I can telnet command  with "elnet  ethash.unmineable.com 3333"  sucessfully.

**Comment by jgonzis** [comment]
> PS D:\lolMiner\1.26> .\mine_eth_4G.bat
> +---------------------------------------------------------+
> | _ _ __ __ _ _ ____ __ |
> | | | ___ | | / (_)_ __ ___ _ __ / | |___ \ / /_ |
> | | |/ _ | | |/| | | '_ \ / _ \ '__| | | __) | '_ \ | | | | (_) | | | | | | | | | __/ | | |_ / __/| (_) | | | |_|___/|_|_| |_|_|_| |_|___|_| |_(_)___**|_**/ |
> | |
> | This software is for mining |
> | Ethash, Etchash |
> | Equihash 144/5, 192/7, 210/9 |
> | BeamHash I, II, III |
> | ZelHash (EquihashR 125/4/0) |
> | Cuck(ar)oo 29 |
> | Cuckaroo 30 CTX |
> | Cuckatoo 31/32 |
> | |
> | |
> | Made by Lolliedieb, April 2021 |
> +---------------------------------------------------------+
> 
> Setup Miner...
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 1
> No Cuda driver or GPUs detected.
> Device 0:
> Name: Intel(R) UHD Graphics 620
> Address: 4294967295:4294967295
> Vendor: Intel(R) Corporation
> Drivers: OpenCL
> Memory: 3215 MByte
> Active: false (not selected)
> 
> Connecting to pool...
> Connected to ethash.unmineable.com:3333 (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Lost connection to stratum server ethash.unmineable.com:3333 or server not reachable.
> Trying to connect in 1 second
> Connected to ethash.unmineable.com:3333 (TLS disabled)
> Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.
> Set Ethash stratum mode: EthereumStratum/1.0.0
> Lost connection to stratum server ethash.unmineable.com:3333 or server not reachable.
> Trying to connect in 1 second
> Connected to ethash.unmineable.com:3333 (TLS disabled)
> Immediately lost connection on EthereumStratum/1.0.0 (Nicehash) stratum mode. Reconnect attempt will try ETHPROXY stratum mode.
> Set Ethash stratum mode: Ethereum Proxy
> Lost connection to stratum server ethash.unmineable.com:3333 or server not reachable.
> Trying to connect in 1 second
> 
> Bug I can telnet command with "elnet ethash.unmineable.com 3333" sucessfully.

It is an internet problem, also to avoid trying more configuration, you will not be able to mine with an Integrated GPU, in this case the GPU of the Intel CPU.
