### ISSUE TITLE
Slowed down the mh/s

### ISSUE THREAD

**Issue by Jose10Espinoza** [Lolliedieb/lolMiner-releases#464]
Update 1.26 reduced my hash rate from 31.52 to 30.95-99![image](https://user-images.githubusercontent.com/12351274/115690842-4d817280-a312-11eb-971d-95b2b9a9ad51.jpeg)
![image](https://user-images.githubusercontent.com/12351274/115691107-9507fe80-a312-11eb-9102-0a0433aa3597.jpeg)

**Comment by jinglei207** [comment]
same here. from 19.6 to 19.1

**Comment by pdieppa** [comment]
You are only allowing the program to hash for a little over 1 minute. You need to let it run for longer to see what the hashrate is. Also, look at the pool for the actual hashrate.

Good luck

**Comment by jgonzis** [comment]
All Pascal goind down with EPOCH increase...
