### ISSUE TITLE
Am I able to integrate this into a programming language such as Rust?

### ISSUE THREAD

**Issue by Joe23232** [Lolliedieb/lolMiner-releases#465]
Hi I wanted to know is it possible for me to use it as a library and integrate it into my [Rust](https://www.rust-lang.org/) programming code that way I can then integrate it into one single executable?

Also is this supported on AMD graphics cards?

**Comment by jgonzis** [comment]
> Hi I wanted to know is it possible for me to use it as a library and integrate it into my [Rust](https://www.rust-lang.org/) programming code that way I can then integrate it into one single executable?
> 
> Also is this supported on AMD graphics cards?

You can use the command line to generate to start and read in the API the parameters...

**Comment by jgonzis** [comment]
No problem or feedback... close issue
