### ISSUE TITLE
580 8gb Win64 0 MH/s

### ISSUE THREAD

**Issue by Tris10w** [Lolliedieb/lolMiner-releases#467]
Haven't noticed an issue in a while, but recently, I have been getting 0 MH/s with all my RX 580s on Windows OS. 1.26 seems to be having the same issue, whereas ETC is operating as normal. Anyone else experiencing a similar issue?

**Comment by jgonzis** [comment]
> Haven't noticed an issue in a while, but recently, I have been getting 0 MH/s with all my RX 580s on Windows OS. 1.26 seems to be having the same issue, whereas ETC is operating as normal. Anyone else experiencing a similar issue?

Can you put a photo... ?

**Comment by Tris10w** [comment]
To verify what? What information are you looking for in the photo? Are there certain debugging options to enable that could assist?

**Comment by jgonzis** [comment]
> To verify what? What information are you looking for in the photo? Are there certain debugging options to enable that could assist?

It could help if you put some photo, like the start of the miner or also the line you use to connect to eth.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
