### ISSUE TITLE
--tstart and --tstop don't seem to work

### ISSUE THREAD

**Issue by mlandHanze** [Lolliedieb/lolMiner-releases#468]
Hi, I've started using lolMiner to participate in my unMineable pool recently, gotta say it works great. I saw in the readme you can add the --tstart and --tstop commands in the commandline to stop/restart the miner if the gpu reaches a certain temperature, so i tried that.

in the .bat i run, i put the following:
`lolMiner.exe --algo ETCHASH --pool etchash.unmineable.com:3333 --user DOGE:DQovBQou4E7bJ5r1mUCLyF2L2BYDowHGTZ.GTX_1050Ti#61th-njw8 --tstart 75 --tstop 80` 

However, my GPU still reaches temperatures of 81 and 82 degrees C (it's a laptop, don't want to be at risk here). Have I used the commands incorrectly? Or are they not working?
Thank you in advance for your help!

EDIT: GPU is an NVIDIA GTX 1050 Ti, laptop version. not entirely sure if this is relevant, but figured I'd add it.

**Comment by jgonzis** [comment]
> Hi, I've started using lolMiner to participate in my unMineable pool recently, gotta say it works great. I saw in the readme you can add the --tstart and --tstop commands in the commandline to stop/restart the miner if the gpu reaches a certain temperature, so i tried that.
> 
> in the .bat i run, i put the following:
> `lolMiner.exe --algo ETCHASH --pool etchash.unmineable.com:3333 --user DOGE:DQovBQou4E7bJ5r1mUCLyF2L2BYDowHGTZ.GTX_1050Ti#61th-njw8 --tstart 75 --tstop 80`
> 
> However, my GPU still reaches temperatures of 81 and 82 degrees C (it's a laptop, don't want to be at risk here). Have I used the commands incorrectly? Or are they not working?
> Thank you in advance for your help!
> 
> EDIT: GPU is an NVIDIA GTX 1050 Ti, laptop version. not entirely sure if this is relevant, but figured I'd add it.

It could be that the NVML is not working properly... It was some fault Nvidia Drivers with that problem... That Temperatures are also really high?. Have you try to reduce the Power Limit?

**Comment by mlandHanze** [comment]
> It could be that the NVML is not working properly... It was some fault Nvidia Drivers with that problem... That Temperatures are also really high?. Have you try to reduce the Power Limit?

Sadly, I can't reduce the power limit or temperature limit, I've tried MSI Afterburner and EVGA Precision X1, but because my GPU is a laptop version, I don't think it's supported. After cleaning my laptop fans and raising the back of my laptop when mining, i got the temperatures to be stable at around 70C though

**Comment by jgonzis** [comment]
> > It could be that the NVML is not working properly... It was some fault Nvidia Drivers with that problem... That Temperatures are also really high?. Have you try to reduce the Power Limit?
> 
> Sadly, I can't reduce the power limit or temperature limit, I've tried MSI Afterburner and EVGA Precision X1, but because my GPU is a laptop version, I don't think it's supported. After cleaning my laptop fans and raising the back of my laptop when mining, i got the temperatures to be stable at around 70C though

I saw that problem on a laptop with RTX 2070. Good solution that clean up.
