### ISSUE TITLE
1.26 Goes into sleep mode if the feature is on.

### ISSUE THREAD

**Issue by chrisistansell** [Lolliedieb/lolMiner-releases#473]
Was using 1.21 and made the jump to 1.26 to test efficiency.  Mining works until the screen goes to sleep followed by a complete sleep state.  I realize this probably isn't a setting that everyone has running, but if you do there's a chance you will get up and leave your rig and realize it's decided to go into sleep mode.

Tested on 3 rigs.  1 laptop, 1 desktop.   Doesn't impact my dual card PC.

Running Windows 10 20H2

**Comment by pdieppa** [comment]
That is a Windows 10 issue. My guess is that Windows is not "seeing" lolMiner working in the background and decides to go to sleep after the preset timeout. Disabling sleep or hibernation in Windows will solve the problem.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
