### ISSUE TITLE
Stuck on GPU 0, DAB Build Complete 71% - Press any key to contine

### ISSUE THREAD

**Issue by dyluck07** [Lolliedieb/lolMiner-releases#474]
Hello all.  Have a GTX 1060 6g  Win10 pro 64bit  using lolMiner V1.26 64bit (for the first time)
I'm trying to run mine_eth.bat and it gets to DAG build complete 71% and then stops and says says press any key to continue...
Not sure exactly what is going on, hopefully, someone has found a solution to this!  Any help will be super appreciated.

**Comment by jgonzis** [comment]
> Hello all. Have a GTX 1060 6g Win10 pro 64bit using lolMiner V1.26 64bit (for the first time)
> I'm trying to run mine_eth.bat and it gets to DAG build complete 71% and then stops and says says press any key to continue...
> Not sure exactly what is going on, hopefully, someone has found a solution to this! Any help will be super appreciated.

You should try to put more Swap disk and check the OC... It could be you have the Power Limit to high or to low and that crash ...
