### ISSUE TITLE
Trying to connect in 1 second Time out on connection attempt resolve. Retrying. Lost connection to stratum server asia1-etc.ethermine.org:4444 or server not reachable. Trying to connect in 1 second

### ISSUE THREAD

**Issue by 5harpp** [Lolliedieb/lolMiner-releases#479]
this come up every time I try and run the miner and i have tried every server and both stratum ports. not sure what to do

**Comment by jgonzis** [comment]
Can you put a photo of your Flightsheet or line parameters... to try to have more information. Because that is a Internet problem or firewall, let's see if there is another parameter that is making not to connect. Or if you have SSL selected...

**Comment by monkeydust** [comment]
Also having this problem, Did anyone figure this out?

______

Connected to eu1.ethermine.org:4444 (TLS disabled)

Set Ethash stratum mode: Ethereum Proxy

GPU 979: Share is stale (0 ms)

Lost connection to stratum server eu1.ethermine.org:4444 or server not reachable.

Trying to connect in 1 second

Connected to eu1.ethermine.org:4444 (TLS disabled)

Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.

**Comment by jgonzis** [comment]
It seems to be connected and later is disconnected... the strange thing is GPU 979... and Stale with 0ms...

It could a be a firewall...  

try this server:  ssl://eu1.ethermine.org:5555 

If that helps

**Comment by monkeydust** [comment]
Thanks. It connects via TLS but still throws error.

Connected to eu1.ethermine.org:5555  (TLS enabled)
TLS Handshake success
Set Ethash stratum mode: Ethereum Proxy
GPU 979: Share is stale (0 ms)
Lost connection to stratum server eu1.ethermine.org:5555 or server not reachable.
Trying to connect in 1 second

**Comment by jgonzis** [comment]
I hope you can put the complete line connection and some photos... because it is really strange...

**Comment by monkeydust** [comment]
Sorry how can do that exactly (line connection / photos) what do i need to do exactly?

**Comment by monkeydust** [comment]
Ok sorted. Was my ETH address, I dont know why but I created a new one on metamask and its working. Thanks

**Comment by jgonzis** [comment]
Great!! Thx for information :-)
