### ISSUE TITLE
1060 5G get error

### ISSUE THREAD

**Issue by fangw1** [Lolliedieb/lolMiner-releases#480]
![image](https://user-images.githubusercontent.com/20739640/116100505-90ab5f00-a6df-11eb-8a18-d34cc4ec79bb.png)

**Comment by fangw1** [comment]
![image](https://user-images.githubusercontent.com/20739640/116100714-c81a0b80-a6df-11eb-8f54-033753d4d40f.png)

**Comment by fangw1** [comment]
![image](https://user-images.githubusercontent.com/20739640/116100986-06172f80-a6e0-11eb-8d18-3d26ac8bbc69.png)

**Comment by jgonzis** [comment]
It is a crash of the driver, that could a OC like it says the miner... Only to know, have you tryed the old version the 1.21 for Windows?  That use the old OpenCL, only to know if it is a Cuda Driver problem or a OpenCL problem

**Comment by fangw1** [comment]
I just tryed v1.25 and v1.26 on win10 。They all have the same problem.
