### ISSUE TITLE
rx 6800 low hashrate

### ISSUE THREAD

**Issue by add09** [Lolliedieb/lolMiner-releases#485]
My video card rx 6800. When mining, it shows a hashrate of 25 mh / sec. Am I doing something wrong? Compute mode is on. OS win7. Should be at least 50. Please help me. I've already broken my whole head. :)

**Comment by jgonzis** [comment]
> My video card rx 6800. When mining, it shows a hashrate of 25 mh / sec. Am I doing something wrong? Compute mode is on. OS win7. Should be at least 50. Please help me. I've already broken my whole head. :)

Can you try it with MMPOS?. It is a free Mining OS that you can run it with a Pendrive, so you don't need to touch Windows 7. It should be some limitation on Windows for that...

**Comment by jgonzis** [comment]
No problem or feedback... close issue
