### ISSUE TITLE
How to set worker's email as password?

### ISSUE THREAD

**Issue by neuwander** [Lolliedieb/lolMiner-releases#486]
I want to change nanopool payout minimum limit. It said that I should set the email for each worker as password.  I konw some old version claymore can do, but how to set in lolminer?
Does anyone know? Thanks a million :)

**Comment by jgonzis** [comment]
> I want to change nanopool payout minimum limit. It said that I should set the email for each worker as password. I konw some old version claymore can do, but how to set in lolminer?
> Does anyone know? Thanks a million :)

In the user parameter use it like this: ETHWAL/WORKERNAME/EMAIL that will inform nanopool your mail to change the payout

**Comment by jgonzis** [comment]
No problem or feedback... close issue
