### ISSUE TITLE
Zombie DAG Rx 570 4gb

### ISSUE THREAD

**Issue by djmrodrigues** [Lolliedieb/lolMiner-releases#489]
After 60 shares start geting lots of invalid shares like 20. The the miner identifies the problem and refreshes the dag. it would be nice to have the option to auto refresh the dag every x shares. avoided invalid shares, each chose the number of shares from which to refresh the dag.

**Comment by jgonzis** [comment]
> After 60 shares start geting lots of invalid shares like 20. The the miner identifies the problem and refreshes the dag. it would be nice to have the option to auto refresh the dag every x shares. avoided invalid shares, each chose the number of shares from which to refresh the dag.

each 3 Invalid Shares it regenerates DAG normally... You should decrease Memory OC and reduce the 4g-alloc-size parameter

**Comment by djmrodrigues** [comment]
Tanks. At lower mem OC it is beter

Obter Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
