### ISSUE TITLE
I'm so close to mining please help me

### ISSUE THREAD

**Issue by tyler2019** [Lolliedieb/lolMiner-releases#490]
I'm having an issue when I start the mine_eth_4G
The minor pops up but I'm getting some errors and I don't understand what I'm reading
See attached screenshot
Please help
![Snapchat-106824296](https://user-images.githubusercontent.com/42032121/116576291-6d4e0300-a8dd-11eb-8cc7-552cd97d53ad.jpg)

**Comment by Jose10Espinoza** [comment]
Active: false (Unsupported device or driver version)

**Comment by jgonzis** [comment]
> I'm having an issue when I start the mine_eth_4G
> The minor pops up but I'm getting some errors and I don't understand what I'm reading
> See attached screenshot
> Please help
> ![Snapchat-106824296](https://user-images.githubusercontent.com/42032121/116576291-6d4e0300-a8dd-11eb-8cc7-552cd97d53ad.jpg)

You will not be able to mine with the integrated GPU of your Laptop

**Comment by tyler2019** [comment]
Can it mine anything 🤷🏼‍♂️

**Comment by jgonzis** [comment]
You can try cpu miner... like Monero or similar

**Comment by tyler2019** [comment]
Wont work

**Comment by jgonzis** [comment]
No support for iGPU
