### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by vergmafia** [Lolliedieb/lolMiner-releases#492]
im showing this at the bottom straight from the download ? any fixes ?

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto loop
)

**Comment by Jose10Espinoza** [comment]
That is normal.

**Comment by jgonzis** [comment]
> im showing this at the bottom straight from the download ? any fixes ?
> 
> lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto loop
> )

That is making a loop... so in case the driver fails... it will automatic reload the miner. And you don't need to worry about it. It does it automaticly.
