### ISSUE TITLE
miner not showing up in ethermine

### ISSUE THREAD

**Issue by mathijskip** [Lolliedieb/lolMiner-releases#493]
hi im mining etc but i dont see the worker in ethermine dash, 
some1 can help me out ?

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eu1-etc.ethermine.org:4444"
set "WALLET=0xff34D5A00e6Cf4d746287bF9165Ac664Ec841a77.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETCHASH --pool eu1-etc.ethermine.org:4444 --user 0xff34D5A00e6Cf4d746287bF9165Ac664Ec841a77.lolMinerWorker
pause

**Comment by mathijskip** [comment]
![mine screen](https://user-images.githubusercontent.com/50025562/116777023-3e19cc00-aa6c-11eb-9bf4-640e487bf3ee.jpg)

for some reason it randomly works a little time.. and then its gone again..

**Comment by jgonzis** [comment]
> ![mine screen](https://user-images.githubusercontent.com/50025562/116777023-3e19cc00-aa6c-11eb-9bf4-640e487bf3ee.jpg)
> 
> for some reason it randomly works a little time.. and then its gone again..

It is normal... You are connecting to nanopool etc. It will never be show in ethermine.

**Comment by mathijskip** [comment]
ye i changed it to ethermine but it wont connect via lolminer,   now i tried claymore, and now it connects

**Comment by jgonzis** [comment]
> ye i changed it to ethermine but it wont connect via lolminer, now i tried claymore, and now it connects

Show the line, it sure can connect.  It is strange that claymore can connect to ETC because  if haven't update to ETCHASH algo

**Comment by mlamlam** [comment]
try change to this

set "POOL=stratum+ssl://asia1.ethermine.org:5555"

**Comment by jgonzis** [comment]
No problem or feedback... close issue
