### ISSUE TITLE
1.26 Hash rate keeps dropping to 0 have to restart to get hash rate back

### ISSUE THREAD

**Issue by Amishtek** [Lolliedieb/lolMiner-releases#498]
---------------------------------------------------------+
|  _       _ __  __ _                   _   ____   __     |
| | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \ / /_    |
| | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) | '_ \   |
| | | (_) | | |  | | | | | |  __/ |    | |_ / __/| (_) |  |
| |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____|\___/   |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|             Made by Lolliedieb, April 2021              |
+---------------------------------------------------------+

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    NVIDIA GeForce RTX 3080
    Address: 9:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  10240 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)

Connecting to pool...
Connected to ethash-us.unmineable.com:3333  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: DOGE:DS1g94fbEb18x4qD6yd2cUuasZdmFdUZRH.Nvidia#sy4i-7o2c
New job received: 0xfce776 Epoch: 411 Target: 000000007e000000
Start Mining...
-------------------------------------------------------
          Generated light cache for epoch 411
       Took 1944 ms, size of new DAG: 4311 MByte
-------------------------------------------------------
Start DAG gen on GPU 0 (normal mode)
GPU 0, DAG build complete 17%
GPU 0, DAG build complete 35%
New job received: 0x49e366 Epoch: 411 Target: 000000007e000000
GPU 0, DAG build complete 53%
GPU 0, DAG build complete 71%
GPU 0, DAG build complete 89%
Finished DAG gen on GPU 0 (5828 ms)
New job received: 0xb1a8e8 Epoch: 411 Target: 000000007e000000
New job received: 0xa5c219 Epoch: 411 Target: 000000007e000000
New job received: 0x4a1dc2 Epoch: 411 Target: 000000007e000000
Average speed (30s): 28.73 mh/s
New job received: 0x4e47b0 Epoch: 411 Target: 000000007e000000
New job received: 0x114d33 Epoch: 411 Target: 000000007e000000
New job received: 0x952b1a Epoch: 411 Target: 000000007e000000
New job received: 0xa17411 Epoch: 411 Target: 000000007e000000
New job received: 0x6da2e4 Epoch: 411 Target: 000000007e000000
New job received: 0x05bd77 Epoch: 411 Target: 000000007e000000
New job received: 0x74dc39 Epoch: 411 Target: 000000007e000000
New job received: 0x6d4632 Epoch: 411 Target: 000000007e000000
Average speed (30s): 39.76 mh/s
New job received: 0x101155 Epoch: 411 Target: 000000007e000000
New job received: 0x07b123 Epoch: 411 Target: 000000007e000000
New job received: 0x30d049 Epoch: 411 Target: 000000007e000000
New job received: 0x207ec0 Epoch: 411 Target: 000000007e000000
New job received: 0x81da25 Epoch: 411 Target: 000000007e000000
New job received: 0x8e8ae5 Epoch: 411 Target: 000000007e000000
New job received: 0x92173c Epoch: 411 Target: 000000007e000000
New job received: 0xa0a0f9 Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.55 mh/s
New job received: 0xafae70 Epoch: 411 Target: 000000007e000000
New job received: 0xa18d3d Epoch: 411 Target: 000000007e000000
New job received: 0x483469 Epoch: 411 Target: 000000007e000000
New job received: 0x072fe0 Epoch: 411 Target: 000000007e000000
New job received: 0xed5067 Epoch: 411 Target: 000000007e000000
New job received: 0x48b94a Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.77 mh/s
New job received: 0x8f6aab Epoch: 411 Target: 000000007e000000
New job received: 0x8a2dd2 Epoch: 411 Target: 000000007e000000
New job received: 0xd39be2 Epoch: 411 Target: 000000007e000000
New job received: 0xd11f35 Epoch: 411 Target: 000000007e000000
New job received: 0x351126 Epoch: 411 Target: 000000007e000000
New job received: 0x2b2cbd Epoch: 411 Target: 000000007e000000
New job received: 0x522af3 Epoch: 411 Target: 000000007e000000
New job received: 0xe347cd Epoch: 411 Target: 000000007e000000
GPU 0: Found a share of difficulty 63.36G
---------------------------------------------
Statistics (21:34:46); Mining: Ethash
Connected to: ethash-us.unmineable.com:3333
Uptime: 0h 2m 31s
                       GPU 0   Total
Speed (mh/s):          38.10   38.10
Pool (mh/s):            0.00    0.00
Best Share:            63.4G   63.4G
Shares (A/S/Hw):       0/0/0   0/0/0
Power (W):              n.a.
Efficiency (mh/s/W):    n.a.    n.a.
Temp (deg C):           n.a.
Fan Speed (%):             0
---------------------------------------------
GPU 0: Share accepted (27 ms)
Average speed (30s): 40.70 mh/s
New job received: 0x58c406 Epoch: 411 Target: 000000007e000000
New job received: 0x6eb6b1 Epoch: 411 Target: 000000007e000000
New job received: 0x994e57 Epoch: 411 Target: 000000007e000000
New job received: 0x5e6f81 Epoch: 411 Target: 000000007e000000
New job received: 0xe65f60 Epoch: 411 Target: 000000007e000000
New job received: 0xf354b9 Epoch: 411 Target: 000000007e000000
New job received: 0x9eb2a1 Epoch: 411 Target: 000000007e000000
New job received: 0x162cea Epoch: 411 Target: 000000007e000000
New job received: 0x3d220d Epoch: 411 Target: 000000007e000000
New job received: 0x5d92de Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.55 mh/s
New job received: 0xc4d467 Epoch: 411 Target: 000000007e000000
New job received: 0xbd567b Epoch: 411 Target: 000000007e000000
New job received: 0x22a3ae Epoch: 411 Target: 000000007e000000
New job received: 0x89fef6 Epoch: 411 Target: 000000007e000000
New job received: 0x4cc935 Epoch: 411 Target: 000000007e000000
New job received: 0x2b0b59 Epoch: 411 Target: 000000007e000000
New job received: 0x9079ce Epoch: 411 Target: 000000007e000000
New job received: 0x8dbaa1 Epoch: 411 Target: 000000007e000000
New job received: 0xafff6b Epoch: 411 Target: 000000007e000000
New job received: 0x49c9b7 Epoch: 411 Target: 000000007e000000
New job received: 0x0ce919 Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.48 mh/s
New job received: 0x2d1da3 Epoch: 411 Target: 000000007e000000
New job received: 0xa84c83 Epoch: 411 Target: 000000007e000000
New job received: 0x769742 Epoch: 411 Target: 000000007e000000
New job received: 0x753304 Epoch: 411 Target: 000000007e000000
New job received: 0x547a86 Epoch: 411 Target: 000000007e000000
New job received: 0x522d20 Epoch: 411 Target: 000000007e000000
Average speed (30s): 39.87 mh/s
New job received: 0xed4528 Epoch: 411 Target: 000000007e000000
New job received: 0x6afe18 Epoch: 411 Target: 000000007e000000
New job received: 0x41cc78 Epoch: 411 Target: 000000007e000000
New job received: 0x770a2d Epoch: 411 Target: 000000007e000000
Average speed (30s): 39.15 mh/s
New job received: 0x3de37c Epoch: 411 Target: 000000007e000000
New job received: 0x80a3db Epoch: 411 Target: 000000007e000000
New job received: 0x1a9c17 Epoch: 411 Target: 000000007e000000
New job received: 0x823c63 Epoch: 411 Target: 000000007e000000
New job received: 0x4a4d45 Epoch: 411 Target: 000000007e000000
New job received: 0x53c4bd Epoch: 411 Target: 000000007e000000
New job received: 0x1f12e9 Epoch: 411 Target: 000000007e000000
New job received: 0x00efb6 Epoch: 411 Target: 000000007e000000
---------------------------------------------
Statistics (21:37:16); Mining: Ethash
Connected to: ethash-us.unmineable.com:3333
Uptime: 0h 5m 1s
                       GPU 0   Total
Speed (mh/s):          39.98   39.98
Pool (mh/s):           28.99   28.99
Best Share:            63.4G   63.4G
Shares (A/S/Hw):       1/0/0   1/0/0
Power (W):              n.a.
Efficiency (mh/s/W):    n.a.    n.a.
Temp (deg C):           n.a.
Fan Speed (%):             0
---------------------------------------------
Average speed (30s): 39.81 mh/s
New job received: 0x752660 Epoch: 411 Target: 000000007e000000
New job received: 0x07176b Epoch: 411 Target: 000000007e000000
GPU 0: Found a share of difficulty 52.14G
GPU 0: Share accepted (24 ms)
New job received: 0x456f6a Epoch: 411 Target: 000000007e000000
New job received: 0x0edc6c Epoch: 411 Target: 000000007e000000
New job received: 0x29a92d Epoch: 411 Target: 000000007e000000
New job received: 0x5b51f4 Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.59 mh/s
GPU 0: Found a share of difficulty 15.37G
GPU 0: Share accepted (24 ms)
New job received: 0x2354c9 Epoch: 411 Target: 000000007e000000
New job received: 0xa9839b Epoch: 411 Target: 000000007e000000
New job received: 0xd72489 Epoch: 411 Target: 000000007e000000
New job received: 0x1adb54 Epoch: 411 Target: 000000007e000000
GPU 0: Found a share of difficulty 60.91G
GPU 0: Share accepted (25 ms)
New job received: 0x8ed0e3 Epoch: 411 Target: 000000007e000000
New job received: 0x0ac57c Epoch: 411 Target: 000000007e000000
New job received: 0xbbdc29 Epoch: 411 Target: 000000007e000000
New job received: 0x533703 Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.09 mh/s
New job received: 0x74210d Epoch: 411 Target: 000000007e000000
New job received: 0x0cf9da Epoch: 411 Target: 000000007e000000
New job received: 0xa6af2a Epoch: 411 Target: 000000007e000000
New job received: 0xd6fee2 Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.15 mh/s
New job received: 0x93972e Epoch: 411 Target: 000000007e000000
New job received: 0xf19d4a Epoch: 411 Target: 000000007e000000
New job received: 0x034a56 Epoch: 411 Target: 000000007e000000
New job received: 0xa58359 Epoch: 411 Target: 000000007e000000
New job received: 0xbbee94 Epoch: 411 Target: 000000007e000000
New job received: 0x07904f Epoch: 411 Target: 000000007e000000
New job received: 0x682f02 Epoch: 411 Target: 000000007e000000
New job received: 0xf2a3c7 Epoch: 411 Target: 000000007e000000
New job received: 0x0dc190 Epoch: 411 Target: 000000007e000000
New job received: 0xc7e9bf Epoch: 411 Target: 000000007e000000
New job received: 0x8c63bb Epoch: 411 Target: 000000007e000000
Average speed (30s): 40.10 mh/s
New job received: 0x4f0e48 Epoch: 411 Target: 000000007e000000
New job received: 0x94be85 Epoch: 411 Target: 000000007e000000
New job received: 0x43f9b4 Epoch: 411 Target: 000000007e000000
New job received: 0x9b2ff1 Epoch: 411 Target: 000000007e000000
New job received: 0x96e2b1 Epoch: 411 Target: 000000007e000000
New job received: 0xd3c3fc Epoch: 411 Target: 000000007e000000
New job received: 0x9531b4 Epoch: 411 Target: 000000007e000000
New job received: 0xc1a1fd Epoch: 411 Target: 000000007e000000
New job received: 0x08391b Epoch: 411 Target: 000000007e000000
New job received: 0x183a48 Epoch: 411 Target: 000000007e000000
New job received: 0xed9d41 Epoch: 411 Target: 000000007e000000
---------------------------------------------
Statistics (21:39:46); Mining: Ethash
Connected to: ethash-us.unmineable.com:3333
Uptime: 0h 7m 31s
                       GPU 0   Total
Speed (mh/s):          40.02   40.02
Pool (mh/s):           77.39   77.39
Best Share:            63.4G   63.4G
Shares (A/S/Hw):       4/0/0   4/0/0
Power (W):              n.a.
Efficiency (mh/s/W):    n.a.    n.a.
Temp (deg C):           n.a.
Fan Speed (%):             0
---------------------------------------------
Average speed (30s): 39.20 mh/s
New job received: 0x4e8973 Epoch: 411 Target: 000000007e000000
New job received: 0x6aac2d Epoch: 411 Target: 000000007e000000
New job received: 0xc8dc5b Epoch: 411 Target: 000000007e000000
New job received: 0x017e24 Epoch: 411 Target: 000000007e000000
New job received: 0x4fdc52 Epoch: 411 Target: 000000007e000000
New job received: 0x56a02f Epoch: 411 Target: 000000007e000000
New job received: 0xbb5707 Epoch: 411 Target: 000000007e000000
New job received: 0xe8f9d6 Epoch: 411 Target: 000000007e000000
New job received: 0x1a5bce Epoch: 411 Target: 000000007e000000
Average speed (30s): 24.33 mh/s
New job received: 0x2812c8 Epoch: 411 Target: 000000007e000000
New job received: 0x1630c9 Epoch: 411 Target: 000000007e000000
New job received: 0xe3dd8f Epoch: 411 Target: 000000007e000000
New job received: 0x1ce61c Epoch: 411 Target: 000000007e000000
New job received: 0x38ab51 Epoch: 411 Target: 000000007e000000
New job received: 0x93e7e5 Epoch: 411 Target: 000000007e000000
New job received: 0x2d8b66 Epoch: 411 Target: 000000007e000000
New job received: 0x8bec8f Epoch: 411 Target: 000000007e000000
New job received: 0xcd7b05 Epoch: 411 Target: 000000007e000000
Average speed (30s): 0.00 mh/s
New job received: 0x8be31d Epoch: 411 Target: 000000007e000000
New job received: 0x9ab852 Epoch: 411 Target: 000000007e000000
New job received: 0xf9f3c9 Epoch: 411 Target: 000000007e000000
New job received: 0x3f3af7 Epoch: 411 Target: 000000007e000000
New job received: 0x55c509 Epoch: 411 Target: 000000007e000000
New job received: 0xe95cc0 Epoch: 411 Target: 000000007e000000
New job received: 0x148bf6 Epoch: 411 Target: 000000007e000000
New job received: 0x657e09 Epoch: 411 Target: 000000007e000000
New job received: 0x64a690 Epoch: 411 Target: 000000007e000000
New job received: 0x059cd4 Epoch: 411 Target: 000000007e000000
New job received: 0xc6bec1 Epoch: 411 Target: 000000007e000000
Average speed (30s): 0.00 mh/s
New job received: 0x572160 Epoch: 411 Target: 000000007e000000
New job received: 0xc0b05e Epoch: 411 Target: 000000007e000000
New job received: 0x8fccb7 Epoch: 411 Target: 000000007e000000
New job received: 0xffc526 Epoch: 411 Target: 000000007e000000
New job received: 0x568b15 Epoch: 411 Target: 000000007e000000
Average speed (30s): 0.00 mh/s
New job received: 0x4a4e42 Epoch: 411 Target: 000000007e000000
New job received: 0x864ecc Epoch: 411 Target: 000000007e000000
New job received: 0x236d5d Epoch: 411 Target: 000000007e000000
New job received: 0x5197d4 Epoch: 411 Target: 000000007e000000
New job received: 0x6c4e33 Epoch: 411 Target: 000000007e000000
---------------------------------------------
Statistics (21:42:16); Mining: Ethash
Connected to: ethash-us.unmineable.com:3333
Uptime: 0h 10m 1s
                       GPU 0   Total
Speed (mh/s):           4.90    4.90
Pool (mh/s):           58.08   58.08
Best Share:            63.4G   63.4G
Shares (A/S/Hw):       4/0/0   4/0/0
Power (W):              n.a.
Efficiency (mh/s/W):    n.a.    n.a.
Temp (deg C):           n.a.
Fan Speed (%):             0
---------------------------------------------
Average speed (30s): 0.00 mh/s
New job received: 0x3372a5 Epoch: 411 Target: 000000007e000000
New job received: 0x28754a Epoch: 411 Target: 000000007e000000
New job received: 0x04d120 Epoch: 411 Target: 000000007e000000
New job received: 0x289319 Epoch: 411 Target: 000000007e000000
New job received: 0x04fb1b Epoch: 411 Target: 000000007e000000
New job received: 0x264da4 Epoch: 411 Target: 000000007e000000
New job received: 0xd2ad19 Epoch: 411 Target: 000000007e000000
Average speed (30s): 0.00 mh/s
New job received: 0x3b6b7c Epoch: 411 Target: 000000007e000000
New job received: 0x4f5c0a Epoch: 411 Target: 000000007e000000
New job received: 0xf48c52 Epoch: 411 Target: 000000007e000000
New job received: 0x752f1d Epoch: 411 Target: 000000007e000000
Average speed (30s): 0.00 mh/s
New job received: 0x1d5cc1 Epoch: 411 Target: 000000007e000000
New job received: 0xa1a264 Epoch: 411 Target: 000000007e000000
New job received: 0xaf72ca Epoch: 411 Target: 000000007e000000
New job received: 0x088b3b Epoch: 411 Target: 000000007e000000
New job received: 0x96ab60 Epoch: 411 Target: 000000007e000000
New job received: 0x802685 Epoch: 411 Target: 000000007e000000
New job received: 0x555270 Epoch: 411 Target: 000000007e000000
New job received: 0x414f57 Epoch: 411 Target: 000000007e000000
New job received: 0xea156c Epoch: 411 Target: 000000007e000000
New job received: 0x6c66df Epoch: 411 Target: 000000007e000000
Average speed (30s): 0.00 mh/s
New job received: 0x2371ce Epoch: 411 Target: 000000007e000000
New job received: 0x9b7d3c Epoch: 411 Target: 000000007e000000
New job received: 0x2f8eae Epoch: 411 Target: 000000007e000000
New job received: 0xb19e23 Epoch: 411 Target: 000000007e000000
New job received: 0xaef4b9 Epoch: 411 Target: 000000007e000000

**Comment by jgonzis** [comment]
I think you have thermal Problem with this 3080... Which is your OC. 

That make the card to crash. The 3080 should be with the right OC and good ventilation around the 92-100Mhs. You are getting not more than 40Mhs after 7 minutes... 

What are you using for the OC of the card?

**Comment by Lolliedieb** [comment]
Something horribly wrong there with the system. The dag build already is way too slow - half the speed of a 3070 ... and the crash is odd, because the driver does not crash, else we would see an error message. 
Can you completely relax oc settings and turn up ventilation? Also check with nvidia-smi if no other process is running in parallel.

**Comment by SK-StYleZ** [comment]
check your gpu memory junction temperature - ideally it should be below 95°C.
rtx 3080 & 3090 a prone to high memory junction temperatures, whitch results in slow rates.

**Comment by jgonzis** [comment]
No user answer...
