### ISSUE TITLE
Hash rate not showing up in pool

### ISSUE THREAD

**Issue by asifsa** [Lolliedieb/lolMiner-releases#499]
Hello all,

I am trying to mine Ethereum using ethermine pool with Windows 10. However, I am getting insanely high hashrates but they are not showing up on the ethermine.org website. I have made it run for about half an hour many times. Something's wrong and I'm not sure what's up. Any help is appreciated.

![image](https://user-images.githubusercontent.com/44511975/116806307-b6e45b00-ab34-11eb-9ad2-946a2516aa20.png)

![image](https://user-images.githubusercontent.com/44511975/116806162-f3fc1d80-ab33-11eb-8682-d357e5144434.png)

**Comment by pdieppa** [comment]
Connect to digipools as a test. Your starts will show up within 30 seconds.
Ethermine is slow showing starts, they say within 20 minutes but I have seen way longer than that.
I'm not sure why the number is so why, it could be math is wrong with the software (display only) but hashing correctly.

**Comment by jgonzis** [comment]
> Hello all,
> 
> I am trying to mine Ethereum using ethermine pool with Windows 10. However, I am getting insanely high hashrates but they are not showing up on the ethermine.org website. I have made it run for about half an hour many times. Something's wrong and I'm not sure what's up. Any help is appreciated.
> 
> ![image](https://user-images.githubusercontent.com/44511975/116806307-b6e45b00-ab34-11eb-9ad2-946a2516aa20.png)
> 
> ![image](https://user-images.githubusercontent.com/44511975/116806162-f3fc1d80-ab33-11eb-8682-d357e5144434.png)

It is normal that you will never get any hash rate in ethermine. You have only selected the 4Gb card to mine and 4Gb card cannot mine ETH in Windows. So the hashrate is 0Mhs so any option to find solution. 

You should run in Windows Beam or ETC both with nice profit...
