### ISSUE TITLE
0.7 release is Just one big BUG

### ISSUE THREAD

**Issue by Quake4** [Lolliedieb/lolMiner-releases#5]
![image](https://user-images.githubusercontent.com/29517243/53392078-677cd000-39a9-11e9-9169-7bcb7f6d786f.png)

**Comment by Quake4** [comment]
0.7a5 working well

**Comment by Quake4** [comment]
and 192auto on zergpool isnt working.

**Comment by Quake4** [comment]
beam on 584 in 07a5 fork fine in 07 release isnt working

**Comment by Lolliedieb** [comment]
Can confirm that AUTO192_7 is broken, but 144_5 working for me on Nicehash

What issue you have with beam?

**Comment by Quake4** [comment]
please, see screen on bitcointalk it same error

**Comment by ImmortalJ** [comment]
I get the same error as Quake4 using 144_5 on Nicehash
