### ISSUE TITLE
 BEAMV3 Miner makes system crash (Linux)

### ISSUE THREAD

**Issue by BayLee4** [Lolliedieb/lolMiner-releases#50]
Hi,
when trying to launch `mine_beam.sh` the machine reboot almost instantly, the issue does not exist with other coins (just updated from 0.9.7 to 1.0 to test the BEAMv3 algo)

I'm on Ubuntu 18.04 using a RX64 card, and amgpu-pro 19.50

**Comment by Lolliedieb** [comment]
Can you test if this also happens with 1.04?
If yes: can you enable log file writing and see if any debug output is printed?

**Comment by BayLee4** [comment]
Sure, unfortunately 1.04 doesn't resolve the issue, and there is no log created even with the `--log` parameter : it crashes immediately after the "Start mining" message :(

**Comment by Lolliedieb** [comment]
I do not have a V64 - but let me check Beam with 19.50 and my Vii :)

**Comment by Lolliedieb** [comment]
Just did start 1.05 with 19.50 on my 580 / Vii mixed rig and its working well there - since the version got all new kernels can you give it a test?

**Comment by BayLee4** [comment]
Yay it now works flawlessly :) 

Thank you !
