### ISSUE TITLE
All targets are blank. (0000000ffff0000)

### ISSUE THREAD

**Issue by Dougman7** [Lolliedieb/lolMiner-releases#503]
Target: 0000000ffff0000
... This seems like a problem.
![Screenshot (18)](https://user-images.githubusercontent.com/33228183/116949694-dfa14900-ac37-11eb-9ea5-9158581a668a.png)

**Comment by jgonzis** [comment]
I don't know if the new version will solve that, there are a new Stats format, that could probably be solved

**Comment by MarcoPSanchez** [comment]
I have the same problem. I have input my wallet instead of !WALLET! in the bat file:
:loop
lolMiner.exe --algo ETHASH --pool !POOL! --user 0x118A89cXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto loop
)
it have the same issue. I don't have a number assigned with my wallet.

**Comment by jgonzis** [comment]
> I have the same problem. I have input my wallet instead of !WALLET! in the bat file:
> :loop
> lolMiner.exe --algo ETHASH --pool !POOL! --user 0x118A89cXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --watchdog exit
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto loop
> )
> it have the same issue. I don't have a number assigned with my wallet.

That's not a problem... not too much hash and you don't find solutions...

**Comment by MarcoPSanchez** [comment]
jgonzis what do you mean not too much hash and you don't find solution, see my capture on my setup:

![MPS capture 05052021](https://user-images.githubusercontent.com/82722519/117232101-5de72200-add5-11eb-8e48-4a877cd4f629.png)

Please let me know if the 00000000ffff0000 is a problem.

**Comment by jgonzis** [comment]
> jgonzis what do you mean not too much hash and you don't find solution, see my capture on my setup:
> 
> ![MPS capture 05052021](https://user-images.githubusercontent.com/82722519/117232101-5de72200-add5-11eb-8e48-4a877cd4f629.png)
> 
> Please let me know if the 00000000ffff0000 is a problem.

It is not a problem.... don't worry. I have same Target in ethermine too:

Eth: New job received: 0x6dc652 Epoch: 412 Target: 00000000ffff0000 
Eth: New job received: 0x319732 Epoch: 412 Target: 00000000ffff0000 

Don't worry. It is normal 👍

**Comment by MarcoPSanchez** [comment]
Thanks a  lot for confirming that this is not a problem. Thanks again for your help, support on this and it is greatly appreciated.
