### ISSUE TITLE
Zombie Mode On 4Gb Card RX 560 ,very slow mining speed : 0.1mh/s (ETH)

### ISSUE THREAD

**Issue by NewSoul** [Lolliedieb/lolMiner-releases#504]
mining eth on windows 10, 
gpu Radeon Rx 560 4G , 
lolminer version 1.26, using mine_eth_4G.bat to mining.
> C:\Users\Admin\Desktop\1.26\lolMiner.exe --algo ETHASH --pool stratum+tcp://es.huobipool.com:1800 --user newsoul9090 --worker test01 --4g-alloc-size 4000 --keepfree 8 

why my mining speed so slow, only 0.1mh/s.
waiting for your reply, thx !
![2](https://user-images.githubusercontent.com/22075767/116968015-3a917980-ace6-11eb-9d0a-341297278c9b.jpg)
![1](https://user-images.githubusercontent.com/22075767/116968307-d4592680-ace6-11eb-8193-e700f68be1f5.jpg)

**Comment by NewSoul** [comment]
does it not support mining eth on 4gb gpu cards anymore?

**Comment by brutalminer** [comment]
Hi. First, Windows is not good to zombiemode. Second: --4g-alloc-size 4000 is not a good parameter. 

Try this:

lolMiner.exe --algo ETHASH --pool stratum+tcp://es.huobipool.com:1800 --user newsoul9090 --worker test01 --keepfree 8

If freeze, increase keepfree by 5. (--keepfree 13...)

Maybe try to use Hiveos. is easy. I think you reach 14Mhs in Hiveos with rx 560.

**Comment by jgonzis** [comment]
> Hi. First, Windows is not good to zombiemode. Second: --4g-alloc-size 4000 is not a good parameter.
> 
> Try this:
> 
> lolMiner.exe --algo ETHASH --pool stratum+tcp://es.huobipool.com:1800 --user newsoul9090 --worker test01 --keepfree 8
> 
> If freeze, increase keepfree by 5. (--keepfree 13...)
> 
> Maybe try to use Hiveos. is easy. I think you reach 14Mhs in Hiveos with rx 560.

You cannot mine ETH in Windows with 4Gb Cards...I recommend you to swap to ETC it has a really nice profit now... similar to ETH. You can do it also with lolMiner and in Windows
