### ISSUE TITLE
--tstop --tstart don't seem to be working

### ISSUE THREAD

**Issue by lollipopminer** [Lolliedieb/lolMiner-releases#507]
Firstly thank you for making lolMiner.

In the .bat file I have modified the parameters to the following -
lolMiner.exe --tstop 72 --tstart 62 --tmode junction --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit

However, the temperature goes to 84 degrees and the miner still continues mining and doesn't stop at any point. I thought with this command the miner would stop at 72 degrees and start again once the temp falls back to 62. Used the junction parameter as I think that corresponds to the GPU hotspot? Using GPU-Z to monitor temps...

Machine is a ASUS Scar Rog Strix laptop with a 3080 16GB which I've purchased for work but using for casual mining as I can't work on it currently... So definitely don't want to damage the hardware with heat just to generate a few dollars. :)

Thanks for your help!

**Comment by Lolliedieb** [comment]
Thanks for reporting. 
Indeed on Nvidias that is buggy at the moment. I will put it to fix list for 1.28.

**Comment by lollipopminer** [comment]
Thank you for fixing the bug - can see it in the release notes for 1.28
- Emergency temperature stop (--tmode, --tstart, --stop) now also working for Nvidia GPUs using CUDA.

Waiting for the Windows release in 24 hours. Cheers!

**Comment by lollipopminer** [comment]
Hi, this is great! It seems to be working but only in edge mode - it seems to ignore the junction parameter... which is fine for the time being.  Great to see the miner turn off and on, definitely preventing the card from heating damage. I'll close the issue after you reply to let me know whether it is only working in edge mode currently... Thanks again!

**Comment by Lolliedieb** [comment]
I will check again if there is an issue with junction, thanks for reporting :)
