### ISSUE TITLE
LOLminer 1.26 stuck on start mining..

### ISSUE THREAD

**Issue by Distarks** [Lolliedieb/lolMiner-releases#508]
Hey Guys ive looked everywhere for something to help me fix this but i have no idea whats going on i have been running lolminer for a few weeks just fine and i had to close it down yesterday and when i try to re-open the software it loads and connects but just won't continue ive tried different servers and still doesn't work any help would be greatly appreciated here is a photo to show whats going on

Thanks
![Untitled](https://user-images.githubusercontent.com/83727109/117194878-00de7280-adbb-11eb-9a1c-674c5af31e63.png)

**Comment by dvorel** [comment]
just try clicking enter

**Comment by Distarks** [comment]
I did its like its frozen sometimes it goes a little bit further then what you see then stops

**Comment by dvorel** [comment]
did you try without overclocks if you are using any

**Comment by Distarks** [comment]
There are no overclocks i tried pheonix also did the same thing disabled my firewalls to see if that was the problen but nothing but also tried other miners and only one that works is nicehash i find that kind of weird

**Comment by dvorel** [comment]
Did you also disable windows defender?

**Comment by Distarks** [comment]
Yes i did

**Comment by dvorel** [comment]
Did myb windows update since it was working?
If not I would try DDUing nvidia drivers and reinstalling

**Comment by asdas1234dsad** [comment]
Yes i did

**Comment by jgonzis** [comment]
No user answer...
