### ISSUE TITLE
1.27 Crashing\1.26 doesn't

### ISSUE THREAD

**Issue by dvorel** [Lolliedieb/lolMiner-releases#509]
1.26 mining since release, never crashes. 1.27 stops after few minutes, anything changed with linux zombie mode?

![1 27](https://user-images.githubusercontent.com/24752476/117216726-702a8580-ae00-11eb-97e6-6941353b3dfe.png)

**Comment by jgonzis** [comment]
Can you try please the 1.28a? It seems it was a bug in the 1.27 with the zombie mode...

**Comment by dvorel** [comment]
1.28a working fine
