### ISSUE TITLE
7970 dont work upgrade from 1.21 to latest 1.28a

### ISSUE THREAD

**Issue by ostro78** [Lolliedieb/lolMiner-releases#521]
Hello
My two 7970 gpu that i used to mine bitcoin gold with 3 Gb memory are not detected,
is there anything you can do to still support this old generation ?

All is working fine with 1.21 version.
The log file is empty dont have anything to provide.

Because ETC is still minable with gpu 3gb.

I am avalaible to do further test.

**Comment by jgonzis** [comment]
> Hello
> My two 7970 gpu that i used to mine bitcoin gold with 3 Gb memory are not detected,
> is there anything you can do to still support this old generation ?
> 
> All is working fine with 1.21 version.
> The log file is empty dont have anything to provide.
> 
> Because ETC is still minable with gpu 3gb.
> 
> I am avalaible to do further test.

It seems there is a problem with the 1.28a Windows version, in the Telegram group they are testing it... I suppose it will come very soon the update.

**Comment by ostro78** [comment]
hi, 1.26 is working fine.

I would like to thanx lolminer team as you support old gpu.
Had to test several miner to find one working with my 7970.

**Comment by jgonzis** [comment]
> hi, 1.26 is working fine.
> 
> I would like to thanx lolminer team as you support old gpu.
> Had to test several miner to find one working with my 7970.

Can you try to redownload 1.28a, It should be solved now...
