### ISSUE TITLE
opencl.dllerror

### ISSUE THREAD

**Issue by wolfcaveland** [Lolliedieb/lolMiner-releases#522]
Hi guys, i'm a newbie and a noob at this but, i've setted up the CFG file and runned the programme but it keeps popping up the same error "Opencl.dll not found"

**Comment by jgonzis** [comment]
That seems drivers are not properly installed... Always a Photo help to find the problem :-)

**Comment by wolfcaveland** [comment]
> That seems drivers are not properly installed... Always a Photo help to find the problem :-)

Oh sorry I didn't posted a photo cause it's all in Italian, btw It seems that my pc is too old for that, I've tried to use it cause every mining software that I tried to use on my MacBook Pro 2020 are reaaaaally slow, I gain like 1.5 btt everyday

**Comment by wolfcaveland** [comment]
> That seems drivers are not properly installed... Always a Photo help to find the problem :-)

Is there any good mining software for Mac OS?

**Comment by jgonzis** [comment]
Not at the moment...
