### ISSUE TITLE
Unable to start miner: _M_construct null not valid

### ISSUE THREAD

**Issue by BakeryD** [Lolliedieb/lolMiner-releases#523]
![20210507_135321](https://user-images.githubusercontent.com/39867159/117496100-2b0b6e00-af3c-11eb-864e-2d128400ca6c.jpg)

Os/kernel: Manjaro Linux-5.4.114-1-Manjaro
Glibc version 2.33-4
Gpus:
NVIDIA Rtx 3060 gigabyte OC 12g
AMD Gigabyte rx 570 gaming 4g

Drivers:
Nvidia: 460.73.01
AMD: [20.45](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=opencl-amd&id=99929da87153c0f36a2a9497c38221c12307ecfc)

When starting the miner, it throws an error and core dumps (see images). I'm guessing this is due to a missing library of some sort that it depends on.
Can the dependencies needed to run the program be added to the README.md

**Comment by Lolliedieb** [comment]
No, this seems to be some bug with some string processing ... nothing to do with your library I think. 
Absolutely not sure what causes this - my rig in a mixed state works fine. The 20.45 driver is a bit special though - most rigs run on the 20.40. I will check the 45 manually here if its something related to that one.

**Comment by BakeryD** [comment]
I am about 99% sure it has nothing to do with the driver version because i get this error on 20.40, latest drivers, 19.50 and 20.50. Also i get the error on 1.24a version of the miner as well as 1.26
