### ISSUE TITLE
Crashed and trying to call the emergency.sh

### ISSUE THREAD

**Issue by ChesDonno** [Lolliedieb/lolMiner-releases#524]
emergency.sh does nothing?

So, I don't like doing a Hard Restart anymore and I cannot stop/kill the process and cannot start a new one. Even I try kill the process, I still cannot start a new one.
All my setting is lower than usual.

Does anyone know a way to kill the process so I can start a new one without restarting my system.

OS: Ubuntu 20.04

Thank you for your time

![Screenshot from 2021-05-07 19-51-43](https://user-images.githubusercontent.com/43768935/117520422-b7825480-af6d-11eb-865b-16514d52b991.png)

**Comment by Lolliedieb** [comment]
Note that emergency.sh is a dummy. You need to fill it with the commands you want to get executed. Also make sure the miner then runs with the needed privileges to execute the commands in the .sh file, else it can't work. Originally this file was meant to be used by mining os like hive or mmp to call os watchdog functions that inform the os about the crashed cards.
