### ISSUE TITLE
Don't want to submit a hashrate report to the mining pool

### ISSUE THREAD

**Issue by 13543990638** [Lolliedieb/lolMiner-releases#525]
I don’t want to submit a hashrate report to the mining pool. May I ask if there is a command that can be set. If so, please edit a new complete command parameter and upload it when you update it next time, thank you! ! !

**Comment by jgonzis** [comment]
That it is complicated, unless you use a proxy or something that stop that information

**Comment by jgonzis** [comment]
No problem or feedback... close issue
