### ISSUE TITLE
Why it cannot do reconnection when it is requested a reconnection??

### ISSUE THREAD

**Issue by zhengzongpeng** [Lolliedieb/lolMiner-releases#526]
Below are logs, and in this moment if I push Enter key, it will do reconnection, see log begin "The miner or pool requested a reconnection. Doing so.".  What happen? And is some setting will fix this??

New job received: 0x81001c Epoch: 413 Target: 0000000089705f41
New job received: 0x52d515 Epoch: 413 Target: 0000000089705f41
15:44:34 Average speed (30s): 53.65 mh/s
Pool not sending data for 150 seconds. Reconnecting.
GPU 0: Found a share of difficulty 23.26G
GPU 0: Found a share of difficulty 16.08G
GPU 0: Found a share of difficulty 31.58G
GPU 0: Found a share of difficulty 10.58G
GPU 0: Found a share of difficulty 354.82G
GPU 0: Found a share of difficulty 34.20G
GPU 0: Found a share of difficulty 12.95G
GPU 0: Found a share of difficulty 22.54G
GPU 0: Found a share of difficulty 62.20G
New job received: 0xf0e554 Epoch: 413 Target: 0000000089705f41
The miner or pool requested a reconnection. Doing so.
Lost connection to stratum server cn.sparkpool.com:3333 or server not reachable.
Trying to connect in 1 second
---------------------------------------------
Statistics (15:54:57); Mining: Ethash
Connected to:
Uptime: 2h 29m 54s
                             GPU 0    Total
Name:                  RTX 3060 Ti      Rig
Speed (mh/s):                58.13    58.13
Pool (mh/s):                 48.92    48.92
Shares (A/S/Hw):            55/0/0   55/0/0
Best Share:                 354.8G   354.8G
Power (W):                   106.4    106.4
Efficiency (mh/s/W):         0.544    0.544
Temp (deg C):                   51
Fan Speed (%):                  65
---------------------------------------------
Connected to cn.sparkpool.com:3333  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
New job received: 0x95ec5a Epoch: 413 Target: 0000000089705f41
New job received: 0xc1705d Epoch: 413 Target: 0000000089705f41
Received a defect stratum message: <unspecified file>(1): expected ']' or ','
Lost connection to stratum server cn.sparkpool.com:3333 or server not reachable.
Trying to connect in 1 second
Connected to cn.sparkpool.com:3333  (TLS disabled)
Immediately lost connection on ETHPROXY stratum mode. Reconnect attempt will try EthereumStratum/1.0.0 (Nicehash) stratum mode.
Set Ethash stratum mode: EthereumStratum/1.0.0
Subscribed to stratum server
New job received: ae7639a2 Epoch: 413
New job received: 7e022a18 Epoch: 413
New job received: 9e6a69c3 Epoch: 413
New job received: ff53c5f5 Epoch: 413
New job received: bc393464 Epoch: 413
New job received: 6c8cea8a Epoch: 413

**Comment by jgonzis** [comment]
That happens when pool is not giving  information for long time in dual mining. I recommend you unless you are from China to select a pools more close to you... mining to China Server is not the best option...

**Comment by jgonzis** [comment]
No user answer...
