### ISSUE TITLE
All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . .

### ISSUE THREAD

**Issue by m0nk3s** [Lolliedieb/lolMiner-releases#527]
i got no clue on how to fix this i have been searching on the internet for like 3 hours. I started up yesterday and then boom my entire computer just shut down after like some hours. and i have been looking in all sorts of forum. Please help !

**Comment by brookmg** [comment]
Getting the same result

```
Device 0:
    Name:    AMD Radeon(TM) Vega 8 Graphics
    Address: 4:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  4128 MByte (4060 MByte free)
    Active:  false (Unsupported device or driver version.)
```

**Comment by brookmg** [comment]
Ow got it @jgonzis ... so is it only for lolMiner or any other mining?

**Comment by m0nk3s** [comment]
is i really the GPU ??

**Comment by jgonzis** [comment]
Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 0
Cuda driver detected.
Number of Cuda supported GPUs: 0

Yes it is... only for GPU Mining

> is i really the GPU ??
