### ISSUE TITLE
connetion error

### ISSUE THREAD

**Issue by dbl520** [Lolliedieb/lolMiner-releases#528]
![image](https://user-images.githubusercontent.com/17171011/117573966-77f26e80-b10d-11eb-8865-db5520c00c97.png)
![image](https://user-images.githubusercontent.com/17171011/117573980-92c4e300-b10d-11eb-9ad7-b73a90637efb.png)
麻烦问问这是什么问题

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/17171011/117573966-77f26e80-b10d-11eb-8865-db5520c00c97.png)
> ![image](https://user-images.githubusercontent.com/17171011/117573980-92c4e300-b10d-11eb-9ad7-b73a90637efb.png)
> 麻烦问问这是什么问题

You will not be able to mine with the integrated GPU or that old GPU ETHASH... also in this case is that you haven configured correctly the pool... As you can read server ethash.unmineable.com:13333 is not reachable. That means you are not connecting properly. But As I said, with that hardware you will not be able to mine ETHASH

**Comment by jgonzis** [comment]
No problem or feedback... close issue
