### ISSUE TITLE
Failed to start mining

### ISSUE THREAD

**Issue by lonnietc** [Lolliedieb/lolMiner-releases#529]
Hello,

I have a "Intel NUC NUC7i7DNHE Mini PC/HTPC, Intel Quad-Core i7-8650U Upto 4.2GHz, 32GB DDR4, 512GB SSD, WiFi, Bluetooth, 4k Support, Dual Monitor Capable, Wind" and tried to use your software but get a message:

+---------------------------------------------------------+
|   _       _ __  __ _                   _   ____  ___    |
|  | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ \( _ )   |
|  | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   __) / _ \   |
|  | | (_) | | |  | | | | | |  __/ |    | |_ / __/ (_) |  |
|  |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)_____\___/   |
|                                                         |
|              This software is for mining                |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I, II, III                        |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|              Made by Lolliedieb, May 2021               |
+---------------------------------------------------------+

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    Intel(R) UHD Graphics 620
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  13056 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to ethash.unmineable.com:3333  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: WIN:TC83shNtkQufByK5czBmFr1TnrjFeZbHdZ.LTMining
New job received: 0x447193 Epoch: 413 Target: 000000007e000000
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMiner

Can you please assist?

**Comment by dedizones** [comment]
juste it's not possible mining...

I don't think your "nuk" is an AMD or NVIDIA graphics card with 6GB min

Intel(R) UHD Graphics 620 not possible mining ETH or other

**Comment by jgonzis** [comment]
> juste it's not possible mining...
> 
> I don't think your "nuk" is an AMD or NVIDIA graphics card with 6GB min
> 
> Intel(R) UHD Graphics 620 not possible mining ETH or other

Complete Correct... You will not be able to mine with an integrated GPU... you will need an AMD or NVIDIA with 3-4Gb for ETC or  more for ETH.

**Comment by lonnietc** [comment]
Thanks All.

Guess that I am out of luck for the time being.
