### ISSUE TITLE
GRIN hardfork

### ISSUE THREAD

**Issue by kr-deps** [Lolliedieb/lolMiner-releases#53]
GRIN is supposed to fork to a new algo on July, 16.

https://forum.grin.mw/t/grin-v4-0-0-network-upgrade-hard-fork-3-july-2020/7001

Do you plan on supporting the hardfork? Cuckaroom29 is changing to Cuckarooz29.

**Comment by Lolliedieb** [comment]
I know it changed... but due to lack of users C29M was not a profitable algorithm for me to work on :(
