### ISSUE TITLE
How to Stop Onboard Graphics

### ISSUE THREAD

**Issue by techric** [Lolliedieb/lolMiner-releases#532]
Installed the latest version. 

The onboard video graphics are being utilized along with  3 x 1070s. 

How can I stop the onboard graphics from mining? 

CPU: Intel Pentium G4400 @ 3.3 GHz
RAM: 16 GB
OS: Windows 10 
MoBo: BIOStar TB250-BTC
![GPU  2](https://user-images.githubusercontent.com/6571806/117659316-6c309780-b161-11eb-822c-a79c7ec3a65e.jpeg)
![GPU](https://user-images.githubusercontent.com/6571806/117659335-718de200-b161-11eb-923a-c62346379757.jpeg)

**Comment by jgonzis** [comment]
> Installed the latest version.
> 
> The onboard video graphics are being utilized along with 3 x 1070s.
> 
> How can I stop the onboard graphics from mining?
> 
> CPU: Intel Pentium G4400 @ 3.3 GHz
> RAM: 16 GB
> OS: Windows 10
> MoBo: BIOStar TB250-BTC

Hi,

You should use add the line --devices 0,2 that for example will use device 0 and 2 for mining. 

--devices 1,2 will only use devices 1 and 2.

Only add that --devices gpus_separated_by_commas

**Comment by jgonzis** [comment]
请在Windows中增加交换文件。

在行的末尾添加--nocolor，以更好地查看信息。 

[https://www.windowscentral.com/how-change-virtual-memory-size-windows-10](https://www.windowscentral.com/how-change-virtual-memory-size-windows-10) 60000MB

**Comment by techric** [comment]
> > Installed the latest version.
> > The onboard video graphics are being utilized along with 3 x 1070s.
> > How can I stop the onboard graphics from mining?
> > CPU: Intel Pentium G4400 @ 3.3 GHz
> > RAM: 16 GB
> > OS: Windows 10
> > MoBo: BIOStar TB250-BTC
> 
> Hi,
> 
> You should use add the line --devices 0,2 that for example will use device 0 and 2 for mining.
> 
> --devices 1,2 will only use devices 1 and 2.
> 
> Only add that --devices gpus_separated_by_commas

Thanks for the advise, but I don't know where or how to even enter that information. 

Can you provide some more detailed instructions on how to accomplish this? 

Thanks

**Comment by techric** [comment]
> You need to edit the mine_eth.bat file and go to the line lolMiner.exe and at the end add the "--devices ..."
> 
> The problem of GPU0 is that you have it limited, I suppose you have make some reduction in MSI Afterburner or similar.

Ok, here's what I've done ... 

1) Went into the [mine.eth.bat] file with right-click > Edit 


2) Made your suggested changes in bold. 


************   BEGIN   ***************
@echo off

setlocal enableDelayedExpansion

REM #############################
REM ##     Begin of user-editable part      ##
REM #############################

set POOL = miningPool:portNumber
set"WALLET=walletAddress.lolMinerWorker"

REM #############################
REM ##        End of user-editable part       ##
REM #############################

:loop
lolMiner.exe -- algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit **--devices 0, 1**
if %ERRORLEVEL% == 42 (
                 timeout 10 
                 go to loop
) 

pause


************   END   ***************

Nothing happened. 

Then I tried -- devices 0, 1, 2, 3, 4, 5, 6

Still nothing. No changes. 


GPU 0 isn't limited at all. No MSI Afterburner modifications.

**Comment by techric** [comment]
CORRECTION: The hash rate balanced out among the 4 out 4 attached GPUs. 

Now, check this out. I added another 1070 to the rig for a total of five (5) GPUs. 

This is the new issues  that I get: (see photo)


1) lolminer detects all 5 out of 5 of the 1070 GPUs. 

2) However, device 0 is "detected as crashed". This remains constant even after restarting.  

3) The error message "unrecoverable memory error" is rotating between the other GPU/Devices: 1, 2, 3, 4, and 5.

![GPU 3](https://user-images.githubusercontent.com/6571806/117704690-c3019580-b190-11eb-9255-90c2c4fe21af.jpeg)

**Comment by techric** [comment]
I've solved the last two errors by increasing the Windows 10 Virtual Memory. 

Essentially, go into Advanced Settings and customize virtual memory by calculating [ # of GPUs] x [GPU RAM in MBs] = Virtual Memory Initial and Max.

6 x 1070 8 GB = 48,000 MB Initial and Max 



You can find the specific solution to doing this on Nicehash's FAQ/Support pages. 

I've attached screenshots. 


Thanks for all of your help. 


<img width="949" alt="Screen Shot 2021-05-10 at 1 39 31 PM" src="https://user-images.githubusercontent.com/6571806/117708246-2db4d000-b195-11eb-837f-389e3bbe4a1e.png">
<img width="1006" alt="Screen Shot 2021-05-10 at 1 39 18 PM" src="https://user-images.githubusercontent.com/6571806/117708249-2e4d6680-b195-11eb-8610-d5776ca9a277.png">
