### ISSUE TITLE
win10 可以   win7 不可以？？？

### ISSUE THREAD

**Issue by 123456223** [Lolliedieb/lolMiner-releases#534]
可以帮我看一下 是不是已经再挖了
![2](https://user-images.githubusercontent.com/83933729/117599927-79f41600-b17d-11eb-8364-f6e0b09144b8.png)

**Comment by jgonzis** [comment]
> 可以帮我看一下 是不是已经再挖了
> ![2](https://user-images.githubusercontent.com/83933729/117599927-79f41600-b17d-11eb-8364-f6e0b09144b8.png)

请在Windows中增加交换文件。

在行的末尾添加--nocolor，以更好地查看信息。

https://www.windowscentral.com/how-change-virtual-memory-size-windows-10 60000MB

**Comment by jgonzis** [comment]
No problem or feedback... close issue
