### ISSUE TITLE
bestshare

### ISSUE THREAD

**Issue by needhelp101** [Lolliedieb/lolMiner-releases#54]
HI, 

Could us solo miners get some form of top 10 best share display, like what xmrig and xmrstak have.. 

Thanks

**Comment by Lolliedieb** [comment]
Good idea - don't know what exactly xmrig does but let me have a lool. Thanks for suggestion :)

**Comment by Lolliedieb** [comment]
Implemented with lolMiner 1.08 / 1.09 for Ethash - will come for other algos gradually.
