### ISSUE TITLE
windows 1.28a don't have mine_eth_4G.bat file

### ISSUE THREAD

**Issue by 2250749979** [Lolliedieb/lolMiner-releases#540]
![image](https://user-images.githubusercontent.com/41992301/117802670-579aef00-b288-11eb-9a32-98ef041585ba.png)

**Comment by christianc24** [comment]
Hello, I am looking for it aswell. I know I need to tweak --4g-alloc-size parameter and  other  setting but cant seem to find where. let me know if you find anything :)

**Comment by pdieppa** [comment]
@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --4g-alloc-size 4024 --keepfree 8 
timeout 10

**Comment by jgonzis** [comment]
No more option to mine with 4G Gpus in Windows.
