### ISSUE TITLE
Crash in 1.28A after some time...

### ISSUE THREAD

**Issue by Visikek** [Lolliedieb/lolMiner-releases#542]
![eth_crash](https://user-images.githubusercontent.com/84043620/117876564-cd608400-b2a3-11eb-9e8b-859b8012c3c9.png)

Any idea why is this happening? 
This happened with me twice today. First after 12 hours mining and the second about 3 hours later.

**Comment by jgonzis** [comment]
> ![eth_crash](https://user-images.githubusercontent.com/84043620/117876564-cd608400-b2a3-11eb-9e8b-859b8012c3c9.png)
> 
> Any idea why is this happening?
> This happened with me twice today. First after 12 hours mining and the second about 3 hours later.

That is normally a Windows driver crash... in the bat file you should have a loop created, it normally comes with it... can you prove it is?. Because in case of a crash it automaticly restart the miner

**Comment by jgonzis** [comment]
No user answer...
