### ISSUE TITLE
Can't run lolminer in ubuntu

### ISSUE THREAD

**Issue by konohanaruto** [Lolliedieb/lolMiner-releases#544]
```
$ ./lolMiner
bash: ./lolMiner: No such file or directory


$ file lolMiner
lolMiner: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-86-64.so.2, for GNU/Linux 3.2.0, not stripped
```

It does not seem to be a valid executable file?

**Comment by ChesDonno** [comment]
cd lolMiner/1.2xx     enter
./lolMiner    enter

**Comment by konohanaruto** [comment]
![image](https://user-images.githubusercontent.com/18207841/118343932-51459500-b55e-11eb-89f8-dfef5854c50b.png)

It is not an executable file, please help me. thank you

**Comment by jgonzis** [comment]
Which version of Ubuntu are you running?. 

Why you don't run the sh file that is the one that has de parameters to run lolMiner?

**Comment by konohanaruto** [comment]
![image](https://user-images.githubusercontent.com/18207841/118352953-cfbe2900-b596-11eb-974f-d10024a7f8d1.png)

Ubuntu 20.04.2 LTS
lolMiner version：lolMiner 1.28a

**Comment by konohanaruto** [comment]
![image](https://user-images.githubusercontent.com/18207841/118353338-6212fc80-b598-11eb-9731-12feec1e3be4.png)

Ubuntu 20.04.2 LTS
lolMiner version：lolMiner 1.28a

**Comment by konohanaruto** [comment]
![image](https://user-images.githubusercontent.com/18207841/118353442-c930b100-b598-11eb-895a-72f7a40ca27d.png)

**Comment by jgonzis** [comment]
Found it ... it is compiled for x86_64... that's the problem... which GPU do you have?

**Comment by konohanaruto** [comment]
I understand, I don't have a GPU, I will install it. thank you

**Comment by jgonzis** [comment]
And you need x86_64 CPU

**Comment by konohanaruto** [comment]
thank u
