### ISSUE TITLE
Is "GlIBC_ 2.18" necessary?

### ISSUE THREAD

**Issue by StubbornYang** [Lolliedieb/lolMiner-releases#554]
Version: Latest release  1.28
Description:
I tried to run lolmine on CentOS 7.4 and get an error "./lolMiner: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./lolMiner)".
I want to know that Is "GlIBC_ 2.18" necessary?If it's not necessary, can you reduce the glibc version the next time you compile the program.
I can't update "libc.so.6" because I have no root authority.

**Comment by jgonzis** [comment]
Could you try with ubuntu? It could be old librarys in your CentOS

**Comment by jgonzis** [comment]
No problem or feedback... close issue
