### ISSUE TITLE
Time out on DNS resolve. Retrying. Lost connection to stratum server 

### ISSUE THREAD

**Issue by zmx110** [Lolliedieb/lolMiner-releases#555]
when run the programe,
Time out on DNS resolve. Retrying.
Lost connection to stratum server eth.f2pool:6688 or server not reachable.
Trying to connect in 1 second
what should i do 
thanks!

**Comment by jgonzis** [comment]
That is a internet problem, it could be blocked by the firewall... try other eth server too...

**Comment by jgonzis** [comment]
No problem or feedback... close issue
