### ISSUE TITLE
1.28a decreased hashrate?

### ISSUE THREAD

**Issue by pierrediderot** [Lolliedieb/lolMiner-releases#556]
Hi guys,
I would like to make a report, when downloading version 1.28a, I noticed that the hashrate has decreased a little.
I've been using version 1.26, and I noticed a drop of + - .1 / .2.

Version 1.28a with an average of 23.19 / 23.31.
Version 1.26 has an average of 23.35 / 23.49.

Thanks guys, grateful for the team's work!

**Comment by jgonzis** [comment]
Which GPU? which mode?

**Comment by pierrediderot** [comment]
GPU: Galax GeForce GTX 1060 6GB.
ALGO: Ethash.
S.O: Linux.

I'm using 1.26.
I just downloaded the new version (1.28a) and ran it with my data (pool / wallet).
I soon noticed that the hashrate had dropped a bit, so I decided to report it to the team.
-
The same happened with a friend, but he uses GTX 1080ti, S.O (Windows).

**Comment by jgonzis** [comment]
> GPU: Galax GeForce GTX 1060 6GB.
> ALGO: Ethash.
> S.O: Linux.
> 
> I'm using 1.26.
> I just downloaded the new version (1.28a) and ran it with my data (pool / wallet).
> I soon noticed that the hashrate had dropped a bit, so I decided to report it to the team.
> 
> The same happened with a friend, but he uses GTX 1080ti, S.O (Windows).

Yes 1.28a has made a new kernell with less Watts consume for Pascal card... can you try to add "--mode a" in the parameter... that will run the old kernel that is more Watts aggresive.  that should give around 0.15Mhs more Mhs at around 3W cost...
