### ISSUE TITLE
"insufficient memory for DAG epoch 414 will be in zombie mode with reduced hashrate" error 

### ISSUE THREAD

**Issue by king1267** [Lolliedieb/lolMiner-releases#563]
I just installed and set up lolMiner and it works for the most part but my hash rates are really low considering I have a 4Gb RX580. Can someone help me figure out how to fix this error? Along with that, my worker does not show up on etherminer.org. I checked and I have all the right ports and pools entered but it shows up despite it saying connected to us1.ethermine.org:444 (TLS disabled)

**Comment by jgonzis** [comment]
That's not an error, is a great function of the lolMiner. It allows you to mine ETH with 4Gb cards. You can only do this in Linux, in Windows will be 0Mhs... If you want full speed you can also try to mine ETC

**Comment by king1267** [comment]
Oh ok, thank you so much!!
