### ISSUE TITLE
About Ezil worker name error！

### ISSUE THREAD

**Issue by lzzyon** [Lolliedieb/lolMiner-releases#564]
When lolminer was working at Ezil, the worker name was displayed incorrectly, it was displayed as the address of zil.

**Comment by jgonzis** [comment]
> When lolminer was working at Ezil, the worker name was displayed incorrectly, it was displayed as the address of zil.

Can you put your config file, to try to see where is the mistake?. 

Many thanks

**Comment by lzzyon** [comment]
> > When lolminer was working at Ezil, the worker name was displayed incorrectly, it was displayed as the address of zil.
> 
> Can you put your config file, to try to see where is the mistake?.
> 
> Many thanks

It can work normally, but the worker name displayed in the mine pool is not the set worker name, but the ZIL address of ezil.

**Comment by jgonzis** [comment]
With the config file I can tell you where to add the worker name... 

You can try to add in the config lane --worker NAME_OF_THE_RIG and in --dualtratum that you have put  the ETH_WALLET@ETHPOOL, if you want to have the name of the rig too, you have to put ETH_WALLET.NAME_OF_THE_RIG@ETHPOOL  . If after that it doesn't work I think the best is to see the config to try to help you easily.

**Comment by anielk** [comment]
I have the same problem version 1.31 
I use the standard config file. instead of the workername it show the wallet name:

my config:

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eu.ezil.me:5555"
set "ZILWALLET="
set "ETHWALLET="	

set "WORKER=RX5700xt"									

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################


if exist %CD%"\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist %MyVariable% goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
%MyVariable% --algo ETHASH --pool !POOL! --user !ETHWALLET!.!ZILWALLET! --worker !WORKER!  --enablezilcache  --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
%MyVariable% --algo ETHASH --pool !POOL! --user !ETHWALLET!.!ZILWALLET! --worker !WORKER!  --enablezilcache --watchdog exit --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause

**Comment by jgonzis** [comment]
> I have the same problem version 1.31
> I use the standard config file. instead of the workername it show the wallet name:
> 
> my config:
> 
> @echo off
> 
> setlocal enableDelayedExpansion
> 
> Rem #################################
> Rem ## Begin of user-editable part ##
> Rem #################################
> 
> set "POOL=eu.ezil.me:5555"
> set "ZILWALLET="
> set "ETHWALLET="
> 
> set "WORKER=RX5700xt"
> 
> Rem #################################
> Rem ## End of user-editable part ##
> Rem #################################
> 
> if exist %CD%"\lolMiner.exe" goto infolder
> echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
> if exist %MyVariable% goto WindowsVer
> echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> goto END
> 
> :infolder
> set MyVariable=%CD%\lolMiner.exe
> 
> :WindowsVer
> for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
> if "%version%" == "10.0" goto W10
> goto OtherW
> 
> :W10
> %MyVariable% --algo ETHASH --pool !POOL! --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! --enablezilcache --watchdog exit
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto W10
> )
> goto END
> 
> :OtherW
> %MyVariable% --algo ETHASH --pool !POOL! --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! --enablezilcache --watchdog exit --nocolor
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto OtherW
> )
> 
> :END
> pause

Just to confirm, you have delete your ETH and zil wallet...

**Comment by anielk** [comment]
> > I have the same problem version 1.31
> > I use the standard config file. instead of the workername it show the wallet name:
> > my config:
> > @echo off
> > setlocal enableDelayedExpansion
> > Rem #################################
> > Rem ## Begin of user-editable part ##
> > Rem #################################
> > set "POOL=eu.ezil.me:5555"
> > set "ZILWALLET="
> > set "ETHWALLET="
> > set "WORKER=RX5700xt"
> > Rem #################################
> > Rem ## End of user-editable part ##
> > Rem #################################
> > if exist %CD%"\lolMiner.exe" goto infolder
> > echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> > for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
> > if exist %MyVariable% goto WindowsVer
> > echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> > goto END
> > :infolder
> > set MyVariable=%CD%\lolMiner.exe
> > :WindowsVer
> > for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
> > if "%version%" == "10.0" goto W10
> > goto OtherW
> > :W10
> > %MyVariable% --algo ETHASH --pool !POOL! --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! --enablezilcache --watchdog exit
> > if %ERRORLEVEL% == 42 (
> > timeout 10
> > goto W10
> > )
> > goto END
> > :OtherW
> > %MyVariable% --algo ETHASH --pool !POOL! --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! --enablezilcache --watchdog exit --nocolor
> > if %ERRORLEVEL% == 42 (
> > timeout 10
> > goto OtherW
> > )
> > :END
> > pause
> 
> Just to confirm, you have delete your ETH and zil wallet...

Yes I did

**Comment by anielk** [comment]
any update on this?

**Comment by jgonzis** [comment]
> any update on this?

 --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! Replace for:

 --user !ETHWALLET!.!ZILWALLET!.!WORKER! 

That's all 😊

**Comment by anielk** [comment]
> > any update on this?
> 
>  --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! Replace for:
> 
> --user !ETHWALLET!.!ZILWALLET!.!WORKER!
> 
> That's all 😊

Do you need the exclamation marks?
like
--user: !ETHwallet address!.!zila wallet address!.!AMD! ?

**Comment by jgonzis** [comment]
> > > any update on this?
> > 
> > 
> >  --user !ETHWALLET!.!ZILWALLET! --worker !WORKER! Replace for:
> > --user !ETHWALLET!.!ZILWALLET!.!WORKER!
> > That's all 😊
> 
> Do you need the exclamation marks?
> like
> --user: !ETHwallet address!.!zila wallet address!.!AMD! ?

No no... only copy as I send you and change the parameters at the beginning.

That is the information that the system will copied directly to the parameters  !ETHWALLET!.!ZILWALLET!.!WORKER!

set "POOL=eu.ezil.me:5555"
set "ZILWALLET="
set "ETHWALLET="
set "WORKER=RX5700xt"

**Comment by anielk** [comment]
nevermind, it is without it.
But now I used my old line and not the one which is included. it now works thanks!

lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWallet.ZILWallet.RX580 --devices 0

**Comment by jgonzis** [comment]
> nevermind, it is without it.
> But now I used my old line and not the one which is included. it now works thanks!
> 
> lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWallet.ZILWallet.RX580 --devices 0

Perfect 👌

**Comment by anielk** [comment]
When using the miner like this it keeps crashing, lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWallet.ZILWallet.RX580 --devices 0. But when using like this the name does not work, but it does not crash:
set "POOL=eu.ezil.me:5555"
set "ZILWALLET=zilwallet"
set "ETHWALLET=eth wallet"
set "WORKER=RX580"

this is the message I get:

GPU 0: Starting DAG generation (normal mode)
GPU 0: DAG generation completed (2060 ms)
0x00007FFF9E5E9B0E (0x0000000000000300 0xFFFFFFFFFFFFFFFF 0x0000000000000300 0x0000021CA0EA8A00), aclWriteToMem() + 0x153914E bytes(s)
0x00007FFF9CE7B7C1 (0xFFFFFFFFFFFFFFFF 0x0000021CA0EA8A00 0x0000000000000100 0x0000021CB2466190), clGetPipeInfo() + 0x93351 bytes(s)
0x00007FFF9CE562C9 (0x0000021CAA34AA80 0x0000021CBC7C2E30 0x0000021CB1D99160 0x0000021CBC79AAF0), clGetPipeInfo() + 0x6DE59 bytes(s)
0x00007FFF9CE63696 (0x0000000000000600 0x0000009E6BFFF5A0 0x00007FF700000000 0x00007FF700000027), clGetPipeInfo() + 0x7B226 bytes(s)
0x00007FFF9CE1C94F (0x0000000000000000 0x0000021CA3E0A028 0x0000021C00000000 0x0000000000000000), clGetPipeInfo() + 0x344DF bytes(s)
0x00007FFF9CE0421C (0x0000021CB2960B01 0x0000009E6BFFF7E8 0x0000000000000008 0x0000000000000000), clGetPipeInfo() + 0x1BDAC bytes(s)
0x00007FFF9CDD8AA8 (0x0000000000000000 0x0000021CA3E09FE0 0x0000000000000001 0x0000009E6BFFF8A0), clBuildProgram() + 0x168 bytes(s)
0x00007FF743698043 (0x0000009E6BFFFB00 0x0000000004000000 0x0000000000000000 0x0000009E6BFFFBB0)
0x00007FF7436A6AB8 (0x0000000400000004 0x0000021CB1DA64B0 0x0000009E6BEFFBA8 0x0000009E6BFFFDC8)
0x00007FF7436A51D4 (0x0000021CBC7C9770 0x0000000000000000 0x0000000000000005 0x0000000000000005)
0x00007FF7435B4F59 (0x0000021CBC7C9770 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF7438E9C54 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFFE6F27034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFFE8CC2651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

is there a solution for this?

**Comment by jgonzis** [comment]
> 0x00007FF7435B4F59 (0x0000021CBC7C9770 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FF7438E9C54 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)

Adrenaline Driver?
Windows version?
GPU Model

**Comment by anielk** [comment]
ah sorry for that:
Adrenaline Driver 21.4.1
Windows version 21H1 (19043.1165)
GPU Model AMD RX580 8GB

**Comment by anielk** [comment]
now I updated the AMD drivers to: 21.8.1
changed the config to: 
--user !ETHWALLET!.!ZILWALLET! --worker !WORKER! Replace for:

--user !ETHWALLET!.!ZILWALLET!.!WORKER!

then it was running for a couple a minutes then it crashed again:

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 3
No Cuda driver or GPUs detected.
Device 0:
    Name:    Radeon RX 580 Series
    Address: 1:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8192 MByte (8137 MByte free)
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash OpenCL)
Device 1:
    Name:    Radeon RX 580 Series
    Address: 1:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8192 MByte (8137 MByte free)
    Max epoch (approx): 894
    Active:  true (Selected Algorithm: ETHash OpenCL)
Device 2:
    Name:    Intel(R) HD Graphics 4600
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  1629 MByte
    Active:  false (not selected)

the system has only one RX580 not 2

error message:

GPU 0: DAG generation completed (39014 ms)
GPU 0: DAG verification passed
New job received: 0xc030f0 Epoch: 435 Target: 0000000100000000
New job received: 0x8235ba Epoch: 435 Target: 0000000100000000
New job received: 0x2cb956 Epoch: 435 Target: 0000000100000000
GPU 1: DAG generation completed (40685 ms)
0x00007FF88C206670 (0x000001E2F9AB6FA0 0x000001E2E66ED970 0x0000000000000000 0x000001E2F9B20C10), clGetPipeInfo() + 0x595A0 bytes(s)
0x00007FF88C1FD3B0 (0x000001E200000000 0x00007FF88E078D28 0x000001E2F8E99060 0x0000005F23EFF788), clGetPipeInfo() + 0x502E0 bytes(s)
0x00007FF88C23F2F3 (0x0000000000000018 0x000001E2F9BE6150 0x000001E2F8E99060 0x0000005F23EFF910), clGetPipeInfo() + 0x92223 bytes(s)
0x00007FF88C23F4B9 (0x000001E2EBC6E780 0x000001E2EB8C9FB0 0x0000005F23EFF9C0 0x0000000000000FA0), clGetPipeInfo() + 0x923E9 bytes(s)
0x00007FF88C212948 (0x000001E2EB8C9FB0 0x000001E2F9BE6150 0x000001E2F8E9A000 0x0000000000000000), clGetPipeInfo() + 0x65878 bytes(s)
0x00007FF88C1BE64E (0x000001E2EBA41EB0 0x000001E2EB8C9F90 0x000001E2EBA41EB0 0x000001E2F9AAA370), clGetPipeInfo() + 0x1157E bytes(s)
0x00007FF88C1BE741 (0x000001E2EBC6F510 0x0000000000000000 0x000001E2EBC6F510 0x0000000000000000), clGetPipeInfo() + 0x11671 bytes(s)
0x00007FF88C1ADCEA (0x000001E2EBC6F510 0x0000000000000000 0x0000000000000000 0x0000000000000000), clGetPipeInfo() + 0xC1A bytes(s)
0x00007FF88C1CE469 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), clGetPipeInfo() + 0x21399 bytes(s)
0x00007FF8D92C7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF8DB242651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

am I doing something wrong?

**Comment by anielk** [comment]
I think --devices 0 did the trick. It is still working!
every minute is waisting money you know :) 
I really glad of the good support!

**Comment by jgonzis** [comment]
> I think --devices 0 did the trick. It is still working!
> every minute is waisting money you know :)
> I really glad of the good support!

Your answer was faster than mine :-)... Keep mining

**Comment by anielk** [comment]
after updating to version 1.35 it is broke again.
lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT.RX580 --devices 0
was there a change?

**Comment by jgonzis** [comment]
> after updating to version 1.35 it is broke again. lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT.RX580 --devices 0 was there a change?

lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT --worker RX580 --devices 0

**Comment by jsangeorzan** [comment]
I Just tried the new 1.36a version and Ezil is still showing a 0 under workers.  I am using HiveOS.

**Comment by anielk** [comment]
i'm using windows 10, I have the same problem it is still showing indeed a 0

**Comment by anielk** [comment]
> > after updating to version 1.35 it is broke again. lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT.RX580 --devices 0 was there a change?
> 
> lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT --worker RX580 --devices 0

when using this line, it is not showing the worker name but the zil wallet number :(

**Comment by jgonzis** [comment]
> > > after updating to version 1.35 it is broke again. lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT.RX580 --devices 0 was there a change?
> > 
> > 
> > lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT --worker RX580 --devices 0
> 
> when using this line, it is not showing the worker name but the zil wallet number :(

have you try new 1.36a?... it seems has some solution to EZIL pool

**Comment by anielk** [comment]
> > > > after updating to version 1.35 it is broke again. lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT.RX580 --devices 0 was there a change?
> > > 
> > > 
> > > lolMiner.exe --algo ETHASH --pool eu.ezil.me:5555 --ethstratum ETHPROXY --user ETHWALLET.ZILWAKKT --worker RX580 --devices 0
> > 
> > 
> > when using this line, it is not showing the worker name but the zil wallet number :(
> 
> have you try new 1.36a?... it seems has some solution to EZIL pool

Good advice, I just tested this version and indeed it does work now!
thanks you!
