### ISSUE TITLE
GPU 0: Allocation of DAG failed with error: Memory object allocation failure GPU 0: will be stopped.

### ISSUE THREAD

**Issue by Lukasko84** [Lolliedieb/lolMiner-releases#567]
![image](https://user-images.githubusercontent.com/84182754/118272145-77b5f280-b4c2-11eb-90f5-87831b4ee775.png)
Hi all,  could you please help me with mentioned issue? This PC was working about 4 month as miner without problem, but from yesterday I obtained this message and mining is not working... I have RTX 2070 SUPER with 8 GB RAM graphic card. It is strange, it is possible to lost RAM on graphic card? Or what?

**Comment by jgonzis** [comment]
I think you are in Windows... you need to increase the Swap File :

[https://www.howtogeek.com/126430/htg-explains-what-is-the-windows-page-file-and-should-you-disable-it/](https://www.howtogeek.com/126430/htg-explains-what-is-the-windows-page-file-and-should-you-disable-it/)

Put 60000 - 60000 in both options min and max

**Comment by Lukasko84** [comment]
Thank you, but I think that I found cause of this case. C:/Program files/Experience/.. that was running on demand, seems to be that somebody used my computer for mining... app atomloudgre was stopped, deleted and now it is working as previously.
![image](https://user-images.githubusercontent.com/84182754/118322190-06e0fb80-b4ff-11eb-834d-d3446447153d.png)

@ also added information about virus:
Trojan.MulDrop16.13005
Added to the virus database: 2021-03-02

Virus description added: 2021-03-03

Technical Information
To ensure autorun and distribution
Creates or modifies the following files
%APPDATA%\microsoft\windows\start menu\programs\startup\startpa.bat
Modifies file system
Creates the following files
%ProgramFiles%\experience\bottlewater.exe
%ProgramFiles%\experience\copy.bat
%ProgramFiles%\experience\sonis.vbs
%ProgramFiles%\experience\startpa.bat
%ProgramFiles%\experience\sonis.bat
Miscellaneous
Searches for the following windows
ClassName: 'EDIT' WindowName: ''
Creates and executes the following
'<SYSTEM32>\wscript.exe' "%ProgramFiles%\Experience\sonis.vbs"
'%ProgramFiles%\experience\bottlewater.exe' --algo ETHASH --pool eth-eu1.nanopool.org:9999 --user 0x32076c6c1bdca78233f1a31d7cff9a53d6a65c45.2A10625 --watchdog exit
'<SYSTEM32>\cmd.exe' /c ""%ProgramFiles%\Experience\sonis.bat" "' (with hidden window)
Executes the following
'<SYSTEM32>\cmd.exe' /c ""%ProgramFiles%\Experience\copy.bat" "
'<SYSTEM32>\xcopy.exe' startpa.bat "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\". /Y
'<SYSTEM32>\cmd.exe' /c ""%ProgramFiles%\Experience\sonis.bat" "

**Comment by jgonzis** [comment]
> Thank you, but I think that I found cause of this case. C:/Program files/Experience/.. that was running on demand, seems to be that somebody used my computer for mining... app atomloudgre was stopped, deleted and now it is working as previously.
> ![image](https://user-images.githubusercontent.com/84182754/118322190-06e0fb80-b4ff-11eb-834d-d3446447153d.png)
> 
> @ also added information about virus:
> Trojan.MulDrop16.13005
> Added to the virus database: 2021-03-02
> 
> Virus description added: 2021-03-03
> 
> Technical Information
> To ensure autorun and distribution
> Creates or modifies the following files
> %APPDATA%\microsoft\windows\start menu\programs\startup\startpa.bat
> Modifies file system
> Creates the following files
> %ProgramFiles%\experience\bottlewater.exe
> %ProgramFiles%\experience\copy.bat
> %ProgramFiles%\experience\sonis.vbs
> %ProgramFiles%\experience\startpa.bat
> %ProgramFiles%\experience\sonis.bat
> Miscellaneous
> Searches for the following windows
> ClassName: 'EDIT' WindowName: ''
> Creates and executes the following
> '\wscript.exe' "%ProgramFiles%\Experience\sonis.vbs"
> '%ProgramFiles%\experience\bottlewater.exe' --algo ETHASH --pool eth-eu1.nanopool.org:9999 --user 0x32076c6c1bdca78233f1a31d7cff9a53d6a65c45.2A10625 --watchdog exit
> '\cmd.exe' /c ""%ProgramFiles%\Experience\sonis.bat" "' (with hidden window)
> Executes the following
> '\cmd.exe' /c ""%ProgramFiles%\Experience\copy.bat" "
> '\xcopy.exe' startpa.bat "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup". /Y
> '\cmd.exe' /c ""%ProgramFiles%\Experience\sonis.bat" "

That was a Virus comming from outside... they put a nice name to avoid to be deleted. thx for sharing
