### ISSUE TITLE
I'm having trouble with bootup of lolminer! please help!

### ISSUE THREAD

**Issue by trillllzyy** [Lolliedieb/lolMiner-releases#568]
Anytime I try to boot up lolminer, the code i'm left with is, "no user account or wallet to mine on configured". I know I have the correct wallet set up and the right pool address. Another thing it says is, "Environment Variable us1.ethermine.org:4444 not defined.  I'm not sure what to do and it seems as though nobody else on the internet has had this problem. Thank you in advance!

**Comment by jgonzis** [comment]
> Anytime I try to boot up lolminer, the code i'm left with is, "no user account or wallet to mine on configured". I know I have the correct wallet set up and the right pool address. Another thing it says is, "Environment Variable us1.ethermine.org:4444 not defined. I'm not sure what to do and it seems as though nobody else on the internet has had this problem. Thank you in advance!

Please can you put a photo of your configuration mine_eth file?. In case you are in a Mining OS then the flightsheet you are using.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
