### ISSUE TITLE
All devices deselected or failed compatiblity check. Closing lolMiner (BEAM - GTX 980)

### ISSUE THREAD

**Issue by P4R4NORM4L** [Lolliedieb/lolMiner-releases#569]
Can you not mine BEAM with GTX 980s ? I have installed the latest Nvidia Driver on Linux 460, let me know if you have an idea of what could be wrong

**Comment by jgonzis** [comment]
> Can you not mine BEAM with GTX 980s ? I have installed the latest Nvidia Driver on Linux 460, let me know if you have an idea of what could be wrong

At the moment with Nvidia CUDA is ETC and ETH, I think new realease will take CUDA also for more algo

**Comment by P4R4NORM4L** [comment]
Ok so i have to wait til there's an update to the software ... thanks

**Comment by jgonzis** [comment]
Now Cuda support in Beam, but with 980 not much profit expected.
