### ISSUE TITLE
Feature request: Alternative device selection, use Slot number

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#57]
I'd like an alternative device selector.

Could you add a new parameter that allows selecting the devices by their slot number (instead of the device index).

Reason:
I am integrating you miner into NemosMiner (https://nemosminer.com/)
When the Citrix Connector gets installed it adds a new device (CitrixIndirectDisplayAdapter) which affects extisting device IDs:

Before:

![image](https://user-images.githubusercontent.com/30080938/89332375-96fe3480-d693-11ea-94d0-362c56e596e5.png)

After:

![image](https://user-images.githubusercontent.com/30080938/89332460-ba28e400-d693-11ea-99fe-97bcab1a763c.png)

The slot number (Address) is the only value that remains unchanged in this scenario:

![image](https://user-images.githubusercontent.com/30080938/89332833-58b54500-d694-11ea-91c8-2510f6da348e.png)

**Comment by Lolliedieb** [comment]
Liked the request - and just implemented it in 1.06 dev version :D 

![grafik](https://user-images.githubusercontent.com/40234439/89511666-84d6e000-d7d2-11ea-8467-908431848578.png)

**Comment by UselessGuru** [comment]
Liked the request
👍 

> and just implemented it in 1.06 dev version :D

Where can I find it?

**Comment by Lolliedieb** [comment]
Feature is shipped with new 1.06 release :)
