### ISSUE TITLE
The  _4g bat file is missing in  version 1.28

### ISSUE THREAD

**Issue by LordVoldermote** [Lolliedieb/lolMiner-releases#570]
Hi guys, 

I am a tech noob. I am setting up lolminer based on [Son of a tech](https://www.youtube.com/watch?v=xqny5SSFRTo). However I cannot find the mine_eth_4G.bat file, but even the 'readme' says to have it. Am I missing something? Please advise: 
I have a NVDIA GeForce GTX 1650 GDDR5 @4GB (128 bits), fixed in a ASUS Strix gaming laptop. 

Hereby attaching the list of files available in the latest 1.28a. 
![image_2021-05-15_083618](https://user-images.githubusercontent.com/84215175/118346386-9e266d00-b558-11eb-9d30-a1c1d18237d8.png)

**Comment by jgonzis** [comment]
> Hi guys,
> 
> I am a tech noob. I am setting up lolminer based on [Son of a tech](https://www.youtube.com/watch?v=xqny5SSFRTo). However I cannot find the mine_eth_4G.bat file, but even the 'readme' says to have it. Am I missing something? Please advise:
> I have a NVDIA GeForce GTX 1650 GDDR5 @4GB (128 bits), fixed in a ASUS Strix gaming laptop.
> 
> Hereby attaching the list of files available in the latest 1.28a.
> ![image_2021-05-15_083618](https://user-images.githubusercontent.com/84215175/118346386-9e266d00-b558-11eb-9d30-a1c1d18237d8.png)

4G in Windows is not working any more, the driver in memory of the card, doesn't allow you to put the 4Gb ETH mining. I recommend you to try ETC for example or for more profit ETX + ZIL
