### ISSUE TITLE
Time out on DNS resolve

### ISSUE THREAD

**Issue by weir12** [Lolliedieb/lolMiner-releases#571]
Hi
When I run LolMiner on the Linux side, I get the following error.The machine is not directly linked to the Internet, but via a jumper that links to the external network (by setting $http_proxy).
many thanks
```
Setup Miner...
Done
Done
Done
Done
OpenCL driver detected.
Number of OpenCL supported GPUs: 4
Cuda driver detected.
Number of Cuda supported GPUs: 4
Device 0:
    Name:    GeForce RTX 2080 Ti
    Address: 61:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  11019 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
Device 1:
    Name:    GeForce RTX 2080 Ti
    Address: 65:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  11019 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
Device 2:
    Name:    GeForce RTX 2080 Ti
    Address: 177:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  11019 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
Device 3:
    Name:    GeForce RTX 2080 Ti
    Address: 181:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  11019 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)

Connecting to pool...
Time out on DNS resolve. Retrying.
Lost connection to stratum server eth.f2pool.com:6688 or server not reachable.
Trying to connect in 1 second
Average speed (30s): 0.00mh/s | 0.00mh/s | 0.00mh/s | 0.00mh/s Total: 0.00 mh/s
Segmentation fault (core dumped)

```

**Comment by jgonzis** [comment]
> Hi
> When I run LolMiner on the Linux side, I get the following error.The machine is not directly linked to the Internet, but via a jumper that links to the external network (by setting $http_proxy).
> many thanks
> 
> ```
> Setup Miner...
> Done
> Done
> Done
> Done
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 4
> Cuda driver detected.
> Number of Cuda supported GPUs: 4
> Device 0:
>     Name:    GeForce RTX 2080 Ti
>     Address: 61:0
>     Vendor:  NVIDIA Corporation
>     Drivers: Cuda, OpenCL
>     Memory:  11019 MByte
>     Active:  true (Selected Algorithm: ETHash Cuda)
> Device 1:
>     Name:    GeForce RTX 2080 Ti
>     Address: 65:0
>     Vendor:  NVIDIA Corporation
>     Drivers: Cuda, OpenCL
>     Memory:  11019 MByte
>     Active:  true (Selected Algorithm: ETHash Cuda)
> Device 2:
>     Name:    GeForce RTX 2080 Ti
>     Address: 177:0
>     Vendor:  NVIDIA Corporation
>     Drivers: Cuda, OpenCL
>     Memory:  11019 MByte
>     Active:  true (Selected Algorithm: ETHash Cuda)
> Device 3:
>     Name:    GeForce RTX 2080 Ti
>     Address: 181:0
>     Vendor:  NVIDIA Corporation
>     Drivers: Cuda, OpenCL
>     Memory:  11019 MByte
>     Active:  true (Selected Algorithm: ETHash Cuda)
> 
> Connecting to pool...
> Time out on DNS resolve. Retrying.
> Lost connection to stratum server eth.f2pool.com:6688 or server not reachable.
> Trying to connect in 1 second
> Average speed (30s): 0.00mh/s | 0.00mh/s | 0.00mh/s | 0.00mh/s Total: 0.00 mh/s
> Segmentation fault (core dumped)
> ```

You should entry en nameserver of linux the DNS of eth.f2pool.com

ping eth.f2pool.com
PING 12f713daf74148c18f110d179fc6170c.pacloudflare.com (172.65.210.108) 56(84) bytes of data.
64 bytes from 172.65.210.108 (172.65.210.108): icmp_seq=1 ttl=55 time=18.5 ms
64 bytes from 172.65.210.108 (172.65.210.108): icmp_seq=2 ttl=55 time=20.7 ms
64 bytes from 172.65.210.108 (172.65.210.108): icmp_seq=3 ttl=55 time=18.4 ms
64 bytes from 172.65.210.108 (172.65.210.108): icmp_seq=4 ttl=55 time=18.6 ms

That could probably help, because that is that the DNS are not correct and he cannot find the pool. Have you try other pool?

**Comment by jgonzis** [comment]
No problem or feedback... close issue
