### ISSUE TITLE
No OpenCL driver or GPUs detected. 

### ISSUE THREAD

**Issue by Springrass** [Lolliedieb/lolMiner-releases#572]
Setup Miner... 
No OpenCL driver or GPUs detected. 
No Cuda driver or GPUs detected. 
Neither OpenCL nor Cuda drivers detected. Closing lolMiner. 
Please help me to solve this problem
<img width="733" alt="截屏2021-05-15 下午10 04 48" src="https://user-images.githubusercontent.com/65485088/118364089-9652e100-b5c9-11eb-9a45-b2ee991ebfbe.png">

**Comment by jgonzis** [comment]
Which is your dedicated GPU card?

**Comment by jgonzis** [comment]
No problem or feedback... close issue
