### ISSUE TITLE
DAG verification failed on some cards with exact model and exact OC setting. Repair is too slow.

### ISSUE THREAD

**Issue by manuellp12** [Lolliedieb/lolMiner-releases#573]
Hello,

I have HiveOS and run ASUS AMD 5500XT 8GB Micron Memory with OC setting 1050 Core, 990 Memory, 720mv core, 1250mv memory.

3 out of 6 fail. 1 usually fails with a few segments and 2 fail with more than 100 segments. Using team red miner they have no problems and works 100%.

Lol version 1.28a

**Comment by jgonzis** [comment]
> Hello,
> 
> I have HiveOS and run ASUS AMD 5500XT 8GB Micron Memory with OC setting 1050 Core, 990 Memory, 720mv core, 1250mv memory.
> 
> 3 out of 6 fail. 1 usually fails with a few segments and 2 fail with more than 100 segments. Using team red miner they have no problems and works 100%.
> 
> Lol version 1.28a

It is not a problem, it is a new premium check. That appears for an excess of Memory OC. DAG is not perfectly load and try to repair it before mining. 

You can avoid this new premium functionality with  --disbale-dag-verify parameters. But after some minutes the DAG will be repaired and perfectly loaded.

**Comment by manuellp12** [comment]
I understand, but the insteresting thing is that I have 6 cards of exact model as I pointed out. All have the same OC configuration, but just some of them fail, the same 3 fail every time, the first not so much (up to 5 segments), the second a bit more (up to 100 segments) and the third fails with more than 200 segments.
This is strange being the same model and exact configuration. And also because using TRM I get no complaints and no invalid/reject shares. The lowest the efficiency goes is down to 99.97%, and most of the time I get 100% accepted shares. Since this version (I used lol before like in 1.20 or so) I am getting an efficiency of around 95%. So I'm just comparing these two scenarios and that is why i suspect there shoud be a bug somewhere.

**Comment by jgonzis** [comment]
> I understand, but the insteresting thing is that I have 6 cards of exact model as I pointed out. All have the same OC configuration, but just some of them fail, the same 3 fail every time, the first not so much (up to 5 segments), the second a bit more (up to 100 segments) and the third fails with more than 200 segments.
> This is strange being the same model and exact configuration. And also because using TRM I get no complaints and no invalid/reject shares. The lowest the efficiency goes is down to 99.97%, and most of the time I get 100% accepted shares. Since this version (I used lol before like in 1.20 or so) I am getting an efficiency of around 95%. So I'm just comparing these two scenarios and that is why i suspect there shoud be a bug somewhere.

It is completely normal... the Silicon Lottery.  As I said, it is a premium check added on 1.28a. You can disable and you will note any difference, but it is always better to have a perfect DAG. You can try if you decrease this 3 GPUs... if that disappears... then you know at that OC you don't have memory errors or just disable and forget it. But I prefer to have perfect DAG loaded or know that my OC is too high for that GPUs...

**Comment by manuellp12** [comment]
Indeed, on factory setting I get no errors, but hashrate is too low. It was almost impossible to have zero DAG errors even on light OC. probably it is something about the AMD cards? Nvidia cards have no problem at all even though they are OC.

**Comment by manuellp12** [comment]
Just as a suggestion then, can the repair be faster? It takes a few seconds per segment, which added up can take a lot of time.

**Comment by jgonzis** [comment]
> Just as a suggestion then, can the repair be faster? It takes a few seconds per segment, which added up can take a lot of time.

One nice improvements to work on it...

**Comment by nCr78** [comment]
@jgonzis This issue still exists and there's a very simple solution that other miners use: store OC per card in a temp variable, reset OC of each card and when DAG is built, apply OC from temp variable. Any chance this is considered as a fix? It works when I do this manually, why not to bake it in the code? 😄

No need to fix your repair algorithm this way (which I assume is harder).

**Comment by jgonzis** [comment]
> @jgonzis This issue still exists and there's a very simple solution that other miners use: store OC per card in a temp variable, reset OC of each card and when DAG is built, apply OC from temp variable. Any chance this is considered as a fix? It works when I do this manually, why not to bake it in the code? 😄
> 
> No need to fix your repair algorithm this way (which I assume is harder).

You need Admins privilegs to do that, at the moment that is possible to mine without them.
