### ISSUE TITLE
Lost connection to stratum server us2.ethermine.org:4444 or server not reachable. Trying to connect in 1 second

### ISSUE THREAD

**Issue by Nimmmy** [Lolliedieb/lolMiner-releases#577]
Is anyone else receiving this error message?  Please advise.

**Comment by jgonzis** [comment]
> Is anyone else receiving this error message? Please advise.

That is an Internet problem... check your firewall... or check you are not using ssl connection

**Comment by thangckt** [comment]
did you solve it? I have the same problem

**Comment by aijie00017** [comment]
me too

**Comment by deea156** [comment]
I have the same problem. Please help

**Comment by jgonzis** [comment]
No problem or feedback... close issue
