### ISSUE TITLE
Crashes on listing devices, when Portable Compute Language (pocl) package is installed

### ISSUE THREAD

**Issue by NicolaiSchmitt** [Lolliedieb/lolMiner-releases#58]
Hello Lolliedieb,
Lolminer crashes while listing available devices when pocl package is installed on the system.
The crash happens when starting lolminer via a shell script to start mining as well as starting it with --list-devices.

I could produce this behaviour on a system running Manjaro Linux with amdgpu driver and opencl-amd package installed with a Radeon VII where Lolminer runs perfectly as long as the pocl package is not installed.

I could also reproduce this behaviour on another system running Arch Linux with a nvidia NVS4200M card running the proprietary nvidia driver (this system is not used for mining).

Even if Lolminer can not use pocl as OpenCL device, it should not crash when pocl is installed.

Tested Versions:
- 1.0_alpha2 
- 1.05

The Screenshot of the crash is attached.
Please let me know if you need further information.

Best Regards and Thanks in advance,
Nicolai Schmitt
![listdevicescrash](https://user-images.githubusercontent.com/13466359/89414463-b98f5c80-d72a-11ea-92a7-cf5a4e8efde7.png)
![startcrash](https://user-images.githubusercontent.com/13466359/89414470-bd22e380-d72a-11ea-976c-a076f12312a0.png)

**Comment by Lolliedieb** [comment]
Good catch!

Never tried pocl yet and found out it crashes because it is a CPU-Only OpenCL platform (at least on my devices) that return error status -1 on clcreatecontext when asking for only GPUs. 

Fixed the issue in development version of next release :) 

Thanks!

**Comment by Lolliedieb** [comment]
Fix is shipped with new 1.06 release
