### ISSUE TITLE
lolMiner 1.29: Error when allocating memory on 1060 6GB

### ISSUE THREAD

**Issue by ingomar-gutmann** [Lolliedieb/lolMiner-releases#580]
Hi!

I get the following out of memory message even though I am using a 6GB Nvidia 1060FE

> Setup Miner... 
OpenCL driver detected.
Number of OpenCL supported GPUs: 1 
Cuda driver detected.
Number of Cuda supported GPUs: 1 
Device 0: 
    Name:    GeForce GTX 1060 6GB 
    Address: 11:0 
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  6044 MByte 
    Active:  true (Selected Algorithm: ETHash Cuda) 
Start Benchmark... 

>GPU 0: error when allocating memory or building DAG. Disabling card.

How can I resolve this?

I use cuda 11.2 on ubuntu 21.04

thanks a lot!

**Comment by jgonzis** [comment]
Can you try 1.28a or the old one 1.24a.
1.24a ist the last OpenCL... to check is working

**Comment by Ernijs** [comment]
I got the same issue, I have total of 3 cards in a rig.  3rd one doesn't start and gives this error and its on random, Any 2 cards works. 
Got 3x 1060 6GB, 8 GB RAM, Intel Pentium G4400 SR2DC 3.30 Ghz. 
OS: Windows

**Comment by jgonzis** [comment]
> I got the same issue, I have total of 3 cards in a rig. 3rd one doesn't start and gives this error and its on random, Any 2 cards works.
> Got 3x 1060 6GB, 8 GB RAM, Intel Pentium G4400 SR2DC 3.30 Ghz.
> OS: Windows

Just increase Swap disk size in Windows and problem will be solve it

**Comment by Ernijs** [comment]
> > I got the same issue, I have total of 3 cards in a rig. 3rd one doesn't start and gives this error and its on random, Any 2 cards works.
> > Got 3x 1060 6GB, 8 GB RAM, Intel Pentium G4400 SR2DC 3.30 Ghz.
> > OS: Windows
> 
> Just increase Swap disk size in Windows and problem will be solve it

Man, you just saved me, and it works. 
For those that need guide in this, internet is full, but here is example: https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/

**Comment by jgonzis** [comment]
Great to know ☺
