### ISSUE TITLE
HiveOS 3060 Booster

### ISSUE THREAD

**Issue by lerasah** [Lolliedieb/lolMiner-releases#584]
Hi,

I executed `nvidia-driver-update 460.39` and my primary display went off (which is normal during a graphics driver update), and it never came back even after a restart. lolMiner also didn't work (remotely, it accepts the restart miner signal but doesn't really start)

Thanks.

OS VERSION 0.6-203@210519
ROG STRIX Z490-F GAMING ASUSTeK COMPUTER INC. (0403 03/23/2020)
GA106 [GeForce RTX 3060 6GB]  · MSI

**Comment by jgonzis** [comment]
> Hi,
> 
> I executed `nvidia-driver-update 460.39` and my primary display went off (which is normal during a graphics driver update), and it never came back even after a restart. lolMiner also didn't work (remotely, it accepts the restart miner signal but doesn't really start)
> 
> Thanks.
> 
> OS VERSION 0.6-203@210519
> ROG STRIX Z490-F GAMING ASUSTeK COMPUTER INC. (0403 03/23/2020)
> GA106 [GeForce RTX 3060 6GB] · MSI

Could you please active 1st the Integrated GPU of the Intel CPU, to run with the integrated GPU?. 

Then you will be able to run the upgrade... you can do:

nvidia-driver-update 460
nvidia-driver-update 455.45.01
nvidia-driver-update 460.32
nvidia-driver-update 460.39

Whatever of this realease will work. You can also download the HiveOS image another time and just start with the nvidia-driver-update to directly have the right version

**Comment by pdieppa** [comment]
Make sure you are running those command using SSH and not VNC. The VNC session is cancelled during the upgrade or downgrade .

**Comment by lerasah** [comment]
> Make sure you are running those command using SSH and not VNC. The VNC session is cancelled during the upgrade or downgrade .

I have physical access to the rig

**Comment by lerasah** [comment]
> > Hi,
> > I executed `nvidia-driver-update 460.39` and my primary display went off (which is normal during a graphics driver update), and it never came back even after a restart. lolMiner also didn't work (remotely, it accepts the restart miner signal but doesn't really start)
> > Thanks.
> > OS VERSION 0.6-203@210519
> > ROG STRIX Z490-F GAMING ASUSTeK COMPUTER INC. (0403 03/23/2020)
> > GA106 [GeForce RTX 3060 6GB] · MSI
> 
> Could you please active 1st the Integrated GPU of the Intel CPU, to run with the integrated GPU?.
> 
> Then you will be able to run the upgrade... you can do:
> 
> nvidia-driver-update 460
> nvidia-driver-update 455.45.01
> nvidia-driver-update 460.32
> nvidia-driver-update 460.39
> 
> Whatever of this realease will work. You can also download the HiveOS image another time and just start with the nvidia-driver-update to directly have the right version

This worked.. Thank you! @jgonzis

**Comment by pdieppa** [comment]
> > Make sure you are running those command using SSH and not VNC. The VNC session is cancelled during the upgrade or downgrade .
> 
> I have physical access to the rig

Sorry I didn't mention the local session (terminal) is also cancelled. That's why it is recommended to connect using SSH.

**Comment by lerasah** [comment]
> > > Make sure you are running those command using SSH and not VNC. The VNC session is cancelled during the upgrade or downgrade .
> > 
> > 
> > I have physical access to the rig
> 
> Sorry I didn't mention the local session (terminal) is also cancelled. That's why it is recommended to connect using SSH.

Aaaah I see now.. Thank you @pdieppa .. It helps
