### ISSUE TITLE
I Started Mining Not Long Ago And Out Of No Where It Just Stopped... Can I Get An Explanation?

### ISSUE THREAD

**Issue by SickDC** [Lolliedieb/lolMiner-releases#585]
![Mining](https://user-images.githubusercontent.com/84492587/118924468-22874000-b90b-11eb-8b75-3ec0ed4562c2.PNG)

**Comment by jgonzis** [comment]
That seems a small Swap Disk in Windows... Could you try:

[https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/](https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/
)

Try to put 60000 and 60000 I think that is the problem you have...

**Comment by SickDC** [comment]
> That seems a small Swap Disk in Windows... Could you try:
> 
> https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/
> 
> Try to put 60000 and 60000 I think that is the problem you have...

I'm not sure if I set up the Swap Disk incorrectly but after I set it up I still had the same issue.

**Comment by SickDC** [comment]
@jgonzis Could I get some assistance please?

**Comment by jgonzis** [comment]
> > That seems a small Swap Disk in Windows... Could you try:
> > https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/
> > Try to put 60000 and 60000 I think that is the problem you have...
> 
> I'm not sure if I set up the Swap Disk incorrectly but after I set it up I still had the same issue.

Can you provide a Photo?.

If you want to run without problem you can use also a Mining OS like MMPOS.eu it is free up to 8 GPU and it use Linux... it works with USB Pendrive... and this small problems are solved normally there too.

**Comment by SickDC** [comment]
What are you needing a photo of? do you want at picture of the failed mining cmd or of the swap disk? @jgonzis

**Comment by SickDC** [comment]
I am not sure if this helps with the diagnosis but I'm not able to run the BEAM miner either..

**Comment by SickDC** [comment]
![image](https://user-images.githubusercontent.com/84492587/119041316-7a15c200-b984-11eb-81d2-7f27acaf6cc0.png)

I do not understand why it starts but doesn't start the DAG, is there something causing the DAG to not start up? Like I recently reset my BIOS because I got myself locked out, did I by chance change something that I needed to be enabled or disabled in the BIOS?

**Comment by SickDC** [comment]
@jgonzis @Lolliedieb

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/84492587/119041316-7a15c200-b984-11eb-81d2-7f27acaf6cc0.png)
> 
> I do not understand why it starts but doesn't start the DAG, is there something causing the DAG to not start up? Like I recently reset my BIOS because I got myself locked out, did I by chance change something that I needed to be enabled or disabled in the BIOS?

It seens to be a Windows problem, can you please try a Mining OS like MMPOS or RaveOS or HiveOS or minerstat?. Then you will be able to check it better.

All this software can run free with a USB ...

**Comment by SickDC** [comment]
Ok thanks, I am currently setting up HiveOS but it may take some time to finish because of my internet. I appreciate the help a ton.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
