### ISSUE TITLE
3060 0 megahash

### ISSUE THREAD

**Issue by qazdude** [Lolliedieb/lolMiner-releases#587]
![Capture](https://user-images.githubusercontent.com/84542364/119042492-89454180-b97d-11eb-892b-f2bafcb2521e.PNG)
Hello I have 3 cards 2 3060s and 1 1060. I have the correct 460.39 driver and up to date hive os. When I run lolMiner the 3060s seem to not hash. I did run the rig in maintenence mode and was able to hash 32mh. but when I put in the 1060 it recognized none of them. Im also getting errors such as nvidia oc failed and code such as: 
=== GPU 0, 02:00.0 GA106 [GeForce RTX 3060 6GB] 12053 MB, PL: 100 W, 170 W, 170 W === 12:54:27
  SET CLOCKS: 0 MHz
  SET POWER LIMIT: 125.0 W [Unknown Error]
(exitcode=123)
  Max Perf mode: 4 (auto)
ERROR: Error assigning value 100 to attribute 'GPUTargetFanSpeed'
       (Shit_box:0[fan:0]) as specified in assignment
       '[fan:0]/GPUTargetFanSpeed=100' (Unknown Error).
ERROR: Error assigning value 100 to attribute 'GPUTargetFanSpeed'
       (Shit_box:0[fan:1]) as specified in assignment
       '[fan:1]/GPUTargetFanSpeed=100' (Unknown Error).
ERROR: Error assigning value 100 to attribute 'GPUGraphicsClockOffset'
       (Shit_box:0[gpu:0]) as specified in assignment
       '[gpu:0]/GPUGraphicsClockOffset[4]=100' (Unknown Error).
ERROR: Error assigning value 200 to attribute 'GPUMemoryTransferRateOffset'
       (Shit_box:0[gpu:0]) as specified in assignment
       '[gpu:0]/GPUMemoryTransferRateOffset[4]=200' (Unknown Error).
  Attribute 'GPUFanControlState' (Shit_box:0[gpu:0]) assigned value 1.

Please if anyone has a solution let me know

**Comment by jgonzis** [comment]
Use lolMiner 1.29
Try to put 1450 in Core and Memory don't pass from 2000. 
Power Limit put 125 it will be better.

It seems something that no applyes correctly As you see it says clock Offset 100 and you don't have these values in the OC of HiveOS...

**Comment by qazdude** [comment]
I am in lolminer 1.29 and i cant overclock it says nvidia oc failed and gives me those erros
it wont even run with normal clocks

**Comment by jgonzis** [comment]
Could you try to change the riser??

**Comment by qazdude** [comment]
i am on a riserless motherboard Onda D1800 BTC Mining Motherboard and I have moved the cards around on all slots.

**Comment by qazdude** [comment]
Im going to try and update the bios of the mb
Onda D1800 BTC Mining Motherboard

**Comment by qazdude** [comment]
updated the motherboard still the same issue. Anyone have a solution?

**Comment by jgonzis** [comment]
Stupid solution... try adding --devices 0,1 just to be sure if only the 2 x 3060 are working if it do it properly

**Comment by qazdude** [comment]
I did and both of them dont get recognized

**Comment by jgonzis** [comment]
Try one  by one the GPUs... it is moment to try and test...

**Comment by pdieppa** [comment]
Do you have a OC profile? If you do, delete it and re-create it. I have seen this before where the OC setting do not take effect no matter what I do. Deleting a algo and entering a new one did the trick.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
