### ISSUE TITLE
GPU's stop mining for no reason

### ISSUE THREAD

**Issue by DarioAcevedo** [Lolliedieb/lolMiner-releases#590]
Hi, 

I have a rig of 4 3060, it starts working well @ 35 MH/s, but suddenly one or two stop mining. 
I have a pentium processor with 8 GB on RAM, runs on Hive OS

![image](https://user-images.githubusercontent.com/47285245/119203485-c3cfdc80-ba58-11eb-9d1b-9cb8ecc8d3ae.png)

**Comment by judders** [comment]
Could be a lot of things. Try removing the overclock settings all together to start.

**Comment by DarioAcevedo** [comment]
It works, but if I keep it without overclock, my cards get too hot

**Comment by judders** [comment]
Then that sounds like your answer. Play with the overclocks. Start aggressively. like 80,1200,1800,160. Run for a hour, Then increment slowly. One of my 3060's I can only get 31mh. Silicon lottery.

**Comment by DarioAcevedo** [comment]
Ok then, Thank you very much for your help!
