### ISSUE TITLE
Gpu rig 8gb+4gb+4gb+…

### ISSUE THREAD

**Issue by vedene** [Lolliedieb/lolMiner-releases#591]
Hello, it would be cool to have part of a dag file in another video card with 8GB of memory

**Comment by jgonzis** [comment]
> Hello, it would be cool to have part of a dag file in another video card with 8GB of memory

That will be like an actual Zombie-Mode.... limit with bus Bandwith....

**Comment by vedene** [comment]
I have a Tesla k80 with 24gb memory, it would be great to use this memory

**Comment by jgonzis** [comment]
> I have a Tesla k80 with 24gb memory, it would be great to use this memory

Yes I know what you mean... the problem will be the same the connection bottleneck between the GPU...
