### ISSUE TITLE
Error mining Beam on RX 5600 XT

### ISSUE THREAD

**Issue by gzz10** [Lolliedieb/lolMiner-releases#592]
Hello, i get this error mining beam:
![error](https://user-images.githubusercontent.com/81320728/119384275-d46f9500-bc9a-11eb-9104-65ba4d4c3ba6.jpg)

More info:
- This happen everytime, but only mining beam, not on other coins.
- The error could happen after 2-3 hrs or 15 min.
- I have tried differents OC settings, even stock settings, still happening.
- I am on Windows 10 since is my personal computer, not tried another OS.
- Temps are under control.
- I started mining beam with 1.21 realease and so on (now on 1.28a).

I added a loop in the bat file so everytime this happen the miner will go on but since the error is persistent i wanna report it. Also i can mine ETH for 8-12 hrs no problem so it looks like something with beam? idk.

Thanks.

**Comment by jgonzis** [comment]
That is a Driver crash... it could be that you have an aggresive undervolt, some extra voltage on the core could help to see if that doesn't happen

**Comment by Malique2** [comment]
Thats happening on my AMD cards regardless with the new drivers. No overclocking or undervolting.

**Comment by jgonzis** [comment]
> Thats happening on my AMD cards regardless with the new drivers. No overclocking or undervolting.

New Drivers seems not working yet... try to use older Driver until New drivers are loaded.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
