### ISSUE TITLE
Miner not showing up in ethermine

### ISSUE THREAD

**Issue by Alexwhelan123** [Lolliedieb/lolMiner-releases#595]
New to this so most probably user issue. 
Looked to me everything was alright and mining is actually working but the miner just isn't showing up in ethermine dashboard..

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    GeForce RTX 2080 Ti
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  11264 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)

Connecting to pool...
Connected to eu1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0xF6534067309cE13fA08e166433675E7fB3b19f0c.lolMinerWorker
New job received: 0x65de0d Epoch: 416 Target: 00000000ffff0000
Start Mining...
-------------------------------------------------------
          Generated light cache for epoch 416
       Took 1745 ms, size of new DAG: 4351 MByte
-------------------------------------------------------
GPU 0: Starting DAG generation (normal mode)
New job received: 0xde781b Epoch: 416 Target: 00000000ffff0000
GPU 0: DAG build complete 17%
GPU 0: DAG build complete 35%
GPU 0: DAG build complete 52%
New job received: 0x1973a5 Epoch: 416 Target: 00000000ffff0000
GPU 0: DAG build complete 70%
GPU 0: DAG build complete 88%
GPU 0: DAG generation completed (6423 ms)
GPU 0: DAG verification passed
New job received: 0xd868b3 Epoch: 416 Target: 00000000ffff0000
New job received: 0x9d1939 Epoch: 416 Target: 00000000ffff0000
New job received: 0xf147f1 Epoch: 416 Target: 00000000ffff0000
New job received: 0x6bd9f6 Epoch: 416 Target: 00000000ffff0000
New job received: 0xe955da Epoch: 416 Target: 00000000ffff0000
New job received: 0x13f626 Epoch: 416 Target: 00000000ffff0000
New job received: 0x231808 Epoch: 416 Target: 00000000ffff0000
New job received: 0x2069e6 Epoch: 416 Target: 00000000ffff0000
New job received: 0x07925b Epoch: 416 Target: 00000000ffff0000
Average speed (30s): 28.19 mh/s
New job received: 0x6a34ca Epoch: 416 Target: 00000000ffff0000
New job received: 0xb8c1f7 Epoch: 416 Target: 00000000ffff0000
New job received: 0xa8fcc4 Epoch: 416 Target: 00000000ffff0000
New job received: 0x5cfb3a Epoch: 416 Target: 00000000ffff0000
New job received: 0x2769c6 Epoch: 416 Target: 00000000ffff0000
New job received: 0xfeb584 Epoch: 416 Target: 00000000ffff0000
New job received: 0x26f43f Epoch: 416 Target: 00000000ffff0000
Average speed (30s): 41.50 mh/s
New job received: 0x5f78bb Epoch: 416 Target: 00000000ffff0000
New job received: 0x51c2a2 Epoch: 416 Target: 00000000ffff0000
New job received: 0xdbb58b Epoch: 416 Target: 00000000ffff0000
New job received: 0x71b47d Epoch: 416 Target: 00000000ffff0000
New job received: 0x134324 Epoch: 416 Target: 00000000ffff0000
New job received: 0x6cd80b Epoch: 416 Target: 00000000ffff0000
New job received: 0xd80cf9 Epoch: 416 Target: 00000000ffff0000
New job received: 0xbf5a3c Epoch: 416 Target: 00000000ffff0000
New job received: 0xbfd7fb Epoch: 416 Target: 00000000ffff0000
New job received: 0x95908a Epoch: 416 Target: 00000000ffff0000
New job received: 0x6e063a Epoch: 416 Target: 00000000ffff0000
New job received: 0xab81c3 Epoch: 416 Target: 00000000ffff0000
New job received: 0x039e13 Epoch: 416 Target: 00000000ffff0000
New job received: 0x661a40 Epoch: 416 Target: 00000000ffff0000
Average speed (30s): 41.17 mh/s
New job received: 0xeb3ccf Epoch: 416 Target: 00000000ffff0000
New job received: 0xffeb2e Epoch: 416 Target: 00000000ffff0000
New job received: 0x3353fe Epoch: 416 Target: 00000000ffff0000
New job received: 0x2349ee Epoch: 416 Target: 00000000ffff0000
New job received: 0x2ec9a2 Epoch: 416 Target: 00000000ffff0000
New job received: 0xb4be3f Epoch: 416 Target: 00000000ffff0000
New job received: 0xca7bad Epoch: 416 Target: 00000000ffff0000
New job received: 0xbd73ad Epoch: 416 Target: 00000000ffff0000
New job received: 0x731dc2 Epoch: 416 Target: 00000000ffff0000
Average speed (30s): 38.60 mh/s
New job received: 0x71cb04 Epoch: 416 Target: 00000000ffff0000
New job received: 0x3ba1d8 Epoch: 416 Target: 00000000ffff0000
New job received: 0xc8d5ba Epoch: 416 Target: 00000000ffff0000
New job received: 0x93698f Epoch: 416 Target: 00000000ffff0000
GPU 0: Found a share of difficulty 169.17G
GPU 0: Share accepted (10 ms)
New job received: 0x7a668b Epoch: 416 Target: 00000000ffff0000
New job received: 0x980194 Epoch: 416 Target: 00000000ffff0000
New job received: 0xc7e401 Epoch: 416 Target: 00000000ffff0000
New job received: 0x0754b4 Epoch: 416 Target: 00000000ffff0000
New job received: 0xc58c54 Epoch: 416 Target: 00000000ffff0000
---------------------------------------------
Statistics (06:07:27); Mining: Ethash
Connected to: eu1.ethermine.org:4444
Uptime: 0h 2m 30s
                             GPU 0    Total
Name:                  RTX 2080 Ti      Rig
Speed (mh/s):                38.01    38.01
Pool (mh/s):                 28.63    28.63
Shares (A/S/Hw):             1/0/0    1/0/0
Best Share:                 169.2G   169.2G
Power (W):                   223.8    223.8
Efficiency (mh/s/W):         0.169    0.169
Temp (deg C):                   61
Fan Speed (%):                  48
---------------------------------------------
Average speed (30s): 40.61 mh/s****
https://www.loom.com/share/57bfa039321942e4b2ae0812d78a146c

**Comment by jgonzis** [comment]
No more Feedback
