### ISSUE TITLE
RTX 3060 speed

### ISSUE THREAD

**Issue by pdieppa** [Lolliedieb/lolMiner-releases#596]
Anyone getting more than 38mh/s with their 3060 while mining ETH under Linux (HiveOs)?

**Comment by jgonzis** [comment]
> Anyone getting more than 38mh/s with their 3060 while mining ETH under Linux (HiveOs)?

It is the max at the moment without destroying the card in Linux...

**Comment by pdieppa** [comment]
Yeah, I saw that but the reality is it's unworkable for a 24/7 operation. Currently you can make more money mining ERG than ETH. My rigs are rented mining ETH but as soon as they are free I'll be changing them to ERG for a while.

This is for a single 3060

![image](https://user-images.githubusercontent.com/74556152/120012590-aeedce80-bfad-11eb-9437-ad7707e8e69e.png)
