### ISSUE TITLE
Devices not recognized anymore 

### ISSUE THREAD

**Issue by StagGander** [Lolliedieb/lolMiner-releases#597]
![image](https://user-images.githubusercontent.com/84790264/119518471-87e19380-bd46-11eb-901c-e5a39a60ce4e.png)

Both GPU's are RX580 and visible and working from AMD monitoring.

![image](https://user-images.githubusercontent.com/84790264/119518837-e575e000-bd46-11eb-9e5f-9294da7c2c4a.png)

How do I fix this?

**Comment by jgonzis** [comment]
Could yo please try to increase the SWAP Memory Disk?.

[https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/](https://www.pcgamer.com/what-are-page-and-swap-files-and-how-big-should-they-be/)

**Comment by Turbonator0** [comment]
what drivers are you using? from personal experience the newer drivers caused another miner to not see my GPU

**Comment by jgonzis** [comment]
No more feedback
