### ISSUE TITLE
--devices arg and tls error

### ISSUE THREAD

**Issue by rexsllemel** [Lolliedieb/lolMiner-releases#598]
I am in hiveos. 

When I set miner arg to --devices AMD or --devices 0,1 all works. But when I try to add a command --tls 0, the extra argument for --devices is not working unless I'll remove the --tls 0 arg.

On the other hand, if I am not using --tls 0, lolminer will be connected to the pool but immediately disconnected and looping connect/disconnect, so I have to use --tls 0, but I should say all of the argument will be disregarded for that option (--tls 0).

I am using BeamV3 on lolminer 1.29 (latest)

**Comment by pdieppa** [comment]
You don't have to specify the --tls in hiveon. Just use the option in the flightsheet

![image](https://user-images.githubusercontent.com/74556152/119656159-60e39a00-bdf8-11eb-9fc9-96ea6f8c821a.png)

**Comment by rexsllemel** [comment]
> You don't have to specify the --tls in hiveon. Just use the option on the flightsheet
> 
> ![image](https://user-images.githubusercontent.com/74556152/119656159-60e39a00-bdf8-11eb-9fc9-96ea6f8c821a.png)
> 
> Also, which pool are you connecting to? Some pools have specific ports for TLS and non-tls connections and will refuse incorrect ones.

Already turned off. On BeamV3 algo, that option may be not working as I see the option --tls 0 has already set in extra parameter as a default extra arg when selecting that algo.

**Comment by pdieppa** [comment]
lolMiner does not use tls by default, so there is no need to enter it as an extra config argument.
Let's take a look a the pool you are trying to connect. If you are trying to connect to pool port that is set for TLS and you are not using it, usually the pool may disconnect you.

**Comment by rexsllemel** [comment]
> lolMiner does not use tls by default, so there is no need to enter it as an extra config argument.
> Let's take a look a the pool you are trying to connect. If you are trying to connect to pool port that is set for TLS and you are not using it, usually the pool may disconnect you.

**Comment by rexsllemel** [comment]
> lolMiner does not use tls by default, so there is no need to enter it as an extra config argument.
> Let's take a look a the pool you are trying to connect. If you are trying to connect to pool port that is set for TLS and you are not using it, usually the pool may disconnect you.

I am connecting to this pool
```
beamv3.hk.nicehash.com:3387
beamv3.jp.nicehash.com:3387

```
![image](https://user-images.githubusercontent.com/15032596/119828125-74901d00-bf2c-11eb-9ad4-5db2bd36fcd0.png)

as you can see the image above, --tls 0 option already set by default ( I did not set that argument). If I remove --tls 0, lolminer will use tls as what I am seeing in the log (tls enabled).

![image](https://user-images.githubusercontent.com/15032596/119829638-06e4f080-bf2e-11eb-8f88-a1901d4a2f93.png)

if I will keep --tls 0 arg, all of the the argument I should say will be disregarded (not working).

![image](https://user-images.githubusercontent.com/15032596/119830076-7a86fd80-bf2e-11eb-9cde-8cb2d1050e85.png)

as you can see --devices AMD arg not work.

**Comment by pdieppa** [comment]
Hmmm. Interesting. My rigs is currently rented so I can't try it for another 11 hours.
My flightsheets do not add the --tls 0 by default, so I wonder where that is coming from. At least it should not be coming from the Tuning section since anything you add there overwrites your extra arguments and they show up crossed out.

Have you tested with other pools like https://beam.herominers.com/ ?

**Comment by rexsllemel** [comment]
herominers pool not working (all server) I can't ping them either.
2miners pool is okay.

If I select Beam coin (not nicehash beam) it did not set --tls 0 automatically but on the log TLS is enabled. 

On the other side, nicehash beam will set --tls 0 automatically.
![image](https://user-images.githubusercontent.com/15032596/119846950-2afbfe00-bf3d-11eb-8aee-4e7f69f935c2.png)
![image](https://user-images.githubusercontent.com/15032596/119846248-8c6f9d00-bf3c-11eb-82c2-df9881fdc37a.png)

In my test, I conclude lolminer enabled tls by default for beamhash algo which is in my side (nicehash) is not using tls so I have to forcibly disable tls by using --tls 0 arg which then again it'll disregard the other argument.

**Comment by pdieppa** [comment]
Finally got a chance to test it. I does add the --tls automatically. I left it and added --devices 0 and it starts mining using Nicehash BeamV3. Interesting. 

![image](https://user-images.githubusercontent.com/74556152/119920778-df485500-bf3a-11eb-86df-eb65f6f1fa72.png)

![image](https://user-images.githubusercontent.com/74556152/119920872-06068b80-bf3b-11eb-9098-95acc6f33c13.png)

**Comment by pdieppa** [comment]
BTW, I connected using the USA server and did not test the one you selected.

**Comment by rexsllemel** [comment]
So, I tried the way you add the argument and it works!

It should be
--tls 0
--devices

And not
--tls 0 --devices

Thank you! I haven't think the way to put like that in the argument.
