### ISSUE TITLE
Can't download the 1.28 windows version because of some error with the internet, maybe an error conecting to the server

### ISSUE THREAD

**Issue by DuarteRei** [Lolliedieb/lolMiner-releases#599]
When i press to download version 1.28 wind.rar it says that are some error with the internet and it can't download, i think it might be an issue with the server, anyone has the same problem or has a solution?

Thank you!

**Comment by pdieppa** [comment]
You need to disable your anti-virus before you can download any miner. Most if not all anti-virus program flag miner programs as malware. You also need to add an exception to the AV for the directory where you are going to eventually run the program. If you don't, the AV will block the execution of the miner.

good luck

**Comment by DuarteRei** [comment]
Try it did nt work :/ from my experince when the anti virus blocked the file it would just say that the file was blocked, in this case does not say that it only says error with the internet, going to attach a print (sry for the portuguese but the translation is "network error"
![error](https://user-images.githubusercontent.com/84846629/119659162-d31ea380-be25-11eb-8d4b-7df0b23bf2df.PNG)

**Comment by pdieppa** [comment]
This is the official link for 1.28a
https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.28/lolMiner_v1.28a_Win64.zip

If you have a third party AV, you also need to make sure Windows Defender is not blocking the download. Network Error is the classic sign that the AV interrupted the download.

**Comment by DuarteRei** [comment]
Thank you! I be disable it and it worked
