### ISSUE TITLE
Version 0.7: GPU sorting changed

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#6]
> GPU sorting changed. Its now sorted by PCIE bus address. This addresses are also shown at startup and in API.

This might cause compatibility issues with multipool miners like www.multipoolminer.io.

Could you please add a command line options to have the old GPU sorting back (for backward compatibility). Thank you very much!

**Comment by Lolliedieb** [comment]
Should now be handled by all integrations correctly. Order is same as pcie address
