### ISSUE TITLE
Request Inclusion of XTA new Cuckoo Pow 48 Cycles

### ISSUE THREAD

**Issue by italocoin-project** [Lolliedieb/lolMiner-releases#60]
Hello,

ITALO (XTA) will move on cuckoo pow probably next week, we are wondering if you guys would add XTA support on your Miner, here are the node's

https://github.com/italocoin-project/node-cryptoforknote-util

https://github.com/italocoin-project/node-cryptonight-hashing

https://github.com/italocoin-project/node-cuckaroo29i-hashing

we are on cuckoo Like Swap what differs are the cycles, we are on 48 Cycles swap is on 32, thank you verry much!

Regards,
ITALO TEAM

**Comment by Lolliedieb** [comment]
Hello,

Indeed adding a 48 cycle finder would not be that hard. Can you provide more details on your stratum interface you use for pool mining? Then it would be rather easy and likely be done with next release.

Kind regards :)

**Comment by italocoin-project** [comment]
Hello,

thanks for the reply, here is a reference miner https://github.com/italocoin-project/ItaloReferenceMiner and here is a working testnet pool http://test.italo.network/ i am currently mining with the daemon as i don't own a NVIDIA nor AMD Card, thank you.

**Comment by Lolliedieb** [comment]
Implemented in 1.07
