### ISSUE TITLE
Where is the eth 4g batch file in the 1.28 version?

### ISSUE THREAD

**Issue by DuarteRei** [Lolliedieb/lolMiner-releases#601]
I have a 4gb card so i must use the 4gb file however i can't find it, do i need to download it separately or do i need to configure the normal file?
Thank you

**Comment by pdieppa** [comment]
If you are referring to the sample batch file that is included with lolMiner, here it is

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --4g-alloc-size 4024 --keepfree 8 
timeout 10

**Comment by DuarteRei** [comment]
Thank you
