### ISSUE TITLE
Personalization Strings?

### ISSUE THREAD

**Issue by Radar5k** [Lolliedieb/lolMiner-releases#61]
Just wondering what the various personalization strings are for the algo's that require them.

Would it be possible to list them after each algo when we use the --list-algos switch?

Thanks.

**Comment by Lolliedieb** [comment]
Well this is a property of Equihash 144/5 and 192/7. The different coins that run on this algorithm have a short - 8 characters - string that personalize the PoW a bit.

Some pools support sending the right code via stratum (for this the --coin AUTO144_5 and --coin AUTO192_7 options are there), others do not support it. To support smaller coins that I am not aware of the personalization can be set manually with parameter --pers.

Let me know if you need to know more :)
