### ISSUE TITLE
Average speed too high (lolMiner 1.28a / Windows 10)

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#610]
![image](https://user-images.githubusercontent.com/30080938/120983719-41465d00-c77a-11eb-8425-6cd13fc64556.png)

Command line used:
`lolminer.exe --algo ETHASH --ethstratum ETHV1 --pool us-east.ethash-hub.miningpoolhub.com:20535 --user ************************************.*********** --pass x --tls off --log off --apiport 4003 --devicesbypcie --shortstats=2 --longstats=60 --devices 1:0`

Speed reported in statistics is correct.
If I set  `--shortstats=1` then the average speed is reported correctly.

**Comment by jgonzis** [comment]
normally the best is to put --shortstats=10 to have some time to calculate...

**Comment by UselessGuru** [comment]
Problem is solved with 1.31. Thank you!
