### ISSUE TITLE
3060 "Unlocker" v1.29 doesn't work with new 3060 LHR model

### ISSUE THREAD

**Issue by dealbreak3r** [Lolliedieb/lolMiner-releases#611]
Last week I received a newly manufactured EVGA 3060.  It has the GA106-302 die and a new PCI device ID 2504.  I know per the readme nvidia linux driver 460.39 or earlier is required.   After incremental testing, the earliest nvidia driver that detects the new 3060 LHR card is 465.27.

I can confirm I am unable to get a partial unlock of 75% ethash rate with this earliest supported driver. I just wanted to make the dev team aware and I can offer whatever assistance is needed.  Thanks.

**Comment by pdieppa** [comment]
What error do you get when you mine with 460.39?

**Comment by dealbreak3r** [comment]
With that driver version (460.39), the 3060 LHR is not detected by the OS.  It reads "Device 2504".  The miner only sees the other two cards in my rig.  The first driver that supports this card is 465.27.  I tested them all, one at a time.  465.27 correctly recognizes the GPU as a GeForce RTX 3060.

Those purchasing newly manufactured 3060's will not have the option to downgrade drivers to get the ethash speed improvement. 

![Capture_460 39](https://user-images.githubusercontent.com/37665464/121127473-d50a3e80-c7f7-11eb-8e4e-4fd75ada5392.JPG)
![Detected](https://user-images.githubusercontent.com/37665464/121127489-d9365c00-c7f7-11eb-9410-68449a5e6fe2.JPG)
![miner1](https://user-images.githubusercontent.com/37665464/121127502-de93a680-c7f7-11eb-85d1-09cfdf792c25.JPG)
![miner2](https://user-images.githubusercontent.com/37665464/121127510-e05d6a00-c7f7-11eb-8433-86fb13bce677.JPG)

**Comment by jgonzis** [comment]
Try to enter to the Telegram group... it could be useful if you let the developer to enter to the rig to see what it really does...

**Comment by dydzio0614** [comment]
get rekt, stupid mining only pumps up GPU prices, buy dedicated mining hardware

**Comment by pdieppa** [comment]
That is a myth that miners are buying all the GPUs. According to Nvidia's numbers, only 20% of their sales went to miners (YTD). The cards and prices will start to go down very fast since China is cracking down on crypto.  If I had to guess, the bulk of the cards are being sold to the Chinese market but Nvidia is lying to all its customers.

**Comment by japex-brz** [comment]
Hi...
I think that driver 460.39 is from Jan/2021. As its an old driver, HiveOS won't "install" the card.
The same happens in Windows. This new RTX 3060 (GA-102-**_306_**) requires newer drivers.

**Comment by jgonzis** [comment]
> Hi...
> I think that driver 460.39 is from Jan/2021. As its an old driver, HiveOS won't "install" the card.
> The same happens in Windows. This new RTX 3060 (GA-102-**_306_**) requires newer drivers.
> Im getting just 15MHs...

You are right you have and V2 3060... that has a new blocker to avoid the unlock that was working... It will take time... it is probably necessary to think in another coins with that GPU

**Comment by jgonzis** [comment]
No problem or feedback... close issue
