### ISSUE TITLE
List devices only found one RX6800  with lolminer 1.29

### ISSUE THREAD

**Issue by Ardziv** [Lolliedieb/lolMiner-releases#612]
I have a rig with 3 x AMD RX6800 and using the latest AMDGPU PRO stable driver - the cards are plugged using a riser extender from PCIe1x to PCIe16x. 
The OS is UBUNTU 20.04 with kernel 5.4.0-74.
The output of CLINFO finds the cards.
The same for LSHW output.

But the output from LOLMINER --list-devices shows 4 cards: 1 active and 3 other RX6800 through OPENCL.

The only thing I do not understand is that it only happens after I install the package "mesa-opencl-icd" - before I install this package only 1 GPU is found by lolminer.

Please help thanks.

![image](https://user-images.githubusercontent.com/13898818/121341337-2549e380-c953-11eb-95ff-104b2248ce57.jpeg)![image](https://user-images.githubusercontent.com/13898818/121341352-28dd6a80-c953-11eb-91ac-fe5399ee9bb1.jpeg)
![image](https://user-images.githubusercontent.com/13898818/121341373-2da21e80-c953-11eb-882e-1ef1dcbc9362.jpeg)

**Comment by jgonzis** [comment]
Could you try to add the --devices 0,2,4 to try if that helps?. 

I also think the first kernel 5.4.0-80 or 108, at least that is like this in HiveOS for example.

**Comment by Ardziv** [comment]
> Could you try to add the --devices 0,2,4 to try if that helps?.
> 
> I also think the first kernel 5.4.0-80 or 108, at least that is like this in HiveOS for example.

Thanks i am testing a full distro upgrade now and see if that fixes the bug.

**Comment by Ardziv** [comment]
> > Could you try to add the --devices 0,2,4 to try if that helps?.
> > I also think the first kernel 5.4.0-80 or 108, at least that is like this in HiveOS for example.
> 
> Thanks i am testing a full distro upgrade now and see if that fixes the bug.

same same - after full upgrade to ubuntu 20.10 (groovy) and reinstalling the ROCM driver (not the AMDGPU one but the one from ROCM repository) i end up in exactly the same situtation - also the --devices 0,2,4 flag made no difference.

can you advise anything else? or fix the bug to handle MESA better?

**Comment by Ardziv** [comment]
one thing extra - once i removed the package "mesa-opencl-icd" and keep just the ROCM packages i can see only the single ROCM + Opencl card available - the other 2 cards are not detected - anything you think i should do to fix it? is it a problem at the ROCM driver level that does not support the other two cards?
![image](https://user-images.githubusercontent.com/13898818/122156894-7f3f3180-ce9c-11eb-91a6-eaa0a73e84d8.png)

**Comment by jgonzis** [comment]
Can you try distro MMPOS or HiveOS.  Then you will be able to discard OS problems or hardware problems

**Comment by Ardziv** [comment]
> Can you try distro MMPOS or HiveOS. Then you will be able to discard OS problems or hardware problems

i will give it a try to other distro - but one last discovery is that this bug only seems to be linked to ROCMINFO/ROCM layer that only detects one cards - but the AMDGPU kernel driver sees the 3 cards fine

**Comment by jgonzis** [comment]
No problem or feedback... close issue
