### ISSUE TITLE
lolMiner.exe randomly got deleted while running

### ISSUE THREAD

**Issue by purestone9** [Lolliedieb/lolMiner-releases#614]
I was running lolMiner and about 12 hours after running it lolMiner.exe got deleted, I was able to successfully get the exe back by extracting a new copy of the exe from the zip I originally downloaded, While it isn't an issue at the moment, I do worry that it could happen again.

**Comment by purestone9** [comment]
Im running lolMiner on windows 10, here is a picture showing that i was able to get it back and i am able to run it after getting the exe back in the folder

![image](https://user-images.githubusercontent.com/29181158/121603804-98f8f880-ca06-11eb-8f04-a679aaabddbe.png)

**Comment by pdieppa** [comment]
Your anti-virus is deleting the file. You must add an exception for the miner directory to your AV. All AV programs flag most miners are malware.

**Comment by jgonzis** [comment]
No user answer...
