### ISSUE TITLE
Wallet Reset

### ISSUE THREAD

**Issue by billquick** [Lolliedieb/lolMiner-releases#616]
I downloaded the 1.28 lolminer batch files and was running it smoothly for two days continuously with no issues. Today at 6pm I checked my 2miner pool to see the status, and it showed no workers were active for 2 hours. I pulled up the miner and it was still running, so I checked the batch file info. Sure enough the wallet had switched back to the default wallet address that comes pre configured in the download. I had not touched the computer in over 12 hours, there were no heating or technical issues that I could see that might cause this, am I missing something? I am worried it will happen again and continue to mine to someone elses wallet Edit; windows 10 on intel processor and 1080ti with up to date drivers

**Comment by jgonzis** [comment]
That is not for the miner... you should check the pool, the miner cannot modify a Wallet.
