### ISSUE TITLE
gpu detection thread timed out on card 0 of opencl platform 0

### ISSUE THREAD

**Issue by danilomnds** [Lolliedieb/lolMiner-releases#618]
I'm working with 3 rx 550 4gb.

I'm receiving the error below:

gpu detection thread timed out on card 0 of opencl platform 0

Follow my configurations:

--worker %WORKER_NAME%
--ethstratum ETHPROXY
--4g-alloc-size 4062
--zombie-tune auto

I didn't apply any overclock template.

Do you have an ideia about what's going on?

**Comment by danilomnds** [comment]
PS: I have a Hiveos

**Comment by jgonzis** [comment]
That seems to be that you cannot allocate that 4062...

Can you try 4000,4062,4062?

Just to give 4000 to gpu0 and 4062 to gpu 1 and 2

**Comment by jgonzis** [comment]
No problem or feedback... close issue
