### ISSUE TITLE
Excessive RAM usage + Crash

### ISSUE THREAD

**Issue by martinviz** [Lolliedieb/lolMiner-releases#619]
Hello, 
I have the lolminer on two machines - one on my gaming PC another on mining RIG. The problem is with my mining rig, when I launch the lolminer on my mining rig it requires ~ 560MB of RAM, after about 12hours it shows ~1530MB, after 18/20 hours ~2000MB, and finally, it crashes and stops. Does anyone have any idea how to fix it? My rig has 8GB DDR4 3000mhz RAM.

![IMG_2078](https://user-images.githubusercontent.com/85966723/122123118-4bc9bc00-ce36-11eb-85b3-38c4c951a5ab.jpg)

**Comment by jgonzis** [comment]
> Hello,
> I have the lolminer on two machines - one on my gaming PC another on mining RIG. The problem is with my mining rig, when I launch the lolminer on my mining rig it requires ~ 560MB of RAM, after about 12hours it shows ~1530MB, after 18/20 hours ~2000MB, and finally, it crashes and stops. Does anyone have any idea how to fix it? My rig has 8GB DDR4 3000mhz RAM.
> 
> ![IMG_2078](https://user-images.githubusercontent.com/85966723/122123118-4bc9bc00-ce36-11eb-85b3-38c4c951a5ab.jpg)

Could you try to increase the virtual memory disk of Windows?. I understand you are using both in Windows...

**Comment by jgonzis** [comment]
No user answer...
