### ISSUE TITLE
Help menu will not display on windows without drivers loaded.

### ISSUE THREAD

**Issue by mechanator** [Lolliedieb/lolMiner-releases#62]
On a windows 10 build, you cannot bring up the --help options for display, the miner brings up a dialog box of "no opencl drivers" and terminates without producing output.
Steps to reproduce:

Windows 10, no AMD drivers drivers loaded.
or
Windows 10, Nvidia opencl 2 drivers loaded for a GTX 580 card
Open command prompt
run lolminer.exe --help
Get dialog box error mesage about no open cl loaded.
exits to command prompt.

Possible fix:
Report on the command line that mining cannot proceed until you have the drivers/opencl installed correctly.
At the logic juncture to execute even a simple non mining option, like --help, do the output even though mining is impossible.
Possibly spit out a static URL to a wiki or help resource page for lolminer.

Results:
Cosmetically and logically makes sense.

**Comment by jgonzis** [comment]
Solved with latest releases
