### ISSUE TITLE
I mine 4 hours and hashrate down to 0 mh/s

### ISSUE THREAD

**Issue by infidus46** [Lolliedieb/lolMiner-releases#622]
hi, i mine 4 hours+- and my rig hashrate down to 0 mh/s. Windows 10, 1060 6 gb, 3060 ti

**Comment by jgonzis** [comment]
> hi, i mine 4 hours+- and my rig hashrate down to 0 mh/s. Windows 10, 1060 6 gb, 3060 ti

Which lolMiner Version are you using?. Last version should loop in case extra OC memory that make them crash

**Comment by infidus46** [comment]
> > hi, i mine 4 hours+- and my rig hashrate down to 0 mh/s. Windows 10, 1060 6 gb, 3060 ti
> 
> Which lolMiner Version are you using?. Last version should loop in case extra OC memory that make them crash

last version, not restart. and i see all time 0 mh/s when crush gpu. problem on ETHASH, ETCHASH is good

**Comment by jgonzis** [comment]
Have you try last version 1.48?

**Comment by jgonzis** [comment]
No more feedback
