### ISSUE TITLE
All devices deselected or failed compatiblity check. Closing lolMiner

### ISSUE THREAD

**Issue by edris-007** [Lolliedieb/lolMiner-releases#626]

**Comment by jgonzis** [comment]
> Setup Miner...
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 0
> Cuda driver detected.
> Number of Cuda supported GPUs: 0
> 
> Connecting to pool...
> Connected to ethash.unmineable.com:3333 (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Authorized worker: BTC:3CjbVR3FGWooEf2V964qxTFg8gDRAYAVbm.unknown
> New job received: 0x7bf205 Epoch: 422 Target: 000000007e000000
> Start Mining...
> All devices deselected or failed compatiblity check. Closing lolMiner

Which complete model is your GPU?

**Comment by jgonzis** [comment]
No more Feedback
