### ISSUE TITLE
lost connection to ethermine.org or server not reachable

### ISSUE THREAD

**Issue by deea156** [Lolliedieb/lolMiner-releases#629]
Hi, 

About 17 hours ago I "lost" my miner and since then I keep getting the following message: "lost connection to stratum server eu1.ethermine.org: 4444 or server not reachable. Trying to connect in 1 second"... and, beside keep receiving this message, nothing happen. I changed the server,  from asia1 to eu1, to us1 and us2, I changed the stratum port to alt. stratum port but nothing. 
Please help.

**Comment by jgonzis** [comment]
> Hi,
> 
> About 17 hours ago I "lost" my miner and since then I keep getting the following message: "lost connection to stratum server eu1.ethermine.org: 4444 or server not reachable. Trying to connect in 1 second"... and, beside keep receiving this message, nothing happen. I changed the server, from asia1 to eu1, to us1 and us2, I changed the stratum port to alt. stratum port but nothing.
> Please help.

That is something related to Internet or Service providers.... not to the miner. You can try to connect to ssl port, but remember to add parameter --tls on
You can also make a try to connect to other pool,

**Comment by jgonzis** [comment]
No more Feedback
