### ISSUE TITLE
Is Lolminer v1.08 ETHASH compatible with NiceHash?

### ISSUE THREAD

**Issue by RainbowMiner** [Lolliedieb/lolMiner-releases#63]
.. which --ethstratum to use? Or is it incompatible, for now?

**Comment by Lolliedieb** [comment]
Generally it should work in the standard mode, but indeed there are some fixes coming soon of stuff I only recently discovered when using Nicehash ... well will not take long -> this weekend :)

**Comment by RainbowMiner** [comment]
Super :) so I will wait for the fixes, before I enable Ethash on Nicehash with lolminer for my RainbowMiner users.

**Comment by Lolliedieb** [comment]
Done :D
