### ISSUE TITLE
Mining lock after 4 hours (RTX 3060)

### ISSUE THREAD

**Issue by noeXzTi** [Lolliedieb/lolMiner-releases#630]
I have a EVGA RTX 3060 mining ETH with Hive OS, and I have seen an issue where after 4 hours of mining (approximately), the mining lock kicks in and lolminer isn’t able to rise the hashrate again.

Is this a known issue with the 3060 Boost? I’m using the NVIDIA 460.39 driver, and the RTX 3060 is the unique GPU connected.

**Comment by jgonzis** [comment]
> I have a EVGA RTX 3060 mining ETH with Hive OS, and I have seen an issue where after 4 hours of mining (approximately), the mining lock kicks in and lolminer isn’t able to rise the hashrate again.
> 
> Is this a known issue with the 3060 Boost? I’m using the NVIDIA 460.39 driver, and the RTX 3060 is the unique GPU connected.

That could happen when it is a Epoch change, just only reboot or restart miner and that will be solve. EPOCH change each 4-5days.

**Comment by pdieppa** [comment]
I have seen this too. The way I have solved the problem is to set the hashrate watchdog.
![image](https://user-images.githubusercontent.com/74556152/123452680-a4bef000-d5ac-11eb-9c17-e5b933a29e0b.png)

**Comment by jgonzis** [comment]
> I have seen this too. The way I have solved the problem is to set the hashrate watchdog.
> ![image](https://user-images.githubusercontent.com/74556152/123452680-a4bef000-d5ac-11eb-9c17-e5b933a29e0b.png)

Nice option too...

**Comment by jgonzis** [comment]
With 1.62 working with new unlock drivers of Nvidia.
