### ISSUE TITLE
All device deselected or failed compatibility check.

### ISSUE THREAD

**Issue by kido-kit-kat** [Lolliedieb/lolMiner-releases#631]
Getting this error when trying to do mining using AMD graphics.

![image](https://user-images.githubusercontent.com/62174595/123702525-dec81480-d880-11eb-9794-fe129e29d8ac.png)

**Comment by jgonzis** [comment]
> Getting this error when trying to do mining using AMD graphics.
> 
> ![image](https://user-images.githubusercontent.com/62174595/123702525-dec81480-d880-11eb-9794-fe129e29d8ac.png)

That's normal... you are trying to mine ETH with a 3Gb card... that's not possible. You can only try to mine ETC for example.
