### ISSUE TITLE
All devices deselected or failed compatiblity check. Closing lolMiner

### ISSUE THREAD

**Issue by nikeus10** [Lolliedieb/lolMiner-releases#634]
![123](https://user-images.githubusercontent.com/54740481/123937711-0629f900-d9c9-11eb-8629-426fc25bd3eb.jpg)

GPU:MSI VEGA56

**Comment by jgonzis** [comment]
> ![123](https://user-images.githubusercontent.com/54740481/123937711-0629f900-d9c9-11eb-8629-426fc25bd3eb.jpg)
> 
> GPU:MSI VEGA56

That seems to be a driver problem... which Windows AMD driver are you using?. It has been reported that last AMD driver is not yet working.

**Comment by jgonzis** [comment]
No more Feedback
