### ISSUE TITLE
Client crashes and results in a GPU memory leak when --keepfree parameter is too high

### ISSUE THREAD

**Issue by Pxartist** [Lolliedieb/lolMiner-releases#636]
I am using a AMD 6900XT to mine and was trying to reduce the intensity of the mining  strain with the --keepfree parameter. However, upon entering values above 1000, the client would crash and the allocated VRAM would still continue to be allocated.

**Comment by jgonzis** [comment]
the keepfree parameter was used for the Zombie mode ... that should be used for a Big Navi with 16Gb
