### ISSUE TITLE
Epoch 0

### ISSUE THREAD

**Issue by rewrewby** [Lolliedieb/lolMiner-releases#64]
**v1.09**
`New Feature: Jobs send with epoch 0 will cause the miner to pause (this might help burning less energy on Nicehash when they run out of work)`

Epoch 0 is a Zilliqa (ZIL) mining with Ethash. You shouldn't pause the miner anyway!

**Comment by Lolliedieb** [comment]
Hmm ... this is interesting. Can you give me more details about this, since I had some mayor trouble (miner got stuck) when epoch 0 got send by the pool. So thats why I disabled it. But I can revert this in case its useful for Zilliqa mining.

**Comment by rewrewby** [comment]
Please refer to https://github.com/Zilliqa/Zilliqa/wiki/Mining

`Zilliqa is using Ethash for its PoW algorithm. Hence, Zilliqa uses a DAG in its proof-of-work algorithm, that is generated at an incremental rate for each DS epoch. The bootstrap DAG size will be roughly 1.02GB.`

Now is **8092** DS Epoch only.
P.S. You can see Nicehash Daggerhashimoto prices increases ~ every 100 minutes - it's ZIL mining window.
lolMiner is the only option for AMD cards to mine ZIL on Nicehash or directly on pools. But you disabled it. :\

**Comment by Lolliedieb** [comment]
I have the feeling that I do not understand it right. Or maybe I do, but that scheme was unknown to me.

So at the beginning of each DS epoch the ethash epoch is 0 for 60 seconds. Task is to submit a high diff share in this time to qualify to continue mining with other ethash epochs in that window? Did I get that right? Thats something I was not aware / familiar with yet and when epoch 0 mining is required I will do needed changes to get it going again with next release.

**Comment by rewrewby** [comment]
Yes, ZIL mining window about 60-90 sec (you can set it in node's config). At first you mine to be a shard node (current diff is 799.64G), and once you get and submit "shard" share to node, at second ZIL node send you a new work for mining to qualify for DS node (current diff is 173.22T). So I'm not sure about other pools (I think they are giving a job to miners with target 799.64G and 173.22T and in that way you don't see shares and think that lolMiner "stucks"), but our https://k1pool.com/pool/zil requests shares with low diff (3G) and submit only "shard" or "DS" shares to node.
So you must to return epoch 0 mining to lolMiner. :)

**Comment by Lolliedieb** [comment]
I just found the bug that caused my miner to freeze in the epoch 0 case. Will fix this now gradually for all kernels, but can confirm the next release will support ZIL mining in full.

**Comment by rewrewby** [comment]
Lolliedieb, how to contact you in Telegram?

**Comment by Lolliedieb** [comment]
Same nickname as here @Lolliedieb  :)
