### ISSUE TITLE
3060 unlock not working with 1.3

### ISSUE THREAD

**Issue by MoreWillFollow** [Lolliedieb/lolMiner-releases#644]
All 3 RTX 3060 in rig goest above 22 Mh/s when locking detected. 
Same settings, same OC but with 1.2 works fine and all 3 cards get 39-41 Mh/s.  

Must be some bug...
![Screen Shot 2021-07-04 at 3 14 09 AM](https://user-images.githubusercontent.com/9204243/124368900-f8010480-dc76-11eb-9c9c-5430f00a2585.png)

**Comment by jgonzis** [comment]
Could you try to work with FIX Core?

**Comment by MoreWillFollow** [comment]
It helped a little. But after 1 hour mining issue happens again. But this time no notification about lock detection and adjusting things... Hashrate drops to 21.5 and nothing else happens. 
![Screen Shot 2021-07-04 at 5 11 11 PM](https://user-images.githubusercontent.com/9204243/124386383-3c2dec80-dceb-11eb-972a-67c56470a19b.png)

This is card's settings: 
![Screen Shot 2021-07-04 at 5 11 11 PM](https://user-images.githubusercontent.com/9204243/124386414-5667ca80-dceb-11eb-82ae-fc557b0fdbbf.png)

**Comment by jgonzis** [comment]
Take out PL concept on GPU0 if that works

**Comment by MoreWillFollow** [comment]
That doesn't help too... 20 minutes. Got "detected mining lock" notification and now all 3 card's are down to 21Mh/s and can't recover back no normal hashrate.

**Comment by hss78** [comment]
I got 42mh after the update ,I dont know what i did  :) After the reset its gone and now 38Mh. (-250,2600,115)
I think its so close we get full 50 mh.

**Comment by niagars** [comment]
After updating I also have 21 MH, changed the lolminer to 1.29 and became 38 again. You just have to wait for the bug fixes.

**Comment by jgonzis** [comment]
> After updating I also have 21 MH, changed the lolminer to 1.29 and became 38 again. You just have to wait for the bug fixes.

Interesting lot of dispair people... some getting the extra Mhs and other get the card blocked...

**Comment by MoreWillFollow** [comment]
This is what I'm able get now. Works fine, pretty stable (3 hours already):

![Screen Shot 2021-07-04 at 8 27 21 PM](https://user-images.githubusercontent.com/9204243/124392412-75c02100-dd06-11eb-8733-cceb0a83d82c.png)


Best part with 1.3 power consumption reduced by 44 W for 3 cards (approx. 32KW/month).

**Comment by jgonzis** [comment]
> This is what I'm able get now. Works fine, pretty stable (3 hours already):
> 
> ![Screen Shot 2021-07-04 at 8 27 21 PM](https://user-images.githubusercontent.com/9204243/124392412-75c02100-dd06-11eb-8733-cceb0a83d82c.png)
> 
> Best part with 1.3 power consumption reduced by 44 W for 3 cards (approx. 32KW/month).

Great Job.... How did you get it working?...

**Comment by MoreWillFollow** [comment]
> > This is what I'm able get now. Works fine, pretty stable (3 hours already):
> > ![Screen Shot 2021-07-04 at 8 27 21 PM](https://user-images.githubusercontent.com/9204243/124392412-75c02100-dd06-11eb-8733-cceb0a83d82c.png)
> > Best part with 1.3 power consumption reduced by 44 W for 3 cards (approx. 32KW/month).
> 
> Great Job.... How did you get it working?...

Delay before applying overclock helped. I tried 45 seconds and it works fine with this settings. I guess settings may be different, but delay will solve issue with mining detection...

**Comment by jgonzis** [comment]
> After updating I also have 21 MH, changed the lolminer to 1.29 and became 38 again. You just have to wait for the bug fixes.

Could you take out the Power Limit and work with a Fix Clock? Just only to try like the others did. Do this test with a reboot

**Comment by wulong2020** [comment]
After upgrading lol to 1.3, the operation is very stable,
There is a question, the same OC, 3070 can reach 62.37M with T-rex hash, but the lol is only about 61.5M?
![Snipaste_2021-07-05_22-06-13](https://user-images.githubusercontent.com/86549530/124484229-c5255080-dddd-11eb-99e4-f737f0ab44b9.png)

**Comment by jgonzis** [comment]
> After upgrading lol to 1.3, the operation is very stable,
> There is a question, the same OC, 3070 can reach 62.37M with T-rex hash, but the lol is only about 61.5M?
> ![Snipaste_2021-07-05_22-06-13](https://user-images.githubusercontent.com/86549530/124484229-c5255080-dddd-11eb-99e4-f737f0ab44b9.png)

You should not check reported hashrate... that can be very easy modify it... only do Reported Hashrate = Real HashRate +2%... Then all people will think you have the faster miner. To know the reality you should check average hashrate in pool for a long time. To do that put them all to a pool one one miner ... and watch the real received hashrate for a week. Make a note every day same time. Then re-do same with lolMiner and compare number of received shares. Then you will realise, which miner say real hash and which one inflates his hashrate to have more users...
And you will realise that lolMiner don't inflate his hashrate.



> > > This is what I'm able get now. Works fine, pretty stable (3 hours already):
> > > ![Screen Shot 2021-07-04 at 8 27 21 PM](https://user-images.githubusercontent.com/9204243/124392412-75c02100-dd06-11eb-8733-cceb0a83d82c.png)
> > > Best part with 1.3 power consumption reduced by 44 W for 3 cards (approx. 32KW/month).
> > 
> > 
> > Great Job.... How did you get it working?...
> 
> Delay before applying overclock helped. I tried 45 seconds and it works fine with this settings. I guess settings may be different, but delay will solve issue with mining detection...

Nice information...

**Comment by niagars** [comment]
> > After updating I also have 21 MH, changed the lolminer to 1.29 and became 38 again. You just have to wait for the bug fixes.
> 
> Could you take out the Power Limit and work with a Fix Clock? Just only to try like the others did. Do this test with a reboot

I tried, but again the same, all settings were in default, the system rebooted, more than 22 MH was not. Probably, this is because I have AMD cards in one rig and miner 1.3 does not work correctly.

**Comment by jgonzis** [comment]
That is solved now with 1.31

Try new version!!!

**Comment by niagars** [comment]
Thank developers. Everything works great. Hashrate has risen, the power has lowered, works without interruptions. Version 1.31 Fixed and completed.
