### ISSUE TITLE
Unable to Mine on a RX6700 XT 

### ISSUE THREAD

**Issue by final-method** [Lolliedieb/lolMiner-releases#645]
I am unable to mine. By any chance would you know how to fix this error?

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    Radeon RX 6700XT
    Address: 8:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  12272 MByte (12208 MByte free)
**Build Log: Error: AMD HSA Code Object loading failed.**

    **Problem in loading kernel
    Active:  false (Unsupported device or driver version.)**

Connecting to pool...
Connected to us2.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x03027555a0edE85Af657ECf71f14c88f218427bC.lolMinerWorker
New job received: 0x24c4a0 Epoch: 425 Target: 00000000ffff0000
0x0000012145B31F80 (0x0000000000000000 0x0000000000000000 0x0000000200000000 0x0000000000000000) <unknown module>
0x00007FF7DE34A6AD (0x0000000000000000 0x0000001DC12FED98 0x0000012145B32A60 0x00007FF7DE34A917)
0x00007FF7DE13284A (0x0000012145B32A60 0x0000001DC15FFE78 0x0000012145B32A60 0x00007FF87F0E07B0)
0x00007FF7DE043855 (0x0000000000000057 0x000001214F299190 0x0000000000000000 0x0000000000000005)
0x00007FF7DE042F49 (0x000001214F299190 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF7DE3643A4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF87D237034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF87F0E2651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
Press any key to continue . . .

**Comment by jgonzis** [comment]
> I am unable to mine. By any chance would you know how to fix this error?
> 
> Setup Miner...
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 1
> No Cuda driver or GPUs detected.
> Device 0:
> Name: Radeon RX 6700XT
> Address: 8:0
> Vendor: Advanced Micro Devices (AMD)
> Drivers: OpenCL
> Memory: 12272 MByte (12208 MByte free)
> **Build Log: Error: AMD HSA Code Object loading failed.**
> 
> ```
> **Problem in loading kernel
> Active:  false (Unsupported device or driver version.)**
> ```
> 
> Connecting to pool...
> Connected to us2.ethermine.org:4444 (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Authorized worker: 0x03027555a0edE85Af657ECf71f14c88f218427bC.lolMinerWorker
> New job received: 0x24c4a0 Epoch: 425 Target: 00000000ffff0000
> 0x0000012145B31F80 (0x0000000000000000 0x0000000000000000 0x0000000200000000 0x0000000000000000)
> 0x00007FF7DE34A6AD (0x0000000000000000 0x0000001DC12FED98 0x0000012145B32A60 0x00007FF7DE34A917)
> 0x00007FF7DE13284A (0x0000012145B32A60 0x0000001DC15FFE78 0x0000012145B32A60 0x00007FF87F0E07B0)
> 0x00007FF7DE043855 (0x0000000000000057 0x000001214F299190 0x0000000000000000 0x0000000000000005)
> 0x00007FF7DE042F49 (0x000001214F299190 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FF7DE3643A4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FF87D237034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
> 0x00007FF87F0E2651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
> Press any key to continue . . .

I think, it was said in telegram that new AMD Drivers are not working yet in Windows. Dev has said he will try in the next Windows release, so the best solution now is to DDU the driver and install the previous version.
