### ISSUE TITLE
"conversion of data to type "b" failed" on nicehash pool

### ISSUE THREAD

**Issue by imperialgames** [Lolliedieb/lolMiner-releases#648]
Hi, just upgraded to 1.3.0, i have this error with nicehash pool.

1.2.9 is working fine.

**Comment by Fireqc** [comment]
same here...  +1

**Comment by bekman1** [comment]
same error

**Comment by jgonzis** [comment]
> Hi, just upgraded to 1.3.0, i have this error with nicehash pool.
> 
> 1.2.9 is working fine.

It seems to be a bug with the nicehash, the Developer said in the Telegram Group he will realease an update soon with that problem solve :-)

**Comment by LordDrakath** [comment]
Same issue, same resolution as everyone else.

**Comment by jgonzis** [comment]
That is solved now with 1.31

Try new version!!!
