### ISSUE TITLE
Why does lolminer use 3070 hashrate lower than t-rex and nbminer?

### ISSUE THREAD

**Issue by wulong2020** [Lolliedieb/lolMiner-releases#651]
After upgrading lol to 1.3, the operation is very stable,

but，There is a question, the same OC, RTX3070 can reach 62.37M with T-rex hash, but the lol is only about 61.5M?
![Snipaste_2021-07-05_22-06-13](https://user-images.githubusercontent.com/86549530/124484346-e71ed300-dddd-11eb-90ec-bfd2bf48ebd4.png)

**Comment by jgonzis** [comment]
> After upgrading lol to 1.3, the operation is very stable,
> 
> but，There is a question, the same OC, RTX3070 can reach 62.37M with T-rex hash, but the lol is only about 61.5M?
> ![Snipaste_2021-07-05_22-06-13](https://user-images.githubusercontent.com/86549530/124484346-e71ed300-dddd-11eb-90ec-bfd2bf48ebd4.png)

You should not check reported hashrate... that can be very easy modify it... only do Reported Hashrate = Real HashRate +2%... Then all people will think you have the faster  miner. To know the reality you should check average hashrate in pool for a long time. To do that put them all to a pool one one miner ... and watch the real received hashrate for a week. Make a note every day same time. Then re-do same with lolMiner and compare number of received shares. Then you will realise, which miner say real hash and which one inflates his hashrate to have more users... 
And you will realise that lolMiner don't inflate his hashrate.
