### ISSUE TITLE
 Run lolminer 1.3 error report

### ISSUE THREAD

**Issue by wulong2020** [Lolliedieb/lolMiner-releases#652]
After running for a few hours, if the following error message is reported, lolminer will restart:
===========================================
Unrecoverable memory error by GPU 2.
Reset of all Cuda GPUs required.
Please check your (memory) OC & UV settings on this card.
New job received: 0x542ce7 Epoch: 425 Target: 000000016e80fe03 
Device 0 detected as crashed. 
Closing miner and trying to call external script: ./emergency.sh (--watchdog script) 

<img width="435" alt="Snipaste_2021-07-06_08-52-55" src="https://user-images.githubusercontent.com/86549530/124527591-8ffa1c00-de38-11eb-8e84-b080c09340cd.png">

After trying to reduce the video memory frequency from 2500 to 2400, the error will still occur

<img width="1234" alt="Snipaste_2021-07-06_09-03-34" src="https://user-images.githubusercontent.com/86549530/124527850-3f36f300-de39-11eb-95fe-aa97f698df6a.png">

**Comment by jgonzis** [comment]
> # After running for a few hours, if the following error message is reported, lolminer will restart:
> Unrecoverable memory error by GPU 2.
> Reset of all Cuda GPUs required.
> Please check your (memory) OC & UV settings on this card.
> New job received: 0x542ce7 Epoch: 425 Target: 000000016e80fe03
> Device 0 detected as crashed.
> Closing miner and trying to call external script: ./emergency.sh (--watchdog script)
> 
> <img alt="Snipaste_2021-07-06_08-52-55" width="435" src="https://user-images.githubusercontent.com/86549530/124527591-8ffa1c00-de38-11eb-8e84-b080c09340cd.png">
> 
> After trying to reduce the video memory frequency from 2500 to 2400, the error will still occur
> 
> <img alt="Snipaste_2021-07-06_09-03-34" width="1234" src="https://user-images.githubusercontent.com/86549530/124527850-3f36f300-de39-11eb-95fe-aa97f698df6a.png">

Could you try to reduce Memory OC to 2200 for example... 2400 is quite up and could be the problem of the crash...
