### ISSUE TITLE
lolMiner 1.30 not starting  (any algorithm / Windows 10 / AMD & NVIDIA cards)

### ISSUE THREAD

**Issue by UselessGuru** [Lolliedieb/lolMiner-releases#655]
Miner just closes after 'Setup Miner'.

It does not even write anything to the log file.

Command line used:

`lolminer.exe --algo BEAM-III --pool BEAMV3.eu-west.nicehash.com:3387 --user ###############################.####### --pass x --tls off --log on --apiport 4001 --shortstats=1 --longstats=30 --logfile=.\lolminer.log
`

**Comment by jgonzis** [comment]
> Miner just closes after 'Setup Miner'.
> 
> It does not even write anything to the log file.
> 
> Command line used:
> 
> `lolminer.exe --algo BEAM-III --pool BEAMV3.eu-west.nicehash.com:3387 --user ###############################.####### --pass x --tls off --log on --apiport 4001 --shortstats=1 --longstats=30 --logfile=.\lolminer.log `

Could you describe which cards are you using?
Have you tryed the 1.28a?.

**Comment by UselessGuru** [comment]
> Have you tryed the 1.28a?.

Working fine

> Could you describe which cards are you using?

AMD RX5700XT & RX580 8GB (Driver version 3224.5 / 2021.3.2)
NVIDIA GTX 1660 Super & RX750 (Driver version 466.77)

**Comment by jgonzis** [comment]
> > Have you tryed the 1.28a?.
> 
> Working fine
> 
> > Could you describe which cards are you using?
> 
> AMD RX5700XT & RX580 8GB (Driver version 3224.5 / 2021.3.2)
> NVIDIA GTX 1660 Super & RX750 (Driver version 466.77)

Many thanks for the fast answer, let's hope that info help the Dev too...

**Comment by jgonzis** [comment]
That is solved now with 1.31

Try new version!!!

**Comment by UselessGuru** [comment]
Problem is solved with 1.31. Thank you!
