### ISSUE TITLE
Lolminer 1.3 not starting in Eth

### ISSUE THREAD

**Issue by RunOrDrink** [Lolliedieb/lolMiner-releases#657]
Hi, my problem with 1.3 after i edit the eth batch with adress pool and wallet, when i start the miner it shows me “ starting mine” and after that i get the msg “press any key to continue”. Is not even showing me all the gpus or at least to get to the dag. 

All i did in batch is to setup the pool, wallet adress and name of the miner. Lolminer.exe is in my antivirus exception.

**Comment by UselessGuru** [comment]
Same as this?

https://github.com/Lolliedieb/lolMiner-releases/issues/655

**Comment by RunOrDrink** [comment]
> Same as this?
> 
> #655

Yes, but i’m using only nvidia and for me all the other versions of lolminer works fine

**Comment by jgonzis** [comment]
It seems Version 1.30 is not working properly in Windows. It seem the detection of GPU at start is not working. We have to still use the version 1.28a

**Comment by jgonzis** [comment]
That is solved now with 1.31 

Try new version!!!
