### ISSUE TITLE
RTX 3060 gets black screen after grub load

### ISSUE THREAD

**Issue by fabionvs** [Lolliedieb/lolMiner-releases#658]
Hello there,
when I install NVIDIA-Linux-x86_64-460.39.run my screen gets black after grub loading.
I am using RTX 3060 and I couldn't use or install 460.39 (linux gets black screen) and 470.05 (windows says not compatible before install).  My video card was developed on may/2021, is there any way to unlock it? When I try to install HiveOS my screen gets black too when it starts to boot. I am starting to think it is not possible to unlock my video card. Is there any path I could get unlock success?

**Comment by pdieppa** [comment]
Make sure you are updating your video drivers using SSH. Don't use any other method including the console.

**Comment by jgonzis** [comment]
That seems not to be a miner problem... is more system problem... try to check with another GPU if it is a problem of GPU Problem or you have the new 3060 LHR v2
