### ISSUE TITLE
Miner ignore password

### ISSUE THREAD

**Issue by Gondagar** [Lolliedieb/lolMiner-releases#66]
Please fix send password to pool with -esm 0 (ETHPROXY)
Miner ignore --pass in bat file

**Comment by Lolliedieb** [comment]
Can you show me the pool where this happens?
Because generally the password is sent (since 1.10 ... 1.08 / 1.09 were indeed buggy)
So if the issue is still there I need to dive a bit deeper to figure out what is going on

**Comment by Gondagar** [comment]
zergpool.com

пт, 16 жовт. 2020 о 12:44 Lolliedieb <notifications@github.com> пише:

**Comment by mechanator** [comment]
Seems to work fine with options to convert mined ethash to BTC on zergpool.com:9999
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --devices AMD --pass c=BTC          for example in windows.

**Comment by jgonzis** [comment]
Solved with the autoswitch ethproxy and Nicehash Proto 1.0
