### ISSUE TITLE
Upgraded two systems & both were not registering on Ethermine

### ISSUE THREAD

**Issue by NadoJoe** [Lolliedieb/lolMiner-releases#660]
I upgraded both and just added my address and name as always and they were runn ing for about an hour or so and then I noticed that they were not showing up on the list with my rig and another computer that I didnt update.  I noticed that the information in the bat file had tons of new stuff under the non editable section.  Did everyone else keep that as is?

**Comment by jgonzis** [comment]
You have to edit the beginning of the file... the new bat file is to people that don't know you to run as administrator. It automaticly search the lolminer.exe 

Could you show some pictures of the  start and mining to see what's happening

**Comment by NadoJoe** [comment]
Yeah, the only part that I changed was the Pool line and wallet address part.  I noticed that there are two sections there for two pool options.  DO i need to leave that there as is? normally I use this (set "<POOL=eu1.ethermine.org>:<4444>" )

**Comment by jgonzis** [comment]
> Yeah, the only part that I changed was the Pool line and wallet address part. I noticed that there are two sections there for two pool options. DO i need to leave that there as is? normally I use this (set "<POOL=eu1.ethermine.org>:<4444>" )

There are 2 pools to have also backup pool, eu1.ethermine.org:4444 and eu1.ethermine.org:14444

**Comment by NadoJoe** [comment]
My apologies. I haven’t had a chance to change it back Bc I was losing money leaving it on when it wasn’t being recognized. Not sure what u wanted. Two miners were working but werent. showing up in  My online workers. Then I rebooted them both and one continued and still didn’t show up and the other got an error message. That will possibly be hard to duplicate but I will try soon. Just have to take it off like and be off work so I can check on it.

Joey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
