### ISSUE TITLE
error when allocating memory or building DAG. Disabling card. (Version 1.28a)

### ISSUE THREAD

**Issue by Palerm0** [Lolliedieb/lolMiner-releases#661]
Hi, 
I've been googling for sometime now. But I could not find a solution.
As of today (Mining ETH for some month now with version 1.28a) I`m getting this error on 2 cards.
One is still working.

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 3
Cuda driver detected.
Number of Cuda supported GPUs: 3
Device 0:
    Name:    NVIDIA GeForce GTX 1070 Ti
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  8192 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
Device 1:
    Name:    NVIDIA GeForce GTX 1070
    Address: 2:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  8192 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
Device 2:
    Name:    NVIDIA GeForce GTX 1070
    Address: 8:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  8192 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)

Connecting to pool...
Connected to eu1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: XXXXX
Start Mining...
GPU 1: error when allocating memory or building DAG. Disabling card.
GPU 0: error when allocating memory or building DAG. Disabling card.

How is this possible after working all the time. And stops working today.
Does anyone have an idea?

Thanks in advance
Greetings
Palermo

**Comment by jgonzis** [comment]
> Hi,
> I've been googling for sometime now. But I could not find a solution.
> As of today (Mining ETH for some month now with version 1.28a) I`m getting this error on 2 cards.
> One is still working.
> 
> Setup Miner...
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 3
> Cuda driver detected.
> Number of Cuda supported GPUs: 3
> Device 0:
> Name: NVIDIA GeForce GTX 1070 Ti
> Address: 1:0
> Vendor: NVIDIA Corporation
> Drivers: Cuda, OpenCL
> Memory: 8192 MByte
> Active: true (Selected Algorithm: ETHash Cuda)
> Device 1:
> Name: NVIDIA GeForce GTX 1070
> Address: 2:0
> Vendor: NVIDIA Corporation
> Drivers: Cuda, OpenCL
> Memory: 8192 MByte
> Active: true (Selected Algorithm: ETHash Cuda)
> Device 2:
> Name: NVIDIA GeForce GTX 1070
> Address: 8:0
> Vendor: NVIDIA Corporation
> Drivers: Cuda, OpenCL
> Memory: 8192 MByte
> Active: true (Selected Algorithm: ETHash Cuda)
> 
> Connecting to pool...
> Connected to eu1.ethermine.org:4444 (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Authorized worker: XXXXX
> Start Mining...
> GPU 1: error when allocating memory or building DAG. Disabling card.
> GPU 0: error when allocating memory or building DAG. Disabling card.
> 
> How is this possible after working all the time. And stops working today.
> Does anyone have an idea?
> 
> Thanks in advance
> Greetings
> Palermo

You have to increase the Virtual Disk of Windows. 

Try to put 80000 - 80000

https://www.hellotech.com/guide/for/how-to-increase-virtual-memory
