### ISSUE TITLE
New 3060 with LHS PCI Device ID 2504.

### ISSUE THREAD

**Issue by wtferror** [Lolliedieb/lolMiner-releases#662]
Hello guys. 

We have any path to follow about the new 3060 with Device ID 2504?

I see about the drivers to unlock are before that new 3060. 

https://www.techworm.net/2021/04/rtx-3060-cryptomining-hash-limiters.html

**Comment by jgonzis** [comment]
You are right... Device ID 2504 is the new 3060 LHR. 

So you need to update your drivers. To show the complete device name

**Comment by 5helloworld** [comment]
https://github.com/Lolliedieb/lolMiner-releases/issues/683
My experience may help you
