### ISSUE TITLE
lolminer.exe is not found in the system

### ISSUE THREAD

**Issue by vitekc45c** [Lolliedieb/lolMiner-releases#670]
lolminer v1.31
Windows 10 Home Edition 64bit
NVIDIA GeForce RTX 2070

"Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
"lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
Press any key to continue . . .

lolminer is installed on D: drive
Adding exemption to windows defender does not help

**Comment by pdieppa** [comment]
Please post the command line.

**Comment by jgonzis** [comment]
> lolminer v1.31
> Windows 10 Home Edition 64bit
> NVIDIA GeForce RTX 2070
> 
> "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> Press any key to continue . . .
> 
> lolminer is installed on D: drive
> Adding exemption to windows defender does not help

Ok... I know the problem... Could you please put it in the C: Drive?. The search is done only in the C: Unit...  you are trying to run it as administrator (that's perfect). But that makes to go to C:\Windows\System32... and then the search start in the C Unit... so if you copy that folder in the C: Unit the the search will found it automaticly

**Comment by vitekc45c** [comment]
Yes, it works on C: , but I´d rather have it installed on my second drive. Is there some setting I can eddit to point it to the right folder?

**Comment by jgonzis** [comment]
> Yes, it works on C: , but I´d rather have it installed on my second drive. Is there some setting I can eddit to point it to the right folder?

yes of course you can... 

Change:
%MyVariable% --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET!  --watchdog exit 

For: 
D:\FOLDER_OF_LOLMINER\lolMiner.exe  --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET!  --watchdog exit 

I hope that helps you

**Comment by vitekc45c** [comment]
Changed the following lines in mine_eth.bat

:W10
D:\Program Files (x86)\lolMiner\1.31\lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET!  --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
D:\Program Files (x86)\lolMiner\1.31\lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

still getting the same error

**Comment by jgonzis** [comment]
Just put in d:\lolMiner\ your problem is not writing properly the space of "Program Files (x86)"

**Comment by vitekc45c** [comment]
How do I "properly write the space" then?

**Comment by jgonzis** [comment]
I have think another easy trick way... Can you restore the original bat file, and modify the line that has:

'dir /b /s "C:\lolMiner.exe"  and change C:\lolMiner.exe for D:\lolMiner.exe change C for D that will work in your system 😀

**Comment by greekfreek69** [comment]
I am having this same exact issue. Not sure what to do. I only have one hard drive, so I am not sure what the issue is.

**Comment by pdieppa** [comment]
If your command line contains a directory name that has a space, you need to enclose it with double quotes.

Example:
D:\Program Files (x86)\lolMiner\1.31\lolMiner.exe

You need
"D:\Program Files (x86)\lolMiner\1.31\lolMiner.exe"

Just the path and the executable,  do not include the switches.

**Comment by jgonzis** [comment]
> I am having this same exact issue. Not sure what to do. I only have one hard drive, so I am not sure what the issue is.

If it said is not found that means the Windows defender has delete it... or your antivirus

**Comment by greekfreek69** [comment]
Solved the issue. I greatly appreciate the rapid assistance!

**Comment by Isaac7540** [comment]
Mine looks like this and I have the same problem
if exist %CD%"\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist %MyVariable% goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
C:\Users\Isaac\Downloads\lolMiner_v1.31_Win64 (16)\1.31\lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET!  --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
%MyVariable% --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause

**Comment by jgonzis** [comment]
> Mine looks like this and I have the same problem
> if exist %CD%"\lolMiner.exe" goto infolder
> echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
> if exist %MyVariable% goto WindowsVer
> echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> goto END
> 
> :infolder
> set MyVariable=%CD%\lolMiner.exe
> 
> :WindowsVer
> for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
> if "%version%" == "10.0" goto W10
> goto OtherW
> 
> :W10
> C:\Users\Isaac\Downloads\lolMiner_v1.31_Win64 (16)\1.31\lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto W10
> )
> goto END
> 
> :OtherW
> %MyVariable% --algo ETHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto OtherW
> )
> 
> :END
> pause

In which folder do you have the lolMiner.exe file?

**Comment by erickwan88** [comment]
how do i set the folder locate of my lolminer?

if exist %CD%"\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist %MyVariable% goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
%MyVariable% --algo ETCHASH  --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET!  --watchdog exit
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
%MyVariable% --algo ETCHASH  --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause

**Comment by jgonzis** [comment]
> how do i set the folder locate of my lolminer?
> 
> if exist %CD%"\lolMiner.exe" goto infolder
> echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
> if exist %MyVariable% goto WindowsVer
> echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> goto END
> 
> :infolder
> set MyVariable=%CD%\lolMiner.exe
> 
> :WindowsVer
> for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
> if "%version%" == "10.0" goto W10
> goto OtherW
> 
> :W10
> %MyVariable% --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto W10
> )
> goto END
> 
> :OtherW
> %MyVariable% --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
> if %ERRORLEVEL% == 42 (
> timeout 10
> goto OtherW
> )
> 
> :END
> pause

That should automatically search for a lolMiner.exe file in the C drive. If you delete the old versions it will automatically find it.

That is done because it is run it as Administrator, and Administrator run it from C:\Windows\System32 that is not your actual folder.

The easy delete old versions and will work automatically 
If not you can

**Comment by erickwan88** [comment]
> > how do i set the folder locate of my lolminer?
> > 
> > if exist %CD%"\lolMiner.exe" goto infolder
> > echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> > for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
> > if exist %MyVariable% goto WindowsVer
> > echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> > goto END
> > 
> > :infolder
> > set MyVariable=%CD%\lolMiner.exe
> > 
> > :WindowsVer
> > for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
> > if "%version%" == "10.0" goto W10
> > goto OtherW
> > 
> > :W10
> > %MyVariable% --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit
> > if %ERRORLEVEL% == 42 (
> > timeout 10
> > goto W10
> > )
> > goto END
> > 
> > :OtherW
> > %MyVariable% --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
> > if %ERRORLEVEL% == 42 (
> > timeout 10
> > goto OtherW
> > )
> > 
> > :END
> > pause
> 
> That should automatically search for a lolMiner.exe file in the C drive. If you delete the old versions it will automatically find it.
> 
> That is done because it is run it as Administrator, and Administrator run it from C:\Windows\System32 that is not your actual folder.
> 
> The easy delete old versions and will work automatically 
> If not you can 

Alright will try it when I'm back 😊

**Comment by erickwan88** [comment]
> > how do i set the folder locate of my lolminer?
> > if exist %CD%"\lolMiner.exe" goto infolder
> > echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> > for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
> > if exist %MyVariable% goto WindowsVer
> > echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
> > goto END
> > :infolder
> > set MyVariable=%CD%\lolMiner.exe
> > :WindowsVer
> > for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
> > if "%version%" == "10.0" goto W10
> > goto OtherW
> > :W10
> > %MyVariable% --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit
> > if %ERRORLEVEL% == 42 (
> > timeout 10
> > goto W10
> > )
> > goto END
> > :OtherW
> > %MyVariable% --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET! --watchdog exit --nocolor
> > if %ERRORLEVEL% == 42 (
> > timeout 10
> > goto OtherW
> > )
> > :END
> > pause
> 
> That should automatically search for a lolMiner.exe file in the C drive. If you delete the old versions it will automatically find it.
> 
> That is done because it is run it as Administrator, and Administrator run it from C:\Windows\System32 that is not your actual folder.
> 
> The easy delete old versions and will work automatically
> If not you can

erm...done deleted the old version,but searching for lolminer failed...any idea?
![lolminer not found](https://user-images.githubusercontent.com/71332481/129185911-4ba82001-c751-4c76-af0c-27bfb9d03897.jpg)

**Comment by erickwan88** [comment]
window defender disable and no antivirus on my window but still unable to start lolminer....

**Comment by jgonzis** [comment]
> window defender disable and no antivirus on my window but still unable to start lolminer....

Have you unlock it? Sometimes you need first to unlock external Windows file. What happens if you try to click on lolMiner.exe?

O try to go with commands Windows to check if runs or not

**Comment by erickwan88** [comment]
> > window defender disable and no antivirus on my window but still unable to start lolminer....
> 
> Have you unlock it? Sometimes you need first to unlock external Windows file. What happens if you try to click on lolMiner.exe?
> 
> O try to go with commands Windows to check if runs or not

If i double click lolminer.exe popup and closed,if i click any of these bat file will show these error just like above picture.btw what do you mean unlock external window file?do you mean cmd?

**Comment by jgonzis** [comment]
Yes CMD command line ejecutor in Windows

You can go to the folder and put:

lolminer.exe --algo ETCHASH --pool !POOL! --user !WALLET! --pool !POOL2! --user !WALLET!

Just replacing values of !POOL! !WALLET! !POOL2! for your values 

If you try to open and close that normally is the Windows Defender

**Comment by jgonzis** [comment]
> > > window defender disable and no antivirus on my window but still unable to start lolminer....
> > 
> > 
> > Have you unlock it? Sometimes you need first to unlock external Windows file. What happens if you try to click on lolMiner.exe?
> > O try to go with commands Windows to check if runs or not
> 
> If i double click lolminer.exe popup and closed,if i click any of these bat file will show these error just like above picture.btw what do you mean unlock external window file?do you mean cmd?

Why you don't try the mmpOS.eu software? It is a really easy mining OS Linux that work with an USB...

**Comment by erickwan88** [comment]
> > > > window defender disable and no antivirus on my window but still unable to start lolminer....
> > > 
> > > 
> > > Have you unlock it? Sometimes you need first to unlock external Windows file. What happens if you try to click on lolMiner.exe?
> > > O try to go with commands Windows to check if runs or not
> > 
> > If i double click lolminer.exe popup and closed,if i click any of these bat file will show these error just like above picture.btw what do you mean unlock external window file?do you mean cmd?
> 
> Why you don't try the mmpOS.eu software? It is a really easy mining OS Linux that work with an USB... 

......never use linux os before... Have been using window for 2x years.....will try to download mmpos later when I'm back.. 😅 Anway thanks for informing 👍

**Comment by erickwan88** [comment]
> > > > window defender disable and no antivirus on my window but still unable to start lolminer....
> > > 
> > > 
> > > Have you unlock it? Sometimes you need first to unlock external Windows file. What happens if you try to click on lolMiner.exe?
> > > O try to go with commands Windows to check if runs or not
> > 
> > If i double click lolminer.exe popup and closed,if i click any of these bat file will show these error just like above picture.btw what do you mean unlock external window file?do you mean cmd?
> 
> Why you don't try the mmpOS.eu software? It is a really easy mining OS Linux that work with an USB... 

Whatever i will try to solve my problems on first place

**Comment by m0haz** [comment]
I don't know who wrote these batch file templates, but they must be very new at it.  Attempting to run a batch file as admin with the %CD% environment variable will always have it look in C:\Windows\System32 rather than "C:" Or current directory.  Make sure that lolMiner.exe and your batch files are in the same folder, any folder you what, buried as deep in to subfolders as you wish, and replace "%CD%" with  "%~dp0"  and it will always always always call on the directory the batch file is in to search for whatever you're executable you're wanting.  So open your batch template, be sure that your batch file and your .exe file ("lolMiner.exe" in this case) are all in the same folder/directory, and anywhere you see "%CD%" replace with %~dp0". You can now run as admin all day.  Or run unelevated. Whatever.  Example of my Flux batch file for lolMiner.exe:

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=MYPOOOL"
set "WALLET=MYWALLETADDRESS.RIGNAME"										

set "PASSWORD=IGOTSAPASSWORDANDUCANTHAVE"

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "**%~dp0**\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=**%~dp0**\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%"  --coin ZEL --pool !POOL! --user !WALLET!  --watchdog exit !EXTRAPARAMETERS!
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
"%MyVariable%"  --coin ZEL --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause

**Comment by jgonzis** [comment]
> I don't know who wrote these batch file templates, but they must be very new at it. Attempting to run a batch file as admin with the %CD% environment variable will always have it look in C:\Windows\System32 rather than "C:" Or current directory. Make sure that lolMiner.exe and your batch files are in the same folder, any folder you what, buried as deep in to subfolders as you wish, and replace "%CD%" with "%~dp0" and it will always always always call on the directory the batch file is in to search for whatever you're executable you're wanting. So open your batch template, be sure that your batch file and your .exe file ("lolMiner.exe" in this case) are all in the same folder/directory, and anywhere you see "%CD%" replace with %~dp0". You can now run as admin all day. Or run unelevated. Whatever. Example of my Flux batch file for lolMiner.exe:
> 
> @echo off
> 
> setlocal enableDelayedExpansion
> 
> Rem ################################# Rem ## Begin of user-editable part ## Rem #################################
> 
> set "POOL=MYPOOOL" set "WALLET=MYWALLETADDRESS.RIGNAME"
> 
> set "PASSWORD=IGOTSAPASSWORDANDUCANTHAVE"
> 
> Rem ################################# Rem ## End of user-editable part ## Rem #################################
> 
> if exist "%~dp0\lolMiner.exe" goto infolder echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..." for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F if exist "%MyVariable%" goto WindowsVer echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus " goto END
> 
> :infolder set MyVariable=%~dp0\lolMiner.exe
> 
> :WindowsVer echo "Running lolMiner from %MyVariable%" for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j if "%version%" == "10.0" goto W10 goto OtherW
> 
> :W10 "%MyVariable%" --coin ZEL --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! if %ERRORLEVEL% == 42 ( timeout 10 goto W10 ) goto END
> 
> :OtherW "%MyVariable%" --coin ZEL --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor if %ERRORLEVEL% == 42 ( timeout 10 goto OtherW )
> 
> :END pause

Running as administrator that is the reason, better put lolMiner.exe and then run bat as normal

**Comment by m0haz** [comment]
Did you even read my post? I literally just showed how to fix the batch so it can be ran as administrator without any issues

**Comment by m0haz** [comment]
> > I don't know who wrote these batch file templates, but they must be very new at it. Attempting to run a batch file as admin with the %CD% environment variable will always have it look in C:\Windows\System32 rather than "C:" Or current directory. Make sure that lolMiner.exe and your batch files are in the same folder, any folder you what, buried as deep in to subfolders as you wish, and replace "%CD%" with "%~dp0" and it will always always always call on the directory the batch file is in to search for whatever you're executable you're wanting. So open your batch template, be sure that your batch file and your .exe file ("lolMiner.exe" in this case) are all in the same folder/directory, and anywhere you see "%CD%" replace with %~dp0". You can now run as admin all day. Or run unelevated. Whatever. Example of my Flux batch file for lolMiner.exe:
> > @echo off
> > setlocal enableDelayedExpansion
> > Rem ################################# Rem ## Begin of user-editable part ## Rem #################################
> > set "POOL=MYPOOOL" set "WALLET=MYWALLETADDRESS.RIGNAME"
> > set "PASSWORD=IGOTSAPASSWORDANDUCANTHAVE"
> > Rem ################################# Rem ## End of user-editable part ## Rem #################################
> > if exist "%~dp0\lolMiner.exe" goto infolder echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..." for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F if exist "%MyVariable%" goto WindowsVer echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus " goto END
> > :infolder set MyVariable=%~dp0\lolMiner.exe
> > :WindowsVer echo "Running lolMiner from %MyVariable%" for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j if "%version%" == "10.0" goto W10 goto OtherW
> > :W10 "%MyVariable%" --coin ZEL --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! if %ERRORLEVEL% == 42 ( timeout 10 goto W10 ) goto END
> > :OtherW "%MyVariable%" --coin ZEL --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor if %ERRORLEVEL% == 42 ( timeout 10 goto OtherW )
> > :END pause
> 
> Running as administrator that is the reason, better put lolMiner.exe and then run bat as normal

Did you even read my post? I literally just showed how to fix the batch so it can be ran as administrator without any issues

**Comment by jgonzis** [comment]
> 

You are right, I didn't read it complete. Nice way to automatic run in the folder.
