### ISSUE TITLE
mine_eth_4GB isnt in the folder anywhere

### ISSUE THREAD

**Issue by dizduckz** [Lolliedieb/lolMiner-releases#671]
When I try to mine ETH, it says there isn't enough memory for DAG. I know this issue, but, people say to use "keepaway" or whatever but they say to use it in mine_eth_4GB. After looking, I have no results. Please help.
![help](https://user-images.githubusercontent.com/87373379/125452377-dec528a5-c5da-469c-bcba-22b04f044cf7.png)

**Comment by pdieppa** [comment]
@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --4g-alloc-size 4024 --keepfree 8 
timeout 10

**Comment by ASSVIOLATOR** [comment]
having same problem

**Comment by jgonzis** [comment]
> When I try to mine ETH, it says there isn't enough memory for DAG. I know this issue, but, people say to use "keepaway" or whatever but they say to use it in mine_eth_4GB. After looking, I have no results. Please help.
> ![help](https://user-images.githubusercontent.com/87373379/125452377-dec528a5-c5da-469c-bcba-22b04f044cf7.png)

It is not possible to mine more 4Gb... try to mine ERGO for exampleo or ETC or BEAM. ETH is not possible because of the DAG size is bigger than 4Gb
