### ISSUE TITLE
lolMiner.exe dissapearing

### ISSUE THREAD

**Issue by Wiruses1** [Lolliedieb/lolMiner-releases#678]
When I download the zip file, I can preview it in BreeZip and i can see the lolMiner.exe but when i extract the zip file, the .exe is in my folder for about a second and then dissapears, when i try to run mine_eth.bat it says:

"Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
Access is denied.
Press any key to continue . . .

**Comment by pdieppa** [comment]
Your anti-virus is deleting the file. Most if not all crypto miners are flagged as malware. You need to add an exception to your AV program to be able to download it and run it.

**Comment by Wiruses1** [comment]
> Your anti-virus is deleting the file. Most if not all crypto miners are flagged as malware. You need to add an exception to your AV program to be able to download it and run it.

How do i make an exception if the file dissapears as soon as i download it?

**Comment by jims23211** [comment]
Two options.  

1. Add your download directory to the anti-virus exception list.
2. Create a new temporary directory to download to that is on the exception list and download it to there.

Ideally you would download it to a non networked PC with a exception directory and scan the files before you move them to your mining PC(s)/Rigs that have a directory with the anti-virus exception.

**Comment by jgonzis** [comment]
> When I download the zip file, I can preview it in BreeZip and i can see the lolMiner.exe but when i extract the zip file, the .exe is in my folder for about a second and then dissapears, when i try to run mine_eth.bat it says:
> 
> "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
> Access is denied.
> Press any key to continue . . .

That is the antivirus ... he is blocking the file. You should also click the lolminer.exe right click "Propierties" and select unlock.
There bat file in lastest version it is with an autosearch of the lolminer.exe in case you run it as Administrator, because the default administrator folder is Windows\system32 and that's not the normally folder where lolMiner.exe is

**Comment by jgonzis** [comment]
No problem or feedback... close issue
