### ISSUE TITLE
GPU insufficient memory?

### ISSUE THREAD

**Issue by Wiruses1** [Lolliedieb/lolMiner-releases#682]
When I start my miner i get this at the start:

GPU 0: insufficient memory for DAG epoch 428.
GPU 0: will be paused.
 GPU 1: insufficient memory for DAG epoch 428.
GPU 1: will be paused.

And then it proceeds to only get the same job of 00000000ffff0000
and a mh/s of 0

**Comment by kiaas** [comment]
I suggest you include what GPU and OS you're using.

**Comment by Wiruses1** [comment]
> I suggest you include what GPU and OS you're using.

    Name:    AMD Radeon HD 7900 Series
    Address: 3:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  3072 MByte (3022 MByte free)
    --4g-alloc-size parameter not set
    Max epoch (approx): 254
    Active:  true (Selected Algorithm: ETHash OpenCL)

Windows 10, 64 bit

**Comment by kiaas** [comment]
Now, while I'm not the developer I can tell you what your problem is: the DAG for ethereum is just under 4.4GB in size while your GPU has 3GB, I don't believe zombiemode works on windows nor do I believe zombiemode is available for HD 79xx at this time.

**Comment by Wiruses1** [comment]
> Now, while I'm not the developer I can tell you what your problem is: the DAG for ethereum is just under 4.4GB in size while your GPU has 3GB, I don't believe zombiemode works on windows nor do I believe zombiemode is available for HD 79xx at this time.

is there anything i can do except buy a new gpu?

**Comment by kiaas** [comment]
mine a different coin. I Believe Ergo mining (Autolykos 2) was just added for the HD 79xx cards and will work.

**Comment by jgonzis** [comment]
You are not able to mine with that GPU ETH... as the collegue said... ERGO is a good solution or ETC that it will work with your card too.
