### ISSUE TITLE
Is RTX3060 LHR v2 possible to crack on ETH? 

### ISSUE THREAD

**Issue by 5helloworld** [Lolliedieb/lolMiner-releases#683]
I bought an Leadtek-NVIDIA Public RTX3060 LHR (shipped by the seller by mistake), the manufacturing date is the 22nd week of 2021. Yesterday I used the latest version of hiveos and NVIDIA driver 465.31 to successfully drive the graphics card before going to bed. With the help of the latest version of lolminer, a stable eth hash rate of 32.5mh/s has been achieved, and it has worked more than 24. But I am puzzled that it works at 16mh/s first. After a few hours, I woke up and found that it was working at 32.5mh/s.
![image](https://user-images.githubusercontent.com/24307179/126493599-68472b27-187c-4923-ac76-18113059ee90.png)
My use parameters are as follows
![image](https://user-images.githubusercontent.com/24307179/126493029-a464e299-98a2-41db-bf13-e12a55d80a77.png)
Before the hiveos and NVIDIA drivers are updated, the graphics card is recognized as device 2504
![image](https://user-images.githubusercontent.com/24307179/126494694-09f16332-3e63-425a-9c0f-71a0da4971d2.png)
Recognized as RTX 3060 LHR after update
![image](https://user-images.githubusercontent.com/24307179/126493259-2d1950b6-4f84-4028-8dec-d2ee5dfe11ed.png)

_Originally posted by @5helloworld in https://github.com/Lolliedieb/lolMiner-releases/discussions/654#discussioncomment-1032486_

**Comment by maickelbr** [comment]
In your case it is more likely that your board is a GA106-300 V1 and not the new LHR GA106-302 V2

**Comment by 5helloworld** [comment]
> In your case it is more likely that your board is a GA106-300 V1 and not the new LHR GA106-302 V2

I have to install the 470.05 driver in win10, but I cannot install the driver. All my 3060v1 graphics cards can be driven under the 470.05 driver. LHR v1 was recognized as device2503 in hiveos, and I also asked Leadtek to verify that pci  device 2504 is lhr v2. Because this is the PCI device number of lhr v2. Unfortunately, I cannot get the chip device number of the device. Calculated from the SN of the device, the manufacturing date（May 2021） of this graphics card was after NVIDIA replaced the new GPU core

**Comment by maickelbr** [comment]
Very interesting, I will take the test!

**Comment by 5helloworld** [comment]
> Very interesting, I will take the test!

Maybe the developer can circumvent the restriction based on this discovery

**Comment by Geosan1** [comment]
Tested now, confirmed working after about an hour stuck on 16 mh/s 

![image](https://user-images.githubusercontent.com/87777728/126535469-c7ed070c-4b36-4831-872d-d46f307924a0.png)

**Comment by pdieppa** [comment]
Here are my settings for 3060v1

![image](https://user-images.githubusercontent.com/74556152/126539677-2d158939-b104-496b-8549-3d7c161f6458.png)

**Comment by pdieppa** [comment]
running lspci
![image](https://user-images.githubusercontent.com/74556152/126543296-063ad2f8-dc12-481b-9e51-0192d5f959a2.png)

**Comment by 5helloworld** [comment]
> Here are my settings for 3060v1
> 
> ![image](https://user-images.githubusercontent.com/74556152/126539677-2d158939-b104-496b-8549-3d7c161f6458.png)

**Comment by 5helloworld** [comment]
> Tested now, confirmed working after about an hour stuck on 16 mh/s , 3060 LHR V2
> 
> ![image](https://user-images.githubusercontent.com/87777728/126535469-c7ed070c-4b36-4831-872d-d46f307924a0.png)

Maybe rtx3060 lhr really has a way to crack

**Comment by 5helloworld** [comment]
> Here are my settings for 3060v1
> 
> ![image](https://user-images.githubusercontent.com/74556152/126539677-2d158939-b104-496b-8549-3d7c161f6458.png)
3060v1 is expensive and not easy to obtain.

**Comment by 5helloworld** [comment]
Is there a better way to get higher eth?

**Comment by 0jsg** [comment]
I know you closed this, but on a whim I decided to test this for myself and I can second that this happened to me on HiveOS. After about an hour and 10 minutes, the hash rate jumped up to 32.5. Could be a significant discovery? The accepted rate by the pool matches this value so I don't think it's fake reporting.

**Comment by 5helloworld** [comment]
> I know you closed this, but on a whim I decided to test this for myself and I can second that this happened to me on HiveOS. After about an hour and 10 minutes, the hash rate jumped up to 32.5. Could be a significant discovery? The accepted rate by the pool matches this value so I don't think it's fake reporting.


Yes, I found that there will be some errors in some cases, so I closed this conversation
