### ISSUE TITLE
lolminer bind address already in use

### ISSUE THREAD

**Issue by chrise123456789** [Lolliedieb/lolMiner-releases#684]
lolminer bind address already in use and it is not mining. i have restarted the miner and my rig and same issue, also tried to go down in versions but still same issue

**Comment by jgonzis** [comment]
> lolminer bind address already in use and it is not mining. i have restarted the miner and my rig and same issue, also tried to go down in versions but still same issue

That happens when you try to run it 2 times... normally best solution to have last version and check in console if crash at the beginning at that is why is bind in use

**Comment by jgonzis** [comment]
No user answer...

**Comment by Stargajzer** [comment]
Hello, I'm experiencing a problem with my HiveOS 0.6-213@220306 while running lolminer v.1.46a when my rig crashes and attempts to restart I receive the error "bind: Address already in use" and hangs until the motherboard is power cycled manually. Please advise, thank you.

![IMG_7431 (1)](https://user-images.githubusercontent.com/101605477/158274015-3eeabeb2-000e-4c5a-ae0f-0dd247f92d47.jpg)
![IMG_7430 (1)](https://user-images.githubusercontent.com/101605477/158274023-35a4e4b7-21e2-4913-92ba-9e3ab028ebc5.jpg)

**Comment by jgonzis** [comment]
> Hello, I'm experiencing a problem with my HiveOS 0.6-213@220306 while running lolminer v.1.46a when my rig crashes and attempts to restart I receive the error "bind: Address already in use" and hangs until the motherboard is power cycled manually. Please advise, thank you.
> 
> ![IMG_7431 (1)](https://user-images.githubusercontent.com/101605477/158274015-3eeabeb2-000e-4c5a-ae0f-0dd247f92d47.jpg) ![IMG_7430 (1)](https://user-images.githubusercontent.com/101605477/158274023-35a4e4b7-21e2-4913-92ba-9e3ab028ebc5.jpg)

Restart Rig. That happens because another lolMiner is running. Like a crash not ended and not able to restart it properly

**Comment by Stargajzer** [comment]
Well yes, I have no other choice but to manually power cycle the motherboard only after I learn that it's not mining, however why isn't it fully automatic, hanging / stuck and not able to restart itself? I have the watchdog set

**Comment by jgonzis** [comment]
> Well yes, I have no other choice but to manually power cycle the motherboard only after I learn that it's not mining, however why isn't it fully automatic, hanging / stuck and not able to restart itself? I have the watchdog set

With the HiveOS watchdog doesn't work?

**Comment by Stargajzer** [comment]
Sometimes it reboots successfully other times not, I just chatted with HiveOS support and they provided this URL to notify you of this bug.

![Screen Shot 2022-03-14 at 6 08 36 PM](https://user-images.githubusercontent.com/101605477/158275420-4380671b-8782-4a1c-b54f-3320254ee04a.png)

**Comment by jgonzis** [comment]
> Sometimes it reboots successfully other times not, I just chatted with HiveOS support and they provided this URL to notify you of this bug.
> 
> ![Screen Shot 2022-03-14 at 6 08 36 PM](https://user-images.githubusercontent.com/101605477/158275420-4380671b-8782-4a1c-b54f-3320254ee04a.png)

I want to know why is developer error and not HiveOS, that is not able to kill the process ... or the watchdog to properly restart. Interesting. 

But probably the most important is to know why your miner hat a restart. Too much undervold OC in AMD o excess of OC?

**Comment by Stargajzer** [comment]
I'm only the end user, yes the rig is having trouble because of overclocking settings however that's not my complaint, we're communicating because the miner becomes stuck / frozen at the screen above where it says "setup miner . . . " and can only be corrected by manually power cycling the motherboard which cannot be done remotely.

**Comment by jgonzis** [comment]
> I'm only the end user, yes the rig is having trouble because of overclocking settings however that's not my complaint, we're communicating because the miner becomes stuck / frozen at the screen above where it says "setup miner . . . " and can only be corrected by manually power cycling the motherboard which cannot be done remotely.

Before the setup Miner it says Bind already in use... that is not ended the previous version, if it cannot use the API port it will not start.  Active logs-on and check why is frozen... Miner will not work if another instance is running. And it will not show gpus if a GPU is hanged. That's why I say you check which gpu hangs up...
