### ISSUE TITLE
 help i'm new

### ISSUE THREAD

**Issue by aprenminer** [Lolliedieb/lolMiner-releases#69]
I have a problem when I run benchmark I want to compare my gtx 1050ti but the following error appears
![Screenshot_64](https://user-images.githubusercontent.com/38128383/96627189-e2190280-12e6-11eb-8d16-7460ff1d11e6.jpg)
![Screenshot_65](https://user-images.githubusercontent.com/38128383/96627254-f8bf5980-12e6-11eb-82cd-c9d5237dc7ca.jpg)

**Comment by Festest** [comment]
It clearly says unsuported device or driver version. Try updating your GPU driver. Otherwise your GPU might not compatible.

**Comment by jgonzis** [comment]
Solved with the latest releases... 1050 Ti will not mine ETH it can ETC for the DAG Size
