### ISSUE TITLE
Beam error host not reachable. 

### ISSUE THREAD

**Issue by ReconLTU** [Lolliedieb/lolMiner-releases#690]
+---------------------------------------------------------+
|    _       _ __  __ _                   _   _____ _     |
|   | | ___ | |  \/  (_)_ __   ___ _ __  / | |___ // |    |
|   | |/ _ \| | |\/| | | '_ \ / _ \ '__| | |   |_ \| |    |
|   | | (_) | | |  | | | | | |  __/ |    | |_ ___) | |    |
|   |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)____/|_|    |
|                                                         |
|              This software is for mining                |
|              Autolykos V2                               |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash III                               |
|              ZelHash     (EquihashR 125/4/0)            |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|             Made by Lolliedieb, July 2021               |
+---------------------------------------------------------+

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    NVIDIA GeForce RTX 2060
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  6144 MByte
    Active:  true (Selected Algorithm: BeamHash III 4G+)

Connecting to pool...
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Average speed (30s): 0.0 sol/s
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
---------------------------------------------
Statistics (23:19:22); Mining: BeamHash III
Connected to:
Uptime: 0h 2m 51s
                           GPU 0   Total
Name:                   RTX 2060     Rig
Speed (sol/s):               0.0     0.0
Shares (A/S/R):            0/0/0   0/0/0
Best Share:                  0.0     0.0
Power (W):                  21.4    21.4
Efficiency (sol/s/W):      0.000   0.000
Temp (deg C):                 50
Fan Speed (%):                 0
---------------------------------------------
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second
Connected to beam.herominers.com:10230  (TLS enabled)
TLS Handshake success
Lost connection to stratum server beam.herominers.com:10230 or server not reachable.
Trying to connect in 1 second

**Comment by ReconLTU** [comment]
How to fix it ??????????????????????????????????????

**Comment by jgonzis** [comment]
> How to fix it ??????????????????????????????????????

It seems the wallet is not correct because it arrives to connect, but you get disconnected by the pool

**Comment by jgonzis** [comment]
No problem or feedback... close issue
