### ISSUE TITLE
lolminer with binancepool

### ISSUE THREAD

**Issue by thecoderop** [Lolliedieb/lolMiner-releases#692]
hey dev thanks for making such a awesome miner thank you very much 
i am trying to mine ethereum on binance pool but getting error when i run miner can you help me with start.bat file i dont know what hand how to put parameters inside it for binance pool i tried but failed can you give me an example where i can just put my binance pool ethereum address and workername so i can mine on it 
reply me as soon as you get this
thank you

**Comment by jgonzis** [comment]
> hey dev thanks for making such a awesome miner thank you very much
> i am trying to mine ethereum on binance pool but getting error when i run miner can you help me with start.bat file i dont know what hand how to put parameters inside it for binance pool i tried but failed can you give me an example where i can just put my binance pool ethereum address and workername so i can mine on it
> reply me as soon as you get this
> thank you

Pool: ethash.poolbinance.com:1800
Pool2: ethash.poolbinance.com:3333
Wallet the user you have for the pool

**Comment by jgonzis** [comment]
No problem or feedback... close issue
