### ISSUE TITLE
massive rejected shares

### ISSUE THREAD

**Issue by Black6spdZ** [Lolliedieb/lolMiner-releases#693]
Running FirePro S9150 "16GB Hawaii" with latest Lolminer 1.31 and get only ~35% accepted mining AutolykosV2 to Nicehash. I get 99.8% accepted mining ETH with exact same hardware and settings using PhoenixMiner. Are there any magic settings I am missing?

**Comment by jgonzis** [comment]
Could you try to put with reduce Memory OC or try another server?

**Comment by Black6spdZ** [comment]
Stock memory clock on these cards, 1250Mhz.. Like I mentioned it mines ETH with 99.7% accepted using PM

**Comment by jgonzis** [comment]
> Running FirePro S9150 "16GB Hawaii" with latest Lolminer 1.31 and get only ~35% accepted mining AutolykosV2 to Nicehash. I get 99.8% accepted mining ETH with exact same hardware and settings using PhoenixMiner. Are there any magic settings I am missing?

Could you send a Photo that could help

**Comment by kiaas** [comment]
I'm going to try to test my FirePro S9100 (Hawaii, 12GB of VRAM. ) on SMOS for this too, since I remember getting more than expected invalids with it myself.

**Comment by kiaas** [comment]
![ErgoInvalid](https://user-images.githubusercontent.com/86855309/128611093-5c04707f-08bb-4e87-a214-cf8c8cc95111.PNG)
only running for 20 minutes, but I can certainly reproduce his S9150's error on my S9100.
I'm using SMOS, lolminer-v1.31 --algo AUTOLYKOS2 --pool autolykos.usa-west.nicehash.com:3390 --user redacted --pass x --apihost 127.0.0.1 --apiport 4444

**Comment by Black6spdZ** [comment]
Thanks for testing your S9100, glad to see its not just an issue with my rig. I know these FirePros aren't nearly as efficient as modern cards but the 12and 16gb models have plenty of life left, 512-bit bus helps too

**Comment by jgonzis** [comment]
> Thanks for testing your S9100, glad to see its not just an issue with my rig. I know these FirePros aren't nearly as efficient as modern cards but the 12and 16gb models have plenty of life left, 512-bit bus helps too

That seems that the kernel is not properly done. Only to determinate is kernel, could you try for example herominers.com pool instead nicehash?

Many thanks in advance for the feedback

**Comment by Black6spdZ** [comment]
> I'm going to try to test my FirePro S9100 (Hawaii, 12GB of VRAM. ) on SMOS for this too, since I remember getting more than expected invalids with it myself, but didn't go into full troubleshooting.

little off topic but have you looked at unlocking your card? https://www.overclock.net/threads/activation-of-cores-in-hawaii-tonga-and-fiji-unlockability-tester-ver-1-6-and-atomtool.1567179/

**Comment by kiaas** [comment]
> > Thanks for testing your S9100, glad to see its not just an issue with my rig. I know these FirePros aren't nearly as efficient as modern cards but the 12and 16gb models have plenty of life left, 512-bit bus helps too
> 
> That seems that the kernel is not properly done. Only to determinate is kernel, could you try for example herominers.com pool instead nicehash?
> 
> Many thanks in advance for the feedback

![ErgoInvalidHero](https://user-images.githubusercontent.com/86855309/128647718-df857910-9297-457a-8925-04b459eba494.PNG)
it appears to apply to herominers too

**Comment by jgonzis** [comment]
> > > Thanks for testing your S9100, glad to see its not just an issue with my rig. I know these FirePros aren't nearly as efficient as modern cards but the 12and 16gb models have plenty of life left, 512-bit bus helps too
> > 
> > 
> > That seems that the kernel is not properly done. Only to determinate is kernel, could you try for example herominers.com pool instead nicehash?
> > Many thanks in advance for the feedback
> 
> ![ErgoInvalidHero](https://user-images.githubusercontent.com/86855309/128647718-df857910-9297-457a-8925-04b459eba494.PNG)
> it appears to apply to herominers too

Many thanks, that seems a problem in the kernell

**Comment by CecoSvidovski** [comment]
Did someone found a fix? Having the same problem with my r9 390s and rx 580s... Also I saw other people having the same issue with r9 290s.  #772
