### ISSUE TITLE
"Searching for lolminer.exe, because is not in the folder.That could take some time..."

### ISSUE THREAD

**Issue by Z0IDZ** [Lolliedieb/lolMiner-releases#694]
i downloaded the 1.31 version of lolminer, i opened it , and it said that message and open the 1.28 version of lolminer help lol
![image_2021-08-07_123012](https://user-images.githubusercontent.com/76829864/128587898-512b67fd-ad2b-4354-b4f5-5f29811e4ee3.png)

**Comment by Z0IDZ** [comment]
tried with 1.30 too
didnt work

**Comment by jgonzis** [comment]
> tried with 1.30 too
> didnt work

Please delete your old lolMiner 1.28 folder 

What it does the bat file is search for the lolMiner file. The first it has found is the 1.28

Could you delete or rename it?

**Comment by Z0IDZ** [comment]
i deleted the 1.28 file already
didnt work
got too lazy to fix this problem
ima just use the 1.28 version
