### ISSUE TITLE
lolMiner with AMD GPU Driver 21.30 not working

### ISSUE THREAD

**Issue by palmengladosTV** [Lolliedieb/lolMiner-releases#695]
After installing the latest driver from the AMD website, lolMiner didn't recognize any of my AMD cards (RX 570, RX 580, R9 390). 
Before I've updated the drivers everything worked fine. :)
If there will be an update to lolMiner soon to cover this quite new driver, please ignore everything I've just said. ^^

PS: When typing `lspci -k | grep VGA -EA2` it shows that the cards are there and using the right driver.

**Comment by jgonzis** [comment]
> After installing the latest driver from the AMD website, lolMiner didn't recognize any of my AMD cards (RX 570, RX 580, R9 390).
> Before I've updated the drivers everything worked fine. :)
> If there will be an update to lolMiner soon to cover this quite new driver, please ignore everything I've just said. ^^
> 
> PS: When typing `lspci -k | grep VGA -EA2` it shows that the cards are there and using the right driver.
> 
> Edit: Found the error.

Can you share the solution?

**Comment by palmengladosTV** [comment]
I reinstalled an old driver. I know that this isn't a proper fix but that seemed to be the easiest solution for me. :)
