### ISSUE TITLE
Worker name not supported with ETHPROXY (1.11)

### ISSUE THREAD

**Issue by iLLNESS** [Lolliedieb/lolMiner-releases#70]
Setting the worker name in the wallet does not work when the pool uses ETHPROXY.

lolMiner.exe -p eth-us.maxhash.org:13011 -u 0xWallet**.miner** -a ETHASH --tls 1 --ethstratum ETHPROXY
......................
Connecting to pool...
Connected to eth-us.maxhash.org:13011 (TLS enabled)
TLS Handshake success
Set Ethash stratum mode: Ethereum Proxy
Property Tree error: conversion of data to type "bool" failed

Alternatively without specifying --ethstratum ETHPROXY it just hangs at:
Pool responded in ETHPROXY format to EthereumStratum/1.0.0 login request. Changing to stratum mode ETHPROXY.

Setting the wallet to just the ETH address (without .worker) solves the issue.

**Comment by Lolliedieb** [comment]
Fixed with 1.12 and new parameter --worker :)
