### ISSUE TITLE
6Gb Tahiti GPUs using 3Gb version of AutolykosV2 kernel

### ISSUE THREAD

**Issue by angrykirc** [Lolliedieb/lolMiner-releases#700]
With lolMiner and AMD R9 280x 6Gb, upon miner initialization, there is a message saying that these cards are using Autolykos V2 (Ergo) 3G kernel, and 3G, as I guess, stands for 3Gb version of the OCL kernel. 
Are there different versions of the mining kernel available depending on the VRAM amount on the card? 
I think so, because temps are much lower when mining Ergo vs when mining Ethereum.
If this is true, perhaps you can add a check if the GPUs actually have more than 3Gb of VRAM available before defaulting to 3G kernel?

**Comment by jgonzis** [comment]
> With lolMiner and AMD R9 280x 6Gb, upon miner initialization, there is a message saying that these cards are using Autolykos V2 (Ergo) 3G kernel, and 3G, as I guess, stands for 3Gb version of the OCL kernel.
> Are there different versions of the mining kernel available depending on the VRAM amount on the card?
> I think so, because temps are much lower when mining Ergo vs when mining Ethereum.
> If this is true, perhaps you can add a check if the GPUs actually have more than 3Gb of VRAM available before defaulting to 3G kernel?

I recommend you to enter the telegram group, it will be a nice update for you GPU very soon. The alpha is working great with your GPU
