### ISSUE TITLE
Incorrect hashrate displayed by shortstats on AutolykosV2 kernel

### ISSUE THREAD

**Issue by angrykirc** [Lolliedieb/lolMiner-releases#701]
Using lolMiner 1.31, R9 280x 6Gb, --shortstats 3 in cli reports current hashrate as a total of all GPUs in rig.
For example, I have 3 cards that do 30 mh/s, and cli shortstats reports "Average speed (3s): 90.xx mh/s | 90.xx mh/s 90.xx mh/s Total: 270.xx mh/s". But real hashrate for each card is still 30 mh/s.

**Comment by jgonzis** [comment]
> Using lolMiner 1.31, R9 280x 6Gb, --shortstats 3 in cli reports current hashrate as a total of all GPUs in rig.
> For example, I have 3 cards that do 30 mh/s, and cli shortstats reports "Average speed (3s): 90.xx mh/s | 90.xx mh/s 90.xx mh/s Total: 270.xx mh/s". But real hashrate for each card is still 30 mh/s.

Yes short stats at 3s and 4s are not to real, the best is to put 10s, or 30s,
