### ISSUE TITLE
Build Log Error: AMD HSA Code Object Loading Failed. (rx 6600xt)

### ISSUE THREAD

**Issue by amskhan** [Lolliedieb/lolMiner-releases#702]
I am having the same problem as the below thread, but I could not identify the solution for the problem. Any guidance is appreciated.

https://github.com/Lolliedieb/lolMiner-releases/issues/645

```
Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    RDNA 2
    Address: 14:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8176 MByte (8112 MByte free)
Build Log: Error: AMD HSA Code Object loading failed.

    Problem in loading kernel
    Active:  false (Unsupported device or driver version.)

Connecting to pool...
Connected to us1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker
New job received: 0x786699 Epoch: 434 Target: 00000000ffff0000
0x000002BBFF6A1AA0 (0x0000000000000000 0x0000000000000000 0x0000000200000000 0x0000000000000000) <unknown module>
0x00007FF60C65FF5D (0x0000000000000000 0x000000C4A40FED48 0x000002BBFF6A3CC0 0x00007FF60C6601C7)
0x00007FF60C43B64A (0x000002BBFF6A3CC0 0x000000C4A43FFC58 0x000002BBFF6A3CC0 0x00007FFFD59007B0)
0x00007FF60C345865 (0x0000000000000057 0x000002BBFF655E90 0x0000000000000000 0x0000000000000005)
0x00007FF60C344F59 (0x000002BBFF655E90 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF60C679C54 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFFD4227034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFFD5902651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
Press any key to continue . . .

```

**Comment by jgonzis** [comment]
> I am having the same problem as the below thread, but I could not identify the solution for the problem. Any guidance is appreciated.
> 
> #645
> 
> ```
> Setup Miner...
> OpenCL driver detected.
> Number of OpenCL supported GPUs: 1
> No Cuda driver or GPUs detected.
> Device 0:
>     Name:    RDNA 2
>     Address: 14:0
>     Vendor:  Advanced Micro Devices (AMD)
>     Drivers: OpenCL
>     Memory:  8176 MByte (8112 MByte free)
> Build Log: Error: AMD HSA Code Object loading failed.
> 
>     Problem in loading kernel
>     Active:  false (Unsupported device or driver version.)
> 
> Connecting to pool...
> Connected to us1.ethermine.org:4444  (TLS disabled)
> Set Ethash stratum mode: Ethereum Proxy
> Authorized worker: 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker
> New job received: 0x786699 Epoch: 434 Target: 00000000ffff0000
> 0x000002BBFF6A1AA0 (0x0000000000000000 0x0000000000000000 0x0000000200000000 0x0000000000000000) <unknown module>
> 0x00007FF60C65FF5D (0x0000000000000000 0x000000C4A40FED48 0x000002BBFF6A3CC0 0x00007FF60C6601C7)
> 0x00007FF60C43B64A (0x000002BBFF6A3CC0 0x000000C4A43FFC58 0x000002BBFF6A3CC0 0x00007FFFD59007B0)
> 0x00007FF60C345865 (0x0000000000000057 0x000002BBFF655E90 0x0000000000000000 0x0000000000000005)
> 0x00007FF60C344F59 (0x000002BBFF655E90 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FF60C679C54 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FFFD4227034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
> 0x00007FFFD5902651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
> Press any key to continue . . .
> ```

At the moment is not yet supported. If you ask in the Telegram group I think it is an alpha version that is working

**Comment by amskhan** [comment]
I switched over to teamredminer and it's working.

**Comment by parpok** [comment]
> I switched over to teamredminer and it's working.

I was using teamredminer but after mining for some time without doing anything else the entire system would crash requiring restart.

**Comment by jgonzis** [comment]
The alpha version is working with 6600XT
About the 6700XT, it seems last drivers of Adrenaline Windows are not working properly yet. In Linux with 20.40 all cards are working

**Comment by jgonzis** [comment]
It should be working now. No more Feedback
