### ISSUE TITLE
Internet disruption causes shares to not be submitted.

### ISSUE THREAD

**Issue by Marhault1980** [Lolliedieb/lolMiner-releases#703]
I'm having an issue with lolminer. It's only been happening with the new release but I'm not sure if it's happening because of that or because of changes with Ethermine.org. 

Anytime my miner is running if there's a disruption in internet, the miner quickly resumes when internet is restored, however all the shares it's processing don't seem to be submitted to ethermine.org. 

This is really frustrating and if there's anything I can do to prevent this is greatly appreciate the help, thanks!

**Comment by jgonzis** [comment]
> I'm having an issue with lolminer. It's only been happening with the new release but I'm not sure if it's happening because of that or because of changes with Ethermine.org.
> 
> Anytime my miner is running if there's a disruption in internet, the miner quickly resumes when internet is restored, however all the shares it's processing don't seem to be submitted to ethermine.org.
> 
> This is really frustrating and if there's anything I can do to prevent this is greatly appreciate the help, thanks!

That's normal... If there is not internet you cannot send your shares. The Pool will reject all of them for been so late the send of information. You must know each 13s average it is a new block

**Comment by Marhault1980** [comment]
You're not understanding. I realize if I have no internet that the shares will be invalid/stale. What I'm saying is when my internet drops and reconnects the miner reconnects like normal and from that point forward until I catch it and reboot the machine/restart lolminer nothing will even be submitted to ethermine.org it views it as an inactive miner even though it is actively mining.

It never did this before with 1.28 but now that I've updated to 1.31 it is. Before the miner would pick back up after an internet drop no problem, now it does but it's not submitting shares.

Like I said. I upgraded to 1.31 at the same time that ethermine.org changed some stuff to do with the new Ethereum block changes so I'm not sure which is the issue.

**Comment by jgonzis** [comment]
Are you in Windows or some Linux OS Mining? 
Can you see the log if there are retries of reconnection of the miner?

Or do a test, mine and take out ethernet cable to see what happens... to have some log information

**Comment by jgonzis** [comment]
No problem or feedback... close issue
