### ISSUE TITLE
error with the ETH miner...

### ISSUE THREAD

**Issue by Deataaaaa** [Lolliedieb/lolMiner-releases#705]
i set the pools correctly with my wallet (code below)

set "POOL=eu1.ethermine.org:4444"
set "POOL=eth-eu.sparkpool.com:3333" 
set "WALLET=0x63195246fA353e5f6888eD46e587806703746490.lolMinerWorker"	

and then... the command prompt tell this:
"Error: Your input to --pool "--user" can not be split into a address and a port. Please use format <pool address>:<pool port>."

I tried everything... i may be dumb but this version got me stuck...

**Comment by pdieppa** [comment]
Please post your complete command line

**Comment by ziirish** [comment]
The second line should be:

```
set "POOL2=eth-eu.sparkpool.com:3333"
```

Mind the variable named **POOL2** which is used in the command line.

**Comment by Deataaaaa** [comment]
Thanks! It works! Sorry for bothering i am new to crytpo mining launching my first real worker soon !


> The second line should be:
> 
> ```
> set "POOL2=eth-eu.sparkpool.com:3333"
> ```
> 
> Mind the variable named **POOL2** which is used in the command line.
