### ISSUE TITLE
Failover pool set,  how to auto switch back to main pool when it resume?

### ISSUE THREAD

**Issue by MXS2514** [Lolliedieb/lolMiner-releases#708]
--algo AUTOLYKOS2 --pool poolmain --user walletaddr --pass pw --pool poolfailover --user walletaddr --pass pw --watchdog

When the mainpool down, it worked to switch failoverpool, but when mainpool resume, how to switch back mainpool automatically regardless failover pool down or not?

**Comment by jgonzis** [comment]
> --algo AUTOLYKOS2 --pool poolmain --user walletaddr --pass pw --pool poolfailover --user walletaddr --pass pw --watchdog
> 
> When the mainpool down, it worked to switch failoverpool, but when mainpool resume, how to switch back mainpool automatically regardless failover pool down or not?

Nice question, it will only swap when the poolfailover goes down or in a restart...

**Comment by shamashii** [comment]
> > --algo AUTOLYKOS2 --pool poolmain --user walletaddr --pass pw --pool poolfailover --user walletaddr --pass pw --watchdog
> > When the mainpool down, it worked to switch failoverpool, but when mainpool resume, how to switch back mainpool automatically regardless failover pool down or not?
> 
> Nice question, it will only swap when the poolfailover goes down or in a restart...

From an ancient doc https://manuals.plus/software/lolminer-command-line-manual seems have two commands to archieve it, but I cannot manage it work in current version miner.

**Comment by jgonzis** [comment]
From last release after some time it will autoswitch to main pool
