### ISSUE TITLE
Error when allocating memory or building DAG

### ISSUE THREAD

**Issue by Deataaaaa** [Lolliedieb/lolMiner-releases#709]
When itry to mine ETC with lolminer 1.31 and my gtx 1060 3gb i get this error:

![image](https://user-images.githubusercontent.com/89153160/130365419-63a3c33d-a77c-49ab-9ff1-69f79b684fcb.png)

**Comment by kiaas** [comment]
are you on windows? Windows reserves some amount of memory on the GPU for itself, so a 2.8GB DAG might not fit on a 3GB card once windows and various apps take 0.3GB or so

**Comment by Deataaaaa** [comment]
> **are you on windows?** Windows reserves some amount of memory on the GPU for itself, so a 2.8GB DAG might not fit on a 3GB card once windows and various apps take 0.3GB or so

Yes i am. sadly my mining rig power suply died yesterday i have a new one tomorow so i will keep you in touch with HiveOS

**Comment by jgonzis** [comment]
> > **are you on windows?** Windows reserves some amount of memory on the GPU for itself, so a 2.8GB DAG might not fit on a 3GB card once windows and various apps take 0.3GB or so
> 
> Yes i am. sadly my mining rig power suply died yesterday i have a new one tomorow so i will keep you in touch with HiveOS

You can try also MMPOS if you like or RaveOS both are great alternative

**Comment by Deataaaaa** [comment]
> > > **are you on windows?** Windows reserves some amount of memory on the GPU for itself, so a 2.8GB DAG might not fit on a 3GB card once windows and various apps take 0.3GB or so
> > 
> > 
> > Yes i am. sadly my mining rig power suply died yesterday i have a new one tomorow so i will keep you in touch with HiveOS
> 
> You can try also MMPOS if you like or RaveOS both are great alternative

Hi! Sorry for the late response but the power supply dude tricked me up and i lost a bunch of time but here i am again! Now with a rx560 4gb from MSI with polaris bios mod and a tiiny overclock i got another problem… the gpu boots fine with lolminer 1.31 mining etcash with 13.70mh/s with a tdp of 43W but my hashrate drops to 0 and my gpu 0 crashes… can you guys help me ?

**Comment by jgonzis** [comment]
> > > > **are you on windows?** Windows reserves some amount of memory on the GPU for itself, so a 2.8GB DAG might not fit on a 3GB card once windows and various apps take 0.3GB or so
> > > 
> > > 
> > > Yes i am. sadly my mining rig power suply died yesterday i have a new one tomorow so i will keep you in touch with HiveOS
> > 
> > 
> > You can try also MMPOS if you like or RaveOS both are great alternative
> 
> Hi! Sorry for the late response but the power supply dude tricked me up and i lost a bunch of time but here i am again! Now with a rx560 4gb from MSI with polaris bios mod and a tiiny overclock i got another problem… the gpu boots fine with lolminer 1.31 mining etcash with 13.70mh/s with a tdp of 43W but my hashrate drops to 0 and my gpu 0 crashes… can you guys help me ?

Your problem is the BIOS Mod... that could made to crash the GPU... it shouldn't be other problem. You can also add extra voltage to the core

**Comment by jgonzis** [comment]
No problem or feedback... close issue
