### ISSUE TITLE
HELP, pls!  R9 390 ETH - 16 MH.... V. 1.11...

### ISSUE THREAD

**Issue by EVGENY1777** [Lolliedieb/lolMiner-releases#71]
Hello there! 

I use version 1.11 of Linux with driver 20.10. 

R9 390 ETH - 16 MH.... V. 1.11  

On other miners (Phoenix 5.1) -everything is fine, 30 MH. 

What should I do or what am I doing wrong?  

With respect.

**Comment by Lolliedieb** [comment]
Well .. most likely the problem is on my side since I was not able to test my code on Hawaii cards yet ^^

**Comment by Lolliedieb** [comment]
Fixed in 1.20 and newer
