### ISSUE TITLE
Miner not even starting

### ISSUE THREAD

**Issue by jantheman827** [Lolliedieb/lolMiner-releases#712]
when I launch the eth.bat file it shows the window but at the top it says can find lolMiner.exe although lolminer.exe is in the folder it isn't detecting it I was wondering if there is a fix for this?  

![image](https://user-images.githubusercontent.com/89607541/131024251-4a497b35-2001-46d3-b047-e9daa77c6195.png)
![image](https://user-images.githubusercontent.com/89607541/131024372-db509380-39c7-4083-9dc5-4a1bddb9d869.png)

**Comment by jgonzis** [comment]
That bat file search for a lolminer.exe, because it was lot of people that when running as adminsitrador they didn't put the right folder at the beginning. You can also use the web configurator, that creates a bat file like the old way.

[http://lolminer.byethost16.com/](url)

**Comment by jgonzis** [comment]
New Version 1.33 has solved that problems with bat files.
