### ISSUE TITLE
Second 3060 - Half Hash Rate 

### ISSUE THREAD

**Issue by japson12** [Lolliedieb/lolMiner-releases#713]
Hi,

Been running just one 3060 for a while and grabbed another to double up my hash rate.

However, when I connected the second gpu it only gets half the max hash I've gotten from the 1st card.

![image](https://user-images.githubusercontent.com/89623552/131069335-ca95ae0e-1f4b-4467-b510-d98c16d09d0f.png)

First card (48mh/s)
Second(26mh/s)

I've tried with the dummy hdmi, tried different mining programs, running two different instances with device 0/1, with them all having the second gpu at half.

Wondering if power supply could be an issue, if my math is right I am close to the limit of my power supply, with only 50watts or so to spare.

Any ideas?

**Comment by Deataaaaa** [comment]
I think think you solved the problem by yourself

**Comment by jgonzis** [comment]
3060 need PCIe Gen3x or Gen3x16 with HDMI
