### ISSUE TITLE
Radeon RX 6800XT Ubuntu issues

### ISSUE THREAD

**Issue by Tongie969** [Lolliedieb/lolMiner-releases#714]
Hello all, 

I am trying to use lolMiner with my new Ubuntu 20.04.2 system. Doesn't matter what drivers I try ( AMD GPU Pro 21.10 l 21.20 l 21.30 and latest RocM ) lolMiner doesn't recognize the cards. 

glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     AMD
    GL_RENDERER:   AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.11.0-27-generic, LLVM 12.0.0)
    GL_VERSION:    4.6 (Compatibility Profile) Mesa 21.0.3

Is there anyway driver/Kernel setup to get lolMiner running with my setup or are there informations I can provide to get it running in future? 

I am willing to help as much as I can.

**Comment by jgonzis** [comment]
> Hello all,
> 
> I am trying to use lolMiner with my new Ubuntu 20.04.2 system. Doesn't matter what drivers I try ( AMD GPU Pro 21.10 l 21.20 l 21.30 and latest RocM ) lolMiner doesn't recognize the cards.
> 
> # glmark2 2021.02
> ```
> OpenGL Information
> GL_VENDOR:     AMD
> GL_RENDERER:   AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.11.0-27-generic, LLVM 12.0.0)
> GL_VERSION:    4.6 (Compatibility Profile) Mesa 21.0.3
> ```
> 
> Is there anyway driver/Kernel setup to get lolMiner running with my setup or are there informations I can provide to get it running in future?
> 
> I am willing to help as much as I can.

Could you please try it with 20.40?. With 20.40 is working on my with HiveOS and MMPOS.EU

**Comment by Tongie969** [comment]
> > Hello all,
> > 
> > I am trying to use lolMiner with my new Ubuntu 20.04.2 system. Doesn't matter what drivers I try ( AMD GPU Pro 21.10 l 21.20 l 21.30 and latest RocM ) lolMiner doesn't recognize the cards.
> > 
> > # glmark2 2021.02
> > ```
> > OpenGL Information
> > GL_VENDOR:     AMD
> > GL_RENDERER:   AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.11.0-27-generic, LLVM 12.0.0)
> > GL_VERSION:    4.6 (Compatibility Profile) Mesa 21.0.3
> > ```
> > 
> > Is there anyway driver/Kernel setup to get lolMiner running with my setup or are there informations I can provide to get it running in future?
> > 
> > I am willing to help as much as I can.
> 
> Could you please try it with 20.40?. With 20.40 is working on my with HiveOS and MMPOS.EU

Thanks for your reply. 

I was playing around with different Kernels now and as I found out that mmpOS is using Kernel 5.11.2x with AMD driver 20.40 I tried it again and TeamReadMiner is working with this setup. 

I will try around with the others after some days break. 

Cheers

**Comment by jgonzis** [comment]
Nice to see that here we solve the problems of other miners 👍

**Comment by Tongie969** [comment]
> Nice to see that here we solve the problems of other miners 👍

You did not, I just tried different ones as well and that fixed it. After two days of trying I was not in the mood to try what other miners work with driver and Kernel setup.

**Comment by jgonzis** [comment]
With driver 20.40 all should work. It is the common driver of the Linux Mining OS
