### ISSUE TITLE
Methods for 100% Bypass

### ISSUE THREAD

**Issue by Austin-Src** [Lolliedieb/lolMiner-releases#715]
It looks like much of the current 70% bypass is aimed at ethereum, but there may be methods for a full bypass worth considering: https://0xbypass.weebly.com/methods-for-bypassing-the-3060-ti-lhr-mode/possible-methods-for-bypassing-the-3060-ti-lhr-mode

**Comment by jgonzis** [comment]
> It looks like much of the current 70% bypass is aimed at ethereum, but there may be methods for a full bypass worth considering: https://0xbypass.weebly.com/methods-for-bypassing-the-3060-ti-lhr-mode/possible-methods-for-bypassing-the-3060-ti-lhr-mode

All this methods are hardware ways to modify or extract information of the GPU... it will be nice to see how this steps go ...

**Comment by jgonzis** [comment]
Working with new Nvidia Drivers now
