### ISSUE TITLE
Problemas con Dual minig ETH + ZIL

### ISSUE THREAD

**Issue by Tonitkd** [Lolliedieb/lolMiner-releases#716]
Hola buenos dias, tengo un problema para hacer cual mining, quiero minar ETH e Crazy pool y Zilliqa en Ezil
Pero segun la guia o las diferentes opciones que haga no me deja minar

Y esto metira la info en Hiveos

![image](https://user-images.githubusercontent.com/89988162/131860314-ca174a5c-1a6a-47c6-83ec-001a36bdff00.png)
![image](https://user-images.githubusercontent.com/89988162/131860414-cb78010c-ff49-4a55-ac64-7e5f89c410bd.png)

aguardo su ayuda o guia para poder hacer dual mining en diferentes pools.

Muchas gracias!

**Comment by jgonzis** [comment]
La solución casi la tenías... únicamente cambia lo que pone --dualmode eth por --dualmode zil y prueba :-)
Puedes borrar lo de --devices 0,1,2 y --dualdevices 0,1,2

Solo cambiar la palabra de eth a zil y quitar lo de los devices te funcionará :-)

**Comment by Tonitkd** [comment]
Hola buen dia muchas gracias por la respuesta, cambie los comandos, pero sigue igual, creo que es un problema de la Pool, pero con otro minero, con teamredminer por ejemplo funciona ahora mando capturas de todo

![image](https://user-images.githubusercontent.com/89988162/132000275-c5f65cb0-d393-467e-8e35-9dc9c9740662.png)
![image](https://user-images.githubusercontent.com/89988162/132000554-94c20b8c-c540-4ce4-a7c9-da9cef979a2b.png)


Y aca les dejo como lo configure con Teamredminer, quizas sirva

![image](https://user-images.githubusercontent.com/89988162/132000620-ce02e9ae-d815-423d-a9f0-ae2bfdd4a2cb.png)


Muchas gracias!

**Comment by jgonzis** [comment]
> Hola buen dia muchas gracias por la respuesta, cambie los comandos, pero sigue igual, creo que es un problema de la Pool, pero con otro minero, con teamredminer por ejemplo funciona ahora mando capturas de todo
> 
> ![image](https://user-images.githubusercontent.com/89988162/132000275-c5f65cb0-d393-467e-8e35-9dc9c9740662.png)
> ![image](https://user-images.githubusercontent.com/89988162/132000554-94c20b8c-c540-4ce4-a7c9-da9cef979a2b.png)
> 
> Y aca les dejo como lo configure con Teamredminer, quizas sirva
> 
> ![image](https://user-images.githubusercontent.com/89988162/132000620-ce02e9ae-d815-423d-a9f0-ae2bfdd4a2cb.png)
> 
> Muchas gracias!

Creo que se dónde puede estar: 
añade --ethstratum ETHPROXY,ETHV1

Y dónde te pone %WAL%.%WORKER_NAME% Pon únicamente %WAL%

Creo que con eso te irá :-) ya verás!!

**Comment by Tonitkd** [comment]
Muchisimas gracias!!!! la verdad increible tu ayuda, aca dejo print funcionando perfecto

![image](https://user-images.githubusercontent.com/89988162/132013244-8c275796-cf43-4ae9-9fdb-4b6715e01b49.png)

**Comment by jgonzis** [comment]
De lujo :-) como me alegro!!! GRacias por informar

**Comment by Tonitkd** [comment]
Paso los comandos por si alguno le sirve y los prints

--dualmode eth --dualstratum (PonernumerodetuwallerETH).(Ponernombredeminero)@latam.crazypool.org:3333 --ethstratum ETHPROXY,ETHV1
