### ISSUE TITLE
"lolMiner.exe not found"

### ISSUE THREAD

**Issue by Ferrum-0** [Lolliedieb/lolMiner-releases#717]
The lolMiner.exe folder has somehow not been found, it is in the same folder and is not being blocked, please help.

**Comment by jgonzis** [comment]
> The lolMiner.exe folder has somehow not been found, it is in the same folder and is not being blocked, please help.

I know the problem... you have spaces in the name of the folder... could you try this new bat file please??

[New Bat File lolMiner 1.31.zip](https://github.com/Lolliedieb/lolMiner-releases/files/7106253/New.Bat.File.lolMiner.1.31.zip)

**Comment by jgonzis** [comment]
No problem or feedback... close issue
