### ISSUE TITLE
unexpected closing

### ISSUE THREAD

**Issue by Dhee0** [Lolliedieb/lolMiner-releases#718]
Please why does mine show this to me...
![Screenshot (1)_LI](https://user-images.githubusercontent.com/90117689/132111051-347d4031-bbab-47f3-8a8c-215e7e3faac8.jpg)

**Comment by jgonzis** [comment]
> Please why does mine show this to me...
> ![Screenshot (1)_LI](https://user-images.githubusercontent.com/90117689/132111051-347d4031-bbab-47f3-8a8c-215e7e3faac8.jpg)

You cannot mine with an integrated GPU sorry... You need a dedicated GPU. No option...
