### ISSUE TITLE
Error del sistema OpenCL.dll

### ISSUE THREAD

**Issue by Gonza222** [Lolliedieb/lolMiner-releases#719]
Cuando intento ejecutar el programa mine_eth.bat me salta el siguiente error alguien podria indicarme que pued hacer para solucionarlo?
Muchas gracias.

![Sin título](https://user-images.githubusercontent.com/90155539/132139667-fc7f738d-29e2-4545-80db-87d3d472f272.png)

**Comment by kiaas** [comment]
what GPU, driver and OS are you using?

**Comment by Gonza222** [comment]
windows 10 Home NVIDIA GeForce GTX 1050 y el controlador no sabria decirte

**Comment by Gonza222** [comment]
> ¿Qué GPU, controlador y sistema operativo estás usando?

Windows 10 Home NVIDIA GeForce GTX 1050 y el controlador no sabria decirte

**Comment by pdieppa** [comment]
Si tu tarjeta de video tiene 4gb de memoria, no vas a poder usar ETH.

**Comment by kiaas** [comment]
The GTX 1050 and 1050 Ti are limited in what they can mine, due to limited memory, but I expect some things might work.
That error likely means you need to reinstall the driver for the 1050 from nvidia's website to get lolminer to start and tell you if it can do what you want.

**Comment by Gonza222** [comment]
> The GTX 1050 and 1050 Ti are limited in what they can mine, due to limited memory, but I expect some things might work.
> That error likely means you need to reinstall the driver for the 1050 from nvidia's website to get lolminer to start and tell you if it can do what you want.

i reinstall the program and lolminer starts to run but it send me this message GPU will be in ZOMBIE MODE
![lolminer](https://user-images.githubusercontent.com/90155539/132745623-5468f5cd-d43a-402e-8012-6b929dec61a5.jpg)

**Comment by kiaas** [comment]
Your card has 2GB of memory and you are attempting to mine Ethereum which requires nearly 5GB of video memory to fit all of it. On Linux based operating systems 4GB cards have Zombie Mode that can put what doesn't fit on the card into system memory, but this will not work for you.
