### ISSUE TITLE
mining Kawpow on Mining Pool Hub

### ISSUE THREAD

**Issue by Waytoogo** [Lolliedieb/lolMiner-releases#72]
I am unable to mine Kawpow on Mining Pool Hub. I can mine other algorithms on Mining Pool Hub, but not Kawpow. It doesn't crash or give any errors it just doesn't mine. I can mine Kawpow on other pools fine, it's just Mining Pool Hub I'm having trouble with. One thing I noticed is that it never says anything about making the DAG, it just shows it's mining at 0 h/s. 
Windows 10 pro 20h2
AMD R9 390X

**Comment by Lolliedieb** [comment]
This miner does not support Kawpow ... yet ...

**Comment by Waytoogo** [comment]
it mines Kawpow on zergpool and zpool just fine.
