### ISSUE TITLE
AMD 21.6.1 drivers and lolminer crashing

### ISSUE THREAD

**Issue by Malique2** [Lolliedieb/lolMiner-releases#722]
Anyone have a fix for LOLminer crashing with the newer drivers for AMD GPUs?

**Comment by jgonzis** [comment]
> Anyone have a fix for LOLminer crashing with the newer drivers for AMD GPUs?

Completely true... it seems new drivers are not yet fully compatible.

**Comment by jgonzis** [comment]
New drivers supported
