### ISSUE TITLE
Beam mining random freeze bug

### ISSUE THREAD

**Issue by rhyno78** [Lolliedieb/lolMiner-releases#725]
Hello, when I mine Beam, the lolminer software randomly freeze. It occurs very often.. Sometimes when I mine for 30 minutes, sometimes for 4 hours or more. However when I mine other coins, this bug doesn't appear and I can mine it for 7 days straight for no problem. So far only Beam has this issue. I use AMD RX 6900 and lolminer is the only beam miner for AMD... Please fix it, thank you.

**Comment by jgonzis** [comment]
Which OS?
Which Memory or Swap Disk?

**Comment by rhyno78** [comment]
i use windows 10. amd driver is 21.6.2

**Comment by jgonzis** [comment]
> i use windows 10. amd driver is 21.6.2. the weird numbers always appear and the miner paused itself.

I think that could be problem... could you try the 21.5 driver? to see if that helps on that freeze?

**Comment by rhyno78** [comment]
well today version 32 just out. i will try it first before i downgrade my amd driver

**Comment by rhyno78** [comment]
I use amd driver 21.9.1 now. no problem so far. I will post if i get the freeze bug

**Comment by jgonzis** [comment]
No more Feedback
