### ISSUE TITLE
1.31"\lolMiner.exe" was unexpected at this time.

### ISSUE THREAD

**Issue by tipsonthefly** [Lolliedieb/lolMiner-releases#726]
When i try to run it it just closes immediately when i run through CMD opening the folder and running from it, i get the error "1.31"\lolMiner.exe" was unexpected at this time." only values i changed were the wallet and the pools. there are no logs in the log folder

**Comment by jgonzis** [comment]
https://github.com/Lolliedieb/lolMiner-releases/files/7106253/New.Bat.File.lolMiner.1.31.zip`

**Comment by jgonzis** [comment]
New version bat files 1.62 will improve that problem.
