### ISSUE TITLE
LHR1 does not work. 

### ISSUE THREAD

**Issue by drugsnhugs** [Lolliedieb/lolMiner-releases#729]
Hello, 
I just updated and introduced --mode LHR1 and the one 3060 v1 that i had now only gets 25 mh instead of 37 before. :( 
It's a mixed rig, only the one card is lhr, i tried --mode LHR1 6 (6 is the GPU number) but still locked at 25 mh. 
Using Hiveos with 460.39 drivers

Any ideas?

**Comment by Roman7487** [comment]
+

**Comment by jgonzis** [comment]
Try the new update 1.32a I think that solve it 

1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.

**Comment by drugsnhugs** [comment]
> Try the new update 1.32a I think that solve it
> 
> 1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
> 1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.

Just saw that. came here to post for other people searching. 
Tbahks!

**Comment by drugsnhugs** [comment]
> Try the new update 1.32a I think that solve it
> 
> 1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
> 1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.

well, now my 3060ti founders edition only get 38 mh/s lol.

**Comment by Roman7487** [comment]
3060 V1 runs at 1.32a for exactly 40 seconds, when triggered (detected mining lock) MH / s decreases by 21 and no longer accelerates back to 38 + mh / s
![PXL_20210913_151048803](https://user-images.githubusercontent.com/83368279/133111158-f21966dc-989c-4833-bbfa-54b11c742b52.jpg)

**Comment by jgonzis** [comment]
> > Try the new update 1.32a I think that solve it
> > 1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
> > 1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.
> 
> well, now my 3060ti founders edition only get 38 mh/s lol.

Which OC are you using? and which parameters in the mode selection?.

**Comment by jgonzis** [comment]
> > Try the new update 1.32a I think that solve it
> > 1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
> > 1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.
> 
> well, now my 3060ti founders edition only get 38 mh/s lol.

with --mode LHR2 and Fixed Core 1500 - 1545 and --lhrtune 10 my 3060ti are at 41-41.8Mhs... give a try

**Comment by drugsnhugs** [comment]
> > > Try the new update 1.32a I think that solve it
> > > 1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
> > > 1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.
> > 
> > 
> > well, now my 3060ti founders edition only get 38 mh/s lol.
> 
> with --mode LHR2 and Fixed Core 1500 - 1545 and --lhrtune 10 my 3060ti are at 41-41.8Mhs... give a try

They are founders edition. Unlocked cards :) 
Basically, they are being considered locked cards when using --mode LHR1. 
The rig is mixed with unlocked cards and 3060 v1

**Comment by jgonzis** [comment]
> > > > Try the new update 1.32a I think that solve it
> > > > 1.32a: Fixed --mode LHR1 not starting in unlocked state on many systems.
> > > > 1.32a: Fixed 3060 LHR V1 not starting in semi-unlock when the right drivers are detected.
> > > 
> > > 
> > > well, now my 3060ti founders edition only get 38 mh/s lol.
> > 
> > 
> > with --mode LHR2 and Fixed Core 1500 - 1545 and --lhrtune 10 my 3060ti are at 41-41.8Mhs... give a try
> 
> They are founders edition. Unlocked cards :)
> Basically, they are being considered locked cards when using --mode LHR1.
> The rig is mixed with unlocked cards and 3060 v1

So put in extra parameters 
--mode b,b,b,LHR1,LHR1,b where you should put LHR1 to v1 and the non LHR b. That will be 0,1 2 and 5 non LHR and the 3,4 a V1

**Comment by jgonzis** [comment]
Try new version 1.33 with autodetect LHR, remember please to have 470.74 Drivers. In HiveOS just run :

nvidia-driver-update 470.74
