### ISSUE TITLE
ubuntu 18.04 GeForce GTX 1050 Ti   error:  Unsupported device or driver version

### ISSUE THREAD

**Issue by antongritsenko2018** [Lolliedieb/lolMiner-releases#73]
Hi!

I use ubuntu 18.04 and want to use "zombie mode" that you include in you miner.

But when I try to run miner i get a error message:  

Name:    GeForce GTX 1050 Ti
    Address: 7:0
    Vendor:  NVIDIA Corporation
    Memory:  4040 MByte
    Active:  false (Unsupported device or driver version.)

I already tryed different driver versions (390,435,455) with same result.

Can you provide correct driver version, or a guide for 1050ti users?

Thank you.

**Comment by jgonzis** [comment]
Solved with latest Cuda Support. It will not work with Zombie Mode, it will work with ETC for example for DAG Size
