### ISSUE TITLE
RTX-3060 V1 e V2 - Which driver to use?

### ISSUE THREAD

**Issue by gustavofiod** [Lolliedieb/lolMiner-releases#730]
I have 2 RTX-3060 V1 running at 80% on LoLminer!!! Driver 460.39 (linux-HiveOS).

I bought an RTX-3060 V2, not even linux can load it with the 460.39 driver.

Surely someone has had a similar problem.

How did you solve it?

Can you guide me?

**Comment by pdieppa** [comment]
I hate to say this but I have been reading about people creating separate rigs for V1 and V2. 460.39 works perfectly with V1 and many are having issues with newer drivers to get V1 to work next to V2.

**Comment by jgonzis** [comment]
> I hate to say this but I have been reading about people creating separate rigs for V1 and V2. 460.39 works perfectly with V1 and many are having issues with newer drivers to get V1 to work next to V2. These are the drivers that lolminer is recommending 470.63.01 or 465.31 for V2.

Complete true it is better separate rigs. You can  not have 460.39 drivers with v2 and you are loosing then 4-5Mhs in v1 with drivers that accept v2

**Comment by ovan-mining87** [comment]
> I have 2 RTX-3060 V1 running at 80% on LoLminer!!! Driver 460.39 (linux-HiveOS).
> 
> I bought an RTX-3060 V2, not even linux can load it with the 460.39 driver.
> 
> Surely someone has had a similar problem.
> 
> How did you solve it?
> 
> Can you guide me?

I have same configuration 1x 3060v1 1x 3060v2. 460.39 wont work for v2 instead iam using 470.63 driver
and use mode --LHR2 then start tuning each card
now I get 34 MH/s each card. hopefully LHR unlock up to 80%
