### ISSUE TITLE
Palit gamerock OC RTX 3080TI doesn't work mode LHRLP and LHR2. 49-50 mh

### ISSUE THREAD

**Issue by MINT322** [Lolliedieb/lolMiner-releases#731]
Hello there!
HiveOS. Palit Gamerock 3080TI OC. Trying to run lhrlp mode  (1150/2600, 1500/2600) or lhr2 mode (1500/2600) and got only 49-51 mh stable. 
Another miner works good with 83-85 mh.

**Comment by jgonzis** [comment]
> Hello there!
> HiveOS. Palit Gamerock 3080TI OC. Trying to run lhrlp mode (1150/2600, 1500/2600) or lhr2 mode (1500/2600) and got only 49-51 mh stable.
> Another miner works good with 83-85 mh.

coul you try adding:

--mode LHR2 as parameter 

Try it... if you have your card connected directly to the Mobo then try adding --lhrtune -10, if continues at 49-51, decrease in steps of 10 until you get it running

**Comment by MINT322** [comment]
Directly MB connect - Yes
So, I've got that result:
1150/2600 LHR2 lhrtune -10 = 49-50
1150/2600 LHR2 lhrtune -20 = 81-83 (PL 260-280)

**Comment by jgonzis** [comment]
> Directly MB connect - Yes
> So, I've got that result:
> 1150/2600 LHR2 lhrtune -10 = 49-50
> 1150/2600 LHR2 lhrtune -20 = 81-83 (PL 260-280)

That's great, now you can play from -20 to -11, the higher it doesn't lock your card the more hash you will have...
Try -15 to see if start blocked or not... so know you have a good option to start.  Values around -20 to -11

**Comment by zallos98** [comment]
would you mind pasting the script for mining here? please remember to leave out your wallet.

**Comment by jgonzis** [comment]
Could you try new release 1.33 that work without parameters and you could be able to achive  the result directly from the autotune. It will need aprox 10 min but it is done automaticly.
