### ISSUE TITLE
Fee subtraction?

### ISSUE THREAD

**Issue by CryptoDonkeyMiner** [Lolliedieb/lolMiner-releases#733]
Hey, I would like some help with how the fee is subtracted.

I have read the readme but cannot seem to find the details that I am looking for. Forums are not help either, as they are full of misinformation.

When I see my hashrate in the miner and HiveOS, in this case 268.9 MH/s in ERGO, is the 1.5% fee subtracted already, which would give a real hashrate of 272.99 MH/s when using inverse percentage calculations?

**Comment by jgonzis** [comment]
> Hey, I would like some help with how the fee is subtracted.
> 
> I have read the readme but cannot seem to find the details that I am looking for. Forums are not help either, as they are full of misinformation.
> 
> When I see my hashrate in the miner and HiveOS, in this case 268.9 MH/s in ERGO, is the 1.5% fee subtracted already, which would give a real hashrate of 272.99 MH/s when using inverse percentage calculations?

At the end the best is to check in long term the average at the pool.  So you will see that the value you get at the pool  is the same as reported. Other miners don't have this political... they increase their reported hashrate to pick more users.

**Comment by CryptoDonkeyMiner** [comment]
@jgonzis yes there is a lot of confusion when it comes to how the fee is calculated and subtracted. I am doing a bunch of hashrate comparison videos ( https://www.youtube.com/c/CryptoDonkeyMiner ) where I would like to subtract the fee and I am working on an in-depth look at fee calculations. However it seems very hard to get an official explanation from developers and is not included in the documentation :/

**Comment by jgonzis** [comment]
> @jgonzis yes there is a lot of confusion when it comes to how the fee is calculated and subtracted. I am doing a bunch of hashrate comparison videos ( https://www.youtube.com/c/CryptoDonkeyMiner ) where I would like to subtract the fee and I am working on an in-depth look at fee calculations. However it seems very hard to get an official explanation from developers and is not included in the documentation :/

You can enter in lolMiner telegram group and ask the developer, he is normally open to talk

**Comment by CryptoDonkeyMiner** [comment]
Perfect, thank you! 👍
