### ISSUE TITLE
Please add Octopus algo for AMD GPUs

### ISSUE THREAD

**Issue by rhyno78** [Lolliedieb/lolMiner-releases#734]
So far this is the only algo that we can’t mine on AMD RX 6000 series… please add this algo. Thanks

**Comment by jgonzis** [comment]
> So far this is the only algo that we can’t mine on AMD RX 6000 series… please add this algo. Thanks

The problem is that is not efficient for AMD that algo... that's the big problem...

**Comment by rhyno78** [comment]
does the performance that bad in amd gpus? so no plan for adding octopus for amd gpus then…

**Comment by jgonzis** [comment]
> does the performance that bad in amd gpus? so no plan for adding octopus for amd gpus then…

Yes it is.... really bad in AMD

**Comment by kamenkadze** [comment]
Where Octopus? -_-
