### ISSUE TITLE
API and Performance_Unit

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [Lolliedieb/lolMiner-releases#74]
Hi
During create API client found an issue, that always in few examples (for BTCZ, BEAM) got hashrate (Performance_Summary) in "sol/s" units.
For ETHash algo see that hashrate is presented in "mh/s"

Please give more details about all available units in Performance_Unit field API json results. And please give info if for example for ETHash units always are "mh/s" or with small values will be presented as "h/s"?

**Comment by Lolliedieb** [comment]
The exact unit that is used is always presented in "Session.Performance_Unit". This field is what is relevant and can be relied on.

Overall at the moment Ethash and Etchash algorithms use mh/s (10^6 hashes per second), Equihash and Beam algorithms use sol/s (solutions per second) and all cuckoo based algorithms use g/s (graphs per second)
