### ISSUE TITLE
RX 470 4GB, ZOMBIE MOD 0MH/S

### ISSUE THREAD

**Issue by tinho200069** [Lolliedieb/lolMiner-releases#744]
Hello, I have an rx 470 DE 4GB, connected directly to the x16 3.0, and when I start lolminer, it activates the zombie mod, but the mh / s doesn't go up, it's always at 0.1

What can I do
![zombie](https://user-images.githubusercontent.com/91621492/135304015-d17ed931-a767-4ae5-ae68-013b236da9e5.PNG)
?

![image](https://user-images.githubusercontent.com/91621492/135304074-2a15ec0d-3c0c-4431-a931-98484e884ce1.png)

**Comment by pdieppa** [comment]
I'm not sure you are able to mine ETH using a 4GB card anymore due to the current size of DAG.

**Comment by kiaas** [comment]
Zombiemode doesn't work on windows anymore.

**Comment by jgonzis** [comment]
Complety true, it is not possible to mine more ETH in 4Gb in Windows. You can do it in Linux, profit is quite small, it is more profitable for that 4Gb, ETC, ERGO or BEAM
