### ISSUE TITLE
1060 3gb with errice messgage on 1.28a 

### ISSUE THREAD

**Issue by shangxue12345** [Lolliedieb/lolMiner-releases#745]
hi guys just install this app on the computer , is this message saying not mining or it's mining ? not sure ... please help .
its the one saying will work on 1060 3 gb ,,, so i downloaded .but  not sure if it's working 

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    NVIDIA GeForce GTX 1060 3GB
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  3072 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)

Connecting to pool...
Connected to asia2.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: xxxxxxxxxxxxxxxxxxx.lolMinershang
New job received: 0x0275f3 Epoch: 444 Target: 00000000ffff0000
Start Mining...
GPU 0: error when allocating memory or building DAG. Disabling card.
New job received: 0x558c35 Epoch: 444 Target: 00000000ffff0000
New job received: 0x5dc697 Epoch: 444 Target: 00000000ffff0000
New job received: 0x42b572 Epoch: 444 Target: 00000000ffff0000
New job received: 0x1bef9f Epoch: 444 Target: 00000000ffff0000
Average speed (30s): 0.01 mh/s
New job received: 0x8b0740 Epoch: 444 Target: 00000000ffff0000
New job received: 0x2c7e91 Epoch: 444 Target: 00000000ffff0000
New job received: 0xe9c794 Epoch: 444 Target: 00000000ffff0000
New job received: 0xfa93ef Epoch: 444 Target: 00000000ffff0000
New job received: 0x993290 Epoch: 444 Target: 00000000ffff0000
New job received: 0x3fe7e5 Epoch: 444 Target: 00000000ffff0000
New job received: 0xafb8a0 Epoch: 444 Target: 00000000ffff0000
New job received: 0x66276b Epoch: 444 Target: 00000000ffff0000
New job received: 0x0c3b75 Epoch: 444 Target: 00000000ffff0000
New job received: 0x8e30ff Epoch: 444 Target: 00000000ffff0000
New job received: 0x22e94a Epoch: 444 Target: 00000000ffff0000
New job received: 0x0c76bc Epoch: 444 Target: 00000000ffff0000
New job received: 0x6579ec Epoch: 444 Target: 00000000ffff0000
New job received: 0xdf5b9f Epoch: 444 Target: 00000000ffff0000
New job received: 0xbe555e Epoch: 444 Target: 00000000ffff0000
New job received: 0x1b3cd5 Epoch: 444 Target: 00000000ffff0000
New job received: 0x8f2412 Epoch: 444 Target: 00000000ffff0000
New job received: 0x006094 Epoch: 444 Target: 00000000ffff0000
New job received: 0x9b6392 Epoch: 444 Target: 00000000ffff0000
New job received: 0xb3bc24 Epoch: 444 Target: 00000000ffff0000
New job received: 0x3f9aea Epoch: 444 Target: 00000000ffff0000
Average speed (30s): 0.00 mh/s
New job received: 0x115b6f Epoch: 444 Target: 00000000ffff0000
New job received: 0x7a3231 Epoch: 444 Target: 00000000ffff0000
New job received: 0xabe2c6 Epoch: 444 Target: 00000000ffff0000
New job received: 0xa7a00d Epoch: 444 Target: 00000000ffff0000
New job received: 0x20204a Epoch: 444 Target: 00000000ffff0000
New job received: 0x667b4a Epoch: 444 Target: 00000000ffff0000
New job received: 0x184642 Epoch: 444 Target: 00000000ffff0000
New job received: 0x791453 Epoch: 444 Target: 00000000ffff0000
New job received: 0x834296 Epoch: 444 Target: 00000000ffff0000
New job received: 0x82399c Epoch: 444 Target: 00000000ffff0000
New job received: 0x1213a4 Epoch: 444 Target: 00000000ffff0000
New job received: 0x7416b5 Epoch: 444 Target: 00000000ffff0000
New job received: 0xbb1521 Epoch: 444 Target: 00000000ffff0000
New job received: 0x488c7b Epoch: 444 Target: 00000000ffff0000
New job received: 0xb7e829 Epoch: 444 Target: 00000000ffff0000
New job received: 0x4538a6 Epoch: 444 Target: 00000000ffff0000
New job received: 0x554974 Epoch: 444 Target: 00000000ffff0000
New job received: 0xff4b7e Epoch: 444 Target: 00000000ffff0000
New job received: 0x681d41 Epoch: 444 Target: 00000000ffff0000
New job received: 0x5872f3 Epoch: 444 Target: 00000000ffff0000
New job received: 0xfd6396 Epoch: 444 Target: 00000000ffff0000
New job received: 0x5a83bd Epoch: 444 Target: 00000000ffff0000
New job received: 0x3a1260 Epoch: 444 Target: 00000000ffff0000
New job received: 0x80e7bb Epoch: 444 Target: 00000000ffff0000
New job received: 0x2a5d3b Epoch: 444 Target: 00000000ffff0000
New job received: 0x0a34c5 Epoch: 444 Target: 00000000ffff0000
New job received: 0x47a60c Epoch: 444 Target: 00000000ffff0000
New job received: 0xdeb78b Epoch: 444 Target: 00000000ffff0000
Average speed (30s): 0.00 mh/s

**Comment by kiaas** [comment]
I'm not in any way associated with the developers- but I don't believe there is support for Zombie mode on the 1060 3GB in general, so it simply won't be able to mine ethereum on any platform.

**Comment by jgonzis** [comment]
You cannot mine with a 3Gb GPU ETH. You can try to run ERGO or ETC that will work.
