### ISSUE TITLE
Hashrate very low

### ISSUE THREAD

**Issue by OpenAI-coder** [Lolliedieb/lolMiner-releases#75]
In version 1.11 the hashrate is unstable on Windows for Ethash. Hashrates vary from 1 mh/s to 28 mh/s (for RX 580 4GB). I have a rig with 5 cards (all RX 580) and every time I stop and start again I get another hashrate varying from 5 mh/s to 80 mh/s for the rig. It seems sometimes not all the cards can mine at full speed.
Thx for checking

**Comment by Lolliedieb** [comment]
Windows and Ethash is difficult with 4G - but I will give it a try with 1.12 :)
