### ISSUE TITLE
lolminer hive OS problem ETHASH

### ISSUE THREAD

**Issue by githubreader11** [Lolliedieb/lolMiner-releases#76]
Hello
there is a problem with lolminer in HIVE OS:
- i decided to change the miner, after installing lolminer as a default miner, the farm starts to reboot every minute, mining does not work, hash rate is not visible. coin - ETHASH.
I tried to do this on different farms, the situation does not change. on other miners (phoenix miner and several others, the same farm mines without any problems. Card - 6x Radeon RX 470 4GB
maybe, some additional tuning need to be made. can you help me in this situation? thank you.
![1](https://user-images.githubusercontent.com/73833987/97873324-231a0980-1d20-11eb-8f06-e005c5fcd97b.png)
![2](https://user-images.githubusercontent.com/73833987/97873342-27462700-1d20-11eb-9b20-3cabcc8bc546.png)

**Comment by kichsp** [comment]
Что лог манера выжаёт?

**Comment by litwi1rm** [comment]
I have a mixed card rig, some 8GB rx480s some 4GB rx480s, the 4GB are not hashing with lolminer for me either. However, my rig had a month up time after a restart today I haven't been able to get the 4GB cards to work with any miner for ETH.

**Comment by Lolliedieb** [comment]
Can you share what linux kernel you are running on? Please use a Linux kernel different to 5.6 - this one is buggy ...

**Comment by litwi1rm** [comment]
I'm using Kernel
5.0.21-200905-hiveos

**Comment by Lolliedieb** [comment]
Hmm .. ok ... can you see some kind of miner log that is created? Text output the miner prints when starting?

**Comment by lolmineruser** [comment]
After 1-2 minutes rig restarts every time. Hive OS, Lolminer. Radeon RX470-4GB. 

![1](https://user-images.githubusercontent.com/75203838/100540277-64350900-324d-11eb-82ea-2f6be98d217e.png)

**Comment by jgonzis** [comment]
Old thread
