### ISSUE TITLE
Rtx 3080ti power and hash rate fluctuation

### ISSUE THREAD

**Issue by Minersito** [Lolliedieb/lolMiner-releases#768]
Hello , first of all  I would like to thank you for Great work ;) and have 1 question hopefully you  help me out  , I have a rig with 3 X 3080 Ti ( Palit game rock) and Rtx 3080ti MSI Suprimx  on HIVE Os  , used Nbminer ( wattage fluctuation was bad) watched red panda video yesterday I switch to lolminer 1.33 however it seems to struggle with calibrating or something i down know what power drops to 0 somtimes and it is a mess , I have exactly the same Gpus  is another rigs where is works fine ( they are  mixed with non lhr gpus , calibated for 5 mitues and work fine )  , wattage and HR  is stable much better than nb miner  ,  Do you thing that lolmoner is not able to calibrate multiple gpus? its been on for 3 hour  not sable at all ,HIve OS 4gb ram ( 750mb ram left ) could it be that i need more ram?    Clocks are 

Hive os 
core 1000 , memory 2000 power 300 
NVIDIA driver 470.74 

it would be great to work it out :)

thanks 
![Screenshot (27)](https://user-images.githubusercontent.com/92190993/136637691-b4bab966-4549-4e7c-9751-88f5d3c68577.png)

**Comment by jgonzis** [comment]
> You can see stabile line is non lhr cards and blue and green is lhar 3080ti and 3070ti , As i sad hashrate is good and stabile it just the power fluctuation is bothering me
> 
> And Rig with 3080ti (x7) i switch to RVN coin bcause power fluctuation wass too high and got scared , if you somehow help me solve these power fluctuation issue i will donate 1 days profits to the charity of your choice ;)

It is quite normal the Watts fluctuations because it makes small pauses in the no mining time to avoid the lock of the LHR Card. I suppose you are with Fixed Core too.

**Comment by Minersito** [comment]
Thanks for quick reply , I understand , when i first switchedb lol anfter watching red panda minig video  , power was stabile , my clock was core -200 memt 1600 however it stopped working in 1 day , after i set core 1200 and mem 2000 it works stabile , then i restarted rig and power was fluctuating so that why i am confused , you mentioned FIXED CORE , is there any thing i can do to unfix it?  If that helps any was i think its not yoo bad so i ll jusy live with it 

Thanks again and i wish you to 100% unlock soon maby you can invent some kind of riser which would unlock the gpu 100% ;)
