### ISSUE TITLE
105% invalid Shares

### ISSUE THREAD

**Issue by Glitch08** [Lolliedieb/lolMiner-releases#772]
The number of invalid shares my rig is calculating exceed the number of the valid shares, and I don't know why. I've already tried to de-overclock all of my 5x R9 290 Tri-X OC edition, and also tried to reduce the clock to the clock of a R9 290 stock  (I'm on Windows and I'm mining Ergo on the 2 miners pool, changing pool nothing change). 
Pls Help

**Comment by kiaas** [comment]
Hawaii has a known bug that causes many/most of its shares to be invalid https://github.com/Lolliedieb/lolMiner-releases/issues/693

**Comment by CecoSvidovski** [comment]
> > Having the same problem here with my r9 390s... Someone found a fix?
> 
> Could you show a picture please? To have an idea what is happening?. Also which Driver? Which Miner version ....

Fixed it! It was happening only on lolminer but after switching to "Radeon Software Crimson ReLive Edition Beta for Blockchain Compute" - [https://www.amd.com/en/support/kb/release-notes/rn-rad-win-blockchain-beta](url) it works fine for now. I will write here if something goes wrong. I forgot to check which driver I was using. It was the driver windows 10 installs by default. I think it was showing 27.x.x for my r9s and 30.x.x for my rx 580s in the device manager (I can't remember the exact version). All the gpus were getting stale shares. Not 100% but more like 30%. The thing was that I was struggling to make them all mine on 1 rig and I tried a couple of drivers and either the 580s or the r9s were randomly crashing or not even showing in all miners I have installed then I decided to let windows do it's thing and it worked but then the stales started appearing out of nowhere. That crimson beta compute driver was the most stable driver that I can find that both supports amd's compute mode, works with older gpus like my r9 390s and was also able to get the max hashrate out of my rig.

**Comment by jgonzis** [comment]
> > > Having the same problem here with my r9 390s... Someone found a fix?
> > 
> > 
> > Could you show a picture please? To have an idea what is happening?. Also which Driver? Which Miner version ....
> 
> Fixed it! It was happening only on lolminer but after switching to "Radeon Software Crimson ReLive Edition Beta for Blockchain Compute" - [https://www.amd.com/en/support/kb/release-notes/rn-rad-win-blockchain-beta](url) it works fine for now. I will write here if something goes wrong. I forgot to check which driver I was using. It was the driver windows 10 installs by default. I think it was showing 27.x.x for my r9s and 30.x.x for my rx 580s in the device manager (I can't remember the exact version). All the gpus were getting stale shares. Not 100% but more like 30%. The thing was that I was struggling to make them all mine on 1 rig and I tried a couple of drivers and either the 580s or the r9s were randomly crashing or not even showing in all miners I have installed then I decided to let windows do it's thing and it worked but then the stales started appearing out of nowhere. That crimson beta compute driver was the most stable driver that I can find that both supports amd's compute mode, works with older gpus like my r9 390s and was also able to get the max hashrate out of my rig.
> 
> EDIT: I thought I mentioned it but I didn't. My rig has r9s and 580s mixed together and by the way the 580 was also getting stale shares.

Many thanks for the feedback and the really well guide solution
