### ISSUE TITLE
Unrecoverable memory error by GPU 2

### ISSUE THREAD

**Issue by IkhbayarO** [Lolliedieb/lolMiner-releases#775]
I am getting below error with one of my MSI rtx3090 GPU.
Unrecoverable memory error by GPU 2. Reset of all Cuda GPUs required. Please check your (memory) OC & UV settings on this card. ... Device 0 detected as crashed.

It is failing even all settings are 0 and it works good for gaming. All other same brand gpu's works fine.
What should I do, can you help on that?

**Comment by jgonzis** [comment]
> I am getting below error with one of my MSI rtx3090 GPU. Unrecoverable memory error by GPU 2. Reset of all Cuda GPUs required. Please check your (memory) OC & UV settings on this card. ... Device 0 detected as crashed.
> 
> It is failing even all settings are 0 and it works good for gaming. All other same brand gpu's works fine. What should I do, can you help on that?

That's Normally that Memory OC it is too high in the GPU2,the nvidia Drivers after that crash normally all goes down. Try to reduce a big step in memory OC of the GPU2 to work without problem. The problem lot of youtubers and people have an extreme OC it can work sometime until you damage the GPU in the memory, so problems starts then...

**Comment by jgonzis** [comment]
No problem or feedback... close issue
