### ISSUE TITLE
Lolminer cuando se reinicia, luego no inicia a trabajar

### ISSUE THREAD

**Issue by Tonitkd** [Lolliedieb/lolMiner-releases#776]
Hola chicos como estan? tengo un proble hace un tiempo, tengo una 3060 LHR V1 la cual de vez en cuando crashea, pero el problema es que cuando reinicia el minero automaticamente no inicia a minar, tengo que cambiar el minero, por ejemplo a trex y luego volver a lolminer para que funcione.

Hay algun parametro que pueda agregar u opcion para que arranque automaticamente cuando se reinicia? comparto mis parametros

![image](https://user-images.githubusercontent.com/89988162/136848053-9cc6aceb-3cc2-434d-98e6-45261c3c6e4c.png)

![image](https://user-images.githubusercontent.com/89988162/136848041-ebadfe43-b533-464d-a30f-8fe0d1baf921.png)

Muchas gracias

**Comment by Tonitkd** [comment]
Muchas gracias! voy a probar bajando la memoria. Pero por otro lado tenes idea porque no incia automaticamente Lolminer luego de esto? Muchas gracias!

**Comment by jgonzis** [comment]
No problem or feedback... close issue
