### ISSUE TITLE
Bestway for autotune to work? 

### ISSUE THREAD

**Issue by Vantharas** [Lolliedieb/lolMiner-releases#777]
Should I leave the cards stock and let it autotune. *then* overclock? Or set my overclock settings then let it figure it out?

**Comment by jgonzis** [comment]
Always put 1st the OC and later let them Autotune work, if you change OC after autone the values won't be real. Each change of OC is recommended a miner restart.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
