### ISSUE TITLE
hash rate Is very low compaered to benchmark 

### ISSUE THREAD

**Issue by yahia20** [Lolliedieb/lolMiner-releases#78]
I have a 5500xt 4GB online hashrate is stated to be 24.17 when I benchmark it gives me similar value but when I connect to a pool I get hash rate of 1.6 which is very low 
what can cause this ?

**Comment by Lolliedieb** [comment]
I guess this is Windows... the reason is that for Navi cards I did not create a zombie mode kernel yet. Will see if I can add them in the future.

**Comment by yahia20** [comment]
I have opened a very similar issue here https://github.com/Lolliedieb/lolMiner-releases/issues/82 by accident so I will close this one
