### ISSUE TITLE
3070TI Does not Tune unless overclocks are dropped first. Then applied during tuning. *reproducible* 

### ISSUE THREAD

**Issue by Vantharas** [Lolliedieb/lolMiner-releases#780]
When pairing this card with my 3 3080TI's my 3070TI is not getting any LHR tuning. LoLminer keeps leaving it at 46mh, It did tune it once. and got it up to over 60 then, when I checked again it dropped down to 46 and never went back up.  This is consistent though. Every restart it tunes it, and then it drops off to mid 40s.

**Comment by Vantharas** [comment]
To reproduce this bug, I have a 3070TI with a 2000mhz stable memory overclock. On LOLminer if I do nothing it mines at  46mh/s if I leave this Overclock on. However, if I turn it *off* Then it says the MH is too low and goes into LHR mode and starts tuning then if I reapply the overclock it tunes it back up to over 60mh's.

**Comment by jgonzis** [comment]
> To reproduce this bug, I have a 3070TI with a 2000mhz stable memory overclock. On LOLminer if I do nothing it mines at 46mh/s if I leave this Overclock on. However, if I turn it _off_ Then it says the MH is too low and goes into LHR mode and starts tuning then if I reapply the overclock it tunes it back up to over 60mh's.

Which OS and which Drivers?.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
