### ISSUE TITLE
Invalid Shares and Fluctuations after new Update

### ISSUE THREAD

**Issue by Skydiver911** [Lolliedieb/lolMiner-releases#781]
Hello, after Updating to the newest Version of LoLMiner my 3080 TI Founders Edition gets Invalid Shares and Fluctuations at the MH by Mining Ethereum.

I downgrade after that again and everything is Working fine now. I Used Same OCs before the Update.

**Comment by Skydiver911** [comment]
Mining at HiveOS, after the Update i noticed that Sometimes the MHs dropped down to 20mh

**Comment by jgonzis** [comment]
Could you share some pictures or more information to try to help?

**Comment by jgonzis** [comment]
No problem or feedback... close issue
