### ISSUE TITLE
New driver Nvidia

### ISSUE THREAD

**Issue by xKabal** [Lolliedieb/lolMiner-releases#783]
Hello, there is a new driver for nvidia 496.13 (windows). Should I install it on version 1.33? Also tell me when the new version will be released?

**Comment by jgonzis** [comment]
> Hello, there is a new driver for nvidia 496.13 (windows). Should I install it on version 1.33? Also tell me when the new version will be released?

The last release I think it was used with Nvidia Driver 472, You can try 496.13 and give us some feedback too

**Comment by xKabal** [comment]
> > Здравствуйте, появился новый драйвер для nvidia 496.13 (windows). Стоит ли устанавливать на версию 1.33? Также скажите, когда выйдет новая версия?
> 
> Последний выпуск, я думаю, он использовался с Nvidia Driver 472, вы можете попробовать 496.13 и дать нам несколько отзывов

I downloaded the new version today, h/s fell by 0.5-1. the settings are the same as on version 1.33. I'll try to install a new driver the other day and write reviews in this topic

**Comment by jgonzis** [comment]
> I'm using this version on Windows and I haven't had problems with hashrate drops.
> 
> Windows 11 and driver 496.13
> 
> Except for the sudden drops I have with version 1.33 on Windows, something that with 1.34 doesn't happen anymore on Windows

Could you try 1.48 please?
