### ISSUE TITLE
LOL miner detects my RTX3070 non LHR as being LHR and drop the hashhate 

### ISSUE THREAD

**Issue by AndyPedra** [Lolliedieb/lolMiner-releases#787]
I have in the same rig one GTX1060, RTX3070(non LHR) and a RTX3060 TI LHR.. after  autotune set my cards, works fine for some hours but after that the miner decrease the hashhate for my RTX3070(non LHR)

lhrtune only for RTX3060TI LHR card.. OK!
![image](https://user-images.githubusercontent.com/92612590/137569251-972a3337-1793-458b-9354-cfa8232f02cf.png)

After some hours, my RTX3070 dropping substantially the hashhate (I use Minerstat on Windows)
![image](https://user-images.githubusercontent.com/92612590/137569333-890620d3-aeab-4669-bdf4-2df26fa2a2c1.png)

![image](https://user-images.githubusercontent.com/92612590/137569625-f5b864b0-8662-430e-8bb2-b616b0c75a2b.png)

Unfortunately I don't have the print of the lol miner dropping the hashhate, but the LHR on the screen change for the GPU 1 RTX3070, the new valor is "1"

Watt oscillation is great in this new version for LHR cards, I hope the problem with the RTX3070 is found and fixed by the development team.

Great Work

**Comment by jgonzis** [comment]
> I have in the same rig one GTX1060, RTX3070(non LHR) and a RTX3060 TI LHR.. after autotune set my cards, works fine for some hours but after that the miner decrease the hashhate for my RTX3070(non LHR)
> 
> lhrtune only for RTX3060TI LHR card.. OK! ![image](https://user-images.githubusercontent.com/92612590/137569251-972a3337-1793-458b-9354-cfa8232f02cf.png)
> 
> After some hours, my RTX3070 dropping substantially the hashhate (I use Minerstat on Windows) ![image](https://user-images.githubusercontent.com/92612590/137569333-890620d3-aeab-4669-bdf4-2df26fa2a2c1.png)
> 
> ![image](https://user-images.githubusercontent.com/92612590/137569625-f5b864b0-8662-430e-8bb2-b616b0c75a2b.png)
> 
> Unfortunately I don't have the print of the lol miner dropping the hashhate, but the LHR on the screen change for the GPU 1 RTX3070, the new valor is "1"
> 
> Watt oscillation is great in this new version for LHR cards, I hope the problem with the RTX3070 is found and fixed by the development team.
> 
> Great Work

Do you have a temp stop or similar?,  it could be also that you connect to the rig and when you start to move remotely or locally the use of the gpu makes to drop hashrate and that's why is detected as LHR, the miner think is a drop of the LHR

**Comment by AndyPedra** [comment]
> > I have in the same rig one GTX1060, RTX3070(non LHR) and a RTX3060 TI LHR.. after autotune set my cards, works fine for some hours but after that the miner decrease the hashhate for my RTX3070(non LHR)
> > lhrtune only for RTX3060TI LHR card.. OK! ![image](https://user-images.githubusercontent.com/92612590/137569251-972a3337-1793-458b-9354-cfa8232f02cf.png)
> > After some hours, my RTX3070 dropping substantially the hashhate (I use Minerstat on Windows) ![image](https://user-images.githubusercontent.com/92612590/137569333-890620d3-aeab-4669-bdf4-2df26fa2a2c1.png)
> > ![image](https://user-images.githubusercontent.com/92612590/137569625-f5b864b0-8662-430e-8bb2-b616b0c75a2b.png)
> > Unfortunately I don't have the print of the lol miner dropping the hashhate, but the LHR on the screen change for the GPU 1 RTX3070, the new valor is "1"
> > Watt oscillation is great in this new version for LHR cards, I hope the problem with the RTX3070 is found and fixed by the development team.
> > Great Work
> 
> Do you have a temp stop or similar?, it could be also that you connect to the rig and when you start to move remotely or locally the use of the gpu makes to drop hashrate and that's why is detected as LHR, the miner think is a drop of the LHR

Hi, I don't have temp stop or similar.. today happening again and the temperature in my city today was low, The temperature on the rig was stable low along the day, I think it is another problem. I printed new evidences of the issue....

Tune LHR on my non-LHR GPU1 RTX3070 
![Capturar1](https://user-images.githubusercontent.com/92612590/137601094-a909787c-0c4f-4514-b23f-3835274fecb9.JPG)

The exact moment......

![Capturar2](https://user-images.githubusercontent.com/92612590/137601100-b5f0a496-989a-496e-9efa-c23dda3a5315.JPG)

**Comment by rcerebro** [comment]
Same problem. I have an LHR and an NLHR, in both HiveOS and Windows it has the same behavior, starts without problems and after a period the NLHR becomes LHR for the miner without making clock changes, temperatures, etc.

**Comment by jgonzis** [comment]
> Same problem. I have an LHR and an NLHR, in both HiveOS and Windows it has the same behavior, starts without problems and after a period the NLHR becomes LHR for the miner without making clock changes, temperatures, etc.

That hat happened if --tstop is used and the GPU reach that temp...

**Comment by rcerebro** [comment]
> > Same problem. I have an LHR and an NLHR, in both HiveOS and Windows it has the same behavior, starts without problems and after a period the NLHR becomes LHR for the miner without making clock changes, temperatures, etc.
> 
> That hat happened if --tstop is used and the GPU reach that temp...

I never used the option, default mining by hiveos or Windows with minerstat, just indicating URL, Wallet and Pool, nothing else. The system itself takes care of temperature and fans, however in hiveos only the LHR does not cause problems regardless of fan or temperature, and other miners also do not have the problem of drops with oscillating or increasing fan temperatures

**Comment by jgonzis** [comment]
Are you using Nvidia Driver 470.74?

**Comment by rcerebro** [comment]
> Are you using Nvidia Driver 470.74?

Latest version 496 and the same behavior for 472 for Windows and for HiveOS 470.74, I've tried previous versions as well and the same behavior when using all cards only with lolminer, if I only leave mining in LHR I have no problems.

**Comment by jgonzis** [comment]
You can try new 1.34, it has the function to turn off lhrtune if a card start making LHR Settings.

**Comment by rcerebro** [comment]
![image](https://user-images.githubusercontent.com/38794375/137809974-ca2367d4-ae57-4ea0-bf60-7770f955523e.png)

While I was writing the above post, it simply restarted the miner by itself, there was even loss of the 3070 NLHR, after a run of about 2 minutes it normalized again

**Comment by rcerebro** [comment]
> Don't forget not all miners give real hash... some inflate their numbers to bring more users... that's not the politics of lolminer, but some of the mentioned they do it. So average at pool is not what they report...

Yes, I've noticed this in other miners and compared to the pool, they are really inflated to draw attention.

**Comment by rcerebro** [comment]
> > ![image](https://user-images.githubusercontent.com/38794375/137816006-44d1bc16-2001-4699-adef-993297828553.png)
> > Agora no Windows, veja que o 3070 acabou batendo no meio da mineração, mesmo usando lhrtune off, off, auto que deve desativar, após esse erro, apenas reiniciando o mineiro e o mesmo problema de travamento volta, e também a velocidade de mineração no Windows é melhor que o HiveOS (mesma versão do mineiro).
> > ![image](https://user-images.githubusercontent.com/38794375/137816141-10a21fda-6f68-475f-b050-82fa53f0f7bb.png)
> > Detalhe o mesmo overclock funciona normalmente em todos os mineiros, exceto para lolminer que cai, e minerstat aplica o overclock somente depois que o dag é criado, mesmo minerando por um tempo e, em seguida, o acidente
> 
> Ele trava no Windows por exceder de OC...
> 
> > ![image](https://user-images.githubusercontent.com/38794375/137814270-fe56cba2-5c57-4d1f-9ca2-7ed3b6035258.png)
> > ![image](https://user-images.githubusercontent.com/38794375/137814939-25069f9f-296f-4dbd-adf4-a7fd15078b8d.png)
> > E essa diferença de hashrate entre versões? Não é muito, mas existe.
> 
> Se os Drivers Nvidia são 470.74, isso deve ser o mesmo depois de algum longo prazo. Normalmente, os 45 que você vê vão ficar trancados. Também em 1.34 ele começa mais rápido e vai.passo a passo para cima.
> 
> Suponho que você é algo dividindo mem clock por 2 para Windows. Pode ser que o Nvidia Windows deixe mais espaço para o LHR. Por exemplo, no Linux 460.93 dá muito menos espaço do que 470.74

Yes, Windows/2 of course. But what's strange is, but it doesn't matter, I opted for the time being to stay at 1.33 only with this VGA and leave the others in other miners as before until a new version comes out and that maybe stabilizes better, but thanks for the help and attention

![image](https://user-images.githubusercontent.com/38794375/137898980-bb7e9821-5efb-4fbc-a0fa-b44ca3c386e7.png)

**Comment by rcerebro** [comment]
I'll test it with this over you passed and I'll report it to you

**Comment by D3RON** [comment]
I think this issue affected me. 

I have just a 3070 and have been mining fine for about 6 months using lolminer 1.26 achieving around 59mh on average.

A few days back 11th November I decided to update my lolminer 1.26 client to 1.35 to realise any improvements. I noticed yesterday 13th November that my average hashrate had dropped to 50.

When I checked this morning I noticed it had dropped down to 40 with the same message about LHR Semi-unlocking calibration in my feed.

I stopped it this morning and went back to 1.26 and have started realising my previous hashrate.

I've attached the screenshots from this morning when I reverted to 1.26

![Screenshot 2021-11-14 114641 1 35](https://user-images.githubusercontent.com/94294751/141679878-bdb6af79-4490-424c-a736-68d91c121283.png)

![Screenshot 2021-11-14 114803 1 26](https://user-images.githubusercontent.com/94294751/141679965-6090b8cd-2097-4374-8890-5012ad61d338.png)

**Comment by jgonzis** [comment]
> I think this issue affected me.
> 
> I have just a 3070 and have been mining fine for about 6 months using lolminer 1.26 achieving around 59mh on average.
> 
> A few days back 11th November I decided to update my lolminer 1.26 client to 1.35 to realise any improvements. I noticed yesterday 13th November that my average hashrate had dropped to 50.
> 
> When I checked this morning I noticed it had dropped down to 40 with the same message about LHR Semi-unlocking calibration in my feed.
> 
> I stopped it this morning and went back to 1.26 and have started realising my previous hashrate.
> 
> I've attached the screenshots from this morning when I reverted to 1.26
> 
> ![Screenshot 2021-11-14 114641 1 35](https://user-images.githubusercontent.com/94294751/141679878-bdb6af79-4490-424c-a736-68d91c121283.png)
> 
> ![Screenshot 2021-11-14 114803 1 26](https://user-images.githubusercontent.com/94294751/141679965-6090b8cd-2097-4374-8890-5012ad61d338.png)

Are you in Windows?... It could be that playing ot opnening something the detection runs on it... you can use --lhrtune off as a parameter and it will not happen again :-)

**Comment by D3RON** [comment]
Thanks, I've reverted back to 1.26 now. Back to my usual hash level.

If it's not broke!

**Comment by jgonzis** [comment]
Try 1.36 with higher hashrate and less latency for less stales, and add the --lhrtune off as parameter.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
