### ISSUE TITLE
Windows 11 2x Gigabyte 3080 Turbos 8G

### ISSUE THREAD

**Issue by Oscaramr** [Lolliedieb/lolMiner-releases#788]
Lol miner is pulling a insane amount of my cpu for some reason around 15%-25% 
My CPI is a AMD Ryzen 7 3700x 8-Core
My RAM is RipJaws 2400MHz 16GB
My GPU(S) are Gigabyte 3080 Turbo LHR Rev 2.0 X 2
My OS is 
  Edition: Windows 11 Home 
  Version: 21H2 
  Build Version: 22000.282 
  Experience: Windows Feature Experience Pack 1000.22000.282.0
LolMiners Version Tried 1.33 and 1.32a
![image](https://user-images.githubusercontent.com/40370279/137639513-f064e274-26bb-4779-aad8-9572e4dad7d7.png)

**Comment by Oscaramr** [comment]
Ahh i see you know when windows 11 will fix this? or know any fix to this

**Comment by jgonzis** [comment]
Could you try new version 1.48?

**Comment by Oscaramr** [comment]
> Could you try new version 1.48?

I am using nbminer but beofre i switched i think i fixed it by. Using a older driver

**Comment by jgonzis** [comment]
> > Could you try new version 1.48?
> 
> I am using nbminer but beofre i switched i think i fixed it by. Using a older driver

Thx for the feedback
