### ISSUE TITLE
Dont want unlock lhr, it is already unlocked without lolminer so it reduce hashrate for nothing 

### ISSUE THREAD

**Issue by lhmnona** [Lolliedieb/lolMiner-releases#789]
how to disable unlock lhr? 

where to put the code and which code? 

![DD32FBEF-0286-4119-AB44-484EDAD1C3CD](https://user-images.githubusercontent.com/92714641/137691717-1f253f93-f12c-4d97-ae30-bf3ad5728c3e.jpeg)

**Comment by jgonzis** [comment]
No problem or feedback... close issue
