### ISSUE TITLE
on vegs 56 does not mine CuckaroozC29 only rejects Shar

### ISSUE THREAD

**Issue by ma77** [Lolliedieb/lolMiner-releases#79]

**Comment by ma77** [comment]
1.11 does not mine CuckaroozC29, CuckatooC32 on vegs 56. on CuckaroozC29 the miner is launched but everything is redjectshare,  CuckatooC32 does not start at all freezes you have to close the miner

**Comment by Lolliedieb** [comment]
lolMiner does not support C29Z ... the last C29 code that was supported was C29M

**Comment by dropdeadrus** [comment]
> lolMiner does not support C29Z ... the last C29 code that was supported was C29M
but your wiki states that C29Z is supported.

https://github.com/Lolliedieb/lolMiner-releases/wiki/lolMiner-1.0-and-newer-basic-useage
<img width="323" alt="Снимок экрана 2020-11-24 в 04 39 12" src="https://user-images.githubusercontent.com/18132734/100027673-149aab80-2e0f-11eb-812d-f130401906bb.png">

you don't want to implement it? :)
