### ISSUE TITLE
LolMiner 1.34 and HiveOS - autotune lhr - restart and reboot all the time 

### ISSUE THREAD

**Issue by Gkozd** [Lolliedieb/lolMiner-releases#794]
Hi,
Same thing happening like with Lolminer 1.33. 

RIG 8 cards (3060ti and 3080 - all lhr v2). Autolykos2, Ergo.

If I will use in HiveOS -> tunining -> lolminer  --lhrtune (alone) or --lhrtune auto or --lhrtune  auto,auto,auto,auto,auto,auto,auto,auto , Lolminer will start working for few minutes ( random time for me) and restart. After another restart it will reboot rig. And all over again. 

![lol1 34a](https://user-images.githubusercontent.com/87426164/137872153-726ba182-8b9e-40dd-a9dc-3ac63df879ac.JPG)

![lol1 34c](https://user-images.githubusercontent.com/87426164/137872178-f88c62e4-9f77-4aa8-b078-6cbc44db3f64.JPG)

![lolminer 1 34aa](https://user-images.githubusercontent.com/87426164/137872242-5490d48e-2552-4fb3-8c04-00871f27efad.JPG)

![lolminer 1 34](https://user-images.githubusercontent.com/87426164/137873076-bc748b08-dffd-4eed-95a4-de68d6c8722f.JPG)

after restart: 

![lolminer 1 34b](https://user-images.githubusercontent.com/87426164/137873092-6f9d9785-101d-4bfc-b3c9-af25e03a6a1f.JPG)

But if I will put some numbers ( no matter what numbers, could be 1 could be -66 or 99) lolminer start to work, let say normally (without restarting).
![lol1 34d](https://user-images.githubusercontent.com/87426164/137872374-17188f49-34b2-4a50-853a-154b63537284.JPG)

Also 1.34 look like is less effective ( around 20 Mh/s less for entire rig - from  around 1577 dropping to around 1555)

**Comment by Gkozd** [comment]
Fair enough. Do not use  --lhrtune for Ergo. Thank you for explanation. 

But there is still second issue - dropping hashrate. It look like 1-2 MH/s less on every g-card with Lolminer 1.34. So for entire rig (8 cards) it will give me around  20 Mh/s. For big mine (n-rigs)  it will be much more of issue to consider. 

Tried several time and 1.33 oscillating around 1577, 1.34 around 1555.

**Comment by Gkozd** [comment]
> > Fair enough. Do not use --lhrtune for Ergo. Thank you for explanation.
> > But there is still second issue - dropping hashrate. It look like 1-2 MH/s less on every g-card with Lolminer 1.34. So for entire rig (8 cards) it will give me around 20 Mh/s. For big mine (n-rigs) it will be much more of issue to consider.
> > Tried several time and 1.33 oscillating around 1577, 1.34 around 1555.
> 
> try adding more charge to ERGO... with the parameter --workmulti 288 it is now added, it could probably help with all your 3080...

Quick question - is that parameter ("--workmulti 288") still valid for Lolminer 1.35 ?


 

> Looks like your harshrate watchdog is restating the miner. Disable the watchdog until you calculate what the correct hashrate should be and then set the watchdog again.

Watchdog was set up to act below 800 MH/s (usually I had,  with 1.32 -> 1580 MH/s, with higher version of the Lolminer, including 1.35 < 1560 MH/s)

**Comment by jgonzis** [comment]
> > > Fair enough. Do not use --lhrtune for Ergo. Thank you for explanation.
> > > But there is still second issue - dropping hashrate. It look like 1-2 MH/s less on every g-card with Lolminer 1.34. So for entire rig (8 cards) it will give me around 20 Mh/s. For big mine (n-rigs) it will be much more of issue to consider.
> > > Tried several time and 1.33 oscillating around 1577, 1.34 around 1555.
> > 
> > 
> > try adding more charge to ERGO... with the parameter --workmulti 288 it is now added, it could probably help with all your 3080...
> 
> Quick question - is that parameter ("--workmulti 288") still valid for Lolminer 1.35 ? Also, for quantity of 8 g-cards, where first is 3060ti v2 and the rest are 3080 lhr v2, that "--workmulti 288" should look like (hiveos tuning section) -> "--workmulti 192,288,288,288,288,288,288,288" ? or "--workmulti 288" will work for ALL worker's g-cards?
> 
> I am using Lolminer 1.35 For ERGO only. Most of the tweaks are for eth. But it is not always clear. So:
> 
> --lhrtune now understands the parameter "off" - should I use it for ERGO? If YES, should be like "--lhrtune off" or "--lhrtune off,off,off,off,off,off,off,off" ?
> 
> --ergo-prebuild ? Is it valid for nvidia g-cards and for ergo?
> 
> --workmulti - should I use it for ERGO?
> 
> > Looks like your harshrate watchdog is restating the miner. Disable the watchdog until you calculate what the correct hashrate should be and then set the watchdog again.
> 
> Watchdog was set up to act below 800 MH/s (usually I had, with 1.32 -> 1580 MH/s, with higher version of the Lolminer, including 1.35 < 1560 MH/s)

Lhrtune is for ETH at the moment, new epoch makes a little bit slower the mining, increase clock or power limit.
Ergo pre-build is not YET 😉...

**Comment by jgonzis** [comment]
No problem or feedback... close issue
