### ISSUE TITLE
Mineria Dual ETH + ZIL con Lolminer 1.34 no funciona

### ISSUE THREAD

**Issue by Tonitkd** [Lolliedieb/lolMiner-releases#797]
Hola chicos como estan? venia usando el 1.33 para hacer mineria doble ETH + zil con estos parametros

![image](https://user-images.githubusercontent.com/89988162/137956463-7caa4db1-1e6c-49d8-9279-0aff3f767104.png)

Pero con el nuevo 1.34 no puedo hacerlo, hay algun parametro que haya que modificar?

Muchas gracias!

**Comment by jgonzis** [comment]
> Hola chicos como estan? venia usando el 1.33 para hacer mineria doble ETH + zil con estos parametros
> 
> ![image](https://user-images.githubusercontent.com/89988162/137956463-7caa4db1-1e6c-49d8-9279-0aff3f767104.png)
> 
> Pero con el nuevo 1.34 no puedo hacerlo, hay algun parametro que haya que modificar?
> 
> Muchas gracias!

Hazlo al revés!!

Pon la conexión normal de ETH directa a la pool que indicas... Y en extra parameters pones:

--enablezilcache --dualmode zil --dualpool eu.ezil.me:5555 --dualuser %WAL%.AQUÍ_TU_CAMBIA_ESTO_POR_TU_ZIL_WALLET

Solo con eso debería funcionar. Repito pasos:
1 - Haz que funcione solo ETH
2- Añade en extraparameters lo comentado arriba .

**Comment by Tonitkd** [comment]
> > Hola chicos como estan? venia usando el 1.33 para hacer mineria doble ETH + zil con estos parametros
> > ![image](https://user-images.githubusercontent.com/89988162/137956463-7caa4db1-1e6c-49d8-9279-0aff3f767104.png)
> > Pero con el nuevo 1.34 no puedo hacerlo, hay algun parametro que haya que modificar?
> > Muchas gracias!
> 
> Hazlo al revés!!
> 
> Pon la conexión normal de ETH directa a la pool que indicas... Y en extra parameters pones:
> 
> --enablezilcache --dualmode zil --dualpool eu.ezil.me:5555 --dualuser %WAL%.AQUÍ_TU_CAMBIA_ESTO_POR_TU_ZIL_WALLET
> 
> Solo con eso debería funcionar. Repito pasos: 1 - Haz que funcione solo ETH 2- Añade en extraparameters lo comentado arriba .

Muchisimas gracias! funcionando perfecto nuevamente con Lolminer 1.34 . un abrazo!
