### ISSUE TITLE
Can you Add Vram Temps on the Miner Dashboard Please? Really needed Feature!!! (Windows)

### ISSUE THREAD

**Issue by HeraklesTR** [Lolliedieb/lolMiner-releases#798]
I really like lol miner but the only major thing it misses is not showing ram temperatures on the dashboard on Windows. All your major competitors already included memory junction temperatures to their user interface (t'rex, gminer, nbminer) because it is very important for eth mining (more important than core temp actually) to see my card throttles or not because of card's vram temps hits 110 C. Thats the only reason i even use windows because hive os and others don't show vram temps either. I really don't want to use custom program all the time to check my vram temps (like hwinfo).

So, developers, you already outdid yourself with LHR unlocks and stability and i kindly ask you to hear our suggestion and please include this small feature to this beautiful miner...

Regards,

**Comment by jgonzis** [comment]
That is done now since last 1.47
