### ISSUE TITLE
core dump in v0.8.1 & Grin

### ISSUE THREAD

**Issue by hammuh1911** [Lolliedieb/lolMiner-releases#8]
Was mining for a while and saw this

New job received: 146098000 Difficulty: 4
Average speed (30s): 0.77 g/s
Average speed (30s): 0.80 g/s
Average speed (30s): 0.80 g/s
New job received: 146099000 Difficulty: 4
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  cancel: Bad file descriptor
./run_miner.sh: line 16:  2583 Aborted                 (core dumped) ./lolMiner --profile $PROFILE $@
miner@rig10:/opt/0.8.1$

Ubuntu 18.04 + ROCm + Vega 64
v0.8.1 on Grin C31

**Comment by Lolliedieb** [comment]
Should be fixed
