### ISSUE TITLE
watchdog not working on Linux

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [Lolliedieb/lolMiner-releases#80]
Hi
I have reported problems from some our users, that watchdog in lolminer is not working.

I did some tests today and see that reboot.sh is not executed at all.

Linux Ubuntu 18, LolMiner 1.12, mining ETH on RX 570 and during mining I ejected GPU from PCIe.
After about one minute hashrate goes down to 0 MH/s and miner gives beauty red message:
"Stuck device detected. Invoking emergency script"
...and nothing more happened.

In miner directory there is reboot.sh script (with 777 privileges - rwxrwxrwx) and content:

--- start script ---
#!/bin/bash

touch /tmp/error.flag
sudo /path/to/my/reboot/script.sh
--- end script ---

and even the flag file in /tmp/ is not created. I was waiting about 10 minutes...and still nothing else happened with this rig.

Please help

**Comment by tymoteuszrogalewski** [comment]
I found some info....that is called "emergency.sh"...

when this change was done from reboot.sh? ;-) and why I could not find nothing about it in changelog or google? :)

**Comment by mbunal** [comment]
in hiveos, emergency.sh did not run. lolminer print invoked on screen, but script did not run.

**Comment by tymoteuszrogalewski** [comment]
Yea, I would like to reopen issue. I also tested with emergency.sh file...and this also didn't run (only bold red message on screen)
Please also update "--help" with watchdog options described
and if you could...do option for test watchdog (simulate crash access to GPU to run watchdog script)

Best regards

**Comment by mbunal** [comment]
i tried 1.15 but it didint work still.

**Comment by Lolliedieb** [comment]
I just did test it ... and indeed have a strange finding.

The code to call the script works exactly until a card hangs up (added just an echo "Hello" to the script) ... and from that point stops doing so... why ever o.O  

Will check whats going on there ... 

Note: when you have something with sudo in the script make sure that its a sudo without password ... else it will ask then for the pw and that won't work ;)

**Comment by Lolliedieb** [comment]
Fixed with 1.16(a)

**Comment by mbunal** [comment]
at last it worked. thank you very much....

**Comment by gravisxv** [comment]
It doesn't work in 1.22 linux version. It message 'closing miner and trying to call external script..' and then nothing it remains stuck.
Is there another way to send reboot to linux?

**Comment by mbunal** [comment]
> It doesn't work in 1.22 linux version. It message 'closing miner and trying to call external script..' and then nothing it remains stuck.
> Is there another way to send reboot to linux?

u should run root privilege.

**Comment by bitcoincff** [comment]
Please fix this error. in version 1.46 the same thing happens
