### ISSUE TITLE
need log files

### ISSUE THREAD

**Issue by stevedidienne** [Lolliedieb/lolMiner-releases#804]
hello, I would like to have the log file but I can not manage because I do not understand the command.
can you help me ?
here are my commands:

.......
set "log = on"

set "path = C: \ Users \ rig_3090_1 \ Desktop \ soft mining \ lolMiner_v1.33_Win64 \ 1.33 \ logs"

Rem ################################
Rem ## End of user-editable part ##
Rem ################################

if exist "% CD% \ lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder. That could take sometime ..."
for / f "delims =" %% F in ('dir / b / s "C: \ lolMiner.exe" 2 ^> nul') do set MyVariable = %% F
if exist "% MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus"
goto END

: infolder
set MyVariable =% CD% \ lolMiner.exe

: WindowsVer
echo "Running lolMiner from% MyVariable%"
for / f "tokens = 4-5 delims =." %% i in ('ver') do set VERSION = %% i. %% j
if "% version%" == "10.0" goto W10
goto OtherW

: W10
"% MyVariable%" --algo ETHASH --pool! POOL! --user! WALLET! --logfile! path! --watchdog exit! EXTRAPARAMETERS!
if% ERRORLEVEL% == 42 (
timeout 10
goto W10
)
goto END

....

**Comment by stevedidienne** [comment]
super ! Is perfect ! thanks!

**Comment by remzej** [comment]
Thanks for this script. Just did a little changes is day, month and year.

for /f "tokens=1-4 delims=/ " %%i in ("%date%") do (
set day=%%i
set month=%%j
set year=%%k
)
for /f "tokens=1-3 delims=: " %%i in ("%time%") do (
set hour=%%i
set min=%%j
set sec=%%k
)
set datestr=%day%-%month%-%year%_%hour%%min%
