### ISSUE TITLE
GPU 1: Error when allocating memory or building DAG. Disabling card

### ISSUE THREAD

**Issue by luckyboyfr** [Lolliedieb/lolMiner-releases#807]
Hi guys,

I have currently a mining box (Windows 10) composed of four GTX 1660S (6GB), I just got a GTX 1650S 4GB so I have added it on that box and launched lolminer 1.28a mining ETH.

At launch I got following msg: GPU 1: Error when allocating memory or building DAG. Disabling card

[https://pasteboard.co/GZo2D7VE4Zzk.png](url)

GPU 1 is the GPU that I just added, the GTX 1650S, the other GTX 1660S are mining fine.

So I tried to fix it by updating lolminer to the latest version: 1.34 and to update Nvidia driver (496.13) as well, the problem is still there.

If anyone have any idea how to solve it, please help thanks.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
