### ISSUE TITLE
RX 5500 Active:  false (Unsupported device or driver version.)

### ISSUE THREAD

**Issue by mbonina** [Lolliedieb/lolMiner-releases#808]
Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    Radeon RX 5500 XT
    Address: 10:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  8176 MByte (8112 MByte free)
    Active:  false (Unsupported device or driver version.)

Help !!! 
Windows 10
Version Radeon 21.8.2
To play the card run ok, but i cant mine.

**Comment by Malique2** [comment]
Tried 1.35. Still not detecting my 5500xts. Mix of 5600, 5700, 5500xts. 5600 and 5700xt detected, 5500xts not.

**Comment by robmemeck** [comment]
hello im having the same problem  in lominer.  
I have a 3070 , 2080 , RX 6700 XT    .. it was working perfectly with driver  "21.5.1"

and  i just added a RX 6600 XT  

had to install another driver for that my new 6600 XT can be detected  " driver 21.12.1" 
and now i have this message 
" Problem in loading kernel Active: false (Unsupported device or driver version.)"

only nvidia cards are detected

i've tried to reinstall "21.5.1"   , same problem  RX 6600 XT not detected 

any ideas please ?

**Comment by jgonzis** [comment]
> hello im having the same problem in lominer. I have a 3070 , 2080 , RX 6700 XT .. it was working perfectly with driver "21.5.1"
> 
> and i just added a RX 6600 XT
> 
> had to install another driver for that my new 6600 XT can be detected " driver 21.12.1" and now i have this message " Problem in loading kernel Active: false (Unsupported device or driver version.)"
> 
> only nvidia cards are detected
> 
> i've tried to reinstall "21.5.1" , same problem RX 6600 XT not detected
> 
> any ideas please ?

Did you try last release 1.38 too??

**Comment by robmemeck** [comment]
yes i  tried the last version 1.38 and it worked fine , thank you

**Comment by Blz14me** [comment]
Hey guys I’m running a 4gb 5500xt a 8gb rx580 and I added a 8gb rx6600. No issues with the 5500 and 580 with drivers 21.5 but that driver set will not recognize the 6600 card. To get that card running I need 21.12.1 for amd to recognize all 3 cards but it kicks the 5500 out in the mining software. It’s either  21.5 and run the 580 and 5500 or 21.12 to run the 589 and 6600. Any suggestions or am I looking for a software fix in the miner code to address this card configuration to work??
Thank you

**Comment by jgonzis** [comment]
> Hey guys I’m running a 4gb 5500xt a 8gb rx580 and I added a 8gb rx6600. No issues with the 5500 and 580 with drivers 21.5 but that driver set will not recognize the 6600 card. To get that card running I need 21.12.1 for amd to recognize all 3 cards but it kicks the 5500 out in the mining software. It’s either 21.5 and run the 580 and 5500 or 21.12 to run the 589 and 6600. Any suggestions or am I looking for a software fix in the miner code to address this card configuration to work?? Thank you

6600 should run with older drivers.... could you try 21.7 or 21.8 or 9M

**Comment by Blz14me** [comment]
I will try these drivers tonight and report back thank you for something to try

**Comment by Blz14me** [comment]
Well mixed results but everything ended wit one card or another not being recognized by windows , amd and the miner. The oldest avail drivers I can find that will let amd recognize the 6600 is 21.12.1 and I’m back to everything running except the 5500 I’m at a loss why the 580 has no issues  but the 5500xt does. If it’s any help the added card that required a driver change to be made is a power color hellhound amd rx6600. Hopefully the next release of lolminer will have some support for the new amd drivers that they seem to change faster than there underwear

**Comment by Malique2** [comment]
I eventually gave up. Went to Teamredminer and haven't looked back.
    On Wednesday, December 15, 2021, 10:04:24 PM EST, Blz14me ***@***.***> wrote:  
 
 


Well mixed results but everything ended wit one card or another not being recognized by windows , amd and the miner. The oldest avail drivers I can find that will let amd recognize the 6600 is 21.12.1 and I’m back to everything running except the 5500 I’m at a loss why the 580 has no issues but the 5500xt does. If it’s any help the added card that required a driver change to be made is a power color hellhound amd rx6600. Hopefully the next release of lolminer will have some support for the new amd drivers that they seem to change faster than there underwear

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Blz14me** [comment]
Thanks for the tip trm reads all cards without issue problem solved thank you
