### ISSUE TITLE
individual gpu control

### ISSUE THREAD

**Issue by stevedidienne** [Lolliedieb/lolMiner-releases#810]
Hello,
I have a mixed rig (3080 non lhr, 3090 and 3070 ti) and I would like to configure each gpu and see the info.
  os: w10
driver 472.12
can you help me place the right orders please.

: W10
for / f "tokens = 1-4 delims = /" %% i in ("% date%") do (
set dow = %% i
set month = %% j
set day = %% k
set year = %% l
)
for / f "tokens = 1-3 delims =:" %% i in ("% time%") do (
set hour = %% i
set min = %% j
set sec = %% k
)
set datestr =% year %% month %% day% _% hour %% min%

"% MyVariable%" --algo ETHASH --pool! POOL! --user! WALLET! --log = on --logfile = eth_% datestr% .log --watchdog exit! EXTRAPARAMETERS! --statsformat "lhrinfo"
if% ERRORLEVEL% == 42 (
timeout 10
goto W10
)
goto END

**Comment by jgonzis** [comment]
No problem or feedback... close issue

**Comment by NPC-lab-python** [comment]
It's ok for me. thank you
