### ISSUE TITLE
RX5500 4GB

### ISSUE THREAD

**Issue by Jonasuke59** [Lolliedieb/lolMiner-releases#813]
hello,

i have try Zombie mode with my RX5500 XT 4GB but down work.

its unsupported for moment or its me?

Best regards

**Comment by Malique2** [comment]
My 5500xts w 8gb havent been working with the last 2 releases.

**Comment by jgonzis** [comment]
> My 5500xts w 8gb havent been working with the last 2 releases.

Windows? Did you update AMD Drivers?  With 21.5.1 seems to be last AMD Driver on Windows

**Comment by Malique2** [comment]
Yes. Fully updated to latest release and still getting false for the 5500xt. So not sure what is going on at this point. Tried on 5 different 5500xts in 2 different machines. Everything was fine up until the last couple of releases.

**Comment by jgonzis** [comment]
> Yes. Fully updated to latest release and still getting false for the 5500xt. So not sure what is going on at this point. Tried on 5 different 5500xts in 2 different machines. Everything was fine up until the last couple of releases.
> 
> My 6600xt works fine in the same rig though. Ugh.

5500 seems no need old drivers AMD 21.5

**Comment by jgonzis** [comment]
No problem or feedback... close issue
