### ISSUE TITLE
3060无法稳定运行

### ISSUE THREAD

**Issue by jia7388289** [Lolliedieb/lolMiner-releases#818]
3060v2经过几个小时后算力会逐渐降低 如何才能稳定的保持算力？ 在最新hive os 470.74下

**Comment by jgonzis** [comment]
求你了，就用固定核心工作吧。

核心1500 
你想要的内存
PL 130

下去是锁定在GPU上。

**Comment by ROCKET0101** [comment]
Bro my rig is working properly but in hive os show offline some time show data loading retry.. and i am using nbminer that time i do not know but is this 
![Screenshot 2021-11-03 175121](https://user-images.githubusercontent.com/92781808/140059123-ce943bf3-d3ae-44b3-8fca-76ad9dedd7db.png)

**Comment by jgonzis** [comment]
No problem or feedback... close issue
