### ISSUE TITLE
GPU 0: insufficient memory for DAG epoch 385.

### ISSUE THREAD

**Issue by yahia20** [Lolliedieb/lolMiner-releases#82]
I get this error when trying to benchmark shouldn't it turn to zombie mode?

**Comment by Lolliedieb** [comment]
It should - what card is this?

**Comment by yahia20** [comment]
I have 5500xt on linux

**Comment by yahia20** [comment]
since you didn't add zombie mode on navi cards it's better for me to just wait till they decrease the dag for etc as ethereum will move to proof of stake thanks anyways

**Comment by Lolliedieb** [comment]
See 1.13 / 1.14 ... they added Zombie mode for Navi :)

Am Di., 10. Nov. 2020 um 15:44 Uhr schrieb yahia20 <notifications@github.com

**Comment by yahia20** [comment]
thanks
