### ISSUE TITLE
Gigabyte 3080TI 0-60Mh\s

### ISSUE THREAD

**Issue by NucleaR-II** [Lolliedieb/lolMiner-releases#823]
2 Gigabyte 3080TI of mine don't manage to get above 60Mh/s, it immediately gets an LHR lock.

LolMiner Version 1.33
HiveOS Version: 0.6-210@211021 
Nvidia Driver: 470.74

Core 0, Mem 0, Power 287 FAN: auto but they are at 100

Connected to: xxxxxxx 
Uptime: 0h 20m 2s 
                            GPU 5        GPU 6     Total
Name:                  RTX 3080Ti   RTX 3080Ti       Rig
LHR Locks:                     28           15          
--lhrtune:                   -189           36          
Speed (mh/s):               31.85        37.81     69.66
Pool (mh/s):                44.20        34.00     78.19
Shares (A/S/Hw):           68/0/0       52/1/0   120/1/0
Best Share:                 31.5G        30.6G     31.5G
Power (W):                  182.9        234.7     417.5
Efficiency (mh/s/W):        0.174        0.161     0.166
Temp (deg C):                  59           59          
Fan Speed (%):                 98           94          
--------------------------------------------- 
Average speed (10s): 32.44mh/s | 67.92mh/s Total: 100.36 mh/s                                                                                        
New job received: 00000000fd459659 Epoch: 449                                                                                                        
New job received: 00000000fd45965a Epoch: 449                                                                                                        
GPU 6: Found a share of difficulty 0.81G                                                                                                             
New job received: 00000000fd45965b Epoch: 449                                                                                                        
GPU 6: Share accepted (105 ms)                                                                                                                       
GPU 6: Detected lock during calibration. Maybe your --lhrtune value was too high. Unlocking card and lowering value...
GPU 5: Found a share of difficulty 0.72G                                                                                                             
GPU 5: Share accepted (19 ms)                                                                                                                        
New job received: 00000000fd45965c Epoch: 449   

.......

                            GPU 5        GPU 6     Total
Name:                  RTX 3080Ti   RTX 3080Ti       Rig
LHR Locks:                     44           22          
--lhrtune:                   -205         -157          
Speed (mh/s):               34.60        34.77     69.37
Pool (mh/s):                37.98        31.47     69.45
Shares (A/S/Hw):           98/0/0       83/1/0   181/1/0
Best Share:                 31.5G        30.6G     31.5G
Power (W):                  189.7        183.4     373.1
Efficiency (mh/s/W):        0.182        0.189     0.185
Temp (deg C):                  56           53          
Fan Speed (%):                 99           99          
--------------------------------------------- 
Average speed (10s): 53.77mh/s | 42.33mh/s Total: 96.10 mh/s                                                                                         
New job received: 00000000fd459723 Epoch: 449                                                                                                        
New job received: 00000000fd459724 Epoch: 449                                                                                                        
New job received: 00000000fd459725 Epoch: 449                                                                                                        
New job received: 00000000fd459726 Epoch: 449                                                                                                        
GPU 5: applying new LHR parameters... 
Average speed (10s): 28.70mh/s | 0.00mh/s Total: 28.70 mh/s                                                                                          
New job received: 00000000fd459727 Epoch: 449                                                                                                        
GPU 5: Found a share of difficulty 0.79G                                                                                                             
GPU 5: Share accepted (19 ms)                                                                                                                        
GPU 5: Found a share of difficulty 1.44G                                                                                                             
GPU 5: Share accepted (18 ms)                                                                                                                        
GPU 6: applying new LHR parameters... 

.....

GPU 5: Share accepted (20 ms)                                                                                                                        
GPU 5: detected mining lock. Unlocking & reducing --lhrtune parameter... 
GPU 5: GPU will be paused to make sure it is unlocked... 
New job received: 00000000fd459735 Epoch: 449                                                                                                        
New job received: 00000000fd459736 Epoch: 449                                                                                                        
New job received: 00000000fd459737 Epoch: 449                                                                                                        
GPU 6: detected mining lock. Unlocking & reducing --lhrtune parameter... 
GPU 6: GPU will be paused to make sure it is unlocked... 
New job received: 00000000fd459738 Epoch: 449                                                                                                        
Average speed (10s): 53.19mh/s | 61.22mh/s Total: 114.41 mh/s                                                                                        
New job received: 00000000fd459739 Epoch: 449                                                                                                        
Average speed (10s): 1.77mh/s | 0.00mh/s Total: 1.77 mh/s                                                                                            
New job received: 00000000fd45973a Epoch: 449                                                                                                        
GPU 5: applying new LHR parameters... 
GPU 6: applying new LHR parameters... 
New job received: 00000000fd45973b Epoch: 449                                                                                                        
Average speed (10s): 68.42mh/s | 48.37mh/s Total: 116.79 mh/s                                                                                        
GPU 6: Found a share of difficulty 2.98G                                                                                                             
GPU 6: Share accepted (137 ms)                                                                                                                       
New job received: 00000000fd45973c Epoch: 449                                                                                                        
GPU 6: Found a share of difficulty 0.59G                                                                                                             
GPU 6: Share accepted (19 ms)                                                                                                                        
Average speed (10s): 52.69mh/s | 64.88mh/s Total: 117.57 mh/s                                                                                        
GPU 5: detected mining lock. Unlocking & reducing --lhrtune parameter... 
GPU 5: GPU will be paused to make sure it is unlocked... 
New job received: 00000000fd45973d Epoch: 449                                                                                                        
GPU 6: detected mining lock. Unlocking & reducing --lhrtune parameter... 
GPU 6: GPU will be paused to make sure it is unlocked... 

is this maybe a new LHR lock or are the pads to blame ? or have I just got 2 bad cards ? Does anyone have a hint for me that I get to 85Mh / s ?

THANKS

**Comment by jgonzis** [comment]
No problem or feedback... close issue
