### ISSUE TITLE
api not working?

### ISSUE THREAD

**Issue by m1losh** [Lolliedieb/lolMiner-releases#83]
Hi,
congrats on your miner, seems like it has a good potential - wish you all the best.
I'm aware that your wiki/help/readme is incomplete, but can you shed some light on lolMiner's api?

I get 'file not found' after defining --apiport (say, to 9000) - maybe I'm missing some dependencies - or api isn't working at all yet?
Thanks.

**Comment by UselessGuru** [comment]
> api isn't working at all yet?

api is working well. For PowerShell code see here:

https://github.com/Minerx117/NemosMiner/blob/testing/Includes/APIs/lolMiner.ps1

**Comment by m1losh** [comment]
> > api isn't working at all yet?
> 
> api is working well. For PowerShell code see here:
> 
> https://github.com/Minerx117/NemosMiner/blob/testing/Includes/APIs/lolMiner.ps1

Ah, so it's [IP]:[PORT]/summary - thanks mate. :)
