### ISSUE TITLE
HOW TO MAKE FIX INVALID SHARES IN HIVE OS PLEASE HELP!!!!!!! SEE THIS SCREENSHOT..

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#832]
![Capture](https://user-images.githubusercontent.com/92781808/139291589-45cd1085-55e1-4ec9-b526-fb8548551a74.PNG)

**Comment by ROCKET0101** [comment]
> > > Only 2 errors is not too much depending on the time, the errors appear normally for an excess of Memory OC or degradation of the memory after use of time. LolMiner repair DAG on load, when the memory gives error but it was only until EPOCH 449. But now that is solved with the 1.34a
> > > That invalids are for an excess of Memory OC, the repair of the DAG for that high OC Memory were implemented until epoch 450. Epoch 450 arrived yesterday and the update 1.34a was done some hours later. In HiveOS you only need to update HiveOS to have 1.34a
> > > Remember that is also an advise that it could be that GPU it has too much memory if that start to go up in big quantities, a pair in long time is really acceptable
> > 
> > Ok Bro. what i am doing i also update hive os to 1.34a this is normal or not .
> 
> Yes in HiveOS is it yet and I think in nearly all of other OS too

Bro this card is good mining or not please tell me bro![IMG-20211029-WA0014.jpeg](https://user-images.githubusercontent.com/92781808/139523025-4683d00b-07b2-4e9d-a9a7-a573ed05b366.jpeg)

**Comment by jgonzis** [comment]
Yes, you can mine with a 3060TI...

**Comment by ROCKET0101** [comment]
> Yes, you can mine with a 3060TI...

bro this card is asus 3060ti mini version . this will be give any heating problem or not ..please tell me

**Comment by jgonzis** [comment]
> > Yes, you can mine with a 3060TI...
> 
> bro this card is asus 3060ti mini version . this will be give any heating problem or not in future...please tell me and this is my overclock setting is perfect or not... i am using NB MINER ![Capture](https://user-images.githubusercontent.com/92781808/139524094-f639dacc-5a4a-47fe-a173-98fbca9d1ea7.PNG) g

Use theses OC:
3060 Core from 100 to 1500 you will reduce 20W on each GPU minimum.

3060TI Core from 0 to 1410 - Memory Hynix will normally crash at that speed... I recommend you not to pass from 1800... you could be lucky with that but in my experience all end with problems over 1800

**Comment by ROCKET0101** [comment]
> > > Yes, you can mine with a 3060TI...
> > 
> > 
> > bro this card is asus 3060ti mini version . this will be give any heating problem or not in future...please tell me and this is my overclock setting is perfect or not... i am using NB MINER ![Capture](https://user-images.githubusercontent.com/92781808/139524094-f639dacc-5a4a-47fe-a173-98fbca9d1ea7.PNG) g
> 
> Use theses OC: 3060 Core from 100 to 1500 you will reduce 20W on each GPU minimum.
> 
> 3060TI Core from 0 to 1410 - Memory Hynix will normally crash at that speed... I recommend you not to pass from 1800... you could be lucky with that but in my experience all end with problems over 1800

BRO THIS SETTING IS NOT GOOD FOR MY RIG /
