### ISSUE TITLE
after Update 3070 non LHR behaves like a 3070 LHR

### ISSUE THREAD

**Issue by VKrieger** [Lolliedieb/lolMiner-releases#833]
In Windows 11 and now in Windows 10 after the 12. Oktober 2021 – KB5006670 update my Hashrate is only about 30 and the Memory speed is locked to 5000MHZ.

I Use lolminer 1.34
my Setting is 

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%" --lhrtune off --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! 
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
"%MyVariable%" --lhrtune off --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause

**Comment by jgonzis** [comment]
> In Windows 11 and now in Windows 10 after the 12. Oktober 2021 – KB5006670 update my Hashrate is only about 30 and the Memory speed is locked to 5000MHZ.
> 
> I Use lolminer 1.34 my Setting is
> 
> :infolder set MyVariable=%CD%\lolMiner.exe
> 
> :WindowsVer echo "Running lolMiner from %MyVariable%" for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j if "%version%" == "10.0" goto W10 goto OtherW
> 
> :W10 "%MyVariable%" --lhrtune off --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! if %ERRORLEVEL% == 42 ( timeout 10 goto W10 ) goto END
> 
> :OtherW "%MyVariable%" --lhrtune off --algo ETHASH --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS! --nocolor if %ERRORLEVEL% == 42 ( timeout 10 goto OtherW )
> 
> :END pause

One good miner comment me to try to go to 472 Nvidia Driver. That could probably solve your problem too

**Comment by VKrieger** [comment]
opening snipping tool solved the problem

**Comment by jgonzis** [comment]
With new Nvidia Driver no more problems
