### ISSUE TITLE
Bro this card is good for mining or Not please tell me any body..

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#837]
![IMG-20211029-WA0014.jpeg](https://user-images.githubusercontent.com/92781808/139469021-6bb0aea2-cff7-445b-a32d-fa73d3840460.jpeg)

**Comment by jgonzis** [comment]
That is not for comment GPUs for that there are lot of other forums. That is a RTX 3060 and it will go with LHR or not LHR
