### ISSUE TITLE
Miner Stuck at "New Job Received"

### ISSUE THREAD

**Issue by bravokun** [Lolliedieb/lolMiner-releases#839]
I get to the point where it starts mining and then just stops after the prompt of "New Job Recieved" and the batch file lingers indefinitely on that line on version 1.34 in Windows 11.

**It does not continue after this line.**

I have not made any edits to the batch file other than setting the pool and wallet address. I have also ensured that any antivirus software is blocking the miner from running. I have also expanded my virtual memory. Currently on the latest nvidia drivers. 

![image](https://user-images.githubusercontent.com/78499072/139665802-62f37997-b859-4e37-a01c-d2cb765a97d4.png)

Sometimes I can get to this part of the process, but ultimately just stops here. Never continues mining after this.

![image](https://user-images.githubusercontent.com/78499072/139668062-02c3bc4e-9eee-43ab-bc80-7594ca1617c5.png)

**Comment by jgonzis** [comment]
Could you try to increase Virtual Disk?. Or try Nvidia Drivers 472.12

It could be also something with Windows 11, but try 1st other options

**Comment by bravokun** [comment]
> Could you try to increase Virtual Disk?. Or try Nvidia Drivers 472.12
> 
> It could be also something with Windows 11, but try 1st other options

I have tried to increase the virtual disk to no avail. I have also tried Nvidia Drivers 472.12 which seems to work.
