### ISSUE TITLE
GPU 0: error when allocating memory or building DAG. Disabling card. | 0.00 mh/s

### ISSUE THREAD

**Issue by wuniversales** [Lolliedieb/lolMiner-releases#842]
Error: `"GPU 0: error when allocating memory or building DAG. Disabling card. "`

![image](https://user-images.githubusercontent.com/48658161/140035288-f7575c06-56ff-421f-9369-64531f2eef4e.png)

**Comment by pdieppa** [comment]
Looks like that card does not have enough memory to mine ETH.

**Comment by jgonzis** [comment]
Please increase virtual memory in Windows.

https://www.windowscentral.com/how-change-virtual-memory-size-windows-10

**Comment by wuniversales** [comment]
I have linux, manjaro KDE...
