### ISSUE TITLE
Bro my rig is working properly but in hive os show offline some time show data loading retry.. and i am using nbminer that time i do not know but is this .please help bro!!!!

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#843]
![Screenshot 2021-11-03 175121](https://user-images.githubusercontent.com/92781808/140061031-6cadf1f3-8948-400e-9023-8ccfb0790450.png)

**Comment by jgonzis** [comment]
That was hiveos problem we have it lot of use the other day
