### ISSUE TITLE
[SMOS] Console colors?

### ISSUE THREAD

**Issue by onetaped** [Lolliedieb/lolMiner-releases#847]
Hi, 
I've searched in wiki and everywhere on Google but couldn't find if lolMiner supports colored stats in console. I've switched from nb to lolMiner 1.35 but I'd like to have colored logs like I had on nb.
Plain white just looks ugly to me.

If such feature does not exist, I'd like to suggest another param e.g. --infoColor, --statsColor, --errorColor.

Keep up the great work and thanks in advance!

Cheers.

**Comment by jgonzis** [comment]
> Hi, I've searched in wiki and everywhere on Google but couldn't find if lolMiner supports colored stats in console. I've switched from nb to lolMiner 1.35 but I'd like to have colored logs like I had on nb. Plain white just looks ugly to me.
> 
> If such feature does not exist, I'd like to suggest another param e.g. --infoColor, --statsColor, --errorColor.
> 
> Keep up the great work and thanks in advance!
> 
> Cheers.

Could you try --basecolor parameter in the config line?

**Comment by onetaped** [comment]
> > Hi, I've searched in wiki and everywhere on Google but couldn't find if lolMiner supports colored stats in console. I've switched from nb to lolMiner 1.35 but I'd like to have colored logs like I had on nb. Plain white just looks ugly to me.
> > If such feature does not exist, I'd like to suggest another param e.g. --infoColor, --statsColor, --errorColor.
> > Keep up the great work and thanks in advance!
> > Cheers.
> 
> Could you try --basecolor parameter in the config line?

That works, thanks!
