### ISSUE TITLE
1.33 vs 1.34 solver diffs

### ISSUE THREAD

**Issue by wheelpharaoh** [Lolliedieb/lolMiner-releases#848]
> Ethash: Added option to use the version 1.33 semi-unlocker style - this was more performant for some GDDR6X cards. Use --lhrtune xauto to activate the 1.33 solver style auto tuning and use --lhrtune x to set a predetermined tune value. The 1.33 style solver can be mixed with 1.34+ style solvers by using a comma separated list of values.

which model/sub-series of cards are ideal for testing the differences with this parameter?

**Comment by jgonzis** [comment]
> > Ethash: Added option to use the version 1.33 semi-unlocker style - this was more performant for some GDDR6X cards. Use --lhrtune xauto to activate the 1.33 solver style auto tuning and use --lhrtune x to set a predetermined tune value. The 1.33 style solver can be mixed with 1.34+ style solvers by using a comma separated list of values.
> 
> which model/sub-series of cards are ideal for testing the differences with this parameter?

It uses 2 different ways of LHR... for 1.35 just test both and decide:

--lhrtune auto
--lhrtune xauto

It is only usefull for the GDDR6x gpu, 3070ti, 3080 and 3080TI.

**Comment by jgonzis** [comment]
With new Nvidia Drivers all done
