### ISSUE TITLE
DAG gen on 4G cards running for over an hour, still not generated

### ISSUE THREAD

**Issue by bruhmoment998** [Lolliedieb/lolMiner-releases#86]
I have let the mining program run for over an hour to try to get the dag to generate. I am trying to mine etc with the included batch file "mine_ETC_4G.BAT" I have replaced the stock pool with ethermine, and the wallet details are mine.

**Comment by Lolliedieb** [comment]
Then you have a too high value for --4g-alloc-size . Try to start with a lower value, e.g. 4000 and then step slowly up until it gets slow. Once so, go one step back. See the 4G_Windows_Readme.txt (you might need to open this in Wordpad to see proper line breaks)
