### ISSUE TITLE
All devices deselected or failed compatiblity check. Closing lolMinerPresione una tecla para continuar . . .

### ISSUE THREAD

**Issue by Arnold262001** [Lolliedieb/lolMiner-releases#860]
![error LOLMINER](https://user-images.githubusercontent.com/94386704/141814312-1f2c6777-c8a4-40c6-8b79-438271dd2802.PNG)
GPU:  Intel(R) Iris(R) Plus Graphics

**Comment by jgonzis** [comment]
You need a dedicated GPU to mine. You cannot use iGPU of your CPU.

**Comment by Arnold262001** [comment]
ok, thank u
