### ISSUE TITLE
RX 5500 XT 8GB GRAPHIC CARD

### ISSUE THREAD

**Issue by Zalimroque** [Lolliedieb/lolMiner-releases#861]
My video card is 8gb, but lolminer-eth is using 4gb bytes when digging, how can i increase it from 4gb to 8gb

<img width="672" alt="123124" src="https://user-images.githubusercontent.com/80879478/142153339-52303b4c-7c59-4ae7-9f26-336c935961c2.PNG">

**Comment by jgonzis** [comment]
> My video card is 8gb, but lolminer-eth is using 4gb bytes when digging, how can i increase it from 4gb to 8gb
> 
> <img alt="123124" width="672" src="https://user-images.githubusercontent.com/80879478/142153339-52303b4c-7c59-4ae7-9f26-336c935961c2.PNG">

It is only getting 4Gb because it the actual size of the DAG of Ethereum, that increase in each EPOCH change... around each 4-5 days
