### ISSUE TITLE
LHR broken

### ISSUE THREAD

**Issue by mina18767** [Lolliedieb/lolMiner-releases#867]
![Снимок](https://user-images.githubusercontent.com/94790371/142764269-0f8787d7-2616-49dc-b774-e44269bc25d5.PNG)

**Comment by amerkocan** [comment]
How?

**Comment by mina18767** [comment]
> How?

Just update miner 1.36a, and reboot computer any times, p0 in Nvidia profile inspector, and run mining,

**Comment by jgonzis** [comment]
> Just update miner 1.36a, and reboot computer any times, p0 in Nvidia profile inspector, and run mining,

Could you share your Core Clock Curve... Really interesting :-)

**Comment by amerkocan** [comment]
Do a youtube video on it @mina18767

**Comment by mina18767** [comment]
![image](https://user-images.githubusercontent.com/94790371/142803707-dfaeff19-f23a-4189-9a5d-cec0e5e46927.png)
really want to help broke lhr at all, want to contact with developer, to transfer data on my situation

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/94790371/142803707-dfaeff19-f23a-4189-9a5d-cec0e5e46927.png) really want to help broke lhr at all, want to contact with developer, to transfer data on my situation

Contact him in the Telegram group, is the faster way!!

**Comment by sasayagoodtodrink12** [comment]
Is this situation happened in other LHR's cases?

**Comment by zulu1905** [comment]
i tried same curve and setup pstate to p0 but it did not work for me :((

**Comment by jomual0** [comment]
> LHR broken here too. It starts with 75Mh and after 1 minute turns to 52 Mh

Do you have a special parameter in the bat file?

**Comment by jgonzis** [comment]
New Nvidia Drivers should solve that problem. No more Feedback
