### ISSUE TITLE
how to fix this issue please help see this photo!!!!

### ISSUE THREAD

**Issue by ROCKET0101** [Lolliedieb/lolMiner-releases#868]
![WhatsApp Image 2021-11-21 at 9 58 35 PM](https://user-images.githubusercontent.com/92781808/142771342-2d748fc6-07c8-40a0-8b31-790deaa9e0c7.jpeg)

**Comment by jgonzis** [comment]
> ![WhatsApp Image 2021-11-21 at 9 58 35 PM](https://user-images.githubusercontent.com/92781808/142771342-2d748fc6-07c8-40a0-8b31-790deaa9e0c7.jpeg)

Nice that people of others miners come here to find the solution... check your internet or prove other miner :-)
