### ISSUE TITLE
lolminer 1.13 segfault

### ISSUE THREAD

**Issue by adamwelsh** [Lolliedieb/lolMiner-releases#87]
Could I get help with this issue? I have tried updating to new drivers and no dice.

Ubuntu 20.04
Nvidia 450 Drivers

Setup Miner...
 Device 0:
    Name:    GeForce GTX 1050 Ti
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  4040 MByte
Problem in building kernel
    Active:  false (OpenCL init failure: Build program failure)
 Device 1:
    Name:    Intel(R) HD Graphics IvyBridge GT2
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Memory:  2048 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to eth.2miners.com:2020 (TLS disabled)
Set Ethash stratum mode: EthereumStratum/1.0.0
Subscribed to stratum server 
Authorized worker: 0xe4f6a6a7f11771f5d706bbbfd4986b00fa210e2d.lolMinerWorker
New target received: 0000000080008206 (Diff 1.99997)
New job received: 78b4 Epoch: 374
./mine_eth_4G.sh: line 16: 13784 Segmentation fault      (core dumped) ./lolMiner --algo ETHASH --pool $POOL --user $WALLET $@ --keepfree 16 --4g-alloc-size 4000

**Comment by Lolliedieb** [comment]
Fixed with 1.14

Also Zombie mode introduced for 4G Nvidia cards with the new release
