### ISSUE TITLE
Lost connection to stratum server eth.f2pool.com:6688 or server not reachable. 

### ISSUE THREAD

**Issue by xujiameng** [Lolliedieb/lolMiner-releases#870]
I have two RTX3090. They had been working normally for nearly two months before yesterday, but it suddenly showed yesterday

“Connecting to pool...
Lost connection to stratum server eth.f2pool.com:6688 or server not reachable.
Trying to connect in 1 second”

I haven't changed any code, and “Ping eth.f2pool.com” works normally

64 bits from 124.236.16.55 (124.236.16.55): ICMP_ Seq = 1 TTL = 46 time = 23.3 MS
64 bits from 124.236.16.55 (124.236.16.55): ICMP_ Seq = 2 TTL = 46 time = 40.0 MS
64 bits from 124.236.16.55 (124.236.16.55): ICMP_ Seq = 3 TTL = 46 time = 24.0 MS
64 bits from 124.236.16.55 (124.236.16.55): ICMP_ Seq = 4 TTL = 46 time = 31.0 MS
64 bits from 124.236.16.55 (124.236.16.55): ICMP_ Seq = 5 TTL = 46 time = 27.8 MS
64 bits from 124.236.16.55 (124.236.16.55): ICMP_ Seq = 6 TTL = 46 time = 33.6 MS

How should I solve this problem?

**Comment by snow-tyan** [comment]
鱼池昨晚不是凉了嘛，都打不开网页
---
试试备用地址eth-bakeup.f2pool.com:6688
你还能ping通，贴吧老哥都ping不通，dns被污染，ping返回本地回环

**Comment by xujiameng** [comment]
> 鱼池昨晚不是凉了嘛，都打不开网页
> 
> 试试备用地址eth-backup.f2pool.com:6688 你还能ping通，贴吧老哥都ping不通，dns被污染，ping返回本地回环

我是有两台机器来着，两个3090的机器已经停了两天了；另外一台是两块tesla P4在鱼池显示还有收益。我还以为是网络设置有问题。

**Comment by jgonzis** [comment]
China Restriction... 😶

Try other pools please

**Comment by jgonzis** [comment]
No more Feedback
