### ISSUE TITLE
lolMiner.exe --list-devices , RX570 and RX580 not detected

### ISSUE THREAD

**Issue by IordX** [Lolliedieb/lolMiner-releases#871]
title 
other miners working just fine , just wanted to try lolMiner and it can't see any AMD card , tested 3 drivers 
last version not working too , I am on 30.0.13037.1003 , Adrenalin Release 21.11.3 , Internal Driver 21.30.37.01 , wtf they have so many names for same driver

**Comment by jgonzis** [comment]
> title other miners working just fine , just wanted to try lolMiner and it can't see any AMD card , tested 3 drivers last version not working too , I am on 30.0.13037.1003 , Adrenalin Release 21.11.3 , Internal Driver 21.30.37.01 , wtf they have so many names for same driver

Could you try an older version drivers please?. That's the problem...

**Comment by jgonzis** [comment]
1.62 has solved that problem.
