### ISSUE TITLE
when lolminer wroking，process try connect to a port 12020，why？ 

### ISSUE THREAD

**Issue by zhiqsu** [Lolliedieb/lolMiner-releases#872]
当lolminer工作时，除了连接 pool 的端口外，还在尝试连接一个 12020的端口，这个端口对应的主机不固定，总是在变，见截图；从tcp状态中发现，连接没有成功，只是发了 syn 同步报文，没有收到对应的响应； 这个 12020端口是干嘛的？ 有什么用？
![image](https://user-images.githubusercontent.com/18306990/143809984-f70cd05d-c33f-4cc7-bd1f-c74bba162913.png)

**Comment by jgonzis** [comment]
It is Fee connection.

**Comment by snow-tyan** [comment]
@jgonzis Hey, jgonzis. Thx for lolMiner. My 4x3080 speed always fluctuates up and down at 4x60mh / s. Is this normal speed, or do I need to set any parameters? 
Ubuntu 18.04
Cuda 11.1

**Comment by jgonzis** [comment]
> @jgonzis Hey, jgonzis. Thx for lolMiner. My 4x3080 speed always fluctuates up and down at 4x60mh / s. Is this normal speed, or do I need to set any parameters? I check the device id, this seems to be LHR...
> 
> ```
> Device Id                         : 0x221610DE
> ```

Are you using 1.37? 

Could you send a Picture please?.

Many thanks in advance

**Comment by snow-tyan** [comment]
> 

I am using 1.36a. I'll try 1.37 and send picuture a few hours later

**Comment by snow-tyan** [comment]
> > @jgonzis Hey, jgonzis. Thx for lolMiner. My 4x3080 speed always fluctuates up and down at 4x60mh / s. Is this normal speed, or do I need to set any parameters? I check the device id, this seems to be LHR...
> > ```
> > Device Id                         : 0x221610DE
> > ```
> 
> Are you using 1.37?
> 
> Could you send a Picture please?.
> 
> Many thanks in advance

I am using 1.36a. I'll try 1.37 and send picuture a few hours later
