### ISSUE TITLE
Lolminer 1.37 many invalid share

### ISSUE THREAD

**Issue by Ricco59163** [Lolliedieb/lolMiner-releases#877]
Hi,

I always use lolminer for my 3060v1 , but now with 1.37 version , i have many reject share . ( driver460.39)
i downgrade to 1.36a and no probléme now

thank for develloper

**Comment by jgonzis** [comment]
Could you try new 1.38...Changed LHR kernel defaults for RTX 3060 and RTX 3070, because the default ones had an issue with defect shares at high oc.

**Comment by jgonzis** [comment]
With new Nvidia Drivers that should be solved. No more Feedback
