### ISSUE TITLE
lolminer 1.38 - LHR mode(s) does not work at all on RTX 3080 LHR v2

### ISSUE THREAD

**Issue by spajdrEX** [Lolliedieb/lolMiner-releases#879]
on **LHR RTX 3080 V2**
--mode LHR2 - keep getting locked every minute - GPU on 1050Mhz (even if it's not needed here to be this low on GPU freq)
--mode LHRLP - keep getting locked every minute - GPU on 1050Mhz
--lhrtune -22.8 | -24.2 | -25.6 | -27 | -28.4 | -50 | -100

Driver 496.98

**Comment by jgonzis** [comment]
> on **LHR RTX 3080 V2** --mode LHR2 - keep getting locked every minute - GPU on 1050Mhz (even if it's not needed here to be this low on GPU freq) --mode LHRLP - keep getting locked every minute - GPU on 1050Mhz --lhrtune -22.8 | -24.2 | -25.6 | -27 | -28.4 | -50 | -100
> 
> Driver 496.98

Lastest version 1.38 doesn't use anymore the mode... it is all automatic. Could you try older Nvidia Version too? It seems newer version are locking it.

**Comment by spajdrEX** [comment]
Switched to Driver 471.41. Removed --mode and --lhrtune, does not make any difference, still locking every minute or less.

**Comment by jgonzis** [comment]
> Switched to Driver 471.41. Removed --mode and --lhrtune, does not make any difference, still locking every minute or less.

Could you see the Memory Temp, it could be that then the problem. You can do it with GPUZ .just to discard a Memory Throlling

**Comment by spajdrEX** [comment]
> > Switched to Driver 471.41. Removed --mode and --lhrtune, does not make any difference, still locking every minute or less.
> 
> Could you see the Memory Temp, it could be that then the problem. You can do it with GPUZ .just to discard a Memory Throlling

Memory temps are hovering between 92-96C . It's not that because other miners like T-Rex, NBMiner does not exhibit same issue.

**Comment by jgonzis** [comment]
Could you try parameter --lhrtune  xauto

**Comment by cosdal** [comment]
> > > Switched to Driver 471.41. Removed --mode and --lhrtune, does not make any difference, still locking every minute or less.
> > 
> > 
> > Could you see the Memory Temp, it could be that then the problem. You can do it with GPUZ .just to discard a Memory Throlling
> 
> Memory temps are hovering between 92-96C . It's not that because other miners like T-Rex, NBMiner does not exhibit same issue.

try the tool removelhr. Maybe is a solution.

**Comment by jgonzis** [comment]
New Nvidia Drivers should solve that problems.No more Feedback
