### ISSUE TITLE
 multi Fiji (FuryX) not working (ETH)

### ISSUE THREAD

**Issue by jaschx** [Lolliedieb/lolMiner-releases#88]
Hi, 
i know Fiji are old Cards, but maybe its nothing big.

When i use one FuryX, its working pushing 33MHs+ on ETH.
If i use multiple Cards, only one Card is working.
Its the Card which Dag is finished first(its not every Time the same Card) , all others are under 1MHs.
This also happens in Zombie Mode, only one is full Speed(29-30).(testet all Kind of Settings memfree...)
(for Testing i added one Polaris to the Mix, working fine together with the Fury which Dag finished first.

With TRM Miner all Cards working (but lol is much faster on Fiji).

wbr

**Comment by Lolliedieb** [comment]
Interesting... What OS & driver your running on? I sadly do not have multiple Fiji's to test this :(

**Comment by bela3333** [comment]
I also have a problem on hiveos. Only one card works.
5pcs amd r9 290

**Comment by joker2a** [comment]
Hello,
I have exactly the same problem, I think my rig (hiveos) 4xFidji is incompatible with lolminer.

**Comment by jgonzis** [comment]
Supported in later lolMiner version
