### ISSUE TITLE
Worker Name not included in API data anymore

### ISSUE THREAD

**Issue by intmech** [Lolliedieb/lolMiner-releases#880]
Previous versions of the API would return both the wallet address and the worker name separated by a period but the latest versions do not.  Was this deliberate?  I had been utilizing the response from the API to extract both the wallet address and the worker name from APIdata/Statrum/CurrentUser.  Is there another method of extracting the workername?  Thanks.

**Comment by jgonzis** [comment]
> Previous versions of the API would return both the wallet address and the worker name separated by a period but the latest versions do not. Was this deliberate? I had been utilizing the response from the API to extract both the wallet address and the worker name from APIdata/Statrum/CurrentUser. Is there another method of extracting the workername? Thanks.

You are completely right.  Sure it will implement an other field to api including the worker name

**Comment by jgonzis** [comment]
That should be solved now. Other way to extract is to check if wallet has a point . to trim from point to the end.
