### ISSUE TITLE
Error lhr 3060 ti 

### ISSUE THREAD

**Issue by K1l3r0** [Lolliedieb/lolMiner-releases#881]
I have a 3060 ti lhr rig to update to the latest nvidia dirver and now no unlocking version of lhr works, error 42 comes out and after a while the miner is exited

**Comment by jgonzis** [comment]
> I have a 3060 ti lhr rig to update to the latest nvidia dirver and now no unlocking version of lhr works, error 42 comes out and after a while the miner is exited

Yes it seems lastest Nvidia Driver 497 are not the best. Could You try with an older version?. And reported if worked?

**Comment by jgonzis** [comment]
No more problem with new Nvidia Drivers. No more Feedback
