### ISSUE TITLE
lolminer  --coin option "flux" is not supported

### ISSUE THREAD

**Issue by ledoze** [Lolliedieb/lolMiner-releases#882]

**Comment by spajdrEX** [comment]
Use MiniZ miner if you use NVIDIA card as it gives highest Sol/S so far.

**Comment by jgonzis** [comment]
> _No description provided._
Flux was developed for AMD GPUs and later opened to Nvidia. Probably yet not the best miner for Nvidia

**Comment by jgonzis** [comment]
Flux full Nvidia Support from 1.58 - No more Feedback
