### ISSUE TITLE
Hashrate suddenly drops 

### ISSUE THREAD

**Issue by Samura777** [Lolliedieb/lolMiner-releases#886]
The hashrate of the whole rig suddenly drops and does'nt restart on its own using the watchdog script. This has been happening frequently on simple mining OS and as well as on Hive OS. Please help me solve this issue. i have attached the screenshot below
Thank you 

![lolminer](https://user-images.githubusercontent.com/95909548/145571657-afbd80ee-9ed0-4a16-891a-a73e4fb4cc29.png)

**Comment by pdieppa** [comment]
What OC settings are you using?

**Comment by Samura777** [comment]
> 
![image](https://user-images.githubusercontent.com/95909548/145777132-198bfe81-581d-488c-9d06-d28739b9330f.png)
im currently using the same OC for gminer. its working well

**Comment by Samura777** [comment]
Hi
im currently using the same OC in gminer. its working well

**Comment by Samura777** [comment]
> What OC settings are you using?

core 1100, mem 1350 , core undervolt 750

**Comment by pdieppa** [comment]
Try these. They are my HiveOS (linux) settings 

![Screenshot_20211214-073036_Hive OS](https://user-images.githubusercontent.com/74556152/145998946-11e382ee-40b3-4126-9b36-13d9e93a7553.jpg)

**Comment by jgonzis** [comment]
> The hashrate of the whole rig suddenly drops and does'nt restart on its own using the watchdog script. This has been happening frequently on simple mining OS and as well as on Hive OS. Please help me solve this issue. i have attached the screenshot below Thank you
> 
> ![lolminer](https://user-images.githubusercontent.com/95909548/145571657-afbd80ee-9ed0-4a16-891a-a73e4fb4cc29.png)

That could be also Internet problem

**Comment by Samura777** [comment]
> Try these. They are my HiveOS (linux) settings
> 
> ![Screenshot_20211214-073036_Hive OS](https://user-images.githubusercontent.com/74556152/145998946-11e382ee-40b3-4126-9b36-13d9e93a7553.jpg)

sure , ill give it a try

**Comment by Samura777** [comment]
> > The hashrate of the whole rig suddenly drops and does'nt restart on its own using the watchdog script. This has been happening frequently on simple mining OS and as well as on Hive OS. Please help me solve this issue. i have attached the screenshot below Thank you
> > ![lolminer](https://user-images.githubusercontent.com/95909548/145571657-afbd80ee-9ed0-4a16-891a-a73e4fb4cc29.png)
> 
> That could be also Internet problem

it could have been internet issue if my other rigs did the same. but all of them are fine. its issue with only this rig

**Comment by jgonzis** [comment]
No more Feedback. That seems a crash in the driver for really low Core Voltage
