### ISSUE TITLE
About DDR5 and DDR5X graphics cards.

### ISSUE THREAD

**Issue by Nicolas-Gong** [Lolliedieb/lolMiner-releases#887]
How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards.
When can lolMiner use the socks5 proxy tunnel?

**Comment by liukaixin007** [comment]
I need an proxy, too?

**Comment by jgonzis** [comment]
> How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards. When can lolMiner use the socks5 proxy tunnel?

At the moment not Memory Cloks optimisation, you need to use 3rd Party Apps

**Comment by Nicolas-Gong** [comment]
> > How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards. When can lolMiner use the socks5 proxy tunnel?
> 
> At the moment not Memory Cloks optimisation, you need to use 3rd Party Apps

Please add proxy, because now the miners in China need it. If you add proxy, more people should always choose your software.

**Comment by jgonzis** [comment]
> > > How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards. When can lolMiner use the socks5 proxy tunnel?
> > 
> > 
> > At the moment not Memory Cloks optimisation, you need to use 3rd Party Apps
> 
> Please add proxy, because now the miners in China need it. If you add proxy, more people should always choose your software.

New DoH doesn't help?.

**Comment by Nicolas-Gong** [comment]
> 

Doh is meaningless because the linked IP access is prohibited. Secondly, the stability of the direct connection IP is very poor, and the stale rate will be very high, usually rising to 20%. It will also carry the problem of invalid rate. Therefore, most people now use the transit server or v2ray SS and SSR proxy to solve the blocking problem.

**Comment by Nicolas-Gong** [comment]
> > > > How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards. When can lolMiner use the socks5 proxy tunnel?
> > > 
> > > 
> > > At the moment not Memory Cloks optimisation, you need to use 3rd Party Apps
> > 
> > 
> > Please add proxy, because now the miners in China need it. If you add proxy, more people should always choose your software.
> 
> New DoH doesn't help?.

Doh is meaningless because the linked IP access is prohibited. Secondly, the stability of the direct connection IP is very poor, and the stale rate will be very high, usually rising to 20%. It will also carry the problem of invalid rate. Therefore, most people now use the transit server or v2ray SS and SSR proxy to solve the blocking problem.

**Comment by Nicolas-Gong** [comment]
> > > > How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards. When can lolMiner use the socks5 proxy tunnel?
> > > 
> > > 
> > > At the moment not Memory Cloks optimisation, you need to use 3rd Party Apps
> > 
> > 
> > Please add proxy, because now the miners in China need it. If you add proxy, more people should always choose your software.
> 
> New DoH doesn't help?.

Hello, it cannot be used when using the socks5 parameter in the latest version 1.39, because the hashrate is always 0. Is it because the mining pool is not connected or caused by other problems? The output log cannot analyze the reason.

**Comment by jgonzis** [comment]
> > > > > How to use pill on GTX 1080 and 1080ti? For example, the -mt parameter function of t-rex is optimized for DDR5 and DDR5 graphics cards. When can lolMiner use the socks5 proxy tunnel?
> > > > 
> > > > 
> > > > At the moment not Memory Cloks optimisation, you need to use 3rd Party Apps
> > > 
> > > 
> > > Please add proxy, because now the miners in China need it. If you add proxy, more people should always choose your software.
> > 
> > 
> > New DoH doesn't help?.
> 
> Hello, it cannot be used when using the socks5 parameter in the latest version 1.39, because the hashrate is always 0. Is it because the mining pool is not connected or caused by other problems? The output log cannot analyze the reason.

could you show your config and the start?

**Comment by Nicolas-Gong** [comment]
> 

![image](https://user-images.githubusercontent.com/23067153/147823653-1cadf586-f25f-47c7-a69c-9af9cc8f9f9d.png)

This is my configuration information in hiveos.

![image](https://user-images.githubusercontent.com/23067153/147823759-efe5a2ed-7ec7-401c-a286-73e2b9120097.png)

This is the execution log when I took a graphics card.
I use the v2ray proxy, and I have no problem using t-rex.

**Comment by jgonzis** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/23067153/147823653-1cadf586-f25f-47c7-a69c-9af9cc8f9f9d.png)
> 
> This is my configuration information in hiveos.
> 
> ![image](https://user-images.githubusercontent.com/23067153/147823759-efe5a2ed-7ec7-401c-a286-73e2b9120097.png)
> 
> This is the execution log when I took a graphics card. I use the v2ray proxy, and I have no problem using t-rex.

have you run the proxy too?.

**Comment by Nicolas-Gong** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23067153/147823653-1cadf586-f25f-47c7-a69c-9af9cc8f9f9d.png)
> > This is my configuration information in hiveos.
> > ![image](https://user-images.githubusercontent.com/23067153/147823759-efe5a2ed-7ec7-401c-a286-73e2b9120097.png)
> > This is the execution log when I took a graphics card. I use the v2ray proxy, and I have no problem using t-rex.
> 
> have you run the proxy too?.

Yes,I guarantee that there is no problem with my poxy, because this machine has just switched back to t-rex and is now running perfectly.

**Comment by cndxpy** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23067153/147823653-1cadf586-f25f-47c7-a69c-9af9cc8f9f9d.png)
> > This is my configuration information in hiveos.
> > ![image](https://user-images.githubusercontent.com/23067153/147823759-efe5a2ed-7ec7-401c-a286-73e2b9120097.png)
> > This is the execution log when I took a graphics card. I use the v2ray proxy, and I have no problem using t-rex.
> 
> have you run the proxy too?.

can you use socks5 now？

**Comment by jgonzis** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/23067153/147823653-1cadf586-f25f-47c7-a69c-9af9cc8f9f9d.png)
> > > This is my configuration information in hiveos.
> > > ![image](https://user-images.githubusercontent.com/23067153/147823759-efe5a2ed-7ec7-401c-a286-73e2b9120097.png)
> > > This is the execution log when I took a graphics card. I use the v2ray proxy, and I have no problem using t-rex.
> > 
> > 
> > have you run the proxy too?.
> 
> can you use socks5 now？

--socks5 arguments
