### ISSUE TITLE
what is this matter??? this is not work :(

### ISSUE THREAD

**Issue by tlswlsgns2** [Lolliedieb/lolMiner-releases#89]
![error](https://user-images.githubusercontent.com/57703799/99444758-00166900-2960-11eb-8973-ebe79171702a.JPG)
![error2](https://user-images.githubusercontent.com/57703799/99444861-1de3ce00-2960-11eb-8751-277108dcb418.JPG)
![error3](https://user-images.githubusercontent.com/57703799/99444870-1fad9180-2960-11eb-8e88-4e9c6ed54612.JPG)

**Comment by Lolliedieb** [comment]
Can you share the GPU you are running? Also did you test the instructions that were printed in the 4G_Windows_Readme.txt? 
There are instructions how to configure it so it starts up on your machine.
