### ISSUE TITLE
Ergo 1.38x no optimizing watt

### ISSUE THREAD

**Issue by dedizones** [Lolliedieb/lolMiner-releases#890]
Hi,

I want try ergo with lolminer but problem:

I am 400/500 w more than nbminer or trex for a less better hashrate too

Could you work on more than optimizing ETH at end of life?

Then seeing the faster block generation would be a plus thank you

**Comment by jgonzis** [comment]
> Hi,
> 
> I want try ergo with lolminer but problem:
> 
> I am 400/500 w more than nbminer or trex for a less better hashrate too
> 
> Could you work on more than optimizing ETH at end of life?
> 
> Then seeing the faster block generation would be a plus thank you

Could you say in which GPUs are you getting that values and also give some extra information?.  Many thanks in advance

**Comment by dedizones** [comment]
Total Farm ERGO: 41 RTX
RTX: 3070,3080 NoLHR and 3070Ti, 3080Ti LHR
Hiveos linux last update
Driver nvidia 470.74
OC: Ccore: 1540 | Mcore 2000 | PL 0 (no pl limited by Ccore)

Trex: 6300w for 7230 Ghs
Nbminer: 6400 For 7186 Ghs
Lolminer: 6720w for 7184 Ghs

other miner
they succeeded in reducing consumption on the ergo, I think there is something to do with you as well.
We could take advantage of the 1.5% fee + electricity optimization

I see on the wall ;)

**Comment by MOCO-MHz** [comment]
@dedizones have you tried overclocking. Unfortunately our software [https://github.com/MOCO-MHz/MOCO](url) has not yet been configured to work with lolminer or egro. Our initial release was with T-rex and ETH
