### ISSUE TITLE
LOLminer 1.38 stuck on "Setup Miner..."

### ISSUE THREAD

**Issue by RaZVaNx17** [Lolliedieb/lolMiner-releases#892]
Hey Guys, 

I have looked everywhere for something to help me fix this issue, but I haven't found anything related to it.No idea whats going on.
I have been running lolminer(1.18) since January just fine. The rig is a Windows10 PC with 8 x XFX RX580 8GB.
Yesterday and the day before it stopped working around 8AM, but a small restart fixed it.
Today on the other hand it won't go beyond the "setup miner" step even in the 1.18 version and also the 1.38.
It seams to be something which stops lolminer.exe from starting
![echo_OFF](https://user-images.githubusercontent.com/96479383/146935259-a2023ca4-43da-4642-a290-88ee2aa6f8b6.jpg)

I also attached another picture with echo turned ON.

![echo_ON](https://user-images.githubusercontent.com/96479383/146935255-6fb9958a-58e5-4141-97ad-dd412f183d79.jpg)

Thanks!

**Comment by maximeCote819** [comment]
Hi, what was the fix after all ? Thanks !

**Comment by RaZVaNx17** [comment]
Hi. I can't say for sure. I ended up, deleting everything, reseting the windows settings, then reinstalling and configuring everything again.
Since then it's been working without any issues but I can't exactly pinpoint the problem.
Best of luck!
