### ISSUE TITLE
windows and full unlock with 470.05 Beta on 3060 LHR1

### ISSUE THREAD

**Issue by niagars** [Lolliedieb/lolMiner-releases#893]
Hi,
Version 1.34 written: 
...... For 3060 LHR V1 use either 460.39 or earlier driver (Linux) or the full unlock with 470.05 Beta in Windows.

3060 LHR1. More than 41 MH I have not reached. I think all the drivers I downloaded were not the ones I needed. Maybe someone has a result of 50 MH, you can write an accurate and verified link to the driver.

**Comment by pdieppa** [comment]
I have a single 3060V1 using  460.39 under HiveOs and the max I get is 48+- when the fan stops reporting. WhenI reboot the rig and the fan is fixed I get about 39 to 40. I have never gotten 50.

**Comment by niagars** [comment]
`when the fan stops reporting` - what does it mean and how to do it? My setting is
![зображення](https://user-images.githubusercontent.com/86908290/147372855-4df30aad-c31d-4e9e-83f3-2953dd0da1a6.png)

**Comment by jgonzis** [comment]
New Nvidia Drivers solve it all.
