### ISSUE TITLE
Lost connection to stratum server or server not reachable - Please Help!

### ISSUE THREAD

**Issue by Casserole21** [Lolliedieb/lolMiner-releases#896]
I'm new to this and just really want it to work! No matter what I do I keep coming to this road block where my command prompt just won't connect to the server. It doesn't matter which server I use. They all don't work. I've done everything; let the files through my firewalls, tried every server and port combination, watched multiple videos, but I can't get anything to work in my favor. I'm working with lolMiner 1.38! If there is anyone out there that can help me it would be greatly appreciated!!
![2021-12-27 (2)](https://user-images.githubusercontent.com/96716287/147444660-58e307a3-4442-488e-b664-7dfb59d3df58.png)

**Comment by jgonzis** [comment]
> I'm new to this and just really want it to work! No matter what I do I keep coming to this road block where my command prompt just won't connect to the server. It doesn't matter which server I use. They all don't work. I've done everything; let the files through my firewalls, tried every server and port combination, watched multiple videos, but I can't get anything to work in my favor. I'm working with lolMiner 1.38! If there is anyone out there that can help me it would be greatly appreciated!! ![2021-12-27 (2)](https://user-images.githubusercontent.com/96716287/147444660-58e307a3-4442-488e-b664-7dfb59d3df58.png)

could you add in extra parameters: --dns-over-https 0

That seems to be an Internet failure, let's try to use like old version.

**Comment by jgonzis** [comment]
No more Feedback
