### ISSUE TITLE
toncoinpool.io add pool support

### ISSUE THREAD

**Issue by anton85798** [Lolliedieb/lolMiner-releases#898]
toncoinpool.io add pool support
wss://pplns.toncoinpool.io/stratum  stratum-miner

**Comment by jgonzis** [comment]
You are right it is not yet... But it is in the TODO list :-)

**Comment by bagyanugraha** [comment]
> toncoinpool.io add pool support wss://pplns.toncoinpool.io/stratum stratum-miner

We need lolminer

**Comment by jgonzis** [comment]
> > toncoinpool.io add pool support wss://pplns.toncoinpool.io/stratum stratum-miner
> 
> We need lolminer

It is added in 1.41b

**Comment by bagyanugraha** [comment]
HiveOS
try to use wss://
fill in port: 443
It works!

**Comment by xerces13** [comment]
what the config ?
