### ISSUE TITLE
5700XT Crashing when starting the miner for Toncoin

### ISSUE THREAD

**Issue by NudeNULL** [Lolliedieb/lolMiner-releases#899]
I am getting this error on Windows 10 machine, latest AMD drivers, latest Windows updates installed, and the latest lolminer version used.

Is the 5700XT even compatible with the Toncoin mining?

I attached a screenshot with the error
![image](https://user-images.githubusercontent.com/15786742/147848233-aea7a0b9-5cb9-4f9e-ab74-22c89bab5487.png)

**Comment by NudeNULL** [comment]
I tried other bat files for other coins, and everything was working fine, the error is only for Toncoin for now.

**Comment by jgonzis** [comment]
> I tried other bat files for other coins, and everything was working fine, the error is only for Toncoin for now.

That is for the OC that you are using... try to don't use Voltage control. like for Ethereum please. Only Core.

**Comment by NudeNULL** [comment]
I set the default settings for the overclocking before trying the ton mining bat file, and even restarted the PC to make sure that the settings are applied.
![image](https://user-images.githubusercontent.com/15786742/147849302-230ac09e-9734-46a6-ab68-a9e635e6dbde.png)

**Comment by jgonzis** [comment]
Could you try it with MMPOS.EU or HiveOS, people seems to don't have problems. Could you put lower FixCore to see if that helps an increase step by step?

**Comment by NudeNULL** [comment]
I will try to play with the core settings, anyway I will not use other
OS-es because it's my personal computer and I want to use Windows.

**Comment by jgonzis** [comment]
The idea was to try if it is stable, because with Mining OS is easy. But that seems to be all Core issue with voltage

**Comment by NudeNULL** [comment]
I tried with several settings and nothing helped, seems like for windows for this card it is broken :(

**Comment by jgonzis** [comment]
> I tried with several settings and nothing helped, seems like for windows for this card it is broken :(

Sorry...

**Comment by Vadim-Podlevsky** [comment]
Having the same issue for both of my 5700XT on windows 10 with latest Lolminer v1.39 with TonCoin algo. - "Problem loading kernel". All settings are in stock, and bios also. No issues with other AMD or Nvidia cards. Video-driver is not crashing and I can easily mine eth with 5700Xts on Phoenix after this error. Please resolve this issue more closely.

**Comment by jgonzis** [comment]
Windows? Which AMD Drivers? Could you try an older driver?

**Comment by NudeNULL** [comment]
I tried with new version of the miner and it works now 

Thanks!

**Comment by jgonzis** [comment]
> Having the same issue for RX 6800 after a windows update.. Specs: Latest lolminer Windows 10 - 19043.1348 AMD Software Version 21.2.3 Drivers: 27.20.14535.3005 (17/02/21) Any OC (auto/manual/preset) does this
> 
> I do not want to update driver/software because I lose hashrate on ethash if I do. I hadn't updated windows 10 since July or so.. I used lolminer for a few minutes but then the AMD software was bugging out so I updated windows cause it wouldn't let me restart my machine. After that, I was getting this error "problem loading kernel". I tried running as admin with your custom scripts but I got the same results.
> 
> any temporary fixes? Thanks!

Amd changes kernel on new drives and new drivers are not supported. Use older drivers.
