### ISSUE TITLE
Toncoin high (2%~3%) rejected rate on whales pool

### ISSUE THREAD

**Issue by winiel559** [Lolliedieb/lolMiner-releases#902]
My machine gets a high (2% ~ 3%) rejected rate on whales pool.
The miner shows a 100% acceptance rate. But the pool shows a 2% ~ 3% rejected rate due to seed.
The latency of shares is 160ms ~ 300ms if it helps.

Danila miner gets almost zero rejected shares (but lower hashrate especially for my 6800 so overall same profit)

Tks

**Comment by jgonzis** [comment]
> My machine gets a high (2% ~ 3%) rejected rate on whales pool. The miner shows a 100% acceptance rate. But the pool shows a 2% ~ 3% rejected rate due to seed. The latency of shares is 160ms ~ 300ms if it helps.
> 
> Danila miner gets almost zero rejected shares (but lower hashrate especially for my 6800 so overall same profit)
> 
> Tks

The ms are quite high...  could you try another of the 2 servers of Whales pool?

**Comment by phanity2** [comment]
What are the other 2 servers? and what are the location of the servers? the group is in russian

**Comment by jgonzis** [comment]
Solved with new update 1.41b
