### ISSUE TITLE
Specific GPU for Ton coin

### ISSUE THREAD

**Issue by Shindorei** [Lolliedieb/lolMiner-releases#907]
Which parameter need to use for specific GPU for TON coin mining

**Comment by Shindorei** [comment]
Solved it... 
In case of anyone need it :
"%MyVariable%" -a TON  **--devices 1** --pool !POOL! --user !WALLET!  --watchdog exit !EXTRAPARAMETERS!

**Comment by jgonzis** [comment]
> Solved it... In case of anyone need it : "%MyVariable%" -a TON **--devices 1** --pool !POOL! --user !WALLET! --watchdog exit !EXTRAPARAMETERS!

If you don't want to modify it there... you can add it later from the EXTRAPARAMETERS like:

EXTRAPARAMETERS=--devices 1"

**Comment by Masakatra** [comment]
EXTRAPARAMETERS=--devices 1" this doesn't work for me.
