### ISSUE TITLE
toncoin restart miner

### ISSUE THREAD

**Issue by mtmtmt123** [Lolliedieb/lolMiner-releases#908]
All time restart

**Comment by jgonzis** [comment]
> All time restart

It is a know bug in some rigs, which OS are you using?. Dev said it will be a release next day to solve that fast reboot in HiveOS at least.

**Comment by mtmtmt123** [comment]
Hive OS, all 20 minits, all 2 hours or so.

**Comment by krzyk** [comment]
I have similar results. Miner restarts randomly about every 1-2 hours, sometimes there is no restart for 4 hours and sometimes there are restarts every 20 mins. Very strange.

**Comment by ShampooWoo** [comment]
mine with no overlock, have a try

**Comment by jgonzis** [comment]
Solved with new update 1.41b

**Comment by krzyk** [comment]
This was actually solved for me with 1.40 already.

@jgonzis Thank you for your work
