### ISSUE TITLE
0.0sol/sec flux

### ISSUE THREAD

**Issue by Eltonton** [Lolliedieb/lolMiner-releases#909]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/68582398/147886645-d4405b6c-50dd-41bf-94c1-56df3f389c5e.png">

**Comment by jgonzis** [comment]
> <img alt="image" width="665" src="https://user-images.githubusercontent.com/68582398/147886645-d4405b6c-50dd-41bf-94c1-56df3f389c5e.png">

Honestly FLUX for NVidia it is not yet the best miner, for AMD it is working good, but for Nvidia there are other better alternatives. That you should use know. If you want also a good solution of profit for your LHR, mining TON will give you a very good profit too.
