### ISSUE TITLE
ETChash and EthereumStratum protocol is not compatible ?

### ISSUE THREAD

**Issue by Rom1kz** [Lolliedieb/lolMiner-releases#91]
I have tried MORDOR testnet to upgrade my pool for support etchash algo
the pool is working on EthereumStratum protocol, which, as i can see, is not compatible with ETChash.
when i change the proto to EthProxy all working fine and miner say me right epoch (45 atm)

lolMiner 1.15

![изображение](https://user-images.githubusercontent.com/34973778/99985317-ff962c00-2dbe-11eb-9d89-96f7ebbf775a.png)
![изображение](https://user-images.githubusercontent.com/34973778/99985521-1b99cd80-2dbf-11eb-9050-d1b6d0bbfb35.png)

**Comment by Rom1kz** [comment]
in my first example i made an mistake, i sent "algo": "ethash" instead of "etchash"
here i've changed to algo to etchash, but lolMiner still send invalid shares


![изображение](https://user-images.githubusercontent.com/34973778/99998592-f9f51200-2dcf-11eb-81eb-5b318c9b9ee9.png)

**Comment by Rom1kz** [comment]
nvm, i did smth (i really dont know what, maybe old cache ))) and now miner working good

**Comment by Lolliedieb** [comment]
Well ... the CPU verify agrees with the shares and the stratum message should be independent to that. 
What makes a difference: the ethproxy mode sends the mixhash, which makes the verify on pool side simpler. While on ethstratum v1 the pool needs to calc it first. Thus the two verify routines are different on poolside and when one works and one not ... that indicates a pool side error.
