### ISSUE TITLE
stale shares toncoinpool

### ISSUE THREAD

**Issue by anton85798** [Lolliedieb/lolMiner-releases#916]
about 1% outdated, which is a lot
![Снимок экрана 2022-01-05 222347](https://user-images.githubusercontent.com/83923635/148276564-817fade0-b1c5-4d89-8279-96c1b8675d84.png)

**Comment by jgonzis** [comment]
> about 1% outdated, which is a lot ![Снимок экрана 2022-01-05 222347](https://user-images.githubusercontent.com/83923635/148276564-817fade0-b1c5-4d89-8279-96c1b8675d84.png)

That complete normal... the pool has a very big pin... you are under 1%, don't worry about it. Enjoy mining
