### ISSUE TITLE
TON Mining, old Maxwell cards

### ISSUE THREAD

**Issue by dompazz** [Lolliedieb/lolMiner-releases#917]
Seeing performance degradation on Maxwell cards on 1.4 vs 1.39 on TON.  
1.39
`--------------------------------------------- 
Statistics (16:55:30); Mining: SHA256-TON 
Connected to: https://server1.whalestonpool.com:443 
Uptime: 3h 51m 0s 
                       GPU 0       GPU 1       GPU 2       GPU 3      Total
Name:               Tesla M40   Tesla M40   Tesla M40   Tesla M40       Rig
Speed (MH/s):          989.02      999.08      994.05      994.89   3977.04
`

1.4
`--------------------------------------------- 
Statistics (16:59:48); Mining: SHA256-TON 
Connected to: https://server1.whalestonpool.com:443 
Uptime: 0h 3m 0s 
                       GPU 0       GPU 1       GPU 2       GPU 3      Total
Name:               Tesla M40   Tesla M40   Tesla M40   Tesla M40       Rig
Speed (MH/s):          970.56      979.79      976.43      978.11   3904.90
`

**Comment by jgonzis** [comment]
Nice information!!... we should put then the old code for Maxwell too and not the new one.

**Comment by jgonzis** [comment]
> Nice information!!... we should put then the old code for Maxwell too and not the new one.

Has it been correct in 1.41b?

**Comment by dompazz** [comment]
> Has it been correct in 1.41b?

Looks like it:
`--------------------------------------------- 
Statistics (13:36:25); Mining: SHA256-TON 
Connected to: https://pool.services.tonwhales.com:443 
Uptime: 5h 15m 0s 
                       GPU 0       GPU 1       GPU 2       GPU 3      Total
Name:               Tesla M40   Tesla M40   Tesla M40   Tesla M40       Rig
Speed (MH/s):          989.33      999.36      999.36      999.36   3987.41
`

**Comment by Givet911** [comment]
> > Has it been correct in 1.41b?
> 
> Looks like it: `--------------------------------------------- Statistics (13:36:25); Mining: SHA256-TON Connected to: https://pool.services.tonwhales.com:443 Uptime: 5h 15m 0s GPU 0 GPU 1 GPU 2 GPU 3 Total Name: Tesla M40 Tesla M40 Tesla M40 Tesla M40 Rig Speed (MH/s): 989.33 999.36 999.36 999.36 3987.41 `

How many watts?

**Comment by dompazz** [comment]
> How many watts?

about 175W  Not very efficient but it is profitable on older Maxwells (980ti and Tesla M40)

**Comment by oiG8Uchi** [comment]
Setup Miner...
No OpenCL driver or GPUs detected.
Cuda driver detected.
Number of Cuda supported GPUs: 1
Device 0:
    Name:    Quadro M1000M
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  4043 MByte
    Active:  false (Unsupported device or driver version.)

Connecting to pool...
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1)
DNS over HTTPS resolve succeeded
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
Ton job with difficulty 274.88G and giver Ef9iWhwk9GwAXjtwKG-vN7rmXT3hLIT23RBY6KhVaynRrDkx received.
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMiner

**Comment by jgonzis** [comment]
> Setup Miner... No OpenCL driver or GPUs detected. Cuda driver detected. Number of Cuda supported GPUs: 1 Device 0: Name: Quadro M1000M Address: 1:0 Vendor: NVIDIA Corporation Drivers: Cuda Memory: 4043 MByte Active: false (Unsupported device or driver version.)
> 
> Connecting to pool... Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve succeeded https://server1.whalestonpool.com: Address is valid https://server1.whalestonpool.com: Address is registered Ton job with difficulty 274.88G and giver Ef9iWhwk9GwAXjtwKG-vN7rmXT3hLIT23RBY6KhVaynRrDkx received. Start Mining... All devices deselected or failed compatiblity check. Closing lolMiner

It is not supported that GPU

**Comment by dompazz** [comment]
Did support for Maxwell change in a new version?  Or maybe it is an old driver?  Those M40s I have work on the version noted here.
