### ISSUE TITLE
Up to 10% of rejected shares on whales pool

### ISSUE THREAD

**Issue by Vadim-Podlevsky** [Lolliedieb/lolMiner-releases#918]
![msg310054221-57614](https://user-images.githubusercontent.com/1458033/148326873-e8508737-f879-4b5c-82e8-74afc6929b25.jpg)
Having up to 10% of Rejected (seed) on whales pool with lolminer 1.39. What does that even mean? Feels almost like a chunky hidden fee. Just updated to v1.40 so let's see if that will change. Surely problem is not on the miner side as the are 0 issues with toncoinpool so far (~2 hour).

**Comment by jgonzis** [comment]
> ![msg310054221-57614](https://user-images.githubusercontent.com/1458033/148326873-e8508737-f879-4b5c-82e8-74afc6929b25.jpg) Having up to 10% of Rejected (seed) on whales pool with lolminer 1.39. What does that even mean? Feels almost like a chunky hidden fee. Just updated to v1.40 so let's see if that will change. Surely problem is not on the miner side as the are 0 issues with toncoinpool so far (~2 hour).

that is for the DDOS of the pool... try other of the 3 server the pool has.

**Comment by jgonzis** [comment]
update to 1.41 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start
