### ISSUE TITLE
Ton mine: no working connection for 300 seconds

### ISSUE THREAD

**Issue by ShampooWoo** [Lolliedieb/lolMiner-releases#919]
mine for hours, the rig suddenly didnt work,the hashrate of cards are all 0, console log:
------------------------------------
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
No working connection for 300 seconds (Authorization or Work missing). Reconnecting. 
------------------------------------
what should I do ?

**Comment by mobin890** [comment]
> ## mine for hourse, the rig suddenly didnt work,the hashrate of cards are all 0, console log:
> ## Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1)
> No working connection for 300 seconds (Authorization or Work missing). Reconnecting.
> what should I do ?

**Comment by jgonzis** [comment]
It has been another block from ton-whales pool.  Which pool server where you using?. Now all seems another time in order. The good think is you can mix pools, so the pool safe can go from one pool to another.

**Comment by jgonzis** [comment]
update to 1.41 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start

**Comment by NKP144** [comment]
I have a similar problem.
No working connection for 300 seconds (Authorization or Work missing). Reconnecting.
After that the program stops with an error
./dual_mine_eth_ton.sh: line 20: 55091 Segmentation error (memory stack flushed to disk) ./lolMiner --algo ETHASH --pool $ETHPOOL --user $ETHWALLET --dualmode TONDUAL --dualpool $TONPOOL --dualuser $TONWALLET --worker $ETHWORKER $@

I don’t know if it’s a coincidence or not, it happened two days later at 3 o’clock in the morning

Here are the job stats
----------------------------------------------------
Statistics (02:56:59); Uptime: 2h 59m 0s
Algorithm 1: Ethash
Connected to: eth.f2pool.com:6688 (27ms latency)
Algorithm 2: SHA256-TON
Connected to: https://server1.whalestonpool.com:443 (1008ms latency)

      Name Speed ​​Pool Shares Best Eff. Speed ​​Pool Shares Best Eff. Power CCLK MCLK Core Fan --lhrtune
                   Mh/s Mh/s A/S/Hw Share Mh/s/W Mh/s Mh/s A/S/Hw Share Mh/s/W W MHz MHz Temp Pct
GPU 0 RTX 3060 Ti 36.82 38.39 48/0/0 258.1G 0.186 1677.48 1023.75 40/0/0 14.3T 8.461 197.8 1905 6800 57 31 21.4
----------------------------
Total 36.82 38.39 48/0/0 258.1G 0.186 1677.48 1023.75 40/0/0 14.3T 8.461 197.8

Ubuntu 20.04.1
Nvidia GeForce RTS 3060Ti LHR

**Comment by bds89** [comment]
I have the same problem. 
Ubuntu, 3060ti, lol 1,48

**Comment by jgonzis** [comment]
> I have the same problem. Ubuntu, 3060ti, lol 1,48

Pool connection try other pool link
