### ISSUE TITLE
Windows defender: Trojan:Win32/Wacatac.C!ml

### ISSUE THREAD

**Issue by thebrumby** [Lolliedieb/lolMiner-releases#92]
Hi,

Windows Defender is now preventing v1.16a from downloading, flagging the above virus and marking it as **Severe**. I know a lot of mining software gets flagged as low level threats, but this seems new. Is it an intended part of the software?

Thanks

![image](https://user-images.githubusercontent.com/29182343/100094346-c73f2e00-2e50-11eb-9bc0-e5d8a6f07a7a.png)

**Comment by stangerjm** [comment]
I am experiencing this too. Is there a way to get around this?

**Comment by thebrumby** [comment]
I'm waiting for Lollideb to comment before overriding this. Seems different to the normal warnings.

**Comment by thebrumby** [comment]
FYI, after redownloading it today, Windows is not longer reporting the above.
