### ISSUE TITLE
RX6600 & RX580 Running together (not so much...)

### ISSUE THREAD

**Issue by Owl182-1** [Lolliedieb/lolMiner-releases#920]
Good morning,

So, i have four RX580 which run perfectly on lolminer, my rig is an eight card system, so i recently bought two RX6600 to add, not totally unexpected the system (Ububtu 20) did not pick the cards up, clinfo returned bad news etc, so with messing with drivers etc i crashed my OS, when i loaded the four RX580 I had the same problem and went with a fresh reload, as all the machine does is mine its not like there is info to lose on a reload... 

So, if this helps anyone.... and perhaps someone can help with my own problem...

1. Reload Ubuntu, fresh install
2. run all updates on the fresh install that it may want
3. Download and extract Lolminer (if you try run it now it will not work)
3. install clinfo (if you now run clinfo there is a good chance you will get supported platforms 0)
4. install oibaf driver pps
5. sudo add-apt-repository ppa:oibaf/graphics-drivers
6. sudo apt-get update
7. https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
8. Installed the latest version of AMD drivers for Linux 21.03
9. After installation i installed the following by invoking the script as follows (warning, if internet is slow this will take a long time...)
10. In terminal use the following to install opencl: amdgpu-install --opencl=rocr,legacy
11. Finally after all of this i ran lolminer 1.40 BUT i get way too many gpu's showing up AND it shows kernel panic as well, but strangely, it picked up all six cards, (i will show an example after) my four RX580 Started mining as before, nice, quiet and stable, however the two new RX6600 cards just sit there doing nothing, i am sure this may be a driver related problem and the clue i have to that is it shows the model and driver of the RX580 cards BUT only shows the driver name for the RX6600 no model number, when checking AMD Driver 21.03 it shows compatability for both cards so i am not sure what the further problem could be...
12. Here is  little info below which may help identify the issue...

    Device Name                                   AMD Radeon RX 580 2048SP (polaris10, LLVM 13.0.0, DRM 3.43, 5.11.0-44-generic)
    Device Name                                   AMD Radeon RX 580 2048SP (polaris10, LLVM 13.0.0, DRM 3.43, 5.11.0-44-generic)
    Device Name                                   AMD Radeon RX 580 2048SP (polaris10, LLVM 13.0.0, DRM 3.43, 5.11.0-44-generic)
    Device Name                                   AMD Radeon RX 580 2048SP (polaris10, LLVM 13.0.0, DRM 3.43, 5.11.0-44-generic)
    Device Name                                   AMD DIMGREY_CAVEFISH (LLVM 13.0.0, DRM 3.43, 5.11.0-44-generic)
    Device Name                                   AMD DIMGREY_CAVEFISH (LLVM 13.0.0, DRM 3.43, 5.11.0-44-generic)

owl182@Owl182BTC-B37:~$ lspci | grep -1 VGA
00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] (rev ef)
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] (rev ef)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] (rev ef)
04:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] (rev ef)
05:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
--
07:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Downstream Port of PCI Express Switch
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 73ff (rev c7)
08:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device ab28
--
0a:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Downstream Port of PCI Express Switch
0b:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 73ff (rev c7)
0b:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device ab28

So, hopefully someone can help, also hopefully my "sequence" helps someone else...

I have thought of putting the two RX6600 in PCI 0, 1 and the RX580 to PCI 2,3,4,5 But i dont see how this actually helps...

Thanks for your time :)

W.

**Comment by jgonzis** [comment]
AMD Driver 20.40 should be able to run 6600 too, at least the miner allows it. For Example MMPOS or HiveOS run with 20.40 AMD Drivers without any issue.

**Comment by Owl182-1** [comment]
Hi, thanks for the reply, bear in mind i'm trying to run both RX580 and RX6600 in the same 8 card rig, i am wondering if changing the 6600's to the 0,1 slots before the 580's would help, will fool around with it later again, at work now :)

**Comment by Owl182-1** [comment]
Good morning,

Ok, so no, moving the cards around did absolutely nothing, still picks up my RX580 cards which are quietly sitting there doing their thing and not bothering anyone, but my goodness, the frustration with the RX6600 cards is very real !! i will be dropping down to the 20.30 drivers later after work and see if this helps at all...
