### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0Lambda** [Lolliedieb/lolMiner-releases#921]
Hello all, does anyone know what caused this crush?
![image](https://user-images.githubusercontent.com/97218467/148346604-ba69a77a-c92b-4519-b205-5ebccef1288a.png)

**Comment by donPuerto** [comment]
Does mine too Authorization missing

**Comment by donPuerto** [comment]
Not only that it always shutdown itself

**Comment by NudeNULL** [comment]
Same here for any of my cards

**Comment by jgonzis** [comment]
> Hello all, does anyone know what caused this crush? ![image](https://user-images.githubusercontent.com/97218467/148346604-ba69a77a-c92b-4519-b205-5ebccef1288a.png)

Yes it has been another time a block of DDOS in the pool, now all seems working. Problem is happening with cloudfare and tonwhales.

**Comment by jgonzis** [comment]
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start

**Comment by donPuerto** [comment]
thanks @jgonzis
