### ISSUE TITLE
Invalid shares on Nvidia Ampere under HiveOS

### ISSUE THREAD

**Issue by Sanchous98** [Lolliedieb/lolMiner-releases#922]
Even in stock lolminer reports invalid shares on my RTX 3080Ti. My rig has got 5x 3080ti and rx480. Rx480 doesn't generate any invalid shares even after applying undervoltage. Rtx 3080Tis generate 6-8 invalid shares after 10 hours of mining in stock. I use the latest version of lolminer 1.40. The pool is toncoinpool.io

**Comment by jgonzis** [comment]
> Even in stock lolminer reports invalid shares on my RTX 3080Ti. My rig has got 5x 3080ti and rx480. Rx480 doesn't generate any invalid shares even after applying undervoltage. Rtx 3080Tis generate 6-8 invalid shares after 10 hours of mining in stock. I use the latest version of lolminer 1.40. The pool is toncoinpool.io

Yes that normal... 1.39 there were a bug not showing it... is not a problem hardware don't worry. It is normal, when and old and new job come could that happen. So don't worry about it.

**Comment by Sanchous98** [comment]
> > Even in stock lolminer reports invalid shares on my RTX 3080Ti. My rig has got 5x 3080ti and rx480. Rx480 doesn't generate any invalid shares even after applying undervoltage. Rtx 3080Tis generate 6-8 invalid shares after 10 hours of mining in stock. I use the latest version of lolminer 1.40. The pool is toncoinpool.io
> 
> Yes that normal... 1.39 there were a bug not showing it... is not a problem hardware don't worry. It is normal, when and old and new job come could that happen. So don't worry about it.

Yeah, I understood that it's not a hardware problem but it confuses users, so I cannot find optimal overclock settings, because there is no info if the error is due to software or hardware issue. Also there is no such problem on AMD GCN
![Снимок экрана 2022-01-06 в 15 15 00](https://user-images.githubusercontent.com/45293316/148388378-8b14b1b6-4ce8-4022-937b-4ca9b202dc9b.png)

**Comment by jgonzis** [comment]
That normal mining with TON... it could happen...

**Comment by Sanchous98** [comment]
> That normal mining with TON... it could happen...

Version 1.41b seems to solve the issue
