### ISSUE TITLE
1.40 version problems on ton mining

### ISSUE THREAD

**Issue by FreshCloud330** [Lolliedieb/lolMiner-releases#924]
i am getting %90-95 accept/reject ratio with 3060. some of my friends says amd cards getting more rejects. another problem is miner restarts itself every 10-30 minutes with this error: 

terminate called after throwing an instance of 'boost::wrapexcept'
  what():  resolve: Device or resource busy

lolminer exited (exitcode=0), waiting to cooldown a bit

ton mining with lolminer v1.40 on ton universe pool on hiveos

**Comment by FreshCloud330** [comment]
![image](https://user-images.githubusercontent.com/80773438/148373564-40132517-c699-48a1-b790-933a618d5dd4.png)
![image](https://user-images.githubusercontent.com/80773438/148373597-e9f13b12-cac9-4d0f-8ec6-e0e83d1e69de.png)

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/80773438/148373564-40132517-c699-48a1-b790-933a618d5dd4.png) ![image](https://user-images.githubusercontent.com/80773438/148373597-e9f13b12-cac9-4d0f-8ec6-e0e83d1e69de.png) two different issues

Tonuniverse shared that pool was down... now is working... I give you 2 pools connection to tonuniverse so you can have a safe pool too.  https://other.tonuniverse.com

You can add it as extra paramaters:
--pool https://other.tonuniverse.com --user (your_poolID_from_the_boot)

**Comment by FreshCloud330** [comment]
pool problem solved but what about miner restart issue? i return back to v1.39

**Comment by dario417** [comment]
I’m having the same problems as of 20 min ago using whalespool. I had to change back to eth mining

**Comment by jgonzis** [comment]
update to 1.41 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start
