### ISSUE TITLE
1.40  restart without error

### ISSUE THREAD

**Issue by anton85798** [Lolliedieb/lolMiner-releases#926]
I did not notice any errors in the log file, the miner just restarts
![Снимок экрана 2022-01-06 135724](https://user-images.githubusercontent.com/83923635/148372521-5b47fe41-f78a-47f2-a04c-25b305a735fb.png)

**Comment by jgonzis** [comment]
> I did not notice any errors in the log file, the miner just restarts ![Снимок экрана 2022-01-06 135724](https://user-images.githubusercontent.com/83923635/148372521-5b47fe41-f78a-47f2-a04c-25b305a735fb.png)

Yes the bug has been reported... it seems only happen with toncoinpool.io... Dev is working on it!!

**Comment by sebek72** [comment]
For me this happens also on other pools. After reverting to 1.39 only whales poll is supported.

**Comment by Tylon-ldd** [comment]
I got the same issue.

**Comment by jgonzis** [comment]
update to 1.41 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start
