### ISSUE TITLE
toncoin mining bug problem

### ISSUE THREAD

**Issue by thiefhigh02** [Lolliedieb/lolMiner-releases#927]
this is the problem i get from my rig

No working connection for 300 seconds (Authorization or Work missing). Reconnecting.
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
Pool https://server1.whalestonpool.com timeout or send defect message: "<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> whalestonpool.com</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">

              <span class="cf-no-screenshot error"></span>

          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6c946d408ff701d1</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 119.56.105.240</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>

    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};

</script>

</body>
</html>
"

**Comment by rcerebro** [comment]
I didn't see the message, but 4 of my rigs stopped working this morning, as I remotely accessed minerstat and changed it to CFX I didn't get to see this message, but I assume the same happened to me, in 4 RIGs that were in this pool

**Comment by Paultuc** [comment]
having same problem

tried v1.4 same error 

+---------------------------------------------------------+
|   _       _ __  __ _                   _  _  _    ___   |
|  | | ___ | |  \/  (_)_ __   ___ _ __  / || || |  / _ \  |
|  | |/ _ \| | |\/| | | '_ \ / _ \ '__| | || || |_| | | | |
|  | | (_) | | |  | | | | | |  __/ |    | ||__   _| |_| | |
|  |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_) |_|  \___/  |
|                                                         |
|              This software is for mining                |
|              Autolykos V2                               |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash III                               |
|              ZelHash     (EquihashR 125/4/0)            |
|              SHA256 (TON)                               |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|             Made by Lolliedieb, January 2022            |
+---------------------------------------------------------+

Setup Miner... 
OpenCL driver detected.
Number of OpenCL supported GPUs: 4 
Cuda driver detected.
Number of Cuda supported GPUs: 4 
Device 0: 
    Name:    NVIDIA GeForce RTX 2060 
    Address: 1:0 
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  6144 MByte 
    Active:  true (Selected Algorithm: TON (Sha 256)) 
Device 1: 
    Name:    NVIDIA GeForce RTX 3080 
    Address: 2:0 
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  10240 MByte 
    Active:  true (Selected Algorithm: TON (Sha 256)) 
Device 2: 
    Name:    NVIDIA GeForce RTX 3060 Ti 
    Address: 3:0 
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  8192 MByte 
    Active:  true (Selected Algorithm: TON (Sha 256)) 
Device 3: 
    Name:    NVIDIA GeForce RTX 3080 
    Address: 4:0 
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  10240 MByte 
    Active:  true (Selected Algorithm: TON (Sha 256)) 

Connecting to pool... 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve succeeded 
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered
Pool https://server1.whalestonpool.com timeout or send defect message: "<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> whalestonpool.com</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6c94d4946bf1055a</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 197.89.106.138</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>
" 
No working connection for 300 seconds (Authorization or Work missing). Reconnecting. 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve succeeded 
https://server1.whalestonpool.com: Address is valid
https://server1.whalestonpool.com: Address is registered

**Comment by jgonzis** [comment]
update to 1.41 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start
