### ISSUE TITLE
RaveOs not mining

### ISSUE THREAD

**Issue by valery29** [Lolliedieb/lolMiner-releases#928]
Any version ... RaveOs Log writes - you have been blocked. The miner is not working ...

**Comment by jgonzis** [comment]
in which Pool?

**Comment by jgonzis** [comment]
update to 1.41 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.41

MMPOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ &&  agent-stop && sudo cp lolMiner /opt/mmp/miners/lolminer-equihash && agent-start 

HiveOS update to 1.41 from 1.40: Open console en write it:
cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && miner stop && cp lolMiner /hive/miners/lolminer/1.40/ && miner start 

RaveOS update to 1.41 from 1.40: Open console en write it:
stop && cd /tmp && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.41/lolMiner_v1.41_Lin64.tar.gz && tar -xvf lolMiner_v1.41_Lin64.tar.gz && cd 1.41/ && cp lolMiner /app-data/miners/lolminer-1.40 &&  start
