### ISSUE TITLE
Memory usage HIVEOS

### ISSUE THREAD

**Issue by G9third** [Lolliedieb/lolMiner-releases#93]
Over time on hive mining eth/etc with 4gb gpus my memory usage slowly gets taken up until my rig becomes unresponsive. Memory usage after reboot is about 5.5 free and after 12-24 hours it depletes to <500mb free and then turns offline. I am not 100% sure that this is a lolminer issue but I wanted to leave this here just in case.

**Comment by G9third** [comment]
I can provide images/more info if needed

**Comment by jgonzis** [comment]
I also have similar problem... I think the dev is looking on that too...

**Comment by pdieppa** [comment]
Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.

**Comment by jgonzis** [comment]
> Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.

It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍

**Comment by pdieppa** [comment]
> > Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.
> 
> It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍

Hmm. Do you know if they are having the same issue with 1.17?

**Comment by pdieppa** [comment]
> > Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.
> 
> It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍

hmmm. Do you know if they are having the same issue with 1.17? I could downgrade if needed.

**Comment by jgonzis** [comment]
> > > Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.
> > 
> > 
> > It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍
> 
> hmmm. Do you know if they are having the same issue with 1.17? I could downgrade if needed.

Is not issue of lolMiner, it is issue with drivers 20.30 and the kernel of HiveOS... don't worry about it... when arrives to 0... restarts and goes to 6.9Gb another time. It happens normally with some 5700 units...

**Comment by pdieppa** [comment]
> > > > Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.
> > > 
> > > 
> > > It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍
> > 
> > 
> > hmmm. Do you know if they are having the same issue with 1.17? I could downgrade if needed.
> 
> Is not issue of lolMiner, it is issue with drivers 20.30 and the kernel of HiveOS... don't worry about it... when arrives to 0... restarts and goes to 6.9Gb another time. It happens normally with some 5700 units...
👍👍

**Comment by pdieppa** [comment]
> > > > Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.
> > > 
> > > 
> > > It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍
> > 
> > 
> > hmmm. Do you know if they are having the same issue with 1.17? I could downgrade if needed.
> 
> Is not issue of lolMiner, it is issue with drivers 20.30 and the kernel of HiveOS... don't worry about it... when arrives to 0... restarts and goes to 6.9Gb another time. It happens normally with some 5700 units...

👍👍G9third mentioned 4Gb GPUs but it is also happening with the 5700XT. I have 6 of them.

**Comment by jgonzis** [comment]
> > > > > Looks like I'm having the same issue with lolMiner 1.18a and HiveOs 0.6-190@210106. The rig starts with about 6.9Gb of RAM and 8 hours later is down to 4.4.
> > > > 
> > > > 
> > > > It is problem with kernel HiveOS and drivers 20.30... with the 5700. Se have to wait for the new beta of HiveOS. But It males when is complete down a fast restart and continues. No problem ☺👍
> > > 
> > > 
> > > hmmm. Do you know if they are having the same issue with 1.17? I could downgrade if needed.
> > 
> > 
> > Is not issue of lolMiner, it is issue with drivers 20.30 and the kernel of HiveOS... don't worry about it... when arrives to 0... restarts and goes to 6.9Gb another time. It happens normally with some 5700 units...
> 
> 👍👍G9third mentioned 4Gb GPUs but it is also happening with the 5700XT. I have 6 of them.
Solution is ready:

🇬🇧 New Stable Branch Image release v0.6-190@210108 💿

🔑 Key features:
* Hive Linux client: v0.6-190@210106
* Universal boot mode: BIOS | UEFI
* Linux kernel: v5.4.80-hiveos
* AMD drivers:  OpenCL v20.40
* Nvidia drivers: v455.45.01
* Updated drivers for ethernet and wi-fi adapters

This Image is recommended for Nvidia 10xx/16xx/20xx/30xx and AMD Polaris RX4xx/5xx, Vega and Navi RX 5xxx

💾 Available for download as a torrent or XZ archive in the "GPU" section "Stable Image" over on https://hiveos.farm/install or it can be reflashed via the hive-replace tool or using balenaEtcher or Rufus tools on PC.
