### ISSUE TITLE
Toncoin 1.40 rtx 3090

### ISSUE THREAD

**Issue by tsladrvr** [Lolliedieb/lolMiner-releases#930]
Hi,
My Rtx 3090 getting this error after 30 mins of mining.

Unrecoverable memory error by GPU 1.
Reset of all Cuda GPUs required.
Please check your (memory) OC & UV settings on this card.
Device 0 detected as crashed. 
Device 1 detected as crashed. 
Device 2 detected as crashed. 
Device 3 detected as crashed. 
Device 4 detected as crashed. 
Device 5 detected as crashed. 
Device 6 detected as crashed. 
Device 7 detected as crashed. 
Device 8 detected as crashed. 
Device 9 detected as crashed. 
Device 10 detected as crashed. 
Device 11 detected as crashed. 
Device 12 detected as crashed. 
Device 13 detected as crashed. 
Closing miner and trying to call external script: ./emergency.sh (--watchdog script) 
Closing miner and trying to call external script: ./emergency.sh (--watchdog script) 
Closing miner and trying to call external script: ./emergency.sh (--watchdog script) 
> Sending danger with payload to http://api.hiveos.farm
OK
> Preparing for reboot
Protocol spec without prior Class and Subclass spec at line 23179
> Unmounting disks
client_loop: send disconnect: Broken pipe

**Comment by jgonzis** [comment]
" Unrecoverable memory error by GPU 1. " That is the help!! You should reduce the Core Clock Offset of that GPU. Always look at which GPU has caused to adjust the offset! :-)
