### ISSUE TITLE
Dont know what im doing wrong

### ISSUE THREAD

**Issue by Klaebelmine** [Lolliedieb/lolMiner-releases#934]
Sry for asking, but i am very new to this and i really dont know what is going wrong when i try to launch my eth miner all its says is this:

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 1
No Cuda driver or GPUs detected.
Device 0:
    Name:    Intel(R) UHD Graphics 620
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  1590 MByte
    Active:  false (not selected)

Connecting to pool...
DNS over HTTPS resolve succeeded
Connected to eu1.ethermine.org(172.65.207.106):4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x9b624088A9D679f4a4c9b77b13318f41e6bb6E08.Account
New job received: 0x95f4d0 Epoch: 465 Difficulty: 4.30G
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . .

Please help me with this, thx

**Comment by jgonzis** [comment]
> Sry for asking, but i am very new to this and i really dont know what is going wrong when i try to launch my eth miner all its says is this:
> 
> Setup Miner... OpenCL driver detected. Number of OpenCL supported GPUs: 1 No Cuda driver or GPUs detected. Device 0: Name: Intel(R) UHD Graphics 620 Address: 4294967295:4294967295 Vendor: Intel(R) Corporation Drivers: OpenCL Memory: 1590 MByte Active: false (not selected)
> 
> Connecting to pool... DNS over HTTPS resolve succeeded Connected to eu1.ethermine.org(172.65.207.106):4444 (TLS disabled) Set Ethash stratum mode: Ethereum Proxy Authorized worker: 0x9b624088A9D679f4a4c9b77b13318f41e6bb6E08.Account New job received: 0x95f4d0 Epoch: 465 Difficulty: 4.30G Start Mining... All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . .
> 
> Please help me with this, thx

You need a dedicated GPU... you cannot mine with the GPU of the CPU

**Comment by Klaebelmine** [comment]
thx u:)
