### ISSUE TITLE
1.41/win crashes after a while when mining on tonuniverse

### ISSUE THREAD

**Issue by syncro16** [Lolliedieb/lolMiner-releases#935]
The new networking code seems to have some faults, almost all my miners have crashed after running about an hour and mine_ton.bat is telling "Press any key to continue ...
![screenshot](https://user-images.githubusercontent.com/28645605/148499383-53ba0814-d09a-411b-9e60-ce7eacf1683a.png)
"

**Comment by syncro16** [comment]
> The new networking code seems to have some faults, almost all my miners have crashed after running about an hour and mine_ton.bat is telling "Press any key to continue ...
> ![screenshot](https://user-images.githubusercontent.com/28645605/148499383-53ba0814-d09a-411b-9e60-ce7eacf1683a.png)
> "

It might be related (invalid) server response. For a miner containing two cards, i did run separete miners on each card, and both stopped working on a same time.

**Comment by jgonzis** [comment]
> The new networking code seems to have some faults, almost all my miners have crashed after running about an hour and mine_ton.bat is telling "Press any key to continue ... ![screenshot](https://user-images.githubusercontent.com/28645605/148499383-53ba0814-d09a-411b-9e60-ce7eacf1683a.png) "

Could you use the loop? to autorestart... it seems we are several with that crash in pool.tonuniverse.com but with loop it will be reduced (use 1.41a please)

for the bat file :

:loop

lolminer.exe --algo TON --pool https://server1.whalestonpool.com  --user yourwallethere  --pool https://pool.tonuniverse.com --user yourwallethere --hstats

timeout 10
goto loop

**Comment by syncro16** [comment]
> 

Yes i did loops to my startup scripts, but it's little bit more workaround than a fix :-) ... 

Too bad difficulty in tonuniverse seems to quite high, and one share can be calculated over 20min or so. Too bad to lose them due to crash..

**Comment by piraciskoo** [comment]
Hi
I have the same problem. Stops every 20 minutes. in version 1.40 there was no this problem.

**Comment by jgonzis** [comment]
> Hi I have the same problem. Stops every 20 minutes. in version 1.40 there was no this problem.

Yes it is been working on it... 1.41b should make all 4 pools working... Now with 1.41a ton whales, ton-pool and toncoinpool perfect

**Comment by piraciskoo** [comment]
> > Hi I have the same problem. Stops every 20 minutes. in version 1.40 there was no this problem.
> 
> Yes it is been working on it... 1.41b should make all 4 pools working... Now with 1.41a ton whales, ton-pool and toncoinpool perfect

Ok. Tx. :) I'll wait patiently

**Comment by jgonzis** [comment]
Solved with new update 1.41b
