### ISSUE TITLE
worker name for tonwhales pool / TON

### ISSUE THREAD

**Issue by DnzYg** [Lolliedieb/lolMiner-releases#938]
You said that pools other than toncoinpool do not support worker name, but "rig name" option can be defined in danilaminergui for tonwhales pool. I think this is a little secret trick, it would be nice if you could fix this problem when you have time.

![image](https://user-images.githubusercontent.com/88924605/148559046-19a0ae8c-deb2-4c76-879f-b20d3b49b630.png)

**Comment by jgonzis** [comment]
> You said that pools other than toncoinpool do not support worker name, but "rig name" option can be defined in danilaminergui for tonwhales pool. I think this is a little secret trick, it would be nice if you could fix this problem when you have time.
> 
> ![image](https://user-images.githubusercontent.com/88924605/148559046-19a0ae8c-deb2-4c76-879f-b20d3b49b630.png)

Try it... add --worker RIGNAME :-)

**Comment by DnzYg** [comment]
> > You said that pools other than toncoinpool do not support worker name, but "rig name" option can be defined in danilaminergui for tonwhales pool. I think this is a little secret trick, it would be nice if you could fix this problem when you have time.
> > ![image](https://user-images.githubusercontent.com/88924605/148559046-19a0ae8c-deb2-4c76-879f-b20d3b49b630.png)
> 
> Try it... add --worker RIGNAME :-) inn toncoinpool is working

of course I tried it and wlt.rigname but it doesn't work, the pool accepts packages but telegram bot shows 0 GH/s on my account

**Comment by jgonzis** [comment]
> > > You said that pools other than toncoinpool do not support worker name, but "rig name" option can be defined in danilaminergui for tonwhales pool. I think this is a little secret trick, it would be nice if you could fix this problem when you have time.
> > > ![image](https://user-images.githubusercontent.com/88924605/148559046-19a0ae8c-deb2-4c76-879f-b20d3b49b630.png)
> > 
> > 
> > Try it... add --worker RIGNAME :-) inn toncoinpool is working
> 
> of course I tried it and wlt.rigname but it doesn't work, the pool accepts packages but telegram bot shows 0 GH/s on my account

We comment to the creator of the watchdog to read the api of lolMiner it should be nice too
