### ISSUE TITLE
lolMiner 1.41 program startup error

### ISSUE THREAD

**Issue by hakan2604** [Lolliedieb/lolMiner-releases#939]
lolMiner 1.41 program startup error ,I leave the image of the error, I wonder what is the problem. 

"All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . ."
![33333333](https://user-images.githubusercontent.com/97301954/148569166-19fcf9b8-5a1f-41f7-ac89-09bf08f9738b.JPG)

**Comment by jgonzis** [comment]
> lolMiner 1.41 program startup error ,I leave the image of the error, I wonder what is the problem.
> 
> "All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . ." ![33333333](https://user-images.githubusercontent.com/97301954/148569166-19fcf9b8-5a1f-41f7-ac89-09bf08f9738b.JPG)

Which Nvidia Driver are you using??... It seems that version it is to new that is not yet supported. Could you give that information?

**Comment by hakan2604** [comment]
Nvdia driver  versiyon 497.29

**Comment by jgonzis** [comment]
> Nvdia driver versiyon 497.29

Could you try older version? Like 472.12 for example?

**Comment by MinerTi** [comment]
Yep, some miners working with new drivers, but hashrate slower. One of best drivers for miners is yes 472.12.

**Comment by jgonzis** [comment]
> Yep, some miners working with new drivers, but hashrate slower. One of best drivers for miners is yes 472.12.

Worked with 472.12? Great ☺

**Comment by hakan2604** [comment]
I solved the problem. There was a problem with windows automatic update, it was fixed after updating again.Thank you
