### ISSUE TITLE
Getting this error 1.41B

### ISSUE THREAD

**Issue by Dirpt** [Lolliedieb/lolMiner-releases#940]
everypool I try I get this error:
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/97310923/148594023-a8972a46-d8fb-4876-aab1-5e638c84c59f.png">

not sure what's wrong with my configs

Sorry, trying to miner ton in whalespool with lolminer (HIVEOS)

**Comment by jgonzis** [comment]
> everypool I try I get this error: <img alt="image" width="1044" src="https://user-images.githubusercontent.com/97310923/148594023-a8972a46-d8fb-4876-aab1-5e638c84c59f.png">
> 
> not sure what's wrong with my configs
> 
> Sorry, trying to miner ton in whalespool with lolminer (HIVEOS)

Update HiveOS,  it says Coin not supported that means you haven't click the orange link update of HiveOS
