### ISSUE TITLE
RX 6800 ton mining with1.39 working but crashing with > 1.4x

### ISSUE THREAD

**Issue by DasUnding** [Lolliedieb/lolMiner-releases#942]
Is there something changed? The radeon gpu which runs this coin since 1.39 is not able to run the newer version. It displays a crash. I run this card at 2000MHz 756mV 192Mhz Memory but it seems also to crash with stock settings by starting the miner. For some reason I use an older driver maybe it has something to do with that? Do you have similar experience?

**Comment by jgonzis** [comment]
Increase Core ... Voltage... it has been an increase of performance and that increase could need more Core..

**Comment by DasUnding** [comment]
It also crashes with stock settings, it is a bit strange. 1.39 is running without any problems.
