### ISSUE TITLE
lolMiner 1.42, Memory clock setting

### ISSUE THREAD

**Issue by dawidmosk** [Lolliedieb/lolMiner-releases#944]
I cant set -200 setting because setting is not an offset? Any ideas?

**Comment by karmagkz** [comment]
adminstrator mode

**Comment by dawidmosk** [comment]
?

**Comment by karmagkz** [comment]
set "EXTRAPARAMETERS=--mclk 807 --cclk 2009" best for 3090

**Comment by dawidmosk** [comment]
Thanks You, maybe someone have best for 3060 and 3060 ti? :)

**Comment by ghtweb** [comment]
3080ti
--mclk 810 --cclk 2008
3060ti and 3070ti
--mclk 810 --cclk 2100

**Comment by dawidmosk** [comment]
> 3080ti --mclk 810 --cclk 2008 3060ti and 3070ti --mclk 810 --cclk 2100

thank you, but still i dont know how it works - its counting from 0 or like offset?

**Comment by Vavok** [comment]
how to disable  --mclk  and return the standard values?

**Comment by dawidmosk** [comment]
> how to disable --mclk and return the standard values?

or show default values

**Comment by karmagkz** [comment]
power off, power on computer

**Comment by dawidmosk** [comment]
> power off, power on computer

nice try! 👯 haha

**Comment by Shindorei** [comment]
> > power off, power on computer
> 
> nice try! 👯 haha

But it is true :)

**Comment by dawidmosk** [comment]
> > > power off, power on computer
> > 
> > 
> > nice try! 👯 haha
> 
> But it is true :)

I didn't know this, you talking about strange things. Computer should work always :D

**Comment by BANZAI-616** [comment]
Hello, how did you install 810 from memory in hive os?  I updated on the hive Miner registered --mclk 810 but there is no sense in the miner writes 9251 from memory.  Map 3080. I put it in hiveos -2000, well, the memory fell to 9151 in the logs. When I wrote through the command, I removed the memory values ​​\u200b\u200bin hive os.  At the same time, Miner writes that he applied overclocking, but the memory does not change, if you write --cclk 1740, then Miner writes that he applied --cclk 1740 to the GPU
![Uploading Screenshot_20220113-152226_Chrome.png…]()

**Comment by Shindorei** [comment]
> > > > power off, power on computer
> > > 
> > > 
> > > nice try! 👯 haha
> > 
> > 
> > But it is true :)
> 
> I didn't know this, you talking about strange things. Computer should work always :D

I guess it is a bug. Couse when you close lol miner and say yes to clear data, nothing changes. Mem clock still be 800 Mhz. To solve this issue you need to restart computer.

**Comment by BANZAI-616** [comment]
> > > > > выключить, включить компьютер
> > > > 
> > > > 
> > > > хорошая попытка! 👯 ха-ха
> > > 
> > > 
> > > Но это правда :)
> > 
> > 
> > Я этого не знал, ты говоришь о странных вещах. Компьютер должен работать всегда :D
> 
> Я думаю, это ошибка. Потому что, когда вы закрываете lol miner и говорите «да», чтобы очистить данные, ничего не меняется. Часы памяти по-прежнему будут 800 МГц. Чтобы решить эту проблему, вам необходимо перезагрузить компьютер.

I will reboot

**Comment by BANZAI-616** [comment]
> > > > > > выключить, включить компьютер
> > > > > 
> > > > > 
> > > > > хорошая попытка! 👯 ха-ха
> > > > 
> > > > 
> > > > Но это правда :)
> > > 
> > > 
> > > Ты говоришь о странных вещах. Компьютер должен работать всегда :D
> > 
> > 
> > Я думаю, это ошибка. Потому что, когда вы закрываете lol miner и говорит «да», чтобы очистить данные, ничего не меняется. Память часов по-прежнему будет 800 МГц. Чтобы решить эту проблему, вам необходимо перезагрузить компьютер.
> 
> я перезагружу

no need to restart the rig!  need firewood 470.86!  on firewood 460.84 does not work!  the issue is closed, after updating the drivers it worked!

**Comment by Shindorei** [comment]
> > > > > > > выключить, включить компьютер
> > > > > > 
> > > > > > 
> > > > > > хорошая попытка! 👯 ха-ха
> > > > > 
> > > > > 
> > > > > Но это правда :)
> > > > 
> > > > 
> > > > Ты говоришь о странных вещах. Компьютер должен работать всегда :D
> > > 
> > > 
> > > Я думаю, это ошибка. Потому что, когда вы закрываете lol miner и говорит «да», чтобы очистить данные, ничего не меняется. Память часов по-прежнему будет 800 МГц. Чтобы решить эту проблему, вам необходимо перезагрузить компьютер.
> > 
> > 
> > я перезагружу
> 
> no need to restart the rig! need firewood 470.86! on firewood 460.84 does not work! the issue is closed, after updating the drivers it worked!

In wi ndows driver version 472.12 not worked. U need to restart computer

**Comment by soslyfox** [comment]
It seems like my --mclk 810 is not working properly for v. 1.42. What could be a potential problem?
![image](https://user-images.githubusercontent.com/97693867/149379789-fdcb8999-1eaa-4c87-b3c4-84b98f04488c.png)
![image](https://user-images.githubusercontent.com/97693867/149379855-952dbcf2-df9f-4bcd-980e-7e748509ca33.png)

**Comment by jgonzis** [comment]
> It seems like my --mclk 810 is not working properly for v. 1.42. What could be a potential problem? ![image](https://user-images.githubusercontent.com/97693867/149379789-fdcb8999-1eaa-4c87-b3c4-84b98f04488c.png) ![image](https://user-images.githubusercontent.com/97693867/149379855-952dbcf2-df9f-4bcd-980e-7e748509ca33.png)

You need at least driver Nvidia 470, which Nvidia Driver do you have?.

**Comment by winiel559** [comment]
> It seems like my --mclk 810 is not working properly for v. 1.42. What could be a potential problem? 

What cards are you using?
mclk 810 only supports Ampere cards.

**Comment by dawidmosk** [comment]
I dont see changes on 3060 (ti and not ti) with option mclk. Driver version 470.74. It's not working for ETH mining?

**Comment by jgonzis** [comment]
> I dont see changes on 3060 (ti and not ti) with option mclk. Driver version 470.74. It's not working for ETH mining?

You have to run them as administrator, it is only profitable the optimisation for TON, for ETH it is not recommend

**Comment by soslyfox** [comment]
> > It seems like my --mclk 810 is not working properly for v. 1.42. What could be a potential problem? ![image](https://user-images.githubusercontent.com/97693867/149379789-fdcb8999-1eaa-4c87-b3c4-84b98f04488c.png) ![image](https://user-images.githubusercontent.com/97693867/149379855-952dbcf2-df9f-4bcd-980e-7e748509ca33.png)
> 
> You need at least driver Nvidia 470, which Nvidia Driver do you have?.

Thank you, you are absolutely right. Once I'd updated it, it worked out.
