### ISSUE TITLE
All devices deselected or failed compatiblity check.

### ISSUE THREAD

**Issue by nuubminer** [Lolliedieb/lolMiner-releases#946]
![Screenshot 2022-01-10 131452](https://user-images.githubusercontent.com/97474533/148826610-ab296395-c0e2-4bb4-9fe7-50c28330b5b0.png)

I get this message when I try to launch, please help and thanks in advanced!

**Comment by jgonzis** [comment]
> ![Screenshot 2022-01-10 131452](https://user-images.githubusercontent.com/97474533/148826610-ab296395-c0e2-4bb4-9fe7-50c28330b5b0.png)
> 
> I get this message when I try to launch, please help and thanks in advanced!

Which GPU do you have?. It is an Integrated GPU o dedicated INTEL GPU?

**Comment by jgonzis** [comment]
> ![Screenshot 2022-01-10 131452](https://user-images.githubusercontent.com/97474533/148826610-ab296395-c0e2-4bb4-9fe7-50c28330b5b0.png)
> 
> I get this message when I try to launch, please help and thanks in advanced!

Could you confirm if that is one of the new Intel GPUs? It will be great if you enter our Telegram group to talk with the Dev to test it and ADD the option to mine with it. Many thanks in advance.

**Comment by nuubminer** [comment]
Sadly this is just a Laptop Dell Latitude 7420
![GPUZ](https://user-images.githubusercontent.com/97474533/148946703-e33461f3-2ffa-46e2-b278-6c78b9429bb7.png)
![CPUZ](https://user-images.githubusercontent.com/97474533/148946709-9fa64273-81b0-4275-96d5-671d2b9313b0.png)
![CPUZ2](https://user-images.githubusercontent.com/97474533/148946717-81b1e649-f7c2-4e6b-9847-22f3b98cb9e2.png)
![CPUZ3](https://user-images.githubusercontent.com/97474533/148946720-73451f6b-8791-489e-a9b6-db22c7780ee7.png)
.

**Comment by jgonzis** [comment]
> Sadly this is just a Laptop Dell Latitude 7420 ![GPUZ](https://user-images.githubusercontent.com/97474533/148946703-e33461f3-2ffa-46e2-b278-6c78b9429bb7.png) ![CPUZ](https://user-images.githubusercontent.com/97474533/148946709-9fa64273-81b0-4275-96d5-671d2b9313b0.png) ![CPUZ2](https://user-images.githubusercontent.com/97474533/148946717-81b1e649-f7c2-4e6b-9847-22f3b98cb9e2.png) ![CPUZ3](https://user-images.githubusercontent.com/97474533/148946720-73451f6b-8791-489e-a9b6-db22c7780ee7.png) .

So that was the problem... you need a dedicated GPU for that

**Comment by nuubminer** [comment]
![GPUZunMINABLE](https://user-images.githubusercontent.com/97474533/148948408-0d864afe-b2c3-468b-b336-82b1209092ad.png)

**Comment by nuubminer** [comment]
Thank you.
