### ISSUE TITLE
Keeps saying "Error when allocating memory or building DAG.  Disabling card."

### ISSUE THREAD

**Issue by Qwiqs** [Lolliedieb/lolMiner-releases#948]
it keeps on saying "GPU 0: error when allocating memory or building ram DAG, disabling card"

I know that means i dont have enough memory to mine since i need more than 4, but my real question is how do i add more memory to lolminer? 
I'm mining eth btw.

**Comment by Qwiqs** [comment]
> 

sorry for such a late reply, im using a gtx 1650, my friend with a 1060 can mine just fine.

**Comment by jgonzis** [comment]
The 1650 hat only 4Gb and the 1060 can have 6GB. To mine ethereum you need minimum 5GB of Memory GPUs. You will not been able to mine with the 1650, you can mine ETC for example
