### ISSUE TITLE
How to unlock the memory clock? 

### ISSUE THREAD

**Issue by bill8362** [Lolliedieb/lolMiner-releases#949]
I used the parameter - - mclk 810  and I deleted the parameter afterwards, the memory clock is still 810. Dose anyone know how to turn off that setting ?

**Comment by Vavok** [comment]
yes, very intresting question.

**Comment by bill8362** [comment]
I finally found out the solution which is restart the power then it will go back to before

**Comment by donPuerto** [comment]
@bill8362 can you show your bat file settings here :)

**Comment by karmagkz** [comment]
power off, power on computer

**Comment by xchainw** [comment]
you can try(required administrator permissions):
`nvidia-smi.exe -rmc`
