### ISSUE TITLE
ROCm?

### ISSUE THREAD

**Issue by plasticbomb1986** [Lolliedieb/lolMiner-releases#95]
Im not sure if its the miner, or something on my system.
When i start the miner (just the default mine_eth.sh i get this:

```
Setup Miner... 
Device 0: 
    Name:    Radeon RX Vega 
    Address: 11:0 
    Vendor:  Advanced Micro Devices (AMD), ROCm
    Memory:  8176 MByte (8176 MByte free) 
    Active:  false (Unsupported device or driver version.) 
Device 1: 
    Name:    Radeon RX Vega 
    Address: 14:0 
    Vendor:  Advanced Micro Devices (AMD), ROCm
    Memory:  8176 MByte (8176 MByte free) 
    Active:  false (Unsupported device or driver version.) 

Connecting to pool... 
Connected to eth.2miners.com:2020  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker 
New job received: 0x8e0636 Epoch: 378 Target: 000000007fffffff 
Start Mining... 
All devices deselected or failed compatiblity check. Closing lolMiner
```

My system:

CPU: AMD Ryzen 3800XT
GPU: 2*VEGA64 
Driver/LLVM version: MESA 20.2.2
Kernel version: 5.9.8-zen1-1-zen (ArchLinux)

By my knowledge i have opencl-amd installed, not ROCm, luxmark runs perfectly, clinfo gives this:
[gist](https://gist.github.com/plasticbomb1986/7ea8d7f69d20a993654f1071cd4a06a0)
 Im trying to run 1.16a.

**Comment by jgonzis** [comment]
Which AMD Driver do you have installed? Have you installed with the paramaters --opencl=pal,legacy,rocm ?

**Comment by plasticbomb1986** [comment]
i had the opencl-amd aur package [AUR](https://aur.archlinux.org/packages/opencl-amd/).

To check, went and installed ROCm from AUR (archedu), same error.

**Comment by ericluciano** [comment]
Do you resolv?

> i had the opencl-amd aur package [AUR](https://aur.archlinux.org/packages/opencl-amd/).
> 
> To check, went and installed ROCm from AUR (archedu), same error.


Did you solve it? I have the same problem.

**Comment by plasticbomb1986** [comment]
> Do you resolv?
> 
> > i had the opencl-amd aur package [AUR](https://aur.archlinux.org/packages/opencl-amd/).
> > To check, went and installed ROCm from AUR (archedu), same error.
> 
> Did you solve it? I have the same problem.

Nah, found teamredminer, whats been working flawlessly with my cards, and since than, i havent checked others.

**Comment by Kipkurui-mutai** [comment]
@plasticbomb1986  Did you solve this issue? and How?

**Comment by jgonzis** [comment]
Install amd drivers with the parameter 
--opencl=legacy,pal,rocm

I hope that help

**Comment by Kipkurui-mutai** [comment]
@jgonzis in CMD or?

**Comment by jgonzis** [comment]
> @jgonzis Where should I write this "--opencl=legacy,pal,rocm"?

When you install the amdgpupro...

**Comment by Kipkurui-mutai** [comment]
@jgonzis Is there a video to guide me on how to use the miner?

**Comment by jgonzis** [comment]
The best is to

> @jgonzis Is there a video to guide me on how to use the miner?

The best is download from the oficial website :

https://www.amd.com/es/support/graphics/radeon-rx-vega-series/radeon-rx-vega-series/radeon-rx-vega-64

The installation guide:
https://amdgpu-install.readthedocs.io/en/latest/

**Comment by Kipkurui-mutai** [comment]
@jgonzis  Thanks
