### ISSUE TITLE
How to do single-player mining

### ISSUE THREAD

**Issue by lzy2009** [Lolliedieb/lolMiner-releases#950]
How to set up to do single-person mining, I am not very familiar with this LOLMINER

**Comment by pdieppa** [comment]
The program includes some batch file examples that you can use as a template for the coins you are trying to mine.

**Comment by jgonzis** [comment]
> How to set up to do single-person mining, I am not very familiar with this LOLMINER

Just only add in POOL=SOLO" and you will do SOLO Mining... you should have minimum around 300Ghs to be luck enough to get a block in not more than 2 Days...
