### ISSUE TITLE
Dashboard and withdrawel solo mining ton

### ISSUE THREAD

**Issue by koberit** [Lolliedieb/lolMiner-releases#954]
Hi guys,
how can i use a dashbaord und other things like balance and withdrawel like the telegram bot for pool mining within the solo mining?

**Comment by jgonzis** [comment]
> Hi guys, how can i use a dashbaord und other things like balance and withdrawel like the telegram bot for pool mining within the solo mining?

SOLO Mining no Telegram... you will be payed only when you get a block... NO block no payed... Normally Solo will be for around minimum 300Ghs or the options to get a Block it will be difficult...
