### ISSUE TITLE
Authorization problem on all configured pools Terminating lolMiner

### ISSUE THREAD

**Issue by keks2293** [Lolliedieb/lolMiner-releases#958]
How make it stop terminating?

`Pool not reacting to submitted shares for too long. Reconnecting.
Pool not sending data for 300 seconds. Reconnecting.
Average speed (15s): 845.52MH/s | 769.46MH/s | 969.21MH/s | 1684.43MH/s | 733.67MH/s Total: 5002.29 MH/s
Pool not reacting to submitted shares for too long. Reconnecting.
Pool not sending data for 300 seconds. Reconnecting.
Pool not reacting to submitted shares for too long. Reconnecting.
Pool not sending data for 300 seconds. Reconnecting.
Pool not reacting to submitted shares for too long. Reconnecting.
Pool not sending data for 300 seconds. Reconnecting.
Pool not reacting to submitted shares for too long. Reconnecting.
Pool not sending data for 300 seconds. Reconnecting.
DNS resolve error - retrying in two seconds
Pool not reacting to submitted shares for too long. Reconnecting.
Pool not sending data for 300 seconds. Reconnecting.
GPU 3: Share accepted (34864 ms)
Ton job with difficulty 274.88G and giver Ef8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4PgP received.
GPU 0: Share accepted (83532 ms)
GPU 1: Share accepted (84677 ms)
GPU 0: Share accepted (83806 ms)
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1)
GPU 1: Share accepted (84783 ms)
DNS over HTTPS resolve succeeded
GPU 1: Share accepted (84929 ms)
GPU 0: Share accepted (84058 ms)
GPU 2: Share accepted (49780 ms)
GPU 3: Share accepted (35894 ms)
https://server1.whalestonpool.com: Address is not valid
Authorization problem on all configured pools
Terminating lolMiner`

**Comment by evilpaul13** [comment]
Did you sign up on their Telegram first?

**Comment by keks2293** [comment]
> Did you sign up on their Telegram first?

Yes, I think sometimes the connection to the pool is lost and the problem is that the limit of reconnection attempts is triggered, I did not find how I can turn it off

**Comment by jgonzis** [comment]
> How make it stop terminating?
> 
> `Pool not reacting to submitted shares for too long. Reconnecting. Pool not sending data for 300 seconds. Reconnecting. Average speed (15s): 845.52MH/s | 769.46MH/s | 969.21MH/s | 1684.43MH/s | 733.67MH/s Total: 5002.29 MH/s Pool not reacting to submitted shares for too long. Reconnecting. Pool not sending data for 300 seconds. Reconnecting. Pool not reacting to submitted shares for too long. Reconnecting. Pool not sending data for 300 seconds. Reconnecting. Pool not reacting to submitted shares for too long. Reconnecting. Pool not sending data for 300 seconds. Reconnecting. Pool not reacting to submitted shares for too long. Reconnecting. Pool not sending data for 300 seconds. Reconnecting. DNS resolve error - retrying in two seconds Pool not reacting to submitted shares for too long. Reconnecting. Pool not sending data for 300 seconds. Reconnecting. GPU 3: Share accepted (34864 ms) Ton job with difficulty 274.88G and giver Ef8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4PgP received. GPU 0: Share accepted (83532 ms) GPU 1: Share accepted (84677 ms) GPU 0: Share accepted (83806 ms) Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) GPU 1: Share accepted (84783 ms) DNS over HTTPS resolve succeeded GPU 1: Share accepted (84929 ms) GPU 0: Share accepted (84058 ms) GPU 2: Share accepted (49780 ms) GPU 3: Share accepted (35894 ms) https://server1.whalestonpool.com: Address is not valid Authorization problem on all configured pools Terminating lolMiner`

Tonwhales.com have got lot of problems the last week, too much people in there, you can have a look on ton-pool or toncoinpool.io it seems less problems. 

If you don't know how the bot of telegram works then use directly toncoinpool.io
