### ISSUE TITLE
Lolminer 1.42 crashes HiveOS

### ISSUE THREAD

**Issue by Sanchous98** [Lolliedieb/lolMiner-releases#959]
After update from 1.41b to 1.42 HiveOS began to crash instead of generating invalid shares. Tried to use gpus in stock and even to downclock them. Rig contains 5x 3080ti and rx480. Mining pool is toncoinpool.io

**Comment by Sanchous98** [comment]
![Снимок экрана 2022-01-14 в 09 16 38](https://user-images.githubusercontent.com/45293316/149467243-e534a767-ee89-47df-8eeb-7fff5a8e0e23.png)

On the screen is seen where I have downgraded lolminer version. Before that I tried everything

**Comment by jgonzis** [comment]
> After update from 1.41b to 1.42 HiveOS began to crash instead of generating invalid shares. Tried to use gpus in stock and even to downclock them. Rig contains 5x 3080ti and rx480. Mining pool is toncoinpool.io

That crash could be a lot of things, but the most important is that you are not in 1.42.  It could be pool problem that toncoinpool have it 3 days ago.

**Comment by Sanchous98** [comment]
> > After update from 1.41b to 1.42 HiveOS began to crash instead of generating invalid shares. Tried to use gpus in stock and even to downclock them. Rig contains 5x 3080ti and rx480. Mining pool is toncoinpool.io
> 
> That crash could be a lot of things, but the most important is that you are not in 1.42. It could be pool problem that toncoinpool have it 3 days ago.

I don't think so. I tried today to use lolminer 1.42 and it still crashing, while I have a PC with 1060 and rx 580 running on Windows 11 with the same version of miner running for 1.5 day without interrupting neither for pool or local issues. So, I think it's related to OS or video architecture
