### ISSUE TITLE
 Generating light cache for epoch

### ISSUE THREAD

**Issue by lplebrun** [Lolliedieb/lolMiner-releases#96]
Hi, 
Today during a change of epoch my NVIDIA card stopped working.
During the log I will write with capitals letter to pinpoint and give some explanation. I hope the whole thing is clear.

WHEN I STARTED MINING:

         Generating light cache for epoch 378 
------------------------------------------------------- 
Start Mining... 
------------------------------------------------------- 
     Done (2390 ms), size of new DAG: 4048 MByte 
------------------------------------------------------- 
Start DAG gen on GPU 1 (fast mode) 
New job received: 0x44d62f Epoch: 378 Target: 0000000112e0be82 
Start DAG gen on GPU 3 (fast mode) 
Start DAG gen on GPU 2 (fast mode) 

GPU2 DAG GEN IS FLAWLESS.

Start DAG gen on GPU 4 (fast mode) 
Start DAG gen on GPU 0 (fast mode) 
New job received: 0xcd9ff8 Epoch: 378 Target: 0000000112e0be82 
New job received: 0xe3b35f Epoch: 378 Target: 0000000112e0be82 
New job received: 0x51bee9 Epoch: 378 Target: 0000000112e0be82 
Finished DAG gen on GPU 1 (7876 ms) 
Finished DAG gen on GPU 0 (7139 ms) 
Finished DAG gen on GPU 3 (8666 ms) 
Finished DAG gen on GPU 2 (8855 ms) 
Finished DAG gen on GPU 4 (8667 ms) 

DURING THE CHANGE OF EPOCH;

Average speed (30s): 31.31mh/s | 31.11mh/s | 29.19mh/s | 29.64mh/s | 29.64mh/s Total: 150.90 mh/s 

------------------------------------------------------- 
         Generating light cache for epoch 379 
------------------------------------------------------- 
New job received: 0x9ee7ea Epoch: 379 Target: 0000000112e0be82 
------------------------------------------------------- 
     Done (2367 ms), size of new DAG: 4056 MByte 
------------------------------------------------------- 
Start DAG gen on GPU 1 (fast mode) 
Start DAG gen on GPU 3 (fast mode) 
Start DAG gen on GPU 0 (fast mode) 
Start DAG gen on GPU 4 (fast mode) 

**YOU CAN SEE HERE THAT THE MINER DIDNT START DAG GEN ON GPU2 WHICH IS MY ONLY NVIDIA CARD

 
Finished DAG gen on GPU 0 (6730 ms) 
Finished DAG gen on GPU 1 (7829 ms) 
Finished DAG gen on GPU 3 (8584 ms) 
Finished DAG gen on GPU 4 (8707 ms) 
--------------------------------------------- 

Average speed (30s): 21.12mh/s | 20.14mh/s | 15.74mh/s | 18.45mh/s | 18.57mh/s Total: 94.03 mh/s 

GPU2 LOSE HASHING.

Average speed (30s): 31.35mh/s | 31.04mh/s | 0.00mh/s | 29.61mh/s | 29.64mh/s Total: 121.64 mh/s 

GPU2 WITH NO HASHRATE. NO ERROR,

Anyone had the same problem with nvidia gpu?

**Comment by jgonzis** [comment]
Which Nvidia are you using and which driver version?

**Comment by Lolliedieb** [comment]
Interesting ... the miner hangs in the moment the memory is allocated for the next epoch. But usually it should alloc it for 5 epochs early on. I will double check the code if this mechanism does not work.

**Comment by lplebrun** [comment]
it happened again on the change of epoch. Only my nvidia gpu seems to be affected.

OS: Windows 10
Driver:457.30
Card: Asus GTX1070
Miner Version: lolminer 1.16a

**Comment by lplebrun** [comment]
> Interesting ... the miner hangs in the moment the memory is allocated for the next epoch. But usually it should alloc it for 5 epochs early on. I will double check the code if this mechanism does not work.

Did you find anything? It is still happening, all drivers are up-to-date and the mining software too. I have no other stability issues.

**Comment by Lolliedieb** [comment]
Is fixed with 1.25 / 1.26
