### ISSUE TITLE
lolminer unstable hashrate on tonpool

### ISSUE THREAD

**Issue by thiefhigh02** [Lolliedieb/lolMiner-releases#963]
i got unstable hasrate on pool after 8 minutes my second gpu still not running.

---------------------------------------------
Statistics (07:49:43); Mining: SHA256-TON
Connected to: https://server1.whalestonpool.com:443
Uptime: 0h 8m 3s
      Name        Speed     Pool  Shares   Best  Power    Eff.  CCLK  MCLK  Core  Junc  Fan
                   MH/s     MH/s  A/S/Hw  Share      W  MH/s/W   MHz   MHz  Temp  Temp  Pct
GPU 0 RX 6700XT 2412.28  2276.42   4/0/0   4.1T   88.5  27.104  2233    24    66    83   30
GPU 1 RX 6600   1749.25     0.00   0/0/0    0.0   76.5  22.708  2311    20    55    70   56
---------------------------
Total           4161.53  2276.42   4/0/0   4.1T  165.0  25.064

even after running only got small hashrate

Statistics (07:55:43); Mining: SHA256-TON
Connected to: https://server1.whalestonpool.com:443
Uptime: 0h 14m 3s
      Name        Speed     Pool  Shares   Best  Power    Eff.  CCLK  MCLK  Core  Junc  Fan
                   MH/s     MH/s  A/S/Hw  Share      W  MH/s/W   MHz   MHz  Temp  Temp  Pct
GPU 0 RX 6700XT 2414.63  1956.43   6/0/0   4.1T   88.7  27.058  2241    10    68    84   28
GPU 1 RX 6600   1743.06   978.21   3/0/0   2.5T   76.5  22.631  2310    20    55    70   57
---------------------------
Total           4157.69  2934.64   9/0/0   4.1T  165.3  25.007

please fix this issue,thanks
currently i'm back to 1.41b much stable hashrate for me rather than 1.42.

**Comment by jgonzis** [comment]
> i got unstable hasrate on pool after 8 minutes my second gpu still not running.
> 
> ## Statistics (07:49:43); Mining: SHA256-TON
> Connected to: https://server1.whalestonpool.com:443
> Uptime: 0h 8m 3s
> Name Speed Pool Shares Best Power Eff. CCLK MCLK Core Junc Fan
> MH/s MH/s A/S/Hw Share W MH/s/W MHz MHz Temp Temp Pct
> GPU 0 RX 6700XT 2412.28 2276.42 4/0/0 4.1T 88.5 27.104 2233 24 66 83 30
> GPU 1 RX 6600 1749.25 0.00 0/0/0 0.0 76.5 22.708 2311 20 55 70 56
> Total 4161.53 2276.42 4/0/0 4.1T 165.0 25.064
> 
> even after running only got small hashrate
> 
> ## Statistics (07:55:43); Mining: SHA256-TON
> Connected to: https://server1.whalestonpool.com:443
> Uptime: 0h 14m 3s
> Name Speed Pool Shares Best Power Eff. CCLK MCLK Core Junc Fan
> MH/s MH/s A/S/Hw Share W MH/s/W MHz MHz Temp Temp Pct
> GPU 0 RX 6700XT 2414.63 1956.43 6/0/0 4.1T 88.7 27.058 2241 10 68 84 28
> GPU 1 RX 6600 1743.06 978.21 3/0/0 2.5T 76.5 22.631 2310 20 55 70 57
> Total 4157.69 2934.64 9/0/0 4.1T 165.3 25.007
> 
> please fix this issue,thanks currently i'm back to 1.41b much stable hashrate for me rather than 1.42.

Problem is whalestonpool. It has been last week several problems with that pool, it has been reported  in their Telegram group. Try other pool or wait until pool problems are solved.
