### ISSUE TITLE
lolminer amd RX580 not mining trouble shooting OpenCL

### ISSUE THREAD

**Issue by Eagles1971** [Lolliedieb/lolMiner-releases#964]
Hi,

Just downloaded the newest version of lolminer 1.42 on linux mint 20.3 using AMD RX580, with driver version 21.40.1, the miner starts but nothing is happening, and just keeps running, any help would be great. Hopefully this screen shot will help to understand the problem thank you.

![Screenshot from 2022-01-16 18-29-48](https://user-images.githubusercontent.com/97851330/149682887-82bc9e2b-84ed-447f-9248-9b944386c1fa.png)

**Comment by jgonzis** [comment]
> Hi,
> 
> Just downloaded the newest version of lolminer 1.42 on linux mint 20.3 using AMD RX580, with driver version 21.40.1, the miner starts but nothing is happening, and just keeps running, any help would be great. Hopefully this screen shot will help to understand the problem thank you.
> 
> ![Screenshot from 2022-01-16 18-29-48](https://user-images.githubusercontent.com/97851330/149682887-82bc9e2b-84ed-447f-9248-9b944386c1fa.png)

That seems to be the AMD Driver version... Could you try please with the 20.40?. The 21.40 are not supported at the moment.

**Comment by Eagles1971** [comment]
Hello jgonzis

Tried installing driver 20.40 and it tells me the version is 21.3 when installed see below.
Tried lolminer again and it's does the same thing, also tried installing the version with opencl from the documents from AMD LINUX installation guide also see below but I get, command not found.

What would be the next step from here ?

thank you.

![Screenshot from 2022-01-17 20-03-34](https://user-images.githubusercontent.com/97851330/149854291-bfe5f991-ca62-4b99-9492-cc53d0d25859.png)

![Screenshot from 2022-01-17 20-19-22](https://user-images.githubusercontent.com/97851330/149854398-2e5e3ca2-1979-476f-ae13-4548c7d666f5.png)
