### ISSUE TITLE
Lolminer - Toncoin 1.42 Windows New Error Occur after mining 2 days straight

### ISSUE THREAD

**Issue by donPuerto** [Lolliedieb/lolMiner-releases#965]
![image](https://user-images.githubusercontent.com/9329005/149685663-91b275e8-7524-4bea-8681-79cd4849b400.png)

**Comment by oiG8Uchi** [comment]
I also got the same error

**Comment by Nixkita** [comment]
same issue on Rave OS! Lol team, please resolve immediately!

**Comment by jgonzis** [comment]
> same issue on Rave OS! Lol team, please resolve immediately!

It is not lolMiner problem... Is tonwhales problem... Tonwhales hat several problems last week, it has been reported also in his telegram. Wait until tonwhales solve the problem or use another pool, like ton-pool or toncoinpool.io
