### ISSUE TITLE
lolminer 1.42 restarted by timeout!

### ISSUE THREAD

**Issue by Nixkita** [Lolliedieb/lolMiner-releases#967]
Hello dev team. I used lol miner 1.42 with my Rave OS for several days and it worked very well. However tonight it crashed and didn't restart, here's the log, please help to resolve:
2022/01/17 01:19:55 ERROR: lolminer-1.42: restarted by timeout
2022/01/17 01:19:55 MINER LOG [lolminer-1.42]: 
##################################### START MINER LOG #####################################
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
01:19:47 Average speed (15s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds 
Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) 
DNS over HTTPS resolve failed - switching to standard resolve 
DNS resolve error - retrying in two seconds
###################################### END MINER LOG ######################################

**Comment by jgonzis** [comment]
> Hello dev team. I used lol miner 1.42 with my Rave OS for several days and it worked very well. However tonight it crashed and didn't restart, here's the log, please help to resolve: 2022/01/17 01:19:55 ERROR: lolminer-1.42: restarted by timeout 2022/01/17 01:19:55 MINER LOG [lolminer-1.42]: ##################################### START MINER LOG ##################################### DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds 01:19:47 Average speed (15s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1) DNS over HTTPS resolve failed - switching to standard resolve DNS resolve error - retrying in two seconds ###################################### END MINER LOG ######################################

As comment in the other post... Tonwhales server problems, their announced in their telegram group too. That has been passed in the last week several times. Wait until tonwhales solve the problem or try other pools like ton-pool or toncoinpool.io
