### ISSUE TITLE
Memory object allocation failure on 8GB AMD RX 580 with epoch 379

### ISSUE THREAD

**Issue by twiddledeebit** [Lolliedieb/lolMiner-releases#97]
6-GPU Windows 10 x64 miner with (5) 8GB RX 480 cards and (1) 8GB RX 580 card. Upon startup lolMiner reports "GPU 2: Allocation of DAG failed with error: Memory object allocation failure" and shuts down the card. Issue seems to have started at epoch 379. Using Crimson BETA 22.19.659.0 driver on all cards.

**Comment by jgonzis** [comment]
> 6-GPU Windows 10 x64 miner with (5) 8GB RX 480 cards and (1) 8GB RX 580 card. Upon startup lolMiner reports "GPU 2: Allocation of DAG failed with error: Memory object allocation failure" and shuts down the card. Issue seems to have started at epoch 379. Using Crimson BETA 22.19.659.0 driver on all cards.

Why you don't try AMD 20.4.2 for example in compute mode?

**Comment by twiddledeebit** [comment]
I can try AMD Adrenalin driver in compute mode but blockchain driver is working fine on the (5) RX 480 cards. Curious why you suggest 20.4.2 when current standard AMD driver is 20.11.3? If I'm going to update the driver, shouldn't I go with most current?

**Comment by jgonzis** [comment]
I say 20.4.2 because is the last version that works perfectly with OverdriveNTool 0.28. If you use AMD driver to regulate voltage go to last version.

**Comment by twiddledeebit** [comment]
I cloned the SSD to another rig so I could troubleshoot the RX580 by itself. It worked okay in the other rig with no configuration changes (using the same Crimson blockchain driver). I put the RX580 back in the original rig with (4) RX480s (one of the other RX480s had failed with a hardware issue) and it also worked fine. Possibly the issue was a loose connection or some kind of interaction with the RX480 that ended up failing.
