### ISSUE TITLE
100% usage

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [Lolliedieb/lolMiner-releases#971]
Had this problem before, but thought it had been fixed recently. Lolminer is using a 100% of a cpu.

  ```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                         
 9923 root      20   0 52.031g 595032 440688 S 101.3  7.5 257:48.08 lolMiner                                        
```

It used to happen when mining eth+zil, but now on aion

The setup on hive is

```
AlgoAION
Passmp=8
Port%URL_PORT%
Server%URL_HOST%
Template%WAL%.%WORKER_NAME%
User Config--devices 1
```

**Comment by jgonzis** [comment]
Could it be a Nvidia??

**Comment by basking-in-the-sun2000** [comment]
Indeed, sorry didn't gave much info

I tried nvidia-smi, and it is weird

```
 Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|                                                    
|    0   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
|    0   N/A  N/A      6273      C   lolMiner                          127MiB |                                                    
|    0   N/A  N/A      6362      C   t-rex                            4957MiB |                                                    
|    1   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
|    1   N/A  N/A      6273      C   lolMiner                          925MiB |                                                    
|    2   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
|    2   N/A  N/A      6219      C   ./miniZ                          3947MiB |                                                    
|    2   N/A  N/A      6273      C   lolMiner                           99MiB |                                                    
|    3   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
|    3   N/A  N/A      6273      C   lolMiner                          149MiB |                                                    
|    3   N/A  N/A      6362      C   t-rex                            4979MiB |       
```                                             


t-rex has "devices": "0,3"
lol has --devices 1
miniz -cd 2
teamread doesn't have anything, since I only have 1 amd card


seems that lol doesn't like to play nice and wants all the toys

**Comment by jgonzis** [comment]
> Indeed, sorry didn't gave much info
> 
> I tried nvidia-smi, and it is weird
> 
> ```
>  Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|                                                    
> |    0   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
> |    0   N/A  N/A      6273      C   lolMiner                          127MiB |                                                    
> |    0   N/A  N/A      6362      C   t-rex                            4957MiB |                                                    
> |    1   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
> |    1   N/A  N/A      6273      C   lolMiner                          925MiB |                                                    
> |    2   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
> |    2   N/A  N/A      6219      C   ./miniZ                          3947MiB |                                                    
> |    2   N/A  N/A      6273      C   lolMiner                           99MiB |                                                    
> |    3   N/A  N/A      2841      G   /usr/lib/xorg/Xorg                  6MiB |                                                    
> |    3   N/A  N/A      6273      C   lolMiner                          149MiB |                                                    
> |    3   N/A  N/A      6362      C   t-rex                            4979MiB |       
> ```
> 
> t-rex has "devices": "0,3" lol has --devices 1 miniz -cd 2 teamread doesn't have anything, since I only have 1 amd card
> 
> seems that lol doesn't like to play nice and wants all the toys

I know what is happening AION was developed for AMD at the beginning, so the kernel for Nvidia is not well developed for AION coin. That's the reason of the full CPU usage.... the Equihash algos need to be rewrited specific for Nvidia for sure.

**Comment by basking-in-the-sun2000** [comment]
no problem. Know that aion isn't too popular, so I will try another miner. You have a nice miner, so I usually give it a try when I have an option
