### ISSUE TITLE
0MHs after internet outage

### ISSUE THREAD

**Issue by xsoft** [Lolliedieb/lolMiner-releases#973]
Hi,
when internet goes for for 10 minutes, lolminer would not recover itselfs.

```Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
-------------------------------------------
Statistics (01:09:35); Mining: Ethash
Connected to:
Uptime: 78h 32m 2s
      Name        Speed    Pool  --lhrtune     Shares    Best
                   MH/s    MH/s                A/S/Hw   Share
GPU 0 RTX 3060 Ti  0.00   34.99       14.4   2303/0/0   28.0T
GPU 1 RTX 3060 Ti  0.00   36.86       17.8   2426/0/0   24.9T
GPU 2 RTX 3060 Ti  0.00   37.25       19.4   2452/0/0   84.9T
GPU 3 RTX 3060 Ti  0.00   33.95       15.6   2235/0/0  130.7T
GPU 4 RTX 3060 Ti  0.00   35.72       19.4   2351/0/0    5.8T
---------------------------
Total              0.00  178.76             11767/0/0  130.7T

        Power    Eff.  CCLK  MCLK  Core  Fan  --lhrtune
            W  MH/s/W   MHz   MHz  Temp  Pct
GPU 0    64.8   0.000  1470  6800    40   30       14.4
GPU 1    66.8   0.000  1425  6800    51    0       17.8
GPU 2    61.9   0.000  1440  6800    58    0       19.4
GPU 3    68.1   0.000  1485  6800    39   30       15.6
GPU 4    63.3   0.000  1455  6800    53    0       19.4
-- -------------------------
Total   325.0   0.000
---------------------------------------------
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
```

Im on Linux, HiveOS, lolminer 1.42 with params:
`--dns-over-https 0 --tls off --basecolor on --compactaccept off`

**Comment by jgonzis** [comment]
> Hi, when internet goes for for 10 minutes, lolminer would not recover itselfs.
> 
> ```
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> -------------------------------------------
> Statistics (01:09:35); Mining: Ethash
> Connected to:
> Uptime: 78h 32m 2s
>       Name        Speed    Pool  --lhrtune     Shares    Best
>                    MH/s    MH/s                A/S/Hw   Share
> GPU 0 RTX 3060 Ti  0.00   34.99       14.4   2303/0/0   28.0T
> GPU 1 RTX 3060 Ti  0.00   36.86       17.8   2426/0/0   24.9T
> GPU 2 RTX 3060 Ti  0.00   37.25       19.4   2452/0/0   84.9T
> GPU 3 RTX 3060 Ti  0.00   33.95       15.6   2235/0/0  130.7T
> GPU 4 RTX 3060 Ti  0.00   35.72       19.4   2351/0/0    5.8T
> ---------------------------
> Total              0.00  178.76             11767/0/0  130.7T
> 
>         Power    Eff.  CCLK  MCLK  Core  Fan  --lhrtune
>             W  MH/s/W   MHz   MHz  Temp  Pct
> GPU 0    64.8   0.000  1470  6800    40   30       14.4
> GPU 1    66.8   0.000  1425  6800    51    0       17.8
> GPU 2    61.9   0.000  1440  6800    58    0       19.4
> GPU 3    68.1   0.000  1485  6800    39   30       15.6
> GPU 4    63.3   0.000  1455  6800    53    0       19.4
> -- -------------------------
> Total   325.0   0.000
> ---------------------------------------------
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> ```
> 
> Im on Linux, HiveOS, lolminer 1.42 with params: `--dns-over-https 0 --tls off --basecolor on --compactaccept off`

Complete 0 after 78H. The strange is that show not pool connected...

**Comment by jgonzis** [comment]
> Any tips here? --watchdog seems to be for card-crash issue. Not for Internet disconnection. It seems like a school mistake to NOT continue after short internet outage. Any 'retry' param? When backup pool is present, how often is/are those pools check? Is there check for resolve part also?
> 
> This issue seems to really easy to simulate, test and verify. Just unplug the cable.

I did a bat file to check in case hashrate goes to 0... to reboot it. let me check if I find it..

**Comment by xsoft** [comment]
Reboot batch? Seems like Windows solution. Hmm ... ```shutdown.exe /r /t 00```
But Im not on Windows.
Btw, are you sure that reboot script (via --watchdog abc.bat) is called when INTERNET does down? Its on GPU crash, isnt it? According manual.

Also .. reboot entire farm just because internet issue (which affects entire farm) is NOT good approach.

Fix this but would be better.

**Comment by jgonzis** [comment]
> Reboot batch? Seems like Windows solution. Hmm ... `shutdown.exe /r /t 00` But Im not on Windows. Btw, are you sure that reboot script (via --watchdog abc.bat) is called when INTERNET does down? Its on GPU crash, isnt it? According manual.
> 
> Also .. reboot entire farm just because internet issue (which affects entire farm) is NOT good approach.
> 
> Fix this but would be better.

Which OS are you using? Sorry I thought you were in Windows

**Comment by xsoft** [comment]
> Which OS are you using? Sorry I thought you were in Windows

See 1st post, next-to-last line.

**Comment by jgonzis** [comment]
> > Which OS are you using? Sorry I thought you were in Windows
> 
> See 1st post, next-to-last line.

Ok... so I could be done with a curl reading the API

**Comment by pdieppa** [comment]
Since you are using HiveOS, I would suggest you setup the Hashrate Watchdog and set the hash rate for the algo. Here is a sample screen of a disabled Watchdog.

![image](https://user-images.githubusercontent.com/74556152/150691612-717b7a01-db79-49d8-af2c-7fc341bef774.png)

**Comment by jgonzis** [comment]
1.46 should solve some of these reconnections
