### ISSUE TITLE
Support for the new 3080 12 GB cards 

### ISSUE THREAD

**Issue by Brellic** [Lolliedieb/lolMiner-releases#976]
Is there any update for supporting the New 12 GB cards?

**Comment by jgonzis** [comment]
> Is there any update for supporting the New 12 GB cards?

It will be released with the 1.43 for sure. You can also go to the Telegram group in case the Dev need one to test it

**Comment by Brellic** [comment]
Thanks for the update

**Comment by GenCodeInc** [comment]
> > Is there any update for supporting the New 12 GB cards?
> 
> It will be released with the 1.43 for sure. You can also go to the Telegram group in case the Dev need one to test it

Thanks, any ETA on 1.43 and estimated MH/s.
Getting in the 60s now.

I don't have Telegram so hopefully its here soon, thanks for all your hard work.
EVGA 3080 12GB FTW

**Comment by jgonzis** [comment]
> > > Is there any update for supporting the New 12 GB cards?
> > 
> > 
> > It will be released with the 1.43 for sure. You can also go to the Telegram group in case the Dev need one to test it
> 
> Thanks, any ETA on 1.43 and estimated MH/s. Getting in the 60s now.
> 
> I don't have Telegram so hopefully its here soon, thanks for all your hard work. EVGA 3080 12GB FTW

In 12hours will be released with support for 3080 12Gb

**Comment by GenCodeInc** [comment]
Thanks so much for the quick update, sure hope it beats the 63MHs :)
