### ISSUE TITLE
Take out global.config.json for solo TON

### ISSUE THREAD

**Issue by seoseo29** [Lolliedieb/lolMiner-releases#979]
Hi! Take out global.config.json for solo TON so that you can mine on your node

**Comment by jgonzis** [comment]
> Hi! Take out global.config.json for solo TON so that you can mine on your node

SOLO doesn't need a node to mine, it directly mine to the Givers...

**Comment by seoseo29** [comment]
This is the problem, there are a lot of solutions that are late due to ping, so you need to beckon to your server that is closer and to do this, take out the global.config file.json in which to specify only one node

**Comment by jgonzis** [comment]
> This is the problem, there are a lot of solutions that are late due to ping, so you need to beckon to your server that is closer and to do this, take out the global.config file.json in which to specify only one node

NO. You only need to add SOLO to the server or parameter --ton-mode 5 that's all to mine for SOLO

**Comment by seoseo29** [comment]
Вопрос не в  том, что манит соло, а в том, что куча просроченых шар при ктоторых нет начисления 100 тон, рекомендации разработчиков  - манить на свою ноду, а для этого в голобал конфиг указать не общие ноды мировые, а локальные ближе всего к майнеру, поэтому вынесети глобал нод как отдельный инструмент выбора

**Comment by seoseo29** [comment]
![image](https://user-images.githubusercontent.com/79798383/152749514-7a393a8a-a7b9-4ed4-be0a-d94009769c2e.png)
Видите, решнеие найдено? а начисления 100 тон нет

**Comment by seoseo29** [comment]
И таких решений очень много, выведите global.config.json отдельной настройкой

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/79798383/152749514-7a393a8a-a7b9-4ed4-be0a-d94009769c2e.png) Видите, решнеие найдено? а начисления 100 тон нет

возможно, ваше решение устарело, кто-то отправил его раньше вас.

**Comment by seoseo29** [comment]
у нас не может устаревать половину решений, если мы переключаем майнить в соло https://github.com/tontechio/pow-miner-gpu/releases/tag/20211230.1 то все нормально, вашим же майнером половину решений устаревает или их кто то перехватывает. Но майнером https://github.com/tontechio/pow-miner-gpu/releases/tag/20211230.1 мы маним на свою ноду, поэтому и просим вынести global.config.json для того, что бы в нем указать только одну свою ноду. Спасибо!

**Comment by seoseo29** [comment]
Или дайте адреса куда уходит трафик соло, мы перенаправим трафик на свою ноду
