### ISSUE TITLE
Zelhash K80 K10

### ISSUE THREAD

**Issue by DX664** [Lolliedieb/lolMiner-releases#983]
running GTX 1060, K80, K10 in that order.  hash rate 29sol Watchdog set to -off in arg however k80 and k10 are reported as crashed even tho they are finding shares and the shares are reported as accepted. When this happens my speed is reported as 0 in Hiveos until i receive a new target then  most times everything returns to normal for a period of time sometime. However screen says new job received but sol is 0 and all hiveos is blank. overclock is turned off (thinking this might solve problem ,but not) I know you recommend Miniz but lolminer has been working great for 2 months.
  equihash 125/4

unable to insert screen capture
GTX 1060 6GB 19sol..oc 24sol
K80 5 sol x 2 no oc
k10 1.5 sol x 2 no oc
my setup
Z390 DESIGNARE-CF Gigabyte Technology Co., Ltd. (F9k 02/24/2021) 
6 × Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz AES
Linux 5.10.0-hiveos #83

**Comment by DX664** [comment]
Problem solved.

US-east server was dropping connection to K10. moved to west and everything is back to normal.

**Comment by DX664** [comment]
Ok. Issue not resolved. Miner freezes . resorting to Miniz.

**Comment by jgonzis** [comment]
> Ok. Issue not resolved. Miner freezes . resorting to Miniz.

Equihash with Nvidia is not the best development. It is for AMD, for Nvidia extra work is  need it
