### ISSUE TITLE
Dual mining ton+eth on RaveOS

### ISSUE THREAD

**Issue by Nixkita** [Lolliedieb/lolMiner-releases#986]
Hi there. Could you send the instructions if any for configuring dual mining eth+ton on RaveOS.

**Comment by Maythecoffee** [comment]
https://github.com/ravinos/custom_mining
you need to add miner as custom (make zip file following instructions above or ask creator to share such pack) or may be just wait till Rave will add this new ,imer

**Comment by Maythecoffee** [comment]
fixed in Rave
