### ISSUE TITLE
Cclk and mclk commands not working...

### ISSUE THREAD

**Issue by allpaspartou** [Lolliedieb/lolMiner-releases#987]
Hi my friends! I can't make the mclk and cclk commands to work on lolminer 1.42 for ton coin!

Mining rig 1x3060 lhr +2x3080ti
Driver: 496.49 or 511.23
Os: windows 10

Ton coin batch file is working fine if I just click and start it! But when i put the --cclk and --mclk commands on the batch file is says that these commands are not recognized as internal or external commands! If i start it with admin privileges....it says the same! If i start the cmd with admin privileges and start the batch file from there...it says nothing...but the commands are not applied at all!

Can someone help please???

**Comment by jgonzis** [comment]
> Hi my friends! I can't make the mclk and cclk commands to work on lolminer 1.42 for ton coin!
> 
> Mining rig 1x3060 lhr +2x3080ti Driver: 496.49 or 511.23 Os: windows 10
> 
> Ton coin batch file is working fine if I just click and start it! But when i put the --cclk and --mclk commands on the batch file is says that these commands are not recognized as internal or external commands! If i start it with admin privileges....it says the same! If i start the cmd with admin privileges and start the batch file from there...it says nothing...but the commands are not applied at all!
> 
> Can someone help please???

Did you use with administrator privileges?

**Comment by allpaspartou** [comment]
I have tried everything! With or without admin privileges!

**Comment by jgonzis** [comment]
> I have tried everything! With or without admin privileges!

Try directly with a CMD administrator:

nvidia-smi -lgc clock value
nvidia-smi -lmc memory_value

**Comment by allpaspartou** [comment]
> > I have tried everything! With or without admin privileges!
> 
> Try directly with a CMD administrator:
> 
> nvidia-smi -lgc clock value nvidia-smi -lmc memory_value

That way it works...but ...immediately i lose msi afterburner! It stops showing frequencies....what gpus are connected...!

**Comment by allpaspartou** [comment]
> > > I have tried everything! With or without admin privileges!
> > 
> > 
> > Try directly with a CMD administrator:
> > nvidia-smi -lgc clock value nvidia-smi -lmc memory_value
> 
> That way it works...but ...immediately i lose msi afterburner! It stops showing frequencies....what gpus are connected...!

Edit!!!! Reinstalled msi afterburner and it works for now!
