### ISSUE TITLE
Conversation protocol with https://toncoinpool.io

### ISSUE THREAD

**Issue by wwarlock** [Lolliedieb/lolMiner-releases#988]
Dear developers,

How lolminer is connecting to https://toncoinpool.io/: ws, wss, http, https?
And which protocols used to conversate further: GetWork, stratum?
Is actual the link https://github.com/toncoinpool/stratum-miner/blob/main/docs/stratum.md ?

May you describe or attach the conversation example?

**Comment by jgonzis** [comment]
> Dear developers,
> 
> How lolminer is connecting to https://toncoinpool.io/: ws, wss, http, https? And which protocols used to conversate further: GetWork, stratum? Is actual the link https://github.com/toncoinpool/stratum-miner/blob/main/docs/stratum.md ?
> 
> May you describe or attach the conversation example?

Pool for Toncoinpool.io is:

wss://pplns.toncoinpool.io/stratum

**Comment by wwarlock** [comment]
Maybe I was unclear, I know that pool and my question is not where it located or how connect to it.
I want to know how is your miner is working with it.
I am asking as the developer not as the user.

**Comment by jgonzis** [comment]
> Maybe I was unclear, I know that pool and my question is not where it located or how connect to it. I want to know how is your miner is working with it. I am asking as the developer not as the user.

Stratum TCO

**Comment by wwarlock** [comment]
Thank you for the answer.
As I see lolminer is accepting stratum messages even on HTTP.
For example, that is written in the log after subscription:
```bash
Subscribed to stratum server. Pool difficulty: 39841.78T
Authorized worker: EQBSOMEwalletNumberHeremr
Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
```
Which next message is required to force lolminer start mining?

**Comment by jgonzis** [comment]
> Thank you for the answer. As I see lolminer is accepting stratum messages even on HTTP. For example, that is written in the log after subscription:
> 
> ```shell
> Subscribed to stratum server. Pool difficulty: 39841.78T
> Authorized worker: EQBSOMEwalletNumberHeremr
> Average speed (10s): 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s | 0.00MH/s Total: 0.00 MH/s
> ```
> 
> Which next message is required to force lolminer start mining and send back to the pool mining results?

On https doesn't work... use the wss

**Comment by wwarlock** [comment]
I see, thanks

**Comment by wwarlock** [comment]
Still having the problem even with wss.

The miner-side connection looks like
```
Connecting to pool... 
Ton pool connection mode: toncoinpool.io stratum (--ton-mode 3) 
Connected to wss://127.0.0.1/stratum(127.0.0.1):443  (TLS enabled)
TLS Handshake success 
Websocket handshare done with pool wss://127.0.0.1/stratum
Average speed (15s): 0.00 Mh/s
Lost connection to stratum server wss://127.0.0.1/stratum:443 or server not reachable. 
Trying to connect in 5 second(s) 
Ton pool connection mode: toncoinpool.io stratum (--ton-mode 3) 
```

The pool log looks like:
```
INFO:     ('127.0.0.1', 53794) - "WebSocket /stratum" [accepted]
INFO:     ('127.0.0.1', 443) - job sent to miner {'seed': 169373057170662217903318295427747828433, 'complexity': 6083979197911564836366055970541554992384580489780762130039009, 'iterations': 100000000000, 'giver': 'Ef_NSzfDJI1A3rOM0GQm7xsoUXHTgmdhN5-OrGD8uwL2JHBa'}
INFO:     ('127.0.0.1', 53794) - connection data from client miner {"id": 1, "method": "mining.subscribe", "params": ["lolMiner 1.43", null, null, null]}

INFO:     ('127.0.0.1', 443) - subscribe response sent to miner {'seed': 169373057170662217903318295427747828433, 'complexity': 6083979197911564836366055970541554992384580489780762130039009, 'iterations': 100000000000, 'giver': 'Ef_NSzfDJI1A3rOM0GQm7xsoUXHTgmdhN5-OrGD8uwL2JHBa'}: {"id": 1, "result": [null, "6083979197911564836366055970541554992384580489780762130039009"], "error": null}
```

Sometime miner is sending "mining.authorize", but mostly not.
I don't understand why this happens and what else required.

**Comment by wwarlock** [comment]
I've thrown out of project the http.
Now lolMiner trying to connect via plain tcp-sockets.
It is sending SSL-headers and after succesfull handshake coming the silence.
Sometimes it drop the connection.
Here is the code written to test the connection.
![Снимок экрана от 2022-02-07 18-31-47](https://user-images.githubusercontent.com/478413/152819247-5e487643-0cc0-4cb8-866e-310e81fdf18b.png)

**Comment by jgonzis** [comment]
> I've thrown out of project the http. Now lolMiner trying to connect via plain tcp-sockets. It is sending SSL-headers and after succesfull handshake coming the silence. Sometimes it drop the connection. Here is the code written to test the connection. ![Снимок экрана от 2022-02-07 18-31-47](https://user-images.githubusercontent.com/478413/152819247-5e487643-0cc0-4cb8-866e-310e81fdf18b.png)

Honestly, I'm sorry I cannot help you on that ... that is another level for me

**Comment by wwarlock** [comment]
May you share the little part of code where lolMiner is conversating with any stratum ton-pool?
