### ISSUE TITLE
Unable to find any openCL devices?

### ISSUE THREAD

**Issue by dhershko2** [Lolliedieb/lolMiner-releases#99]
clean install of ubuntu 20.04, v 1.16.  6 rx580's, can see them in lshw and dmesg, all seems ok.

getting "No OpenCL devices found in your system"
same error when running --list-devices

saw some references to driver issues with 20.04.

any suggestions?

**Comment by ChesDonno** [comment]
Have you install amdpro or ROCm?

**Comment by dhershko2** [comment]
I tried both, and a variety of other things that went down a bad path, package mess then the machine wouldnt recognize the cards.  Gave up on 20.04 and now on 18.04.   Will close this out - thx for reply.
