### ISSUE TITLE
Corrupt DAG file

### ISSUE THREAD

**Issue by zloyjoy** [Lolliedieb/lolMiner-releases#991]
LOL1,42 on overclocked 3060ti creates DAGs with a bunch of errors, repairs them for a long time and painfully, but then it works fine. The question is, does he have a command to disable overclocking while creating the DAG?

**Comment by jgonzis** [comment]
> LOL1,42 on overclocked 3060ti creates DAGs with a bunch of errors, repairs them for a long time and painfully, but then it works fine. The question is, does he have a command to disable overclocking while creating the DAG?

Reduce Memory OC, is not a miner problem. It could be memory degratation... that happens with high Memory OC
