### ISSUE TITLE
How to /where download ver 1.43?

### ISSUE THREAD

**Issue by iban83** [Lolliedieb/lolMiner-releases#992]

**Comment by OtavioPontes24** [comment]
help

**Comment by queinnec35** [comment]
yes , i am on hiveos , and i have just the 1.42 , when i put --dualmode TONDUAL --dualpool https://pool.services.tonwhales.com --dualuser EQAjod0llfE8Ph5K_PziHh0P4Nd3plXDr28P7dB2rA8G9I4K , nothing happen, the card just mine ETH like usualy

**Comment by RedBoardDev** [comment]
You need 1.43 but it doesn't exist, it's a delirium :') :')

**Comment by jgonzis** [comment]
Now released
