### ISSUE TITLE
extra commands for eth+ton double mining don't work for me

### ISSUE THREAD

**Issue by FOXHARD1** [Lolliedieb/lolMiner-releases#994]
extra commands for eth+ton double mining don't work for me, am i doing something wrong? follow data I got here:

--dualmode TONDUAL --dualpool https://next.ton-pool.com --dualuser my wallet --devices 0,1,2,3

**Comment by 3uncol** [comment]
you must have lolminer 1.43, that will be release today

**Comment by FOXHARD1** [comment]
> you must have lolminer 1.43, that will be release today

I'm already using it

**Comment by FOXHARD1** [comment]
> you must have lolminer 1.43, that will be release today

I understand how you hear an update today of the miner on hive the ones that said it was available dual miner I thought it would be it but it says 1.42 thanks

**Comment by kiyoung89** [comment]
What time is version 1.43 updated today?

**Comment by mininggago** [comment]
> What time is version 1.43 updated today?

It is released
