### ISSUE TITLE
High CPU usage on RocketLake platform(1.42)

### ISSUE THREAD

**Issue by edisonchan** [Lolliedieb/lolMiner-releases#995]
![image](https://user-images.githubusercontent.com/8596506/152475970-56f845da-85ad-470d-8764-a8f5361bbb77.png)

Platform:
CPU: Core i7 11700K

This problem only appear on rocket lake platform so far, there is not such problem on my another system that have Zen3(5800x, below):
![image](https://user-images.githubusercontent.com/8596506/152476435-8326c57c-e2df-404f-a29a-400dfc0d193a.png)

**Comment by jgonzis** [comment]
Which algo are you using?

**Comment by edisonchan** [comment]
> Which algo are you using?

TON only.

This problem is still appear in 1.43.

my display is connected to the iGPU of 11700k.

**Comment by edisonchan** [comment]
In eth + ton dual mine mode, the cpu usage will reduce to almost 0%.

So I think there is somthing happen while Ton only.

**Comment by jgonzis** [comment]
> In eth + ton dual mine mode, the cpu usage will reduce to almost 0%.
> 
> So I think there is something happen while Ton only.

Could it be something with the TON... max perfomance

**Comment by edisonchan** [comment]
> > In eth + ton dual mine mode, the cpu usage will reduce to almost 0%.
> > So I think there is something happen while Ton only.
> 
> Could it be something with the TON... max perfomance

I am not sure, I think 1.2 GHash/s(1 RTX 3050) should not make a big impact to the CPU.

**Comment by jgonzis** [comment]
No it shouldn't...

**Comment by jgonzis** [comment]
Last release should solve some of that small glitches
