### ISSUE TITLE
RTX 3060 not mine TON

### ISSUE THREAD

**Issue by viper1986** [Lolliedieb/lolMiner-releases#998]
I setup lolminer to mine ETH+TON but two 3060 does not mine TON
![image](https://user-images.githubusercontent.com/19300597/152524130-7d7b9d12-a5d2-4fa2-8628-306f5a08bcc9.png)

**Comment by viper1986** [comment]
Ok I solve the problem. 
After upgrade Hive Os cards are mining.

**Comment by jgonzis** [comment]
Normally Fix Core Clock and no Power Limit
