### ISSUE TITLE
3080 12GB Results 1.43

### ISSUE THREAD

**Issue by GenCodeInc** [Lolliedieb/lolMiner-releases#999]
It still does not seem to unlock anything as an LHR, still getting 62MHs

I did see this
GPU 1: measured GPU raw speed: 73.31MH/s (Memory clock: 10225 mhz)
GPU 1: does not seem to be LHR - sorry for bothering you

Full results (EVGA 3080 12GB FTW)

+---------------------------------------------------------+
|   _       _ __  __ _                   _  _  _  _____   |
|  | | ___ | |  \/  (_)_ __   ___ _ __  / || || ||___ /   |
|  | |/ _ \| | |\/| | | '_ \ / _ \ '__| | || || |_ |_ \   |
|  | | (_) | | |  | | | | | |  __/ |    | ||__   _|__) |  |
|  |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_) |_||____/   |
|                                                         |
|              This software is for mining                |
|              Autolykos V2                               |
|              Ethash, Etchash                            |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash III                               |
|              ZelHash     (EquihashR 125/4/0)            |
|              SHA256 (TON)                               |
|              Cuck(ar)oo 29                              |
|              Cuckaroo   30 CTX                          |
|              Cuckatoo   31/32                           |
|                                                         |
|                                                         |
|            Made by Lolliedieb, February 2022            |
+---------------------------------------------------------+

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 4
Cuda driver detected.
Number of Cuda supported GPUs: 4
Device 0:
    Name:    NVIDIA GeForce RTX 3090
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  24575 MByte
    Active:  false (not selected)
Device 1:
    Name:    NVIDIA GeForce RTX 3080
    Address: 7:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  12287 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
Device 2:
    Name:    NVIDIA GeForce RTX 3090
    Address: 10:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  24575 MByte
    Active:  false (not selected)
Device 3:
    Name:    NVIDIA GeForce RTX 3080
    Address: 12:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda
    Memory:  10239 MByte
    Active:  false (not selected)

Connecting to pool...
DNS over HTTPS resolve succeeded
Connected to (removed by user)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: (removed by user)
New job received: 0x478e48 Epoch: 471 Difficulty: 4.30G
Start Mining...
New job received: 0x442cdb Epoch: 471 Difficulty: 4.30G
-------------------------------------------------------
          Generated light cache for epoch 471
       Took 2209 ms, size of new DAG: 4791 MByte
-------------------------------------------------------
GPU 1: Starting DAG generation (normal mode)
New job received: 0xfa4904 Epoch: 471 Difficulty: 4.30G
GPU 1: DAG build complete 16%
GPU 1: DAG build complete 32%
New job received: 0x87f775 Epoch: 471 Difficulty: 4.30G
GPU 1: DAG build complete 48%
GPU 1: DAG build complete 64%
New job received: 0x16c0ad Epoch: 471 Difficulty: 4.30G
New job received: 0x3da3d6 Epoch: 471 Difficulty: 4.30G
GPU 1: DAG build complete 80%
GPU 1: DAG build complete 96%
GPU 1: DAG generation completed (4936 ms)
GPU 1: DAG verification passed
New job received: 0x6dd5cc Epoch: 471 Difficulty: 4.30G
New job received: 0xa09fc9 Epoch: 471 Difficulty: 4.30G
New job received: 0xa0bb52 Epoch: 471 Difficulty: 4.30G
New job received: 0x6b78c4 Epoch: 471 Difficulty: 4.30G
GPU 1: detected an unexpected low hashrate. Checking if GPU is LHR...
Average speed (15s): 31.39 Mh/s
New job received: 0xb432b8 Epoch: 471 Difficulty: 4.30G
GPU 1: GPU will be paused to make sure it is unlocked...
New job received: 0x358714 Epoch: 471 Difficulty: 4.30G
New job received: 0x616ac9 Epoch: 471 Difficulty: 4.30G
New job received: 0x679776 Epoch: 471 Difficulty: 4.30G
New job received: 0xa0cc4e Epoch: 471 Difficulty: 4.30G
New job received: 0x5c624e Epoch: 471 Difficulty: 4.30G
New job received: 0x64628d Epoch: 471 Difficulty: 4.30G
New job received: 0x19965b Epoch: 471 Difficulty: 4.30G
New job received: 0x1d261a Epoch: 471 Difficulty: 4.30G
New job received: 0x3dfd0b Epoch: 471 Difficulty: 4.30G
New job received: 0xf8328d Epoch: 471 Difficulty: 4.30G
New job received: 0x8ea3f7 Epoch: 471 Difficulty: 4.30G
New job received: 0x2dc0eb Epoch: 471 Difficulty: 4.30G
New job received: 0x127544 Epoch: 471 Difficulty: 4.30G
New job received: 0xd19753 Epoch: 471 Difficulty: 4.30G
Average speed (15s): 1.83 Mh/s
New job received: 0xf87775 Epoch: 471 Difficulty: 4.30G
New job received: 0xa8e517 Epoch: 471 Difficulty: 4.30G
New job received: 0xb6a5d2 Epoch: 471 Difficulty: 4.30G
New job received: 0xe4e129 Epoch: 471 Difficulty: 4.30G
New job received: 0x92b186 Epoch: 471 Difficulty: 4.30G
New job received: 0x7b071b Epoch: 471 Difficulty: 4.30G
GPU 1: measured GPU raw speed: 73.31MH/s (Memory clock: 10225 mhz)
GPU 1: does not seem to be LHR - sorry for bothering you
New job received: 0xb8d016 Epoch: 471 Difficulty: 4.30G
New job received: 0x5b1ebc Epoch: 471 Difficulty: 4.30G
New job received: 0x7841fc Epoch: 471 Difficulty: 4.30G
New job received: 0xd2af11 Epoch: 471 Difficulty: 4.30G
Average speed (15s): 31.39 Mh/s
New job received: 0xde6409 Epoch: 471 Difficulty: 4.30G
New job received: 0x245d47 Epoch: 471 Difficulty: 4.30G
New job received: 0x4235e7 Epoch: 471 Difficulty: 4.30G
New job received: 0x4d2a21 Epoch: 471 Difficulty: 4.30G
New job received: 0x3c5cf2 Epoch: 471 Difficulty: 4.30G
New job received: 0x4fc20c Epoch: 471 Difficulty: 4.30G
New job received: 0xf11511 Epoch: 471 Difficulty: 4.30G
New job received: 0xf39530 Epoch: 471 Difficulty: 4.30G
New job received: 0x568905 Epoch: 471 Difficulty: 4.30G
---------------------------------------------
Statistics (06:39:50); Uptime: 0h 1m 1s
Mining: Ethash
Connected to: us1.ethermine.org:4444

      Name     Speed  Pool  Shares   Best    Eff.  Power  CCLK   MCLK  Core  Fan  --lhrtune
                Mh/s  Mh/s  A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Pct
GPU 1 RTX 3080 44.84  0.00   0/0/0    0.0   0.214  209.0  1208  10225    44   88       auto
---------------------------
Total          44.84  0.00   0/0/0    0.0   0.214  209.0
---------------------------------------------
Average speed (15s): 62.77 Mh/s
New job received: 0x9d8ba0 Epoch: 471 Difficulty: 4.30G
New job received: 0x04d52a Epoch: 471 Difficulty: 4.30G
New job received: 0x2e6149 Epoch: 471 Difficulty: 4.30G
New job received: 0xc329e1 Epoch: 471 Difficulty: 4.30G
New job received: 0x8f2e76 Epoch: 471 Difficulty: 4.30G
New job received: 0xc215ec Epoch: 471 Difficulty: 4.30G
New job received: 0xa1e245 Epoch: 471 Difficulty: 4.30G
New job received: 0xee9349 Epoch: 471 Difficulty: 4.30G
New job received: 0xa5b1c4 Epoch: 471 Difficulty: 4.30G
Average speed (15s): 62.77 Mh/s
New job received: 0x22b5db Epoch: 471 Difficulty: 4.30G
GPU 1: Found a share of difficulty 46.24G
GPU 1: Share accepted (11 ms)

**Comment by jgonzis** [comment]
> It still does not seem to unlock anything as an LHR, still getting 62MHs
> 
> I did see this GPU 1: measured GPU raw speed: 73.31MH/s (Memory clock: 10225 mhz) GPU 1: does not seem to be LHR - sorry for bothering you
> 
> Full results (EVGA 3080 12GB FTW)
> 
> +---------------------------------------------------------+ | _ _ __ __ _ _ _ _ _____ | | | | ___ | | / (_)_ __ ___ _ __ / || || ||___ / | | | |/ _ | | |/| | | '_ \ / _ \ '**| | || || |_ |_ \ | | | | (_) | | | | | | | | | **/ | | ||** _|**) | | | |_|___/|_|_| |_|_|_| |_|___|_| |_(_) |_||____/ | | | | This software is for mining | | Autolykos V2 | | Ethash, Etchash | | Equihash 144/5, 192/7, 210/9 | | BeamHash III | | ZelHash (EquihashR 125/4/0) | | SHA256 (TON) | | Cuck(ar)oo 29 | | Cuckaroo 30 CTX | | Cuckatoo 31/32 | | | | | | Made by Lolliedieb, February 2022 | +---------------------------------------------------------+
> 
> Setup Miner... OpenCL driver detected. Number of OpenCL supported GPUs: 4 Cuda driver detected. Number of Cuda supported GPUs: 4 Device 0: Name: NVIDIA GeForce RTX 3090 Address: 1:0 Vendor: NVIDIA Corporation Drivers: Cuda Memory: 24575 MByte Active: false (not selected) Device 1: Name: NVIDIA GeForce RTX 3080 Address: 7:0 Vendor: NVIDIA Corporation Drivers: Cuda Memory: 12287 MByte Active: true (Selected Algorithm: ETHash Cuda) Device 2: Name: NVIDIA GeForce RTX 3090 Address: 10:0 Vendor: NVIDIA Corporation Drivers: Cuda Memory: 24575 MByte Active: false (not selected) Device 3: Name: NVIDIA GeForce RTX 3080 Address: 12:0 Vendor: NVIDIA Corporation Drivers: Cuda Memory: 10239 MByte Active: false (not selected)
> 
> ## Connecting to pool...
> DNS over HTTPS resolve succeeded
> Connected to (removed by user)
> Set Ethash stratum mode: Ethereum Proxy
> Authorized worker: (removed by user)
> New job received: 0x478e48 Epoch: 471 Difficulty: 4.30G
> Start Mining...
> New job received: 0x442cdb Epoch: 471 Difficulty: 4.30G
> ```
>       Generated light cache for epoch 471
>    Took 2209 ms, size of new DAG: 4791 MByte
> ```
> 
> ## GPU 1: Starting DAG generation (normal mode)
> New job received: 0xfa4904 Epoch: 471 Difficulty: 4.30G
> GPU 1: DAG build complete 16%
> GPU 1: DAG build complete 32%
> New job received: 0x87f775 Epoch: 471 Difficulty: 4.30G
> GPU 1: DAG build complete 48%
> GPU 1: DAG build complete 64%
> New job received: 0x16c0ad Epoch: 471 Difficulty: 4.30G
> New job received: 0x3da3d6 Epoch: 471 Difficulty: 4.30G
> GPU 1: DAG build complete 80%
> GPU 1: DAG build complete 96%
> GPU 1: DAG generation completed (4936 ms)
> GPU 1: DAG verification passed
> New job received: 0x6dd5cc Epoch: 471 Difficulty: 4.30G
> New job received: 0xa09fc9 Epoch: 471 Difficulty: 4.30G
> New job received: 0xa0bb52 Epoch: 471 Difficulty: 4.30G
> New job received: 0x6b78c4 Epoch: 471 Difficulty: 4.30G
> GPU 1: detected an unexpected low hashrate. Checking if GPU is LHR...
> Average speed (15s): 31.39 Mh/s
> New job received: 0xb432b8 Epoch: 471 Difficulty: 4.30G
> GPU 1: GPU will be paused to make sure it is unlocked...
> New job received: 0x358714 Epoch: 471 Difficulty: 4.30G
> New job received: 0x616ac9 Epoch: 471 Difficulty: 4.30G
> New job received: 0x679776 Epoch: 471 Difficulty: 4.30G
> New job received: 0xa0cc4e Epoch: 471 Difficulty: 4.30G
> New job received: 0x5c624e Epoch: 471 Difficulty: 4.30G
> New job received: 0x64628d Epoch: 471 Difficulty: 4.30G
> New job received: 0x19965b Epoch: 471 Difficulty: 4.30G
> New job received: 0x1d261a Epoch: 471 Difficulty: 4.30G
> New job received: 0x3dfd0b Epoch: 471 Difficulty: 4.30G
> New job received: 0xf8328d Epoch: 471 Difficulty: 4.30G
> New job received: 0x8ea3f7 Epoch: 471 Difficulty: 4.30G
> New job received: 0x2dc0eb Epoch: 471 Difficulty: 4.30G
> New job received: 0x127544 Epoch: 471 Difficulty: 4.30G
> New job received: 0xd19753 Epoch: 471 Difficulty: 4.30G
> Average speed (15s): 1.83 Mh/s
> New job received: 0xf87775 Epoch: 471 Difficulty: 4.30G
> New job received: 0xa8e517 Epoch: 471 Difficulty: 4.30G
> New job received: 0xb6a5d2 Epoch: 471 Difficulty: 4.30G
> New job received: 0xe4e129 Epoch: 471 Difficulty: 4.30G
> New job received: 0x92b186 Epoch: 471 Difficulty: 4.30G
> New job received: 0x7b071b Epoch: 471 Difficulty: 4.30G
> GPU 1: measured GPU raw speed: 73.31MH/s (Memory clock: 10225 mhz)
> GPU 1: does not seem to be LHR - sorry for bothering you
> New job received: 0xb8d016 Epoch: 471 Difficulty: 4.30G
> New job received: 0x5b1ebc Epoch: 471 Difficulty: 4.30G
> New job received: 0x7841fc Epoch: 471 Difficulty: 4.30G
> New job received: 0xd2af11 Epoch: 471 Difficulty: 4.30G
> Average speed (15s): 31.39 Mh/s
> New job received: 0xde6409 Epoch: 471 Difficulty: 4.30G
> New job received: 0x245d47 Epoch: 471 Difficulty: 4.30G
> New job received: 0x4235e7 Epoch: 471 Difficulty: 4.30G
> New job received: 0x4d2a21 Epoch: 471 Difficulty: 4.30G
> New job received: 0x3c5cf2 Epoch: 471 Difficulty: 4.30G
> New job received: 0x4fc20c Epoch: 471 Difficulty: 4.30G
> New job received: 0xf11511 Epoch: 471 Difficulty: 4.30G
> New job received: 0xf39530 Epoch: 471 Difficulty: 4.30G
> New job received: 0x568905 Epoch: 471 Difficulty: 4.30G
> Statistics (06:39:50); Uptime: 0h 1m 1s Mining: Ethash Connected to: us1.ethermine.org:4444
> 
> ```
>   Name     Speed  Pool  Shares   Best    Eff.  Power  CCLK   MCLK  Core  Fan  --lhrtune
>             Mh/s  Mh/s  A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Pct
> ```
> 
> ## GPU 1 RTX 3080 44.84 0.00 0/0/0 0.0 0.214 209.0 1208 10225 44 88 auto
> ## Total 44.84 0.00 0/0/0 0.0 0.214 209.0
> Average speed (15s): 62.77 Mh/s New job received: 0x9d8ba0 Epoch: 471 Difficulty: 4.30G New job received: 0x04d52a Epoch: 471 Difficulty: 4.30G New job received: 0x2e6149 Epoch: 471 Difficulty: 4.30G New job received: 0xc329e1 Epoch: 471 Difficulty: 4.30G New job received: 0x8f2e76 Epoch: 471 Difficulty: 4.30G New job received: 0xc215ec Epoch: 471 Difficulty: 4.30G New job received: 0xa1e245 Epoch: 471 Difficulty: 4.30G New job received: 0xee9349 Epoch: 471 Difficulty: 4.30G New job received: 0xa5b1c4 Epoch: 471 Difficulty: 4.30G Average speed (15s): 62.77 Mh/s New job received: 0x22b5db Epoch: 471 Difficulty: 4.30G GPU 1: Found a share of difficulty 46.24G GPU 1: Share accepted (11 ms)

Windows??? It seems new drivers have a very high lock

**Comment by GenCodeInc** [comment]
> Windows??? It seems new drivers have a very high lock
Correct, its Win 10.  Anything you want me to try?
I resorted back to the dinosaur miner with 63 MHs :(

**Comment by jgonzis** [comment]
> > Windows??? It seems new drivers have a very high lock
> > Correct, its Win 10.  Anything you want me to try?
> > I resorted back to the dinosaur miner with 63 MHs :(

Yes you are right new drivers... are really restricted

**Comment by GenCodeInc** [comment]
> Yes you are right new drivers... are really restricted
Also its not reporting stats back to my Awesomeminer, so I assume once they add miner definitions for the new ver it it will.

A bit more info for you on latest run

Nvidia Driver: 511.65

New job received: 0xcf12ef Epoch: 471 Difficulty: 4.30G
GPU 1: measured GPU raw speed: 74.06MH/s (Memory clock: 25 mhz)
GPU 1: does not seem to be LHR - sorry for bothering you
New job received: 0x2b2297 Epoch: 471 Difficulty: 4.30G
....
New job received: 0x445bd2 Epoch: 471 Difficulty: 4.30G
GPU 1: Share accepted (10 ms)
---------------------------------------------
Statistics (14:35:49); Uptime: 0h 1m 1s
Mining: Ethash
Connected to: us1.ethermine.org:4444 (10ms latency)

      Name     Speed   Pool  Shares   Best    Eff.  Power  CCLK   MCLK  Core  Fan  --lhrtune
                Mh/s   Mh/s  A/S/Hw  Share  Mh/s/W      W   MHz    MHz  Temp  Pct
GPU 1 RTX 3080 47.76  70.41   1/0/0   5.3G   0.228  208.7  1228  10225    45   88       auto
---------------------------
Total          47.76  70.41   1/0/0   5.3G   0.228  208.7
---------------------------------------------
Average speed (15s): 62.77 Mh/s

Image bottom one is the 3080 12GB (no stats)
![image](https://user-images.githubusercontent.com/3945575/152656431-9f308ed4-2395-4f39-bc09-4a926536919e.png)

**Comment by nirotub** [comment]
How can I disable LHR definition on RTX 3080 12 GB in lolminer? So that it is defined as not an LHR card. Otherwise, the miner cannot choose the parameters for it and constantly drops.

**Comment by jgonzis** [comment]
> How can I disable LHR definition on RTX 3080 12GB in lolminer? So that it is defined as not an LHR card. Otherwise, the miner cannot choose the parameters for it and constantly drops. I would like her to mine ETH + TON as a regular card. Thanks

Yes of course --lhrtune off

**Comment by nirotub** [comment]
> > How can I disable LHR definition on RTX 3080 12GB in lolminer? So that it is defined as not an LHR card. Otherwise, the miner cannot choose the parameters for it and constantly drops. I would like her to mine ETH + TON as a regular card. Thanks
> 
> Yes of course --lhrtune off

And if there are several cards and only one needs to do this?

**Comment by jgonzis** [comment]
> > > How can I disable LHR definition on RTX 3080 12GB in lolminer? So that it is defined as not an LHR card. Otherwise, the miner cannot choose the parameters for it and constantly drops. I would like her to mine ETH + TON as a regular card. Thanks
> > 
> > 
> > Yes of course --lhrtune off
> 
> And if there are several cards and only one needs to do this?

Sorry then,

--lhrtune auto,off,off,auto

Then gpu0 and 3 are LHR meanwhile gpu1 and 2 are NOLHR

**Comment by nirotub** [comment]
> --lhrtune auto,off,off,auto
Thanks!
